import typing

import androidx
import androidx.arch.core.util
import java.lang
import java.util.concurrent

_ComputableLiveData__T = typing.TypeVar('_ComputableLiveData__T')  # <T>
class ComputableLiveData(java.lang.Object, typing.Generic[_ComputableLiveData__T]):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, executor: java.util.concurrent.Executor, /) -> None: ...
    def compute(self) -> _ComputableLiveData__T: ...
    def getLiveData(self) -> LiveData[_ComputableLiveData__T]: ...
    def invalidate(self) -> None: ...

_MediatorLiveData__T = typing.TypeVar('_MediatorLiveData__T')  # <T>
class MediatorLiveData(androidx.lifecycle.MutableLiveData[_MediatorLiveData__T], typing.Generic[_MediatorLiveData__T]):
    def __init__(self) -> None: ...
    _addSource__S = typing.TypeVar('_addSource__S')  # <S>
    def addSource(self, source: LiveData[_addSource__S], onChanged: Observer[_addSource__S], /) -> None: ...
    def onActive(self) -> None: ...
    def onInactive(self) -> None: ...
    def removeSource(self, toRemote: LiveData[java.lang.Object], /) -> None: ...

class Transformations(java.lang.Object):
    _distinctUntilChanged__X = typing.TypeVar('_distinctUntilChanged__X')  # <X>
    @staticmethod
    def distinctUntilChanged(source: LiveData[_distinctUntilChanged__X], /) -> LiveData[_distinctUntilChanged__X]: ...
    _map__X = typing.TypeVar('_map__X')  # <X>
    _map__Y = typing.TypeVar('_map__Y')  # <Y>
    @staticmethod
    def map(source: LiveData[_map__X], mapFunction: androidx.arch.core.util.Function[_map__X, _map__Y], /) -> LiveData[_map__Y]: ...
    _switchMap__X = typing.TypeVar('_switchMap__X')  # <X>
    _switchMap__Y = typing.TypeVar('_switchMap__Y')  # <Y>
    @staticmethod
    def switchMap(source: LiveData[_switchMap__X], switchMapFunction: androidx.arch.core.util.Function[_switchMap__X, LiveData[_switchMap__Y]], /) -> LiveData[_switchMap__Y]: ...
