import typing

import android.text
import java
import java.chaquopy
import java.lang
import java.util
import kotlin
import kotlin.jvm.functions
import kotlin.ranges

class CharSequenceKt(java.lang.Object):
    @staticmethod
    def isDigitsOnly(receiver: java.lang.CharSequence, /) -> bool: ...
    @staticmethod
    def trimmedLength(receiver: java.lang.CharSequence, /) -> int: ...

class HtmlKt(java.lang.Object):
    @staticmethod
    def parseAsHtml(receiver: str | java.lang.String, flags: int | java.jint | java.lang.Integer, imageGetter: android.text.Html.ImageGetter, tagHandler: android.text.Html.TagHandler, /) -> android.text.Spanned: ...
    @staticmethod
    def toHtml(receiver: android.text.Spanned, option: int | java.jint | java.lang.Integer, /) -> str: ...

class LocaleKt(java.lang.Object):
    @staticmethod
    def getLayoutDirection(receiver: java.util.Locale, /) -> int: ...

class SpannableStringBuilderKt(java.lang.Object):
    @staticmethod
    def backgroundColor(receiver: android.text.SpannableStringBuilder, color: int | java.jint | java.lang.Integer, builderAction: kotlin.jvm.functions.Function1[android.text.SpannableStringBuilder, kotlin.Unit], /) -> android.text.SpannableStringBuilder: ...
    @staticmethod
    def bold(receiver: android.text.SpannableStringBuilder, builderAction: kotlin.jvm.functions.Function1[android.text.SpannableStringBuilder, kotlin.Unit], /) -> android.text.SpannableStringBuilder: ...
    @staticmethod
    def buildSpannedString(builderAction: kotlin.jvm.functions.Function1[android.text.SpannableStringBuilder, kotlin.Unit], /) -> android.text.SpannedString: ...
    @staticmethod
    def color(receiver: android.text.SpannableStringBuilder, color: int | java.jint | java.lang.Integer, builderAction: kotlin.jvm.functions.Function1[android.text.SpannableStringBuilder, kotlin.Unit], /) -> android.text.SpannableStringBuilder: ...
    @typing.overload
    @staticmethod
    def inSpans(receiver: android.text.SpannableStringBuilder, span: java.lang.Object | int | bool | float | str, builderAction: kotlin.jvm.functions.Function1[android.text.SpannableStringBuilder, kotlin.Unit], /) -> android.text.SpannableStringBuilder: ...
    @typing.overload
    @staticmethod
    def inSpans(receiver: android.text.SpannableStringBuilder, spans: java.chaquopy.JavaArray[java.lang.Object], builderAction: kotlin.jvm.functions.Function1[android.text.SpannableStringBuilder, kotlin.Unit], /) -> android.text.SpannableStringBuilder: ...
    @staticmethod
    def italic(receiver: android.text.SpannableStringBuilder, builderAction: kotlin.jvm.functions.Function1[android.text.SpannableStringBuilder, kotlin.Unit], /) -> android.text.SpannableStringBuilder: ...
    @staticmethod
    def scale(receiver: android.text.SpannableStringBuilder, proportion: float | java.jfloat | java.lang.Float, builderAction: kotlin.jvm.functions.Function1[android.text.SpannableStringBuilder, kotlin.Unit], /) -> android.text.SpannableStringBuilder: ...
    @staticmethod
    def strikeThrough(receiver: android.text.SpannableStringBuilder, builderAction: kotlin.jvm.functions.Function1[android.text.SpannableStringBuilder, kotlin.Unit], /) -> android.text.SpannableStringBuilder: ...
    @staticmethod
    def subscript(receiver: android.text.SpannableStringBuilder, builderAction: kotlin.jvm.functions.Function1[android.text.SpannableStringBuilder, kotlin.Unit], /) -> android.text.SpannableStringBuilder: ...
    @staticmethod
    def superscript(receiver: android.text.SpannableStringBuilder, builderAction: kotlin.jvm.functions.Function1[android.text.SpannableStringBuilder, kotlin.Unit], /) -> android.text.SpannableStringBuilder: ...
    @staticmethod
    def underline(receiver: android.text.SpannableStringBuilder, builderAction: kotlin.jvm.functions.Function1[android.text.SpannableStringBuilder, kotlin.Unit], /) -> android.text.SpannableStringBuilder: ...

class SpannableStringKt(java.lang.Object):
    @staticmethod
    def clearSpans(receiver: android.text.Spannable, /) -> None: ...
    @typing.overload
    @staticmethod
    def set(receiver: android.text.Spannable, range: kotlin.ranges.IntRange, span: java.lang.Object | int | bool | float | str, /) -> None: ...
    @typing.overload
    @staticmethod
    def set(receiver: android.text.Spannable, start: int | java.jint | java.lang.Integer, end: int | java.jint | java.lang.Integer, span: java.lang.Object | int | bool | float | str, /) -> None: ...
    @staticmethod
    def toSpannable(receiver: java.lang.CharSequence, /) -> android.text.Spannable: ...

class SpannedStringKt(java.lang.Object):
    @staticmethod
    def toSpanned(receiver: java.lang.CharSequence, /) -> android.text.Spanned: ...

class StringKt(java.lang.Object):
    @staticmethod
    def htmlEncode(receiver: str | java.lang.String, /) -> str: ...
