import typing

import androidx
import java
import java.lang
import java.time
import java.util.concurrent
import java.util.concurrent.atomic
import kotlin
import kotlin.coroutines
import kotlin.jvm.functions
import kotlinx.coroutines
import kotlinx.coroutines.flow

class Api26Impl(java.lang.Object):
    INSTANCE: typing.ClassVar[Api26Impl] = ...
    def toMillis(self, timeout: java.time.Duration, /) -> int: ...

_BlockRunner__T = typing.TypeVar('_BlockRunner__T')  # <T>
class BlockRunner(java.lang.Object, typing.Generic[_BlockRunner__T]):
    def __init__(self, liveData: CoroutineLiveData[_BlockRunner__T], block: kotlin.jvm.functions.Function2[LiveDataScope[_BlockRunner__T], kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], timeoutInMs: int | java.jlong | java.lang.Long, scope: kotlinx.coroutines.CoroutineScope, onDone: kotlin.jvm.functions.Function0[kotlin.Unit], /) -> None: ...
    def cancel(self) -> None: ...
    def maybeRun(self) -> None: ...

_ComputableLiveData__T = typing.TypeVar('_ComputableLiveData__T')  # <T>
class ComputableLiveData(java.lang.Object, typing.Generic[_ComputableLiveData__T]):
    refreshRunnable: java.lang.Runnable = ...
    invalidationRunnable: java.lang.Runnable = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, executor: java.util.concurrent.Executor, /) -> None: ...
    def compute(self) -> _ComputableLiveData__T: ...
    def getComputing$lifecycle_livedata(self) -> java.util.concurrent.atomic.AtomicBoolean: ...
    def getExecutor$lifecycle_livedata(self) -> java.util.concurrent.Executor: ...
    def getInvalid$lifecycle_livedata(self) -> java.util.concurrent.atomic.AtomicBoolean: ...
    def getLiveData(self) -> LiveData[_ComputableLiveData__T]: ...
    def invalidate(self) -> None: ...

_CoroutineLiveData__T = typing.TypeVar('_CoroutineLiveData__T')  # <T>
class CoroutineLiveData(MediatorLiveData[_CoroutineLiveData__T], typing.Generic[_CoroutineLiveData__T]):
    def __init__(self, context: kotlin.coroutines.CoroutineContext, timeoutInMs: int | java.jlong | java.lang.Long, block: kotlin.jvm.functions.Function2[LiveDataScope[_CoroutineLiveData__T], kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], /) -> None: ...
    def clearSource$lifecycle_livedata(self, completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def emitSource$lifecycle_livedata(self, source: LiveData[_CoroutineLiveData__T], completion: kotlin.coroutines.Continuation[kotlinx.coroutines.DisposableHandle], /) -> java.lang.Object: ...
    def onActive(self) -> None: ...
    def onInactive(self) -> None: ...

class CoroutineLiveDataKt(java.lang.Object):
    DEFAULT_TIMEOUT: typing.ClassVar[int] = ...
    _addDisposableSource__T = typing.TypeVar('_addDisposableSource__T')  # <T>
    @staticmethod
    def addDisposableSource(this_addDisposableSource: MediatorLiveData[_addDisposableSource__T], source: LiveData[_addDisposableSource__T], completion: kotlin.coroutines.Continuation[EmittedSource], /) -> java.lang.Object: ...
    _liveData_0__T = typing.TypeVar('_liveData_0__T')  # <T>
    _liveData_1__T = typing.TypeVar('_liveData_1__T')  # <T>
    _liveData_2__T = typing.TypeVar('_liveData_2__T')  # <T>
    _liveData_3__T = typing.TypeVar('_liveData_3__T')  # <T>
    _liveData_4__T = typing.TypeVar('_liveData_4__T')  # <T>
    @typing.overload
    @staticmethod
    def liveData(block: kotlin.jvm.functions.Function2[LiveDataScope[_liveData_0__T], kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], /) -> LiveData[_liveData_0__T]: ...
    @typing.overload
    @staticmethod
    def liveData(timeout: java.time.Duration, block: kotlin.jvm.functions.Function2[LiveDataScope[_liveData_1__T], kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], /) -> LiveData[_liveData_1__T]: ...
    @typing.overload
    @staticmethod
    def liveData(context: kotlin.coroutines.CoroutineContext, block: kotlin.jvm.functions.Function2[LiveDataScope[_liveData_2__T], kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], /) -> LiveData[_liveData_2__T]: ...
    @typing.overload
    @staticmethod
    def liveData(timeout: java.time.Duration, context: kotlin.coroutines.CoroutineContext, block: kotlin.jvm.functions.Function2[LiveDataScope[_liveData_3__T], kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], /) -> LiveData[_liveData_3__T]: ...
    @typing.overload
    @staticmethod
    def liveData(context: kotlin.coroutines.CoroutineContext, timeoutInMs: int | java.jlong | java.lang.Long, block: kotlin.jvm.functions.Function2[LiveDataScope[_liveData_4__T], kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], /) -> LiveData[_liveData_4__T]: ...

class EmittedSource(kotlinx.coroutines.DisposableHandle):
    def __init__(self, source: LiveData[java.lang.Object], mediator: MediatorLiveData[java.lang.Object], /) -> None: ...
    def dispose(self) -> None: ...
    def disposeNow(self, completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...

class FlowLiveDataConversions(java.lang.Object):
    _asFlow__T = typing.TypeVar('_asFlow__T')  # <T>
    @staticmethod
    def asFlow(this_asFlow: LiveData[_asFlow__T], /) -> kotlinx.coroutines.flow.Flow[_asFlow__T]: ...
    _asLiveData_0__T = typing.TypeVar('_asLiveData_0__T')  # <T>
    _asLiveData_1__T = typing.TypeVar('_asLiveData_1__T')  # <T>
    _asLiveData_2__T = typing.TypeVar('_asLiveData_2__T')  # <T>
    _asLiveData_3__T = typing.TypeVar('_asLiveData_3__T')  # <T>
    @typing.overload
    @staticmethod
    def asLiveData(this_asLiveData: kotlinx.coroutines.flow.Flow[_asLiveData_0__T], /) -> LiveData[_asLiveData_0__T]: ...
    @typing.overload
    @staticmethod
    def asLiveData(this_asLiveData: kotlinx.coroutines.flow.Flow[_asLiveData_1__T], context: kotlin.coroutines.CoroutineContext, /) -> LiveData[_asLiveData_1__T]: ...
    @typing.overload
    @staticmethod
    def asLiveData(this_asLiveData: kotlinx.coroutines.flow.Flow[_asLiveData_2__T], timeout: java.time.Duration, context: kotlin.coroutines.CoroutineContext, /) -> LiveData[_asLiveData_2__T]: ...
    @typing.overload
    @staticmethod
    def asLiveData(this_asLiveData: kotlinx.coroutines.flow.Flow[_asLiveData_3__T], context: kotlin.coroutines.CoroutineContext, timeoutInMs: int | java.jlong | java.lang.Long, /) -> LiveData[_asLiveData_3__T]: ...

_LiveDataScope__T = typing.TypeVar('_LiveDataScope__T')  # <T>
class LiveDataScope(java.lang.Object, typing.Generic[_LiveDataScope__T]):
    def emit(self, arg1: _LiveDataScope__T, arg2: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def emitSource(self, arg1: LiveData[_LiveDataScope__T], arg2: kotlin.coroutines.Continuation[kotlinx.coroutines.DisposableHandle], /) -> java.lang.Object: ...
    def getLatestValue(self) -> _LiveDataScope__T: ...

_LiveDataScopeImpl__T = typing.TypeVar('_LiveDataScopeImpl__T')  # <T>
class LiveDataScopeImpl(LiveDataScope[_LiveDataScopeImpl__T], typing.Generic[_LiveDataScopeImpl__T]):
    def __init__(self, target: CoroutineLiveData[_LiveDataScopeImpl__T], context: kotlin.coroutines.CoroutineContext, /) -> None: ...
    def emit(self, value: _LiveDataScopeImpl__T, completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def emitSource(self, source: LiveData[_LiveDataScopeImpl__T], completion: kotlin.coroutines.Continuation[kotlinx.coroutines.DisposableHandle], /) -> java.lang.Object: ...
    def getLatestValue(self) -> _LiveDataScopeImpl__T: ...
    def getTarget$lifecycle_livedata(self) -> CoroutineLiveData[_LiveDataScopeImpl__T]: ...
    def setTarget$lifecycle_livedata(self, <set-?>: CoroutineLiveData[_LiveDataScopeImpl__T], /) -> None: ...

_MediatorLiveData__T = typing.TypeVar('_MediatorLiveData__T')  # <T>
class MediatorLiveData(androidx.lifecycle.MutableLiveData[_MediatorLiveData__T], typing.Generic[_MediatorLiveData__T]):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, value: _MediatorLiveData__T, /) -> None: ...
    _addSource__S = typing.TypeVar('_addSource__S')  # <S>
    def addSource(self, source: LiveData[_addSource__S], onChanged: Observer[_addSource__S], /) -> None: ...
    def onActive(self) -> None: ...
    def onInactive(self) -> None: ...
    def removeSource(self, toRemote: LiveData[java.lang.Object], /) -> None: ...

class Transformations(java.lang.Object):
    _distinctUntilChanged__X = typing.TypeVar('_distinctUntilChanged__X')  # <X>
    @staticmethod
    def distinctUntilChanged(this_distinctUntilChanged: LiveData[_distinctUntilChanged__X], /) -> LiveData[_distinctUntilChanged__X]: ...
    _map__X = typing.TypeVar('_map__X')  # <X>
    _map__Y = typing.TypeVar('_map__Y')  # <Y>
    @staticmethod
    def map(this_map: LiveData[_map__X], transform: kotlin.jvm.functions.Function1[_map__X, _map__Y], /) -> LiveData[_map__Y]: ...
    _switchMap__X = typing.TypeVar('_switchMap__X')  # <X>
    _switchMap__Y = typing.TypeVar('_switchMap__Y')  # <Y>
    @staticmethod
    def switchMap(this_switchMap: LiveData[_switchMap__X], transform: kotlin.jvm.functions.Function1[_switchMap__X, LiveData[_switchMap__Y]], /) -> LiveData[_switchMap__Y]: ...
