import android.content
import android.content.res
import android.graphics
import android.graphics.drawable
import android.util
import android.view
import android.widget
import androidx.core.graphics.drawable
import androidx.dynamicanimation.animation
import androidx.graphics.shapes
import com
import com.google.android.material.canvas
import com.google.android.material.elevation
import java
import java.chaquopy
import java.lang
import java.lang.annotation
import typing



class AbsoluteCornerSize(CornerSize):
    def __init__(self, size: float | java.jfloat | java.lang.Float, /) -> None: ...
    def equals(self, o: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @typing.overload
    def getCornerSize(self) -> float: ...
    @typing.overload
    def getCornerSize(self, bounds: android.graphics.RectF, /) -> float: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class AdjustedCornerSize(CornerSize):
    def __init__(self, adjustment: float | java.jfloat | java.lang.Float, other: CornerSize, /) -> None: ...
    def equals(self, o: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getCornerSize(self, bounds: android.graphics.RectF, /) -> float: ...
    def hashCode(self) -> int: ...

class ClampedCornerSize(CornerSize):
    def __init__(self, target: float | java.jfloat | java.lang.Float, /) -> None: ...
    @staticmethod
    def createFromCornerSize(cornerSize: AbsoluteCornerSize, /) -> ClampedCornerSize: ...
    def equals(self, o: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getCornerSize(self, bounds: android.graphics.RectF, /) -> float: ...
    def hashCode(self) -> int: ...

class CornerFamily(java.lang.annotation.Annotation):
    ROUNDED: typing.ClassVar[int] = ...
    CUT: typing.ClassVar[int] = ...

class CornerSize(java.lang.Object):
    def getCornerSize(self, arg1: android.graphics.RectF, /) -> float: ...

class CornerTreatment(java.lang.Object):
    def __init__(self) -> None: ...
    @typing.overload
    def getCornerPath(self, angle: float | java.jfloat | java.lang.Float, interpolation: float | java.jfloat | java.lang.Float, shapePath: ShapePath, /) -> None: ...
    @typing.overload
    def getCornerPath(self, shapePath: ShapePath, angle: float | java.jfloat | java.lang.Float, interpolation: float | java.jfloat | java.lang.Float, radius: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def getCornerPath(self, shapePath: ShapePath, angle: float | java.jfloat | java.lang.Float, interpolation: float | java.jfloat | java.lang.Float, bounds: android.graphics.RectF, size: CornerSize, /) -> None: ...

class CutCornerTreatment(CornerTreatment):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, size: float | java.jfloat | java.lang.Float, /) -> None: ...
    def getCornerPath(self, shapePath: ShapePath, angle: float | java.jfloat | java.lang.Float, interpolation: float | java.jfloat | java.lang.Float, radius: float | java.jfloat | java.lang.Float, /) -> None: ...

class EdgeTreatment(java.lang.Object):
    def __init__(self) -> None: ...
    @typing.overload
    def getEdgePath(self, length: float | java.jfloat | java.lang.Float, interpolation: float | java.jfloat | java.lang.Float, shapePath: ShapePath, /) -> None: ...
    @typing.overload
    def getEdgePath(self, length: float | java.jfloat | java.lang.Float, center: float | java.jfloat | java.lang.Float, interpolation: float | java.jfloat | java.lang.Float, shapePath: ShapePath, /) -> None: ...

class InterpolateOnScrollPositionChangeHelper(java.lang.Object):
    def __init__(self, shapedView: android.view.View, materialShapeDrawable: MaterialShapeDrawable, containingScrollView: android.widget.ScrollView, /) -> None: ...
    def setContainingScrollView(self, containingScrollView: android.widget.ScrollView, /) -> None: ...
    def setMaterialShapeDrawable(self, materialShapeDrawable: MaterialShapeDrawable, /) -> None: ...
    def startListeningForScrollChanges(self, viewTreeObserver: android.view.ViewTreeObserver, /) -> None: ...
    def stopListeningForScrollChanges(self, viewTreeObserver: android.view.ViewTreeObserver, /) -> None: ...
    def updateInterpolationForScreenPosition(self) -> None: ...

class MarkerEdgeTreatment(EdgeTreatment):
    def __init__(self, radius: float | java.jfloat | java.lang.Float, /) -> None: ...
    def getEdgePath(self, length: float | java.jfloat | java.lang.Float, center: float | java.jfloat | java.lang.Float, interpolation: float | java.jfloat | java.lang.Float, shapePath: ShapePath, /) -> None: ...

class MaterialShapeDrawable(android.graphics.drawable.Drawable, androidx.core.graphics.drawable.TintAwareDrawable, Shapeable):
    SHADOW_COMPAT_MODE_DEFAULT: typing.ClassVar[int] = ...
    SHADOW_COMPAT_MODE_NEVER: typing.ClassVar[int] = ...
    SHADOW_COMPAT_MODE_ALWAYS: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, drawableState: MaterialShapeDrawable.MaterialShapeDrawableState, /) -> None: ...
    @typing.overload
    def __init__(self, shapeAppearanceModel: ShapeAppearanceModel, /) -> None: ...
    @typing.overload
    def __init__(self, shapePathModel: ShapePathModel, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, /) -> None: ...
    def calculatePathForSize(self, bounds: android.graphics.RectF, path: android.graphics.Path, /) -> None: ...
    def compositeElevationOverlayIfNeeded(self, backgroundColor: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def createWithElevationOverlay(context: android.content.Context, /) -> MaterialShapeDrawable: ...
    @typing.overload
    @staticmethod
    def createWithElevationOverlay(context: android.content.Context, elevation: float | java.jfloat | java.lang.Float, /) -> MaterialShapeDrawable: ...
    @typing.overload
    @staticmethod
    def createWithElevationOverlay(context: android.content.Context, elevation: float | java.jfloat | java.lang.Float, backgroundTint: android.content.res.ColorStateList, /) -> MaterialShapeDrawable: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def drawShape(self, canvas: android.graphics.Canvas, paint: android.graphics.Paint, path: android.graphics.Path, bounds: android.graphics.RectF, /) -> None: ...
    def drawStrokeShape(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getAlpha(self) -> int: ...
    def getBottomLeftCornerResolvedSize(self) -> float: ...
    def getBottomRightCornerResolvedSize(self) -> float: ...
    def getBoundsAsRectF(self) -> android.graphics.RectF: ...
    def getConstantState(self) -> android.graphics.drawable.Drawable.ConstantState: ...
    def getCornerSizeDiffX(self) -> float: ...
    def getCornerSpringForce(self) -> androidx.dynamicanimation.animation.SpringForce: ...
    def getElevation(self) -> float: ...
    def getFillColor(self) -> android.content.res.ColorStateList: ...
    def getInterpolation(self) -> float: ...
    def getOpacity(self) -> int: ...
    def getOutline(self, outline: android.graphics.Outline, /) -> None: ...
    def getPadding(self, padding: android.graphics.Rect, /) -> bool: ...
    def getPaintStyle(self) -> android.graphics.Paint.Style: ...
    def getParentAbsoluteElevation(self) -> float: ...
    def getPathForSize(self, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, path: android.graphics.Path, /) -> None: ...
    def getResolvedTintColor(self) -> int: ...
    def getScale(self) -> float: ...
    def getShadowCompatRotation(self) -> int: ...
    def getShadowCompatibilityMode(self) -> int: ...
    def getShadowElevation(self) -> int: ...
    def getShadowOffsetX(self) -> int: ...
    def getShadowOffsetY(self) -> int: ...
    def getShadowRadius(self) -> int: ...
    def getShadowVerticalOffset(self) -> int: ...
    def getShapeAppearanceModel(self) -> ShapeAppearanceModel: ...
    def getShapedViewModel(self) -> ShapePathModel: ...
    def getStateListShapeAppearanceModel(self) -> StateListShapeAppearanceModel: ...
    def getStrokeColor(self) -> android.content.res.ColorStateList: ...
    def getStrokeTintList(self) -> android.content.res.ColorStateList: ...
    def getStrokeWidth(self) -> float: ...
    def getTintList(self) -> android.content.res.ColorStateList: ...
    def getTopLeftCornerResolvedSize(self) -> float: ...
    def getTopRightCornerResolvedSize(self) -> float: ...
    def getTranslationZ(self) -> float: ...
    def getTransparentRegion(self) -> android.graphics.Region: ...
    def getZ(self) -> float: ...
    def initializeElevationOverlay(self, context: android.content.Context, /) -> None: ...
    def invalidateSelf(self) -> None: ...
    def isElevationOverlayEnabled(self) -> bool: ...
    def isElevationOverlayInitialized(self) -> bool: ...
    def isPointInTransparentRegion(self, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, /) -> bool: ...
    def isRoundRect(self) -> bool: ...
    def isShadowEnabled(self) -> bool: ...
    def isStateful(self) -> bool: ...
    def mutate(self) -> android.graphics.drawable.Drawable: ...
    def onBoundsChange(self, bounds: android.graphics.Rect, /) -> None: ...
    def onStateChange(self, state: java.chaquopy.JavaArrayJInt, /) -> bool: ...
    def requiresCompatShadow(self) -> bool: ...
    def setAlpha(self, alpha: int | java.jint | java.lang.Integer, /) -> None: ...
    def setColorFilter(self, colorFilter: android.graphics.ColorFilter, /) -> None: ...
    @typing.overload
    def setCornerSize(self, cornerSize: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def setCornerSize(self, cornerSize: CornerSize, /) -> None: ...
    def setCornerSpringForce(self, springForce: androidx.dynamicanimation.animation.SpringForce, /) -> None: ...
    def setEdgeIntersectionCheckEnable(self, enable: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setElevation(self, elevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setFillColor(self, fillColor: android.content.res.ColorStateList, /) -> None: ...
    def setInterpolation(self, interpolation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setOnCornerSizeChangeListener(self, onCornerSizeChangeListener: MaterialShapeDrawable.OnCornerSizeChangeListener, /) -> None: ...
    def setPadding(self, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPaintStyle(self, paintStyle: android.graphics.Paint.Style, /) -> None: ...
    def setParentAbsoluteElevation(self, parentAbsoluteElevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setScale(self, scale: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setShadowBitmapDrawingEnable(self, enable: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setShadowColor(self, shadowColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setShadowCompatRotation(self, shadowRotation: int | java.jint | java.lang.Integer, /) -> None: ...
    def setShadowCompatibilityMode(self, mode: int | java.jint | java.lang.Integer, /) -> None: ...
    def setShadowElevation(self, shadowElevation: int | java.jint | java.lang.Integer, /) -> None: ...
    def setShadowEnabled(self, shadowEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setShadowRadius(self, shadowRadius: int | java.jint | java.lang.Integer, /) -> None: ...
    def setShadowVerticalOffset(self, shadowOffset: int | java.jint | java.lang.Integer, /) -> None: ...
    def setShapeAppearanceModel(self, shapeAppearanceModel: ShapeAppearanceModel, /) -> None: ...
    def setShapedViewModel(self, shapedViewModel: ShapePathModel, /) -> None: ...
    def setStateListShapeAppearanceModel(self, stateListShapeAppearanceModel: StateListShapeAppearanceModel, /) -> None: ...
    @typing.overload
    def setStroke(self, strokeWidth: float | java.jfloat | java.lang.Float, strokeColor: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setStroke(self, strokeWidth: float | java.jfloat | java.lang.Float, strokeColor: android.content.res.ColorStateList, /) -> None: ...
    def setStrokeColor(self, strokeColor: android.content.res.ColorStateList, /) -> None: ...
    @typing.overload
    def setStrokeTint(self, tintColor: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setStrokeTint(self, tintList: android.content.res.ColorStateList, /) -> None: ...
    def setStrokeWidth(self, strokeWidth: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTint(self, tintColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTintList(self, tintList: android.content.res.ColorStateList, /) -> None: ...
    def setTintMode(self, tintMode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def setTranslationZ(self, translationZ: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setUseTintColorForShadow(self, useTintColorForShadow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setZ(self, z: float | java.jfloat | java.lang.Float, /) -> None: ...

    class OnCornerSizeChangeListener(java.lang.Object):
        def onCornerSizeChange(self, arg1: float | java.jfloat | java.lang.Float, /) -> None: ...

    class MaterialShapeDrawableState(android.graphics.drawable.Drawable.ConstantState):
        @typing.overload
        def __init__(self, orig: MaterialShapeDrawable.MaterialShapeDrawableState, /) -> None: ...
        @typing.overload
        def __init__(self, shapeAppearanceModel: ShapeAppearanceModel, elevationOverlayProvider: com.google.android.material.elevation.ElevationOverlayProvider, /) -> None: ...
        def getChangingConfigurations(self) -> int: ...
        def newDrawable(self) -> android.graphics.drawable.Drawable: ...

    class CompatibilityShadowMode(java.lang.annotation.Annotation): ...

class MaterialShapeUtils(java.lang.Object):
    @staticmethod
    def setElevation(view: android.view.View, elevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    @staticmethod
    def setParentAbsoluteElevation(view: android.view.View, /) -> None: ...
    @typing.overload
    @staticmethod
    def setParentAbsoluteElevation(view: android.view.View, materialShapeDrawable: MaterialShapeDrawable, /) -> None: ...

class MaterialShapes(java.lang.Object):
    CIRCLE: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    SQUARE: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    SLANTED_SQUARE: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    ARCH: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    FAN: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    ARROW: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    SEMI_CIRCLE: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    OVAL: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    PILL: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    TRIANGLE: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    DIAMOND: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    CLAM_SHELL: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    PENTAGON: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    GEM: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    SUNNY: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    VERY_SUNNY: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    COOKIE_4: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    COOKIE_6: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    COOKIE_7: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    COOKIE_9: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    COOKIE_12: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    GHOSTISH: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    CLOVER_4: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    CLOVER_8: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    BURST: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    SOFT_BURST: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    BOOM: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    SOFT_BOOM: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    FLOWER: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    PUFFY: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    PUFFY_DIAMOND: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    PIXEL_CIRCLE: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    PIXEL_TRIANGLE: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    BUN: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    HEART: typing.ClassVar[androidx.graphics.shapes.RoundedPolygon] = ...
    @staticmethod
    def createShapeDrawable(shape: androidx.graphics.shapes.RoundedPolygon, /) -> android.graphics.drawable.ShapeDrawable: ...
    @typing.overload
    @staticmethod
    def normalize(shape: androidx.graphics.shapes.RoundedPolygon, radial: bool | java.jboolean | java.lang.Boolean, /) -> androidx.graphics.shapes.RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def normalize(shape: androidx.graphics.shapes.RoundedPolygon, radial: bool | java.jboolean | java.lang.Boolean, dstBounds: android.graphics.RectF, /) -> androidx.graphics.shapes.RoundedPolygon: ...

class OffsetEdgeTreatment(EdgeTreatment):
    def __init__(self, other: EdgeTreatment, offset: float | java.jfloat | java.lang.Float, /) -> None: ...
    def getEdgePath(self, length: float | java.jfloat | java.lang.Float, center: float | java.jfloat | java.lang.Float, interpolation: float | java.jfloat | java.lang.Float, shapePath: ShapePath, /) -> None: ...

class RelativeCornerSize(CornerSize):
    def __init__(self, percent: float | java.jfloat | java.lang.Float, /) -> None: ...
    @staticmethod
    def createFromCornerSize(bounds: android.graphics.RectF, cornerSize: CornerSize, /) -> RelativeCornerSize: ...
    def equals(self, o: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getCornerSize(self, bounds: android.graphics.RectF, /) -> float: ...
    def getRelativePercent(self) -> float: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class RoundedCornerTreatment(CornerTreatment):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, radius: float | java.jfloat | java.lang.Float, /) -> None: ...
    def getCornerPath(self, shapePath: ShapePath, angle: float | java.jfloat | java.lang.Float, interpolation: float | java.jfloat | java.lang.Float, radius: float | java.jfloat | java.lang.Float, /) -> None: ...

class ShapeAppearanceModel(java.lang.Object):
    NUM_CORNERS: typing.ClassVar[int] = ...
    PILL: typing.ClassVar[CornerSize] = ...
    def __init__(self) -> None: ...
    @typing.overload
    @staticmethod
    def builder() -> ShapeAppearanceModel.Builder: ...
    @typing.overload
    @staticmethod
    def builder(context: android.content.Context, shapeAppearanceResId: int | java.jint | java.lang.Integer, shapeAppearanceOverlayResId: int | java.jint | java.lang.Integer, /) -> ShapeAppearanceModel.Builder: ...
    @typing.overload
    @staticmethod
    def builder(context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, /) -> ShapeAppearanceModel.Builder: ...
    @typing.overload
    @staticmethod
    def builder(context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, defaultCornerSize: int | java.jint | java.lang.Integer, /) -> ShapeAppearanceModel.Builder: ...
    @typing.overload
    @staticmethod
    def builder(context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, defaultCornerSize: CornerSize, /) -> ShapeAppearanceModel.Builder: ...
    def getBottomEdge(self) -> EdgeTreatment: ...
    def getBottomLeftCorner(self) -> CornerTreatment: ...
    def getBottomLeftCornerSize(self) -> CornerSize: ...
    def getBottomRightCorner(self) -> CornerTreatment: ...
    def getBottomRightCornerSize(self) -> CornerSize: ...
    @staticmethod
    def getCornerSize(a: android.content.res.TypedArray, index: int | java.jint | java.lang.Integer, defaultValue: CornerSize, /) -> CornerSize: ...
    def getLeftEdge(self) -> EdgeTreatment: ...
    def getRightEdge(self) -> EdgeTreatment: ...
    def getTopEdge(self) -> EdgeTreatment: ...
    def getTopLeftCorner(self) -> CornerTreatment: ...
    def getTopLeftCornerSize(self) -> CornerSize: ...
    def getTopRightCorner(self) -> CornerTreatment: ...
    def getTopRightCornerSize(self) -> CornerSize: ...
    def hasRoundedCorners(self) -> bool: ...
    def isRoundRect(self, bounds: android.graphics.RectF, /) -> bool: ...
    def toBuilder(self) -> ShapeAppearanceModel.Builder: ...
    def toString(self) -> str: ...
    @typing.overload
    def withCornerSize(self, cornerSize: float | java.jfloat | java.lang.Float, /) -> ShapeAppearanceModel: ...
    @typing.overload
    def withCornerSize(self, cornerSize: CornerSize, /) -> ShapeAppearanceModel: ...
    def withTransformedCornerSizes(self, op: ShapeAppearanceModel.CornerSizeUnaryOperator, /) -> ShapeAppearanceModel: ...

    class Builder(java.lang.Object):
        @typing.overload
        def __init__(self) -> None: ...
        @typing.overload
        def __init__(self, other: ShapeAppearanceModel, /) -> None: ...
        def build(self) -> ShapeAppearanceModel: ...
        @typing.overload
        def setAllCornerSizes(self, cornerSize: float | java.jfloat | java.lang.Float, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setAllCornerSizes(self, cornerSize: CornerSize, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setAllCorners(self, cornerTreatment: CornerTreatment, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setAllCorners(self, cornerFamily: int | java.jint | java.lang.Integer, cornerSize: float | java.jfloat | java.lang.Float, /) -> ShapeAppearanceModel.Builder: ...
        def setAllEdges(self, edgeTreatment: EdgeTreatment, /) -> ShapeAppearanceModel.Builder: ...
        def setBottomEdge(self, bottomEdge: EdgeTreatment, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setBottomLeftCorner(self, bottomLeftCorner: CornerTreatment, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setBottomLeftCorner(self, cornerFamily: int | java.jint | java.lang.Integer, cornerSize: float | java.jfloat | java.lang.Float, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setBottomLeftCorner(self, cornerFamily: int | java.jint | java.lang.Integer, cornerSize: CornerSize, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setBottomLeftCornerSize(self, cornerSize: float | java.jfloat | java.lang.Float, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setBottomLeftCornerSize(self, cornerSize: CornerSize, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setBottomRightCorner(self, bottomRightCorner: CornerTreatment, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setBottomRightCorner(self, cornerFamily: int | java.jint | java.lang.Integer, cornerSize: float | java.jfloat | java.lang.Float, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setBottomRightCorner(self, cornerFamily: int | java.jint | java.lang.Integer, cornerSize: CornerSize, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setBottomRightCornerSize(self, cornerSize: float | java.jfloat | java.lang.Float, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setBottomRightCornerSize(self, cornerSize: CornerSize, /) -> ShapeAppearanceModel.Builder: ...
        def setLeftEdge(self, leftEdge: EdgeTreatment, /) -> ShapeAppearanceModel.Builder: ...
        def setRightEdge(self, rightEdge: EdgeTreatment, /) -> ShapeAppearanceModel.Builder: ...
        def setTopEdge(self, topEdge: EdgeTreatment, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setTopLeftCorner(self, topLeftCorner: CornerTreatment, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setTopLeftCorner(self, cornerFamily: int | java.jint | java.lang.Integer, cornerSize: float | java.jfloat | java.lang.Float, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setTopLeftCorner(self, cornerFamily: int | java.jint | java.lang.Integer, cornerSize: CornerSize, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setTopLeftCornerSize(self, cornerSize: float | java.jfloat | java.lang.Float, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setTopLeftCornerSize(self, cornerSize: CornerSize, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setTopRightCorner(self, topRightCorner: CornerTreatment, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setTopRightCorner(self, cornerFamily: int | java.jint | java.lang.Integer, cornerSize: float | java.jfloat | java.lang.Float, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setTopRightCorner(self, cornerFamily: int | java.jint | java.lang.Integer, cornerSize: CornerSize, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setTopRightCornerSize(self, cornerSize: float | java.jfloat | java.lang.Float, /) -> ShapeAppearanceModel.Builder: ...
        @typing.overload
        def setTopRightCornerSize(self, cornerSize: CornerSize, /) -> ShapeAppearanceModel.Builder: ...

    class CornerSizeUnaryOperator(java.lang.Object):
        def apply(self, arg1: CornerSize, /) -> CornerSize: ...

class ShapeAppearancePathProvider(java.lang.Object):
    TOP_RIGHT_CORNER_INDEX: typing.ClassVar[int] = ...
    BOTTOM_RIGHT_CORNER_INDEX: typing.ClassVar[int] = ...
    BOTTOM_LEFT_CORNER_INDEX: typing.ClassVar[int] = ...
    TOP_LEFT_CORNER_INDEX: typing.ClassVar[int] = ...
    def __init__(self) -> None: ...
    @typing.overload
    def calculatePath(self, shapeAppearanceModel: ShapeAppearanceModel, interpolation: float | java.jfloat | java.lang.Float, bounds: android.graphics.RectF, path: android.graphics.Path, /) -> None: ...
    @typing.overload
    def calculatePath(self, shapeAppearanceModel: ShapeAppearanceModel, interpolation: float | java.jfloat | java.lang.Float, bounds: android.graphics.RectF, pathListener: ShapeAppearancePathProvider.PathListener, path: android.graphics.Path, /) -> None: ...
    @typing.overload
    def calculatePath(self, shapeAppearanceModel: ShapeAppearanceModel, cornerSizeOverrides: java.chaquopy.JavaArrayJFloat, interpolation: float | java.jfloat | java.lang.Float, bounds: android.graphics.RectF, pathListener: ShapeAppearancePathProvider.PathListener, path: android.graphics.Path, /) -> None: ...
    @staticmethod
    def getInstance() -> ShapeAppearancePathProvider: ...

    class PathListener(java.lang.Object):
        def onCornerPathCreated(self, arg1: ShapePath, arg2: android.graphics.Matrix, arg3: int | java.jint | java.lang.Integer, /) -> None: ...
        def onEdgePathCreated(self, arg1: ShapePath, arg2: android.graphics.Matrix, arg3: int | java.jint | java.lang.Integer, /) -> None: ...

class ShapePath(java.lang.Object):
    ANGLE_LEFT: typing.ClassVar[float] = ...
    startX: float = ...
    startY: float = ...
    endX: float = ...
    endY: float = ...
    currentShadowAngle: float = ...
    endShadowAngle: float = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, startX: float | java.jfloat | java.lang.Float, startY: float | java.jfloat | java.lang.Float, /) -> None: ...
    def addArc(self, left: float | java.jfloat | java.lang.Float, top: float | java.jfloat | java.lang.Float, right: float | java.jfloat | java.lang.Float, bottom: float | java.jfloat | java.lang.Float, startAngle: float | java.jfloat | java.lang.Float, sweepAngle: float | java.jfloat | java.lang.Float, /) -> None: ...
    def applyToPath(self, transform: android.graphics.Matrix, path: android.graphics.Path, /) -> None: ...
    def cubicToPoint(self, controlX1: float | java.jfloat | java.lang.Float, controlY1: float | java.jfloat | java.lang.Float, controlX2: float | java.jfloat | java.lang.Float, controlY2: float | java.jfloat | java.lang.Float, toX: float | java.jfloat | java.lang.Float, toY: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def lineTo(self, x: float | java.jfloat | java.lang.Float, y: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def lineTo(self, x1: float | java.jfloat | java.lang.Float, y1: float | java.jfloat | java.lang.Float, x2: float | java.jfloat | java.lang.Float, y2: float | java.jfloat | java.lang.Float, /) -> None: ...
    def quadToPoint(self, controlX: float | java.jfloat | java.lang.Float, controlY: float | java.jfloat | java.lang.Float, toX: float | java.jfloat | java.lang.Float, toY: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def reset(self, startX: float | java.jfloat | java.lang.Float, startY: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def reset(self, startX: float | java.jfloat | java.lang.Float, startY: float | java.jfloat | java.lang.Float, shadowStartAngle: float | java.jfloat | java.lang.Float, shadowSweepAngle: float | java.jfloat | java.lang.Float, /) -> None: ...

    class PathLineOperation(com.google.android.material.shape.ShapePath.PathOperation):
        def __init__(self) -> None: ...
        def applyToPath(self, transform: android.graphics.Matrix, path: android.graphics.Path, /) -> None: ...

    class PathQuadOperation(com.google.android.material.shape.ShapePath.PathOperation):
        controlX: float = ...
        controlY: float = ...
        endX: float = ...
        endY: float = ...
        def __init__(self) -> None: ...
        def applyToPath(self, transform: android.graphics.Matrix, path: android.graphics.Path, /) -> None: ...

    class PathCubicOperation(com.google.android.material.shape.ShapePath.PathOperation):
        def __init__(self, controlX1: float | java.jfloat | java.lang.Float, controlY1: float | java.jfloat | java.lang.Float, controlX2: float | java.jfloat | java.lang.Float, controlY2: float | java.jfloat | java.lang.Float, endX: float | java.jfloat | java.lang.Float, endY: float | java.jfloat | java.lang.Float, /) -> None: ...
        def applyToPath(self, transform: android.graphics.Matrix, path: android.graphics.Path, /) -> None: ...

    class PathArcOperation(com.google.android.material.shape.ShapePath.PathOperation):
        left: float = ...
        top: float = ...
        right: float = ...
        bottom: float = ...
        startAngle: float = ...
        sweepAngle: float = ...
        def __init__(self, left: float | java.jfloat | java.lang.Float, top: float | java.jfloat | java.lang.Float, right: float | java.jfloat | java.lang.Float, bottom: float | java.jfloat | java.lang.Float, /) -> None: ...
        def applyToPath(self, transform: android.graphics.Matrix, path: android.graphics.Path, /) -> None: ...

    class PathOperation(java.lang.Object):
        matrix: android.graphics.Matrix = ...
        def __init__(self) -> None: ...
        def applyToPath(self, arg1: android.graphics.Matrix, arg2: android.graphics.Path, /) -> None: ...

class ShapePathModel(ShapeAppearanceModel):
    def __init__(self) -> None: ...
    def setAllCorners(self, cornerTreatment: CornerTreatment, /) -> None: ...
    def setAllEdges(self, edgeTreatment: EdgeTreatment, /) -> None: ...
    def setBottomEdge(self, bottomEdge: EdgeTreatment, /) -> None: ...
    def setBottomLeftCorner(self, bottomLeftCorner: CornerTreatment, /) -> None: ...
    def setBottomRightCorner(self, bottomRightCorner: CornerTreatment, /) -> None: ...
    def setCornerTreatments(self, topLeftCorner: CornerTreatment, topRightCorner: CornerTreatment, bottomRightCorner: CornerTreatment, bottomLeftCorner: CornerTreatment, /) -> None: ...
    def setEdgeTreatments(self, leftEdge: EdgeTreatment, topEdge: EdgeTreatment, rightEdge: EdgeTreatment, bottomEdge: EdgeTreatment, /) -> None: ...
    def setLeftEdge(self, leftEdge: EdgeTreatment, /) -> None: ...
    def setRightEdge(self, rightEdge: EdgeTreatment, /) -> None: ...
    def setTopEdge(self, topEdge: EdgeTreatment, /) -> None: ...
    def setTopLeftCorner(self, topLeftCorner: CornerTreatment, /) -> None: ...
    def setTopRightCorner(self, topRightCorner: CornerTreatment, /) -> None: ...

class Shapeable(java.lang.Object):
    def getShapeAppearanceModel(self) -> ShapeAppearanceModel: ...
    def setShapeAppearanceModel(self, arg1: ShapeAppearanceModel, /) -> None: ...

class ShapeableDelegate(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def create(view: android.view.View, /) -> ShapeableDelegate: ...
    def isForceCompatClippingEnabled(self) -> bool: ...
    def maybeClip(self, canvas: android.graphics.Canvas, op: com.google.android.material.canvas.CanvasCompat.CanvasOperation, /) -> None: ...
    def onMaskChanged(self, view: android.view.View, maskBounds: android.graphics.RectF, /) -> None: ...
    def onShapeAppearanceChanged(self, view: android.view.View, shapeAppearanceModel: ShapeAppearanceModel, /) -> None: ...
    def setForceCompatClippingEnabled(self, view: android.view.View, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setOffsetZeroCornerEdgeBoundsEnabled(self, view: android.view.View, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class ShapeableDelegateV14(ShapeableDelegate): ...

class ShapeableDelegateV22(ShapeableDelegate): ...

class ShapeableDelegateV33(ShapeableDelegate): ...

class StateListCornerSize(java.lang.Object):
    def __init__(self) -> None: ...
    @typing.overload
    @staticmethod
    def create(cornerSize: CornerSize, /) -> StateListCornerSize: ...
    @typing.overload
    @staticmethod
    def create(context: android.content.Context, attributes: android.content.res.TypedArray, index: int | java.jint | java.lang.Integer, defaultCornerSize: CornerSize, /) -> StateListCornerSize: ...
    def getCornerSizeForState(self, stateSet: java.chaquopy.JavaArrayJInt, /) -> CornerSize: ...
    def getDefaultCornerSize(self) -> CornerSize: ...
    def isStateful(self) -> bool: ...
    def withTransformedCornerSizes(self, op: ShapeAppearanceModel.CornerSizeUnaryOperator, /) -> StateListCornerSize: ...

class StateListShapeAppearanceModel(java.lang.Object):
    CORNER_TOP_LEFT: typing.ClassVar[int] = ...
    CORNER_TOP_RIGHT: typing.ClassVar[int] = ...
    CORNER_BOTTOM_LEFT: typing.ClassVar[int] = ...
    CORNER_BOTTOM_RIGHT: typing.ClassVar[int] = ...
    @staticmethod
    def create(context: android.content.Context, attributes: android.content.res.TypedArray, index: int | java.jint | java.lang.Integer, /) -> StateListShapeAppearanceModel: ...
    def getDefaultShape(self, withCornerSizeOverrides: bool | java.jboolean | java.lang.Boolean, /) -> ShapeAppearanceModel: ...
    def getShapeForState(self, stateSet: java.chaquopy.JavaArrayJInt, /) -> ShapeAppearanceModel: ...
    def getStateCount(self) -> int: ...
    def isStateful(self) -> bool: ...
    @staticmethod
    def swapCornerPositionRtl(flagSet: int | java.jint | java.lang.Integer, /) -> int: ...
    def toBuilder(self) -> StateListShapeAppearanceModel.Builder: ...
    def withTransformedCornerSizes(self, op: ShapeAppearanceModel.CornerSizeUnaryOperator, /) -> StateListShapeAppearanceModel: ...

    class Builder(java.lang.Object):
        @typing.overload
        def __init__(self, shapeAppearanceModel: ShapeAppearanceModel, /) -> None: ...
        @typing.overload
        def __init__(self, other: StateListShapeAppearanceModel, /) -> None: ...
        def addStateShapeAppearanceModel(self, stateSpec: java.chaquopy.JavaArrayJInt, shapeAppearanceModel: ShapeAppearanceModel, /) -> StateListShapeAppearanceModel.Builder: ...
        def build(self) -> StateListShapeAppearanceModel: ...
        def setCornerSizeOverride(self, cornerSizeOverride: StateListCornerSize, cornerPositionSet: int | java.jint | java.lang.Integer, /) -> StateListShapeAppearanceModel.Builder: ...
        def withTransformedCornerSizes(self, op: ShapeAppearanceModel.CornerSizeUnaryOperator, /) -> StateListShapeAppearanceModel.Builder: ...

class StateListSizeChange(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def create(context: android.content.Context, attributes: android.content.res.TypedArray, index: int | java.jint | java.lang.Integer, /) -> StateListSizeChange: ...
    def getDefaultSizeChange(self) -> StateListSizeChange.SizeChange: ...
    def getMaxWidthChange(self, baseWidth: int | java.jint | java.lang.Integer, /) -> int: ...
    def getSizeChangeForState(self, stateSet: java.chaquopy.JavaArrayJInt, /) -> StateListSizeChange.SizeChange: ...
    def isStateful(self) -> bool: ...

    class SizeChange(java.lang.Object):
        widthChange: StateListSizeChange.SizeChangeAmount = ...

    class SizeChangeAmount(java.lang.Object):
        def getChange(self, baseSize: int | java.jint | java.lang.Integer, /) -> int: ...

    class SizeChangeType(java.lang.Enum[StateListSizeChange.SizeChangeType]):
        PERCENT: typing.ClassVar[StateListSizeChange.SizeChangeType] = ...
        PIXELS: typing.ClassVar[StateListSizeChange.SizeChangeType] = ...
        @staticmethod
        def valueOf(name: str | java.lang.String, /) -> StateListSizeChange.SizeChangeType: ...
        @staticmethod
        def values() -> java.chaquopy.JavaArray[StateListSizeChange.SizeChangeType]: ...

class TriangleEdgeTreatment(EdgeTreatment):
    def __init__(self, size: float | java.jfloat | java.lang.Float, inside: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def getEdgePath(self, length: float | java.jfloat | java.lang.Float, center: float | java.jfloat | java.lang.Float, interpolation: float | java.jfloat | java.lang.Float, shapePath: ShapePath, /) -> None: ...
