import android.content
import android.content.res
import android.graphics.drawable
import android.util
import android.view.accessibility
import android.widget
import androidx.cardview.widget
import com.google.android.material.shape
import java
import java.chaquopy
import java.lang
import java.lang.annotation
import typing



class MaterialCardView(androidx.cardview.widget.CardView, android.widget.Checkable, com.google.android.material.shape.Shapeable):
    CHECKED_ICON_GRAVITY_TOP_START: typing.ClassVar[int] = ...
    CHECKED_ICON_GRAVITY_BOTTOM_START: typing.ClassVar[int] = ...
    CHECKED_ICON_GRAVITY_TOP_END: typing.ClassVar[int] = ...
    CHECKED_ICON_GRAVITY_BOTTOM_END: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def getCardBackgroundColor(self) -> android.content.res.ColorStateList: ...
    def getCardForegroundColor(self) -> android.content.res.ColorStateList: ...
    def getCheckedIcon(self) -> android.graphics.drawable.Drawable: ...
    def getCheckedIconGravity(self) -> int: ...
    def getCheckedIconMargin(self) -> int: ...
    def getCheckedIconSize(self) -> int: ...
    def getCheckedIconTint(self) -> android.content.res.ColorStateList: ...
    def getContentPaddingBottom(self) -> int: ...
    def getContentPaddingLeft(self) -> int: ...
    def getContentPaddingRight(self) -> int: ...
    def getContentPaddingTop(self) -> int: ...
    def getProgress(self) -> float: ...
    def getRadius(self) -> float: ...
    def getRippleColor(self) -> android.content.res.ColorStateList: ...
    def getShapeAppearanceModel(self) -> com.google.android.material.shape.ShapeAppearanceModel: ...
    def getStrokeColor(self) -> int: ...
    def getStrokeColorStateList(self) -> android.content.res.ColorStateList: ...
    def getStrokeWidth(self) -> int: ...
    def isCheckable(self) -> bool: ...
    def isChecked(self) -> bool: ...
    def isDragged(self) -> bool: ...
    def onAttachedToWindow(self) -> None: ...
    def onCreateDrawableState(self, extraSpace: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJInt: ...
    def onInitializeAccessibilityEvent(self, accessibilityEvent: android.view.accessibility.AccessibilityEvent, /) -> None: ...
    def onInitializeAccessibilityNodeInfo(self, info: android.view.accessibility.AccessibilityNodeInfo, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBackground(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...
    def setBackgroundDrawable(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...
    @typing.overload
    def setCardBackgroundColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCardBackgroundColor(self, color: android.content.res.ColorStateList, /) -> None: ...
    def setCardElevation(self, elevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setCardForegroundColor(self, foregroundColor: android.content.res.ColorStateList, /) -> None: ...
    def setCheckable(self, checkable: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setChecked(self, checked: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setCheckedIcon(self, checkedIcon: android.graphics.drawable.Drawable, /) -> None: ...
    def setCheckedIconGravity(self, checkedIconGravity: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCheckedIconMargin(self, checkedIconMargin: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCheckedIconMarginResource(self, checkedIconMarginResId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCheckedIconResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCheckedIconSize(self, checkedIconSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCheckedIconSizeResource(self, checkedIconSizeResId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCheckedIconTint(self, checkedIconTint: android.content.res.ColorStateList, /) -> None: ...
    def setClickable(self, clickable: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setContentPadding(self, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDragged(self, dragged: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setMaxCardElevation(self, maxCardElevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setOnCheckedChangeListener(self, listener: MaterialCardView.OnCheckedChangeListener, /) -> None: ...
    def setPreventCornerOverlap(self, preventCornerOverlap: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setProgress(self, progress: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setRadius(self, radius: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setRippleColor(self, rippleColor: android.content.res.ColorStateList, /) -> None: ...
    def setRippleColorResource(self, rippleColorResourceId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setShapeAppearanceModel(self, shapeAppearanceModel: com.google.android.material.shape.ShapeAppearanceModel, /) -> None: ...
    @typing.overload
    def setStrokeColor(self, strokeColor: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setStrokeColor(self, strokeColor: android.content.res.ColorStateList, /) -> None: ...
    def setStrokeWidth(self, strokeWidth: int | java.jint | java.lang.Integer, /) -> None: ...
    def setUseCompatPadding(self, useCompatPadding: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def toggle(self) -> None: ...

    class OnCheckedChangeListener(java.lang.Object):
        def onCheckedChanged(self, arg1: MaterialCardView, arg2: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

    class CheckedIconGravity(java.lang.annotation.Annotation): ...

class MaterialCardViewHelper(java.lang.Object):
    DEFAULT_FADE_ANIM_DURATION: typing.ClassVar[int] = ...
    def __init__(self, card: MaterialCardView, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, /) -> None: ...
    def animateCheckedIcon(self, checked: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def setChecked(self, checked: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def setChecked(self, checked: bool | java.jboolean | java.lang.Boolean, animate: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
