import typing

import java
import java.chaquopy
import java.lang
import java.util
import kotlin
import kotlin.collections
import kotlin.coroutines
import kotlin.jvm.functions
import kotlin.jvm.internal.markers
import kotlin.random

_ConstrainedOnceSequence__T = typing.TypeVar('_ConstrainedOnceSequence__T')  # <T>
class ConstrainedOnceSequence(Sequence[_ConstrainedOnceSequence__T], typing.Generic[_ConstrainedOnceSequence__T]):
    def __init__(self, sequence: Sequence[_ConstrainedOnceSequence__T], /) -> None: ...
    def iterator(self) -> java.util.Iterator[_ConstrainedOnceSequence__T]: ...

_DistinctIterator__T = typing.TypeVar('_DistinctIterator__T')  # <T>
_DistinctIterator__K = typing.TypeVar('_DistinctIterator__K')  # <K>
class DistinctIterator(kotlin.collections.AbstractIterator[_DistinctIterator__T], typing.Generic[_DistinctIterator__T, _DistinctIterator__K]):
    def __init__(self, source: java.util.Iterator[_DistinctIterator__T], keySelector: kotlin.jvm.functions.Function1[_DistinctIterator__T, _DistinctIterator__K], /) -> None: ...
    def computeNext(self) -> None: ...

_DistinctSequence__T = typing.TypeVar('_DistinctSequence__T')  # <T>
_DistinctSequence__K = typing.TypeVar('_DistinctSequence__K')  # <K>
class DistinctSequence(Sequence[_DistinctSequence__T], typing.Generic[_DistinctSequence__T, _DistinctSequence__K]):
    def __init__(self, source: Sequence[_DistinctSequence__T], keySelector: kotlin.jvm.functions.Function1[_DistinctSequence__T, _DistinctSequence__K], /) -> None: ...
    def iterator(self) -> java.util.Iterator[_DistinctSequence__T]: ...

_DropSequence__T = typing.TypeVar('_DropSequence__T')  # <T>
class DropSequence(Sequence[_DropSequence__T], DropTakeSequence[_DropSequence__T], typing.Generic[_DropSequence__T]):
    def __init__(self, sequence: Sequence[_DropSequence__T], count: int | java.jint | java.lang.Integer, /) -> None: ...
    def drop(self, n: int | java.jint | java.lang.Integer, /) -> Sequence[_DropSequence__T]: ...
    def iterator(self) -> java.util.Iterator[_DropSequence__T]: ...
    def take(self, n: int | java.jint | java.lang.Integer, /) -> Sequence[_DropSequence__T]: ...

_DropTakeSequence__T = typing.TypeVar('_DropTakeSequence__T')  # <T>
class DropTakeSequence(Sequence[_DropTakeSequence__T], typing.Generic[_DropTakeSequence__T]):
    def drop(self, arg1: int | java.jint | java.lang.Integer, /) -> Sequence[_DropTakeSequence__T]: ...
    def take(self, arg1: int | java.jint | java.lang.Integer, /) -> Sequence[_DropTakeSequence__T]: ...

_DropWhileSequence__T = typing.TypeVar('_DropWhileSequence__T')  # <T>
class DropWhileSequence(Sequence[_DropWhileSequence__T], typing.Generic[_DropWhileSequence__T]):
    def __init__(self, sequence: Sequence[_DropWhileSequence__T], predicate: kotlin.jvm.functions.Function1[_DropWhileSequence__T, java.lang.Boolean], /) -> None: ...
    def iterator(self) -> java.util.Iterator[_DropWhileSequence__T]: ...

class EmptySequence(Sequence, DropTakeSequence):
    INSTANCE: typing.ClassVar[EmptySequence] = ...
    def drop(self, n: int | java.jint | java.lang.Integer, /) -> EmptySequence: ...
    def iterator(self) -> java.util.Iterator: ...
    def take(self, n: int | java.jint | java.lang.Integer, /) -> EmptySequence: ...

_FilteringSequence__T = typing.TypeVar('_FilteringSequence__T')  # <T>
class FilteringSequence(Sequence[_FilteringSequence__T], typing.Generic[_FilteringSequence__T]):
    def __init__(self, sequence: Sequence[_FilteringSequence__T], sendWhen: bool | java.jboolean | java.lang.Boolean, predicate: kotlin.jvm.functions.Function1[_FilteringSequence__T, java.lang.Boolean], /) -> None: ...
    def iterator(self) -> java.util.Iterator[_FilteringSequence__T]: ...

_FlatteningSequence__T = typing.TypeVar('_FlatteningSequence__T')  # <T>
_FlatteningSequence__R = typing.TypeVar('_FlatteningSequence__R')  # <R>
_FlatteningSequence__E = typing.TypeVar('_FlatteningSequence__E')  # <E>
class FlatteningSequence(Sequence[_FlatteningSequence__E], typing.Generic[_FlatteningSequence__T, _FlatteningSequence__R, _FlatteningSequence__E]):
    def __init__(self, sequence: Sequence[_FlatteningSequence__T], transformer: kotlin.jvm.functions.Function1[_FlatteningSequence__T, _FlatteningSequence__R], iterator: kotlin.jvm.functions.Function1[_FlatteningSequence__R, java.util.Iterator[_FlatteningSequence__E]], /) -> None: ...
    def iterator(self) -> java.util.Iterator[_FlatteningSequence__E]: ...

_GeneratorSequence__T = typing.TypeVar('_GeneratorSequence__T')  # <T>
class GeneratorSequence(Sequence[_GeneratorSequence__T], typing.Generic[_GeneratorSequence__T]):
    def __init__(self, getInitialValue: kotlin.jvm.functions.Function0[_GeneratorSequence__T], getNextValue: kotlin.jvm.functions.Function1[_GeneratorSequence__T, _GeneratorSequence__T], /) -> None: ...
    def iterator(self) -> java.util.Iterator[_GeneratorSequence__T]: ...

_IndexingSequence__T = typing.TypeVar('_IndexingSequence__T')  # <T>
class IndexingSequence(Sequence[kotlin.collections.IndexedValue[_IndexingSequence__T]], typing.Generic[_IndexingSequence__T]):
    def __init__(self, sequence: Sequence[_IndexingSequence__T], /) -> None: ...
    def iterator(self) -> java.util.Iterator[kotlin.collections.IndexedValue[_IndexingSequence__T]]: ...

_MergingSequence__T1 = typing.TypeVar('_MergingSequence__T1')  # <T1>
_MergingSequence__T2 = typing.TypeVar('_MergingSequence__T2')  # <T2>
_MergingSequence__V = typing.TypeVar('_MergingSequence__V')  # <V>
class MergingSequence(Sequence[_MergingSequence__V], typing.Generic[_MergingSequence__T1, _MergingSequence__T2, _MergingSequence__V]):
    def __init__(self, sequence1: Sequence[_MergingSequence__T1], sequence2: Sequence[_MergingSequence__T2], transform: kotlin.jvm.functions.Function2[_MergingSequence__T1, _MergingSequence__T2, _MergingSequence__V], /) -> None: ...
    def iterator(self) -> java.util.Iterator[_MergingSequence__V]: ...

_Sequence__T = typing.TypeVar('_Sequence__T')  # <T>
class Sequence(java.lang.Object, typing.Generic[_Sequence__T]):
    def iterator(self) -> java.util.Iterator[_Sequence__T]: ...

_SequenceBuilderIterator__T = typing.TypeVar('_SequenceBuilderIterator__T')  # <T>
class SequenceBuilderIterator(SequenceScope[_SequenceBuilderIterator__T], java.util.Iterator[_SequenceBuilderIterator__T], kotlin.coroutines.Continuation[kotlin.Unit], kotlin.jvm.internal.markers.KMappedMarker, typing.Generic[_SequenceBuilderIterator__T]):
    def __init__(self) -> None: ...
    def getContext(self) -> kotlin.coroutines.CoroutineContext: ...
    def getNextStep(self) -> kotlin.coroutines.Continuation[kotlin.Unit]: ...
    def hasNext(self) -> bool: ...
    def next(self) -> _SequenceBuilderIterator__T: ...
    def remove(self) -> None: ...
    def resumeWith(self, result: java.lang.Object | int | bool | float | str, /) -> None: ...
    def setNextStep(self, <set-?>: kotlin.coroutines.Continuation[kotlin.Unit], /) -> None: ...
    def yieldAll(self, iterator: java.util.Iterator[_SequenceBuilderIterator__T], completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def yield_(self, value: _SequenceBuilderIterator__T, completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...

_SequenceScope__T = typing.TypeVar('_SequenceScope__T')  # <T>
class SequenceScope(java.lang.Object, typing.Generic[_SequenceScope__T]):
    def __init__(self) -> None: ...
    @typing.overload
    def yieldAll(self, elements: java.lang.Iterable[_SequenceScope__T], completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    @typing.overload
    def yieldAll(self, arg1: java.util.Iterator[_SequenceScope__T], arg2: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    @typing.overload
    def yieldAll(self, sequence: Sequence[_SequenceScope__T], completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def yield_(self, arg1: _SequenceScope__T, arg2: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...

class SequencesKt(SequencesKt___SequencesKt): ...

class SequencesKt__SequenceBuilderKt(java.lang.Object):
    def __init__(self) -> None: ...
    _iterator__T = typing.TypeVar('_iterator__T')  # <T>
    @staticmethod
    def iterator(block: kotlin.jvm.functions.Function2[SequenceScope[_iterator__T], kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], /) -> java.util.Iterator[_iterator__T]: ...
    _sequence__T = typing.TypeVar('_sequence__T')  # <T>
    @staticmethod
    def sequence(block: kotlin.jvm.functions.Function2[SequenceScope[_sequence__T], kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], /) -> Sequence[_sequence__T]: ...

class SequencesKt__SequencesJVMKt(SequencesKt__SequenceBuilderKt):
    def __init__(self) -> None: ...

class SequencesKt__SequencesKt(SequencesKt__SequencesJVMKt):
    def __init__(self) -> None: ...
    _asSequence__T = typing.TypeVar('_asSequence__T')  # <T>
    @staticmethod
    def asSequence(this_asSequence: java.util.Iterator[_asSequence__T], /) -> Sequence[_asSequence__T]: ...
    _constrainOnce__T = typing.TypeVar('_constrainOnce__T')  # <T>
    @staticmethod
    def constrainOnce(this_constrainOnce: Sequence[_constrainOnce__T], /) -> Sequence[_constrainOnce__T]: ...
    @staticmethod
    def emptySequence() -> Sequence[java.lang.Object]: ...
    _flatMapIndexed__T = typing.TypeVar('_flatMapIndexed__T')  # <T>
    _flatMapIndexed__C = typing.TypeVar('_flatMapIndexed__C')  # <C>
    _flatMapIndexed__R = typing.TypeVar('_flatMapIndexed__R')  # <R>
    @staticmethod
    def flatMapIndexed(source: Sequence[_flatMapIndexed__T], transform: kotlin.jvm.functions.Function2[int, _flatMapIndexed__T, _flatMapIndexed__C], iterator: kotlin.jvm.functions.Function1[_flatMapIndexed__C, java.util.Iterator[_flatMapIndexed__R]], /) -> Sequence[_flatMapIndexed__R]: ...
    _flatten__T = typing.TypeVar('_flatten__T')  # <T>
    @staticmethod
    def flatten(this_flatten: Sequence[Sequence[_flatten__T]], /) -> Sequence[_flatten__T]: ...
    _flattenSequenceOfIterable__T = typing.TypeVar('_flattenSequenceOfIterable__T')  # <T>
    @staticmethod
    def flattenSequenceOfIterable(this_flatten: Sequence[java.lang.Iterable[_flattenSequenceOfIterable__T]], /) -> Sequence[_flattenSequenceOfIterable__T]: ...
    _generateSequence_0__T = typing.TypeVar('_generateSequence_0__T')  # <T>
    _generateSequence_1__T = typing.TypeVar('_generateSequence_1__T')  # <T>
    _generateSequence_2__T = typing.TypeVar('_generateSequence_2__T')  # <T>
    @typing.overload
    @staticmethod
    def generateSequence(nextFunction: kotlin.jvm.functions.Function0[_generateSequence_0__T], /) -> Sequence[_generateSequence_0__T]: ...
    @typing.overload
    @staticmethod
    def generateSequence(seed: _generateSequence_1__T, nextFunction: kotlin.jvm.functions.Function1[_generateSequence_1__T, _generateSequence_1__T], /) -> Sequence[_generateSequence_1__T]: ...
    @typing.overload
    @staticmethod
    def generateSequence(seedFunction: kotlin.jvm.functions.Function0[_generateSequence_2__T], nextFunction: kotlin.jvm.functions.Function1[_generateSequence_2__T, _generateSequence_2__T], /) -> Sequence[_generateSequence_2__T]: ...
    _ifEmpty__T = typing.TypeVar('_ifEmpty__T')  # <T>
    @staticmethod
    def ifEmpty(this_ifEmpty: Sequence[_ifEmpty__T], defaultValue: kotlin.jvm.functions.Function0[Sequence[_ifEmpty__T]], /) -> Sequence[_ifEmpty__T]: ...
    _sequenceOf__T = typing.TypeVar('_sequenceOf__T')  # <T>
    @staticmethod
    def sequenceOf(*elements: _sequenceOf__T) -> Sequence[_sequenceOf__T]: ...
    _shuffled_0__T = typing.TypeVar('_shuffled_0__T')  # <T>
    _shuffled_1__T = typing.TypeVar('_shuffled_1__T')  # <T>
    @typing.overload
    @staticmethod
    def shuffled(this_shuffled: Sequence[_shuffled_0__T], /) -> Sequence[_shuffled_0__T]: ...
    @typing.overload
    @staticmethod
    def shuffled(this_shuffled: Sequence[_shuffled_1__T], random: kotlin.random.Random, /) -> Sequence[_shuffled_1__T]: ...
    _unzip__T = typing.TypeVar('_unzip__T')  # <T>
    _unzip__R = typing.TypeVar('_unzip__R')  # <R>
    @staticmethod
    def unzip(this_unzip: Sequence[kotlin.Pair[_unzip__T, _unzip__R]], /) -> kotlin.Pair[java.util.List[_unzip__T], java.util.List[_unzip__R]]: ...

class SequencesKt___SequencesJvmKt(SequencesKt__SequencesKt):
    def __init__(self) -> None: ...
    _filterIsInstance__R = typing.TypeVar('_filterIsInstance__R')  # <R>
    @staticmethod
    def filterIsInstance(this_filterIsInstance: Sequence[java.lang.Object], klass: typing.Type[_filterIsInstance__R], /) -> Sequence[_filterIsInstance__R]: ...
    _filterIsInstanceTo__C = typing.TypeVar('_filterIsInstanceTo__C')  # <C>
    @staticmethod
    def filterIsInstanceTo(this_filterIsInstanceTo: Sequence[java.lang.Object], destination: _filterIsInstanceTo__C, klass: typing.Type[java.lang.Object], /) -> _filterIsInstanceTo__C: ...
    _toSortedSet_0__T = typing.TypeVar('_toSortedSet_0__T')  # <T>
    _toSortedSet_1__T = typing.TypeVar('_toSortedSet_1__T')  # <T>
    @typing.overload
    @staticmethod
    def toSortedSet(this_toSortedSet: Sequence[_toSortedSet_0__T], /) -> java.util.SortedSet[_toSortedSet_0__T]: ...
    @typing.overload
    @staticmethod
    def toSortedSet(this_toSortedSet: Sequence[_toSortedSet_1__T], comparator: java.util.Comparator[_toSortedSet_1__T], /) -> java.util.SortedSet[_toSortedSet_1__T]: ...

class SequencesKt___SequencesKt(SequencesKt___SequencesJvmKt):
    def __init__(self) -> None: ...
    _all__T = typing.TypeVar('_all__T')  # <T>
    @staticmethod
    def all(this_all: Sequence[_all__T], predicate: kotlin.jvm.functions.Function1[_all__T, java.lang.Boolean], /) -> bool: ...
    _any_1__T = typing.TypeVar('_any_1__T')  # <T>
    @typing.overload
    @staticmethod
    def any(this_any: Sequence[java.lang.Object], /) -> bool: ...
    @typing.overload
    @staticmethod
    def any(this_any: Sequence[_any_1__T], predicate: kotlin.jvm.functions.Function1[_any_1__T, java.lang.Boolean], /) -> bool: ...
    _asIterable__T = typing.TypeVar('_asIterable__T')  # <T>
    @staticmethod
    def asIterable(this_asIterable: Sequence[_asIterable__T], /) -> java.lang.Iterable[_asIterable__T]: ...
    _associate__T = typing.TypeVar('_associate__T')  # <T>
    _associate__K = typing.TypeVar('_associate__K')  # <K>
    _associate__V = typing.TypeVar('_associate__V')  # <V>
    @staticmethod
    def associate(this_associate: Sequence[_associate__T], transform: kotlin.jvm.functions.Function1[_associate__T, kotlin.Pair[_associate__K, _associate__V]], /) -> java.util.Map[_associate__K, _associate__V]: ...
    _associateBy_0__T = typing.TypeVar('_associateBy_0__T')  # <T>
    _associateBy_0__K = typing.TypeVar('_associateBy_0__K')  # <K>
    _associateBy_1__T = typing.TypeVar('_associateBy_1__T')  # <T>
    _associateBy_1__K = typing.TypeVar('_associateBy_1__K')  # <K>
    _associateBy_1__V = typing.TypeVar('_associateBy_1__V')  # <V>
    @typing.overload
    @staticmethod
    def associateBy(this_associateBy: Sequence[_associateBy_0__T], keySelector: kotlin.jvm.functions.Function1[_associateBy_0__T, _associateBy_0__K], /) -> java.util.Map[_associateBy_0__K, _associateBy_0__T]: ...
    @typing.overload
    @staticmethod
    def associateBy(this_associateBy: Sequence[_associateBy_1__T], keySelector: kotlin.jvm.functions.Function1[_associateBy_1__T, _associateBy_1__K], valueTransform: kotlin.jvm.functions.Function1[_associateBy_1__T, _associateBy_1__V], /) -> java.util.Map[_associateBy_1__K, _associateBy_1__V]: ...
    _associateByTo_0__T = typing.TypeVar('_associateByTo_0__T')  # <T>
    _associateByTo_0__M = typing.TypeVar('_associateByTo_0__M')  # <M>
    _associateByTo_1__T = typing.TypeVar('_associateByTo_1__T')  # <T>
    _associateByTo_1__M = typing.TypeVar('_associateByTo_1__M')  # <M>
    @typing.overload
    @staticmethod
    def associateByTo(this_associateByTo: Sequence[_associateByTo_0__T], destination: _associateByTo_0__M, keySelector: kotlin.jvm.functions.Function1[_associateByTo_0__T, java.lang.Object], /) -> _associateByTo_0__M: ...
    @typing.overload
    @staticmethod
    def associateByTo(this_associateByTo: Sequence[_associateByTo_1__T], destination: _associateByTo_1__M, keySelector: kotlin.jvm.functions.Function1[_associateByTo_1__T, java.lang.Object], valueTransform: kotlin.jvm.functions.Function1[_associateByTo_1__T, java.lang.Object], /) -> _associateByTo_1__M: ...
    _associateTo__T = typing.TypeVar('_associateTo__T')  # <T>
    _associateTo__M = typing.TypeVar('_associateTo__M')  # <M>
    @staticmethod
    def associateTo(this_associateTo: Sequence[_associateTo__T], destination: _associateTo__M, transform: kotlin.jvm.functions.Function1[_associateTo__T, kotlin.Pair[java.lang.Object, java.lang.Object]], /) -> _associateTo__M: ...
    _associateWith__K = typing.TypeVar('_associateWith__K')  # <K>
    _associateWith__V = typing.TypeVar('_associateWith__V')  # <V>
    @staticmethod
    def associateWith(this_associateWith: Sequence[_associateWith__K], valueSelector: kotlin.jvm.functions.Function1[_associateWith__K, _associateWith__V], /) -> java.util.Map[_associateWith__K, _associateWith__V]: ...
    _associateWithTo__K = typing.TypeVar('_associateWithTo__K')  # <K>
    _associateWithTo__M = typing.TypeVar('_associateWithTo__M')  # <M>
    @staticmethod
    def associateWithTo(this_associateWithTo: Sequence[_associateWithTo__K], destination: _associateWithTo__M, valueSelector: kotlin.jvm.functions.Function1[_associateWithTo__K, java.lang.Object], /) -> _associateWithTo__M: ...
    @staticmethod
    def averageOfByte(this_average: Sequence[java.lang.Byte], /) -> float: ...
    @staticmethod
    def averageOfDouble(this_average: Sequence[java.lang.Double], /) -> float: ...
    @staticmethod
    def averageOfFloat(this_average: Sequence[java.lang.Float], /) -> float: ...
    @staticmethod
    def averageOfInt(this_average: Sequence[java.lang.Integer], /) -> float: ...
    @staticmethod
    def averageOfLong(this_average: Sequence[java.lang.Long], /) -> float: ...
    @staticmethod
    def averageOfShort(this_average: Sequence[java.lang.Short], /) -> float: ...
    _chunked_0__T = typing.TypeVar('_chunked_0__T')  # <T>
    _chunked_1__T = typing.TypeVar('_chunked_1__T')  # <T>
    _chunked_1__R = typing.TypeVar('_chunked_1__R')  # <R>
    @typing.overload
    @staticmethod
    def chunked(this_chunked: Sequence[_chunked_0__T], size: int | java.jint | java.lang.Integer, /) -> Sequence[java.util.List[_chunked_0__T]]: ...
    @typing.overload
    @staticmethod
    def chunked(this_chunked: Sequence[_chunked_1__T], size: int | java.jint | java.lang.Integer, transform: kotlin.jvm.functions.Function1[java.util.List[_chunked_1__T], _chunked_1__R], /) -> Sequence[_chunked_1__R]: ...
    _contains__T = typing.TypeVar('_contains__T')  # <T>
    @staticmethod
    def contains(this_contains: Sequence[_contains__T], element: _contains__T, /) -> bool: ...
    _count_1__T = typing.TypeVar('_count_1__T')  # <T>
    @typing.overload
    @staticmethod
    def count(this_count: Sequence[java.lang.Object], /) -> int: ...
    @typing.overload
    @staticmethod
    def count(this_count: Sequence[_count_1__T], predicate: kotlin.jvm.functions.Function1[_count_1__T, java.lang.Boolean], /) -> int: ...
    _distinct__T = typing.TypeVar('_distinct__T')  # <T>
    @staticmethod
    def distinct(this_distinct: Sequence[_distinct__T], /) -> Sequence[_distinct__T]: ...
    _distinctBy__T = typing.TypeVar('_distinctBy__T')  # <T>
    @staticmethod
    def distinctBy(this_distinctBy: Sequence[_distinctBy__T], selector: kotlin.jvm.functions.Function1[_distinctBy__T, java.lang.Object], /) -> Sequence[_distinctBy__T]: ...
    _drop__T = typing.TypeVar('_drop__T')  # <T>
    @staticmethod
    def drop(this_drop: Sequence[_drop__T], n: int | java.jint | java.lang.Integer, /) -> Sequence[_drop__T]: ...
    _dropWhile__T = typing.TypeVar('_dropWhile__T')  # <T>
    @staticmethod
    def dropWhile(this_dropWhile: Sequence[_dropWhile__T], predicate: kotlin.jvm.functions.Function1[_dropWhile__T, java.lang.Boolean], /) -> Sequence[_dropWhile__T]: ...
    _elementAt__T = typing.TypeVar('_elementAt__T')  # <T>
    @staticmethod
    def elementAt(this_elementAt: Sequence[_elementAt__T], index: int | java.jint | java.lang.Integer, /) -> _elementAt__T: ...
    _elementAtOrElse__T = typing.TypeVar('_elementAtOrElse__T')  # <T>
    @staticmethod
    def elementAtOrElse(this_elementAtOrElse: Sequence[_elementAtOrElse__T], index: int | java.jint | java.lang.Integer, defaultValue: kotlin.jvm.functions.Function1[int, _elementAtOrElse__T], /) -> _elementAtOrElse__T: ...
    _elementAtOrNull__T = typing.TypeVar('_elementAtOrNull__T')  # <T>
    @staticmethod
    def elementAtOrNull(this_elementAtOrNull: Sequence[_elementAtOrNull__T], index: int | java.jint | java.lang.Integer, /) -> _elementAtOrNull__T: ...
    _filter__T = typing.TypeVar('_filter__T')  # <T>
    @staticmethod
    def filter(this_filter: Sequence[_filter__T], predicate: kotlin.jvm.functions.Function1[_filter__T, java.lang.Boolean], /) -> Sequence[_filter__T]: ...
    _filterIndexed__T = typing.TypeVar('_filterIndexed__T')  # <T>
    @staticmethod
    def filterIndexed(this_filterIndexed: Sequence[_filterIndexed__T], predicate: kotlin.jvm.functions.Function2[int, _filterIndexed__T, java.lang.Boolean], /) -> Sequence[_filterIndexed__T]: ...
    _filterIndexedTo__T = typing.TypeVar('_filterIndexedTo__T')  # <T>
    _filterIndexedTo__C = typing.TypeVar('_filterIndexedTo__C')  # <C>
    @staticmethod
    def filterIndexedTo(this_filterIndexedTo: Sequence[_filterIndexedTo__T], destination: _filterIndexedTo__C, predicate: kotlin.jvm.functions.Function2[int, _filterIndexedTo__T, java.lang.Boolean], /) -> _filterIndexedTo__C: ...
    _filterNot__T = typing.TypeVar('_filterNot__T')  # <T>
    @staticmethod
    def filterNot(this_filterNot: Sequence[_filterNot__T], predicate: kotlin.jvm.functions.Function1[_filterNot__T, java.lang.Boolean], /) -> Sequence[_filterNot__T]: ...
    _filterNotNull__T = typing.TypeVar('_filterNotNull__T')  # <T>
    @staticmethod
    def filterNotNull(this_filterNotNull: Sequence[_filterNotNull__T], /) -> Sequence[_filterNotNull__T]: ...
    _filterNotNullTo__C = typing.TypeVar('_filterNotNullTo__C')  # <C>
    @staticmethod
    def filterNotNullTo(this_filterNotNullTo: Sequence[java.lang.Object], destination: _filterNotNullTo__C, /) -> _filterNotNullTo__C: ...
    _filterNotTo__T = typing.TypeVar('_filterNotTo__T')  # <T>
    _filterNotTo__C = typing.TypeVar('_filterNotTo__C')  # <C>
    @staticmethod
    def filterNotTo(this_filterNotTo: Sequence[_filterNotTo__T], destination: _filterNotTo__C, predicate: kotlin.jvm.functions.Function1[_filterNotTo__T, java.lang.Boolean], /) -> _filterNotTo__C: ...
    _filterTo__T = typing.TypeVar('_filterTo__T')  # <T>
    _filterTo__C = typing.TypeVar('_filterTo__C')  # <C>
    @staticmethod
    def filterTo(this_filterTo: Sequence[_filterTo__T], destination: _filterTo__C, predicate: kotlin.jvm.functions.Function1[_filterTo__T, java.lang.Boolean], /) -> _filterTo__C: ...
    _first_0__T = typing.TypeVar('_first_0__T')  # <T>
    _first_1__T = typing.TypeVar('_first_1__T')  # <T>
    @typing.overload
    @staticmethod
    def first(this_first: Sequence[_first_0__T], /) -> _first_0__T: ...
    @typing.overload
    @staticmethod
    def first(this_first: Sequence[_first_1__T], predicate: kotlin.jvm.functions.Function1[_first_1__T, java.lang.Boolean], /) -> _first_1__T: ...
    _firstOrNull_0__T = typing.TypeVar('_firstOrNull_0__T')  # <T>
    _firstOrNull_1__T = typing.TypeVar('_firstOrNull_1__T')  # <T>
    @typing.overload
    @staticmethod
    def firstOrNull(this_firstOrNull: Sequence[_firstOrNull_0__T], /) -> _firstOrNull_0__T: ...
    @typing.overload
    @staticmethod
    def firstOrNull(this_firstOrNull: Sequence[_firstOrNull_1__T], predicate: kotlin.jvm.functions.Function1[_firstOrNull_1__T, java.lang.Boolean], /) -> _firstOrNull_1__T: ...
    _flatMap__T = typing.TypeVar('_flatMap__T')  # <T>
    _flatMap__R = typing.TypeVar('_flatMap__R')  # <R>
    @staticmethod
    def flatMap(this_flatMap: Sequence[_flatMap__T], transform: kotlin.jvm.functions.Function1[_flatMap__T, Sequence[_flatMap__R]], /) -> Sequence[_flatMap__R]: ...
    _flatMapIndexedIterable__T = typing.TypeVar('_flatMapIndexedIterable__T')  # <T>
    _flatMapIndexedIterable__R = typing.TypeVar('_flatMapIndexedIterable__R')  # <R>
    @staticmethod
    def flatMapIndexedIterable(this_flatMapIndexed: Sequence[_flatMapIndexedIterable__T], transform: kotlin.jvm.functions.Function2[int, _flatMapIndexedIterable__T, java.lang.Iterable[_flatMapIndexedIterable__R]], /) -> Sequence[_flatMapIndexedIterable__R]: ...
    _flatMapIndexedSequence__T = typing.TypeVar('_flatMapIndexedSequence__T')  # <T>
    _flatMapIndexedSequence__R = typing.TypeVar('_flatMapIndexedSequence__R')  # <R>
    @staticmethod
    def flatMapIndexedSequence(this_flatMapIndexed: Sequence[_flatMapIndexedSequence__T], transform: kotlin.jvm.functions.Function2[int, _flatMapIndexedSequence__T, Sequence[_flatMapIndexedSequence__R]], /) -> Sequence[_flatMapIndexedSequence__R]: ...
    _flatMapIterable__T = typing.TypeVar('_flatMapIterable__T')  # <T>
    _flatMapIterable__R = typing.TypeVar('_flatMapIterable__R')  # <R>
    @staticmethod
    def flatMapIterable(this_flatMap: Sequence[_flatMapIterable__T], transform: kotlin.jvm.functions.Function1[_flatMapIterable__T, java.lang.Iterable[_flatMapIterable__R]], /) -> Sequence[_flatMapIterable__R]: ...
    _flatMapIterableTo__T = typing.TypeVar('_flatMapIterableTo__T')  # <T>
    _flatMapIterableTo__C = typing.TypeVar('_flatMapIterableTo__C')  # <C>
    @staticmethod
    def flatMapIterableTo(this_flatMapTo: Sequence[_flatMapIterableTo__T], destination: _flatMapIterableTo__C, transform: kotlin.jvm.functions.Function1[_flatMapIterableTo__T, java.lang.Iterable[java.lang.Object]], /) -> _flatMapIterableTo__C: ...
    _flatMapTo__T = typing.TypeVar('_flatMapTo__T')  # <T>
    _flatMapTo__C = typing.TypeVar('_flatMapTo__C')  # <C>
    @staticmethod
    def flatMapTo(this_flatMapTo: Sequence[_flatMapTo__T], destination: _flatMapTo__C, transform: kotlin.jvm.functions.Function1[_flatMapTo__T, Sequence[java.lang.Object]], /) -> _flatMapTo__C: ...
    _fold__T = typing.TypeVar('_fold__T')  # <T>
    _fold__R = typing.TypeVar('_fold__R')  # <R>
    @staticmethod
    def fold(this_fold: Sequence[_fold__T], initial: _fold__R, operation: kotlin.jvm.functions.Function2[_fold__R, _fold__T, _fold__R], /) -> _fold__R: ...
    _foldIndexed__T = typing.TypeVar('_foldIndexed__T')  # <T>
    _foldIndexed__R = typing.TypeVar('_foldIndexed__R')  # <R>
    @staticmethod
    def foldIndexed(this_foldIndexed: Sequence[_foldIndexed__T], initial: _foldIndexed__R, operation: kotlin.jvm.functions.Function3[int, _foldIndexed__R, _foldIndexed__T, _foldIndexed__R], /) -> _foldIndexed__R: ...
    _forEach__T = typing.TypeVar('_forEach__T')  # <T>
    @staticmethod
    def forEach(this_forEach: Sequence[_forEach__T], action: kotlin.jvm.functions.Function1[_forEach__T, kotlin.Unit], /) -> None: ...
    _forEachIndexed__T = typing.TypeVar('_forEachIndexed__T')  # <T>
    @staticmethod
    def forEachIndexed(this_forEachIndexed: Sequence[_forEachIndexed__T], action: kotlin.jvm.functions.Function2[int, _forEachIndexed__T, kotlin.Unit], /) -> None: ...
    _groupBy_0__T = typing.TypeVar('_groupBy_0__T')  # <T>
    _groupBy_0__K = typing.TypeVar('_groupBy_0__K')  # <K>
    _groupBy_1__T = typing.TypeVar('_groupBy_1__T')  # <T>
    _groupBy_1__K = typing.TypeVar('_groupBy_1__K')  # <K>
    _groupBy_1__V = typing.TypeVar('_groupBy_1__V')  # <V>
    @typing.overload
    @staticmethod
    def groupBy(this_groupBy: Sequence[_groupBy_0__T], keySelector: kotlin.jvm.functions.Function1[_groupBy_0__T, _groupBy_0__K], /) -> java.util.Map[_groupBy_0__K, java.util.List[_groupBy_0__T]]: ...
    @typing.overload
    @staticmethod
    def groupBy(this_groupBy: Sequence[_groupBy_1__T], keySelector: kotlin.jvm.functions.Function1[_groupBy_1__T, _groupBy_1__K], valueTransform: kotlin.jvm.functions.Function1[_groupBy_1__T, _groupBy_1__V], /) -> java.util.Map[_groupBy_1__K, java.util.List[_groupBy_1__V]]: ...
    _groupByTo_0__T = typing.TypeVar('_groupByTo_0__T')  # <T>
    _groupByTo_0__M = typing.TypeVar('_groupByTo_0__M')  # <M>
    _groupByTo_1__T = typing.TypeVar('_groupByTo_1__T')  # <T>
    _groupByTo_1__M = typing.TypeVar('_groupByTo_1__M')  # <M>
    @typing.overload
    @staticmethod
    def groupByTo(this_groupByTo: Sequence[_groupByTo_0__T], destination: _groupByTo_0__M, keySelector: kotlin.jvm.functions.Function1[_groupByTo_0__T, java.lang.Object], /) -> _groupByTo_0__M: ...
    @typing.overload
    @staticmethod
    def groupByTo(this_groupByTo: Sequence[_groupByTo_1__T], destination: _groupByTo_1__M, keySelector: kotlin.jvm.functions.Function1[_groupByTo_1__T, java.lang.Object], valueTransform: kotlin.jvm.functions.Function1[_groupByTo_1__T, java.lang.Object], /) -> _groupByTo_1__M: ...
    _groupingBy__T = typing.TypeVar('_groupingBy__T')  # <T>
    _groupingBy__K = typing.TypeVar('_groupingBy__K')  # <K>
    @staticmethod
    def groupingBy(this_groupingBy: Sequence[_groupingBy__T], keySelector: kotlin.jvm.functions.Function1[_groupingBy__T, _groupingBy__K], /) -> kotlin.collections.Grouping[_groupingBy__T, _groupingBy__K]: ...
    _indexOf__T = typing.TypeVar('_indexOf__T')  # <T>
    @staticmethod
    def indexOf(this_indexOf: Sequence[_indexOf__T], element: _indexOf__T, /) -> int: ...
    _indexOfFirst__T = typing.TypeVar('_indexOfFirst__T')  # <T>
    @staticmethod
    def indexOfFirst(this_indexOfFirst: Sequence[_indexOfFirst__T], predicate: kotlin.jvm.functions.Function1[_indexOfFirst__T, java.lang.Boolean], /) -> int: ...
    _indexOfLast__T = typing.TypeVar('_indexOfLast__T')  # <T>
    @staticmethod
    def indexOfLast(this_indexOfLast: Sequence[_indexOfLast__T], predicate: kotlin.jvm.functions.Function1[_indexOfLast__T, java.lang.Boolean], /) -> int: ...
    _joinTo__T = typing.TypeVar('_joinTo__T')  # <T>
    _joinTo__A = typing.TypeVar('_joinTo__A')  # <A>
    @staticmethod
    def joinTo(this_joinTo: Sequence[_joinTo__T], buffer: _joinTo__A, separator: java.lang.CharSequence, prefix: java.lang.CharSequence, postfix: java.lang.CharSequence, limit: int | java.jint | java.lang.Integer, truncated: java.lang.CharSequence, transform: kotlin.jvm.functions.Function1[_joinTo__T, java.lang.CharSequence], /) -> _joinTo__A: ...
    _joinToString__T = typing.TypeVar('_joinToString__T')  # <T>
    @staticmethod
    def joinToString(this_joinToString: Sequence[_joinToString__T], separator: java.lang.CharSequence, prefix: java.lang.CharSequence, postfix: java.lang.CharSequence, limit: int | java.jint | java.lang.Integer, truncated: java.lang.CharSequence, transform: kotlin.jvm.functions.Function1[_joinToString__T, java.lang.CharSequence], /) -> str: ...
    _last_0__T = typing.TypeVar('_last_0__T')  # <T>
    _last_1__T = typing.TypeVar('_last_1__T')  # <T>
    @typing.overload
    @staticmethod
    def last(this_last: Sequence[_last_0__T], /) -> _last_0__T: ...
    @typing.overload
    @staticmethod
    def last(this_last: Sequence[_last_1__T], predicate: kotlin.jvm.functions.Function1[_last_1__T, java.lang.Boolean], /) -> _last_1__T: ...
    _lastIndexOf__T = typing.TypeVar('_lastIndexOf__T')  # <T>
    @staticmethod
    def lastIndexOf(this_lastIndexOf: Sequence[_lastIndexOf__T], element: _lastIndexOf__T, /) -> int: ...
    _lastOrNull_0__T = typing.TypeVar('_lastOrNull_0__T')  # <T>
    _lastOrNull_1__T = typing.TypeVar('_lastOrNull_1__T')  # <T>
    @typing.overload
    @staticmethod
    def lastOrNull(this_lastOrNull: Sequence[_lastOrNull_0__T], /) -> _lastOrNull_0__T: ...
    @typing.overload
    @staticmethod
    def lastOrNull(this_lastOrNull: Sequence[_lastOrNull_1__T], predicate: kotlin.jvm.functions.Function1[_lastOrNull_1__T, java.lang.Boolean], /) -> _lastOrNull_1__T: ...
    _map__T = typing.TypeVar('_map__T')  # <T>
    _map__R = typing.TypeVar('_map__R')  # <R>
    @staticmethod
    def map(this_map: Sequence[_map__T], transform: kotlin.jvm.functions.Function1[_map__T, _map__R], /) -> Sequence[_map__R]: ...
    _mapIndexed__T = typing.TypeVar('_mapIndexed__T')  # <T>
    _mapIndexed__R = typing.TypeVar('_mapIndexed__R')  # <R>
    @staticmethod
    def mapIndexed(this_mapIndexed: Sequence[_mapIndexed__T], transform: kotlin.jvm.functions.Function2[int, _mapIndexed__T, _mapIndexed__R], /) -> Sequence[_mapIndexed__R]: ...
    _mapIndexedNotNull__T = typing.TypeVar('_mapIndexedNotNull__T')  # <T>
    _mapIndexedNotNull__R = typing.TypeVar('_mapIndexedNotNull__R')  # <R>
    @staticmethod
    def mapIndexedNotNull(this_mapIndexedNotNull: Sequence[_mapIndexedNotNull__T], transform: kotlin.jvm.functions.Function2[int, _mapIndexedNotNull__T, _mapIndexedNotNull__R], /) -> Sequence[_mapIndexedNotNull__R]: ...
    _mapIndexedNotNullTo__T = typing.TypeVar('_mapIndexedNotNullTo__T')  # <T>
    _mapIndexedNotNullTo__C = typing.TypeVar('_mapIndexedNotNullTo__C')  # <C>
    @staticmethod
    def mapIndexedNotNullTo(this_mapIndexedNotNullTo: Sequence[_mapIndexedNotNullTo__T], destination: _mapIndexedNotNullTo__C, transform: kotlin.jvm.functions.Function2[int, _mapIndexedNotNullTo__T, java.lang.Object], /) -> _mapIndexedNotNullTo__C: ...
    _mapIndexedTo__T = typing.TypeVar('_mapIndexedTo__T')  # <T>
    _mapIndexedTo__C = typing.TypeVar('_mapIndexedTo__C')  # <C>
    @staticmethod
    def mapIndexedTo(this_mapIndexedTo: Sequence[_mapIndexedTo__T], destination: _mapIndexedTo__C, transform: kotlin.jvm.functions.Function2[int, _mapIndexedTo__T, java.lang.Object], /) -> _mapIndexedTo__C: ...
    _mapNotNull__T = typing.TypeVar('_mapNotNull__T')  # <T>
    _mapNotNull__R = typing.TypeVar('_mapNotNull__R')  # <R>
    @staticmethod
    def mapNotNull(this_mapNotNull: Sequence[_mapNotNull__T], transform: kotlin.jvm.functions.Function1[_mapNotNull__T, _mapNotNull__R], /) -> Sequence[_mapNotNull__R]: ...
    _mapNotNullTo__T = typing.TypeVar('_mapNotNullTo__T')  # <T>
    _mapNotNullTo__C = typing.TypeVar('_mapNotNullTo__C')  # <C>
    @staticmethod
    def mapNotNullTo(this_mapNotNullTo: Sequence[_mapNotNullTo__T], destination: _mapNotNullTo__C, transform: kotlin.jvm.functions.Function1[_mapNotNullTo__T, java.lang.Object], /) -> _mapNotNullTo__C: ...
    _mapTo__T = typing.TypeVar('_mapTo__T')  # <T>
    _mapTo__C = typing.TypeVar('_mapTo__C')  # <C>
    @staticmethod
    def mapTo(this_mapTo: Sequence[_mapTo__T], destination: _mapTo__C, transform: kotlin.jvm.functions.Function1[_mapTo__T, java.lang.Object], /) -> _mapTo__C: ...
    _max_0__T = typing.TypeVar('_max_0__T')  # <T>
    @typing.overload
    @staticmethod
    def max(this_max: Sequence[_max_0__T], /) -> _max_0__T: ...
    @typing.overload
    @staticmethod
    def max(this_max: Sequence[java.lang.Double], /) -> float: ...
    @typing.overload
    @staticmethod
    def max(this_max: Sequence[java.lang.Float], /) -> float: ...
    _maxBy__T = typing.TypeVar('_maxBy__T')  # <T>
    @staticmethod
    def maxBy(this_maxBy: Sequence[_maxBy__T], selector: kotlin.jvm.functions.Function1[_maxBy__T, java.lang.Object], /) -> _maxBy__T: ...
    _maxByOrNull__T = typing.TypeVar('_maxByOrNull__T')  # <T>
    @staticmethod
    def maxByOrNull(this_maxByOrNull: Sequence[_maxByOrNull__T], selector: kotlin.jvm.functions.Function1[_maxByOrNull__T, java.lang.Object], /) -> _maxByOrNull__T: ...
    _maxOrNull_0__T = typing.TypeVar('_maxOrNull_0__T')  # <T>
    @typing.overload
    @staticmethod
    def maxOrNull(this_maxOrNull: Sequence[_maxOrNull_0__T], /) -> _maxOrNull_0__T: ...
    @typing.overload
    @staticmethod
    def maxOrNull(this_maxOrNull: Sequence[java.lang.Double], /) -> float: ...
    @typing.overload
    @staticmethod
    def maxOrNull(this_maxOrNull: Sequence[java.lang.Float], /) -> float: ...
    _maxWith__T = typing.TypeVar('_maxWith__T')  # <T>
    @staticmethod
    def maxWith(this_maxWith: Sequence[_maxWith__T], comparator: java.util.Comparator[_maxWith__T], /) -> _maxWith__T: ...
    _maxWithOrNull__T = typing.TypeVar('_maxWithOrNull__T')  # <T>
    @staticmethod
    def maxWithOrNull(this_maxWithOrNull: Sequence[_maxWithOrNull__T], comparator: java.util.Comparator[_maxWithOrNull__T], /) -> _maxWithOrNull__T: ...
    _min_0__T = typing.TypeVar('_min_0__T')  # <T>
    @typing.overload
    @staticmethod
    def min(this_min: Sequence[_min_0__T], /) -> _min_0__T: ...
    @typing.overload
    @staticmethod
    def min(this_min: Sequence[java.lang.Double], /) -> float: ...
    @typing.overload
    @staticmethod
    def min(this_min: Sequence[java.lang.Float], /) -> float: ...
    _minBy__T = typing.TypeVar('_minBy__T')  # <T>
    @staticmethod
    def minBy(this_minBy: Sequence[_minBy__T], selector: kotlin.jvm.functions.Function1[_minBy__T, java.lang.Object], /) -> _minBy__T: ...
    _minByOrNull__T = typing.TypeVar('_minByOrNull__T')  # <T>
    @staticmethod
    def minByOrNull(this_minByOrNull: Sequence[_minByOrNull__T], selector: kotlin.jvm.functions.Function1[_minByOrNull__T, java.lang.Object], /) -> _minByOrNull__T: ...
    _minOrNull_0__T = typing.TypeVar('_minOrNull_0__T')  # <T>
    @typing.overload
    @staticmethod
    def minOrNull(this_minOrNull: Sequence[_minOrNull_0__T], /) -> _minOrNull_0__T: ...
    @typing.overload
    @staticmethod
    def minOrNull(this_minOrNull: Sequence[java.lang.Double], /) -> float: ...
    @typing.overload
    @staticmethod
    def minOrNull(this_minOrNull: Sequence[java.lang.Float], /) -> float: ...
    _minWith__T = typing.TypeVar('_minWith__T')  # <T>
    @staticmethod
    def minWith(this_minWith: Sequence[_minWith__T], comparator: java.util.Comparator[_minWith__T], /) -> _minWith__T: ...
    _minWithOrNull__T = typing.TypeVar('_minWithOrNull__T')  # <T>
    @staticmethod
    def minWithOrNull(this_minWithOrNull: Sequence[_minWithOrNull__T], comparator: java.util.Comparator[_minWithOrNull__T], /) -> _minWithOrNull__T: ...
    _minus_0__T = typing.TypeVar('_minus_0__T')  # <T>
    _minus_1__T = typing.TypeVar('_minus_1__T')  # <T>
    _minus_2__T = typing.TypeVar('_minus_2__T')  # <T>
    _minus_3__T = typing.TypeVar('_minus_3__T')  # <T>
    @typing.overload
    @staticmethod
    def minus(this_minus: Sequence[_minus_0__T], elements: java.lang.Iterable[_minus_0__T], /) -> Sequence[_minus_0__T]: ...
    @typing.overload
    @staticmethod
    def minus(this_minus: Sequence[_minus_1__T], element: _minus_1__T, /) -> Sequence[_minus_1__T]: ...
    @typing.overload
    @staticmethod
    def minus(this_minus: Sequence[_minus_2__T], elements: Sequence[_minus_2__T], /) -> Sequence[_minus_2__T]: ...
    @typing.overload
    @staticmethod
    def minus(this_minus: Sequence[_minus_3__T], elements: java.chaquopy.JavaArray[_minus_3__T], /) -> Sequence[_minus_3__T]: ...
    _none_1__T = typing.TypeVar('_none_1__T')  # <T>
    @typing.overload
    @staticmethod
    def none(this_none: Sequence[java.lang.Object], /) -> bool: ...
    @typing.overload
    @staticmethod
    def none(this_none: Sequence[_none_1__T], predicate: kotlin.jvm.functions.Function1[_none_1__T, java.lang.Boolean], /) -> bool: ...
    _onEach__T = typing.TypeVar('_onEach__T')  # <T>
    @staticmethod
    def onEach(this_onEach: Sequence[_onEach__T], action: kotlin.jvm.functions.Function1[_onEach__T, kotlin.Unit], /) -> Sequence[_onEach__T]: ...
    _onEachIndexed__T = typing.TypeVar('_onEachIndexed__T')  # <T>
    @staticmethod
    def onEachIndexed(this_onEachIndexed: Sequence[_onEachIndexed__T], action: kotlin.jvm.functions.Function2[int, _onEachIndexed__T, kotlin.Unit], /) -> Sequence[_onEachIndexed__T]: ...
    _partition__T = typing.TypeVar('_partition__T')  # <T>
    @staticmethod
    def partition(this_partition: Sequence[_partition__T], predicate: kotlin.jvm.functions.Function1[_partition__T, java.lang.Boolean], /) -> kotlin.Pair[java.util.List[_partition__T], java.util.List[_partition__T]]: ...
    _plus_0__T = typing.TypeVar('_plus_0__T')  # <T>
    _plus_1__T = typing.TypeVar('_plus_1__T')  # <T>
    _plus_2__T = typing.TypeVar('_plus_2__T')  # <T>
    _plus_3__T = typing.TypeVar('_plus_3__T')  # <T>
    @typing.overload
    @staticmethod
    def plus(this_plus: Sequence[_plus_0__T], elements: java.lang.Iterable[_plus_0__T], /) -> Sequence[_plus_0__T]: ...
    @typing.overload
    @staticmethod
    def plus(this_plus: Sequence[_plus_1__T], element: _plus_1__T, /) -> Sequence[_plus_1__T]: ...
    @typing.overload
    @staticmethod
    def plus(this_plus: Sequence[_plus_2__T], elements: Sequence[_plus_2__T], /) -> Sequence[_plus_2__T]: ...
    @typing.overload
    @staticmethod
    def plus(this_plus: Sequence[_plus_3__T], elements: java.chaquopy.JavaArray[_plus_3__T], /) -> Sequence[_plus_3__T]: ...
    _reduce__S = typing.TypeVar('_reduce__S')  # <S>
    _reduce__T = typing.TypeVar('_reduce__T')  # <T>
    @staticmethod
    def reduce(this_reduce: Sequence[_reduce__T], operation: kotlin.jvm.functions.Function2[_reduce__S, _reduce__T, _reduce__S], /) -> _reduce__S: ...
    _reduceIndexed__S = typing.TypeVar('_reduceIndexed__S')  # <S>
    _reduceIndexed__T = typing.TypeVar('_reduceIndexed__T')  # <T>
    @staticmethod
    def reduceIndexed(this_reduceIndexed: Sequence[_reduceIndexed__T], operation: kotlin.jvm.functions.Function3[int, _reduceIndexed__S, _reduceIndexed__T, _reduceIndexed__S], /) -> _reduceIndexed__S: ...
    _reduceIndexedOrNull__S = typing.TypeVar('_reduceIndexedOrNull__S')  # <S>
    _reduceIndexedOrNull__T = typing.TypeVar('_reduceIndexedOrNull__T')  # <T>
    @staticmethod
    def reduceIndexedOrNull(this_reduceIndexedOrNull: Sequence[_reduceIndexedOrNull__T], operation: kotlin.jvm.functions.Function3[int, _reduceIndexedOrNull__S, _reduceIndexedOrNull__T, _reduceIndexedOrNull__S], /) -> _reduceIndexedOrNull__S: ...
    _reduceOrNull__S = typing.TypeVar('_reduceOrNull__S')  # <S>
    _reduceOrNull__T = typing.TypeVar('_reduceOrNull__T')  # <T>
    @staticmethod
    def reduceOrNull(this_reduceOrNull: Sequence[_reduceOrNull__T], operation: kotlin.jvm.functions.Function2[_reduceOrNull__S, _reduceOrNull__T, _reduceOrNull__S], /) -> _reduceOrNull__S: ...
    _requireNoNulls__T = typing.TypeVar('_requireNoNulls__T')  # <T>
    @staticmethod
    def requireNoNulls(this_requireNoNulls: Sequence[_requireNoNulls__T], /) -> Sequence[_requireNoNulls__T]: ...
    _runningFold__T = typing.TypeVar('_runningFold__T')  # <T>
    _runningFold__R = typing.TypeVar('_runningFold__R')  # <R>
    @staticmethod
    def runningFold(this_runningFold: Sequence[_runningFold__T], initial: _runningFold__R, operation: kotlin.jvm.functions.Function2[_runningFold__R, _runningFold__T, _runningFold__R], /) -> Sequence[_runningFold__R]: ...
    _runningFoldIndexed__T = typing.TypeVar('_runningFoldIndexed__T')  # <T>
    _runningFoldIndexed__R = typing.TypeVar('_runningFoldIndexed__R')  # <R>
    @staticmethod
    def runningFoldIndexed(this_runningFoldIndexed: Sequence[_runningFoldIndexed__T], initial: _runningFoldIndexed__R, operation: kotlin.jvm.functions.Function3[int, _runningFoldIndexed__R, _runningFoldIndexed__T, _runningFoldIndexed__R], /) -> Sequence[_runningFoldIndexed__R]: ...
    _runningReduce__S = typing.TypeVar('_runningReduce__S')  # <S>
    _runningReduce__T = typing.TypeVar('_runningReduce__T')  # <T>
    @staticmethod
    def runningReduce(this_runningReduce: Sequence[_runningReduce__T], operation: kotlin.jvm.functions.Function2[_runningReduce__S, _runningReduce__T, _runningReduce__S], /) -> Sequence[_runningReduce__S]: ...
    _runningReduceIndexed__S = typing.TypeVar('_runningReduceIndexed__S')  # <S>
    _runningReduceIndexed__T = typing.TypeVar('_runningReduceIndexed__T')  # <T>
    @staticmethod
    def runningReduceIndexed(this_runningReduceIndexed: Sequence[_runningReduceIndexed__T], operation: kotlin.jvm.functions.Function3[int, _runningReduceIndexed__S, _runningReduceIndexed__T, _runningReduceIndexed__S], /) -> Sequence[_runningReduceIndexed__S]: ...
    _scan__T = typing.TypeVar('_scan__T')  # <T>
    _scan__R = typing.TypeVar('_scan__R')  # <R>
    @staticmethod
    def scan(this_scan: Sequence[_scan__T], initial: _scan__R, operation: kotlin.jvm.functions.Function2[_scan__R, _scan__T, _scan__R], /) -> Sequence[_scan__R]: ...
    _scanIndexed__T = typing.TypeVar('_scanIndexed__T')  # <T>
    _scanIndexed__R = typing.TypeVar('_scanIndexed__R')  # <R>
    @staticmethod
    def scanIndexed(this_scanIndexed: Sequence[_scanIndexed__T], initial: _scanIndexed__R, operation: kotlin.jvm.functions.Function3[int, _scanIndexed__R, _scanIndexed__T, _scanIndexed__R], /) -> Sequence[_scanIndexed__R]: ...
    _single_0__T = typing.TypeVar('_single_0__T')  # <T>
    _single_1__T = typing.TypeVar('_single_1__T')  # <T>
    @typing.overload
    @staticmethod
    def single(this_single: Sequence[_single_0__T], /) -> _single_0__T: ...
    @typing.overload
    @staticmethod
    def single(this_single: Sequence[_single_1__T], predicate: kotlin.jvm.functions.Function1[_single_1__T, java.lang.Boolean], /) -> _single_1__T: ...
    _singleOrNull_0__T = typing.TypeVar('_singleOrNull_0__T')  # <T>
    _singleOrNull_1__T = typing.TypeVar('_singleOrNull_1__T')  # <T>
    @typing.overload
    @staticmethod
    def singleOrNull(this_singleOrNull: Sequence[_singleOrNull_0__T], /) -> _singleOrNull_0__T: ...
    @typing.overload
    @staticmethod
    def singleOrNull(this_singleOrNull: Sequence[_singleOrNull_1__T], predicate: kotlin.jvm.functions.Function1[_singleOrNull_1__T, java.lang.Boolean], /) -> _singleOrNull_1__T: ...
    _sorted__T = typing.TypeVar('_sorted__T')  # <T>
    @staticmethod
    def sorted(this_sorted: Sequence[_sorted__T], /) -> Sequence[_sorted__T]: ...
    _sortedBy__T = typing.TypeVar('_sortedBy__T')  # <T>
    @staticmethod
    def sortedBy(this_sortedBy: Sequence[_sortedBy__T], selector: kotlin.jvm.functions.Function1[_sortedBy__T, java.lang.Object], /) -> Sequence[_sortedBy__T]: ...
    _sortedByDescending__T = typing.TypeVar('_sortedByDescending__T')  # <T>
    @staticmethod
    def sortedByDescending(this_sortedByDescending: Sequence[_sortedByDescending__T], selector: kotlin.jvm.functions.Function1[_sortedByDescending__T, java.lang.Object], /) -> Sequence[_sortedByDescending__T]: ...
    _sortedDescending__T = typing.TypeVar('_sortedDescending__T')  # <T>
    @staticmethod
    def sortedDescending(this_sortedDescending: Sequence[_sortedDescending__T], /) -> Sequence[_sortedDescending__T]: ...
    _sortedWith__T = typing.TypeVar('_sortedWith__T')  # <T>
    @staticmethod
    def sortedWith(this_sortedWith: Sequence[_sortedWith__T], comparator: java.util.Comparator[_sortedWith__T], /) -> Sequence[_sortedWith__T]: ...
    _sumBy__T = typing.TypeVar('_sumBy__T')  # <T>
    @staticmethod
    def sumBy(this_sumBy: Sequence[_sumBy__T], selector: kotlin.jvm.functions.Function1[_sumBy__T, java.lang.Integer], /) -> int: ...
    _sumByDouble__T = typing.TypeVar('_sumByDouble__T')  # <T>
    @staticmethod
    def sumByDouble(this_sumByDouble: Sequence[_sumByDouble__T], selector: kotlin.jvm.functions.Function1[_sumByDouble__T, java.lang.Double], /) -> float: ...
    @staticmethod
    def sumOfByte(this_sum: Sequence[java.lang.Byte], /) -> int: ...
    @staticmethod
    def sumOfDouble(this_sum: Sequence[java.lang.Double], /) -> float: ...
    @staticmethod
    def sumOfFloat(this_sum: Sequence[java.lang.Float], /) -> float: ...
    @staticmethod
    def sumOfInt(this_sum: Sequence[java.lang.Integer], /) -> int: ...
    @staticmethod
    def sumOfLong(this_sum: Sequence[java.lang.Long], /) -> int: ...
    @staticmethod
    def sumOfShort(this_sum: Sequence[java.lang.Short], /) -> int: ...
    _take__T = typing.TypeVar('_take__T')  # <T>
    @staticmethod
    def take(this_take: Sequence[_take__T], n: int | java.jint | java.lang.Integer, /) -> Sequence[_take__T]: ...
    _takeWhile__T = typing.TypeVar('_takeWhile__T')  # <T>
    @staticmethod
    def takeWhile(this_takeWhile: Sequence[_takeWhile__T], predicate: kotlin.jvm.functions.Function1[_takeWhile__T, java.lang.Boolean], /) -> Sequence[_takeWhile__T]: ...
    _toCollection__C = typing.TypeVar('_toCollection__C')  # <C>
    @staticmethod
    def toCollection(this_toCollection: Sequence[java.lang.Object], destination: _toCollection__C, /) -> _toCollection__C: ...
    _toHashSet__T = typing.TypeVar('_toHashSet__T')  # <T>
    @staticmethod
    def toHashSet(this_toHashSet: Sequence[_toHashSet__T], /) -> java.util.HashSet[_toHashSet__T]: ...
    _toList__T = typing.TypeVar('_toList__T')  # <T>
    @staticmethod
    def toList(this_toList: Sequence[_toList__T], /) -> java.util.List[_toList__T]: ...
    _toMutableList__T = typing.TypeVar('_toMutableList__T')  # <T>
    @staticmethod
    def toMutableList(this_toMutableList: Sequence[_toMutableList__T], /) -> java.util.List[_toMutableList__T]: ...
    _toMutableSet__T = typing.TypeVar('_toMutableSet__T')  # <T>
    @staticmethod
    def toMutableSet(this_toMutableSet: Sequence[_toMutableSet__T], /) -> java.util.Set[_toMutableSet__T]: ...
    _toSet__T = typing.TypeVar('_toSet__T')  # <T>
    @staticmethod
    def toSet(this_toSet: Sequence[_toSet__T], /) -> java.util.Set[_toSet__T]: ...
    _windowed_0__T = typing.TypeVar('_windowed_0__T')  # <T>
    _windowed_1__T = typing.TypeVar('_windowed_1__T')  # <T>
    _windowed_1__R = typing.TypeVar('_windowed_1__R')  # <R>
    @typing.overload
    @staticmethod
    def windowed(this_windowed: Sequence[_windowed_0__T], size: int | java.jint | java.lang.Integer, step: int | java.jint | java.lang.Integer, partialWindows: bool | java.jboolean | java.lang.Boolean, /) -> Sequence[java.util.List[_windowed_0__T]]: ...
    @typing.overload
    @staticmethod
    def windowed(this_windowed: Sequence[_windowed_1__T], size: int | java.jint | java.lang.Integer, step: int | java.jint | java.lang.Integer, partialWindows: bool | java.jboolean | java.lang.Boolean, transform: kotlin.jvm.functions.Function1[java.util.List[_windowed_1__T], _windowed_1__R], /) -> Sequence[_windowed_1__R]: ...
    _withIndex__T = typing.TypeVar('_withIndex__T')  # <T>
    @staticmethod
    def withIndex(this_withIndex: Sequence[_withIndex__T], /) -> Sequence[kotlin.collections.IndexedValue[_withIndex__T]]: ...
    _zip_0__T = typing.TypeVar('_zip_0__T')  # <T>
    _zip_0__R = typing.TypeVar('_zip_0__R')  # <R>
    _zip_1__T = typing.TypeVar('_zip_1__T')  # <T>
    _zip_1__R = typing.TypeVar('_zip_1__R')  # <R>
    _zip_1__V = typing.TypeVar('_zip_1__V')  # <V>
    @typing.overload
    @staticmethod
    def zip(this_zip: Sequence[_zip_0__T], other: Sequence[_zip_0__R], /) -> Sequence[kotlin.Pair[_zip_0__T, _zip_0__R]]: ...
    @typing.overload
    @staticmethod
    def zip(this_zip: Sequence[_zip_1__T], other: Sequence[_zip_1__R], transform: kotlin.jvm.functions.Function2[_zip_1__T, _zip_1__R, _zip_1__V], /) -> Sequence[_zip_1__V]: ...
    _zipWithNext_0__T = typing.TypeVar('_zipWithNext_0__T')  # <T>
    _zipWithNext_1__T = typing.TypeVar('_zipWithNext_1__T')  # <T>
    _zipWithNext_1__R = typing.TypeVar('_zipWithNext_1__R')  # <R>
    @typing.overload
    @staticmethod
    def zipWithNext(this_zipWithNext: Sequence[_zipWithNext_0__T], /) -> Sequence[kotlin.Pair[_zipWithNext_0__T, _zipWithNext_0__T]]: ...
    @typing.overload
    @staticmethod
    def zipWithNext(this_zipWithNext: Sequence[_zipWithNext_1__T], transform: kotlin.jvm.functions.Function2[_zipWithNext_1__T, _zipWithNext_1__T, _zipWithNext_1__R], /) -> Sequence[_zipWithNext_1__R]: ...

_SubSequence__T = typing.TypeVar('_SubSequence__T')  # <T>
class SubSequence(Sequence[_SubSequence__T], DropTakeSequence[_SubSequence__T], typing.Generic[_SubSequence__T]):
    def __init__(self, sequence: Sequence[_SubSequence__T], startIndex: int | java.jint | java.lang.Integer, endIndex: int | java.jint | java.lang.Integer, /) -> None: ...
    def drop(self, n: int | java.jint | java.lang.Integer, /) -> Sequence[_SubSequence__T]: ...
    def iterator(self) -> java.util.Iterator[_SubSequence__T]: ...
    def take(self, n: int | java.jint | java.lang.Integer, /) -> Sequence[_SubSequence__T]: ...

_TakeSequence__T = typing.TypeVar('_TakeSequence__T')  # <T>
class TakeSequence(Sequence[_TakeSequence__T], DropTakeSequence[_TakeSequence__T], typing.Generic[_TakeSequence__T]):
    def __init__(self, sequence: Sequence[_TakeSequence__T], count: int | java.jint | java.lang.Integer, /) -> None: ...
    def drop(self, n: int | java.jint | java.lang.Integer, /) -> Sequence[_TakeSequence__T]: ...
    def iterator(self) -> java.util.Iterator[_TakeSequence__T]: ...
    def take(self, n: int | java.jint | java.lang.Integer, /) -> Sequence[_TakeSequence__T]: ...

_TakeWhileSequence__T = typing.TypeVar('_TakeWhileSequence__T')  # <T>
class TakeWhileSequence(Sequence[_TakeWhileSequence__T], typing.Generic[_TakeWhileSequence__T]):
    def __init__(self, sequence: Sequence[_TakeWhileSequence__T], predicate: kotlin.jvm.functions.Function1[_TakeWhileSequence__T, java.lang.Boolean], /) -> None: ...
    def iterator(self) -> java.util.Iterator[_TakeWhileSequence__T]: ...

_TransformingIndexedSequence__T = typing.TypeVar('_TransformingIndexedSequence__T')  # <T>
_TransformingIndexedSequence__R = typing.TypeVar('_TransformingIndexedSequence__R')  # <R>
class TransformingIndexedSequence(Sequence[_TransformingIndexedSequence__R], typing.Generic[_TransformingIndexedSequence__T, _TransformingIndexedSequence__R]):
    def __init__(self, sequence: Sequence[_TransformingIndexedSequence__T], transformer: kotlin.jvm.functions.Function2[int, _TransformingIndexedSequence__T, _TransformingIndexedSequence__R], /) -> None: ...
    def iterator(self) -> java.util.Iterator[_TransformingIndexedSequence__R]: ...

_TransformingSequence__T = typing.TypeVar('_TransformingSequence__T')  # <T>
_TransformingSequence__R = typing.TypeVar('_TransformingSequence__R')  # <R>
class TransformingSequence(Sequence[_TransformingSequence__R], typing.Generic[_TransformingSequence__T, _TransformingSequence__R]):
    def __init__(self, sequence: Sequence[_TransformingSequence__T], transformer: kotlin.jvm.functions.Function1[_TransformingSequence__T, _TransformingSequence__R], /) -> None: ...
    _flatten$kotlin_stdlib__E = typing.TypeVar('_flatten$kotlin_stdlib__E')  # <E>
    def flatten$kotlin_stdlib(self, iterator: kotlin.jvm.functions.Function1[_TransformingSequence__R, java.util.Iterator[_flatten.kotlin_stdlib__E]], /) -> Sequence[_flatten.kotlin_stdlib__E]: ...
    def iterator(self) -> java.util.Iterator[_TransformingSequence__R]: ...

class USequencesKt(USequencesKt___USequencesKt): ...

class USequencesKt___USequencesKt(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def sumOfUByte(this_sum: Sequence[kotlin.UByte], /) -> int: ...
    @staticmethod
    def sumOfUInt(this_sum: Sequence[kotlin.UInt], /) -> int: ...
    @staticmethod
    def sumOfULong(this_sum: Sequence[kotlin.ULong], /) -> int: ...
    @staticmethod
    def sumOfUShort(this_sum: Sequence[kotlin.UShort], /) -> int: ...
