import typing

import java
import java.lang
import kotlin
import kotlin.coroutines.experimental
import kotlin.jvm.internal

class CoroutineImpl(kotlin.jvm.internal.Lambda[java.lang.Object], kotlin.coroutines.experimental.Continuation[java.lang.Object]):
    label: int = ...
    completion: kotlin.coroutines.experimental.Continuation[java.lang.Object] = ...
    def __init__(self, arity: int | java.jint | java.lang.Integer, completion: kotlin.coroutines.experimental.Continuation[java.lang.Object], /) -> None: ...
    @typing.overload
    def create(self, completion: kotlin.coroutines.experimental.Continuation[java.lang.Object], /) -> kotlin.coroutines.experimental.Continuation[kotlin.Unit]: ...
    @typing.overload
    def create(self, value: java.lang.Object | int | bool | float | str, completion: kotlin.coroutines.experimental.Continuation[java.lang.Object], /) -> kotlin.coroutines.experimental.Continuation[kotlin.Unit]: ...
    def doResume(self, arg1: java.lang.Object | int | bool | float | str, arg2: java.lang.Throwable, /) -> java.lang.Object: ...
    def getContext(self) -> kotlin.coroutines.experimental.CoroutineContext: ...
    def getFacade(self) -> kotlin.coroutines.experimental.Continuation[java.lang.Object]: ...
    def resume(self, value: java.lang.Object | int | bool | float | str, /) -> None: ...
    def resumeWithException(self, exception: java.lang.Throwable, /) -> None: ...

class CoroutineIntrinsics(java.lang.Object):
    _interceptContinuationIfNeeded__T = typing.TypeVar('_interceptContinuationIfNeeded__T')  # <T>
    @staticmethod
    def interceptContinuationIfNeeded(context: kotlin.coroutines.experimental.CoroutineContext, continuation: kotlin.coroutines.experimental.Continuation[_interceptContinuationIfNeeded__T], /) -> kotlin.coroutines.experimental.Continuation[_interceptContinuationIfNeeded__T]: ...
    _normalizeContinuation__T = typing.TypeVar('_normalizeContinuation__T')  # <T>
    @staticmethod
    def normalizeContinuation(continuation: kotlin.coroutines.experimental.Continuation[_normalizeContinuation__T], /) -> kotlin.coroutines.experimental.Continuation[_normalizeContinuation__T]: ...
