import android.content
import android.content.res
import android.graphics
import android.graphics.drawable
import android.text
import android.util
import android.view
import android.view.accessibility
import android.widget
import androidx.appcompat.widget
import androidx.core.graphics.drawable
import com
import com.google.android.material.animation
import com.google.android.material.internal
import com.google.android.material.resources
import com.google.android.material.shape
import java
import java.chaquopy
import java.lang
import java.util
import typing



class Chip(androidx.appcompat.widget.AppCompatCheckBox, com.google.android.material.chip.ChipDrawable.Delegate, com.google.android.material.shape.Shapeable, com.google.android.material.internal.MaterialCheckable[Chip]):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def dispatchHoverEvent(self, event: android.view.MotionEvent, /) -> bool: ...
    def dispatchKeyEvent(self, event: android.view.KeyEvent, /) -> bool: ...
    def drawableStateChanged(self) -> None: ...
    def ensureAccessibleTouchTarget(self, minTargetPx: int | java.jint | java.lang.Integer, /) -> bool: ...
    def getAccessibilityClassName(self) -> java.lang.CharSequence: ...
    def getBackgroundDrawable(self) -> android.graphics.drawable.Drawable: ...
    def getCheckedIcon(self) -> android.graphics.drawable.Drawable: ...
    def getCheckedIconTint(self) -> android.content.res.ColorStateList: ...
    def getChipBackgroundColor(self) -> android.content.res.ColorStateList: ...
    def getChipCornerRadius(self) -> float: ...
    def getChipDrawable(self) -> android.graphics.drawable.Drawable: ...
    def getChipEndPadding(self) -> float: ...
    def getChipIcon(self) -> android.graphics.drawable.Drawable: ...
    def getChipIconSize(self) -> float: ...
    def getChipIconTint(self) -> android.content.res.ColorStateList: ...
    def getChipMinHeight(self) -> float: ...
    def getChipStartPadding(self) -> float: ...
    def getChipStrokeColor(self) -> android.content.res.ColorStateList: ...
    def getChipStrokeWidth(self) -> float: ...
    def getChipText(self) -> java.lang.CharSequence: ...
    def getCloseIcon(self) -> android.graphics.drawable.Drawable: ...
    def getCloseIconContentDescription(self) -> java.lang.CharSequence: ...
    def getCloseIconEndPadding(self) -> float: ...
    def getCloseIconSize(self) -> float: ...
    def getCloseIconStartPadding(self) -> float: ...
    def getCloseIconTint(self) -> android.content.res.ColorStateList: ...
    def getEllipsize(self) -> android.text.TextUtils.TruncateAt: ...
    def getFocusedRect(self, r: android.graphics.Rect, /) -> None: ...
    def getHideMotionSpec(self) -> com.google.android.material.animation.MotionSpec: ...
    def getIconEndPadding(self) -> float: ...
    def getIconStartPadding(self) -> float: ...
    def getRippleColor(self) -> android.content.res.ColorStateList: ...
    def getShapeAppearanceModel(self) -> com.google.android.material.shape.ShapeAppearanceModel: ...
    def getShowMotionSpec(self) -> com.google.android.material.animation.MotionSpec: ...
    def getTextEndPadding(self) -> float: ...
    def getTextStartPadding(self) -> float: ...
    def isCheckable(self) -> bool: ...
    def isCheckedIconEnabled(self) -> bool: ...
    def isCheckedIconVisible(self) -> bool: ...
    def isChipIconEnabled(self) -> bool: ...
    def isChipIconVisible(self) -> bool: ...
    def isCloseIconEnabled(self) -> bool: ...
    def isCloseIconVisible(self) -> bool: ...
    def onAttachedToWindow(self) -> None: ...
    def onChipDrawableSizeChange(self) -> None: ...
    def onCreateDrawableState(self, extraSpace: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJInt: ...
    def onFocusChanged(self, focused: bool | java.jboolean | java.lang.Boolean, direction: int | java.jint | java.lang.Integer, previouslyFocusedRect: android.graphics.Rect, /) -> None: ...
    def onHoverEvent(self, event: android.view.MotionEvent, /) -> bool: ...
    def onInitializeAccessibilityNodeInfo(self, info: android.view.accessibility.AccessibilityNodeInfo, /) -> None: ...
    def onResolvePointerIcon(self, event: android.view.MotionEvent, pointerIndex: int | java.jint | java.lang.Integer, /) -> android.view.PointerIcon: ...
    def onRtlPropertiesChanged(self, layoutDirection: int | java.jint | java.lang.Integer, /) -> None: ...
    def onTouchEvent(self, event: android.view.MotionEvent, /) -> bool: ...
    def performCloseIconClick(self) -> bool: ...
    def setAccessibilityClassName(self, className: java.lang.CharSequence, /) -> None: ...
    def setBackground(self, background: android.graphics.drawable.Drawable, /) -> None: ...
    def setBackgroundColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBackgroundDrawable(self, background: android.graphics.drawable.Drawable, /) -> None: ...
    def setBackgroundResource(self, resid: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBackgroundTintList(self, tint: android.content.res.ColorStateList, /) -> None: ...
    def setBackgroundTintMode(self, tintMode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def setCheckable(self, checkable: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setCheckableResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChecked(self, checked: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setCheckedIcon(self, checkedIcon: android.graphics.drawable.Drawable, /) -> None: ...
    def setCheckedIconEnabled(self, checkedIconEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setCheckedIconEnabledResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCheckedIconResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCheckedIconTint(self, checkedIconTint: android.content.res.ColorStateList, /) -> None: ...
    def setCheckedIconTintResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCheckedIconVisible(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCheckedIconVisible(self, checkedIconVisible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setChipBackgroundColor(self, chipBackgroundColor: android.content.res.ColorStateList, /) -> None: ...
    def setChipBackgroundColorResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipCornerRadius(self, chipCornerRadius: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setChipCornerRadiusResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipDrawable(self, drawable: ChipDrawable, /) -> None: ...
    def setChipEndPadding(self, chipEndPadding: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setChipEndPaddingResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipIcon(self, chipIcon: android.graphics.drawable.Drawable, /) -> None: ...
    def setChipIconEnabled(self, chipIconEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setChipIconEnabledResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipIconResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipIconSize(self, chipIconSize: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setChipIconSizeResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipIconTint(self, chipIconTint: android.content.res.ColorStateList, /) -> None: ...
    def setChipIconTintResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setChipIconVisible(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setChipIconVisible(self, chipIconVisible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setChipMinHeight(self, minHeight: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setChipMinHeightResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipStartPadding(self, chipStartPadding: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setChipStartPaddingResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipStrokeColor(self, chipStrokeColor: android.content.res.ColorStateList, /) -> None: ...
    def setChipStrokeColorResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipStrokeWidth(self, chipStrokeWidth: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setChipStrokeWidthResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipText(self, chipText: java.lang.CharSequence, /) -> None: ...
    def setChipTextResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCloseIcon(self, closeIcon: android.graphics.drawable.Drawable, /) -> None: ...
    def setCloseIconContentDescription(self, closeIconContentDescription: java.lang.CharSequence, /) -> None: ...
    def setCloseIconEnabled(self, closeIconEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setCloseIconEnabledResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCloseIconEndPadding(self, closeIconEndPadding: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setCloseIconEndPaddingResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCloseIconResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCloseIconSize(self, closeIconSize: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setCloseIconSizeResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCloseIconStartPadding(self, closeIconStartPadding: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setCloseIconStartPaddingResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCloseIconTint(self, closeIconTint: android.content.res.ColorStateList, /) -> None: ...
    def setCloseIconTintResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCloseIconVisible(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCloseIconVisible(self, closeIconVisible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setCompoundDrawables(self, left: android.graphics.drawable.Drawable, top: android.graphics.drawable.Drawable, right: android.graphics.drawable.Drawable, bottom: android.graphics.drawable.Drawable, /) -> None: ...
    def setCompoundDrawablesRelative(self, start: android.graphics.drawable.Drawable, top: android.graphics.drawable.Drawable, end: android.graphics.drawable.Drawable, bottom: android.graphics.drawable.Drawable, /) -> None: ...
    @typing.overload
    def setCompoundDrawablesRelativeWithIntrinsicBounds(self, start: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, end: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCompoundDrawablesRelativeWithIntrinsicBounds(self, start: android.graphics.drawable.Drawable, top: android.graphics.drawable.Drawable, end: android.graphics.drawable.Drawable, bottom: android.graphics.drawable.Drawable, /) -> None: ...
    @typing.overload
    def setCompoundDrawablesWithIntrinsicBounds(self, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCompoundDrawablesWithIntrinsicBounds(self, left: android.graphics.drawable.Drawable, top: android.graphics.drawable.Drawable, right: android.graphics.drawable.Drawable, bottom: android.graphics.drawable.Drawable, /) -> None: ...
    def setElevation(self, elevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setEllipsize(self, where: android.text.TextUtils.TruncateAt, /) -> None: ...
    def setEnsureMinTouchTargetSize(self, flag: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setGravity(self, gravity: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHideMotionSpec(self, hideMotionSpec: com.google.android.material.animation.MotionSpec, /) -> None: ...
    def setHideMotionSpecResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setIconEndPadding(self, iconEndPadding: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setIconEndPaddingResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setIconStartPadding(self, iconStartPadding: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setIconStartPaddingResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setInternalOnCheckedChangeListener(self, listener: com.google.android.material.internal.MaterialCheckable.OnCheckedChangeListener[Chip], /) -> None: ...
    def setLayoutDirection(self, layoutDirection: int | java.jint | java.lang.Integer, /) -> None: ...
    def setLines(self, lines: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMaxLines(self, maxLines: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMaxWidth(self, maxWidth: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMinLines(self, minLines: int | java.jint | java.lang.Integer, /) -> None: ...
    def setOnCheckedChangeListener(self, listener: android.widget.CompoundButton.OnCheckedChangeListener, /) -> None: ...
    def setOnCloseIconClickListener(self, listener: android.view.View.OnClickListener, /) -> None: ...
    def setRippleColor(self, rippleColor: android.content.res.ColorStateList, /) -> None: ...
    def setRippleColorResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setShapeAppearanceModel(self, shapeAppearanceModel: com.google.android.material.shape.ShapeAppearanceModel, /) -> None: ...
    def setShowMotionSpec(self, showMotionSpec: com.google.android.material.animation.MotionSpec, /) -> None: ...
    def setShowMotionSpecResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setSingleLine(self, singleLine: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setText(self, text: java.lang.CharSequence, type: android.widget.TextView.BufferType, /) -> None: ...
    @typing.overload
    def setTextAppearance(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setTextAppearance(self, textAppearance: com.google.android.material.resources.TextAppearance, /) -> None: ...
    @typing.overload
    def setTextAppearance(self, context: android.content.Context, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTextAppearanceResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTextEndPadding(self, textEndPadding: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTextEndPaddingResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTextSize(self, unit: int | java.jint | java.lang.Integer, size: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTextStartPadding(self, textStartPadding: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTextStartPaddingResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def shouldEnsureMinTouchTargetSize(self) -> bool: ...

class ChipDrawable(com.google.android.material.shape.MaterialShapeDrawable, androidx.core.graphics.drawable.TintAwareDrawable, android.graphics.drawable.Drawable.Callback, com.google.android.material.internal.TextDrawableHelper.TextDrawableDelegate):
    @staticmethod
    def createFromAttributes(context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, /) -> ChipDrawable: ...
    @staticmethod
    def createFromResource(context: android.content.Context, id: int | java.jint | java.lang.Integer, /) -> ChipDrawable: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getAlpha(self) -> int: ...
    def getCheckedIcon(self) -> android.graphics.drawable.Drawable: ...
    def getCheckedIconTint(self) -> android.content.res.ColorStateList: ...
    def getChipBackgroundColor(self) -> android.content.res.ColorStateList: ...
    def getChipCornerRadius(self) -> float: ...
    def getChipEndPadding(self) -> float: ...
    def getChipIcon(self) -> android.graphics.drawable.Drawable: ...
    def getChipIconSize(self) -> float: ...
    def getChipIconTint(self) -> android.content.res.ColorStateList: ...
    def getChipMinHeight(self) -> float: ...
    def getChipStartPadding(self) -> float: ...
    def getChipStrokeColor(self) -> android.content.res.ColorStateList: ...
    def getChipStrokeWidth(self) -> float: ...
    def getChipTouchBounds(self, bounds: android.graphics.RectF, /) -> None: ...
    def getCloseIcon(self) -> android.graphics.drawable.Drawable: ...
    def getCloseIconContentDescription(self) -> java.lang.CharSequence: ...
    def getCloseIconEndPadding(self) -> float: ...
    def getCloseIconSize(self) -> float: ...
    def getCloseIconStartPadding(self) -> float: ...
    def getCloseIconState(self) -> java.chaquopy.JavaArrayJInt: ...
    def getCloseIconTint(self) -> android.content.res.ColorStateList: ...
    def getCloseIconTouchBounds(self, bounds: android.graphics.RectF, /) -> None: ...
    def getColorFilter(self) -> android.graphics.ColorFilter: ...
    def getEllipsize(self) -> android.text.TextUtils.TruncateAt: ...
    def getHideMotionSpec(self) -> com.google.android.material.animation.MotionSpec: ...
    def getIconEndPadding(self) -> float: ...
    def getIconStartPadding(self) -> float: ...
    def getIntrinsicHeight(self) -> int: ...
    def getIntrinsicWidth(self) -> int: ...
    def getMaxWidth(self) -> int: ...
    def getOpacity(self) -> int: ...
    def getOutline(self, outline: android.graphics.Outline, /) -> None: ...
    def getRippleColor(self) -> android.content.res.ColorStateList: ...
    def getShowMotionSpec(self) -> com.google.android.material.animation.MotionSpec: ...
    def getText(self) -> java.lang.CharSequence: ...
    def getTextAppearance(self) -> com.google.android.material.resources.TextAppearance: ...
    def getTextEndPadding(self) -> float: ...
    def getTextStartPadding(self) -> float: ...
    def getUseCompatRipple(self) -> bool: ...
    def invalidateDrawable(self, who: android.graphics.drawable.Drawable, /) -> None: ...
    def isCheckable(self) -> bool: ...
    def isCheckedIconEnabled(self) -> bool: ...
    def isCheckedIconVisible(self) -> bool: ...
    def isChipIconEnabled(self) -> bool: ...
    def isChipIconVisible(self) -> bool: ...
    def isCloseIconEnabled(self) -> bool: ...
    def isCloseIconStateful(self) -> bool: ...
    def isCloseIconVisible(self) -> bool: ...
    def isStateful(self) -> bool: ...
    def onLayoutDirectionChanged(self, layoutDirection: int | java.jint | java.lang.Integer, /) -> bool: ...
    def onLevelChange(self, level: int | java.jint | java.lang.Integer, /) -> bool: ...
    def onSizeChange(self) -> None: ...
    def onStateChange(self, state: java.chaquopy.JavaArrayJInt, /) -> bool: ...
    def onTextSizeChange(self) -> None: ...
    def scheduleDrawable(self, who: android.graphics.drawable.Drawable, what: java.lang.Runnable, when: int | java.jlong | java.lang.Long, /) -> None: ...
    def setAlpha(self, alpha: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCheckable(self, checkable: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setCheckableResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCheckedIcon(self, checkedIcon: android.graphics.drawable.Drawable, /) -> None: ...
    def setCheckedIconEnabled(self, checkedIconEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setCheckedIconEnabledResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCheckedIconResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCheckedIconTint(self, checkedIconTint: android.content.res.ColorStateList, /) -> None: ...
    def setCheckedIconTintResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCheckedIconVisible(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCheckedIconVisible(self, checkedIconVisible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setChipBackgroundColor(self, chipBackgroundColor: android.content.res.ColorStateList, /) -> None: ...
    def setChipBackgroundColorResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipCornerRadius(self, chipCornerRadius: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setChipCornerRadiusResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipEndPadding(self, chipEndPadding: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setChipEndPaddingResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipIcon(self, chipIcon: android.graphics.drawable.Drawable, /) -> None: ...
    def setChipIconEnabled(self, chipIconEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setChipIconEnabledResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipIconResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipIconSize(self, chipIconSize: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setChipIconSizeResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipIconTint(self, chipIconTint: android.content.res.ColorStateList, /) -> None: ...
    def setChipIconTintResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setChipIconVisible(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setChipIconVisible(self, chipIconVisible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setChipMinHeight(self, chipMinHeight: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setChipMinHeightResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipStartPadding(self, chipStartPadding: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setChipStartPaddingResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipStrokeColor(self, chipStrokeColor: android.content.res.ColorStateList, /) -> None: ...
    def setChipStrokeColorResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipStrokeWidth(self, chipStrokeWidth: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setChipStrokeWidthResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCloseIcon(self, closeIcon: android.graphics.drawable.Drawable, /) -> None: ...
    def setCloseIconContentDescription(self, closeIconContentDescription: java.lang.CharSequence, /) -> None: ...
    def setCloseIconEnabled(self, closeIconEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setCloseIconEnabledResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCloseIconEndPadding(self, closeIconEndPadding: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setCloseIconEndPaddingResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCloseIconResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCloseIconSize(self, closeIconSize: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setCloseIconSizeResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCloseIconStartPadding(self, closeIconStartPadding: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setCloseIconStartPaddingResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCloseIconState(self, stateSet: java.chaquopy.JavaArrayJInt, /) -> bool: ...
    def setCloseIconTint(self, closeIconTint: android.content.res.ColorStateList, /) -> None: ...
    def setCloseIconTintResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCloseIconVisible(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCloseIconVisible(self, closeIconVisible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setColorFilter(self, colorFilter: android.graphics.ColorFilter, /) -> None: ...
    def setDelegate(self, delegate: ChipDrawable.Delegate, /) -> None: ...
    def setEllipsize(self, truncateAt: android.text.TextUtils.TruncateAt, /) -> None: ...
    def setHideMotionSpec(self, hideMotionSpec: com.google.android.material.animation.MotionSpec, /) -> None: ...
    def setHideMotionSpecResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setIconEndPadding(self, iconEndPadding: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setIconEndPaddingResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setIconStartPadding(self, iconStartPadding: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setIconStartPaddingResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMaxWidth(self, maxWidth: int | java.jint | java.lang.Integer, /) -> None: ...
    def setRippleColor(self, rippleColor: android.content.res.ColorStateList, /) -> None: ...
    def setRippleColorResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setShowMotionSpec(self, showMotionSpec: com.google.android.material.animation.MotionSpec, /) -> None: ...
    def setShowMotionSpecResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setText(self, text: java.lang.CharSequence, /) -> None: ...
    def setTextAppearance(self, textAppearance: com.google.android.material.resources.TextAppearance, /) -> None: ...
    def setTextAppearanceResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setTextColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setTextColor(self, color: android.content.res.ColorStateList, /) -> None: ...
    def setTextEndPadding(self, textEndPadding: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTextEndPaddingResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTextResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTextSize(self, size: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTextStartPadding(self, textStartPadding: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTextStartPaddingResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTintList(self, tint: android.content.res.ColorStateList, /) -> None: ...
    def setTintMode(self, tintMode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def setUseCompatRipple(self, useCompatRipple: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setVisible(self, visible: bool | java.jboolean | java.lang.Boolean, restart: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def unscheduleDrawable(self, who: android.graphics.drawable.Drawable, what: java.lang.Runnable, /) -> None: ...

    class Delegate(java.lang.Object):
        def onChipDrawableSizeChange(self) -> None: ...

class ChipGroup(com.google.android.material.internal.FlowLayout):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def check(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def checkLayoutParams(self, p: android.view.ViewGroup.LayoutParams, /) -> bool: ...
    def clearCheck(self) -> None: ...
    def generateDefaultLayoutParams(self) -> android.view.ViewGroup.LayoutParams: ...
    @typing.overload
    def generateLayoutParams(self, attrs: android.util.AttributeSet, /) -> android.view.ViewGroup.LayoutParams: ...
    @typing.overload
    def generateLayoutParams(self, lp: android.view.ViewGroup.LayoutParams, /) -> android.view.ViewGroup.LayoutParams: ...
    def getCheckedChipId(self) -> int: ...
    def getCheckedChipIds(self) -> java.util.List[java.lang.Integer]: ...
    def getChipSpacingHorizontal(self) -> int: ...
    def getChipSpacingVertical(self) -> int: ...
    def isSelectionRequired(self) -> bool: ...
    def isSingleLine(self) -> bool: ...
    def isSingleSelection(self) -> bool: ...
    def onFinishInflate(self) -> None: ...
    def onInitializeAccessibilityNodeInfo(self, info: android.view.accessibility.AccessibilityNodeInfo, /) -> None: ...
    def setChipSpacing(self, chipSpacing: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipSpacingHorizontal(self, chipSpacingHorizontal: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipSpacingHorizontalResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipSpacingResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipSpacingVertical(self, chipSpacingVertical: int | java.jint | java.lang.Integer, /) -> None: ...
    def setChipSpacingVerticalResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDividerDrawableHorizontal(self, divider: android.graphics.drawable.Drawable, /) -> None: ...
    def setDividerDrawableVertical(self, divider: android.graphics.drawable.Drawable, /) -> None: ...
    def setFlexWrap(self, flexWrap: int | java.jint | java.lang.Integer, /) -> None: ...
    def setOnCheckedChangeListener(self, listener: ChipGroup.OnCheckedChangeListener, /) -> None: ...
    def setOnCheckedStateChangeListener(self, listener: ChipGroup.OnCheckedStateChangeListener, /) -> None: ...
    def setOnHierarchyChangeListener(self, listener: android.view.ViewGroup.OnHierarchyChangeListener, /) -> None: ...
    def setSelectionRequired(self, selectionRequired: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setShowDividerHorizontal(self, dividerMode: int | java.jint | java.lang.Integer, /) -> None: ...
    def setShowDividerVertical(self, dividerMode: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setSingleLine(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setSingleLine(self, singleLine: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def setSingleSelection(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setSingleSelection(self, singleSelection: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

    class OnCheckedStateChangeListener(java.lang.Object):
        def onCheckedChanged(self, arg1: ChipGroup, arg2: java.util.List[java.lang.Integer], /) -> None: ...

    class LayoutParams(android.view.ViewGroup.MarginLayoutParams):
        @typing.overload
        def __init__(self, source: android.view.ViewGroup.LayoutParams, /) -> None: ...
        @typing.overload
        def __init__(self, source: android.view.ViewGroup.MarginLayoutParams, /) -> None: ...
        @typing.overload
        def __init__(self, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...
        @typing.overload
        def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...

    class OnCheckedChangeListener(java.lang.Object):
        def onCheckedChanged(self, arg1: ChipGroup, arg2: int | java.jint | java.lang.Integer, /) -> None: ...
