import typing

import android.content
import android.graphics
import android.graphics.drawable
import java
import java.lang
import java.lang.annotation

class DrawerArrowDrawable(android.graphics.drawable.Drawable):
    ARROW_DIRECTION_LEFT: typing.ClassVar[int] = ...
    ARROW_DIRECTION_RIGHT: typing.ClassVar[int] = ...
    ARROW_DIRECTION_START: typing.ClassVar[int] = ...
    ARROW_DIRECTION_END: typing.ClassVar[int] = ...
    def __init__(self, context: android.content.Context, /) -> None: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getArrowHeadLength(self) -> float: ...
    def getArrowShaftLength(self) -> float: ...
    def getBarLength(self) -> float: ...
    def getBarThickness(self) -> float: ...
    def getColor(self) -> int: ...
    def getDirection(self) -> int: ...
    def getGapSize(self) -> float: ...
    def getIntrinsicHeight(self) -> int: ...
    def getIntrinsicWidth(self) -> int: ...
    def getOpacity(self) -> int: ...
    def getPaint(self) -> android.graphics.Paint: ...
    def getProgress(self) -> float: ...
    def isSpinEnabled(self) -> bool: ...
    def setAlpha(self, alpha: int | java.jint | java.lang.Integer, /) -> None: ...
    def setArrowHeadLength(self, length: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setArrowShaftLength(self, length: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setBarLength(self, length: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setBarThickness(self, width: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    def setColorFilter(self, colorFilter: android.graphics.ColorFilter, /) -> None: ...
    def setDirection(self, direction: int | java.jint | java.lang.Integer, /) -> None: ...
    def setGapSize(self, gap: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setProgress(self, progress: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setSpinEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setVerticalMirror(self, verticalMirror: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

    class ArrowDirection(java.lang.annotation.Annotation): ...
