import android.content
import android.content.res
import android.graphics
import android.graphics.drawable
import android.util
import androidx.appcompat.widget
import java
import java.chaquopy
import java.lang
import typing



class MaterialSwitch(androidx.appcompat.widget.SwitchCompat):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def getThumbDrawable(self) -> android.graphics.drawable.Drawable: ...
    def getThumbIconDrawable(self) -> android.graphics.drawable.Drawable: ...
    def getThumbIconSize(self) -> int: ...
    def getThumbIconTintList(self) -> android.content.res.ColorStateList: ...
    def getThumbIconTintMode(self) -> android.graphics.PorterDuff.Mode: ...
    def getThumbTintList(self) -> android.content.res.ColorStateList: ...
    def getTrackDecorationDrawable(self) -> android.graphics.drawable.Drawable: ...
    def getTrackDecorationTintList(self) -> android.content.res.ColorStateList: ...
    def getTrackDecorationTintMode(self) -> android.graphics.PorterDuff.Mode: ...
    def getTrackDrawable(self) -> android.graphics.drawable.Drawable: ...
    def getTrackTintList(self) -> android.content.res.ColorStateList: ...
    def invalidate(self) -> None: ...
    def onCreateDrawableState(self, extraSpace: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJInt: ...
    def setThumbDrawable(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...
    def setThumbIconDrawable(self, icon: android.graphics.drawable.Drawable, /) -> None: ...
    def setThumbIconResource(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setThumbIconSize(self, size: int | java.jint | java.lang.Integer, /) -> None: ...
    def setThumbIconTintList(self, tintList: android.content.res.ColorStateList, /) -> None: ...
    def setThumbIconTintMode(self, tintMode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def setThumbTintList(self, tintList: android.content.res.ColorStateList, /) -> None: ...
    def setThumbTintMode(self, tintMode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def setTrackDecorationDrawable(self, trackDecoration: android.graphics.drawable.Drawable, /) -> None: ...
    def setTrackDecorationResource(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTrackDecorationTintList(self, tintList: android.content.res.ColorStateList, /) -> None: ...
    def setTrackDecorationTintMode(self, tintMode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def setTrackDrawable(self, track: android.graphics.drawable.Drawable, /) -> None: ...
    def setTrackTintList(self, tintList: android.content.res.ColorStateList, /) -> None: ...
    def setTrackTintMode(self, tintMode: android.graphics.PorterDuff.Mode, /) -> None: ...
