import android.hardware
import android.location
import android.os
import java
import java.lang
import typing



class LocationListenerProxy(android.location.LocationListener):
    def __init__(self, pLocationManager: android.location.LocationManager, /) -> None: ...
    def onLocationChanged(self, arg0: android.location.Location, /) -> None: ...
    def onProviderDisabled(self, arg0: str | java.lang.String, /) -> None: ...
    def onProviderEnabled(self, arg0: str | java.lang.String, /) -> None: ...
    def onStatusChanged(self, arg0: str | java.lang.String, arg1: int | java.jint | java.lang.Integer, arg2: android.os.Bundle, /) -> None: ...
    def startListening(self, pListener: android.location.LocationListener, pUpdateTime: int | java.jlong | java.lang.Long, pUpdateDistance: float | java.jfloat | java.lang.Float, /) -> bool: ...
    def stopListening(self) -> None: ...

class OsmdroidBuildInfo(java.lang.Object):
    VERSION: typing.ClassVar[str] = ...
    BUILD_DATE: typing.ClassVar[str] = ...

class SensorEventListenerProxy(android.hardware.SensorEventListener):
    def __init__(self, pSensorManager: android.hardware.SensorManager, /) -> None: ...
    def onAccuracyChanged(self, pSensor: android.hardware.Sensor, pAccuracy: int | java.jint | java.lang.Integer, /) -> None: ...
    def onSensorChanged(self, pEvent: android.hardware.SensorEvent, /) -> None: ...
    def startListening(self, pListener: android.hardware.SensorEventListener, pSensorType: int | java.jint | java.lang.Integer, pRate: int | java.jint | java.lang.Integer, /) -> bool: ...
    def stopListening(self) -> None: ...
