import java
import java.chaquopy
import java.lang
import typing



class MathUtils(java.lang.Object):
    DEFAULT_EPSILON: typing.ClassVar[float] = ...
    @staticmethod
    def areAllElementsEqual(array: java.chaquopy.JavaArrayJFloat, /) -> bool: ...
    @staticmethod
    def dist(x1: float | java.jfloat | java.lang.Float, y1: float | java.jfloat | java.lang.Float, x2: float | java.jfloat | java.lang.Float, y2: float | java.jfloat | java.lang.Float, /) -> float: ...
    @staticmethod
    def distanceToFurthestCorner(pointX: float | java.jfloat | java.lang.Float, pointY: float | java.jfloat | java.lang.Float, rectLeft: float | java.jfloat | java.lang.Float, rectTop: float | java.jfloat | java.lang.Float, rectRight: float | java.jfloat | java.lang.Float, rectBottom: float | java.jfloat | java.lang.Float, /) -> float: ...
    @typing.overload
    @staticmethod
    def floorMod(x: float | java.jfloat | java.lang.Float, y: int | java.jint | java.lang.Integer, /) -> float: ...
    @typing.overload
    @staticmethod
    def floorMod(x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def geq(a: float | java.jfloat | java.lang.Float, b: float | java.jfloat | java.lang.Float, epsilon: float | java.jfloat | java.lang.Float, /) -> bool: ...
    @staticmethod
    def lerp(start: float | java.jfloat | java.lang.Float, stop: float | java.jfloat | java.lang.Float, amount: float | java.jfloat | java.lang.Float, /) -> float: ...
