import typing

import java.chaquopy
import java.lang
import java.lang.annotation
import kotlin.reflect

class JvmClassMappingKt(java.lang.Object):
    _getAnnotationClass__T = typing.TypeVar('_getAnnotationClass__T')  # <T>
    @staticmethod
    def getAnnotationClass(receiver: _getAnnotationClass__T, /) -> kotlin.reflect.KClass[_getAnnotationClass__T]: ...
    _getJavaClass_0__T = typing.TypeVar('_getJavaClass_0__T')  # <T>
    _getJavaClass_1__T = typing.TypeVar('_getJavaClass_1__T')  # <T>
    @typing.overload
    @staticmethod
    def getJavaClass(receiver: _getJavaClass_0__T, /) -> typing.Type[_getJavaClass_0__T]: ...
    @typing.overload
    @staticmethod
    def getJavaClass(receiver: kotlin.reflect.KClass[_getJavaClass_1__T], /) -> typing.Type[_getJavaClass_1__T]: ...
    _getJavaObjectType__T = typing.TypeVar('_getJavaObjectType__T')  # <T>
    @staticmethod
    def getJavaObjectType(receiver: kotlin.reflect.KClass[_getJavaObjectType__T], /) -> typing.Type[_getJavaObjectType__T]: ...
    _getJavaPrimitiveType__T = typing.TypeVar('_getJavaPrimitiveType__T')  # <T>
    @staticmethod
    def getJavaPrimitiveType(receiver: kotlin.reflect.KClass[_getJavaPrimitiveType__T], /) -> typing.Type[_getJavaPrimitiveType__T]: ...
    _getKotlinClass__T = typing.TypeVar('_getKotlinClass__T')  # <T>
    @staticmethod
    def getKotlinClass(receiver: typing.Type[_getKotlinClass__T], /) -> kotlin.reflect.KClass[_getKotlinClass__T]: ...
    _getRuntimeClassOfKClassInstance__T = typing.TypeVar('_getRuntimeClassOfKClassInstance__T')  # <T>
    @staticmethod
    def getRuntimeClassOfKClassInstance(receiver: kotlin.reflect.KClass[_getRuntimeClassOfKClassInstance__T], /) -> typing.Type[kotlin.reflect.KClass[_getRuntimeClassOfKClassInstance__T]]: ...

class JvmDefault(java.lang.annotation.Annotation): ...

class JvmField(java.lang.annotation.Annotation): ...

class JvmMultifileClass(java.lang.annotation.Annotation): ...

class JvmName(java.lang.annotation.Annotation):
    def name(self) -> str: ...

class JvmOverloads(java.lang.annotation.Annotation): ...

class JvmPackageName(java.lang.annotation.Annotation):
    def name(self) -> str: ...

class JvmStatic(java.lang.annotation.Annotation): ...

class JvmSuppressWildcards(java.lang.annotation.Annotation):
    def suppress(self) -> bool: ...

class JvmSynthetic(java.lang.annotation.Annotation): ...

class JvmVersion(java.lang.annotation.Annotation):
    def maximum(self) -> int: ...
    def minimum(self) -> int: ...

class JvmWildcard(java.lang.annotation.Annotation): ...

class KotlinReflectionNotSupportedError(java.lang.Error):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, message: str | java.lang.String, /) -> None: ...
    @typing.overload
    def __init__(self, cause: java.lang.Throwable, /) -> None: ...
    @typing.overload
    def __init__(self, message: str | java.lang.String, cause: java.lang.Throwable, /) -> None: ...

class PurelyImplements(java.lang.annotation.Annotation):
    def value(self) -> str: ...

class Strictfp(java.lang.annotation.Annotation): ...

class Synchronized(java.lang.annotation.Annotation): ...

class Throws(java.lang.annotation.Annotation):
    def exceptionClasses(self) -> java.chaquopy.JavaArray[typing.Type[java.lang.Throwable]]: ...

class Transient(java.lang.annotation.Annotation): ...

class Volatile(java.lang.annotation.Annotation): ...
