import typing

import java.chaquopy
import java.lang
import java.lang.annotation

class AnnotationRetention(java.lang.Enum[AnnotationRetention]):
    SOURCE: typing.ClassVar[AnnotationRetention] = ...
    BINARY: typing.ClassVar[AnnotationRetention] = ...
    RUNTIME: typing.ClassVar[AnnotationRetention] = ...
    @staticmethod
    def valueOf(value: str | java.lang.String, /) -> AnnotationRetention: ...
    @staticmethod
    def values() -> java.chaquopy.JavaArray[AnnotationRetention]: ...

class AnnotationTarget(java.lang.Enum[AnnotationTarget]):
    CLASS: typing.ClassVar[AnnotationTarget] = ...
    ANNOTATION_CLASS: typing.ClassVar[AnnotationTarget] = ...
    TYPE_PARAMETER: typing.ClassVar[AnnotationTarget] = ...
    PROPERTY: typing.ClassVar[AnnotationTarget] = ...
    FIELD: typing.ClassVar[AnnotationTarget] = ...
    LOCAL_VARIABLE: typing.ClassVar[AnnotationTarget] = ...
    VALUE_PARAMETER: typing.ClassVar[AnnotationTarget] = ...
    CONSTRUCTOR: typing.ClassVar[AnnotationTarget] = ...
    FUNCTION: typing.ClassVar[AnnotationTarget] = ...
    PROPERTY_GETTER: typing.ClassVar[AnnotationTarget] = ...
    PROPERTY_SETTER: typing.ClassVar[AnnotationTarget] = ...
    TYPE: typing.ClassVar[AnnotationTarget] = ...
    EXPRESSION: typing.ClassVar[AnnotationTarget] = ...
    FILE: typing.ClassVar[AnnotationTarget] = ...
    TYPEALIAS: typing.ClassVar[AnnotationTarget] = ...
    @staticmethod
    def valueOf(value: str | java.lang.String, /) -> AnnotationTarget: ...
    @staticmethod
    def values() -> java.chaquopy.JavaArray[AnnotationTarget]: ...

class MustBeDocumented(java.lang.annotation.Annotation): ...

class Repeatable(java.lang.annotation.Annotation): ...

class Retention(java.lang.annotation.Annotation):
    def value(self) -> AnnotationRetention: ...

class Target(java.lang.annotation.Annotation):
    def allowedTargets(self) -> java.chaquopy.JavaArray[AnnotationTarget]: ...
