import android.content
import android.content.res
import android.graphics
import android.graphics.drawable
import android.os
import android.text
import android.util
import android.view
import android.view.accessibility
import android.view.inputmethod
import android.widget
import androidx.appcompat.widget
import androidx.core.view
import androidx.core.view.accessibility
import com.google.android.material.shape
import java
import java.chaquopy
import java.lang
import java.lang.annotation
import typing



class ClearTextEndIconDelegate(EndIconDelegate):
    def onEditTextAttached(self, editText: android.widget.EditText, /) -> None: ...

class CustomEndIconDelegate(EndIconDelegate): ...

class CutoutDrawable(com.google.android.material.shape.MaterialShapeDrawable):
    def mutate(self) -> android.graphics.drawable.Drawable: ...

class DropdownMenuEndIconDelegate(EndIconDelegate):
    def afterEditTextChanged(self, s: android.text.Editable, /) -> None: ...
    def getTouchExplorationStateChangeListener(self) -> android.view.accessibility.AccessibilityManager.TouchExplorationStateChangeListener: ...
    def onEditTextAttached(self, editText: android.widget.EditText, /) -> None: ...
    def onInitializeAccessibilityNodeInfo(self, host: android.view.View, info: androidx.core.view.accessibility.AccessibilityNodeInfoCompat, /) -> None: ...
    def onPopulateAccessibilityEvent(self, host: android.view.View, event: android.view.accessibility.AccessibilityEvent, /) -> None: ...

class EditTextUtils(java.lang.Object): ...

class EndCompoundLayout(android.widget.LinearLayout): ...

class EndIconDelegate(java.lang.Object): ...

class IconHelper(java.lang.Object): ...

class IndicatorViewController(java.lang.Object):
    def __init__(self, textInputView: TextInputLayout, /) -> None: ...

class MaterialAutoCompleteTextView(androidx.appcompat.widget.AppCompatAutoCompleteTextView):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attributeSet: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def dismissDropDown(self) -> None: ...
    def getDropDownBackgroundTintList(self) -> android.content.res.ColorStateList: ...
    def getHint(self) -> java.lang.CharSequence: ...
    def getPopupElevation(self) -> float: ...
    def getSimpleItemSelectedColor(self) -> int: ...
    def getSimpleItemSelectedRippleColor(self) -> android.content.res.ColorStateList: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def onWindowFocusChanged(self, hasWindowFocus: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setAdapter(self, adapter: java.lang.Object, /) -> None: ...
    def setDropDownBackgroundDrawable(self, d: android.graphics.drawable.Drawable, /) -> None: ...
    def setDropDownBackgroundTint(self, dropDownBackgroundColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDropDownBackgroundTintList(self, dropDownBackgroundTint: android.content.res.ColorStateList, /) -> None: ...
    def setOnItemSelectedListener(self, listener: android.widget.AdapterView.OnItemSelectedListener, /) -> None: ...
    def setRawInputType(self, type: int | java.jint | java.lang.Integer, /) -> None: ...
    def setSimpleItemSelectedColor(self, simpleItemSelectedColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setSimpleItemSelectedRippleColor(self, simpleItemSelectedRippleColor: android.content.res.ColorStateList, /) -> None: ...
    @typing.overload
    def setSimpleItems(self, stringArrayResId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setSimpleItems(self, stringArray: java.chaquopy.JavaArray[java.lang.String], /) -> None: ...
    def showDropDown(self) -> None: ...

class NoEndIconDelegate(EndIconDelegate): ...

class PasswordToggleEndIconDelegate(EndIconDelegate): ...

class StartCompoundLayout(android.widget.LinearLayout):
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...

class TextInputEditText(androidx.appcompat.widget.AppCompatEditText):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def getFocusedRect(self, r: android.graphics.Rect, /) -> None: ...
    def getGlobalVisibleRect(self, r: android.graphics.Rect, globalOffset: android.graphics.Point, /) -> bool: ...
    def getHint(self) -> java.lang.CharSequence: ...
    def isTextInputLayoutFocusedRectEnabled(self) -> bool: ...
    def onAttachedToWindow(self) -> None: ...
    def onCreateInputConnection(self, outAttrs: android.view.inputmethod.EditorInfo, /) -> android.view.inputmethod.InputConnection: ...
    def onInitializeAccessibilityNodeInfo(self, info: android.view.accessibility.AccessibilityNodeInfo, /) -> None: ...
    def requestRectangleOnScreen(self, rectangle: android.graphics.Rect, /) -> bool: ...
    def setTextInputLayoutFocusedRectEnabled(self, textInputLayoutFocusedRectEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class TextInputLayout(android.widget.LinearLayout, android.view.ViewTreeObserver.OnGlobalLayoutListener):
    BOX_BACKGROUND_NONE: typing.ClassVar[int] = ...
    BOX_BACKGROUND_FILLED: typing.ClassVar[int] = ...
    BOX_BACKGROUND_OUTLINE: typing.ClassVar[int] = ...
    END_ICON_CUSTOM: typing.ClassVar[int] = ...
    END_ICON_NONE: typing.ClassVar[int] = ...
    END_ICON_PASSWORD_TOGGLE: typing.ClassVar[int] = ...
    END_ICON_CLEAR_TEXT: typing.ClassVar[int] = ...
    END_ICON_DROPDOWN_MENU: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def addOnEditTextAttachedListener(self, listener: TextInputLayout.OnEditTextAttachedListener, /) -> None: ...
    def addOnEndIconChangedListener(self, listener: TextInputLayout.OnEndIconChangedListener, /) -> None: ...
    def addView(self, child: android.view.View, index: int | java.jint | java.lang.Integer, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    def clearOnEditTextAttachedListeners(self) -> None: ...
    def clearOnEndIconChangedListeners(self) -> None: ...
    def dispatchProvideAutofillStructure(self, structure: android.view.ViewStructure, flags: int | java.jint | java.lang.Integer, /) -> None: ...
    def dispatchRestoreInstanceState(self, container: android.util.SparseArray[android.os.Parcelable], /) -> None: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def drawableStateChanged(self) -> None: ...
    def getBaseline(self) -> int: ...
    def getBoxBackgroundColor(self) -> int: ...
    def getBoxBackgroundMode(self) -> int: ...
    def getBoxCollapsedPaddingTop(self) -> int: ...
    def getBoxCornerRadiusBottomEnd(self) -> float: ...
    def getBoxCornerRadiusBottomStart(self) -> float: ...
    def getBoxCornerRadiusTopEnd(self) -> float: ...
    def getBoxCornerRadiusTopStart(self) -> float: ...
    def getBoxStrokeColor(self) -> int: ...
    def getBoxStrokeErrorColor(self) -> android.content.res.ColorStateList: ...
    def getBoxStrokeWidth(self) -> int: ...
    def getBoxStrokeWidthFocused(self) -> int: ...
    def getCounterMaxLength(self) -> int: ...
    def getCounterOverflowTextColor(self) -> android.content.res.ColorStateList: ...
    def getCounterTextColor(self) -> android.content.res.ColorStateList: ...
    def getCursorColor(self) -> android.content.res.ColorStateList: ...
    def getCursorErrorColor(self) -> android.content.res.ColorStateList: ...
    def getDefaultHintTextColor(self) -> android.content.res.ColorStateList: ...
    def getEditText(self) -> android.widget.EditText: ...
    def getEndIconContentDescription(self) -> java.lang.CharSequence: ...
    def getEndIconDrawable(self) -> android.graphics.drawable.Drawable: ...
    def getEndIconMinSize(self) -> int: ...
    def getEndIconMode(self) -> int: ...
    def getEndIconScaleType(self) -> android.widget.ImageView.ScaleType: ...
    def getError(self) -> java.lang.CharSequence: ...
    def getErrorAccessibilityLiveRegion(self) -> int: ...
    def getErrorContentDescription(self) -> java.lang.CharSequence: ...
    def getErrorCurrentTextColors(self) -> int: ...
    def getErrorIconDrawable(self) -> android.graphics.drawable.Drawable: ...
    def getHelperText(self) -> java.lang.CharSequence: ...
    def getHelperTextCurrentTextColor(self) -> int: ...
    def getHint(self) -> java.lang.CharSequence: ...
    def getHintMaxLines(self) -> int: ...
    def getHintTextColor(self) -> android.content.res.ColorStateList: ...
    def getLengthCounter(self) -> TextInputLayout.LengthCounter: ...
    def getMaxEms(self) -> int: ...
    def getMaxWidth(self) -> int: ...
    def getMinEms(self) -> int: ...
    def getMinWidth(self) -> int: ...
    def getPasswordVisibilityToggleContentDescription(self) -> java.lang.CharSequence: ...
    def getPasswordVisibilityToggleDrawable(self) -> android.graphics.drawable.Drawable: ...
    def getPlaceholderText(self) -> java.lang.CharSequence: ...
    def getPlaceholderTextAppearance(self) -> int: ...
    def getPlaceholderTextColor(self) -> android.content.res.ColorStateList: ...
    def getPrefixText(self) -> java.lang.CharSequence: ...
    def getPrefixTextColor(self) -> android.content.res.ColorStateList: ...
    def getPrefixTextView(self) -> android.widget.TextView: ...
    def getShapeAppearanceModel(self) -> com.google.android.material.shape.ShapeAppearanceModel: ...
    def getStartIconContentDescription(self) -> java.lang.CharSequence: ...
    def getStartIconDrawable(self) -> android.graphics.drawable.Drawable: ...
    def getStartIconMinSize(self) -> int: ...
    def getStartIconScaleType(self) -> android.widget.ImageView.ScaleType: ...
    def getSuffixText(self) -> java.lang.CharSequence: ...
    def getSuffixTextColor(self) -> android.content.res.ColorStateList: ...
    def getSuffixTextView(self) -> android.widget.TextView: ...
    def getTypeface(self) -> android.graphics.Typeface: ...
    def isCounterEnabled(self) -> bool: ...
    def isEndIconCheckable(self) -> bool: ...
    def isEndIconVisible(self) -> bool: ...
    def isErrorEnabled(self) -> bool: ...
    def isExpandedHintEnabled(self) -> bool: ...
    def isHelperTextEnabled(self) -> bool: ...
    def isHintAnimationEnabled(self) -> bool: ...
    def isHintEnabled(self) -> bool: ...
    def isPasswordVisibilityToggleEnabled(self) -> bool: ...
    def isProvidingHint(self) -> bool: ...
    def isStartIconCheckable(self) -> bool: ...
    def isStartIconVisible(self) -> bool: ...
    def onConfigurationChanged(self, newConfig: android.content.res.Configuration, /) -> None: ...
    def onGlobalLayout(self) -> None: ...
    def onLayout(self, changed: bool | java.jboolean | java.lang.Boolean, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def onRestoreInstanceState(self, state: android.os.Parcelable, /) -> None: ...
    def onRtlPropertiesChanged(self, layoutDirection: int | java.jint | java.lang.Integer, /) -> None: ...
    def onSaveInstanceState(self) -> android.os.Parcelable: ...
    def passwordVisibilityToggleRequested(self, shouldSkipAnimations: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def refreshEndIconDrawableState(self) -> None: ...
    def refreshErrorIconDrawableState(self) -> None: ...
    def refreshStartIconDrawableState(self) -> None: ...
    def removeOnEditTextAttachedListener(self, listener: TextInputLayout.OnEditTextAttachedListener, /) -> None: ...
    def removeOnEndIconChangedListener(self, listener: TextInputLayout.OnEndIconChangedListener, /) -> None: ...
    def setBoxBackgroundColor(self, boxBackgroundColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBoxBackgroundColorResource(self, boxBackgroundColorId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBoxBackgroundColorStateList(self, boxBackgroundColorStateList: android.content.res.ColorStateList, /) -> None: ...
    def setBoxBackgroundMode(self, boxBackgroundMode: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBoxCollapsedPaddingTop(self, boxCollapsedPaddingTop: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBoxCornerFamily(self, cornerFamily: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBoxCornerRadii(self, boxCornerRadiusTopStart: float | java.jfloat | java.lang.Float, boxCornerRadiusTopEnd: float | java.jfloat | java.lang.Float, boxCornerRadiusBottomStart: float | java.jfloat | java.lang.Float, boxCornerRadiusBottomEnd: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setBoxCornerRadiiResources(self, boxCornerRadiusTopStartId: int | java.jint | java.lang.Integer, boxCornerRadiusTopEndId: int | java.jint | java.lang.Integer, boxCornerRadiusBottomEndId: int | java.jint | java.lang.Integer, boxCornerRadiusBottomStartId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBoxStrokeColor(self, boxStrokeColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBoxStrokeColorStateList(self, boxStrokeColorStateList: android.content.res.ColorStateList, /) -> None: ...
    def setBoxStrokeErrorColor(self, strokeErrorColor: android.content.res.ColorStateList, /) -> None: ...
    def setBoxStrokeWidth(self, boxStrokeWidth: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBoxStrokeWidthFocused(self, boxStrokeWidthFocused: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBoxStrokeWidthFocusedResource(self, boxStrokeWidthFocusedResId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBoxStrokeWidthResource(self, boxStrokeWidthResId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCounterEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setCounterMaxLength(self, maxLength: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCounterOverflowTextAppearance(self, counterOverflowTextAppearance: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCounterOverflowTextColor(self, counterOverflowTextColor: android.content.res.ColorStateList, /) -> None: ...
    def setCounterTextAppearance(self, counterTextAppearance: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCounterTextColor(self, counterTextColor: android.content.res.ColorStateList, /) -> None: ...
    def setCursorColor(self, cursorColor: android.content.res.ColorStateList, /) -> None: ...
    def setCursorErrorColor(self, cursorErrorColor: android.content.res.ColorStateList, /) -> None: ...
    def setDefaultHintTextColor(self, textColor: android.content.res.ColorStateList, /) -> None: ...
    def setEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setEndIconActivated(self, endIconActivated: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setEndIconCheckable(self, endIconCheckable: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def setEndIconContentDescription(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setEndIconContentDescription(self, endIconContentDescription: java.lang.CharSequence, /) -> None: ...
    @typing.overload
    def setEndIconDrawable(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setEndIconDrawable(self, endIconDrawable: android.graphics.drawable.Drawable, /) -> None: ...
    def setEndIconMinSize(self, iconSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def setEndIconMode(self, endIconMode: int | java.jint | java.lang.Integer, /) -> None: ...
    def setEndIconOnClickListener(self, endIconOnClickListener: android.view.View.OnClickListener, /) -> None: ...
    def setEndIconOnLongClickListener(self, endIconOnLongClickListener: android.view.View.OnLongClickListener, /) -> None: ...
    def setEndIconScaleType(self, scaleType: android.widget.ImageView.ScaleType, /) -> None: ...
    def setEndIconTintList(self, endIconTintList: android.content.res.ColorStateList, /) -> None: ...
    def setEndIconTintMode(self, endIconTintMode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def setEndIconVisible(self, visible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setError(self, errorText: java.lang.CharSequence, /) -> None: ...
    def setErrorAccessibilityLiveRegion(self, errorAccessibilityLiveRegion: int | java.jint | java.lang.Integer, /) -> None: ...
    def setErrorContentDescription(self, errorContentDescription: java.lang.CharSequence, /) -> None: ...
    def setErrorEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def setErrorIconDrawable(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setErrorIconDrawable(self, errorIconDrawable: android.graphics.drawable.Drawable, /) -> None: ...
    def setErrorIconOnClickListener(self, errorIconOnClickListener: android.view.View.OnClickListener, /) -> None: ...
    def setErrorIconOnLongClickListener(self, errorIconOnLongClickListener: android.view.View.OnLongClickListener, /) -> None: ...
    def setErrorIconTintList(self, errorIconTintList: android.content.res.ColorStateList, /) -> None: ...
    def setErrorIconTintMode(self, errorIconTintMode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def setErrorTextAppearance(self, errorTextAppearance: int | java.jint | java.lang.Integer, /) -> None: ...
    def setErrorTextColor(self, errorTextColor: android.content.res.ColorStateList, /) -> None: ...
    def setExpandedHintEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setHelperText(self, helperText: java.lang.CharSequence, /) -> None: ...
    def setHelperTextColor(self, helperTextColor: android.content.res.ColorStateList, /) -> None: ...
    def setHelperTextEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setHelperTextTextAppearance(self, helperTextTextAppearance: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setHint(self, textHintId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setHint(self, hint: java.lang.CharSequence, /) -> None: ...
    def setHintAnimationEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setHintEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setHintMaxLines(self, hintMaxLines: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHintTextAppearance(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHintTextColor(self, hintTextColor: android.content.res.ColorStateList, /) -> None: ...
    def setLengthCounter(self, lengthCounter: TextInputLayout.LengthCounter, /) -> None: ...
    def setMaxEms(self, maxEms: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMaxWidth(self, maxWidth: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMaxWidthResource(self, maxWidthId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMinEms(self, minEms: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMinWidth(self, minWidth: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMinWidthResource(self, minWidthId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setPasswordVisibilityToggleContentDescription(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setPasswordVisibilityToggleContentDescription(self, description: java.lang.CharSequence, /) -> None: ...
    @typing.overload
    def setPasswordVisibilityToggleDrawable(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setPasswordVisibilityToggleDrawable(self, icon: android.graphics.drawable.Drawable, /) -> None: ...
    def setPasswordVisibilityToggleEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setPasswordVisibilityToggleTintList(self, tintList: android.content.res.ColorStateList, /) -> None: ...
    def setPasswordVisibilityToggleTintMode(self, mode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def setPlaceholderText(self, placeholderText: java.lang.CharSequence, /) -> None: ...
    def setPlaceholderTextAppearance(self, placeholderTextAppearance: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPlaceholderTextColor(self, placeholderTextColor: android.content.res.ColorStateList, /) -> None: ...
    def setPrefixText(self, prefixText: java.lang.CharSequence, /) -> None: ...
    def setPrefixTextAppearance(self, prefixTextAppearance: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPrefixTextColor(self, prefixTextColor: android.content.res.ColorStateList, /) -> None: ...
    def setShapeAppearanceModel(self, shapeAppearanceModel: com.google.android.material.shape.ShapeAppearanceModel, /) -> None: ...
    def setStartIconCheckable(self, startIconCheckable: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def setStartIconContentDescription(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setStartIconContentDescription(self, startIconContentDescription: java.lang.CharSequence, /) -> None: ...
    @typing.overload
    def setStartIconDrawable(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setStartIconDrawable(self, startIconDrawable: android.graphics.drawable.Drawable, /) -> None: ...
    def setStartIconMinSize(self, iconSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def setStartIconOnClickListener(self, startIconOnClickListener: android.view.View.OnClickListener, /) -> None: ...
    def setStartIconOnLongClickListener(self, startIconOnLongClickListener: android.view.View.OnLongClickListener, /) -> None: ...
    def setStartIconScaleType(self, scaleType: android.widget.ImageView.ScaleType, /) -> None: ...
    def setStartIconTintList(self, startIconTintList: android.content.res.ColorStateList, /) -> None: ...
    def setStartIconTintMode(self, startIconTintMode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def setStartIconVisible(self, visible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setSuffixText(self, suffixText: java.lang.CharSequence, /) -> None: ...
    def setSuffixTextAppearance(self, suffixTextAppearance: int | java.jint | java.lang.Integer, /) -> None: ...
    def setSuffixTextColor(self, suffixTextColor: android.content.res.ColorStateList, /) -> None: ...
    def setTextInputAccessibilityDelegate(self, delegate: TextInputLayout.AccessibilityDelegate, /) -> None: ...
    def setTypeface(self, typeface: android.graphics.Typeface, /) -> None: ...

    class LengthCounter(java.lang.Object):
        def countLength(self, arg1: android.text.Editable, /) -> int: ...

    class AccessibilityDelegate(androidx.core.view.AccessibilityDelegateCompat):
        def __init__(self, layout: TextInputLayout, /) -> None: ...
        def onInitializeAccessibilityNodeInfo(self, host: android.view.View, info: androidx.core.view.accessibility.AccessibilityNodeInfoCompat, /) -> None: ...
        def onPopulateAccessibilityEvent(self, host: android.view.View, event: android.view.accessibility.AccessibilityEvent, /) -> None: ...

    class OnEndIconChangedListener(java.lang.Object):
        def onEndIconChanged(self, arg1: TextInputLayout, arg2: int | java.jint | java.lang.Integer, /) -> None: ...

    class OnEditTextAttachedListener(java.lang.Object):
        def onEditTextAttached(self, arg1: TextInputLayout, /) -> None: ...

    class EndIconMode(java.lang.annotation.Annotation): ...

    class BoxBackgroundMode(java.lang.annotation.Annotation): ...
