import typing

import androidx.constraintlayout.core.motion.key
import androidx.constraintlayout.core.motion.utils
import androidx.constraintlayout.core.state
import java
import java.chaquopy
import java.lang
import java.util

class CustomAttribute(java.lang.Object):
    @typing.overload
    def __init__(self, source: CustomAttribute, value: java.lang.Object | int | bool | float | str, /) -> None: ...
    @typing.overload
    def __init__(self, name: str | java.lang.String, attributeType: CustomAttribute.AttributeType, /) -> None: ...
    @typing.overload
    def __init__(self, name: str | java.lang.String, attributeType: CustomAttribute.AttributeType, value: java.lang.Object | int | bool | float | str, method: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def applyCustom(self, view: java.lang.Object | int | bool | float | str, /) -> None: ...
    def diff(self, CustomAttribute: CustomAttribute, /) -> bool: ...
    @staticmethod
    def extractAttributes(base: java.util.HashMap[java.lang.String, CustomAttribute], view: java.lang.Object | int | bool | float | str, /) -> java.util.HashMap[java.lang.String, CustomAttribute]: ...
    def getType(self) -> CustomAttribute.AttributeType: ...
    def getValueToInterpolate(self) -> float: ...
    def getValuesToInterpolate(self, ret: java.chaquopy.JavaArrayJFloat, /) -> None: ...
    @staticmethod
    def hsvToRgb(hue: float | java.jfloat | java.lang.Float, saturation: float | java.jfloat | java.lang.Float, value: float | java.jfloat | java.lang.Float, /) -> int: ...
    def isContinuous(self) -> bool: ...
    def numberOfInterpolatedValues(self) -> int: ...
    @staticmethod
    def setAttributes(view: java.lang.Object | int | bool | float | str, map: java.util.HashMap[java.lang.String, CustomAttribute], /) -> None: ...
    def setColorValue(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setFloatValue(self, value: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setIntValue(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setInterpolatedValue(self, view: java.lang.Object | int | bool | float | str, value: java.chaquopy.JavaArrayJFloat, /) -> None: ...
    def setStringValue(self, value: str | java.lang.String, /) -> None: ...
    @typing.overload
    def setValue(self, value: java.lang.Object | int | bool | float | str, /) -> None: ...
    @typing.overload
    def setValue(self, value: java.chaquopy.JavaArrayJFloat, /) -> None: ...

    class AttributeType(java.lang.Enum[CustomAttribute.AttributeType]):
        INT_TYPE: typing.ClassVar[CustomAttribute.AttributeType] = ...
        FLOAT_TYPE: typing.ClassVar[CustomAttribute.AttributeType] = ...
        COLOR_TYPE: typing.ClassVar[CustomAttribute.AttributeType] = ...
        COLOR_DRAWABLE_TYPE: typing.ClassVar[CustomAttribute.AttributeType] = ...
        STRING_TYPE: typing.ClassVar[CustomAttribute.AttributeType] = ...
        BOOLEAN_TYPE: typing.ClassVar[CustomAttribute.AttributeType] = ...
        DIMENSION_TYPE: typing.ClassVar[CustomAttribute.AttributeType] = ...
        REFERENCE_TYPE: typing.ClassVar[CustomAttribute.AttributeType] = ...
        @staticmethod
        def valueOf(name: str | java.lang.String, /) -> CustomAttribute.AttributeType: ...
        @staticmethod
        def values() -> java.chaquopy.JavaArray[CustomAttribute.AttributeType]: ...

class CustomVariable(java.lang.Object):
    @typing.overload
    def __init__(self, c: CustomVariable, /) -> None: ...
    @typing.overload
    def __init__(self, source: CustomVariable, value: java.lang.Object | int | bool | float | str, /) -> None: ...
    @typing.overload
    def __init__(self, name: str | java.lang.String, attributeType: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, name: str | java.lang.String, type: int | java.jint | java.lang.Integer, value: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def __init__(self, name: str | java.lang.String, type: int | java.jint | java.lang.Integer, value: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, name: str | java.lang.String, attributeType: int | java.jint | java.lang.Integer, value: java.lang.Object | int | bool | float | str, /) -> None: ...
    @typing.overload
    def __init__(self, name: str | java.lang.String, type: int | java.jint | java.lang.Integer, value: str | java.lang.String, /) -> None: ...
    @typing.overload
    def __init__(self, name: str | java.lang.String, type: int | java.jint | java.lang.Integer, value: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def applyToWidget(self, view: MotionWidget, /) -> None: ...
    @staticmethod
    def colorString(v: int | java.jint | java.lang.Integer, /) -> str: ...
    def copy(self) -> CustomVariable: ...
    def diff(self, CustomAttribute: CustomVariable, /) -> bool: ...
    def getBooleanValue(self) -> bool: ...
    def getColorValue(self) -> int: ...
    def getFloatValue(self) -> float: ...
    def getIntegerValue(self) -> int: ...
    def getInterpolatedColor(self, value: java.chaquopy.JavaArrayJFloat, /) -> int: ...
    def getName(self) -> str: ...
    def getStringValue(self) -> str: ...
    def getType(self) -> int: ...
    def getValueToInterpolate(self) -> float: ...
    def getValuesToInterpolate(self, ret: java.chaquopy.JavaArrayJFloat, /) -> None: ...
    @staticmethod
    def hsvToRgb(hue: float | java.jfloat | java.lang.Float, saturation: float | java.jfloat | java.lang.Float, value: float | java.jfloat | java.lang.Float, /) -> int: ...
    def isContinuous(self) -> bool: ...
    def numberOfInterpolatedValues(self) -> int: ...
    @staticmethod
    def rgbaTocColor(r: float | java.jfloat | java.lang.Float, g: float | java.jfloat | java.lang.Float, b: float | java.jfloat | java.lang.Float, a: float | java.jfloat | java.lang.Float, /) -> int: ...
    def setBooleanValue(self, value: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setFloatValue(self, value: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setIntValue(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setInterpolatedValue(self, view: MotionWidget, value: java.chaquopy.JavaArrayJFloat, /) -> None: ...
    def setStringValue(self, value: str | java.lang.String, /) -> None: ...
    @typing.overload
    def setValue(self, value: java.lang.Object | int | bool | float | str, /) -> None: ...
    @typing.overload
    def setValue(self, value: java.chaquopy.JavaArrayJFloat, /) -> None: ...
    def toString(self) -> str: ...

class Motion(java.lang.Object):
    PATH_PERCENT: typing.ClassVar[int] = ...
    PATH_PERPENDICULAR: typing.ClassVar[int] = ...
    HORIZONTAL_PATH_X: typing.ClassVar[int] = ...
    HORIZONTAL_PATH_Y: typing.ClassVar[int] = ...
    VERTICAL_PATH_X: typing.ClassVar[int] = ...
    VERTICAL_PATH_Y: typing.ClassVar[int] = ...
    DRAW_PATH_NONE: typing.ClassVar[int] = ...
    DRAW_PATH_BASIC: typing.ClassVar[int] = ...
    DRAW_PATH_RELATIVE: typing.ClassVar[int] = ...
    DRAW_PATH_CARTESIAN: typing.ClassVar[int] = ...
    DRAW_PATH_AS_CONFIGURED: typing.ClassVar[int] = ...
    DRAW_PATH_RECTANGLE: typing.ClassVar[int] = ...
    DRAW_PATH_SCREEN: typing.ClassVar[int] = ...
    ROTATION_RIGHT: typing.ClassVar[int] = ...
    ROTATION_LEFT: typing.ClassVar[int] = ...
    def __init__(self, view: MotionWidget, /) -> None: ...
    def addKey(self, key: androidx.constraintlayout.core.motion.key.MotionKey, /) -> None: ...
    def buildKeyFrames(self, keyFrames: java.chaquopy.JavaArrayJFloat, mode: java.chaquopy.JavaArrayJInt, pos: java.chaquopy.JavaArrayJInt, /) -> int: ...
    def buildPath(self, points: java.chaquopy.JavaArrayJFloat, pointCount: int | java.jint | java.lang.Integer, /) -> None: ...
    def buildRect(self, p: float | java.jfloat | java.lang.Float, path: java.chaquopy.JavaArrayJFloat, offset: int | java.jint | java.lang.Integer, /) -> None: ...
    def getAnimateRelativeTo(self) -> int: ...
    def getCenter(self, p: float | java.jdouble | java.lang.Double, pos: java.chaquopy.JavaArrayJFloat, vel: java.chaquopy.JavaArrayJFloat, /) -> None: ...
    def getCenterX(self) -> float: ...
    def getCenterY(self) -> float: ...
    def getDrawPath(self) -> int: ...
    def getFinalHeight(self) -> float: ...
    def getFinalWidth(self) -> float: ...
    def getFinalX(self) -> float: ...
    def getFinalY(self) -> float: ...
    def getKeyFrame(self, i: int | java.jint | java.lang.Integer, /) -> MotionPaths: ...
    def getKeyFrameInfo(self, type: int | java.jint | java.lang.Integer, info: java.chaquopy.JavaArrayJInt, /) -> int: ...
    def getKeyFramePositions(self, type: java.chaquopy.JavaArrayJInt, pos: java.chaquopy.JavaArrayJFloat, /) -> int: ...
    def getStartHeight(self) -> float: ...
    def getStartWidth(self) -> float: ...
    def getStartX(self) -> float: ...
    def getStartY(self) -> float: ...
    def getTransformPivotTarget(self) -> int: ...
    def getView(self) -> MotionWidget: ...
    def interpolate(self, child: MotionWidget, global_position: float | java.jfloat | java.lang.Float, time: int | java.jlong | java.lang.Long, keyCache: androidx.constraintlayout.core.motion.utils.KeyCache, /) -> bool: ...
    def setDrawPath(self, debugMode: int | java.jint | java.lang.Integer, /) -> None: ...
    def setEnd(self, mw: MotionWidget, /) -> None: ...
    def setPathMotionArc(self, arc: int | java.jint | java.lang.Integer, /) -> None: ...
    def setStart(self, mw: MotionWidget, /) -> None: ...
    def setStartState(self, rect: androidx.constraintlayout.core.motion.utils.ViewState, v: MotionWidget, rotation: int | java.jint | java.lang.Integer, preWidth: int | java.jint | java.lang.Integer, preHeight: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTransformPivotTarget(self, transformPivotTarget: int | java.jint | java.lang.Integer, /) -> None: ...
    def setView(self, view: MotionWidget, /) -> None: ...
    def setup(self, parentWidth: int | java.jint | java.lang.Integer, parentHeight: int | java.jint | java.lang.Integer, transitionDuration: float | java.jfloat | java.lang.Float, currentTime: int | java.jlong | java.lang.Long, /) -> None: ...
    def setupRelative(self, motionController: Motion, /) -> None: ...
    def toString(self) -> str: ...

class MotionConstrainedPoint(java.lang.Comparable[MotionConstrainedPoint]):
    TAG: typing.ClassVar[str] = ...
    DEBUG: typing.ClassVar[bool] = ...
    rotationY: float = ...
    def __init__(self) -> None: ...
    def addValues(self, splines: java.util.HashMap[java.lang.String, androidx.constraintlayout.core.motion.utils.SplineSet], mFramePosition: int | java.jint | java.lang.Integer, /) -> None: ...
    def applyParameters(self, view: MotionWidget, /) -> None: ...
    def compareTo(self, o: MotionConstrainedPoint, /) -> int: ...
    @typing.overload
    def setState(self, view: MotionWidget, /) -> None: ...
    @typing.overload
    def setState(self, rect: androidx.constraintlayout.core.motion.utils.Rect, view: MotionWidget, rotation: int | java.jint | java.lang.Integer, prevous: float | java.jfloat | java.lang.Float, /) -> None: ...

class MotionPaths(java.lang.Comparable[MotionPaths]):
    TAG: typing.ClassVar[str] = ...
    DEBUG: typing.ClassVar[bool] = ...
    OLD_WAY: typing.ClassVar[bool] = ...
    PERPENDICULAR: typing.ClassVar[int] = ...
    CARTESIAN: typing.ClassVar[int] = ...
    SCREEN: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, parentWidth: int | java.jint | java.lang.Integer, parentHeight: int | java.jint | java.lang.Integer, c: androidx.constraintlayout.core.motion.key.MotionKeyPosition, startTimePoint: MotionPaths, endTimePoint: MotionPaths, /) -> None: ...
    def applyParameters(self, c: MotionWidget, /) -> None: ...
    def compareTo(self, o: MotionPaths, /) -> int: ...
    def configureRelativeTo(self, toOrbit: Motion, /) -> None: ...
    def setupRelative(self, mc: Motion, relative: MotionPaths, /) -> None: ...

class MotionWidget(androidx.constraintlayout.core.motion.utils.TypedValues):
    VISIBILITY_MODE_NORMAL: typing.ClassVar[int] = ...
    VISIBILITY_MODE_IGNORE: typing.ClassVar[int] = ...
    INVISIBLE: typing.ClassVar[int] = ...
    VISIBLE: typing.ClassVar[int] = ...
    ROTATE_NONE: typing.ClassVar[int] = ...
    ROTATE_PORTRATE_OF_RIGHT: typing.ClassVar[int] = ...
    ROTATE_PORTRATE_OF_LEFT: typing.ClassVar[int] = ...
    ROTATE_RIGHT_OF_PORTRATE: typing.ClassVar[int] = ...
    ROTATE_LEFT_OF_PORTRATE: typing.ClassVar[int] = ...
    UNSET: typing.ClassVar[int] = ...
    MATCH_CONSTRAINT: typing.ClassVar[int] = ...
    PARENT_ID: typing.ClassVar[int] = ...
    FILL_PARENT: typing.ClassVar[int] = ...
    MATCH_PARENT: typing.ClassVar[int] = ...
    WRAP_CONTENT: typing.ClassVar[int] = ...
    GONE_UNSET: typing.ClassVar[int] = ...
    MATCH_CONSTRAINT_WRAP: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, f: androidx.constraintlayout.core.state.WidgetFrame, /) -> None: ...
    def findViewById(self, mTransformPivotTarget: int | java.jint | java.lang.Integer, /) -> MotionWidget: ...
    def getAlpha(self) -> float: ...
    def getBottom(self) -> int: ...
    def getCustomAttribute(self, name: str | java.lang.String, /) -> CustomVariable: ...
    def getCustomAttributeNames(self) -> java.util.Set[java.lang.String]: ...
    def getHeight(self) -> int: ...
    def getId(self, name: str | java.lang.String, /) -> int: ...
    def getLeft(self) -> int: ...
    def getName(self) -> str: ...
    def getParent(self) -> MotionWidget: ...
    def getPivotX(self) -> float: ...
    def getPivotY(self) -> float: ...
    def getRight(self) -> int: ...
    def getRotationX(self) -> float: ...
    def getRotationY(self) -> float: ...
    def getRotationZ(self) -> float: ...
    def getScaleX(self) -> float: ...
    def getScaleY(self) -> float: ...
    def getTop(self) -> int: ...
    def getTranslationX(self) -> float: ...
    def getTranslationY(self) -> float: ...
    def getTranslationZ(self) -> float: ...
    def getValueAttributes(self, id: int | java.jint | java.lang.Integer, /) -> float: ...
    def getVisibility(self) -> int: ...
    def getWidgetFrame(self) -> androidx.constraintlayout.core.state.WidgetFrame: ...
    def getWidth(self) -> int: ...
    def getX(self) -> int: ...
    def getY(self) -> int: ...
    def layout(self, l: int | java.jint | java.lang.Integer, t: int | java.jint | java.lang.Integer, r: int | java.jint | java.lang.Integer, b: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBounds(self, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCustomAttribute(self, name: str | java.lang.String, type: int | java.jint | java.lang.Integer, value: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def setCustomAttribute(self, name: str | java.lang.String, type: int | java.jint | java.lang.Integer, value: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCustomAttribute(self, name: str | java.lang.String, type: int | java.jint | java.lang.Integer, value: str | java.lang.String, /) -> None: ...
    @typing.overload
    def setCustomAttribute(self, name: str | java.lang.String, type: int | java.jint | java.lang.Integer, value: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setPivotX(self, px: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setPivotY(self, py: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setRotationX(self, rotationX: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setRotationY(self, rotationY: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setRotationZ(self, rotationZ: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setScaleX(self, scaleX: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setScaleY(self, scaleY: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTranslationX(self, translationX: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTranslationY(self, translationY: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTranslationZ(self, tz: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def setValue(self, id: int | java.jint | java.lang.Integer, value: float | java.jfloat | java.lang.Float, /) -> bool: ...
    @typing.overload
    def setValue(self, id: int | java.jint | java.lang.Integer, value: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def setValue(self, id: int | java.jint | java.lang.Integer, value: str | java.lang.String, /) -> bool: ...
    @typing.overload
    def setValue(self, id: int | java.jint | java.lang.Integer, value: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def setValueAttributes(self, id: int | java.jint | java.lang.Integer, value: float | java.jfloat | java.lang.Float, /) -> bool: ...
    @typing.overload
    def setValueMotion(self, id: int | java.jint | java.lang.Integer, value: float | java.jfloat | java.lang.Float, /) -> bool: ...
    @typing.overload
    def setValueMotion(self, id: int | java.jint | java.lang.Integer, value: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def setValueMotion(self, id: int | java.jint | java.lang.Integer, value: str | java.lang.String, /) -> bool: ...
    def setVisibility(self, visibility: int | java.jint | java.lang.Integer, /) -> None: ...
    def toString(self) -> str: ...

    class PropertySet(java.lang.Object):
        visibility: int = ...
        mVisibilityMode: int = ...
        alpha: float = ...
        mProgress: float = ...
        def __init__(self) -> None: ...

    class Motion(java.lang.Object):
        mAnimateRelativeTo: int = ...
        mAnimateCircleAngleTo: int = ...
        mTransitionEasing: str = ...
        mPathMotionArc: int = ...
        mDrawPath: int = ...
        mMotionStagger: float = ...
        mPolarRelativeTo: int = ...
        mPathRotate: float = ...
        mQuantizeMotionPhase: float = ...
        mQuantizeMotionSteps: int = ...
        mQuantizeInterpolatorString: str = ...
        mQuantizeInterpolatorType: int = ...
        mQuantizeInterpolatorID: int = ...
        def __init__(self) -> None: ...
