import typing

import android.util
import android.view
import java
import java.lang

class AnimationHandler(java.lang.Object):
    sAnimatorHandler: typing.ClassVar[java.lang.ThreadLocal[AnimationHandler]] = ...
    def addAnimationFrameCallback(self, callback: AnimationHandler.AnimationFrameCallback, delay: int | java.jlong | java.lang.Long, /) -> None: ...
    @staticmethod
    def getFrameTime() -> int: ...
    @staticmethod
    def getInstance() -> AnimationHandler: ...
    def removeCallback(self, callback: AnimationHandler.AnimationFrameCallback, /) -> None: ...
    def setProvider(self, provider: AnimationHandler.AnimationFrameCallbackProvider, /) -> None: ...

_DynamicAnimation__T = typing.TypeVar('_DynamicAnimation__T', bound=DynamicAnimation[T])  # <T>
class DynamicAnimation(AnimationHandler.AnimationFrameCallback, typing.Generic[_DynamicAnimation__T]):
    TRANSLATION_X: typing.ClassVar[DynamicAnimation.ViewProperty] = ...
    TRANSLATION_Y: typing.ClassVar[DynamicAnimation.ViewProperty] = ...
    TRANSLATION_Z: typing.ClassVar[DynamicAnimation.ViewProperty] = ...
    SCALE_X: typing.ClassVar[DynamicAnimation.ViewProperty] = ...
    SCALE_Y: typing.ClassVar[DynamicAnimation.ViewProperty] = ...
    ROTATION: typing.ClassVar[DynamicAnimation.ViewProperty] = ...
    ROTATION_X: typing.ClassVar[DynamicAnimation.ViewProperty] = ...
    ROTATION_Y: typing.ClassVar[DynamicAnimation.ViewProperty] = ...
    X: typing.ClassVar[DynamicAnimation.ViewProperty] = ...
    Y: typing.ClassVar[DynamicAnimation.ViewProperty] = ...
    Z: typing.ClassVar[DynamicAnimation.ViewProperty] = ...
    ALPHA: typing.ClassVar[DynamicAnimation.ViewProperty] = ...
    SCROLL_X: typing.ClassVar[DynamicAnimation.ViewProperty] = ...
    SCROLL_Y: typing.ClassVar[DynamicAnimation.ViewProperty] = ...
    MIN_VISIBLE_CHANGE_PIXELS: typing.ClassVar[float] = ...
    MIN_VISIBLE_CHANGE_ROTATION_DEGREES: typing.ClassVar[float] = ...
    MIN_VISIBLE_CHANGE_ALPHA: typing.ClassVar[float] = ...
    MIN_VISIBLE_CHANGE_SCALE: typing.ClassVar[float] = ...
    def addEndListener(self, listener: DynamicAnimation.OnAnimationEndListener, /) -> _DynamicAnimation__T: ...
    def addUpdateListener(self, listener: DynamicAnimation.OnAnimationUpdateListener, /) -> _DynamicAnimation__T: ...
    def cancel(self) -> None: ...
    def doAnimationFrame(self, frameTime: int | java.jlong | java.lang.Long, /) -> bool: ...
    def getMinimumVisibleChange(self) -> float: ...
    def isRunning(self) -> bool: ...
    def removeEndListener(self, listener: DynamicAnimation.OnAnimationEndListener, /) -> None: ...
    def removeUpdateListener(self, listener: DynamicAnimation.OnAnimationUpdateListener, /) -> None: ...
    def setMaxValue(self, max: float | java.jfloat | java.lang.Float, /) -> _DynamicAnimation__T: ...
    def setMinValue(self, min: float | java.jfloat | java.lang.Float, /) -> _DynamicAnimation__T: ...
    def setMinimumVisibleChange(self, minimumVisibleChange: float | java.jfloat | java.lang.Float, /) -> _DynamicAnimation__T: ...
    def setStartValue(self, startValue: float | java.jfloat | java.lang.Float, /) -> _DynamicAnimation__T: ...
    def setStartVelocity(self, startVelocity: float | java.jfloat | java.lang.Float, /) -> _DynamicAnimation__T: ...
    def start(self) -> None: ...

    class OnAnimationUpdateListener(java.lang.Object):
        def onAnimationUpdate(self, arg1: DynamicAnimation, arg2: float | java.jfloat | java.lang.Float, arg3: float | java.jfloat | java.lang.Float, /) -> None: ...

    class OnAnimationEndListener(java.lang.Object):
        def onAnimationEnd(self, arg1: DynamicAnimation, arg2: bool | java.jboolean | java.lang.Boolean, arg3: float | java.jfloat | java.lang.Float, arg4: float | java.jfloat | java.lang.Float, /) -> None: ...

    class ViewProperty(FloatPropertyCompat[android.view.View]): ...

class FlingAnimation(DynamicAnimation[FlingAnimation]):
    ___init___1__K = typing.TypeVar('___init___1__K')  # <K>
    @typing.overload
    def __init__(self, floatValueHolder: FloatValueHolder, /) -> None: ...
    @typing.overload
    def __init__(self, object: ___init___1__K, property: FloatPropertyCompat[___init___1__K], /) -> None: ...
    def getFriction(self) -> float: ...
    def setFriction(self, friction: float | java.jfloat | java.lang.Float, /) -> FlingAnimation: ...
    def setMaxValue(self, maxValue: float | java.jfloat | java.lang.Float, /) -> FlingAnimation: ...
    def setMinValue(self, minValue: float | java.jfloat | java.lang.Float, /) -> FlingAnimation: ...
    def setStartVelocity(self, startVelocity: float | java.jfloat | java.lang.Float, /) -> FlingAnimation: ...

_FloatPropertyCompat__T = typing.TypeVar('_FloatPropertyCompat__T')  # <T>
class FloatPropertyCompat(java.lang.Object, typing.Generic[_FloatPropertyCompat__T]):
    def __init__(self, name: str | java.lang.String, /) -> None: ...
    _createFloatPropertyCompat__T = typing.TypeVar('_createFloatPropertyCompat__T')  # <T>
    @staticmethod
    def createFloatPropertyCompat(property: android.util.FloatProperty[_createFloatPropertyCompat__T], /) -> FloatPropertyCompat[_createFloatPropertyCompat__T]: ...
    def getValue(self, arg1: _FloatPropertyCompat__T, /) -> float: ...
    def setValue(self, arg1: _FloatPropertyCompat__T, arg2: float | java.jfloat | java.lang.Float, /) -> None: ...

class FloatValueHolder(java.lang.Object):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, value: float | java.jfloat | java.lang.Float, /) -> None: ...
    def getValue(self) -> float: ...
    def setValue(self, value: float | java.jfloat | java.lang.Float, /) -> None: ...

class Force(java.lang.Object):
    def getAcceleration(self, arg1: float | java.jfloat | java.lang.Float, arg2: float | java.jfloat | java.lang.Float, /) -> float: ...
    def isAtEquilibrium(self, arg1: float | java.jfloat | java.lang.Float, arg2: float | java.jfloat | java.lang.Float, /) -> bool: ...

class SpringAnimation(DynamicAnimation[SpringAnimation]):
    ___init___1__K = typing.TypeVar('___init___1__K')  # <K>
    ___init___2__K = typing.TypeVar('___init___2__K')  # <K>
    @typing.overload
    def __init__(self, floatValueHolder: FloatValueHolder, /) -> None: ...
    @typing.overload
    def __init__(self, object: ___init___1__K, property: FloatPropertyCompat[___init___1__K], /) -> None: ...
    @typing.overload
    def __init__(self, object: ___init___2__K, property: FloatPropertyCompat[___init___2__K], finalPosition: float | java.jfloat | java.lang.Float, /) -> None: ...
    def animateToFinalPosition(self, finalPosition: float | java.jfloat | java.lang.Float, /) -> None: ...
    def canSkipToEnd(self) -> bool: ...
    def getSpring(self) -> SpringForce: ...
    def setSpring(self, force: SpringForce, /) -> SpringAnimation: ...
    def skipToEnd(self) -> None: ...
    def start(self) -> None: ...

class SpringForce(Force):
    STIFFNESS_HIGH: typing.ClassVar[float] = ...
    STIFFNESS_MEDIUM: typing.ClassVar[float] = ...
    STIFFNESS_LOW: typing.ClassVar[float] = ...
    STIFFNESS_VERY_LOW: typing.ClassVar[float] = ...
    DAMPING_RATIO_HIGH_BOUNCY: typing.ClassVar[float] = ...
    DAMPING_RATIO_MEDIUM_BOUNCY: typing.ClassVar[float] = ...
    DAMPING_RATIO_LOW_BOUNCY: typing.ClassVar[float] = ...
    DAMPING_RATIO_NO_BOUNCY: typing.ClassVar[float] = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, finalPosition: float | java.jfloat | java.lang.Float, /) -> None: ...
    def getAcceleration(self, lastDisplacement: float | java.jfloat | java.lang.Float, lastVelocity: float | java.jfloat | java.lang.Float, /) -> float: ...
    def getDampingRatio(self) -> float: ...
    def getFinalPosition(self) -> float: ...
    def getStiffness(self) -> float: ...
    def isAtEquilibrium(self, value: float | java.jfloat | java.lang.Float, velocity: float | java.jfloat | java.lang.Float, /) -> bool: ...
    def setDampingRatio(self, dampingRatio: float | java.jfloat | java.lang.Float, /) -> SpringForce: ...
    def setFinalPosition(self, finalPosition: float | java.jfloat | java.lang.Float, /) -> SpringForce: ...
    def setStiffness(self, stiffness: float | java.jfloat | java.lang.Float, /) -> SpringForce: ...
