import typing

import android.content
import android.content.res
import android.graphics
import android.graphics.drawable
import android.os
import android.util
import android.view
import android.view.animation
import android.widget
import androidx.core.text
import androidx.core.view
import java
import java.chaquopy
import java.lang
import java.lang.annotation

class AutoScrollHelper(android.view.View.OnTouchListener):
    RELATIVE_UNSPECIFIED: typing.ClassVar[float] = ...
    NO_MAX: typing.ClassVar[float] = ...
    NO_MIN: typing.ClassVar[float] = ...
    EDGE_TYPE_INSIDE: typing.ClassVar[int] = ...
    EDGE_TYPE_INSIDE_EXTEND: typing.ClassVar[int] = ...
    EDGE_TYPE_OUTSIDE: typing.ClassVar[int] = ...
    def __init__(self, target: android.view.View, /) -> None: ...
    def canTargetScrollHorizontally(self, arg1: int | java.jint | java.lang.Integer, /) -> bool: ...
    def canTargetScrollVertically(self, arg1: int | java.jint | java.lang.Integer, /) -> bool: ...
    def isEnabled(self) -> bool: ...
    def isExclusive(self) -> bool: ...
    def onTouch(self, v: android.view.View, event: android.view.MotionEvent, /) -> bool: ...
    def scrollTargetBy(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, /) -> None: ...
    def setActivationDelay(self, delayMillis: int | java.jint | java.lang.Integer, /) -> AutoScrollHelper: ...
    def setEdgeType(self, type: int | java.jint | java.lang.Integer, /) -> AutoScrollHelper: ...
    def setEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> AutoScrollHelper: ...
    def setExclusive(self, exclusive: bool | java.jboolean | java.lang.Boolean, /) -> AutoScrollHelper: ...
    def setMaximumEdges(self, horizontalMax: float | java.jfloat | java.lang.Float, verticalMax: float | java.jfloat | java.lang.Float, /) -> AutoScrollHelper: ...
    def setMaximumVelocity(self, horizontalMax: float | java.jfloat | java.lang.Float, verticalMax: float | java.jfloat | java.lang.Float, /) -> AutoScrollHelper: ...
    def setMinimumVelocity(self, horizontalMin: float | java.jfloat | java.lang.Float, verticalMin: float | java.jfloat | java.lang.Float, /) -> AutoScrollHelper: ...
    def setRampDownDuration(self, durationMillis: int | java.jint | java.lang.Integer, /) -> AutoScrollHelper: ...
    def setRampUpDuration(self, durationMillis: int | java.jint | java.lang.Integer, /) -> AutoScrollHelper: ...
    def setRelativeEdges(self, horizontal: float | java.jfloat | java.lang.Float, vertical: float | java.jfloat | java.lang.Float, /) -> AutoScrollHelper: ...
    def setRelativeVelocity(self, horizontal: float | java.jfloat | java.lang.Float, vertical: float | java.jfloat | java.lang.Float, /) -> AutoScrollHelper: ...

class AutoSizeableTextView(java.lang.Object):
    PLATFORM_SUPPORTS_AUTOSIZE: typing.ClassVar[bool] = ...
    def getAutoSizeMaxTextSize(self) -> int: ...
    def getAutoSizeMinTextSize(self) -> int: ...
    def getAutoSizeStepGranularity(self) -> int: ...
    def getAutoSizeTextAvailableSizes(self) -> java.chaquopy.JavaArrayJInt: ...
    def getAutoSizeTextType(self) -> int: ...
    def setAutoSizeTextTypeUniformWithConfiguration(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, arg4: int | java.jint | java.lang.Integer, /) -> None: ...
    def setAutoSizeTextTypeUniformWithPresetSizes(self, arg1: java.chaquopy.JavaArrayJInt, arg2: int | java.jint | java.lang.Integer, /) -> None: ...
    def setAutoSizeTextTypeWithDefaults(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...

class CheckedTextViewCompat(java.lang.Object):
    @staticmethod
    def getCheckMarkDrawable(textView: android.widget.CheckedTextView, /) -> android.graphics.drawable.Drawable: ...
    @staticmethod
    def getCheckMarkTintList(textView: android.widget.CheckedTextView, /) -> android.content.res.ColorStateList: ...
    @staticmethod
    def getCheckMarkTintMode(textView: android.widget.CheckedTextView, /) -> android.graphics.PorterDuff.Mode: ...
    @staticmethod
    def setCheckMarkTintList(textView: android.widget.CheckedTextView, tint: android.content.res.ColorStateList, /) -> None: ...
    @staticmethod
    def setCheckMarkTintMode(textView: android.widget.CheckedTextView, tintMode: android.graphics.PorterDuff.Mode, /) -> None: ...

class CompoundButtonCompat(java.lang.Object):
    @staticmethod
    def getButtonDrawable(button: android.widget.CompoundButton, /) -> android.graphics.drawable.Drawable: ...
    @staticmethod
    def getButtonTintList(button: android.widget.CompoundButton, /) -> android.content.res.ColorStateList: ...
    @staticmethod
    def getButtonTintMode(button: android.widget.CompoundButton, /) -> android.graphics.PorterDuff.Mode: ...
    @staticmethod
    def setButtonTintList(button: android.widget.CompoundButton, tint: android.content.res.ColorStateList, /) -> None: ...
    @staticmethod
    def setButtonTintMode(button: android.widget.CompoundButton, tintMode: android.graphics.PorterDuff.Mode, /) -> None: ...

class ContentLoadingProgressBar(android.widget.ProgressBar):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    def hide(self) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def show(self) -> None: ...

class EdgeEffectCompat(java.lang.Object):
    def __init__(self, context: android.content.Context, /) -> None: ...
    @staticmethod
    def create(context: android.content.Context, attrs: android.util.AttributeSet, /) -> android.widget.EdgeEffect: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> bool: ...
    def finish(self) -> None: ...
    @staticmethod
    def getDistance(edgeEffect: android.widget.EdgeEffect, /) -> float: ...
    def isFinished(self) -> bool: ...
    def onAbsorb(self, velocity: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def onPull(self, deltaDistance: float | java.jfloat | java.lang.Float, /) -> bool: ...
    @typing.overload
    def onPull(self, deltaDistance: float | java.jfloat | java.lang.Float, displacement: float | java.jfloat | java.lang.Float, /) -> bool: ...
    @typing.overload
    @staticmethod
    def onPull(edgeEffect: android.widget.EdgeEffect, deltaDistance: float | java.jfloat | java.lang.Float, displacement: float | java.jfloat | java.lang.Float, /) -> None: ...
    @staticmethod
    def onPullDistance(edgeEffect: android.widget.EdgeEffect, deltaDistance: float | java.jfloat | java.lang.Float, displacement: float | java.jfloat | java.lang.Float, /) -> float: ...
    def onRelease(self) -> bool: ...
    def setSize(self, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...

class ImageViewCompat(java.lang.Object):
    @staticmethod
    def getImageTintList(view: android.widget.ImageView, /) -> android.content.res.ColorStateList: ...
    @staticmethod
    def getImageTintMode(view: android.widget.ImageView, /) -> android.graphics.PorterDuff.Mode: ...
    @staticmethod
    def setImageTintList(view: android.widget.ImageView, tintList: android.content.res.ColorStateList, /) -> None: ...
    @staticmethod
    def setImageTintMode(view: android.widget.ImageView, mode: android.graphics.PorterDuff.Mode, /) -> None: ...

class ListPopupWindowCompat(java.lang.Object):
    @typing.overload
    @staticmethod
    def createDragToOpenListener(listPopupWindow: android.widget.ListPopupWindow, src: android.view.View, /) -> android.view.View.OnTouchListener: ...
    @typing.overload
    @staticmethod
    def createDragToOpenListener(listPopupWindow: java.lang.Object | int | bool | float | str, src: android.view.View, /) -> android.view.View.OnTouchListener: ...

class ListViewAutoScrollHelper(AutoScrollHelper):
    def __init__(self, target: android.widget.ListView, /) -> None: ...
    def canTargetScrollHorizontally(self, direction: int | java.jint | java.lang.Integer, /) -> bool: ...
    def canTargetScrollVertically(self, direction: int | java.jint | java.lang.Integer, /) -> bool: ...
    def scrollTargetBy(self, deltaX: int | java.jint | java.lang.Integer, deltaY: int | java.jint | java.lang.Integer, /) -> None: ...

class ListViewCompat(java.lang.Object):
    @staticmethod
    def canScrollList(listView: android.widget.ListView, direction: int | java.jint | java.lang.Integer, /) -> bool: ...
    @staticmethod
    def scrollListBy(listView: android.widget.ListView, y: int | java.jint | java.lang.Integer, /) -> None: ...

class NestedScrollView(android.widget.FrameLayout, androidx.core.view.NestedScrollingParent3, androidx.core.view.NestedScrollingChild3, androidx.core.view.ScrollingView):
    mEdgeGlowTop: android.widget.EdgeEffect = ...
    mEdgeGlowBottom: android.widget.EdgeEffect = ...
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def addView(self, child: android.view.View, /) -> None: ...
    @typing.overload
    def addView(self, child: android.view.View, index: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def addView(self, child: android.view.View, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    @typing.overload
    def addView(self, child: android.view.View, index: int | java.jint | java.lang.Integer, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    def arrowScroll(self, direction: int | java.jint | java.lang.Integer, /) -> bool: ...
    def computeHorizontalScrollExtent(self) -> int: ...
    def computeHorizontalScrollOffset(self) -> int: ...
    def computeHorizontalScrollRange(self) -> int: ...
    def computeScroll(self) -> None: ...
    def computeScrollDeltaToGetChildRectOnScreen(self, rect: android.graphics.Rect, /) -> int: ...
    def computeVerticalScrollExtent(self) -> int: ...
    def computeVerticalScrollOffset(self) -> int: ...
    def computeVerticalScrollRange(self) -> int: ...
    def dispatchKeyEvent(self, event: android.view.KeyEvent, /) -> bool: ...
    def dispatchNestedFling(self, velocityX: float | java.jfloat | java.lang.Float, velocityY: float | java.jfloat | java.lang.Float, consumed: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def dispatchNestedPreFling(self, velocityX: float | java.jfloat | java.lang.Float, velocityY: float | java.jfloat | java.lang.Float, /) -> bool: ...
    @typing.overload
    def dispatchNestedPreScroll(self, dx: int | java.jint | java.lang.Integer, dy: int | java.jint | java.lang.Integer, consumed: java.chaquopy.JavaArrayJInt, offsetInWindow: java.chaquopy.JavaArrayJInt, /) -> bool: ...
    @typing.overload
    def dispatchNestedPreScroll(self, dx: int | java.jint | java.lang.Integer, dy: int | java.jint | java.lang.Integer, consumed: java.chaquopy.JavaArrayJInt, offsetInWindow: java.chaquopy.JavaArrayJInt, type: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def dispatchNestedScroll(self, dxConsumed: int | java.jint | java.lang.Integer, dyConsumed: int | java.jint | java.lang.Integer, dxUnconsumed: int | java.jint | java.lang.Integer, dyUnconsumed: int | java.jint | java.lang.Integer, offsetInWindow: java.chaquopy.JavaArrayJInt, /) -> bool: ...
    @typing.overload
    def dispatchNestedScroll(self, dxConsumed: int | java.jint | java.lang.Integer, dyConsumed: int | java.jint | java.lang.Integer, dxUnconsumed: int | java.jint | java.lang.Integer, dyUnconsumed: int | java.jint | java.lang.Integer, offsetInWindow: java.chaquopy.JavaArrayJInt, type: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def dispatchNestedScroll(self, dxConsumed: int | java.jint | java.lang.Integer, dyConsumed: int | java.jint | java.lang.Integer, dxUnconsumed: int | java.jint | java.lang.Integer, dyUnconsumed: int | java.jint | java.lang.Integer, offsetInWindow: java.chaquopy.JavaArrayJInt, type: int | java.jint | java.lang.Integer, consumed: java.chaquopy.JavaArrayJInt, /) -> None: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def executeKeyEvent(self, event: android.view.KeyEvent, /) -> bool: ...
    def fling(self, velocityY: int | java.jint | java.lang.Integer, /) -> None: ...
    def fullScroll(self, direction: int | java.jint | java.lang.Integer, /) -> bool: ...
    def getBottomFadingEdgeStrength(self) -> float: ...
    def getMaxScrollAmount(self) -> int: ...
    def getNestedScrollAxes(self) -> int: ...
    def getTopFadingEdgeStrength(self) -> float: ...
    @typing.overload
    def hasNestedScrollingParent(self) -> bool: ...
    @typing.overload
    def hasNestedScrollingParent(self, type: int | java.jint | java.lang.Integer, /) -> bool: ...
    def isFillViewport(self) -> bool: ...
    def isNestedScrollingEnabled(self) -> bool: ...
    def isSmoothScrollingEnabled(self) -> bool: ...
    def measureChild(self, child: android.view.View, parentWidthMeasureSpec: int | java.jint | java.lang.Integer, parentHeightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def measureChildWithMargins(self, child: android.view.View, parentWidthMeasureSpec: int | java.jint | java.lang.Integer, widthUsed: int | java.jint | java.lang.Integer, parentHeightMeasureSpec: int | java.jint | java.lang.Integer, heightUsed: int | java.jint | java.lang.Integer, /) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def onGenericMotionEvent(self, event: android.view.MotionEvent, /) -> bool: ...
    def onInterceptTouchEvent(self, ev: android.view.MotionEvent, /) -> bool: ...
    def onLayout(self, changed: bool | java.jboolean | java.lang.Boolean, l: int | java.jint | java.lang.Integer, t: int | java.jint | java.lang.Integer, r: int | java.jint | java.lang.Integer, b: int | java.jint | java.lang.Integer, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def onNestedFling(self, target: android.view.View, velocityX: float | java.jfloat | java.lang.Float, velocityY: float | java.jfloat | java.lang.Float, consumed: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def onNestedPreFling(self, target: android.view.View, velocityX: float | java.jfloat | java.lang.Float, velocityY: float | java.jfloat | java.lang.Float, /) -> bool: ...
    @typing.overload
    def onNestedPreScroll(self, target: android.view.View, dx: int | java.jint | java.lang.Integer, dy: int | java.jint | java.lang.Integer, consumed: java.chaquopy.JavaArrayJInt, /) -> None: ...
    @typing.overload
    def onNestedPreScroll(self, target: android.view.View, dx: int | java.jint | java.lang.Integer, dy: int | java.jint | java.lang.Integer, consumed: java.chaquopy.JavaArrayJInt, type: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def onNestedScroll(self, target: android.view.View, dxConsumed: int | java.jint | java.lang.Integer, dyConsumed: int | java.jint | java.lang.Integer, dxUnconsumed: int | java.jint | java.lang.Integer, dyUnconsumed: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def onNestedScroll(self, target: android.view.View, dxConsumed: int | java.jint | java.lang.Integer, dyConsumed: int | java.jint | java.lang.Integer, dxUnconsumed: int | java.jint | java.lang.Integer, dyUnconsumed: int | java.jint | java.lang.Integer, type: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def onNestedScroll(self, target: android.view.View, dxConsumed: int | java.jint | java.lang.Integer, dyConsumed: int | java.jint | java.lang.Integer, dxUnconsumed: int | java.jint | java.lang.Integer, dyUnconsumed: int | java.jint | java.lang.Integer, type: int | java.jint | java.lang.Integer, consumed: java.chaquopy.JavaArrayJInt, /) -> None: ...
    @typing.overload
    def onNestedScrollAccepted(self, child: android.view.View, target: android.view.View, axes: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def onNestedScrollAccepted(self, child: android.view.View, target: android.view.View, axes: int | java.jint | java.lang.Integer, type: int | java.jint | java.lang.Integer, /) -> None: ...
    def onOverScrolled(self, scrollX: int | java.jint | java.lang.Integer, scrollY: int | java.jint | java.lang.Integer, clampedX: bool | java.jboolean | java.lang.Boolean, clampedY: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def onRequestFocusInDescendants(self, direction: int | java.jint | java.lang.Integer, previouslyFocusedRect: android.graphics.Rect, /) -> bool: ...
    def onRestoreInstanceState(self, state: android.os.Parcelable, /) -> None: ...
    def onSaveInstanceState(self) -> android.os.Parcelable: ...
    def onScrollChanged(self, l: int | java.jint | java.lang.Integer, t: int | java.jint | java.lang.Integer, oldl: int | java.jint | java.lang.Integer, oldt: int | java.jint | java.lang.Integer, /) -> None: ...
    def onSizeChanged(self, w: int | java.jint | java.lang.Integer, h: int | java.jint | java.lang.Integer, oldw: int | java.jint | java.lang.Integer, oldh: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def onStartNestedScroll(self, child: android.view.View, target: android.view.View, axes: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def onStartNestedScroll(self, child: android.view.View, target: android.view.View, axes: int | java.jint | java.lang.Integer, type: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def onStopNestedScroll(self, target: android.view.View, /) -> None: ...
    @typing.overload
    def onStopNestedScroll(self, target: android.view.View, type: int | java.jint | java.lang.Integer, /) -> None: ...
    def onTouchEvent(self, ev: android.view.MotionEvent, /) -> bool: ...
    def pageScroll(self, direction: int | java.jint | java.lang.Integer, /) -> bool: ...
    def requestChildFocus(self, child: android.view.View, focused: android.view.View, /) -> None: ...
    def requestChildRectangleOnScreen(self, child: android.view.View, rectangle: android.graphics.Rect, immediate: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def requestDisallowInterceptTouchEvent(self, disallowIntercept: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def requestLayout(self) -> None: ...
    def scrollTo(self, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, /) -> None: ...
    def setFillViewport(self, fillViewport: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setNestedScrollingEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setOnScrollChangeListener(self, l: NestedScrollView.OnScrollChangeListener, /) -> None: ...
    def setSmoothScrollingEnabled(self, smoothScrollingEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def shouldDelayChildPressedState(self) -> bool: ...
    @typing.overload
    def smoothScrollBy(self, dx: int | java.jint | java.lang.Integer, dy: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def smoothScrollBy(self, dx: int | java.jint | java.lang.Integer, dy: int | java.jint | java.lang.Integer, scrollDurationMs: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def smoothScrollTo(self, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def smoothScrollTo(self, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, scrollDurationMs: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def startNestedScroll(self, axes: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def startNestedScroll(self, axes: int | java.jint | java.lang.Integer, type: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def stopNestedScroll(self) -> None: ...
    @typing.overload
    def stopNestedScroll(self, type: int | java.jint | java.lang.Integer, /) -> None: ...

    class OnScrollChangeListener(java.lang.Object):
        def onScrollChange(self, arg1: NestedScrollView, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, arg4: int | java.jint | java.lang.Integer, arg5: int | java.jint | java.lang.Integer, /) -> None: ...

class PopupMenuCompat(java.lang.Object):
    @staticmethod
    def getDragToOpenListener(popupMenu: java.lang.Object | int | bool | float | str, /) -> android.view.View.OnTouchListener: ...

class PopupWindowCompat(java.lang.Object):
    @staticmethod
    def getOverlapAnchor(popupWindow: android.widget.PopupWindow, /) -> bool: ...
    @staticmethod
    def getWindowLayoutType(popupWindow: android.widget.PopupWindow, /) -> int: ...
    @staticmethod
    def setOverlapAnchor(popupWindow: android.widget.PopupWindow, overlapAnchor: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def setWindowLayoutType(popupWindow: android.widget.PopupWindow, layoutType: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def showAsDropDown(popup: android.widget.PopupWindow, anchor: android.view.View, xoff: int | java.jint | java.lang.Integer, yoff: int | java.jint | java.lang.Integer, gravity: int | java.jint | java.lang.Integer, /) -> None: ...

class ScrollerCompat(java.lang.Object):
    def abortAnimation(self) -> None: ...
    def computeScrollOffset(self) -> bool: ...
    @typing.overload
    @staticmethod
    def create(context: android.content.Context, /) -> ScrollerCompat: ...
    @typing.overload
    @staticmethod
    def create(context: android.content.Context, interpolator: android.view.animation.Interpolator, /) -> ScrollerCompat: ...
    @typing.overload
    def fling(self, startX: int | java.jint | java.lang.Integer, startY: int | java.jint | java.lang.Integer, velocityX: int | java.jint | java.lang.Integer, velocityY: int | java.jint | java.lang.Integer, minX: int | java.jint | java.lang.Integer, maxX: int | java.jint | java.lang.Integer, minY: int | java.jint | java.lang.Integer, maxY: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def fling(self, startX: int | java.jint | java.lang.Integer, startY: int | java.jint | java.lang.Integer, velocityX: int | java.jint | java.lang.Integer, velocityY: int | java.jint | java.lang.Integer, minX: int | java.jint | java.lang.Integer, maxX: int | java.jint | java.lang.Integer, minY: int | java.jint | java.lang.Integer, maxY: int | java.jint | java.lang.Integer, overX: int | java.jint | java.lang.Integer, overY: int | java.jint | java.lang.Integer, /) -> None: ...
    def getCurrVelocity(self) -> float: ...
    def getCurrX(self) -> int: ...
    def getCurrY(self) -> int: ...
    def getFinalX(self) -> int: ...
    def getFinalY(self) -> int: ...
    def isFinished(self) -> bool: ...
    def isOverScrolled(self) -> bool: ...
    def notifyHorizontalEdgeReached(self, startX: int | java.jint | java.lang.Integer, finalX: int | java.jint | java.lang.Integer, overX: int | java.jint | java.lang.Integer, /) -> None: ...
    def notifyVerticalEdgeReached(self, startY: int | java.jint | java.lang.Integer, finalY: int | java.jint | java.lang.Integer, overY: int | java.jint | java.lang.Integer, /) -> None: ...
    def springBack(self, startX: int | java.jint | java.lang.Integer, startY: int | java.jint | java.lang.Integer, minX: int | java.jint | java.lang.Integer, maxX: int | java.jint | java.lang.Integer, minY: int | java.jint | java.lang.Integer, maxY: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def startScroll(self, startX: int | java.jint | java.lang.Integer, startY: int | java.jint | java.lang.Integer, dx: int | java.jint | java.lang.Integer, dy: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def startScroll(self, startX: int | java.jint | java.lang.Integer, startY: int | java.jint | java.lang.Integer, dx: int | java.jint | java.lang.Integer, dy: int | java.jint | java.lang.Integer, duration: int | java.jint | java.lang.Integer, /) -> None: ...

class TextViewCompat(java.lang.Object):
    AUTO_SIZE_TEXT_TYPE_NONE: typing.ClassVar[int] = ...
    AUTO_SIZE_TEXT_TYPE_UNIFORM: typing.ClassVar[int] = ...
    @staticmethod
    def getAutoSizeMaxTextSize(textView: android.widget.TextView, /) -> int: ...
    @staticmethod
    def getAutoSizeMinTextSize(textView: android.widget.TextView, /) -> int: ...
    @staticmethod
    def getAutoSizeStepGranularity(textView: android.widget.TextView, /) -> int: ...
    @staticmethod
    def getAutoSizeTextAvailableSizes(textView: android.widget.TextView, /) -> java.chaquopy.JavaArrayJInt: ...
    @staticmethod
    def getAutoSizeTextType(textView: android.widget.TextView, /) -> int: ...
    @staticmethod
    def getCompoundDrawableTintList(textView: android.widget.TextView, /) -> android.content.res.ColorStateList: ...
    @staticmethod
    def getCompoundDrawableTintMode(textView: android.widget.TextView, /) -> android.graphics.PorterDuff.Mode: ...
    @staticmethod
    def getCompoundDrawablesRelative(textView: android.widget.TextView, /) -> java.chaquopy.JavaArray[android.graphics.drawable.Drawable]: ...
    @staticmethod
    def getFirstBaselineToTopHeight(textView: android.widget.TextView, /) -> int: ...
    @staticmethod
    def getLastBaselineToBottomHeight(textView: android.widget.TextView, /) -> int: ...
    @staticmethod
    def getMaxLines(textView: android.widget.TextView, /) -> int: ...
    @staticmethod
    def getMinLines(textView: android.widget.TextView, /) -> int: ...
    @staticmethod
    def getTextMetricsParams(textView: android.widget.TextView, /) -> androidx.core.text.PrecomputedTextCompat.Params: ...
    @staticmethod
    def setAutoSizeTextTypeUniformWithConfiguration(textView: android.widget.TextView, autoSizeMinTextSize: int | java.jint | java.lang.Integer, autoSizeMaxTextSize: int | java.jint | java.lang.Integer, autoSizeStepGranularity: int | java.jint | java.lang.Integer, unit: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setAutoSizeTextTypeUniformWithPresetSizes(textView: android.widget.TextView, presetSizes: java.chaquopy.JavaArrayJInt, unit: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setAutoSizeTextTypeWithDefaults(textView: android.widget.TextView, autoSizeTextType: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setCompoundDrawableTintList(textView: android.widget.TextView, tint: android.content.res.ColorStateList, /) -> None: ...
    @staticmethod
    def setCompoundDrawableTintMode(textView: android.widget.TextView, tintMode: android.graphics.PorterDuff.Mode, /) -> None: ...
    @staticmethod
    def setCompoundDrawablesRelative(textView: android.widget.TextView, start: android.graphics.drawable.Drawable, top: android.graphics.drawable.Drawable, end: android.graphics.drawable.Drawable, bottom: android.graphics.drawable.Drawable, /) -> None: ...
    @typing.overload
    @staticmethod
    def setCompoundDrawablesRelativeWithIntrinsicBounds(textView: android.widget.TextView, start: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, end: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    @staticmethod
    def setCompoundDrawablesRelativeWithIntrinsicBounds(textView: android.widget.TextView, start: android.graphics.drawable.Drawable, top: android.graphics.drawable.Drawable, end: android.graphics.drawable.Drawable, bottom: android.graphics.drawable.Drawable, /) -> None: ...
    @staticmethod
    def setCustomSelectionActionModeCallback(textView: android.widget.TextView, callback: android.view.ActionMode.Callback, /) -> None: ...
    @staticmethod
    def setFirstBaselineToTopHeight(textView: android.widget.TextView, firstBaselineToTopHeight: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setLastBaselineToBottomHeight(textView: android.widget.TextView, lastBaselineToBottomHeight: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setLineHeight(textView: android.widget.TextView, lineHeight: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setPrecomputedText(textView: android.widget.TextView, precomputed: androidx.core.text.PrecomputedTextCompat, /) -> None: ...
    @staticmethod
    def setTextAppearance(textView: android.widget.TextView, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setTextMetricsParams(textView: android.widget.TextView, params: androidx.core.text.PrecomputedTextCompat.Params, /) -> None: ...
    @staticmethod
    def unwrapCustomSelectionActionModeCallback(callback: android.view.ActionMode.Callback, /) -> android.view.ActionMode.Callback: ...
    @staticmethod
    def wrapCustomSelectionActionModeCallback(textView: android.widget.TextView, callback: android.view.ActionMode.Callback, /) -> android.view.ActionMode.Callback: ...

    class AutoSizeTextType(java.lang.annotation.Annotation): ...

class TextViewOnReceiveContentListener(androidx.core.view.OnReceiveContentListener):
    def __init__(self) -> None: ...
    def onReceiveContent(self, view: android.view.View, payload: androidx.core.view.ContentInfoCompat, /) -> androidx.core.view.ContentInfoCompat: ...

class TintableCheckedTextView(java.lang.Object):
    def getSupportCheckMarkTintList(self) -> android.content.res.ColorStateList: ...
    def getSupportCheckMarkTintMode(self) -> android.graphics.PorterDuff.Mode: ...
    def setSupportCheckMarkTintList(self, arg1: android.content.res.ColorStateList, /) -> None: ...
    def setSupportCheckMarkTintMode(self, arg1: android.graphics.PorterDuff.Mode, /) -> None: ...

class TintableCompoundButton(java.lang.Object):
    def getSupportButtonTintList(self) -> android.content.res.ColorStateList: ...
    def getSupportButtonTintMode(self) -> android.graphics.PorterDuff.Mode: ...
    def setSupportButtonTintList(self, arg1: android.content.res.ColorStateList, /) -> None: ...
    def setSupportButtonTintMode(self, arg1: android.graphics.PorterDuff.Mode, /) -> None: ...

class TintableCompoundDrawablesView(java.lang.Object):
    def getSupportCompoundDrawablesTintList(self) -> android.content.res.ColorStateList: ...
    def getSupportCompoundDrawablesTintMode(self) -> android.graphics.PorterDuff.Mode: ...
    def setSupportCompoundDrawablesTintList(self, arg1: android.content.res.ColorStateList, /) -> None: ...
    def setSupportCompoundDrawablesTintMode(self, arg1: android.graphics.PorterDuff.Mode, /) -> None: ...

class TintableImageSourceView(java.lang.Object):
    def getSupportImageTintList(self) -> android.content.res.ColorStateList: ...
    def getSupportImageTintMode(self) -> android.graphics.PorterDuff.Mode: ...
    def setSupportImageTintList(self, arg1: android.content.res.ColorStateList, /) -> None: ...
    def setSupportImageTintMode(self, arg1: android.graphics.PorterDuff.Mode, /) -> None: ...
