import typing

import java.chaquopy
import java.lang
import java.lang.annotation
import javax.lang.model.element

class CanIgnoreReturnValue(java.lang.annotation.Annotation): ...

class CheckReturnValue(java.lang.annotation.Annotation): ...

class CompatibleWith(java.lang.annotation.Annotation):
    def value(self) -> str: ...

class CompileTimeConstant(java.lang.annotation.Annotation): ...

class DoNotCall(java.lang.annotation.Annotation):
    def value(self) -> str: ...

class DoNotMock(java.lang.annotation.Annotation):
    def value(self) -> str: ...

class ForOverride(java.lang.annotation.Annotation): ...

class FormatMethod(java.lang.annotation.Annotation): ...

class FormatString(java.lang.annotation.Annotation): ...

class Immutable(java.lang.annotation.Annotation):
    def containerOf(self) -> java.chaquopy.JavaArray[java.lang.String]: ...

class IncompatibleModifiers(java.lang.annotation.Annotation):
    def value(self) -> java.chaquopy.JavaArray[javax.lang.model.element.Modifier]: ...

class InlineMe(java.lang.annotation.Annotation):
    def imports(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    def replacement(self) -> str: ...
    def staticImports(self) -> java.chaquopy.JavaArray[java.lang.String]: ...

class InlineMeValidationDisabled(java.lang.annotation.Annotation):
    def value(self) -> str: ...

class MustBeClosed(java.lang.annotation.Annotation): ...

class NoAllocation(java.lang.annotation.Annotation): ...

class OverridingMethodsMustInvokeSuper(java.lang.annotation.Annotation): ...

class RequiredModifiers(java.lang.annotation.Annotation):
    def value(self) -> java.chaquopy.JavaArray[javax.lang.model.element.Modifier]: ...

class RestrictedApi(java.lang.annotation.Annotation):
    def allowedOnPath(self) -> str: ...
    def allowlistAnnotations(self) -> java.chaquopy.JavaArray[typing.Type[java.lang.annotation.Annotation]]: ...
    def allowlistWithWarningAnnotations(self) -> java.chaquopy.JavaArray[typing.Type[java.lang.annotation.Annotation]]: ...
    def explanation(self) -> str: ...
    def link(self) -> str: ...

class SuppressPackageLocation(java.lang.annotation.Annotation): ...

class Var(java.lang.annotation.Annotation): ...
