import android.app
import android.content
import android.database
import android.graphics
import android.graphics.drawable
import android.view
import android.widget
import androidx.appcompat.app
import java
import java.chaquopy
import java.lang
import typing



class InsetDialogOnTouchListener(android.view.View.OnTouchListener):
    def __init__(self, dialog: android.app.Dialog, insets: android.graphics.Rect, /) -> None: ...
    def onTouch(self, view: android.view.View, event: android.view.MotionEvent, /) -> bool: ...

class MaterialAlertDialogBuilder(androidx.appcompat.app.AlertDialog.Builder):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, overrideThemeResId: int | java.jint | java.lang.Integer, /) -> None: ...
    def create(self) -> androidx.appcompat.app.AlertDialog: ...
    def getBackground(self) -> android.graphics.drawable.Drawable: ...
    def setAdapter(self, adapter: android.widget.ListAdapter, listener: android.content.DialogInterface.OnClickListener, /) -> MaterialAlertDialogBuilder: ...
    def setBackground(self, background: android.graphics.drawable.Drawable, /) -> MaterialAlertDialogBuilder: ...
    def setBackgroundInsetBottom(self, backgroundInsetBottom: int | java.jint | java.lang.Integer, /) -> MaterialAlertDialogBuilder: ...
    def setBackgroundInsetEnd(self, backgroundInsetEnd: int | java.jint | java.lang.Integer, /) -> MaterialAlertDialogBuilder: ...
    def setBackgroundInsetStart(self, backgroundInsetStart: int | java.jint | java.lang.Integer, /) -> MaterialAlertDialogBuilder: ...
    def setBackgroundInsetTop(self, backgroundInsetTop: int | java.jint | java.lang.Integer, /) -> MaterialAlertDialogBuilder: ...
    def setCancelable(self, cancelable: bool | java.jboolean | java.lang.Boolean, /) -> MaterialAlertDialogBuilder: ...
    def setCursor(self, cursor: android.database.Cursor, listener: android.content.DialogInterface.OnClickListener, labelColumn: str | java.lang.String, /) -> MaterialAlertDialogBuilder: ...
    def setCustomTitle(self, customTitleView: android.view.View, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setIcon(self, iconId: int | java.jint | java.lang.Integer, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setIcon(self, icon: android.graphics.drawable.Drawable, /) -> MaterialAlertDialogBuilder: ...
    def setIconAttribute(self, attrId: int | java.jint | java.lang.Integer, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setItems(self, itemsId: int | java.jint | java.lang.Integer, listener: android.content.DialogInterface.OnClickListener, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setItems(self, items: java.chaquopy.JavaArray[java.lang.CharSequence], listener: android.content.DialogInterface.OnClickListener, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setMessage(self, messageId: int | java.jint | java.lang.Integer, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setMessage(self, message: java.lang.CharSequence, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setMultiChoiceItems(self, itemsId: int | java.jint | java.lang.Integer, checkedItems: java.chaquopy.JavaArrayJBoolean, listener: android.content.DialogInterface.OnMultiChoiceClickListener, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setMultiChoiceItems(self, items: java.chaquopy.JavaArray[java.lang.CharSequence], checkedItems: java.chaquopy.JavaArrayJBoolean, listener: android.content.DialogInterface.OnMultiChoiceClickListener, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setMultiChoiceItems(self, cursor: android.database.Cursor, isCheckedColumn: str | java.lang.String, labelColumn: str | java.lang.String, listener: android.content.DialogInterface.OnMultiChoiceClickListener, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setNegativeButton(self, textId: int | java.jint | java.lang.Integer, listener: android.content.DialogInterface.OnClickListener, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setNegativeButton(self, text: java.lang.CharSequence, listener: android.content.DialogInterface.OnClickListener, /) -> MaterialAlertDialogBuilder: ...
    def setNegativeButtonIcon(self, icon: android.graphics.drawable.Drawable, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setNeutralButton(self, textId: int | java.jint | java.lang.Integer, listener: android.content.DialogInterface.OnClickListener, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setNeutralButton(self, text: java.lang.CharSequence, listener: android.content.DialogInterface.OnClickListener, /) -> MaterialAlertDialogBuilder: ...
    def setNeutralButtonIcon(self, icon: android.graphics.drawable.Drawable, /) -> MaterialAlertDialogBuilder: ...
    def setOnCancelListener(self, onCancelListener: android.content.DialogInterface.OnCancelListener, /) -> MaterialAlertDialogBuilder: ...
    def setOnDismissListener(self, onDismissListener: android.content.DialogInterface.OnDismissListener, /) -> MaterialAlertDialogBuilder: ...
    def setOnItemSelectedListener(self, listener: android.widget.AdapterView.OnItemSelectedListener, /) -> MaterialAlertDialogBuilder: ...
    def setOnKeyListener(self, onKeyListener: android.content.DialogInterface.OnKeyListener, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setPositiveButton(self, textId: int | java.jint | java.lang.Integer, listener: android.content.DialogInterface.OnClickListener, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setPositiveButton(self, text: java.lang.CharSequence, listener: android.content.DialogInterface.OnClickListener, /) -> MaterialAlertDialogBuilder: ...
    def setPositiveButtonIcon(self, icon: android.graphics.drawable.Drawable, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setSingleChoiceItems(self, itemsId: int | java.jint | java.lang.Integer, checkedItem: int | java.jint | java.lang.Integer, listener: android.content.DialogInterface.OnClickListener, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setSingleChoiceItems(self, adapter: android.widget.ListAdapter, checkedItem: int | java.jint | java.lang.Integer, listener: android.content.DialogInterface.OnClickListener, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setSingleChoiceItems(self, items: java.chaquopy.JavaArray[java.lang.CharSequence], checkedItem: int | java.jint | java.lang.Integer, listener: android.content.DialogInterface.OnClickListener, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setSingleChoiceItems(self, cursor: android.database.Cursor, checkedItem: int | java.jint | java.lang.Integer, labelColumn: str | java.lang.String, listener: android.content.DialogInterface.OnClickListener, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setTitle(self, titleId: int | java.jint | java.lang.Integer, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setTitle(self, title: java.lang.CharSequence, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setView(self, layoutResId: int | java.jint | java.lang.Integer, /) -> MaterialAlertDialogBuilder: ...
    @typing.overload
    def setView(self, view: android.view.View, /) -> MaterialAlertDialogBuilder: ...

class MaterialDialogs(java.lang.Object):
    @staticmethod
    def getDialogBackgroundInsets(context: android.content.Context, defaultStyleAttribute: int | java.jint | java.lang.Integer, defaultStyleResource: int | java.jint | java.lang.Integer, /) -> android.graphics.Rect: ...
    @staticmethod
    def insetDrawable(drawable: android.graphics.drawable.Drawable, backgroundInsets: android.graphics.Rect, /) -> android.graphics.drawable.InsetDrawable: ...
