import typing

import android.content
import android.graphics
import android.util
import android.view
import androidx
import androidx.constraintlayout.solver
import androidx.constraintlayout.solver.widgets
import java
import java.chaquopy
import java.lang

class Barrier(ConstraintHelper):
    LEFT: typing.ClassVar[int] = ...
    TOP: typing.ClassVar[int] = ...
    RIGHT: typing.ClassVar[int] = ...
    BOTTOM: typing.ClassVar[int] = ...
    START: typing.ClassVar[int] = ...
    END: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def allowsGoneWidget(self) -> bool: ...
    def getType(self) -> int: ...
    def init(self, attrs: android.util.AttributeSet, /) -> None: ...
    def setAllowsGoneWidget(self, supportGone: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setType(self, type: int | java.jint | java.lang.Integer, /) -> None: ...

class ConstraintHelper(android.view.View):
    mIds: java.chaquopy.JavaArrayJInt = ...
    mCount: int = ...
    myContext: android.content.Context = ...
    mHelperWidget: androidx.constraintlayout.solver.widgets.Helper = ...
    mUseViewMeasure: bool = ...
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def getReferencedIds(self) -> java.chaquopy.JavaArrayJInt: ...
    def init(self, attrs: android.util.AttributeSet, /) -> None: ...
    def onDraw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def setReferencedIds(self, ids: java.chaquopy.JavaArrayJInt, /) -> None: ...
    def setTag(self, tag: int | java.jint | java.lang.Integer, value: java.lang.Object | int | bool | float | str, /) -> None: ...
    def updatePostLayout(self, container: ConstraintLayout, /) -> None: ...
    def updatePostMeasure(self, container: ConstraintLayout, /) -> None: ...
    def updatePreLayout(self, container: ConstraintLayout, /) -> None: ...
    def validateParams(self) -> None: ...

class ConstraintLayout(android.view.ViewGroup):
    VERSION: typing.ClassVar[str] = ...
    DESIGN_INFO_ID: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def addView(self, child: android.view.View, index: int | java.jint | java.lang.Integer, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    def checkLayoutParams(self, p: android.view.ViewGroup.LayoutParams, /) -> bool: ...
    def dispatchDraw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def fillMetrics(self, metrics: androidx.constraintlayout.solver.Metrics, /) -> None: ...
    def generateDefaultLayoutParams(self) -> ConstraintLayout.LayoutParams: ...
    @typing.overload
    def generateLayoutParams(self, attrs: android.util.AttributeSet, /) -> ConstraintLayout.LayoutParams: ...
    @typing.overload
    def generateLayoutParams(self, p: android.view.ViewGroup.LayoutParams, /) -> android.view.ViewGroup.LayoutParams: ...
    def getDesignInformation(self, type: int | java.jint | java.lang.Integer, value: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def getMaxHeight(self) -> int: ...
    def getMaxWidth(self) -> int: ...
    def getMinHeight(self) -> int: ...
    def getMinWidth(self) -> int: ...
    def getOptimizationLevel(self) -> int: ...
    def getViewById(self, id: int | java.jint | java.lang.Integer, /) -> android.view.View: ...
    def getViewWidget(self, view: android.view.View, /) -> androidx.constraintlayout.solver.widgets.ConstraintWidget: ...
    def onLayout(self, changed: bool | java.jboolean | java.lang.Boolean, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def onViewAdded(self, view: android.view.View, /) -> None: ...
    def onViewRemoved(self, view: android.view.View, /) -> None: ...
    def removeView(self, view: android.view.View, /) -> None: ...
    def requestLayout(self) -> None: ...
    def setConstraintSet(self, set: ConstraintSet, /) -> None: ...
    def setDesignInformation(self, type: int | java.jint | java.lang.Integer, value1: java.lang.Object | int | bool | float | str, value2: java.lang.Object | int | bool | float | str, /) -> None: ...
    def setId(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMaxHeight(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMaxWidth(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMinHeight(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMinWidth(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setOptimizationLevel(self, level: int | java.jint | java.lang.Integer, /) -> None: ...
    def shouldDelayChildPressedState(self) -> bool: ...
    def solveLinearSystem(self, reason: str | java.lang.String, /) -> None: ...

    class LayoutParams(android.view.ViewGroup.MarginLayoutParams):
        MATCH_CONSTRAINT: typing.ClassVar[int] = ...
        PARENT_ID: typing.ClassVar[int] = ...
        UNSET: typing.ClassVar[int] = ...
        HORIZONTAL: typing.ClassVar[int] = ...
        VERTICAL: typing.ClassVar[int] = ...
        LEFT: typing.ClassVar[int] = ...
        RIGHT: typing.ClassVar[int] = ...
        TOP: typing.ClassVar[int] = ...
        BOTTOM: typing.ClassVar[int] = ...
        BASELINE: typing.ClassVar[int] = ...
        START: typing.ClassVar[int] = ...
        END: typing.ClassVar[int] = ...
        MATCH_CONSTRAINT_WRAP: typing.ClassVar[int] = ...
        MATCH_CONSTRAINT_SPREAD: typing.ClassVar[int] = ...
        MATCH_CONSTRAINT_PERCENT: typing.ClassVar[int] = ...
        CHAIN_SPREAD: typing.ClassVar[int] = ...
        CHAIN_SPREAD_INSIDE: typing.ClassVar[int] = ...
        CHAIN_PACKED: typing.ClassVar[int] = ...
        guideBegin: int = ...
        guideEnd: int = ...
        guidePercent: float = ...
        leftToLeft: int = ...
        leftToRight: int = ...
        rightToLeft: int = ...
        rightToRight: int = ...
        topToTop: int = ...
        topToBottom: int = ...
        bottomToTop: int = ...
        bottomToBottom: int = ...
        baselineToBaseline: int = ...
        circleConstraint: int = ...
        circleRadius: int = ...
        circleAngle: float = ...
        startToEnd: int = ...
        startToStart: int = ...
        endToStart: int = ...
        endToEnd: int = ...
        goneLeftMargin: int = ...
        goneTopMargin: int = ...
        goneRightMargin: int = ...
        goneBottomMargin: int = ...
        goneStartMargin: int = ...
        goneEndMargin: int = ...
        horizontalBias: float = ...
        verticalBias: float = ...
        dimensionRatio: str = ...
        horizontalWeight: float = ...
        verticalWeight: float = ...
        horizontalChainStyle: int = ...
        verticalChainStyle: int = ...
        matchConstraintDefaultWidth: int = ...
        matchConstraintDefaultHeight: int = ...
        matchConstraintMinWidth: int = ...
        matchConstraintMinHeight: int = ...
        matchConstraintMaxWidth: int = ...
        matchConstraintMaxHeight: int = ...
        matchConstraintPercentWidth: float = ...
        matchConstraintPercentHeight: float = ...
        editorAbsoluteX: int = ...
        editorAbsoluteY: int = ...
        orientation: int = ...
        constrainedWidth: bool = ...
        constrainedHeight: bool = ...
        helped: bool = ...
        @typing.overload
        def __init__(self, source: android.view.ViewGroup.LayoutParams, /) -> None: ...
        @typing.overload
        def __init__(self, source: ConstraintLayout.LayoutParams, /) -> None: ...
        @typing.overload
        def __init__(self, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...
        @typing.overload
        def __init__(self, c: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
        def reset(self) -> None: ...
        def resolveLayoutDirection(self, layoutDirection: int | java.jint | java.lang.Integer, /) -> None: ...
        def validate(self) -> None: ...

class ConstraintSet(java.lang.Object):
    UNSET: typing.ClassVar[int] = ...
    MATCH_CONSTRAINT: typing.ClassVar[int] = ...
    WRAP_CONTENT: typing.ClassVar[int] = ...
    MATCH_CONSTRAINT_WRAP: typing.ClassVar[int] = ...
    MATCH_CONSTRAINT_SPREAD: typing.ClassVar[int] = ...
    PARENT_ID: typing.ClassVar[int] = ...
    HORIZONTAL: typing.ClassVar[int] = ...
    VERTICAL: typing.ClassVar[int] = ...
    HORIZONTAL_GUIDELINE: typing.ClassVar[int] = ...
    VERTICAL_GUIDELINE: typing.ClassVar[int] = ...
    VISIBLE: typing.ClassVar[int] = ...
    INVISIBLE: typing.ClassVar[int] = ...
    GONE: typing.ClassVar[int] = ...
    LEFT: typing.ClassVar[int] = ...
    RIGHT: typing.ClassVar[int] = ...
    TOP: typing.ClassVar[int] = ...
    BOTTOM: typing.ClassVar[int] = ...
    BASELINE: typing.ClassVar[int] = ...
    START: typing.ClassVar[int] = ...
    END: typing.ClassVar[int] = ...
    CHAIN_SPREAD: typing.ClassVar[int] = ...
    CHAIN_SPREAD_INSIDE: typing.ClassVar[int] = ...
    CHAIN_PACKED: typing.ClassVar[int] = ...
    def __init__(self) -> None: ...
    def addToHorizontalChain(self, viewId: int | java.jint | java.lang.Integer, leftId: int | java.jint | java.lang.Integer, rightId: int | java.jint | java.lang.Integer, /) -> None: ...
    def addToHorizontalChainRTL(self, viewId: int | java.jint | java.lang.Integer, leftId: int | java.jint | java.lang.Integer, rightId: int | java.jint | java.lang.Integer, /) -> None: ...
    def addToVerticalChain(self, viewId: int | java.jint | java.lang.Integer, topId: int | java.jint | java.lang.Integer, bottomId: int | java.jint | java.lang.Integer, /) -> None: ...
    def applyTo(self, constraintLayout: ConstraintLayout, /) -> None: ...
    def center(self, centerID: int | java.jint | java.lang.Integer, firstID: int | java.jint | java.lang.Integer, firstSide: int | java.jint | java.lang.Integer, firstMargin: int | java.jint | java.lang.Integer, secondId: int | java.jint | java.lang.Integer, secondSide: int | java.jint | java.lang.Integer, secondMargin: int | java.jint | java.lang.Integer, bias: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def centerHorizontally(self, viewId: int | java.jint | java.lang.Integer, toView: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def centerHorizontally(self, centerID: int | java.jint | java.lang.Integer, leftId: int | java.jint | java.lang.Integer, leftSide: int | java.jint | java.lang.Integer, leftMargin: int | java.jint | java.lang.Integer, rightId: int | java.jint | java.lang.Integer, rightSide: int | java.jint | java.lang.Integer, rightMargin: int | java.jint | java.lang.Integer, bias: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def centerHorizontallyRtl(self, viewId: int | java.jint | java.lang.Integer, toView: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def centerHorizontallyRtl(self, centerID: int | java.jint | java.lang.Integer, startId: int | java.jint | java.lang.Integer, startSide: int | java.jint | java.lang.Integer, startMargin: int | java.jint | java.lang.Integer, endId: int | java.jint | java.lang.Integer, endSide: int | java.jint | java.lang.Integer, endMargin: int | java.jint | java.lang.Integer, bias: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def centerVertically(self, viewId: int | java.jint | java.lang.Integer, toView: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def centerVertically(self, centerID: int | java.jint | java.lang.Integer, topId: int | java.jint | java.lang.Integer, topSide: int | java.jint | java.lang.Integer, topMargin: int | java.jint | java.lang.Integer, bottomId: int | java.jint | java.lang.Integer, bottomSide: int | java.jint | java.lang.Integer, bottomMargin: int | java.jint | java.lang.Integer, bias: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def clear(self, viewId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def clear(self, viewId: int | java.jint | java.lang.Integer, anchor: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def clone(self, constraintLayout: ConstraintLayout, /) -> None: ...
    @typing.overload
    def clone(self, set: ConstraintSet, /) -> None: ...
    @typing.overload
    def clone(self, constraints: Constraints, /) -> None: ...
    @typing.overload
    def clone(self, context: android.content.Context, constraintLayoutId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def connect(self, startID: int | java.jint | java.lang.Integer, startSide: int | java.jint | java.lang.Integer, endID: int | java.jint | java.lang.Integer, endSide: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def connect(self, startID: int | java.jint | java.lang.Integer, startSide: int | java.jint | java.lang.Integer, endID: int | java.jint | java.lang.Integer, endSide: int | java.jint | java.lang.Integer, margin: int | java.jint | java.lang.Integer, /) -> None: ...
    def constrainCircle(self, viewId: int | java.jint | java.lang.Integer, id: int | java.jint | java.lang.Integer, radius: int | java.jint | java.lang.Integer, angle: float | java.jfloat | java.lang.Float, /) -> None: ...
    def constrainDefaultHeight(self, viewId: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...
    def constrainDefaultWidth(self, viewId: int | java.jint | java.lang.Integer, width: int | java.jint | java.lang.Integer, /) -> None: ...
    def constrainHeight(self, viewId: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...
    def constrainMaxHeight(self, viewId: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...
    def constrainMaxWidth(self, viewId: int | java.jint | java.lang.Integer, width: int | java.jint | java.lang.Integer, /) -> None: ...
    def constrainMinHeight(self, viewId: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...
    def constrainMinWidth(self, viewId: int | java.jint | java.lang.Integer, width: int | java.jint | java.lang.Integer, /) -> None: ...
    def constrainPercentHeight(self, viewId: int | java.jint | java.lang.Integer, percent: float | java.jfloat | java.lang.Float, /) -> None: ...
    def constrainPercentWidth(self, viewId: int | java.jint | java.lang.Integer, percent: float | java.jfloat | java.lang.Float, /) -> None: ...
    def constrainWidth(self, viewId: int | java.jint | java.lang.Integer, width: int | java.jint | java.lang.Integer, /) -> None: ...
    def create(self, guidelineID: int | java.jint | java.lang.Integer, orientation: int | java.jint | java.lang.Integer, /) -> None: ...
    def createBarrier(self, id: int | java.jint | java.lang.Integer, direction: int | java.jint | java.lang.Integer, /, *referenced: java.jint) -> None: ...
    def createHorizontalChain(self, leftId: int | java.jint | java.lang.Integer, leftSide: int | java.jint | java.lang.Integer, rightId: int | java.jint | java.lang.Integer, rightSide: int | java.jint | java.lang.Integer, chainIds: java.chaquopy.JavaArrayJInt, weights: java.chaquopy.JavaArrayJFloat, style: int | java.jint | java.lang.Integer, /) -> None: ...
    def createHorizontalChainRtl(self, startId: int | java.jint | java.lang.Integer, startSide: int | java.jint | java.lang.Integer, endId: int | java.jint | java.lang.Integer, endSide: int | java.jint | java.lang.Integer, chainIds: java.chaquopy.JavaArrayJInt, weights: java.chaquopy.JavaArrayJFloat, style: int | java.jint | java.lang.Integer, /) -> None: ...
    def createVerticalChain(self, topId: int | java.jint | java.lang.Integer, topSide: int | java.jint | java.lang.Integer, bottomId: int | java.jint | java.lang.Integer, bottomSide: int | java.jint | java.lang.Integer, chainIds: java.chaquopy.JavaArrayJInt, weights: java.chaquopy.JavaArrayJFloat, style: int | java.jint | java.lang.Integer, /) -> None: ...
    def getApplyElevation(self, viewId: int | java.jint | java.lang.Integer, /) -> bool: ...
    def getParameters(self, mId: int | java.jint | java.lang.Integer, /) -> ConstraintSet.Constraint: ...
    def load(self, context: android.content.Context, resourceId: int | java.jint | java.lang.Integer, /) -> None: ...
    def removeFromHorizontalChain(self, viewId: int | java.jint | java.lang.Integer, /) -> None: ...
    def removeFromVerticalChain(self, viewId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setAlpha(self, viewId: int | java.jint | java.lang.Integer, alpha: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setApplyElevation(self, viewId: int | java.jint | java.lang.Integer, apply: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setBarrierType(self, id: int | java.jint | java.lang.Integer, type: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDimensionRatio(self, viewId: int | java.jint | java.lang.Integer, ratio: str | java.lang.String, /) -> None: ...
    def setElevation(self, viewId: int | java.jint | java.lang.Integer, elevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setGoneMargin(self, viewId: int | java.jint | java.lang.Integer, anchor: int | java.jint | java.lang.Integer, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setGuidelineBegin(self, guidelineID: int | java.jint | java.lang.Integer, margin: int | java.jint | java.lang.Integer, /) -> None: ...
    def setGuidelineEnd(self, guidelineID: int | java.jint | java.lang.Integer, margin: int | java.jint | java.lang.Integer, /) -> None: ...
    def setGuidelinePercent(self, guidelineID: int | java.jint | java.lang.Integer, ratio: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setHorizontalBias(self, viewId: int | java.jint | java.lang.Integer, bias: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setHorizontalChainStyle(self, viewId: int | java.jint | java.lang.Integer, chainStyle: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHorizontalWeight(self, viewId: int | java.jint | java.lang.Integer, weight: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setMargin(self, viewId: int | java.jint | java.lang.Integer, anchor: int | java.jint | java.lang.Integer, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setRotation(self, viewId: int | java.jint | java.lang.Integer, rotation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setRotationX(self, viewId: int | java.jint | java.lang.Integer, rotationX: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setRotationY(self, viewId: int | java.jint | java.lang.Integer, rotationY: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setScaleX(self, viewId: int | java.jint | java.lang.Integer, scaleX: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setScaleY(self, viewId: int | java.jint | java.lang.Integer, scaleY: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTransformPivot(self, viewId: int | java.jint | java.lang.Integer, transformPivotX: float | java.jfloat | java.lang.Float, transformPivotY: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTransformPivotX(self, viewId: int | java.jint | java.lang.Integer, transformPivotX: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTransformPivotY(self, viewId: int | java.jint | java.lang.Integer, transformPivotY: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTranslation(self, viewId: int | java.jint | java.lang.Integer, translationX: float | java.jfloat | java.lang.Float, translationY: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTranslationX(self, viewId: int | java.jint | java.lang.Integer, translationX: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTranslationY(self, viewId: int | java.jint | java.lang.Integer, translationY: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTranslationZ(self, viewId: int | java.jint | java.lang.Integer, translationZ: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setVerticalBias(self, viewId: int | java.jint | java.lang.Integer, bias: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setVerticalChainStyle(self, viewId: int | java.jint | java.lang.Integer, chainStyle: int | java.jint | java.lang.Integer, /) -> None: ...
    def setVerticalWeight(self, viewId: int | java.jint | java.lang.Integer, weight: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setVisibility(self, viewId: int | java.jint | java.lang.Integer, visibility: int | java.jint | java.lang.Integer, /) -> None: ...

class Constraints(android.view.ViewGroup):
    TAG: typing.ClassVar[str] = ...
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def generateDefaultLayoutParams(self) -> Constraints.LayoutParams: ...
    @typing.overload
    def generateLayoutParams(self, attrs: android.util.AttributeSet, /) -> Constraints.LayoutParams: ...
    @typing.overload
    def generateLayoutParams(self, p: android.view.ViewGroup.LayoutParams, /) -> android.view.ViewGroup.LayoutParams: ...
    def getConstraintSet(self) -> ConstraintSet: ...
    def onLayout(self, changed: bool | java.jboolean | java.lang.Boolean, l: int | java.jint | java.lang.Integer, t: int | java.jint | java.lang.Integer, r: int | java.jint | java.lang.Integer, b: int | java.jint | java.lang.Integer, /) -> None: ...

    class LayoutParams(androidx.constraintlayout.widget.ConstraintLayout.LayoutParams):
        alpha: float = ...
        applyElevation: bool = ...
        elevation: float = ...
        rotation: float = ...
        rotationX: float = ...
        rotationY: float = ...
        scaleX: float = ...
        scaleY: float = ...
        transformPivotX: float = ...
        transformPivotY: float = ...
        translationX: float = ...
        translationY: float = ...
        translationZ: float = ...
        @typing.overload
        def __init__(self, source: Constraints.LayoutParams, /) -> None: ...
        @typing.overload
        def __init__(self, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...
        @typing.overload
        def __init__(self, c: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...

class Group(ConstraintHelper):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def init(self, attrs: android.util.AttributeSet, /) -> None: ...
    def updatePostLayout(self, container: ConstraintLayout, /) -> None: ...
    def updatePreLayout(self, container: ConstraintLayout, /) -> None: ...

class Guideline(android.view.View):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, /) -> None: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def setGuidelineBegin(self, margin: int | java.jint | java.lang.Integer, /) -> None: ...
    def setGuidelineEnd(self, margin: int | java.jint | java.lang.Integer, /) -> None: ...
    def setGuidelinePercent(self, ratio: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setVisibility(self, visibility: int | java.jint | java.lang.Integer, /) -> None: ...

class Placeholder(android.view.View):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, /) -> None: ...
    def getContent(self) -> android.view.View: ...
    def getEmptyVisibility(self) -> int: ...
    def onDraw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def setContentId(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setEmptyVisibility(self, visibility: int | java.jint | java.lang.Integer, /) -> None: ...
    def updatePostMeasure(self, container: ConstraintLayout, /) -> None: ...
    def updatePreLayout(self, container: ConstraintLayout, /) -> None: ...
