import typing

import android.content
import android.util
import android.view
import androidx.coordinatorlayout.widget
import java
import java.lang

_HideBottomViewOnScrollBehavior__V = typing.TypeVar('_HideBottomViewOnScrollBehavior__V', bound=android.view.View)  # <V>
class HideBottomViewOnScrollBehavior(androidx.coordinatorlayout.widget.CoordinatorLayout.Behavior[_HideBottomViewOnScrollBehavior__V], typing.Generic[_HideBottomViewOnScrollBehavior__V]):
    ENTER_ANIMATION_DURATION: typing.ClassVar[int] = ...
    EXIT_ANIMATION_DURATION: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    def onLayoutChild(self, parent: androidx.coordinatorlayout.widget.CoordinatorLayout, child: _HideBottomViewOnScrollBehavior__V, layoutDirection: int | java.jint | java.lang.Integer, /) -> bool: ...
    def onNestedScroll(self, coordinatorLayout: androidx.coordinatorlayout.widget.CoordinatorLayout, child: _HideBottomViewOnScrollBehavior__V, target: android.view.View, dxConsumed: int | java.jint | java.lang.Integer, dyConsumed: int | java.jint | java.lang.Integer, dxUnconsumed: int | java.jint | java.lang.Integer, dyUnconsumed: int | java.jint | java.lang.Integer, /) -> None: ...
    def onStartNestedScroll(self, coordinatorLayout: androidx.coordinatorlayout.widget.CoordinatorLayout, child: _HideBottomViewOnScrollBehavior__V, directTargetChild: android.view.View, target: android.view.View, nestedScrollAxes: int | java.jint | java.lang.Integer, /) -> bool: ...
    def slideDown(self, child: _HideBottomViewOnScrollBehavior__V, /) -> None: ...
    def slideUp(self, child: _HideBottomViewOnScrollBehavior__V, /) -> None: ...

_SwipeDismissBehavior__V = typing.TypeVar('_SwipeDismissBehavior__V', bound=android.view.View)  # <V>
class SwipeDismissBehavior(androidx.coordinatorlayout.widget.CoordinatorLayout.Behavior[_SwipeDismissBehavior__V], typing.Generic[_SwipeDismissBehavior__V]):
    STATE_IDLE: typing.ClassVar[int] = ...
    STATE_DRAGGING: typing.ClassVar[int] = ...
    STATE_SETTLING: typing.ClassVar[int] = ...
    SWIPE_DIRECTION_START_TO_END: typing.ClassVar[int] = ...
    SWIPE_DIRECTION_END_TO_START: typing.ClassVar[int] = ...
    SWIPE_DIRECTION_ANY: typing.ClassVar[int] = ...
    def __init__(self) -> None: ...
    def canSwipeDismissView(self, view: android.view.View, /) -> bool: ...
    def getDragState(self) -> int: ...
    def onInterceptTouchEvent(self, parent: androidx.coordinatorlayout.widget.CoordinatorLayout, child: _SwipeDismissBehavior__V, event: android.view.MotionEvent, /) -> bool: ...
    def onTouchEvent(self, parent: androidx.coordinatorlayout.widget.CoordinatorLayout, child: _SwipeDismissBehavior__V, event: android.view.MotionEvent, /) -> bool: ...
    def setDragDismissDistance(self, distance: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setEndAlphaSwipeDistance(self, fraction: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setListener(self, listener: SwipeDismissBehavior.OnDismissListener, /) -> None: ...
    def setSensitivity(self, sensitivity: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setStartAlphaSwipeDistance(self, fraction: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setSwipeDirection(self, direction: int | java.jint | java.lang.Integer, /) -> None: ...

    class OnDismissListener(java.lang.Object):
        def onDismiss(self, arg1: android.view.View, /) -> None: ...
        def onDragStateChanged(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
