import typing

import java.chaquopy
import java.lang
import java.lang.annotation
import java.lang.reflect
import java.util
import kotlin
import kotlin.enums
import kotlin.jvm.functions

class GenericArrayTypeImpl(java.lang.reflect.GenericArrayType, TypeImpl):
    def __init__(self, elementType: java.lang.reflect.Type, /) -> None: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getGenericComponentType(self) -> java.lang.reflect.Type: ...
    def getTypeName(self) -> str: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class KAnnotatedElement(java.lang.Object):
    def getAnnotations(self) -> java.util.List[java.lang.annotation.Annotation]: ...

_KCallable__R = typing.TypeVar('_KCallable__R')  # <R>
class KCallable(KAnnotatedElement, typing.Generic[_KCallable__R]):
    def call(self, *arg1: java.lang.Object) -> _KCallable__R: ...
    def callBy(self, arg1: java.util.Map[KParameter, java.lang.Object], /) -> _KCallable__R: ...
    def getName(self) -> str: ...
    def getParameters(self) -> java.util.List[KParameter]: ...
    def getReturnType(self) -> KType: ...
    def getTypeParameters(self) -> java.util.List[KTypeParameter]: ...
    def getVisibility(self) -> KVisibility: ...
    def isAbstract(self) -> bool: ...
    def isFinal(self) -> bool: ...
    def isOpen(self) -> bool: ...
    def isSuspend(self) -> bool: ...

    class DefaultImpls(java.lang.Object): ...

_KClass__T = typing.TypeVar('_KClass__T')  # <T>
class KClass(KDeclarationContainer, KAnnotatedElement, KClassifier, typing.Generic[_KClass__T]):
    def equals(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getConstructors(self) -> java.util.Collection[KFunction[_KClass__T]]: ...
    def getMembers(self) -> java.util.Collection[KCallable[java.lang.Object]]: ...
    def getNestedClasses(self) -> java.util.Collection[KClass[java.lang.Object]]: ...
    def getObjectInstance(self) -> _KClass__T: ...
    def getQualifiedName(self) -> str: ...
    def getSealedSubclasses(self) -> java.util.List[KClass[_KClass__T]]: ...
    def getSimpleName(self) -> str: ...
    def getSupertypes(self) -> java.util.List[KType]: ...
    def getTypeParameters(self) -> java.util.List[KTypeParameter]: ...
    def getVisibility(self) -> KVisibility: ...
    def hashCode(self) -> int: ...
    def isAbstract(self) -> bool: ...
    def isCompanion(self) -> bool: ...
    def isData(self) -> bool: ...
    def isFinal(self) -> bool: ...
    def isFun(self) -> bool: ...
    def isInner(self) -> bool: ...
    def isInstance(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def isOpen(self) -> bool: ...
    def isSealed(self) -> bool: ...
    def isValue(self) -> bool: ...

    class DefaultImpls(java.lang.Object): ...

class KClasses(java.lang.Object):
    _cast__T = typing.TypeVar('_cast__T')  # <T>
    @staticmethod
    def cast(this_cast: KClass[_cast__T], value: java.lang.Object | int | bool | float | str, /) -> _cast__T: ...
    _safeCast__T = typing.TypeVar('_safeCast__T')  # <T>
    @staticmethod
    def safeCast(this_safeCast: KClass[_safeCast__T], value: java.lang.Object | int | bool | float | str, /) -> _safeCast__T: ...

class KClassesImplKt(java.lang.Object):
    @staticmethod
    def getQualifiedOrSimpleName(this_qualifiedOrSimpleName: KClass[java.lang.Object], /) -> str: ...

class KClassifier(java.lang.Object): ...

class KDeclarationContainer(java.lang.Object):
    def getMembers(self) -> java.util.Collection[KCallable[java.lang.Object]]: ...

_KFunction__R = typing.TypeVar('_KFunction__R')  # <R>
class KFunction(KCallable[_KFunction__R], kotlin.Function[_KFunction__R], typing.Generic[_KFunction__R]):
    def isExternal(self) -> bool: ...
    def isInfix(self) -> bool: ...
    def isInline(self) -> bool: ...
    def isOperator(self) -> bool: ...
    def isSuspend(self) -> bool: ...

    class DefaultImpls(java.lang.Object): ...

_KMutableProperty__V = typing.TypeVar('_KMutableProperty__V')  # <V>

_KMutableProperty__Setter__V = typing.TypeVar('_KMutableProperty__Setter__V')  # <V>
class KMutableProperty(KProperty[_KMutableProperty__V], typing.Generic[_KMutableProperty__V]):
    def getSetter(self) -> KMutableProperty.Setter[_KMutableProperty__V]: ...
    class Setter(kotlin.reflect.KProperty.Accessor[_KMutableProperty__Setter__V], KFunction[kotlin.Unit], typing.Generic[_KMutableProperty__Setter__V]): ...

_KMutableProperty0__V = typing.TypeVar('_KMutableProperty0__V')  # <V>

_KMutableProperty0__Setter__V = typing.TypeVar('_KMutableProperty0__Setter__V')  # <V>
class KMutableProperty0(KProperty0[_KMutableProperty0__V], KMutableProperty[_KMutableProperty0__V], typing.Generic[_KMutableProperty0__V]):
    def getSetter(self) -> KMutableProperty0.Setter[_KMutableProperty0__V]: ...
    def set(self, arg1: _KMutableProperty0__V, /) -> None: ...
    class Setter(kotlin.reflect.KMutableProperty.Setter[_KMutableProperty0__Setter__V], kotlin.jvm.functions.Function1[_KMutableProperty0__Setter__V, kotlin.Unit], typing.Generic[_KMutableProperty0__Setter__V]): ...

_KMutableProperty1__T = typing.TypeVar('_KMutableProperty1__T')  # <T>
_KMutableProperty1__V = typing.TypeVar('_KMutableProperty1__V')  # <V>

_KMutableProperty1__Setter__T = typing.TypeVar('_KMutableProperty1__Setter__T')  # <T>
_KMutableProperty1__Setter__V = typing.TypeVar('_KMutableProperty1__Setter__V')  # <V>
class KMutableProperty1(KProperty1[_KMutableProperty1__T, _KMutableProperty1__V], KMutableProperty[_KMutableProperty1__V], typing.Generic[_KMutableProperty1__T, _KMutableProperty1__V]):
    def getSetter(self) -> KMutableProperty1.Setter[_KMutableProperty1__T, _KMutableProperty1__V]: ...
    def set(self, arg1: _KMutableProperty1__T, arg2: _KMutableProperty1__V, /) -> None: ...
    class Setter(kotlin.reflect.KMutableProperty.Setter[_KMutableProperty1__Setter__V], kotlin.jvm.functions.Function2[_KMutableProperty1__Setter__T, _KMutableProperty1__Setter__V, kotlin.Unit], typing.Generic[_KMutableProperty1__Setter__T, _KMutableProperty1__Setter__V]): ...

_KMutableProperty2__D = typing.TypeVar('_KMutableProperty2__D')  # <D>
_KMutableProperty2__E = typing.TypeVar('_KMutableProperty2__E')  # <E>
_KMutableProperty2__V = typing.TypeVar('_KMutableProperty2__V')  # <V>

_KMutableProperty2__Setter__D = typing.TypeVar('_KMutableProperty2__Setter__D')  # <D>
_KMutableProperty2__Setter__E = typing.TypeVar('_KMutableProperty2__Setter__E')  # <E>
_KMutableProperty2__Setter__V = typing.TypeVar('_KMutableProperty2__Setter__V')  # <V>
class KMutableProperty2(KProperty2[_KMutableProperty2__D, _KMutableProperty2__E, _KMutableProperty2__V], KMutableProperty[_KMutableProperty2__V], typing.Generic[_KMutableProperty2__D, _KMutableProperty2__E, _KMutableProperty2__V]):
    def getSetter(self) -> KMutableProperty2.Setter[_KMutableProperty2__D, _KMutableProperty2__E, _KMutableProperty2__V]: ...
    def set(self, arg1: _KMutableProperty2__D, arg2: _KMutableProperty2__E, arg3: _KMutableProperty2__V, /) -> None: ...
    class Setter(kotlin.reflect.KMutableProperty.Setter[_KMutableProperty2__Setter__V], kotlin.jvm.functions.Function3[_KMutableProperty2__Setter__D, _KMutableProperty2__Setter__E, _KMutableProperty2__Setter__V, kotlin.Unit], typing.Generic[_KMutableProperty2__Setter__D, _KMutableProperty2__Setter__E, _KMutableProperty2__Setter__V]): ...

class KParameter(KAnnotatedElement):
    def getIndex(self) -> int: ...
    def getKind(self) -> KParameter.Kind: ...
    def getName(self) -> str: ...
    def getType(self) -> KType: ...
    def isOptional(self) -> bool: ...
    def isVararg(self) -> bool: ...

    class DefaultImpls(java.lang.Object): ...

    class Kind(java.lang.Enum[KParameter.Kind]):
        INSTANCE: typing.ClassVar[KParameter.Kind] = ...
        EXTENSION_RECEIVER: typing.ClassVar[KParameter.Kind] = ...
        VALUE: typing.ClassVar[KParameter.Kind] = ...
        @staticmethod
        def getEntries() -> kotlin.enums.EnumEntries[KParameter.Kind]: ...
        @staticmethod
        def valueOf(value: str | java.lang.String, /) -> KParameter.Kind: ...
        @staticmethod
        def values() -> java.chaquopy.JavaArray[KParameter.Kind]: ...

_KProperty__V = typing.TypeVar('_KProperty__V')  # <V>

_KProperty__Accessor__V = typing.TypeVar('_KProperty__Accessor__V')  # <V>

_KProperty__Getter__V = typing.TypeVar('_KProperty__Getter__V')  # <V>
class KProperty(KCallable[_KProperty__V], typing.Generic[_KProperty__V]):
    def getGetter(self) -> KProperty.Getter[_KProperty__V]: ...
    def isConst(self) -> bool: ...
    def isLateinit(self) -> bool: ...
    class Accessor(java.lang.Object, typing.Generic[_KProperty__Accessor__V]):
        def getProperty(self) -> KProperty[_KProperty__Accessor__V]: ...

    class DefaultImpls(java.lang.Object): ...
    class Getter(kotlin.reflect.KProperty.Accessor[_KProperty__Getter__V], KFunction[_KProperty__Getter__V], typing.Generic[_KProperty__Getter__V]): ...

_KProperty0__V = typing.TypeVar('_KProperty0__V')  # <V>

_KProperty0__Getter__V = typing.TypeVar('_KProperty0__Getter__V')  # <V>
class KProperty0(KProperty[_KProperty0__V], kotlin.jvm.functions.Function0[_KProperty0__V], typing.Generic[_KProperty0__V]):
    def get(self) -> _KProperty0__V: ...
    def getDelegate(self) -> java.lang.Object: ...
    def getGetter(self) -> KProperty0.Getter[_KProperty0__V]: ...
    class Getter(kotlin.reflect.KProperty.Getter[_KProperty0__Getter__V], kotlin.jvm.functions.Function0[_KProperty0__Getter__V], typing.Generic[_KProperty0__Getter__V]): ...

_KProperty1__T = typing.TypeVar('_KProperty1__T')  # <T>
_KProperty1__V = typing.TypeVar('_KProperty1__V')  # <V>

_KProperty1__Getter__T = typing.TypeVar('_KProperty1__Getter__T')  # <T>
_KProperty1__Getter__V = typing.TypeVar('_KProperty1__Getter__V')  # <V>
class KProperty1(KProperty[_KProperty1__V], kotlin.jvm.functions.Function1[_KProperty1__T, _KProperty1__V], typing.Generic[_KProperty1__T, _KProperty1__V]):
    def get(self, arg1: _KProperty1__T, /) -> _KProperty1__V: ...
    def getDelegate(self, arg1: _KProperty1__T, /) -> java.lang.Object: ...
    def getGetter(self) -> KProperty1.Getter[_KProperty1__T, _KProperty1__V]: ...
    class Getter(kotlin.reflect.KProperty.Getter[_KProperty1__Getter__V], kotlin.jvm.functions.Function1[_KProperty1__Getter__T, _KProperty1__Getter__V], typing.Generic[_KProperty1__Getter__T, _KProperty1__Getter__V]): ...

_KProperty2__D = typing.TypeVar('_KProperty2__D')  # <D>
_KProperty2__E = typing.TypeVar('_KProperty2__E')  # <E>
_KProperty2__V = typing.TypeVar('_KProperty2__V')  # <V>

_KProperty2__Getter__D = typing.TypeVar('_KProperty2__Getter__D')  # <D>
_KProperty2__Getter__E = typing.TypeVar('_KProperty2__Getter__E')  # <E>
_KProperty2__Getter__V = typing.TypeVar('_KProperty2__Getter__V')  # <V>
class KProperty2(KProperty[_KProperty2__V], kotlin.jvm.functions.Function2[_KProperty2__D, _KProperty2__E, _KProperty2__V], typing.Generic[_KProperty2__D, _KProperty2__E, _KProperty2__V]):
    def get(self, arg1: _KProperty2__D, arg2: _KProperty2__E, /) -> _KProperty2__V: ...
    def getDelegate(self, arg1: _KProperty2__D, arg2: _KProperty2__E, /) -> java.lang.Object: ...
    def getGetter(self) -> KProperty2.Getter[_KProperty2__D, _KProperty2__E, _KProperty2__V]: ...
    class Getter(kotlin.reflect.KProperty.Getter[_KProperty2__Getter__V], kotlin.jvm.functions.Function2[_KProperty2__Getter__D, _KProperty2__Getter__E, _KProperty2__Getter__V], typing.Generic[_KProperty2__Getter__D, _KProperty2__Getter__E, _KProperty2__Getter__V]): ...

class KType(KAnnotatedElement):
    def getArguments(self) -> java.util.List[KTypeProjection]: ...
    def getClassifier(self) -> KClassifier: ...
    def isMarkedNullable(self) -> bool: ...

    class DefaultImpls(java.lang.Object): ...

class KTypeParameter(KClassifier):
    def getName(self) -> str: ...
    def getUpperBounds(self) -> java.util.List[KType]: ...
    def getVariance(self) -> KVariance: ...
    def isReified(self) -> bool: ...

class KTypeProjection(java.lang.Object):
    Companion: typing.ClassVar[KTypeProjection.Companion] = ...
    star: typing.ClassVar[KTypeProjection] = ...
    def __init__(self, variance: KVariance, type: KType, /) -> None: ...
    def component1(self) -> KVariance: ...
    def component2(self) -> KType: ...
    @staticmethod
    def contravariant(type: KType, /) -> KTypeProjection: ...
    def copy(self, variance: KVariance, type: KType, /) -> KTypeProjection: ...
    @staticmethod
    def covariant(type: KType, /) -> KTypeProjection: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getType(self) -> KType: ...
    def getVariance(self) -> KVariance: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def invariant(type: KType, /) -> KTypeProjection: ...
    def toString(self) -> str: ...

    class Companion(java.lang.Object):
        def contravariant(self, type: KType, /) -> KTypeProjection: ...
        def covariant(self, type: KType, /) -> KTypeProjection: ...
        def getSTAR(self) -> KTypeProjection: ...
        def invariant(self, type: KType, /) -> KTypeProjection: ...

class KVariance(java.lang.Enum[KVariance]):
    INVARIANT: typing.ClassVar[KVariance] = ...
    IN: typing.ClassVar[KVariance] = ...
    OUT: typing.ClassVar[KVariance] = ...
    @staticmethod
    def getEntries() -> kotlin.enums.EnumEntries[KVariance]: ...
    @staticmethod
    def valueOf(value: str | java.lang.String, /) -> KVariance: ...
    @staticmethod
    def values() -> java.chaquopy.JavaArray[KVariance]: ...

class KVisibility(java.lang.Enum[KVisibility]):
    PUBLIC: typing.ClassVar[KVisibility] = ...
    PROTECTED: typing.ClassVar[KVisibility] = ...
    INTERNAL: typing.ClassVar[KVisibility] = ...
    PRIVATE: typing.ClassVar[KVisibility] = ...
    @staticmethod
    def getEntries() -> kotlin.enums.EnumEntries[KVisibility]: ...
    @staticmethod
    def valueOf(value: str | java.lang.String, /) -> KVisibility: ...
    @staticmethod
    def values() -> java.chaquopy.JavaArray[KVisibility]: ...

class ParameterizedTypeImpl(java.lang.reflect.ParameterizedType, TypeImpl):
    def __init__(self, rawType: typing.Type[java.lang.Object], ownerType: java.lang.reflect.Type, typeArguments: java.util.List[java.lang.reflect.Type], /) -> None: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getActualTypeArguments(self) -> java.chaquopy.JavaArray[java.lang.reflect.Type]: ...
    def getOwnerType(self) -> java.lang.reflect.Type: ...
    def getRawType(self) -> java.lang.reflect.Type: ...
    def getTypeName(self) -> str: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class TypeImpl(java.lang.reflect.Type):
    def getTypeName(self) -> str: ...

class TypeOfKt(java.lang.Object): ...

class TypeVariableImpl(java.lang.reflect.TypeVariable[java.lang.reflect.GenericDeclaration], TypeImpl):
    def __init__(self, typeParameter: KTypeParameter, /) -> None: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    _getAnnotation__T = typing.TypeVar('_getAnnotation__T')  # <T>
    def getAnnotation(self, annotationClass: typing.Type[_getAnnotation__T], /) -> _getAnnotation__T: ...
    def getAnnotations(self) -> java.chaquopy.JavaArray[java.lang.annotation.Annotation]: ...
    def getBounds(self) -> java.chaquopy.JavaArray[java.lang.reflect.Type]: ...
    def getDeclaredAnnotations(self) -> java.chaquopy.JavaArray[java.lang.annotation.Annotation]: ...
    def getGenericDeclaration(self) -> java.lang.reflect.GenericDeclaration: ...
    def getName(self) -> str: ...
    def getTypeName(self) -> str: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class TypesJVMKt(java.lang.Object):
    @staticmethod
    def getJavaType(this_javaType: KType, /) -> java.lang.reflect.Type: ...

class WildcardTypeImpl(java.lang.reflect.WildcardType, TypeImpl):
    Companion: typing.ClassVar[WildcardTypeImpl.Companion] = ...
    def __init__(self, upperBound: java.lang.reflect.Type, lowerBound: java.lang.reflect.Type, /) -> None: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getLowerBounds(self) -> java.chaquopy.JavaArray[java.lang.reflect.Type]: ...
    def getTypeName(self) -> str: ...
    def getUpperBounds(self) -> java.chaquopy.JavaArray[java.lang.reflect.Type]: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

    class Companion(java.lang.Object):
        def getSTAR(self) -> WildcardTypeImpl: ...
