import android.graphics
import java
import java.lang
import typing



class IGeoPoint(java.lang.Object):
    def getLatitude(self) -> float: ...
    def getLatitudeE6(self) -> int: ...
    def getLongitude(self) -> float: ...
    def getLongitudeE6(self) -> int: ...

class IMapController(java.lang.Object):
    @typing.overload
    def animateTo(self, arg1: IGeoPoint, /) -> None: ...
    @typing.overload
    def animateTo(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def animateTo(self, arg1: IGeoPoint, arg2: float | java.jdouble | java.lang.Double, arg3: int | java.jlong | java.lang.Long, /) -> None: ...
    @typing.overload
    def animateTo(self, arg1: IGeoPoint, arg2: float | java.jdouble | java.lang.Double, arg3: int | java.jlong | java.lang.Long, arg4: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def animateTo(self, arg1: IGeoPoint, arg2: float | java.jdouble | java.lang.Double, arg3: int | java.jlong | java.lang.Long, arg4: float | java.jfloat | java.lang.Float, arg5: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def scrollBy(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCenter(self, arg1: IGeoPoint, /) -> None: ...
    @typing.overload
    def setZoom(self, arg1: float | java.jdouble | java.lang.Double, /) -> float: ...
    @typing.overload
    def setZoom(self, arg1: int | java.jint | java.lang.Integer, /) -> int: ...
    def stopAnimation(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def stopPanning(self) -> None: ...
    @typing.overload
    def zoomIn(self) -> bool: ...
    @typing.overload
    def zoomIn(self, arg1: int | java.jlong | java.lang.Long, /) -> bool: ...
    @typing.overload
    def zoomInFixing(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def zoomInFixing(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jlong | java.lang.Long, /) -> bool: ...
    @typing.overload
    def zoomOut(self) -> bool: ...
    @typing.overload
    def zoomOut(self, arg1: int | java.jlong | java.lang.Long, /) -> bool: ...
    def zoomOutFixing(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def zoomTo(self, arg1: float | java.jdouble | java.lang.Double, /) -> bool: ...
    @typing.overload
    def zoomTo(self, arg1: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def zoomTo(self, arg1: float | java.jdouble | java.lang.Double, arg2: int | java.jlong | java.lang.Long, /) -> bool: ...
    @typing.overload
    def zoomTo(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jlong | java.lang.Long, /) -> bool: ...
    @typing.overload
    def zoomToFixing(self, arg1: float | java.jdouble | java.lang.Double, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def zoomToFixing(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def zoomToFixing(self, arg1: float | java.jdouble | java.lang.Double, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, arg4: int | java.jlong | java.lang.Long, /) -> bool: ...
    @typing.overload
    def zoomToFixing(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, arg4: int | java.jlong | java.lang.Long, /) -> bool: ...
    @typing.overload
    def zoomToSpan(self, arg1: float | java.jdouble | java.lang.Double, arg2: float | java.jdouble | java.lang.Double, /) -> None: ...
    @typing.overload
    def zoomToSpan(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, /) -> None: ...

class IMapView(java.lang.Object):
    LOGTAG: typing.ClassVar[str] = ...
    def getController(self) -> IMapController: ...
    def getLatitudeSpanDouble(self) -> float: ...
    def getLongitudeSpanDouble(self) -> float: ...
    def getMapCenter(self) -> IGeoPoint: ...
    def getMaxZoomLevel(self) -> float: ...
    def getProjection(self) -> IProjection: ...
    def getZoomLevel(self) -> int: ...
    def getZoomLevelDouble(self) -> float: ...
    def setBackgroundColor(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...

class IProjection(java.lang.Object):
    def fromPixels(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, /) -> IGeoPoint: ...
    def getNorthEast(self) -> IGeoPoint: ...
    def getSouthWest(self) -> IGeoPoint: ...
    def metersToEquatorPixels(self, arg1: float | java.jfloat | java.lang.Float, /) -> float: ...
    def toPixels(self, arg1: IGeoPoint, arg2: android.graphics.Point, /) -> android.graphics.Point: ...
