import typing

import java.lang

class OpenStreetMapContributorConstants(java.lang.Object):
    NOT_SET: typing.ClassVar[int] = ...
    OSM_USERNAME: typing.ClassVar[str] = ...
    OSM_PASSWORD: typing.ClassVar[str] = ...
    MINGEOPOINTS_FOR_OSM_CONTRIBUTION: typing.ClassVar[int] = ...
    MINDIAGONALMETERS_FOR_OSM_CONTRIBUTION: typing.ClassVar[int] = ...
    OSM_CREATOR_INFO: typing.ClassVar[str] = ...
