import typing

import android.content
import android.content.res
import android.graphics
import android.graphics.drawable
import android.os
import android.util
import android.view
import android.view.accessibility
import android.widget
import androidx.appcompat.widget
import com.google.android.material.shape
import java
import java.chaquopy
import java.lang
import java.lang.annotation
import java.util

class MaterialButton(androidx.appcompat.widget.AppCompatButton, android.widget.Checkable, com.google.android.material.shape.Shapeable):
    ICON_GRAVITY_START: typing.ClassVar[int] = ...
    ICON_GRAVITY_TEXT_START: typing.ClassVar[int] = ...
    ICON_GRAVITY_END: typing.ClassVar[int] = ...
    ICON_GRAVITY_TEXT_END: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def addOnCheckedChangeListener(self, listener: MaterialButton.OnCheckedChangeListener, /) -> None: ...
    def clearOnCheckedChangeListeners(self) -> None: ...
    def getBackgroundTintList(self) -> android.content.res.ColorStateList: ...
    def getBackgroundTintMode(self) -> android.graphics.PorterDuff.Mode: ...
    def getCornerRadius(self) -> int: ...
    def getIcon(self) -> android.graphics.drawable.Drawable: ...
    def getIconGravity(self) -> int: ...
    def getIconPadding(self) -> int: ...
    def getIconSize(self) -> int: ...
    def getIconTint(self) -> android.content.res.ColorStateList: ...
    def getIconTintMode(self) -> android.graphics.PorterDuff.Mode: ...
    def getRippleColor(self) -> android.content.res.ColorStateList: ...
    def getShapeAppearanceModel(self) -> com.google.android.material.shape.ShapeAppearanceModel: ...
    def getStrokeColor(self) -> android.content.res.ColorStateList: ...
    def getStrokeWidth(self) -> int: ...
    def getSupportBackgroundTintList(self) -> android.content.res.ColorStateList: ...
    def getSupportBackgroundTintMode(self) -> android.graphics.PorterDuff.Mode: ...
    def isCheckable(self) -> bool: ...
    def isChecked(self) -> bool: ...
    def onAttachedToWindow(self) -> None: ...
    def onCreateDrawableState(self, extraSpace: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJInt: ...
    def onInitializeAccessibilityEvent(self, accessibilityEvent: android.view.accessibility.AccessibilityEvent, /) -> None: ...
    def onInitializeAccessibilityNodeInfo(self, info: android.view.accessibility.AccessibilityNodeInfo, /) -> None: ...
    def onLayout(self, changed: bool | java.jboolean | java.lang.Boolean, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def onRestoreInstanceState(self, state: android.os.Parcelable, /) -> None: ...
    def onSaveInstanceState(self) -> android.os.Parcelable: ...
    def onTextChanged(self, charSequence: java.lang.CharSequence, i: int | java.jint | java.lang.Integer, i1: int | java.jint | java.lang.Integer, i2: int | java.jint | java.lang.Integer, /) -> None: ...
    def performClick(self) -> bool: ...
    def removeOnCheckedChangeListener(self, listener: MaterialButton.OnCheckedChangeListener, /) -> None: ...
    def setBackground(self, background: android.graphics.drawable.Drawable, /) -> None: ...
    def setBackgroundColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBackgroundDrawable(self, background: android.graphics.drawable.Drawable, /) -> None: ...
    def setBackgroundResource(self, backgroundResourceId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBackgroundTintList(self, tintList: android.content.res.ColorStateList, /) -> None: ...
    def setBackgroundTintMode(self, tintMode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def setCheckable(self, checkable: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setChecked(self, checked: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setCornerRadius(self, cornerRadius: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCornerRadiusResource(self, cornerRadiusResourceId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setElevation(self, elevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setIcon(self, icon: android.graphics.drawable.Drawable, /) -> None: ...
    def setIconGravity(self, iconGravity: int | java.jint | java.lang.Integer, /) -> None: ...
    def setIconPadding(self, iconPadding: int | java.jint | java.lang.Integer, /) -> None: ...
    def setIconResource(self, iconResourceId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setIconSize(self, iconSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def setIconTint(self, iconTint: android.content.res.ColorStateList, /) -> None: ...
    def setIconTintMode(self, iconTintMode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def setIconTintResource(self, iconTintResourceId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPressed(self, pressed: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setRippleColor(self, rippleColor: android.content.res.ColorStateList, /) -> None: ...
    def setRippleColorResource(self, rippleColorResourceId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setShapeAppearanceModel(self, shapeAppearanceModel: com.google.android.material.shape.ShapeAppearanceModel, /) -> None: ...
    def setStrokeColor(self, strokeColor: android.content.res.ColorStateList, /) -> None: ...
    def setStrokeColorResource(self, strokeColorResourceId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setStrokeWidth(self, strokeWidth: int | java.jint | java.lang.Integer, /) -> None: ...
    def setStrokeWidthResource(self, strokeWidthResourceId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setSupportBackgroundTintList(self, tint: android.content.res.ColorStateList, /) -> None: ...
    def setSupportBackgroundTintMode(self, tintMode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def toggle(self) -> None: ...

    class IconGravity(java.lang.annotation.Annotation): ...

    class OnCheckedChangeListener(java.lang.Object):
        def onCheckedChanged(self, arg1: MaterialButton, arg2: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class MaterialButtonHelper(java.lang.Object):
    def getMaskDrawable(self) -> com.google.android.material.shape.Shapeable: ...

class MaterialButtonToggleGroup(android.widget.LinearLayout):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def addOnButtonCheckedListener(self, listener: MaterialButtonToggleGroup.OnButtonCheckedListener, /) -> None: ...
    def addView(self, child: android.view.View, index: int | java.jint | java.lang.Integer, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    def check(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def clearChecked(self) -> None: ...
    def clearOnButtonCheckedListeners(self) -> None: ...
    def dispatchDraw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getAccessibilityClassName(self) -> java.lang.CharSequence: ...
    def getCheckedButtonId(self) -> int: ...
    def getCheckedButtonIds(self) -> java.util.List[java.lang.Integer]: ...
    def getChildDrawingOrder(self, childCount: int | java.jint | java.lang.Integer, i: int | java.jint | java.lang.Integer, /) -> int: ...
    def isSelectionRequired(self) -> bool: ...
    def isSingleSelection(self) -> bool: ...
    def onFinishInflate(self) -> None: ...
    def onInitializeAccessibilityNodeInfo(self, info: android.view.accessibility.AccessibilityNodeInfo, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def onViewRemoved(self, child: android.view.View, /) -> None: ...
    def removeOnButtonCheckedListener(self, listener: MaterialButtonToggleGroup.OnButtonCheckedListener, /) -> None: ...
    def setSelectionRequired(self, selectionRequired: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def setSingleSelection(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setSingleSelection(self, singleSelection: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def uncheck(self, id: int | java.jint | java.lang.Integer, /) -> None: ...

    class OnButtonCheckedListener(java.lang.Object):
        def onButtonChecked(self, arg1: MaterialButtonToggleGroup, arg2: int | java.jint | java.lang.Integer, arg3: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
