import typing

import java.lang
import kotlin
import kotlin.jvm.functions
import kotlin.reflect

class Delegates(java.lang.Object):
    INSTANCE: typing.ClassVar[Delegates] = ...
    def notNull(self) -> ReadWriteProperty[java.lang.Object, java.lang.Object]: ...
    _observable__T = typing.TypeVar('_observable__T')  # <T>
    def observable(self, initialValue: _observable__T, onChange: kotlin.jvm.functions.Function3[kotlin.reflect.KProperty[java.lang.Object], _observable__T, _observable__T, kotlin.Unit], /) -> ReadWriteProperty[java.lang.Object, _observable__T]: ...
    _vetoable__T = typing.TypeVar('_vetoable__T')  # <T>
    def vetoable(self, initialValue: _vetoable__T, onChange: kotlin.jvm.functions.Function3[kotlin.reflect.KProperty[java.lang.Object], _vetoable__T, _vetoable__T, java.lang.Boolean], /) -> ReadWriteProperty[java.lang.Object, _vetoable__T]: ...

_NotNullVar__T = typing.TypeVar('_NotNullVar__T')  # <T>
class NotNullVar(ReadWriteProperty[java.lang.Object, _NotNullVar__T], typing.Generic[_NotNullVar__T]):
    def __init__(self) -> None: ...
    def getValue(self, thisRef: java.lang.Object | int | bool | float | str, property: kotlin.reflect.KProperty[java.lang.Object], /) -> _NotNullVar__T: ...
    def setValue(self, thisRef: java.lang.Object | int | bool | float | str, property: kotlin.reflect.KProperty[java.lang.Object], value: _NotNullVar__T, /) -> None: ...

_ObservableProperty__T = typing.TypeVar('_ObservableProperty__T')  # <T>
class ObservableProperty(ReadWriteProperty[java.lang.Object, _ObservableProperty__T], typing.Generic[_ObservableProperty__T]):
    def __init__(self, initialValue: _ObservableProperty__T, /) -> None: ...
    def afterChange(self, property: kotlin.reflect.KProperty[java.lang.Object], oldValue: _ObservableProperty__T, newValue: _ObservableProperty__T, /) -> None: ...
    def beforeChange(self, property: kotlin.reflect.KProperty[java.lang.Object], oldValue: _ObservableProperty__T, newValue: _ObservableProperty__T, /) -> bool: ...
    def getValue(self, thisRef: java.lang.Object | int | bool | float | str, property: kotlin.reflect.KProperty[java.lang.Object], /) -> _ObservableProperty__T: ...
    def setValue(self, thisRef: java.lang.Object | int | bool | float | str, property: kotlin.reflect.KProperty[java.lang.Object], value: _ObservableProperty__T, /) -> None: ...

_ReadOnlyProperty__R = typing.TypeVar('_ReadOnlyProperty__R')  # <R>
_ReadOnlyProperty__T = typing.TypeVar('_ReadOnlyProperty__T')  # <T>
class ReadOnlyProperty(java.lang.Object, typing.Generic[_ReadOnlyProperty__R, _ReadOnlyProperty__T]):
    def getValue(self, arg1: _ReadOnlyProperty__R, arg2: kotlin.reflect.KProperty[java.lang.Object], /) -> _ReadOnlyProperty__T: ...

_ReadWriteProperty__R = typing.TypeVar('_ReadWriteProperty__R')  # <R>
_ReadWriteProperty__T = typing.TypeVar('_ReadWriteProperty__T')  # <T>
class ReadWriteProperty(java.lang.Object, typing.Generic[_ReadWriteProperty__R, _ReadWriteProperty__T]):
    def getValue(self, arg1: _ReadWriteProperty__R, arg2: kotlin.reflect.KProperty[java.lang.Object], /) -> _ReadWriteProperty__T: ...
    def setValue(self, arg1: _ReadWriteProperty__R, arg2: kotlin.reflect.KProperty[java.lang.Object], arg3: _ReadWriteProperty__T, /) -> None: ...
