import android.content
import android.util
import android.view
import com.google.android.material.navigation
import java
import java.lang
import java.lang.annotation
import typing



class BottomNavigationItemView(com.google.android.material.navigation.NavigationBarItemView):
    def __init__(self, context: android.content.Context, /) -> None: ...
    def getItemDefaultMarginResId(self) -> int: ...
    def getItemLayoutResId(self) -> int: ...

class BottomNavigationMenuView(com.google.android.material.navigation.NavigationBarMenuView):
    def __init__(self, context: android.content.Context, /) -> None: ...
    def createNavigationBarItemView(self, context: android.content.Context, /) -> com.google.android.material.navigation.NavigationBarItemView: ...
    def isItemHorizontalTranslationEnabled(self) -> bool: ...
    def onLayout(self, changed: bool | java.jboolean | java.lang.Boolean, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemHorizontalTranslationEnabled(self, itemHorizontalTranslationEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class BottomNavigationView(com.google.android.material.navigation.NavigationBarView):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, /) -> None: ...
    def createNavigationBarMenuView(self, context: android.content.Context, /) -> com.google.android.material.navigation.NavigationBarMenuView: ...
    def getMaxItemCount(self) -> int: ...
    def isItemHorizontalTranslationEnabled(self) -> bool: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def onTouchEvent(self, event: android.view.MotionEvent, /) -> bool: ...
    def setItemHorizontalTranslationEnabled(self, itemHorizontalTranslationEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setOnNavigationItemReselectedListener(self, listener: BottomNavigationView.OnNavigationItemReselectedListener, /) -> None: ...
    def setOnNavigationItemSelectedListener(self, listener: BottomNavigationView.OnNavigationItemSelectedListener, /) -> None: ...

    class OnNavigationItemReselectedListener(com.google.android.material.navigation.NavigationBarView.OnItemReselectedListener): ...

    class OnNavigationItemSelectedListener(com.google.android.material.navigation.NavigationBarView.OnItemSelectedListener): ...

class LabelVisibilityMode(java.lang.annotation.Annotation):
    LABEL_VISIBILITY_AUTO: typing.ClassVar[int] = ...
    LABEL_VISIBILITY_SELECTED: typing.ClassVar[int] = ...
    LABEL_VISIBILITY_LABELED: typing.ClassVar[int] = ...
    LABEL_VISIBILITY_UNLABELED: typing.ClassVar[int] = ...
