import typing

import android.app
import android.view
import androidx.lifecycle.viewmodel
import java.io
import java.lang
import kotlin
import kotlin.jvm.functions
import kotlin.reflect

class AndroidViewModel(ViewModel):
    def __init__(self, application: android.app.Application, /) -> None: ...
    def getApplication(self) -> android.app.Application: ...

class HasDefaultViewModelProviderFactory(java.lang.Object):
    def getDefaultViewModelCreationExtras(self) -> androidx.lifecycle.viewmodel.CreationExtras: ...
    def getDefaultViewModelProviderFactory(self) -> ViewModelProvider.Factory: ...

class ViewModel(java.lang.Object):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, *closeables: java.io.Closeable) -> None: ...
    def addCloseable(self, closeable: java.io.Closeable, /) -> None: ...
    def onCleared(self) -> None: ...

_ViewModelLazy__VM = typing.TypeVar('_ViewModelLazy__VM', bound=ViewModel)  # <VM>
class ViewModelLazy(kotlin.Lazy[_ViewModelLazy__VM], typing.Generic[_ViewModelLazy__VM]):
    @typing.overload
    def __init__(self, viewModelClass: kotlin.reflect.KClass[_ViewModelLazy__VM], storeProducer: kotlin.jvm.functions.Function0[ViewModelStore], factoryProducer: kotlin.jvm.functions.Function0[ViewModelProvider.Factory], /) -> None: ...
    @typing.overload
    def __init__(self, viewModelClass: kotlin.reflect.KClass[_ViewModelLazy__VM], storeProducer: kotlin.jvm.functions.Function0[ViewModelStore], factoryProducer: kotlin.jvm.functions.Function0[ViewModelProvider.Factory], extrasProducer: kotlin.jvm.functions.Function0[androidx.lifecycle.viewmodel.CreationExtras], /) -> None: ...
    def getValue(self) -> _ViewModelLazy__VM: ...
    def isInitialized(self) -> bool: ...

class ViewModelProvider(java.lang.Object):
    @typing.overload
    def __init__(self, owner: ViewModelStoreOwner, /) -> None: ...
    @typing.overload
    def __init__(self, store: ViewModelStore, factory: ViewModelProvider.Factory, /) -> None: ...
    @typing.overload
    def __init__(self, owner: ViewModelStoreOwner, factory: ViewModelProvider.Factory, /) -> None: ...
    @typing.overload
    def __init__(self, store: ViewModelStore, factory: ViewModelProvider.Factory, defaultCreationExtras: androidx.lifecycle.viewmodel.CreationExtras, /) -> None: ...
    _get_0__T = typing.TypeVar('_get_0__T', bound=ViewModel)  # <T>
    _get_1__T = typing.TypeVar('_get_1__T', bound=ViewModel)  # <T>
    @typing.overload
    def get(self, modelClass: typing.Type[_get_0__T], /) -> _get_0__T: ...
    @typing.overload
    def get(self, key: str | java.lang.String, modelClass: typing.Type[_get_1__T], /) -> _get_1__T: ...

    class Factory(java.lang.Object):
        Companion: typing.ClassVar[ViewModelProvider.Factory.Companion] = ...
        _create_0__T = typing.TypeVar('_create_0__T', bound=ViewModel)  # <T>
        _create_1__T = typing.TypeVar('_create_1__T', bound=ViewModel)  # <T>
        @typing.overload
        def create(self, modelClass: typing.Type[_create_0__T], /) -> _create_0__T: ...
        @typing.overload
        def create(self, modelClass: typing.Type[_create_1__T], extras: androidx.lifecycle.viewmodel.CreationExtras, /) -> _create_1__T: ...
        @staticmethod
        def from_(*initializers: androidx.lifecycle.viewmodel.ViewModelInitializer[java.lang.Object]) -> ViewModelProvider.Factory: ...

        class Companion(java.lang.Object):
            def from_(self, *initializers: androidx.lifecycle.viewmodel.ViewModelInitializer[java.lang.Object]) -> ViewModelProvider.Factory: ...

    class OnRequeryFactory(java.lang.Object):
        def __init__(self) -> None: ...
        def onRequery(self, viewModel: ViewModel, /) -> None: ...

    class NewInstanceFactory(ViewModelProvider.Factory):
        Companion: typing.ClassVar[ViewModelProvider.NewInstanceFactory.Companion] = ...
        VIEW_MODEL_KEY: typing.ClassVar[androidx.lifecycle.viewmodel.CreationExtras.Key[java.lang.String]] = ...
        def __init__(self) -> None: ...
        _create__T = typing.TypeVar('_create__T', bound=ViewModel)  # <T>
        def create(self, modelClass: typing.Type[_create__T], /) -> _create__T: ...
        @staticmethod
        def getInstance() -> ViewModelProvider.NewInstanceFactory: ...

        class Companion(java.lang.Object):
            def getInstance(self) -> ViewModelProvider.NewInstanceFactory: ...

    class AndroidViewModelFactory(ViewModelProvider.NewInstanceFactory):
        Companion: typing.ClassVar[ViewModelProvider.AndroidViewModelFactory.Companion] = ...
        DEFAULT_KEY: typing.ClassVar[str] = ...
        APPLICATION_KEY: typing.ClassVar[androidx.lifecycle.viewmodel.CreationExtras.Key[android.app.Application]] = ...
        @typing.overload
        def __init__(self) -> None: ...
        @typing.overload
        def __init__(self, application: android.app.Application, /) -> None: ...
        _create_0__T = typing.TypeVar('_create_0__T', bound=ViewModel)  # <T>
        _create_1__T = typing.TypeVar('_create_1__T', bound=ViewModel)  # <T>
        @typing.overload
        def create(self, modelClass: typing.Type[_create_0__T], /) -> _create_0__T: ...
        @typing.overload
        def create(self, modelClass: typing.Type[_create_1__T], extras: androidx.lifecycle.viewmodel.CreationExtras, /) -> _create_1__T: ...
        @staticmethod
        def getInstance(application: android.app.Application, /) -> ViewModelProvider.AndroidViewModelFactory: ...

        class Companion(java.lang.Object):
            def getInstance(self, application: android.app.Application, /) -> ViewModelProvider.AndroidViewModelFactory: ...

class ViewModelProviderGetKt(java.lang.Object):
    @staticmethod
    def defaultCreationExtras(owner: ViewModelStoreOwner, /) -> androidx.lifecycle.viewmodel.CreationExtras: ...

class ViewModelStore(java.lang.Object):
    def __init__(self) -> None: ...
    def clear(self) -> None: ...

class ViewModelStoreOwner(java.lang.Object):
    def getViewModelStore(self) -> ViewModelStore: ...

class ViewTreeViewModelKt(java.lang.Object):
    @staticmethod
    def findViewTreeViewModelStoreOwner(this_findViewTreeViewModelStoreOwner: android.view.View, /) -> ViewModelStoreOwner: ...

class ViewTreeViewModelStoreOwner(java.lang.Object):
    @staticmethod
    def get(view: android.view.View, /) -> ViewModelStoreOwner: ...
    @staticmethod
    def set(view: android.view.View, viewModelStoreOwner: ViewModelStoreOwner, /) -> None: ...
