import android.animation
import java.lang
import kotlin
import kotlin.jvm.functions

class AnimatorKt(java.lang.Object):
    @staticmethod
    def addListener(receiver: android.animation.Animator, onEnd: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], onStart: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], onCancel: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], onRepeat: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], /) -> android.animation.Animator.AnimatorListener: ...
    @staticmethod
    def addPauseListener(receiver: android.animation.Animator, onResume: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], onPause: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], /) -> android.animation.Animator.AnimatorPauseListener: ...
    @staticmethod
    def doOnCancel(receiver: android.animation.Animator, action: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], /) -> android.animation.Animator.AnimatorListener: ...
    @staticmethod
    def doOnEnd(receiver: android.animation.Animator, action: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], /) -> android.animation.Animator.AnimatorListener: ...
    @staticmethod
    def doOnPause(receiver: android.animation.Animator, action: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], /) -> android.animation.Animator.AnimatorPauseListener: ...
    @staticmethod
    def doOnRepeat(receiver: android.animation.Animator, action: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], /) -> android.animation.Animator.AnimatorListener: ...
    @staticmethod
    def doOnResume(receiver: android.animation.Animator, action: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], /) -> android.animation.Animator.AnimatorPauseListener: ...
    @staticmethod
    def doOnStart(receiver: android.animation.Animator, action: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], /) -> android.animation.Animator.AnimatorListener: ...
