import java.lang
import java.util
import jet
import jet.modules

class AllModules(java.lang.ThreadLocal[java.util.ArrayList[Module]], jet.JetObject):
    def initialValue(self) -> java.util.ArrayList[Module]: ...

class AnnotationsPathBuilder(jet.JetObject):
    def __init__(self, parent: ModuleBuilder, /) -> None: ...
    def getParent(self) -> ModuleBuilder: ...
    def plusAssign(self, name: str | java.lang.String, /) -> None: ...

class ClasspathBuilder(jet.JetObject):
    def __init__(self, parent: ModuleBuilder, /) -> None: ...
    def getParent(self) -> ModuleBuilder: ...
    def plusAssign(self, name: str | java.lang.String, /) -> None: ...

class Module(jet.JetObject):
    def getAnnotationsRoots(self) -> java.util.List[java.lang.String]: ...
    def getClasspathRoots(self) -> java.util.List[java.lang.String]: ...
    def getModuleName(self) -> str: ...
    def getOutputDirectory(self) -> str: ...
    def getSourceFiles(self) -> java.util.List[java.lang.String]: ...

class ModuleBuilder(jet.JetObject, jet.modules.Module, Module):
    def __init__(self, name: str | java.lang.String, outputDir: str | java.lang.String, /) -> None: ...
    def addAnnotationsPathEntry(self, name: str | java.lang.String, /) -> None: ...
    def addClasspathEntry(self, name: str | java.lang.String, /) -> None: ...
    def addSourceFiles(self, pattern: str | java.lang.String, /) -> None: ...
    def getAnnotationsPath(self) -> AnnotationsPathBuilder: ...
    def getAnnotationsRoots(self) -> java.util.List[java.lang.String]: ...
    def getClasspath(self) -> ClasspathBuilder: ...
    def getClasspathRoots(self) -> java.util.List[java.lang.String]: ...
    def getModuleName(self) -> str: ...
    def getName(self) -> str: ...
    def getOutputDir(self) -> str: ...
    def getOutputDirectory(self) -> str: ...
    def getSourceFiles(self) -> java.util.List[java.lang.String]: ...
    def getSources(self) -> SourcesBuilder: ...

class ModulesPackage-ModuleBuilder-9d472008(java.lang.Object):
    @staticmethod
    def module(name: str | java.lang.String, outputDir: str | java.lang.String, callback: jet.ExtensionFunction0[ModuleBuilder, jet.Unit], /) -> None: ...

class ModulesPackage(java.lang.Object):
    @staticmethod
    def module(name: str | java.lang.String, outputDir: str | java.lang.String, callback: jet.ExtensionFunction0[ModuleBuilder, jet.Unit], /) -> None: ...

class SourcesBuilder(jet.JetObject):
    def __init__(self, parent: ModuleBuilder, /) -> None: ...
    def getParent(self) -> ModuleBuilder: ...
    def plusAssign(self, pattern: str | java.lang.String, /) -> None: ...
