import typing

import android.content
import android.content.res
import android.graphics
import android.net
import android.os
import androidx.core.content.res
import androidx.core.provider
import java
import java.chaquopy
import java.io
import java.lang
import java.lang.reflect
import java.nio
import java.util

class BitmapCompat(java.lang.Object):
    @staticmethod
    def getAllocationByteCount(bitmap: android.graphics.Bitmap, /) -> int: ...
    @staticmethod
    def hasMipMap(bitmap: android.graphics.Bitmap, /) -> bool: ...
    @staticmethod
    def setHasMipMap(bitmap: android.graphics.Bitmap, hasMipMap: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class ColorUtils(java.lang.Object):
    @staticmethod
    def HSLToColor(hsl: java.chaquopy.JavaArrayJFloat, /) -> int: ...
    @staticmethod
    def LABToColor(l: float | java.jdouble | java.lang.Double, a: float | java.jdouble | java.lang.Double, b: float | java.jdouble | java.lang.Double, /) -> int: ...
    @staticmethod
    def LABToXYZ(l: float | java.jdouble | java.lang.Double, a: float | java.jdouble | java.lang.Double, b: float | java.jdouble | java.lang.Double, outXyz: java.chaquopy.JavaArrayJDouble, /) -> None: ...
    @staticmethod
    def RGBToHSL(r: int | java.jint | java.lang.Integer, g: int | java.jint | java.lang.Integer, b: int | java.jint | java.lang.Integer, outHsl: java.chaquopy.JavaArrayJFloat, /) -> None: ...
    @staticmethod
    def RGBToLAB(r: int | java.jint | java.lang.Integer, g: int | java.jint | java.lang.Integer, b: int | java.jint | java.lang.Integer, outLab: java.chaquopy.JavaArrayJDouble, /) -> None: ...
    @staticmethod
    def RGBToXYZ(r: int | java.jint | java.lang.Integer, g: int | java.jint | java.lang.Integer, b: int | java.jint | java.lang.Integer, outXyz: java.chaquopy.JavaArrayJDouble, /) -> None: ...
    @staticmethod
    def XYZToColor(x: float | java.jdouble | java.lang.Double, y: float | java.jdouble | java.lang.Double, z: float | java.jdouble | java.lang.Double, /) -> int: ...
    @staticmethod
    def XYZToLAB(x: float | java.jdouble | java.lang.Double, y: float | java.jdouble | java.lang.Double, z: float | java.jdouble | java.lang.Double, outLab: java.chaquopy.JavaArrayJDouble, /) -> None: ...
    @staticmethod
    def blendARGB(color1: int | java.jint | java.lang.Integer, color2: int | java.jint | java.lang.Integer, ratio: float | java.jfloat | java.lang.Float, /) -> int: ...
    @staticmethod
    def blendHSL(hsl1: java.chaquopy.JavaArrayJFloat, hsl2: java.chaquopy.JavaArrayJFloat, ratio: float | java.jfloat | java.lang.Float, outResult: java.chaquopy.JavaArrayJFloat, /) -> None: ...
    @staticmethod
    def blendLAB(lab1: java.chaquopy.JavaArrayJDouble, lab2: java.chaquopy.JavaArrayJDouble, ratio: float | java.jdouble | java.lang.Double, outResult: java.chaquopy.JavaArrayJDouble, /) -> None: ...
    @staticmethod
    def calculateContrast(foreground: int | java.jint | java.lang.Integer, background: int | java.jint | java.lang.Integer, /) -> float: ...
    @staticmethod
    def calculateLuminance(color: int | java.jint | java.lang.Integer, /) -> float: ...
    @staticmethod
    def calculateMinimumAlpha(foreground: int | java.jint | java.lang.Integer, background: int | java.jint | java.lang.Integer, minContrastRatio: float | java.jfloat | java.lang.Float, /) -> int: ...
    @staticmethod
    def colorToHSL(color: int | java.jint | java.lang.Integer, outHsl: java.chaquopy.JavaArrayJFloat, /) -> None: ...
    @staticmethod
    def colorToLAB(color: int | java.jint | java.lang.Integer, outLab: java.chaquopy.JavaArrayJDouble, /) -> None: ...
    @staticmethod
    def colorToXYZ(color: int | java.jint | java.lang.Integer, outXyz: java.chaquopy.JavaArrayJDouble, /) -> None: ...
    @typing.overload
    @staticmethod
    def compositeColors(foreground: int | java.jint | java.lang.Integer, background: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def compositeColors(foreground: android.graphics.Color, background: android.graphics.Color, /) -> android.graphics.Color: ...
    @staticmethod
    def distanceEuclidean(labX: java.chaquopy.JavaArrayJDouble, labY: java.chaquopy.JavaArrayJDouble, /) -> float: ...
    @staticmethod
    def setAlphaComponent(color: int | java.jint | java.lang.Integer, alpha: int | java.jint | java.lang.Integer, /) -> int: ...

class PaintCompat(java.lang.Object):
    @staticmethod
    def hasGlyph(paint: android.graphics.Paint, string: str | java.lang.String, /) -> bool: ...

class PathParser(java.lang.Object):
    @staticmethod
    def canMorph(nodesFrom: java.chaquopy.JavaArray[PathParser.PathDataNode], nodesTo: java.chaquopy.JavaArray[PathParser.PathDataNode], /) -> bool: ...
    @staticmethod
    def createNodesFromPathData(pathData: str | java.lang.String, /) -> java.chaquopy.JavaArray[PathParser.PathDataNode]: ...
    @staticmethod
    def createPathFromPathData(pathData: str | java.lang.String, /) -> android.graphics.Path: ...
    @staticmethod
    def deepCopyNodes(source: java.chaquopy.JavaArray[PathParser.PathDataNode], /) -> java.chaquopy.JavaArray[PathParser.PathDataNode]: ...
    @staticmethod
    def updateNodes(target: java.chaquopy.JavaArray[PathParser.PathDataNode], source: java.chaquopy.JavaArray[PathParser.PathDataNode], /) -> None: ...

    class PathDataNode(java.lang.Object):
        mType: str = ...
        mParams: java.chaquopy.JavaArrayJFloat = ...
        def interpolatePathDataNode(self, nodeFrom: PathParser.PathDataNode, nodeTo: PathParser.PathDataNode, fraction: float | java.jfloat | java.lang.Float, /) -> None: ...
        @staticmethod
        def nodesToPath(node: java.chaquopy.JavaArray[PathParser.PathDataNode], path: android.graphics.Path, /) -> None: ...

class PathSegment(java.lang.Object):
    def __init__(self, start: android.graphics.PointF, startFraction: float | java.jfloat | java.lang.Float, end: android.graphics.PointF, endFraction: float | java.jfloat | java.lang.Float, /) -> None: ...
    def equals(self, o: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getEnd(self) -> android.graphics.PointF: ...
    def getEndFraction(self) -> float: ...
    def getStart(self) -> android.graphics.PointF: ...
    def getStartFraction(self) -> float: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class PathUtils(java.lang.Object):
    @typing.overload
    @staticmethod
    def flatten(path: android.graphics.Path, /) -> java.util.Collection[PathSegment]: ...
    @typing.overload
    @staticmethod
    def flatten(path: android.graphics.Path, error: float | java.jfloat | java.lang.Float, /) -> java.util.Collection[PathSegment]: ...

class TypefaceCompat(java.lang.Object):
    @staticmethod
    def createFromFontInfo(context: android.content.Context, cancellationSignal: android.os.CancellationSignal, fonts: java.chaquopy.JavaArray[androidx.core.provider.FontsContractCompat.FontInfo], style: int | java.jint | java.lang.Integer, /) -> android.graphics.Typeface: ...
    @staticmethod
    def createFromResourcesFamilyXml(context: android.content.Context, entry: androidx.core.content.res.FontResourcesParserCompat.FamilyResourceEntry, resources: android.content.res.Resources, id: int | java.jint | java.lang.Integer, style: int | java.jint | java.lang.Integer, fontCallback: androidx.core.content.res.ResourcesCompat.FontCallback, handler: android.os.Handler, isRequestFromLayoutInflator: bool | java.jboolean | java.lang.Boolean, /) -> android.graphics.Typeface: ...
    @staticmethod
    def createFromResourcesFontFile(context: android.content.Context, resources: android.content.res.Resources, id: int | java.jint | java.lang.Integer, path: str | java.lang.String, style: int | java.jint | java.lang.Integer, /) -> android.graphics.Typeface: ...
    @staticmethod
    def findFromCache(resources: android.content.res.Resources, id: int | java.jint | java.lang.Integer, style: int | java.jint | java.lang.Integer, /) -> android.graphics.Typeface: ...

class TypefaceCompatApi21Impl(TypefaceCompatBaseImpl):
    def createFromFontInfo(self, context: android.content.Context, cancellationSignal: android.os.CancellationSignal, fonts: java.chaquopy.JavaArray[androidx.core.provider.FontsContractCompat.FontInfo], style: int | java.jint | java.lang.Integer, /) -> android.graphics.Typeface: ...

class TypefaceCompatApi24Impl(TypefaceCompatBaseImpl):
    def createFromFontFamilyFilesResourceEntry(self, context: android.content.Context, entry: androidx.core.content.res.FontResourcesParserCompat.FontFamilyFilesResourceEntry, resources: android.content.res.Resources, style: int | java.jint | java.lang.Integer, /) -> android.graphics.Typeface: ...
    def createFromFontInfo(self, context: android.content.Context, cancellationSignal: android.os.CancellationSignal, fonts: java.chaquopy.JavaArray[androidx.core.provider.FontsContractCompat.FontInfo], style: int | java.jint | java.lang.Integer, /) -> android.graphics.Typeface: ...
    @staticmethod
    def isUsable() -> bool: ...

class TypefaceCompatApi26Impl(TypefaceCompatApi21Impl):
    mFontFamily: typing.Type = ...
    mFontFamilyCtor: java.lang.reflect.Constructor = ...
    mAddFontFromAssetManager: java.lang.reflect.Method = ...
    mAddFontFromBuffer: java.lang.reflect.Method = ...
    mFreeze: java.lang.reflect.Method = ...
    mAbortCreation: java.lang.reflect.Method = ...
    mCreateFromFamiliesWithDefault: java.lang.reflect.Method = ...
    def __init__(self) -> None: ...
    def createFromFamiliesWithDefault(self, family: java.lang.Object | int | bool | float | str, /) -> android.graphics.Typeface: ...
    def createFromFontFamilyFilesResourceEntry(self, context: android.content.Context, entry: androidx.core.content.res.FontResourcesParserCompat.FontFamilyFilesResourceEntry, resources: android.content.res.Resources, style: int | java.jint | java.lang.Integer, /) -> android.graphics.Typeface: ...
    def createFromFontInfo(self, context: android.content.Context, cancellationSignal: android.os.CancellationSignal, fonts: java.chaquopy.JavaArray[androidx.core.provider.FontsContractCompat.FontInfo], style: int | java.jint | java.lang.Integer, /) -> android.graphics.Typeface: ...
    def createFromResourcesFontFile(self, context: android.content.Context, resources: android.content.res.Resources, id: int | java.jint | java.lang.Integer, path: str | java.lang.String, style: int | java.jint | java.lang.Integer, /) -> android.graphics.Typeface: ...
    def obtainAbortCreationMethod(self, fontFamily: typing.Type, /) -> java.lang.reflect.Method: ...
    def obtainAddFontFromAssetManagerMethod(self, fontFamily: typing.Type, /) -> java.lang.reflect.Method: ...
    def obtainAddFontFromBufferMethod(self, fontFamily: typing.Type, /) -> java.lang.reflect.Method: ...
    def obtainCreateFromFamiliesWithDefaultMethod(self, fontFamily: typing.Type, /) -> java.lang.reflect.Method: ...
    def obtainFontFamily(self) -> typing.Type: ...
    def obtainFontFamilyCtor(self, fontFamily: typing.Type, /) -> java.lang.reflect.Constructor: ...
    def obtainFreezeMethod(self, fontFamily: typing.Type, /) -> java.lang.reflect.Method: ...

class TypefaceCompatApi28Impl(TypefaceCompatApi26Impl):
    def __init__(self) -> None: ...
    def createFromFamiliesWithDefault(self, family: java.lang.Object | int | bool | float | str, /) -> android.graphics.Typeface: ...
    def obtainCreateFromFamiliesWithDefaultMethod(self, fontFamily: typing.Type, /) -> java.lang.reflect.Method: ...

class TypefaceCompatBaseImpl(java.lang.Object):
    def createFromFontFamilyFilesResourceEntry(self, context: android.content.Context, entry: androidx.core.content.res.FontResourcesParserCompat.FontFamilyFilesResourceEntry, resources: android.content.res.Resources, style: int | java.jint | java.lang.Integer, /) -> android.graphics.Typeface: ...
    def createFromFontInfo(self, context: android.content.Context, cancellationSignal: android.os.CancellationSignal, fonts: java.chaquopy.JavaArray[androidx.core.provider.FontsContractCompat.FontInfo], style: int | java.jint | java.lang.Integer, /) -> android.graphics.Typeface: ...
    def createFromInputStream(self, context: android.content.Context, is_: java.io.InputStream, /) -> android.graphics.Typeface: ...
    def createFromResourcesFontFile(self, context: android.content.Context, resources: android.content.res.Resources, id: int | java.jint | java.lang.Integer, path: str | java.lang.String, style: int | java.jint | java.lang.Integer, /) -> android.graphics.Typeface: ...
    def findBestInfo(self, fonts: java.chaquopy.JavaArray[androidx.core.provider.FontsContractCompat.FontInfo], style: int | java.jint | java.lang.Integer, /) -> androidx.core.provider.FontsContractCompat.FontInfo: ...

class TypefaceCompatUtil(java.lang.Object):
    @staticmethod
    def closeQuietly(c: java.io.Closeable, /) -> None: ...
    @staticmethod
    def copyToDirectBuffer(context: android.content.Context, res: android.content.res.Resources, id: int | java.jint | java.lang.Integer, /) -> java.nio.ByteBuffer: ...
    @typing.overload
    @staticmethod
    def copyToFile(file: java.io.File, is_: java.io.InputStream, /) -> bool: ...
    @typing.overload
    @staticmethod
    def copyToFile(file: java.io.File, res: android.content.res.Resources, id: int | java.jint | java.lang.Integer, /) -> bool: ...
    @staticmethod
    def getTempFile(context: android.content.Context, /) -> java.io.File: ...
    @staticmethod
    def mmap(context: android.content.Context, cancellationSignal: android.os.CancellationSignal, uri: android.net.Uri, /) -> java.nio.ByteBuffer: ...
