import typing

import java
import java.lang
import java.util.concurrent.atomic
import kotlin
import kotlin.coroutines
import kotlin.jvm.functions
import kotlinx.coroutines
import kotlinx.coroutines.internal
import kotlinx.coroutines.selects

class Mutex(java.lang.Object):
    def getOnLock(self) -> kotlinx.coroutines.selects.SelectClause2[java.lang.Object, Mutex]: ...
    def holdsLock(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def isLocked(self) -> bool: ...
    def lock(self, arg1: java.lang.Object | int | bool | float | str, arg2: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def tryLock(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def unlock(self, arg1: java.lang.Object | int | bool | float | str, /) -> None: ...

    class DefaultImpls(java.lang.Object): ...

class MutexImpl(SemaphoreImpl, Mutex):
    def __init__(self, locked: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def getOnLock(self) -> kotlinx.coroutines.selects.SelectClause2[java.lang.Object, Mutex]: ...
    def holdsLock(self, owner: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def isLocked(self) -> bool: ...
    def lock(self, owner: java.lang.Object | int | bool | float | str, completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def onLockProcessResult(self, owner: java.lang.Object | int | bool | float | str, result: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def onLockRegFunction(self, select: kotlinx.coroutines.selects.SelectInstance[java.lang.Object], owner: java.lang.Object | int | bool | float | str, /) -> None: ...
    def toString(self) -> str: ...
    def tryLock(self, owner: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def unlock(self, owner: java.lang.Object | int | bool | float | str, /) -> None: ...

class MutexKt(java.lang.Object):
    @staticmethod
    def Mutex(locked: bool | java.jboolean | java.lang.Boolean, /) -> Mutex: ...
    _withLock__T = typing.TypeVar('_withLock__T')  # <T>
    @staticmethod
    def withLock(this_withLock: Mutex, owner: java.lang.Object | int | bool | float | str, action: kotlin.jvm.functions.Function0[_withLock__T], arg4: kotlin.coroutines.Continuation[_withLock__T], /) -> java.lang.Object: ...

class Semaphore(java.lang.Object):
    def acquire(self, arg1: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def getAvailablePermits(self) -> int: ...
    def release(self) -> None: ...
    def tryAcquire(self) -> bool: ...

class SemaphoreImpl(Semaphore):
    def __init__(self, permits: int | java.jint | java.lang.Integer, acquiredPermits: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def acquire(self, completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    @typing.overload
    def acquire(self, waiter: kotlinx.coroutines.CancellableContinuation[kotlin.Unit], /) -> None: ...
    def getAvailablePermits(self) -> int: ...
    def onAcquireRegFunction(self, select: kotlinx.coroutines.selects.SelectInstance[java.lang.Object], ignoredParam: java.lang.Object | int | bool | float | str, /) -> None: ...
    def release(self) -> None: ...
    def tryAcquire(self) -> bool: ...

class SemaphoreKt(java.lang.Object):
    @staticmethod
    def Semaphore(permits: int | java.jint | java.lang.Integer, acquiredPermits: int | java.jint | java.lang.Integer, /) -> Semaphore: ...
    _withPermit__T = typing.TypeVar('_withPermit__T')  # <T>
    @staticmethod
    def withPermit(this_withPermit: Semaphore, action: kotlin.jvm.functions.Function0[_withPermit__T], arg3: kotlin.coroutines.Continuation[_withPermit__T], /) -> java.lang.Object: ...

class SemaphoreSegment(kotlinx.coroutines.internal.Segment[SemaphoreSegment]):
    def __init__(self, id: int | java.jlong | java.lang.Long, prev: SemaphoreSegment, pointers: int | java.jint | java.lang.Integer, /) -> None: ...
    def cas(self, index: int | java.jint | java.lang.Integer, expected: java.lang.Object | int | bool | float | str, value: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def get(self, index: int | java.jint | java.lang.Integer, /) -> java.lang.Object: ...
    def getAcquirers(self) -> java.util.concurrent.atomic.AtomicReferenceArray: ...
    def getAndSet(self, index: int | java.jint | java.lang.Integer, value: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def getNumberOfSlots(self) -> int: ...
    def onCancellation(self, index: int | java.jint | java.lang.Integer, cause: java.lang.Throwable, context: kotlin.coroutines.CoroutineContext, /) -> None: ...
    def set(self, index: int | java.jint | java.lang.Integer, value: java.lang.Object | int | bool | float | str, /) -> None: ...
    def toString(self) -> str: ...
