import typing

import android.app
import android.os
import androidx.core.app
import androidx.versionedparcelable
import java
import java.lang

class INotificationSideChannel(android.os.IInterface):
    DESCRIPTOR: typing.ClassVar[str] = ...
    def cancel(self, arg1: str | java.lang.String, arg2: int | java.jint | java.lang.Integer, arg3: str | java.lang.String, /) -> None: ...
    def cancelAll(self, arg1: str | java.lang.String, /) -> None: ...
    def notify(self, arg1: str | java.lang.String, arg2: int | java.jint | java.lang.Integer, arg3: str | java.lang.String, arg4: android.app.Notification, /) -> None: ...

    class Stub(android.os.Binder, INotificationSideChannel):
        def __init__(self) -> None: ...
        def asBinder(self) -> android.os.IBinder: ...
        @staticmethod
        def asInterface(obj: android.os.IBinder, /) -> INotificationSideChannel: ...
        def onTransact(self, code: int | java.jint | java.lang.Integer, data: android.os.Parcel, reply: android.os.Parcel, flags: int | java.jint | java.lang.Integer, /) -> bool: ...

    class Default(INotificationSideChannel):
        def __init__(self) -> None: ...
        def asBinder(self) -> android.os.IBinder: ...
        def cancel(self, packageName: str | java.lang.String, id: int | java.jint | java.lang.Integer, tag: str | java.lang.String, /) -> None: ...
        def cancelAll(self, packageName: str | java.lang.String, /) -> None: ...
        def notify(self, packageName: str | java.lang.String, id: int | java.jint | java.lang.Integer, tag: str | java.lang.String, notification: android.app.Notification, /) -> None: ...

class RemoteActionCompatParcelizer(androidx.core.app.RemoteActionCompatParcelizer):
    def __init__(self) -> None: ...
    @staticmethod
    def read(parcel: androidx.versionedparcelable.VersionedParcel, /) -> androidx.core.app.RemoteActionCompat: ...
    @staticmethod
    def write(obj: androidx.core.app.RemoteActionCompat, parcel: androidx.versionedparcelable.VersionedParcel, /) -> None: ...
