import android.content
import android.util
import android.view
import androidx.coordinatorlayout.widget
import java
import java.chaquopy
import java.lang
import java.lang.annotation
import typing



_HideBottomViewOnScrollBehavior__V = typing.TypeVar('_HideBottomViewOnScrollBehavior__V', bound=android.view.View)  # <V>
class HideBottomViewOnScrollBehavior(androidx.coordinatorlayout.widget.CoordinatorLayout.Behavior[_HideBottomViewOnScrollBehavior__V], typing.Generic[_HideBottomViewOnScrollBehavior__V]):
    STATE_SCROLLED_DOWN: typing.ClassVar[int] = ...
    STATE_SCROLLED_UP: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    def addOnScrollStateChangedListener(self, listener: HideBottomViewOnScrollBehavior.OnScrollStateChangedListener, /) -> None: ...
    def clearOnScrollStateChangedListeners(self) -> None: ...
    def disableOnTouchExploration(self, disableOnTouchExploration: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def isDisabledOnTouchExploration(self) -> bool: ...
    def isScrolledDown(self) -> bool: ...
    def isScrolledUp(self) -> bool: ...
    def onLayoutChild(self, parent: androidx.coordinatorlayout.widget.CoordinatorLayout, child: _HideBottomViewOnScrollBehavior__V, layoutDirection: int | java.jint | java.lang.Integer, /) -> bool: ...
    def onNestedScroll(self, coordinatorLayout: androidx.coordinatorlayout.widget.CoordinatorLayout, child: _HideBottomViewOnScrollBehavior__V, target: android.view.View, dxConsumed: int | java.jint | java.lang.Integer, dyConsumed: int | java.jint | java.lang.Integer, dxUnconsumed: int | java.jint | java.lang.Integer, dyUnconsumed: int | java.jint | java.lang.Integer, type: int | java.jint | java.lang.Integer, consumed: java.chaquopy.JavaArrayJInt, /) -> None: ...
    def onStartNestedScroll(self, coordinatorLayout: androidx.coordinatorlayout.widget.CoordinatorLayout, child: _HideBottomViewOnScrollBehavior__V, directTargetChild: android.view.View, target: android.view.View, nestedScrollAxes: int | java.jint | java.lang.Integer, type: int | java.jint | java.lang.Integer, /) -> bool: ...
    def removeOnScrollStateChangedListener(self, listener: HideBottomViewOnScrollBehavior.OnScrollStateChangedListener, /) -> None: ...
    def setAdditionalHiddenOffsetY(self, child: _HideBottomViewOnScrollBehavior__V, offset: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def slideDown(self, child: _HideBottomViewOnScrollBehavior__V, /) -> None: ...
    @typing.overload
    def slideDown(self, child: _HideBottomViewOnScrollBehavior__V, animate: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def slideUp(self, child: _HideBottomViewOnScrollBehavior__V, /) -> None: ...
    @typing.overload
    def slideUp(self, child: _HideBottomViewOnScrollBehavior__V, animate: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

    class OnScrollStateChangedListener(java.lang.Object):
        def onStateChanged(self, arg1: android.view.View, arg2: int | java.jint | java.lang.Integer, /) -> None: ...

    class ScrollState(java.lang.annotation.Annotation): ...

class HideBottomViewOnScrollDelegate(HideViewOnScrollDelegate): ...

class HideLeftViewOnScrollDelegate(HideViewOnScrollDelegate): ...

class HideRightViewOnScrollDelegate(HideViewOnScrollDelegate): ...

_HideViewOnScrollBehavior__V = typing.TypeVar('_HideViewOnScrollBehavior__V', bound=android.view.View)  # <V>
class HideViewOnScrollBehavior(androidx.coordinatorlayout.widget.CoordinatorLayout.Behavior[_HideViewOnScrollBehavior__V], typing.Generic[_HideViewOnScrollBehavior__V]):
    EDGE_RIGHT: typing.ClassVar[int] = ...
    EDGE_BOTTOM: typing.ClassVar[int] = ...
    EDGE_LEFT: typing.ClassVar[int] = ...
    STATE_SCROLLED_OUT: typing.ClassVar[int] = ...
    STATE_SCROLLED_IN: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, viewEdge: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    def addOnScrollStateChangedListener(self, listener: HideViewOnScrollBehavior.OnScrollStateChangedListener, /) -> None: ...
    def clearOnScrollStateChangedListeners(self) -> None: ...
    def disableOnTouchExploration(self, disableOnTouchExploration: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    _from___V = typing.TypeVar('_from___V', bound=android.view.View)  # <V>
    @staticmethod
    def from_(view: _from___V, /) -> HideViewOnScrollBehavior[_from___V]: ...
    def isDisabledOnTouchExploration(self) -> bool: ...
    def isScrolledIn(self) -> bool: ...
    def isScrolledOut(self) -> bool: ...
    def onLayoutChild(self, parent: androidx.coordinatorlayout.widget.CoordinatorLayout, child: _HideViewOnScrollBehavior__V, layoutDirection: int | java.jint | java.lang.Integer, /) -> bool: ...
    def onNestedScroll(self, coordinatorLayout: androidx.coordinatorlayout.widget.CoordinatorLayout, child: _HideViewOnScrollBehavior__V, target: android.view.View, dxConsumed: int | java.jint | java.lang.Integer, dyConsumed: int | java.jint | java.lang.Integer, dxUnconsumed: int | java.jint | java.lang.Integer, dyUnconsumed: int | java.jint | java.lang.Integer, type: int | java.jint | java.lang.Integer, consumed: java.chaquopy.JavaArrayJInt, /) -> None: ...
    def onStartNestedScroll(self, coordinatorLayout: androidx.coordinatorlayout.widget.CoordinatorLayout, child: _HideViewOnScrollBehavior__V, directTargetChild: android.view.View, target: android.view.View, nestedScrollAxes: int | java.jint | java.lang.Integer, type: int | java.jint | java.lang.Integer, /) -> bool: ...
    def removeOnScrollStateChangedListener(self, listener: HideViewOnScrollBehavior.OnScrollStateChangedListener, /) -> None: ...
    def setAdditionalHiddenOffset(self, child: _HideViewOnScrollBehavior__V, offset: int | java.jint | java.lang.Integer, /) -> None: ...
    def setViewEdge(self, viewEdge: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def slideIn(self, child: _HideViewOnScrollBehavior__V, /) -> None: ...
    @typing.overload
    def slideIn(self, child: _HideViewOnScrollBehavior__V, animate: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def slideOut(self, child: _HideViewOnScrollBehavior__V, /) -> None: ...
    @typing.overload
    def slideOut(self, child: _HideViewOnScrollBehavior__V, animate: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

    class OnScrollStateChangedListener(java.lang.Object):
        def onStateChanged(self, arg1: android.view.View, arg2: int | java.jint | java.lang.Integer, /) -> None: ...

    class ScrollState(java.lang.annotation.Annotation): ...

class HideViewOnScrollDelegate(java.lang.Object): ...

_SwipeDismissBehavior__V = typing.TypeVar('_SwipeDismissBehavior__V', bound=android.view.View)  # <V>
class SwipeDismissBehavior(androidx.coordinatorlayout.widget.CoordinatorLayout.Behavior[_SwipeDismissBehavior__V], typing.Generic[_SwipeDismissBehavior__V]):
    STATE_IDLE: typing.ClassVar[int] = ...
    STATE_DRAGGING: typing.ClassVar[int] = ...
    STATE_SETTLING: typing.ClassVar[int] = ...
    SWIPE_DIRECTION_START_TO_END: typing.ClassVar[int] = ...
    SWIPE_DIRECTION_END_TO_START: typing.ClassVar[int] = ...
    SWIPE_DIRECTION_ANY: typing.ClassVar[int] = ...
    def __init__(self) -> None: ...
    def canSwipeDismissView(self, view: android.view.View, /) -> bool: ...
    def getDragState(self) -> int: ...
    def getListener(self) -> SwipeDismissBehavior.OnDismissListener: ...
    def onInterceptTouchEvent(self, parent: androidx.coordinatorlayout.widget.CoordinatorLayout, child: _SwipeDismissBehavior__V, event: android.view.MotionEvent, /) -> bool: ...
    def onLayoutChild(self, parent: androidx.coordinatorlayout.widget.CoordinatorLayout, child: _SwipeDismissBehavior__V, layoutDirection: int | java.jint | java.lang.Integer, /) -> bool: ...
    def onTouchEvent(self, parent: androidx.coordinatorlayout.widget.CoordinatorLayout, child: _SwipeDismissBehavior__V, event: android.view.MotionEvent, /) -> bool: ...
    def setDragDismissDistance(self, distance: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setEndAlphaSwipeDistance(self, fraction: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setListener(self, listener: SwipeDismissBehavior.OnDismissListener, /) -> None: ...
    def setSensitivity(self, sensitivity: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setStartAlphaSwipeDistance(self, fraction: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setSwipeDirection(self, direction: int | java.jint | java.lang.Integer, /) -> None: ...

    class OnDismissListener(java.lang.Object):
        def onDismiss(self, arg1: android.view.View, /) -> None: ...
        def onDragStateChanged(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
