import typing

import android.content
import android.content.res
import android.graphics
import android.graphics.drawable
import android.os
import android.util
import android.view
import java
import java.lang
import java.util

_BaseOnChangeListener__S = typing.TypeVar('_BaseOnChangeListener__S')  # <S>
class BaseOnChangeListener(java.lang.Object, typing.Generic[_BaseOnChangeListener__S]):
    def onValueChange(self, arg1: _BaseOnChangeListener__S, arg2: float | java.jfloat | java.lang.Float, arg3: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

_BaseOnSliderTouchListener__S = typing.TypeVar('_BaseOnSliderTouchListener__S')  # <S>
class BaseOnSliderTouchListener(java.lang.Object, typing.Generic[_BaseOnSliderTouchListener__S]):
    def onStartTrackingTouch(self, arg1: _BaseOnSliderTouchListener__S, /) -> None: ...
    def onStopTrackingTouch(self, arg1: _BaseOnSliderTouchListener__S, /) -> None: ...

_BaseSlider__S = typing.TypeVar('_BaseSlider__S', bound=BaseSlider[S, L, T])  # <S>
_BaseSlider__L = typing.TypeVar('_BaseSlider__L')  # <L>
_BaseSlider__T = typing.TypeVar('_BaseSlider__T')  # <T>
class BaseSlider(android.view.View, typing.Generic[_BaseSlider__S, _BaseSlider__L, _BaseSlider__T]):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def addOnChangeListener(self, listener: _BaseSlider__L, /) -> None: ...
    def addOnSliderTouchListener(self, listener: _BaseSlider__T, /) -> None: ...
    def clearOnChangeListeners(self) -> None: ...
    def clearOnSliderTouchListeners(self) -> None: ...
    def dispatchHoverEvent(self, event: android.view.MotionEvent, /) -> bool: ...
    def dispatchKeyEvent(self, event: android.view.KeyEvent, /) -> bool: ...
    def drawableStateChanged(self) -> None: ...
    def getAccessibilityClassName(self) -> java.lang.CharSequence: ...
    def getActiveThumbIndex(self) -> int: ...
    def getFocusedThumbIndex(self) -> int: ...
    def getHaloRadius(self) -> int: ...
    def getHaloTintList(self) -> android.content.res.ColorStateList: ...
    def getLabelBehavior(self) -> int: ...
    def getMinSeparation(self) -> float: ...
    def getStepSize(self) -> float: ...
    def getThumbElevation(self) -> float: ...
    def getThumbHeight(self) -> int: ...
    def getThumbRadius(self) -> int: ...
    def getThumbStrokeColor(self) -> android.content.res.ColorStateList: ...
    def getThumbStrokeWidth(self) -> float: ...
    def getThumbTintList(self) -> android.content.res.ColorStateList: ...
    def getThumbTrackGapSize(self) -> int: ...
    def getThumbWidth(self) -> int: ...
    def getTickActiveRadius(self) -> int: ...
    def getTickActiveTintList(self) -> android.content.res.ColorStateList: ...
    def getTickInactiveRadius(self) -> int: ...
    def getTickInactiveTintList(self) -> android.content.res.ColorStateList: ...
    def getTickTintList(self) -> android.content.res.ColorStateList: ...
    def getTrackActiveTintList(self) -> android.content.res.ColorStateList: ...
    def getTrackHeight(self) -> int: ...
    def getTrackInactiveTintList(self) -> android.content.res.ColorStateList: ...
    def getTrackInsideCornerSize(self) -> int: ...
    def getTrackSidePadding(self) -> int: ...
    def getTrackStopIndicatorSize(self) -> int: ...
    def getTrackTintList(self) -> android.content.res.ColorStateList: ...
    def getTrackWidth(self) -> int: ...
    def getValueFrom(self) -> float: ...
    def getValueTo(self) -> float: ...
    def hasLabelFormatter(self) -> bool: ...
    def isTickVisible(self) -> bool: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onDraw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def onFocusChanged(self, gainFocus: bool | java.jboolean | java.lang.Boolean, direction: int | java.jint | java.lang.Integer, previouslyFocusedRect: android.graphics.Rect, /) -> None: ...
    def onKeyDown(self, keyCode: int | java.jint | java.lang.Integer, event: android.view.KeyEvent, /) -> bool: ...
    def onKeyUp(self, keyCode: int | java.jint | java.lang.Integer, event: android.view.KeyEvent, /) -> bool: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def onRestoreInstanceState(self, state: android.os.Parcelable, /) -> None: ...
    def onSaveInstanceState(self) -> android.os.Parcelable: ...
    def onSizeChanged(self, w: int | java.jint | java.lang.Integer, h: int | java.jint | java.lang.Integer, oldw: int | java.jint | java.lang.Integer, oldh: int | java.jint | java.lang.Integer, /) -> None: ...
    def onTouchEvent(self, event: android.view.MotionEvent, /) -> bool: ...
    def onVisibilityChanged(self, changedView: android.view.View, visibility: int | java.jint | java.lang.Integer, /) -> None: ...
    def pickActiveThumb(self) -> bool: ...
    def removeOnChangeListener(self, listener: _BaseSlider__L, /) -> None: ...
    def removeOnSliderTouchListener(self, listener: _BaseSlider__T, /) -> None: ...
    def setActiveThumbIndex(self, index: int | java.jint | java.lang.Integer, /) -> None: ...
    def setEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setFocusedThumbIndex(self, index: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHaloRadius(self, radius: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHaloRadiusResource(self, radius: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHaloTintList(self, haloColor: android.content.res.ColorStateList, /) -> None: ...
    def setLabelBehavior(self, labelBehavior: int | java.jint | java.lang.Integer, /) -> None: ...
    def setLabelFormatter(self, formatter: LabelFormatter, /) -> None: ...
    def setSeparationUnit(self, separationUnit: int | java.jint | java.lang.Integer, /) -> None: ...
    def setStepSize(self, stepSize: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setThumbElevation(self, elevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setThumbElevationResource(self, elevation: int | java.jint | java.lang.Integer, /) -> None: ...
    def setThumbHeight(self, height: int | java.jint | java.lang.Integer, /) -> None: ...
    def setThumbHeightResource(self, height: int | java.jint | java.lang.Integer, /) -> None: ...
    def setThumbRadius(self, radius: int | java.jint | java.lang.Integer, /) -> None: ...
    def setThumbRadiusResource(self, radius: int | java.jint | java.lang.Integer, /) -> None: ...
    def setThumbStrokeColor(self, thumbStrokeColor: android.content.res.ColorStateList, /) -> None: ...
    def setThumbStrokeColorResource(self, thumbStrokeColorResourceId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setThumbStrokeWidth(self, thumbStrokeWidth: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setThumbStrokeWidthResource(self, thumbStrokeWidthResourceId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setThumbTintList(self, thumbColor: android.content.res.ColorStateList, /) -> None: ...
    def setThumbTrackGapSize(self, thumbTrackGapSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def setThumbWidth(self, width: int | java.jint | java.lang.Integer, /) -> None: ...
    def setThumbWidthResource(self, width: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTickActiveRadius(self, tickActiveRadius: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTickActiveTintList(self, tickColor: android.content.res.ColorStateList, /) -> None: ...
    def setTickInactiveRadius(self, tickInactiveRadius: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTickInactiveTintList(self, tickColor: android.content.res.ColorStateList, /) -> None: ...
    def setTickTintList(self, tickColor: android.content.res.ColorStateList, /) -> None: ...
    def setTickVisible(self, tickVisible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setTrackActiveTintList(self, trackColor: android.content.res.ColorStateList, /) -> None: ...
    def setTrackHeight(self, trackHeight: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTrackInactiveTintList(self, trackColor: android.content.res.ColorStateList, /) -> None: ...
    def setTrackInsideCornerSize(self, cornerSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTrackStopIndicatorSize(self, trackStopIndicatorSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTrackTintList(self, trackColor: android.content.res.ColorStateList, /) -> None: ...
    def setValueFrom(self, valueFrom: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setValueTo(self, valueTo: float | java.jfloat | java.lang.Float, /) -> None: ...

class BasicLabelFormatter(LabelFormatter):
    def __init__(self) -> None: ...
    def getFormattedValue(self, value: float | java.jfloat | java.lang.Float, /) -> str: ...

class LabelFormatter(java.lang.Object):
    LABEL_FLOATING: typing.ClassVar[int] = ...
    LABEL_WITHIN_BOUNDS: typing.ClassVar[int] = ...
    LABEL_GONE: typing.ClassVar[int] = ...
    LABEL_VISIBLE: typing.ClassVar[int] = ...
    def getFormattedValue(self, arg1: float | java.jfloat | java.lang.Float, /) -> str: ...

class RangeSlider(BaseSlider[RangeSlider, RangeSlider.OnChangeListener, RangeSlider.OnSliderTouchListener]):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def getMinSeparation(self) -> float: ...
    def getValues(self) -> java.util.List[java.lang.Float]: ...
    def onRestoreInstanceState(self, state: android.os.Parcelable, /) -> None: ...
    def onSaveInstanceState(self) -> android.os.Parcelable: ...
    @typing.overload
    def setCustomThumbDrawable(self, drawableResId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCustomThumbDrawable(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...
    @typing.overload
    def setCustomThumbDrawablesForValues(self, *drawableResIds: java.jint) -> None: ...
    @typing.overload
    def setCustomThumbDrawablesForValues(self, *drawables: android.graphics.drawable.Drawable) -> None: ...
    def setMinSeparation(self, minSeparation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setMinSeparationValue(self, minSeparation: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def setValues(self, values: java.util.List[java.lang.Float], /) -> None: ...
    @typing.overload
    def setValues(self, *values: java.jfloat) -> None: ...

    class OnSliderTouchListener(BaseOnSliderTouchListener[RangeSlider]):
        def onStartTrackingTouch(self, arg1: RangeSlider, /) -> None: ...
        def onStopTrackingTouch(self, arg1: RangeSlider, /) -> None: ...

    class OnChangeListener(BaseOnChangeListener[RangeSlider]):
        def onValueChange(self, arg1: RangeSlider, arg2: float | java.jfloat | java.lang.Float, arg3: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class Slider(BaseSlider[Slider, Slider.OnChangeListener, Slider.OnSliderTouchListener]):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def getValue(self) -> float: ...
    def pickActiveThumb(self) -> bool: ...
    @typing.overload
    def setCustomThumbDrawable(self, drawableResId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCustomThumbDrawable(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...
    def setValue(self, value: float | java.jfloat | java.lang.Float, /) -> None: ...

    class OnSliderTouchListener(BaseOnSliderTouchListener[Slider]):
        def onStartTrackingTouch(self, arg1: Slider, /) -> None: ...
        def onStopTrackingTouch(self, arg1: Slider, /) -> None: ...

    class OnChangeListener(BaseOnChangeListener[Slider]):
        def onValueChange(self, arg1: Slider, arg2: float | java.jfloat | java.lang.Float, arg3: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
