import typing

import android.animation
import android.content
import android.graphics
import android.graphics.drawable
import android.util
import android.view
import android.widget
import androidx.dynamicanimation.animation
import androidx.vectordrawable.graphics.drawable
import java
import java.chaquopy
import java.lang
import java.lang.annotation

class AnimatorDurationScaleProvider(java.lang.Object):
    def __init__(self) -> None: ...
    def getSystemAnimatorDurationScale(self, contentResolver: android.content.ContentResolver, /) -> float: ...
    @staticmethod
    def setDefaultSystemAnimatorDurationScale(scale: float | java.jfloat | java.lang.Float, /) -> None: ...

_BaseProgressIndicator__S = typing.TypeVar('_BaseProgressIndicator__S', bound=BaseProgressIndicatorSpec)  # <S>
class BaseProgressIndicator(android.widget.ProgressBar, typing.Generic[_BaseProgressIndicator__S]):
    SHOW_NONE: typing.ClassVar[int] = ...
    SHOW_OUTWARD: typing.ClassVar[int] = ...
    SHOW_INWARD: typing.ClassVar[int] = ...
    HIDE_NONE: typing.ClassVar[int] = ...
    HIDE_OUTWARD: typing.ClassVar[int] = ...
    HIDE_INWARD: typing.ClassVar[int] = ...
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, /) -> None: ...
    def applyNewVisibility(self, animate: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def getCurrentDrawable(self) -> android.graphics.drawable.Drawable: ...
    def getHideAnimationBehavior(self) -> int: ...
    def getIndeterminateDrawable(self) -> IndeterminateDrawable[_BaseProgressIndicator__S]: ...
    def getIndicatorColor(self) -> java.chaquopy.JavaArrayJInt: ...
    def getProgressDrawable(self) -> DeterminateDrawable[_BaseProgressIndicator__S]: ...
    def getShowAnimationBehavior(self) -> int: ...
    def getTrackColor(self) -> int: ...
    def getTrackCornerRadius(self) -> int: ...
    def getTrackThickness(self) -> int: ...
    def hide(self) -> None: ...
    def invalidate(self) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onDraw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def onVisibilityChanged(self, changedView: android.view.View, visibility: int | java.jint | java.lang.Integer, /) -> None: ...
    def onWindowVisibilityChanged(self, visibility: int | java.jint | java.lang.Integer, /) -> None: ...
    def setAnimatorDurationScaleProvider(self, animatorDurationScaleProvider: AnimatorDurationScaleProvider, /) -> None: ...
    def setHideAnimationBehavior(self, hideAnimationBehavior: int | java.jint | java.lang.Integer, /) -> None: ...
    def setIndeterminate(self, indeterminate: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setIndeterminateDrawable(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...
    def setIndicatorColor(self, *indicatorColors: java.jint) -> None: ...
    def setProgress(self, progress: int | java.jint | java.lang.Integer, /) -> None: ...
    def setProgressCompat(self, progress: int | java.jint | java.lang.Integer, animated: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setProgressDrawable(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...
    def setShowAnimationBehavior(self, showAnimationBehavior: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTrackColor(self, trackColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTrackCornerRadius(self, trackCornerRadius: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTrackThickness(self, trackThickness: int | java.jint | java.lang.Integer, /) -> None: ...
    def setVisibilityAfterHide(self, visibility: int | java.jint | java.lang.Integer, /) -> None: ...
    def show(self) -> None: ...

    class HideAnimationBehavior(java.lang.annotation.Annotation): ...

    class ShowAnimationBehavior(java.lang.annotation.Annotation): ...

class BaseProgressIndicatorSpec(java.lang.Object):
    trackThickness: int = ...
    trackCornerRadius: int = ...
    indicatorColors: java.chaquopy.JavaArrayJInt = ...
    trackColor: int = ...
    showAnimationBehavior: int = ...
    hideAnimationBehavior: int = ...
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, /) -> None: ...
    def isHideAnimationEnabled(self) -> bool: ...
    def isShowAnimationEnabled(self) -> bool: ...

class CircularDrawingDelegate(DrawingDelegate[CircularProgressIndicatorSpec]):
    def __init__(self, spec: CircularProgressIndicatorSpec, /) -> None: ...
    def adjustCanvas(self, canvas: android.graphics.Canvas, trackThicknessFraction: float | java.jfloat | java.lang.Float, /) -> None: ...
    def getPreferredHeight(self) -> int: ...
    def getPreferredWidth(self) -> int: ...

class CircularIndeterminateAnimatorDelegate(IndeterminateAnimatorDelegate[android.animation.ObjectAnimator]):
    def __init__(self, spec: CircularProgressIndicatorSpec, /) -> None: ...
    def invalidateSpecValues(self) -> None: ...
    def registerAnimatorsCompleteCallback(self, callback: androidx.vectordrawable.graphics.drawable.Animatable2Compat.AnimationCallback, /) -> None: ...
    def unregisterAnimatorsCompleteCallback(self) -> None: ...

class CircularProgressIndicator(BaseProgressIndicator[CircularProgressIndicatorSpec]):
    DEF_STYLE_RES: typing.ClassVar[int] = ...
    INDICATOR_DIRECTION_CLOCKWISE: typing.ClassVar[int] = ...
    INDICATOR_DIRECTION_COUNTERCLOCKWISE: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def getIndicatorDirection(self) -> int: ...
    def getIndicatorInset(self) -> int: ...
    def getIndicatorSize(self) -> int: ...
    def setIndicatorDirection(self, indicatorDirection: int | java.jint | java.lang.Integer, /) -> None: ...
    def setIndicatorInset(self, indicatorInset: int | java.jint | java.lang.Integer, /) -> None: ...
    def setIndicatorSize(self, indicatorSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTrackThickness(self, trackThickness: int | java.jint | java.lang.Integer, /) -> None: ...

    class IndicatorDirection(java.lang.annotation.Annotation): ...

class CircularProgressIndicatorSpec(BaseProgressIndicatorSpec):
    indicatorSize: int = ...
    indicatorInset: int = ...
    indicatorDirection: int = ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, /) -> None: ...

_DeterminateDrawable__S = typing.TypeVar('_DeterminateDrawable__S', bound=BaseProgressIndicatorSpec)  # <S>
class DeterminateDrawable(DrawableWithAnimatedVisibilityChange, typing.Generic[_DeterminateDrawable__S]):
    def addSpringAnimationEndListener(self, listener: androidx.dynamicanimation.animation.DynamicAnimation.OnAnimationEndListener, /) -> None: ...
    @staticmethod
    def createCircularDrawable(context: android.content.Context, spec: CircularProgressIndicatorSpec, /) -> DeterminateDrawable[CircularProgressIndicatorSpec]: ...
    @staticmethod
    def createLinearDrawable(context: android.content.Context, spec: LinearProgressIndicatorSpec, /) -> DeterminateDrawable[LinearProgressIndicatorSpec]: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getIntrinsicHeight(self) -> int: ...
    def getIntrinsicWidth(self) -> int: ...
    def jumpToCurrentState(self) -> None: ...
    def onLevelChange(self, level: int | java.jint | java.lang.Integer, /) -> bool: ...
    def removeSpringAnimationEndListener(self, listener: androidx.dynamicanimation.animation.DynamicAnimation.OnAnimationEndListener, /) -> None: ...

class DrawableWithAnimatedVisibilityChange(android.graphics.drawable.Drawable, androidx.vectordrawable.graphics.drawable.Animatable2Compat):
    def clearAnimationCallbacks(self) -> None: ...
    def getAlpha(self) -> int: ...
    def getOpacity(self) -> int: ...
    def hideNow(self) -> bool: ...
    def isHiding(self) -> bool: ...
    def isRunning(self) -> bool: ...
    def isShowing(self) -> bool: ...
    def registerAnimationCallback(self, callback: androidx.vectordrawable.graphics.drawable.Animatable2Compat.AnimationCallback, /) -> None: ...
    def setAlpha(self, alpha: int | java.jint | java.lang.Integer, /) -> None: ...
    def setColorFilter(self, colorFilter: android.graphics.ColorFilter, /) -> None: ...
    @typing.overload
    def setVisible(self, visible: bool | java.jboolean | java.lang.Boolean, restart: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    @typing.overload
    def setVisible(self, visible: bool | java.jboolean | java.lang.Boolean, restart: bool | java.jboolean | java.lang.Boolean, animate: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def unregisterAnimationCallback(self, callback: androidx.vectordrawable.graphics.drawable.Animatable2Compat.AnimationCallback, /) -> bool: ...

_DrawingDelegate__S = typing.TypeVar('_DrawingDelegate__S', bound=BaseProgressIndicatorSpec)  # <S>
class DrawingDelegate(java.lang.Object, typing.Generic[_DrawingDelegate__S]):
    drawable: DrawableWithAnimatedVisibilityChange = ...
    def __init__(self, spec: _DrawingDelegate__S, /) -> None: ...
    def registerDrawable(self, drawable: DrawableWithAnimatedVisibilityChange, /) -> None: ...

_IndeterminateAnimatorDelegate__T = typing.TypeVar('_IndeterminateAnimatorDelegate__T', bound=android.animation.Animator)  # <T>
class IndeterminateAnimatorDelegate(java.lang.Object, typing.Generic[_IndeterminateAnimatorDelegate__T]):
    drawable: IndeterminateDrawable = ...
    segmentPositions: java.chaquopy.JavaArrayJFloat = ...
    segmentColors: java.chaquopy.JavaArrayJInt = ...
    def __init__(self, segmentCount: int | java.jint | java.lang.Integer, /) -> None: ...
    def getFractionInRange(self, playtime: int | java.jint | java.lang.Integer, start: int | java.jint | java.lang.Integer, duration: int | java.jint | java.lang.Integer, /) -> float: ...
    def invalidateSpecValues(self) -> None: ...
    def registerAnimatorsCompleteCallback(self, arg1: androidx.vectordrawable.graphics.drawable.Animatable2Compat.AnimationCallback, /) -> None: ...
    def registerDrawable(self, drawable: IndeterminateDrawable, /) -> None: ...
    def unregisterAnimatorsCompleteCallback(self) -> None: ...

_IndeterminateDrawable__S = typing.TypeVar('_IndeterminateDrawable__S', bound=BaseProgressIndicatorSpec)  # <S>
class IndeterminateDrawable(DrawableWithAnimatedVisibilityChange, typing.Generic[_IndeterminateDrawable__S]):
    @staticmethod
    def createCircularDrawable(context: android.content.Context, spec: CircularProgressIndicatorSpec, /) -> IndeterminateDrawable[CircularProgressIndicatorSpec]: ...
    @staticmethod
    def createLinearDrawable(context: android.content.Context, spec: LinearProgressIndicatorSpec, /) -> IndeterminateDrawable[LinearProgressIndicatorSpec]: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getIntrinsicHeight(self) -> int: ...
    def getIntrinsicWidth(self) -> int: ...

class LinearDrawingDelegate(DrawingDelegate[LinearProgressIndicatorSpec]):
    def __init__(self, spec: LinearProgressIndicatorSpec, /) -> None: ...
    def adjustCanvas(self, canvas: android.graphics.Canvas, trackThicknessFraction: float | java.jfloat | java.lang.Float, /) -> None: ...
    def fillIndicator(self, canvas: android.graphics.Canvas, paint: android.graphics.Paint, startFraction: float | java.jfloat | java.lang.Float, endFraction: float | java.jfloat | java.lang.Float, color: int | java.jint | java.lang.Integer, /) -> None: ...
    def getPreferredHeight(self) -> int: ...
    def getPreferredWidth(self) -> int: ...

class LinearIndeterminateContiguousAnimatorDelegate(IndeterminateAnimatorDelegate[android.animation.ObjectAnimator]):
    def __init__(self, spec: LinearProgressIndicatorSpec, /) -> None: ...
    def cancelAnimatorImmediately(self) -> None: ...
    def invalidateSpecValues(self) -> None: ...
    def registerAnimatorsCompleteCallback(self, callback: androidx.vectordrawable.graphics.drawable.Animatable2Compat.AnimationCallback, /) -> None: ...
    def requestCancelAnimatorAfterCurrentCycle(self) -> None: ...
    def startAnimator(self) -> None: ...
    def unregisterAnimatorsCompleteCallback(self) -> None: ...

class LinearIndeterminateDisjointAnimatorDelegate(IndeterminateAnimatorDelegate[android.animation.ObjectAnimator]):
    def __init__(self, context: android.content.Context, spec: LinearProgressIndicatorSpec, /) -> None: ...
    def cancelAnimatorImmediately(self) -> None: ...
    def invalidateSpecValues(self) -> None: ...
    def registerAnimatorsCompleteCallback(self, callback: androidx.vectordrawable.graphics.drawable.Animatable2Compat.AnimationCallback, /) -> None: ...
    def requestCancelAnimatorAfterCurrentCycle(self) -> None: ...
    def startAnimator(self) -> None: ...
    def unregisterAnimatorsCompleteCallback(self) -> None: ...

class LinearProgressIndicator(BaseProgressIndicator[LinearProgressIndicatorSpec]):
    DEF_STYLE_RES: typing.ClassVar[int] = ...
    INDETERMINATE_ANIMATION_TYPE_CONTIGUOUS: typing.ClassVar[int] = ...
    INDETERMINATE_ANIMATION_TYPE_DISJOINT: typing.ClassVar[int] = ...
    INDICATOR_DIRECTION_LEFT_TO_RIGHT: typing.ClassVar[int] = ...
    INDICATOR_DIRECTION_RIGHT_TO_LEFT: typing.ClassVar[int] = ...
    INDICATOR_DIRECTION_START_TO_END: typing.ClassVar[int] = ...
    INDICATOR_DIRECTION_END_TO_START: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def getIndeterminateAnimationType(self) -> int: ...
    def getIndicatorDirection(self) -> int: ...
    def onLayout(self, changed: bool | java.jboolean | java.lang.Boolean, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def onSizeChanged(self, w: int | java.jint | java.lang.Integer, h: int | java.jint | java.lang.Integer, oldw: int | java.jint | java.lang.Integer, oldh: int | java.jint | java.lang.Integer, /) -> None: ...
    def setIndeterminateAnimationType(self, indeterminateAnimationType: int | java.jint | java.lang.Integer, /) -> None: ...
    def setIndicatorColor(self, *indicatorColors: java.jint) -> None: ...
    def setIndicatorDirection(self, indicatorDirection: int | java.jint | java.lang.Integer, /) -> None: ...
    def setProgressCompat(self, progress: int | java.jint | java.lang.Integer, animated: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setTrackCornerRadius(self, trackCornerRadius: int | java.jint | java.lang.Integer, /) -> None: ...

    class IndicatorDirection(java.lang.annotation.Annotation): ...

    class IndeterminateAnimationType(java.lang.annotation.Annotation): ...

class LinearProgressIndicatorSpec(BaseProgressIndicatorSpec):
    indeterminateAnimationType: int = ...
    indicatorDirection: int = ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, /) -> None: ...
