import typing

import java
import java.lang
import java.lang.annotation
import java.util.concurrent.atomic
import kotlin.jvm.functions

class AtomicArraysKt(AtomicArraysKt__AtomicArrays_jvmKt): ...

class AtomicArraysKt__AtomicArrays_commonKt(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def AtomicIntArray(size: int | java.jint | java.lang.Integer, init: kotlin.jvm.functions.Function1[int, java.lang.Integer], /) -> java.util.concurrent.atomic.AtomicIntegerArray: ...
    @staticmethod
    def AtomicLongArray(size: int | java.jint | java.lang.Integer, init: kotlin.jvm.functions.Function1[int, java.lang.Long], /) -> java.util.concurrent.atomic.AtomicLongArray: ...
    @typing.overload
    @staticmethod
    def decrementAndFetchAt(this_decrementAndFetchAt: java.util.concurrent.atomic.AtomicIntegerArray, index: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def decrementAndFetchAt(this_decrementAndFetchAt: java.util.concurrent.atomic.AtomicLongArray, index: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def fetchAndDecrementAt(this_fetchAndDecrementAt: java.util.concurrent.atomic.AtomicIntegerArray, index: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def fetchAndDecrementAt(this_fetchAndDecrementAt: java.util.concurrent.atomic.AtomicLongArray, index: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def fetchAndIncrementAt(this_fetchAndIncrementAt: java.util.concurrent.atomic.AtomicIntegerArray, index: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def fetchAndIncrementAt(this_fetchAndIncrementAt: java.util.concurrent.atomic.AtomicLongArray, index: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def incrementAndFetchAt(this_incrementAndFetchAt: java.util.concurrent.atomic.AtomicIntegerArray, index: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def incrementAndFetchAt(this_incrementAndFetchAt: java.util.concurrent.atomic.AtomicLongArray, index: int | java.jint | java.lang.Integer, /) -> int: ...

class AtomicArraysKt__AtomicArrays_jvmKt(AtomicArraysKt__AtomicArrays_commonKt):
    def __init__(self) -> None: ...
    _asJavaAtomicArray_2__T = typing.TypeVar('_asJavaAtomicArray_2__T')  # <T>
    @typing.overload
    @staticmethod
    def asJavaAtomicArray(this_asJavaAtomicArray: java.util.concurrent.atomic.AtomicIntegerArray, /) -> java.util.concurrent.atomic.AtomicIntegerArray: ...
    @typing.overload
    @staticmethod
    def asJavaAtomicArray(this_asJavaAtomicArray: java.util.concurrent.atomic.AtomicLongArray, /) -> java.util.concurrent.atomic.AtomicLongArray: ...
    @typing.overload
    @staticmethod
    def asJavaAtomicArray(this_asJavaAtomicArray: java.util.concurrent.atomic.AtomicReferenceArray[_asJavaAtomicArray_2__T], /) -> java.util.concurrent.atomic.AtomicReferenceArray[_asJavaAtomicArray_2__T]: ...
    _asKotlinAtomicArray_2__T = typing.TypeVar('_asKotlinAtomicArray_2__T')  # <T>
    @typing.overload
    @staticmethod
    def asKotlinAtomicArray(this_asKotlinAtomicArray: java.util.concurrent.atomic.AtomicIntegerArray, /) -> java.util.concurrent.atomic.AtomicIntegerArray: ...
    @typing.overload
    @staticmethod
    def asKotlinAtomicArray(this_asKotlinAtomicArray: java.util.concurrent.atomic.AtomicLongArray, /) -> java.util.concurrent.atomic.AtomicLongArray: ...
    @typing.overload
    @staticmethod
    def asKotlinAtomicArray(this_asKotlinAtomicArray: java.util.concurrent.atomic.AtomicReferenceArray[_asKotlinAtomicArray_2__T], /) -> java.util.concurrent.atomic.AtomicReferenceArray[_asKotlinAtomicArray_2__T]: ...

class AtomicsKt(AtomicsKt__Atomics_jvmKt): ...

class AtomicsKt__Atomics_commonKt(java.lang.Object):
    def __init__(self) -> None: ...
    @typing.overload
    @staticmethod
    def decrementAndFetch(this_decrementAndFetch: java.util.concurrent.atomic.AtomicInteger, /) -> int: ...
    @typing.overload
    @staticmethod
    def decrementAndFetch(this_decrementAndFetch: java.util.concurrent.atomic.AtomicLong, /) -> int: ...
    @typing.overload
    @staticmethod
    def fetchAndDecrement(this_fetchAndDecrement: java.util.concurrent.atomic.AtomicInteger, /) -> int: ...
    @typing.overload
    @staticmethod
    def fetchAndDecrement(this_fetchAndDecrement: java.util.concurrent.atomic.AtomicLong, /) -> int: ...
    @typing.overload
    @staticmethod
    def fetchAndIncrement(this_fetchAndIncrement: java.util.concurrent.atomic.AtomicInteger, /) -> int: ...
    @typing.overload
    @staticmethod
    def fetchAndIncrement(this_fetchAndIncrement: java.util.concurrent.atomic.AtomicLong, /) -> int: ...
    @typing.overload
    @staticmethod
    def incrementAndFetch(this_incrementAndFetch: java.util.concurrent.atomic.AtomicInteger, /) -> int: ...
    @typing.overload
    @staticmethod
    def incrementAndFetch(this_incrementAndFetch: java.util.concurrent.atomic.AtomicLong, /) -> int: ...
    @typing.overload
    @staticmethod
    def minusAssign(this_minusAssign: java.util.concurrent.atomic.AtomicInteger, delta: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    @staticmethod
    def minusAssign(this_minusAssign: java.util.concurrent.atomic.AtomicLong, delta: int | java.jlong | java.lang.Long, /) -> None: ...
    @typing.overload
    @staticmethod
    def plusAssign(this_plusAssign: java.util.concurrent.atomic.AtomicInteger, delta: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    @staticmethod
    def plusAssign(this_plusAssign: java.util.concurrent.atomic.AtomicLong, delta: int | java.jlong | java.lang.Long, /) -> None: ...

class AtomicsKt__Atomics_jvmKt(AtomicsKt__Atomics_commonKt):
    def __init__(self) -> None: ...
    _asJavaAtomic_3__T = typing.TypeVar('_asJavaAtomic_3__T')  # <T>
    @typing.overload
    @staticmethod
    def asJavaAtomic(this_asJavaAtomic: java.util.concurrent.atomic.AtomicBoolean, /) -> java.util.concurrent.atomic.AtomicBoolean: ...
    @typing.overload
    @staticmethod
    def asJavaAtomic(this_asJavaAtomic: java.util.concurrent.atomic.AtomicInteger, /) -> java.util.concurrent.atomic.AtomicInteger: ...
    @typing.overload
    @staticmethod
    def asJavaAtomic(this_asJavaAtomic: java.util.concurrent.atomic.AtomicLong, /) -> java.util.concurrent.atomic.AtomicLong: ...
    @typing.overload
    @staticmethod
    def asJavaAtomic(this_asJavaAtomic: java.util.concurrent.atomic.AtomicReference[_asJavaAtomic_3__T], /) -> java.util.concurrent.atomic.AtomicReference[_asJavaAtomic_3__T]: ...
    _asKotlinAtomic_3__T = typing.TypeVar('_asKotlinAtomic_3__T')  # <T>
    @typing.overload
    @staticmethod
    def asKotlinAtomic(this_asKotlinAtomic: java.util.concurrent.atomic.AtomicBoolean, /) -> java.util.concurrent.atomic.AtomicBoolean: ...
    @typing.overload
    @staticmethod
    def asKotlinAtomic(this_asKotlinAtomic: java.util.concurrent.atomic.AtomicInteger, /) -> java.util.concurrent.atomic.AtomicInteger: ...
    @typing.overload
    @staticmethod
    def asKotlinAtomic(this_asKotlinAtomic: java.util.concurrent.atomic.AtomicLong, /) -> java.util.concurrent.atomic.AtomicLong: ...
    @typing.overload
    @staticmethod
    def asKotlinAtomic(this_asKotlinAtomic: java.util.concurrent.atomic.AtomicReference[_asKotlinAtomic_3__T], /) -> java.util.concurrent.atomic.AtomicReference[_asKotlinAtomic_3__T]: ...

class ExperimentalAtomicApi(java.lang.annotation.Annotation): ...
