import typing

import android.content
import android.net
import android.os
import android.view.inputmethod
import java
import java.chaquopy
import java.lang

class EditorInfoCompat(java.lang.Object):
    IME_FLAG_NO_PERSONALIZED_LEARNING: typing.ClassVar[int] = ...
    IME_FLAG_FORCE_ASCII: typing.ClassVar[int] = ...
    def __init__(self) -> None: ...
    @staticmethod
    def getContentMimeTypes(editorInfo: android.view.inputmethod.EditorInfo, /) -> java.chaquopy.JavaArray[java.lang.String]: ...
    @staticmethod
    def setContentMimeTypes(editorInfo: android.view.inputmethod.EditorInfo, contentMimeTypes: java.chaquopy.JavaArray[java.lang.String], /) -> None: ...

class InputConnectionCompat(java.lang.Object):
    INPUT_CONTENT_GRANT_READ_URI_PERMISSION: typing.ClassVar[int] = ...
    def __init__(self) -> None: ...
    @staticmethod
    def commitContent(inputConnection: android.view.inputmethod.InputConnection, editorInfo: android.view.inputmethod.EditorInfo, inputContentInfo: InputContentInfoCompat, flags: int | java.jint | java.lang.Integer, opts: android.os.Bundle, /) -> bool: ...
    @staticmethod
    def createWrapper(inputConnection: android.view.inputmethod.InputConnection, editorInfo: android.view.inputmethod.EditorInfo, onCommitContentListener: InputConnectionCompat.OnCommitContentListener, /) -> android.view.inputmethod.InputConnection: ...

    class OnCommitContentListener(java.lang.Object):
        def onCommitContent(self, arg1: InputContentInfoCompat, arg2: int | java.jint | java.lang.Integer, arg3: android.os.Bundle, /) -> bool: ...

class InputContentInfoCompat(java.lang.Object):
    def __init__(self, contentUri: android.net.Uri, description: android.content.ClipDescription, linkUri: android.net.Uri, /) -> None: ...
    def getContentUri(self) -> android.net.Uri: ...
    def getDescription(self) -> android.content.ClipDescription: ...
    def getLinkUri(self) -> android.net.Uri: ...
    def releasePermission(self) -> None: ...
    def requestPermission(self) -> None: ...
    def unwrap(self) -> java.lang.Object: ...
    @staticmethod
    def wrap(inputContentInfo: java.lang.Object | int | bool | float | str, /) -> InputContentInfoCompat: ...
