import typing

import androidx.constraintlayout.core
import androidx.constraintlayout.core.widgets
import java
import java.lang
import java.util

class BaselineDimensionDependency(DimensionDependency):
    def update(self, node: DependencyNode, /) -> None: ...

class BasicMeasure(java.lang.Object):
    UNSPECIFIED: typing.ClassVar[int] = ...
    EXACTLY: typing.ClassVar[int] = ...
    AT_MOST: typing.ClassVar[int] = ...
    MATCH_PARENT: typing.ClassVar[int] = ...
    WRAP_CONTENT: typing.ClassVar[int] = ...
    FIXED: typing.ClassVar[int] = ...
    def __init__(self, constraintWidgetContainer: androidx.constraintlayout.core.widgets.ConstraintWidgetContainer, /) -> None: ...
    def solverMeasure(self, layout: androidx.constraintlayout.core.widgets.ConstraintWidgetContainer, optimizationLevel: int | java.jint | java.lang.Integer, paddingX: int | java.jint | java.lang.Integer, paddingY: int | java.jint | java.lang.Integer, widthMode: int | java.jint | java.lang.Integer, widthSize: int | java.jint | java.lang.Integer, heightMode: int | java.jint | java.lang.Integer, heightSize: int | java.jint | java.lang.Integer, lastMeasureWidth: int | java.jint | java.lang.Integer, lastMeasureHeight: int | java.jint | java.lang.Integer, /) -> int: ...
    def updateHierarchy(self, layout: androidx.constraintlayout.core.widgets.ConstraintWidgetContainer, /) -> None: ...

    class Measure(java.lang.Object):
        SELF_DIMENSIONS: typing.ClassVar[int] = ...
        TRY_GIVEN_DIMENSIONS: typing.ClassVar[int] = ...
        USE_GIVEN_DIMENSIONS: typing.ClassVar[int] = ...
        horizontalBehavior: androidx.constraintlayout.core.widgets.ConstraintWidget.DimensionBehaviour = ...
        verticalBehavior: androidx.constraintlayout.core.widgets.ConstraintWidget.DimensionBehaviour = ...
        horizontalDimension: int = ...
        verticalDimension: int = ...
        measuredWidth: int = ...
        measuredHeight: int = ...
        measuredBaseline: int = ...
        measuredHasBaseline: bool = ...
        measuredNeedsSolverPass: bool = ...
        measureStrategy: int = ...
        def __init__(self) -> None: ...

    class Measurer(java.lang.Object):
        def didMeasures(self) -> None: ...
        def measure(self, arg1: androidx.constraintlayout.core.widgets.ConstraintWidget, arg2: BasicMeasure.Measure, /) -> None: ...

class ChainRun(WidgetRun):
    def __init__(self, widget: androidx.constraintlayout.core.widgets.ConstraintWidget, orientation: int | java.jint | java.lang.Integer, /) -> None: ...
    def applyToWidget(self) -> None: ...
    def getWrapDimension(self) -> int: ...
    def toString(self) -> str: ...
    def update(self, dependency: Dependency, /) -> None: ...

class Dependency(java.lang.Object):
    def update(self, arg1: Dependency, /) -> None: ...

class DependencyGraph(java.lang.Object):
    def __init__(self, container: androidx.constraintlayout.core.widgets.ConstraintWidgetContainer, /) -> None: ...
    @typing.overload
    def buildGraph(self) -> None: ...
    @typing.overload
    def buildGraph(self, runs: java.util.ArrayList[WidgetRun], /) -> None: ...
    def defineTerminalWidgets(self, horizontalBehavior: androidx.constraintlayout.core.widgets.ConstraintWidget.DimensionBehaviour, verticalBehavior: androidx.constraintlayout.core.widgets.ConstraintWidget.DimensionBehaviour, /) -> None: ...
    def directMeasure(self, optimizeWrap: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def directMeasureSetup(self, optimizeWrap: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def directMeasureWithOrientation(self, optimizeWrap: bool | java.jboolean | java.lang.Boolean, orientation: int | java.jint | java.lang.Integer, /) -> bool: ...
    def invalidateGraph(self) -> None: ...
    def invalidateMeasures(self) -> None: ...
    def measureWidgets(self) -> None: ...
    def setMeasurer(self, measurer: BasicMeasure.Measurer, /) -> None: ...

class DependencyNode(Dependency):
    updateDelegate: Dependency = ...
    delegateToWidgetRun: bool = ...
    readyToSolve: bool = ...
    value: int = ...
    resolved: bool = ...
    def __init__(self, run: WidgetRun, /) -> None: ...
    def addDependency(self, dependency: Dependency, /) -> None: ...
    def clear(self) -> None: ...
    def name(self) -> str: ...
    def resolve(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def toString(self) -> str: ...
    def update(self, node: Dependency, /) -> None: ...

class DimensionDependency(DependencyNode):
    wrapValue: int = ...
    def resolve(self, value: int | java.jint | java.lang.Integer, /) -> None: ...

class Direct(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def ls(level: int | java.jint | java.lang.Integer, /) -> str: ...
    @staticmethod
    def solveChain(container: androidx.constraintlayout.core.widgets.ConstraintWidgetContainer, system: androidx.constraintlayout.core.LinearSystem, orientation: int | java.jint | java.lang.Integer, offset: int | java.jint | java.lang.Integer, chainHead: androidx.constraintlayout.core.widgets.ChainHead, isChainSpread: bool | java.jboolean | java.lang.Boolean, isChainSpreadInside: bool | java.jboolean | java.lang.Boolean, isChainPacked: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    @staticmethod
    def solvingPass(layout: androidx.constraintlayout.core.widgets.ConstraintWidgetContainer, measurer: BasicMeasure.Measurer, /) -> None: ...

class Grouping(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def findDependents(constraintWidget: androidx.constraintlayout.core.widgets.ConstraintWidget, orientation: int | java.jint | java.lang.Integer, list: java.util.ArrayList[WidgetGroup], group: WidgetGroup, /) -> WidgetGroup: ...
    @staticmethod
    def simpleSolvingPass(layout: androidx.constraintlayout.core.widgets.ConstraintWidgetContainer, measurer: BasicMeasure.Measurer, /) -> bool: ...
    @staticmethod
    def validInGroup(layoutHorizontal: androidx.constraintlayout.core.widgets.ConstraintWidget.DimensionBehaviour, layoutVertical: androidx.constraintlayout.core.widgets.ConstraintWidget.DimensionBehaviour, widgetHorizontal: androidx.constraintlayout.core.widgets.ConstraintWidget.DimensionBehaviour, widgetVertical: androidx.constraintlayout.core.widgets.ConstraintWidget.DimensionBehaviour, /) -> bool: ...

class GuidelineReference(WidgetRun):
    def applyToWidget(self) -> None: ...
    def update(self, dependency: Dependency, /) -> None: ...

class HelperReferences(WidgetRun):
    def applyToWidget(self) -> None: ...
    def update(self, dependency: Dependency, /) -> None: ...

class HorizontalWidgetRun(WidgetRun):
    def __init__(self, widget: androidx.constraintlayout.core.widgets.ConstraintWidget, /) -> None: ...
    def applyToWidget(self) -> None: ...
    def toString(self) -> str: ...
    def update(self, dependency: Dependency, /) -> None: ...

class RunGroup(java.lang.Object):
    START: typing.ClassVar[int] = ...
    END: typing.ClassVar[int] = ...
    BASELINE: typing.ClassVar[int] = ...
    index: typing.ClassVar[int] = ...
    position: int = ...
    dual: bool = ...
    def add(self, run: WidgetRun, /) -> None: ...
    def computeWrapSize(self, container: androidx.constraintlayout.core.widgets.ConstraintWidgetContainer, orientation: int | java.jint | java.lang.Integer, /) -> int: ...
    def defineTerminalWidgets(self, horizontalCheck: bool | java.jboolean | java.lang.Boolean, verticalCheck: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class VerticalWidgetRun(WidgetRun):
    baseline: DependencyNode = ...
    def __init__(self, widget: androidx.constraintlayout.core.widgets.ConstraintWidget, /) -> None: ...
    def applyToWidget(self) -> None: ...
    def toString(self) -> str: ...
    def update(self, dependency: Dependency, /) -> None: ...

class WidgetGroup(java.lang.Object):
    def __init__(self, orientation: int | java.jint | java.lang.Integer, /) -> None: ...
    def add(self, widget: androidx.constraintlayout.core.widgets.ConstraintWidget, /) -> bool: ...
    def apply(self) -> None: ...
    def cleanup(self, dependencyLists: java.util.ArrayList[WidgetGroup], /) -> None: ...
    def clear(self) -> None: ...
    def getId(self) -> int: ...
    def getOrientation(self) -> int: ...
    def intersectWith(self, group: WidgetGroup, /) -> bool: ...
    def isAuthoritative(self) -> bool: ...
    def measureWrap(self, system: androidx.constraintlayout.core.LinearSystem, orientation: int | java.jint | java.lang.Integer, /) -> int: ...
    def moveTo(self, orientation: int | java.jint | java.lang.Integer, widgetGroup: WidgetGroup, /) -> None: ...
    def setAuthoritative(self, isAuthoritative: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setOrientation(self, orientation: int | java.jint | java.lang.Integer, /) -> None: ...
    def size(self) -> int: ...
    def toString(self) -> str: ...

class WidgetRun(Dependency):
    matchConstraintsType: int = ...
    mDimensionBehavior: androidx.constraintlayout.core.widgets.ConstraintWidget.DimensionBehaviour = ...
    orientation: int = ...
    start: DependencyNode = ...
    end: DependencyNode = ...
    mRunType: WidgetRun.RunType = ...
    def __init__(self, widget: androidx.constraintlayout.core.widgets.ConstraintWidget, /) -> None: ...
    @typing.overload
    def addTarget(self, node: DependencyNode, target: DependencyNode, margin: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def addTarget(self, node: DependencyNode, target: DependencyNode, marginFactor: int | java.jint | java.lang.Integer, dimensionDependency: DimensionDependency, /) -> None: ...
    def getLimitedDimension(self, dimension: int | java.jint | java.lang.Integer, orientation: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    def getTarget(self, anchor: androidx.constraintlayout.core.widgets.ConstraintAnchor, /) -> DependencyNode: ...
    @typing.overload
    def getTarget(self, anchor: androidx.constraintlayout.core.widgets.ConstraintAnchor, orientation: int | java.jint | java.lang.Integer, /) -> DependencyNode: ...
    def getWrapDimension(self) -> int: ...
    def isCenterConnection(self) -> bool: ...
    def isDimensionResolved(self) -> bool: ...
    def isResolved(self) -> bool: ...
    def update(self, dependency: Dependency, /) -> None: ...
    def updateRunCenter(self, dependency: Dependency, startAnchor: androidx.constraintlayout.core.widgets.ConstraintAnchor, endAnchor: androidx.constraintlayout.core.widgets.ConstraintAnchor, orientation: int | java.jint | java.lang.Integer, /) -> None: ...
    def updateRunEnd(self, dependency: Dependency, /) -> None: ...
    def updateRunStart(self, dependency: Dependency, /) -> None: ...
    def wrapSize(self, direction: int | java.jint | java.lang.Integer, /) -> int: ...
