import android.content
import android.view
import java
import java.lang
import org
import org.osmdroid.views
import org.osmdroid.views.overlay
import typing



class OneFingerZoomOverlay(org.osmdroid.views.overlay.Overlay):
    def __init__(self) -> None: ...
    def onDoubleTap(self, event: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onDoubleTapEvent(self, event: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onTouchEvent(self, event: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...

class RotationGestureDetector(java.lang.Object):
    mRotation: float = ...
    def __init__(self, listener: RotationGestureDetector.RotationListener, /) -> None: ...
    def isEnabled(self) -> bool: ...
    def onTouch(self, e: android.view.MotionEvent, /) -> None: ...
    def setEnabled(self, pEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

    class RotationListener(java.lang.Object):
        def onRotate(self, arg1: float | java.jfloat | java.lang.Float, /) -> None: ...

class RotationGestureOverlay(org.osmdroid.views.overlay.Overlay, org.osmdroid.views.overlay.gestures.RotationGestureDetector.RotationListener, org.osmdroid.views.overlay.IOverlayMenuProvider):
    @typing.overload
    def __init__(self, mapView: org.osmdroid.views.MapView, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, mapView: org.osmdroid.views.MapView, /) -> None: ...
    def isOptionsMenuEnabled(self) -> bool: ...
    def onCreateOptionsMenu(self, pMenu: android.view.Menu, pMenuIdOffset: int | java.jint | java.lang.Integer, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onDetach(self, map: org.osmdroid.views.MapView, /) -> None: ...
    def onOptionsItemSelected(self, pItem: android.view.MenuItem, pMenuIdOffset: int | java.jint | java.lang.Integer, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onPrepareOptionsMenu(self, pMenu: android.view.Menu, pMenuIdOffset: int | java.jint | java.lang.Integer, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onRotate(self, deltaAngle: float | java.jfloat | java.lang.Float, /) -> None: ...
    def onTouchEvent(self, event: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def setEnabled(self, pEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setOptionsMenuEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
