import java.lang
import java.lang.annotation

class BitwiseOperationsKt(java.lang.Object): ...

class ExperimentalObjCName(java.lang.annotation.Annotation): ...

class ExperimentalObjCRefinement(java.lang.annotation.Annotation): ...

class ExperimentalTypeInference(java.lang.annotation.Annotation): ...
