import java.lang
import org.w3c.dom

class BrowserPackage-Properties-178c8a05(java.lang.Object):
    @staticmethod
    def getDocument() -> org.w3c.dom.Document: ...
    @staticmethod
    def get_document() -> org.w3c.dom.Document: ...
    @staticmethod
    def setDocument(value: org.w3c.dom.Document, /) -> None: ...
    @staticmethod
    def set_document(set___: org.w3c.dom.Document, /) -> None: ...

class BrowserPackage(java.lang.Object):
    @staticmethod
    def getDocument() -> org.w3c.dom.Document: ...
    @staticmethod
    def get_document() -> org.w3c.dom.Document: ...
    @staticmethod
    def setDocument(value: org.w3c.dom.Document, /) -> None: ...
    @staticmethod
    def set_document(set___: org.w3c.dom.Document, /) -> None: ...
