import typing

import android.content
import android.view
import java
import java.lang

class MaterialColors(java.lang.Object):
    ALPHA_FULL: typing.ClassVar[float] = ...
    ALPHA_MEDIUM: typing.ClassVar[float] = ...
    ALPHA_DISABLED: typing.ClassVar[float] = ...
    ALPHA_LOW: typing.ClassVar[float] = ...
    ALPHA_DISABLED_LOW: typing.ClassVar[float] = ...
    def __init__(self) -> None: ...
    @typing.overload
    @staticmethod
    def getColor(view: android.view.View, colorAttributeResId: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getColor(context: android.content.Context, colorAttributeResId: int | java.jint | java.lang.Integer, defaultValue: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getColor(context: android.content.Context, colorAttributeResId: int | java.jint | java.lang.Integer, errorMessageComponent: str | java.lang.String, /) -> int: ...
    @typing.overload
    @staticmethod
    def getColor(view: android.view.View, colorAttributeResId: int | java.jint | java.lang.Integer, defaultValue: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def layer(backgroundColor: int | java.jint | java.lang.Integer, overlayColor: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def layer(backgroundColor: int | java.jint | java.lang.Integer, overlayColor: int | java.jint | java.lang.Integer, overlayAlpha: float | java.jfloat | java.lang.Float, /) -> int: ...
    @typing.overload
    @staticmethod
    def layer(view: android.view.View, backgroundColorAttributeResId: int | java.jint | java.lang.Integer, overlayColorAttributeResId: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def layer(view: android.view.View, backgroundColorAttributeResId: int | java.jint | java.lang.Integer, overlayColorAttributeResId: int | java.jint | java.lang.Integer, overlayAlpha: float | java.jfloat | java.lang.Float, /) -> int: ...
