import typing

import java
import java.lang

class Constants(java.lang.Object):
    LN2: typing.ClassVar[float] = ...
    epsilon: typing.ClassVar[float] = ...
    taylor_2_bound: typing.ClassVar[float] = ...
    taylor_n_bound: typing.ClassVar[float] = ...
    upper_taylor_2_bound: typing.ClassVar[float] = ...
    upper_taylor_n_bound: typing.ClassVar[float] = ...
    INSTANCE: typing.ClassVar[Constants] = ...

class MathKt(MathKt__MathJVMKt):
    E: typing.ClassVar[float] = ...
    PI: typing.ClassVar[float] = ...

class MathKt__MathHKt(java.lang.Object):
    def __init__(self) -> None: ...

class MathKt__MathJVMKt(MathKt__MathHKt):
    def __init__(self) -> None: ...
    @staticmethod
    def acosh(x: float | java.jdouble | java.lang.Double, /) -> float: ...
    @staticmethod
    def asinh(x: float | java.jdouble | java.lang.Double, /) -> float: ...
    @staticmethod
    def atanh(x: float | java.jdouble | java.lang.Double, /) -> float: ...
    @typing.overload
    @staticmethod
    def getSign(this_sign: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getSign(this_sign: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def log(x: float | java.jdouble | java.lang.Double, base: float | java.jdouble | java.lang.Double, /) -> float: ...
    @typing.overload
    @staticmethod
    def log(x: float | java.jfloat | java.lang.Float, base: float | java.jfloat | java.lang.Float, /) -> float: ...
    @typing.overload
    @staticmethod
    def log2(x: float | java.jdouble | java.lang.Double, /) -> float: ...
    @typing.overload
    @staticmethod
    def log2(x: float | java.jfloat | java.lang.Float, /) -> float: ...
    @typing.overload
    @staticmethod
    def roundToInt(this_roundToInt: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def roundToInt(this_roundToInt: float | java.jfloat | java.lang.Float, /) -> int: ...
    @typing.overload
    @staticmethod
    def roundToLong(this_roundToLong: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def roundToLong(this_roundToLong: float | java.jfloat | java.lang.Float, /) -> int: ...
    @typing.overload
    @staticmethod
    def truncate(x: float | java.jdouble | java.lang.Double, /) -> float: ...
    @typing.overload
    @staticmethod
    def truncate(x: float | java.jfloat | java.lang.Float, /) -> float: ...

class UMathKt(java.lang.Object): ...
