import android.content
import android.view
import java
import java.chaquopy
import java.lang
import typing



class ElevationOverlayProvider(java.lang.Object):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, elevationOverlayEnabled: bool | java.jboolean | java.lang.Boolean, elevationOverlayColor: int | java.jint | java.lang.Integer, elevationOverlayAccentColor: int | java.jint | java.lang.Integer, colorSurface: int | java.jint | java.lang.Integer, displayDensity: float | java.jfloat | java.lang.Float, /) -> None: ...
    def calculateOverlayAlpha(self, elevation: float | java.jfloat | java.lang.Float, /) -> int: ...
    def calculateOverlayAlphaFraction(self, elevation: float | java.jfloat | java.lang.Float, /) -> float: ...
    @typing.overload
    def compositeOverlay(self, backgroundColor: int | java.jint | java.lang.Integer, elevation: float | java.jfloat | java.lang.Float, /) -> int: ...
    @typing.overload
    def compositeOverlay(self, backgroundColor: int | java.jint | java.lang.Integer, elevation: float | java.jfloat | java.lang.Float, overlayView: android.view.View, /) -> int: ...
    @typing.overload
    def compositeOverlayIfNeeded(self, backgroundColor: int | java.jint | java.lang.Integer, elevation: float | java.jfloat | java.lang.Float, /) -> int: ...
    @typing.overload
    def compositeOverlayIfNeeded(self, backgroundColor: int | java.jint | java.lang.Integer, elevation: float | java.jfloat | java.lang.Float, overlayView: android.view.View, /) -> int: ...
    @typing.overload
    def compositeOverlayWithThemeSurfaceColorIfNeeded(self, elevation: float | java.jfloat | java.lang.Float, /) -> int: ...
    @typing.overload
    def compositeOverlayWithThemeSurfaceColorIfNeeded(self, elevation: float | java.jfloat | java.lang.Float, overlayView: android.view.View, /) -> int: ...
    def getParentAbsoluteElevation(self, overlayView: android.view.View, /) -> float: ...
    def getThemeElevationOverlayColor(self) -> int: ...
    def getThemeSurfaceColor(self) -> int: ...
    def isThemeElevationOverlayEnabled(self) -> bool: ...

class SurfaceColors(java.lang.Enum[SurfaceColors]):
    SURFACE_0: typing.ClassVar[SurfaceColors] = ...
    SURFACE_1: typing.ClassVar[SurfaceColors] = ...
    SURFACE_2: typing.ClassVar[SurfaceColors] = ...
    SURFACE_3: typing.ClassVar[SurfaceColors] = ...
    SURFACE_4: typing.ClassVar[SurfaceColors] = ...
    SURFACE_5: typing.ClassVar[SurfaceColors] = ...
    def getColor(self, context: android.content.Context, /) -> int: ...
    @staticmethod
    def getColorForElevation(context: android.content.Context, elevation: float | java.jfloat | java.lang.Float, /) -> int: ...
    @staticmethod
    def valueOf(name: str | java.lang.String, /) -> SurfaceColors: ...
    @staticmethod
    def values() -> java.chaquopy.JavaArray[SurfaceColors]: ...
