import java.lang

class ArtificialStackFrames(java.lang.Object):
    def __init__(self) -> None: ...
    def coroutineBoundary(self) -> java.lang.StackTraceElement: ...
    def coroutineCreation(self) -> java.lang.StackTraceElement: ...

class CoroutineDebuggingKt(java.lang.Object):
    @staticmethod
    def getARTIFICIAL_FRAME_PACKAGE_NAME() -> str: ...

class _BOUNDARY(java.lang.Object):
    def __init__(self) -> None: ...

class _CREATION(java.lang.Object):
    def __init__(self) -> None: ...
