import android.graphics
import android.view
import java
import java.lang
import java.util
import kotlin
import kotlin.jvm.functions
import kotlin.sequences

class MenuKt(java.lang.Object):
    @staticmethod
    def contains(receiver: android.view.Menu, item: android.view.MenuItem, /) -> bool: ...
    @staticmethod
    def forEach(receiver: android.view.Menu, action: kotlin.jvm.functions.Function1[android.view.MenuItem, kotlin.Unit], /) -> None: ...
    @staticmethod
    def forEachIndexed(receiver: android.view.Menu, action: kotlin.jvm.functions.Function2[int, android.view.MenuItem, kotlin.Unit], /) -> None: ...
    @staticmethod
    def get(receiver: android.view.Menu, index: int | java.jint | java.lang.Integer, /) -> android.view.MenuItem: ...
    @staticmethod
    def getSize(receiver: android.view.Menu, /) -> int: ...
    @staticmethod
    def isEmpty(receiver: android.view.Menu, /) -> bool: ...
    @staticmethod
    def isNotEmpty(receiver: android.view.Menu, /) -> bool: ...
    @staticmethod
    def iterator(receiver: android.view.Menu, /) -> java.util.Iterator[android.view.MenuItem]: ...

class ViewGroupKt(java.lang.Object):
    @staticmethod
    def contains(receiver: android.view.ViewGroup, view: android.view.View, /) -> bool: ...
    @staticmethod
    def forEach(receiver: android.view.ViewGroup, action: kotlin.jvm.functions.Function1[android.view.View, kotlin.Unit], /) -> None: ...
    @staticmethod
    def forEachIndexed(receiver: android.view.ViewGroup, action: kotlin.jvm.functions.Function2[int, android.view.View, kotlin.Unit], /) -> None: ...
    @staticmethod
    def get(receiver: android.view.ViewGroup, index: int | java.jint | java.lang.Integer, /) -> android.view.View: ...
    @staticmethod
    def getChildren(receiver: android.view.ViewGroup, /) -> kotlin.sequences.Sequence[android.view.View]: ...
    @staticmethod
    def getSize(receiver: android.view.ViewGroup, /) -> int: ...
    @staticmethod
    def isEmpty(receiver: android.view.ViewGroup, /) -> bool: ...
    @staticmethod
    def isNotEmpty(receiver: android.view.ViewGroup, /) -> bool: ...
    @staticmethod
    def iterator(receiver: android.view.ViewGroup, /) -> java.util.Iterator[android.view.View]: ...
    @staticmethod
    def minusAssign(receiver: android.view.ViewGroup, view: android.view.View, /) -> None: ...
    @staticmethod
    def plusAssign(receiver: android.view.ViewGroup, view: android.view.View, /) -> None: ...
    @staticmethod
    def setMargins(receiver: android.view.ViewGroup.MarginLayoutParams, size: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def updateMargins(receiver: android.view.ViewGroup.MarginLayoutParams, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def updateMarginsRelative(receiver: android.view.ViewGroup.MarginLayoutParams, start: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, end: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...

class ViewKt(java.lang.Object):
    @staticmethod
    def announceForAccessibility(receiver: android.view.View, resource: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def doOnLayout(receiver: android.view.View, action: kotlin.jvm.functions.Function1[android.view.View, kotlin.Unit], /) -> None: ...
    @staticmethod
    def doOnNextLayout(receiver: android.view.View, action: kotlin.jvm.functions.Function1[android.view.View, kotlin.Unit], /) -> None: ...
    @staticmethod
    def doOnPreDraw(receiver: android.view.View, action: kotlin.jvm.functions.Function1[android.view.View, kotlin.Unit], /) -> None: ...
    @staticmethod
    def isGone(receiver: android.view.View, /) -> bool: ...
    @staticmethod
    def isInvisible(receiver: android.view.View, /) -> bool: ...
    @staticmethod
    def isVisible(receiver: android.view.View, /) -> bool: ...
    @staticmethod
    def postDelayed(receiver: android.view.View, delayInMillis: int | java.jlong | java.lang.Long, action: kotlin.jvm.functions.Function0[kotlin.Unit], /) -> java.lang.Runnable: ...
    @staticmethod
    def postOnAnimationDelayed(receiver: android.view.View, delayInMillis: int | java.jlong | java.lang.Long, action: kotlin.jvm.functions.Function0[kotlin.Unit], /) -> java.lang.Runnable: ...
    @staticmethod
    def setGone(receiver: android.view.View, value: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def setInvisible(receiver: android.view.View, value: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def setPadding(receiver: android.view.View, size: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setVisible(receiver: android.view.View, value: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def toBitmap(receiver: android.view.View, config: android.graphics.Bitmap.Config, /) -> android.graphics.Bitmap: ...
    @staticmethod
    def updateLayoutParams(receiver: android.view.View, block: kotlin.jvm.functions.Function1[android.view.ViewGroup.LayoutParams, kotlin.Unit], /) -> None: ...
    @staticmethod
    def updatePadding(receiver: android.view.View, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def updatePaddingRelative(receiver: android.view.View, start: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, end: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
