import typing

import android.animation
import android.content
import android.content.res
import android.graphics
import android.graphics.drawable
import android.os
import android.util
import android.view
import android.widget
import androidx.appcompat.view.menu
import androidx.appcompat.widget
import androidx.core.view
import androidx.recyclerview.widget
import androidx.transition
import java
import java.chaquopy
import java.lang
import java.lang.annotation

class BaselineLayout(android.view.ViewGroup):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def getBaseline(self) -> int: ...
    def onLayout(self, changed: bool | java.jboolean | java.lang.Boolean, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...

class CheckableImageButton(androidx.appcompat.widget.AppCompatImageButton, android.widget.Checkable):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def isChecked(self) -> bool: ...
    def onCreateDrawableState(self, extraSpace: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJInt: ...
    def setChecked(self, checked: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def toggle(self) -> None: ...

class CircularBorderDrawable(android.graphics.drawable.Drawable):
    def __init__(self) -> None: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getConstantState(self) -> android.graphics.drawable.Drawable.ConstantState: ...
    def getOpacity(self) -> int: ...
    def getPadding(self, padding: android.graphics.Rect, /) -> bool: ...
    def isStateful(self) -> bool: ...
    def onBoundsChange(self, bounds: android.graphics.Rect, /) -> None: ...
    def onStateChange(self, state: java.chaquopy.JavaArrayJInt, /) -> bool: ...
    def setAlpha(self, alpha: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBorderTint(self, tint: android.content.res.ColorStateList, /) -> None: ...
    def setBorderWidth(self, width: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setColorFilter(self, colorFilter: android.graphics.ColorFilter, /) -> None: ...
    def setGradientColors(self, topOuterStrokeColor: int | java.jint | java.lang.Integer, topInnerStrokeColor: int | java.jint | java.lang.Integer, bottomOuterStrokeColor: int | java.jint | java.lang.Integer, bottomInnerStrokeColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setRotation(self, rotation: float | java.jfloat | java.lang.Float, /) -> None: ...

class CircularBorderDrawableLollipop(CircularBorderDrawable):
    def __init__(self) -> None: ...
    def getOutline(self, outline: android.graphics.Outline, /) -> None: ...

class CollapsingTextHelper(java.lang.Object):
    def __init__(self, view: android.view.View, /) -> None: ...
    def calculateCollapsedTextWidth(self) -> float: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getCollapsedTextActualBounds(self, bounds: android.graphics.RectF, /) -> None: ...
    def getCollapsedTextColor(self) -> android.content.res.ColorStateList: ...
    def getCollapsedTextGravity(self) -> int: ...
    def getCollapsedTextHeight(self) -> float: ...
    def getCollapsedTextSize(self) -> float: ...
    def getCollapsedTypeface(self) -> android.graphics.Typeface: ...
    def getCurrentCollapsedTextColor(self) -> int: ...
    def getExpandedTextColor(self) -> android.content.res.ColorStateList: ...
    def getExpandedTextGravity(self) -> int: ...
    def getExpandedTextSize(self) -> float: ...
    def getExpandedTypeface(self) -> android.graphics.Typeface: ...
    def getExpansionFraction(self) -> float: ...
    def getText(self) -> java.lang.CharSequence: ...
    def isStateful(self) -> bool: ...
    def recalculate(self) -> None: ...
    def setCollapsedBounds(self, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCollapsedTextAppearance(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCollapsedTextColor(self, textColor: android.content.res.ColorStateList, /) -> None: ...
    def setCollapsedTextGravity(self, gravity: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCollapsedTextSize(self, textSize: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setCollapsedTypeface(self, typeface: android.graphics.Typeface, /) -> None: ...
    def setExpandedBounds(self, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setExpandedTextAppearance(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setExpandedTextColor(self, textColor: android.content.res.ColorStateList, /) -> None: ...
    def setExpandedTextGravity(self, gravity: int | java.jint | java.lang.Integer, /) -> None: ...
    def setExpandedTextSize(self, textSize: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setExpandedTypeface(self, typeface: android.graphics.Typeface, /) -> None: ...
    def setExpansionFraction(self, fraction: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setPositionInterpolator(self, interpolator: android.animation.TimeInterpolator, /) -> None: ...
    def setState(self, state: java.chaquopy.JavaArrayJInt, /) -> bool: ...
    def setText(self, text: java.lang.CharSequence, /) -> None: ...
    def setTextSizeInterpolator(self, interpolator: android.animation.TimeInterpolator, /) -> None: ...
    def setTypefaces(self, typeface: android.graphics.Typeface, /) -> None: ...

class DescendantOffsetUtils(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def getDescendantRect(parent: android.view.ViewGroup, descendant: android.view.View, out: android.graphics.Rect, /) -> None: ...
    @staticmethod
    def offsetDescendantRect(parent: android.view.ViewGroup, descendant: android.view.View, rect: android.graphics.Rect, /) -> None: ...

class DrawableUtils(java.lang.Object):
    @staticmethod
    def setContainerConstantState(drawable: android.graphics.drawable.DrawableContainer, constantState: android.graphics.drawable.Drawable.ConstantState, /) -> bool: ...

class Experimental(java.lang.annotation.Annotation):
    def value(self) -> str: ...

class FlowLayout(android.view.ViewGroup):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, /) -> None: ...
    def getItemSpacing(self) -> int: ...
    def getLineSpacing(self) -> int: ...
    def isSingleLine(self) -> bool: ...
    def onLayout(self, sizeChanged: bool | java.jboolean | java.lang.Boolean, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemSpacing(self, itemSpacing: int | java.jint | java.lang.Integer, /) -> None: ...
    def setLineSpacing(self, lineSpacing: int | java.jint | java.lang.Integer, /) -> None: ...
    def setSingleLine(self, singleLine: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class ForegroundLinearLayout(androidx.appcompat.widget.LinearLayoutCompat):
    mForegroundInPadding: bool = ...
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyle: int | java.jint | java.lang.Integer, /) -> None: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def drawableHotspotChanged(self, x: float | java.jfloat | java.lang.Float, y: float | java.jfloat | java.lang.Float, /) -> None: ...
    def drawableStateChanged(self) -> None: ...
    def getForeground(self) -> android.graphics.drawable.Drawable: ...
    def getForegroundGravity(self) -> int: ...
    def jumpDrawablesToCurrentState(self) -> None: ...
    def onLayout(self, changed: bool | java.jboolean | java.lang.Boolean, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def onSizeChanged(self, w: int | java.jint | java.lang.Integer, h: int | java.jint | java.lang.Integer, oldw: int | java.jint | java.lang.Integer, oldh: int | java.jint | java.lang.Integer, /) -> None: ...
    def setForeground(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...
    def setForegroundGravity(self, foregroundGravity: int | java.jint | java.lang.Integer, /) -> None: ...
    def verifyDrawable(self, who: android.graphics.drawable.Drawable, /) -> bool: ...

class NavigationMenu(androidx.appcompat.view.menu.MenuBuilder):
    def __init__(self, context: android.content.Context, /) -> None: ...
    def addSubMenu(self, group: int | java.jint | java.lang.Integer, id: int | java.jint | java.lang.Integer, categoryOrder: int | java.jint | java.lang.Integer, title: java.lang.CharSequence, /) -> android.view.SubMenu: ...

class NavigationMenuItemView(ForegroundLinearLayout, androidx.appcompat.view.menu.MenuView.ItemView):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def getItemData(self) -> androidx.appcompat.view.menu.MenuItemImpl: ...
    def initialize(self, itemData: androidx.appcompat.view.menu.MenuItemImpl, menuType: int | java.jint | java.lang.Integer, /) -> None: ...
    def onCreateDrawableState(self, extraSpace: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJInt: ...
    def prefersCondensedTitle(self) -> bool: ...
    def recycle(self) -> None: ...
    def setCheckable(self, checkable: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setChecked(self, checked: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setHorizontalPadding(self, padding: int | java.jint | java.lang.Integer, /) -> None: ...
    def setIcon(self, icon: android.graphics.drawable.Drawable, /) -> None: ...
    def setIconPadding(self, padding: int | java.jint | java.lang.Integer, /) -> None: ...
    def setNeedsEmptyIcon(self, needsEmptyIcon: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setShortcut(self, showShortcut: bool | java.jboolean | java.lang.Boolean, shortcutKey: str | java.jchar | java.lang.Character, /) -> None: ...
    def setTextAppearance(self, textAppearance: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTextColor(self, colors: android.content.res.ColorStateList, /) -> None: ...
    def setTitle(self, title: java.lang.CharSequence, /) -> None: ...
    def showsIcon(self) -> bool: ...

class NavigationMenuPresenter(androidx.appcompat.view.menu.MenuPresenter):
    def __init__(self) -> None: ...
    def addHeaderView(self, view: android.view.View, /) -> None: ...
    def collapseItemActionView(self, menu: androidx.appcompat.view.menu.MenuBuilder, item: androidx.appcompat.view.menu.MenuItemImpl, /) -> bool: ...
    def dispatchApplyWindowInsets(self, insets: androidx.core.view.WindowInsetsCompat, /) -> None: ...
    def expandItemActionView(self, menu: androidx.appcompat.view.menu.MenuBuilder, item: androidx.appcompat.view.menu.MenuItemImpl, /) -> bool: ...
    def flagActionItems(self) -> bool: ...
    def getCheckedItem(self) -> androidx.appcompat.view.menu.MenuItemImpl: ...
    def getHeaderCount(self) -> int: ...
    def getHeaderView(self, index: int | java.jint | java.lang.Integer, /) -> android.view.View: ...
    def getId(self) -> int: ...
    def getItemBackground(self) -> android.graphics.drawable.Drawable: ...
    def getItemHorizontalPadding(self) -> int: ...
    def getItemIconPadding(self) -> int: ...
    def getItemTextColor(self) -> android.content.res.ColorStateList: ...
    def getItemTintList(self) -> android.content.res.ColorStateList: ...
    def getMenuView(self, root: android.view.ViewGroup, /) -> androidx.appcompat.view.menu.MenuView: ...
    def inflateHeaderView(self, res: int | java.jint | java.lang.Integer, /) -> android.view.View: ...
    def initForMenu(self, context: android.content.Context, menu: androidx.appcompat.view.menu.MenuBuilder, /) -> None: ...
    def onCloseMenu(self, menu: androidx.appcompat.view.menu.MenuBuilder, allMenusAreClosing: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def onRestoreInstanceState(self, parcelable: android.os.Parcelable, /) -> None: ...
    def onSaveInstanceState(self) -> android.os.Parcelable: ...
    def onSubMenuSelected(self, subMenu: androidx.appcompat.view.menu.SubMenuBuilder, /) -> bool: ...
    def removeHeaderView(self, view: android.view.View, /) -> None: ...
    def setCallback(self, cb: androidx.appcompat.view.menu.MenuPresenter.Callback, /) -> None: ...
    def setCheckedItem(self, item: androidx.appcompat.view.menu.MenuItemImpl, /) -> None: ...
    def setId(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemBackground(self, itemBackground: android.graphics.drawable.Drawable, /) -> None: ...
    def setItemHorizontalPadding(self, itemHorizontalPadding: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemIconPadding(self, itemIconPadding: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemIconTintList(self, tint: android.content.res.ColorStateList, /) -> None: ...
    def setItemTextAppearance(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemTextColor(self, textColor: android.content.res.ColorStateList, /) -> None: ...
    def setUpdateSuspended(self, updateSuspended: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def updateMenuView(self, cleared: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class NavigationMenuView(androidx.recyclerview.widget.RecyclerView, androidx.appcompat.view.menu.MenuView):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def getWindowAnimations(self) -> int: ...
    def initialize(self, menu: androidx.appcompat.view.menu.MenuBuilder, /) -> None: ...

class NavigationSubMenu(androidx.appcompat.view.menu.SubMenuBuilder):
    def __init__(self, context: android.content.Context, menu: NavigationMenu, item: androidx.appcompat.view.menu.MenuItemImpl, /) -> None: ...
    def onItemsChanged(self, structureChanged: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class ParcelableSparseArray(android.util.SparseArray[android.os.Parcelable], android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator[ParcelableSparseArray]] = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, source: android.os.Parcel, loader: java.lang.ClassLoader, /) -> None: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, parcel: android.os.Parcel, flags: int | java.jint | java.lang.Integer, /) -> None: ...

class ScrimInsetsFrameLayout(android.widget.FrameLayout):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onInsetsChanged(self, insets: androidx.core.view.WindowInsetsCompat, /) -> None: ...

class StateListAnimator(java.lang.Object):
    def __init__(self) -> None: ...
    def addState(self, specs: java.chaquopy.JavaArrayJInt, animator: android.animation.ValueAnimator, /) -> None: ...
    def jumpToCurrentState(self) -> None: ...
    def setState(self, state: java.chaquopy.JavaArrayJInt, /) -> None: ...

class TextScale(androidx.transition.Transition):
    def __init__(self) -> None: ...
    def captureEndValues(self, transitionValues: androidx.transition.TransitionValues, /) -> None: ...
    def captureStartValues(self, transitionValues: androidx.transition.TransitionValues, /) -> None: ...
    def createAnimator(self, sceneRoot: android.view.ViewGroup, startValues: androidx.transition.TransitionValues, endValues: androidx.transition.TransitionValues, /) -> android.animation.Animator: ...

class ThemeEnforcement(java.lang.Object):
    @staticmethod
    def checkAppCompatTheme(context: android.content.Context, /) -> None: ...
    @staticmethod
    def checkMaterialTheme(context: android.content.Context, /) -> None: ...
    @staticmethod
    def isAppCompatTheme(context: android.content.Context, /) -> bool: ...
    @staticmethod
    def isMaterialTheme(context: android.content.Context, /) -> bool: ...
    @staticmethod
    def obtainStyledAttributes(context: android.content.Context, set: android.util.AttributeSet, attrs: java.chaquopy.JavaArrayJInt, defStyleAttr: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, /, *textAppearanceResIndices: java.jint) -> android.content.res.TypedArray: ...
    @staticmethod
    def obtainTintedStyledAttributes(context: android.content.Context, set: android.util.AttributeSet, attrs: java.chaquopy.JavaArrayJInt, defStyleAttr: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, /, *textAppearanceResIndices: java.jint) -> androidx.appcompat.widget.TintTypedArray: ...

class ViewUtils(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def isLayoutRtl(view: android.view.View, /) -> bool: ...
    @staticmethod
    def parseTintMode(value: int | java.jint | java.lang.Integer, defaultMode: android.graphics.PorterDuff.Mode, /) -> android.graphics.PorterDuff.Mode: ...

class VisibilityAwareImageButton(android.widget.ImageButton):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def getUserSetVisibility(self) -> int: ...
    def internalSetVisibility(self, visibility: int | java.jint | java.lang.Integer, fromUser: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setVisibility(self, visibility: int | java.jint | java.lang.Integer, /) -> None: ...
