import typing

import android.content
import android.content.res
import android.view
import android.view.accessibility
import android.view.animation
import androidx
import androidx.appcompat.view.menu
import androidx.appcompat.widget
import androidx.core.view
import java
import java.lang
import java.util

class ActionBarPolicy(java.lang.Object):
    def enableHomeButtonByDefault(self) -> bool: ...
    @staticmethod
    def get(context: android.content.Context, /) -> ActionBarPolicy: ...
    def getEmbeddedMenuWidthLimit(self) -> int: ...
    def getMaxActionButtons(self) -> int: ...
    def getStackedTabMaxWidth(self) -> int: ...
    def getTabContainerHeight(self) -> int: ...
    def hasEmbeddedTabs(self) -> bool: ...
    def showsOverflowMenuButton(self) -> bool: ...

class ActionMode(java.lang.Object):
    def __init__(self) -> None: ...
    def finish(self) -> None: ...
    def getCustomView(self) -> android.view.View: ...
    def getMenu(self) -> android.view.Menu: ...
    def getMenuInflater(self) -> android.view.MenuInflater: ...
    def getSubtitle(self) -> java.lang.CharSequence: ...
    def getTag(self) -> java.lang.Object: ...
    def getTitle(self) -> java.lang.CharSequence: ...
    def getTitleOptionalHint(self) -> bool: ...
    def invalidate(self) -> None: ...
    def isTitleOptional(self) -> bool: ...
    def isUiFocusable(self) -> bool: ...
    def setCustomView(self, arg1: android.view.View, /) -> None: ...
    @typing.overload
    def setSubtitle(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setSubtitle(self, arg1: java.lang.CharSequence, /) -> None: ...
    def setTag(self, tag: java.lang.Object | int | bool | float | str, /) -> None: ...
    @typing.overload
    def setTitle(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setTitle(self, arg1: java.lang.CharSequence, /) -> None: ...
    def setTitleOptionalHint(self, titleOptional: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

    class Callback(java.lang.Object):
        def onActionItemClicked(self, arg1: ActionMode, arg2: android.view.MenuItem, /) -> bool: ...
        def onCreateActionMode(self, arg1: ActionMode, arg2: android.view.Menu, /) -> bool: ...
        def onDestroyActionMode(self, arg1: ActionMode, /) -> None: ...
        def onPrepareActionMode(self, arg1: ActionMode, arg2: android.view.Menu, /) -> bool: ...

class CollapsibleActionView(java.lang.Object):
    def onActionViewCollapsed(self) -> None: ...
    def onActionViewExpanded(self) -> None: ...

class ContextThemeWrapper(android.content.ContextWrapper):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, base: android.content.Context, themeResId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, base: android.content.Context, theme: android.content.res.Resources.Theme, /) -> None: ...
    def applyOverrideConfiguration(self, overrideConfiguration: android.content.res.Configuration, /) -> None: ...
    def attachBaseContext(self, newBase: android.content.Context, /) -> None: ...
    def getAssets(self) -> android.content.res.AssetManager: ...
    def getResources(self) -> android.content.res.Resources: ...
    def getSystemService(self, name: str | java.lang.String, /) -> java.lang.Object: ...
    def getTheme(self) -> android.content.res.Resources.Theme: ...
    def getThemeResId(self) -> int: ...
    def onApplyThemeResource(self, theme: android.content.res.Resources.Theme, resid: int | java.jint | java.lang.Integer, first: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setTheme(self, resid: int | java.jint | java.lang.Integer, /) -> None: ...

class StandaloneActionMode(ActionMode, androidx.appcompat.view.menu.MenuBuilder.Callback):
    def __init__(self, context: android.content.Context, view: androidx.appcompat.widget.ActionBarContextView, callback: ActionMode.Callback, isFocusable: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def finish(self) -> None: ...
    def getCustomView(self) -> android.view.View: ...
    def getMenu(self) -> android.view.Menu: ...
    def getMenuInflater(self) -> android.view.MenuInflater: ...
    def getSubtitle(self) -> java.lang.CharSequence: ...
    def getTitle(self) -> java.lang.CharSequence: ...
    def invalidate(self) -> None: ...
    def isTitleOptional(self) -> bool: ...
    def isUiFocusable(self) -> bool: ...
    def onCloseMenu(self, menu: androidx.appcompat.view.menu.MenuBuilder, allMenusAreClosing: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def onCloseSubMenu(self, menu: androidx.appcompat.view.menu.SubMenuBuilder, /) -> None: ...
    def onMenuItemSelected(self, menu: androidx.appcompat.view.menu.MenuBuilder, item: android.view.MenuItem, /) -> bool: ...
    def onMenuModeChange(self, menu: androidx.appcompat.view.menu.MenuBuilder, /) -> None: ...
    def onSubMenuSelected(self, subMenu: androidx.appcompat.view.menu.SubMenuBuilder, /) -> bool: ...
    def setCustomView(self, view: android.view.View, /) -> None: ...
    @typing.overload
    def setSubtitle(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setSubtitle(self, subtitle: java.lang.CharSequence, /) -> None: ...
    @typing.overload
    def setTitle(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setTitle(self, title: java.lang.CharSequence, /) -> None: ...
    def setTitleOptionalHint(self, titleOptional: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class SupportActionModeWrapper(android.view.ActionMode):
    def __init__(self, context: android.content.Context, supportActionMode: ActionMode, /) -> None: ...
    def finish(self) -> None: ...
    def getCustomView(self) -> android.view.View: ...
    def getMenu(self) -> android.view.Menu: ...
    def getMenuInflater(self) -> android.view.MenuInflater: ...
    def getSubtitle(self) -> java.lang.CharSequence: ...
    def getTag(self) -> java.lang.Object: ...
    def getTitle(self) -> java.lang.CharSequence: ...
    def getTitleOptionalHint(self) -> bool: ...
    def invalidate(self) -> None: ...
    def isTitleOptional(self) -> bool: ...
    def setCustomView(self, view: android.view.View, /) -> None: ...
    @typing.overload
    def setSubtitle(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setSubtitle(self, subtitle: java.lang.CharSequence, /) -> None: ...
    def setTag(self, tag: java.lang.Object | int | bool | float | str, /) -> None: ...
    @typing.overload
    def setTitle(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setTitle(self, title: java.lang.CharSequence, /) -> None: ...
    def setTitleOptionalHint(self, titleOptional: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

    class CallbackWrapper(androidx.appcompat.view.ActionMode.Callback):
        def __init__(self, context: android.content.Context, supportCallback: android.view.ActionMode.Callback, /) -> None: ...
        def getActionModeWrapper(self, mode: ActionMode, /) -> android.view.ActionMode: ...
        def onActionItemClicked(self, mode: ActionMode, item: android.view.MenuItem, /) -> bool: ...
        def onCreateActionMode(self, mode: ActionMode, menu: android.view.Menu, /) -> bool: ...
        def onDestroyActionMode(self, mode: ActionMode, /) -> None: ...
        def onPrepareActionMode(self, mode: ActionMode, menu: android.view.Menu, /) -> bool: ...

class SupportMenuInflater(android.view.MenuInflater):
    def __init__(self, context: android.content.Context, /) -> None: ...
    def inflate(self, menuRes: int | java.jint | java.lang.Integer, menu: android.view.Menu, /) -> None: ...

class ViewPropertyAnimatorCompatSet(java.lang.Object):
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    def play(self, animator: androidx.core.view.ViewPropertyAnimatorCompat, /) -> ViewPropertyAnimatorCompatSet: ...
    def playSequentially(self, anim1: androidx.core.view.ViewPropertyAnimatorCompat, anim2: androidx.core.view.ViewPropertyAnimatorCompat, /) -> ViewPropertyAnimatorCompatSet: ...
    def setDuration(self, duration: int | java.jlong | java.lang.Long, /) -> ViewPropertyAnimatorCompatSet: ...
    def setInterpolator(self, interpolator: android.view.animation.Interpolator, /) -> ViewPropertyAnimatorCompatSet: ...
    def setListener(self, listener: androidx.core.view.ViewPropertyAnimatorListener, /) -> ViewPropertyAnimatorCompatSet: ...
    def start(self) -> None: ...

class WindowCallbackWrapper(android.view.Window.Callback):
    def __init__(self, wrapped: android.view.Window.Callback, /) -> None: ...
    def dispatchGenericMotionEvent(self, event: android.view.MotionEvent, /) -> bool: ...
    def dispatchKeyEvent(self, event: android.view.KeyEvent, /) -> bool: ...
    def dispatchKeyShortcutEvent(self, event: android.view.KeyEvent, /) -> bool: ...
    def dispatchPopulateAccessibilityEvent(self, event: android.view.accessibility.AccessibilityEvent, /) -> bool: ...
    def dispatchTouchEvent(self, event: android.view.MotionEvent, /) -> bool: ...
    def dispatchTrackballEvent(self, event: android.view.MotionEvent, /) -> bool: ...
    def onActionModeFinished(self, mode: android.view.ActionMode, /) -> None: ...
    def onActionModeStarted(self, mode: android.view.ActionMode, /) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def onContentChanged(self) -> None: ...
    def onCreatePanelMenu(self, featureId: int | java.jint | java.lang.Integer, menu: android.view.Menu, /) -> bool: ...
    def onCreatePanelView(self, featureId: int | java.jint | java.lang.Integer, /) -> android.view.View: ...
    def onDetachedFromWindow(self) -> None: ...
    def onMenuItemSelected(self, featureId: int | java.jint | java.lang.Integer, item: android.view.MenuItem, /) -> bool: ...
    def onMenuOpened(self, featureId: int | java.jint | java.lang.Integer, menu: android.view.Menu, /) -> bool: ...
    def onPanelClosed(self, featureId: int | java.jint | java.lang.Integer, menu: android.view.Menu, /) -> None: ...
    def onPointerCaptureChanged(self, hasCapture: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def onPreparePanel(self, featureId: int | java.jint | java.lang.Integer, view: android.view.View, menu: android.view.Menu, /) -> bool: ...
    def onProvideKeyboardShortcuts(self, data: java.util.List[android.view.KeyboardShortcutGroup], menu: android.view.Menu, deviceId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def onSearchRequested(self) -> bool: ...
    @typing.overload
    def onSearchRequested(self, searchEvent: android.view.SearchEvent, /) -> bool: ...
    def onWindowAttributesChanged(self, attrs: android.view.WindowManager.LayoutParams, /) -> None: ...
    def onWindowFocusChanged(self, hasFocus: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def onWindowStartingActionMode(self, callback: android.view.ActionMode.Callback, /) -> android.view.ActionMode: ...
    @typing.overload
    def onWindowStartingActionMode(self, callback: android.view.ActionMode.Callback, type: int | java.jint | java.lang.Integer, /) -> android.view.ActionMode: ...
