import typing

import android.content
import android.content.res
import android.graphics
import android.graphics.drawable
import android.util
import android.view
import android.widget
import androidx.viewpager.widget
import com
import java
import java.lang
import java.lang.annotation

class TabItem(android.view.View):
    text: java.lang.CharSequence = ...
    icon: android.graphics.drawable.Drawable = ...
    customLayout: int = ...
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...


_TabLayout__BaseOnTabSelectedListener__T = typing.TypeVar('_TabLayout__BaseOnTabSelectedListener__T', bound=TabLayout.Tab)  # <T>
class TabLayout(android.widget.HorizontalScrollView):
    MODE_SCROLLABLE: typing.ClassVar[int] = ...
    MODE_FIXED: typing.ClassVar[int] = ...
    GRAVITY_FILL: typing.ClassVar[int] = ...
    GRAVITY_CENTER: typing.ClassVar[int] = ...
    INDICATOR_GRAVITY_BOTTOM: typing.ClassVar[int] = ...
    INDICATOR_GRAVITY_CENTER: typing.ClassVar[int] = ...
    INDICATOR_GRAVITY_TOP: typing.ClassVar[int] = ...
    INDICATOR_GRAVITY_STRETCH: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def addOnTabSelectedListener(self, listener: TabLayout.BaseOnTabSelectedListener, /) -> None: ...
    @typing.overload
    def addTab(self, tab: TabLayout.Tab, /) -> None: ...
    @typing.overload
    def addTab(self, tab: TabLayout.Tab, position: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def addTab(self, tab: TabLayout.Tab, setSelected: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def addTab(self, tab: TabLayout.Tab, position: int | java.jint | java.lang.Integer, setSelected: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def addView(self, child: android.view.View, /) -> None: ...
    @typing.overload
    def addView(self, child: android.view.View, index: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def addView(self, child: android.view.View, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    @typing.overload
    def addView(self, child: android.view.View, index: int | java.jint | java.lang.Integer, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    def clearOnTabSelectedListeners(self) -> None: ...
    def createTabFromPool(self) -> TabLayout.Tab: ...
    def generateLayoutParams(self, attrs: android.util.AttributeSet, /) -> android.widget.FrameLayout.LayoutParams: ...
    def getSelectedTabPosition(self) -> int: ...
    def getTabAt(self, index: int | java.jint | java.lang.Integer, /) -> TabLayout.Tab: ...
    def getTabCount(self) -> int: ...
    def getTabGravity(self) -> int: ...
    def getTabIconTint(self) -> android.content.res.ColorStateList: ...
    def getTabIndicatorGravity(self) -> int: ...
    def getTabMode(self) -> int: ...
    def getTabRippleColor(self) -> android.content.res.ColorStateList: ...
    def getTabSelectedIndicator(self) -> android.graphics.drawable.Drawable: ...
    def getTabTextColors(self) -> android.content.res.ColorStateList: ...
    def hasUnboundedRipple(self) -> bool: ...
    def isInlineLabel(self) -> bool: ...
    def isTabIndicatorFullWidth(self) -> bool: ...
    def newTab(self) -> TabLayout.Tab: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onDraw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def releaseFromTabPool(self, tab: TabLayout.Tab, /) -> bool: ...
    def removeAllTabs(self) -> None: ...
    def removeOnTabSelectedListener(self, listener: TabLayout.BaseOnTabSelectedListener, /) -> None: ...
    def removeTab(self, tab: TabLayout.Tab, /) -> None: ...
    def removeTabAt(self, position: int | java.jint | java.lang.Integer, /) -> None: ...
    def setInlineLabel(self, inline: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setInlineLabelResource(self, inlineResourceId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setOnTabSelectedListener(self, listener: TabLayout.BaseOnTabSelectedListener, /) -> None: ...
    def setScrollPosition(self, position: int | java.jint | java.lang.Integer, positionOffset: float | java.jfloat | java.lang.Float, updateSelectedText: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def setSelectedTabIndicator(self, tabSelectedIndicatorResourceId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setSelectedTabIndicator(self, tabSelectedIndicator: android.graphics.drawable.Drawable, /) -> None: ...
    def setSelectedTabIndicatorColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    def setSelectedTabIndicatorGravity(self, indicatorGravity: int | java.jint | java.lang.Integer, /) -> None: ...
    def setSelectedTabIndicatorHeight(self, height: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTabGravity(self, gravity: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTabIconTint(self, iconTint: android.content.res.ColorStateList, /) -> None: ...
    def setTabIconTintResource(self, iconTintResourceId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTabIndicatorFullWidth(self, tabIndicatorFullWidth: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setTabMode(self, mode: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTabRippleColor(self, color: android.content.res.ColorStateList, /) -> None: ...
    def setTabRippleColorResource(self, tabRippleColorResourceId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setTabTextColors(self, textColor: android.content.res.ColorStateList, /) -> None: ...
    @typing.overload
    def setTabTextColors(self, normalColor: int | java.jint | java.lang.Integer, selectedColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTabsFromPagerAdapter(self, adapter: androidx.viewpager.widget.PagerAdapter, /) -> None: ...
    def setUnboundedRipple(self, unboundedRipple: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setUnboundedRippleResource(self, unboundedRippleResourceId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setupWithViewPager(self, viewPager: androidx.viewpager.widget.ViewPager, /) -> None: ...
    @typing.overload
    def setupWithViewPager(self, viewPager: androidx.viewpager.widget.ViewPager, autoRefresh: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def shouldDelayChildPressedState(self) -> bool: ...

    class ViewPagerOnTabSelectedListener(com.google.android.material.tabs.TabLayout.OnTabSelectedListener):
        def __init__(self, viewPager: androidx.viewpager.widget.ViewPager, /) -> None: ...
        def onTabReselected(self, tab: TabLayout.Tab, /) -> None: ...
        def onTabSelected(self, tab: TabLayout.Tab, /) -> None: ...
        def onTabUnselected(self, tab: TabLayout.Tab, /) -> None: ...

    class TabLayoutOnPageChangeListener(androidx.viewpager.widget.ViewPager.OnPageChangeListener):
        def __init__(self, tabLayout: TabLayout, /) -> None: ...
        def onPageScrollStateChanged(self, state: int | java.jint | java.lang.Integer, /) -> None: ...
        def onPageScrolled(self, position: int | java.jint | java.lang.Integer, positionOffset: float | java.jfloat | java.lang.Float, positionOffsetPixels: int | java.jint | java.lang.Integer, /) -> None: ...
        def onPageSelected(self, position: int | java.jint | java.lang.Integer, /) -> None: ...

    class Tab(java.lang.Object):
        INVALID_POSITION: typing.ClassVar[int] = ...
        parent: TabLayout = ...
        view: TabLayout.TabView = ...
        def __init__(self) -> None: ...
        def getContentDescription(self) -> java.lang.CharSequence: ...
        def getCustomView(self) -> android.view.View: ...
        def getIcon(self) -> android.graphics.drawable.Drawable: ...
        def getPosition(self) -> int: ...
        def getTag(self) -> java.lang.Object: ...
        def getText(self) -> java.lang.CharSequence: ...
        def isSelected(self) -> bool: ...
        def select(self) -> None: ...
        @typing.overload
        def setContentDescription(self, resId: int | java.jint | java.lang.Integer, /) -> TabLayout.Tab: ...
        @typing.overload
        def setContentDescription(self, contentDesc: java.lang.CharSequence, /) -> TabLayout.Tab: ...
        @typing.overload
        def setCustomView(self, resId: int | java.jint | java.lang.Integer, /) -> TabLayout.Tab: ...
        @typing.overload
        def setCustomView(self, view: android.view.View, /) -> TabLayout.Tab: ...
        @typing.overload
        def setIcon(self, resId: int | java.jint | java.lang.Integer, /) -> TabLayout.Tab: ...
        @typing.overload
        def setIcon(self, icon: android.graphics.drawable.Drawable, /) -> TabLayout.Tab: ...
        def setTag(self, tag: java.lang.Object | int | bool | float | str, /) -> TabLayout.Tab: ...
        @typing.overload
        def setText(self, resId: int | java.jint | java.lang.Integer, /) -> TabLayout.Tab: ...
        @typing.overload
        def setText(self, text: java.lang.CharSequence, /) -> TabLayout.Tab: ...

    class OnTabSelectedListener(com.google.android.material.tabs.TabLayout.BaseOnTabSelectedListener[TabLayout.Tab]): ...
    class BaseOnTabSelectedListener(java.lang.Object, typing.Generic[_TabLayout__BaseOnTabSelectedListener__T]):
        def onTabReselected(self, arg1: _TabLayout__BaseOnTabSelectedListener__T, /) -> None: ...
        def onTabSelected(self, arg1: _TabLayout__BaseOnTabSelectedListener__T, /) -> None: ...
        def onTabUnselected(self, arg1: _TabLayout__BaseOnTabSelectedListener__T, /) -> None: ...

    class TabIndicatorGravity(java.lang.annotation.Annotation): ...

    class TabGravity(java.lang.annotation.Annotation): ...

    class Mode(java.lang.annotation.Annotation): ...
