import java.lang.annotation
import kotlin.jvm.internal

class strictfp(kotlin.jvm.internal.KObject, java.lang.annotation.Annotation): ...

class synchronized(kotlin.jvm.internal.KObject, java.lang.annotation.Annotation): ...

class transient(kotlin.jvm.internal.KObject, java.lang.annotation.Annotation): ...

class volatile(kotlin.jvm.internal.KObject, java.lang.annotation.Annotation): ...
