import typing

import android.content
import android.content.res
import android.os
import android.util
import java
import java.chaquopy
import java.io
import java.lang
import java.lang.annotation
import java.util
import java.util.concurrent
import java.util.function
import kotlinx.coroutines.flow

class BufferFillPolicy(java.lang.Object):
    Companion: typing.ClassVar[BufferFillPolicy.Companion] = ...
    DISCARD: typing.ClassVar[BufferFillPolicy] = ...
    RING_BUFFER: typing.ClassVar[BufferFillPolicy] = ...

    class Companion(java.lang.Object): ...

class BuildCompat(java.lang.Object):
    INSTANCE: typing.ClassVar[BuildCompat] = ...
    R_EXTENSION_INT: typing.ClassVar[int] = ...
    S_EXTENSION_INT: typing.ClassVar[int] = ...
    T_EXTENSION_INT: typing.ClassVar[int] = ...
    AD_SERVICES_EXTENSION_INT: typing.ClassVar[int] = ...
    @staticmethod
    def isAtLeastB() -> bool: ...
    @staticmethod
    def isAtLeastB_1() -> bool: ...
    @staticmethod
    def isAtLeastN() -> bool: ...
    @staticmethod
    def isAtLeastNMR1() -> bool: ...
    @staticmethod
    def isAtLeastO() -> bool: ...
    @staticmethod
    def isAtLeastOMR1() -> bool: ...
    @staticmethod
    def isAtLeastP() -> bool: ...
    @staticmethod
    def isAtLeastPreReleaseCodename(codename: str | java.lang.String, buildCodename: str | java.lang.String, /) -> bool: ...
    @staticmethod
    def isAtLeastQ() -> bool: ...
    @staticmethod
    def isAtLeastR() -> bool: ...
    @staticmethod
    def isAtLeastS() -> bool: ...
    @staticmethod
    def isAtLeastSv2() -> bool: ...
    @staticmethod
    def isAtLeastT() -> bool: ...
    @staticmethod
    def isAtLeastU() -> bool: ...
    @staticmethod
    def isAtLeastV() -> bool: ...

    class PrereleaseSdkCheck(java.lang.annotation.Annotation): ...

class BundleCompat(java.lang.Object):
    @staticmethod
    def getBinder(bundle: android.os.Bundle, key: str | java.lang.String, /) -> android.os.IBinder: ...
    _getParcelable__T = typing.TypeVar('_getParcelable__T')  # <T>
    @staticmethod
    def getParcelable(in_: android.os.Bundle, key: str | java.lang.String, clazz: typing.Type[_getParcelable__T], /) -> _getParcelable__T: ...
    @staticmethod
    def getParcelableArray(in_: android.os.Bundle, key: str | java.lang.String, clazz: typing.Type[android.os.Parcelable], /) -> java.chaquopy.JavaArray[android.os.Parcelable]: ...
    _getParcelableArrayList__T = typing.TypeVar('_getParcelableArrayList__T')  # <T>
    @staticmethod
    def getParcelableArrayList(in_: android.os.Bundle, key: str | java.lang.String, clazz: typing.Type[_getParcelableArrayList__T], /) -> java.util.ArrayList[_getParcelableArrayList__T]: ...
    _getSerializable__T = typing.TypeVar('_getSerializable__T')  # <T>
    @staticmethod
    def getSerializable(in_: android.os.Bundle, key: str | java.lang.String, clazz: typing.Type[_getSerializable__T], /) -> _getSerializable__T: ...
    _getSparseParcelableArray__T = typing.TypeVar('_getSparseParcelableArray__T')  # <T>
    @staticmethod
    def getSparseParcelableArray(in_: android.os.Bundle, key: str | java.lang.String, clazz: typing.Type[_getSparseParcelableArray__T], /) -> android.util.SparseArray[_getSparseParcelableArray__T]: ...
    @staticmethod
    def putBinder(bundle: android.os.Bundle, key: str | java.lang.String, binder: android.os.IBinder, /) -> None: ...

class CancellationSignal(java.lang.Object):
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    def getCancellationSignalObject(self) -> java.lang.Object: ...
    def isCanceled(self) -> bool: ...
    def setOnCancelListener(self, listener: CancellationSignal.OnCancelListener, /) -> None: ...
    def throwIfCanceled(self) -> None: ...

    class OnCancelListener(java.lang.Object):
        def onCancel(self) -> None: ...

class ConfigurationCompat(java.lang.Object):
    @staticmethod
    def getLocales(configuration: android.content.res.Configuration, /) -> LocaleListCompat: ...
    @staticmethod
    def setLocales(configuration: android.content.res.Configuration, locales: LocaleListCompat, /) -> None: ...

class EnvironmentCompat(java.lang.Object):
    MEDIA_UNKNOWN: typing.ClassVar[str] = ...
    @staticmethod
    def getStorageState(path: java.io.File, /) -> str: ...

class ExecutorCompat(java.lang.Object):
    @staticmethod
    def create(handler: android.os.Handler, /) -> java.util.concurrent.Executor: ...

class HandlerCompat(java.lang.Object):
    @typing.overload
    @staticmethod
    def createAsync(looper: android.os.Looper, /) -> android.os.Handler: ...
    @typing.overload
    @staticmethod
    def createAsync(looper: android.os.Looper, callback: android.os.Handler.Callback, /) -> android.os.Handler: ...
    @staticmethod
    def hasCallbacks(handler: android.os.Handler, r: java.lang.Runnable, /) -> bool: ...
    @staticmethod
    def postDelayed(handler: android.os.Handler, r: java.lang.Runnable, token: java.lang.Object | int | bool | float | str, delayMillis: int | java.jlong | java.lang.Long, /) -> bool: ...

class HeapProfileRequestBuilder(ProfilingRequestBuilder[HeapProfileRequestBuilder]):
    def __init__(self) -> None: ...
    def getParams(self) -> android.os.Bundle: ...
    def getProfilingType(self) -> int: ...
    def getThis(self) -> HeapProfileRequestBuilder: ...
    def setBufferSizeKb(self, bufferSizeKb: int | java.jint | java.lang.Integer, /) -> HeapProfileRequestBuilder: ...
    def setDurationMs(self, durationMs: int | java.jint | java.lang.Integer, /) -> HeapProfileRequestBuilder: ...
    def setSamplingIntervalBytes(self, samplingIntervalBytes: int | java.jlong | java.lang.Long, /) -> HeapProfileRequestBuilder: ...
    def setTrackJavaAllocations(self, traceJavaAllocations: bool | java.jboolean | java.lang.Boolean, /) -> HeapProfileRequestBuilder: ...

class JavaHeapDumpRequestBuilder(ProfilingRequestBuilder[JavaHeapDumpRequestBuilder]):
    def __init__(self) -> None: ...
    def getParams(self) -> android.os.Bundle: ...
    def getProfilingType(self) -> int: ...
    def getThis(self) -> JavaHeapDumpRequestBuilder: ...
    def setBufferSizeKb(self, bufferSizeKb: int | java.jint | java.lang.Integer, /) -> JavaHeapDumpRequestBuilder: ...

class LocaleListCompat(java.lang.Object):
    @staticmethod
    def create(*localeList: java.util.Locale) -> LocaleListCompat: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def forLanguageTags(list: str | java.lang.String, /) -> LocaleListCompat: ...
    def get(self, index: int | java.jint | java.lang.Integer, /) -> java.util.Locale: ...
    @staticmethod
    def getAdjustedDefault() -> LocaleListCompat: ...
    @staticmethod
    def getDefault() -> LocaleListCompat: ...
    @staticmethod
    def getEmptyLocaleList() -> LocaleListCompat: ...
    def getFirstMatch(self, supportedLocales: java.chaquopy.JavaArray[java.lang.String], /) -> java.util.Locale: ...
    def hashCode(self) -> int: ...
    def indexOf(self, locale: java.util.Locale, /) -> int: ...
    def isEmpty(self) -> bool: ...
    @staticmethod
    def matchesLanguageAndScript(supported: java.util.Locale, desired: java.util.Locale, /) -> bool: ...
    def size(self) -> int: ...
    def toLanguageTags(self) -> str: ...
    def toString(self) -> str: ...
    def unwrap(self) -> java.lang.Object: ...
    @typing.overload
    @staticmethod
    def wrap(localeList: android.os.LocaleList, /) -> LocaleListCompat: ...
    @typing.overload
    @staticmethod
    def wrap(localeList: java.lang.Object | int | bool | float | str, /) -> LocaleListCompat: ...

class LocaleListCompatWrapper(LocaleListInterface):
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def get(self, index: int | java.jint | java.lang.Integer, /) -> java.util.Locale: ...
    def getFirstMatch(self, supportedLocales: java.chaquopy.JavaArray[java.lang.String], /) -> java.util.Locale: ...
    def getLocaleList(self) -> java.lang.Object: ...
    def hashCode(self) -> int: ...
    def indexOf(self, locale: java.util.Locale, /) -> int: ...
    def isEmpty(self) -> bool: ...
    def size(self) -> int: ...
    def toLanguageTags(self) -> str: ...
    def toString(self) -> str: ...

class LocaleListInterface(java.lang.Object):
    def get(self, arg1: int | java.jint | java.lang.Integer, /) -> java.util.Locale: ...
    def getFirstMatch(self, arg1: java.chaquopy.JavaArray[java.lang.String], /) -> java.util.Locale: ...
    def getLocaleList(self) -> java.lang.Object: ...
    def indexOf(self, arg1: java.util.Locale, /) -> int: ...
    def isEmpty(self) -> bool: ...
    def size(self) -> int: ...
    def toLanguageTags(self) -> str: ...

class LocaleListPlatformWrapper(LocaleListInterface):
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def get(self, index: int | java.jint | java.lang.Integer, /) -> java.util.Locale: ...
    def getFirstMatch(self, supportedLocales: java.chaquopy.JavaArray[java.lang.String], /) -> java.util.Locale: ...
    def getLocaleList(self) -> java.lang.Object: ...
    def hashCode(self) -> int: ...
    def indexOf(self, locale: java.util.Locale, /) -> int: ...
    def isEmpty(self) -> bool: ...
    def size(self) -> int: ...
    def toLanguageTags(self) -> str: ...
    def toString(self) -> str: ...

class MessageCompat(java.lang.Object):
    @staticmethod
    def isAsynchronous(message: android.os.Message, /) -> bool: ...
    @staticmethod
    def setAsynchronous(message: android.os.Message, async_: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class OperationCanceledException(java.lang.RuntimeException):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, message: str | java.lang.String, /) -> None: ...

_OutcomeReceiverCompat__R = typing.TypeVar('_OutcomeReceiverCompat__R')  # <R>
_OutcomeReceiverCompat__E = typing.TypeVar('_OutcomeReceiverCompat__E', bound=java.lang.Throwable)  # <E>
class OutcomeReceiverCompat(java.lang.Object, typing.Generic[_OutcomeReceiverCompat__R, _OutcomeReceiverCompat__E]):
    def onError(self, error: _OutcomeReceiverCompat__E, /) -> None: ...
    def onResult(self, arg1: _OutcomeReceiverCompat__R, /) -> None: ...

class ParcelCompat(java.lang.Object):
    @staticmethod
    def readArray(in_: android.os.Parcel, loader: java.lang.ClassLoader, clazz: typing.Type[java.lang.Object], /) -> java.chaquopy.JavaArray[java.lang.Object]: ...
    _readArrayList__T = typing.TypeVar('_readArrayList__T')  # <T>
    @staticmethod
    def readArrayList(in_: android.os.Parcel, loader: java.lang.ClassLoader, clazz: typing.Type[_readArrayList__T], /) -> java.util.ArrayList[_readArrayList__T]: ...
    @staticmethod
    def readBoolean(in_: android.os.Parcel, /) -> bool: ...
    _readHashMap__K = typing.TypeVar('_readHashMap__K')  # <K>
    _readHashMap__V = typing.TypeVar('_readHashMap__V')  # <V>
    @staticmethod
    def readHashMap(in_: android.os.Parcel, loader: java.lang.ClassLoader, clazzKey: typing.Type[_readHashMap__K], clazzValue: typing.Type[_readHashMap__V], /) -> java.util.HashMap[_readHashMap__K, _readHashMap__V]: ...
    _readList__T = typing.TypeVar('_readList__T')  # <T>
    @staticmethod
    def readList(in_: android.os.Parcel, outVal: java.util.List[_readList__T], loader: java.lang.ClassLoader, clazz: typing.Type[_readList__T], /) -> None: ...
    _readMap__K = typing.TypeVar('_readMap__K')  # <K>
    _readMap__V = typing.TypeVar('_readMap__V')  # <V>
    @staticmethod
    def readMap(in_: android.os.Parcel, outVal: java.util.Map[_readMap__K, _readMap__V], loader: java.lang.ClassLoader, clazzKey: typing.Type[_readMap__K], clazzValue: typing.Type[_readMap__V], /) -> None: ...
    _readParcelable__T = typing.TypeVar('_readParcelable__T')  # <T>
    @staticmethod
    def readParcelable(in_: android.os.Parcel, loader: java.lang.ClassLoader, clazz: typing.Type[_readParcelable__T], /) -> _readParcelable__T: ...
    _readParcelableArray__T = typing.TypeVar('_readParcelableArray__T')  # <T>
    @staticmethod
    def readParcelableArray(in_: android.os.Parcel, loader: java.lang.ClassLoader, clazz: typing.Type[_readParcelableArray__T], /) -> java.chaquopy.JavaArray[_readParcelableArray__T]: ...
    @staticmethod
    def readParcelableArrayTyped(in_: android.os.Parcel, loader: java.lang.ClassLoader, clazz: typing.Type[java.lang.Object], /) -> java.chaquopy.JavaArray[android.os.Parcelable]: ...
    _readParcelableCreator__T = typing.TypeVar('_readParcelableCreator__T')  # <T>
    @staticmethod
    def readParcelableCreator(in_: android.os.Parcel, loader: java.lang.ClassLoader, clazz: typing.Type[_readParcelableCreator__T], /) -> android.os.Parcelable.Creator[_readParcelableCreator__T]: ...
    _readParcelableList__T = typing.TypeVar('_readParcelableList__T')  # <T>
    @staticmethod
    def readParcelableList(in_: android.os.Parcel, list: java.util.List[_readParcelableList__T], cl: java.lang.ClassLoader, clazz: typing.Type[_readParcelableList__T], /) -> java.util.List[_readParcelableList__T]: ...
    _readSerializable__T = typing.TypeVar('_readSerializable__T')  # <T>
    @staticmethod
    def readSerializable(in_: android.os.Parcel, loader: java.lang.ClassLoader, clazz: typing.Type[_readSerializable__T], /) -> _readSerializable__T: ...
    _readSparseArray__T = typing.TypeVar('_readSparseArray__T')  # <T>
    @staticmethod
    def readSparseArray(in_: android.os.Parcel, loader: java.lang.ClassLoader, clazz: typing.Type[_readSparseArray__T], /) -> android.util.SparseArray[_readSparseArray__T]: ...
    @staticmethod
    def writeBoolean(out: android.os.Parcel, value: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class ParcelableCompat(java.lang.Object):
    _newCreator__T = typing.TypeVar('_newCreator__T')  # <T>
    @staticmethod
    def newCreator(callbacks: ParcelableCompatCreatorCallbacks[_newCreator__T], /) -> android.os.Parcelable.Creator[_newCreator__T]: ...

_ParcelableCompatCreatorCallbacks__T = typing.TypeVar('_ParcelableCompatCreatorCallbacks__T')  # <T>
class ParcelableCompatCreatorCallbacks(java.lang.Object, typing.Generic[_ParcelableCompatCreatorCallbacks__T]):
    def createFromParcel(self, arg1: android.os.Parcel, arg2: java.lang.ClassLoader, /) -> _ParcelableCompatCreatorCallbacks__T: ...
    def newArray(self, arg1: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArray[_ParcelableCompatCreatorCallbacks__T]: ...

class ProcessCompat(java.lang.Object):
    @staticmethod
    def isApplicationUid(uid: int | java.jint | java.lang.Integer, /) -> bool: ...

class Profiling(java.lang.Object):
    @typing.overload
    @staticmethod
    def registerForAllProfilingResults(context: android.content.Context, /) -> kotlinx.coroutines.flow.Flow[android.os.ProfilingResult]: ...
    @typing.overload
    @staticmethod
    def registerForAllProfilingResults(context: android.content.Context, executor: java.util.concurrent.Executor, listener: java.util.function.Consumer[android.os.ProfilingResult], /) -> None: ...
    @staticmethod
    def requestProfiling(context: android.content.Context, profilingRequest: ProfilingRequest, executor: java.util.concurrent.Executor, listener: java.util.function.Consumer[android.os.ProfilingResult], /) -> None: ...
    @staticmethod
    def unregisterForAllProfilingResults(context: android.content.Context, listener: java.util.function.Consumer[android.os.ProfilingResult], /) -> None: ...

class ProfilingRequest(java.lang.Object):
    def __init__(self, profilingType: int | java.jint | java.lang.Integer, params: android.os.Bundle, tag: str | java.lang.String, cancellationSignal: android.os.CancellationSignal, /) -> None: ...
    def getCancellationSignal(self) -> android.os.CancellationSignal: ...
    def getParams(self) -> android.os.Bundle: ...
    def getProfilingType(self) -> int: ...
    def getTag(self) -> str: ...

_ProfilingRequestBuilder__T = typing.TypeVar('_ProfilingRequestBuilder__T', bound=ProfilingRequestBuilder[T])  # <T>
class ProfilingRequestBuilder(java.lang.Object, typing.Generic[_ProfilingRequestBuilder__T]):
    def __init__(self) -> None: ...
    def build(self) -> ProfilingRequest: ...
    def getParams(self) -> android.os.Bundle: ...
    def getProfilingType(self) -> int: ...
    def getThis(self) -> _ProfilingRequestBuilder__T: ...
    def setCancellationSignal(self, cancellationSignal: android.os.CancellationSignal, /) -> _ProfilingRequestBuilder__T: ...
    def setTag(self, tag: str | java.lang.String, /) -> _ProfilingRequestBuilder__T: ...

class StackSamplingRequestBuilder(ProfilingRequestBuilder[StackSamplingRequestBuilder]):
    def __init__(self) -> None: ...
    def getParams(self) -> android.os.Bundle: ...
    def getProfilingType(self) -> int: ...
    def getThis(self) -> StackSamplingRequestBuilder: ...
    def setBufferSizeKb(self, bufferSizeKb: int | java.jint | java.lang.Integer, /) -> StackSamplingRequestBuilder: ...
    def setDurationMs(self, durationMs: int | java.jint | java.lang.Integer, /) -> StackSamplingRequestBuilder: ...
    def setSamplingFrequencyHz(self, samplingFrequencyHz: int | java.jint | java.lang.Integer, /) -> StackSamplingRequestBuilder: ...

class SystemTraceRequestBuilder(ProfilingRequestBuilder[SystemTraceRequestBuilder]):
    def __init__(self) -> None: ...
    def getParams(self) -> android.os.Bundle: ...
    def getProfilingType(self) -> int: ...
    def getThis(self) -> SystemTraceRequestBuilder: ...
    def setBufferFillPolicy(self, bufferFillPolicy: BufferFillPolicy, /) -> SystemTraceRequestBuilder: ...
    def setBufferSizeKb(self, bufferSizeKb: int | java.jint | java.lang.Integer, /) -> SystemTraceRequestBuilder: ...
    def setDurationMs(self, durationMs: int | java.jint | java.lang.Integer, /) -> SystemTraceRequestBuilder: ...

class TraceCompat(java.lang.Object):
    @staticmethod
    def beginAsyncSection(methodName: str | java.lang.String, cookie: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def beginSection(sectionName: str | java.lang.String, /) -> None: ...
    @staticmethod
    def endAsyncSection(methodName: str | java.lang.String, cookie: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def endSection() -> None: ...
    @staticmethod
    def isEnabled() -> bool: ...
    @staticmethod
    def setCounter(counterName: str | java.lang.String, counterValue: int | java.jint | java.lang.Integer, /) -> None: ...

class UserHandleCompat(java.lang.Object):
    @staticmethod
    def getUserHandleForUid(uid: int | java.jint | java.lang.Integer, /) -> android.os.UserHandle: ...

class UserManagerCompat(java.lang.Object):
    @staticmethod
    def isUserUnlocked(context: android.content.Context, /) -> bool: ...
