import android.content
import android.graphics
import java
import java.lang
import java.text
import org.osmdroid.util
import org.osmdroid.views
import org.osmdroid.views.overlay
import typing



class LatLonGridlineOverlay(java.lang.Object):
    lineColor: typing.ClassVar[int] = ...
    fontColor: typing.ClassVar[int] = ...
    fontSizeDp: typing.ClassVar[int] = ...
    backgroundColor: typing.ClassVar[int] = ...
    lineWidth: typing.ClassVar[float] = ...
    DEBUG: typing.ClassVar[bool] = ...
    DEBUG2: typing.ClassVar[bool] = ...
    def __init__(self) -> None: ...
    @staticmethod
    def getLatLonGrid(ctx: android.content.Context, mapView: org.osmdroid.views.MapView, /) -> org.osmdroid.views.overlay.FolderOverlay: ...
    @staticmethod
    def setDefaults() -> None: ...

class LatLonGridlineOverlay2(org.osmdroid.views.overlay.Overlay):
    mDecimalFormatter: java.text.DecimalFormat = ...
    mMultiplier: float = ...
    mLinePaint: android.graphics.Paint = ...
    mTextBackgroundPaint: android.graphics.Paint = ...
    mTextPaint: android.graphics.Paint = ...
    mOptimizationGeoPoint: org.osmdroid.util.GeoPoint = ...
    mOptimizationPoint: android.graphics.Point = ...
    def __init__(self) -> None: ...
    def draw(self, c: android.graphics.Canvas, pProjection: org.osmdroid.views.Projection, /) -> None: ...
    def getIncrementor(self, zoom: int | java.jint | java.lang.Integer, /) -> float: ...
    def getTextPaint(self) -> android.graphics.Paint: ...
    def setBackgroundColor(self, backgroundColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDecimalFormatter(self, df: java.text.DecimalFormat, /) -> None: ...
    def setFontColor(self, fontColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setFontSizeDp(self, fontSizeDp: int | java.jshort | java.lang.Short, /) -> None: ...
    def setLineColor(self, lineColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setLineWidth(self, lineWidth: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setMultiplier(self, multiplier: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTextPaint(self, paint: android.graphics.Paint, /) -> None: ...
    def setTextStyle(self, paint: android.graphics.Paint.Style, /) -> None: ...
