import typing

import android.content.res
import android.graphics
import android.graphics.drawable
import android.util
import androidx.core.graphics.drawable
import java
import java.chaquopy
import java.lang
import org.xmlpull.v1

class AndroidResources(java.lang.Object):
    STYLEABLE_ANIMATOR: typing.ClassVar[java.chaquopy.JavaArrayJInt] = ...
    STYLEABLE_ANIMATOR_INTERPOLATOR: typing.ClassVar[int] = ...
    STYLEABLE_ANIMATOR_DURATION: typing.ClassVar[int] = ...
    STYLEABLE_ANIMATOR_START_OFFSET: typing.ClassVar[int] = ...
    STYLEABLE_ANIMATOR_REPEAT_COUNT: typing.ClassVar[int] = ...
    STYLEABLE_ANIMATOR_REPEAT_MODE: typing.ClassVar[int] = ...
    STYLEABLE_ANIMATOR_VALUE_FROM: typing.ClassVar[int] = ...
    STYLEABLE_ANIMATOR_VALUE_TO: typing.ClassVar[int] = ...
    STYLEABLE_ANIMATOR_VALUE_TYPE: typing.ClassVar[int] = ...
    STYLEABLE_ANIMATOR_SET: typing.ClassVar[java.chaquopy.JavaArrayJInt] = ...
    STYLEABLE_ANIMATOR_SET_ORDERING: typing.ClassVar[int] = ...
    STYLEABLE_PROPERTY_VALUES_HOLDER: typing.ClassVar[java.chaquopy.JavaArrayJInt] = ...
    STYLEABLE_PROPERTY_VALUES_HOLDER_VALUE_FROM: typing.ClassVar[int] = ...
    STYLEABLE_PROPERTY_VALUES_HOLDER_VALUE_TO: typing.ClassVar[int] = ...
    STYLEABLE_PROPERTY_VALUES_HOLDER_VALUE_TYPE: typing.ClassVar[int] = ...
    STYLEABLE_PROPERTY_VALUES_HOLDER_PROPERTY_NAME: typing.ClassVar[int] = ...
    STYLEABLE_KEYFRAME: typing.ClassVar[java.chaquopy.JavaArrayJInt] = ...
    STYLEABLE_KEYFRAME_VALUE: typing.ClassVar[int] = ...
    STYLEABLE_KEYFRAME_INTERPOLATOR: typing.ClassVar[int] = ...
    STYLEABLE_KEYFRAME_VALUE_TYPE: typing.ClassVar[int] = ...
    STYLEABLE_KEYFRAME_FRACTION: typing.ClassVar[int] = ...
    STYLEABLE_PROPERTY_ANIMATOR: typing.ClassVar[java.chaquopy.JavaArrayJInt] = ...
    STYLEABLE_PROPERTY_ANIMATOR_PROPERTY_NAME: typing.ClassVar[int] = ...
    STYLEABLE_PROPERTY_ANIMATOR_PATH_DATA: typing.ClassVar[int] = ...
    STYLEABLE_PROPERTY_ANIMATOR_PROPERTY_X_NAME: typing.ClassVar[int] = ...
    STYLEABLE_PROPERTY_ANIMATOR_PROPERTY_Y_NAME: typing.ClassVar[int] = ...
    STYLEABLE_PATH_INTERPOLATOR: typing.ClassVar[java.chaquopy.JavaArrayJInt] = ...
    STYLEABLE_PATH_INTERPOLATOR_CONTROL_X_1: typing.ClassVar[int] = ...
    STYLEABLE_PATH_INTERPOLATOR_CONTROL_Y_1: typing.ClassVar[int] = ...
    STYLEABLE_PATH_INTERPOLATOR_CONTROL_X_2: typing.ClassVar[int] = ...
    STYLEABLE_PATH_INTERPOLATOR_CONTROL_Y_2: typing.ClassVar[int] = ...
    STYLEABLE_PATH_INTERPOLATOR_PATH_DATA: typing.ClassVar[int] = ...
    FAST_OUT_LINEAR_IN: typing.ClassVar[int] = ...
    FAST_OUT_SLOW_IN: typing.ClassVar[int] = ...
    LINEAR_OUT_SLOW_IN: typing.ClassVar[int] = ...

class VectorDrawableCommon(android.graphics.drawable.Drawable, androidx.core.graphics.drawable.TintAwareDrawable):
    def applyTheme(self, t: android.content.res.Resources.Theme, /) -> None: ...
    def clearColorFilter(self) -> None: ...
    def getCurrent(self) -> android.graphics.drawable.Drawable: ...
    def getMinimumHeight(self) -> int: ...
    def getMinimumWidth(self) -> int: ...
    def getPadding(self, padding: android.graphics.Rect, /) -> bool: ...
    def getState(self) -> java.chaquopy.JavaArrayJInt: ...
    def getTransparentRegion(self) -> android.graphics.Region: ...
    def jumpToCurrentState(self) -> None: ...
    def onBoundsChange(self, bounds: android.graphics.Rect, /) -> None: ...
    def onLevelChange(self, level: int | java.jint | java.lang.Integer, /) -> bool: ...
    def setChangingConfigurations(self, configs: int | java.jint | java.lang.Integer, /) -> None: ...
    def setColorFilter(self, color: int | java.jint | java.lang.Integer, mode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def setFilterBitmap(self, filter: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setHotspot(self, x: float | java.jfloat | java.lang.Float, y: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setHotspotBounds(self, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setState(self, stateSet: java.chaquopy.JavaArrayJInt, /) -> bool: ...

class VectorDrawableCompat(VectorDrawableCommon):
    def canApplyTheme(self) -> bool: ...
    @staticmethod
    def create(res: android.content.res.Resources, resId: int | java.jint | java.lang.Integer, theme: android.content.res.Resources.Theme, /) -> VectorDrawableCompat: ...
    @staticmethod
    def createFromXmlInner(r: android.content.res.Resources, parser: org.xmlpull.v1.XmlPullParser, attrs: android.util.AttributeSet, theme: android.content.res.Resources.Theme, /) -> VectorDrawableCompat: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getAlpha(self) -> int: ...
    def getChangingConfigurations(self) -> int: ...
    def getColorFilter(self) -> android.graphics.ColorFilter: ...
    def getConstantState(self) -> android.graphics.drawable.Drawable.ConstantState: ...
    def getIntrinsicHeight(self) -> int: ...
    def getIntrinsicWidth(self) -> int: ...
    def getOpacity(self) -> int: ...
    def getPixelSize(self) -> float: ...
    @typing.overload
    def inflate(self, res: android.content.res.Resources, parser: org.xmlpull.v1.XmlPullParser, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def inflate(self, res: android.content.res.Resources, parser: org.xmlpull.v1.XmlPullParser, attrs: android.util.AttributeSet, theme: android.content.res.Resources.Theme, /) -> None: ...
    def invalidateSelf(self) -> None: ...
    def isAutoMirrored(self) -> bool: ...
    def isStateful(self) -> bool: ...
    def mutate(self) -> android.graphics.drawable.Drawable: ...
    def onBoundsChange(self, bounds: android.graphics.Rect, /) -> None: ...
    def onStateChange(self, stateSet: java.chaquopy.JavaArrayJInt, /) -> bool: ...
    def scheduleSelf(self, what: java.lang.Runnable, when: int | java.jlong | java.lang.Long, /) -> None: ...
    def setAlpha(self, alpha: int | java.jint | java.lang.Integer, /) -> None: ...
    def setAutoMirrored(self, mirrored: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setColorFilter(self, colorFilter: android.graphics.ColorFilter, /) -> None: ...
    def setTint(self, tint: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTintList(self, tint: android.content.res.ColorStateList, /) -> None: ...
    def setTintMode(self, tintMode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def setVisible(self, visible: bool | java.jboolean | java.lang.Boolean, restart: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def unscheduleSelf(self, what: java.lang.Runnable, /) -> None: ...
