import typing

import android.content
import android.graphics
import android.graphics.drawable
import android.util
import android.view
import androidx.appcompat.widget
import androidx.constraintlayout.motion.widget
import java
import java.lang

class ImageFilterButton(androidx.appcompat.widget.AppCompatImageButton):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getContrast(self) -> float: ...
    def getCrossfade(self) -> float: ...
    def getImagePanX(self) -> float: ...
    def getImagePanY(self) -> float: ...
    def getImageRotate(self) -> float: ...
    def getImageZoom(self) -> float: ...
    def getRound(self) -> float: ...
    def getRoundPercent(self) -> float: ...
    def getSaturation(self) -> float: ...
    def getWarmth(self) -> float: ...
    def layout(self, l: int | java.jint | java.lang.Integer, t: int | java.jint | java.lang.Integer, r: int | java.jint | java.lang.Integer, b: int | java.jint | java.lang.Integer, /) -> None: ...
    def setAltImageResource(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBrightness(self, brightness: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setContrast(self, contrast: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setCrossfade(self, crossfade: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setImageDrawable(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...
    def setImagePanX(self, pan: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setImagePanY(self, pan: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setImageResource(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setImageRotate(self, rotation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setImageZoom(self, zoom: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setRound(self, round: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setRoundPercent(self, round: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setSaturation(self, saturation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setWarmth(self, warmth: float | java.jfloat | java.lang.Float, /) -> None: ...

class ImageFilterView(androidx.appcompat.widget.AppCompatImageView):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getBrightness(self) -> float: ...
    def getContrast(self) -> float: ...
    def getCrossfade(self) -> float: ...
    def getImagePanX(self) -> float: ...
    def getImagePanY(self) -> float: ...
    def getImageRotate(self) -> float: ...
    def getImageZoom(self) -> float: ...
    def getRound(self) -> float: ...
    def getRoundPercent(self) -> float: ...
    def getSaturation(self) -> float: ...
    def getWarmth(self) -> float: ...
    def layout(self, l: int | java.jint | java.lang.Integer, t: int | java.jint | java.lang.Integer, r: int | java.jint | java.lang.Integer, b: int | java.jint | java.lang.Integer, /) -> None: ...
    def setAltImageDrawable(self, altDrawable: android.graphics.drawable.Drawable, /) -> None: ...
    def setAltImageResource(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBrightness(self, brightness: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setContrast(self, contrast: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setCrossfade(self, crossfade: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setImageDrawable(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...
    def setImagePanX(self, pan: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setImagePanY(self, pan: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setImageResource(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setImageRotate(self, rotation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setImageZoom(self, zoom: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setRound(self, round: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setRoundPercent(self, round: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setSaturation(self, saturation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setWarmth(self, warmth: float | java.jfloat | java.lang.Float, /) -> None: ...

class MockView(android.view.View):
    mText: str = ...
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def onDraw(self, canvas: android.graphics.Canvas, /) -> None: ...

class MotionButton(androidx.appcompat.widget.AppCompatButton):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getRound(self) -> float: ...
    def getRoundPercent(self) -> float: ...
    def setRound(self, round: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setRoundPercent(self, round: float | java.jfloat | java.lang.Float, /) -> None: ...

class MotionLabel(android.view.View, androidx.constraintlayout.motion.widget.FloatLayout):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def getRound(self) -> float: ...
    def getRoundPercent(self) -> float: ...
    def getScaleFromTextSize(self) -> float: ...
    def getTextBackgroundPanX(self) -> float: ...
    def getTextBackgroundPanY(self) -> float: ...
    def getTextBackgroundRotate(self) -> float: ...
    def getTextBackgroundZoom(self) -> float: ...
    def getTextOutlineColor(self) -> int: ...
    def getTextPanX(self) -> float: ...
    def getTextPanY(self) -> float: ...
    def getTextureHeight(self) -> float: ...
    def getTextureWidth(self) -> float: ...
    def getTypeface(self) -> android.graphics.Typeface: ...
    @typing.overload
    def layout(self, l: float | java.jfloat | java.lang.Float, t: float | java.jfloat | java.lang.Float, r: float | java.jfloat | java.lang.Float, b: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def layout(self, l: int | java.jint | java.lang.Integer, t: int | java.jint | java.lang.Integer, r: int | java.jint | java.lang.Integer, b: int | java.jint | java.lang.Integer, /) -> None: ...
    def onDraw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def setGravity(self, gravity: int | java.jint | java.lang.Integer, /) -> None: ...
    def setRound(self, round: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setRoundPercent(self, round: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setScaleFromTextSize(self, size: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setText(self, text: java.lang.CharSequence, /) -> None: ...
    def setTextBackgroundPanX(self, pan: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTextBackgroundPanY(self, pan: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTextBackgroundRotate(self, rotation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTextBackgroundZoom(self, zoom: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTextFillColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTextOutlineColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTextOutlineThickness(self, width: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTextPanX(self, textPanX: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTextPanY(self, textPanY: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTextSize(self, size: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTextureHeight(self, mTextureHeight: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTextureWidth(self, mTextureWidth: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTypeface(self, tf: android.graphics.Typeface, /) -> None: ...

class MotionTelltales(MockView):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def onDraw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def onLayout(self, changed: bool | java.jboolean | java.lang.Boolean, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setText(self, text: java.lang.CharSequence, /) -> None: ...
