import typing

import java
import java.chaquopy
import java.io
import java.lang
import java.lang.annotation
import java.util
import kotlin.jvm.functions

class ArrayIntrinsicsKt(java.lang.Object): ...

class Deprecated(java.lang.annotation.Annotation):
    def level(self) -> DeprecationLevel: ...
    def message(self) -> str: ...
    def replaceWith(self) -> ReplaceWith: ...

class DeprecationLevel(java.lang.Enum[DeprecationLevel]):
    WARNING: typing.ClassVar[DeprecationLevel] = ...
    ERROR: typing.ClassVar[DeprecationLevel] = ...
    HIDDEN: typing.ClassVar[DeprecationLevel] = ...
    def __init__(self) -> None: ...
    @staticmethod
    def valueOf(arg1: str | java.lang.String, /) -> DeprecationLevel: ...
    @staticmethod
    def values() -> java.chaquopy.JavaArray[DeprecationLevel]: ...

class DslMarker(java.lang.annotation.Annotation): ...

class ExceptionsKt(ExceptionsKt__ExceptionsKt): ...

class ExceptionsKt__ExceptionsKt(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def addSuppressed(receiver: java.lang.Throwable, exception: java.lang.Throwable, /) -> None: ...
    @staticmethod
    def getStackTrace(receiver: java.lang.Throwable, /) -> java.chaquopy.JavaArray[java.lang.StackTraceElement]: ...

class ExtensionFunctionType(java.lang.annotation.Annotation): ...

_Function__R = typing.TypeVar('_Function__R')  # <R>
class Function(java.lang.Object, typing.Generic[_Function__R]): ...

_InitializedLazyImpl__T = typing.TypeVar('_InitializedLazyImpl__T')  # <T>
class InitializedLazyImpl(Lazy[_InitializedLazyImpl__T], java.io.Serializable, typing.Generic[_InitializedLazyImpl__T]):
    def __init__(self, value: _InitializedLazyImpl__T, /) -> None: ...
    def getValue(self) -> _InitializedLazyImpl__T: ...
    def isInitialized(self) -> bool: ...
    def toString(self) -> str: ...

class KotlinNullPointerException(java.lang.NullPointerException):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, message: str | java.lang.String, /) -> None: ...

class KotlinVersion(java.lang.Comparable[KotlinVersion]):
    MAX_COMPONENT_VALUE: typing.ClassVar[int] = ...
    CURRENT: typing.ClassVar[KotlinVersion] = ...
    Companion: typing.ClassVar[KotlinVersion.Companion] = ...
    @typing.overload
    def __init__(self, major: int | java.jint | java.lang.Integer, minor: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, major: int | java.jint | java.lang.Integer, minor: int | java.jint | java.lang.Integer, patch: int | java.jint | java.lang.Integer, /) -> None: ...
    def compareTo(self, other: KotlinVersion, /) -> int: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getMajor(self) -> int: ...
    def getMinor(self) -> int: ...
    def getPatch(self) -> int: ...
    def hashCode(self) -> int: ...
    @typing.overload
    def isAtLeast(self, major: int | java.jint | java.lang.Integer, minor: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def isAtLeast(self, major: int | java.jint | java.lang.Integer, minor: int | java.jint | java.lang.Integer, patch: int | java.jint | java.lang.Integer, /) -> bool: ...
    def toString(self) -> str: ...

    class Companion(java.lang.Object): ...

class LateinitKt(java.lang.Object): ...

_Lazy__T = typing.TypeVar('_Lazy__T')  # <T>
class Lazy(java.lang.Object, typing.Generic[_Lazy__T]):
    def getValue(self) -> _Lazy__T: ...
    def isInitialized(self) -> bool: ...

class LazyKt(java.lang.Object):
    _lazy_0__T = typing.TypeVar('_lazy_0__T')  # <T>
    _lazy_1__T = typing.TypeVar('_lazy_1__T')  # <T>
    _lazy_2__T = typing.TypeVar('_lazy_2__T')  # <T>
    @typing.overload
    @staticmethod
    def lazy(initializer: kotlin.jvm.functions.Function0[_lazy_0__T], /) -> Lazy[_lazy_0__T]: ...
    @typing.overload
    @staticmethod
    def lazy(lock: java.lang.Object | int | bool | float | str, initializer: kotlin.jvm.functions.Function0[_lazy_1__T], /) -> Lazy[_lazy_1__T]: ...
    @typing.overload
    @staticmethod
    def lazy(mode: LazyThreadSafetyMode, initializer: kotlin.jvm.functions.Function0[_lazy_2__T], /) -> Lazy[_lazy_2__T]: ...
    _lazyOf__T = typing.TypeVar('_lazyOf__T')  # <T>
    @staticmethod
    def lazyOf(value: _lazyOf__T, /) -> Lazy[_lazyOf__T]: ...

class LazyThreadSafetyMode(java.lang.Enum[LazyThreadSafetyMode]):
    SYNCHRONIZED: typing.ClassVar[LazyThreadSafetyMode] = ...
    PUBLICATION: typing.ClassVar[LazyThreadSafetyMode] = ...
    NONE: typing.ClassVar[LazyThreadSafetyMode] = ...
    def __init__(self) -> None: ...
    @staticmethod
    def valueOf(arg1: str | java.lang.String, /) -> LazyThreadSafetyMode: ...
    @staticmethod
    def values() -> java.chaquopy.JavaArray[LazyThreadSafetyMode]: ...

class MathKt(MathKt__NumbersKt): ...

class MathKt__BigDecimalsKt(java.lang.Object):
    def __init__(self) -> None: ...

class MathKt__BigIntegersKt(MathKt__BigDecimalsKt):
    def __init__(self) -> None: ...

class MathKt__NumbersKt(MathKt__BigIntegersKt):
    def __init__(self) -> None: ...

class Metadata(java.lang.annotation.Annotation):
    def bv(self) -> java.chaquopy.JavaArrayJInt: ...
    def d1(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    def d2(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    def k(self) -> int: ...
    def mv(self) -> java.chaquopy.JavaArrayJInt: ...
    def pn(self) -> str: ...
    def xi(self) -> int: ...
    def xs(self) -> str: ...

class NoWhenBranchMatchedException(java.lang.RuntimeException):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, message: str | java.lang.String, /) -> None: ...
    @typing.overload
    def __init__(self, cause: java.lang.Throwable, /) -> None: ...
    @typing.overload
    def __init__(self, message: str | java.lang.String, cause: java.lang.Throwable, /) -> None: ...

class NotImplementedError(java.lang.Error):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, message: str | java.lang.String, /) -> None: ...

_Pair__A = typing.TypeVar('_Pair__A')  # <A>
_Pair__B = typing.TypeVar('_Pair__B')  # <B>
class Pair(java.io.Serializable, typing.Generic[_Pair__A, _Pair__B]):
    def __init__(self, first: _Pair__A, second: _Pair__B, /) -> None: ...
    def component1(self) -> _Pair__A: ...
    def component2(self) -> _Pair__B: ...
    def copy(self, first: _Pair__A, second: _Pair__B, /) -> Pair[_Pair__A, _Pair__B]: ...
    def equals(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getFirst(self) -> _Pair__A: ...
    def getSecond(self) -> _Pair__B: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class ParameterName(java.lang.annotation.Annotation):
    def name(self) -> str: ...

class PreconditionsKt(PreconditionsKt__PreconditionsKt): ...

class PreconditionsKt__AssertionsJVMKt(java.lang.Object):
    def __init__(self) -> None: ...

class PreconditionsKt__PreconditionsKt(PreconditionsKt__AssertionsJVMKt):
    def __init__(self) -> None: ...

class PublishedApi(java.lang.annotation.Annotation): ...

class ReplaceWith(java.lang.annotation.Annotation):
    def expression(self) -> str: ...
    def imports(self) -> java.chaquopy.JavaArray[java.lang.String]: ...

_SafePublicationLazyImpl__T = typing.TypeVar('_SafePublicationLazyImpl__T')  # <T>
class SafePublicationLazyImpl(Lazy[_SafePublicationLazyImpl__T], java.io.Serializable, typing.Generic[_SafePublicationLazyImpl__T]):
    Companion: typing.ClassVar[SafePublicationLazyImpl.Companion] = ...
    def __init__(self, initializer: kotlin.jvm.functions.Function0[_SafePublicationLazyImpl__T], /) -> None: ...
    def getValue(self) -> _SafePublicationLazyImpl__T: ...
    def isInitialized(self) -> bool: ...
    def toString(self) -> str: ...

    class Companion(java.lang.Object): ...

class SinceKotlin(java.lang.annotation.Annotation):
    def version(self) -> str: ...

class StandardKt(StandardKt__SynchronizedKt): ...

class StandardKt__StandardKt(java.lang.Object):
    def __init__(self) -> None: ...

class StandardKt__SynchronizedKt(StandardKt__StandardKt):
    def __init__(self) -> None: ...

class Suppress(java.lang.annotation.Annotation):
    def names(self) -> java.chaquopy.JavaArray[java.lang.String]: ...

_SynchronizedLazyImpl__T = typing.TypeVar('_SynchronizedLazyImpl__T')  # <T>
class SynchronizedLazyImpl(Lazy[_SynchronizedLazyImpl__T], java.io.Serializable, typing.Generic[_SynchronizedLazyImpl__T]):
    def __init__(self, initializer: kotlin.jvm.functions.Function0[_SynchronizedLazyImpl__T], lock: java.lang.Object | int | bool | float | str, /) -> None: ...
    def getValue(self) -> _SynchronizedLazyImpl__T: ...
    def isInitialized(self) -> bool: ...
    def toString(self) -> str: ...

_Triple__A = typing.TypeVar('_Triple__A')  # <A>
_Triple__B = typing.TypeVar('_Triple__B')  # <B>
_Triple__C = typing.TypeVar('_Triple__C')  # <C>
class Triple(java.io.Serializable, typing.Generic[_Triple__A, _Triple__B, _Triple__C]):
    def __init__(self, first: _Triple__A, second: _Triple__B, third: _Triple__C, /) -> None: ...
    def component1(self) -> _Triple__A: ...
    def component2(self) -> _Triple__B: ...
    def component3(self) -> _Triple__C: ...
    def copy(self, first: _Triple__A, second: _Triple__B, third: _Triple__C, /) -> Triple[_Triple__A, _Triple__B, _Triple__C]: ...
    def equals(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getFirst(self) -> _Triple__A: ...
    def getSecond(self) -> _Triple__B: ...
    def getThird(self) -> _Triple__C: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class TuplesKt(java.lang.Object):
    _to__A = typing.TypeVar('_to__A')  # <A>
    _to__B = typing.TypeVar('_to__B')  # <B>
    @staticmethod
    def to(receiver: _to__A, that: _to__B, /) -> Pair[_to__A, _to__B]: ...
    _toList_0__T = typing.TypeVar('_toList_0__T')  # <T>
    _toList_1__T = typing.TypeVar('_toList_1__T')  # <T>
    @typing.overload
    @staticmethod
    def toList(receiver: Pair[_toList_0__T, _toList_0__T], /) -> java.util.List[_toList_0__T]: ...
    @typing.overload
    @staticmethod
    def toList(receiver: Triple[_toList_1__T, _toList_1__T, _toList_1__T], /) -> java.util.List[_toList_1__T]: ...

class TypeAliasesKt(java.lang.Object): ...

class TypeCastException(java.lang.ClassCastException):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, message: str | java.lang.String, /) -> None: ...

class UNINITIALIZED_VALUE(java.lang.Object):
    INSTANCE: typing.ClassVar[UNINITIALIZED_VALUE] = ...

class UninitializedPropertyAccessException(java.lang.RuntimeException):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, message: str | java.lang.String, /) -> None: ...
    @typing.overload
    def __init__(self, cause: java.lang.Throwable, /) -> None: ...
    @typing.overload
    def __init__(self, message: str | java.lang.String, cause: java.lang.Throwable, /) -> None: ...

class Unit(java.lang.Object):
    INSTANCE: typing.ClassVar[Unit] = ...
    def toString(self) -> str: ...

_UnsafeLazyImpl__T = typing.TypeVar('_UnsafeLazyImpl__T')  # <T>
class UnsafeLazyImpl(Lazy[_UnsafeLazyImpl__T], java.io.Serializable, typing.Generic[_UnsafeLazyImpl__T]):
    def __init__(self, initializer: kotlin.jvm.functions.Function0[_UnsafeLazyImpl__T], /) -> None: ...
    def getValue(self) -> _UnsafeLazyImpl__T: ...
    def isInitialized(self) -> bool: ...
    def toString(self) -> str: ...

class UnsafeVariance(java.lang.annotation.Annotation): ...

class _Assertions(java.lang.Object):
    ENABLED: typing.ClassVar[bool] = ...
    INSTANCE: typing.ClassVar[_Assertions] = ...
