import typing

import java.lang
import java.lang.annotation
import kotlin.jvm.internal

class JvmPackage(java.lang.Object):
    @typing.overload
    @staticmethod
    def getMAX_VALUE(receiver: kotlin.jvm.internal.ByteCompanionObject, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMAX_VALUE(receiver: kotlin.jvm.internal.DoubleCompanionObject, /) -> float: ...
    @typing.overload
    @staticmethod
    def getMAX_VALUE(receiver: kotlin.jvm.internal.FloatCompanionObject, /) -> float: ...
    @typing.overload
    @staticmethod
    def getMAX_VALUE(receiver: kotlin.jvm.internal.IntCompanionObject, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMAX_VALUE(receiver: kotlin.jvm.internal.LongCompanionObject, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMAX_VALUE(receiver: kotlin.jvm.internal.ShortCompanionObject, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMIN_VALUE(receiver: kotlin.jvm.internal.ByteCompanionObject, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMIN_VALUE(receiver: kotlin.jvm.internal.DoubleCompanionObject, /) -> float: ...
    @typing.overload
    @staticmethod
    def getMIN_VALUE(receiver: kotlin.jvm.internal.FloatCompanionObject, /) -> float: ...
    @typing.overload
    @staticmethod
    def getMIN_VALUE(receiver: kotlin.jvm.internal.IntCompanionObject, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMIN_VALUE(receiver: kotlin.jvm.internal.LongCompanionObject, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMIN_VALUE(receiver: kotlin.jvm.internal.ShortCompanionObject, /) -> int: ...

class native(java.lang.annotation.Annotation): ...

class strictfp(java.lang.annotation.Annotation): ...

class synchronized(java.lang.annotation.Annotation): ...

class transient(java.lang.annotation.Annotation): ...

class volatile(java.lang.annotation.Annotation): ...
