import android.content
import java
import java.io
import java.lang
import java.text

class Configuration(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def getInstance() -> IConfigurationProvider: ...
    @staticmethod
    def setConfigurationProvider(instance: IConfigurationProvider, /) -> None: ...

class DefaultConfigurationProvider(IConfigurationProvider):
    gpsWaitTime: int = ...
    debugMode: bool = ...
    debugMapView: bool = ...
    debugTileProviders: bool = ...
    debugMapTileDownloader: bool = ...
    isMapViewHardwareAccelerated: bool = ...
    userAgentValue: str = ...
    userAgentHttpHeader: str = ...
    cacheMapTileCount: int = ...
    tileDownloadThreads: int = ...
    tileFileSystemThreads: int = ...
    tileDownloadMaxQueueSize: int = ...
    tileFileSystemMaxQueueSize: int = ...
    tileFileSystemCacheMaxBytes: int = ...
    tileFileSystemCacheTrimBytes: int = ...
    httpHeaderDateTimeFormat: java.text.SimpleDateFormat = ...
    osmdroidBasePath: java.io.File = ...
    osmdroidTileCache: java.io.File = ...
    expirationAdder: int = ...
    expirationOverride: int = ...
    def __init__(self) -> None: ...
    def getCacheMapTileCount(self) -> int: ...
    def getExpirationExtendedDuration(self) -> int: ...
    def getExpirationOverrideDuration(self) -> int: ...
    def getGpsWaitTime(self) -> int: ...
    def getHttpHeaderDateTimeFormat(self) -> java.text.SimpleDateFormat: ...
    def getOsmdroidBasePath(self) -> java.io.File: ...
    def getOsmdroidTileCache(self) -> java.io.File: ...
    def getTileDownloadMaxQueueSize(self) -> int: ...
    def getTileDownloadThreads(self) -> int: ...
    def getTileFileSystemCacheMaxBytes(self) -> int: ...
    def getTileFileSystemCacheTrimBytes(self) -> int: ...
    def getTileFileSystemMaxQueueSize(self) -> int: ...
    def getTileFileSystemThreads(self) -> int: ...
    def getUserAgentHttpHeader(self) -> str: ...
    def getUserAgentValue(self) -> str: ...
    def isDebugMapTileDownloader(self) -> bool: ...
    def isDebugMapView(self) -> bool: ...
    def isDebugMode(self) -> bool: ...
    def isDebugTileProviders(self) -> bool: ...
    def isMapViewHardwareAccelerated(self) -> bool: ...
    def load(self, ctx: android.content.Context, prefs: android.content.SharedPreferences, /) -> None: ...
    def save(self, ctx: android.content.Context, prefs: android.content.SharedPreferences, /) -> None: ...
    def setCacheMapTileCount(self, cacheMapTileCount: int | java.jshort | java.lang.Short, /) -> None: ...
    def setDebugMapTileDownloader(self, debugMapTileDownloader: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDebugMapView(self, debugMapView: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDebugMode(self, debugMode: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDebugTileProviders(self, debugTileProviders: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setExpirationExtendedDuration(self, period: int | java.jlong | java.lang.Long, /) -> None: ...
    def setExpirationOverrideDuration(self, period: int | java.jlong | java.lang.Long, /) -> None: ...
    def setGpsWaitTime(self, gpsWaitTime: int | java.jlong | java.lang.Long, /) -> None: ...
    def setHttpHeaderDateTimeFormat(self, httpHeaderDateTimeFormat: java.text.SimpleDateFormat, /) -> None: ...
    def setMapViewHardwareAccelerated(self, mapViewHardwareAccelerated: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setOsmdroidBasePath(self, osmdroidBasePath: java.io.File, /) -> None: ...
    def setOsmdroidTileCache(self, osmdroidTileCache: java.io.File, /) -> None: ...
    def setTileDownloadMaxQueueSize(self, tileDownloadMaxQueueSize: int | java.jshort | java.lang.Short, /) -> None: ...
    def setTileDownloadThreads(self, tileDownloadThreads: int | java.jshort | java.lang.Short, /) -> None: ...
    def setTileFileSystemCacheMaxBytes(self, tileFileSystemCacheMaxBytes: int | java.jlong | java.lang.Long, /) -> None: ...
    def setTileFileSystemCacheTrimBytes(self, tileFileSystemCacheTrimBytes: int | java.jlong | java.lang.Long, /) -> None: ...
    def setTileFileSystemMaxQueueSize(self, tileFileSystemMaxQueueSize: int | java.jshort | java.lang.Short, /) -> None: ...
    def setTileFileSystemThreads(self, tileFileSystemThreads: int | java.jshort | java.lang.Short, /) -> None: ...
    def setUserAgentHttpHeader(self, userAgentHttpHeader: str | java.lang.String, /) -> None: ...
    def setUserAgentValue(self, userAgentValue: str | java.lang.String, /) -> None: ...

class IConfigurationProvider(java.lang.Object):
    def getCacheMapTileCount(self) -> int: ...
    def getExpirationExtendedDuration(self) -> int: ...
    def getExpirationOverrideDuration(self) -> int: ...
    def getGpsWaitTime(self) -> int: ...
    def getHttpHeaderDateTimeFormat(self) -> java.text.SimpleDateFormat: ...
    def getOsmdroidBasePath(self) -> java.io.File: ...
    def getOsmdroidTileCache(self) -> java.io.File: ...
    def getTileDownloadMaxQueueSize(self) -> int: ...
    def getTileDownloadThreads(self) -> int: ...
    def getTileFileSystemCacheMaxBytes(self) -> int: ...
    def getTileFileSystemCacheTrimBytes(self) -> int: ...
    def getTileFileSystemMaxQueueSize(self) -> int: ...
    def getTileFileSystemThreads(self) -> int: ...
    def getUserAgentHttpHeader(self) -> str: ...
    def getUserAgentValue(self) -> str: ...
    def isDebugMapTileDownloader(self) -> bool: ...
    def isDebugMapView(self) -> bool: ...
    def isDebugMode(self) -> bool: ...
    def isDebugTileProviders(self) -> bool: ...
    def isMapViewHardwareAccelerated(self) -> bool: ...
    def load(self, arg1: android.content.Context, arg2: android.content.SharedPreferences, /) -> None: ...
    def save(self, arg1: android.content.Context, arg2: android.content.SharedPreferences, /) -> None: ...
    def setCacheMapTileCount(self, arg1: int | java.jshort | java.lang.Short, /) -> None: ...
    def setDebugMapTileDownloader(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDebugMapView(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDebugMode(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDebugTileProviders(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setExpirationExtendedDuration(self, arg1: int | java.jlong | java.lang.Long, /) -> None: ...
    def setExpirationOverrideDuration(self, arg1: int | java.jlong | java.lang.Long, /) -> None: ...
    def setGpsWaitTime(self, arg1: int | java.jlong | java.lang.Long, /) -> None: ...
    def setHttpHeaderDateTimeFormat(self, arg1: java.text.SimpleDateFormat, /) -> None: ...
    def setMapViewHardwareAccelerated(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setOsmdroidBasePath(self, arg1: java.io.File, /) -> None: ...
    def setOsmdroidTileCache(self, arg1: java.io.File, /) -> None: ...
    def setTileDownloadMaxQueueSize(self, arg1: int | java.jshort | java.lang.Short, /) -> None: ...
    def setTileDownloadThreads(self, arg1: int | java.jshort | java.lang.Short, /) -> None: ...
    def setTileFileSystemCacheMaxBytes(self, arg1: int | java.jlong | java.lang.Long, /) -> None: ...
    def setTileFileSystemCacheTrimBytes(self, arg1: int | java.jlong | java.lang.Long, /) -> None: ...
    def setTileFileSystemMaxQueueSize(self, arg1: int | java.jshort | java.lang.Short, /) -> None: ...
    def setTileFileSystemThreads(self, arg1: int | java.jshort | java.lang.Short, /) -> None: ...
    def setUserAgentHttpHeader(self, arg1: str | java.lang.String, /) -> None: ...
    def setUserAgentValue(self, arg1: str | java.lang.String, /) -> None: ...
