import typing

import android.animation
import android.app
import android.content
import android.content.res
import android.graphics
import android.os
import android.util
import android.view
import android.view.animation
import android.widget
import androidx
import androidx.activity
import androidx.activity.result
import androidx.activity.result.contract
import androidx.collection
import androidx.core.app
import androidx.core.os
import androidx.lifecycle
import androidx.loader.app
import androidx.savedstate
import androidx.viewpager.widget
import java
import java.chaquopy
import java.io
import java.lang
import java.lang.annotation
import java.util
import java.util.concurrent

class BackStackRecord(FragmentTransaction, androidx.fragment.app.FragmentManager.BackStackEntry, androidx.fragment.app.FragmentManager.OpGenerator):
    def commit(self) -> int: ...
    def commitAllowingStateLoss(self) -> int: ...
    def commitNow(self) -> None: ...
    def commitNowAllowingStateLoss(self) -> None: ...
    def detach(self, fragment: Fragment, /) -> FragmentTransaction: ...
    @typing.overload
    def dump(self, prefix: str | java.lang.String, writer: java.io.PrintWriter, /) -> None: ...
    @typing.overload
    def dump(self, prefix: str | java.lang.String, writer: java.io.PrintWriter, full: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def generateOps(self, records: java.util.ArrayList[BackStackRecord], isRecordPop: java.util.ArrayList[java.lang.Boolean], /) -> bool: ...
    def getBreadCrumbShortTitle(self) -> java.lang.CharSequence: ...
    def getBreadCrumbShortTitleRes(self) -> int: ...
    def getBreadCrumbTitle(self) -> java.lang.CharSequence: ...
    def getBreadCrumbTitleRes(self) -> int: ...
    def getId(self) -> int: ...
    def getName(self) -> str: ...
    def hide(self, fragment: Fragment, /) -> FragmentTransaction: ...
    def isEmpty(self) -> bool: ...
    def remove(self, fragment: Fragment, /) -> FragmentTransaction: ...
    def runOnCommitRunnables(self) -> None: ...
    def setMaxLifecycle(self, fragment: Fragment, state: androidx.lifecycle.Lifecycle.State, /) -> FragmentTransaction: ...
    def setPrimaryNavigationFragment(self, fragment: Fragment, /) -> FragmentTransaction: ...
    def show(self, fragment: Fragment, /) -> FragmentTransaction: ...
    def toString(self) -> str: ...

class BackStackState(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator[BackStackState]] = ...
    @typing.overload
    def __init__(self, in_: android.os.Parcel, /) -> None: ...
    @typing.overload
    def __init__(self, bse: BackStackRecord, /) -> None: ...
    def describeContents(self) -> int: ...
    def instantiate(self, fm: FragmentManager, /) -> BackStackRecord: ...
    def writeToParcel(self, dest: android.os.Parcel, flags: int | java.jint | java.lang.Integer, /) -> None: ...

class DefaultSpecialEffectsController(SpecialEffectsController): ...

class DialogFragment(Fragment, android.content.DialogInterface.OnCancelListener, android.content.DialogInterface.OnDismissListener):
    STYLE_NORMAL: typing.ClassVar[int] = ...
    STYLE_NO_TITLE: typing.ClassVar[int] = ...
    STYLE_NO_FRAME: typing.ClassVar[int] = ...
    STYLE_NO_INPUT: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, contentLayoutId: int | java.jint | java.lang.Integer, /) -> None: ...
    def dismiss(self) -> None: ...
    def dismissAllowingStateLoss(self) -> None: ...
    def getDialog(self) -> android.app.Dialog: ...
    def getShowsDialog(self) -> bool: ...
    def getTheme(self) -> int: ...
    def isCancelable(self) -> bool: ...
    def onAttach(self, context: android.content.Context, /) -> None: ...
    def onCancel(self, dialog: android.content.DialogInterface, /) -> None: ...
    def onCreate(self, savedInstanceState: android.os.Bundle, /) -> None: ...
    def onCreateDialog(self, savedInstanceState: android.os.Bundle, /) -> android.app.Dialog: ...
    def onDestroyView(self) -> None: ...
    def onDetach(self) -> None: ...
    def onDismiss(self, dialog: android.content.DialogInterface, /) -> None: ...
    def onGetLayoutInflater(self, savedInstanceState: android.os.Bundle, /) -> android.view.LayoutInflater: ...
    def onSaveInstanceState(self, outState: android.os.Bundle, /) -> None: ...
    def onStart(self) -> None: ...
    def onStop(self) -> None: ...
    def onViewStateRestored(self, savedInstanceState: android.os.Bundle, /) -> None: ...
    def requireDialog(self) -> android.app.Dialog: ...
    def setCancelable(self, cancelable: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setShowsDialog(self, showsDialog: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setStyle(self, style: int | java.jint | java.lang.Integer, theme: int | java.jint | java.lang.Integer, /) -> None: ...
    def setupDialog(self, dialog: android.app.Dialog, style: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def show(self, manager: FragmentManager, tag: str | java.lang.String, /) -> None: ...
    @typing.overload
    def show(self, transaction: FragmentTransaction, tag: str | java.lang.String, /) -> int: ...
    def showNow(self, manager: FragmentManager, tag: str | java.lang.String, /) -> None: ...

class Fragment(android.content.ComponentCallbacks, android.view.View.OnCreateContextMenuListener, androidx.lifecycle.LifecycleOwner, androidx.lifecycle.ViewModelStoreOwner, androidx.lifecycle.HasDefaultViewModelProviderFactory, androidx.savedstate.SavedStateRegistryOwner, androidx.activity.result.ActivityResultCaller):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, contentLayoutId: int | java.jint | java.lang.Integer, /) -> None: ...
    def dump(self, prefix: str | java.lang.String, fd: java.io.FileDescriptor, writer: java.io.PrintWriter, args: java.chaquopy.JavaArray[java.lang.String], /) -> None: ...
    def equals(self, o: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getActivity(self) -> FragmentActivity: ...
    def getAllowEnterTransitionOverlap(self) -> bool: ...
    def getAllowReturnTransitionOverlap(self) -> bool: ...
    def getArguments(self) -> android.os.Bundle: ...
    def getChildFragmentManager(self) -> FragmentManager: ...
    def getContext(self) -> android.content.Context: ...
    def getDefaultViewModelProviderFactory(self) -> androidx.lifecycle.ViewModelProvider.Factory: ...
    def getEnterTransition(self) -> java.lang.Object: ...
    def getExitTransition(self) -> java.lang.Object: ...
    def getFragmentManager(self) -> FragmentManager: ...
    def getHost(self) -> java.lang.Object: ...
    def getId(self) -> int: ...
    @typing.overload
    def getLayoutInflater(self) -> android.view.LayoutInflater: ...
    @typing.overload
    def getLayoutInflater(self, savedFragmentState: android.os.Bundle, /) -> android.view.LayoutInflater: ...
    def getLifecycle(self) -> androidx.lifecycle.Lifecycle: ...
    def getLoaderManager(self) -> androidx.loader.app.LoaderManager: ...
    def getParentFragment(self) -> Fragment: ...
    def getParentFragmentManager(self) -> FragmentManager: ...
    def getReenterTransition(self) -> java.lang.Object: ...
    def getResources(self) -> android.content.res.Resources: ...
    def getRetainInstance(self) -> bool: ...
    def getReturnTransition(self) -> java.lang.Object: ...
    def getSavedStateRegistry(self) -> androidx.savedstate.SavedStateRegistry: ...
    def getSharedElementEnterTransition(self) -> java.lang.Object: ...
    def getSharedElementReturnTransition(self) -> java.lang.Object: ...
    @typing.overload
    def getString(self, resId: int | java.jint | java.lang.Integer, /) -> str: ...
    @typing.overload
    def getString(self, resId: int | java.jint | java.lang.Integer, /, *formatArgs: java.lang.Object) -> str: ...
    def getTag(self) -> str: ...
    def getTargetFragment(self) -> Fragment: ...
    def getTargetRequestCode(self) -> int: ...
    def getText(self, resId: int | java.jint | java.lang.Integer, /) -> java.lang.CharSequence: ...
    def getUserVisibleHint(self) -> bool: ...
    def getView(self) -> android.view.View: ...
    def getViewLifecycleOwner(self) -> androidx.lifecycle.LifecycleOwner: ...
    def getViewLifecycleOwnerLiveData(self) -> androidx.lifecycle.LiveData[androidx.lifecycle.LifecycleOwner]: ...
    def getViewModelStore(self) -> androidx.lifecycle.ViewModelStore: ...
    def hasOptionsMenu(self) -> bool: ...
    def hashCode(self) -> int: ...
    @typing.overload
    @staticmethod
    def instantiate(context: android.content.Context, fname: str | java.lang.String, /) -> Fragment: ...
    @typing.overload
    @staticmethod
    def instantiate(context: android.content.Context, fname: str | java.lang.String, args: android.os.Bundle, /) -> Fragment: ...
    def isAdded(self) -> bool: ...
    def isDetached(self) -> bool: ...
    def isHidden(self) -> bool: ...
    def isInLayout(self) -> bool: ...
    def isMenuVisible(self) -> bool: ...
    def isRemoving(self) -> bool: ...
    def isResumed(self) -> bool: ...
    def isStateSaved(self) -> bool: ...
    def isVisible(self) -> bool: ...
    def onActivityCreated(self, savedInstanceState: android.os.Bundle, /) -> None: ...
    def onActivityResult(self, requestCode: int | java.jint | java.lang.Integer, resultCode: int | java.jint | java.lang.Integer, data: android.content.Intent, /) -> None: ...
    @typing.overload
    def onAttach(self, activity: android.app.Activity, /) -> None: ...
    @typing.overload
    def onAttach(self, context: android.content.Context, /) -> None: ...
    def onAttachFragment(self, childFragment: Fragment, /) -> None: ...
    def onConfigurationChanged(self, newConfig: android.content.res.Configuration, /) -> None: ...
    def onContextItemSelected(self, item: android.view.MenuItem, /) -> bool: ...
    def onCreate(self, savedInstanceState: android.os.Bundle, /) -> None: ...
    def onCreateAnimation(self, transit: int | java.jint | java.lang.Integer, enter: bool | java.jboolean | java.lang.Boolean, nextAnim: int | java.jint | java.lang.Integer, /) -> android.view.animation.Animation: ...
    def onCreateAnimator(self, transit: int | java.jint | java.lang.Integer, enter: bool | java.jboolean | java.lang.Boolean, nextAnim: int | java.jint | java.lang.Integer, /) -> android.animation.Animator: ...
    def onCreateContextMenu(self, menu: android.view.ContextMenu, v: android.view.View, menuInfo: android.view.ContextMenu.ContextMenuInfo, /) -> None: ...
    def onCreateOptionsMenu(self, menu: android.view.Menu, inflater: android.view.MenuInflater, /) -> None: ...
    def onCreateView(self, inflater: android.view.LayoutInflater, container: android.view.ViewGroup, savedInstanceState: android.os.Bundle, /) -> android.view.View: ...
    def onDestroy(self) -> None: ...
    def onDestroyOptionsMenu(self) -> None: ...
    def onDestroyView(self) -> None: ...
    def onDetach(self) -> None: ...
    def onGetLayoutInflater(self, savedInstanceState: android.os.Bundle, /) -> android.view.LayoutInflater: ...
    def onHiddenChanged(self, hidden: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def onInflate(self, activity: android.app.Activity, attrs: android.util.AttributeSet, savedInstanceState: android.os.Bundle, /) -> None: ...
    @typing.overload
    def onInflate(self, context: android.content.Context, attrs: android.util.AttributeSet, savedInstanceState: android.os.Bundle, /) -> None: ...
    def onLowMemory(self) -> None: ...
    def onMultiWindowModeChanged(self, isInMultiWindowMode: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def onOptionsItemSelected(self, item: android.view.MenuItem, /) -> bool: ...
    def onOptionsMenuClosed(self, menu: android.view.Menu, /) -> None: ...
    def onPause(self) -> None: ...
    def onPictureInPictureModeChanged(self, isInPictureInPictureMode: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def onPrepareOptionsMenu(self, menu: android.view.Menu, /) -> None: ...
    def onPrimaryNavigationFragmentChanged(self, isPrimaryNavigationFragment: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def onRequestPermissionsResult(self, requestCode: int | java.jint | java.lang.Integer, permissions: java.chaquopy.JavaArray[java.lang.String], grantResults: java.chaquopy.JavaArrayJInt, /) -> None: ...
    def onResume(self) -> None: ...
    def onSaveInstanceState(self, outState: android.os.Bundle, /) -> None: ...
    def onStart(self) -> None: ...
    def onStop(self) -> None: ...
    def onViewCreated(self, view: android.view.View, savedInstanceState: android.os.Bundle, /) -> None: ...
    def onViewStateRestored(self, savedInstanceState: android.os.Bundle, /) -> None: ...
    @typing.overload
    def postponeEnterTransition(self) -> None: ...
    @typing.overload
    def postponeEnterTransition(self, duration: int | java.jlong | java.lang.Long, timeUnit: java.util.concurrent.TimeUnit, /) -> None: ...
    _registerForActivityResult_0__I = typing.TypeVar('_registerForActivityResult_0__I')  # <I>
    _registerForActivityResult_0__O = typing.TypeVar('_registerForActivityResult_0__O')  # <O>
    _registerForActivityResult_1__I = typing.TypeVar('_registerForActivityResult_1__I')  # <I>
    _registerForActivityResult_1__O = typing.TypeVar('_registerForActivityResult_1__O')  # <O>
    @typing.overload
    def registerForActivityResult(self, contract: androidx.activity.result.contract.ActivityResultContract[_registerForActivityResult_0__I, _registerForActivityResult_0__O], callback: androidx.activity.result.ActivityResultCallback[_registerForActivityResult_0__O], /) -> androidx.activity.result.ActivityResultLauncher[_registerForActivityResult_0__I]: ...
    @typing.overload
    def registerForActivityResult(self, contract: androidx.activity.result.contract.ActivityResultContract[_registerForActivityResult_1__I, _registerForActivityResult_1__O], registry: androidx.activity.result.ActivityResultRegistry, callback: androidx.activity.result.ActivityResultCallback[_registerForActivityResult_1__O], /) -> androidx.activity.result.ActivityResultLauncher[_registerForActivityResult_1__I]: ...
    def registerForContextMenu(self, view: android.view.View, /) -> None: ...
    def requestPermissions(self, permissions: java.chaquopy.JavaArray[java.lang.String], requestCode: int | java.jint | java.lang.Integer, /) -> None: ...
    def requireActivity(self) -> FragmentActivity: ...
    def requireArguments(self) -> android.os.Bundle: ...
    def requireContext(self) -> android.content.Context: ...
    def requireFragmentManager(self) -> FragmentManager: ...
    def requireHost(self) -> java.lang.Object: ...
    def requireParentFragment(self) -> Fragment: ...
    def requireView(self) -> android.view.View: ...
    def setAllowEnterTransitionOverlap(self, allow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setAllowReturnTransitionOverlap(self, allow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setArguments(self, args: android.os.Bundle, /) -> None: ...
    def setEnterSharedElementCallback(self, callback: androidx.core.app.SharedElementCallback, /) -> None: ...
    def setEnterTransition(self, transition: java.lang.Object | int | bool | float | str, /) -> None: ...
    def setExitSharedElementCallback(self, callback: androidx.core.app.SharedElementCallback, /) -> None: ...
    def setExitTransition(self, transition: java.lang.Object | int | bool | float | str, /) -> None: ...
    def setHasOptionsMenu(self, hasMenu: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setInitialSavedState(self, state: Fragment.SavedState, /) -> None: ...
    def setMenuVisibility(self, menuVisible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setReenterTransition(self, transition: java.lang.Object | int | bool | float | str, /) -> None: ...
    def setRetainInstance(self, retain: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setReturnTransition(self, transition: java.lang.Object | int | bool | float | str, /) -> None: ...
    def setSharedElementEnterTransition(self, transition: java.lang.Object | int | bool | float | str, /) -> None: ...
    def setSharedElementReturnTransition(self, transition: java.lang.Object | int | bool | float | str, /) -> None: ...
    def setTargetFragment(self, fragment: Fragment, requestCode: int | java.jint | java.lang.Integer, /) -> None: ...
    def setUserVisibleHint(self, isVisibleToUser: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def shouldShowRequestPermissionRationale(self, permission: str | java.lang.String, /) -> bool: ...
    @typing.overload
    def startActivity(self, intent: android.content.Intent, /) -> None: ...
    @typing.overload
    def startActivity(self, intent: android.content.Intent, options: android.os.Bundle, /) -> None: ...
    @typing.overload
    def startActivityForResult(self, intent: android.content.Intent, requestCode: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def startActivityForResult(self, intent: android.content.Intent, requestCode: int | java.jint | java.lang.Integer, options: android.os.Bundle, /) -> None: ...
    def startIntentSenderForResult(self, intent: android.content.IntentSender, requestCode: int | java.jint | java.lang.Integer, fillInIntent: android.content.Intent, flagsMask: int | java.jint | java.lang.Integer, flagsValues: int | java.jint | java.lang.Integer, extraFlags: int | java.jint | java.lang.Integer, options: android.os.Bundle, /) -> None: ...
    def startPostponedEnterTransition(self) -> None: ...
    def toString(self) -> str: ...
    def unregisterForContextMenu(self, view: android.view.View, /) -> None: ...

    class InstantiationException(java.lang.RuntimeException):
        def __init__(self, msg: str | java.lang.String, cause: java.lang.Exception, /) -> None: ...

    class SavedState(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator[Fragment.SavedState]] = ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, dest: android.os.Parcel, flags: int | java.jint | java.lang.Integer, /) -> None: ...

class FragmentActivity(androidx.activity.ComponentActivity, androidx.core.app.ActivityCompat.OnRequestPermissionsResultCallback, androidx.core.app.ActivityCompat.RequestPermissionsRequestCodeValidator):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, contentLayoutId: int | java.jint | java.lang.Integer, /) -> None: ...
    def dump(self, prefix: str | java.lang.String, fd: java.io.FileDescriptor, writer: java.io.PrintWriter, args: java.chaquopy.JavaArray[java.lang.String], /) -> None: ...
    def getSupportFragmentManager(self) -> FragmentManager: ...
    def getSupportLoaderManager(self) -> androidx.loader.app.LoaderManager: ...
    def onActivityResult(self, requestCode: int | java.jint | java.lang.Integer, resultCode: int | java.jint | java.lang.Integer, data: android.content.Intent, /) -> None: ...
    def onAttachFragment(self, fragment: Fragment, /) -> None: ...
    def onConfigurationChanged(self, newConfig: android.content.res.Configuration, /) -> None: ...
    def onCreate(self, savedInstanceState: android.os.Bundle, /) -> None: ...
    def onCreatePanelMenu(self, featureId: int | java.jint | java.lang.Integer, menu: android.view.Menu, /) -> bool: ...
    @typing.overload
    def onCreateView(self, name: str | java.lang.String, context: android.content.Context, attrs: android.util.AttributeSet, /) -> android.view.View: ...
    @typing.overload
    def onCreateView(self, parent: android.view.View, name: str | java.lang.String, context: android.content.Context, attrs: android.util.AttributeSet, /) -> android.view.View: ...
    def onDestroy(self) -> None: ...
    def onLowMemory(self) -> None: ...
    def onMenuItemSelected(self, featureId: int | java.jint | java.lang.Integer, item: android.view.MenuItem, /) -> bool: ...
    def onMultiWindowModeChanged(self, isInMultiWindowMode: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def onNewIntent(self, intent: android.content.Intent, /) -> None: ...
    def onPanelClosed(self, featureId: int | java.jint | java.lang.Integer, menu: android.view.Menu, /) -> None: ...
    def onPause(self) -> None: ...
    def onPictureInPictureModeChanged(self, isInPictureInPictureMode: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def onPostResume(self) -> None: ...
    def onPrepareOptionsPanel(self, view: android.view.View, menu: android.view.Menu, /) -> bool: ...
    def onPreparePanel(self, featureId: int | java.jint | java.lang.Integer, view: android.view.View, menu: android.view.Menu, /) -> bool: ...
    def onRequestPermissionsResult(self, requestCode: int | java.jint | java.lang.Integer, permissions: java.chaquopy.JavaArray[java.lang.String], grantResults: java.chaquopy.JavaArrayJInt, /) -> None: ...
    def onResume(self) -> None: ...
    def onResumeFragments(self) -> None: ...
    def onStart(self) -> None: ...
    def onStateNotSaved(self) -> None: ...
    def onStop(self) -> None: ...
    def setEnterSharedElementCallback(self, callback: androidx.core.app.SharedElementCallback, /) -> None: ...
    def setExitSharedElementCallback(self, listener: androidx.core.app.SharedElementCallback, /) -> None: ...
    @typing.overload
    def startActivityFromFragment(self, fragment: Fragment, intent: android.content.Intent, requestCode: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def startActivityFromFragment(self, fragment: Fragment, intent: android.content.Intent, requestCode: int | java.jint | java.lang.Integer, options: android.os.Bundle, /) -> None: ...
    def startIntentSenderFromFragment(self, fragment: Fragment, intent: android.content.IntentSender, requestCode: int | java.jint | java.lang.Integer, fillInIntent: android.content.Intent, flagsMask: int | java.jint | java.lang.Integer, flagsValues: int | java.jint | java.lang.Integer, extraFlags: int | java.jint | java.lang.Integer, options: android.os.Bundle, /) -> None: ...
    def supportFinishAfterTransition(self) -> None: ...
    def supportInvalidateOptionsMenu(self) -> None: ...
    def supportPostponeEnterTransition(self) -> None: ...
    def supportStartPostponedEnterTransition(self) -> None: ...
    def validateRequestPermissionsRequestCode(self, requestCode: int | java.jint | java.lang.Integer, /) -> None: ...

class FragmentAnim(java.lang.Object): ...

class FragmentContainer(java.lang.Object):
    def __init__(self) -> None: ...
    def instantiate(self, context: android.content.Context, className: str | java.lang.String, arguments: android.os.Bundle, /) -> Fragment: ...
    def onFindViewById(self, arg1: int | java.jint | java.lang.Integer, /) -> android.view.View: ...
    def onHasView(self) -> bool: ...

class FragmentContainerView(android.widget.FrameLayout):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def addView(self, child: android.view.View, index: int | java.jint | java.lang.Integer, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    def addViewInLayout(self, child: android.view.View, index: int | java.jint | java.lang.Integer, params: android.view.ViewGroup.LayoutParams, preventRequestLayout: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def dispatchApplyWindowInsets(self, insets: android.view.WindowInsets, /) -> android.view.WindowInsets: ...
    def dispatchDraw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def drawChild(self, canvas: android.graphics.Canvas, child: android.view.View, drawingTime: int | java.jlong | java.lang.Long, /) -> bool: ...
    def endViewTransition(self, view: android.view.View, /) -> None: ...
    def removeAllViewsInLayout(self) -> None: ...
    def removeDetachedView(self, child: android.view.View, animate: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def removeView(self, view: android.view.View, /) -> None: ...
    def removeViewAt(self, index: int | java.jint | java.lang.Integer, /) -> None: ...
    def removeViewInLayout(self, view: android.view.View, /) -> None: ...
    def removeViews(self, start: int | java.jint | java.lang.Integer, count: int | java.jint | java.lang.Integer, /) -> None: ...
    def removeViewsInLayout(self, start: int | java.jint | java.lang.Integer, count: int | java.jint | java.lang.Integer, /) -> None: ...
    def setLayoutTransition(self, transition: android.animation.LayoutTransition, /) -> None: ...
    def setOnApplyWindowInsetsListener(self, listener: android.view.View.OnApplyWindowInsetsListener, /) -> None: ...
    def startViewTransition(self, view: android.view.View, /) -> None: ...

class FragmentController(java.lang.Object):
    def attachHost(self, parent: Fragment, /) -> None: ...
    @staticmethod
    def createController(callbacks: FragmentHostCallback[java.lang.Object], /) -> FragmentController: ...
    def dispatchActivityCreated(self) -> None: ...
    def dispatchConfigurationChanged(self, newConfig: android.content.res.Configuration, /) -> None: ...
    def dispatchContextItemSelected(self, item: android.view.MenuItem, /) -> bool: ...
    def dispatchCreate(self) -> None: ...
    def dispatchCreateOptionsMenu(self, menu: android.view.Menu, inflater: android.view.MenuInflater, /) -> bool: ...
    def dispatchDestroy(self) -> None: ...
    def dispatchDestroyView(self) -> None: ...
    def dispatchLowMemory(self) -> None: ...
    def dispatchMultiWindowModeChanged(self, isInMultiWindowMode: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def dispatchOptionsItemSelected(self, item: android.view.MenuItem, /) -> bool: ...
    def dispatchOptionsMenuClosed(self, menu: android.view.Menu, /) -> None: ...
    def dispatchPause(self) -> None: ...
    def dispatchPictureInPictureModeChanged(self, isInPictureInPictureMode: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def dispatchPrepareOptionsMenu(self, menu: android.view.Menu, /) -> bool: ...
    def dispatchReallyStop(self) -> None: ...
    def dispatchResume(self) -> None: ...
    def dispatchStart(self) -> None: ...
    def dispatchStop(self) -> None: ...
    def doLoaderDestroy(self) -> None: ...
    def doLoaderRetain(self) -> None: ...
    def doLoaderStart(self) -> None: ...
    def doLoaderStop(self, retain: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def dumpLoaders(self, prefix: str | java.lang.String, fd: java.io.FileDescriptor, writer: java.io.PrintWriter, args: java.chaquopy.JavaArray[java.lang.String], /) -> None: ...
    def execPendingActions(self) -> bool: ...
    def findFragmentByWho(self, who: str | java.lang.String, /) -> Fragment: ...
    def getActiveFragments(self, actives: java.util.List[Fragment], /) -> java.util.List[Fragment]: ...
    def getActiveFragmentsCount(self) -> int: ...
    def getSupportFragmentManager(self) -> FragmentManager: ...
    def getSupportLoaderManager(self) -> androidx.loader.app.LoaderManager: ...
    def noteStateNotSaved(self) -> None: ...
    def onCreateView(self, parent: android.view.View, name: str | java.lang.String, context: android.content.Context, attrs: android.util.AttributeSet, /) -> android.view.View: ...
    def reportLoaderStart(self) -> None: ...
    @typing.overload
    def restoreAllState(self, state: android.os.Parcelable, nonConfig: FragmentManagerNonConfig, /) -> None: ...
    @typing.overload
    def restoreAllState(self, state: android.os.Parcelable, nonConfigList: java.util.List[Fragment], /) -> None: ...
    def restoreLoaderNonConfig(self, loaderManagers: androidx.collection.SimpleArrayMap[java.lang.String, androidx.loader.app.LoaderManager], /) -> None: ...
    def restoreSaveState(self, state: android.os.Parcelable, /) -> None: ...
    def retainLoaderNonConfig(self) -> androidx.collection.SimpleArrayMap[java.lang.String, androidx.loader.app.LoaderManager]: ...
    def retainNestedNonConfig(self) -> FragmentManagerNonConfig: ...
    def retainNonConfig(self) -> java.util.List[Fragment]: ...
    def saveAllState(self) -> android.os.Parcelable: ...

class FragmentFactory(java.lang.Object):
    def __init__(self) -> None: ...
    def instantiate(self, classLoader: java.lang.ClassLoader, className: str | java.lang.String, /) -> Fragment: ...
    @staticmethod
    def loadFragmentClass(classLoader: java.lang.ClassLoader, className: str | java.lang.String, /) -> typing.Type[Fragment]: ...

_FragmentHostCallback__E = typing.TypeVar('_FragmentHostCallback__E')  # <E>
class FragmentHostCallback(FragmentContainer, typing.Generic[_FragmentHostCallback__E]):
    def __init__(self, context: android.content.Context, handler: android.os.Handler, windowAnimations: int | java.jint | java.lang.Integer, /) -> None: ...
    def onDump(self, prefix: str | java.lang.String, fd: java.io.FileDescriptor, writer: java.io.PrintWriter, args: java.chaquopy.JavaArray[java.lang.String], /) -> None: ...
    def onFindViewById(self, id: int | java.jint | java.lang.Integer, /) -> android.view.View: ...
    def onGetHost(self) -> _FragmentHostCallback__E: ...
    def onGetLayoutInflater(self) -> android.view.LayoutInflater: ...
    def onGetWindowAnimations(self) -> int: ...
    def onHasView(self) -> bool: ...
    def onHasWindowAnimations(self) -> bool: ...
    def onRequestPermissionsFromFragment(self, fragment: Fragment, permissions: java.chaquopy.JavaArray[java.lang.String], requestCode: int | java.jint | java.lang.Integer, /) -> None: ...
    def onShouldSaveFragmentState(self, fragment: Fragment, /) -> bool: ...
    def onShouldShowRequestPermissionRationale(self, permission: str | java.lang.String, /) -> bool: ...
    @typing.overload
    def onStartActivityFromFragment(self, fragment: Fragment, intent: android.content.Intent, requestCode: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def onStartActivityFromFragment(self, fragment: Fragment, intent: android.content.Intent, requestCode: int | java.jint | java.lang.Integer, options: android.os.Bundle, /) -> None: ...
    def onStartIntentSenderFromFragment(self, fragment: Fragment, intent: android.content.IntentSender, requestCode: int | java.jint | java.lang.Integer, fillInIntent: android.content.Intent, flagsMask: int | java.jint | java.lang.Integer, flagsValues: int | java.jint | java.lang.Integer, extraFlags: int | java.jint | java.lang.Integer, options: android.os.Bundle, /) -> None: ...
    def onSupportInvalidateOptionsMenu(self) -> None: ...

class FragmentLayoutInflaterFactory(android.view.LayoutInflater.Factory2):
    @typing.overload
    def onCreateView(self, name: str | java.lang.String, context: android.content.Context, attrs: android.util.AttributeSet, /) -> android.view.View: ...
    @typing.overload
    def onCreateView(self, parent: android.view.View, name: str | java.lang.String, context: android.content.Context, attrs: android.util.AttributeSet, /) -> android.view.View: ...

class FragmentLifecycleCallbacksDispatcher(java.lang.Object):
    def registerFragmentLifecycleCallbacks(self, cb: FragmentManager.FragmentLifecycleCallbacks, recursive: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def unregisterFragmentLifecycleCallbacks(self, cb: FragmentManager.FragmentLifecycleCallbacks, /) -> None: ...

class FragmentManager(FragmentResultOwner):
    POP_BACK_STACK_INCLUSIVE: typing.ClassVar[int] = ...
    def __init__(self) -> None: ...
    def addFragmentOnAttachListener(self, listener: FragmentOnAttachListener, /) -> None: ...
    def addOnBackStackChangedListener(self, listener: FragmentManager.OnBackStackChangedListener, /) -> None: ...
    def beginTransaction(self) -> FragmentTransaction: ...
    def clearFragmentResult(self, requestKey: str | java.lang.String, /) -> None: ...
    def clearFragmentResultListener(self, requestKey: str | java.lang.String, /) -> None: ...
    def dump(self, prefix: str | java.lang.String, fd: java.io.FileDescriptor, writer: java.io.PrintWriter, args: java.chaquopy.JavaArray[java.lang.String], /) -> None: ...
    @staticmethod
    def enableDebugLogging(enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def enableNewStateManager(enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def executePendingTransactions(self) -> bool: ...
    @staticmethod
    def findFragment(view: android.view.View, /) -> Fragment: ...
    def findFragmentById(self, id: int | java.jint | java.lang.Integer, /) -> Fragment: ...
    def findFragmentByTag(self, tag: str | java.lang.String, /) -> Fragment: ...
    def getBackStackEntryAt(self, index: int | java.jint | java.lang.Integer, /) -> FragmentManager.BackStackEntry: ...
    def getBackStackEntryCount(self) -> int: ...
    def getFragment(self, bundle: android.os.Bundle, key: str | java.lang.String, /) -> Fragment: ...
    def getFragmentFactory(self) -> FragmentFactory: ...
    def getFragments(self) -> java.util.List[Fragment]: ...
    def getPrimaryNavigationFragment(self) -> Fragment: ...
    def isDestroyed(self) -> bool: ...
    def isStateSaved(self) -> bool: ...
    def openTransaction(self) -> FragmentTransaction: ...
    @typing.overload
    def popBackStack(self) -> None: ...
    @typing.overload
    def popBackStack(self, id: int | java.jint | java.lang.Integer, flags: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def popBackStack(self, name: str | java.lang.String, flags: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def popBackStackImmediate(self) -> bool: ...
    @typing.overload
    def popBackStackImmediate(self, id: int | java.jint | java.lang.Integer, flags: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def popBackStackImmediate(self, name: str | java.lang.String, flags: int | java.jint | java.lang.Integer, /) -> bool: ...
    def putFragment(self, bundle: android.os.Bundle, key: str | java.lang.String, fragment: Fragment, /) -> None: ...
    def registerFragmentLifecycleCallbacks(self, cb: FragmentManager.FragmentLifecycleCallbacks, recursive: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def removeFragmentOnAttachListener(self, listener: FragmentOnAttachListener, /) -> None: ...
    def removeOnBackStackChangedListener(self, listener: FragmentManager.OnBackStackChangedListener, /) -> None: ...
    def saveFragmentInstanceState(self, fragment: Fragment, /) -> Fragment.SavedState: ...
    def setFragmentFactory(self, fragmentFactory: FragmentFactory, /) -> None: ...
    def setFragmentResult(self, requestKey: str | java.lang.String, result: android.os.Bundle, /) -> None: ...
    def setFragmentResultListener(self, requestKey: str | java.lang.String, lifecycleOwner: androidx.lifecycle.LifecycleOwner, listener: FragmentResultListener, /) -> None: ...
    def toString(self) -> str: ...
    def unregisterFragmentLifecycleCallbacks(self, cb: FragmentManager.FragmentLifecycleCallbacks, /) -> None: ...

    class FragmentLifecycleCallbacks(java.lang.Object):
        def __init__(self) -> None: ...
        def onFragmentActivityCreated(self, fm: FragmentManager, f: Fragment, savedInstanceState: android.os.Bundle, /) -> None: ...
        def onFragmentAttached(self, fm: FragmentManager, f: Fragment, context: android.content.Context, /) -> None: ...
        def onFragmentCreated(self, fm: FragmentManager, f: Fragment, savedInstanceState: android.os.Bundle, /) -> None: ...
        def onFragmentDestroyed(self, fm: FragmentManager, f: Fragment, /) -> None: ...
        def onFragmentDetached(self, fm: FragmentManager, f: Fragment, /) -> None: ...
        def onFragmentPaused(self, fm: FragmentManager, f: Fragment, /) -> None: ...
        def onFragmentPreAttached(self, fm: FragmentManager, f: Fragment, context: android.content.Context, /) -> None: ...
        def onFragmentPreCreated(self, fm: FragmentManager, f: Fragment, savedInstanceState: android.os.Bundle, /) -> None: ...
        def onFragmentResumed(self, fm: FragmentManager, f: Fragment, /) -> None: ...
        def onFragmentSaveInstanceState(self, fm: FragmentManager, f: Fragment, outState: android.os.Bundle, /) -> None: ...
        def onFragmentStarted(self, fm: FragmentManager, f: Fragment, /) -> None: ...
        def onFragmentStopped(self, fm: FragmentManager, f: Fragment, /) -> None: ...
        def onFragmentViewCreated(self, fm: FragmentManager, f: Fragment, v: android.view.View, savedInstanceState: android.os.Bundle, /) -> None: ...
        def onFragmentViewDestroyed(self, fm: FragmentManager, f: Fragment, /) -> None: ...

    class OnBackStackChangedListener(java.lang.Object):
        def onBackStackChanged(self) -> None: ...

    class BackStackEntry(java.lang.Object):
        def getBreadCrumbShortTitle(self) -> java.lang.CharSequence: ...
        def getBreadCrumbShortTitleRes(self) -> int: ...
        def getBreadCrumbTitle(self) -> java.lang.CharSequence: ...
        def getBreadCrumbTitleRes(self) -> int: ...
        def getId(self) -> int: ...
        def getName(self) -> str: ...

class FragmentManagerImpl(FragmentManager): ...

class FragmentManagerNonConfig(java.lang.Object): ...

class FragmentManagerState(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator[FragmentManagerState]] = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, in_: android.os.Parcel, /) -> None: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, dest: android.os.Parcel, flags: int | java.jint | java.lang.Integer, /) -> None: ...

class FragmentManagerViewModel(androidx.lifecycle.ViewModel):
    def equals(self, o: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def hashCode(self) -> int: ...
    def onCleared(self) -> None: ...
    def toString(self) -> str: ...

class FragmentOnAttachListener(java.lang.Object):
    def onAttachFragment(self, arg1: FragmentManager, arg2: Fragment, /) -> None: ...

class FragmentPagerAdapter(androidx.viewpager.widget.PagerAdapter):
    BEHAVIOR_SET_USER_VISIBLE_HINT: typing.ClassVar[int] = ...
    BEHAVIOR_RESUME_ONLY_CURRENT_FRAGMENT: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, fm: FragmentManager, /) -> None: ...
    @typing.overload
    def __init__(self, fm: FragmentManager, behavior: int | java.jint | java.lang.Integer, /) -> None: ...
    def destroyItem(self, container: android.view.ViewGroup, position: int | java.jint | java.lang.Integer, object: java.lang.Object | int | bool | float | str, /) -> None: ...
    def finishUpdate(self, container: android.view.ViewGroup, /) -> None: ...
    def getItem(self, arg1: int | java.jint | java.lang.Integer, /) -> Fragment: ...
    def getItemId(self, position: int | java.jint | java.lang.Integer, /) -> int: ...
    def instantiateItem(self, container: android.view.ViewGroup, position: int | java.jint | java.lang.Integer, /) -> java.lang.Object: ...
    def isViewFromObject(self, view: android.view.View, object: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def restoreState(self, state: android.os.Parcelable, loader: java.lang.ClassLoader, /) -> None: ...
    def saveState(self) -> android.os.Parcelable: ...
    def setPrimaryItem(self, container: android.view.ViewGroup, position: int | java.jint | java.lang.Integer, object: java.lang.Object | int | bool | float | str, /) -> None: ...
    def startUpdate(self, container: android.view.ViewGroup, /) -> None: ...

class FragmentResultListener(java.lang.Object):
    def onFragmentResult(self, arg1: str | java.lang.String, arg2: android.os.Bundle, /) -> None: ...

class FragmentResultOwner(java.lang.Object):
    def clearFragmentResult(self, arg1: str | java.lang.String, /) -> None: ...
    def clearFragmentResultListener(self, arg1: str | java.lang.String, /) -> None: ...
    def setFragmentResult(self, arg1: str | java.lang.String, arg2: android.os.Bundle, /) -> None: ...
    def setFragmentResultListener(self, arg1: str | java.lang.String, arg2: androidx.lifecycle.LifecycleOwner, arg3: FragmentResultListener, /) -> None: ...

class FragmentState(android.os.Parcelable):
    CREATOR: typing.ClassVar[android.os.Parcelable.Creator[FragmentState]] = ...
    def describeContents(self) -> int: ...
    def toString(self) -> str: ...
    def writeToParcel(self, dest: android.os.Parcel, flags: int | java.jint | java.lang.Integer, /) -> None: ...

class FragmentStateManager(java.lang.Object): ...

class FragmentStateManagerControl(java.lang.annotation.Annotation): ...

class FragmentStatePagerAdapter(androidx.viewpager.widget.PagerAdapter):
    BEHAVIOR_SET_USER_VISIBLE_HINT: typing.ClassVar[int] = ...
    BEHAVIOR_RESUME_ONLY_CURRENT_FRAGMENT: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, fm: FragmentManager, /) -> None: ...
    @typing.overload
    def __init__(self, fm: FragmentManager, behavior: int | java.jint | java.lang.Integer, /) -> None: ...
    def destroyItem(self, container: android.view.ViewGroup, position: int | java.jint | java.lang.Integer, object: java.lang.Object | int | bool | float | str, /) -> None: ...
    def finishUpdate(self, container: android.view.ViewGroup, /) -> None: ...
    def getItem(self, arg1: int | java.jint | java.lang.Integer, /) -> Fragment: ...
    def instantiateItem(self, container: android.view.ViewGroup, position: int | java.jint | java.lang.Integer, /) -> java.lang.Object: ...
    def isViewFromObject(self, view: android.view.View, object: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def restoreState(self, state: android.os.Parcelable, loader: java.lang.ClassLoader, /) -> None: ...
    def saveState(self) -> android.os.Parcelable: ...
    def setPrimaryItem(self, container: android.view.ViewGroup, position: int | java.jint | java.lang.Integer, object: java.lang.Object | int | bool | float | str, /) -> None: ...
    def startUpdate(self, container: android.view.ViewGroup, /) -> None: ...

class FragmentStore(java.lang.Object): ...

class FragmentTabHost(android.widget.TabHost, android.widget.TabHost.OnTabChangeListener):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    def addTab(self, tabSpec: android.widget.TabHost.TabSpec, clss: typing.Type[java.lang.Object], args: android.os.Bundle, /) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onRestoreInstanceState(self, state: android.os.Parcelable, /) -> None: ...
    def onSaveInstanceState(self) -> android.os.Parcelable: ...
    def onTabChanged(self, tabId: str | java.lang.String, /) -> None: ...
    def setOnTabChangedListener(self, l: android.widget.TabHost.OnTabChangeListener, /) -> None: ...
    @typing.overload
    def setup(self) -> None: ...
    @typing.overload
    def setup(self, context: android.content.Context, manager: FragmentManager, /) -> None: ...
    @typing.overload
    def setup(self, context: android.content.Context, manager: FragmentManager, containerId: int | java.jint | java.lang.Integer, /) -> None: ...

class FragmentTransaction(java.lang.Object):
    TRANSIT_ENTER_MASK: typing.ClassVar[int] = ...
    TRANSIT_EXIT_MASK: typing.ClassVar[int] = ...
    TRANSIT_UNSET: typing.ClassVar[int] = ...
    TRANSIT_NONE: typing.ClassVar[int] = ...
    TRANSIT_FRAGMENT_OPEN: typing.ClassVar[int] = ...
    TRANSIT_FRAGMENT_CLOSE: typing.ClassVar[int] = ...
    TRANSIT_FRAGMENT_FADE: typing.ClassVar[int] = ...
    def __init__(self) -> None: ...
    @typing.overload
    def add(self, containerViewId: int | java.jint | java.lang.Integer, fragment: Fragment, /) -> FragmentTransaction: ...
    @typing.overload
    def add(self, fragment: Fragment, tag: str | java.lang.String, /) -> FragmentTransaction: ...
    @typing.overload
    def add(self, containerViewId: int | java.jint | java.lang.Integer, fragment: Fragment, tag: str | java.lang.String, /) -> FragmentTransaction: ...
    @typing.overload
    def add(self, containerViewId: int | java.jint | java.lang.Integer, fragmentClass: typing.Type[Fragment], args: android.os.Bundle, /) -> FragmentTransaction: ...
    @typing.overload
    def add(self, fragmentClass: typing.Type[Fragment], args: android.os.Bundle, tag: str | java.lang.String, /) -> FragmentTransaction: ...
    @typing.overload
    def add(self, containerViewId: int | java.jint | java.lang.Integer, fragmentClass: typing.Type[Fragment], args: android.os.Bundle, tag: str | java.lang.String, /) -> FragmentTransaction: ...
    def addSharedElement(self, sharedElement: android.view.View, name: str | java.lang.String, /) -> FragmentTransaction: ...
    def addToBackStack(self, name: str | java.lang.String, /) -> FragmentTransaction: ...
    def attach(self, fragment: Fragment, /) -> FragmentTransaction: ...
    def commit(self) -> int: ...
    def commitAllowingStateLoss(self) -> int: ...
    def commitNow(self) -> None: ...
    def commitNowAllowingStateLoss(self) -> None: ...
    def detach(self, fragment: Fragment, /) -> FragmentTransaction: ...
    def disallowAddToBackStack(self) -> FragmentTransaction: ...
    def hide(self, fragment: Fragment, /) -> FragmentTransaction: ...
    def isAddToBackStackAllowed(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    def remove(self, fragment: Fragment, /) -> FragmentTransaction: ...
    @typing.overload
    def replace(self, containerViewId: int | java.jint | java.lang.Integer, fragment: Fragment, /) -> FragmentTransaction: ...
    @typing.overload
    def replace(self, containerViewId: int | java.jint | java.lang.Integer, fragment: Fragment, tag: str | java.lang.String, /) -> FragmentTransaction: ...
    @typing.overload
    def replace(self, containerViewId: int | java.jint | java.lang.Integer, fragmentClass: typing.Type[Fragment], args: android.os.Bundle, /) -> FragmentTransaction: ...
    @typing.overload
    def replace(self, containerViewId: int | java.jint | java.lang.Integer, fragmentClass: typing.Type[Fragment], args: android.os.Bundle, tag: str | java.lang.String, /) -> FragmentTransaction: ...
    def runOnCommit(self, runnable: java.lang.Runnable, /) -> FragmentTransaction: ...
    def setAllowOptimization(self, allowOptimization: bool | java.jboolean | java.lang.Boolean, /) -> FragmentTransaction: ...
    @typing.overload
    def setBreadCrumbShortTitle(self, res: int | java.jint | java.lang.Integer, /) -> FragmentTransaction: ...
    @typing.overload
    def setBreadCrumbShortTitle(self, text: java.lang.CharSequence, /) -> FragmentTransaction: ...
    @typing.overload
    def setBreadCrumbTitle(self, res: int | java.jint | java.lang.Integer, /) -> FragmentTransaction: ...
    @typing.overload
    def setBreadCrumbTitle(self, text: java.lang.CharSequence, /) -> FragmentTransaction: ...
    @typing.overload
    def setCustomAnimations(self, enter: int | java.jint | java.lang.Integer, exit: int | java.jint | java.lang.Integer, /) -> FragmentTransaction: ...
    @typing.overload
    def setCustomAnimations(self, enter: int | java.jint | java.lang.Integer, exit: int | java.jint | java.lang.Integer, popEnter: int | java.jint | java.lang.Integer, popExit: int | java.jint | java.lang.Integer, /) -> FragmentTransaction: ...
    def setMaxLifecycle(self, fragment: Fragment, state: androidx.lifecycle.Lifecycle.State, /) -> FragmentTransaction: ...
    def setPrimaryNavigationFragment(self, fragment: Fragment, /) -> FragmentTransaction: ...
    def setReorderingAllowed(self, reorderingAllowed: bool | java.jboolean | java.lang.Boolean, /) -> FragmentTransaction: ...
    def setTransition(self, transition: int | java.jint | java.lang.Integer, /) -> FragmentTransaction: ...
    def setTransitionStyle(self, styleRes: int | java.jint | java.lang.Integer, /) -> FragmentTransaction: ...
    def show(self, fragment: Fragment, /) -> FragmentTransaction: ...

class FragmentTransition(java.lang.Object):
    @staticmethod
    def calculateFragments(transaction: BackStackRecord, transitioningFragments: android.util.SparseArray[FragmentTransition.FragmentContainerTransition], isReordered: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def calculatePopFragments(transaction: BackStackRecord, transitioningFragments: android.util.SparseArray[FragmentTransition.FragmentContainerTransition], isReordered: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class FragmentTransitionCompat21(FragmentTransitionImpl):
    def addTarget(self, transitionObj: java.lang.Object | int | bool | float | str, view: android.view.View, /) -> None: ...
    def addTargets(self, transitionObj: java.lang.Object | int | bool | float | str, views: java.util.ArrayList[android.view.View], /) -> None: ...
    def beginDelayedTransition(self, sceneRoot: android.view.ViewGroup, transition: java.lang.Object | int | bool | float | str, /) -> None: ...
    def canHandle(self, transition: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def cloneTransition(self, transition: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def mergeTransitionsInSequence(self, exitTransitionObj: java.lang.Object | int | bool | float | str, enterTransitionObj: java.lang.Object | int | bool | float | str, sharedElementTransitionObj: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def mergeTransitionsTogether(self, transition1: java.lang.Object | int | bool | float | str, transition2: java.lang.Object | int | bool | float | str, transition3: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def removeTarget(self, transitionObj: java.lang.Object | int | bool | float | str, view: android.view.View, /) -> None: ...
    def replaceTargets(self, transitionObj: java.lang.Object | int | bool | float | str, oldTargets: java.util.ArrayList[android.view.View], newTargets: java.util.ArrayList[android.view.View], /) -> None: ...
    def scheduleHideFragmentView(self, exitTransitionObj: java.lang.Object | int | bool | float | str, fragmentView: android.view.View, exitingViews: java.util.ArrayList[android.view.View], /) -> None: ...
    def scheduleRemoveTargets(self, overallTransitionObj: java.lang.Object | int | bool | float | str, enterTransition: java.lang.Object | int | bool | float | str, enteringViews: java.util.ArrayList[android.view.View], exitTransition: java.lang.Object | int | bool | float | str, exitingViews: java.util.ArrayList[android.view.View], sharedElementTransition: java.lang.Object | int | bool | float | str, sharedElementsIn: java.util.ArrayList[android.view.View], /) -> None: ...
    @typing.overload
    def setEpicenter(self, transitionObj: java.lang.Object | int | bool | float | str, epicenter: android.graphics.Rect, /) -> None: ...
    @typing.overload
    def setEpicenter(self, transitionObj: java.lang.Object | int | bool | float | str, view: android.view.View, /) -> None: ...
    def setListenerForTransitionEnd(self, outFragment: Fragment, transition: java.lang.Object | int | bool | float | str, signal: androidx.core.os.CancellationSignal, transitionCompleteRunnable: java.lang.Runnable, /) -> None: ...
    def setSharedElementTargets(self, transitionObj: java.lang.Object | int | bool | float | str, nonExistentView: android.view.View, sharedViews: java.util.ArrayList[android.view.View], /) -> None: ...
    def swapSharedElementTargets(self, sharedElementTransitionObj: java.lang.Object | int | bool | float | str, sharedElementsOut: java.util.ArrayList[android.view.View], sharedElementsIn: java.util.ArrayList[android.view.View], /) -> None: ...
    def wrapTransitionInSet(self, transition: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...

class FragmentTransitionImpl(java.lang.Object):
    def __init__(self) -> None: ...
    def addTarget(self, arg1: java.lang.Object | int | bool | float | str, arg2: android.view.View, /) -> None: ...
    def addTargets(self, arg1: java.lang.Object | int | bool | float | str, arg2: java.util.ArrayList[android.view.View], /) -> None: ...
    def beginDelayedTransition(self, arg1: android.view.ViewGroup, arg2: java.lang.Object | int | bool | float | str, /) -> None: ...
    @staticmethod
    def bfsAddViewChildren(views: java.util.List[android.view.View], startView: android.view.View, /) -> None: ...
    def canHandle(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def cloneTransition(self, arg1: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def getBoundsOnScreen(self, view: android.view.View, epicenter: android.graphics.Rect, /) -> None: ...
    @staticmethod
    def isNullOrEmpty(list: java.util.List, /) -> bool: ...
    def mergeTransitionsInSequence(self, arg1: java.lang.Object | int | bool | float | str, arg2: java.lang.Object | int | bool | float | str, arg3: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def mergeTransitionsTogether(self, arg1: java.lang.Object | int | bool | float | str, arg2: java.lang.Object | int | bool | float | str, arg3: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def removeTarget(self, arg1: java.lang.Object | int | bool | float | str, arg2: android.view.View, /) -> None: ...
    def replaceTargets(self, arg1: java.lang.Object | int | bool | float | str, arg2: java.util.ArrayList[android.view.View], arg3: java.util.ArrayList[android.view.View], /) -> None: ...
    def scheduleHideFragmentView(self, arg1: java.lang.Object | int | bool | float | str, arg2: android.view.View, arg3: java.util.ArrayList[android.view.View], /) -> None: ...
    def scheduleRemoveTargets(self, arg1: java.lang.Object | int | bool | float | str, arg2: java.lang.Object | int | bool | float | str, arg3: java.util.ArrayList[android.view.View], arg4: java.lang.Object | int | bool | float | str, arg5: java.util.ArrayList[android.view.View], arg6: java.lang.Object | int | bool | float | str, arg7: java.util.ArrayList[android.view.View], /) -> None: ...
    @typing.overload
    def setEpicenter(self, arg1: java.lang.Object | int | bool | float | str, arg2: android.graphics.Rect, /) -> None: ...
    @typing.overload
    def setEpicenter(self, arg1: java.lang.Object | int | bool | float | str, arg2: android.view.View, /) -> None: ...
    def setListenerForTransitionEnd(self, outFragment: Fragment, transition: java.lang.Object | int | bool | float | str, signal: androidx.core.os.CancellationSignal, transitionCompleteRunnable: java.lang.Runnable, /) -> None: ...
    def setSharedElementTargets(self, arg1: java.lang.Object | int | bool | float | str, arg2: android.view.View, arg3: java.util.ArrayList[android.view.View], /) -> None: ...
    def swapSharedElementTargets(self, arg1: java.lang.Object | int | bool | float | str, arg2: java.util.ArrayList[android.view.View], arg3: java.util.ArrayList[android.view.View], /) -> None: ...
    def wrapTransitionInSet(self, arg1: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...

class FragmentViewLifecycleOwner(androidx.savedstate.SavedStateRegistryOwner, androidx.lifecycle.ViewModelStoreOwner):
    def getLifecycle(self) -> androidx.lifecycle.Lifecycle: ...
    def getSavedStateRegistry(self) -> androidx.savedstate.SavedStateRegistry: ...
    def getViewModelStore(self) -> androidx.lifecycle.ViewModelStore: ...

class ListFragment(Fragment):
    def __init__(self) -> None: ...
    def getListAdapter(self) -> android.widget.ListAdapter: ...
    def getListView(self) -> android.widget.ListView: ...
    def getSelectedItemId(self) -> int: ...
    def getSelectedItemPosition(self) -> int: ...
    def onCreateView(self, inflater: android.view.LayoutInflater, container: android.view.ViewGroup, savedInstanceState: android.os.Bundle, /) -> android.view.View: ...
    def onDestroyView(self) -> None: ...
    def onListItemClick(self, l: android.widget.ListView, v: android.view.View, position: int | java.jint | java.lang.Integer, id: int | java.jlong | java.lang.Long, /) -> None: ...
    def onViewCreated(self, view: android.view.View, savedInstanceState: android.os.Bundle, /) -> None: ...
    def requireListAdapter(self) -> android.widget.ListAdapter: ...
    def setEmptyText(self, text: java.lang.CharSequence, /) -> None: ...
    def setListAdapter(self, adapter: android.widget.ListAdapter, /) -> None: ...
    def setListShown(self, shown: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setListShownNoAnimation(self, shown: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setSelection(self, position: int | java.jint | java.lang.Integer, /) -> None: ...

class LogWriter(java.io.Writer):
    def close(self) -> None: ...
    def flush(self) -> None: ...
    def write(self, buf: java.chaquopy.JavaArrayJChar, offset: int | java.jint | java.lang.Integer, count: int | java.jint | java.lang.Integer, /) -> None: ...

class SpecialEffectsController(java.lang.Object):
    def getContainer(self) -> android.view.ViewGroup: ...

class SpecialEffectsControllerFactory(java.lang.Object):
    def createController(self, arg1: android.view.ViewGroup, /) -> SpecialEffectsController: ...

class SuperNotCalledException(android.util.AndroidRuntimeException):
    def __init__(self, msg: str | java.lang.String, /) -> None: ...
