import typing

import android.content
import android.content.res
import androidx.startup
import java
import java.io
import java.lang
import java.lang.annotation
import java.util
import java.util.concurrent

class DeviceProfileWriter(java.lang.Object):
    def __init__(self, assetManager: android.content.res.AssetManager, executor: java.util.concurrent.Executor, diagnosticsCallback: ProfileInstaller.DiagnosticsCallback, apkName: str | java.lang.String, profileSourceLocation: str | java.lang.String, curProfile: java.io.File, refProfile: java.io.File, /) -> None: ...
    def copyProfileOrRead(self, skipStrategy: DeviceProfileWriter.SkipStrategy, /) -> DeviceProfileWriter: ...
    def deviceAllowsProfileInstallerAotWrites(self) -> bool: ...
    def transcodeIfNeeded(self) -> DeviceProfileWriter: ...
    def writeIfNeeded(self, skipStrategy: DeviceProfileWriter.SkipStrategy, /) -> None: ...

    class ExistingProfileState(java.lang.Object):
        def getCurLength(self) -> int: ...
        def getRefLength(self) -> int: ...
        def hasCurFile(self) -> bool: ...
        def hasRefFile(self) -> bool: ...

    class SkipStrategy(java.lang.Object):
        def shouldSkip(self, arg1: int | java.jlong | java.lang.Long, arg2: DeviceProfileWriter.ExistingProfileState, /) -> bool: ...

class DexProfileData(java.lang.Object): ...

class Encoding(java.lang.Object): ...

class ProfileInstallReceiver(android.content.BroadcastReceiver):
    ACTION_INSTALL_PROFILE: typing.ClassVar[str] = ...
    def __init__(self) -> None: ...
    def onReceive(self, context: android.content.Context, intent: android.content.Intent, /) -> None: ...

class ProfileInstaller(java.lang.Object):
    DIAGNOSTIC_CURRENT_PROFILE_EXISTS: typing.ClassVar[int] = ...
    DIAGNOSTIC_CURRENT_PROFILE_DOES_NOT_EXIST: typing.ClassVar[int] = ...
    DIAGNOSTIC_REF_PROFILE_EXISTS: typing.ClassVar[int] = ...
    DIAGNOSTIC_REF_PROFILE_DOES_NOT_EXIST: typing.ClassVar[int] = ...
    RESULT_INSTALL_SUCCESS: typing.ClassVar[int] = ...
    RESULT_ALREADY_INSTALLED: typing.ClassVar[int] = ...
    RESULT_UNSUPPORTED_ART_VERSION: typing.ClassVar[int] = ...
    RESULT_NOT_WRITABLE: typing.ClassVar[int] = ...
    RESULT_DESIRED_FORMAT_UNSUPPORTED: typing.ClassVar[int] = ...
    RESULT_BASELINE_PROFILE_NOT_FOUND: typing.ClassVar[int] = ...
    RESULT_IO_EXCEPTION: typing.ClassVar[int] = ...
    RESULT_PARSE_EXCEPTION: typing.ClassVar[int] = ...
    @typing.overload
    @staticmethod
    def writeProfile(context: android.content.Context, /) -> None: ...
    @typing.overload
    @staticmethod
    def writeProfile(context: android.content.Context, executor: java.util.concurrent.Executor, diagnostics: ProfileInstaller.DiagnosticsCallback, /) -> None: ...

    class ResultCode(java.lang.annotation.Annotation): ...

    class DiagnosticCode(java.lang.annotation.Annotation): ...

    class DiagnosticsCallback(java.lang.Object):
        def onDiagnosticReceived(self, arg1: int | java.jint | java.lang.Integer, arg2: java.lang.Object | int | bool | float | str, /) -> None: ...
        def onResultReceived(self, arg1: int | java.jint | java.lang.Integer, arg2: java.lang.Object | int | bool | float | str, /) -> None: ...

class ProfileInstallerInitializer(androidx.startup.Initializer[ProfileInstallerInitializer.Result]):
    def __init__(self) -> None: ...
    def create(self, context: android.content.Context, /) -> ProfileInstallerInitializer.Result: ...
    def dependencies(self) -> java.util.List[typing.Type[androidx.startup.Initializer[java.lang.Object]]]: ...

    class Result(java.lang.Object):
        def __init__(self) -> None: ...

class ProfileTranscoder(java.lang.Object): ...

class ProfileVersion(java.lang.Object): ...
