import typing

import android.app
import android.content
import android.content.res
import android.view
import java
import java.chaquopy
import java.lang

class Blend(java.lang.Object):
    @staticmethod
    def blendCam16Ucs(from_: int | java.jint | java.lang.Integer, to: int | java.jint | java.lang.Integer, amount: float | java.jfloat | java.lang.Float, /) -> int: ...
    @staticmethod
    def blendHctHue(from_: int | java.jint | java.lang.Integer, to: int | java.jint | java.lang.Integer, amount: float | java.jfloat | java.lang.Float, /) -> int: ...
    @staticmethod
    def harmonize(designColor: int | java.jint | java.lang.Integer, sourceColor: int | java.jint | java.lang.Integer, /) -> int: ...

class Cam16(java.lang.Object):
    @staticmethod
    def fromInt(argb: int | java.jint | java.lang.Integer, /) -> Cam16: ...
    @staticmethod
    def fromUcs(jstar: float | java.jfloat | java.lang.Float, astar: float | java.jfloat | java.lang.Float, bstar: float | java.jfloat | java.lang.Float, /) -> Cam16: ...
    @staticmethod
    def fromUcsInViewingConditions(jstar: float | java.jfloat | java.lang.Float, astar: float | java.jfloat | java.lang.Float, bstar: float | java.jfloat | java.lang.Float, viewingConditions: ViewingConditions, /) -> Cam16: ...
    def getAStar(self) -> float: ...
    def getBStar(self) -> float: ...
    def getChroma(self) -> float: ...
    def getHue(self) -> float: ...
    def getInt(self) -> int: ...
    def getJ(self) -> float: ...
    def getJStar(self) -> float: ...
    def getM(self) -> float: ...
    def getQ(self) -> float: ...
    def getS(self) -> float: ...

class ColorResourcesLoaderCreator(java.lang.Object): ...

class ColorResourcesTableCreator(java.lang.Object): ...

class ColorRoles(java.lang.Object):
    def getAccent(self) -> int: ...
    def getAccentContainer(self) -> int: ...
    def getOnAccent(self) -> int: ...
    def getOnAccentContainer(self) -> int: ...

class ColorUtils(java.lang.Object):
    @staticmethod
    def blueFromInt(argb: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def delinearized(rgb: float | java.jfloat | java.lang.Float, /) -> float: ...
    @staticmethod
    def greenFromInt(argb: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def hexFromInt(argb: int | java.jint | java.lang.Integer, /) -> str: ...
    @staticmethod
    def intFromLab(l: float | java.jdouble | java.lang.Double, a: float | java.jdouble | java.lang.Double, b: float | java.jdouble | java.lang.Double, /) -> int: ...
    @staticmethod
    def intFromLstar(lstar: float | java.jfloat | java.lang.Float, /) -> int: ...
    @staticmethod
    def intFromRgb(r: int | java.jint | java.lang.Integer, g: int | java.jint | java.lang.Integer, b: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def intFromXyz(xyz: java.chaquopy.JavaArrayJFloat, /) -> int: ...
    @staticmethod
    def intFromXyzComponents(x: float | java.jfloat | java.lang.Float, y: float | java.jfloat | java.lang.Float, z: float | java.jfloat | java.lang.Float, /) -> int: ...
    @staticmethod
    def labFromInt(argb: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJDouble: ...
    @staticmethod
    def linearized(rgb: float | java.jfloat | java.lang.Float, /) -> float: ...
    @staticmethod
    def lstarFromInt(argb: int | java.jint | java.lang.Integer, /) -> float: ...
    @staticmethod
    def redFromInt(argb: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def whitePointD65() -> java.chaquopy.JavaArrayJFloat: ...
    @staticmethod
    def xyzFromInt(argb: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJFloat: ...
    @staticmethod
    def yFromLstar(lstar: float | java.jfloat | java.lang.Float, /) -> float: ...

class DynamicColors(java.lang.Object):
    @typing.overload
    @staticmethod
    def applyIfAvailable(activity: android.app.Activity, /) -> None: ...
    @typing.overload
    @staticmethod
    def applyIfAvailable(activity: android.app.Activity, theme: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    @staticmethod
    def applyIfAvailable(activity: android.app.Activity, precondition: DynamicColors.Precondition, /) -> None: ...
    @typing.overload
    @staticmethod
    def applyToActivitiesIfAvailable(application: android.app.Application, /) -> None: ...
    @typing.overload
    @staticmethod
    def applyToActivitiesIfAvailable(application: android.app.Application, theme: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    @staticmethod
    def applyToActivitiesIfAvailable(application: android.app.Application, precondition: DynamicColors.Precondition, /) -> None: ...
    @typing.overload
    @staticmethod
    def applyToActivitiesIfAvailable(application: android.app.Application, dynamicColorsOptions: DynamicColorsOptions, /) -> None: ...
    @typing.overload
    @staticmethod
    def applyToActivitiesIfAvailable(application: android.app.Application, theme: int | java.jint | java.lang.Integer, precondition: DynamicColors.Precondition, /) -> None: ...
    @typing.overload
    @staticmethod
    def applyToActivityIfAvailable(activity: android.app.Activity, /) -> None: ...
    @typing.overload
    @staticmethod
    def applyToActivityIfAvailable(activity: android.app.Activity, dynamicColorsOptions: DynamicColorsOptions, /) -> None: ...
    @staticmethod
    def isDynamicColorAvailable() -> bool: ...
    @typing.overload
    @staticmethod
    def wrapContextIfAvailable(originalContext: android.content.Context, /) -> android.content.Context: ...
    @typing.overload
    @staticmethod
    def wrapContextIfAvailable(originalContext: android.content.Context, theme: int | java.jint | java.lang.Integer, /) -> android.content.Context: ...

    class OnAppliedCallback(java.lang.Object):
        def onApplied(self, arg1: android.app.Activity, /) -> None: ...

    class Precondition(java.lang.Object):
        def shouldApplyDynamicColors(self, arg1: android.app.Activity, arg2: int | java.jint | java.lang.Integer, /) -> bool: ...

class DynamicColorsOptions(java.lang.Object):
    def getOnAppliedCallback(self) -> DynamicColors.OnAppliedCallback: ...
    def getPrecondition(self) -> DynamicColors.Precondition: ...
    def getThemeOverlay(self) -> int: ...

    class Builder(java.lang.Object):
        def __init__(self) -> None: ...
        def build(self) -> DynamicColorsOptions: ...
        def setOnAppliedCallback(self, onAppliedCallback: DynamicColors.OnAppliedCallback, /) -> DynamicColorsOptions.Builder: ...
        def setPrecondition(self, precondition: DynamicColors.Precondition, /) -> DynamicColorsOptions.Builder: ...
        def setThemeOverlay(self, themeOverlay: int | java.jint | java.lang.Integer, /) -> DynamicColorsOptions.Builder: ...

class HarmonizedColorAttributes(java.lang.Object):
    @typing.overload
    @staticmethod
    def create(attributes: java.chaquopy.JavaArrayJInt, /) -> HarmonizedColorAttributes: ...
    @typing.overload
    @staticmethod
    def create(attributes: java.chaquopy.JavaArrayJInt, themeOverlay: int | java.jint | java.lang.Integer, /) -> HarmonizedColorAttributes: ...
    @staticmethod
    def createMaterialDefaults() -> HarmonizedColorAttributes: ...
    def getAttributes(self) -> java.chaquopy.JavaArrayJInt: ...
    def getThemeOverlay(self) -> int: ...

class HarmonizedColors(java.lang.Object):
    @staticmethod
    def applyToContextIfAvailable(context: android.content.Context, options: HarmonizedColorsOptions, /) -> None: ...
    @staticmethod
    def isHarmonizedColorAvailable() -> bool: ...
    @staticmethod
    def wrapContextIfAvailable(context: android.content.Context, options: HarmonizedColorsOptions, /) -> android.content.Context: ...

class HarmonizedColorsOptions(java.lang.Object):
    @staticmethod
    def createMaterialDefaults() -> HarmonizedColorsOptions: ...
    def getColorAttributeToHarmonizeWith(self) -> int: ...
    def getColorAttributes(self) -> HarmonizedColorAttributes: ...
    def getColorResourceIds(self) -> java.chaquopy.JavaArrayJInt: ...

    class Builder(java.lang.Object):
        def __init__(self) -> None: ...
        def build(self) -> HarmonizedColorsOptions: ...
        def setColorAttributeToHarmonizeWith(self, colorAttributeToHarmonizeWith: int | java.jint | java.lang.Integer, /) -> HarmonizedColorsOptions.Builder: ...
        def setColorAttributes(self, colorAttributes: HarmonizedColorAttributes, /) -> HarmonizedColorsOptions.Builder: ...
        def setColorResourceIds(self, colorResourceIds: java.chaquopy.JavaArrayJInt, /) -> HarmonizedColorsOptions.Builder: ...

class Hct(java.lang.Object):
    @staticmethod
    def fromInt(argb: int | java.jint | java.lang.Integer, /) -> Hct: ...
    @staticmethod
    def from_(hue: float | java.jfloat | java.lang.Float, chroma: float | java.jfloat | java.lang.Float, tone: float | java.jfloat | java.lang.Float, /) -> Hct: ...
    def getChroma(self) -> float: ...
    def getHue(self) -> float: ...
    def getTone(self) -> float: ...
    def setChroma(self, newChroma: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setHue(self, newHue: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTone(self, newTone: float | java.jfloat | java.lang.Float, /) -> None: ...
    def toInt(self) -> int: ...

class MaterialColors(java.lang.Object):
    ALPHA_FULL: typing.ClassVar[float] = ...
    ALPHA_MEDIUM: typing.ClassVar[float] = ...
    ALPHA_DISABLED: typing.ClassVar[float] = ...
    ALPHA_LOW: typing.ClassVar[float] = ...
    ALPHA_DISABLED_LOW: typing.ClassVar[float] = ...
    @staticmethod
    def compositeARGBWithAlpha(originalARGB: int | java.jint | java.lang.Integer, alpha: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getColor(view: android.view.View, colorAttributeResId: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getColor(context: android.content.Context, colorAttributeResId: int | java.jint | java.lang.Integer, defaultValue: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getColor(context: android.content.Context, colorAttributeResId: int | java.jint | java.lang.Integer, errorMessageComponent: str | java.lang.String, /) -> int: ...
    @typing.overload
    @staticmethod
    def getColor(view: android.view.View, colorAttributeResId: int | java.jint | java.lang.Integer, defaultValue: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getColorRoles(color: int | java.jint | java.lang.Integer, isLightTheme: bool | java.jboolean | java.lang.Boolean, /) -> ColorRoles: ...
    @typing.overload
    @staticmethod
    def getColorRoles(context: android.content.Context, color: int | java.jint | java.lang.Integer, /) -> ColorRoles: ...
    @staticmethod
    def getColorStateList(context: android.content.Context, colorAttributeResId: int | java.jint | java.lang.Integer, defaultValue: android.content.res.ColorStateList, /) -> android.content.res.ColorStateList: ...
    @staticmethod
    def harmonize(colorToHarmonize: int | java.jint | java.lang.Integer, colorToHarmonizeWith: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def harmonizeWithPrimary(context: android.content.Context, colorToHarmonize: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def isColorLight(color: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    @staticmethod
    def layer(backgroundColor: int | java.jint | java.lang.Integer, overlayColor: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def layer(backgroundColor: int | java.jint | java.lang.Integer, overlayColor: int | java.jint | java.lang.Integer, overlayAlpha: float | java.jfloat | java.lang.Float, /) -> int: ...
    @typing.overload
    @staticmethod
    def layer(view: android.view.View, backgroundColorAttributeResId: int | java.jint | java.lang.Integer, overlayColorAttributeResId: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def layer(view: android.view.View, backgroundColorAttributeResId: int | java.jint | java.lang.Integer, overlayColorAttributeResId: int | java.jint | java.lang.Integer, overlayAlpha: float | java.jfloat | java.lang.Float, /) -> int: ...

class MathUtils(java.lang.Object):
    @staticmethod
    def differenceDegrees(a: float | java.jfloat | java.lang.Float, b: float | java.jfloat | java.lang.Float, /) -> float: ...
    @staticmethod
    def lerp(start: float | java.jfloat | java.lang.Float, stop: float | java.jfloat | java.lang.Float, amount: float | java.jfloat | java.lang.Float, /) -> float: ...
    @typing.overload
    @staticmethod
    def sanitizeDegrees(degrees: float | java.jfloat | java.lang.Float, /) -> float: ...
    @typing.overload
    @staticmethod
    def sanitizeDegrees(degrees: int | java.jint | java.lang.Integer, /) -> int: ...

class ThemeUtils(java.lang.Object): ...

class ViewingConditions(java.lang.Object):
    DEFAULT: typing.ClassVar[ViewingConditions] = ...
    def getAw(self) -> float: ...
    def getFlRoot(self) -> float: ...
    def getN(self) -> float: ...
    def getNbb(self) -> float: ...
    def getRgbD(self) -> java.chaquopy.JavaArrayJFloat: ...
