import typing

import android.content
import android.os
import android.view
import java.io
import java.lang
import org.osmdroid.tileprovider

class CloudmadeUtil(java.lang.Object):
    DEBUGMODE: typing.ClassVar[bool] = ...
    def __init__(self) -> None: ...
    @staticmethod
    def getCloudmadeKey() -> str: ...
    @staticmethod
    def getCloudmadeToken() -> str: ...
    @staticmethod
    def retrieveCloudmadeKey(aContext: android.content.Context, /) -> None: ...
    @staticmethod
    def setCloudmadeKey(key: str | java.lang.String, /) -> None: ...

class ManifestUtil(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def retrieveKey(aContext: android.content.Context, aKey: str | java.lang.String, /) -> str: ...

class SimpleInvalidationHandler(android.os.Handler):
    def __init__(self, pView: android.view.View, /) -> None: ...
    def handleMessage(self, msg: android.os.Message, /) -> None: ...

class SimpleRegisterReceiver(org.osmdroid.tileprovider.IRegisterReceiver):
    def __init__(self, pContext: android.content.Context, /) -> None: ...
    def registerReceiver(self, aReceiver: android.content.BroadcastReceiver, aFilter: android.content.IntentFilter, /) -> android.content.Intent: ...
    def unregisterReceiver(self, aReceiver: android.content.BroadcastReceiver, /) -> None: ...

class StreamUtils(java.lang.Object):
    IO_BUFFER_SIZE: typing.ClassVar[int] = ...
    @staticmethod
    def closeStream(stream: java.io.Closeable, /) -> None: ...
    @staticmethod
    def copy(in_: java.io.InputStream, out: java.io.OutputStream, /) -> int: ...
