import typing

import android.location
import android.os
import androidx.core.os
import androidx.core.util
import java
import java.lang
import java.lang.annotation
import java.util.concurrent

class GnssStatusCompat(java.lang.Object):
    CONSTELLATION_UNKNOWN: typing.ClassVar[int] = ...
    CONSTELLATION_GPS: typing.ClassVar[int] = ...
    CONSTELLATION_SBAS: typing.ClassVar[int] = ...
    CONSTELLATION_GLONASS: typing.ClassVar[int] = ...
    CONSTELLATION_QZSS: typing.ClassVar[int] = ...
    CONSTELLATION_BEIDOU: typing.ClassVar[int] = ...
    CONSTELLATION_GALILEO: typing.ClassVar[int] = ...
    CONSTELLATION_IRNSS: typing.ClassVar[int] = ...
    def getAzimuthDegrees(self, arg1: int | java.jint | java.lang.Integer, /) -> float: ...
    def getBasebandCn0DbHz(self, arg1: int | java.jint | java.lang.Integer, /) -> float: ...
    def getCarrierFrequencyHz(self, arg1: int | java.jint | java.lang.Integer, /) -> float: ...
    def getCn0DbHz(self, arg1: int | java.jint | java.lang.Integer, /) -> float: ...
    def getConstellationType(self, arg1: int | java.jint | java.lang.Integer, /) -> int: ...
    def getElevationDegrees(self, arg1: int | java.jint | java.lang.Integer, /) -> float: ...
    def getSatelliteCount(self) -> int: ...
    def getSvid(self, arg1: int | java.jint | java.lang.Integer, /) -> int: ...
    def hasAlmanacData(self, arg1: int | java.jint | java.lang.Integer, /) -> bool: ...
    def hasBasebandCn0DbHz(self, arg1: int | java.jint | java.lang.Integer, /) -> bool: ...
    def hasCarrierFrequencyHz(self, arg1: int | java.jint | java.lang.Integer, /) -> bool: ...
    def hasEphemerisData(self, arg1: int | java.jint | java.lang.Integer, /) -> bool: ...
    def usedInFix(self, arg1: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    @staticmethod
    def wrap(gnssStatus: android.location.GnssStatus, /) -> GnssStatusCompat: ...
    @typing.overload
    @staticmethod
    def wrap(gpsStatus: android.location.GpsStatus, /) -> GnssStatusCompat: ...

    class Callback(java.lang.Object):
        def __init__(self) -> None: ...
        def onFirstFix(self, ttffMillis: int | java.jint | java.lang.Integer, /) -> None: ...
        def onSatelliteStatusChanged(self, status: GnssStatusCompat, /) -> None: ...
        def onStarted(self) -> None: ...
        def onStopped(self) -> None: ...

    class ConstellationType(java.lang.annotation.Annotation): ...

class GnssStatusWrapper(GnssStatusCompat):
    def equals(self, o: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getAzimuthDegrees(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> float: ...
    def getBasebandCn0DbHz(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> float: ...
    def getCarrierFrequencyHz(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> float: ...
    def getCn0DbHz(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> float: ...
    def getConstellationType(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> int: ...
    def getElevationDegrees(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> float: ...
    def getSatelliteCount(self) -> int: ...
    def getSvid(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> int: ...
    def hasAlmanacData(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> bool: ...
    def hasBasebandCn0DbHz(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> bool: ...
    def hasCarrierFrequencyHz(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> bool: ...
    def hasEphemerisData(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> bool: ...
    def hashCode(self) -> int: ...
    def usedInFix(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> bool: ...

class GpsStatusWrapper(GnssStatusCompat):
    def equals(self, o: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getAzimuthDegrees(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> float: ...
    def getBasebandCn0DbHz(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> float: ...
    def getCarrierFrequencyHz(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> float: ...
    def getCn0DbHz(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> float: ...
    def getConstellationType(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> int: ...
    def getElevationDegrees(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> float: ...
    def getSatelliteCount(self) -> int: ...
    def getSvid(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> int: ...
    def hasAlmanacData(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> bool: ...
    def hasBasebandCn0DbHz(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> bool: ...
    def hasCarrierFrequencyHz(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> bool: ...
    def hasEphemerisData(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> bool: ...
    def hashCode(self) -> int: ...
    def usedInFix(self, satelliteIndex: int | java.jint | java.lang.Integer, /) -> bool: ...

class LocationCompat(java.lang.Object):
    EXTRA_IS_MOCK: typing.ClassVar[str] = ...
    EXTRA_VERTICAL_ACCURACY: typing.ClassVar[str] = ...
    EXTRA_SPEED_ACCURACY: typing.ClassVar[str] = ...
    EXTRA_BEARING_ACCURACY: typing.ClassVar[str] = ...
    @staticmethod
    def getBearingAccuracyDegrees(location: android.location.Location, /) -> float: ...
    @staticmethod
    def getElapsedRealtimeMillis(location: android.location.Location, /) -> int: ...
    @staticmethod
    def getElapsedRealtimeNanos(location: android.location.Location, /) -> int: ...
    @staticmethod
    def getSpeedAccuracyMetersPerSecond(location: android.location.Location, /) -> float: ...
    @staticmethod
    def getVerticalAccuracyMeters(location: android.location.Location, /) -> float: ...
    @staticmethod
    def hasBearingAccuracy(location: android.location.Location, /) -> bool: ...
    @staticmethod
    def hasSpeedAccuracy(location: android.location.Location, /) -> bool: ...
    @staticmethod
    def hasVerticalAccuracy(location: android.location.Location, /) -> bool: ...
    @staticmethod
    def isMock(location: android.location.Location, /) -> bool: ...
    @staticmethod
    def setBearingAccuracyDegrees(location: android.location.Location, bearingAccuracyD: float | java.jfloat | java.lang.Float, /) -> None: ...
    @staticmethod
    def setMock(location: android.location.Location, mock: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def setSpeedAccuracyMetersPerSecond(location: android.location.Location, speedAccuracyMps: float | java.jfloat | java.lang.Float, /) -> None: ...
    @staticmethod
    def setVerticalAccuracyMeters(location: android.location.Location, verticalAccuracyM: float | java.jfloat | java.lang.Float, /) -> None: ...

class LocationListenerCompat(android.location.LocationListener):
    def onProviderDisabled(self, provider: str | java.lang.String, /) -> None: ...
    def onProviderEnabled(self, provider: str | java.lang.String, /) -> None: ...
    def onStatusChanged(self, provider: str | java.lang.String, status: int | java.jint | java.lang.Integer, extras: android.os.Bundle, /) -> None: ...

class LocationManagerCompat(java.lang.Object):
    @staticmethod
    def getCurrentLocation(locationManager: android.location.LocationManager, provider: str | java.lang.String, cancellationSignal: androidx.core.os.CancellationSignal, executor: java.util.concurrent.Executor, consumer: androidx.core.util.Consumer[android.location.Location], /) -> None: ...
    @staticmethod
    def getGnssHardwareModelName(locationManager: android.location.LocationManager, /) -> str: ...
    @staticmethod
    def getGnssYearOfHardware(locationManager: android.location.LocationManager, /) -> int: ...
    @staticmethod
    def hasProvider(locationManager: android.location.LocationManager, provider: str | java.lang.String, /) -> bool: ...
    @staticmethod
    def isLocationEnabled(locationManager: android.location.LocationManager, /) -> bool: ...
    @typing.overload
    @staticmethod
    def registerGnssStatusCallback(locationManager: android.location.LocationManager, callback: GnssStatusCompat.Callback, handler: android.os.Handler, /) -> bool: ...
    @typing.overload
    @staticmethod
    def registerGnssStatusCallback(locationManager: android.location.LocationManager, executor: java.util.concurrent.Executor, callback: GnssStatusCompat.Callback, /) -> bool: ...
    @staticmethod
    def removeUpdates(locationManager: android.location.LocationManager, listener: LocationListenerCompat, /) -> None: ...
    @typing.overload
    @staticmethod
    def requestLocationUpdates(locationManager: android.location.LocationManager, provider: str | java.lang.String, locationRequest: LocationRequestCompat, listener: LocationListenerCompat, looper: android.os.Looper, /) -> None: ...
    @typing.overload
    @staticmethod
    def requestLocationUpdates(locationManager: android.location.LocationManager, provider: str | java.lang.String, locationRequest: LocationRequestCompat, executor: java.util.concurrent.Executor, listener: LocationListenerCompat, /) -> None: ...
    @staticmethod
    def unregisterGnssStatusCallback(locationManager: android.location.LocationManager, callback: GnssStatusCompat.Callback, /) -> None: ...

class LocationRequestCompat(java.lang.Object):
    PASSIVE_INTERVAL: typing.ClassVar[int] = ...
    QUALITY_HIGH_ACCURACY: typing.ClassVar[int] = ...
    QUALITY_BALANCED_POWER_ACCURACY: typing.ClassVar[int] = ...
    QUALITY_LOW_POWER: typing.ClassVar[int] = ...
    def equals(self, o: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getDurationMillis(self) -> int: ...
    def getIntervalMillis(self) -> int: ...
    def getMaxUpdateDelayMillis(self) -> int: ...
    def getMaxUpdates(self) -> int: ...
    def getMinUpdateDistanceMeters(self) -> float: ...
    def getMinUpdateIntervalMillis(self) -> int: ...
    def getQuality(self) -> int: ...
    def hashCode(self) -> int: ...
    @typing.overload
    def toLocationRequest(self) -> android.location.LocationRequest: ...
    @typing.overload
    def toLocationRequest(self, provider: str | java.lang.String, /) -> android.location.LocationRequest: ...
    def toString(self) -> str: ...

    class Builder(java.lang.Object):
        @typing.overload
        def __init__(self, intervalMillis: int | java.jlong | java.lang.Long, /) -> None: ...
        @typing.overload
        def __init__(self, locationRequest: LocationRequestCompat, /) -> None: ...
        def build(self) -> LocationRequestCompat: ...
        def clearMinUpdateIntervalMillis(self) -> LocationRequestCompat.Builder: ...
        def setDurationMillis(self, durationMillis: int | java.jlong | java.lang.Long, /) -> LocationRequestCompat.Builder: ...
        def setIntervalMillis(self, intervalMillis: int | java.jlong | java.lang.Long, /) -> LocationRequestCompat.Builder: ...
        def setMaxUpdateDelayMillis(self, maxUpdateDelayMillis: int | java.jlong | java.lang.Long, /) -> LocationRequestCompat.Builder: ...
        def setMaxUpdates(self, maxUpdates: int | java.jint | java.lang.Integer, /) -> LocationRequestCompat.Builder: ...
        def setMinUpdateDistanceMeters(self, minUpdateDistanceMeters: float | java.jfloat | java.lang.Float, /) -> LocationRequestCompat.Builder: ...
        def setMinUpdateIntervalMillis(self, minUpdateIntervalMillis: int | java.jlong | java.lang.Long, /) -> LocationRequestCompat.Builder: ...
        def setQuality(self, quality: int | java.jint | java.lang.Integer, /) -> LocationRequestCompat.Builder: ...

    class Quality(java.lang.annotation.Annotation): ...
