import typing

import java
import java.chaquopy
import java.io
import java.lang
import java.net
import java.nio.charset
import java.util
import kotlin
import kotlin.collections
import kotlin.jvm.functions
import kotlin.sequences

class AccessDeniedException(FileSystemException):
    def __init__(self, file: java.io.File, other: java.io.File, reason: str | java.lang.String, /) -> None: ...

class ByteStreamsKt(java.lang.Object):
    @staticmethod
    def copyTo(receiver: java.io.InputStream, out: java.io.OutputStream, bufferSize: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def iterator(receiver: java.io.BufferedInputStream, /) -> kotlin.collections.ByteIterator: ...
    @typing.overload
    @staticmethod
    def readBytes(receiver: java.io.InputStream, /) -> java.chaquopy.JavaArrayJByte: ...
    @typing.overload
    @staticmethod
    def readBytes(receiver: java.io.InputStream, estimatedSize: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJByte: ...

class CloseableKt(java.lang.Object):
    @staticmethod
    def closeFinally(receiver: java.io.Closeable, cause: java.lang.Throwable, /) -> None: ...

class ConsoleKt(java.lang.Object):
    @typing.overload
    @staticmethod
    def readLine() -> str: ...
    @typing.overload
    @staticmethod
    def readLine(inputStream: java.io.InputStream, decoder: java.nio.charset.CharsetDecoder, /) -> str: ...

class ConstantsKt(java.lang.Object):
    DEFAULT_BUFFER_SIZE: typing.ClassVar[int] = ...
    DEFAULT_BLOCK_SIZE: typing.ClassVar[int] = ...
    MINIMUM_BLOCK_SIZE: typing.ClassVar[int] = ...

class ExceptionsKt(java.lang.Object): ...

class FileAlreadyExistsException(FileSystemException):
    def __init__(self, file: java.io.File, other: java.io.File, reason: str | java.lang.String, /) -> None: ...

class FilePathComponents(java.lang.Object):
    def __init__(self, root: java.io.File, segments: java.util.List[java.io.File], /) -> None: ...
    def component1(self) -> java.io.File: ...
    def component2(self) -> java.util.List[java.io.File]: ...
    def copy(self, root: java.io.File, segments: java.util.List[java.io.File], /) -> FilePathComponents: ...
    def equals(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getRoot(self) -> java.io.File: ...
    def getRootName(self) -> str: ...
    def getSegments(self) -> java.util.List[java.io.File]: ...
    def getSize(self) -> int: ...
    def hashCode(self) -> int: ...
    def isRooted(self) -> bool: ...
    def subPath(self, beginIndex: int | java.jint | java.lang.Integer, endIndex: int | java.jint | java.lang.Integer, /) -> java.io.File: ...
    def toString(self) -> str: ...

class FileSystemException(java.io.IOException):
    def __init__(self, file: java.io.File, other: java.io.File, reason: str | java.lang.String, /) -> None: ...
    def getFile(self) -> java.io.File: ...
    def getOther(self) -> java.io.File: ...
    def getReason(self) -> str: ...

class FileTreeWalk(kotlin.sequences.Sequence[java.io.File]):
    def __init__(self, start: java.io.File, direction: FileWalkDirection, /) -> None: ...
    def iterator(self) -> java.util.Iterator[java.io.File]: ...
    def maxDepth(self, depth: int | java.jint | java.lang.Integer, /) -> FileTreeWalk: ...
    def onEnter(self, function: kotlin.jvm.functions.Function1[java.io.File, java.lang.Boolean], /) -> FileTreeWalk: ...
    def onFail(self, function: kotlin.jvm.functions.Function2[java.io.File, java.io.IOException, kotlin.Unit], /) -> FileTreeWalk: ...
    def onLeave(self, function: kotlin.jvm.functions.Function1[java.io.File, kotlin.Unit], /) -> FileTreeWalk: ...

class FileWalkDirection(java.lang.Enum[FileWalkDirection]):
    TOP_DOWN: typing.ClassVar[FileWalkDirection] = ...
    BOTTOM_UP: typing.ClassVar[FileWalkDirection] = ...
    @staticmethod
    def valueOf(arg1: str | java.lang.String, /) -> FileWalkDirection: ...
    @staticmethod
    def values() -> java.chaquopy.JavaArray[FileWalkDirection]: ...

class FilesKt(FilesKt__UtilsKt): ...

class FilesKt__FilePathComponentsKt(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def getRoot(receiver: java.io.File, /) -> java.io.File: ...
    @staticmethod
    def getRootName(receiver: java.io.File, /) -> str: ...
    @staticmethod
    def isRooted(receiver: java.io.File, /) -> bool: ...
    @staticmethod
    def subPath(receiver: java.io.File, beginIndex: int | java.jint | java.lang.Integer, endIndex: int | java.jint | java.lang.Integer, /) -> java.io.File: ...
    @staticmethod
    def toComponents(receiver: java.io.File, /) -> FilePathComponents: ...

class FilesKt__FileReadWriteKt(FilesKt__FilePathComponentsKt):
    def __init__(self) -> None: ...
    @staticmethod
    def appendBytes(receiver: java.io.File, array: java.chaquopy.JavaArrayJByte, /) -> None: ...
    @staticmethod
    def appendText(receiver: java.io.File, text: str | java.lang.String, charset: java.nio.charset.Charset, /) -> None: ...
    @typing.overload
    @staticmethod
    def forEachBlock(receiver: java.io.File, action: kotlin.jvm.functions.Function2[java.chaquopy.JavaArrayJByte, int, kotlin.Unit], /) -> None: ...
    @typing.overload
    @staticmethod
    def forEachBlock(receiver: java.io.File, blockSize: int | java.jint | java.lang.Integer, action: kotlin.jvm.functions.Function2[java.chaquopy.JavaArrayJByte, int, kotlin.Unit], /) -> None: ...
    @staticmethod
    def forEachLine(receiver: java.io.File, charset: java.nio.charset.Charset, action: kotlin.jvm.functions.Function1[str, kotlin.Unit], /) -> None: ...
    @staticmethod
    def readBytes(receiver: java.io.File, /) -> java.chaquopy.JavaArrayJByte: ...
    @staticmethod
    def readLines(receiver: java.io.File, charset: java.nio.charset.Charset, /) -> java.util.List[java.lang.String]: ...
    @staticmethod
    def readText(receiver: java.io.File, charset: java.nio.charset.Charset, /) -> str: ...
    _useLines__T = typing.TypeVar('_useLines__T')  # <T>
    @staticmethod
    def useLines(receiver: java.io.File, charset: java.nio.charset.Charset, block: kotlin.jvm.functions.Function1[kotlin.sequences.Sequence[java.lang.String], _useLines__T], /) -> _useLines__T: ...
    @staticmethod
    def writeBytes(receiver: java.io.File, array: java.chaquopy.JavaArrayJByte, /) -> None: ...
    @staticmethod
    def writeText(receiver: java.io.File, text: str | java.lang.String, charset: java.nio.charset.Charset, /) -> None: ...

class FilesKt__FileTreeWalkKt(FilesKt__FileReadWriteKt):
    def __init__(self) -> None: ...
    @staticmethod
    def walk(receiver: java.io.File, direction: FileWalkDirection, /) -> FileTreeWalk: ...
    @staticmethod
    def walkBottomUp(receiver: java.io.File, /) -> FileTreeWalk: ...
    @staticmethod
    def walkTopDown(receiver: java.io.File, /) -> FileTreeWalk: ...

class FilesKt__UtilsKt(FilesKt__FileTreeWalkKt):
    def __init__(self) -> None: ...
    @staticmethod
    def copyRecursively(receiver: java.io.File, target: java.io.File, overwrite: bool | java.jboolean | java.lang.Boolean, onError: kotlin.jvm.functions.Function2[java.io.File, java.io.IOException, OnErrorAction], /) -> bool: ...
    @staticmethod
    def copyTo(receiver: java.io.File, target: java.io.File, overwrite: bool | java.jboolean | java.lang.Boolean, bufferSize: int | java.jint | java.lang.Integer, /) -> java.io.File: ...
    @staticmethod
    def createTempDir(prefix: str | java.lang.String, suffix: str | java.lang.String, directory: java.io.File, /) -> java.io.File: ...
    @staticmethod
    def createTempFile(prefix: str | java.lang.String, suffix: str | java.lang.String, directory: java.io.File, /) -> java.io.File: ...
    @staticmethod
    def deleteRecursively(receiver: java.io.File, /) -> bool: ...
    @typing.overload
    @staticmethod
    def endsWith(receiver: java.io.File, other: java.io.File, /) -> bool: ...
    @typing.overload
    @staticmethod
    def endsWith(receiver: java.io.File, other: str | java.lang.String, /) -> bool: ...
    @staticmethod
    def getExtension(receiver: java.io.File, /) -> str: ...
    @staticmethod
    def getInvariantSeparatorsPath(receiver: java.io.File, /) -> str: ...
    @staticmethod
    def getNameWithoutExtension(receiver: java.io.File, /) -> str: ...
    @staticmethod
    def normalize(receiver: java.io.File, /) -> java.io.File: ...
    @staticmethod
    def relativeTo(receiver: java.io.File, base: java.io.File, /) -> java.io.File: ...
    @staticmethod
    def relativeToOrNull(receiver: java.io.File, base: java.io.File, /) -> java.io.File: ...
    @staticmethod
    def relativeToOrSelf(receiver: java.io.File, base: java.io.File, /) -> java.io.File: ...
    @typing.overload
    @staticmethod
    def resolve(receiver: java.io.File, relative: java.io.File, /) -> java.io.File: ...
    @typing.overload
    @staticmethod
    def resolve(receiver: java.io.File, relative: str | java.lang.String, /) -> java.io.File: ...
    @typing.overload
    @staticmethod
    def resolveSibling(receiver: java.io.File, relative: java.io.File, /) -> java.io.File: ...
    @typing.overload
    @staticmethod
    def resolveSibling(receiver: java.io.File, relative: str | java.lang.String, /) -> java.io.File: ...
    @typing.overload
    @staticmethod
    def startsWith(receiver: java.io.File, other: java.io.File, /) -> bool: ...
    @typing.overload
    @staticmethod
    def startsWith(receiver: java.io.File, other: str | java.lang.String, /) -> bool: ...
    @staticmethod
    def toRelativeString(receiver: java.io.File, base: java.io.File, /) -> str: ...

class LinesSequence(kotlin.sequences.Sequence[java.lang.String]):
    def __init__(self, reader: java.io.BufferedReader, /) -> None: ...
    def iterator(self) -> java.util.Iterator[java.lang.String]: ...

class NoSuchFileException(FileSystemException):
    def __init__(self, file: java.io.File, other: java.io.File, reason: str | java.lang.String, /) -> None: ...

class OnErrorAction(java.lang.Enum[OnErrorAction]):
    SKIP: typing.ClassVar[OnErrorAction] = ...
    TERMINATE: typing.ClassVar[OnErrorAction] = ...
    @staticmethod
    def valueOf(arg1: str | java.lang.String, /) -> OnErrorAction: ...
    @staticmethod
    def values() -> java.chaquopy.JavaArray[OnErrorAction]: ...

class SerializableKt(java.lang.Object): ...

class TerminateException(FileSystemException):
    def __init__(self, file: java.io.File, /) -> None: ...

class TextStreamsKt(java.lang.Object):
    @staticmethod
    def copyTo(receiver: java.io.Reader, out: java.io.Writer, bufferSize: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def forEachLine(receiver: java.io.Reader, action: kotlin.jvm.functions.Function1[str, kotlin.Unit], /) -> None: ...
    @staticmethod
    def lineSequence(receiver: java.io.BufferedReader, /) -> kotlin.sequences.Sequence[java.lang.String]: ...
    @staticmethod
    def readBytes(receiver: java.net.URL, /) -> java.chaquopy.JavaArrayJByte: ...
    @staticmethod
    def readLines(receiver: java.io.Reader, /) -> java.util.List[java.lang.String]: ...
    @staticmethod
    def readText(receiver: java.io.Reader, /) -> str: ...
    _useLines__T = typing.TypeVar('_useLines__T')  # <T>
    @staticmethod
    def useLines(receiver: java.io.Reader, block: kotlin.jvm.functions.Function1[kotlin.sequences.Sequence[java.lang.String], _useLines__T], /) -> _useLines__T: ...
