import typing

import android.content
import android.util
import android.view
import com.google.android.material.navigation
import java
import java.lang

class NavigationRailItemView(com.google.android.material.navigation.NavigationBarItemView):
    def __init__(self, context: android.content.Context, /) -> None: ...
    def getItemDefaultMarginResId(self) -> int: ...
    def getItemLayoutResId(self) -> int: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...

class NavigationRailMenuView(com.google.android.material.navigation.NavigationBarMenuView):
    def __init__(self, context: android.content.Context, /) -> None: ...
    def createNavigationBarItemView(self, context: android.content.Context, /) -> com.google.android.material.navigation.NavigationBarItemView: ...
    def getItemMinimumHeight(self) -> int: ...
    def onLayout(self, changed: bool | java.jboolean | java.lang.Boolean, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemMinimumHeight(self, minHeight: int | java.jint | java.lang.Integer, /) -> None: ...

class NavigationRailView(com.google.android.material.navigation.NavigationBarView):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def addHeaderView(self, layoutRes: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def addHeaderView(self, headerView: android.view.View, /) -> None: ...
    def createNavigationBarMenuView(self, context: android.content.Context, /) -> NavigationRailMenuView: ...
    def getHeaderView(self) -> android.view.View: ...
    def getItemMinimumHeight(self) -> int: ...
    def getMaxItemCount(self) -> int: ...
    def getMenuGravity(self) -> int: ...
    def onLayout(self, changed: bool | java.jboolean | java.lang.Boolean, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def removeHeaderView(self) -> None: ...
    def setItemMinimumHeight(self, minHeight: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMenuGravity(self, gravity: int | java.jint | java.lang.Integer, /) -> None: ...
