import android.content
import android.content.res
import android.graphics
import android.graphics.drawable
import android.text
import androidx.core.content.res
import java
import java.lang

class MaterialResources(java.lang.Object):
    @staticmethod
    def getColorStateList(context: android.content.Context, attributes: android.content.res.TypedArray, index: int | java.jint | java.lang.Integer, /) -> android.content.res.ColorStateList: ...
    @staticmethod
    def getDrawable(context: android.content.Context, attributes: android.content.res.TypedArray, index: int | java.jint | java.lang.Integer, /) -> android.graphics.drawable.Drawable: ...
    @staticmethod
    def getTextAppearance(context: android.content.Context, attributes: android.content.res.TypedArray, index: int | java.jint | java.lang.Integer, /) -> TextAppearance: ...

class TextAppearance(java.lang.Object):
    textSize: float = ...
    textColor: android.content.res.ColorStateList = ...
    textColorHint: android.content.res.ColorStateList = ...
    textColorLink: android.content.res.ColorStateList = ...
    textStyle: int = ...
    typeface: int = ...
    fontFamily: str = ...
    textAllCaps: bool = ...
    shadowColor: android.content.res.ColorStateList = ...
    shadowDx: float = ...
    shadowDy: float = ...
    shadowRadius: float = ...
    def __init__(self, context: android.content.Context, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def getFont(self, context: android.content.Context, /) -> android.graphics.Typeface: ...
    def getFontAsync(self, context: android.content.Context, textPaint: android.text.TextPaint, callback: androidx.core.content.res.ResourcesCompat.FontCallback, /) -> None: ...
    def updateDrawState(self, context: android.content.Context, textPaint: android.text.TextPaint, callback: androidx.core.content.res.ResourcesCompat.FontCallback, /) -> None: ...
    def updateMeasureState(self, context: android.content.Context, textPaint: android.text.TextPaint, callback: androidx.core.content.res.ResourcesCompat.FontCallback, /) -> None: ...
    def updateTextPaintMeasureState(self, textPaint: android.text.TextPaint, typeface: android.graphics.Typeface, /) -> None: ...

class TextAppearanceConfig(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def setShouldLoadFontSynchronously(flag: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def shouldLoadFontSynchronously() -> bool: ...
