import typing

import java
import java.chaquopy
import java.io
import java.lang
import java.util.concurrent
import java.util.concurrent.atomic
import kotlin.coroutines
import kotlinx.coroutines
import kotlinx.coroutines.internal

class CoroutineScheduler(java.util.concurrent.Executor, java.io.Closeable):
    globalCpuQueue: GlobalQueue = ...
    globalBlockingQueue: GlobalQueue = ...
    workers: java.util.concurrent.atomic.AtomicReferenceArray[CoroutineScheduler.Worker] = ...
    corePoolSize: int = ...
    maxPoolSize: int = ...
    idleWorkerKeepAliveNs: int = ...
    schedulerName: str = ...
    NOT_IN_STACK: typing.ClassVar[kotlinx.coroutines.internal.Symbol] = ...
    MIN_SUPPORTED_POOL_SIZE: typing.ClassVar[int] = ...
    MAX_SUPPORTED_POOL_SIZE: typing.ClassVar[int] = ...
    Companion: typing.ClassVar[CoroutineScheduler.Companion] = ...
    def __init__(self, corePoolSize: int | java.jint | java.lang.Integer, maxPoolSize: int | java.jint | java.lang.Integer, idleWorkerKeepAliveNs: int | java.jlong | java.lang.Long, schedulerName: str | java.lang.String, /) -> None: ...
    def availableCpuPermits(self, state: int | java.jlong | java.lang.Long, /) -> int: ...
    def close(self) -> None: ...
    def createTask(self, block: java.lang.Runnable, taskContext: TaskContext, /) -> Task: ...
    def dispatch(self, block: java.lang.Runnable, taskContext: TaskContext, tailDispatch: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def execute(self, command: java.lang.Runnable, /) -> None: ...
    def isTerminated(self) -> bool: ...
    def parkedWorkersStackPush(self, worker: CoroutineScheduler.Worker, /) -> bool: ...
    def parkedWorkersStackTopUpdate(self, worker: CoroutineScheduler.Worker, oldIndex: int | java.jint | java.lang.Integer, newIndex: int | java.jint | java.lang.Integer, /) -> None: ...
    def runSafely(self, task: Task, /) -> None: ...
    def shutdown(self, timeout: int | java.jlong | java.lang.Long, /) -> None: ...
    def signalCpuWork(self) -> None: ...
    def toString(self) -> str: ...

    class Worker(java.lang.Thread):
        localQueue: WorkQueue = ...
        state: CoroutineScheduler.WorkerState = ...
        mayHaveLocalTasks: bool = ...
        def __init__(self, this_0: int | java.jint | java.lang.Integer, /) -> None: ...
        def findTask(self, scanLocalQueue: bool | java.jboolean | java.lang.Boolean, /) -> Task: ...
        def getIndexInArray(self) -> int: ...
        def getNextParkedWorker(self) -> java.lang.Object: ...
        def getScheduler(self) -> CoroutineScheduler: ...
        def nextInt(self, upperBound: int | java.jint | java.lang.Integer, /) -> int: ...
        def run(self) -> None: ...
        def setIndexInArray(self, index: int | java.jint | java.lang.Integer, /) -> None: ...
        def setNextParkedWorker(self, set___: java.lang.Object | int | bool | float | str, /) -> None: ...
        def tryReleaseCpu(self, newState: CoroutineScheduler.WorkerState, /) -> bool: ...

    class WorkerState(java.lang.Enum[CoroutineScheduler.WorkerState]):
        CPU_ACQUIRED: typing.ClassVar[CoroutineScheduler.WorkerState] = ...
        BLOCKING: typing.ClassVar[CoroutineScheduler.WorkerState] = ...
        PARKING: typing.ClassVar[CoroutineScheduler.WorkerState] = ...
        DORMANT: typing.ClassVar[CoroutineScheduler.WorkerState] = ...
        TERMINATED: typing.ClassVar[CoroutineScheduler.WorkerState] = ...
        @staticmethod
        def valueOf(arg1: str | java.lang.String, /) -> CoroutineScheduler.WorkerState: ...
        @staticmethod
        def values() -> java.chaquopy.JavaArray[CoroutineScheduler.WorkerState]: ...

    class Companion(java.lang.Object): ...

class CoroutineSchedulerKt(java.lang.Object):
    @staticmethod
    def isSchedulerWorker(thread: java.lang.Thread, /) -> bool: ...
    @staticmethod
    def mayNotBlock(thread: java.lang.Thread, /) -> bool: ...

class DefaultScheduler(ExperimentalCoroutineDispatcher):
    INSTANCE: typing.ClassVar[DefaultScheduler] = ...
    def close(self) -> None: ...
    def getIO(self) -> kotlinx.coroutines.CoroutineDispatcher: ...
    def toDebugString(self) -> str: ...
    def toString(self) -> str: ...

class ExperimentalCoroutineDispatcher(kotlinx.coroutines.ExecutorCoroutineDispatcher):
    @typing.overload
    def __init__(self, corePoolSize: int | java.jint | java.lang.Integer, maxPoolSize: int | java.jint | java.lang.Integer, schedulerName: str | java.lang.String, /) -> None: ...
    @typing.overload
    def __init__(self, corePoolSize: int | java.jint | java.lang.Integer, maxPoolSize: int | java.jint | java.lang.Integer, idleWorkerKeepAliveNs: int | java.jlong | java.lang.Long, schedulerName: str | java.lang.String, /) -> None: ...
    def blocking(self, parallelism: int | java.jint | java.lang.Integer, /) -> kotlinx.coroutines.CoroutineDispatcher: ...
    def close(self) -> None: ...
    def dispatch(self, context: kotlin.coroutines.CoroutineContext, block: java.lang.Runnable, /) -> None: ...
    def dispatchYield(self, context: kotlin.coroutines.CoroutineContext, block: java.lang.Runnable, /) -> None: ...
    def getExecutor(self) -> java.util.concurrent.Executor: ...
    def limited(self, parallelism: int | java.jint | java.lang.Integer, /) -> kotlinx.coroutines.CoroutineDispatcher: ...
    def toString(self) -> str: ...

class GlobalQueue(kotlinx.coroutines.internal.LockFreeTaskQueue[Task]):
    def __init__(self) -> None: ...

class LimitingDispatcher(kotlinx.coroutines.ExecutorCoroutineDispatcher, TaskContext, java.util.concurrent.Executor):
    def __init__(self, dispatcher: ExperimentalCoroutineDispatcher, parallelism: int | java.jint | java.lang.Integer, name: str | java.lang.String, taskMode: int | java.jint | java.lang.Integer, /) -> None: ...
    def afterTask(self) -> None: ...
    def close(self) -> None: ...
    def dispatch(self, context: kotlin.coroutines.CoroutineContext, block: java.lang.Runnable, /) -> None: ...
    def dispatchYield(self, context: kotlin.coroutines.CoroutineContext, block: java.lang.Runnable, /) -> None: ...
    def execute(self, command: java.lang.Runnable, /) -> None: ...
    def getExecutor(self) -> java.util.concurrent.Executor: ...
    def getTaskMode(self) -> int: ...
    def toString(self) -> str: ...

class NanoTimeSource(SchedulerTimeSource):
    INSTANCE: typing.ClassVar[NanoTimeSource] = ...
    def nanoTime(self) -> int: ...

class NonBlockingContext(TaskContext):
    INSTANCE: typing.ClassVar[NonBlockingContext] = ...
    def afterTask(self) -> None: ...
    def getTaskMode(self) -> int: ...

class SchedulerTimeSource(java.lang.Object):
    def __init__(self) -> None: ...
    def nanoTime(self) -> int: ...

class Task(java.lang.Runnable):
    submissionTime: int = ...
    taskContext: TaskContext = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, submissionTime: int | java.jlong | java.lang.Long, taskContext: TaskContext, /) -> None: ...
    def getMode(self) -> int: ...

class TaskContext(java.lang.Object):
    def afterTask(self) -> None: ...
    def getTaskMode(self) -> int: ...

class TaskImpl(Task):
    block: java.lang.Runnable = ...
    def __init__(self, block: java.lang.Runnable, submissionTime: int | java.jlong | java.lang.Long, taskContext: TaskContext, /) -> None: ...
    def run(self) -> None: ...
    def toString(self) -> str: ...

class TasksKt(java.lang.Object):
    DEFAULT_DISPATCHER_NAME: typing.ClassVar[str] = ...
    DEFAULT_SCHEDULER_NAME: typing.ClassVar[str] = ...
    WORK_STEALING_TIME_RESOLUTION_NS: typing.ClassVar[int] = ...
    BLOCKING_DEFAULT_PARALLELISM: typing.ClassVar[int] = ...
    CORE_POOL_SIZE: typing.ClassVar[int] = ...
    MAX_POOL_SIZE: typing.ClassVar[int] = ...
    IDLE_WORKER_KEEP_ALIVE_NS: typing.ClassVar[int] = ...
    schedulerTimeSource: typing.ClassVar[SchedulerTimeSource] = ...
    TASK_NON_BLOCKING: typing.ClassVar[int] = ...
    TASK_PROBABLY_BLOCKING: typing.ClassVar[int] = ...
    @staticmethod
    def isBlocking(this_isBlocking: Task, /) -> bool: ...

class WorkQueue(java.lang.Object):
    def __init__(self) -> None: ...
    def add(self, task: Task, fair: bool | java.jboolean | java.lang.Boolean, /) -> Task: ...
    def offloadAllWorkTo(self, globalQueue: GlobalQueue, /) -> None: ...
    def poll(self) -> Task: ...
    def tryStealBlockingFrom(self, victim: WorkQueue, /) -> int: ...
    def tryStealFrom(self, victim: WorkQueue, /) -> int: ...

class WorkQueueKt(java.lang.Object):
    BUFFER_CAPACITY_BASE: typing.ClassVar[int] = ...
    BUFFER_CAPACITY: typing.ClassVar[int] = ...
    MASK: typing.ClassVar[int] = ...
    TASK_STOLEN: typing.ClassVar[int] = ...
    NOTHING_TO_STEAL: typing.ClassVar[int] = ...
