import android.content
import android.content.res
import android.graphics
import android.graphics.drawable
import android.util
import androidx.core.graphics.drawable
import java
import java.chaquopy
import java.lang
import org.xmlpull.v1

class AnimatedStateListDrawableCompat(StateListDrawableCompat, androidx.core.graphics.drawable.TintAwareDrawable):
    def __init__(self) -> None: ...
    def addState(self, stateSet: java.chaquopy.JavaArrayJInt, drawable: android.graphics.drawable.Drawable, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def addTransition(self, fromId: int | java.jint | java.lang.Integer, toId: int | java.jint | java.lang.Integer, transition: android.graphics.drawable.Drawable, reversible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def create(context: android.content.Context, resId: int | java.jint | java.lang.Integer, theme: android.content.res.Resources.Theme, /) -> AnimatedStateListDrawableCompat: ...
    @staticmethod
    def createFromXmlInner(context: android.content.Context, resources: android.content.res.Resources, parser: org.xmlpull.v1.XmlPullParser, attrs: android.util.AttributeSet, theme: android.content.res.Resources.Theme, /) -> AnimatedStateListDrawableCompat: ...
    def inflate(self, context: android.content.Context, resources: android.content.res.Resources, parser: org.xmlpull.v1.XmlPullParser, attrs: android.util.AttributeSet, theme: android.content.res.Resources.Theme, /) -> None: ...
    def isStateful(self) -> bool: ...
    def jumpToCurrentState(self) -> None: ...
    def mutate(self) -> android.graphics.drawable.Drawable: ...
    def onStateChange(self, stateSet: java.chaquopy.JavaArrayJInt, /) -> bool: ...
    def setVisible(self, visible: bool | java.jboolean | java.lang.Boolean, restart: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...

class DrawableContainerCompat(android.graphics.drawable.Drawable, android.graphics.drawable.Drawable.Callback):
    def __init__(self) -> None: ...
    def applyTheme(self, theme: android.content.res.Resources.Theme, /) -> None: ...
    def canApplyTheme(self) -> bool: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getAlpha(self) -> int: ...
    def getChangingConfigurations(self) -> int: ...
    def getConstantState(self) -> android.graphics.drawable.Drawable.ConstantState: ...
    def getCurrent(self) -> android.graphics.drawable.Drawable: ...
    def getHotspotBounds(self, outRect: android.graphics.Rect, /) -> None: ...
    def getIntrinsicHeight(self) -> int: ...
    def getIntrinsicWidth(self) -> int: ...
    def getMinimumHeight(self) -> int: ...
    def getMinimumWidth(self) -> int: ...
    def getOpacity(self) -> int: ...
    def getOutline(self, outline: android.graphics.Outline, /) -> None: ...
    def getPadding(self, padding: android.graphics.Rect, /) -> bool: ...
    def invalidateDrawable(self, who: android.graphics.drawable.Drawable, /) -> None: ...
    def isAutoMirrored(self) -> bool: ...
    def isStateful(self) -> bool: ...
    def jumpToCurrentState(self) -> None: ...
    def mutate(self) -> android.graphics.drawable.Drawable: ...
    def onBoundsChange(self, bounds: android.graphics.Rect, /) -> None: ...
    def onLayoutDirectionChanged(self, layoutDirection: int | java.jint | java.lang.Integer, /) -> bool: ...
    def onLevelChange(self, level: int | java.jint | java.lang.Integer, /) -> bool: ...
    def onStateChange(self, state: java.chaquopy.JavaArrayJInt, /) -> bool: ...
    def scheduleDrawable(self, who: android.graphics.drawable.Drawable, what: java.lang.Runnable, when: int | java.jlong | java.lang.Long, /) -> None: ...
    def setAlpha(self, alpha: int | java.jint | java.lang.Integer, /) -> None: ...
    def setAutoMirrored(self, mirrored: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setColorFilter(self, colorFilter: android.graphics.ColorFilter, /) -> None: ...
    def setDither(self, dither: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setEnterFadeDuration(self, ms: int | java.jint | java.lang.Integer, /) -> None: ...
    def setExitFadeDuration(self, ms: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHotspot(self, x: float | java.jfloat | java.lang.Float, y: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setHotspotBounds(self, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTint(self, tintColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTintList(self, tint: android.content.res.ColorStateList, /) -> None: ...
    def setTintMode(self, tintMode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def setVisible(self, visible: bool | java.jboolean | java.lang.Boolean, restart: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def unscheduleDrawable(self, who: android.graphics.drawable.Drawable, what: java.lang.Runnable, /) -> None: ...

class DrawableWrapperCompat(android.graphics.drawable.Drawable, android.graphics.drawable.Drawable.Callback):
    def __init__(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getChangingConfigurations(self) -> int: ...
    def getCurrent(self) -> android.graphics.drawable.Drawable: ...
    def getDrawable(self) -> android.graphics.drawable.Drawable: ...
    def getIntrinsicHeight(self) -> int: ...
    def getIntrinsicWidth(self) -> int: ...
    def getMinimumHeight(self) -> int: ...
    def getMinimumWidth(self) -> int: ...
    def getOpacity(self) -> int: ...
    def getPadding(self, padding: android.graphics.Rect, /) -> bool: ...
    def getState(self) -> java.chaquopy.JavaArrayJInt: ...
    def getTransparentRegion(self) -> android.graphics.Region: ...
    def invalidateDrawable(self, who: android.graphics.drawable.Drawable, /) -> None: ...
    def isAutoMirrored(self) -> bool: ...
    def isStateful(self) -> bool: ...
    def jumpToCurrentState(self) -> None: ...
    def onBoundsChange(self, bounds: android.graphics.Rect, /) -> None: ...
    def onLevelChange(self, level: int | java.jint | java.lang.Integer, /) -> bool: ...
    def scheduleDrawable(self, who: android.graphics.drawable.Drawable, what: java.lang.Runnable, when: int | java.jlong | java.lang.Long, /) -> None: ...
    def setAlpha(self, alpha: int | java.jint | java.lang.Integer, /) -> None: ...
    def setAutoMirrored(self, mirrored: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setChangingConfigurations(self, configs: int | java.jint | java.lang.Integer, /) -> None: ...
    def setColorFilter(self, cf: android.graphics.ColorFilter, /) -> None: ...
    def setDither(self, dither: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDrawable(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...
    def setFilterBitmap(self, filter: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setHotspot(self, x: float | java.jfloat | java.lang.Float, y: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setHotspotBounds(self, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setState(self, stateSet: java.chaquopy.JavaArrayJInt, /) -> bool: ...
    def setTint(self, tint: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTintList(self, tint: android.content.res.ColorStateList, /) -> None: ...
    def setTintMode(self, tintMode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def setVisible(self, visible: bool | java.jboolean | java.lang.Boolean, restart: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def unscheduleDrawable(self, who: android.graphics.drawable.Drawable, what: java.lang.Runnable, /) -> None: ...

class StateListDrawableCompat(DrawableContainerCompat):
    def __init__(self) -> None: ...
    def addState(self, stateSet: java.chaquopy.JavaArrayJInt, drawable: android.graphics.drawable.Drawable, /) -> None: ...
    def applyTheme(self, theme: android.content.res.Resources.Theme, /) -> None: ...
    def inflate(self, context: android.content.Context, r: android.content.res.Resources, parser: org.xmlpull.v1.XmlPullParser, attrs: android.util.AttributeSet, theme: android.content.res.Resources.Theme, /) -> None: ...
    def isStateful(self) -> bool: ...
    def mutate(self) -> android.graphics.drawable.Drawable: ...
    def onStateChange(self, stateSet: java.chaquopy.JavaArrayJInt, /) -> bool: ...
