import typing

import java
import java.chaquopy
import java.lang
import java.lang.annotation
import java.util
import java.util.regex
import kotlin
import kotlin.random
import kotlin.text

class AccessibleLateinitPropertyLiteral(java.lang.annotation.Annotation): ...

class ContractsDsl(java.lang.annotation.Annotation): ...

class DynamicExtension(java.lang.annotation.Annotation): ...

class Exact(java.lang.annotation.Annotation): ...

class HidesMembers(java.lang.annotation.Annotation): ...

class InlineOnly(java.lang.annotation.Annotation): ...

class IntrinsicConstEvaluation(java.lang.annotation.Annotation): ...

class LowPriorityInOverloadResolution(java.lang.annotation.Annotation): ...

class NoInfer(java.lang.annotation.Annotation): ...

class OnlyInputTypes(java.lang.annotation.Annotation): ...

class PlatformDependent(java.lang.annotation.Annotation): ...

class PlatformImplementations(java.lang.Object):
    def __init__(self) -> None: ...
    def addSuppressed(self, cause: java.lang.Throwable, exception: java.lang.Throwable, /) -> None: ...
    def defaultPlatformRandom(self) -> kotlin.random.Random: ...
    def getMatchResultNamedGroup(self, matchResult: java.util.regex.MatchResult, name: str | java.lang.String, /) -> kotlin.text.MatchGroup: ...
    def getSuppressed(self, exception: java.lang.Throwable, /) -> java.util.List[java.lang.Throwable]: ...

class PlatformImplementationsKt(java.lang.Object):
    IMPLEMENTATIONS: typing.ClassVar[PlatformImplementations] = ...
    @staticmethod
    def apiVersionIsAtLeast(major: int | java.jint | java.lang.Integer, minor: int | java.jint | java.lang.Integer, patch: int | java.jint | java.lang.Integer, /) -> bool: ...

class ProgressionUtilKt(java.lang.Object):
    @typing.overload
    @staticmethod
    def getProgressionLastElement(start: int | java.jint | java.lang.Integer, end: int | java.jint | java.lang.Integer, step: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getProgressionLastElement(start: int | java.jlong | java.lang.Long, end: int | java.jlong | java.lang.Long, step: int | java.jlong | java.lang.Long, /) -> int: ...

class PureReifiable(java.lang.annotation.Annotation): ...

class RequireKotlin(java.lang.annotation.Annotation):
    def errorCode(self) -> int: ...
    def level(self) -> kotlin.DeprecationLevel: ...
    def message(self) -> str: ...
    def version(self) -> str: ...
    def versionKind(self) -> RequireKotlinVersionKind: ...

    class Container(java.lang.annotation.Annotation):
        def value(self) -> java.chaquopy.JavaArray[RequireKotlin]: ...

class RequireKotlinVersionKind(java.lang.Enum[RequireKotlinVersionKind]):
    LANGUAGE_VERSION: typing.ClassVar[RequireKotlinVersionKind] = ...
    COMPILER_VERSION: typing.ClassVar[RequireKotlinVersionKind] = ...
    API_VERSION: typing.ClassVar[RequireKotlinVersionKind] = ...
    @staticmethod
    def valueOf(value: str | java.lang.String, /) -> RequireKotlinVersionKind: ...
    @staticmethod
    def values() -> java.chaquopy.JavaArray[RequireKotlinVersionKind]: ...

class UProgressionUtilKt(java.lang.Object): ...
