import typing

import java.io
import java.lang

class OpenStreetMapTileProviderConstants(java.lang.Object):
    DEBUGMODE: typing.ClassVar[bool] = ...
    DEBUG_TILE_PROVIDERS: typing.ClassVar[bool] = ...
    MINIMUM_ZOOMLEVEL: typing.ClassVar[int] = ...
    MAXIMUM_ZOOMLEVEL: typing.ClassVar[int] = ...
    OSMDROID_PATH: typing.ClassVar[java.io.File] = ...
    TILE_PATH_BASE: typing.ClassVar[java.io.File] = ...
    TILE_PATH_EXTENSION: typing.ClassVar[str] = ...
    CACHE_MAPTILECOUNT_DEFAULT: typing.ClassVar[int] = ...
    NUMBER_OF_TILE_DOWNLOAD_THREADS: typing.ClassVar[int] = ...
    NUMBER_OF_TILE_FILESYSTEM_THREADS: typing.ClassVar[int] = ...
    ONE_SECOND: typing.ClassVar[int] = ...
    ONE_MINUTE: typing.ClassVar[int] = ...
    ONE_HOUR: typing.ClassVar[int] = ...
    ONE_DAY: typing.ClassVar[int] = ...
    ONE_WEEK: typing.ClassVar[int] = ...
    ONE_YEAR: typing.ClassVar[int] = ...
    DEFAULT_MAXIMUM_CACHED_FILE_AGE: typing.ClassVar[int] = ...
    TILE_DOWNLOAD_MAXIMUM_QUEUE_SIZE: typing.ClassVar[int] = ...
    TILE_FILESYSTEM_MAXIMUM_QUEUE_SIZE: typing.ClassVar[int] = ...
    TILE_EXPIRY_TIME_MILLISECONDS: typing.ClassVar[int] = ...
    TILE_MAX_CACHE_SIZE_BYTES: typing.ClassVar[int] = ...
    TILE_TRIM_CACHE_SIZE_BYTES: typing.ClassVar[int] = ...
