import android.app
import android.content
import android.content.pm
import android.database
import android.net
import android.os
import android.webkit
import androidx
import java
import java.chaquopy
import java.io
import java.lang
import java.lang.annotation
import java.lang.reflect
import java.util
import java.util.concurrent
import org.chromium.support_lib_boundary
import typing



class BackForwardCacheSettings(java.lang.Object):
    def getMaxPagesInCache(self) -> int: ...
    def getTimeoutSeconds(self) -> int: ...

    class Builder(java.lang.Object):
        def __init__(self) -> None: ...
        def build(self) -> BackForwardCacheSettings: ...
        def setMaxPagesInCache(self, maxPagesInCache: int | java.jint | java.lang.Integer, /) -> BackForwardCacheSettings.Builder: ...
        def setTimeoutSeconds(self, timeoutInSeconds: int | java.jlong | java.lang.Long, /) -> BackForwardCacheSettings.Builder: ...

class CookieManagerCompat(java.lang.Object):
    @staticmethod
    def getCookieInfo(cookieManager: android.webkit.CookieManager, url: str | java.lang.String, /) -> java.util.List[java.lang.String]: ...

class CustomHeader(java.lang.Object):
    def __init__(self, name: str | java.lang.String, value: str | java.lang.String, originRules: java.util.Set[java.lang.String], /) -> None: ...
    def equals(self, obj: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getName(self) -> str: ...
    def getRules(self) -> java.util.Set[java.lang.String]: ...
    def getValue(self) -> str: ...
    def hashCode(self) -> int: ...

class DropDataContentProvider(android.content.ContentProvider):
    def __init__(self) -> None: ...
    def call(self, method: str | java.lang.String, arg: str | java.lang.String, extras: android.os.Bundle, /) -> android.os.Bundle: ...
    def delete(self, uri: android.net.Uri, selection: str | java.lang.String, selectionArgs: java.chaquopy.JavaArray[java.lang.String], /) -> int: ...
    def getType(self, uri: android.net.Uri, /) -> str: ...
    def insert(self, uri: android.net.Uri, contentValues: android.content.ContentValues, /) -> android.net.Uri: ...
    def onCreate(self) -> bool: ...
    def openFile(self, uri: android.net.Uri, mode: str | java.lang.String, /) -> android.os.ParcelFileDescriptor: ...
    def query(self, uri: android.net.Uri, projection: java.chaquopy.JavaArray[java.lang.String], selection: str | java.lang.String, selectionArgs: java.chaquopy.JavaArray[java.lang.String], sortOrder: str | java.lang.String, /) -> android.database.Cursor: ...
    def update(self, uri: android.net.Uri, contentValues: android.content.ContentValues, s: str | java.lang.String, strings: java.chaquopy.JavaArray[java.lang.String], /) -> int: ...

class JavaScriptReplyProxy(java.lang.Object):
    def __init__(self) -> None: ...
    @typing.overload
    def postMessage(self, arg1: str | java.lang.String, /) -> None: ...
    @typing.overload
    def postMessage(self, arg1: java.chaquopy.JavaArrayJByte, /) -> None: ...

class Navigation(java.lang.Object):
    def didCommit(self) -> bool: ...
    def didCommitErrorPage(self) -> bool: ...
    def getPage(self) -> Page: ...
    def getStatusCode(self) -> int: ...
    def getUrl(self) -> str: ...
    def isBack(self) -> bool: ...
    def isForward(self) -> bool: ...
    def isHistory(self) -> bool: ...
    def isReload(self) -> bool: ...
    def isRestore(self) -> bool: ...
    def isSameDocument(self) -> bool: ...
    def wasInitiatedByPage(self) -> bool: ...

class NavigationListener(java.lang.Object):
    def onFirstContentfulPaint(self, page: Page, loadTimeUs: int | java.jlong | java.lang.Long, /) -> None: ...
    def onNavigationCompleted(self, navigation: Navigation, /) -> None: ...
    def onNavigationRedirected(self, navigation: Navigation, /) -> None: ...
    def onNavigationStarted(self, navigation: Navigation, /) -> None: ...
    def onPageDeleted(self, page: Page, /) -> None: ...
    def onPageDomContentLoadedEvent(self, page: Page, /) -> None: ...
    def onPageLoadEvent(self, page: Page, /) -> None: ...

class NoVarySearchHeader(java.lang.Object):
    varyOnKeyOrder: bool = ...
    ignoreDifferencesInParameters: bool = ...
    ignoredQueryParameters: java.util.List[java.lang.String] = ...
    consideredQueryParameters: java.util.List[java.lang.String] = ...
    @staticmethod
    def alwaysVaryHeader() -> NoVarySearchHeader: ...
    @staticmethod
    def neverVaryExcept(varyOnOrdering: bool | java.jboolean | java.lang.Boolean, consideredQueryParameters: java.util.List[java.lang.String], /) -> NoVarySearchHeader: ...
    @staticmethod
    def neverVaryHeader() -> NoVarySearchHeader: ...
    @staticmethod
    def varyExcept(varyOnOrdering: bool | java.jboolean | java.lang.Boolean, ignoredQueryParameters: java.util.List[java.lang.String], /) -> NoVarySearchHeader: ...

_OutcomeReceiverCompat__T = typing.TypeVar('_OutcomeReceiverCompat__T')  # <T>
_OutcomeReceiverCompat__E = typing.TypeVar('_OutcomeReceiverCompat__E', bound=java.lang.Throwable)  # <E>
class OutcomeReceiverCompat(java.lang.Object, typing.Generic[_OutcomeReceiverCompat__T, _OutcomeReceiverCompat__E]):
    def onError(self, error: _OutcomeReceiverCompat__E, /) -> None: ...
    def onResult(self, arg1: _OutcomeReceiverCompat__T, /) -> None: ...

class Page(java.lang.Object): ...

class PrefetchException(java.lang.Exception):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, error: str | java.lang.String, /) -> None: ...

class PrefetchNetworkException(PrefetchException):
    NO_HTTP_RESPONSE_STATUS_CODE: typing.ClassVar[int] = ...
    httpResponseStatusCode: int = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, httpResponseStatusCode: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, error: str | java.lang.String, /) -> None: ...
    @typing.overload
    def __init__(self, error: str | java.lang.String, httpResponseStatusCode: int | java.jint | java.lang.Integer, /) -> None: ...

class PrerenderException(java.lang.Exception):
    def __init__(self, error: str | java.lang.String, cause: java.lang.Throwable, /) -> None: ...

class PrerenderOperationCallback(java.lang.Object):
    def onError(self, arg1: PrerenderException, /) -> None: ...
    def onPrerenderActivated(self) -> None: ...

class ProcessGlobalConfig(java.lang.Object):
    UI_THREAD_STARTUP_MODE_DEFAULT: typing.ClassVar[int] = ...
    UI_THREAD_STARTUP_MODE_SYNC: typing.ClassVar[int] = ...
    UI_THREAD_STARTUP_MODE_ASYNC: typing.ClassVar[int] = ...
    UI_THREAD_STARTUP_MODE_ASYNC_LONG_TASKS: typing.ClassVar[int] = ...
    UI_THREAD_STARTUP_MODE_ASYNC_SHORT_TASKS: typing.ClassVar[int] = ...
    UI_THREAD_STARTUP_MODE_ASYNC_VERY_SHORT_TASKS: typing.ClassVar[int] = ...
    UI_THREAD_STARTUP_MODE_ASYNC_WITHOUT_MULTI_PROCESS_STARTUP: typing.ClassVar[int] = ...
    def __init__(self) -> None: ...
    @staticmethod
    def apply(config: ProcessGlobalConfig, /) -> None: ...
    def setDataDirectorySuffix(self, context: android.content.Context, suffix: str | java.lang.String, /) -> ProcessGlobalConfig: ...
    def setDirectoryBasePaths(self, context: android.content.Context, dataDirectoryBasePath: java.io.File, cacheDirectoryBasePath: java.io.File, /) -> ProcessGlobalConfig: ...
    def setPartitionedCookiesEnabled(self, context: android.content.Context, isEnabled: bool | java.jboolean | java.lang.Boolean, /) -> ProcessGlobalConfig: ...
    def setUiThreadStartupMode(self, context: android.content.Context, startupMode: int | java.jint | java.lang.Integer, /) -> ProcessGlobalConfig: ...
    def setUiThreadStartupModeV2(self, context: android.content.Context, startupMode: int | java.jint | java.lang.Integer, /) -> ProcessGlobalConfig: ...

    class UiThreadStartupMode(java.lang.annotation.Annotation): ...

class Profile(java.lang.Object):
    DEFAULT_PROFILE_NAME: typing.ClassVar[str] = ...
    def addCustomHeader(self, header: CustomHeader, /) -> None: ...
    def addQuicHints(self, urls: java.util.Set[java.lang.String], /) -> None: ...
    def clearAllCustomHeaders(self) -> None: ...
    def clearAllOriginMatchedHeaders(self) -> None: ...
    @typing.overload
    def clearCustomHeader(self, headerName: str | java.lang.String, /) -> None: ...
    @typing.overload
    def clearCustomHeader(self, headerName: str | java.lang.String, headerValue: str | java.lang.String, /) -> None: ...
    def clearOriginMatchedHeader(self, arg1: str | java.lang.String, /) -> None: ...
    def clearPrefetchAsync(self, arg1: str | java.lang.String, arg2: java.util.concurrent.Executor, arg3: OutcomeReceiverCompat[java.lang.Void, PrefetchException], /) -> None: ...
    def getCookieManager(self) -> android.webkit.CookieManager: ...
    @typing.overload
    def getCustomHeaders(self) -> java.util.Set[CustomHeader]: ...
    @typing.overload
    def getCustomHeaders(self, name: str | java.lang.String, /) -> java.util.Set[CustomHeader]: ...
    @typing.overload
    def getCustomHeaders(self, name: str | java.lang.String, value: str | java.lang.String, /) -> java.util.Set[CustomHeader]: ...
    def getGeolocationPermissions(self) -> android.webkit.GeolocationPermissions: ...
    def getName(self) -> str: ...
    def getServiceWorkerController(self) -> android.webkit.ServiceWorkerController: ...
    def getWebStorage(self) -> android.webkit.WebStorage: ...
    def hasCustomHeader(self, headerName: str | java.lang.String, /) -> bool: ...
    def hasOriginMatchedHeader(self, arg1: str | java.lang.String, /) -> bool: ...
    def preconnect(self, url: str | java.lang.String, /) -> None: ...
    @typing.overload
    def prefetchUrlAsync(self, arg1: str | java.lang.String, arg2: android.os.CancellationSignal, arg3: java.util.concurrent.Executor, arg4: OutcomeReceiverCompat[java.lang.Void, PrefetchException], /) -> None: ...
    @typing.overload
    def prefetchUrlAsync(self, arg1: str | java.lang.String, arg2: android.os.CancellationSignal, arg3: java.util.concurrent.Executor, arg4: SpeculativeLoadingParameters, arg5: OutcomeReceiverCompat[java.lang.Void, PrefetchException], /) -> None: ...
    def setOriginMatchedHeader(self, arg1: str | java.lang.String, arg2: str | java.lang.String, arg3: java.util.Set[java.lang.String], /) -> None: ...
    def setSpeculativeLoadingConfig(self, arg1: SpeculativeLoadingConfig, /) -> None: ...
    def warmUpRendererProcess(self) -> None: ...

    class ExperimentalAddQuicHints(java.lang.annotation.Annotation): ...

    class ExperimentalPreconnect(java.lang.annotation.Annotation): ...

    class ExperimentalOriginMatchedHeader(java.lang.annotation.Annotation): ...

    class ExperimentalWarmUpRendererProcess(java.lang.annotation.Annotation): ...

    class ExperimentalUrlPrefetch(java.lang.annotation.Annotation): ...

class ProfileStore(java.lang.Object):
    def deleteProfile(self, arg1: str | java.lang.String, /) -> bool: ...
    def getAllProfileNames(self) -> java.util.List[java.lang.String]: ...
    @staticmethod
    def getInstance() -> ProfileStore: ...
    def getOrCreateProfile(self, arg1: str | java.lang.String, /) -> Profile: ...
    def getProfile(self, arg1: str | java.lang.String, /) -> Profile: ...

class ProxyConfig(java.lang.Object):
    MATCH_HTTP: typing.ClassVar[str] = ...
    MATCH_HTTPS: typing.ClassVar[str] = ...
    MATCH_ALL_SCHEMES: typing.ClassVar[str] = ...
    def __init__(self, proxyRules: java.util.List[ProxyConfig.ProxyRule], bypassRules: java.util.List[java.lang.String], reverseBypass: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def getBypassRules(self) -> java.util.List[java.lang.String]: ...
    def getProxyRules(self) -> java.util.List[ProxyConfig.ProxyRule]: ...
    def isReverseBypassEnabled(self) -> bool: ...

    class Builder(java.lang.Object):
        @typing.overload
        def __init__(self) -> None: ...
        @typing.overload
        def __init__(self, proxyConfig: ProxyConfig, /) -> None: ...
        def addBypassRule(self, bypassRule: str | java.lang.String, /) -> ProxyConfig.Builder: ...
        @typing.overload
        def addDirect(self) -> ProxyConfig.Builder: ...
        @typing.overload
        def addDirect(self, schemeFilter: str | java.lang.String, /) -> ProxyConfig.Builder: ...
        @typing.overload
        def addProxyRule(self, proxyUrl: str | java.lang.String, /) -> ProxyConfig.Builder: ...
        @typing.overload
        def addProxyRule(self, proxyUrl: str | java.lang.String, schemeFilter: str | java.lang.String, /) -> ProxyConfig.Builder: ...
        def build(self) -> ProxyConfig: ...
        def bypassSimpleHostnames(self) -> ProxyConfig.Builder: ...
        def removeImplicitRules(self) -> ProxyConfig.Builder: ...
        def setReverseBypassEnabled(self, reverseBypass: bool | java.jboolean | java.lang.Boolean, /) -> ProxyConfig.Builder: ...

    class ProxyRule(java.lang.Object):
        @typing.overload
        def __init__(self, url: str | java.lang.String, /) -> None: ...
        @typing.overload
        def __init__(self, schemeFilter: str | java.lang.String, url: str | java.lang.String, /) -> None: ...
        def getSchemeFilter(self) -> str: ...
        def getUrl(self) -> str: ...

    class ProxyScheme(java.lang.annotation.Annotation): ...

class ProxyController(java.lang.Object):
    def __init__(self) -> None: ...
    def clearProxyOverride(self, arg1: java.util.concurrent.Executor, arg2: java.lang.Runnable, /) -> None: ...
    @staticmethod
    def getInstance() -> ProxyController: ...
    def setProxyOverride(self, arg1: ProxyConfig, arg2: java.util.concurrent.Executor, arg3: java.lang.Runnable, /) -> None: ...

class RestrictionAllowlist(java.lang.Object):

    class Builder(java.lang.Object):
        def __init__(self, originPatterns: java.util.Set[java.lang.String], /) -> None: ...
        def addJavaScriptInterface(self, object: java.lang.Object | int | bool | float | str, name: str | java.lang.String, /) -> RestrictionAllowlist.Builder: ...
        def build(self) -> RestrictionAllowlist: ...

class SafeBrowsingResponseCompat(java.lang.Object):
    def __init__(self) -> None: ...
    def backToSafety(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def proceed(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def showInterstitial(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class ScriptHandler(java.lang.Object):
    def remove(self) -> None: ...

class ServiceWorkerClientCompat(java.lang.Object):
    def __init__(self) -> None: ...
    def shouldInterceptRequest(self, arg1: android.webkit.WebResourceRequest, /) -> android.webkit.WebResourceResponse: ...

class ServiceWorkerControllerCompat(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def getInstance() -> ServiceWorkerControllerCompat: ...
    def getServiceWorkerWebSettings(self) -> ServiceWorkerWebSettingsCompat: ...
    def setServiceWorkerClient(self, arg1: ServiceWorkerClientCompat, /) -> None: ...

class ServiceWorkerWebSettingsCompat(java.lang.Object):
    def __init__(self) -> None: ...
    def getAllowContentAccess(self) -> bool: ...
    def getAllowFileAccess(self) -> bool: ...
    def getBlockNetworkLoads(self) -> bool: ...
    def getCacheMode(self) -> int: ...
    def getRequestedWithHeaderOriginAllowList(self) -> java.util.Set[java.lang.String]: ...
    def isIncludeCookiesOnShouldInterceptRequestEnabled(self) -> bool: ...
    def setAllowContentAccess(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setAllowFileAccess(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setBlockNetworkLoads(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setCacheMode(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
    def setIncludeCookiesOnShouldInterceptRequestEnabled(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setRequestedWithHeaderOriginAllowList(self, arg1: java.util.Set[java.lang.String], /) -> None: ...

    class CacheMode(java.lang.annotation.Annotation): ...

class SpeculativeLoadingConfig(java.lang.Object):
    def getMaxPrefetches(self) -> int: ...
    def getMaxPrerenders(self) -> int: ...
    def getPrefetchTtlSeconds(self) -> int: ...

    class Builder(java.lang.Object):
        def __init__(self) -> None: ...
        def build(self) -> SpeculativeLoadingConfig: ...
        def setMaxPrefetches(self, max: int | java.jint | java.lang.Integer, /) -> SpeculativeLoadingConfig.Builder: ...
        def setMaxPrerenders(self, max: int | java.jint | java.lang.Integer, /) -> SpeculativeLoadingConfig.Builder: ...
        def setPrefetchTtlSeconds(self, ttlSeconds: int | java.jint | java.lang.Integer, /) -> SpeculativeLoadingConfig.Builder: ...

class SpeculativeLoadingParameters(java.lang.Object):
    def getAdditionalHeaders(self) -> java.util.Map[java.lang.String, java.lang.String]: ...
    def getExpectedNoVarySearchData(self) -> NoVarySearchHeader: ...
    def isJavaScriptEnabled(self) -> bool: ...

    class Builder(java.lang.Object):
        def __init__(self) -> None: ...
        def addAdditionalHeader(self, key: str | java.lang.String, value: str | java.lang.String, /) -> SpeculativeLoadingParameters.Builder: ...
        def addAdditionalHeaders(self, additionalHeaders: java.util.Map[java.lang.String, java.lang.String], /) -> SpeculativeLoadingParameters.Builder: ...
        def build(self) -> SpeculativeLoadingParameters: ...
        def setExpectedNoVarySearchData(self, expectedNoVarySearchHeader: NoVarySearchHeader, /) -> SpeculativeLoadingParameters.Builder: ...
        def setJavaScriptEnabled(self, javaScriptEnabled: bool | java.jboolean | java.lang.Boolean, /) -> SpeculativeLoadingParameters.Builder: ...

class StartUpLocation(java.lang.Object):
    def getStackInformation(self) -> str: ...

class TracingConfig(java.lang.Object):
    CATEGORIES_NONE: typing.ClassVar[int] = ...
    CATEGORIES_ALL: typing.ClassVar[int] = ...
    CATEGORIES_ANDROID_WEBVIEW: typing.ClassVar[int] = ...
    CATEGORIES_WEB_DEVELOPER: typing.ClassVar[int] = ...
    CATEGORIES_INPUT_LATENCY: typing.ClassVar[int] = ...
    CATEGORIES_RENDERING: typing.ClassVar[int] = ...
    CATEGORIES_JAVASCRIPT_AND_RENDERING: typing.ClassVar[int] = ...
    CATEGORIES_FRAME_VIEWER: typing.ClassVar[int] = ...
    RECORD_UNTIL_FULL: typing.ClassVar[int] = ...
    RECORD_CONTINUOUSLY: typing.ClassVar[int] = ...
    def __init__(self, predefinedCategories: int | java.jint | java.lang.Integer, customIncludedCategories: java.util.List[java.lang.String], tracingMode: int | java.jint | java.lang.Integer, /) -> None: ...
    def getCustomIncludedCategories(self) -> java.util.List[java.lang.String]: ...
    def getPredefinedCategories(self) -> int: ...
    def getTracingMode(self) -> int: ...

    class Builder(java.lang.Object):
        def __init__(self) -> None: ...
        @typing.overload
        def addCategories(self, categories: java.util.Collection[java.lang.String], /) -> TracingConfig.Builder: ...
        @typing.overload
        def addCategories(self, *predefinedCategories: java.chaquopy.JavaArrayJInt) -> TracingConfig.Builder: ...
        @typing.overload
        def addCategories(self, *categories: java.lang.String) -> TracingConfig.Builder: ...
        def build(self) -> TracingConfig: ...
        def setTracingMode(self, tracingMode: int | java.jint | java.lang.Integer, /) -> TracingConfig.Builder: ...

    class TracingMode(java.lang.annotation.Annotation): ...

    class PredefinedCategories(java.lang.annotation.Annotation): ...

class TracingController(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def getInstance() -> TracingController: ...
    def isTracing(self) -> bool: ...
    def start(self, arg1: TracingConfig, /) -> None: ...
    def stop(self, arg1: java.io.OutputStream, arg2: java.util.concurrent.Executor, /) -> bool: ...

class URLUtilCompat(java.lang.Object):
    @staticmethod
    def getFilenameFromContentDisposition(contentDisposition: str | java.lang.String, /) -> str: ...
    @staticmethod
    def guessFileName(url: str | java.lang.String, contentDisposition: str | java.lang.String, mimeType: str | java.lang.String, /) -> str: ...

class UserAgentMetadata(java.lang.Object):
    BITNESS_DEFAULT: typing.ClassVar[int] = ...
    FORM_FACTOR_DESKTOP: typing.ClassVar[str] = ...
    FORM_FACTOR_AUTOMOTIVE: typing.ClassVar[str] = ...
    FORM_FACTOR_MOBILE: typing.ClassVar[str] = ...
    FORM_FACTOR_TABLET: typing.ClassVar[str] = ...
    FORM_FACTOR_XR: typing.ClassVar[str] = ...
    FORM_FACTOR_EINK: typing.ClassVar[str] = ...
    FORM_FACTOR_WATCH: typing.ClassVar[str] = ...
    def equals(self, o: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getArchitecture(self) -> str: ...
    def getBitness(self) -> int: ...
    def getBrandVersionList(self) -> java.util.List[UserAgentMetadata.BrandVersion]: ...
    def getFormFactors(self) -> java.util.List[java.lang.String]: ...
    def getFullVersion(self) -> str: ...
    def getModel(self) -> str: ...
    def getPlatform(self) -> str: ...
    def getPlatformVersion(self) -> str: ...
    def hashCode(self) -> int: ...
    def isMobile(self) -> bool: ...
    def isWow64(self) -> bool: ...

    class Builder(java.lang.Object):
        @typing.overload
        def __init__(self) -> None: ...
        @typing.overload
        def __init__(self, uaMetadata: UserAgentMetadata, /) -> None: ...
        def build(self) -> UserAgentMetadata: ...
        def setArchitecture(self, architecture: str | java.lang.String, /) -> UserAgentMetadata.Builder: ...
        def setBitness(self, bitness: int | java.jint | java.lang.Integer, /) -> UserAgentMetadata.Builder: ...
        def setBrandVersionList(self, brandVersions: java.util.List[UserAgentMetadata.BrandVersion], /) -> UserAgentMetadata.Builder: ...
        def setFormFactors(self, formFactors: java.util.List[java.lang.String], /) -> UserAgentMetadata.Builder: ...
        def setFullVersion(self, fullVersion: str | java.lang.String, /) -> UserAgentMetadata.Builder: ...
        def setMobile(self, mobile: bool | java.jboolean | java.lang.Boolean, /) -> UserAgentMetadata.Builder: ...
        def setModel(self, model: str | java.lang.String, /) -> UserAgentMetadata.Builder: ...
        def setPlatform(self, platform: str | java.lang.String, /) -> UserAgentMetadata.Builder: ...
        def setPlatformVersion(self, platformVersion: str | java.lang.String, /) -> UserAgentMetadata.Builder: ...
        def setWow64(self, wow64: bool | java.jboolean | java.lang.Boolean, /) -> UserAgentMetadata.Builder: ...

    class BrandVersion(java.lang.Object):
        def equals(self, o: java.lang.Object | int | bool | float | str, /) -> bool: ...
        def getBrand(self) -> str: ...
        def getFullVersion(self) -> str: ...
        def getMajorVersion(self) -> str: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...

        class Builder(java.lang.Object):
            @typing.overload
            def __init__(self) -> None: ...
            @typing.overload
            def __init__(self, brandVersion: UserAgentMetadata.BrandVersion, /) -> None: ...
            def build(self) -> UserAgentMetadata.BrandVersion: ...
            def setBrand(self, brand: str | java.lang.String, /) -> UserAgentMetadata.BrandVersion.Builder: ...
            def setFullVersion(self, fullVersion: str | java.lang.String, /) -> UserAgentMetadata.BrandVersion.Builder: ...
            def setMajorVersion(self, majorVersion: str | java.lang.String, /) -> UserAgentMetadata.BrandVersion.Builder: ...

    class FormFactors(java.lang.annotation.Annotation): ...

class WebMessageCompat(java.lang.Object):
    TYPE_STRING: typing.ClassVar[int] = ...
    TYPE_ARRAY_BUFFER: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, data: str | java.lang.String, /) -> None: ...
    @typing.overload
    def __init__(self, arrayBuffer: java.chaquopy.JavaArrayJByte, /) -> None: ...
    @typing.overload
    def __init__(self, data: str | java.lang.String, ports: java.chaquopy.JavaArray[WebMessagePortCompat], /) -> None: ...
    @typing.overload
    def __init__(self, arrayBuffer: java.chaquopy.JavaArrayJByte, ports: java.chaquopy.JavaArray[WebMessagePortCompat], /) -> None: ...
    def getArrayBuffer(self) -> java.chaquopy.JavaArrayJByte: ...
    def getData(self) -> str: ...
    def getPorts(self) -> java.chaquopy.JavaArray[WebMessagePortCompat]: ...
    def getType(self) -> int: ...

    class Type(java.lang.annotation.Annotation): ...

class WebMessagePortCompat(java.lang.Object):
    def __init__(self) -> None: ...
    def close(self) -> None: ...
    def getFrameworkPort(self) -> android.webkit.WebMessagePort: ...
    def getInvocationHandler(self) -> java.lang.reflect.InvocationHandler: ...
    def postMessage(self, arg1: WebMessageCompat, /) -> None: ...
    @typing.overload
    def setWebMessageCallback(self, arg1: WebMessagePortCompat.WebMessageCallbackCompat, /) -> None: ...
    @typing.overload
    def setWebMessageCallback(self, arg1: android.os.Handler, arg2: WebMessagePortCompat.WebMessageCallbackCompat, /) -> None: ...

    class WebMessageCallbackCompat(java.lang.Object):
        def __init__(self) -> None: ...
        def onMessage(self, port: WebMessagePortCompat, message: WebMessageCompat, /) -> None: ...

class WebNavigationClient(java.lang.Object):
    def onFirstContentfulPaint(self, arg1: Page, /) -> None: ...
    def onNavigationCompleted(self, arg1: Navigation, /) -> None: ...
    def onNavigationRedirected(self, arg1: Navigation, /) -> None: ...
    def onNavigationStarted(self, arg1: Navigation, /) -> None: ...
    def onPageDeleted(self, arg1: Page, /) -> None: ...
    def onPageDomContentLoadedEventFired(self, arg1: Page, /) -> None: ...
    def onPageLoadEventFired(self, arg1: Page, /) -> None: ...

    class ExperimentalNavigationCallback(java.lang.annotation.Annotation): ...

class WebResourceErrorCompat(java.lang.Object):
    def __init__(self) -> None: ...
    def getDescription(self) -> java.lang.CharSequence: ...
    def getErrorCode(self) -> int: ...

    class NetErrorCode(java.lang.annotation.Annotation): ...

class WebResourceRequestCompat(java.lang.Object):
    @staticmethod
    def isRedirect(request: android.webkit.WebResourceRequest, /) -> bool: ...

class WebResourceResponseCompat(java.lang.Object):
    @typing.overload
    def __init__(self, mimeType: str | java.lang.String, encoding: str | java.lang.String, data: java.io.InputStream, /) -> None: ...
    @typing.overload
    def __init__(self, mimeType: str | java.lang.String, encoding: str | java.lang.String, statusCode: int | java.jint | java.lang.Integer, reasonPhrase: str | java.lang.String, responseHeaders: java.util.Map[java.lang.String, java.lang.String], data: java.io.InputStream, /) -> None: ...
    def getCookies(self) -> java.util.List[java.lang.String]: ...
    def getData(self) -> java.io.InputStream: ...
    def getEncoding(self) -> str: ...
    def getMimeType(self) -> str: ...
    def getReasonPhrase(self) -> str: ...
    def getResponseHeaders(self) -> java.util.Map[java.lang.String, java.lang.String]: ...
    def getStatusCode(self) -> int: ...
    def setCookies(self, cookies: java.util.List[java.lang.String], /) -> None: ...
    def setData(self, data: java.io.InputStream, /) -> None: ...
    def setEncoding(self, encoding: str | java.lang.String, /) -> None: ...
    def setMimeType(self, mimeType: str | java.lang.String, /) -> None: ...
    def setResponseHeaders(self, headers: java.util.Map[java.lang.String, java.lang.String], /) -> None: ...
    def setStatusCodeAndReasonPhrase(self, statusCode: int | java.jint | java.lang.Integer, reasonPhrase: str | java.lang.String, /) -> None: ...
    def toWebResourceResponse(self) -> android.webkit.WebResourceResponse: ...
    @staticmethod
    def toWebResourceResponseCompat(response: android.webkit.WebResourceResponse, /) -> WebResourceResponseCompat: ...

class WebSettingsCompat(java.lang.Object):
    FORCE_DARK_OFF: typing.ClassVar[int] = ...
    FORCE_DARK_AUTO: typing.ClassVar[int] = ...
    FORCE_DARK_ON: typing.ClassVar[int] = ...
    DARK_STRATEGY_USER_AGENT_DARKENING_ONLY: typing.ClassVar[int] = ...
    DARK_STRATEGY_WEB_THEME_DARKENING_ONLY: typing.ClassVar[int] = ...
    DARK_STRATEGY_PREFER_WEB_THEME_OVER_USER_AGENT_DARKENING: typing.ClassVar[int] = ...
    ATTRIBUTION_BEHAVIOR_DISABLED: typing.ClassVar[int] = ...
    ATTRIBUTION_BEHAVIOR_APP_SOURCE_AND_WEB_TRIGGER: typing.ClassVar[int] = ...
    ATTRIBUTION_BEHAVIOR_WEB_SOURCE_AND_WEB_TRIGGER: typing.ClassVar[int] = ...
    ATTRIBUTION_BEHAVIOR_APP_SOURCE_AND_APP_TRIGGER: typing.ClassVar[int] = ...
    WEB_AUTHENTICATION_SUPPORT_NONE: typing.ClassVar[int] = ...
    WEB_AUTHENTICATION_SUPPORT_FOR_APP: typing.ClassVar[int] = ...
    WEB_AUTHENTICATION_SUPPORT_FOR_BROWSER: typing.ClassVar[int] = ...
    SPECULATIVE_LOADING_DISABLED: typing.ClassVar[int] = ...
    SPECULATIVE_LOADING_PRERENDER_ENABLED: typing.ClassVar[int] = ...
    @staticmethod
    def areCookiesIncludedInShouldInterceptRequest(settings: android.webkit.WebSettings, /) -> bool: ...
    @staticmethod
    def getAttributionRegistrationBehavior(settings: android.webkit.WebSettings, /) -> int: ...
    @staticmethod
    def getBackForwardCacheEnabled(settings: android.webkit.WebSettings, /) -> bool: ...
    @staticmethod
    def getBackForwardCacheSettings(settings: android.webkit.WebSettings, /) -> BackForwardCacheSettings: ...
    @staticmethod
    def getDisabledActionModeMenuItems(settings: android.webkit.WebSettings, /) -> int: ...
    @staticmethod
    def getEnterpriseAuthenticationAppLinkPolicyEnabled(settings: android.webkit.WebSettings, /) -> bool: ...
    @staticmethod
    def getForceDark(settings: android.webkit.WebSettings, /) -> int: ...
    @staticmethod
    def getForceDarkStrategy(settings: android.webkit.WebSettings, /) -> int: ...
    @staticmethod
    def getHasEnrolledInstrumentEnabled(settings: android.webkit.WebSettings, /) -> bool: ...
    @staticmethod
    def getOffscreenPreRaster(settings: android.webkit.WebSettings, /) -> bool: ...
    @staticmethod
    def getPaymentRequestEnabled(settings: android.webkit.WebSettings, /) -> bool: ...
    @staticmethod
    def getRequestedWithHeaderOriginAllowList(settings: android.webkit.WebSettings, /) -> java.util.Set[java.lang.String]: ...
    @staticmethod
    def getSafeBrowsingEnabled(settings: android.webkit.WebSettings, /) -> bool: ...
    @staticmethod
    def getSpeculativeLoadingStatus(settings: android.webkit.WebSettings, /) -> int: ...
    @staticmethod
    def getUserAgentMetadata(settings: android.webkit.WebSettings, /) -> UserAgentMetadata: ...
    @staticmethod
    def getWebAuthenticationSupport(settings: android.webkit.WebSettings, /) -> int: ...
    @staticmethod
    def getWebViewMediaIntegrityApiStatus(settings: android.webkit.WebSettings, /) -> WebViewMediaIntegrityApiStatusConfig: ...
    @staticmethod
    def isAlgorithmicDarkeningAllowed(settings: android.webkit.WebSettings, /) -> bool: ...
    @staticmethod
    def setAlgorithmicDarkeningAllowed(settings: android.webkit.WebSettings, allow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def setAttributionRegistrationBehavior(settings: android.webkit.WebSettings, behavior: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setBackForwardCacheEnabled(settings: android.webkit.WebSettings, backForwardCacheEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def setBackForwardCacheSettings(settings: android.webkit.WebSettings, backForwardCacheSettings: BackForwardCacheSettings, /) -> None: ...
    @staticmethod
    def setCookiesIncludedInShouldInterceptRequest(settings: android.webkit.WebSettings, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def setDisabledActionModeMenuItems(settings: android.webkit.WebSettings, menuItems: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setEnterpriseAuthenticationAppLinkPolicyEnabled(settings: android.webkit.WebSettings, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def setForceDark(settings: android.webkit.WebSettings, forceDarkMode: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setForceDarkStrategy(settings: android.webkit.WebSettings, forceDarkBehavior: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setHasEnrolledInstrumentEnabled(settings: android.webkit.WebSettings, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def setHyperlinkContextMenuItems(settings: android.webkit.WebSettings, hyperlinkMenuItems: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setOffscreenPreRaster(settings: android.webkit.WebSettings, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def setPaymentRequestEnabled(settings: android.webkit.WebSettings, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def setRequestedWithHeaderOriginAllowList(settings: android.webkit.WebSettings, allowList: java.util.Set[java.lang.String], /) -> None: ...
    @staticmethod
    def setSafeBrowsingEnabled(settings: android.webkit.WebSettings, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def setSpeculativeLoadingStatus(settings: android.webkit.WebSettings, speculativeLoadingStatus: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setUserAgentMetadata(settings: android.webkit.WebSettings, metadata: UserAgentMetadata, /) -> None: ...
    @staticmethod
    def setWebAuthenticationSupport(settings: android.webkit.WebSettings, support: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setWebViewMediaIntegrityApiStatus(settings: android.webkit.WebSettings, permissionConfig: WebViewMediaIntegrityApiStatusConfig, /) -> None: ...

    class HyperlinkContextMenuItems(java.lang.annotation.Annotation):
        DISABLED: typing.ClassVar[int] = ...
        COPY_LINK_ADDRESS: typing.ClassVar[int] = ...
        COPY_LINK_TEXT: typing.ClassVar[int] = ...
        OPEN_LINK: typing.ClassVar[int] = ...

    class ExperimentalBackForwardCacheSettings(java.lang.annotation.Annotation): ...

    class ExperimentalSpeculativeLoading(java.lang.annotation.Annotation): ...

    class ForceDarkStrategy(java.lang.annotation.Annotation): ...

    class ForceDark(java.lang.annotation.Annotation): ...

    class MenuItemFlags(java.lang.annotation.Annotation): ...

class WebStorageCompat(java.lang.Object):
    @typing.overload
    @staticmethod
    def deleteBrowsingData(instance: android.webkit.WebStorage, doneCallback: java.lang.Runnable, /) -> None: ...
    @typing.overload
    @staticmethod
    def deleteBrowsingData(instance: android.webkit.WebStorage, executor: java.util.concurrent.Executor, doneCallback: java.lang.Runnable, /) -> None: ...
    @typing.overload
    @staticmethod
    def deleteBrowsingDataForSite(instance: android.webkit.WebStorage, site: str | java.lang.String, doneCallback: java.lang.Runnable, /) -> str: ...
    @typing.overload
    @staticmethod
    def deleteBrowsingDataForSite(instance: android.webkit.WebStorage, site: str | java.lang.String, executor: java.util.concurrent.Executor, doneCallback: java.lang.Runnable, /) -> str: ...

class WebViewAssetLoader(java.lang.Object):
    DEFAULT_DOMAIN: typing.ClassVar[str] = ...
    def shouldInterceptRequest(self, url: android.net.Uri, /) -> android.webkit.WebResourceResponse: ...

    class PathHandler(java.lang.Object):
        def handle(self, arg1: str | java.lang.String, /) -> android.webkit.WebResourceResponse: ...

    class Builder(java.lang.Object):
        def __init__(self) -> None: ...
        def addPathHandler(self, path: str | java.lang.String, handler: WebViewAssetLoader.PathHandler, /) -> WebViewAssetLoader.Builder: ...
        def build(self) -> WebViewAssetLoader: ...
        def setDomain(self, domain: str | java.lang.String, /) -> WebViewAssetLoader.Builder: ...
        def setHttpAllowed(self, httpAllowed: bool | java.jboolean | java.lang.Boolean, /) -> WebViewAssetLoader.Builder: ...

    class InternalStoragePathHandler(androidx.webkit.WebViewAssetLoader.PathHandler):
        def __init__(self, context: android.content.Context, directory: java.io.File, /) -> None: ...
        def handle(self, path: str | java.lang.String, /) -> android.webkit.WebResourceResponse: ...

    class ResourcesPathHandler(androidx.webkit.WebViewAssetLoader.PathHandler):
        def __init__(self, context: android.content.Context, /) -> None: ...
        def handle(self, path: str | java.lang.String, /) -> android.webkit.WebResourceResponse: ...

    class AssetsPathHandler(androidx.webkit.WebViewAssetLoader.PathHandler):
        def __init__(self, context: android.content.Context, /) -> None: ...
        def handle(self, path: str | java.lang.String, /) -> android.webkit.WebResourceResponse: ...

class WebViewBuilder(java.lang.Object):
    PRESET_LEGACY: typing.ClassVar[int] = ...
    def __init__(self, preset: int | java.jint | java.lang.Integer, /) -> None: ...
    def addAllowlist(self, allowList: RestrictionAllowlist, /) -> WebViewBuilder: ...
    def build(self, context: android.content.Context, /) -> android.webkit.WebView: ...
    def restrictJavaScriptInterfaces(self) -> WebViewBuilder: ...
    def setProfile(self, profileName: str | java.lang.String, /) -> WebViewBuilder: ...

    class Preset(java.lang.annotation.Annotation): ...

    class Experimental(java.lang.annotation.Annotation): ...

class WebViewBuilderException(java.lang.RuntimeException): ...

class WebViewClientCompat(android.webkit.WebViewClient, org.chromium.support_lib_boundary.WebViewClientBoundaryInterface):
    def __init__(self) -> None: ...
    def getSupportedFeatures(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    def onPageCommitVisible(self, view: android.webkit.WebView, url: str | java.lang.String, /) -> None: ...
    @typing.overload
    def onReceivedError(self, view: android.webkit.WebView, request: android.webkit.WebResourceRequest, error: android.webkit.WebResourceError, /) -> None: ...
    @typing.overload
    def onReceivedError(self, view: android.webkit.WebView, request: android.webkit.WebResourceRequest, error: WebResourceErrorCompat, /) -> None: ...
    @typing.overload
    def onReceivedError(self, view: android.webkit.WebView, request: android.webkit.WebResourceRequest, handler: java.lang.reflect.InvocationHandler, /) -> None: ...
    def onReceivedHttpError(self, view: android.webkit.WebView, request: android.webkit.WebResourceRequest, errorResponse: android.webkit.WebResourceResponse, /) -> None: ...
    @typing.overload
    def onSafeBrowsingHit(self, view: android.webkit.WebView, request: android.webkit.WebResourceRequest, threatType: int | java.jint | java.lang.Integer, response: android.webkit.SafeBrowsingResponse, /) -> None: ...
    @typing.overload
    def onSafeBrowsingHit(self, view: android.webkit.WebView, request: android.webkit.WebResourceRequest, threatType: int | java.jint | java.lang.Integer, callback: SafeBrowsingResponseCompat, /) -> None: ...
    @typing.overload
    def onSafeBrowsingHit(self, view: android.webkit.WebView, request: android.webkit.WebResourceRequest, threatType: int | java.jint | java.lang.Integer, handler: java.lang.reflect.InvocationHandler, /) -> None: ...
    def onWebAuthnIntent(self, view: android.webkit.WebView, intent: android.app.PendingIntent, callback: java.lang.reflect.InvocationHandler, /) -> bool: ...
    def shouldOverrideUrlLoading(self, view: android.webkit.WebView, request: android.webkit.WebResourceRequest, /) -> bool: ...

    class SafeBrowsingThreat(java.lang.annotation.Annotation): ...

class WebViewCompat(java.lang.Object):
    @staticmethod
    def addDocumentStartJavaScript(webview: android.webkit.WebView, script: str | java.lang.String, allowedOriginRules: java.util.Set[java.lang.String], /) -> ScriptHandler: ...
    @typing.overload
    @staticmethod
    def addNavigationListener(webView: android.webkit.WebView, listener: NavigationListener, /) -> None: ...
    @typing.overload
    @staticmethod
    def addNavigationListener(webView: android.webkit.WebView, executor: java.util.concurrent.Executor, listener: NavigationListener, /) -> None: ...
    @staticmethod
    def addWebMessageListener(webView: android.webkit.WebView, jsObjectName: str | java.lang.String, allowedOriginRules: java.util.Set[java.lang.String], listener: WebViewCompat.WebMessageListener, /) -> None: ...
    @staticmethod
    def createWebMessageChannel(webview: android.webkit.WebView, /) -> java.chaquopy.JavaArray[WebMessagePortCompat]: ...
    @staticmethod
    def getCurrentLoadedWebViewPackage() -> android.content.pm.PackageInfo: ...
    @staticmethod
    def getCurrentWebViewPackage(context: android.content.Context, /) -> android.content.pm.PackageInfo: ...
    @staticmethod
    def getProfile(webView: android.webkit.WebView, /) -> Profile: ...
    @staticmethod
    def getSafeBrowsingPrivacyPolicyUrl() -> android.net.Uri: ...
    @staticmethod
    def getVariationsHeader() -> str: ...
    @staticmethod
    def getWebChromeClient(webview: android.webkit.WebView, /) -> android.webkit.WebChromeClient: ...
    @staticmethod
    def getWebNavigationClient(webView: android.webkit.WebView, /) -> WebNavigationClient: ...
    @staticmethod
    def getWebViewClient(webview: android.webkit.WebView, /) -> android.webkit.WebViewClient: ...
    @staticmethod
    def getWebViewRenderProcess(webview: android.webkit.WebView, /) -> WebViewRenderProcess: ...
    @staticmethod
    def getWebViewRenderProcessClient(webview: android.webkit.WebView, /) -> WebViewRenderProcessClient: ...
    @staticmethod
    def isAudioMuted(webView: android.webkit.WebView, /) -> bool: ...
    @staticmethod
    def isMultiProcessEnabled() -> bool: ...
    @staticmethod
    def postVisualStateCallback(webview: android.webkit.WebView, requestId: int | java.jlong | java.lang.Long, callback: WebViewCompat.VisualStateCallback, /) -> None: ...
    @staticmethod
    def postWebMessage(webview: android.webkit.WebView, message: WebMessageCompat, targetOrigin: android.net.Uri, /) -> None: ...
    @typing.overload
    @staticmethod
    def prerenderUrlAsync(webView: android.webkit.WebView, url: str | java.lang.String, cancellationSignal: android.os.CancellationSignal, callbackExecutor: java.util.concurrent.Executor, callback: PrerenderOperationCallback, /) -> None: ...
    @typing.overload
    @staticmethod
    def prerenderUrlAsync(webView: android.webkit.WebView, url: str | java.lang.String, cancellationSignal: android.os.CancellationSignal, callbackExecutor: java.util.concurrent.Executor, params: SpeculativeLoadingParameters, callback: PrerenderOperationCallback, /) -> None: ...
    @staticmethod
    def removeNavigationListener(webView: android.webkit.WebView, listener: NavigationListener, /) -> None: ...
    @staticmethod
    def removeWebMessageListener(webview: android.webkit.WebView, jsObjectName: str | java.lang.String, /) -> None: ...
    @staticmethod
    def saveState(webView: android.webkit.WebView, outState: android.os.Bundle, maxSizeBytes: int | java.jint | java.lang.Integer, includeForwardState: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def setAudioMuted(webView: android.webkit.WebView, mute: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def setDefaultTrafficStatsTag(tag: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setProfile(webView: android.webkit.WebView, profileName: str | java.lang.String, /) -> None: ...
    @staticmethod
    def setSafeBrowsingAllowlist(hosts: java.util.Set[java.lang.String], callback: android.webkit.ValueCallback[java.lang.Boolean], /) -> None: ...
    @staticmethod
    def setSafeBrowsingWhitelist(hosts: java.util.List[java.lang.String], callback: android.webkit.ValueCallback[java.lang.Boolean], /) -> None: ...
    @staticmethod
    def setWebNavigationClient(webView: android.webkit.WebView, client: WebNavigationClient, /) -> None: ...
    @typing.overload
    @staticmethod
    def setWebViewRenderProcessClient(webview: android.webkit.WebView, webViewRenderProcessClient: WebViewRenderProcessClient, /) -> None: ...
    @typing.overload
    @staticmethod
    def setWebViewRenderProcessClient(webview: android.webkit.WebView, executor: java.util.concurrent.Executor, webViewRenderProcessClient: WebViewRenderProcessClient, /) -> None: ...
    @staticmethod
    def startSafeBrowsing(context: android.content.Context, callback: android.webkit.ValueCallback[java.lang.Boolean], /) -> None: ...
    @staticmethod
    def startUpWebView(context: android.content.Context, config: WebViewStartUpConfig, callback: WebViewCompat.WebViewStartUpCallback, /) -> None: ...

    class VisualStateCallback(java.lang.Object):
        def onComplete(self, arg1: int | java.jlong | java.lang.Long, /) -> None: ...

    class WebMessageListener(java.lang.Object):
        def onPostMessage(self, arg1: android.webkit.WebView, arg2: WebMessageCompat, arg3: android.net.Uri, arg4: bool | java.jboolean | java.lang.Boolean, arg5: JavaScriptReplyProxy, /) -> None: ...

    class WebViewStartUpCallback(java.lang.Object):
        def onSuccess(self, arg1: WebViewStartUpResult, /) -> None: ...

    class ExperimentalSaveState(java.lang.annotation.Annotation): ...

    class ExperimentalAsyncStartUp(java.lang.annotation.Annotation): ...

class WebViewFeature(java.lang.Object):
    VISUAL_STATE_CALLBACK: typing.ClassVar[str] = ...
    OFF_SCREEN_PRERASTER: typing.ClassVar[str] = ...
    SAFE_BROWSING_ENABLE: typing.ClassVar[str] = ...
    DISABLED_ACTION_MODE_MENU_ITEMS: typing.ClassVar[str] = ...
    START_SAFE_BROWSING: typing.ClassVar[str] = ...
    SAFE_BROWSING_ALLOWLIST: typing.ClassVar[str] = ...
    SAFE_BROWSING_WHITELIST: typing.ClassVar[str] = ...
    SAFE_BROWSING_PRIVACY_POLICY_URL: typing.ClassVar[str] = ...
    SERVICE_WORKER_BASIC_USAGE: typing.ClassVar[str] = ...
    SERVICE_WORKER_CACHE_MODE: typing.ClassVar[str] = ...
    SERVICE_WORKER_CONTENT_ACCESS: typing.ClassVar[str] = ...
    SERVICE_WORKER_FILE_ACCESS: typing.ClassVar[str] = ...
    SERVICE_WORKER_BLOCK_NETWORK_LOADS: typing.ClassVar[str] = ...
    SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST: typing.ClassVar[str] = ...
    RECEIVE_WEB_RESOURCE_ERROR: typing.ClassVar[str] = ...
    RECEIVE_HTTP_ERROR: typing.ClassVar[str] = ...
    SHOULD_OVERRIDE_WITH_REDIRECTS: typing.ClassVar[str] = ...
    SAFE_BROWSING_HIT: typing.ClassVar[str] = ...
    TRACING_CONTROLLER_BASIC_USAGE: typing.ClassVar[str] = ...
    WEB_RESOURCE_REQUEST_IS_REDIRECT: typing.ClassVar[str] = ...
    WEB_RESOURCE_ERROR_GET_DESCRIPTION: typing.ClassVar[str] = ...
    WEB_RESOURCE_ERROR_GET_CODE: typing.ClassVar[str] = ...
    SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY: typing.ClassVar[str] = ...
    SAFE_BROWSING_RESPONSE_PROCEED: typing.ClassVar[str] = ...
    SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL: typing.ClassVar[str] = ...
    WEB_MESSAGE_PORT_POST_MESSAGE: typing.ClassVar[str] = ...
    WEB_MESSAGE_PORT_CLOSE: typing.ClassVar[str] = ...
    WEB_MESSAGE_ARRAY_BUFFER: typing.ClassVar[str] = ...
    WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK: typing.ClassVar[str] = ...
    CREATE_WEB_MESSAGE_CHANNEL: typing.ClassVar[str] = ...
    POST_WEB_MESSAGE: typing.ClassVar[str] = ...
    WEB_MESSAGE_CALLBACK_ON_MESSAGE: typing.ClassVar[str] = ...
    GET_WEB_VIEW_CLIENT: typing.ClassVar[str] = ...
    GET_WEB_CHROME_CLIENT: typing.ClassVar[str] = ...
    GET_WEB_VIEW_RENDERER: typing.ClassVar[str] = ...
    WEB_VIEW_RENDERER_TERMINATE: typing.ClassVar[str] = ...
    WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE: typing.ClassVar[str] = ...
    PROXY_OVERRIDE: typing.ClassVar[str] = ...
    MULTI_PROCESS: typing.ClassVar[str] = ...
    FORCE_DARK: typing.ClassVar[str] = ...
    FORCE_DARK_STRATEGY: typing.ClassVar[str] = ...
    ALGORITHMIC_DARKENING: typing.ClassVar[str] = ...
    WEB_MESSAGE_LISTENER: typing.ClassVar[str] = ...
    DOCUMENT_START_SCRIPT: typing.ClassVar[str] = ...
    PROXY_OVERRIDE_REVERSE_BYPASS: typing.ClassVar[str] = ...
    GET_VARIATIONS_HEADER: typing.ClassVar[str] = ...
    ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY: typing.ClassVar[str] = ...
    GET_COOKIE_INFO: typing.ClassVar[str] = ...
    STARTUP_FEATURE_SET_DATA_DIRECTORY_SUFFIX: typing.ClassVar[str] = ...
    STARTUP_FEATURE_SET_DIRECTORY_BASE_PATHS: typing.ClassVar[str] = ...
    STARTUP_FEATURE_CONFIGURE_PARTITIONED_COOKIES: typing.ClassVar[str] = ...
    REQUESTED_WITH_HEADER_ALLOW_LIST: typing.ClassVar[str] = ...
    USER_AGENT_METADATA: typing.ClassVar[str] = ...
    USER_AGENT_METADATA_FORM_FACTORS: typing.ClassVar[str] = ...
    MULTI_PROFILE: typing.ClassVar[str] = ...
    ATTRIBUTION_REGISTRATION_BEHAVIOR: typing.ClassVar[str] = ...
    WEBVIEW_MEDIA_INTEGRITY_API_STATUS: typing.ClassVar[str] = ...
    MUTE_AUDIO: typing.ClassVar[str] = ...
    WEB_AUTHENTICATION: typing.ClassVar[str] = ...
    SPECULATIVE_LOADING: typing.ClassVar[str] = ...
    BACK_FORWARD_CACHE: typing.ClassVar[str] = ...
    BACK_FORWARD_CACHE_SETTINGS: typing.ClassVar[str] = ...
    PROFILE_URL_PREFETCH: typing.ClassVar[str] = ...
    DEFAULT_TRAFFICSTATS_TAGGING: typing.ClassVar[str] = ...
    DELETE_BROWSING_DATA: typing.ClassVar[str] = ...
    PRERENDER_WITH_URL: typing.ClassVar[str] = ...
    SPECULATIVE_LOADING_CONFIG: typing.ClassVar[str] = ...
    SAVE_STATE: typing.ClassVar[str] = ...
    NAVIGATION_CALLBACK_BASIC: typing.ClassVar[str] = ...
    NAVIGATION_LISTENER_V1: typing.ClassVar[str] = ...
    PAYMENT_REQUEST: typing.ClassVar[str] = ...
    WEBVIEW_BUILDER_EXPERIMENTAL_V1: typing.ClassVar[str] = ...
    COOKIE_INTERCEPT: typing.ClassVar[str] = ...
    WARM_UP_RENDERER_PROCESS: typing.ClassVar[str] = ...
    ORIGIN_MATCHED_HEADERS: typing.ClassVar[str] = ...
    CUSTOM_REQUEST_HEADERS: typing.ClassVar[str] = ...
    STARTUP_FEATURE_SET_PROFILES_TO_LOAD: typing.ClassVar[str] = ...
    STARTUP_FEATURE_SET_UI_THREAD_STARTUP_MODE: typing.ClassVar[str] = ...
    STARTUP_FEATURE_SET_UI_THREAD_STARTUP_MODE_V2: typing.ClassVar[str] = ...
    PRECONNECT: typing.ClassVar[str] = ...
    ADD_QUIC_HINTS_V1: typing.ClassVar[str] = ...
    HYPERLINK_CONTEXT_MENU_ITEMS: typing.ClassVar[str] = ...
    PROVIDER_WEAKLY_REF_WEBVIEW: typing.ClassVar[str] = ...
    @staticmethod
    def isFeatureSupported(feature: str | java.lang.String, /) -> bool: ...
    @staticmethod
    def isStartupFeatureSupported(context: android.content.Context, startupFeature: str | java.lang.String, /) -> bool: ...

    class WebViewStartupFeature(java.lang.annotation.Annotation): ...

    class WebViewSupportFeature(java.lang.annotation.Annotation): ...

class WebViewMediaIntegrityApiStatusConfig(java.lang.Object):
    WEBVIEW_MEDIA_INTEGRITY_API_ENABLED: typing.ClassVar[int] = ...
    WEBVIEW_MEDIA_INTEGRITY_API_ENABLED_WITHOUT_APP_IDENTITY: typing.ClassVar[int] = ...
    WEBVIEW_MEDIA_INTEGRITY_API_DISABLED: typing.ClassVar[int] = ...
    def __init__(self, builder: WebViewMediaIntegrityApiStatusConfig.Builder, /) -> None: ...
    def getDefaultStatus(self) -> int: ...
    def getOverrideRules(self) -> java.util.Map[java.lang.String, java.lang.Integer]: ...

    class Builder(java.lang.Object):
        def __init__(self, defaultStatus: int | java.jint | java.lang.Integer, /) -> None: ...
        def addOverrideRule(self, originPattern: str | java.lang.String, permission: int | java.jint | java.lang.Integer, /) -> WebViewMediaIntegrityApiStatusConfig.Builder: ...
        def build(self) -> WebViewMediaIntegrityApiStatusConfig: ...
        def setOverrideRules(self, overrideRules: java.util.Map[java.lang.String, java.lang.Integer], /) -> WebViewMediaIntegrityApiStatusConfig.Builder: ...

class WebViewRenderProcess(java.lang.Object):
    def __init__(self) -> None: ...
    def terminate(self) -> bool: ...

class WebViewRenderProcessClient(java.lang.Object):
    def __init__(self) -> None: ...
    def onRenderProcessResponsive(self, arg1: android.webkit.WebView, arg2: WebViewRenderProcess, /) -> None: ...
    def onRenderProcessUnresponsive(self, arg1: android.webkit.WebView, arg2: WebViewRenderProcess, /) -> None: ...

class WebViewStartUpConfig(java.lang.Object):
    def getBackgroundExecutor(self) -> java.util.concurrent.Executor: ...
    def getProfilesToLoadDuringStartup(self) -> java.util.Set[java.lang.String]: ...
    def shouldRunUiThreadStartUpTasks(self) -> bool: ...

    class Builder(java.lang.Object):
        def __init__(self, executor: java.util.concurrent.Executor, /) -> None: ...
        def build(self) -> WebViewStartUpConfig: ...
        def setProfilesToLoadDuringStartup(self, profiles: java.util.Set[java.lang.String], /) -> WebViewStartUpConfig.Builder: ...
        def setShouldRunUiThreadStartUpTasks(self, shouldRunUiThreadStartUpTasks: bool | java.jboolean | java.lang.Boolean, /) -> WebViewStartUpConfig.Builder: ...

class WebViewStartUpResult(java.lang.Object):
    def getMaxTimePerTaskInUiThreadMillis(self) -> int: ...
    def getNonUiThreadBlockingStartUpLocations(self) -> java.util.List[StartUpLocation]: ...
    def getTotalTimeInUiThreadMillis(self) -> int: ...
    def getUiThreadBlockingStartUpLocations(self) -> java.util.List[StartUpLocation]: ...
