import android.transition
import java.lang
import kotlin
import kotlin.jvm.functions

class TransitionKt(java.lang.Object):
    @staticmethod
    def addListener(receiver: android.transition.Transition, onEnd: kotlin.jvm.functions.Function1[android.transition.Transition, kotlin.Unit], onStart: kotlin.jvm.functions.Function1[android.transition.Transition, kotlin.Unit], onCancel: kotlin.jvm.functions.Function1[android.transition.Transition, kotlin.Unit], onResume: kotlin.jvm.functions.Function1[android.transition.Transition, kotlin.Unit], onPause: kotlin.jvm.functions.Function1[android.transition.Transition, kotlin.Unit], /) -> android.transition.Transition.TransitionListener: ...
    @staticmethod
    def doOnCancel(receiver: android.transition.Transition, action: kotlin.jvm.functions.Function1[android.transition.Transition, kotlin.Unit], /) -> android.transition.Transition.TransitionListener: ...
    @staticmethod
    def doOnEnd(receiver: android.transition.Transition, action: kotlin.jvm.functions.Function1[android.transition.Transition, kotlin.Unit], /) -> android.transition.Transition.TransitionListener: ...
    @staticmethod
    def doOnPause(receiver: android.transition.Transition, action: kotlin.jvm.functions.Function1[android.transition.Transition, kotlin.Unit], /) -> android.transition.Transition.TransitionListener: ...
    @staticmethod
    def doOnResume(receiver: android.transition.Transition, action: kotlin.jvm.functions.Function1[android.transition.Transition, kotlin.Unit], /) -> android.transition.Transition.TransitionListener: ...
    @staticmethod
    def doOnStart(receiver: android.transition.Transition, action: kotlin.jvm.functions.Function1[android.transition.Transition, kotlin.Unit], /) -> android.transition.Transition.TransitionListener: ...
