import typing

import java
import java.io
import java.lang

class OpenStreetMapTileProviderConstants(java.lang.Object):
    DEBUGMODE: typing.ClassVar[bool] = ...
    DEBUG_TILE_PROVIDERS: typing.ClassVar[bool] = ...
    USER_AGENT: typing.ClassVar[str] = ...
    MINIMUM_ZOOMLEVEL: typing.ClassVar[int] = ...
    TILE_PATH_BASE: typing.ClassVar[java.io.File] = ...
    TILE_PATH_EXTENSION: typing.ClassVar[str] = ...
    CACHE_MAPTILECOUNT_DEFAULT: typing.ClassVar[int] = ...
    NUMBER_OF_TILE_DOWNLOAD_THREADS: typing.ClassVar[int] = ...
    NUMBER_OF_TILE_FILESYSTEM_THREADS: typing.ClassVar[int] = ...
    ONE_SECOND: typing.ClassVar[int] = ...
    ONE_MINUTE: typing.ClassVar[int] = ...
    ONE_HOUR: typing.ClassVar[int] = ...
    ONE_DAY: typing.ClassVar[int] = ...
    ONE_WEEK: typing.ClassVar[int] = ...
    ONE_YEAR: typing.ClassVar[int] = ...
    DEFAULT_MAXIMUM_CACHED_FILE_AGE: typing.ClassVar[int] = ...
    TILE_DOWNLOAD_MAXIMUM_QUEUE_SIZE: typing.ClassVar[int] = ...
    TILE_FILESYSTEM_MAXIMUM_QUEUE_SIZE: typing.ClassVar[int] = ...
    TILE_EXPIRY_TIME_MILLISECONDS: typing.ClassVar[int] = ...
    TILE_MAX_CACHE_SIZE_BYTES: typing.ClassVar[int] = ...
    TILE_TRIM_CACHE_SIZE_BYTES: typing.ClassVar[int] = ...
    def __init__(self) -> None: ...
    @staticmethod
    def getUserAgentValue() -> str: ...
    @staticmethod
    def setCachePath(newFullPath: str | java.lang.String, /) -> None: ...
    @staticmethod
    def setCacheSizes(maxCacheSize: int | java.jlong | java.lang.Long, trimCacheSize: int | java.jlong | java.lang.Long, /) -> None: ...
    @staticmethod
    def setOfflineMapsPath(path: str | java.lang.String, /) -> None: ...
    @staticmethod
    def setUserAgentValue(val: str | java.lang.String, /) -> None: ...
