import typing

import java
import java.chaquopy
import java.lang
import java.util
import kotlin.ranges

class AbstractPlatformRandom(Random):
    def __init__(self) -> None: ...
    def getImpl(self) -> java.util.Random: ...
    def nextBits(self, bitCount: int | java.jint | java.lang.Integer, /) -> int: ...
    def nextBoolean(self) -> bool: ...
    def nextBytes(self, array: java.chaquopy.JavaArrayJByte, /) -> java.chaquopy.JavaArrayJByte: ...
    def nextDouble(self) -> float: ...
    def nextFloat(self) -> float: ...
    @typing.overload
    def nextInt(self) -> int: ...
    @typing.overload
    def nextInt(self, until: int | java.jint | java.lang.Integer, /) -> int: ...
    def nextLong(self) -> int: ...

class FallbackThreadLocalRandom(AbstractPlatformRandom):
    def __init__(self) -> None: ...
    def getImpl(self) -> java.util.Random: ...

class KotlinRandom(java.util.Random):
    def __init__(self, impl: Random, /) -> None: ...
    def getImpl(self) -> Random: ...
    def next(self, bits: int | java.jint | java.lang.Integer, /) -> int: ...
    def nextBoolean(self) -> bool: ...
    def nextBytes(self, bytes: java.chaquopy.JavaArrayJByte, /) -> None: ...
    def nextDouble(self) -> float: ...
    def nextFloat(self) -> float: ...
    @typing.overload
    def nextInt(self) -> int: ...
    @typing.overload
    def nextInt(self, bound: int | java.jint | java.lang.Integer, /) -> int: ...
    def nextLong(self) -> int: ...
    def setSeed(self, seed: int | java.jlong | java.lang.Long, /) -> None: ...

class PlatformRandom(AbstractPlatformRandom):
    def __init__(self, impl: java.util.Random, /) -> None: ...
    def getImpl(self) -> java.util.Random: ...

class PlatformRandomKt(java.lang.Object):
    @staticmethod
    def asJavaRandom(receiver: Random, /) -> java.util.Random: ...
    @staticmethod
    def asKotlinRandom(receiver: java.util.Random, /) -> Random: ...
    @staticmethod
    def doubleFromParts(hi26: int | java.jint | java.lang.Integer, low27: int | java.jint | java.lang.Integer, /) -> float: ...
    @staticmethod
    def fastLog2(value: int | java.jint | java.lang.Integer, /) -> int: ...

class Random(java.lang.Object):
    Companion: typing.ClassVar[Random.Companion] = ...
    Default: typing.ClassVar[Random.Default] = ...
    def __init__(self) -> None: ...
    def nextBits(self, arg1: int | java.jint | java.lang.Integer, /) -> int: ...
    def nextBoolean(self) -> bool: ...
    @typing.overload
    def nextBytes(self, size: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJByte: ...
    @typing.overload
    def nextBytes(self, array: java.chaquopy.JavaArrayJByte, /) -> java.chaquopy.JavaArrayJByte: ...
    @typing.overload
    def nextBytes(self, array: java.chaquopy.JavaArrayJByte, fromIndex: int | java.jint | java.lang.Integer, toIndex: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJByte: ...
    @typing.overload
    def nextDouble(self) -> float: ...
    @typing.overload
    def nextDouble(self, until: float | java.jdouble | java.lang.Double, /) -> float: ...
    @typing.overload
    def nextDouble(self, from_: float | java.jdouble | java.lang.Double, until: float | java.jdouble | java.lang.Double, /) -> float: ...
    def nextFloat(self) -> float: ...
    @typing.overload
    def nextInt(self) -> int: ...
    @typing.overload
    def nextInt(self, until: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    def nextInt(self, from_: int | java.jint | java.lang.Integer, until: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    def nextLong(self) -> int: ...
    @typing.overload
    def nextLong(self, until: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    def nextLong(self, from_: int | java.jlong | java.lang.Long, until: int | java.jlong | java.lang.Long, /) -> int: ...

    class Companion(Random):
        INSTANCE: typing.ClassVar[Random.Companion] = ...
        def nextBits(self, bitCount: int | java.jint | java.lang.Integer, /) -> int: ...

    class Default(Random):
        def nextBits(self, bitCount: int | java.jint | java.lang.Integer, /) -> int: ...
        def nextBoolean(self) -> bool: ...
        @typing.overload
        def nextBytes(self, size: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJByte: ...
        @typing.overload
        def nextBytes(self, array: java.chaquopy.JavaArrayJByte, /) -> java.chaquopy.JavaArrayJByte: ...
        @typing.overload
        def nextBytes(self, array: java.chaquopy.JavaArrayJByte, fromIndex: int | java.jint | java.lang.Integer, toIndex: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJByte: ...
        @typing.overload
        def nextDouble(self) -> float: ...
        @typing.overload
        def nextDouble(self, until: float | java.jdouble | java.lang.Double, /) -> float: ...
        @typing.overload
        def nextDouble(self, from_: float | java.jdouble | java.lang.Double, until: float | java.jdouble | java.lang.Double, /) -> float: ...
        def nextFloat(self) -> float: ...
        @typing.overload
        def nextInt(self) -> int: ...
        @typing.overload
        def nextInt(self, until: int | java.jint | java.lang.Integer, /) -> int: ...
        @typing.overload
        def nextInt(self, from_: int | java.jint | java.lang.Integer, until: int | java.jint | java.lang.Integer, /) -> int: ...
        @typing.overload
        def nextLong(self) -> int: ...
        @typing.overload
        def nextLong(self, until: int | java.jlong | java.lang.Long, /) -> int: ...
        @typing.overload
        def nextLong(self, from_: int | java.jlong | java.lang.Long, until: int | java.jlong | java.lang.Long, /) -> int: ...

class RandomKt(java.lang.Object):
    @typing.overload
    @staticmethod
    def Random(seed: int | java.jint | java.lang.Integer, /) -> Random: ...
    @typing.overload
    @staticmethod
    def Random(seed: int | java.jlong | java.lang.Long, /) -> Random: ...
    @staticmethod
    def boundsErrorMessage(from_: java.lang.Object | int | bool | float | str, until: java.lang.Object | int | bool | float | str, /) -> str: ...
    @typing.overload
    @staticmethod
    def checkRangeBounds(from_: float | java.jdouble | java.lang.Double, until: float | java.jdouble | java.lang.Double, /) -> None: ...
    @typing.overload
    @staticmethod
    def checkRangeBounds(from_: int | java.jint | java.lang.Integer, until: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    @staticmethod
    def checkRangeBounds(from_: int | java.jlong | java.lang.Long, until: int | java.jlong | java.lang.Long, /) -> None: ...
    @staticmethod
    def nextInt(receiver: Random, range: kotlin.ranges.IntRange, /) -> int: ...
    @staticmethod
    def nextLong(receiver: Random, range: kotlin.ranges.LongRange, /) -> int: ...
    @staticmethod
    def takeUpperBits(receiver: int | java.jint | java.lang.Integer, bitCount: int | java.jint | java.lang.Integer, /) -> int: ...

class URandomKt(java.lang.Object):
    @staticmethod
    def nextUBytes(receiver: Random, size: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJByte: ...
    @typing.overload
    @staticmethod
    def nextUInt(receiver: Random, /) -> int: ...
    @typing.overload
    @staticmethod
    def nextUInt(receiver: Random, range: kotlin.ranges.UIntRange, /) -> int: ...
    @typing.overload
    @staticmethod
    def nextULong(receiver: Random, /) -> int: ...
    @typing.overload
    @staticmethod
    def nextULong(receiver: Random, range: kotlin.ranges.ULongRange, /) -> int: ...

class XorWowRandom(Random):
    @typing.overload
    def __init__(self, seed1: int | java.jint | java.lang.Integer, seed2: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, z: int | java.jint | java.lang.Integer, w: int | java.jint | java.lang.Integer, v: int | java.jint | java.lang.Integer, addend: int | java.jint | java.lang.Integer, /) -> None: ...
    def nextBits(self, bitCount: int | java.jint | java.lang.Integer, /) -> int: ...
    def nextInt(self) -> int: ...
