import typing

import java
import java.chaquopy
import java.lang
import java.util
import java.util.concurrent
import kotlin
import kotlin.coroutines
import kotlin.jvm.functions
import kotlin.reflect
import kotlinx
import kotlinx.coroutines
import kotlinx.coroutines.internal
import kotlinx.coroutines.selects

_ActorCoroutine__E = typing.TypeVar('_ActorCoroutine__E')  # <E>
class ActorCoroutine(ChannelCoroutine[_ActorCoroutine__E], ActorScope[_ActorCoroutine__E], typing.Generic[_ActorCoroutine__E]):
    def __init__(self, parentContext: kotlin.coroutines.CoroutineContext, channel: Channel[_ActorCoroutine__E], active: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def handleJobException(self, exception: java.lang.Throwable, /) -> bool: ...
    def onCancelling(self, cause: java.lang.Throwable, /) -> None: ...

class ActorKt(java.lang.Object):
    _actor__E = typing.TypeVar('_actor__E')  # <E>
    @staticmethod
    def actor(this_actor: kotlinx.coroutines.CoroutineScope, context: kotlin.coroutines.CoroutineContext, capacity: int | java.jint | java.lang.Integer, start: kotlinx.coroutines.CoroutineStart, onCompletion: kotlin.jvm.functions.Function1[java.lang.Throwable, kotlin.Unit], block: kotlin.jvm.functions.Function2[ActorScope[_actor__E], kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], /) -> SendChannel[_actor__E]: ...

_ActorScope__E = typing.TypeVar('_ActorScope__E')  # <E>
class ActorScope(kotlinx.coroutines.CoroutineScope, ReceiveChannel[_ActorScope__E], typing.Generic[_ActorScope__E]):
    def getChannel(self) -> Channel[_ActorScope__E]: ...

    class DefaultImpls(java.lang.Object):
        _getOnReceiveOrNull__E = typing.TypeVar('_getOnReceiveOrNull__E')  # <E>
        @staticmethod
        def getOnReceiveOrNull(this: ActorScope[_getOnReceiveOrNull__E], /) -> kotlinx.coroutines.selects.SelectClause1[_getOnReceiveOrNull__E]: ...
        _poll__E = typing.TypeVar('_poll__E')  # <E>
        @staticmethod
        def poll(this: ActorScope[_poll__E], /) -> _poll__E: ...
        _receiveOrNull__E = typing.TypeVar('_receiveOrNull__E')  # <E>
        @staticmethod
        def receiveOrNull(this: ActorScope[_receiveOrNull__E], completion: kotlin.coroutines.Continuation[_receiveOrNull__E], /) -> java.lang.Object: ...

_BroadcastChannel__E = typing.TypeVar('_BroadcastChannel__E')  # <E>
class BroadcastChannel(SendChannel[_BroadcastChannel__E], typing.Generic[_BroadcastChannel__E]):
    def cancel(self, arg1: java.util.concurrent.CancellationException, /) -> None: ...
    def openSubscription(self) -> ReceiveChannel[_BroadcastChannel__E]: ...

    class DefaultImpls(java.lang.Object):
        _offer__E = typing.TypeVar('_offer__E')  # <E>
        @staticmethod
        def offer(this: BroadcastChannel[_offer__E], element: _offer__E, /) -> bool: ...

_BroadcastChannelImpl__E = typing.TypeVar('_BroadcastChannelImpl__E')  # <E>
class BroadcastChannelImpl(BufferedChannel[_BroadcastChannelImpl__E], BroadcastChannel[_BroadcastChannelImpl__E], typing.Generic[_BroadcastChannelImpl__E]):
    def __init__(self, capacity: int | java.jint | java.lang.Integer, /) -> None: ...
    def cancelImpl$kotlinx_coroutines_core(self, cause: java.lang.Throwable, /) -> bool: ...
    def close(self, cause: java.lang.Throwable, /) -> bool: ...
    def getCapacity(self) -> int: ...
    def getValue(self) -> _BroadcastChannelImpl__E: ...
    def getValueOrNull(self) -> _BroadcastChannelImpl__E: ...
    def isClosedForSend(self) -> bool: ...
    def openSubscription(self) -> ReceiveChannel[_BroadcastChannelImpl__E]: ...
    def registerSelectForSend(self, select: kotlinx.coroutines.selects.SelectInstance[java.lang.Object], element: java.lang.Object | int | bool | float | str, /) -> None: ...
    def send(self, element: _BroadcastChannelImpl__E, arg2: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def toString(self) -> str: ...
    def trySend-JP2dKIU(self, element: _BroadcastChannelImpl__E, /) -> java.lang.Object: ...

class BroadcastChannelKt(java.lang.Object):
    @staticmethod
    def BroadcastChannel(capacity: int | java.jint | java.lang.Integer, /) -> BroadcastChannel[java.lang.Object]: ...

_BroadcastCoroutine__E = typing.TypeVar('_BroadcastCoroutine__E')  # <E>
class BroadcastCoroutine(kotlinx.coroutines.AbstractCoroutine[kotlin.Unit], ProducerScope[_BroadcastCoroutine__E], BroadcastChannel[_BroadcastCoroutine__E], typing.Generic[_BroadcastCoroutine__E]):
    def __init__(self, parentContext: kotlin.coroutines.CoroutineContext, channel: BroadcastChannel[_BroadcastCoroutine__E], active: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def cancel(self, cause: java.util.concurrent.CancellationException, /) -> None: ...
    def cancelInternal(self, cause: java.lang.Throwable, /) -> None: ...
    def close(self, cause: java.lang.Throwable, /) -> bool: ...
    def getChannel(self) -> SendChannel[_BroadcastCoroutine__E]: ...
    def getOnSend(self) -> kotlinx.coroutines.selects.SelectClause2[_BroadcastCoroutine__E, SendChannel[_BroadcastCoroutine__E]]: ...
    def get_channel(self) -> BroadcastChannel[_BroadcastCoroutine__E]: ...
    def invokeOnClose(self, handler: kotlin.jvm.functions.Function1[java.lang.Throwable, kotlin.Unit], /) -> None: ...
    def isActive(self) -> bool: ...
    def isClosedForSend(self) -> bool: ...
    def offer(self, element: _BroadcastCoroutine__E, /) -> bool: ...
    def onCancelled(self, cause: java.lang.Throwable, handled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def onCompleted(self, value: kotlin.Unit, /) -> None: ...
    def openSubscription(self) -> ReceiveChannel[_BroadcastCoroutine__E]: ...
    def send(self, element: _BroadcastCoroutine__E, completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def trySend-JP2dKIU(self, element: _BroadcastCoroutine__E, /) -> java.lang.Object: ...

class BroadcastKt(java.lang.Object):
    _broadcast_0__E = typing.TypeVar('_broadcast_0__E')  # <E>
    _broadcast_1__E = typing.TypeVar('_broadcast_1__E')  # <E>
    @typing.overload
    @staticmethod
    def broadcast(this_broadcast: ReceiveChannel[_broadcast_0__E], capacity: int | java.jint | java.lang.Integer, start: kotlinx.coroutines.CoroutineStart, /) -> BroadcastChannel[_broadcast_0__E]: ...
    @typing.overload
    @staticmethod
    def broadcast(this_broadcast: kotlinx.coroutines.CoroutineScope, context: kotlin.coroutines.CoroutineContext, capacity: int | java.jint | java.lang.Integer, start: kotlinx.coroutines.CoroutineStart, onCompletion: kotlin.jvm.functions.Function1[java.lang.Throwable, kotlin.Unit], block: kotlin.jvm.functions.Function2[ProducerScope[_broadcast_1__E], kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], /) -> BroadcastChannel[_broadcast_1__E]: ...

class BufferOverflow(java.lang.Enum[BufferOverflow]):
    SUSPEND: typing.ClassVar[BufferOverflow] = ...
    DROP_OLDEST: typing.ClassVar[BufferOverflow] = ...
    DROP_LATEST: typing.ClassVar[BufferOverflow] = ...
    @staticmethod
    def valueOf(value: str | java.lang.String, /) -> BufferOverflow: ...
    @staticmethod
    def values() -> java.chaquopy.JavaArray[BufferOverflow]: ...

_BufferedChannel__E = typing.TypeVar('_BufferedChannel__E')  # <E>
class BufferedChannel(Channel[_BufferedChannel__E], typing.Generic[_BufferedChannel__E]):
    onUndeliveredElement: kotlin.jvm.functions.Function1[_BufferedChannel__E, kotlin.Unit] = ...
    def __init__(self, capacity: int | java.jint | java.lang.Integer, onUndeliveredElement: kotlin.jvm.functions.Function1[_BufferedChannel__E, kotlin.Unit], /) -> None: ...
    @typing.overload
    def cancel(self) -> None: ...
    @typing.overload
    def cancel(self, cause: java.lang.Throwable, /) -> bool: ...
    @typing.overload
    def cancel(self, cause: java.util.concurrent.CancellationException, /) -> None: ...
    def cancelImpl$kotlinx_coroutines_core(self, cause: java.lang.Throwable, /) -> bool: ...
    def checkSegmentStructureInvariants(self) -> None: ...
    def close(self, cause: java.lang.Throwable, /) -> bool: ...
    def closeOrCancelImpl(self, cause: java.lang.Throwable, cancel: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def dropFirstElementUntilTheSpecifiedCellIsInTheBuffer(self, globalCellIndex: int | java.jlong | java.lang.Long, /) -> None: ...
    def getCloseCause(self) -> java.lang.Throwable: ...
    def getOnReceive(self) -> kotlinx.coroutines.selects.SelectClause1[_BufferedChannel__E]: ...
    def getOnReceiveCatching(self) -> kotlinx.coroutines.selects.SelectClause1[ChannelResult[_BufferedChannel__E]]: ...
    def getOnReceiveOrNull(self) -> kotlinx.coroutines.selects.SelectClause1[_BufferedChannel__E]: ...
    def getOnSend(self) -> kotlinx.coroutines.selects.SelectClause2[_BufferedChannel__E, BufferedChannel[_BufferedChannel__E]]: ...
    def getReceiversCounter$kotlinx_coroutines_core(self) -> int: ...
    def getSendException(self) -> java.lang.Throwable: ...
    def getSendersCounter$kotlinx_coroutines_core(self) -> int: ...
    def hasElements$kotlinx_coroutines_core(self) -> bool: ...
    def invokeOnClose(self, handler: kotlin.jvm.functions.Function1[java.lang.Throwable, kotlin.Unit], /) -> None: ...
    def isClosedForReceive(self) -> bool: ...
    def isClosedForSend(self) -> bool: ...
    def isConflatedDropOldest(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    def iterator(self) -> ChannelIterator[_BufferedChannel__E]: ...
    def offer(self, element: _BufferedChannel__E, /) -> bool: ...
    def onClosedIdempotent(self) -> None: ...
    def onReceiveDequeued(self) -> None: ...
    def onReceiveEnqueued(self) -> None: ...
    def poll(self) -> _BufferedChannel__E: ...
    def receive(self, completion: kotlin.coroutines.Continuation[_BufferedChannel__E], /) -> java.lang.Object: ...
    def receiveCatching-JP2dKIU(self, completion: kotlin.coroutines.Continuation[ChannelResult[_BufferedChannel__E]], /) -> java.lang.Object: ...
    def receiveOrNull(self, completion: kotlin.coroutines.Continuation[_BufferedChannel__E], /) -> java.lang.Object: ...
    def registerSelectForSend(self, select: kotlinx.coroutines.selects.SelectInstance[java.lang.Object], element: java.lang.Object | int | bool | float | str, /) -> None: ...
    def send(self, element: _BufferedChannel__E, completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def sendBroadcast$kotlinx_coroutines_core(self, element: _BufferedChannel__E, completion: kotlin.coroutines.Continuation[bool], /) -> java.lang.Object: ...
    _sendImpl__R = typing.TypeVar('_sendImpl__R')  # <R>
    def sendImpl(self, element: _BufferedChannel__E, waiter: java.lang.Object | int | bool | float | str, onRendezvousOrBuffered: kotlin.jvm.functions.Function0[_sendImpl__R], onSuspend: kotlin.jvm.functions.Function2[ChannelSegment[_BufferedChannel__E], int, _sendImpl__R], onClosed: kotlin.jvm.functions.Function0[_sendImpl__R], onNoWaiterSuspend: kotlin.jvm.functions.Function4[ChannelSegment[_BufferedChannel__E], int, _BufferedChannel__E, int, _sendImpl__R], /) -> _sendImpl__R: ...
    def shouldSendSuspend$kotlinx_coroutines_core(self) -> bool: ...
    def toString(self) -> str: ...
    def toStringDebug$kotlinx_coroutines_core(self) -> str: ...
    def tryReceive-PtdJZtk(self) -> java.lang.Object: ...
    def trySend-JP2dKIU(self, element: _BufferedChannel__E, /) -> java.lang.Object: ...
    def waitExpandBufferCompletion$kotlinx_coroutines_core(self, globalIndex: int | java.jlong | java.lang.Long, /) -> None: ...

class BufferedChannelKt(java.lang.Object):
    SEGMENT_SIZE: typing.ClassVar[int] = ...
    BUFFERED: typing.ClassVar[kotlinx.coroutines.internal.Symbol] = ...
    @staticmethod
    def createSegmentFunction() -> kotlin.reflect.KFunction[ChannelSegment[java.lang.Object]]: ...
    @staticmethod
    def getCHANNEL_CLOSED() -> kotlinx.coroutines.internal.Symbol: ...

_Channel__E = typing.TypeVar('_Channel__E')  # <E>
class Channel(SendChannel[_Channel__E], ReceiveChannel[_Channel__E], typing.Generic[_Channel__E]):
    Factory: typing.ClassVar[Channel.Factory] = ...
    UNLIMITED: typing.ClassVar[int] = ...
    RENDEZVOUS: typing.ClassVar[int] = ...
    CONFLATED: typing.ClassVar[int] = ...
    BUFFERED: typing.ClassVar[int] = ...
    OPTIONAL_CHANNEL: typing.ClassVar[int] = ...
    DEFAULT_BUFFER_PROPERTY_NAME: typing.ClassVar[str] = ...

    class DefaultImpls(java.lang.Object):
        _getOnReceiveOrNull__E = typing.TypeVar('_getOnReceiveOrNull__E')  # <E>
        @staticmethod
        def getOnReceiveOrNull(this: Channel[_getOnReceiveOrNull__E], /) -> kotlinx.coroutines.selects.SelectClause1[_getOnReceiveOrNull__E]: ...
        _offer__E = typing.TypeVar('_offer__E')  # <E>
        @staticmethod
        def offer(this: Channel[_offer__E], element: _offer__E, /) -> bool: ...
        _poll__E = typing.TypeVar('_poll__E')  # <E>
        @staticmethod
        def poll(this: Channel[_poll__E], /) -> _poll__E: ...
        _receiveOrNull__E = typing.TypeVar('_receiveOrNull__E')  # <E>
        @staticmethod
        def receiveOrNull(this: Channel[_receiveOrNull__E], completion: kotlin.coroutines.Continuation[_receiveOrNull__E], /) -> java.lang.Object: ...

    class Factory(java.lang.Object):
        UNLIMITED: typing.ClassVar[int] = ...
        RENDEZVOUS: typing.ClassVar[int] = ...
        CONFLATED: typing.ClassVar[int] = ...
        BUFFERED: typing.ClassVar[int] = ...
        OPTIONAL_CHANNEL: typing.ClassVar[int] = ...
        DEFAULT_BUFFER_PROPERTY_NAME: typing.ClassVar[str] = ...
        def getCHANNEL_DEFAULT_CAPACITY$kotlinx_coroutines_core(self) -> int: ...

_ChannelCoroutine__E = typing.TypeVar('_ChannelCoroutine__E')  # <E>
class ChannelCoroutine(kotlinx.coroutines.AbstractCoroutine[kotlin.Unit], Channel[_ChannelCoroutine__E], typing.Generic[_ChannelCoroutine__E]):
    def __init__(self, parentContext: kotlin.coroutines.CoroutineContext, channel: Channel[_ChannelCoroutine__E], initParentJob: bool | java.jboolean | java.lang.Boolean, active: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def cancel(self, cause: java.util.concurrent.CancellationException, /) -> None: ...
    def cancelInternal(self, cause: java.lang.Throwable, /) -> None: ...
    def close(self, cause: java.lang.Throwable, /) -> bool: ...
    def getChannel(self) -> Channel[_ChannelCoroutine__E]: ...
    def getOnReceive(self) -> kotlinx.coroutines.selects.SelectClause1[_ChannelCoroutine__E]: ...
    def getOnReceiveCatching(self) -> kotlinx.coroutines.selects.SelectClause1[ChannelResult[_ChannelCoroutine__E]]: ...
    def getOnReceiveOrNull(self) -> kotlinx.coroutines.selects.SelectClause1[_ChannelCoroutine__E]: ...
    def getOnSend(self) -> kotlinx.coroutines.selects.SelectClause2[_ChannelCoroutine__E, SendChannel[_ChannelCoroutine__E]]: ...
    def get_channel(self) -> Channel[_ChannelCoroutine__E]: ...
    def invokeOnClose(self, handler: kotlin.jvm.functions.Function1[java.lang.Throwable, kotlin.Unit], /) -> None: ...
    def isClosedForReceive(self) -> bool: ...
    def isClosedForSend(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    def iterator(self) -> ChannelIterator[_ChannelCoroutine__E]: ...
    def offer(self, element: _ChannelCoroutine__E, /) -> bool: ...
    def poll(self) -> _ChannelCoroutine__E: ...
    def receive(self, completion: kotlin.coroutines.Continuation[_ChannelCoroutine__E], /) -> java.lang.Object: ...
    def receiveCatching-JP2dKIU(self, completion: kotlin.coroutines.Continuation[ChannelResult[_ChannelCoroutine__E]], /) -> java.lang.Object: ...
    def receiveOrNull(self, completion: kotlin.coroutines.Continuation[_ChannelCoroutine__E], /) -> java.lang.Object: ...
    def send(self, element: _ChannelCoroutine__E, completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def tryReceive-PtdJZtk(self) -> java.lang.Object: ...
    def trySend-JP2dKIU(self, element: _ChannelCoroutine__E, /) -> java.lang.Object: ...

_ChannelIterator__E = typing.TypeVar('_ChannelIterator__E')  # <E>
class ChannelIterator(java.lang.Object, typing.Generic[_ChannelIterator__E]):
    def hasNext(self, arg1: kotlin.coroutines.Continuation[bool], /) -> java.lang.Object: ...
    def next(self) -> _ChannelIterator__E: ...

    class DefaultImpls(java.lang.Object): ...

class ChannelKt(java.lang.Object):
    _Channel__E = typing.TypeVar('_Channel__E')  # <E>
    @staticmethod
    def Channel(capacity: int | java.jint | java.lang.Integer, onBufferOverflow: BufferOverflow, onUndeliveredElement: kotlin.jvm.functions.Function1[_Channel__E, kotlin.Unit], /) -> Channel[_Channel__E]: ...
    _getOrElse-WpGqRn0__T = typing.TypeVar('_getOrElse-WpGqRn0__T')  # <T>
    @staticmethod
    def getOrElse-WpGqRn0(this_getOrElse_u2dWpGqRn0: java.lang.Object | int | bool | float | str, onFailure: kotlin.jvm.functions.Function1[java.lang.Throwable, _getOrElse-WpGqRn0__T], /) -> _getOrElse-WpGqRn0__T: ...
    @staticmethod
    def onClosed-WpGqRn0(this_onClosed_u2dWpGqRn0: java.lang.Object | int | bool | float | str, action: kotlin.jvm.functions.Function1[java.lang.Throwable, kotlin.Unit], /) -> java.lang.Object: ...
    @staticmethod
    def onFailure-WpGqRn0(this_onFailure_u2dWpGqRn0: java.lang.Object | int | bool | float | str, action: kotlin.jvm.functions.Function1[java.lang.Throwable, kotlin.Unit], /) -> java.lang.Object: ...
    @staticmethod
    def onSuccess-WpGqRn0(this_onSuccess_u2dWpGqRn0: java.lang.Object | int | bool | float | str, action: kotlin.jvm.functions.Function1[java.lang.Object, kotlin.Unit], /) -> java.lang.Object: ...

_ChannelResult__T = typing.TypeVar('_ChannelResult__T')  # <T>
class ChannelResult(java.lang.Object, typing.Generic[_ChannelResult__T]):
    Companion: typing.ClassVar[ChannelResult.Companion] = ...
    @staticmethod
    def constructor-impl(holder: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl(arg0: java.lang.Object | int | bool | float | str, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl0(p1: java.lang.Object | int | bool | float | str, p2: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def exceptionOrNull-impl(arg0: java.lang.Object | int | bool | float | str, /) -> java.lang.Throwable: ...
    @staticmethod
    def getOrNull-impl(arg0: java.lang.Object | int | bool | float | str, /) -> T: ...
    @staticmethod
    def getOrThrow-impl(arg0: java.lang.Object | int | bool | float | str, /) -> T: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def hashCode-impl(arg0: java.lang.Object | int | bool | float | str, /) -> int: ...
    @staticmethod
    def isClosed-impl(arg0: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def isFailure-impl(arg0: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def isSuccess-impl(arg0: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def toString(self) -> str: ...
    @staticmethod
    def toString-impl(arg0: java.lang.Object | int | bool | float | str, /) -> str: ...

    class Closed(kotlinx.coroutines.channels.ChannelResult.Failed):
        cause: java.lang.Throwable = ...
        def __init__(self, cause: java.lang.Throwable, /) -> None: ...
        def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...

    class Companion(java.lang.Object):
        def closed-JP2dKIU(self, cause: java.lang.Throwable, /) -> java.lang.Object: ...
        def failure-PtdJZtk(self) -> java.lang.Object: ...
        def success-JP2dKIU(self, value: java.lang.Object, /) -> java.lang.Object: ...

    class Failed(java.lang.Object):
        def __init__(self) -> None: ...
        def toString(self) -> str: ...

_ChannelSegment__E = typing.TypeVar('_ChannelSegment__E')  # <E>
class ChannelSegment(kotlinx.coroutines.internal.Segment[ChannelSegment[_ChannelSegment__E]], typing.Generic[_ChannelSegment__E]):
    def __init__(self, id: int | java.jlong | java.lang.Long, prev: ChannelSegment[_ChannelSegment__E], channel: BufferedChannel[_ChannelSegment__E], pointers: int | java.jint | java.lang.Integer, /) -> None: ...
    def casState$kotlinx_coroutines_core(self, index: int | java.jint | java.lang.Integer, from_: java.lang.Object | int | bool | float | str, to: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def cleanElement$kotlinx_coroutines_core(self, index: int | java.jint | java.lang.Integer, /) -> None: ...
    def getAndSetState$kotlinx_coroutines_core(self, index: int | java.jint | java.lang.Integer, update: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def getChannel(self) -> BufferedChannel[_ChannelSegment__E]: ...
    def getElement$kotlinx_coroutines_core(self, index: int | java.jint | java.lang.Integer, /) -> _ChannelSegment__E: ...
    def getNumberOfSlots(self) -> int: ...
    def getState$kotlinx_coroutines_core(self, index: int | java.jint | java.lang.Integer, /) -> java.lang.Object: ...
    @typing.overload
    def onCancellation(self, index: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def onCancellation(self, index: int | java.jint | java.lang.Integer, cause: java.lang.Throwable, /) -> None: ...
    def onCancelledRequest(self, index: int | java.jint | java.lang.Integer, receiver: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def onSenderCancellationWithOnUndeliveredElement(self, index: int | java.jint | java.lang.Integer, context: kotlin.coroutines.CoroutineContext, /) -> None: ...
    def retrieveElement$kotlinx_coroutines_core(self, index: int | java.jint | java.lang.Integer, /) -> _ChannelSegment__E: ...
    def setState$kotlinx_coroutines_core(self, index: int | java.jint | java.lang.Integer, value: java.lang.Object | int | bool | float | str, /) -> None: ...
    def storeElement$kotlinx_coroutines_core(self, index: int | java.jint | java.lang.Integer, element: _ChannelSegment__E, /) -> None: ...

class ChannelsKt(java.lang.Object):
    DEFAULT_CLOSE_MESSAGE: typing.ClassVar[str] = ...
    @staticmethod
    def cancelConsumed(this_cancelConsumed: ReceiveChannel[java.lang.Object], cause: java.lang.Throwable, /) -> None: ...
    _consume_0__E = typing.TypeVar('_consume_0__E')  # <E>
    _consume_0__R = typing.TypeVar('_consume_0__R')  # <R>
    _consume_1__E = typing.TypeVar('_consume_1__E')  # <E>
    _consume_1__R = typing.TypeVar('_consume_1__R')  # <R>
    @typing.overload
    @staticmethod
    def consume(this_consume: BroadcastChannel[_consume_0__E], block: kotlin.jvm.functions.Function1[ReceiveChannel[_consume_0__E], _consume_0__R], /) -> _consume_0__R: ...
    @typing.overload
    @staticmethod
    def consume(this_consume: ReceiveChannel[_consume_1__E], block: kotlin.jvm.functions.Function1[ReceiveChannel[_consume_1__E], _consume_1__R], /) -> _consume_1__R: ...
    _consumeEach_0__E = typing.TypeVar('_consumeEach_0__E')  # <E>
    _consumeEach_1__E = typing.TypeVar('_consumeEach_1__E')  # <E>
    @typing.overload
    @staticmethod
    def consumeEach(this_consumeEach: BroadcastChannel[_consumeEach_0__E], action: kotlin.jvm.functions.Function1[_consumeEach_0__E, kotlin.Unit], completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    @typing.overload
    @staticmethod
    def consumeEach(this_consumeEach: ReceiveChannel[_consumeEach_1__E], action: kotlin.jvm.functions.Function1[_consumeEach_1__E, kotlin.Unit], completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    @staticmethod
    def consumes(this_consumes: ReceiveChannel[java.lang.Object], /) -> kotlin.jvm.functions.Function1[java.lang.Throwable, kotlin.Unit]: ...
    @staticmethod
    def consumesAll(*channels: ReceiveChannel[java.lang.Object]) -> kotlin.jvm.functions.Function1[java.lang.Throwable, kotlin.Unit]: ...
    _distinctBy__E = typing.TypeVar('_distinctBy__E')  # <E>
    @staticmethod
    def distinctBy(this_distinctBy: ReceiveChannel[_distinctBy__E], context: kotlin.coroutines.CoroutineContext, selector: kotlin.jvm.functions.Function2[_distinctBy__E, kotlin.coroutines.Continuation[java.lang.Object], java.lang.Object], /) -> ReceiveChannel[_distinctBy__E]: ...
    _filter__E = typing.TypeVar('_filter__E')  # <E>
    @staticmethod
    def filter(this_filter: ReceiveChannel[_filter__E], context: kotlin.coroutines.CoroutineContext, predicate: kotlin.jvm.functions.Function2[_filter__E, kotlin.coroutines.Continuation[bool], java.lang.Object], /) -> ReceiveChannel[_filter__E]: ...
    _filterNotNull__E = typing.TypeVar('_filterNotNull__E')  # <E>
    @staticmethod
    def filterNotNull(this_filterNotNull: ReceiveChannel[_filterNotNull__E], /) -> ReceiveChannel[_filterNotNull__E]: ...
    _map__E = typing.TypeVar('_map__E')  # <E>
    _map__R = typing.TypeVar('_map__R')  # <R>
    @staticmethod
    def map(this_map: ReceiveChannel[_map__E], context: kotlin.coroutines.CoroutineContext, transform: kotlin.jvm.functions.Function2[_map__E, kotlin.coroutines.Continuation[_map__R], java.lang.Object], /) -> ReceiveChannel[_map__R]: ...
    _mapIndexed__E = typing.TypeVar('_mapIndexed__E')  # <E>
    _mapIndexed__R = typing.TypeVar('_mapIndexed__R')  # <R>
    @staticmethod
    def mapIndexed(this_mapIndexed: ReceiveChannel[_mapIndexed__E], context: kotlin.coroutines.CoroutineContext, transform: kotlin.jvm.functions.Function3[int, _mapIndexed__E, kotlin.coroutines.Continuation[_mapIndexed__R], java.lang.Object], /) -> ReceiveChannel[_mapIndexed__R]: ...
    _toChannel__C = typing.TypeVar('_toChannel__C')  # <C>
    @staticmethod
    def toChannel(this_toChannel: ReceiveChannel[java.lang.Object], destination: _toChannel__C, completion: kotlin.coroutines.Continuation[_toChannel__C], /) -> java.lang.Object: ...
    _toCollection__C = typing.TypeVar('_toCollection__C')  # <C>
    @staticmethod
    def toCollection(this_toCollection: ReceiveChannel[java.lang.Object], destination: _toCollection__C, completion: kotlin.coroutines.Continuation[_toCollection__C], /) -> java.lang.Object: ...
    _toList__E = typing.TypeVar('_toList__E')  # <E>
    @staticmethod
    def toList(this_toList: ReceiveChannel[_toList__E], completion: kotlin.coroutines.Continuation[java.util.List[_toList__E]], /) -> java.lang.Object: ...
    _toMap__M = typing.TypeVar('_toMap__M')  # <M>
    @staticmethod
    def toMap(this_toMap: ReceiveChannel[kotlin.Pair[java.lang.Object, java.lang.Object]], destination: _toMap__M, completion: kotlin.coroutines.Continuation[_toMap__M], /) -> java.lang.Object: ...
    _toMutableSet__E = typing.TypeVar('_toMutableSet__E')  # <E>
    @staticmethod
    def toMutableSet(this_toMutableSet: ReceiveChannel[_toMutableSet__E], completion: kotlin.coroutines.Continuation[java.util.Set[_toMutableSet__E]], /) -> java.lang.Object: ...
    _trySendBlocking__E = typing.TypeVar('_trySendBlocking__E')  # <E>
    @staticmethod
    def trySendBlocking(this_trySendBlocking: SendChannel[_trySendBlocking__E], element: _trySendBlocking__E, /) -> java.lang.Object: ...
    _zip__E = typing.TypeVar('_zip__E')  # <E>
    _zip__R = typing.TypeVar('_zip__R')  # <R>
    _zip__V = typing.TypeVar('_zip__V')  # <V>
    @staticmethod
    def zip(this_zip: ReceiveChannel[_zip__E], other: ReceiveChannel[_zip__R], context: kotlin.coroutines.CoroutineContext, transform: kotlin.jvm.functions.Function2[_zip__E, _zip__R, _zip__V], /) -> ReceiveChannel[_zip__V]: ...

class ClosedReceiveChannelException(java.util.NoSuchElementException):
    def __init__(self, message: str | java.lang.String, /) -> None: ...

class ClosedSendChannelException(java.lang.IllegalStateException):
    def __init__(self, message: str | java.lang.String, /) -> None: ...

_ConflatedBroadcastChannel__E = typing.TypeVar('_ConflatedBroadcastChannel__E')  # <E>
class ConflatedBroadcastChannel(BroadcastChannel[_ConflatedBroadcastChannel__E], typing.Generic[_ConflatedBroadcastChannel__E]):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, value: _ConflatedBroadcastChannel__E, /) -> None: ...
    def cancel(self, cause: java.util.concurrent.CancellationException, /) -> None: ...
    def close(self, cause: java.lang.Throwable, /) -> bool: ...
    def getOnSend(self) -> kotlinx.coroutines.selects.SelectClause2[_ConflatedBroadcastChannel__E, SendChannel[_ConflatedBroadcastChannel__E]]: ...
    def getValue(self) -> _ConflatedBroadcastChannel__E: ...
    def getValueOrNull(self) -> _ConflatedBroadcastChannel__E: ...
    def invokeOnClose(self, handler: kotlin.jvm.functions.Function1[java.lang.Throwable, kotlin.Unit], /) -> None: ...
    def isClosedForSend(self) -> bool: ...
    def offer(self, element: _ConflatedBroadcastChannel__E, /) -> bool: ...
    def openSubscription(self) -> ReceiveChannel[_ConflatedBroadcastChannel__E]: ...
    def send(self, element: _ConflatedBroadcastChannel__E, completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def trySend-JP2dKIU(self, element: _ConflatedBroadcastChannel__E, /) -> java.lang.Object: ...

_ConflatedBufferedChannel__E = typing.TypeVar('_ConflatedBufferedChannel__E')  # <E>
class ConflatedBufferedChannel(BufferedChannel[_ConflatedBufferedChannel__E], typing.Generic[_ConflatedBufferedChannel__E]):
    def __init__(self, capacity: int | java.jint | java.lang.Integer, onBufferOverflow: BufferOverflow, onUndeliveredElement: kotlin.jvm.functions.Function1[_ConflatedBufferedChannel__E, kotlin.Unit], /) -> None: ...
    def isConflatedDropOldest(self) -> bool: ...
    def registerSelectForSend(self, select: kotlinx.coroutines.selects.SelectInstance[java.lang.Object], element: java.lang.Object | int | bool | float | str, /) -> None: ...
    def send(self, element: _ConflatedBufferedChannel__E, completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def sendBroadcast$kotlinx_coroutines_core(self, element: _ConflatedBufferedChannel__E, completion: kotlin.coroutines.Continuation[bool], /) -> java.lang.Object: ...
    def shouldSendSuspend$kotlinx_coroutines_core(self) -> bool: ...
    def trySend-JP2dKIU(self, element: _ConflatedBufferedChannel__E, /) -> java.lang.Object: ...

_LazyActorCoroutine__E = typing.TypeVar('_LazyActorCoroutine__E')  # <E>
class LazyActorCoroutine(ActorCoroutine[_LazyActorCoroutine__E], typing.Generic[_LazyActorCoroutine__E]):
    def __init__(self, parentContext: kotlin.coroutines.CoroutineContext, channel: Channel[_LazyActorCoroutine__E], block: kotlin.jvm.functions.Function2[ActorScope[_LazyActorCoroutine__E], kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], /) -> None: ...
    def close(self, cause: java.lang.Throwable, /) -> bool: ...
    def getOnSend(self) -> kotlinx.coroutines.selects.SelectClause2[_LazyActorCoroutine__E, SendChannel[_LazyActorCoroutine__E]]: ...
    def offer(self, element: _LazyActorCoroutine__E, /) -> bool: ...
    def onStart(self) -> None: ...
    def send(self, element: _LazyActorCoroutine__E, completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def trySend-JP2dKIU(self, element: _LazyActorCoroutine__E, /) -> java.lang.Object: ...

_LazyBroadcastCoroutine__E = typing.TypeVar('_LazyBroadcastCoroutine__E')  # <E>
class LazyBroadcastCoroutine(BroadcastCoroutine[_LazyBroadcastCoroutine__E], typing.Generic[_LazyBroadcastCoroutine__E]):
    def __init__(self, parentContext: kotlin.coroutines.CoroutineContext, channel: BroadcastChannel[_LazyBroadcastCoroutine__E], block: kotlin.jvm.functions.Function2[ProducerScope[_LazyBroadcastCoroutine__E], kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], /) -> None: ...
    def onStart(self) -> None: ...
    def openSubscription(self) -> ReceiveChannel[_LazyBroadcastCoroutine__E]: ...

class ProduceKt(java.lang.Object):
    @staticmethod
    def awaitClose(this_awaitClose: ProducerScope[java.lang.Object], block: kotlin.jvm.functions.Function0[kotlin.Unit], arg3: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    _produce_0__E = typing.TypeVar('_produce_0__E')  # <E>
    _produce_1__E = typing.TypeVar('_produce_1__E')  # <E>
    _produce_2__E = typing.TypeVar('_produce_2__E')  # <E>
    @typing.overload
    @staticmethod
    def produce(this_produce: kotlinx.coroutines.CoroutineScope, context: kotlin.coroutines.CoroutineContext, capacity: int | java.jint | java.lang.Integer, block: kotlin.jvm.functions.Function2[ProducerScope[_produce_0__E], kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], /) -> ReceiveChannel[_produce_0__E]: ...
    @typing.overload
    @staticmethod
    def produce(this_produce: kotlinx.coroutines.CoroutineScope, context: kotlin.coroutines.CoroutineContext, capacity: int | java.jint | java.lang.Integer, start: kotlinx.coroutines.CoroutineStart, onCompletion: kotlin.jvm.functions.Function1[java.lang.Throwable, kotlin.Unit], block: kotlin.jvm.functions.Function2[ProducerScope[_produce_1__E], kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], /) -> ReceiveChannel[_produce_1__E]: ...
    @typing.overload
    @staticmethod
    def produce(this_produce: kotlinx.coroutines.CoroutineScope, context: kotlin.coroutines.CoroutineContext, capacity: int | java.jint | java.lang.Integer, onBufferOverflow: BufferOverflow, start: kotlinx.coroutines.CoroutineStart, onCompletion: kotlin.jvm.functions.Function1[java.lang.Throwable, kotlin.Unit], block: kotlin.jvm.functions.Function2[ProducerScope[_produce_2__E], kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], /) -> ReceiveChannel[_produce_2__E]: ...

_ProducerCoroutine__E = typing.TypeVar('_ProducerCoroutine__E')  # <E>
class ProducerCoroutine(ChannelCoroutine[_ProducerCoroutine__E], ProducerScope[_ProducerCoroutine__E], typing.Generic[_ProducerCoroutine__E]):
    def __init__(self, parentContext: kotlin.coroutines.CoroutineContext, channel: Channel[_ProducerCoroutine__E], /) -> None: ...
    def isActive(self) -> bool: ...
    def onCancelled(self, cause: java.lang.Throwable, handled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def onCompleted(self, value: kotlin.Unit, /) -> None: ...

_ProducerScope__E = typing.TypeVar('_ProducerScope__E')  # <E>
class ProducerScope(kotlinx.coroutines.CoroutineScope, SendChannel[_ProducerScope__E], typing.Generic[_ProducerScope__E]):
    def getChannel(self) -> SendChannel[_ProducerScope__E]: ...

    class DefaultImpls(java.lang.Object):
        _offer__E = typing.TypeVar('_offer__E')  # <E>
        @staticmethod
        def offer(this: ProducerScope[_offer__E], element: _offer__E, /) -> bool: ...

_ReceiveCatching__E = typing.TypeVar('_ReceiveCatching__E')  # <E>
class ReceiveCatching(kotlinx.coroutines.Waiter, typing.Generic[_ReceiveCatching__E]):
    cont: kotlinx.coroutines.CancellableContinuationImpl[ChannelResult[_ReceiveCatching__E]] = ...
    def __init__(self, cont: kotlinx.coroutines.CancellableContinuationImpl[ChannelResult[_ReceiveCatching__E]], /) -> None: ...
    def invokeOnCancellation(self, segment: kotlinx.coroutines.internal.Segment[java.lang.Object], index: int | java.jint | java.lang.Integer, /) -> None: ...

_ReceiveChannel__E = typing.TypeVar('_ReceiveChannel__E')  # <E>
class ReceiveChannel(java.lang.Object, typing.Generic[_ReceiveChannel__E]):
    def cancel(self, arg1: java.util.concurrent.CancellationException, /) -> None: ...
    def getOnReceive(self) -> kotlinx.coroutines.selects.SelectClause1[_ReceiveChannel__E]: ...
    def getOnReceiveCatching(self) -> kotlinx.coroutines.selects.SelectClause1[ChannelResult[_ReceiveChannel__E]]: ...
    def getOnReceiveOrNull(self) -> kotlinx.coroutines.selects.SelectClause1[_ReceiveChannel__E]: ...
    def isClosedForReceive(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    def iterator(self) -> ChannelIterator[_ReceiveChannel__E]: ...
    def poll(self) -> _ReceiveChannel__E: ...
    def receive(self, arg1: kotlin.coroutines.Continuation[_ReceiveChannel__E], /) -> java.lang.Object: ...
    def receiveCatching-JP2dKIU(self, arg1: kotlin.coroutines.Continuation[ChannelResult[_ReceiveChannel__E]], /) -> java.lang.Object: ...
    def receiveOrNull(self, arg1: kotlin.coroutines.Continuation[_ReceiveChannel__E], /) -> java.lang.Object: ...
    def tryReceive-PtdJZtk(self) -> java.lang.Object: ...

    class DefaultImpls(java.lang.Object):
        _getOnReceiveOrNull__E = typing.TypeVar('_getOnReceiveOrNull__E')  # <E>
        @staticmethod
        def getOnReceiveOrNull(this: ReceiveChannel[_getOnReceiveOrNull__E], /) -> kotlinx.coroutines.selects.SelectClause1[_getOnReceiveOrNull__E]: ...
        _poll__E = typing.TypeVar('_poll__E')  # <E>
        @staticmethod
        def poll(this: ReceiveChannel[_poll__E], /) -> _poll__E: ...
        _receiveOrNull__E = typing.TypeVar('_receiveOrNull__E')  # <E>
        @staticmethod
        def receiveOrNull(this: ReceiveChannel[_receiveOrNull__E], arg2: kotlin.coroutines.Continuation[_receiveOrNull__E], /) -> java.lang.Object: ...

_SendChannel__E = typing.TypeVar('_SendChannel__E')  # <E>
class SendChannel(java.lang.Object, typing.Generic[_SendChannel__E]):
    def close(self, arg1: java.lang.Throwable, /) -> bool: ...
    def getOnSend(self) -> kotlinx.coroutines.selects.SelectClause2[_SendChannel__E, SendChannel[_SendChannel__E]]: ...
    def invokeOnClose(self, arg1: kotlin.jvm.functions.Function1[java.lang.Throwable, kotlin.Unit], /) -> None: ...
    def isClosedForSend(self) -> bool: ...
    def offer(self, arg1: _SendChannel__E, /) -> bool: ...
    def send(self, arg1: _SendChannel__E, arg2: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def trySend-JP2dKIU(self, arg1: _SendChannel__E, /) -> java.lang.Object: ...

    class DefaultImpls(java.lang.Object):
        _offer__E = typing.TypeVar('_offer__E')  # <E>
        @staticmethod
        def offer(this: SendChannel[_offer__E], element: _offer__E, /) -> bool: ...

class TickerChannelsKt(java.lang.Object):
    @staticmethod
    def ticker(delayMillis: int | java.jlong | java.lang.Long, initialDelayMillis: int | java.jlong | java.lang.Long, context: kotlin.coroutines.CoroutineContext, mode: TickerMode, /) -> ReceiveChannel[kotlin.Unit]: ...

class TickerMode(java.lang.Enum[TickerMode]):
    FIXED_PERIOD: typing.ClassVar[TickerMode] = ...
    FIXED_DELAY: typing.ClassVar[TickerMode] = ...
    @staticmethod
    def valueOf(value: str | java.lang.String, /) -> TickerMode: ...
    @staticmethod
    def values() -> java.chaquopy.JavaArray[TickerMode]: ...

class WaiterEB(java.lang.Object):
    waiter: kotlinx.coroutines.Waiter = ...
    def __init__(self, waiter: kotlinx.coroutines.Waiter, /) -> None: ...
    def toString(self) -> str: ...
