import java.lang.annotation

class NonNull(java.lang.annotation.Annotation): ...

class NullMarked(java.lang.annotation.Annotation): ...

class NullUnmarked(java.lang.annotation.Annotation): ...

class Nullable(java.lang.annotation.Annotation): ...
