import android.content
import android.graphics
import android.graphics.drawable
import android.os
import android.util
import android.view
import android.widget
import androidx.appcompat.widget
import com.google.android.material.internal
import java
import java.chaquopy
import java.lang
import java.lang.annotation
import java.util
import typing



class BadgeDrawable(android.graphics.drawable.Drawable, com.google.android.material.internal.TextDrawableHelper.TextDrawableDelegate):
    TOP_END: typing.ClassVar[int] = ...
    TOP_START: typing.ClassVar[int] = ...
    BOTTOM_END: typing.ClassVar[int] = ...
    BOTTOM_START: typing.ClassVar[int] = ...
    BADGE_FIXED_EDGE_START: typing.ClassVar[int] = ...
    BADGE_FIXED_EDGE_END: typing.ClassVar[int] = ...
    BADGE_CONTENT_NOT_TRUNCATED: typing.ClassVar[int] = ...
    def clearNumber(self) -> None: ...
    def clearText(self) -> None: ...
    @staticmethod
    def create(context: android.content.Context, /) -> BadgeDrawable: ...
    @staticmethod
    def createFromResource(context: android.content.Context, id: int | java.jint | java.lang.Integer, /) -> BadgeDrawable: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getAlpha(self) -> int: ...
    def getBackgroundColor(self) -> int: ...
    def getBadgeGravity(self) -> int: ...
    def getBadgeNumberLocale(self) -> java.util.Locale: ...
    def getBadgeTextColor(self) -> int: ...
    def getContentDescription(self) -> java.lang.CharSequence: ...
    def getCustomBadgeParent(self) -> android.widget.FrameLayout: ...
    def getHorizontalOffset(self) -> int: ...
    def getHorizontalOffsetWithText(self) -> int: ...
    def getHorizontalOffsetWithoutText(self) -> int: ...
    def getHorizontalPadding(self) -> int: ...
    def getIntrinsicHeight(self) -> int: ...
    def getIntrinsicWidth(self) -> int: ...
    def getLargeFontVerticalOffsetAdjustment(self) -> int: ...
    def getMaxCharacterCount(self) -> int: ...
    def getMaxNumber(self) -> int: ...
    def getNumber(self) -> int: ...
    def getOpacity(self) -> int: ...
    def getText(self) -> str: ...
    def getVerticalOffset(self) -> int: ...
    def getVerticalOffsetWithText(self) -> int: ...
    def getVerticalOffsetWithoutText(self) -> int: ...
    def getVerticalPadding(self) -> int: ...
    def hasNumber(self) -> bool: ...
    def hasText(self) -> bool: ...
    def isStateful(self) -> bool: ...
    def onStateChange(self, state: java.chaquopy.JavaArrayJInt, /) -> bool: ...
    def onTextSizeChange(self) -> None: ...
    def setAlpha(self, alpha: int | java.jint | java.lang.Integer, /) -> None: ...
    def setAutoAdjustToWithinGrandparentBounds(self, autoAdjustToWithinGrandparentBounds: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setBackgroundColor(self, backgroundColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBadgeFixedEdge(self, fixedEdge: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBadgeGravity(self, gravity: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBadgeNumberLocale(self, locale: java.util.Locale, /) -> None: ...
    def setBadgeTextColor(self, badgeTextColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBadgeWithTextShapeAppearance(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBadgeWithTextShapeAppearanceOverlay(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBadgeWithoutTextShapeAppearance(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBadgeWithoutTextShapeAppearanceOverlay(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setColorFilter(self, colorFilter: android.graphics.ColorFilter, /) -> None: ...
    def setContentDescriptionExceedsMaxBadgeNumberStringResource(self, stringsResource: int | java.jint | java.lang.Integer, /) -> None: ...
    def setContentDescriptionForText(self, charSequence: java.lang.CharSequence, /) -> None: ...
    def setContentDescriptionNumberless(self, charSequence: java.lang.CharSequence, /) -> None: ...
    def setContentDescriptionQuantityStringsResource(self, stringsResource: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHorizontalOffset(self, px: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHorizontalOffsetWithText(self, px: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHorizontalOffsetWithoutText(self, px: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHorizontalPadding(self, horizontalPadding: int | java.jint | java.lang.Integer, /) -> None: ...
    def setLargeFontVerticalOffsetAdjustment(self, px: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMaxCharacterCount(self, maxCharacterCount: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMaxNumber(self, maxNumber: int | java.jint | java.lang.Integer, /) -> None: ...
    def setNumber(self, number: int | java.jint | java.lang.Integer, /) -> None: ...
    def setText(self, text: str | java.lang.String, /) -> None: ...
    def setTextAppearance(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setVerticalOffset(self, px: int | java.jint | java.lang.Integer, /) -> None: ...
    def setVerticalOffsetWithText(self, px: int | java.jint | java.lang.Integer, /) -> None: ...
    def setVerticalOffsetWithoutText(self, px: int | java.jint | java.lang.Integer, /) -> None: ...
    def setVerticalPadding(self, verticalPadding: int | java.jint | java.lang.Integer, /) -> None: ...
    def setVisible(self, visible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def updateBadgeCoordinates(self, anchorView: android.view.View, /) -> None: ...
    @typing.overload
    def updateBadgeCoordinates(self, anchorView: android.view.View, customBadgeParent: android.view.ViewGroup, /) -> None: ...
    @typing.overload
    def updateBadgeCoordinates(self, anchorView: android.view.View, customBadgeParent: android.widget.FrameLayout, /) -> None: ...

    class BadgeGravity(java.lang.annotation.Annotation): ...

class BadgeState(java.lang.Object):

    class State(android.os.Parcelable):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator[BadgeState.State]] = ...
        def __init__(self) -> None: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, dest: android.os.Parcel, flags: int | java.jint | java.lang.Integer, /) -> None: ...

class BadgeUtils(java.lang.Object):
    @typing.overload
    @staticmethod
    def attachBadgeDrawable(badgeDrawable: BadgeDrawable, anchor: android.view.View, /) -> None: ...
    @typing.overload
    @staticmethod
    def attachBadgeDrawable(badgeDrawable: BadgeDrawable, anchor: android.view.View, customBadgeParent: android.widget.FrameLayout, /) -> None: ...
    @typing.overload
    @staticmethod
    def attachBadgeDrawable(badgeDrawable: BadgeDrawable, toolbar: androidx.appcompat.widget.Toolbar, menuItemId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    @staticmethod
    def attachBadgeDrawable(badgeDrawable: BadgeDrawable, toolbar: androidx.appcompat.widget.Toolbar, menuItemId: int | java.jint | java.lang.Integer, customBadgeParent: android.widget.FrameLayout, /) -> None: ...
    @staticmethod
    def createBadgeDrawablesFromSavedStates(context: android.content.Context, badgeStates: com.google.android.material.internal.ParcelableSparseArray, /) -> android.util.SparseArray[BadgeDrawable]: ...
    @staticmethod
    def createParcelableBadgeStates(badgeDrawables: android.util.SparseArray[BadgeDrawable], /) -> com.google.android.material.internal.ParcelableSparseArray: ...
    @typing.overload
    @staticmethod
    def detachBadgeDrawable(badgeDrawable: BadgeDrawable, anchor: android.view.View, /) -> None: ...
    @typing.overload
    @staticmethod
    def detachBadgeDrawable(badgeDrawable: BadgeDrawable, toolbar: androidx.appcompat.widget.Toolbar, menuItemId: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setBadgeDrawableBounds(badgeDrawable: BadgeDrawable, anchor: android.view.View, compatBadgeParent: android.widget.FrameLayout, /) -> None: ...
    @staticmethod
    def updateBadgeBounds(rect: android.graphics.Rect, centerX: float | java.jfloat | java.lang.Float, centerY: float | java.jfloat | java.lang.Float, halfWidth: float | java.jfloat | java.lang.Float, halfHeight: float | java.jfloat | java.lang.Float, /) -> None: ...

class ExperimentalBadgeUtils(java.lang.annotation.Annotation): ...
