import typing

import androidx.constraintlayout.core.widgets
import java
import java.chaquopy
import java.lang
import java.util

class ArrayLinkedVariables(ArrayRow.ArrayRowVariables):
    mCache: Cache = ...
    def add(self, variable: SolverVariable, value: float | java.jfloat | java.lang.Float, removeFromDefinition: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def clear(self) -> None: ...
    def contains(self, variable: SolverVariable, /) -> bool: ...
    def display(self) -> None: ...
    def divideByAmount(self, amount: float | java.jfloat | java.lang.Float, /) -> None: ...
    def get(self, v: SolverVariable, /) -> float: ...
    def getCurrentSize(self) -> int: ...
    def getHead(self) -> int: ...
    def getId(self, index: int | java.jint | java.lang.Integer, /) -> int: ...
    def getNextIndice(self, index: int | java.jint | java.lang.Integer, /) -> int: ...
    def getValue(self, index: int | java.jint | java.lang.Integer, /) -> float: ...
    def getVariable(self, index: int | java.jint | java.lang.Integer, /) -> SolverVariable: ...
    def getVariableValue(self, index: int | java.jint | java.lang.Integer, /) -> float: ...
    def indexOf(self, variable: SolverVariable, /) -> int: ...
    def invert(self) -> None: ...
    def put(self, variable: SolverVariable, value: float | java.jfloat | java.lang.Float, /) -> None: ...
    def remove(self, variable: SolverVariable, removeFromDefinition: bool | java.jboolean | java.lang.Boolean, /) -> float: ...
    def sizeInBytes(self) -> int: ...
    def toString(self) -> str: ...
    def use(self, definition: ArrayRow, removeFromDefinition: bool | java.jboolean | java.lang.Boolean, /) -> float: ...

class ArrayRow(LinearSystem.Row):
    variables: ArrayRow.ArrayRowVariables = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, cache: Cache, /) -> None: ...
    @typing.overload
    def addError(self, error: SolverVariable, /) -> None: ...
    @typing.overload
    def addError(self, system: LinearSystem, strength: int | java.jint | java.lang.Integer, /) -> ArrayRow: ...
    def clear(self) -> None: ...
    def createRowDimensionRatio(self, variableA: SolverVariable, variableB: SolverVariable, variableC: SolverVariable, variableD: SolverVariable, ratio: float | java.jfloat | java.lang.Float, /) -> ArrayRow: ...
    def createRowEqualDimension(self, currentWeight: float | java.jfloat | java.lang.Float, totalWeights: float | java.jfloat | java.lang.Float, nextWeight: float | java.jfloat | java.lang.Float, variableStartA: SolverVariable, marginStartA: int | java.jint | java.lang.Integer, variableEndA: SolverVariable, marginEndA: int | java.jint | java.lang.Integer, variableStartB: SolverVariable, marginStartB: int | java.jint | java.lang.Integer, variableEndB: SolverVariable, marginEndB: int | java.jint | java.lang.Integer, /) -> ArrayRow: ...
    def createRowEqualMatchDimensions(self, currentWeight: float | java.jfloat | java.lang.Float, totalWeights: float | java.jfloat | java.lang.Float, nextWeight: float | java.jfloat | java.lang.Float, variableStartA: SolverVariable, variableEndA: SolverVariable, variableStartB: SolverVariable, variableEndB: SolverVariable, /) -> ArrayRow: ...
    @typing.overload
    def createRowEquals(self, variable: SolverVariable, value: int | java.jint | java.lang.Integer, /) -> ArrayRow: ...
    @typing.overload
    def createRowEquals(self, variableA: SolverVariable, variableB: SolverVariable, margin: int | java.jint | java.lang.Integer, /) -> ArrayRow: ...
    @typing.overload
    def createRowGreaterThan(self, a: SolverVariable, b: int | java.jint | java.lang.Integer, slack: SolverVariable, /) -> ArrayRow: ...
    @typing.overload
    def createRowGreaterThan(self, variableA: SolverVariable, variableB: SolverVariable, slack: SolverVariable, margin: int | java.jint | java.lang.Integer, /) -> ArrayRow: ...
    def createRowLowerThan(self, variableA: SolverVariable, variableB: SolverVariable, slack: SolverVariable, margin: int | java.jint | java.lang.Integer, /) -> ArrayRow: ...
    def createRowWithAngle(self, at: SolverVariable, ab: SolverVariable, bt: SolverVariable, bb: SolverVariable, angleComponent: float | java.jfloat | java.lang.Float, /) -> ArrayRow: ...
    def getKey(self) -> SolverVariable: ...
    def getPivotCandidate(self, system: LinearSystem, avoid: java.chaquopy.JavaArrayJBoolean, /) -> SolverVariable: ...
    def initFromRow(self, row: LinearSystem.Row, /) -> None: ...
    def isEmpty(self) -> bool: ...
    def pickPivot(self, exclude: SolverVariable, /) -> SolverVariable: ...
    def reset(self) -> None: ...
    def toString(self) -> str: ...
    def updateFromFinalVariable(self, system: LinearSystem, variable: SolverVariable, removeFromDefinition: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def updateFromRow(self, system: LinearSystem, definition: ArrayRow, removeFromDefinition: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def updateFromSynonymVariable(self, system: LinearSystem, variable: SolverVariable, removeFromDefinition: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def updateFromSystem(self, system: LinearSystem, /) -> None: ...

    class ArrayRowVariables(java.lang.Object):
        def add(self, arg1: SolverVariable, arg2: float | java.jfloat | java.lang.Float, arg3: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
        def clear(self) -> None: ...
        def contains(self, arg1: SolverVariable, /) -> bool: ...
        def display(self) -> None: ...
        def divideByAmount(self, arg1: float | java.jfloat | java.lang.Float, /) -> None: ...
        def get(self, arg1: SolverVariable, /) -> float: ...
        def getCurrentSize(self) -> int: ...
        def getVariable(self, arg1: int | java.jint | java.lang.Integer, /) -> SolverVariable: ...
        def getVariableValue(self, arg1: int | java.jint | java.lang.Integer, /) -> float: ...
        def indexOf(self, arg1: SolverVariable, /) -> int: ...
        def invert(self) -> None: ...
        def put(self, arg1: SolverVariable, arg2: float | java.jfloat | java.lang.Float, /) -> None: ...
        def remove(self, arg1: SolverVariable, arg2: bool | java.jboolean | java.lang.Boolean, /) -> float: ...
        def sizeInBytes(self) -> int: ...
        def use(self, arg1: ArrayRow, arg2: bool | java.jboolean | java.lang.Boolean, /) -> float: ...

class Cache(java.lang.Object):
    def __init__(self) -> None: ...

class GoalRow(ArrayRow):
    def __init__(self, cache: Cache, /) -> None: ...
    def addError(self, error: SolverVariable, /) -> None: ...

class LinearSystem(java.lang.Object):
    FULL_DEBUG: typing.ClassVar[bool] = ...
    DEBUG: typing.ClassVar[bool] = ...
    USE_DEPENDENCY_ORDERING: typing.ClassVar[bool] = ...
    USE_BASIC_SYNONYMS: typing.ClassVar[bool] = ...
    SIMPLIFY_SYNONYMS: typing.ClassVar[bool] = ...
    USE_SYNONYMS: typing.ClassVar[bool] = ...
    SKIP_COLUMNS: typing.ClassVar[bool] = ...
    OPTIMIZED_ENGINE: typing.ClassVar[bool] = ...
    hasSimpleDefinition: bool = ...
    graphOptimizer: bool = ...
    newgraphOptimizer: bool = ...
    sMetrics: typing.ClassVar[Metrics] = ...
    ARRAY_ROW_CREATION: typing.ClassVar[int] = ...
    OPTIMIZED_ARRAY_ROW_CREATION: typing.ClassVar[int] = ...
    def __init__(self) -> None: ...
    def addCenterPoint(self, widget: androidx.constraintlayout.core.widgets.ConstraintWidget, target: androidx.constraintlayout.core.widgets.ConstraintWidget, angle: float | java.jfloat | java.lang.Float, radius: int | java.jint | java.lang.Integer, /) -> None: ...
    def addCentering(self, a: SolverVariable, b: SolverVariable, m1: int | java.jint | java.lang.Integer, bias: float | java.jfloat | java.lang.Float, c: SolverVariable, d: SolverVariable, m2: int | java.jint | java.lang.Integer, strength: int | java.jint | java.lang.Integer, /) -> None: ...
    def addConstraint(self, row: ArrayRow, /) -> None: ...
    @typing.overload
    def addEquality(self, a: SolverVariable, value: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def addEquality(self, a: SolverVariable, b: SolverVariable, margin: int | java.jint | java.lang.Integer, strength: int | java.jint | java.lang.Integer, /) -> ArrayRow: ...
    def addGreaterBarrier(self, a: SolverVariable, b: SolverVariable, margin: int | java.jint | java.lang.Integer, hasMatchConstraintWidgets: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def addGreaterThan(self, a: SolverVariable, b: SolverVariable, margin: int | java.jint | java.lang.Integer, strength: int | java.jint | java.lang.Integer, /) -> None: ...
    def addLowerBarrier(self, a: SolverVariable, b: SolverVariable, margin: int | java.jint | java.lang.Integer, hasMatchConstraintWidgets: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def addLowerThan(self, a: SolverVariable, b: SolverVariable, margin: int | java.jint | java.lang.Integer, strength: int | java.jint | java.lang.Integer, /) -> None: ...
    def addRatio(self, a: SolverVariable, b: SolverVariable, c: SolverVariable, d: SolverVariable, ratio: float | java.jfloat | java.lang.Float, strength: int | java.jint | java.lang.Integer, /) -> None: ...
    def addSynonym(self, a: SolverVariable, b: SolverVariable, margin: int | java.jint | java.lang.Integer, /) -> None: ...
    def createErrorVariable(self, strength: int | java.jint | java.lang.Integer, prefix: str | java.lang.String, /) -> SolverVariable: ...
    def createExtraVariable(self) -> SolverVariable: ...
    def createObjectVariable(self, anchor: java.lang.Object | int | bool | float | str, /) -> SolverVariable: ...
    def createRow(self) -> ArrayRow: ...
    @staticmethod
    def createRowDimensionPercent(linearSystem: LinearSystem, variableA: SolverVariable, variableC: SolverVariable, percent: float | java.jfloat | java.lang.Float, /) -> ArrayRow: ...
    def createSlackVariable(self) -> SolverVariable: ...
    def displayReadableRows(self) -> None: ...
    def displayVariablesReadableRows(self) -> None: ...
    def fillMetrics(self, metrics: Metrics, /) -> None: ...
    def getCache(self) -> Cache: ...
    def getMemoryUsed(self) -> int: ...
    @staticmethod
    def getMetrics() -> Metrics: ...
    def getNumEquations(self) -> int: ...
    def getNumVariables(self) -> int: ...
    def getObjectVariableValue(self, object: java.lang.Object | int | bool | float | str, /) -> int: ...
    def minimize(self) -> None: ...
    def removeRow(self, row: ArrayRow, /) -> None: ...
    def reset(self) -> None: ...

class Metrics(java.lang.Object):
    measuresWidgetsDuration: int = ...
    measuresLayoutDuration: int = ...
    measuredWidgets: int = ...
    measuredMatchWidgets: int = ...
    measures: int = ...
    additionalMeasures: int = ...
    resolutions: int = ...
    tableSizeIncrease: int = ...
    minimize: int = ...
    constraints: int = ...
    simpleconstraints: int = ...
    optimize: int = ...
    iterations: int = ...
    pivots: int = ...
    bfs: int = ...
    variables: int = ...
    errors: int = ...
    slackvariables: int = ...
    extravariables: int = ...
    maxTableSize: int = ...
    fullySolved: int = ...
    graphOptimizer: int = ...
    graphSolved: int = ...
    linearSolved: int = ...
    resolvedWidgets: int = ...
    minimizeGoal: int = ...
    maxVariables: int = ...
    maxRows: int = ...
    nonresolvedWidgets: int = ...
    problematicLayouts: java.util.ArrayList[java.lang.String] = ...
    lastTableSize: int = ...
    widgets: int = ...
    measuresWrap: int = ...
    measuresWrapInfeasible: int = ...
    infeasibleDetermineGroups: int = ...
    determineGroups: int = ...
    layouts: int = ...
    grouping: int = ...
    mNumberOfLayouts: int = ...
    mNumberOfMeasures: int = ...
    mMeasureDuration: int = ...
    mChildCount: int = ...
    mMeasureCalls: int = ...
    mSolverPasses: int = ...
    mEquations: int = ...
    mVariables: int = ...
    mSimpleEquations: int = ...
    def __init__(self) -> None: ...
    def copy(self, metrics: Metrics, /) -> None: ...
    def reset(self) -> None: ...
    def toString(self) -> str: ...

class Pools(java.lang.Object): ...

class PriorityGoalRow(ArrayRow):
    def __init__(self, cache: Cache, /) -> None: ...
    def addError(self, error: SolverVariable, /) -> None: ...
    def clear(self) -> None: ...
    def getPivotCandidate(self, system: LinearSystem, avoid: java.chaquopy.JavaArrayJBoolean, /) -> SolverVariable: ...
    def isEmpty(self) -> bool: ...
    def toString(self) -> str: ...
    def updateFromRow(self, system: LinearSystem, definition: ArrayRow, removeFromDefinition: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class SolverVariable(java.lang.Comparable[SolverVariable]):
    STRENGTH_NONE: typing.ClassVar[int] = ...
    STRENGTH_LOW: typing.ClassVar[int] = ...
    STRENGTH_MEDIUM: typing.ClassVar[int] = ...
    STRENGTH_HIGH: typing.ClassVar[int] = ...
    STRENGTH_HIGHEST: typing.ClassVar[int] = ...
    STRENGTH_EQUALITY: typing.ClassVar[int] = ...
    STRENGTH_BARRIER: typing.ClassVar[int] = ...
    STRENGTH_CENTERING: typing.ClassVar[int] = ...
    STRENGTH_FIXED: typing.ClassVar[int] = ...
    inGoal: bool = ...
    id: int = ...
    strength: int = ...
    computedValue: float = ...
    isFinalValue: bool = ...
    usageInRowCount: int = ...
    @typing.overload
    def __init__(self, type: SolverVariable.Type, prefix: str | java.lang.String, /) -> None: ...
    @typing.overload
    def __init__(self, name: str | java.lang.String, type: SolverVariable.Type, /) -> None: ...
    def addToRow(self, row: ArrayRow, /) -> None: ...
    def compareTo(self, v: SolverVariable, /) -> int: ...
    def getName(self) -> str: ...
    def removeFromRow(self, row: ArrayRow, /) -> None: ...
    def reset(self) -> None: ...
    def setFinalValue(self, system: LinearSystem, value: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setName(self, name: str | java.lang.String, /) -> None: ...
    def setSynonym(self, system: LinearSystem, synonymVariable: SolverVariable, value: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setType(self, type: SolverVariable.Type, prefix: str | java.lang.String, /) -> None: ...
    def toString(self) -> str: ...
    def updateReferencesWithNewDefinition(self, system: LinearSystem, definition: ArrayRow, /) -> None: ...

    class Type(java.lang.Enum[SolverVariable.Type]):
        UNRESTRICTED: typing.ClassVar[SolverVariable.Type] = ...
        CONSTANT: typing.ClassVar[SolverVariable.Type] = ...
        SLACK: typing.ClassVar[SolverVariable.Type] = ...
        ERROR: typing.ClassVar[SolverVariable.Type] = ...
        UNKNOWN: typing.ClassVar[SolverVariable.Type] = ...
        @staticmethod
        def valueOf(name: str | java.lang.String, /) -> SolverVariable.Type: ...
        @staticmethod
        def values() -> java.chaquopy.JavaArray[SolverVariable.Type]: ...

class SolverVariableValues(ArrayRow.ArrayRowVariables):
    mCache: Cache = ...
    def add(self, v: SolverVariable, value: float | java.jfloat | java.lang.Float, removeFromDefinition: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def clear(self) -> None: ...
    def contains(self, variable: SolverVariable, /) -> bool: ...
    def display(self) -> None: ...
    def divideByAmount(self, amount: float | java.jfloat | java.lang.Float, /) -> None: ...
    def get(self, variable: SolverVariable, /) -> float: ...
    def getCurrentSize(self) -> int: ...
    def getVariable(self, index: int | java.jint | java.lang.Integer, /) -> SolverVariable: ...
    def getVariableValue(self, index: int | java.jint | java.lang.Integer, /) -> float: ...
    def indexOf(self, variable: SolverVariable, /) -> int: ...
    def invert(self) -> None: ...
    def put(self, variable: SolverVariable, value: float | java.jfloat | java.lang.Float, /) -> None: ...
    def remove(self, v: SolverVariable, removeFromDefinition: bool | java.jboolean | java.lang.Boolean, /) -> float: ...
    def sizeInBytes(self) -> int: ...
    def toString(self) -> str: ...
    def use(self, definition: ArrayRow, removeFromDefinition: bool | java.jboolean | java.lang.Boolean, /) -> float: ...
