import typing

import java.lang
import java.util
import kotlin
import kotlin.jvm.internal

class AllModules(java.lang.ThreadLocal[java.util.ArrayList[Module]], kotlin.jvm.internal.KObject):
    INSTANCE$: typing.ClassVar[AllModules] = ...
    def initialValue(self) -> java.util.ArrayList[Module]: ...

class AnnotationsPathBuilder(kotlin.jvm.internal.KObject):
    def __init__(self, parent: ModuleBuilder, /) -> None: ...
    def plusAssign(self, name: str | java.lang.String, /) -> None: ...

class ClasspathBuilder(kotlin.jvm.internal.KObject):
    def __init__(self, parent: ModuleBuilder, /) -> None: ...
    def plusAssign(self, name: str | java.lang.String, /) -> None: ...

class Module(kotlin.jvm.internal.KObject):
    def getAnnotationsRoots(self) -> java.util.List[java.lang.String]: ...
    def getClasspathRoots(self) -> java.util.List[java.lang.String]: ...
    def getModuleName(self) -> str: ...
    def getOutputDirectory(self) -> str: ...
    def getSourceFiles(self) -> java.util.List[java.lang.String]: ...

class ModuleBuilder(kotlin.jvm.internal.KObject, Module):
    def __init__(self, name: str | java.lang.String, outputDir: str | java.lang.String, /) -> None: ...
    def addAnnotationsPathEntry(self, name: str | java.lang.String, /) -> None: ...
    def addClasspathEntry(self, name: str | java.lang.String, /) -> None: ...
    def addSourceFiles(self, pattern: str | java.lang.String, /) -> None: ...
    def getAnnotationsPath(self) -> AnnotationsPathBuilder: ...
    def getAnnotationsRoots(self) -> java.util.List[java.lang.String]: ...
    def getClasspath(self) -> ClasspathBuilder: ...
    def getClasspathRoots(self) -> java.util.List[java.lang.String]: ...
    def getModuleName(self) -> str: ...
    def getOutputDirectory(self) -> str: ...
    def getSourceFiles(self) -> java.util.List[java.lang.String]: ...
    def getSources(self) -> SourcesBuilder: ...

class ModulesPackage-ModuleBuilder-9d472008(java.lang.Object):
    @staticmethod
    def module(name: str | java.lang.String, outputDir: str | java.lang.String, callback: kotlin.ExtensionFunction0[ModuleBuilder, kotlin.Unit], /) -> None: ...

class ModulesPackage(java.lang.Object):
    @staticmethod
    def module(name: str | java.lang.String, outputDir: str | java.lang.String, callback: kotlin.ExtensionFunction0[ModuleBuilder, kotlin.Unit], /) -> None: ...

class SourcesBuilder(kotlin.jvm.internal.KObject):
    def __init__(self, parent: ModuleBuilder, /) -> None: ...
    def plusAssign(self, pattern: str | java.lang.String, /) -> None: ...
