import android.animation
import android.content
import android.content.res
import android.graphics
import android.graphics.drawable
import android.util
import android.view
import android.widget
import java
import java.chaquopy
import java.lang
import java.util
import typing



class AnimatableView(java.lang.Object):
    def startAnimation(self, arg1: AnimatableView.Listener, /) -> None: ...
    def stopAnimation(self) -> None: ...

    class Listener(java.lang.Object):
        def onAnimationEnd(self) -> None: ...

class AnimationUtils(java.lang.Object):
    LINEAR_INTERPOLATOR: typing.ClassVar[android.animation.TimeInterpolator] = ...
    FAST_OUT_SLOW_IN_INTERPOLATOR: typing.ClassVar[android.animation.TimeInterpolator] = ...
    FAST_OUT_LINEAR_IN_INTERPOLATOR: typing.ClassVar[android.animation.TimeInterpolator] = ...
    LINEAR_OUT_SLOW_IN_INTERPOLATOR: typing.ClassVar[android.animation.TimeInterpolator] = ...
    DECELERATE_INTERPOLATOR: typing.ClassVar[android.animation.TimeInterpolator] = ...
    def __init__(self) -> None: ...
    @typing.overload
    @staticmethod
    def lerp(startValue: float | java.jfloat | java.lang.Float, endValue: float | java.jfloat | java.lang.Float, fraction: float | java.jfloat | java.lang.Float, /) -> float: ...
    @typing.overload
    @staticmethod
    def lerp(startValue: int | java.jint | java.lang.Integer, endValue: int | java.jint | java.lang.Integer, fraction: float | java.jfloat | java.lang.Float, /) -> int: ...
    @typing.overload
    @staticmethod
    def lerp(outputMin: float | java.jfloat | java.lang.Float, outputMax: float | java.jfloat | java.lang.Float, inputMin: float | java.jfloat | java.lang.Float, inputMax: float | java.jfloat | java.lang.Float, value: float | java.jfloat | java.lang.Float, /) -> float: ...

class AnimatorSetCompat(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def playTogether(animatorSet: android.animation.AnimatorSet, items: java.util.List[android.animation.Animator], /) -> None: ...

class ArgbEvaluatorCompat(android.animation.TypeEvaluator[java.lang.Integer]):
    def __init__(self) -> None: ...
    def evaluate(self, fraction: float | java.jfloat | java.lang.Float, startValue: int | java.jint | java.lang.Integer, endValue: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def getInstance() -> ArgbEvaluatorCompat: ...

class ChildrenAlphaProperty(android.util.Property[android.view.ViewGroup, java.lang.Float]):
    CHILDREN_ALPHA: typing.ClassVar[android.util.Property[android.view.ViewGroup, java.lang.Float]] = ...
    def get(self, object: android.view.ViewGroup, /) -> float: ...
    def set(self, object: android.view.ViewGroup, value: float | java.jfloat | java.lang.Float, /) -> None: ...

class DrawableAlphaProperty(android.util.Property[android.graphics.drawable.Drawable, java.lang.Integer]):
    DRAWABLE_ALPHA_COMPAT: typing.ClassVar[android.util.Property[android.graphics.drawable.Drawable, java.lang.Integer]] = ...
    def get(self, object: android.graphics.drawable.Drawable, /) -> int: ...
    def set(self, object: android.graphics.drawable.Drawable, value: int | java.jint | java.lang.Integer, /) -> None: ...

class ImageMatrixProperty(android.util.Property[android.widget.ImageView, android.graphics.Matrix]):
    def __init__(self) -> None: ...
    def get(self, object: android.widget.ImageView, /) -> android.graphics.Matrix: ...
    def set(self, object: android.widget.ImageView, value: android.graphics.Matrix, /) -> None: ...

class MatrixEvaluator(android.animation.TypeEvaluator[android.graphics.Matrix]):
    def __init__(self) -> None: ...
    def evaluate(self, fraction: float | java.jfloat | java.lang.Float, startValue: android.graphics.Matrix, endValue: android.graphics.Matrix, /) -> android.graphics.Matrix: ...

class MotionSpec(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def createFromAttribute(context: android.content.Context, attributes: android.content.res.TypedArray, index: int | java.jint | java.lang.Integer, /) -> MotionSpec: ...
    @staticmethod
    def createFromResource(context: android.content.Context, id: int | java.jint | java.lang.Integer, /) -> MotionSpec: ...
    def equals(self, o: java.lang.Object | int | bool | float | str, /) -> bool: ...
    _getAnimator__T = typing.TypeVar('_getAnimator__T')  # <T>
    def getAnimator(self, name: str | java.lang.String, target: _getAnimator__T, property: android.util.Property[_getAnimator__T, java.lang.Object], /) -> android.animation.ObjectAnimator: ...
    def getPropertyValues(self, name: str | java.lang.String, /) -> java.chaquopy.JavaArray[android.animation.PropertyValuesHolder]: ...
    def getTiming(self, name: str | java.lang.String, /) -> MotionTiming: ...
    def getTotalDuration(self) -> int: ...
    def hasPropertyValues(self, name: str | java.lang.String, /) -> bool: ...
    def hasTiming(self, name: str | java.lang.String, /) -> bool: ...
    def hashCode(self) -> int: ...
    def setPropertyValues(self, name: str | java.lang.String, values: java.chaquopy.JavaArray[android.animation.PropertyValuesHolder], /) -> None: ...
    def setTiming(self, name: str | java.lang.String, timing: MotionTiming, /) -> None: ...
    def toString(self) -> str: ...

class MotionTiming(java.lang.Object):
    @typing.overload
    def __init__(self, delay: int | java.jlong | java.lang.Long, duration: int | java.jlong | java.lang.Long, /) -> None: ...
    @typing.overload
    def __init__(self, delay: int | java.jlong | java.lang.Long, duration: int | java.jlong | java.lang.Long, interpolator: android.animation.TimeInterpolator, /) -> None: ...
    def apply(self, animator: android.animation.Animator, /) -> None: ...
    def equals(self, o: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getDelay(self) -> int: ...
    def getDuration(self) -> int: ...
    def getInterpolator(self) -> android.animation.TimeInterpolator: ...
    def getRepeatCount(self) -> int: ...
    def getRepeatMode(self) -> int: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class Positioning(java.lang.Object):
    gravity: int = ...
    xAdjustment: float = ...
    yAdjustment: float = ...
    def __init__(self, gravity: int | java.jint | java.lang.Integer, xAdjustment: float | java.jfloat | java.lang.Float, yAdjustment: float | java.jfloat | java.lang.Float, /) -> None: ...

_TransformationCallback__T = typing.TypeVar('_TransformationCallback__T', bound=android.view.View)  # <T>
class TransformationCallback(java.lang.Object, typing.Generic[_TransformationCallback__T]):
    def onScaleChanged(self, arg1: _TransformationCallback__T, /) -> None: ...
    def onTranslationChanged(self, arg1: _TransformationCallback__T, /) -> None: ...
