import typing

import android.os
import java
import java.lang

class IUnusedAppRestrictionsBackportCallback(android.os.IInterface):
    DESCRIPTOR: typing.ClassVar[str] = ...
    def onIsPermissionRevocationEnabledForAppResult(self, arg1: bool | java.jboolean | java.lang.Boolean, arg2: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

    class Stub(android.os.Binder, IUnusedAppRestrictionsBackportCallback):
        def __init__(self) -> None: ...
        def asBinder(self) -> android.os.IBinder: ...
        @staticmethod
        def asInterface(obj: android.os.IBinder, /) -> IUnusedAppRestrictionsBackportCallback: ...
        def onTransact(self, code: int | java.jint | java.lang.Integer, data: android.os.Parcel, reply: android.os.Parcel, flags: int | java.jint | java.lang.Integer, /) -> bool: ...

    class Default(IUnusedAppRestrictionsBackportCallback):
        def __init__(self) -> None: ...
        def asBinder(self) -> android.os.IBinder: ...
        def onIsPermissionRevocationEnabledForAppResult(self, success: bool | java.jboolean | java.lang.Boolean, isEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class IUnusedAppRestrictionsBackportService(android.os.IInterface):
    DESCRIPTOR: typing.ClassVar[str] = ...
    def isPermissionRevocationEnabledForApp(self, arg1: IUnusedAppRestrictionsBackportCallback, /) -> None: ...

    class Stub(android.os.Binder, IUnusedAppRestrictionsBackportService):
        def __init__(self) -> None: ...
        def asBinder(self) -> android.os.IBinder: ...
        @staticmethod
        def asInterface(obj: android.os.IBinder, /) -> IUnusedAppRestrictionsBackportService: ...
        def onTransact(self, code: int | java.jint | java.lang.Integer, data: android.os.Parcel, reply: android.os.Parcel, flags: int | java.jint | java.lang.Integer, /) -> bool: ...

    class Default(IUnusedAppRestrictionsBackportService):
        def __init__(self) -> None: ...
        def asBinder(self) -> android.os.IBinder: ...
        def isPermissionRevocationEnabledForApp(self, callback: IUnusedAppRestrictionsBackportCallback, /) -> None: ...
