import android.animation
import java.lang
import kotlin
import kotlin.jvm.functions

class AnimatorKt(java.lang.Object):
    @staticmethod
    def addListener(this_addListener: android.animation.Animator, onEnd: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], onStart: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], onCancel: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], onRepeat: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], /) -> android.animation.Animator.AnimatorListener: ...
    @staticmethod
    def addPauseListener(this_addPauseListener: android.animation.Animator, onResume: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], onPause: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], /) -> android.animation.Animator.AnimatorPauseListener: ...
    @staticmethod
    def doOnCancel(this_doOnCancel: android.animation.Animator, action: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], /) -> android.animation.Animator.AnimatorListener: ...
    @staticmethod
    def doOnEnd(this_doOnEnd: android.animation.Animator, action: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], /) -> android.animation.Animator.AnimatorListener: ...
    @staticmethod
    def doOnPause(this_doOnPause: android.animation.Animator, action: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], /) -> android.animation.Animator.AnimatorPauseListener: ...
    @staticmethod
    def doOnRepeat(this_doOnRepeat: android.animation.Animator, action: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], /) -> android.animation.Animator.AnimatorListener: ...
    @staticmethod
    def doOnResume(this_doOnResume: android.animation.Animator, action: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], /) -> android.animation.Animator.AnimatorPauseListener: ...
    @staticmethod
    def doOnStart(this_doOnStart: android.animation.Animator, action: kotlin.jvm.functions.Function1[android.animation.Animator, kotlin.Unit], /) -> android.animation.Animator.AnimatorListener: ...
