import android.animation
import android.content
import android.graphics
import android.view
import androidx.activity
import androidx.dynamicanimation.animation
import java
import java.chaquopy
import java.lang
import typing



_MaterialBackAnimationHelper__V = typing.TypeVar('_MaterialBackAnimationHelper__V', bound=android.view.View)  # <V>
class MaterialBackAnimationHelper(java.lang.Object, typing.Generic[_MaterialBackAnimationHelper__V]):
    view: _MaterialBackAnimationHelper__V = ...
    hideDurationMax: int = ...
    hideDurationMin: int = ...
    cancelDuration: int = ...
    def __init__(self, view: _MaterialBackAnimationHelper__V, /) -> None: ...
    def interpolateProgress(self, progress: float | java.jfloat | java.lang.Float, /) -> float: ...
    def onCancelBackProgress(self) -> androidx.activity.BackEventCompat: ...
    def onHandleBackInvoked(self) -> androidx.activity.BackEventCompat: ...
    def onStartBackProgress(self, backEvent: androidx.activity.BackEventCompat, /) -> None: ...
    def onUpdateBackProgress(self, backEvent: androidx.activity.BackEventCompat, /) -> androidx.activity.BackEventCompat: ...

class MaterialBackHandler(java.lang.Object):
    def cancelBackProgress(self) -> None: ...
    def handleBackInvoked(self) -> None: ...
    def startBackProgress(self, arg1: androidx.activity.BackEventCompat, /) -> None: ...
    def updateBackProgress(self, arg1: androidx.activity.BackEventCompat, /) -> None: ...

class MaterialBackOrchestrator(java.lang.Object):
    @typing.overload
    def __init__(self, backHandlerView: android.view.View, /) -> None: ...
    @typing.overload
    def __init__(self, backHandler: MaterialBackHandler, view: android.view.View, /) -> None: ...
    def shouldListenForBackCallbacks(self) -> bool: ...
    def startListeningForBackCallbacks(self) -> None: ...
    def startListeningForBackCallbacksWithPriorityOverlay(self) -> None: ...
    def stopListeningForBackCallbacks(self) -> None: ...

class MaterialBottomContainerBackHelper(MaterialBackAnimationHelper[android.view.View]):
    def __init__(self, view: android.view.View, /) -> None: ...
    def cancelBackProgress(self) -> None: ...
    def finishBackProgressNotPersistent(self, backEvent: androidx.activity.BackEventCompat, animatorListener: android.animation.Animator.AnimatorListener, /) -> None: ...
    def finishBackProgressPersistent(self, backEvent: androidx.activity.BackEventCompat, animatorListener: android.animation.Animator.AnimatorListener, /) -> None: ...
    def startBackProgress(self, backEvent: androidx.activity.BackEventCompat, /) -> None: ...
    @typing.overload
    def updateBackProgress(self, progress: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def updateBackProgress(self, backEvent: androidx.activity.BackEventCompat, /) -> None: ...

class MaterialMainContainerBackHelper(MaterialBackAnimationHelper[android.view.View]):
    def __init__(self, view: android.view.View, /) -> None: ...
    def cancelBackProgress(self, collapsedView: android.view.View, /) -> None: ...
    def clearExpandedCornerRadii(self) -> None: ...
    def finishBackProgress(self, duration: int | java.jlong | java.lang.Long, collapsedView: android.view.View, /) -> None: ...
    def getExpandedCornerRadii(self) -> java.chaquopy.JavaArrayJFloat: ...
    def getInitialHideFromClipBounds(self) -> android.graphics.Rect: ...
    def getInitialHideToClipBounds(self) -> android.graphics.Rect: ...
    @typing.overload
    def startBackProgress(self, touchY: float | java.jfloat | java.lang.Float, collapsedView: android.view.View, /) -> None: ...
    @typing.overload
    def startBackProgress(self, backEvent: androidx.activity.BackEventCompat, collapsedView: android.view.View, /) -> None: ...
    @typing.overload
    def updateBackProgress(self, backEvent: androidx.activity.BackEventCompat, collapsedView: android.view.View, collapsedCornerSize: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def updateBackProgress(self, progress: float | java.jfloat | java.lang.Float, leftSwipeEdge: bool | java.jboolean | java.lang.Boolean, touchY: float | java.jfloat | java.lang.Float, collapsedCornerSize: float | java.jfloat | java.lang.Float, /) -> None: ...

class MaterialSideContainerBackHelper(MaterialBackAnimationHelper[android.view.View]):
    def __init__(self, view: android.view.View, /) -> None: ...
    def cancelBackProgress(self) -> None: ...
    def finishBackProgress(self, backEvent: androidx.activity.BackEventCompat, gravity: int | java.jint | java.lang.Integer, animatorListener: android.animation.Animator.AnimatorListener, finishAnimatorUpdateListener: android.animation.ValueAnimator.AnimatorUpdateListener, /) -> None: ...
    def startBackProgress(self, backEvent: androidx.activity.BackEventCompat, /) -> None: ...
    @typing.overload
    def updateBackProgress(self, backEvent: androidx.activity.BackEventCompat, gravity: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def updateBackProgress(self, progress: float | java.jfloat | java.lang.Float, leftSwipeEdge: bool | java.jboolean | java.lang.Boolean, gravity: int | java.jint | java.lang.Integer, /) -> None: ...

class MotionUtils(java.lang.Object):
    @staticmethod
    def resolveThemeDuration(context: android.content.Context, attrResId: int | java.jint | java.lang.Integer, defaultDuration: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def resolveThemeInterpolator(context: android.content.Context, attrResId: int | java.jint | java.lang.Integer, defaultInterpolator: android.animation.TimeInterpolator, /) -> android.animation.TimeInterpolator: ...
    @staticmethod
    def resolveThemeSpringForce(context: android.content.Context, attrResId: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, /) -> androidx.dynamicanimation.animation.SpringForce: ...
