import typing

import android.animation
import android.content
import android.content.res
import android.graphics
import android.graphics.drawable
import android.os
import android.util
import android.view
import androidx.coordinatorlayout.widget
import androidx.core.view
import androidx.core.widget
import com.google.android.material.animation
import com.google.android.material.expandable
import com.google.android.material.internal
import java
import java.lang
import java.lang.annotation


_FloatingActionButton__BaseBehavior__T = typing.TypeVar('_FloatingActionButton__BaseBehavior__T', bound=FloatingActionButton)  # <T>
class FloatingActionButton(com.google.android.material.internal.VisibilityAwareImageButton, androidx.core.view.TintableBackgroundView, androidx.core.widget.TintableImageSourceView, com.google.android.material.expandable.ExpandableTransformationWidget):
    SIZE_MINI: typing.ClassVar[int] = ...
    SIZE_NORMAL: typing.ClassVar[int] = ...
    SIZE_AUTO: typing.ClassVar[int] = ...
    NO_CUSTOM_SIZE: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def addOnHideAnimationListener(self, listener: android.animation.Animator.AnimatorListener, /) -> None: ...
    def addOnShowAnimationListener(self, listener: android.animation.Animator.AnimatorListener, /) -> None: ...
    def clearCustomSize(self) -> None: ...
    def drawableStateChanged(self) -> None: ...
    def getBackgroundTintList(self) -> android.content.res.ColorStateList: ...
    def getBackgroundTintMode(self) -> android.graphics.PorterDuff.Mode: ...
    def getCompatElevation(self) -> float: ...
    def getCompatHoveredFocusedTranslationZ(self) -> float: ...
    def getCompatPressedTranslationZ(self) -> float: ...
    def getContentBackground(self) -> android.graphics.drawable.Drawable: ...
    def getContentRect(self, rect: android.graphics.Rect, /) -> bool: ...
    def getCustomSize(self) -> int: ...
    def getExpandedComponentIdHint(self) -> int: ...
    def getHideMotionSpec(self) -> com.google.android.material.animation.MotionSpec: ...
    def getMeasuredContentRect(self, rect: android.graphics.Rect, /) -> None: ...
    def getRippleColor(self) -> int: ...
    def getRippleColorStateList(self) -> android.content.res.ColorStateList: ...
    def getShowMotionSpec(self) -> com.google.android.material.animation.MotionSpec: ...
    def getSize(self) -> int: ...
    def getSupportBackgroundTintList(self) -> android.content.res.ColorStateList: ...
    def getSupportBackgroundTintMode(self) -> android.graphics.PorterDuff.Mode: ...
    def getSupportImageTintList(self) -> android.content.res.ColorStateList: ...
    def getSupportImageTintMode(self) -> android.graphics.PorterDuff.Mode: ...
    def getUseCompatPadding(self) -> bool: ...
    @typing.overload
    def hide(self) -> None: ...
    @typing.overload
    def hide(self, listener: FloatingActionButton.OnVisibilityChangedListener, /) -> None: ...
    def isExpanded(self) -> bool: ...
    def isOrWillBeHidden(self) -> bool: ...
    def isOrWillBeShown(self) -> bool: ...
    def jumpDrawablesToCurrentState(self) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def onRestoreInstanceState(self, state: android.os.Parcelable, /) -> None: ...
    def onSaveInstanceState(self) -> android.os.Parcelable: ...
    def onTouchEvent(self, ev: android.view.MotionEvent, /) -> bool: ...
    def removeOnHideAnimationListener(self, listener: android.animation.Animator.AnimatorListener, /) -> None: ...
    def removeOnShowAnimationListener(self, listener: android.animation.Animator.AnimatorListener, /) -> None: ...
    def setBackgroundColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBackgroundDrawable(self, background: android.graphics.drawable.Drawable, /) -> None: ...
    def setBackgroundResource(self, resid: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBackgroundTintList(self, tint: android.content.res.ColorStateList, /) -> None: ...
    def setBackgroundTintMode(self, tintMode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def setCompatElevation(self, elevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setCompatElevationResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCompatHoveredFocusedTranslationZ(self, translationZ: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setCompatHoveredFocusedTranslationZResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCompatPressedTranslationZ(self, translationZ: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setCompatPressedTranslationZResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCustomSize(self, size: int | java.jint | java.lang.Integer, /) -> None: ...
    def setExpanded(self, expanded: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def setExpandedComponentIdHint(self, expandedComponentIdHint: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHideMotionSpec(self, spec: com.google.android.material.animation.MotionSpec, /) -> None: ...
    def setHideMotionSpecResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setImageDrawable(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...
    def setImageResource(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setRippleColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setRippleColor(self, color: android.content.res.ColorStateList, /) -> None: ...
    def setShowMotionSpec(self, spec: com.google.android.material.animation.MotionSpec, /) -> None: ...
    def setShowMotionSpecResource(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setSize(self, size: int | java.jint | java.lang.Integer, /) -> None: ...
    def setSupportBackgroundTintList(self, tint: android.content.res.ColorStateList, /) -> None: ...
    def setSupportBackgroundTintMode(self, tintMode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def setSupportImageTintList(self, tint: android.content.res.ColorStateList, /) -> None: ...
    def setSupportImageTintMode(self, tintMode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def setUseCompatPadding(self, useCompatPadding: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def show(self) -> None: ...
    @typing.overload
    def show(self, listener: FloatingActionButton.OnVisibilityChangedListener, /) -> None: ...
    class BaseBehavior(androidx.coordinatorlayout.widget.CoordinatorLayout.Behavior[_FloatingActionButton__BaseBehavior__T], typing.Generic[_FloatingActionButton__BaseBehavior__T]):
        @typing.overload
        def __init__(self) -> None: ...
        @typing.overload
        def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
        def getInsetDodgeRect(self, parent: androidx.coordinatorlayout.widget.CoordinatorLayout, child: FloatingActionButton, rect: android.graphics.Rect, /) -> bool: ...
        def isAutoHideEnabled(self) -> bool: ...
        def onAttachedToLayoutParams(self, lp: androidx.coordinatorlayout.widget.CoordinatorLayout.LayoutParams, /) -> None: ...
        def onDependentViewChanged(self, parent: androidx.coordinatorlayout.widget.CoordinatorLayout, child: FloatingActionButton, dependency: android.view.View, /) -> bool: ...
        def onLayoutChild(self, parent: androidx.coordinatorlayout.widget.CoordinatorLayout, child: FloatingActionButton, layoutDirection: int | java.jint | java.lang.Integer, /) -> bool: ...
        def setAutoHideEnabled(self, autoHide: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
        def setInternalAutoHideListener(self, listener: FloatingActionButton.OnVisibilityChangedListener, /) -> None: ...

    class Behavior(FloatingActionButton.BaseBehavior[FloatingActionButton]):
        @typing.overload
        def __init__(self) -> None: ...
        @typing.overload
        def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...

    class Size(java.lang.annotation.Annotation): ...

    class OnVisibilityChangedListener(java.lang.Object):
        def __init__(self) -> None: ...
        def onHidden(self, fab: FloatingActionButton, /) -> None: ...
        def onShown(self, fab: FloatingActionButton, /) -> None: ...

class FloatingActionButtonImpl(java.lang.Object):
    def addOnHideAnimationListener(self, listener: android.animation.Animator.AnimatorListener, /) -> None: ...
    def removeOnHideAnimationListener(self, listener: android.animation.Animator.AnimatorListener, /) -> None: ...

class FloatingActionButtonImplLollipop(FloatingActionButtonImpl):
    def getElevation(self) -> float: ...
