import android.os
import java
import java.lang



class ExpandableTransformationWidget(ExpandableWidget):
    def getExpandedComponentIdHint(self) -> int: ...
    def setExpandedComponentIdHint(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...

class ExpandableWidget(java.lang.Object):
    def isExpanded(self) -> bool: ...
    def setExpanded(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...

class ExpandableWidgetHelper(java.lang.Object):
    def __init__(self, widget: ExpandableWidget, /) -> None: ...
    def getExpandedComponentIdHint(self) -> int: ...
    def isExpanded(self) -> bool: ...
    def onRestoreInstanceState(self, state: android.os.Bundle, /) -> None: ...
    def onSaveInstanceState(self) -> android.os.Bundle: ...
    def setExpanded(self, expanded: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def setExpandedComponentIdHint(self, expandedComponentIdHint: int | java.jint | java.lang.Integer, /) -> None: ...
