import typing

import java
import java.chaquopy
import java.lang
import java.util
import kotlin
import kotlin.collections
import kotlin.jvm.functions
import kotlin.jvm.internal.markers

_ArrayMap__K = typing.TypeVar('_ArrayMap__K')  # <K>
_ArrayMap__V = typing.TypeVar('_ArrayMap__V')  # <V>
class ArrayMap(SimpleArrayMap[_ArrayMap__K, _ArrayMap__V], java.util.Map[_ArrayMap__K, _ArrayMap__V], typing.Generic[_ArrayMap__K, _ArrayMap__V]):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, capacity: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, map: SimpleArrayMap, /) -> None: ...
    def containsAll(self, collection: java.util.Collection[java.lang.Object], /) -> bool: ...
    def containsKey(self, key: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def containsValue(self, value: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def entrySet(self) -> java.util.Set[java.util.Map.Entry[_ArrayMap__K, _ArrayMap__V]]: ...
    def get(self, key: java.lang.Object | int | bool | float | str, /) -> _ArrayMap__V: ...
    def keySet(self) -> java.util.Set[_ArrayMap__K]: ...
    def putAll(self, map: java.util.Map[_ArrayMap__K, _ArrayMap__V], /) -> None: ...
    def remove(self, key: java.lang.Object | int | bool | float | str, /) -> _ArrayMap__V: ...
    def removeAll(self, collection: java.util.Collection[java.lang.Object], /) -> bool: ...
    def retainAll(self, collection: java.util.Collection[java.lang.Object], /) -> bool: ...
    def values(self) -> java.util.Collection[_ArrayMap__V]: ...

class ArrayMapKt(java.lang.Object):
    _arrayMapOf_1__K = typing.TypeVar('_arrayMapOf_1__K')  # <K>
    _arrayMapOf_1__V = typing.TypeVar('_arrayMapOf_1__V')  # <V>
    @typing.overload
    @staticmethod
    def arrayMapOf() -> ArrayMap[java.lang.Object, java.lang.Object]: ...
    @typing.overload
    @staticmethod
    def arrayMapOf(*pairs: kotlin.Pair[_arrayMapOf_1__K, _arrayMapOf_1__V]) -> ArrayMap[_arrayMapOf_1__K, _arrayMapOf_1__V]: ...

_ArraySet__E = typing.TypeVar('_ArraySet__E')  # <E>
class ArraySet(java.util.Collection[_ArraySet__E], java.util.Set[_ArraySet__E], kotlin.jvm.internal.markers.KMutableCollection, kotlin.jvm.internal.markers.KMutableSet, typing.Generic[_ArraySet__E]):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, capacity: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, set: ArraySet[_ArraySet__E], /) -> None: ...
    @typing.overload
    def __init__(self, set: java.util.Collection[_ArraySet__E], /) -> None: ...
    @typing.overload
    def __init__(self, array: java.chaquopy.JavaArray[_ArraySet__E], /) -> None: ...
    def add(self, element: _ArraySet__E, /) -> bool: ...
    @typing.overload
    def addAll(self, array: ArraySet[_ArraySet__E], /) -> None: ...
    @typing.overload
    def addAll(self, elements: java.util.Collection[_ArraySet__E], /) -> bool: ...
    def clear(self) -> None: ...
    def contains(self, element: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def containsAll(self, elements: java.util.Collection[java.lang.Object], /) -> bool: ...
    def ensureCapacity(self, minimumCapacity: int | java.jint | java.lang.Integer, /) -> None: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getArray$collection(self) -> java.chaquopy.JavaArray[java.lang.Object]: ...
    def getHashes$collection(self) -> java.chaquopy.JavaArrayJInt: ...
    def getSize(self) -> int: ...
    def get_size$collection(self) -> int: ...
    def hashCode(self) -> int: ...
    def indexOf(self, key: java.lang.Object | int | bool | float | str, /) -> int: ...
    def isEmpty(self) -> bool: ...
    def iterator(self) -> java.util.Iterator[_ArraySet__E]: ...
    def remove(self, element: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @typing.overload
    def removeAll(self, array: ArraySet[_ArraySet__E], /) -> bool: ...
    @typing.overload
    def removeAll(self, elements: java.util.Collection[java.lang.Object], /) -> bool: ...
    def removeAt(self, index: int | java.jint | java.lang.Integer, /) -> _ArraySet__E: ...
    def retainAll(self, elements: java.util.Collection[java.lang.Object], /) -> bool: ...
    def setArray$collection(self, <set-?>: java.chaquopy.JavaArray[java.lang.Object], /) -> None: ...
    def setHashes$collection(self, <set-?>: java.chaquopy.JavaArrayJInt, /) -> None: ...
    def set_size$collection(self, <set-?>: int | java.jint | java.lang.Integer, /) -> None: ...
    _toArray_1__T = typing.TypeVar('_toArray_1__T')  # <T>
    @typing.overload
    def toArray(self) -> java.chaquopy.JavaArray[java.lang.Object]: ...
    @typing.overload
    def toArray(self, array: java.chaquopy.JavaArray[_toArray_1__T], /) -> java.chaquopy.JavaArray[_toArray_1__T]: ...
    def toString(self) -> str: ...
    def valueAt(self, index: int | java.jint | java.lang.Integer, /) -> _ArraySet__E: ...

class ArraySetJvmUtil(java.lang.Object): ...

class ArraySetKt(java.lang.Object):
    ARRAY_SET_BASE_SIZE: typing.ClassVar[int] = ...
    _addAllInternal_0__E = typing.TypeVar('_addAllInternal_0__E')  # <E>
    _addAllInternal_1__E = typing.TypeVar('_addAllInternal_1__E')  # <E>
    @typing.overload
    @staticmethod
    def addAllInternal(this_addAllInternal: ArraySet[_addAllInternal_0__E], array: ArraySet[_addAllInternal_0__E], /) -> None: ...
    @typing.overload
    @staticmethod
    def addAllInternal(this_addAllInternal: ArraySet[_addAllInternal_1__E], elements: java.util.Collection[_addAllInternal_1__E], /) -> bool: ...
    _addInternal__E = typing.TypeVar('_addInternal__E')  # <E>
    @staticmethod
    def addInternal(this_addInternal: ArraySet[_addInternal__E], element: _addInternal__E, /) -> bool: ...
    @staticmethod
    def allocArrays(this_allocArrays: ArraySet[java.lang.Object], size: int | java.jint | java.lang.Integer, /) -> None: ...
    _arraySetOf_1__T = typing.TypeVar('_arraySetOf_1__T')  # <T>
    @typing.overload
    @staticmethod
    def arraySetOf() -> ArraySet[java.lang.Object]: ...
    @typing.overload
    @staticmethod
    def arraySetOf(*values: _arraySetOf_1__T) -> ArraySet[_arraySetOf_1__T]: ...
    @staticmethod
    def binarySearchInternal(this_binarySearchInternal: ArraySet[java.lang.Object], hash: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def clearInternal(this_clearInternal: ArraySet[java.lang.Object], /) -> None: ...
    _containsAllInternal__E = typing.TypeVar('_containsAllInternal__E')  # <E>
    @staticmethod
    def containsAllInternal(this_containsAllInternal: ArraySet[_containsAllInternal__E], elements: java.util.Collection[_containsAllInternal__E], /) -> bool: ...
    _containsInternal__E = typing.TypeVar('_containsInternal__E')  # <E>
    @staticmethod
    def containsInternal(this_containsInternal: ArraySet[_containsInternal__E], element: _containsInternal__E, /) -> bool: ...
    @staticmethod
    def ensureCapacityInternal(this_ensureCapacityInternal: ArraySet[java.lang.Object], minimumCapacity: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def equalsInternal(this_equalsInternal: ArraySet[java.lang.Object], other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def hashCodeInternal(this_hashCodeInternal: ArraySet[java.lang.Object], /) -> int: ...
    @staticmethod
    def indexOf(this_indexOf: ArraySet[java.lang.Object], key: java.lang.Object | int | bool | float | str, hash: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def indexOfInternal(this_indexOfInternal: ArraySet[java.lang.Object], key: java.lang.Object | int | bool | float | str, /) -> int: ...
    @staticmethod
    def indexOfNull(this_indexOfNull: ArraySet[java.lang.Object], /) -> int: ...
    @staticmethod
    def isEmptyInternal(this_isEmptyInternal: ArraySet[java.lang.Object], /) -> bool: ...
    _removeAllInternal_0__E = typing.TypeVar('_removeAllInternal_0__E')  # <E>
    _removeAllInternal_1__E = typing.TypeVar('_removeAllInternal_1__E')  # <E>
    @typing.overload
    @staticmethod
    def removeAllInternal(this_removeAllInternal: ArraySet[_removeAllInternal_0__E], array: ArraySet[_removeAllInternal_0__E], /) -> bool: ...
    @typing.overload
    @staticmethod
    def removeAllInternal(this_removeAllInternal: ArraySet[_removeAllInternal_1__E], elements: java.util.Collection[_removeAllInternal_1__E], /) -> bool: ...
    _removeAtInternal__E = typing.TypeVar('_removeAtInternal__E')  # <E>
    @staticmethod
    def removeAtInternal(this_removeAtInternal: ArraySet[_removeAtInternal__E], index: int | java.jint | java.lang.Integer, /) -> _removeAtInternal__E: ...
    _removeInternal__E = typing.TypeVar('_removeInternal__E')  # <E>
    @staticmethod
    def removeInternal(this_removeInternal: ArraySet[_removeInternal__E], element: _removeInternal__E, /) -> bool: ...
    _retainAllInternal__E = typing.TypeVar('_retainAllInternal__E')  # <E>
    @staticmethod
    def retainAllInternal(this_retainAllInternal: ArraySet[_retainAllInternal__E], elements: java.util.Collection[_retainAllInternal__E], /) -> bool: ...
    @staticmethod
    def toStringInternal(this_toStringInternal: ArraySet[java.lang.Object], /) -> str: ...
    _valueAtInternal__E = typing.TypeVar('_valueAtInternal__E')  # <E>
    @staticmethod
    def valueAtInternal(this_valueAtInternal: ArraySet[_valueAtInternal__E], index: int | java.jint | java.lang.Integer, /) -> _valueAtInternal__E: ...

_CircularArray__E = typing.TypeVar('_CircularArray__E')  # <E>
class CircularArray(java.lang.Object, typing.Generic[_CircularArray__E]):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, minCapacity: int | java.jint | java.lang.Integer, /) -> None: ...
    def addFirst(self, element: _CircularArray__E, /) -> None: ...
    def addLast(self, element: _CircularArray__E, /) -> None: ...
    def clear(self) -> None: ...
    def get(self, index: int | java.jint | java.lang.Integer, /) -> _CircularArray__E: ...
    def getFirst(self) -> _CircularArray__E: ...
    def getLast(self) -> _CircularArray__E: ...
    def isEmpty(self) -> bool: ...
    def popFirst(self) -> _CircularArray__E: ...
    def popLast(self) -> _CircularArray__E: ...
    def removeFromEnd(self, count: int | java.jint | java.lang.Integer, /) -> None: ...
    def removeFromStart(self, count: int | java.jint | java.lang.Integer, /) -> None: ...
    def size(self) -> int: ...

class CircularIntArray(java.lang.Object):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, minCapacity: int | java.jint | java.lang.Integer, /) -> None: ...
    def addFirst(self, element: int | java.jint | java.lang.Integer, /) -> None: ...
    def addLast(self, element: int | java.jint | java.lang.Integer, /) -> None: ...
    def clear(self) -> None: ...
    def get(self, index: int | java.jint | java.lang.Integer, /) -> int: ...
    def getFirst(self) -> int: ...
    def getLast(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def popFirst(self) -> int: ...
    def popLast(self) -> int: ...
    def removeFromEnd(self, count: int | java.jint | java.lang.Integer, /) -> None: ...
    def removeFromStart(self, count: int | java.jint | java.lang.Integer, /) -> None: ...
    def size(self) -> int: ...

class CollectionPlatformUtils(java.lang.Object):
    INSTANCE: typing.ClassVar[CollectionPlatformUtils] = ...
    def createIndexOutOfBoundsException$collection(self) -> java.lang.IndexOutOfBoundsException: ...

_IndexBasedArrayIterator__T = typing.TypeVar('_IndexBasedArrayIterator__T')  # <T>
class IndexBasedArrayIterator(java.util.Iterator[_IndexBasedArrayIterator__T], kotlin.jvm.internal.markers.KMutableIterator, typing.Generic[_IndexBasedArrayIterator__T]):
    def __init__(self, startingSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def elementAt(self, arg1: int | java.jint | java.lang.Integer, /) -> _IndexBasedArrayIterator__T: ...
    def hasNext(self) -> bool: ...
    def next(self) -> _IndexBasedArrayIterator__T: ...
    def remove(self) -> None: ...
    def removeAt(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...

_LongSparseArray__E = typing.TypeVar('_LongSparseArray__E')  # <E>
class LongSparseArray(java.lang.Cloneable, typing.Generic[_LongSparseArray__E]):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, initialCapacity: int | java.jint | java.lang.Integer, /) -> None: ...
    def append(self, key: int | java.jlong | java.lang.Long, value: _LongSparseArray__E, /) -> None: ...
    def clear(self) -> None: ...
    def clone(self) -> LongSparseArray[_LongSparseArray__E]: ...
    def containsKey(self, key: int | java.jlong | java.lang.Long, /) -> bool: ...
    def containsValue(self, value: _LongSparseArray__E, /) -> bool: ...
    def delete(self, key: int | java.jlong | java.lang.Long, /) -> None: ...
    @typing.overload
    def get(self, key: int | java.jlong | java.lang.Long, /) -> _LongSparseArray__E: ...
    @typing.overload
    def get(self, key: int | java.jlong | java.lang.Long, defaultValue: _LongSparseArray__E, /) -> _LongSparseArray__E: ...
    def indexOfKey(self, key: int | java.jlong | java.lang.Long, /) -> int: ...
    def indexOfValue(self, value: _LongSparseArray__E, /) -> int: ...
    def isEmpty(self) -> bool: ...
    def keyAt(self, index: int | java.jint | java.lang.Integer, /) -> int: ...
    def put(self, key: int | java.jlong | java.lang.Long, value: _LongSparseArray__E, /) -> None: ...
    def putAll(self, other: LongSparseArray[_LongSparseArray__E], /) -> None: ...
    def putIfAbsent(self, key: int | java.jlong | java.lang.Long, value: _LongSparseArray__E, /) -> _LongSparseArray__E: ...
    @typing.overload
    def remove(self, key: int | java.jlong | java.lang.Long, /) -> None: ...
    @typing.overload
    def remove(self, key: int | java.jlong | java.lang.Long, value: _LongSparseArray__E, /) -> bool: ...
    def removeAt(self, index: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def replace(self, key: int | java.jlong | java.lang.Long, value: _LongSparseArray__E, /) -> _LongSparseArray__E: ...
    @typing.overload
    def replace(self, key: int | java.jlong | java.lang.Long, oldValue: _LongSparseArray__E, newValue: _LongSparseArray__E, /) -> bool: ...
    def setValueAt(self, index: int | java.jint | java.lang.Integer, value: _LongSparseArray__E, /) -> None: ...
    def size(self) -> int: ...
    def toString(self) -> str: ...
    def valueAt(self, index: int | java.jint | java.lang.Integer, /) -> _LongSparseArray__E: ...

class LongSparseArrayKt(java.lang.Object):
    _commonAppend__E = typing.TypeVar('_commonAppend__E')  # <E>
    @staticmethod
    def commonAppend(this_commonAppend: LongSparseArray[_commonAppend__E], key: int | java.jlong | java.lang.Long, value: _commonAppend__E, /) -> None: ...
    @staticmethod
    def commonClear(this_commonClear: LongSparseArray[java.lang.Object], /) -> None: ...
    @staticmethod
    def commonContainsKey(this_commonContainsKey: LongSparseArray[java.lang.Object], key: int | java.jlong | java.lang.Long, /) -> bool: ...
    _commonContainsValue__E = typing.TypeVar('_commonContainsValue__E')  # <E>
    @staticmethod
    def commonContainsValue(this_commonContainsValue: LongSparseArray[_commonContainsValue__E], value: _commonContainsValue__E, /) -> bool: ...
    @staticmethod
    def commonGc(this_commonGc: LongSparseArray[java.lang.Object], /) -> None: ...
    _commonGet_0__E = typing.TypeVar('_commonGet_0__E')  # <E>
    _commonGet_1__E = typing.TypeVar('_commonGet_1__E')  # <E>
    @typing.overload
    @staticmethod
    def commonGet(this_commonGet: LongSparseArray[_commonGet_0__E], key: int | java.jlong | java.lang.Long, /) -> _commonGet_0__E: ...
    @typing.overload
    @staticmethod
    def commonGet(this_commonGet: LongSparseArray[_commonGet_1__E], key: int | java.jlong | java.lang.Long, defaultValue: _commonGet_1__E, /) -> _commonGet_1__E: ...
    _commonGetInternal__T = typing.TypeVar('_commonGetInternal__T')  # <T>
    @staticmethod
    def commonGetInternal(this_commonGetInternal: LongSparseArray[java.lang.Object], key: int | java.jlong | java.lang.Long, defaultValue: _commonGetInternal__T, /) -> _commonGetInternal__T: ...
    @staticmethod
    def commonIndexOfKey(this_commonIndexOfKey: LongSparseArray[java.lang.Object], key: int | java.jlong | java.lang.Long, /) -> int: ...
    _commonIndexOfValue__E = typing.TypeVar('_commonIndexOfValue__E')  # <E>
    @staticmethod
    def commonIndexOfValue(this_commonIndexOfValue: LongSparseArray[_commonIndexOfValue__E], value: _commonIndexOfValue__E, /) -> int: ...
    @staticmethod
    def commonIsEmpty(this_commonIsEmpty: LongSparseArray[java.lang.Object], /) -> bool: ...
    @staticmethod
    def commonKeyAt(this_commonKeyAt: LongSparseArray[java.lang.Object], index: int | java.jint | java.lang.Integer, /) -> int: ...
    _commonPut__E = typing.TypeVar('_commonPut__E')  # <E>
    @staticmethod
    def commonPut(this_commonPut: LongSparseArray[_commonPut__E], key: int | java.jlong | java.lang.Long, value: _commonPut__E, /) -> None: ...
    _commonPutAll__E = typing.TypeVar('_commonPutAll__E')  # <E>
    @staticmethod
    def commonPutAll(this_commonPutAll: LongSparseArray[_commonPutAll__E], other: LongSparseArray[_commonPutAll__E], /) -> None: ...
    _commonPutIfAbsent__E = typing.TypeVar('_commonPutIfAbsent__E')  # <E>
    @staticmethod
    def commonPutIfAbsent(this_commonPutIfAbsent: LongSparseArray[_commonPutIfAbsent__E], key: int | java.jlong | java.lang.Long, value: _commonPutIfAbsent__E, /) -> _commonPutIfAbsent__E: ...
    _commonRemove_1__E = typing.TypeVar('_commonRemove_1__E')  # <E>
    @typing.overload
    @staticmethod
    def commonRemove(this_commonRemove: LongSparseArray[java.lang.Object], key: int | java.jlong | java.lang.Long, /) -> None: ...
    @typing.overload
    @staticmethod
    def commonRemove(this_commonRemove: LongSparseArray[_commonRemove_1__E], key: int | java.jlong | java.lang.Long, value: _commonRemove_1__E, /) -> bool: ...
    @staticmethod
    def commonRemoveAt(this_commonRemoveAt: LongSparseArray[java.lang.Object], index: int | java.jint | java.lang.Integer, /) -> None: ...
    _commonReplace_0__E = typing.TypeVar('_commonReplace_0__E')  # <E>
    _commonReplace_1__E = typing.TypeVar('_commonReplace_1__E')  # <E>
    @typing.overload
    @staticmethod
    def commonReplace(this_commonReplace: LongSparseArray[_commonReplace_0__E], key: int | java.jlong | java.lang.Long, value: _commonReplace_0__E, /) -> _commonReplace_0__E: ...
    @typing.overload
    @staticmethod
    def commonReplace(this_commonReplace: LongSparseArray[_commonReplace_1__E], key: int | java.jlong | java.lang.Long, oldValue: _commonReplace_1__E, newValue: _commonReplace_1__E, /) -> bool: ...
    _commonSetValueAt__E = typing.TypeVar('_commonSetValueAt__E')  # <E>
    @staticmethod
    def commonSetValueAt(this_commonSetValueAt: LongSparseArray[_commonSetValueAt__E], index: int | java.jint | java.lang.Integer, value: _commonSetValueAt__E, /) -> None: ...
    @staticmethod
    def commonSize(this_commonSize: LongSparseArray[java.lang.Object], /) -> int: ...
    @staticmethod
    def commonToString(this_commonToString: LongSparseArray[java.lang.Object], /) -> str: ...
    _commonValueAt__E = typing.TypeVar('_commonValueAt__E')  # <E>
    @staticmethod
    def commonValueAt(this_commonValueAt: LongSparseArray[_commonValueAt__E], index: int | java.jint | java.lang.Integer, /) -> _commonValueAt__E: ...
    @staticmethod
    def contains(this_contains: LongSparseArray[java.lang.Object], key: int | java.jlong | java.lang.Long, /) -> bool: ...
    _forEach__T = typing.TypeVar('_forEach__T')  # <T>
    @staticmethod
    def forEach(this_forEach: LongSparseArray[_forEach__T], action: kotlin.jvm.functions.Function2[int, _forEach__T, kotlin.Unit], /) -> None: ...
    _getOrDefault__T = typing.TypeVar('_getOrDefault__T')  # <T>
    @staticmethod
    def getOrDefault(this_getOrDefault: LongSparseArray[_getOrDefault__T], key: int | java.jlong | java.lang.Long, defaultValue: _getOrDefault__T, /) -> _getOrDefault__T: ...
    _getOrElse__T = typing.TypeVar('_getOrElse__T')  # <T>
    @staticmethod
    def getOrElse(this_getOrElse: LongSparseArray[_getOrElse__T], key: int | java.jlong | java.lang.Long, defaultValue: kotlin.jvm.functions.Function0[_getOrElse__T], /) -> _getOrElse__T: ...
    @staticmethod
    def getSize(this_size: LongSparseArray[java.lang.Object], /) -> int: ...
    @staticmethod
    def isNotEmpty(this_isNotEmpty: LongSparseArray[java.lang.Object], /) -> bool: ...
    @staticmethod
    def keyIterator(this_keyIterator: LongSparseArray[java.lang.Object], /) -> kotlin.collections.LongIterator: ...
    _plus__T = typing.TypeVar('_plus__T')  # <T>
    @staticmethod
    def plus(this_plus: LongSparseArray[_plus__T], other: LongSparseArray[_plus__T], /) -> LongSparseArray[_plus__T]: ...
    _set__T = typing.TypeVar('_set__T')  # <T>
    @staticmethod
    def set(this_set: LongSparseArray[_set__T], key: int | java.jlong | java.lang.Long, value: _set__T, /) -> None: ...
    _valueIterator__T = typing.TypeVar('_valueIterator__T')  # <T>
    @staticmethod
    def valueIterator(this_valueIterator: LongSparseArray[_valueIterator__T], /) -> java.util.Iterator[_valueIterator__T]: ...

_LruCache__K = typing.TypeVar('_LruCache__K')  # <K>
_LruCache__V = typing.TypeVar('_LruCache__V')  # <V>
class LruCache(java.lang.Object, typing.Generic[_LruCache__K, _LruCache__V]):
    def __init__(self, maxSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def create(self, key: _LruCache__K, /) -> _LruCache__V: ...
    def createCount(self) -> int: ...
    def entryRemoved(self, evicted: bool | java.jboolean | java.lang.Boolean, key: _LruCache__K, oldValue: _LruCache__V, newValue: _LruCache__V, /) -> None: ...
    def evictAll(self) -> None: ...
    def evictionCount(self) -> int: ...
    def get(self, key: _LruCache__K, /) -> _LruCache__V: ...
    def hitCount(self) -> int: ...
    def maxSize(self) -> int: ...
    def missCount(self) -> int: ...
    def put(self, key: _LruCache__K, value: _LruCache__V, /) -> _LruCache__V: ...
    def putCount(self) -> int: ...
    def remove(self, key: _LruCache__K, /) -> _LruCache__V: ...
    def resize(self, maxSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def size(self) -> int: ...
    def sizeOf(self, key: _LruCache__K, value: _LruCache__V, /) -> int: ...
    def snapshot(self) -> java.util.Map[_LruCache__K, _LruCache__V]: ...
    def toString(self) -> str: ...
    def trimToSize(self, maxSize: int | java.jint | java.lang.Integer, /) -> None: ...

class LruCacheKt(java.lang.Object):
    _lruCache__K = typing.TypeVar('_lruCache__K')  # <K>
    _lruCache__V = typing.TypeVar('_lruCache__V')  # <V>
    @staticmethod
    def lruCache(maxSize: int | java.jint | java.lang.Integer, sizeOf: kotlin.jvm.functions.Function2[_lruCache__K, _lruCache__V, java.lang.Integer], create: kotlin.jvm.functions.Function1[_lruCache__K, _lruCache__V], onEntryRemoved: kotlin.jvm.functions.Function4[bool, _lruCache__K, _lruCache__V, _lruCache__V, kotlin.Unit], /) -> LruCache[_lruCache__K, _lruCache__V]: ...

_SimpleArrayMap__K = typing.TypeVar('_SimpleArrayMap__K')  # <K>
_SimpleArrayMap__V = typing.TypeVar('_SimpleArrayMap__V')  # <V>
class SimpleArrayMap(java.lang.Object, typing.Generic[_SimpleArrayMap__K, _SimpleArrayMap__V]):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, capacity: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, map: SimpleArrayMap[_SimpleArrayMap__K, _SimpleArrayMap__V], /) -> None: ...
    def __restricted$indexOfValue(self, value: _SimpleArrayMap__V, /) -> int: ...
    def clear(self) -> None: ...
    def containsKey(self, key: _SimpleArrayMap__K, /) -> bool: ...
    def containsValue(self, value: _SimpleArrayMap__V, /) -> bool: ...
    def ensureCapacity(self, minimumCapacity: int | java.jint | java.lang.Integer, /) -> None: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def get(self, key: _SimpleArrayMap__K, /) -> _SimpleArrayMap__V: ...
    def getOrDefault(self, key: java.lang.Object | int | bool | float | str, defaultValue: _SimpleArrayMap__V, /) -> _SimpleArrayMap__V: ...
    def hashCode(self) -> int: ...
    def indexOfKey(self, key: _SimpleArrayMap__K, /) -> int: ...
    def isEmpty(self) -> bool: ...
    def keyAt(self, index: int | java.jint | java.lang.Integer, /) -> _SimpleArrayMap__K: ...
    def put(self, key: _SimpleArrayMap__K, value: _SimpleArrayMap__V, /) -> _SimpleArrayMap__V: ...
    def putAll(self, map: SimpleArrayMap[_SimpleArrayMap__K, _SimpleArrayMap__V], /) -> None: ...
    def putIfAbsent(self, key: _SimpleArrayMap__K, value: _SimpleArrayMap__V, /) -> _SimpleArrayMap__V: ...
    @typing.overload
    def remove(self, key: _SimpleArrayMap__K, /) -> _SimpleArrayMap__V: ...
    @typing.overload
    def remove(self, key: _SimpleArrayMap__K, value: _SimpleArrayMap__V, /) -> bool: ...
    def removeAt(self, index: int | java.jint | java.lang.Integer, /) -> _SimpleArrayMap__V: ...
    @typing.overload
    def replace(self, key: _SimpleArrayMap__K, value: _SimpleArrayMap__V, /) -> _SimpleArrayMap__V: ...
    @typing.overload
    def replace(self, key: _SimpleArrayMap__K, oldValue: _SimpleArrayMap__V, newValue: _SimpleArrayMap__V, /) -> bool: ...
    def setValueAt(self, index: int | java.jint | java.lang.Integer, value: _SimpleArrayMap__V, /) -> _SimpleArrayMap__V: ...
    def size(self) -> int: ...
    def toString(self) -> str: ...
    def valueAt(self, index: int | java.jint | java.lang.Integer, /) -> _SimpleArrayMap__V: ...

class SimpleArrayMapKt(java.lang.Object): ...

_SparseArrayCompat__E = typing.TypeVar('_SparseArrayCompat__E')  # <E>
class SparseArrayCompat(java.lang.Cloneable, typing.Generic[_SparseArrayCompat__E]):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, initialCapacity: int | java.jint | java.lang.Integer, /) -> None: ...
    def append(self, key: int | java.jint | java.lang.Integer, value: _SparseArrayCompat__E, /) -> None: ...
    def clear(self) -> None: ...
    def clone(self) -> SparseArrayCompat[_SparseArrayCompat__E]: ...
    def containsKey(self, key: int | java.jint | java.lang.Integer, /) -> bool: ...
    def containsValue(self, value: _SparseArrayCompat__E, /) -> bool: ...
    def delete(self, key: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def get(self, key: int | java.jint | java.lang.Integer, /) -> _SparseArrayCompat__E: ...
    @typing.overload
    def get(self, key: int | java.jint | java.lang.Integer, defaultValue: _SparseArrayCompat__E, /) -> _SparseArrayCompat__E: ...
    def getIsEmpty(self) -> bool: ...
    def indexOfKey(self, key: int | java.jint | java.lang.Integer, /) -> int: ...
    def indexOfValue(self, value: _SparseArrayCompat__E, /) -> int: ...
    def isEmpty(self) -> bool: ...
    def keyAt(self, index: int | java.jint | java.lang.Integer, /) -> int: ...
    def put(self, key: int | java.jint | java.lang.Integer, value: _SparseArrayCompat__E, /) -> None: ...
    def putAll(self, other: SparseArrayCompat[_SparseArrayCompat__E], /) -> None: ...
    def putIfAbsent(self, key: int | java.jint | java.lang.Integer, value: _SparseArrayCompat__E, /) -> _SparseArrayCompat__E: ...
    @typing.overload
    def remove(self, key: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def remove(self, key: int | java.jint | java.lang.Integer, value: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def removeAt(self, index: int | java.jint | java.lang.Integer, /) -> None: ...
    def removeAtRange(self, index: int | java.jint | java.lang.Integer, size: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def replace(self, key: int | java.jint | java.lang.Integer, value: _SparseArrayCompat__E, /) -> _SparseArrayCompat__E: ...
    @typing.overload
    def replace(self, key: int | java.jint | java.lang.Integer, oldValue: _SparseArrayCompat__E, newValue: _SparseArrayCompat__E, /) -> bool: ...
    def setValueAt(self, index: int | java.jint | java.lang.Integer, value: _SparseArrayCompat__E, /) -> None: ...
    def size(self) -> int: ...
    def toString(self) -> str: ...
    def valueAt(self, index: int | java.jint | java.lang.Integer, /) -> _SparseArrayCompat__E: ...

class SparseArrayCompatKt(java.lang.Object):
    _commonAppend__E = typing.TypeVar('_commonAppend__E')  # <E>
    @staticmethod
    def commonAppend(this_commonAppend: SparseArrayCompat[_commonAppend__E], key: int | java.jint | java.lang.Integer, value: _commonAppend__E, /) -> None: ...
    @staticmethod
    def commonClear(this_commonClear: SparseArrayCompat[java.lang.Object], /) -> None: ...
    @staticmethod
    def commonContainsKey(this_commonContainsKey: SparseArrayCompat[java.lang.Object], key: int | java.jint | java.lang.Integer, /) -> bool: ...
    _commonContainsValue__E = typing.TypeVar('_commonContainsValue__E')  # <E>
    @staticmethod
    def commonContainsValue(this_commonContainsValue: SparseArrayCompat[_commonContainsValue__E], value: _commonContainsValue__E, /) -> bool: ...
    _commonGet_0__E = typing.TypeVar('_commonGet_0__E')  # <E>
    _commonGet_1__E = typing.TypeVar('_commonGet_1__E')  # <E>
    @typing.overload
    @staticmethod
    def commonGet(this_commonGet: SparseArrayCompat[_commonGet_0__E], key: int | java.jint | java.lang.Integer, /) -> _commonGet_0__E: ...
    @typing.overload
    @staticmethod
    def commonGet(this_commonGet: SparseArrayCompat[_commonGet_1__E], key: int | java.jint | java.lang.Integer, defaultValue: _commonGet_1__E, /) -> _commonGet_1__E: ...
    @staticmethod
    def commonIndexOfKey(this_commonIndexOfKey: SparseArrayCompat[java.lang.Object], key: int | java.jint | java.lang.Integer, /) -> int: ...
    _commonIndexOfValue__E = typing.TypeVar('_commonIndexOfValue__E')  # <E>
    @staticmethod
    def commonIndexOfValue(this_commonIndexOfValue: SparseArrayCompat[_commonIndexOfValue__E], value: _commonIndexOfValue__E, /) -> int: ...
    @staticmethod
    def commonIsEmpty(this_commonIsEmpty: SparseArrayCompat[java.lang.Object], /) -> bool: ...
    @staticmethod
    def commonKeyAt(this_commonKeyAt: SparseArrayCompat[java.lang.Object], index: int | java.jint | java.lang.Integer, /) -> int: ...
    _commonPut__E = typing.TypeVar('_commonPut__E')  # <E>
    @staticmethod
    def commonPut(this_commonPut: SparseArrayCompat[_commonPut__E], key: int | java.jint | java.lang.Integer, value: _commonPut__E, /) -> None: ...
    _commonPutAll__E = typing.TypeVar('_commonPutAll__E')  # <E>
    @staticmethod
    def commonPutAll(this_commonPutAll: SparseArrayCompat[_commonPutAll__E], other: SparseArrayCompat[_commonPutAll__E], /) -> None: ...
    _commonPutIfAbsent__E = typing.TypeVar('_commonPutIfAbsent__E')  # <E>
    @staticmethod
    def commonPutIfAbsent(this_commonPutIfAbsent: SparseArrayCompat[_commonPutIfAbsent__E], key: int | java.jint | java.lang.Integer, value: _commonPutIfAbsent__E, /) -> _commonPutIfAbsent__E: ...
    @typing.overload
    @staticmethod
    def commonRemove(this_commonRemove: SparseArrayCompat[java.lang.Object], key: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    @staticmethod
    def commonRemove(this_commonRemove: SparseArrayCompat[java.lang.Object], key: int | java.jint | java.lang.Integer, value: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def commonRemoveAt(this_commonRemoveAt: SparseArrayCompat[java.lang.Object], index: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def commonRemoveAtRange(this_commonRemoveAtRange: SparseArrayCompat[java.lang.Object], index: int | java.jint | java.lang.Integer, size: int | java.jint | java.lang.Integer, /) -> None: ...
    _commonReplace_0__E = typing.TypeVar('_commonReplace_0__E')  # <E>
    _commonReplace_1__E = typing.TypeVar('_commonReplace_1__E')  # <E>
    @typing.overload
    @staticmethod
    def commonReplace(this_commonReplace: SparseArrayCompat[_commonReplace_0__E], key: int | java.jint | java.lang.Integer, value: _commonReplace_0__E, /) -> _commonReplace_0__E: ...
    @typing.overload
    @staticmethod
    def commonReplace(this_commonReplace: SparseArrayCompat[_commonReplace_1__E], key: int | java.jint | java.lang.Integer, oldValue: _commonReplace_1__E, newValue: _commonReplace_1__E, /) -> bool: ...
    _commonSetValueAt__E = typing.TypeVar('_commonSetValueAt__E')  # <E>
    @staticmethod
    def commonSetValueAt(this_commonSetValueAt: SparseArrayCompat[_commonSetValueAt__E], index: int | java.jint | java.lang.Integer, value: _commonSetValueAt__E, /) -> None: ...
    @staticmethod
    def commonSize(this_commonSize: SparseArrayCompat[java.lang.Object], /) -> int: ...
    @staticmethod
    def commonToString(this_commonToString: SparseArrayCompat[java.lang.Object], /) -> str: ...
    _commonValueAt__E = typing.TypeVar('_commonValueAt__E')  # <E>
    @staticmethod
    def commonValueAt(this_commonValueAt: SparseArrayCompat[_commonValueAt__E], index: int | java.jint | java.lang.Integer, /) -> _commonValueAt__E: ...

class SparseArrayKt(java.lang.Object):
    @staticmethod
    def contains(this_contains: SparseArrayCompat[java.lang.Object], key: int | java.jint | java.lang.Integer, /) -> bool: ...
    _forEach__T = typing.TypeVar('_forEach__T')  # <T>
    @staticmethod
    def forEach(this_forEach: SparseArrayCompat[_forEach__T], action: kotlin.jvm.functions.Function2[int, _forEach__T, kotlin.Unit], /) -> None: ...
    _getOrDefault__T = typing.TypeVar('_getOrDefault__T')  # <T>
    @staticmethod
    def getOrDefault(this_getOrDefault: SparseArrayCompat[_getOrDefault__T], key: int | java.jint | java.lang.Integer, defaultValue: _getOrDefault__T, /) -> _getOrDefault__T: ...
    _getOrElse__T = typing.TypeVar('_getOrElse__T')  # <T>
    @staticmethod
    def getOrElse(this_getOrElse: SparseArrayCompat[_getOrElse__T], key: int | java.jint | java.lang.Integer, defaultValue: kotlin.jvm.functions.Function0[_getOrElse__T], /) -> _getOrElse__T: ...
    @staticmethod
    def getSize(this_size: SparseArrayCompat[java.lang.Object], /) -> int: ...
    @staticmethod
    def isNotEmpty(this_isNotEmpty: SparseArrayCompat[java.lang.Object], /) -> bool: ...
    @staticmethod
    def keyIterator(this_keyIterator: SparseArrayCompat[java.lang.Object], /) -> kotlin.collections.IntIterator: ...
    _plus__T = typing.TypeVar('_plus__T')  # <T>
    @staticmethod
    def plus(this_plus: SparseArrayCompat[_plus__T], other: SparseArrayCompat[_plus__T], /) -> SparseArrayCompat[_plus__T]: ...
    _set__T = typing.TypeVar('_set__T')  # <T>
    @staticmethod
    def set(this_set: SparseArrayCompat[_set__T], key: int | java.jint | java.lang.Integer, value: _set__T, /) -> None: ...
    _valueIterator__T = typing.TypeVar('_valueIterator__T')  # <T>
    @staticmethod
    def valueIterator(this_valueIterator: SparseArrayCompat[_valueIterator__T], /) -> java.util.Iterator[_valueIterator__T]: ...
