import typing

import android.graphics
import android.view
import java
import java.lang
import java.util
import kotlin
import kotlin.jvm.functions
import kotlin.ranges
import kotlin.sequences

class Api16Impl(java.lang.Object):
    INSTANCE: typing.ClassVar[Api16Impl] = ...
    @staticmethod
    def postOnAnimationDelayed(view: android.view.View, action: java.lang.Runnable, delayInMillis: int | java.jlong | java.lang.Long, /) -> None: ...

class MenuKt(java.lang.Object):
    @staticmethod
    def contains(this_contains: android.view.Menu, item: android.view.MenuItem, /) -> bool: ...
    @staticmethod
    def forEach(this_forEach: android.view.Menu, action: kotlin.jvm.functions.Function1[android.view.MenuItem, kotlin.Unit], /) -> None: ...
    @staticmethod
    def forEachIndexed(this_forEachIndexed: android.view.Menu, action: kotlin.jvm.functions.Function2[int, android.view.MenuItem, kotlin.Unit], /) -> None: ...
    @staticmethod
    def get(this_get: android.view.Menu, index: int | java.jint | java.lang.Integer, /) -> android.view.MenuItem: ...
    @staticmethod
    def getChildren(this_children: android.view.Menu, /) -> kotlin.sequences.Sequence[android.view.MenuItem]: ...
    @staticmethod
    def getSize(this_size: android.view.Menu, /) -> int: ...
    @staticmethod
    def isEmpty(this_isEmpty: android.view.Menu, /) -> bool: ...
    @staticmethod
    def isNotEmpty(this_isNotEmpty: android.view.Menu, /) -> bool: ...
    @staticmethod
    def iterator(this_iterator: android.view.Menu, /) -> java.util.Iterator[android.view.MenuItem]: ...
    @staticmethod
    def minusAssign(this_minusAssign: android.view.Menu, item: android.view.MenuItem, /) -> None: ...
    @staticmethod
    def removeItemAt(this_removeItemAt: android.view.Menu, index: int | java.jint | java.lang.Integer, /) -> None: ...

class ViewGroupKt(java.lang.Object):
    @staticmethod
    def contains(this_contains: android.view.ViewGroup, view: android.view.View, /) -> bool: ...
    @staticmethod
    def forEach(this_forEach: android.view.ViewGroup, action: kotlin.jvm.functions.Function1[android.view.View, kotlin.Unit], /) -> None: ...
    @staticmethod
    def forEachIndexed(this_forEachIndexed: android.view.ViewGroup, action: kotlin.jvm.functions.Function2[int, android.view.View, kotlin.Unit], /) -> None: ...
    @staticmethod
    def get(this_get: android.view.ViewGroup, index: int | java.jint | java.lang.Integer, /) -> android.view.View: ...
    @staticmethod
    def getChildren(this_children: android.view.ViewGroup, /) -> kotlin.sequences.Sequence[android.view.View]: ...
    @staticmethod
    def getDescendants(this_descendants: android.view.ViewGroup, /) -> kotlin.sequences.Sequence[android.view.View]: ...
    @staticmethod
    def getIndices(this_indices: android.view.ViewGroup, /) -> kotlin.ranges.IntRange: ...
    @staticmethod
    def getSize(this_size: android.view.ViewGroup, /) -> int: ...
    @staticmethod
    def isEmpty(this_isEmpty: android.view.ViewGroup, /) -> bool: ...
    @staticmethod
    def isNotEmpty(this_isNotEmpty: android.view.ViewGroup, /) -> bool: ...
    @staticmethod
    def iterator(this_iterator: android.view.ViewGroup, /) -> java.util.Iterator[android.view.View]: ...
    @staticmethod
    def minusAssign(this_minusAssign: android.view.ViewGroup, view: android.view.View, /) -> None: ...
    @staticmethod
    def plusAssign(this_plusAssign: android.view.ViewGroup, view: android.view.View, /) -> None: ...
    @staticmethod
    def setMargins(this_setMargins: android.view.ViewGroup.MarginLayoutParams, size: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def updateMargins(this_updateMargins: android.view.ViewGroup.MarginLayoutParams, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def updateMarginsRelative(this_updateMarginsRelative: android.view.ViewGroup.MarginLayoutParams, start: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, end: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...

class ViewKt(java.lang.Object):
    @staticmethod
    def doOnAttach(this_doOnAttach: android.view.View, action: kotlin.jvm.functions.Function1[android.view.View, kotlin.Unit], /) -> None: ...
    @staticmethod
    def doOnDetach(this_doOnDetach: android.view.View, action: kotlin.jvm.functions.Function1[android.view.View, kotlin.Unit], /) -> None: ...
    @staticmethod
    def doOnLayout(this_doOnLayout: android.view.View, action: kotlin.jvm.functions.Function1[android.view.View, kotlin.Unit], /) -> None: ...
    @staticmethod
    def doOnNextLayout(this_doOnNextLayout: android.view.View, action: kotlin.jvm.functions.Function1[android.view.View, kotlin.Unit], /) -> None: ...
    @staticmethod
    def doOnPreDraw(this_doOnPreDraw: android.view.View, action: kotlin.jvm.functions.Function1[android.view.View, kotlin.Unit], /) -> OneShotPreDrawListener: ...
    @staticmethod
    def drawToBitmap(this_drawToBitmap: android.view.View, config: android.graphics.Bitmap.Config, /) -> android.graphics.Bitmap: ...
    @staticmethod
    def getAllViews(this_allViews: android.view.View, /) -> kotlin.sequences.Sequence[android.view.View]: ...
    @staticmethod
    def getAncestors(this_ancestors: android.view.View, /) -> kotlin.sequences.Sequence[android.view.ViewParent]: ...
    @staticmethod
    def getMarginBottom(this_marginBottom: android.view.View, /) -> int: ...
    @staticmethod
    def getMarginEnd(this_marginEnd: android.view.View, /) -> int: ...
    @staticmethod
    def getMarginLeft(this_marginLeft: android.view.View, /) -> int: ...
    @staticmethod
    def getMarginRight(this_marginRight: android.view.View, /) -> int: ...
    @staticmethod
    def getMarginStart(this_marginStart: android.view.View, /) -> int: ...
    @staticmethod
    def getMarginTop(this_marginTop: android.view.View, /) -> int: ...
    @staticmethod
    def isGone(this_isGone: android.view.View, /) -> bool: ...
    @staticmethod
    def isInvisible(this_isInvisible: android.view.View, /) -> bool: ...
    @staticmethod
    def isVisible(this_isVisible: android.view.View, /) -> bool: ...
    @staticmethod
    def postDelayed(this_postDelayed: android.view.View, delayInMillis: int | java.jlong | java.lang.Long, action: kotlin.jvm.functions.Function0[kotlin.Unit], /) -> java.lang.Runnable: ...
    @staticmethod
    def postOnAnimationDelayed(this_postOnAnimationDelayed: android.view.View, delayInMillis: int | java.jlong | java.lang.Long, action: kotlin.jvm.functions.Function0[kotlin.Unit], /) -> java.lang.Runnable: ...
    @staticmethod
    def setGone(this_isGone: android.view.View, value: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def setInvisible(this_isInvisible: android.view.View, value: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def setPadding(this_setPadding: android.view.View, size: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setVisible(this_isVisible: android.view.View, value: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def updateLayoutParams(this_updateLayoutParams: android.view.View, block: kotlin.jvm.functions.Function1[android.view.ViewGroup.LayoutParams, kotlin.Unit], /) -> None: ...
    @staticmethod
    def updatePadding(this_updatePadding: android.view.View, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def updatePaddingRelative(this_updatePaddingRelative: android.view.View, start: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, end: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
