import typing

import java.util
import kotlin.jvm.internal

_AbstractIterator__T = typing.TypeVar('_AbstractIterator__T')  # <T>
class AbstractIterator(kotlin.jvm.internal.KObject, java.util.Iterator[_AbstractIterator__T], typing.Generic[_AbstractIterator__T]):
    def __init__(self) -> None: ...
    def computeNext(self) -> None: ...
    def done(self) -> None: ...
    def hasNext(self) -> bool: ...
    def next(self) -> _AbstractIterator__T: ...
    def peek(self) -> _AbstractIterator__T: ...
    def remove(self) -> None: ...
    def setNext(self, value: _AbstractIterator__T, /) -> None: ...

class State(kotlin.jvm.internal.KObject):
    instance$: typing.ClassVar[State] = ...
    def getDone(self) -> int: ...
    def getFailed(self) -> int: ...
    def getNotReady(self) -> int: ...
    def getReady(self) -> int: ...
