import typing

import androidx.constraintlayout.core.state
import androidx.constraintlayout.core.widgets
import java
import java.lang
import java.util

class AlignHorizontallyReference(androidx.constraintlayout.core.state.HelperReference):
    def __init__(self, state: androidx.constraintlayout.core.state.State, /) -> None: ...
    def apply(self) -> None: ...

class AlignVerticallyReference(androidx.constraintlayout.core.state.HelperReference):
    def __init__(self, state: androidx.constraintlayout.core.state.State, /) -> None: ...
    def apply(self) -> None: ...

class BarrierReference(androidx.constraintlayout.core.state.HelperReference):
    def __init__(self, state: androidx.constraintlayout.core.state.State, /) -> None: ...
    def apply(self) -> None: ...
    def getHelperWidget(self) -> androidx.constraintlayout.core.widgets.HelperWidget: ...
    @typing.overload
    def margin(self, value: int | java.jint | java.lang.Integer, /) -> androidx.constraintlayout.core.state.ConstraintReference: ...
    @typing.overload
    def margin(self, marginValue: java.lang.Object | int | bool | float | str, /) -> androidx.constraintlayout.core.state.ConstraintReference: ...
    def setBarrierDirection(self, barrierDirection: androidx.constraintlayout.core.state.State.Direction, /) -> None: ...

class ChainReference(androidx.constraintlayout.core.state.HelperReference):
    mBias: float = ...
    mMapWeights: java.util.HashMap[java.lang.String, java.lang.Float] = ...
    mMapPreMargin: java.util.HashMap[java.lang.String, java.lang.Float] = ...
    mMapPostMargin: java.util.HashMap[java.lang.String, java.lang.Float] = ...
    mStyle: androidx.constraintlayout.core.state.State.Chain = ...
    def __init__(self, state: androidx.constraintlayout.core.state.State, type: androidx.constraintlayout.core.state.State.Helper, /) -> None: ...
    @typing.overload
    def addChainElement(self, id: str | java.lang.String, weight: float | java.jfloat | java.lang.Float, preMargin: float | java.jfloat | java.lang.Float, postMargin: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def addChainElement(self, id: java.lang.Object | int | bool | float | str, weight: float | java.jfloat | java.lang.Float, preMargin: float | java.jfloat | java.lang.Float, postMargin: float | java.jfloat | java.lang.Float, preGoneMargin: float | java.jfloat | java.lang.Float, postGoneMargin: float | java.jfloat | java.lang.Float, /) -> None: ...
    def bias(self, bias: float | java.jfloat | java.lang.Float, /) -> ChainReference: ...
    def getBias(self) -> float: ...
    def getPostMargin(self, id: str | java.lang.String, /) -> float: ...
    def getPreMargin(self, id: str | java.lang.String, /) -> float: ...
    def getStyle(self) -> androidx.constraintlayout.core.state.State.Chain: ...
    def getWeight(self, id: str | java.lang.String, /) -> float: ...
    def style(self, style: androidx.constraintlayout.core.state.State.Chain, /) -> ChainReference: ...

class Facade(java.lang.Object):
    def apply(self) -> None: ...
    def getConstraintWidget(self) -> androidx.constraintlayout.core.widgets.ConstraintWidget: ...

class FlowReference(androidx.constraintlayout.core.state.HelperReference):
    mFlow: androidx.constraintlayout.core.widgets.Flow = ...
    mMapWeights: java.util.HashMap[java.lang.String, java.lang.Float] = ...
    mMapPreMargin: java.util.HashMap[java.lang.String, java.lang.Float] = ...
    mMapPostMargin: java.util.HashMap[java.lang.String, java.lang.Float] = ...
    mWrapMode: int = ...
    mVerticalStyle: int = ...
    mFirstVerticalStyle: int = ...
    mLastVerticalStyle: int = ...
    mHorizontalStyle: int = ...
    mFirstHorizontalStyle: int = ...
    mLastHorizontalStyle: int = ...
    mVerticalAlign: int = ...
    mHorizontalAlign: int = ...
    mVerticalGap: int = ...
    mHorizontalGap: int = ...
    mPaddingLeft: int = ...
    mPaddingRight: int = ...
    mPaddingTop: int = ...
    mPaddingBottom: int = ...
    mMaxElementsWrap: int = ...
    mOrientation: int = ...
    mFirstVerticalBias: float = ...
    mLastVerticalBias: float = ...
    mFirstHorizontalBias: float = ...
    mLastHorizontalBias: float = ...
    def __init__(self, state: androidx.constraintlayout.core.state.State, type: androidx.constraintlayout.core.state.State.Helper, /) -> None: ...
    def addFlowElement(self, id: str | java.lang.String, weight: float | java.jfloat | java.lang.Float, preMargin: float | java.jfloat | java.lang.Float, postMargin: float | java.jfloat | java.lang.Float, /) -> None: ...
    def apply(self) -> None: ...
    def getFirstHorizontalBias(self) -> float: ...
    def getFirstHorizontalStyle(self) -> int: ...
    def getFirstVerticalBias(self) -> float: ...
    def getFirstVerticalStyle(self) -> int: ...
    def getHelperWidget(self) -> androidx.constraintlayout.core.widgets.HelperWidget: ...
    def getHorizontalAlign(self) -> int: ...
    def getHorizontalBias(self) -> float: ...
    def getHorizontalGap(self) -> int: ...
    def getHorizontalStyle(self) -> int: ...
    def getLastHorizontalBias(self) -> float: ...
    def getLastHorizontalStyle(self) -> int: ...
    def getLastVerticalBias(self) -> float: ...
    def getLastVerticalStyle(self) -> int: ...
    def getMaxElementsWrap(self) -> int: ...
    def getOrientation(self) -> int: ...
    def getPaddingBottom(self) -> int: ...
    def getPaddingLeft(self) -> int: ...
    def getPaddingRight(self) -> int: ...
    def getPaddingTop(self) -> int: ...
    def getPostMargin(self, id: str | java.lang.String, /) -> float: ...
    def getPreMargin(self, id: str | java.lang.String, /) -> float: ...
    def getVerticalAlign(self) -> int: ...
    def getVerticalBias(self) -> float: ...
    def getVerticalGap(self) -> int: ...
    def getVerticalStyle(self) -> int: ...
    def getWeight(self, id: str | java.lang.String, /) -> float: ...
    def getWrapMode(self) -> int: ...
    def setFirstHorizontalBias(self, firstHorizontalBias: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setFirstHorizontalStyle(self, firstHorizontalStyle: int | java.jint | java.lang.Integer, /) -> None: ...
    def setFirstVerticalBias(self, firstVerticalBias: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setFirstVerticalStyle(self, firstVerticalStyle: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHelperWidget(self, widget: androidx.constraintlayout.core.widgets.HelperWidget, /) -> None: ...
    def setHorizontalAlign(self, horizontalAlign: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHorizontalGap(self, horizontalGap: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHorizontalStyle(self, horizontalStyle: int | java.jint | java.lang.Integer, /) -> None: ...
    def setLastHorizontalBias(self, lastHorizontalBias: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setLastHorizontalStyle(self, lastHorizontalStyle: int | java.jint | java.lang.Integer, /) -> None: ...
    def setLastVerticalBias(self, lastVerticalBias: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setLastVerticalStyle(self, lastVerticalStyle: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMaxElementsWrap(self, maxElementsWrap: int | java.jint | java.lang.Integer, /) -> None: ...
    def setOrientation(self, mOrientation: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPaddingBottom(self, padding: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPaddingLeft(self, padding: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPaddingRight(self, padding: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPaddingTop(self, padding: int | java.jint | java.lang.Integer, /) -> None: ...
    def setVerticalAlign(self, verticalAlign: int | java.jint | java.lang.Integer, /) -> None: ...
    def setVerticalGap(self, verticalGap: int | java.jint | java.lang.Integer, /) -> None: ...
    def setVerticalStyle(self, verticalStyle: int | java.jint | java.lang.Integer, /) -> None: ...
    def setWrapMode(self, wrap: int | java.jint | java.lang.Integer, /) -> None: ...

class GridReference(androidx.constraintlayout.core.state.HelperReference):
    def __init__(self, state: androidx.constraintlayout.core.state.State, type: androidx.constraintlayout.core.state.State.Helper, /) -> None: ...
    def apply(self) -> None: ...
    def getColumnWeights(self) -> str: ...
    def getColumnsSet(self) -> int: ...
    def getFlags(self) -> int: ...
    def getHelperWidget(self) -> androidx.constraintlayout.core.widgets.HelperWidget: ...
    def getHorizontalGaps(self) -> float: ...
    def getOrientation(self) -> int: ...
    def getPaddingBottom(self) -> int: ...
    def getPaddingEnd(self) -> int: ...
    def getPaddingStart(self) -> int: ...
    def getPaddingTop(self) -> int: ...
    def getRowWeights(self) -> str: ...
    def getRowsSet(self) -> int: ...
    def getSkips(self) -> str: ...
    def getSpans(self) -> str: ...
    def getVerticalGaps(self) -> float: ...
    def setColumnWeights(self, columnWeights: str | java.lang.String, /) -> None: ...
    def setColumnsSet(self, columnsSet: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setFlags(self, flags: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setFlags(self, flags: str | java.lang.String, /) -> None: ...
    def setHelperWidget(self, widget: androidx.constraintlayout.core.widgets.HelperWidget, /) -> None: ...
    def setHorizontalGaps(self, horizontalGaps: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setOrientation(self, orientation: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPaddingBottom(self, paddingBottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPaddingEnd(self, paddingEnd: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPaddingStart(self, paddingStart: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPaddingTop(self, paddingTop: int | java.jint | java.lang.Integer, /) -> None: ...
    def setRowWeights(self, rowWeights: str | java.lang.String, /) -> None: ...
    def setRowsSet(self, rowsSet: int | java.jint | java.lang.Integer, /) -> None: ...
    def setSkips(self, skips: str | java.lang.String, /) -> None: ...
    def setSpans(self, spans: str | java.lang.String, /) -> None: ...
    def setVerticalGaps(self, verticalGaps: float | java.jfloat | java.lang.Float, /) -> None: ...

class GuidelineReference(Facade, androidx.constraintlayout.core.state.Reference):
    def __init__(self, state: androidx.constraintlayout.core.state.State, /) -> None: ...
    def apply(self) -> None: ...
    def end(self, margin: java.lang.Object | int | bool | float | str, /) -> GuidelineReference: ...
    def getConstraintWidget(self) -> androidx.constraintlayout.core.widgets.ConstraintWidget: ...
    def getFacade(self) -> Facade: ...
    def getKey(self) -> java.lang.Object: ...
    def getOrientation(self) -> int: ...
    def percent(self, percent: float | java.jfloat | java.lang.Float, /) -> GuidelineReference: ...
    def setConstraintWidget(self, widget: androidx.constraintlayout.core.widgets.ConstraintWidget, /) -> None: ...
    def setKey(self, key: java.lang.Object | int | bool | float | str, /) -> None: ...
    def setOrientation(self, orientation: int | java.jint | java.lang.Integer, /) -> None: ...
    def start(self, margin: java.lang.Object | int | bool | float | str, /) -> GuidelineReference: ...

class HorizontalChainReference(ChainReference):
    def __init__(self, state: androidx.constraintlayout.core.state.State, /) -> None: ...
    def apply(self) -> None: ...

class VerticalChainReference(ChainReference):
    def __init__(self, state: androidx.constraintlayout.core.state.State, /) -> None: ...
    def apply(self) -> None: ...
