import typing

import android.graphics
import androidx.collection
import java
import java.chaquopy
import java.lang
import java.util
import kotlin
import kotlin.collections
import kotlin.jvm.functions

class AngleMeasurer(Measurer):
    def __init__(self, centerX: float | java.jfloat | java.lang.Float, centerY: float | java.jfloat | java.lang.Float, /) -> None: ...
    def findCubicCutPoint(self, c: Cubic, m: float | java.jfloat | java.lang.Float, /) -> float: ...
    def getCenterX(self) -> float: ...
    def getCenterY(self) -> float: ...
    def measureCubic(self, c: Cubic, /) -> float: ...

class CornerRounding(java.lang.Object):
    Companion: typing.ClassVar[CornerRounding.Companion] = ...
    Unrounded: typing.ClassVar[CornerRounding] = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, radius: float | java.jfloat | java.lang.Float, smoothing: float | java.jfloat | java.lang.Float, /) -> None: ...
    def getRadius(self) -> float: ...
    def getSmoothing(self) -> float: ...

    class Companion(java.lang.Object): ...

class Cubic(java.lang.Object):
    Companion: typing.ClassVar[Cubic.Companion] = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, points: java.chaquopy.JavaArrayJFloat, /) -> None: ...
    @staticmethod
    def circularArc(centerX: float | java.jfloat | java.lang.Float, centerY: float | java.jfloat | java.lang.Float, x0: float | java.jfloat | java.lang.Float, y0: float | java.jfloat | java.lang.Float, x1: float | java.jfloat | java.lang.Float, y1: float | java.jfloat | java.lang.Float, /) -> Cubic: ...
    @typing.overload
    def div(self, x: float | java.jfloat | java.lang.Float, /) -> Cubic: ...
    @typing.overload
    def div(self, x: int | java.jint | java.lang.Integer, /) -> Cubic: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getAnchor0X(self) -> float: ...
    def getAnchor0Y(self) -> float: ...
    def getAnchor1X(self) -> float: ...
    def getAnchor1Y(self) -> float: ...
    def getControl0X(self) -> float: ...
    def getControl0Y(self) -> float: ...
    def getControl1X(self) -> float: ...
    def getControl1Y(self) -> float: ...
    def hashCode(self) -> int: ...
    def plus(self, o: Cubic, /) -> Cubic: ...
    def reverse(self) -> Cubic: ...
    def split(self, t: float | java.jfloat | java.lang.Float, /) -> kotlin.Pair[Cubic, Cubic]: ...
    @staticmethod
    def straightLine(x0: float | java.jfloat | java.lang.Float, y0: float | java.jfloat | java.lang.Float, x1: float | java.jfloat | java.lang.Float, y1: float | java.jfloat | java.lang.Float, /) -> Cubic: ...
    @typing.overload
    def times(self, x: float | java.jfloat | java.lang.Float, /) -> Cubic: ...
    @typing.overload
    def times(self, x: int | java.jint | java.lang.Integer, /) -> Cubic: ...
    def toString(self) -> str: ...
    def transformed(self, f: PointTransformer, /) -> Cubic: ...

    class Companion(java.lang.Object):
        def circularArc(self, centerX: float | java.jfloat | java.lang.Float, centerY: float | java.jfloat | java.lang.Float, x0: float | java.jfloat | java.lang.Float, y0: float | java.jfloat | java.lang.Float, x1: float | java.jfloat | java.lang.Float, y1: float | java.jfloat | java.lang.Float, /) -> Cubic: ...
        def straightLine(self, x0: float | java.jfloat | java.lang.Float, y0: float | java.jfloat | java.lang.Float, x1: float | java.jfloat | java.lang.Float, y1: float | java.jfloat | java.lang.Float, /) -> Cubic: ...

class CubicKt(java.lang.Object):
    @staticmethod
    def Cubic(anchor0X: float | java.jfloat | java.lang.Float, anchor0Y: float | java.jfloat | java.lang.Float, control0X: float | java.jfloat | java.lang.Float, control0Y: float | java.jfloat | java.lang.Float, control1X: float | java.jfloat | java.lang.Float, control1Y: float | java.jfloat | java.lang.Float, anchor1X: float | java.jfloat | java.lang.Float, anchor1Y: float | java.jfloat | java.lang.Float, /) -> Cubic: ...

class DoubleMapper(java.lang.Object):
    Companion: typing.ClassVar[DoubleMapper.Companion] = ...
    Identity: typing.ClassVar[DoubleMapper] = ...
    def __init__(self, *mappings: kotlin.Pair[java.lang.Float, java.lang.Float]) -> None: ...
    def map(self, x: float | java.jfloat | java.lang.Float, /) -> float: ...
    def mapBack(self, x: float | java.jfloat | java.lang.Float, /) -> float: ...

    class Companion(java.lang.Object): ...

class Feature(java.lang.Object):
    def __init__(self, cubics: java.util.List[Cubic], /) -> None: ...
    def getCubics(self) -> java.util.List[Cubic]: ...

    class Corner(Feature):
        def getConvex(self) -> bool: ...
        def toString(self) -> str: ...

    class Edge(Feature):
        def __init__(self, cubics: java.util.List[Cubic], /) -> None: ...
        def toString(self) -> str: ...

class FeatureMappingKt(java.lang.Object):
    @staticmethod
    def doMapping(f1: java.util.List[ProgressableFeature], f2: java.util.List[ProgressableFeature], /) -> java.util.List[ProgressableFeature]: ...
    @staticmethod
    def featureDistSquared(f1: Feature, f2: Feature, /) -> float: ...
    @staticmethod
    def featureMapper(features1: java.util.List[ProgressableFeature], features2: java.util.List[ProgressableFeature], /) -> DoubleMapper: ...

class FindMinimumFunction(java.lang.Object):
    def invoke(self, arg1: float | java.jfloat | java.lang.Float, /) -> float: ...

class FloatMappingKt(java.lang.Object):
    @staticmethod
    def linearMap(xValues: androidx.collection.FloatList, yValues: androidx.collection.FloatList, x: float | java.jfloat | java.lang.Float, /) -> float: ...
    @staticmethod
    def progressInRange(progress: float | java.jfloat | java.lang.Float, progressFrom: float | java.jfloat | java.lang.Float, progressTo: float | java.jfloat | java.lang.Float, /) -> bool: ...
    @staticmethod
    def validateProgress(p: androidx.collection.FloatList, /) -> None: ...

class Format_jvmKt(java.lang.Object):
    @staticmethod
    def toStringWithLessPrecision(this_toStringWithLessPrecision: float | java.jfloat | java.lang.Float, /) -> str: ...

class MeasuredPolygon(kotlin.collections.AbstractList[MeasuredPolygon.MeasuredCubic]):
    Companion: typing.ClassVar[MeasuredPolygon.Companion] = ...
    def cutAndShift(self, cuttingPoint: float | java.jfloat | java.lang.Float, /) -> MeasuredPolygon: ...
    def get(self, index: int | java.jint | java.lang.Integer, /) -> MeasuredPolygon.MeasuredCubic: ...
    def getFeatures(self) -> java.util.List[ProgressableFeature]: ...
    def getSize(self) -> int: ...

    class Companion(java.lang.Object): ...

    class MeasuredCubic(java.lang.Object):
        def __init__(self, this_0: Cubic, cubic: float | java.jfloat | java.lang.Float, startOutlineProgress: float | java.jfloat | java.lang.Float, /) -> None: ...
        def cutAtProgress(self, cutOutlineProgress: float | java.jfloat | java.lang.Float, /) -> kotlin.Pair[MeasuredPolygon.MeasuredCubic, MeasuredPolygon.MeasuredCubic]: ...
        def getCubic(self) -> Cubic: ...
        def getEndOutlineProgress(self) -> float: ...
        def getMeasuredSize(self) -> float: ...
        def getStartOutlineProgress(self) -> float: ...
        def toString(self) -> str: ...

class Measurer(java.lang.Object):
    def findCubicCutPoint(self, arg1: Cubic, arg2: float | java.jfloat | java.lang.Float, /) -> float: ...
    def measureCubic(self, arg1: Cubic, /) -> float: ...

class Morph(java.lang.Object):
    Companion: typing.ClassVar[Morph.Companion] = ...
    def __init__(self, start: RoundedPolygon, end: RoundedPolygon, /) -> None: ...
    def asCubics(self, progress: float | java.jfloat | java.lang.Float, /) -> java.util.List[Cubic]: ...
    @typing.overload
    def calculateBounds(self) -> java.chaquopy.JavaArrayJFloat: ...
    @typing.overload
    def calculateBounds(self, bounds: java.chaquopy.JavaArrayJFloat, /) -> java.chaquopy.JavaArrayJFloat: ...
    @typing.overload
    def calculateBounds(self, bounds: java.chaquopy.JavaArrayJFloat, approximate: bool | java.jboolean | java.lang.Boolean, /) -> java.chaquopy.JavaArrayJFloat: ...
    def calculateMaxBounds(self, bounds: java.chaquopy.JavaArrayJFloat, /) -> java.chaquopy.JavaArrayJFloat: ...
    @typing.overload
    def forEachCubic(self, progress: float | java.jfloat | java.lang.Float, callback: kotlin.jvm.functions.Function1[MutableCubic, kotlin.Unit], /) -> None: ...
    @typing.overload
    def forEachCubic(self, progress: float | java.jfloat | java.lang.Float, mutableCubic: MutableCubic, callback: kotlin.jvm.functions.Function1[MutableCubic, kotlin.Unit], /) -> None: ...
    def getMorphMatch(self) -> java.util.List[kotlin.Pair[Cubic, Cubic]]: ...

    class Companion(java.lang.Object): ...

class MorphKt(java.lang.Object): ...

class MutableCubic(Cubic):
    def __init__(self) -> None: ...
    def interpolate(self, c1: Cubic, c2: Cubic, progress: float | java.jfloat | java.lang.Float, /) -> None: ...
    def transform(self, f: PointTransformer, /) -> None: ...

class MutablePoint(java.lang.Object):
    def getX(self) -> float: ...
    def getY(self) -> float: ...
    def setX(self, arg1: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setY(self, arg1: float | java.jfloat | java.lang.Float, /) -> None: ...

class PointKt(java.lang.Object): ...

class PointTransformer(java.lang.Object): ...

class PolygonMeasureKt(java.lang.Object): ...

class ProgressableFeature(java.lang.Object):
    def __init__(self, progress: float | java.jfloat | java.lang.Float, feature: Feature, /) -> None: ...
    def component1(self) -> float: ...
    def component2(self) -> Feature: ...
    def copy(self, progress: float | java.jfloat | java.lang.Float, feature: Feature, /) -> ProgressableFeature: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getFeature(self) -> Feature: ...
    def getProgress(self) -> float: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class RoundedCorner(java.lang.Object):
    def getCornerRadius(self) -> float: ...
    def getCosAngle(self) -> float: ...
    @typing.overload
    def getCubics(self, allowedCut0: float | java.jfloat | java.lang.Float, /) -> java.util.List[Cubic]: ...
    @typing.overload
    def getCubics(self, allowedCut0: float | java.jfloat | java.lang.Float, allowedCut1: float | java.jfloat | java.lang.Float, /) -> java.util.List[Cubic]: ...
    def getExpectedCut(self) -> float: ...
    def getExpectedRoundCut(self) -> float: ...
    def getRounding(self) -> CornerRounding: ...
    def getSinAngle(self) -> float: ...
    def getSmoothing(self) -> float: ...

class RoundedPolygon(java.lang.Object):
    Companion: typing.ClassVar[RoundedPolygon.Companion] = ...
    def __init__(self, features: java.util.List[Feature], centerX: float | java.jfloat | java.lang.Float, centerY: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def calculateBounds(self) -> java.chaquopy.JavaArrayJFloat: ...
    @typing.overload
    def calculateBounds(self, bounds: java.chaquopy.JavaArrayJFloat, /) -> java.chaquopy.JavaArrayJFloat: ...
    @typing.overload
    def calculateBounds(self, bounds: java.chaquopy.JavaArrayJFloat, approximate: bool | java.jboolean | java.lang.Boolean, /) -> java.chaquopy.JavaArrayJFloat: ...
    def calculateMaxBounds(self, bounds: java.chaquopy.JavaArrayJFloat, /) -> java.chaquopy.JavaArrayJFloat: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getCenterX(self) -> float: ...
    def getCenterY(self) -> float: ...
    def getCubics(self) -> java.util.List[Cubic]: ...
    def hashCode(self) -> int: ...
    def normalized(self) -> RoundedPolygon: ...
    def toString(self) -> str: ...
    def transformed(self, f: PointTransformer, /) -> RoundedPolygon: ...

    class Companion(java.lang.Object): ...

class RoundedPolygonKt(java.lang.Object):
    @typing.overload
    @staticmethod
    def RoundedPolygon(numVertices: int | java.jint | java.lang.Integer, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def RoundedPolygon(source: RoundedPolygon, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def RoundedPolygon(vertices: java.chaquopy.JavaArrayJFloat, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def RoundedPolygon(numVertices: int | java.jint | java.lang.Integer, radius: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def RoundedPolygon(vertices: java.chaquopy.JavaArrayJFloat, rounding: CornerRounding, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def RoundedPolygon(numVertices: int | java.jint | java.lang.Integer, radius: float | java.jfloat | java.lang.Float, centerX: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def RoundedPolygon(vertices: java.chaquopy.JavaArrayJFloat, rounding: CornerRounding, perVertexRounding: java.util.List[CornerRounding], /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def RoundedPolygon(numVertices: int | java.jint | java.lang.Integer, radius: float | java.jfloat | java.lang.Float, centerX: float | java.jfloat | java.lang.Float, centerY: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def RoundedPolygon(vertices: java.chaquopy.JavaArrayJFloat, rounding: CornerRounding, perVertexRounding: java.util.List[CornerRounding], centerX: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def RoundedPolygon(numVertices: int | java.jint | java.lang.Integer, radius: float | java.jfloat | java.lang.Float, centerX: float | java.jfloat | java.lang.Float, centerY: float | java.jfloat | java.lang.Float, rounding: CornerRounding, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def RoundedPolygon(vertices: java.chaquopy.JavaArrayJFloat, rounding: CornerRounding, perVertexRounding: java.util.List[CornerRounding], centerX: float | java.jfloat | java.lang.Float, centerY: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def RoundedPolygon(numVertices: int | java.jint | java.lang.Integer, radius: float | java.jfloat | java.lang.Float, centerX: float | java.jfloat | java.lang.Float, centerY: float | java.jfloat | java.lang.Float, rounding: CornerRounding, perVertexRounding: java.util.List[CornerRounding], /) -> RoundedPolygon: ...

class ShapesKt(java.lang.Object):
    @typing.overload
    @staticmethod
    def circle(this_circle: RoundedPolygon.Companion, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def circle(this_circle: RoundedPolygon.Companion, numVertices: int | java.jint | java.lang.Integer, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def circle(this_circle: RoundedPolygon.Companion, numVertices: int | java.jint | java.lang.Integer, radius: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def circle(this_circle: RoundedPolygon.Companion, numVertices: int | java.jint | java.lang.Integer, radius: float | java.jfloat | java.lang.Float, centerX: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def circle(this_circle: RoundedPolygon.Companion, numVertices: int | java.jint | java.lang.Integer, radius: float | java.jfloat | java.lang.Float, centerX: float | java.jfloat | java.lang.Float, centerY: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def pill(this_pill: RoundedPolygon.Companion, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def pill(this_pill: RoundedPolygon.Companion, width: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def pill(this_pill: RoundedPolygon.Companion, width: float | java.jfloat | java.lang.Float, height: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def pill(this_pill: RoundedPolygon.Companion, width: float | java.jfloat | java.lang.Float, height: float | java.jfloat | java.lang.Float, smoothing: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def pill(this_pill: RoundedPolygon.Companion, width: float | java.jfloat | java.lang.Float, height: float | java.jfloat | java.lang.Float, smoothing: float | java.jfloat | java.lang.Float, centerX: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def pill(this_pill: RoundedPolygon.Companion, width: float | java.jfloat | java.lang.Float, height: float | java.jfloat | java.lang.Float, smoothing: float | java.jfloat | java.lang.Float, centerX: float | java.jfloat | java.lang.Float, centerY: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def pillStar(this_pillStar: RoundedPolygon.Companion, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def pillStar(this_pillStar: RoundedPolygon.Companion, width: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def pillStar(this_pillStar: RoundedPolygon.Companion, width: float | java.jfloat | java.lang.Float, height: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def pillStar(this_pillStar: RoundedPolygon.Companion, width: float | java.jfloat | java.lang.Float, height: float | java.jfloat | java.lang.Float, numVerticesPerRadius: int | java.jint | java.lang.Integer, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def pillStar(this_pillStar: RoundedPolygon.Companion, width: float | java.jfloat | java.lang.Float, height: float | java.jfloat | java.lang.Float, numVerticesPerRadius: int | java.jint | java.lang.Integer, innerRadiusRatio: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def pillStar(this_pillStar: RoundedPolygon.Companion, width: float | java.jfloat | java.lang.Float, height: float | java.jfloat | java.lang.Float, numVerticesPerRadius: int | java.jint | java.lang.Integer, innerRadiusRatio: float | java.jfloat | java.lang.Float, rounding: CornerRounding, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def pillStar(this_pillStar: RoundedPolygon.Companion, width: float | java.jfloat | java.lang.Float, height: float | java.jfloat | java.lang.Float, numVerticesPerRadius: int | java.jint | java.lang.Integer, innerRadiusRatio: float | java.jfloat | java.lang.Float, rounding: CornerRounding, innerRounding: CornerRounding, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def pillStar(this_pillStar: RoundedPolygon.Companion, width: float | java.jfloat | java.lang.Float, height: float | java.jfloat | java.lang.Float, numVerticesPerRadius: int | java.jint | java.lang.Integer, innerRadiusRatio: float | java.jfloat | java.lang.Float, rounding: CornerRounding, innerRounding: CornerRounding, perVertexRounding: java.util.List[CornerRounding], /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def pillStar(this_pillStar: RoundedPolygon.Companion, width: float | java.jfloat | java.lang.Float, height: float | java.jfloat | java.lang.Float, numVerticesPerRadius: int | java.jint | java.lang.Integer, innerRadiusRatio: float | java.jfloat | java.lang.Float, rounding: CornerRounding, innerRounding: CornerRounding, perVertexRounding: java.util.List[CornerRounding], vertexSpacing: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def pillStar(this_pillStar: RoundedPolygon.Companion, width: float | java.jfloat | java.lang.Float, height: float | java.jfloat | java.lang.Float, numVerticesPerRadius: int | java.jint | java.lang.Integer, innerRadiusRatio: float | java.jfloat | java.lang.Float, rounding: CornerRounding, innerRounding: CornerRounding, perVertexRounding: java.util.List[CornerRounding], vertexSpacing: float | java.jfloat | java.lang.Float, startLocation: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def pillStar(this_pillStar: RoundedPolygon.Companion, width: float | java.jfloat | java.lang.Float, height: float | java.jfloat | java.lang.Float, numVerticesPerRadius: int | java.jint | java.lang.Integer, innerRadiusRatio: float | java.jfloat | java.lang.Float, rounding: CornerRounding, innerRounding: CornerRounding, perVertexRounding: java.util.List[CornerRounding], vertexSpacing: float | java.jfloat | java.lang.Float, startLocation: float | java.jfloat | java.lang.Float, centerX: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def pillStar(this_pillStar: RoundedPolygon.Companion, width: float | java.jfloat | java.lang.Float, height: float | java.jfloat | java.lang.Float, numVerticesPerRadius: int | java.jint | java.lang.Integer, innerRadiusRatio: float | java.jfloat | java.lang.Float, rounding: CornerRounding, innerRounding: CornerRounding, perVertexRounding: java.util.List[CornerRounding], vertexSpacing: float | java.jfloat | java.lang.Float, startLocation: float | java.jfloat | java.lang.Float, centerX: float | java.jfloat | java.lang.Float, centerY: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @staticmethod
    def rectangle(this_rectangle: RoundedPolygon.Companion, width: float | java.jfloat | java.lang.Float, height: float | java.jfloat | java.lang.Float, rounding: CornerRounding, perVertexRounding: java.util.List[CornerRounding], centerX: float | java.jfloat | java.lang.Float, centerY: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def star(this_star: RoundedPolygon.Companion, numVerticesPerRadius: int | java.jint | java.lang.Integer, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def star(this_star: RoundedPolygon.Companion, numVerticesPerRadius: int | java.jint | java.lang.Integer, radius: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def star(this_star: RoundedPolygon.Companion, numVerticesPerRadius: int | java.jint | java.lang.Integer, radius: float | java.jfloat | java.lang.Float, innerRadius: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def star(this_star: RoundedPolygon.Companion, numVerticesPerRadius: int | java.jint | java.lang.Integer, radius: float | java.jfloat | java.lang.Float, innerRadius: float | java.jfloat | java.lang.Float, rounding: CornerRounding, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def star(this_star: RoundedPolygon.Companion, numVerticesPerRadius: int | java.jint | java.lang.Integer, radius: float | java.jfloat | java.lang.Float, innerRadius: float | java.jfloat | java.lang.Float, rounding: CornerRounding, innerRounding: CornerRounding, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def star(this_star: RoundedPolygon.Companion, numVerticesPerRadius: int | java.jint | java.lang.Integer, radius: float | java.jfloat | java.lang.Float, innerRadius: float | java.jfloat | java.lang.Float, rounding: CornerRounding, innerRounding: CornerRounding, perVertexRounding: java.util.List[CornerRounding], /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def star(this_star: RoundedPolygon.Companion, numVerticesPerRadius: int | java.jint | java.lang.Integer, radius: float | java.jfloat | java.lang.Float, innerRadius: float | java.jfloat | java.lang.Float, rounding: CornerRounding, innerRounding: CornerRounding, perVertexRounding: java.util.List[CornerRounding], centerX: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...
    @typing.overload
    @staticmethod
    def star(this_star: RoundedPolygon.Companion, numVerticesPerRadius: int | java.jint | java.lang.Integer, radius: float | java.jfloat | java.lang.Float, innerRadius: float | java.jfloat | java.lang.Float, rounding: CornerRounding, innerRounding: CornerRounding, perVertexRounding: java.util.List[CornerRounding], centerX: float | java.jfloat | java.lang.Float, centerY: float | java.jfloat | java.lang.Float, /) -> RoundedPolygon: ...

class Shapes_androidKt(java.lang.Object):
    @typing.overload
    @staticmethod
    def toPath(this_toPath: RoundedPolygon, /) -> android.graphics.Path: ...
    @typing.overload
    @staticmethod
    def toPath(this_toPath: RoundedPolygon, path: android.graphics.Path, /) -> android.graphics.Path: ...
    @typing.overload
    @staticmethod
    def toPath(this_toPath: Morph, progress: float | java.jfloat | java.lang.Float, path: android.graphics.Path, /) -> android.graphics.Path: ...
    @staticmethod
    def transformed(this_transformed: RoundedPolygon, matrix: android.graphics.Matrix, /) -> RoundedPolygon: ...

class Utils(java.lang.Object):
    DistanceEpsilon: typing.ClassVar[float] = ...
    AngleEpsilon: typing.ClassVar[float] = ...
    DEBUG: typing.ClassVar[bool] = ...
    @staticmethod
    def angle(x: float | java.jfloat | java.lang.Float, y: float | java.jfloat | java.lang.Float, /) -> float: ...
    @staticmethod
    def debugLog(tag: str | java.lang.String, messageFactory: kotlin.jvm.functions.Function0[java.lang.String], /) -> None: ...
    @typing.overload
    @staticmethod
    def directionVector(angleRadians: float | java.jfloat | java.lang.Float, /) -> int: ...
    @typing.overload
    @staticmethod
    def directionVector(x: float | java.jfloat | java.lang.Float, y: float | java.jfloat | java.lang.Float, /) -> int: ...
    @staticmethod
    def distance(x: float | java.jfloat | java.lang.Float, y: float | java.jfloat | java.lang.Float, /) -> float: ...
    @staticmethod
    def distanceSquared(x: float | java.jfloat | java.lang.Float, y: float | java.jfloat | java.lang.Float, /) -> float: ...
    @staticmethod
    def findMinimum(v0: float | java.jfloat | java.lang.Float, v1: float | java.jfloat | java.lang.Float, tolerance: float | java.jfloat | java.lang.Float, f: FindMinimumFunction, /) -> float: ...
    @staticmethod
    def getFloatPi() -> float: ...
    @staticmethod
    def getTwoPi() -> float: ...
    @staticmethod
    def getZero() -> int: ...
    @staticmethod
    def interpolate(start: float | java.jfloat | java.lang.Float, stop: float | java.jfloat | java.lang.Float, fraction: float | java.jfloat | java.lang.Float, /) -> float: ...
    @staticmethod
    def positiveModulo(num: float | java.jfloat | java.lang.Float, mod: float | java.jfloat | java.lang.Float, /) -> float: ...
    @staticmethod
    def square(x: float | java.jfloat | java.lang.Float, /) -> float: ...
