import typing

import android.content
import android.content.res
import android.graphics.drawable
import android.os
import android.util
import android.view
import android.view.accessibility
import android.widget
import androidx.appcompat.view.menu
import androidx.core.view
import androidx.customview.view
import com.google.android.material.badge
import com.google.android.material.internal
import java
import java.chaquopy
import java.lang
import java.lang.annotation

class NavigationBarItemView(android.widget.FrameLayout, androidx.appcompat.view.menu.MenuView.ItemView):
    def __init__(self, context: android.content.Context, /) -> None: ...
    def getBadge(self) -> com.google.android.material.badge.BadgeDrawable: ...
    def getItemBackgroundResId(self) -> int: ...
    def getItemData(self) -> androidx.appcompat.view.menu.MenuItemImpl: ...
    def getItemDefaultMarginResId(self) -> int: ...
    def getItemLayoutResId(self) -> int: ...
    def getItemPosition(self) -> int: ...
    def getSuggestedMinimumHeight(self) -> int: ...
    def getSuggestedMinimumWidth(self) -> int: ...
    def initialize(self, itemData: androidx.appcompat.view.menu.MenuItemImpl, menuType: int | java.jint | java.lang.Integer, /) -> None: ...
    def onCreateDrawableState(self, extraSpace: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJInt: ...
    def onInitializeAccessibilityNodeInfo(self, info: android.view.accessibility.AccessibilityNodeInfo, /) -> None: ...
    def prefersCondensedTitle(self) -> bool: ...
    def setCheckable(self, checkable: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setChecked(self, checked: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setIcon(self, iconDrawable: android.graphics.drawable.Drawable, /) -> None: ...
    def setIconSize(self, iconSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def setIconTintList(self, tint: android.content.res.ColorStateList, /) -> None: ...
    @typing.overload
    def setItemBackground(self, background: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setItemBackground(self, background: android.graphics.drawable.Drawable, /) -> None: ...
    def setItemPosition(self, position: int | java.jint | java.lang.Integer, /) -> None: ...
    def setLabelVisibilityMode(self, mode: int | java.jint | java.lang.Integer, /) -> None: ...
    def setShifting(self, shifting: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setShortcut(self, showShortcut: bool | java.jboolean | java.lang.Boolean, shortcutKey: str | java.jchar | java.lang.Character, /) -> None: ...
    def setTextAppearanceActive(self, activeTextAppearance: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTextAppearanceInactive(self, inactiveTextAppearance: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTextColor(self, color: android.content.res.ColorStateList, /) -> None: ...
    def setTitle(self, title: java.lang.CharSequence, /) -> None: ...
    def showsIcon(self) -> bool: ...

class NavigationBarMenu(androidx.appcompat.view.menu.MenuBuilder):
    def __init__(self, context: android.content.Context, viewClass: typing.Type[java.lang.Object], maxItemCount: int | java.jint | java.lang.Integer, /) -> None: ...
    def addInternal(self, group: int | java.jint | java.lang.Integer, id: int | java.jint | java.lang.Integer, categoryOrder: int | java.jint | java.lang.Integer, title: java.lang.CharSequence, /) -> android.view.MenuItem: ...
    def addSubMenu(self, group: int | java.jint | java.lang.Integer, id: int | java.jint | java.lang.Integer, categoryOrder: int | java.jint | java.lang.Integer, title: java.lang.CharSequence, /) -> android.view.SubMenu: ...
    def getMaxItemCount(self) -> int: ...

class NavigationBarMenuView(android.view.ViewGroup, androidx.appcompat.view.menu.MenuView):
    def __init__(self, context: android.content.Context, /) -> None: ...
    def buildMenuView(self) -> None: ...
    def createDefaultColorStateList(self, baseColorThemeAttr: int | java.jint | java.lang.Integer, /) -> android.content.res.ColorStateList: ...
    def createNavigationBarItemView(self, arg1: android.content.Context, /) -> NavigationBarItemView: ...
    def findItemView(self, menuItemId: int | java.jint | java.lang.Integer, /) -> NavigationBarItemView: ...
    def getBadge(self, menuItemId: int | java.jint | java.lang.Integer, /) -> com.google.android.material.badge.BadgeDrawable: ...
    def getIconTintList(self) -> android.content.res.ColorStateList: ...
    def getItemBackground(self) -> android.graphics.drawable.Drawable: ...
    def getItemBackgroundRes(self) -> int: ...
    def getItemIconSize(self) -> int: ...
    def getItemTextAppearanceActive(self) -> int: ...
    def getItemTextAppearanceInactive(self) -> int: ...
    def getItemTextColor(self) -> android.content.res.ColorStateList: ...
    def getLabelVisibilityMode(self) -> int: ...
    def getMenu(self) -> androidx.appcompat.view.menu.MenuBuilder: ...
    def getSelectedItemId(self) -> int: ...
    def getSelectedItemPosition(self) -> int: ...
    def getWindowAnimations(self) -> int: ...
    def initialize(self, menu: androidx.appcompat.view.menu.MenuBuilder, /) -> None: ...
    def isShifting(self, labelVisibilityMode: int | java.jint | java.lang.Integer, childCount: int | java.jint | java.lang.Integer, /) -> bool: ...
    def onInitializeAccessibilityNodeInfo(self, info: android.view.accessibility.AccessibilityNodeInfo, /) -> None: ...
    def setIconTintList(self, tint: android.content.res.ColorStateList, /) -> None: ...
    def setItemBackground(self, background: android.graphics.drawable.Drawable, /) -> None: ...
    def setItemBackgroundRes(self, background: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemIconSize(self, iconSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemOnTouchListener(self, menuItemId: int | java.jint | java.lang.Integer, onTouchListener: android.view.View.OnTouchListener, /) -> None: ...
    def setItemTextAppearanceActive(self, textAppearanceRes: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemTextAppearanceInactive(self, textAppearanceRes: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemTextColor(self, color: android.content.res.ColorStateList, /) -> None: ...
    def setLabelVisibilityMode(self, labelVisibilityMode: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPresenter(self, presenter: NavigationBarPresenter, /) -> None: ...
    def updateMenuView(self) -> None: ...

class NavigationBarPresenter(androidx.appcompat.view.menu.MenuPresenter):
    def __init__(self) -> None: ...
    def collapseItemActionView(self, menu: androidx.appcompat.view.menu.MenuBuilder, item: androidx.appcompat.view.menu.MenuItemImpl, /) -> bool: ...
    def expandItemActionView(self, menu: androidx.appcompat.view.menu.MenuBuilder, item: androidx.appcompat.view.menu.MenuItemImpl, /) -> bool: ...
    def flagActionItems(self) -> bool: ...
    def getId(self) -> int: ...
    def getMenuView(self, root: android.view.ViewGroup, /) -> androidx.appcompat.view.menu.MenuView: ...
    def initForMenu(self, context: android.content.Context, menu: androidx.appcompat.view.menu.MenuBuilder, /) -> None: ...
    def onCloseMenu(self, menu: androidx.appcompat.view.menu.MenuBuilder, allMenusAreClosing: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def onRestoreInstanceState(self, state: android.os.Parcelable, /) -> None: ...
    def onSaveInstanceState(self) -> android.os.Parcelable: ...
    def onSubMenuSelected(self, subMenu: androidx.appcompat.view.menu.SubMenuBuilder, /) -> bool: ...
    def setCallback(self, cb: androidx.appcompat.view.menu.MenuPresenter.Callback, /) -> None: ...
    def setId(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMenuView(self, menuView: NavigationBarMenuView, /) -> None: ...
    def setUpdateSuspended(self, updateSuspended: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def updateMenuView(self, cleared: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class NavigationBarView(android.widget.FrameLayout):
    LABEL_VISIBILITY_AUTO: typing.ClassVar[int] = ...
    LABEL_VISIBILITY_SELECTED: typing.ClassVar[int] = ...
    LABEL_VISIBILITY_LABELED: typing.ClassVar[int] = ...
    LABEL_VISIBILITY_UNLABELED: typing.ClassVar[int] = ...
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, /) -> None: ...
    def createNavigationBarMenuView(self, arg1: android.content.Context, /) -> NavigationBarMenuView: ...
    def getBadge(self, menuItemId: int | java.jint | java.lang.Integer, /) -> com.google.android.material.badge.BadgeDrawable: ...
    def getItemBackground(self) -> android.graphics.drawable.Drawable: ...
    def getItemBackgroundResource(self) -> int: ...
    def getItemIconSize(self) -> int: ...
    def getItemIconTintList(self) -> android.content.res.ColorStateList: ...
    def getItemRippleColor(self) -> android.content.res.ColorStateList: ...
    def getItemTextAppearanceActive(self) -> int: ...
    def getItemTextAppearanceInactive(self) -> int: ...
    def getItemTextColor(self) -> android.content.res.ColorStateList: ...
    def getLabelVisibilityMode(self) -> int: ...
    def getMaxItemCount(self) -> int: ...
    def getMenu(self) -> android.view.Menu: ...
    def getMenuView(self) -> androidx.appcompat.view.menu.MenuView: ...
    def getOrCreateBadge(self, menuItemId: int | java.jint | java.lang.Integer, /) -> com.google.android.material.badge.BadgeDrawable: ...
    def getPresenter(self) -> NavigationBarPresenter: ...
    def getSelectedItemId(self) -> int: ...
    def inflateMenu(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def onRestoreInstanceState(self, state: android.os.Parcelable, /) -> None: ...
    def onSaveInstanceState(self) -> android.os.Parcelable: ...
    def removeBadge(self, menuItemId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setElevation(self, elevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setItemBackground(self, background: android.graphics.drawable.Drawable, /) -> None: ...
    def setItemBackgroundResource(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemIconSize(self, iconSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemIconSizeRes(self, iconSizeRes: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemIconTintList(self, tint: android.content.res.ColorStateList, /) -> None: ...
    def setItemOnTouchListener(self, menuItemId: int | java.jint | java.lang.Integer, onTouchListener: android.view.View.OnTouchListener, /) -> None: ...
    def setItemRippleColor(self, itemRippleColor: android.content.res.ColorStateList, /) -> None: ...
    def setItemTextAppearanceActive(self, textAppearanceRes: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemTextAppearanceInactive(self, textAppearanceRes: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemTextColor(self, textColor: android.content.res.ColorStateList, /) -> None: ...
    def setLabelVisibilityMode(self, labelVisibilityMode: int | java.jint | java.lang.Integer, /) -> None: ...
    def setOnItemReselectedListener(self, listener: NavigationBarView.OnItemReselectedListener, /) -> None: ...
    def setOnItemSelectedListener(self, listener: NavigationBarView.OnItemSelectedListener, /) -> None: ...
    def setSelectedItemId(self, itemId: int | java.jint | java.lang.Integer, /) -> None: ...

    class OnItemReselectedListener(java.lang.Object):
        def onNavigationItemReselected(self, arg1: android.view.MenuItem, /) -> None: ...

    class OnItemSelectedListener(java.lang.Object):
        def onNavigationItemSelected(self, arg1: android.view.MenuItem, /) -> bool: ...

    class LabelVisibility(java.lang.annotation.Annotation): ...

class NavigationView(com.google.android.material.internal.ScrimInsetsFrameLayout):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def addHeaderView(self, view: android.view.View, /) -> None: ...
    def getCheckedItem(self) -> android.view.MenuItem: ...
    def getHeaderCount(self) -> int: ...
    def getHeaderView(self, index: int | java.jint | java.lang.Integer, /) -> android.view.View: ...
    def getItemBackground(self) -> android.graphics.drawable.Drawable: ...
    def getItemHorizontalPadding(self) -> int: ...
    def getItemIconPadding(self) -> int: ...
    def getItemIconTintList(self) -> android.content.res.ColorStateList: ...
    def getItemMaxLines(self) -> int: ...
    def getItemTextColor(self) -> android.content.res.ColorStateList: ...
    def getMenu(self) -> android.view.Menu: ...
    def inflateHeaderView(self, res: int | java.jint | java.lang.Integer, /) -> android.view.View: ...
    def inflateMenu(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onInsetsChanged(self, insets: androidx.core.view.WindowInsetsCompat, /) -> None: ...
    def onMeasure(self, widthSpec: int | java.jint | java.lang.Integer, heightSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def onRestoreInstanceState(self, savedState: android.os.Parcelable, /) -> None: ...
    def onSaveInstanceState(self) -> android.os.Parcelable: ...
    def removeHeaderView(self, view: android.view.View, /) -> None: ...
    @typing.overload
    def setCheckedItem(self, id: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCheckedItem(self, checkedItem: android.view.MenuItem, /) -> None: ...
    def setElevation(self, elevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setItemBackground(self, itemBackground: android.graphics.drawable.Drawable, /) -> None: ...
    def setItemBackgroundResource(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemHorizontalPadding(self, padding: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemHorizontalPaddingResource(self, paddingResource: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemIconPadding(self, padding: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemIconPaddingResource(self, paddingResource: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemIconSize(self, iconSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemIconTintList(self, tint: android.content.res.ColorStateList, /) -> None: ...
    def setItemMaxLines(self, itemMaxLines: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemTextAppearance(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setItemTextColor(self, textColor: android.content.res.ColorStateList, /) -> None: ...
    def setNavigationItemSelectedListener(self, listener: NavigationView.OnNavigationItemSelectedListener, /) -> None: ...
    def setOverScrollMode(self, overScrollMode: int | java.jint | java.lang.Integer, /) -> None: ...

    class SavedState(androidx.customview.view.AbsSavedState):
        menuState: android.os.Bundle = ...
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator[NavigationView.SavedState]] = ...
        @typing.overload
        def __init__(self, superState: android.os.Parcelable, /) -> None: ...
        @typing.overload
        def __init__(self, in_: android.os.Parcel, loader: java.lang.ClassLoader, /) -> None: ...
        def writeToParcel(self, dest: android.os.Parcel, flags: int | java.jint | java.lang.Integer, /) -> None: ...

    class OnNavigationItemSelectedListener(java.lang.Object):
        def onNavigationItemSelected(self, arg1: android.view.MenuItem, /) -> bool: ...
