import android.content
import android.graphics
import android.graphics.drawable
import androidx.appcompat.graphics.drawable
import java
import java.chaquopy
import java.lang
import typing



class ShadowDrawableWrapper(androidx.appcompat.graphics.drawable.DrawableWrapperCompat):
    def __init__(self, context: android.content.Context, content: android.graphics.drawable.Drawable, radius: float | java.jfloat | java.lang.Float, shadowSize: float | java.jfloat | java.lang.Float, maxShadowSize: float | java.jfloat | java.lang.Float, /) -> None: ...
    @staticmethod
    def calculateHorizontalPadding(maxShadowSize: float | java.jfloat | java.lang.Float, cornerRadius: float | java.jfloat | java.lang.Float, addPaddingForCorners: bool | java.jboolean | java.lang.Boolean, /) -> float: ...
    @staticmethod
    def calculateVerticalPadding(maxShadowSize: float | java.jfloat | java.lang.Float, cornerRadius: float | java.jfloat | java.lang.Float, addPaddingForCorners: bool | java.jboolean | java.lang.Boolean, /) -> float: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getCornerRadius(self) -> float: ...
    def getMaxShadowSize(self) -> float: ...
    def getMinHeight(self) -> float: ...
    def getMinWidth(self) -> float: ...
    def getOpacity(self) -> int: ...
    def getPadding(self, padding: android.graphics.Rect, /) -> bool: ...
    def getShadowSize(self) -> float: ...
    def onBoundsChange(self, bounds: android.graphics.Rect, /) -> None: ...
    def setAddPaddingForCorners(self, addPaddingForCorners: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setAlpha(self, alpha: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCornerRadius(self, radius: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setMaxShadowSize(self, size: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setRotation(self, rotation: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def setShadowSize(self, size: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def setShadowSize(self, shadowSize: float | java.jfloat | java.lang.Float, maxShadowSize: float | java.jfloat | java.lang.Float, /) -> None: ...

class ShadowRenderer(java.lang.Object):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    def drawCornerShadow(self, canvas: android.graphics.Canvas, matrix: android.graphics.Matrix, bounds: android.graphics.RectF, elevation: int | java.jint | java.lang.Integer, startAngle: float | java.jfloat | java.lang.Float, sweepAngle: float | java.jfloat | java.lang.Float, /) -> None: ...
    def drawEdgeShadow(self, canvas: android.graphics.Canvas, transform: android.graphics.Matrix, bounds: android.graphics.RectF, elevation: int | java.jint | java.lang.Integer, /) -> None: ...
    def drawInnerCornerShadow(self, canvas: android.graphics.Canvas, matrix: android.graphics.Matrix, bounds: android.graphics.RectF, elevation: int | java.jint | java.lang.Integer, startAngle: float | java.jfloat | java.lang.Float, sweepAngle: float | java.jfloat | java.lang.Float, cornerPosition: java.chaquopy.JavaArrayJFloat, /) -> None: ...
    def getShadowPaint(self) -> android.graphics.Paint: ...
    def setShadowColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...

class ShadowViewDelegate(java.lang.Object):
    def getRadius(self) -> float: ...
    def isCompatPaddingEnabled(self) -> bool: ...
    def setBackgroundDrawable(self, arg1: android.graphics.drawable.Drawable, /) -> None: ...
    def setShadowPadding(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, arg4: int | java.jint | java.lang.Integer, /) -> None: ...
