import typing

import android.content
import android.content.pm
import android.content.res
import android.graphics
import android.net
import android.os
import android.provider
import androidx.core.content.res
import java
import java.chaquopy
import java.lang
import java.lang.annotation
import java.nio
import java.util
import java.util.concurrent

class CallbackWrapper(java.lang.Object): ...

class CalleeHandler(java.lang.Object): ...

class DocumentsContractCompat(java.lang.Object):
    @staticmethod
    def buildChildDocumentsUri(authority: str | java.lang.String, parentDocumentId: str | java.lang.String, /) -> android.net.Uri: ...
    @staticmethod
    def buildChildDocumentsUriUsingTree(treeUri: android.net.Uri, parentDocumentId: str | java.lang.String, /) -> android.net.Uri: ...
    @staticmethod
    def buildDocumentUri(authority: str | java.lang.String, documentId: str | java.lang.String, /) -> android.net.Uri: ...
    @staticmethod
    def buildDocumentUriUsingTree(treeUri: android.net.Uri, documentId: str | java.lang.String, /) -> android.net.Uri: ...
    @staticmethod
    def buildTreeDocumentUri(authority: str | java.lang.String, documentId: str | java.lang.String, /) -> android.net.Uri: ...
    @staticmethod
    def createDocument(content: android.content.ContentResolver, parentDocumentUri: android.net.Uri, mimeType: str | java.lang.String, displayName: str | java.lang.String, /) -> android.net.Uri: ...
    @staticmethod
    def getDocumentId(documentUri: android.net.Uri, /) -> str: ...
    @staticmethod
    def getTreeDocumentId(documentUri: android.net.Uri, /) -> str: ...
    @staticmethod
    def isDocumentUri(context: android.content.Context, uri: android.net.Uri, /) -> bool: ...
    @staticmethod
    def isTreeUri(uri: android.net.Uri, /) -> bool: ...
    @staticmethod
    def removeDocument(content: android.content.ContentResolver, documentUri: android.net.Uri, parentDocumentUri: android.net.Uri, /) -> bool: ...
    @staticmethod
    def renameDocument(content: android.content.ContentResolver, documentUri: android.net.Uri, displayName: str | java.lang.String, /) -> android.net.Uri: ...

    class DocumentCompat(java.lang.Object):
        FLAG_VIRTUAL_DOCUMENT: typing.ClassVar[int] = ...

class FontProvider(java.lang.Object): ...

class FontRequest(java.lang.Object):
    @typing.overload
    def __init__(self, providerAuthority: str | java.lang.String, providerPackage: str | java.lang.String, query: str | java.lang.String, certificates: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, providerAuthority: str | java.lang.String, providerPackage: str | java.lang.String, query: str | java.lang.String, certificates: java.util.List[java.util.List[java.chaquopy.JavaArrayJByte]], /) -> None: ...
    def getCertificates(self) -> java.util.List[java.util.List[java.chaquopy.JavaArrayJByte]]: ...
    def getCertificatesArrayResId(self) -> int: ...
    def getIdentifier(self) -> str: ...
    def getProviderAuthority(self) -> str: ...
    def getProviderPackage(self) -> str: ...
    def getQuery(self) -> str: ...
    def toString(self) -> str: ...

class FontRequestWorker(java.lang.Object): ...

class FontsContractCompat(java.lang.Object):
    PARCEL_FONT_RESULTS: typing.ClassVar[str] = ...
    @staticmethod
    def buildTypeface(context: android.content.Context, cancellationSignal: android.os.CancellationSignal, fonts: java.chaquopy.JavaArray[FontsContractCompat.FontInfo], /) -> android.graphics.Typeface: ...
    @staticmethod
    def fetchFonts(context: android.content.Context, cancellationSignal: android.os.CancellationSignal, request: FontRequest, /) -> FontsContractCompat.FontFamilyResult: ...
    @staticmethod
    def getFontSync(context: android.content.Context, request: FontRequest, fontCallback: androidx.core.content.res.ResourcesCompat.FontCallback, handler: android.os.Handler, isBlockingFetch: bool | java.jboolean | java.lang.Boolean, timeout: int | java.jint | java.lang.Integer, style: int | java.jint | java.lang.Integer, /) -> android.graphics.Typeface: ...
    @staticmethod
    def getProvider(packageManager: android.content.pm.PackageManager, request: FontRequest, resources: android.content.res.Resources, /) -> android.content.pm.ProviderInfo: ...
    @staticmethod
    def prepareFontData(context: android.content.Context, fonts: java.chaquopy.JavaArray[FontsContractCompat.FontInfo], cancellationSignal: android.os.CancellationSignal, /) -> java.util.Map[android.net.Uri, java.nio.ByteBuffer]: ...
    @typing.overload
    @staticmethod
    def requestFont(context: android.content.Context, request: FontRequest, callback: FontsContractCompat.FontRequestCallback, handler: android.os.Handler, /) -> None: ...
    @typing.overload
    @staticmethod
    def requestFont(context: android.content.Context, request: FontRequest, style: int | java.jint | java.lang.Integer, loadingExecutor: java.util.concurrent.Executor, callbackExecutor: java.util.concurrent.Executor, callback: FontsContractCompat.FontRequestCallback, /) -> None: ...
    @typing.overload
    @staticmethod
    def requestFont(context: android.content.Context, request: FontRequest, style: int | java.jint | java.lang.Integer, isBlockingFetch: bool | java.jboolean | java.lang.Boolean, timeout: int | java.jint | java.lang.Integer, handler: android.os.Handler, callback: FontsContractCompat.FontRequestCallback, /) -> android.graphics.Typeface: ...
    @typing.overload
    @staticmethod
    def requestFont(context: android.content.Context, requests: java.util.List[FontRequest], style: int | java.jint | java.lang.Integer, isBlockingFetch: bool | java.jboolean | java.lang.Boolean, timeout: int | java.jint | java.lang.Integer, handler: android.os.Handler, callback: FontsContractCompat.FontRequestCallback, /) -> android.graphics.Typeface: ...
    @staticmethod
    def requestFontWithFallbackChain(context: android.content.Context, requests: java.util.List[FontRequest], style: int | java.jint | java.lang.Integer, loadingExecutor: java.util.concurrent.Executor, callbackExecutor: java.util.concurrent.Executor, callback: FontsContractCompat.FontRequestCallback, /) -> None: ...
    @staticmethod
    def resetCache() -> None: ...
    @staticmethod
    def resetTypefaceCache() -> None: ...

    class FontInfo(java.lang.Object):
        def __init__(self, uri: android.net.Uri, ttcIndex: int | java.jint | java.lang.Integer, weight: int | java.jint | java.lang.Integer, italic: bool | java.jboolean | java.lang.Boolean, resultCode: int | java.jint | java.lang.Integer, /) -> None: ...
        def getResultCode(self) -> int: ...
        def getTtcIndex(self) -> int: ...
        def getUri(self) -> android.net.Uri: ...
        def getWeight(self) -> int: ...
        def isItalic(self) -> bool: ...

    class FontFamilyResult(java.lang.Object):
        STATUS_OK: typing.ClassVar[int] = ...
        STATUS_WRONG_CERTIFICATES: typing.ClassVar[int] = ...
        STATUS_UNEXPECTED_DATA_PROVIDED: typing.ClassVar[int] = ...
        def __init__(self, statusCode: int | java.jint | java.lang.Integer, fonts: java.chaquopy.JavaArray[FontsContractCompat.FontInfo], /) -> None: ...
        def getFonts(self) -> java.chaquopy.JavaArray[FontsContractCompat.FontInfo]: ...
        def getFontsWithFallbacks(self) -> java.util.List[java.chaquopy.JavaArray[FontsContractCompat.FontInfo]]: ...
        def getStatusCode(self) -> int: ...

    class FontRequestCallback(java.lang.Object):
        RESULT_OK: typing.ClassVar[int] = ...
        FAIL_REASON_PROVIDER_NOT_FOUND: typing.ClassVar[int] = ...
        FAIL_REASON_WRONG_CERTIFICATES: typing.ClassVar[int] = ...
        FAIL_REASON_FONT_LOAD_ERROR: typing.ClassVar[int] = ...
        FAIL_REASON_SECURITY_VIOLATION: typing.ClassVar[int] = ...
        FAIL_REASON_FONT_NOT_FOUND: typing.ClassVar[int] = ...
        FAIL_REASON_FONT_UNAVAILABLE: typing.ClassVar[int] = ...
        FAIL_REASON_MALFORMED_QUERY: typing.ClassVar[int] = ...
        def __init__(self) -> None: ...
        def onTypefaceRequestFailed(self, reason: int | java.jint | java.lang.Integer, /) -> None: ...
        def onTypefaceRetrieved(self, typeface: android.graphics.Typeface, /) -> None: ...

        class FontRequestFailReason(java.lang.annotation.Annotation): ...

    class Columns(android.provider.BaseColumns):
        FILE_ID: typing.ClassVar[str] = ...
        TTC_INDEX: typing.ClassVar[str] = ...
        VARIATION_SETTINGS: typing.ClassVar[str] = ...
        WEIGHT: typing.ClassVar[str] = ...
        ITALIC: typing.ClassVar[str] = ...
        RESULT_CODE: typing.ClassVar[str] = ...
        RESULT_CODE_OK: typing.ClassVar[int] = ...
        RESULT_CODE_FONT_NOT_FOUND: typing.ClassVar[int] = ...
        RESULT_CODE_FONT_UNAVAILABLE: typing.ClassVar[int] = ...
        RESULT_CODE_MALFORMED_QUERY: typing.ClassVar[int] = ...
        def __init__(self) -> None: ...

    class TypefaceStyle(java.lang.annotation.Annotation): ...

class RequestExecutor(java.lang.Object): ...


_SelfDestructiveThread__ReplyCallback__T = typing.TypeVar('_SelfDestructiveThread__ReplyCallback__T')  # <T>
class SelfDestructiveThread(java.lang.Object):
    def __init__(self, threadName: str | java.lang.String, priority: int | java.jint | java.lang.Integer, destructAfterMillisec: int | java.jint | java.lang.Integer, /) -> None: ...
    def getGeneration(self) -> int: ...
    def isRunning(self) -> bool: ...
    _postAndReply__T = typing.TypeVar('_postAndReply__T')  # <T>
    def postAndReply(self, callable: java.util.concurrent.Callable[_postAndReply__T], reply: SelfDestructiveThread.ReplyCallback[_postAndReply__T], /) -> None: ...
    _postAndWait__T = typing.TypeVar('_postAndWait__T')  # <T>
    def postAndWait(self, callable: java.util.concurrent.Callable[_postAndWait__T], timeoutMillis: int | java.jint | java.lang.Integer, /) -> _postAndWait__T: ...
    class ReplyCallback(java.lang.Object, typing.Generic[_SelfDestructiveThread__ReplyCallback__T]):
        def onReply(self, arg1: _SelfDestructiveThread__ReplyCallback__T, /) -> None: ...
