import typing

import android.content
import android.os
import android.util
import android.view
import android.view.accessibility
import androidx.recyclerview.widget
import java
import java.lang
import java.lang.annotation

class AnimateLayoutChangeDetector(java.lang.Object): ...

class CompositeOnPageChangeCallback(ViewPager2.OnPageChangeCallback):
    def onPageScrollStateChanged(self, state: int | java.jint | java.lang.Integer, /) -> None: ...
    def onPageScrolled(self, position: int | java.jint | java.lang.Integer, positionOffset: float | java.jfloat | java.lang.Float, positionOffsetPixels: int | java.jint | java.lang.Integer, /) -> None: ...
    def onPageSelected(self, position: int | java.jint | java.lang.Integer, /) -> None: ...

class CompositePageTransformer(ViewPager2.PageTransformer):
    def __init__(self) -> None: ...
    def addTransformer(self, transformer: ViewPager2.PageTransformer, /) -> None: ...
    def removeTransformer(self, transformer: ViewPager2.PageTransformer, /) -> None: ...
    def transformPage(self, page: android.view.View, position: float | java.jfloat | java.lang.Float, /) -> None: ...

class FakeDrag(java.lang.Object): ...

class MarginPageTransformer(ViewPager2.PageTransformer):
    def __init__(self, marginPx: int | java.jint | java.lang.Integer, /) -> None: ...
    def transformPage(self, page: android.view.View, position: float | java.jfloat | java.lang.Float, /) -> None: ...

class PageTransformerAdapter(ViewPager2.OnPageChangeCallback):
    def onPageScrollStateChanged(self, state: int | java.jint | java.lang.Integer, /) -> None: ...
    def onPageScrolled(self, position: int | java.jint | java.lang.Integer, positionOffset: float | java.jfloat | java.lang.Float, positionOffsetPixels: int | java.jint | java.lang.Integer, /) -> None: ...
    def onPageSelected(self, position: int | java.jint | java.lang.Integer, /) -> None: ...

class ScrollEventAdapter(androidx.recyclerview.widget.RecyclerView.OnScrollListener):
    def onScrollStateChanged(self, recyclerView: androidx.recyclerview.widget.RecyclerView, newState: int | java.jint | java.lang.Integer, /) -> None: ...
    def onScrolled(self, recyclerView: androidx.recyclerview.widget.RecyclerView, dx: int | java.jint | java.lang.Integer, dy: int | java.jint | java.lang.Integer, /) -> None: ...

class ViewPager2(android.view.ViewGroup):
    ORIENTATION_HORIZONTAL: typing.ClassVar[int] = ...
    ORIENTATION_VERTICAL: typing.ClassVar[int] = ...
    SCROLL_STATE_IDLE: typing.ClassVar[int] = ...
    SCROLL_STATE_DRAGGING: typing.ClassVar[int] = ...
    SCROLL_STATE_SETTLING: typing.ClassVar[int] = ...
    OFFSCREEN_PAGE_LIMIT_DEFAULT: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def addItemDecoration(self, decor: androidx.recyclerview.widget.RecyclerView.ItemDecoration, /) -> None: ...
    @typing.overload
    def addItemDecoration(self, decor: androidx.recyclerview.widget.RecyclerView.ItemDecoration, index: int | java.jint | java.lang.Integer, /) -> None: ...
    def beginFakeDrag(self) -> bool: ...
    def canScrollHorizontally(self, direction: int | java.jint | java.lang.Integer, /) -> bool: ...
    def canScrollVertically(self, direction: int | java.jint | java.lang.Integer, /) -> bool: ...
    def dispatchRestoreInstanceState(self, container: android.util.SparseArray[android.os.Parcelable], /) -> None: ...
    def endFakeDrag(self) -> bool: ...
    def fakeDragBy(self, offsetPxFloat: float | java.jfloat | java.lang.Float, /) -> bool: ...
    def getAccessibilityClassName(self) -> java.lang.CharSequence: ...
    def getAdapter(self) -> androidx.recyclerview.widget.RecyclerView.Adapter: ...
    def getCurrentItem(self) -> int: ...
    def getItemDecorationAt(self, index: int | java.jint | java.lang.Integer, /) -> androidx.recyclerview.widget.RecyclerView.ItemDecoration: ...
    def getItemDecorationCount(self) -> int: ...
    def getOffscreenPageLimit(self) -> int: ...
    def getOrientation(self) -> int: ...
    def getScrollState(self) -> int: ...
    def invalidateItemDecorations(self) -> None: ...
    def isFakeDragging(self) -> bool: ...
    def isUserInputEnabled(self) -> bool: ...
    def onInitializeAccessibilityNodeInfo(self, info: android.view.accessibility.AccessibilityNodeInfo, /) -> None: ...
    def onLayout(self, changed: bool | java.jboolean | java.lang.Boolean, l: int | java.jint | java.lang.Integer, t: int | java.jint | java.lang.Integer, r: int | java.jint | java.lang.Integer, b: int | java.jint | java.lang.Integer, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def onRestoreInstanceState(self, state: android.os.Parcelable, /) -> None: ...
    def onSaveInstanceState(self) -> android.os.Parcelable: ...
    def onViewAdded(self, child: android.view.View, /) -> None: ...
    def performAccessibilityAction(self, action: int | java.jint | java.lang.Integer, arguments: android.os.Bundle, /) -> bool: ...
    def registerOnPageChangeCallback(self, callback: ViewPager2.OnPageChangeCallback, /) -> None: ...
    def removeItemDecoration(self, decor: androidx.recyclerview.widget.RecyclerView.ItemDecoration, /) -> None: ...
    def removeItemDecorationAt(self, index: int | java.jint | java.lang.Integer, /) -> None: ...
    def requestTransform(self) -> None: ...
    def setAdapter(self, adapter: androidx.recyclerview.widget.RecyclerView.Adapter, /) -> None: ...
    @typing.overload
    def setCurrentItem(self, item: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCurrentItem(self, item: int | java.jint | java.lang.Integer, smoothScroll: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setLayoutDirection(self, layoutDirection: int | java.jint | java.lang.Integer, /) -> None: ...
    def setOffscreenPageLimit(self, limit: int | java.jint | java.lang.Integer, /) -> None: ...
    def setOrientation(self, orientation: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPageTransformer(self, transformer: ViewPager2.PageTransformer, /) -> None: ...
    def setUserInputEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def unregisterOnPageChangeCallback(self, callback: ViewPager2.OnPageChangeCallback, /) -> None: ...

    class PageTransformer(java.lang.Object):
        def transformPage(self, arg1: android.view.View, arg2: float | java.jfloat | java.lang.Float, /) -> None: ...

    class OnPageChangeCallback(java.lang.Object):
        def __init__(self) -> None: ...
        def onPageScrollStateChanged(self, state: int | java.jint | java.lang.Integer, /) -> None: ...
        def onPageScrolled(self, position: int | java.jint | java.lang.Integer, positionOffset: float | java.jfloat | java.lang.Float, positionOffsetPixels: int | java.jint | java.lang.Integer, /) -> None: ...
        def onPageSelected(self, position: int | java.jint | java.lang.Integer, /) -> None: ...

    class OffscreenPageLimit(java.lang.annotation.Annotation): ...

    class ScrollState(java.lang.annotation.Annotation): ...

    class Orientation(java.lang.annotation.Annotation): ...
