import java.chaquopy
import java.lang
import kotlin

class UArraysKt(UArraysKt___UArraysKt): ...

class UArraysKt___UArraysJvmKt(java.lang.Object):
    def __init__(self) -> None: ...

class UArraysKt___UArraysKt(UArraysKt___UArraysJvmKt):
    def __init__(self) -> None: ...
    @staticmethod
    def sumOfUByte(this_sum: java.chaquopy.JavaArray[kotlin.UByte], /) -> int: ...
    @staticmethod
    def sumOfUInt(this_sum: java.chaquopy.JavaArray[kotlin.UInt], /) -> int: ...
    @staticmethod
    def sumOfULong(this_sum: java.chaquopy.JavaArray[kotlin.ULong], /) -> int: ...
    @staticmethod
    def sumOfUShort(this_sum: java.chaquopy.JavaArray[kotlin.UShort], /) -> int: ...
    @staticmethod
    def toUByteArray(this_toUByteArray: java.chaquopy.JavaArray[kotlin.UByte], /) -> java.chaquopy.JavaArrayJByte: ...
    @staticmethod
    def toUIntArray(this_toUIntArray: java.chaquopy.JavaArray[kotlin.UInt], /) -> java.chaquopy.JavaArrayJInt: ...
    @staticmethod
    def toULongArray(this_toULongArray: java.chaquopy.JavaArray[kotlin.ULong], /) -> java.chaquopy.JavaArrayJLong: ...
    @staticmethod
    def toUShortArray(this_toUShortArray: java.chaquopy.JavaArray[kotlin.UShort], /) -> java.chaquopy.JavaArrayJShort: ...
