import android.content
import android.graphics
import android.hardware
import android.view
import java
import java.lang
import org.osmdroid.views
import org.osmdroid.views.overlay
import typing



class CompassOverlay(org.osmdroid.views.overlay.Overlay, org.osmdroid.views.overlay.IOverlayMenuProvider, IOrientationConsumer):
    mMapView: org.osmdroid.views.MapView = ...
    mOrientationProvider: IOrientationProvider = ...
    mCompassFrameBitmap: android.graphics.Bitmap = ...
    mCompassRoseBitmap: android.graphics.Bitmap = ...
    mCompassFrameCenterX: float = ...
    mCompassFrameCenterY: float = ...
    mCompassRoseCenterX: float = ...
    mCompassRoseCenterY: float = ...
    mLastRender: int = ...
    MENU_COMPASS: typing.ClassVar[int] = ...
    mScale: float = ...
    @typing.overload
    def __init__(self, context: android.content.Context, mapView: org.osmdroid.views.MapView, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, orientationProvider: IOrientationProvider, mapView: org.osmdroid.views.MapView, /) -> None: ...
    def disableCompass(self) -> None: ...
    def draw(self, c: android.graphics.Canvas, pProjection: org.osmdroid.views.Projection, /) -> None: ...
    def drawCompass(self, canvas: android.graphics.Canvas, bearing: float | java.jfloat | java.lang.Float, screenRect: android.graphics.Rect, /) -> None: ...
    @typing.overload
    def enableCompass(self) -> bool: ...
    @typing.overload
    def enableCompass(self, orientationProvider: IOrientationProvider, /) -> bool: ...
    def getAzimuthOffset(self) -> float: ...
    def getOrientation(self) -> float: ...
    def getOrientationProvider(self) -> IOrientationProvider: ...
    def isCompassEnabled(self) -> bool: ...
    def isCompassInCenter(self) -> bool: ...
    def isOptionsMenuEnabled(self) -> bool: ...
    def isPointerMode(self) -> bool: ...
    def onCreateOptionsMenu(self, pMenu: android.view.Menu, pMenuIdOffset: int | java.jint | java.lang.Integer, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onDetach(self, mapView: org.osmdroid.views.MapView, /) -> None: ...
    def onOptionsItemSelected(self, pItem: android.view.MenuItem, pMenuIdOffset: int | java.jint | java.lang.Integer, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onOrientationChanged(self, orientation: float | java.jfloat | java.lang.Float, source: IOrientationProvider, /) -> None: ...
    def onPause(self) -> None: ...
    def onPrepareOptionsMenu(self, pMenu: android.view.Menu, pMenuIdOffset: int | java.jint | java.lang.Integer, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onResume(self) -> None: ...
    def setAzimuthOffset(self, f: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setAzimuthPrecision(self, pAzimuthPrecision: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setCompassCenter(self, x: float | java.jfloat | java.lang.Float, y: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setCompassInCenter(self, b: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setLastRenderLag(self, pLastRenderLag: int | java.jint | java.lang.Integer, /) -> None: ...
    def setOptionsMenuEnabled(self, pOptionsMenuEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setOrientationProvider(self, orientationProvider: IOrientationProvider, /) -> None: ...
    def setPointerMode(self, usePointArrow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class IOrientationConsumer(java.lang.Object):
    def onOrientationChanged(self, arg1: float | java.jfloat | java.lang.Float, arg2: IOrientationProvider, /) -> None: ...

class IOrientationProvider(java.lang.Object):
    def destroy(self) -> None: ...
    def getLastKnownOrientation(self) -> float: ...
    def startOrientationProvider(self, arg1: IOrientationConsumer, /) -> bool: ...
    def stopOrientationProvider(self) -> None: ...

class InternalCompassOrientationProvider(android.hardware.SensorEventListener, IOrientationProvider):
    def __init__(self, context: android.content.Context, /) -> None: ...
    def destroy(self) -> None: ...
    def getLastKnownOrientation(self) -> float: ...
    def onAccuracyChanged(self, sensor: android.hardware.Sensor, accuracy: int | java.jint | java.lang.Integer, /) -> None: ...
    def onSensorChanged(self, event: android.hardware.SensorEvent, /) -> None: ...
    def startOrientationProvider(self, orientationConsumer: IOrientationConsumer, /) -> bool: ...
    def stopOrientationProvider(self) -> None: ...
