import typing

import android.text
import java
import java.chaquopy
import java.lang
import java.util
import java.util.concurrent

class BidiFormatter(java.lang.Object):
    @typing.overload
    @staticmethod
    def getInstance() -> BidiFormatter: ...
    @typing.overload
    @staticmethod
    def getInstance(locale: java.util.Locale, /) -> BidiFormatter: ...
    @typing.overload
    @staticmethod
    def getInstance(rtlContext: bool | java.jboolean | java.lang.Boolean, /) -> BidiFormatter: ...
    def getStereoReset(self) -> bool: ...
    @typing.overload
    def isRtl(self, str: java.lang.CharSequence, /) -> bool: ...
    @typing.overload
    def isRtl(self, str: str | java.lang.String, /) -> bool: ...
    def isRtlContext(self) -> bool: ...
    @typing.overload
    def unicodeWrap(self, str: java.lang.CharSequence, /) -> java.lang.CharSequence: ...
    @typing.overload
    def unicodeWrap(self, str: str | java.lang.String, /) -> str: ...
    @typing.overload
    def unicodeWrap(self, str: java.lang.CharSequence, heuristic: TextDirectionHeuristicCompat, /) -> java.lang.CharSequence: ...
    @typing.overload
    def unicodeWrap(self, str: java.lang.CharSequence, isolate: bool | java.jboolean | java.lang.Boolean, /) -> java.lang.CharSequence: ...
    @typing.overload
    def unicodeWrap(self, str: str | java.lang.String, heuristic: TextDirectionHeuristicCompat, /) -> str: ...
    @typing.overload
    def unicodeWrap(self, str: str | java.lang.String, isolate: bool | java.jboolean | java.lang.Boolean, /) -> str: ...
    @typing.overload
    def unicodeWrap(self, str: java.lang.CharSequence, heuristic: TextDirectionHeuristicCompat, isolate: bool | java.jboolean | java.lang.Boolean, /) -> java.lang.CharSequence: ...
    @typing.overload
    def unicodeWrap(self, str: str | java.lang.String, heuristic: TextDirectionHeuristicCompat, isolate: bool | java.jboolean | java.lang.Boolean, /) -> str: ...

    class Builder(java.lang.Object):
        @typing.overload
        def __init__(self) -> None: ...
        @typing.overload
        def __init__(self, locale: java.util.Locale, /) -> None: ...
        @typing.overload
        def __init__(self, rtlContext: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
        def build(self) -> BidiFormatter: ...
        def setTextDirectionHeuristic(self, heuristic: TextDirectionHeuristicCompat, /) -> BidiFormatter.Builder: ...
        def stereoReset(self, stereoReset: bool | java.jboolean | java.lang.Boolean, /) -> BidiFormatter.Builder: ...

class HtmlCompat(java.lang.Object):
    TO_HTML_PARAGRAPH_LINES_CONSECUTIVE: typing.ClassVar[int] = ...
    TO_HTML_PARAGRAPH_LINES_INDIVIDUAL: typing.ClassVar[int] = ...
    FROM_HTML_SEPARATOR_LINE_BREAK_PARAGRAPH: typing.ClassVar[int] = ...
    FROM_HTML_SEPARATOR_LINE_BREAK_HEADING: typing.ClassVar[int] = ...
    FROM_HTML_SEPARATOR_LINE_BREAK_LIST_ITEM: typing.ClassVar[int] = ...
    FROM_HTML_SEPARATOR_LINE_BREAK_LIST: typing.ClassVar[int] = ...
    FROM_HTML_SEPARATOR_LINE_BREAK_DIV: typing.ClassVar[int] = ...
    FROM_HTML_SEPARATOR_LINE_BREAK_BLOCKQUOTE: typing.ClassVar[int] = ...
    FROM_HTML_OPTION_USE_CSS_COLORS: typing.ClassVar[int] = ...
    FROM_HTML_MODE_LEGACY: typing.ClassVar[int] = ...
    FROM_HTML_MODE_COMPACT: typing.ClassVar[int] = ...
    @typing.overload
    @staticmethod
    def fromHtml(source: str | java.lang.String, flags: int | java.jint | java.lang.Integer, /) -> android.text.Spanned: ...
    @typing.overload
    @staticmethod
    def fromHtml(source: str | java.lang.String, flags: int | java.jint | java.lang.Integer, imageGetter: android.text.Html.ImageGetter, tagHandler: android.text.Html.TagHandler, /) -> android.text.Spanned: ...
    @staticmethod
    def toHtml(text: android.text.Spanned, options: int | java.jint | java.lang.Integer, /) -> str: ...

class ICUCompat(java.lang.Object):
    @staticmethod
    def maximizeAndGetScript(locale: java.util.Locale, /) -> str: ...

class PrecomputedTextCompat(android.text.Spannable):
    def charAt(self, index: int | java.jint | java.lang.Integer, /) -> str: ...
    @staticmethod
    def create(text: java.lang.CharSequence, params: PrecomputedTextCompat.Params, /) -> PrecomputedTextCompat: ...
    def getParagraphCount(self) -> int: ...
    def getParagraphEnd(self, paraIndex: int | java.jint | java.lang.Integer, /) -> int: ...
    def getParagraphStart(self, paraIndex: int | java.jint | java.lang.Integer, /) -> int: ...
    def getParams(self) -> PrecomputedTextCompat.Params: ...
    def getPrecomputedText(self) -> android.text.PrecomputedText: ...
    def getSpanEnd(self, tag: java.lang.Object | int | bool | float | str, /) -> int: ...
    def getSpanFlags(self, tag: java.lang.Object | int | bool | float | str, /) -> int: ...
    def getSpanStart(self, tag: java.lang.Object | int | bool | float | str, /) -> int: ...
    _getSpans__T = typing.TypeVar('_getSpans__T')  # <T>
    def getSpans(self, start: int | java.jint | java.lang.Integer, end: int | java.jint | java.lang.Integer, type: typing.Type[_getSpans__T], /) -> java.chaquopy.JavaArray[_getSpans__T]: ...
    @staticmethod
    def getTextFuture(charSequence: java.lang.CharSequence, params: PrecomputedTextCompat.Params, executor: java.util.concurrent.Executor, /) -> java.util.concurrent.Future[PrecomputedTextCompat]: ...
    def length(self) -> int: ...
    def nextSpanTransition(self, start: int | java.jint | java.lang.Integer, limit: int | java.jint | java.lang.Integer, type: typing.Type, /) -> int: ...
    def removeSpan(self, what: java.lang.Object | int | bool | float | str, /) -> None: ...
    def setSpan(self, what: java.lang.Object | int | bool | float | str, start: int | java.jint | java.lang.Integer, end: int | java.jint | java.lang.Integer, flags: int | java.jint | java.lang.Integer, /) -> None: ...
    def subSequence(self, start: int | java.jint | java.lang.Integer, end: int | java.jint | java.lang.Integer, /) -> java.lang.CharSequence: ...
    def toString(self) -> str: ...

    class Params(java.lang.Object):
        def __init__(self, wrapped: android.text.PrecomputedText.Params, /) -> None: ...
        def equals(self, o: java.lang.Object | int | bool | float | str, /) -> bool: ...
        def equalsWithoutTextDirection(self, other: PrecomputedTextCompat.Params, /) -> bool: ...
        def getBreakStrategy(self) -> int: ...
        def getHyphenationFrequency(self) -> int: ...
        def getTextDirection(self) -> android.text.TextDirectionHeuristic: ...
        def getTextPaint(self) -> android.text.TextPaint: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...

        class Builder(java.lang.Object):
            def __init__(self, paint: android.text.TextPaint, /) -> None: ...
            def build(self) -> PrecomputedTextCompat.Params: ...
            def setBreakStrategy(self, strategy: int | java.jint | java.lang.Integer, /) -> PrecomputedTextCompat.Params.Builder: ...
            def setHyphenationFrequency(self, frequency: int | java.jint | java.lang.Integer, /) -> PrecomputedTextCompat.Params.Builder: ...
            def setTextDirection(self, textDir: android.text.TextDirectionHeuristic, /) -> PrecomputedTextCompat.Params.Builder: ...

class TextDirectionHeuristicCompat(java.lang.Object):
    @typing.overload
    def isRtl(self, arg1: java.lang.CharSequence, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def isRtl(self, arg1: java.chaquopy.JavaArrayJChar, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, /) -> bool: ...

class TextDirectionHeuristicsCompat(java.lang.Object):
    LTR: typing.ClassVar[TextDirectionHeuristicCompat] = ...
    RTL: typing.ClassVar[TextDirectionHeuristicCompat] = ...
    FIRSTSTRONG_LTR: typing.ClassVar[TextDirectionHeuristicCompat] = ...
    FIRSTSTRONG_RTL: typing.ClassVar[TextDirectionHeuristicCompat] = ...
    ANYRTL_LTR: typing.ClassVar[TextDirectionHeuristicCompat] = ...
    LOCALE: typing.ClassVar[TextDirectionHeuristicCompat] = ...

class TextUtilsCompat(java.lang.Object):
    @staticmethod
    def getLayoutDirectionFromLocale(locale: java.util.Locale, /) -> int: ...
    @staticmethod
    def htmlEncode(s: str | java.lang.String, /) -> str: ...
