import typing

import androidx.lifecycle
import java.lang
import java.lang.annotation
import kotlin
import kotlin.jvm.functions
import kotlin.reflect


_CreationExtras__Key__T = typing.TypeVar('_CreationExtras__Key__T')  # <T>
class CreationExtras(java.lang.Object):
    def __init__(self) -> None: ...
    _get__T = typing.TypeVar('_get__T')  # <T>
    def get(self, arg1: CreationExtras.Key[_get__T], /) -> _get__T: ...

    class Empty(CreationExtras):
        INSTANCE: typing.ClassVar[CreationExtras.Empty] = ...
        _get__T = typing.TypeVar('_get__T')  # <T>
        def get(self, key: CreationExtras.Key[_get__T], /) -> _get__T: ...
    class Key(java.lang.Object, typing.Generic[_CreationExtras__Key__T]): ...

class InitializerViewModelFactory(androidx.lifecycle.ViewModelProvider.Factory):
    def __init__(self, *initializers: ViewModelInitializer[java.lang.Object]) -> None: ...
    _create__T = typing.TypeVar('_create__T', bound=androidx.lifecycle.ViewModel)  # <T>
    def create(self, modelClass: typing.Type[_create__T], extras: CreationExtras, /) -> _create__T: ...

class InitializerViewModelFactoryBuilder(java.lang.Object):
    def __init__(self) -> None: ...
    _addInitializer__T = typing.TypeVar('_addInitializer__T', bound=androidx.lifecycle.ViewModel)  # <T>
    def addInitializer(self, clazz: kotlin.reflect.KClass[_addInitializer__T], initializer: kotlin.jvm.functions.Function1[CreationExtras, _addInitializer__T], /) -> None: ...
    def build(self) -> androidx.lifecycle.ViewModelProvider.Factory: ...

class InitializerViewModelFactoryKt(java.lang.Object):
    @staticmethod
    def viewModelFactory(builder: kotlin.jvm.functions.Function1[InitializerViewModelFactoryBuilder, kotlin.Unit], /) -> androidx.lifecycle.ViewModelProvider.Factory: ...

class MutableCreationExtras(CreationExtras):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, initialExtras: CreationExtras, /) -> None: ...
    _get__T = typing.TypeVar('_get__T')  # <T>
    def get(self, key: CreationExtras.Key[_get__T], /) -> _get__T: ...
    _set__T = typing.TypeVar('_set__T')  # <T>
    def set(self, key: CreationExtras.Key[_set__T], t: _set__T, /) -> None: ...

class ViewModelFactoryDsl(java.lang.annotation.Annotation): ...

_ViewModelInitializer__T = typing.TypeVar('_ViewModelInitializer__T', bound=androidx.lifecycle.ViewModel)  # <T>
class ViewModelInitializer(java.lang.Object, typing.Generic[_ViewModelInitializer__T]):
    def __init__(self, clazz: typing.Type[_ViewModelInitializer__T], initializer: kotlin.jvm.functions.Function1[CreationExtras, _ViewModelInitializer__T], /) -> None: ...
