import typing

import android.os
import android.view
import androidx.fragment.app
import androidx.lifecycle
import androidx.recyclerview.widget
import java
import java.lang

class FragmentStateAdapter(androidx.recyclerview.widget.RecyclerView.Adapter[FragmentViewHolder], StatefulAdapter):
    @typing.overload
    def __init__(self, fragment: androidx.fragment.app.Fragment, /) -> None: ...
    @typing.overload
    def __init__(self, fragmentActivity: androidx.fragment.app.FragmentActivity, /) -> None: ...
    @typing.overload
    def __init__(self, fragmentManager: androidx.fragment.app.FragmentManager, lifecycle: androidx.lifecycle.Lifecycle, /) -> None: ...
    def containsItem(self, itemId: int | java.jlong | java.lang.Long, /) -> bool: ...
    def createFragment(self, arg1: int | java.jint | java.lang.Integer, /) -> androidx.fragment.app.Fragment: ...
    def getItemId(self, position: int | java.jint | java.lang.Integer, /) -> int: ...
    def onAttachedToRecyclerView(self, recyclerView: androidx.recyclerview.widget.RecyclerView, /) -> None: ...
    def onBindViewHolder(self, holder: FragmentViewHolder, position: int | java.jint | java.lang.Integer, /) -> None: ...
    def onCreateViewHolder(self, parent: android.view.ViewGroup, viewType: int | java.jint | java.lang.Integer, /) -> FragmentViewHolder: ...
    def onDetachedFromRecyclerView(self, recyclerView: androidx.recyclerview.widget.RecyclerView, /) -> None: ...
    def onFailedToRecycleView(self, holder: FragmentViewHolder, /) -> bool: ...
    def onViewAttachedToWindow(self, holder: FragmentViewHolder, /) -> None: ...
    def onViewRecycled(self, holder: FragmentViewHolder, /) -> None: ...
    def restoreState(self, savedState: android.os.Parcelable, /) -> None: ...
    def saveState(self) -> android.os.Parcelable: ...
    def setHasStableIds(self, hasStableIds: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class FragmentViewHolder(androidx.recyclerview.widget.RecyclerView.ViewHolder): ...

class StatefulAdapter(java.lang.Object):
    def restoreState(self, arg1: android.os.Parcelable, /) -> None: ...
    def saveState(self) -> android.os.Parcelable: ...
