import android.view
import java
import java.lang

class ZoomButtonsController(java.lang.Object):
    def __init__(self, view: android.view.View, /) -> None: ...
    def isVisible(self) -> bool: ...
    def onTouch(self, v: android.view.View, m: android.view.MotionEvent, /) -> bool: ...
    def setOnZoomListener(self, listener: ZoomButtonsController.OnZoomListener, /) -> None: ...
    def setVisible(self, visible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setZoomInEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setZoomOutEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

    class OnZoomListener(java.lang.Object):
        def onVisibilityChanged(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
        def onZoom(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
