import typing

import android.content
import android.graphics
import android.graphics.drawable
import android.os
import android.util
import android.view
import androidx
import androidx.customview.view
import java
import java.lang
import java.util

class DrawerLayout(android.view.ViewGroup):
    STATE_IDLE: typing.ClassVar[int] = ...
    STATE_DRAGGING: typing.ClassVar[int] = ...
    STATE_SETTLING: typing.ClassVar[int] = ...
    LOCK_MODE_UNLOCKED: typing.ClassVar[int] = ...
    LOCK_MODE_LOCKED_CLOSED: typing.ClassVar[int] = ...
    LOCK_MODE_LOCKED_OPEN: typing.ClassVar[int] = ...
    LOCK_MODE_UNDEFINED: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyle: int | java.jint | java.lang.Integer, /) -> None: ...
    def addDrawerListener(self, listener: DrawerLayout.DrawerListener, /) -> None: ...
    def addFocusables(self, views: java.util.ArrayList[android.view.View], direction: int | java.jint | java.lang.Integer, focusableMode: int | java.jint | java.lang.Integer, /) -> None: ...
    def addView(self, child: android.view.View, index: int | java.jint | java.lang.Integer, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    def checkLayoutParams(self, p: android.view.ViewGroup.LayoutParams, /) -> bool: ...
    @typing.overload
    def closeDrawer(self, gravity: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def closeDrawer(self, drawerView: android.view.View, /) -> None: ...
    @typing.overload
    def closeDrawer(self, gravity: int | java.jint | java.lang.Integer, animate: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def closeDrawer(self, drawerView: android.view.View, animate: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def closeDrawers(self) -> None: ...
    def computeScroll(self) -> None: ...
    def dispatchGenericMotionEvent(self, event: android.view.MotionEvent, /) -> bool: ...
    def drawChild(self, canvas: android.graphics.Canvas, child: android.view.View, drawingTime: int | java.jlong | java.lang.Long, /) -> bool: ...
    def generateDefaultLayoutParams(self) -> android.view.ViewGroup.LayoutParams: ...
    @typing.overload
    def generateLayoutParams(self, attrs: android.util.AttributeSet, /) -> android.view.ViewGroup.LayoutParams: ...
    @typing.overload
    def generateLayoutParams(self, p: android.view.ViewGroup.LayoutParams, /) -> android.view.ViewGroup.LayoutParams: ...
    def getDrawerElevation(self) -> float: ...
    @typing.overload
    def getDrawerLockMode(self, edgeGravity: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    def getDrawerLockMode(self, drawerView: android.view.View, /) -> int: ...
    def getDrawerTitle(self, edgeGravity: int | java.jint | java.lang.Integer, /) -> java.lang.CharSequence: ...
    def getStatusBarBackgroundDrawable(self) -> android.graphics.drawable.Drawable: ...
    @typing.overload
    def isDrawerOpen(self, drawerGravity: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def isDrawerOpen(self, drawer: android.view.View, /) -> bool: ...
    @typing.overload
    def isDrawerVisible(self, drawerGravity: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def isDrawerVisible(self, drawer: android.view.View, /) -> bool: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onDraw(self, c: android.graphics.Canvas, /) -> None: ...
    def onInterceptTouchEvent(self, ev: android.view.MotionEvent, /) -> bool: ...
    def onKeyDown(self, keyCode: int | java.jint | java.lang.Integer, event: android.view.KeyEvent, /) -> bool: ...
    def onKeyUp(self, keyCode: int | java.jint | java.lang.Integer, event: android.view.KeyEvent, /) -> bool: ...
    def onLayout(self, changed: bool | java.jboolean | java.lang.Boolean, l: int | java.jint | java.lang.Integer, t: int | java.jint | java.lang.Integer, r: int | java.jint | java.lang.Integer, b: int | java.jint | java.lang.Integer, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def onRestoreInstanceState(self, state: android.os.Parcelable, /) -> None: ...
    def onRtlPropertiesChanged(self, layoutDirection: int | java.jint | java.lang.Integer, /) -> None: ...
    def onSaveInstanceState(self) -> android.os.Parcelable: ...
    def onTouchEvent(self, ev: android.view.MotionEvent, /) -> bool: ...
    @typing.overload
    def openDrawer(self, gravity: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def openDrawer(self, drawerView: android.view.View, /) -> None: ...
    @typing.overload
    def openDrawer(self, gravity: int | java.jint | java.lang.Integer, animate: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def openDrawer(self, drawerView: android.view.View, animate: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def removeDrawerListener(self, listener: DrawerLayout.DrawerListener, /) -> None: ...
    def requestDisallowInterceptTouchEvent(self, disallowIntercept: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def requestLayout(self) -> None: ...
    def setChildInsets(self, insets: java.lang.Object | int | bool | float | str, draw: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDrawerElevation(self, elevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setDrawerListener(self, listener: DrawerLayout.DrawerListener, /) -> None: ...
    @typing.overload
    def setDrawerLockMode(self, lockMode: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setDrawerLockMode(self, lockMode: int | java.jint | java.lang.Integer, edgeGravity: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setDrawerLockMode(self, lockMode: int | java.jint | java.lang.Integer, drawerView: android.view.View, /) -> None: ...
    @typing.overload
    def setDrawerShadow(self, resId: int | java.jint | java.lang.Integer, gravity: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setDrawerShadow(self, shadowDrawable: android.graphics.drawable.Drawable, gravity: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDrawerTitle(self, edgeGravity: int | java.jint | java.lang.Integer, title: java.lang.CharSequence, /) -> None: ...
    def setScrimColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setStatusBarBackground(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setStatusBarBackground(self, bg: android.graphics.drawable.Drawable, /) -> None: ...
    def setStatusBarBackgroundColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...

    class LayoutParams(android.view.ViewGroup.MarginLayoutParams):
        gravity: int = ...
        @typing.overload
        def __init__(self, source: android.view.ViewGroup.LayoutParams, /) -> None: ...
        @typing.overload
        def __init__(self, source: android.view.ViewGroup.MarginLayoutParams, /) -> None: ...
        @typing.overload
        def __init__(self, source: DrawerLayout.LayoutParams, /) -> None: ...
        @typing.overload
        def __init__(self, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...
        @typing.overload
        def __init__(self, c: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
        @typing.overload
        def __init__(self, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, gravity: int | java.jint | java.lang.Integer, /) -> None: ...

    class SavedState(androidx.customview.view.AbsSavedState):
        CREATOR: typing.ClassVar[android.os.Parcelable.Creator[DrawerLayout.SavedState]] = ...
        @typing.overload
        def __init__(self, superState: android.os.Parcelable, /) -> None: ...
        @typing.overload
        def __init__(self, in_: android.os.Parcel, loader: java.lang.ClassLoader, /) -> None: ...
        def writeToParcel(self, dest: android.os.Parcel, flags: int | java.jint | java.lang.Integer, /) -> None: ...

    class SimpleDrawerListener(androidx.drawerlayout.widget.DrawerLayout.DrawerListener):
        def __init__(self) -> None: ...
        def onDrawerClosed(self, drawerView: android.view.View, /) -> None: ...
        def onDrawerOpened(self, drawerView: android.view.View, /) -> None: ...
        def onDrawerSlide(self, drawerView: android.view.View, slideOffset: float | java.jfloat | java.lang.Float, /) -> None: ...
        def onDrawerStateChanged(self, newState: int | java.jint | java.lang.Integer, /) -> None: ...

    class DrawerListener(java.lang.Object):
        def onDrawerClosed(self, arg1: android.view.View, /) -> None: ...
        def onDrawerOpened(self, arg1: android.view.View, /) -> None: ...
        def onDrawerSlide(self, arg1: android.view.View, arg2: float | java.jfloat | java.lang.Float, /) -> None: ...
        def onDrawerStateChanged(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
