import typing

import android.app
import android.content
import android.content.pm
import android.content.res
import android.database
import android.graphics.drawable
import android.net
import android.os
import androidx.concurrent.futures
import androidx.core.app.unusedapprestrictions
import androidx.core.os
import androidx.core.util
import com.google.common.util.concurrent
import java
import java.chaquopy
import java.io
import java.lang
import java.lang.annotation
import java.util.concurrent

class ContentProviderCompat(java.lang.Object):
    @staticmethod
    def requireContext(provider: android.content.ContentProvider, /) -> android.content.Context: ...

class ContentResolverCompat(java.lang.Object):
    @staticmethod
    def query(resolver: android.content.ContentResolver, uri: android.net.Uri, projection: java.chaquopy.JavaArray[java.lang.String], selection: str | java.lang.String, selectionArgs: java.chaquopy.JavaArray[java.lang.String], sortOrder: str | java.lang.String, cancellationSignal: androidx.core.os.CancellationSignal, /) -> android.database.Cursor: ...

class ContextCompat(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def checkSelfPermission(context: android.content.Context, permission: str | java.lang.String, /) -> int: ...
    @staticmethod
    def createDeviceProtectedStorageContext(context: android.content.Context, /) -> android.content.Context: ...
    @staticmethod
    def getAttributionTag(context: android.content.Context, /) -> str: ...
    @staticmethod
    def getCodeCacheDir(context: android.content.Context, /) -> java.io.File: ...
    @staticmethod
    def getColor(context: android.content.Context, id: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def getColorStateList(context: android.content.Context, id: int | java.jint | java.lang.Integer, /) -> android.content.res.ColorStateList: ...
    @staticmethod
    def getDataDir(context: android.content.Context, /) -> java.io.File: ...
    @staticmethod
    def getDrawable(context: android.content.Context, id: int | java.jint | java.lang.Integer, /) -> android.graphics.drawable.Drawable: ...
    @staticmethod
    def getExternalCacheDirs(context: android.content.Context, /) -> java.chaquopy.JavaArray[java.io.File]: ...
    @staticmethod
    def getExternalFilesDirs(context: android.content.Context, type: str | java.lang.String, /) -> java.chaquopy.JavaArray[java.io.File]: ...
    @staticmethod
    def getMainExecutor(context: android.content.Context, /) -> java.util.concurrent.Executor: ...
    @staticmethod
    def getNoBackupFilesDir(context: android.content.Context, /) -> java.io.File: ...
    @staticmethod
    def getObbDirs(context: android.content.Context, /) -> java.chaquopy.JavaArray[java.io.File]: ...
    _getSystemService__T = typing.TypeVar('_getSystemService__T')  # <T>
    @staticmethod
    def getSystemService(context: android.content.Context, serviceClass: typing.Type[_getSystemService__T], /) -> _getSystemService__T: ...
    @staticmethod
    def getSystemServiceName(context: android.content.Context, serviceClass: typing.Type[java.lang.Object], /) -> str: ...
    @staticmethod
    def isDeviceProtectedStorage(context: android.content.Context, /) -> bool: ...
    @typing.overload
    @staticmethod
    def startActivities(context: android.content.Context, intents: java.chaquopy.JavaArray[android.content.Intent], /) -> bool: ...
    @typing.overload
    @staticmethod
    def startActivities(context: android.content.Context, intents: java.chaquopy.JavaArray[android.content.Intent], options: android.os.Bundle, /) -> bool: ...
    @staticmethod
    def startActivity(context: android.content.Context, intent: android.content.Intent, options: android.os.Bundle, /) -> None: ...
    @staticmethod
    def startForegroundService(context: android.content.Context, intent: android.content.Intent, /) -> None: ...

class FileProvider(android.content.ContentProvider):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, resourceId: int | java.jint | java.lang.Integer, /) -> None: ...
    def attachInfo(self, context: android.content.Context, info: android.content.pm.ProviderInfo, /) -> None: ...
    def delete(self, uri: android.net.Uri, selection: str | java.lang.String, selectionArgs: java.chaquopy.JavaArray[java.lang.String], /) -> int: ...
    def getType(self, uri: android.net.Uri, /) -> str: ...
    @typing.overload
    @staticmethod
    def getUriForFile(context: android.content.Context, authority: str | java.lang.String, file: java.io.File, /) -> android.net.Uri: ...
    @typing.overload
    @staticmethod
    def getUriForFile(context: android.content.Context, authority: str | java.lang.String, file: java.io.File, displayName: str | java.lang.String, /) -> android.net.Uri: ...
    def insert(self, uri: android.net.Uri, values: android.content.ContentValues, /) -> android.net.Uri: ...
    def onCreate(self) -> bool: ...
    def openFile(self, uri: android.net.Uri, mode: str | java.lang.String, /) -> android.os.ParcelFileDescriptor: ...
    def query(self, uri: android.net.Uri, projection: java.chaquopy.JavaArray[java.lang.String], selection: str | java.lang.String, selectionArgs: java.chaquopy.JavaArray[java.lang.String], sortOrder: str | java.lang.String, /) -> android.database.Cursor: ...
    def update(self, uri: android.net.Uri, values: android.content.ContentValues, selection: str | java.lang.String, selectionArgs: java.chaquopy.JavaArray[java.lang.String], /) -> int: ...

class IntentCompat(java.lang.Object):
    ACTION_CREATE_REMINDER: typing.ClassVar[str] = ...
    EXTRA_HTML_TEXT: typing.ClassVar[str] = ...
    EXTRA_START_PLAYBACK: typing.ClassVar[str] = ...
    EXTRA_TIME: typing.ClassVar[str] = ...
    CATEGORY_LEANBACK_LAUNCHER: typing.ClassVar[str] = ...
    @staticmethod
    def createManageUnusedAppRestrictionsIntent(context: android.content.Context, packageName: str | java.lang.String, /) -> android.content.Intent: ...
    @staticmethod
    def makeMainSelectorActivity(selectorAction: str | java.lang.String, selectorCategory: str | java.lang.String, /) -> android.content.Intent: ...

class LocusIdCompat(java.lang.Object):
    def __init__(self, id: str | java.lang.String, /) -> None: ...
    def equals(self, obj: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getId(self) -> str: ...
    def hashCode(self) -> int: ...
    def toLocusId(self) -> android.content.LocusId: ...
    @staticmethod
    def toLocusIdCompat(locusId: android.content.LocusId, /) -> LocusIdCompat: ...
    def toString(self) -> str: ...

class MimeTypeFilter(java.lang.Object):
    @typing.overload
    @staticmethod
    def matches(mimeType: str | java.lang.String, filter: str | java.lang.String, /) -> bool: ...
    @typing.overload
    @staticmethod
    def matches(mimeType: str | java.lang.String, filters: java.chaquopy.JavaArray[java.lang.String], /) -> str: ...
    @typing.overload
    @staticmethod
    def matches(mimeTypes: java.chaquopy.JavaArray[java.lang.String], filter: str | java.lang.String, /) -> str: ...
    @staticmethod
    def matchesMany(mimeTypes: java.chaquopy.JavaArray[java.lang.String], filter: str | java.lang.String, /) -> java.chaquopy.JavaArray[java.lang.String]: ...

class OnConfigurationChangedProvider(java.lang.Object):
    def addOnConfigurationChangedListener(self, arg1: androidx.core.util.Consumer[android.content.res.Configuration], /) -> None: ...
    def removeOnConfigurationChangedListener(self, arg1: androidx.core.util.Consumer[android.content.res.Configuration], /) -> None: ...

class OnTrimMemoryProvider(java.lang.Object):
    def addOnTrimMemoryListener(self, arg1: androidx.core.util.Consumer[java.lang.Integer], /) -> None: ...
    def removeOnTrimMemoryListener(self, arg1: androidx.core.util.Consumer[java.lang.Integer], /) -> None: ...

class PackageManagerCompat(java.lang.Object):
    LOG_TAG: typing.ClassVar[str] = ...
    ACTION_PERMISSION_REVOCATION_SETTINGS: typing.ClassVar[str] = ...
    @staticmethod
    def areUnusedAppRestrictionsAvailable(packageManager: android.content.pm.PackageManager, /) -> bool: ...
    @staticmethod
    def getPermissionRevocationVerifierApp(packageManager: android.content.pm.PackageManager, /) -> str: ...
    @staticmethod
    def getUnusedAppRestrictionsStatus(context: android.content.Context, /) -> com.google.common.util.concurrent.ListenableFuture[java.lang.Integer]: ...

    class UnusedAppRestrictionsStatus(java.lang.annotation.Annotation): ...

class PermissionChecker(java.lang.Object):
    PERMISSION_GRANTED: typing.ClassVar[int] = ...
    PERMISSION_DENIED: typing.ClassVar[int] = ...
    PERMISSION_DENIED_APP_OP: typing.ClassVar[int] = ...
    @staticmethod
    def checkCallingOrSelfPermission(context: android.content.Context, permission: str | java.lang.String, /) -> int: ...
    @staticmethod
    def checkCallingPermission(context: android.content.Context, permission: str | java.lang.String, packageName: str | java.lang.String, /) -> int: ...
    @staticmethod
    def checkPermission(context: android.content.Context, permission: str | java.lang.String, pid: int | java.jint | java.lang.Integer, uid: int | java.jint | java.lang.Integer, packageName: str | java.lang.String, /) -> int: ...
    @staticmethod
    def checkSelfPermission(context: android.content.Context, permission: str | java.lang.String, /) -> int: ...

    class PermissionResult(java.lang.annotation.Annotation): ...

class SharedPreferencesCompat(java.lang.Object):

    class EditorCompat(java.lang.Object):
        def apply(self, editor: android.content.SharedPreferences.Editor, /) -> None: ...
        @staticmethod
        def getInstance() -> SharedPreferencesCompat.EditorCompat: ...

class UnusedAppRestrictionsBackportCallback(java.lang.Object):
    def __init__(self, callback: androidx.core.app.unusedapprestrictions.IUnusedAppRestrictionsBackportCallback, /) -> None: ...
    def onResult(self, success: bool | java.jboolean | java.lang.Boolean, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class UnusedAppRestrictionsBackportService(android.app.Service):
    ACTION_UNUSED_APP_RESTRICTIONS_BACKPORT_CONNECTION: typing.ClassVar[str] = ...
    def __init__(self) -> None: ...
    def isPermissionRevocationEnabled(self, arg1: UnusedAppRestrictionsBackportCallback, /) -> None: ...
    def onBind(self, intent: android.content.Intent, /) -> android.os.IBinder: ...

class UnusedAppRestrictionsBackportServiceConnection(android.content.ServiceConnection):
    def connectAndFetchResult(self, resultFuture: androidx.concurrent.futures.ResolvableFuture[java.lang.Integer], /) -> None: ...
    def disconnectFromService(self) -> None: ...
    def onServiceConnected(self, name: android.content.ComponentName, service: android.os.IBinder, /) -> None: ...
    def onServiceDisconnected(self, name: android.content.ComponentName, /) -> None: ...

class UnusedAppRestrictionsConstants(java.lang.Object):
    ERROR: typing.ClassVar[int] = ...
    FEATURE_NOT_AVAILABLE: typing.ClassVar[int] = ...
    DISABLED: typing.ClassVar[int] = ...
    API_30_BACKPORT: typing.ClassVar[int] = ...
    API_30: typing.ClassVar[int] = ...
    API_31: typing.ClassVar[int] = ...
