import typing

import java
import java.chaquopy
import java.io
import java.lang
import java.util
import javax.xml.parsers
import javax.xml.transform
import jet
import kotlin.support
import org.w3c.dom
import org.w3c.dom.events
import org.xml.sax

class CloseableEventListener(jet.JetObject, java.io.Closeable):
    def __init__(self, target: org.w3c.dom.events.EventTarget, listener: org.w3c.dom.events.EventListener, name: str | java.lang.String, capture: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def close(self) -> None: ...
    def getCapture(self) -> bool: ...
    def getListener(self) -> org.w3c.dom.events.EventListener: ...
    def getName(self) -> str: ...
    def getTarget(self) -> org.w3c.dom.events.EventTarget: ...

class DomPackage-Dom-f7f4e75a(java.lang.Object):
    @typing.overload
    @staticmethod
    def addElement(receiver: org.w3c.dom.Document, name: str | java.lang.String, init: jet.ExtensionFunction0[org.w3c.dom.Element, jet.Unit], /) -> org.w3c.dom.Element: ...
    @typing.overload
    @staticmethod
    def addElement(receiver: org.w3c.dom.Element, name: str | java.lang.String, doc: org.w3c.dom.Document, init: jet.ExtensionFunction0[org.w3c.dom.Element, jet.Unit], /) -> org.w3c.dom.Element: ...
    @staticmethod
    def addText(receiver: org.w3c.dom.Element, text: str | java.lang.String, doc: org.w3c.dom.Document, /) -> org.w3c.dom.Element: ...
    @staticmethod
    def attribute(receiver: org.w3c.dom.Element, name: str | java.lang.String, /) -> str: ...
    @typing.overload
    @staticmethod
    def childElements(receiver: org.w3c.dom.Element, /) -> java.util.List[org.w3c.dom.Element]: ...
    @typing.overload
    @staticmethod
    def childElements(receiver: org.w3c.dom.Element, name: str | java.lang.String, /) -> java.util.List[org.w3c.dom.Element]: ...
    @staticmethod
    def children(receiver: org.w3c.dom.Element, /) -> java.util.List[org.w3c.dom.Node]: ...
    @staticmethod
    def clear(receiver: org.w3c.dom.Node, /) -> None: ...
    @typing.overload
    @staticmethod
    def createElement(receiver: org.w3c.dom.Document, name: str | java.lang.String, init: jet.ExtensionFunction0[org.w3c.dom.Element, jet.Unit], /) -> org.w3c.dom.Element: ...
    @typing.overload
    @staticmethod
    def createElement(receiver: org.w3c.dom.Element, name: str | java.lang.String, doc: org.w3c.dom.Document, init: jet.ExtensionFunction0[org.w3c.dom.Element, jet.Unit], /) -> org.w3c.dom.Element: ...
    @typing.overload
    @staticmethod
    def elements(receiver: org.w3c.dom.Document, localName: str | java.lang.String, /) -> java.util.List[org.w3c.dom.Element]: ...
    @typing.overload
    @staticmethod
    def elements(receiver: org.w3c.dom.Element, localName: str | java.lang.String, /) -> java.util.List[org.w3c.dom.Element]: ...
    @typing.overload
    @staticmethod
    def elements(receiver: org.w3c.dom.Document, namespaceUri: str | java.lang.String, localName: str | java.lang.String, /) -> java.util.List[org.w3c.dom.Element]: ...
    @typing.overload
    @staticmethod
    def elements(receiver: org.w3c.dom.Element, namespaceUri: str | java.lang.String, localName: str | java.lang.String, /) -> java.util.List[org.w3c.dom.Element]: ...
    @staticmethod
    def emptyElementList() -> java.util.List[org.w3c.dom.Element]: ...
    @staticmethod
    def emptyNodeList() -> java.util.List[org.w3c.dom.Node]: ...
    @typing.overload
    @staticmethod
    def get(receiver: org.w3c.dom.Document, selector: str | java.lang.String, /) -> java.util.List[org.w3c.dom.Element]: ...
    @typing.overload
    @staticmethod
    def get(receiver: org.w3c.dom.Element, selector: str | java.lang.String, /) -> java.util.List[org.w3c.dom.Element]: ...
    @staticmethod
    def getChildrenText(receiver: org.w3c.dom.Element, /) -> str: ...
    @staticmethod
    def getClasses(receiver: org.w3c.dom.Element, /) -> str: ...
    @typing.overload
    @staticmethod
    def getElements(receiver: org.w3c.dom.Document, /) -> java.util.List[org.w3c.dom.Element]: ...
    @typing.overload
    @staticmethod
    def getElements(receiver: org.w3c.dom.Element, /) -> java.util.List[org.w3c.dom.Element]: ...
    @staticmethod
    def getFirst(receiver: org.w3c.dom.NodeList, /) -> org.w3c.dom.Node: ...
    @staticmethod
    def getHead(receiver: org.w3c.dom.NodeList, /) -> org.w3c.dom.Node: ...
    @staticmethod
    def getId(receiver: org.w3c.dom.Element, /) -> str: ...
    @staticmethod
    def getLast(receiver: org.w3c.dom.NodeList, /) -> org.w3c.dom.Node: ...
    @staticmethod
    def getStyle(receiver: org.w3c.dom.Element, /) -> str: ...
    @staticmethod
    def getTail(receiver: org.w3c.dom.NodeList, /) -> org.w3c.dom.Node: ...
    @staticmethod
    def getText(receiver: org.w3c.dom.Node, /) -> str: ...
    @staticmethod
    def hasClass(receiver: org.w3c.dom.Element, cssClass: str | java.lang.String, /) -> bool: ...
    @staticmethod
    def isText(receiver: org.w3c.dom.Node, /) -> bool: ...
    @staticmethod
    def nextSiblings(receiver: org.w3c.dom.Node, /) -> java.util.Iterator[org.w3c.dom.Node]: ...
    @staticmethod
    def nodesToXmlString(nodes: java.lang.Iterable[org.w3c.dom.Node], xmlDeclaration: bool | java.jboolean | java.lang.Boolean, /) -> str: ...
    @staticmethod
    def ownerDocument(receiver: org.w3c.dom.Node, doc: org.w3c.dom.Document, /) -> org.w3c.dom.Document: ...
    @typing.overload
    @staticmethod
    def plus(receiver: org.w3c.dom.Element, text: str | java.lang.String, /) -> org.w3c.dom.Element: ...
    @typing.overload
    @staticmethod
    def plus(receiver: org.w3c.dom.Node, child: org.w3c.dom.Node, /) -> org.w3c.dom.Node: ...
    @staticmethod
    def plusAssign(receiver: org.w3c.dom.Element, text: str | java.lang.String, /) -> org.w3c.dom.Element: ...
    @staticmethod
    def previousSiblings(receiver: org.w3c.dom.Node, /) -> java.util.Iterator[org.w3c.dom.Node]: ...
    @staticmethod
    def setChildrenText(receiver: org.w3c.dom.Element, value: str | java.lang.String, /) -> None: ...
    @staticmethod
    def setClasses(receiver: org.w3c.dom.Element, value: str | java.lang.String, /) -> None: ...
    @staticmethod
    def setId(receiver: org.w3c.dom.Element, value: str | java.lang.String, /) -> None: ...
    @staticmethod
    def setStyle(receiver: org.w3c.dom.Element, value: str | java.lang.String, /) -> None: ...
    @staticmethod
    def setText(receiver: org.w3c.dom.Node, value: str | java.lang.String, /) -> None: ...
    @staticmethod
    def toElementList(receiver: org.w3c.dom.NodeList, /) -> java.util.List[org.w3c.dom.Element]: ...
    @staticmethod
    def toList(receiver: org.w3c.dom.NodeList, /) -> java.util.List[org.w3c.dom.Node]: ...
    @staticmethod
    def toXmlString(receiver: org.w3c.dom.NodeList, xmlDeclaration: bool | java.jboolean | java.lang.Boolean, /) -> str: ...

class DomPackage-DomEvents-fafea541(java.lang.Object):
    @staticmethod
    def eventHandler(handler: jet.Function1[org.w3c.dom.events.Event, jet.Unit], /) -> org.w3c.dom.events.EventListener: ...
    @staticmethod
    def mouseEventHandler(handler: jet.Function1[org.w3c.dom.events.MouseEvent, jet.Unit], /) -> org.w3c.dom.events.EventListener: ...
    @typing.overload
    @staticmethod
    def on(receiver: org.w3c.dom.Node, name: str | java.lang.String, capture: bool | java.jboolean | java.lang.Boolean, handler: jet.Function1[org.w3c.dom.events.Event, jet.Unit], /) -> java.io.Closeable: ...
    @typing.overload
    @staticmethod
    def on(receiver: org.w3c.dom.Node, name: str | java.lang.String, capture: bool | java.jboolean | java.lang.Boolean, listener: org.w3c.dom.events.EventListener, /) -> java.io.Closeable: ...
    @staticmethod
    def onClick(receiver: org.w3c.dom.Node, capture: bool | java.jboolean | java.lang.Boolean, handler: jet.Function1[org.w3c.dom.events.MouseEvent, jet.Unit], /) -> java.io.Closeable: ...
    @staticmethod
    def onDoubleClick(receiver: org.w3c.dom.Node, capture: bool | java.jboolean | java.lang.Boolean, handler: jet.Function1[org.w3c.dom.events.MouseEvent, jet.Unit], /) -> java.io.Closeable: ...

class DomPackage-DomEventsJVM-b5ef8a8c(java.lang.Object):
    @staticmethod
    def getAltKey(receiver: org.w3c.dom.events.MouseEvent, /) -> bool: ...
    @staticmethod
    def getBubbles(receiver: org.w3c.dom.events.Event, /) -> bool: ...
    @staticmethod
    def getButton(receiver: org.w3c.dom.events.MouseEvent, /) -> int: ...
    @staticmethod
    def getCancelable(receiver: org.w3c.dom.events.Event, /) -> bool: ...
    @staticmethod
    def getClientX(receiver: org.w3c.dom.events.MouseEvent, /) -> int: ...
    @staticmethod
    def getClientY(receiver: org.w3c.dom.events.MouseEvent, /) -> int: ...
    @staticmethod
    def getCtrlKey(receiver: org.w3c.dom.events.MouseEvent, /) -> bool: ...
    @staticmethod
    def getEventPhase(receiver: org.w3c.dom.events.Event, /) -> int: ...
    @staticmethod
    def getEventType(receiver: org.w3c.dom.events.Event, /) -> str: ...
    @staticmethod
    def getGetCurrentTarget(receiver: org.w3c.dom.events.Event, /) -> org.w3c.dom.events.EventTarget: ...
    @staticmethod
    def getMetaKey(receiver: org.w3c.dom.events.MouseEvent, /) -> bool: ...
    @staticmethod
    def getRelatedTarget(receiver: org.w3c.dom.events.MouseEvent, /) -> org.w3c.dom.events.EventTarget: ...
    @staticmethod
    def getScreenX(receiver: org.w3c.dom.events.MouseEvent, /) -> int: ...
    @staticmethod
    def getScreenY(receiver: org.w3c.dom.events.MouseEvent, /) -> int: ...
    @staticmethod
    def getShiftKey(receiver: org.w3c.dom.events.MouseEvent, /) -> bool: ...
    @staticmethod
    def getTarget(receiver: org.w3c.dom.events.Event, /) -> org.w3c.dom.events.EventTarget: ...
    @staticmethod
    def getTimeStamp(receiver: org.w3c.dom.events.Event, /) -> int: ...

class DomPackage-DomJVM-2b4565d3(java.lang.Object):
    @staticmethod
    def addClass(receiver: org.w3c.dom.Element, cssClass: str | java.lang.String, /) -> bool: ...
    @typing.overload
    @staticmethod
    def createDocument(builder: javax.xml.parsers.DocumentBuilder, /) -> org.w3c.dom.Document: ...
    @typing.overload
    @staticmethod
    def createDocument(builderFactory: javax.xml.parsers.DocumentBuilderFactory, /) -> org.w3c.dom.Document: ...
    @staticmethod
    def createTransformer(source: javax.xml.transform.Source, factory: javax.xml.transform.TransformerFactory, /) -> javax.xml.transform.Transformer: ...
    @staticmethod
    def defaultDocumentBuilder(builderFactory: javax.xml.parsers.DocumentBuilderFactory, /) -> javax.xml.parsers.DocumentBuilder: ...
    @staticmethod
    def defaultDocumentBuilderFactory() -> javax.xml.parsers.DocumentBuilderFactory: ...
    @staticmethod
    def getAttributes(receiver: org.w3c.dom.Node, /) -> org.w3c.dom.NamedNodeMap: ...
    @staticmethod
    def getBaseURI(receiver: org.w3c.dom.Node, /) -> str: ...
    @staticmethod
    def getChildNodes(receiver: org.w3c.dom.Node, /) -> org.w3c.dom.NodeList: ...
    @staticmethod
    def getClassSet(receiver: org.w3c.dom.Element, /) -> java.util.Set[java.lang.String]: ...
    @staticmethod
    def getDocumentElement(receiver: org.w3c.dom.Document, /) -> org.w3c.dom.Element: ...
    @staticmethod
    def getFirstChild(receiver: org.w3c.dom.Node, /) -> org.w3c.dom.Node: ...
    @staticmethod
    def getInnerHTML(receiver: org.w3c.dom.Node, /) -> str: ...
    @staticmethod
    def getLastChild(receiver: org.w3c.dom.Node, /) -> org.w3c.dom.Node: ...
    @typing.overload
    @staticmethod
    def getLength(receiver: org.w3c.dom.CharacterData, /) -> int: ...
    @typing.overload
    @staticmethod
    def getLength(receiver: org.w3c.dom.DOMImplementationList, /) -> int: ...
    @typing.overload
    @staticmethod
    def getLength(receiver: org.w3c.dom.DOMStringList, /) -> int: ...
    @typing.overload
    @staticmethod
    def getLength(receiver: org.w3c.dom.NameList, /) -> int: ...
    @typing.overload
    @staticmethod
    def getLength(receiver: org.w3c.dom.NamedNodeMap, /) -> int: ...
    @typing.overload
    @staticmethod
    def getLength(receiver: org.w3c.dom.NodeList, /) -> int: ...
    @staticmethod
    def getLocalName(receiver: org.w3c.dom.Node, /) -> str: ...
    @staticmethod
    def getNamespaceURI(receiver: org.w3c.dom.Node, /) -> str: ...
    @staticmethod
    def getNextSibling(receiver: org.w3c.dom.Node, /) -> org.w3c.dom.Node: ...
    @staticmethod
    def getNodeName(receiver: org.w3c.dom.Node, /) -> str: ...
    @staticmethod
    def getNodeType(receiver: org.w3c.dom.Node, /) -> int: ...
    @staticmethod
    def getNodeValue(receiver: org.w3c.dom.Node, /) -> str: ...
    @typing.overload
    @staticmethod
    def getOuterHTML(receiver: org.w3c.dom.Node, /) -> str: ...
    @typing.overload
    @staticmethod
    def getOuterHTML(receiver: org.w3c.dom.NodeList, /) -> str: ...
    @staticmethod
    def getOwnerDocument(receiver: org.w3c.dom.Node, /) -> org.w3c.dom.Document: ...
    @staticmethod
    def getParentNode(receiver: org.w3c.dom.Node, /) -> org.w3c.dom.Node: ...
    @staticmethod
    def getPrefix(receiver: org.w3c.dom.Node, /) -> str: ...
    @staticmethod
    def getPreviousSibling(receiver: org.w3c.dom.Node, /) -> org.w3c.dom.Node: ...
    @staticmethod
    def getTextContent(receiver: org.w3c.dom.Node, /) -> str: ...
    @staticmethod
    def nextElements(receiver: org.w3c.dom.Node, /) -> java.util.Iterator[org.w3c.dom.Element]: ...
    @typing.overload
    @staticmethod
    def parseXml(file: java.io.File, builder: javax.xml.parsers.DocumentBuilder, /) -> org.w3c.dom.Document: ...
    @typing.overload
    @staticmethod
    def parseXml(inputStream: java.io.InputStream, builder: javax.xml.parsers.DocumentBuilder, /) -> org.w3c.dom.Document: ...
    @typing.overload
    @staticmethod
    def parseXml(uri: str | java.lang.String, builder: javax.xml.parsers.DocumentBuilder, /) -> org.w3c.dom.Document: ...
    @typing.overload
    @staticmethod
    def parseXml(inputSource: org.xml.sax.InputSource, builder: javax.xml.parsers.DocumentBuilder, /) -> org.w3c.dom.Document: ...
    @staticmethod
    def previousElements(receiver: org.w3c.dom.Node, /) -> java.util.Iterator[org.w3c.dom.Element]: ...
    @staticmethod
    def removeClass(receiver: org.w3c.dom.Element, cssClass: str | java.lang.String, /) -> bool: ...
    @staticmethod
    def setClassSet(receiver: org.w3c.dom.Element, value: java.util.Set[java.lang.String], /) -> None: ...
    @staticmethod
    def setTextContent(receiver: org.w3c.dom.Node, value: str | java.lang.String, /) -> None: ...
    @typing.overload
    @staticmethod
    def toXmlString(receiver: org.w3c.dom.Node, /) -> str: ...
    @typing.overload
    @staticmethod
    def toXmlString(receiver: org.w3c.dom.Node, xmlDeclaration: bool | java.jboolean | java.lang.Boolean, /) -> str: ...
    @staticmethod
    def writeXmlString(receiver: org.w3c.dom.Node, writer: java.io.Writer, xmlDeclaration: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class DomPackage(java.lang.Object):
    @staticmethod
    def addClass(receiver: org.w3c.dom.Element, cssClass: str | java.lang.String, /) -> bool: ...
    @typing.overload
    @staticmethod
    def addElement(receiver: org.w3c.dom.Document, name: str | java.lang.String, init: jet.ExtensionFunction0[org.w3c.dom.Element, jet.Unit], /) -> org.w3c.dom.Element: ...
    @typing.overload
    @staticmethod
    def addElement(receiver: org.w3c.dom.Element, name: str | java.lang.String, doc: org.w3c.dom.Document, init: jet.ExtensionFunction0[org.w3c.dom.Element, jet.Unit], /) -> org.w3c.dom.Element: ...
    @staticmethod
    def addText(receiver: org.w3c.dom.Element, text: str | java.lang.String, doc: org.w3c.dom.Document, /) -> org.w3c.dom.Element: ...
    @staticmethod
    def attribute(receiver: org.w3c.dom.Element, name: str | java.lang.String, /) -> str: ...
    @typing.overload
    @staticmethod
    def childElements(receiver: org.w3c.dom.Element, /) -> java.util.List[org.w3c.dom.Element]: ...
    @typing.overload
    @staticmethod
    def childElements(receiver: org.w3c.dom.Element, name: str | java.lang.String, /) -> java.util.List[org.w3c.dom.Element]: ...
    @staticmethod
    def children(receiver: org.w3c.dom.Element, /) -> java.util.List[org.w3c.dom.Node]: ...
    @staticmethod
    def clear(receiver: org.w3c.dom.Node, /) -> None: ...
    @typing.overload
    @staticmethod
    def createDocument(builder: javax.xml.parsers.DocumentBuilder, /) -> org.w3c.dom.Document: ...
    @typing.overload
    @staticmethod
    def createDocument(builderFactory: javax.xml.parsers.DocumentBuilderFactory, /) -> org.w3c.dom.Document: ...
    @typing.overload
    @staticmethod
    def createElement(receiver: org.w3c.dom.Document, name: str | java.lang.String, init: jet.ExtensionFunction0[org.w3c.dom.Element, jet.Unit], /) -> org.w3c.dom.Element: ...
    @typing.overload
    @staticmethod
    def createElement(receiver: org.w3c.dom.Element, name: str | java.lang.String, doc: org.w3c.dom.Document, init: jet.ExtensionFunction0[org.w3c.dom.Element, jet.Unit], /) -> org.w3c.dom.Element: ...
    @staticmethod
    def createTransformer(source: javax.xml.transform.Source, factory: javax.xml.transform.TransformerFactory, /) -> javax.xml.transform.Transformer: ...
    @staticmethod
    def defaultDocumentBuilder(builderFactory: javax.xml.parsers.DocumentBuilderFactory, /) -> javax.xml.parsers.DocumentBuilder: ...
    @staticmethod
    def defaultDocumentBuilderFactory() -> javax.xml.parsers.DocumentBuilderFactory: ...
    @typing.overload
    @staticmethod
    def elements(receiver: org.w3c.dom.Document, localName: str | java.lang.String, /) -> java.util.List[org.w3c.dom.Element]: ...
    @typing.overload
    @staticmethod
    def elements(receiver: org.w3c.dom.Element, localName: str | java.lang.String, /) -> java.util.List[org.w3c.dom.Element]: ...
    @typing.overload
    @staticmethod
    def elements(receiver: org.w3c.dom.Document, namespaceUri: str | java.lang.String, localName: str | java.lang.String, /) -> java.util.List[org.w3c.dom.Element]: ...
    @typing.overload
    @staticmethod
    def elements(receiver: org.w3c.dom.Element, namespaceUri: str | java.lang.String, localName: str | java.lang.String, /) -> java.util.List[org.w3c.dom.Element]: ...
    @staticmethod
    def emptyElementList() -> java.util.List[org.w3c.dom.Element]: ...
    @staticmethod
    def emptyNodeList() -> java.util.List[org.w3c.dom.Node]: ...
    @staticmethod
    def eventHandler(handler: jet.Function1[org.w3c.dom.events.Event, jet.Unit], /) -> org.w3c.dom.events.EventListener: ...
    @typing.overload
    @staticmethod
    def get(receiver: org.w3c.dom.Document, selector: str | java.lang.String, /) -> java.util.List[org.w3c.dom.Element]: ...
    @typing.overload
    @staticmethod
    def get(receiver: org.w3c.dom.Element, selector: str | java.lang.String, /) -> java.util.List[org.w3c.dom.Element]: ...
    @staticmethod
    def getAltKey(receiver: org.w3c.dom.events.MouseEvent, /) -> bool: ...
    @staticmethod
    def getAttributes(receiver: org.w3c.dom.Node, /) -> org.w3c.dom.NamedNodeMap: ...
    @staticmethod
    def getBaseURI(receiver: org.w3c.dom.Node, /) -> str: ...
    @staticmethod
    def getBubbles(receiver: org.w3c.dom.events.Event, /) -> bool: ...
    @staticmethod
    def getButton(receiver: org.w3c.dom.events.MouseEvent, /) -> int: ...
    @staticmethod
    def getCancelable(receiver: org.w3c.dom.events.Event, /) -> bool: ...
    @staticmethod
    def getChildNodes(receiver: org.w3c.dom.Node, /) -> org.w3c.dom.NodeList: ...
    @staticmethod
    def getChildrenText(receiver: org.w3c.dom.Element, /) -> str: ...
    @staticmethod
    def getClassSet(receiver: org.w3c.dom.Element, /) -> java.util.Set[java.lang.String]: ...
    @staticmethod
    def getClasses(receiver: org.w3c.dom.Element, /) -> str: ...
    @staticmethod
    def getClientX(receiver: org.w3c.dom.events.MouseEvent, /) -> int: ...
    @staticmethod
    def getClientY(receiver: org.w3c.dom.events.MouseEvent, /) -> int: ...
    @staticmethod
    def getCtrlKey(receiver: org.w3c.dom.events.MouseEvent, /) -> bool: ...
    @staticmethod
    def getDocumentElement(receiver: org.w3c.dom.Document, /) -> org.w3c.dom.Element: ...
    @typing.overload
    @staticmethod
    def getElements(receiver: org.w3c.dom.Document, /) -> java.util.List[org.w3c.dom.Element]: ...
    @typing.overload
    @staticmethod
    def getElements(receiver: org.w3c.dom.Element, /) -> java.util.List[org.w3c.dom.Element]: ...
    @staticmethod
    def getEventPhase(receiver: org.w3c.dom.events.Event, /) -> int: ...
    @staticmethod
    def getEventType(receiver: org.w3c.dom.events.Event, /) -> str: ...
    @staticmethod
    def getFirst(receiver: org.w3c.dom.NodeList, /) -> org.w3c.dom.Node: ...
    @staticmethod
    def getFirstChild(receiver: org.w3c.dom.Node, /) -> org.w3c.dom.Node: ...
    @staticmethod
    def getGetCurrentTarget(receiver: org.w3c.dom.events.Event, /) -> org.w3c.dom.events.EventTarget: ...
    @staticmethod
    def getHead(receiver: org.w3c.dom.NodeList, /) -> org.w3c.dom.Node: ...
    @staticmethod
    def getId(receiver: org.w3c.dom.Element, /) -> str: ...
    @staticmethod
    def getInnerHTML(receiver: org.w3c.dom.Node, /) -> str: ...
    @staticmethod
    def getLast(receiver: org.w3c.dom.NodeList, /) -> org.w3c.dom.Node: ...
    @staticmethod
    def getLastChild(receiver: org.w3c.dom.Node, /) -> org.w3c.dom.Node: ...
    @typing.overload
    @staticmethod
    def getLength(receiver: org.w3c.dom.CharacterData, /) -> int: ...
    @typing.overload
    @staticmethod
    def getLength(receiver: org.w3c.dom.DOMImplementationList, /) -> int: ...
    @typing.overload
    @staticmethod
    def getLength(receiver: org.w3c.dom.DOMStringList, /) -> int: ...
    @typing.overload
    @staticmethod
    def getLength(receiver: org.w3c.dom.NameList, /) -> int: ...
    @typing.overload
    @staticmethod
    def getLength(receiver: org.w3c.dom.NamedNodeMap, /) -> int: ...
    @typing.overload
    @staticmethod
    def getLength(receiver: org.w3c.dom.NodeList, /) -> int: ...
    @staticmethod
    def getLocalName(receiver: org.w3c.dom.Node, /) -> str: ...
    @staticmethod
    def getMetaKey(receiver: org.w3c.dom.events.MouseEvent, /) -> bool: ...
    @staticmethod
    def getNamespaceURI(receiver: org.w3c.dom.Node, /) -> str: ...
    @staticmethod
    def getNextSibling(receiver: org.w3c.dom.Node, /) -> org.w3c.dom.Node: ...
    @staticmethod
    def getNodeName(receiver: org.w3c.dom.Node, /) -> str: ...
    @staticmethod
    def getNodeType(receiver: org.w3c.dom.Node, /) -> int: ...
    @staticmethod
    def getNodeValue(receiver: org.w3c.dom.Node, /) -> str: ...
    @typing.overload
    @staticmethod
    def getOuterHTML(receiver: org.w3c.dom.Node, /) -> str: ...
    @typing.overload
    @staticmethod
    def getOuterHTML(receiver: org.w3c.dom.NodeList, /) -> str: ...
    @staticmethod
    def getOwnerDocument(receiver: org.w3c.dom.Node, /) -> org.w3c.dom.Document: ...
    @staticmethod
    def getParentNode(receiver: org.w3c.dom.Node, /) -> org.w3c.dom.Node: ...
    @staticmethod
    def getPrefix(receiver: org.w3c.dom.Node, /) -> str: ...
    @staticmethod
    def getPreviousSibling(receiver: org.w3c.dom.Node, /) -> org.w3c.dom.Node: ...
    @staticmethod
    def getRelatedTarget(receiver: org.w3c.dom.events.MouseEvent, /) -> org.w3c.dom.events.EventTarget: ...
    @staticmethod
    def getScreenX(receiver: org.w3c.dom.events.MouseEvent, /) -> int: ...
    @staticmethod
    def getScreenY(receiver: org.w3c.dom.events.MouseEvent, /) -> int: ...
    @staticmethod
    def getShiftKey(receiver: org.w3c.dom.events.MouseEvent, /) -> bool: ...
    @staticmethod
    def getStyle(receiver: org.w3c.dom.Element, /) -> str: ...
    @staticmethod
    def getTail(receiver: org.w3c.dom.NodeList, /) -> org.w3c.dom.Node: ...
    @staticmethod
    def getTarget(receiver: org.w3c.dom.events.Event, /) -> org.w3c.dom.events.EventTarget: ...
    @staticmethod
    def getText(receiver: org.w3c.dom.Node, /) -> str: ...
    @staticmethod
    def getTextContent(receiver: org.w3c.dom.Node, /) -> str: ...
    @staticmethod
    def getTimeStamp(receiver: org.w3c.dom.events.Event, /) -> int: ...
    @staticmethod
    def hasClass(receiver: org.w3c.dom.Element, cssClass: str | java.lang.String, /) -> bool: ...
    @staticmethod
    def isText(receiver: org.w3c.dom.Node, /) -> bool: ...
    @staticmethod
    def mouseEventHandler(handler: jet.Function1[org.w3c.dom.events.MouseEvent, jet.Unit], /) -> org.w3c.dom.events.EventListener: ...
    @staticmethod
    def nextElements(receiver: org.w3c.dom.Node, /) -> java.util.Iterator[org.w3c.dom.Element]: ...
    @staticmethod
    def nextSiblings(receiver: org.w3c.dom.Node, /) -> java.util.Iterator[org.w3c.dom.Node]: ...
    @staticmethod
    def nodesToXmlString(nodes: java.lang.Iterable[org.w3c.dom.Node], xmlDeclaration: bool | java.jboolean | java.lang.Boolean, /) -> str: ...
    @typing.overload
    @staticmethod
    def on(receiver: org.w3c.dom.Node, name: str | java.lang.String, capture: bool | java.jboolean | java.lang.Boolean, handler: jet.Function1[org.w3c.dom.events.Event, jet.Unit], /) -> java.io.Closeable: ...
    @typing.overload
    @staticmethod
    def on(receiver: org.w3c.dom.Node, name: str | java.lang.String, capture: bool | java.jboolean | java.lang.Boolean, listener: org.w3c.dom.events.EventListener, /) -> java.io.Closeable: ...
    @staticmethod
    def onClick(receiver: org.w3c.dom.Node, capture: bool | java.jboolean | java.lang.Boolean, handler: jet.Function1[org.w3c.dom.events.MouseEvent, jet.Unit], /) -> java.io.Closeable: ...
    @staticmethod
    def onDoubleClick(receiver: org.w3c.dom.Node, capture: bool | java.jboolean | java.lang.Boolean, handler: jet.Function1[org.w3c.dom.events.MouseEvent, jet.Unit], /) -> java.io.Closeable: ...
    @staticmethod
    def ownerDocument(receiver: org.w3c.dom.Node, doc: org.w3c.dom.Document, /) -> org.w3c.dom.Document: ...
    @typing.overload
    @staticmethod
    def parseXml(file: java.io.File, builder: javax.xml.parsers.DocumentBuilder, /) -> org.w3c.dom.Document: ...
    @typing.overload
    @staticmethod
    def parseXml(inputStream: java.io.InputStream, builder: javax.xml.parsers.DocumentBuilder, /) -> org.w3c.dom.Document: ...
    @typing.overload
    @staticmethod
    def parseXml(uri: str | java.lang.String, builder: javax.xml.parsers.DocumentBuilder, /) -> org.w3c.dom.Document: ...
    @typing.overload
    @staticmethod
    def parseXml(inputSource: org.xml.sax.InputSource, builder: javax.xml.parsers.DocumentBuilder, /) -> org.w3c.dom.Document: ...
    @typing.overload
    @staticmethod
    def plus(receiver: org.w3c.dom.Element, text: str | java.lang.String, /) -> org.w3c.dom.Element: ...
    @typing.overload
    @staticmethod
    def plus(receiver: org.w3c.dom.Node, child: org.w3c.dom.Node, /) -> org.w3c.dom.Node: ...
    @staticmethod
    def plusAssign(receiver: org.w3c.dom.Element, text: str | java.lang.String, /) -> org.w3c.dom.Element: ...
    @staticmethod
    def previousElements(receiver: org.w3c.dom.Node, /) -> java.util.Iterator[org.w3c.dom.Element]: ...
    @staticmethod
    def previousSiblings(receiver: org.w3c.dom.Node, /) -> java.util.Iterator[org.w3c.dom.Node]: ...
    @staticmethod
    def removeClass(receiver: org.w3c.dom.Element, cssClass: str | java.lang.String, /) -> bool: ...
    @staticmethod
    def setChildrenText(receiver: org.w3c.dom.Element, value: str | java.lang.String, /) -> None: ...
    @staticmethod
    def setClassSet(receiver: org.w3c.dom.Element, value: java.util.Set[java.lang.String], /) -> None: ...
    @staticmethod
    def setClasses(receiver: org.w3c.dom.Element, value: str | java.lang.String, /) -> None: ...
    @staticmethod
    def setId(receiver: org.w3c.dom.Element, value: str | java.lang.String, /) -> None: ...
    @staticmethod
    def setStyle(receiver: org.w3c.dom.Element, value: str | java.lang.String, /) -> None: ...
    @staticmethod
    def setText(receiver: org.w3c.dom.Node, value: str | java.lang.String, /) -> None: ...
    @staticmethod
    def setTextContent(receiver: org.w3c.dom.Node, value: str | java.lang.String, /) -> None: ...
    @staticmethod
    def toElementList(receiver: org.w3c.dom.NodeList, /) -> java.util.List[org.w3c.dom.Element]: ...
    @staticmethod
    def toList(receiver: org.w3c.dom.NodeList, /) -> java.util.List[org.w3c.dom.Node]: ...
    @typing.overload
    @staticmethod
    def toXmlString(receiver: org.w3c.dom.Node, /) -> str: ...
    @typing.overload
    @staticmethod
    def toXmlString(receiver: org.w3c.dom.Node, xmlDeclaration: bool | java.jboolean | java.lang.Boolean, /) -> str: ...
    @typing.overload
    @staticmethod
    def toXmlString(receiver: org.w3c.dom.NodeList, xmlDeclaration: bool | java.jboolean | java.lang.Boolean, /) -> str: ...
    @staticmethod
    def writeXmlString(receiver: org.w3c.dom.Node, writer: java.io.Writer, xmlDeclaration: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class ElementListAsList(java.util.AbstractList[org.w3c.dom.Element]):
    def __init__(self, nodeList: org.w3c.dom.NodeList, /) -> None: ...
    def get(self, index: int | java.jint | java.lang.Integer, /) -> org.w3c.dom.Element: ...
    def getNodeList(self) -> org.w3c.dom.NodeList: ...
    def size(self) -> int: ...
    def toArray(self, arg1: java.chaquopy.JavaArray[java.lang.Object], /) -> java.chaquopy.JavaArray[java.lang.Object]: ...

class EventListenerHandler(jet.JetObject, org.w3c.dom.events.EventListener):
    def __init__(self, handler: jet.Function1[org.w3c.dom.events.Event, jet.Unit], /) -> None: ...
    def getHandler(self) -> jet.Function1[org.w3c.dom.events.Event, jet.Unit]: ...
    def handleEvent(self, e: org.w3c.dom.events.Event, /) -> None: ...

class NextSiblingIterator(kotlin.support.AbstractIterator[org.w3c.dom.Node]):
    def __init__(self, node: org.w3c.dom.Node, /) -> None: ...
    def computeNext(self) -> None: ...
    def getNode(self) -> org.w3c.dom.Node: ...
    def remove(self) -> None: ...
    def setNode(self, <set-?>: org.w3c.dom.Node, /) -> None: ...

class NodeListAsList(java.util.AbstractList[org.w3c.dom.Node]):
    def __init__(self, nodeList: org.w3c.dom.NodeList, /) -> None: ...
    def get(self, index: int | java.jint | java.lang.Integer, /) -> org.w3c.dom.Node: ...
    def getNodeList(self) -> org.w3c.dom.NodeList: ...
    def size(self) -> int: ...
    def toArray(self, arg1: java.chaquopy.JavaArray[java.lang.Object], /) -> java.chaquopy.JavaArray[java.lang.Object]: ...

class PreviousSiblingIterator(kotlin.support.AbstractIterator[org.w3c.dom.Node]):
    def __init__(self, node: org.w3c.dom.Node, /) -> None: ...
    def computeNext(self) -> None: ...
    def getNode(self) -> org.w3c.dom.Node: ...
    def remove(self) -> None: ...
    def setNode(self, <set-?>: org.w3c.dom.Node, /) -> None: ...
