import typing

import android.accessibilityservice
import android.content.pm
import java
import java.lang

class AccessibilityServiceInfoCompat(java.lang.Object):
    CAPABILITY_CAN_RETRIEVE_WINDOW_CONTENT: typing.ClassVar[int] = ...
    CAPABILITY_CAN_REQUEST_TOUCH_EXPLORATION: typing.ClassVar[int] = ...
    CAPABILITY_CAN_REQUEST_ENHANCED_WEB_ACCESSIBILITY: typing.ClassVar[int] = ...
    CAPABILITY_CAN_FILTER_KEY_EVENTS: typing.ClassVar[int] = ...
    FEEDBACK_BRAILLE: typing.ClassVar[int] = ...
    FEEDBACK_ALL_MASK: typing.ClassVar[int] = ...
    FLAG_INCLUDE_NOT_IMPORTANT_VIEWS: typing.ClassVar[int] = ...
    FLAG_REQUEST_TOUCH_EXPLORATION_MODE: typing.ClassVar[int] = ...
    FLAG_REQUEST_ENHANCED_WEB_ACCESSIBILITY: typing.ClassVar[int] = ...
    FLAG_REPORT_VIEW_IDS: typing.ClassVar[int] = ...
    FLAG_REQUEST_FILTER_KEY_EVENTS: typing.ClassVar[int] = ...
    @staticmethod
    def capabilityToString(capability: int | java.jint | java.lang.Integer, /) -> str: ...
    @staticmethod
    def feedbackTypeToString(feedbackType: int | java.jint | java.lang.Integer, /) -> str: ...
    @staticmethod
    def flagToString(flag: int | java.jint | java.lang.Integer, /) -> str: ...
    @staticmethod
    def getCapabilities(info: android.accessibilityservice.AccessibilityServiceInfo, /) -> int: ...
    @staticmethod
    def loadDescription(info: android.accessibilityservice.AccessibilityServiceInfo, packageManager: android.content.pm.PackageManager, /) -> str: ...
