import java.lang.annotation

class Contract(java.lang.annotation.Annotation):
    def pure(self) -> bool: ...
    def value(self) -> str: ...

class Nls(java.lang.annotation.Annotation): ...

class NonNls(java.lang.annotation.Annotation): ...

class NotNull(java.lang.annotation.Annotation):
    def value(self) -> str: ...

class Nullable(java.lang.annotation.Annotation):
    def value(self) -> str: ...

class PropertyKey(java.lang.annotation.Annotation):
    def resourceBundle(self) -> str: ...

class TestOnly(java.lang.annotation.Annotation): ...
