import typing

import androidx.constraintlayout.core
import androidx.constraintlayout.core.state
import androidx.constraintlayout.core.widgets.analyzer
import java
import java.chaquopy
import java.lang
import java.util

class Barrier(HelperWidget):
    LEFT: typing.ClassVar[int] = ...
    RIGHT: typing.ClassVar[int] = ...
    TOP: typing.ClassVar[int] = ...
    BOTTOM: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, debugName: str | java.lang.String, /) -> None: ...
    def addToSolver(self, system: androidx.constraintlayout.core.LinearSystem, optimize: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def allSolved(self) -> bool: ...
    def allowedInBarrier(self) -> bool: ...
    def allowsGoneWidget(self) -> bool: ...
    def copy(self, src: ConstraintWidget, map: java.util.HashMap[ConstraintWidget, ConstraintWidget], /) -> None: ...
    def getAllowsGoneWidget(self) -> bool: ...
    def getBarrierType(self) -> int: ...
    def getMargin(self) -> int: ...
    def getOrientation(self) -> int: ...
    def isResolvedHorizontally(self) -> bool: ...
    def isResolvedVertically(self) -> bool: ...
    def markWidgets(self) -> None: ...
    def setAllowsGoneWidget(self, allowsGoneWidget: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setBarrierType(self, barrierType: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMargin(self, margin: int | java.jint | java.lang.Integer, /) -> None: ...
    def toString(self) -> str: ...

class Chain(java.lang.Object):
    USE_CHAIN_OPTIMIZATION: typing.ClassVar[bool] = ...
    def __init__(self) -> None: ...
    @staticmethod
    def applyChainConstraints(constraintWidgetContainer: ConstraintWidgetContainer, system: androidx.constraintlayout.core.LinearSystem, widgets: java.util.ArrayList[ConstraintWidget], orientation: int | java.jint | java.lang.Integer, /) -> None: ...

class ChainHead(java.lang.Object):
    mFirst: ConstraintWidget = ...
    mFirstVisibleWidget: ConstraintWidget = ...
    mLast: ConstraintWidget = ...
    mLastVisibleWidget: ConstraintWidget = ...
    mHead: ConstraintWidget = ...
    mFirstMatchConstraintWidget: ConstraintWidget = ...
    mLastMatchConstraintWidget: ConstraintWidget = ...
    mWeightedMatchConstraintsWidgets: java.util.ArrayList[ConstraintWidget] = ...
    mWidgetsCount: int = ...
    mWidgetsMatchCount: int = ...
    mTotalWeight: float = ...
    mHasUndefinedWeights: bool = ...
    mHasDefinedWeights: bool = ...
    mHasComplexMatchWeights: bool = ...
    mHasRatio: bool = ...
    def __init__(self, first: ConstraintWidget, orientation: int | java.jint | java.lang.Integer, isRtl: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def define(self) -> None: ...
    def getFirst(self) -> ConstraintWidget: ...
    def getFirstMatchConstraintWidget(self) -> ConstraintWidget: ...
    def getFirstVisibleWidget(self) -> ConstraintWidget: ...
    def getHead(self) -> ConstraintWidget: ...
    def getLast(self) -> ConstraintWidget: ...
    def getLastMatchConstraintWidget(self) -> ConstraintWidget: ...
    def getLastVisibleWidget(self) -> ConstraintWidget: ...
    def getTotalWeight(self) -> float: ...

class ConstraintAnchor(java.lang.Object):
    mOwner: ConstraintWidget = ...
    mType: ConstraintAnchor.Type = ...
    mTarget: ConstraintAnchor = ...
    mMargin: int = ...
    def __init__(self, owner: ConstraintWidget, type: ConstraintAnchor.Type, /) -> None: ...
    @typing.overload
    def connect(self, toAnchor: ConstraintAnchor, margin: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def connect(self, toAnchor: ConstraintAnchor, margin: int | java.jint | java.lang.Integer, goneMargin: int | java.jint | java.lang.Integer, forceConnection: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def copyFrom(self, source: ConstraintAnchor, map: java.util.HashMap[ConstraintWidget, ConstraintWidget], /) -> None: ...
    def findDependents(self, orientation: int | java.jint | java.lang.Integer, list: java.util.ArrayList[androidx.constraintlayout.core.widgets.analyzer.WidgetGroup], group: androidx.constraintlayout.core.widgets.analyzer.WidgetGroup, /) -> None: ...
    def getDependents(self) -> java.util.HashSet[ConstraintAnchor]: ...
    def getFinalValue(self) -> int: ...
    def getMargin(self) -> int: ...
    def getOpposite(self) -> ConstraintAnchor: ...
    def getOwner(self) -> ConstraintWidget: ...
    def getSolverVariable(self) -> androidx.constraintlayout.core.SolverVariable: ...
    def getTarget(self) -> ConstraintAnchor: ...
    def getType(self) -> ConstraintAnchor.Type: ...
    def hasCenteredDependents(self) -> bool: ...
    def hasDependents(self) -> bool: ...
    def hasFinalValue(self) -> bool: ...
    def isConnected(self) -> bool: ...
    @typing.overload
    def isConnectionAllowed(self, target: ConstraintWidget, /) -> bool: ...
    @typing.overload
    def isConnectionAllowed(self, target: ConstraintWidget, anchor: ConstraintAnchor, /) -> bool: ...
    def isSideAnchor(self) -> bool: ...
    def isSimilarDimensionConnection(self, anchor: ConstraintAnchor, /) -> bool: ...
    def isValidConnection(self, anchor: ConstraintAnchor, /) -> bool: ...
    def isVerticalAnchor(self) -> bool: ...
    def reset(self) -> None: ...
    def resetFinalResolution(self) -> None: ...
    def resetSolverVariable(self, cache: androidx.constraintlayout.core.Cache, /) -> None: ...
    def setFinalValue(self, finalValue: int | java.jint | java.lang.Integer, /) -> None: ...
    def setGoneMargin(self, margin: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMargin(self, margin: int | java.jint | java.lang.Integer, /) -> None: ...
    def toString(self) -> str: ...

    class Type(java.lang.Enum[ConstraintAnchor.Type]):
        NONE: typing.ClassVar[ConstraintAnchor.Type] = ...
        LEFT: typing.ClassVar[ConstraintAnchor.Type] = ...
        TOP: typing.ClassVar[ConstraintAnchor.Type] = ...
        RIGHT: typing.ClassVar[ConstraintAnchor.Type] = ...
        BOTTOM: typing.ClassVar[ConstraintAnchor.Type] = ...
        BASELINE: typing.ClassVar[ConstraintAnchor.Type] = ...
        CENTER: typing.ClassVar[ConstraintAnchor.Type] = ...
        CENTER_X: typing.ClassVar[ConstraintAnchor.Type] = ...
        CENTER_Y: typing.ClassVar[ConstraintAnchor.Type] = ...
        @staticmethod
        def valueOf(name: str | java.lang.String, /) -> ConstraintAnchor.Type: ...
        @staticmethod
        def values() -> java.chaquopy.JavaArray[ConstraintAnchor.Type]: ...

class ConstraintWidget(java.lang.Object):
    SOLVER: typing.ClassVar[int] = ...
    DIRECT: typing.ClassVar[int] = ...
    measured: bool = ...
    run: java.chaquopy.JavaArray[androidx.constraintlayout.core.widgets.analyzer.WidgetRun] = ...
    horizontalChainRun: androidx.constraintlayout.core.widgets.analyzer.ChainRun = ...
    verticalChainRun: androidx.constraintlayout.core.widgets.analyzer.ChainRun = ...
    mHorizontalRun: androidx.constraintlayout.core.widgets.analyzer.HorizontalWidgetRun = ...
    mVerticalRun: androidx.constraintlayout.core.widgets.analyzer.VerticalWidgetRun = ...
    isTerminalWidget: java.chaquopy.JavaArrayJBoolean = ...
    frame: androidx.constraintlayout.core.state.WidgetFrame = ...
    stringId: str = ...
    MATCH_CONSTRAINT_SPREAD: typing.ClassVar[int] = ...
    MATCH_CONSTRAINT_WRAP: typing.ClassVar[int] = ...
    MATCH_CONSTRAINT_PERCENT: typing.ClassVar[int] = ...
    MATCH_CONSTRAINT_RATIO: typing.ClassVar[int] = ...
    MATCH_CONSTRAINT_RATIO_RESOLVED: typing.ClassVar[int] = ...
    UNKNOWN: typing.ClassVar[int] = ...
    HORIZONTAL: typing.ClassVar[int] = ...
    VERTICAL: typing.ClassVar[int] = ...
    BOTH: typing.ClassVar[int] = ...
    VISIBLE: typing.ClassVar[int] = ...
    INVISIBLE: typing.ClassVar[int] = ...
    GONE: typing.ClassVar[int] = ...
    CHAIN_SPREAD: typing.ClassVar[int] = ...
    CHAIN_SPREAD_INSIDE: typing.ClassVar[int] = ...
    CHAIN_PACKED: typing.ClassVar[int] = ...
    WRAP_BEHAVIOR_INCLUDED: typing.ClassVar[int] = ...
    WRAP_BEHAVIOR_HORIZONTAL_ONLY: typing.ClassVar[int] = ...
    WRAP_BEHAVIOR_VERTICAL_ONLY: typing.ClassVar[int] = ...
    WRAP_BEHAVIOR_SKIPPED: typing.ClassVar[int] = ...
    mHorizontalResolution: int = ...
    mVerticalResolution: int = ...
    mMatchConstraintDefaultWidth: int = ...
    mMatchConstraintDefaultHeight: int = ...
    mResolvedMatchConstraintDefault: java.chaquopy.JavaArrayJInt = ...
    mMatchConstraintMinWidth: int = ...
    mMatchConstraintMaxWidth: int = ...
    mMatchConstraintPercentWidth: float = ...
    mMatchConstraintMinHeight: int = ...
    mMatchConstraintMaxHeight: int = ...
    mMatchConstraintPercentHeight: float = ...
    mIsWidthWrapContent: bool = ...
    mIsHeightWrapContent: bool = ...
    mCircleConstraintAngle: float = ...
    mLeft: ConstraintAnchor = ...
    mTop: ConstraintAnchor = ...
    mRight: ConstraintAnchor = ...
    mBottom: ConstraintAnchor = ...
    mBaseline: ConstraintAnchor = ...
    mCenter: ConstraintAnchor = ...
    ANCHOR_LEFT: typing.ClassVar[int] = ...
    ANCHOR_RIGHT: typing.ClassVar[int] = ...
    ANCHOR_TOP: typing.ClassVar[int] = ...
    ANCHOR_BOTTOM: typing.ClassVar[int] = ...
    ANCHOR_BASELINE: typing.ClassVar[int] = ...
    mListAnchors: java.chaquopy.JavaArray[ConstraintAnchor] = ...
    mAnchors: java.util.ArrayList[ConstraintAnchor] = ...
    mListDimensionBehaviors: java.chaquopy.JavaArray[ConstraintWidget.DimensionBehaviour] = ...
    mParent: ConstraintWidget = ...
    mDimensionRatio: float = ...
    mDimensionRatioSide: int = ...
    mX: int = ...
    mY: int = ...
    mOffsetX: int = ...
    mOffsetY: int = ...
    mMinWidth: int = ...
    mMinHeight: int = ...
    DEFAULT_BIAS: typing.ClassVar[float] = ...
    mWeight: java.chaquopy.JavaArrayJFloat = ...
    mListNextMatchConstraintsWidget: java.chaquopy.JavaArray[ConstraintWidget] = ...
    mNextChainWidget: java.chaquopy.JavaArray[ConstraintWidget] = ...
    horizontalGroup: int = ...
    verticalGroup: int = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, debugName: str | java.lang.String, /) -> None: ...
    @typing.overload
    def __init__(self, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, debugName: str | java.lang.String, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, debugName: str | java.lang.String, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...
    def addChildrenToSolverByDependency(self, container: ConstraintWidgetContainer, system: androidx.constraintlayout.core.LinearSystem, widgets: java.util.HashSet[ConstraintWidget], orientation: int | java.jint | java.lang.Integer, addSelf: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def addToSolver(self, system: androidx.constraintlayout.core.LinearSystem, optimize: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def allowedInBarrier(self) -> bool: ...
    @typing.overload
    def connect(self, constraintFrom: ConstraintAnchor.Type, target: ConstraintWidget, constraintTo: ConstraintAnchor.Type, /) -> None: ...
    @typing.overload
    def connect(self, from_: ConstraintAnchor, to: ConstraintAnchor, margin: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def connect(self, constraintFrom: ConstraintAnchor.Type, target: ConstraintWidget, constraintTo: ConstraintAnchor.Type, margin: int | java.jint | java.lang.Integer, /) -> None: ...
    def connectCircularConstraint(self, target: ConstraintWidget, angle: float | java.jfloat | java.lang.Float, radius: int | java.jint | java.lang.Integer, /) -> None: ...
    def copy(self, src: ConstraintWidget, map: java.util.HashMap[ConstraintWidget, ConstraintWidget], /) -> None: ...
    def createObjectVariables(self, system: androidx.constraintlayout.core.LinearSystem, /) -> None: ...
    def ensureMeasureRequested(self) -> None: ...
    def ensureWidgetRuns(self) -> None: ...
    def getAnchor(self, anchorType: ConstraintAnchor.Type, /) -> ConstraintAnchor: ...
    def getAnchors(self) -> java.util.ArrayList[ConstraintAnchor]: ...
    def getBaselineDistance(self) -> int: ...
    def getBiasPercent(self, orientation: int | java.jint | java.lang.Integer, /) -> float: ...
    def getBottom(self) -> int: ...
    def getCompanionWidget(self) -> java.lang.Object: ...
    def getContainerItemSkip(self) -> int: ...
    def getDebugName(self) -> str: ...
    def getDimensionBehaviour(self, orientation: int | java.jint | java.lang.Integer, /) -> ConstraintWidget.DimensionBehaviour: ...
    def getDimensionRatio(self) -> float: ...
    def getDimensionRatioSide(self) -> int: ...
    def getHasBaseline(self) -> bool: ...
    def getHeight(self) -> int: ...
    def getHorizontalBiasPercent(self) -> float: ...
    def getHorizontalChainControlWidget(self) -> ConstraintWidget: ...
    def getHorizontalChainStyle(self) -> int: ...
    def getHorizontalDimensionBehaviour(self) -> ConstraintWidget.DimensionBehaviour: ...
    def getHorizontalMargin(self) -> int: ...
    def getLastHorizontalMeasureSpec(self) -> int: ...
    def getLastVerticalMeasureSpec(self) -> int: ...
    def getLeft(self) -> int: ...
    def getLength(self, orientation: int | java.jint | java.lang.Integer, /) -> int: ...
    def getMaxHeight(self) -> int: ...
    def getMaxWidth(self) -> int: ...
    def getMinHeight(self) -> int: ...
    def getMinWidth(self) -> int: ...
    def getNextChainMember(self, orientation: int | java.jint | java.lang.Integer, /) -> ConstraintWidget: ...
    def getOptimizerWrapHeight(self) -> int: ...
    def getOptimizerWrapWidth(self) -> int: ...
    def getParent(self) -> ConstraintWidget: ...
    def getPreviousChainMember(self, orientation: int | java.jint | java.lang.Integer, /) -> ConstraintWidget: ...
    def getRight(self) -> int: ...
    def getRootX(self) -> int: ...
    def getRootY(self) -> int: ...
    def getRun(self, orientation: int | java.jint | java.lang.Integer, /) -> androidx.constraintlayout.core.widgets.analyzer.WidgetRun: ...
    def getSceneString(self, ret: java.lang.StringBuilder, /) -> None: ...
    def getTop(self) -> int: ...
    def getType(self) -> str: ...
    def getVerticalBiasPercent(self) -> float: ...
    def getVerticalChainControlWidget(self) -> ConstraintWidget: ...
    def getVerticalChainStyle(self) -> int: ...
    def getVerticalDimensionBehaviour(self) -> ConstraintWidget.DimensionBehaviour: ...
    def getVerticalMargin(self) -> int: ...
    def getVisibility(self) -> int: ...
    def getWidth(self) -> int: ...
    def getWrapBehaviorInParent(self) -> int: ...
    def getX(self) -> int: ...
    def getY(self) -> int: ...
    def hasBaseline(self) -> bool: ...
    def hasDanglingDimension(self, orientation: int | java.jint | java.lang.Integer, /) -> bool: ...
    def hasDependencies(self) -> bool: ...
    def hasDimensionOverride(self) -> bool: ...
    def hasResolvedTargets(self, orientation: int | java.jint | java.lang.Integer, size: int | java.jint | java.lang.Integer, /) -> bool: ...
    def immediateConnect(self, startType: ConstraintAnchor.Type, target: ConstraintWidget, endType: ConstraintAnchor.Type, margin: int | java.jint | java.lang.Integer, goneMargin: int | java.jint | java.lang.Integer, /) -> None: ...
    def isAnimated(self) -> bool: ...
    def isHeightWrapContent(self) -> bool: ...
    def isHorizontalSolvingPassDone(self) -> bool: ...
    def isInBarrier(self, orientation: int | java.jint | java.lang.Integer, /) -> bool: ...
    def isInHorizontalChain(self) -> bool: ...
    def isInPlaceholder(self) -> bool: ...
    def isInVerticalChain(self) -> bool: ...
    def isInVirtualLayout(self) -> bool: ...
    def isMeasureRequested(self) -> bool: ...
    def isResolvedHorizontally(self) -> bool: ...
    def isResolvedVertically(self) -> bool: ...
    def isRoot(self) -> bool: ...
    def isSpreadHeight(self) -> bool: ...
    def isSpreadWidth(self) -> bool: ...
    def isVerticalSolvingPassDone(self) -> bool: ...
    def isWidthWrapContent(self) -> bool: ...
    def markHorizontalSolvingPassDone(self) -> None: ...
    def markVerticalSolvingPassDone(self) -> None: ...
    def oppositeDimensionDependsOn(self, orientation: int | java.jint | java.lang.Integer, /) -> bool: ...
    def oppositeDimensionsTied(self) -> bool: ...
    def reset(self) -> None: ...
    def resetAllConstraints(self) -> None: ...
    def resetAnchor(self, anchor: ConstraintAnchor, /) -> None: ...
    def resetAnchors(self) -> None: ...
    def resetFinalResolution(self) -> None: ...
    def resetSolverVariables(self, cache: androidx.constraintlayout.core.Cache, /) -> None: ...
    def resetSolvingPassFlag(self) -> None: ...
    def serialize(self, ret: java.lang.StringBuilder, /) -> java.lang.StringBuilder: ...
    def setAnimated(self, animated: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setBaselineDistance(self, baseline: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCompanionWidget(self, companion: java.lang.Object | int | bool | float | str, /) -> None: ...
    def setContainerItemSkip(self, skip: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDebugName(self, name: str | java.lang.String, /) -> None: ...
    def setDebugSolverName(self, system: androidx.constraintlayout.core.LinearSystem, name: str | java.lang.String, /) -> None: ...
    def setDimension(self, w: int | java.jint | java.lang.Integer, h: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setDimensionRatio(self, ratio: str | java.lang.String, /) -> None: ...
    @typing.overload
    def setDimensionRatio(self, ratio: float | java.jfloat | java.lang.Float, dimensionRatioSide: int | java.jint | java.lang.Integer, /) -> None: ...
    def setFinalBaseline(self, baselineValue: int | java.jint | java.lang.Integer, /) -> None: ...
    def setFinalFrame(self, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, baseline: int | java.jint | java.lang.Integer, orientation: int | java.jint | java.lang.Integer, /) -> None: ...
    def setFinalHorizontal(self, x1: int | java.jint | java.lang.Integer, x2: int | java.jint | java.lang.Integer, /) -> None: ...
    def setFinalLeft(self, x1: int | java.jint | java.lang.Integer, /) -> None: ...
    def setFinalTop(self, y1: int | java.jint | java.lang.Integer, /) -> None: ...
    def setFinalVertical(self, y1: int | java.jint | java.lang.Integer, y2: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setFrame(self, start: int | java.jint | java.lang.Integer, end: int | java.jint | java.lang.Integer, orientation: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setFrame(self, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setGoneMargin(self, type: ConstraintAnchor.Type, goneMargin: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHasBaseline(self, hasBaseline: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setHeight(self, h: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHeightWrapContent(self, heightWrapContent: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setHorizontalBiasPercent(self, horizontalBiasPercent: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setHorizontalChainStyle(self, horizontalChainStyle: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHorizontalDimension(self, left: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHorizontalDimensionBehaviour(self, behaviour: ConstraintWidget.DimensionBehaviour, /) -> None: ...
    def setHorizontalMatchStyle(self, horizontalMatchStyle: int | java.jint | java.lang.Integer, min: int | java.jint | java.lang.Integer, max: int | java.jint | java.lang.Integer, percent: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setHorizontalWeight(self, horizontalWeight: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setInBarrier(self, orientation: int | java.jint | java.lang.Integer, value: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setInPlaceholder(self, inPlaceholder: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setInVirtualLayout(self, inVirtualLayout: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setLastMeasureSpec(self, horizontal: int | java.jint | java.lang.Integer, vertical: int | java.jint | java.lang.Integer, /) -> None: ...
    def setLength(self, length: int | java.jint | java.lang.Integer, orientation: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMaxHeight(self, maxHeight: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMaxWidth(self, maxWidth: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMeasureRequested(self, measureRequested: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setMinHeight(self, h: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMinWidth(self, w: int | java.jint | java.lang.Integer, /) -> None: ...
    def setOffset(self, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, /) -> None: ...
    def setOrigin(self, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, /) -> None: ...
    def setParent(self, widget: ConstraintWidget, /) -> None: ...
    def setType(self, type: str | java.lang.String, /) -> None: ...
    def setVerticalBiasPercent(self, verticalBiasPercent: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setVerticalChainStyle(self, verticalChainStyle: int | java.jint | java.lang.Integer, /) -> None: ...
    def setVerticalDimension(self, top: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setVerticalDimensionBehaviour(self, behaviour: ConstraintWidget.DimensionBehaviour, /) -> None: ...
    def setVerticalMatchStyle(self, verticalMatchStyle: int | java.jint | java.lang.Integer, min: int | java.jint | java.lang.Integer, max: int | java.jint | java.lang.Integer, percent: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setVerticalWeight(self, verticalWeight: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setVisibility(self, visibility: int | java.jint | java.lang.Integer, /) -> None: ...
    def setWidth(self, w: int | java.jint | java.lang.Integer, /) -> None: ...
    def setWidthWrapContent(self, widthWrapContent: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setWrapBehaviorInParent(self, behavior: int | java.jint | java.lang.Integer, /) -> None: ...
    def setX(self, x: int | java.jint | java.lang.Integer, /) -> None: ...
    def setY(self, y: int | java.jint | java.lang.Integer, /) -> None: ...
    def setupDimensionRatio(self, hParentWrapContent: bool | java.jboolean | java.lang.Boolean, vParentWrapContent: bool | java.jboolean | java.lang.Boolean, horizontalDimensionFixed: bool | java.jboolean | java.lang.Boolean, verticalDimensionFixed: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def toString(self) -> str: ...
    def updateFromRuns(self, updateHorizontal: bool | java.jboolean | java.lang.Boolean, updateVertical: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def updateFromSolver(self, system: androidx.constraintlayout.core.LinearSystem, optimize: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

    class DimensionBehaviour(java.lang.Enum[ConstraintWidget.DimensionBehaviour]):
        FIXED: typing.ClassVar[ConstraintWidget.DimensionBehaviour] = ...
        WRAP_CONTENT: typing.ClassVar[ConstraintWidget.DimensionBehaviour] = ...
        MATCH_CONSTRAINT: typing.ClassVar[ConstraintWidget.DimensionBehaviour] = ...
        MATCH_PARENT: typing.ClassVar[ConstraintWidget.DimensionBehaviour] = ...
        @staticmethod
        def valueOf(name: str | java.lang.String, /) -> ConstraintWidget.DimensionBehaviour: ...
        @staticmethod
        def values() -> java.chaquopy.JavaArray[ConstraintWidget.DimensionBehaviour]: ...

class ConstraintWidgetContainer(WidgetContainer):
    mDependencyGraph: androidx.constraintlayout.core.widgets.analyzer.DependencyGraph = ...
    mMeasurer: androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.Measurer = ...
    mMetrics: androidx.constraintlayout.core.Metrics = ...
    mSystem: androidx.constraintlayout.core.LinearSystem = ...
    mHorizontalChainsSize: int = ...
    mVerticalChainsSize: int = ...
    mGroupsWrapOptimized: bool = ...
    mHorizontalWrapOptimized: bool = ...
    mVerticalWrapOptimized: bool = ...
    mWrapFixedWidth: int = ...
    mWrapFixedHeight: int = ...
    mSkipSolver: bool = ...
    mMeasure: androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.Measure = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, debugName: str | java.lang.String, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...
    def addChildrenToSolver(self, system: androidx.constraintlayout.core.LinearSystem, /) -> bool: ...
    def addHorizontalWrapMaxVariable(self, right: ConstraintAnchor, /) -> None: ...
    def addHorizontalWrapMinVariable(self, left: ConstraintAnchor, /) -> None: ...
    def defineTerminalWidgets(self) -> None: ...
    def directMeasure(self, optimizeWrap: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def directMeasureSetup(self, optimizeWrap: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def directMeasureWithOrientation(self, optimizeWrap: bool | java.jboolean | java.lang.Boolean, orientation: int | java.jint | java.lang.Integer, /) -> bool: ...
    def fillMetrics(self, metrics: androidx.constraintlayout.core.Metrics, /) -> None: ...
    def getHorizontalGuidelines(self) -> java.util.ArrayList[Guideline]: ...
    def getMeasurer(self) -> androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.Measurer: ...
    def getOptimizationLevel(self) -> int: ...
    def getSceneString(self, ret: java.lang.StringBuilder, /) -> None: ...
    def getSystem(self) -> androidx.constraintlayout.core.LinearSystem: ...
    def getType(self) -> str: ...
    def getVerticalGuidelines(self) -> java.util.ArrayList[Guideline]: ...
    def handlesInternalConstraints(self) -> bool: ...
    def invalidateGraph(self) -> None: ...
    def invalidateMeasures(self) -> None: ...
    def isHeightMeasuredTooSmall(self) -> bool: ...
    def isRtl(self) -> bool: ...
    def isWidthMeasuredTooSmall(self) -> bool: ...
    def layout(self) -> None: ...
    @typing.overload
    @staticmethod
    def measure(level: int | java.jint | java.lang.Integer, widget: ConstraintWidget, measurer: androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.Measurer, measure: androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.Measure, measureStrategy: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def measure(self, optimizationLevel: int | java.jint | java.lang.Integer, widthMode: int | java.jint | java.lang.Integer, widthSize: int | java.jint | java.lang.Integer, heightMode: int | java.jint | java.lang.Integer, heightSize: int | java.jint | java.lang.Integer, lastMeasureWidth: int | java.jint | java.lang.Integer, lastMeasureHeight: int | java.jint | java.lang.Integer, paddingX: int | java.jint | java.lang.Integer, paddingY: int | java.jint | java.lang.Integer, /) -> int: ...
    def optimizeFor(self, feature: int | java.jint | java.lang.Integer, /) -> bool: ...
    def reset(self) -> None: ...
    def setMeasurer(self, measurer: androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.Measurer, /) -> None: ...
    def setOptimizationLevel(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPadding(self, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPass(self, pass_: int | java.jint | java.lang.Integer, /) -> None: ...
    def setRtl(self, isRtl: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def updateChildrenFromSolver(self, system: androidx.constraintlayout.core.LinearSystem, flags: java.chaquopy.JavaArrayJBoolean, /) -> bool: ...
    def updateFromRuns(self, updateHorizontal: bool | java.jboolean | java.lang.Boolean, updateVertical: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def updateHierarchy(self) -> None: ...

class Flow(VirtualLayout):
    HORIZONTAL_ALIGN_START: typing.ClassVar[int] = ...
    HORIZONTAL_ALIGN_END: typing.ClassVar[int] = ...
    HORIZONTAL_ALIGN_CENTER: typing.ClassVar[int] = ...
    VERTICAL_ALIGN_TOP: typing.ClassVar[int] = ...
    VERTICAL_ALIGN_BOTTOM: typing.ClassVar[int] = ...
    VERTICAL_ALIGN_CENTER: typing.ClassVar[int] = ...
    VERTICAL_ALIGN_BASELINE: typing.ClassVar[int] = ...
    WRAP_NONE: typing.ClassVar[int] = ...
    WRAP_CHAIN: typing.ClassVar[int] = ...
    WRAP_ALIGNED: typing.ClassVar[int] = ...
    WRAP_CHAIN_NEW: typing.ClassVar[int] = ...
    def __init__(self) -> None: ...
    def addToSolver(self, system: androidx.constraintlayout.core.LinearSystem, optimize: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def copy(self, src: ConstraintWidget, map: java.util.HashMap[ConstraintWidget, ConstraintWidget], /) -> None: ...
    def getMaxElementsWrap(self) -> float: ...
    def measure(self, widthMode: int | java.jint | java.lang.Integer, widthSize: int | java.jint | java.lang.Integer, heightMode: int | java.jint | java.lang.Integer, heightSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def setFirstHorizontalBias(self, value: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setFirstHorizontalStyle(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setFirstVerticalBias(self, value: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setFirstVerticalStyle(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHorizontalAlign(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHorizontalBias(self, value: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setHorizontalGap(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHorizontalStyle(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setLastHorizontalBias(self, value: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setLastHorizontalStyle(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setLastVerticalBias(self, value: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setLastVerticalStyle(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMaxElementsWrap(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setOrientation(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setVerticalAlign(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setVerticalBias(self, value: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setVerticalGap(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setVerticalStyle(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setWrapMode(self, value: int | java.jint | java.lang.Integer, /) -> None: ...

class Guideline(ConstraintWidget):
    HORIZONTAL: typing.ClassVar[int] = ...
    VERTICAL: typing.ClassVar[int] = ...
    RELATIVE_PERCENT: typing.ClassVar[int] = ...
    RELATIVE_BEGIN: typing.ClassVar[int] = ...
    RELATIVE_END: typing.ClassVar[int] = ...
    RELATIVE_UNKNOWN: typing.ClassVar[int] = ...
    mRelativePercent: float = ...
    mRelativeBegin: int = ...
    mRelativeEnd: int = ...
    mGuidelineUseRtl: bool = ...
    def __init__(self) -> None: ...
    def addToSolver(self, system: androidx.constraintlayout.core.LinearSystem, optimize: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def allowedInBarrier(self) -> bool: ...
    def copy(self, src: ConstraintWidget, map: java.util.HashMap[ConstraintWidget, ConstraintWidget], /) -> None: ...
    def cyclePosition(self) -> None: ...
    @typing.overload
    def getAnchor(self) -> ConstraintAnchor: ...
    @typing.overload
    def getAnchor(self, anchorType: ConstraintAnchor.Type, /) -> ConstraintAnchor: ...
    def getMinimumPosition(self) -> int: ...
    def getOrientation(self) -> int: ...
    def getRelativeBegin(self) -> int: ...
    def getRelativeBehaviour(self) -> int: ...
    def getRelativeEnd(self) -> int: ...
    def getRelativePercent(self) -> float: ...
    def getType(self) -> str: ...
    def isPercent(self) -> bool: ...
    def isResolvedHorizontally(self) -> bool: ...
    def isResolvedVertically(self) -> bool: ...
    def setFinalValue(self, position: int | java.jint | java.lang.Integer, /) -> None: ...
    def setGuideBegin(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setGuideEnd(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setGuidePercent(self, value: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def setGuidePercent(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMinimumPosition(self, minimum: int | java.jint | java.lang.Integer, /) -> None: ...
    def setOrientation(self, orientation: int | java.jint | java.lang.Integer, /) -> None: ...
    def updateFromSolver(self, system: androidx.constraintlayout.core.LinearSystem, optimize: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class Helper(java.lang.Object):
    def add(self, arg1: ConstraintWidget, /) -> None: ...
    def removeAllIds(self) -> None: ...
    def updateConstraints(self, arg1: ConstraintWidgetContainer, /) -> None: ...

class HelperWidget(ConstraintWidget, Helper):
    mWidgets: java.chaquopy.JavaArray[ConstraintWidget] = ...
    mWidgetsCount: int = ...
    def __init__(self) -> None: ...
    def add(self, widget: ConstraintWidget, /) -> None: ...
    def addDependents(self, dependencyLists: java.util.ArrayList[androidx.constraintlayout.core.widgets.analyzer.WidgetGroup], orientation: int | java.jint | java.lang.Integer, group: androidx.constraintlayout.core.widgets.analyzer.WidgetGroup, /) -> None: ...
    def copy(self, src: ConstraintWidget, map: java.util.HashMap[ConstraintWidget, ConstraintWidget], /) -> None: ...
    def findGroupInDependents(self, orientation: int | java.jint | java.lang.Integer, /) -> int: ...
    def removeAllIds(self) -> None: ...
    def updateConstraints(self, container: ConstraintWidgetContainer, /) -> None: ...

class Optimizer(java.lang.Object):
    OPTIMIZATION_NONE: typing.ClassVar[int] = ...
    OPTIMIZATION_DIRECT: typing.ClassVar[int] = ...
    OPTIMIZATION_BARRIER: typing.ClassVar[int] = ...
    OPTIMIZATION_CHAIN: typing.ClassVar[int] = ...
    OPTIMIZATION_DIMENSIONS: typing.ClassVar[int] = ...
    OPTIMIZATION_RATIO: typing.ClassVar[int] = ...
    OPTIMIZATION_GROUPS: typing.ClassVar[int] = ...
    OPTIMIZATION_GRAPH: typing.ClassVar[int] = ...
    OPTIMIZATION_GRAPH_WRAP: typing.ClassVar[int] = ...
    OPTIMIZATION_CACHE_MEASURES: typing.ClassVar[int] = ...
    OPTIMIZATION_DEPENDENCY_ORDERING: typing.ClassVar[int] = ...
    OPTIMIZATION_GROUPING: typing.ClassVar[int] = ...
    OPTIMIZATION_STANDARD: typing.ClassVar[int] = ...
    def __init__(self) -> None: ...
    @staticmethod
    def enabled(optimizationLevel: int | java.jint | java.lang.Integer, optimization: int | java.jint | java.lang.Integer, /) -> bool: ...

class Placeholder(VirtualLayout):
    def __init__(self) -> None: ...
    def addToSolver(self, system: androidx.constraintlayout.core.LinearSystem, optimize: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def measure(self, widthMode: int | java.jint | java.lang.Integer, widthSize: int | java.jint | java.lang.Integer, heightMode: int | java.jint | java.lang.Integer, heightSize: int | java.jint | java.lang.Integer, /) -> None: ...

class Rectangle(java.lang.Object):
    x: int = ...
    y: int = ...
    width: int = ...
    height: int = ...
    def __init__(self) -> None: ...
    def contains(self, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, /) -> bool: ...
    def getCenterX(self) -> int: ...
    def getCenterY(self) -> int: ...
    def setBounds(self, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...

class VirtualLayout(HelperWidget):
    mMeasure: androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.Measure = ...
    def __init__(self) -> None: ...
    def applyRtl(self, isRtl: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def captureWidgets(self) -> None: ...
    def contains(self, widgets: java.util.HashSet[ConstraintWidget], /) -> bool: ...
    def getMeasuredHeight(self) -> int: ...
    def getMeasuredWidth(self) -> int: ...
    def getPaddingBottom(self) -> int: ...
    def getPaddingLeft(self) -> int: ...
    def getPaddingRight(self) -> int: ...
    def getPaddingTop(self) -> int: ...
    @typing.overload
    def measure(self, widthMode: int | java.jint | java.lang.Integer, widthSize: int | java.jint | java.lang.Integer, heightMode: int | java.jint | java.lang.Integer, heightSize: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def measure(self, widget: ConstraintWidget, horizontalBehavior: ConstraintWidget.DimensionBehaviour, horizontalDimension: int | java.jint | java.lang.Integer, verticalBehavior: ConstraintWidget.DimensionBehaviour, verticalDimension: int | java.jint | java.lang.Integer, /) -> None: ...
    def measureChildren(self) -> bool: ...
    def needSolverPass(self) -> bool: ...
    def needsCallbackFromSolver(self, value: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setMeasure(self, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPadding(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPaddingBottom(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPaddingEnd(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPaddingLeft(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPaddingRight(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPaddingStart(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPaddingTop(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def updateConstraints(self, container: ConstraintWidgetContainer, /) -> None: ...

class WidgetContainer(ConstraintWidget):
    mChildren: java.util.ArrayList[ConstraintWidget] = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def add(self, widget: ConstraintWidget, /) -> None: ...
    @typing.overload
    def add(self, *widgets: ConstraintWidget) -> None: ...
    def getChildren(self) -> java.util.ArrayList[ConstraintWidget]: ...
    def getRootConstraintContainer(self) -> ConstraintWidgetContainer: ...
    def layout(self) -> None: ...
    def remove(self, widget: ConstraintWidget, /) -> None: ...
    def removeAllChildren(self) -> None: ...
    def reset(self) -> None: ...
    def resetSolverVariables(self, cache: androidx.constraintlayout.core.Cache, /) -> None: ...
    def setOffset(self, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, /) -> None: ...
