import typing

import java
import java.chaquopy
import java.lang
import java.util.concurrent
import kotlin
import kotlin.coroutines
import kotlin.coroutines.jvm.internal
import kotlin.jvm.functions
import kotlinx.coroutines
import kotlinx.coroutines.channels
import kotlinx.coroutines.flow
import kotlinx.coroutines.internal

class AbortFlowException(java.util.concurrent.CancellationException):
    def __init__(self, owner: kotlinx.coroutines.flow.FlowCollector[java.lang.Object], /) -> None: ...
    def fillInStackTrace(self) -> java.lang.Throwable: ...
    def getOwner(self) -> kotlinx.coroutines.flow.FlowCollector[java.lang.Object]: ...

_ChannelFlow__T = typing.TypeVar('_ChannelFlow__T')  # <T>
class ChannelFlow(FusibleFlow[_ChannelFlow__T], typing.Generic[_ChannelFlow__T]):
    context: kotlin.coroutines.CoroutineContext = ...
    capacity: int = ...
    def __init__(self, context: kotlin.coroutines.CoroutineContext, capacity: int | java.jint | java.lang.Integer, /) -> None: ...
    def additionalToStringProps(self) -> str: ...
    def broadcastImpl(self, scope: kotlinx.coroutines.CoroutineScope, start: kotlinx.coroutines.CoroutineStart, /) -> kotlinx.coroutines.channels.BroadcastChannel[_ChannelFlow__T]: ...
    def collect(self, arg1: kotlinx.coroutines.flow.FlowCollector[_ChannelFlow__T], completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def collectTo(self, arg1: kotlinx.coroutines.channels.ProducerScope[_ChannelFlow__T], arg2: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def create(self, arg1: kotlin.coroutines.CoroutineContext, arg2: int | java.jint | java.lang.Integer, /) -> ChannelFlow[_ChannelFlow__T]: ...
    def fuse(self, context: kotlin.coroutines.CoroutineContext, capacity: int | java.jint | java.lang.Integer, /) -> FusibleFlow[_ChannelFlow__T]: ...
    def produceImpl(self, scope: kotlinx.coroutines.CoroutineScope, /) -> kotlinx.coroutines.channels.ReceiveChannel[_ChannelFlow__T]: ...
    def toString(self) -> str: ...

class ChannelFlowKt(java.lang.Object):
    _asChannelFlow__T = typing.TypeVar('_asChannelFlow__T')  # <T>
    @staticmethod
    def asChannelFlow(this_asChannelFlow: kotlinx.coroutines.flow.Flow[_asChannelFlow__T], /) -> ChannelFlow[_asChannelFlow__T]: ...

_ChannelFlowMerge__T = typing.TypeVar('_ChannelFlowMerge__T')  # <T>
class ChannelFlowMerge(ChannelFlow[_ChannelFlowMerge__T], typing.Generic[_ChannelFlowMerge__T]):
    def __init__(self, flow: kotlinx.coroutines.flow.Flow[kotlinx.coroutines.flow.Flow[_ChannelFlowMerge__T]], concurrency: int | java.jint | java.lang.Integer, context: kotlin.coroutines.CoroutineContext, capacity: int | java.jint | java.lang.Integer, /) -> None: ...
    def additionalToStringProps(self) -> str: ...
    def collectTo(self, scope: kotlinx.coroutines.channels.ProducerScope[_ChannelFlowMerge__T], completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def create(self, context: kotlin.coroutines.CoroutineContext, capacity: int | java.jint | java.lang.Integer, /) -> ChannelFlow[_ChannelFlowMerge__T]: ...
    def produceImpl(self, scope: kotlinx.coroutines.CoroutineScope, /) -> kotlinx.coroutines.channels.ReceiveChannel[_ChannelFlowMerge__T]: ...

_ChannelFlowOperator__S = typing.TypeVar('_ChannelFlowOperator__S')  # <S>
_ChannelFlowOperator__T = typing.TypeVar('_ChannelFlowOperator__T')  # <T>
class ChannelFlowOperator(ChannelFlow[_ChannelFlowOperator__T], typing.Generic[_ChannelFlowOperator__S, _ChannelFlowOperator__T]):
    flow: kotlinx.coroutines.flow.Flow[_ChannelFlowOperator__S] = ...
    def __init__(self, flow: kotlinx.coroutines.flow.Flow[_ChannelFlowOperator__S], context: kotlin.coroutines.CoroutineContext, capacity: int | java.jint | java.lang.Integer, /) -> None: ...
    def collect(self, arg1: kotlinx.coroutines.flow.FlowCollector[_ChannelFlowOperator__T], completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def collectTo(self, arg1: kotlinx.coroutines.channels.ProducerScope[_ChannelFlowOperator__T], completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def flowCollect(self, arg1: kotlinx.coroutines.flow.FlowCollector[_ChannelFlowOperator__T], arg2: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def toString(self) -> str: ...

_ChannelFlowOperatorImpl__T = typing.TypeVar('_ChannelFlowOperatorImpl__T')  # <T>
class ChannelFlowOperatorImpl(ChannelFlowOperator[_ChannelFlowOperatorImpl__T, _ChannelFlowOperatorImpl__T], typing.Generic[_ChannelFlowOperatorImpl__T]):
    def __init__(self, flow: kotlinx.coroutines.flow.Flow[_ChannelFlowOperatorImpl__T], context: kotlin.coroutines.CoroutineContext, capacity: int | java.jint | java.lang.Integer, /) -> None: ...
    def create(self, context: kotlin.coroutines.CoroutineContext, capacity: int | java.jint | java.lang.Integer, /) -> ChannelFlow[_ChannelFlowOperatorImpl__T]: ...
    def flowCollect(self, collector: kotlinx.coroutines.flow.FlowCollector[_ChannelFlowOperatorImpl__T], completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...

_ChannelFlowTransformLatest__T = typing.TypeVar('_ChannelFlowTransformLatest__T')  # <T>
_ChannelFlowTransformLatest__R = typing.TypeVar('_ChannelFlowTransformLatest__R')  # <R>
class ChannelFlowTransformLatest(ChannelFlowOperator[_ChannelFlowTransformLatest__T, _ChannelFlowTransformLatest__R], typing.Generic[_ChannelFlowTransformLatest__T, _ChannelFlowTransformLatest__R]):
    def __init__(self, transform: kotlin.jvm.functions.Function3[kotlinx.coroutines.flow.FlowCollector[_ChannelFlowTransformLatest__R], _ChannelFlowTransformLatest__T, kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], flow: kotlinx.coroutines.flow.Flow[_ChannelFlowTransformLatest__T], context: kotlin.coroutines.CoroutineContext, capacity: int | java.jint | java.lang.Integer, /) -> None: ...
    def create(self, context: kotlin.coroutines.CoroutineContext, capacity: int | java.jint | java.lang.Integer, /) -> ChannelFlow[_ChannelFlowTransformLatest__R]: ...
    def flowCollect(self, collector: kotlinx.coroutines.flow.FlowCollector[_ChannelFlowTransformLatest__R], completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...

_ChannelLimitedFlowMerge__T = typing.TypeVar('_ChannelLimitedFlowMerge__T')  # <T>
class ChannelLimitedFlowMerge(ChannelFlow[_ChannelLimitedFlowMerge__T], typing.Generic[_ChannelLimitedFlowMerge__T]):
    def __init__(self, flows: java.lang.Iterable[kotlinx.coroutines.flow.Flow[_ChannelLimitedFlowMerge__T]], context: kotlin.coroutines.CoroutineContext, capacity: int | java.jint | java.lang.Integer, /) -> None: ...
    def collectTo(self, scope: kotlinx.coroutines.channels.ProducerScope[_ChannelLimitedFlowMerge__T], completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def create(self, context: kotlin.coroutines.CoroutineContext, capacity: int | java.jint | java.lang.Integer, /) -> ChannelFlow[_ChannelLimitedFlowMerge__T]: ...
    def produceImpl(self, scope: kotlinx.coroutines.CoroutineScope, /) -> kotlinx.coroutines.channels.ReceiveChannel[_ChannelLimitedFlowMerge__T]: ...

class ChildCancelledException(java.util.concurrent.CancellationException):
    def __init__(self) -> None: ...
    def fillInStackTrace(self) -> java.lang.Throwable: ...

class CombineKt(java.lang.Object):
    _combineInternal__R = typing.TypeVar('_combineInternal__R')  # <R>
    _combineInternal__T = typing.TypeVar('_combineInternal__T')  # <T>
    @staticmethod
    def combineInternal(this_combineInternal: kotlinx.coroutines.flow.FlowCollector[_combineInternal__R], flows: java.chaquopy.JavaArray[kotlinx.coroutines.flow.Flow[_combineInternal__T]], arrayFactory: kotlin.jvm.functions.Function0[java.chaquopy.JavaArray[_combineInternal__T]], transform: kotlin.jvm.functions.Function3[kotlinx.coroutines.flow.FlowCollector[_combineInternal__R], java.chaquopy.JavaArray[_combineInternal__T], kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    _combineTransformInternal__T1 = typing.TypeVar('_combineTransformInternal__T1')  # <T1>
    _combineTransformInternal__T2 = typing.TypeVar('_combineTransformInternal__T2')  # <T2>
    _combineTransformInternal__R = typing.TypeVar('_combineTransformInternal__R')  # <R>
    @staticmethod
    def combineTransformInternal(this_combineTransformInternal: kotlinx.coroutines.flow.FlowCollector[_combineTransformInternal__R], first: kotlinx.coroutines.flow.Flow[_combineTransformInternal__T1], second: kotlinx.coroutines.flow.Flow[_combineTransformInternal__T2], transform: kotlin.jvm.functions.Function4[kotlinx.coroutines.flow.FlowCollector[_combineTransformInternal__R], _combineTransformInternal__T1, _combineTransformInternal__T2, kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    @staticmethod
    def getNull() -> kotlinx.coroutines.internal.Symbol: ...
    _zipImpl__T1 = typing.TypeVar('_zipImpl__T1')  # <T1>
    _zipImpl__T2 = typing.TypeVar('_zipImpl__T2')  # <T2>
    _zipImpl__R = typing.TypeVar('_zipImpl__R')  # <R>
    @staticmethod
    def zipImpl(flow: kotlinx.coroutines.flow.Flow[_zipImpl__T1], flow2: kotlinx.coroutines.flow.Flow[_zipImpl__T2], transform: kotlin.jvm.functions.Function3[_zipImpl__T1, _zipImpl__T2, kotlin.coroutines.Continuation[_zipImpl__R], java.lang.Object], /) -> kotlinx.coroutines.flow.Flow[_zipImpl__R]: ...

class DownstreamExceptionElement(kotlin.coroutines.CoroutineContext.Element):
    e: java.lang.Throwable = ...
    Key: typing.ClassVar[DownstreamExceptionElement.Key] = ...
    def __init__(self, e: java.lang.Throwable, /) -> None: ...
    _fold__R = typing.TypeVar('_fold__R')  # <R>
    def fold(self, initial: _fold__R, operation: kotlin.jvm.functions.Function2[_fold__R, kotlin.coroutines.CoroutineContext.Element, _fold__R], /) -> _fold__R: ...
    _get__E = typing.TypeVar('_get__E')  # <E>
    def get(self, key: kotlin.coroutines.CoroutineContext.Key[_get__E], /) -> _get__E: ...
    def getKey(self) -> kotlin.coroutines.CoroutineContext.Key[java.lang.Object]: ...
    def minusKey(self, key: kotlin.coroutines.CoroutineContext.Key[java.lang.Object], /) -> kotlin.coroutines.CoroutineContext: ...
    def plus(self, context: kotlin.coroutines.CoroutineContext, /) -> kotlin.coroutines.CoroutineContext: ...

    class Key(kotlin.coroutines.CoroutineContext.Key[DownstreamExceptionElement]): ...

_FlowCoroutine__T = typing.TypeVar('_FlowCoroutine__T')  # <T>
class FlowCoroutine(kotlinx.coroutines.internal.ScopeCoroutine[_FlowCoroutine__T], typing.Generic[_FlowCoroutine__T]):
    def __init__(self, context: kotlin.coroutines.CoroutineContext, uCont: kotlin.coroutines.Continuation[_FlowCoroutine__T], /) -> None: ...
    def childCancelled(self, cause: java.lang.Throwable, /) -> bool: ...

class FlowCoroutineKt(java.lang.Object):
    _flowProduce__T = typing.TypeVar('_flowProduce__T')  # <T>
    @staticmethod
    def flowProduce(this_flowProduce: kotlinx.coroutines.CoroutineScope, context: kotlin.coroutines.CoroutineContext, capacity: int | java.jint | java.lang.Integer, block: kotlin.jvm.functions.Function2[kotlinx.coroutines.channels.ProducerScope[_flowProduce__T], kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], /) -> kotlinx.coroutines.channels.ReceiveChannel[_flowProduce__T]: ...
    _flowScope__R = typing.TypeVar('_flowScope__R')  # <R>
    @staticmethod
    def flowScope(block: kotlin.jvm.functions.Function2[kotlinx.coroutines.CoroutineScope, kotlin.coroutines.Continuation[_flowScope__R], java.lang.Object], completion: kotlin.coroutines.Continuation[_flowScope__R], /) -> java.lang.Object: ...
    _scopedFlow__R = typing.TypeVar('_scopedFlow__R')  # <R>
    @staticmethod
    def scopedFlow(block: kotlin.jvm.functions.Function3[kotlinx.coroutines.CoroutineScope, kotlinx.coroutines.flow.FlowCollector[_scopedFlow__R], kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], /) -> kotlinx.coroutines.flow.Flow[_scopedFlow__R]: ...

class FlowExceptions_commonKt(java.lang.Object):
    @staticmethod
    def checkIndexOverflow(index: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def checkOwnership(this_checkOwnership: AbortFlowException, owner: kotlinx.coroutines.flow.FlowCollector[java.lang.Object], /) -> None: ...

_FlowProduceCoroutine__T = typing.TypeVar('_FlowProduceCoroutine__T')  # <T>
class FlowProduceCoroutine(kotlinx.coroutines.channels.ProducerCoroutine[_FlowProduceCoroutine__T], typing.Generic[_FlowProduceCoroutine__T]):
    def __init__(self, parentContext: kotlin.coroutines.CoroutineContext, channel: kotlinx.coroutines.channels.Channel[_FlowProduceCoroutine__T], /) -> None: ...
    def childCancelled(self, cause: java.lang.Throwable, /) -> bool: ...

_FusibleFlow__T = typing.TypeVar('_FusibleFlow__T')  # <T>
class FusibleFlow(kotlinx.coroutines.flow.Flow[_FusibleFlow__T], typing.Generic[_FusibleFlow__T]):
    def fuse(self, arg1: kotlin.coroutines.CoroutineContext, arg2: int | java.jint | java.lang.Integer, /) -> FusibleFlow[_FusibleFlow__T]: ...

    class DefaultImpls(java.lang.Object): ...

class NoOpContinuation(kotlin.coroutines.Continuation[java.lang.Object]):
    INSTANCE: typing.ClassVar[NoOpContinuation] = ...
    def getContext(self) -> kotlin.coroutines.CoroutineContext: ...
    def resumeWith(self, result: java.lang.Object | int | bool | float | str, /) -> None: ...

class NopCollector(kotlinx.coroutines.flow.FlowCollector[java.lang.Object]):
    INSTANCE: typing.ClassVar[NopCollector] = ...
    def emit(self, value: java.lang.Object | int | bool | float | str, completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...

class NullSurrogateKt(java.lang.Object):
    NULL: typing.ClassVar[kotlinx.coroutines.internal.Symbol] = ...
    DONE: typing.ClassVar[kotlinx.coroutines.internal.Symbol] = ...

_SafeCollector__T = typing.TypeVar('_SafeCollector__T')  # <T>
class SafeCollector(kotlin.coroutines.jvm.internal.ContinuationImpl, kotlinx.coroutines.flow.FlowCollector[_SafeCollector__T], typing.Generic[_SafeCollector__T]):
    collectContextSize: int = ...
    collector: kotlinx.coroutines.flow.FlowCollector[_SafeCollector__T] = ...
    collectContext: kotlin.coroutines.CoroutineContext = ...
    def __init__(self, collector: kotlinx.coroutines.flow.FlowCollector[_SafeCollector__T], collectContext: kotlin.coroutines.CoroutineContext, /) -> None: ...
    def emit(self, value: _SafeCollector__T, completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
    def getContext(self) -> kotlin.coroutines.CoroutineContext: ...
    def invokeSuspend(self, result: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def releaseIntercepted(self) -> None: ...

class SafeCollectorKt(java.lang.Object): ...

class SafeCollector_commonKt(java.lang.Object):
    @staticmethod
    def checkContext(this_checkContext: SafeCollector[java.lang.Object], currentContext: kotlin.coroutines.CoroutineContext, /) -> None: ...
    @staticmethod
    def transitiveCoroutineParent(this_transitiveCoroutineParent: kotlinx.coroutines.Job, collectJob: kotlinx.coroutines.Job, /) -> kotlinx.coroutines.Job: ...
    _unsafeFlow__T = typing.TypeVar('_unsafeFlow__T')  # <T>
    @staticmethod
    def unsafeFlow(block: kotlin.jvm.functions.Function2[kotlinx.coroutines.flow.FlowCollector[_unsafeFlow__T], kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], /) -> kotlinx.coroutines.flow.Flow[_unsafeFlow__T]: ...

_SendingCollector__T = typing.TypeVar('_SendingCollector__T')  # <T>
class SendingCollector(kotlinx.coroutines.flow.FlowCollector[_SendingCollector__T], typing.Generic[_SendingCollector__T]):
    def __init__(self, channel: kotlinx.coroutines.channels.SendChannel[_SendingCollector__T], /) -> None: ...
    def emit(self, value: _SendingCollector__T, completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...

_UndispatchedContextCollector__T = typing.TypeVar('_UndispatchedContextCollector__T')  # <T>
class UndispatchedContextCollector(kotlinx.coroutines.flow.FlowCollector[_UndispatchedContextCollector__T], typing.Generic[_UndispatchedContextCollector__T]):
    def __init__(self, downstream: kotlinx.coroutines.flow.FlowCollector[_UndispatchedContextCollector__T], emitContext: kotlin.coroutines.CoroutineContext, /) -> None: ...
    def emit(self, value: _UndispatchedContextCollector__T, completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...
