import typing

import java
import java.lang
import java.util
import kotlin
import kotlin.collections
import kotlin.jvm.internal.markers
import kotlin.random

class CharProgression(java.lang.Iterable[java.lang.Character], kotlin.jvm.internal.markers.KMappedMarker):
    Companion: typing.ClassVar[CharProgression.Companion] = ...
    def __init__(self, start: str | java.jchar | java.lang.Character, endInclusive: str | java.jchar | java.lang.Character, step: int | java.jint | java.lang.Integer, /) -> None: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getFirst(self) -> str: ...
    def getLast(self) -> str: ...
    def getStep(self) -> int: ...
    def hashCode(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def iterator(self) -> kotlin.collections.CharIterator: ...
    def toString(self) -> str: ...

    class Companion(java.lang.Object):
        def fromClosedRange(self, rangeStart: str | java.jchar | java.lang.Character, rangeEnd: str | java.jchar | java.lang.Character, step: int | java.jint | java.lang.Integer, /) -> CharProgression: ...

class CharProgressionIterator(kotlin.collections.CharIterator):
    def __init__(self, first: str | java.jchar | java.lang.Character, last: str | java.jchar | java.lang.Character, step: int | java.jint | java.lang.Integer, /) -> None: ...
    def getStep(self) -> int: ...
    def hasNext(self) -> bool: ...
    def nextChar(self) -> str: ...

class CharRange(CharProgression, ClosedRange[java.lang.Character]):
    Companion: typing.ClassVar[CharRange.Companion] = ...
    def __init__(self, start: str | java.jchar | java.lang.Character, endInclusive: str | java.jchar | java.lang.Character, /) -> None: ...
    def contains(self, value: str | java.jchar | java.lang.Character, /) -> bool: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getEndInclusive(self) -> str: ...
    def getStart(self) -> str: ...
    def hashCode(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def toString(self) -> str: ...

    class Companion(java.lang.Object):
        def getEMPTY(self) -> CharRange: ...

class ClosedDoubleRange(ClosedFloatingPointRange[java.lang.Double]):
    def __init__(self, start: float | java.jdouble | java.lang.Double, endInclusive: float | java.jdouble | java.lang.Double, /) -> None: ...
    def contains(self, value: float | java.jdouble | java.lang.Double, /) -> bool: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getEndInclusive(self) -> float: ...
    def getStart(self) -> float: ...
    def hashCode(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def lessThanOrEquals(self, a: float | java.jdouble | java.lang.Double, b: float | java.jdouble | java.lang.Double, /) -> bool: ...
    def toString(self) -> str: ...

class ClosedFloatRange(ClosedFloatingPointRange[java.lang.Float]):
    def __init__(self, start: float | java.jfloat | java.lang.Float, endInclusive: float | java.jfloat | java.lang.Float, /) -> None: ...
    def contains(self, value: float | java.jfloat | java.lang.Float, /) -> bool: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getEndInclusive(self) -> float: ...
    def getStart(self) -> float: ...
    def hashCode(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def lessThanOrEquals(self, a: float | java.jfloat | java.lang.Float, b: float | java.jfloat | java.lang.Float, /) -> bool: ...
    def toString(self) -> str: ...

_ClosedFloatingPointRange__T = typing.TypeVar('_ClosedFloatingPointRange__T')  # <T>
class ClosedFloatingPointRange(ClosedRange[_ClosedFloatingPointRange__T], typing.Generic[_ClosedFloatingPointRange__T]):
    def contains(self, arg1: _ClosedFloatingPointRange__T, /) -> bool: ...
    def isEmpty(self) -> bool: ...
    def lessThanOrEquals(self, arg1: _ClosedFloatingPointRange__T, arg2: _ClosedFloatingPointRange__T, /) -> bool: ...

    class DefaultImpls(java.lang.Object):
        _contains__T = typing.TypeVar('_contains__T')  # <T>
        @staticmethod
        def contains(this: ClosedFloatingPointRange[_contains__T], value: _contains__T, /) -> bool: ...
        @staticmethod
        def isEmpty(this: ClosedFloatingPointRange[java.lang.Object], /) -> bool: ...

_ClosedRange__T = typing.TypeVar('_ClosedRange__T')  # <T>
class ClosedRange(java.lang.Object, typing.Generic[_ClosedRange__T]):
    def contains(self, arg1: _ClosedRange__T, /) -> bool: ...
    def getEndInclusive(self) -> _ClosedRange__T: ...
    def getStart(self) -> _ClosedRange__T: ...
    def isEmpty(self) -> bool: ...

    class DefaultImpls(java.lang.Object):
        _contains__T = typing.TypeVar('_contains__T')  # <T>
        @staticmethod
        def contains(this: ClosedRange[_contains__T], value: _contains__T, /) -> bool: ...
        @staticmethod
        def isEmpty(this: ClosedRange[java.lang.Object], /) -> bool: ...

_ComparableRange__T = typing.TypeVar('_ComparableRange__T')  # <T>
class ComparableRange(ClosedRange[_ComparableRange__T], typing.Generic[_ComparableRange__T]):
    def __init__(self, start: _ComparableRange__T, endInclusive: _ComparableRange__T, /) -> None: ...
    def contains(self, value: _ComparableRange__T, /) -> bool: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getEndInclusive(self) -> _ComparableRange__T: ...
    def getStart(self) -> _ComparableRange__T: ...
    def hashCode(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def toString(self) -> str: ...

class IntProgression(java.lang.Iterable[java.lang.Integer], kotlin.jvm.internal.markers.KMappedMarker):
    Companion: typing.ClassVar[IntProgression.Companion] = ...
    def __init__(self, start: int | java.jint | java.lang.Integer, endInclusive: int | java.jint | java.lang.Integer, step: int | java.jint | java.lang.Integer, /) -> None: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getFirst(self) -> int: ...
    def getLast(self) -> int: ...
    def getStep(self) -> int: ...
    def hashCode(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def iterator(self) -> kotlin.collections.IntIterator: ...
    def toString(self) -> str: ...

    class Companion(java.lang.Object):
        def fromClosedRange(self, rangeStart: int | java.jint | java.lang.Integer, rangeEnd: int | java.jint | java.lang.Integer, step: int | java.jint | java.lang.Integer, /) -> IntProgression: ...

class IntProgressionIterator(kotlin.collections.IntIterator):
    def __init__(self, first: int | java.jint | java.lang.Integer, last: int | java.jint | java.lang.Integer, step: int | java.jint | java.lang.Integer, /) -> None: ...
    def getStep(self) -> int: ...
    def hasNext(self) -> bool: ...
    def nextInt(self) -> int: ...

class IntRange(IntProgression, ClosedRange[java.lang.Integer]):
    Companion: typing.ClassVar[IntRange.Companion] = ...
    def __init__(self, start: int | java.jint | java.lang.Integer, endInclusive: int | java.jint | java.lang.Integer, /) -> None: ...
    def contains(self, value: int | java.jint | java.lang.Integer, /) -> bool: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getEndInclusive(self) -> int: ...
    def getStart(self) -> int: ...
    def hashCode(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def toString(self) -> str: ...

    class Companion(java.lang.Object):
        def getEMPTY(self) -> IntRange: ...

class LongProgression(java.lang.Iterable[java.lang.Long], kotlin.jvm.internal.markers.KMappedMarker):
    Companion: typing.ClassVar[LongProgression.Companion] = ...
    def __init__(self, start: int | java.jlong | java.lang.Long, endInclusive: int | java.jlong | java.lang.Long, step: int | java.jlong | java.lang.Long, /) -> None: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getFirst(self) -> int: ...
    def getLast(self) -> int: ...
    def getStep(self) -> int: ...
    def hashCode(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def iterator(self) -> kotlin.collections.LongIterator: ...
    def toString(self) -> str: ...

    class Companion(java.lang.Object):
        def fromClosedRange(self, rangeStart: int | java.jlong | java.lang.Long, rangeEnd: int | java.jlong | java.lang.Long, step: int | java.jlong | java.lang.Long, /) -> LongProgression: ...

class LongProgressionIterator(kotlin.collections.LongIterator):
    def __init__(self, first: int | java.jlong | java.lang.Long, last: int | java.jlong | java.lang.Long, step: int | java.jlong | java.lang.Long, /) -> None: ...
    def getStep(self) -> int: ...
    def hasNext(self) -> bool: ...
    def nextLong(self) -> int: ...

class LongRange(LongProgression, ClosedRange[java.lang.Long]):
    Companion: typing.ClassVar[LongRange.Companion] = ...
    def __init__(self, start: int | java.jlong | java.lang.Long, endInclusive: int | java.jlong | java.lang.Long, /) -> None: ...
    def contains(self, value: int | java.jlong | java.lang.Long, /) -> bool: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getEndInclusive(self) -> int: ...
    def getStart(self) -> int: ...
    def hashCode(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def toString(self) -> str: ...

    class Companion(java.lang.Object):
        def getEMPTY(self) -> LongRange: ...

class RangesKt(RangesKt___RangesKt): ...

class RangesKt__RangesKt(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def checkStepIsPositive(isPositive: bool | java.jboolean | java.lang.Boolean, step: java.lang.Number, /) -> None: ...
    _rangeTo_2__T = typing.TypeVar('_rangeTo_2__T')  # <T>
    @typing.overload
    @staticmethod
    def rangeTo(this_rangeTo: float | java.jdouble | java.lang.Double, that: float | java.jdouble | java.lang.Double, /) -> ClosedFloatingPointRange[java.lang.Double]: ...
    @typing.overload
    @staticmethod
    def rangeTo(this_rangeTo: float | java.jfloat | java.lang.Float, that: float | java.jfloat | java.lang.Float, /) -> ClosedFloatingPointRange[java.lang.Float]: ...
    @typing.overload
    @staticmethod
    def rangeTo(this_rangeTo: _rangeTo_2__T, that: _rangeTo_2__T, /) -> ClosedRange[_rangeTo_2__T]: ...

class RangesKt___RangesKt(RangesKt__RangesKt):
    def __init__(self) -> None: ...
    @typing.overload
    @staticmethod
    def byteRangeContains(this_contains: ClosedRange[java.lang.Byte], value: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    @staticmethod
    def byteRangeContains(this_contains: ClosedRange[java.lang.Byte], value: int | java.jlong | java.lang.Long, /) -> bool: ...
    @typing.overload
    @staticmethod
    def byteRangeContains(this_contains: ClosedRange[java.lang.Byte], value: int | java.jshort | java.lang.Short, /) -> bool: ...
    _coerceAtLeast_5__T = typing.TypeVar('_coerceAtLeast_5__T')  # <T>
    @typing.overload
    @staticmethod
    def coerceAtLeast(this_coerceAtLeast: int | java.jbyte | java.lang.Byte, minimumValue: int | java.jbyte | java.lang.Byte, /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceAtLeast(this_coerceAtLeast: float | java.jdouble | java.lang.Double, minimumValue: float | java.jdouble | java.lang.Double, /) -> float: ...
    @typing.overload
    @staticmethod
    def coerceAtLeast(this_coerceAtLeast: float | java.jfloat | java.lang.Float, minimumValue: float | java.jfloat | java.lang.Float, /) -> float: ...
    @typing.overload
    @staticmethod
    def coerceAtLeast(this_coerceAtLeast: int | java.jint | java.lang.Integer, minimumValue: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceAtLeast(this_coerceAtLeast: int | java.jlong | java.lang.Long, minimumValue: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceAtLeast(this_coerceAtLeast: _coerceAtLeast_5__T, minimumValue: _coerceAtLeast_5__T, /) -> _coerceAtLeast_5__T: ...
    @typing.overload
    @staticmethod
    def coerceAtLeast(this_coerceAtLeast: int | java.jshort | java.lang.Short, minimumValue: int | java.jshort | java.lang.Short, /) -> int: ...
    _coerceAtMost_5__T = typing.TypeVar('_coerceAtMost_5__T')  # <T>
    @typing.overload
    @staticmethod
    def coerceAtMost(this_coerceAtMost: int | java.jbyte | java.lang.Byte, maximumValue: int | java.jbyte | java.lang.Byte, /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceAtMost(this_coerceAtMost: float | java.jdouble | java.lang.Double, maximumValue: float | java.jdouble | java.lang.Double, /) -> float: ...
    @typing.overload
    @staticmethod
    def coerceAtMost(this_coerceAtMost: float | java.jfloat | java.lang.Float, maximumValue: float | java.jfloat | java.lang.Float, /) -> float: ...
    @typing.overload
    @staticmethod
    def coerceAtMost(this_coerceAtMost: int | java.jint | java.lang.Integer, maximumValue: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceAtMost(this_coerceAtMost: int | java.jlong | java.lang.Long, maximumValue: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceAtMost(this_coerceAtMost: _coerceAtMost_5__T, maximumValue: _coerceAtMost_5__T, /) -> _coerceAtMost_5__T: ...
    @typing.overload
    @staticmethod
    def coerceAtMost(this_coerceAtMost: int | java.jshort | java.lang.Short, maximumValue: int | java.jshort | java.lang.Short, /) -> int: ...
    _coerceIn_2__T = typing.TypeVar('_coerceIn_2__T')  # <T>
    _coerceIn_3__T = typing.TypeVar('_coerceIn_3__T')  # <T>
    _coerceIn_9__T = typing.TypeVar('_coerceIn_9__T')  # <T>
    @typing.overload
    @staticmethod
    def coerceIn(this_coerceIn: int | java.jint | java.lang.Integer, range: ClosedRange[java.lang.Integer], /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceIn(this_coerceIn: int | java.jlong | java.lang.Long, range: ClosedRange[java.lang.Long], /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceIn(this_coerceIn: _coerceIn_2__T, range: ClosedFloatingPointRange[_coerceIn_2__T], /) -> _coerceIn_2__T: ...
    @typing.overload
    @staticmethod
    def coerceIn(this_coerceIn: _coerceIn_3__T, range: ClosedRange[_coerceIn_3__T], /) -> _coerceIn_3__T: ...
    @typing.overload
    @staticmethod
    def coerceIn(this_coerceIn: int | java.jbyte | java.lang.Byte, minimumValue: int | java.jbyte | java.lang.Byte, maximumValue: int | java.jbyte | java.lang.Byte, /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceIn(this_coerceIn: float | java.jdouble | java.lang.Double, minimumValue: float | java.jdouble | java.lang.Double, maximumValue: float | java.jdouble | java.lang.Double, /) -> float: ...
    @typing.overload
    @staticmethod
    def coerceIn(this_coerceIn: float | java.jfloat | java.lang.Float, minimumValue: float | java.jfloat | java.lang.Float, maximumValue: float | java.jfloat | java.lang.Float, /) -> float: ...
    @typing.overload
    @staticmethod
    def coerceIn(this_coerceIn: int | java.jint | java.lang.Integer, minimumValue: int | java.jint | java.lang.Integer, maximumValue: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceIn(this_coerceIn: int | java.jlong | java.lang.Long, minimumValue: int | java.jlong | java.lang.Long, maximumValue: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceIn(this_coerceIn: _coerceIn_9__T, minimumValue: _coerceIn_9__T, maximumValue: _coerceIn_9__T, /) -> _coerceIn_9__T: ...
    @typing.overload
    @staticmethod
    def coerceIn(this_coerceIn: int | java.jshort | java.lang.Short, minimumValue: int | java.jshort | java.lang.Short, maximumValue: int | java.jshort | java.lang.Short, /) -> int: ...
    @staticmethod
    def doubleRangeContains(this_contains: ClosedRange[java.lang.Double], value: float | java.jfloat | java.lang.Float, /) -> bool: ...
    @typing.overload
    @staticmethod
    def downTo(this_downTo: int | java.jbyte | java.lang.Byte, to: int | java.jbyte | java.lang.Byte, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def downTo(this_downTo: int | java.jbyte | java.lang.Byte, to: int | java.jint | java.lang.Integer, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def downTo(this_downTo: int | java.jbyte | java.lang.Byte, to: int | java.jlong | java.lang.Long, /) -> LongProgression: ...
    @typing.overload
    @staticmethod
    def downTo(this_downTo: int | java.jbyte | java.lang.Byte, to: int | java.jshort | java.lang.Short, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def downTo(this_downTo: str | java.jchar | java.lang.Character, to: str | java.jchar | java.lang.Character, /) -> CharProgression: ...
    @typing.overload
    @staticmethod
    def downTo(this_downTo: int | java.jint | java.lang.Integer, to: int | java.jbyte | java.lang.Byte, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def downTo(this_downTo: int | java.jint | java.lang.Integer, to: int | java.jint | java.lang.Integer, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def downTo(this_downTo: int | java.jint | java.lang.Integer, to: int | java.jlong | java.lang.Long, /) -> LongProgression: ...
    @typing.overload
    @staticmethod
    def downTo(this_downTo: int | java.jint | java.lang.Integer, to: int | java.jshort | java.lang.Short, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def downTo(this_downTo: int | java.jlong | java.lang.Long, to: int | java.jbyte | java.lang.Byte, /) -> LongProgression: ...
    @typing.overload
    @staticmethod
    def downTo(this_downTo: int | java.jlong | java.lang.Long, to: int | java.jint | java.lang.Integer, /) -> LongProgression: ...
    @typing.overload
    @staticmethod
    def downTo(this_downTo: int | java.jlong | java.lang.Long, to: int | java.jlong | java.lang.Long, /) -> LongProgression: ...
    @typing.overload
    @staticmethod
    def downTo(this_downTo: int | java.jlong | java.lang.Long, to: int | java.jshort | java.lang.Short, /) -> LongProgression: ...
    @typing.overload
    @staticmethod
    def downTo(this_downTo: int | java.jshort | java.lang.Short, to: int | java.jbyte | java.lang.Byte, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def downTo(this_downTo: int | java.jshort | java.lang.Short, to: int | java.jint | java.lang.Integer, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def downTo(this_downTo: int | java.jshort | java.lang.Short, to: int | java.jlong | java.lang.Long, /) -> LongProgression: ...
    @typing.overload
    @staticmethod
    def downTo(this_downTo: int | java.jshort | java.lang.Short, to: int | java.jshort | java.lang.Short, /) -> IntProgression: ...
    @staticmethod
    def floatRangeContains(this_contains: ClosedRange[java.lang.Float], value: float | java.jdouble | java.lang.Double, /) -> bool: ...
    @typing.overload
    @staticmethod
    def intRangeContains(this_contains: ClosedRange[java.lang.Integer], value: int | java.jbyte | java.lang.Byte, /) -> bool: ...
    @typing.overload
    @staticmethod
    def intRangeContains(this_contains: ClosedRange[java.lang.Integer], value: int | java.jlong | java.lang.Long, /) -> bool: ...
    @typing.overload
    @staticmethod
    def intRangeContains(this_contains: ClosedRange[java.lang.Integer], value: int | java.jshort | java.lang.Short, /) -> bool: ...
    @typing.overload
    @staticmethod
    def longRangeContains(this_contains: ClosedRange[java.lang.Long], value: int | java.jbyte | java.lang.Byte, /) -> bool: ...
    @typing.overload
    @staticmethod
    def longRangeContains(this_contains: ClosedRange[java.lang.Long], value: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    @staticmethod
    def longRangeContains(this_contains: ClosedRange[java.lang.Long], value: int | java.jshort | java.lang.Short, /) -> bool: ...
    @typing.overload
    @staticmethod
    def random(this_random: CharRange, random: kotlin.random.Random, /) -> str: ...
    @typing.overload
    @staticmethod
    def random(this_random: IntRange, random: kotlin.random.Random, /) -> int: ...
    @typing.overload
    @staticmethod
    def random(this_random: LongRange, random: kotlin.random.Random, /) -> int: ...
    @typing.overload
    @staticmethod
    def randomOrNull(this_randomOrNull: CharRange, random: kotlin.random.Random, /) -> str: ...
    @typing.overload
    @staticmethod
    def randomOrNull(this_randomOrNull: IntRange, random: kotlin.random.Random, /) -> int: ...
    @typing.overload
    @staticmethod
    def randomOrNull(this_randomOrNull: LongRange, random: kotlin.random.Random, /) -> int: ...
    @typing.overload
    @staticmethod
    def reversed(this_reversed: CharProgression, /) -> CharProgression: ...
    @typing.overload
    @staticmethod
    def reversed(this_reversed: IntProgression, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def reversed(this_reversed: LongProgression, /) -> LongProgression: ...
    @typing.overload
    @staticmethod
    def shortRangeContains(this_contains: ClosedRange[java.lang.Short], value: int | java.jbyte | java.lang.Byte, /) -> bool: ...
    @typing.overload
    @staticmethod
    def shortRangeContains(this_contains: ClosedRange[java.lang.Short], value: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    @staticmethod
    def shortRangeContains(this_contains: ClosedRange[java.lang.Short], value: int | java.jlong | java.lang.Long, /) -> bool: ...
    @typing.overload
    @staticmethod
    def step(this_step: CharProgression, step: int | java.jint | java.lang.Integer, /) -> CharProgression: ...
    @typing.overload
    @staticmethod
    def step(this_step: IntProgression, step: int | java.jint | java.lang.Integer, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def step(this_step: LongProgression, step: int | java.jlong | java.lang.Long, /) -> LongProgression: ...
    @typing.overload
    @staticmethod
    def toByteExactOrNull(this_toByteExactOrNull: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def toByteExactOrNull(this_toByteExactOrNull: float | java.jfloat | java.lang.Float, /) -> int: ...
    @typing.overload
    @staticmethod
    def toByteExactOrNull(this_toByteExactOrNull: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def toByteExactOrNull(this_toByteExactOrNull: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def toByteExactOrNull(this_toByteExactOrNull: int | java.jshort | java.lang.Short, /) -> int: ...
    @typing.overload
    @staticmethod
    def toIntExactOrNull(this_toIntExactOrNull: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def toIntExactOrNull(this_toIntExactOrNull: float | java.jfloat | java.lang.Float, /) -> int: ...
    @typing.overload
    @staticmethod
    def toIntExactOrNull(this_toIntExactOrNull: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def toLongExactOrNull(this_toLongExactOrNull: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def toLongExactOrNull(this_toLongExactOrNull: float | java.jfloat | java.lang.Float, /) -> int: ...
    @typing.overload
    @staticmethod
    def toShortExactOrNull(this_toShortExactOrNull: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def toShortExactOrNull(this_toShortExactOrNull: float | java.jfloat | java.lang.Float, /) -> int: ...
    @typing.overload
    @staticmethod
    def toShortExactOrNull(this_toShortExactOrNull: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def toShortExactOrNull(this_toShortExactOrNull: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def until(this_until: int | java.jbyte | java.lang.Byte, to: int | java.jbyte | java.lang.Byte, /) -> IntRange: ...
    @typing.overload
    @staticmethod
    def until(this_until: int | java.jbyte | java.lang.Byte, to: int | java.jint | java.lang.Integer, /) -> IntRange: ...
    @typing.overload
    @staticmethod
    def until(this_until: int | java.jbyte | java.lang.Byte, to: int | java.jlong | java.lang.Long, /) -> LongRange: ...
    @typing.overload
    @staticmethod
    def until(this_until: int | java.jbyte | java.lang.Byte, to: int | java.jshort | java.lang.Short, /) -> IntRange: ...
    @typing.overload
    @staticmethod
    def until(this_until: str | java.jchar | java.lang.Character, to: str | java.jchar | java.lang.Character, /) -> CharRange: ...
    @typing.overload
    @staticmethod
    def until(this_until: int | java.jint | java.lang.Integer, to: int | java.jbyte | java.lang.Byte, /) -> IntRange: ...
    @typing.overload
    @staticmethod
    def until(this_until: int | java.jint | java.lang.Integer, to: int | java.jint | java.lang.Integer, /) -> IntRange: ...
    @typing.overload
    @staticmethod
    def until(this_until: int | java.jint | java.lang.Integer, to: int | java.jlong | java.lang.Long, /) -> LongRange: ...
    @typing.overload
    @staticmethod
    def until(this_until: int | java.jint | java.lang.Integer, to: int | java.jshort | java.lang.Short, /) -> IntRange: ...
    @typing.overload
    @staticmethod
    def until(this_until: int | java.jlong | java.lang.Long, to: int | java.jbyte | java.lang.Byte, /) -> LongRange: ...
    @typing.overload
    @staticmethod
    def until(this_until: int | java.jlong | java.lang.Long, to: int | java.jint | java.lang.Integer, /) -> LongRange: ...
    @typing.overload
    @staticmethod
    def until(this_until: int | java.jlong | java.lang.Long, to: int | java.jlong | java.lang.Long, /) -> LongRange: ...
    @typing.overload
    @staticmethod
    def until(this_until: int | java.jlong | java.lang.Long, to: int | java.jshort | java.lang.Short, /) -> LongRange: ...
    @typing.overload
    @staticmethod
    def until(this_until: int | java.jshort | java.lang.Short, to: int | java.jbyte | java.lang.Byte, /) -> IntRange: ...
    @typing.overload
    @staticmethod
    def until(this_until: int | java.jshort | java.lang.Short, to: int | java.jint | java.lang.Integer, /) -> IntRange: ...
    @typing.overload
    @staticmethod
    def until(this_until: int | java.jshort | java.lang.Short, to: int | java.jlong | java.lang.Long, /) -> LongRange: ...
    @typing.overload
    @staticmethod
    def until(this_until: int | java.jshort | java.lang.Short, to: int | java.jshort | java.lang.Short, /) -> IntRange: ...

class UIntProgression(java.lang.Iterable[kotlin.UInt], kotlin.jvm.internal.markers.KMappedMarker):
    Companion: typing.ClassVar[UIntProgression.Companion] = ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getFirst-pVg5ArA(self) -> int: ...
    def getLast-pVg5ArA(self) -> int: ...
    def getStep(self) -> int: ...
    def hashCode(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def iterator(self) -> java.util.Iterator[kotlin.UInt]: ...
    def toString(self) -> str: ...

    class Companion(java.lang.Object):
        def fromClosedRange-Nkh28Cs(self, rangeStart: int | java.jint | java.lang.Integer, rangeEnd: int | java.jint | java.lang.Integer, step: int | java.jint | java.lang.Integer, /) -> UIntProgression: ...

class UIntProgressionIterator(kotlin.collections.UIntIterator):
    def hasNext(self) -> bool: ...
    def nextUInt-pVg5ArA(self) -> int: ...

class UIntRange(UIntProgression, ClosedRange[kotlin.UInt]):
    Companion: typing.ClassVar[UIntRange.Companion] = ...
    def contains-WZ4Q5Ns(self, value: int | java.jint | java.lang.Integer, /) -> bool: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getEndInclusive-pVg5ArA(self) -> int: ...
    def getStart-pVg5ArA(self) -> int: ...
    def hashCode(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def toString(self) -> str: ...

    class Companion(java.lang.Object):
        def getEMPTY(self) -> UIntRange: ...

class ULongProgression(java.lang.Iterable[kotlin.ULong], kotlin.jvm.internal.markers.KMappedMarker):
    Companion: typing.ClassVar[ULongProgression.Companion] = ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getFirst-s-VKNKU(self) -> int: ...
    def getLast-s-VKNKU(self) -> int: ...
    def getStep(self) -> int: ...
    def hashCode(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def iterator(self) -> java.util.Iterator[kotlin.ULong]: ...
    def toString(self) -> str: ...

    class Companion(java.lang.Object):
        def fromClosedRange-7ftBX0g(self, rangeStart: int | java.jlong | java.lang.Long, rangeEnd: int | java.jlong | java.lang.Long, step: int | java.jlong | java.lang.Long, /) -> ULongProgression: ...

class ULongProgressionIterator(kotlin.collections.ULongIterator):
    def hasNext(self) -> bool: ...
    def nextULong-s-VKNKU(self) -> int: ...

class ULongRange(ULongProgression, ClosedRange[kotlin.ULong]):
    Companion: typing.ClassVar[ULongRange.Companion] = ...
    def contains-VKZWuLQ(self, value: int | java.jlong | java.lang.Long, /) -> bool: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getEndInclusive-s-VKNKU(self) -> int: ...
    def getStart-s-VKNKU(self) -> int: ...
    def hashCode(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def toString(self) -> str: ...

    class Companion(java.lang.Object):
        def getEMPTY(self) -> ULongRange: ...

class URangesKt(URangesKt___URangesKt): ...

class URangesKt___URangesKt(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def coerceAtLeast-5PvTz6A(this_coerceAtLeast_u2d5PvTz6A: int | java.jshort | java.lang.Short, minimumValue: int | java.jshort | java.lang.Short, /) -> int: ...
    @staticmethod
    def coerceAtLeast-J1ME1BU(this_coerceAtLeast_u2dJ1ME1BU: int | java.jint | java.lang.Integer, minimumValue: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def coerceAtLeast-Kr8caGY(this_coerceAtLeast_u2dKr8caGY: int | java.jbyte | java.lang.Byte, minimumValue: int | java.jbyte | java.lang.Byte, /) -> int: ...
    @staticmethod
    def coerceAtLeast-eb3DHEI(this_coerceAtLeast_u2deb3DHEI: int | java.jlong | java.lang.Long, minimumValue: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def coerceAtMost-5PvTz6A(this_coerceAtMost_u2d5PvTz6A: int | java.jshort | java.lang.Short, maximumValue: int | java.jshort | java.lang.Short, /) -> int: ...
    @staticmethod
    def coerceAtMost-J1ME1BU(this_coerceAtMost_u2dJ1ME1BU: int | java.jint | java.lang.Integer, maximumValue: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def coerceAtMost-Kr8caGY(this_coerceAtMost_u2dKr8caGY: int | java.jbyte | java.lang.Byte, maximumValue: int | java.jbyte | java.lang.Byte, /) -> int: ...
    @staticmethod
    def coerceAtMost-eb3DHEI(this_coerceAtMost_u2deb3DHEI: int | java.jlong | java.lang.Long, maximumValue: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def coerceIn-JPwROB0(this_coerceIn_u2dJPwROB0: int | java.jlong | java.lang.Long, range: ClosedRange[kotlin.ULong], /) -> int: ...
    @staticmethod
    def coerceIn-VKSA0NQ(this_coerceIn_u2dVKSA0NQ: int | java.jshort | java.lang.Short, minimumValue: int | java.jshort | java.lang.Short, maximumValue: int | java.jshort | java.lang.Short, /) -> int: ...
    @staticmethod
    def coerceIn-WZ9TVnA(this_coerceIn_u2dWZ9TVnA: int | java.jint | java.lang.Integer, minimumValue: int | java.jint | java.lang.Integer, maximumValue: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def coerceIn-b33U2AM(this_coerceIn_u2db33U2AM: int | java.jbyte | java.lang.Byte, minimumValue: int | java.jbyte | java.lang.Byte, maximumValue: int | java.jbyte | java.lang.Byte, /) -> int: ...
    @staticmethod
    def coerceIn-sambcqE(this_coerceIn_u2dsambcqE: int | java.jlong | java.lang.Long, minimumValue: int | java.jlong | java.lang.Long, maximumValue: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def coerceIn-wuiCnnA(this_coerceIn_u2dwuiCnnA: int | java.jint | java.lang.Integer, range: ClosedRange[kotlin.UInt], /) -> int: ...
    @staticmethod
    def contains-68kG9v0(this_contains_u2d68kG9v0: UIntRange, value: int | java.jbyte | java.lang.Byte, /) -> bool: ...
    @staticmethod
    def contains-Gab390E(this_contains_u2dGab390E: ULongRange, value: int | java.jint | java.lang.Integer, /) -> bool: ...
    @staticmethod
    def contains-ULb-yJY(this_contains_u2dULb_u2dyJY: ULongRange, value: int | java.jbyte | java.lang.Byte, /) -> bool: ...
    @staticmethod
    def contains-ZsK3CEQ(this_contains_u2dZsK3CEQ: UIntRange, value: int | java.jshort | java.lang.Short, /) -> bool: ...
    @staticmethod
    def contains-fz5IDCE(this_contains_u2dfz5IDCE: UIntRange, value: int | java.jlong | java.lang.Long, /) -> bool: ...
    @staticmethod
    def contains-uhHAxoY(this_contains_u2duhHAxoY: ULongRange, value: int | java.jshort | java.lang.Short, /) -> bool: ...
    @staticmethod
    def downTo-5PvTz6A(this_downTo_u2d5PvTz6A: int | java.jshort | java.lang.Short, to: int | java.jshort | java.lang.Short, /) -> UIntProgression: ...
    @staticmethod
    def downTo-J1ME1BU(this_downTo_u2dJ1ME1BU: int | java.jint | java.lang.Integer, to: int | java.jint | java.lang.Integer, /) -> UIntProgression: ...
    @staticmethod
    def downTo-Kr8caGY(this_downTo_u2dKr8caGY: int | java.jbyte | java.lang.Byte, to: int | java.jbyte | java.lang.Byte, /) -> UIntProgression: ...
    @staticmethod
    def downTo-eb3DHEI(this_downTo_u2deb3DHEI: int | java.jlong | java.lang.Long, to: int | java.jlong | java.lang.Long, /) -> ULongProgression: ...
    @typing.overload
    @staticmethod
    def random(this_random: UIntRange, random: kotlin.random.Random, /) -> int: ...
    @typing.overload
    @staticmethod
    def random(this_random: ULongRange, random: kotlin.random.Random, /) -> int: ...
    @typing.overload
    @staticmethod
    def randomOrNull(this_randomOrNull: UIntRange, random: kotlin.random.Random, /) -> kotlin.UInt: ...
    @typing.overload
    @staticmethod
    def randomOrNull(this_randomOrNull: ULongRange, random: kotlin.random.Random, /) -> kotlin.ULong: ...
    @typing.overload
    @staticmethod
    def reversed(this_reversed: UIntProgression, /) -> UIntProgression: ...
    @typing.overload
    @staticmethod
    def reversed(this_reversed: ULongProgression, /) -> ULongProgression: ...
    @typing.overload
    @staticmethod
    def step(this_step: UIntProgression, step: int | java.jint | java.lang.Integer, /) -> UIntProgression: ...
    @typing.overload
    @staticmethod
    def step(this_step: ULongProgression, step: int | java.jlong | java.lang.Long, /) -> ULongProgression: ...
    @staticmethod
    def until-5PvTz6A(this_until_u2d5PvTz6A: int | java.jshort | java.lang.Short, to: int | java.jshort | java.lang.Short, /) -> UIntRange: ...
    @staticmethod
    def until-J1ME1BU(this_until_u2dJ1ME1BU: int | java.jint | java.lang.Integer, to: int | java.jint | java.lang.Integer, /) -> UIntRange: ...
    @staticmethod
    def until-Kr8caGY(this_until_u2dKr8caGY: int | java.jbyte | java.lang.Byte, to: int | java.jbyte | java.lang.Byte, /) -> UIntRange: ...
    @staticmethod
    def until-eb3DHEI(this_until_u2deb3DHEI: int | java.jlong | java.lang.Long, to: int | java.jlong | java.lang.Long, /) -> ULongRange: ...
