import android.content
import android.graphics
import android.util
import android.view
import android.view.accessibility
import android.widget
import androidx.recyclerview.widget
import com.google.android.material.shape
import java
import java.chaquopy
import java.lang
import typing



class Arrangement(java.lang.Object):
    def __init__(self, priority: int | java.jint | java.lang.Integer, targetSmallSize: float | java.jfloat | java.lang.Float, minSmallSize: float | java.jfloat | java.lang.Float, maxSmallSize: float | java.jfloat | java.lang.Float, smallCount: int | java.jint | java.lang.Integer, targetMediumSize: float | java.jfloat | java.lang.Float, mediumCount: int | java.jint | java.lang.Integer, targetLargeSize: float | java.jfloat | java.lang.Float, largeCount: int | java.jint | java.lang.Integer, availableSpace: float | java.jfloat | java.lang.Float, /) -> None: ...
    @staticmethod
    def findLowestCostArrangement(availableSpace: float | java.jfloat | java.lang.Float, targetSmallSize: float | java.jfloat | java.lang.Float, minSmallSize: float | java.jfloat | java.lang.Float, maxSmallSize: float | java.jfloat | java.lang.Float, smallCounts: java.chaquopy.JavaArrayJInt, targetMediumSize: float | java.jfloat | java.lang.Float, mediumCounts: java.chaquopy.JavaArrayJInt, targetLargeSize: float | java.jfloat | java.lang.Float, largeCounts: java.chaquopy.JavaArrayJInt, /) -> Arrangement: ...
    def toString(self) -> str: ...

class Carousel(java.lang.Object):
    def getCarouselAlignment(self) -> int: ...
    def getContainerHeight(self) -> int: ...
    def getContainerWidth(self) -> int: ...
    def getItemCount(self) -> int: ...
    def isHorizontal(self) -> bool: ...

class CarouselLayoutManager(androidx.recyclerview.widget.RecyclerView.LayoutManager, Carousel, androidx.recyclerview.widget.RecyclerView.SmoothScroller.ScrollVectorProvider):
    HORIZONTAL: typing.ClassVar[int] = ...
    VERTICAL: typing.ClassVar[int] = ...
    ALIGNMENT_START: typing.ClassVar[int] = ...
    ALIGNMENT_CENTER: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, strategy: CarouselStrategy, /) -> None: ...
    @typing.overload
    def __init__(self, strategy: CarouselStrategy, orientation: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, defStyleRes: int | java.jint | java.lang.Integer, /) -> None: ...
    def canScrollHorizontally(self) -> bool: ...
    def canScrollVertically(self) -> bool: ...
    def computeHorizontalScrollExtent(self, state: androidx.recyclerview.widget.RecyclerView.State, /) -> int: ...
    def computeHorizontalScrollOffset(self, state: androidx.recyclerview.widget.RecyclerView.State, /) -> int: ...
    def computeHorizontalScrollRange(self, state: androidx.recyclerview.widget.RecyclerView.State, /) -> int: ...
    def computeScrollVectorForPosition(self, targetPosition: int | java.jint | java.lang.Integer, /) -> android.graphics.PointF: ...
    def computeVerticalScrollExtent(self, state: androidx.recyclerview.widget.RecyclerView.State, /) -> int: ...
    def computeVerticalScrollOffset(self, state: androidx.recyclerview.widget.RecyclerView.State, /) -> int: ...
    def computeVerticalScrollRange(self, state: androidx.recyclerview.widget.RecyclerView.State, /) -> int: ...
    def generateDefaultLayoutParams(self) -> androidx.recyclerview.widget.RecyclerView.LayoutParams: ...
    def getCarouselAlignment(self) -> int: ...
    def getContainerHeight(self) -> int: ...
    def getContainerWidth(self) -> int: ...
    def getDecoratedBoundsWithMargins(self, view: android.view.View, outBounds: android.graphics.Rect, /) -> None: ...
    def getOrientation(self) -> int: ...
    def isAutoMeasureEnabled(self) -> bool: ...
    def isHorizontal(self) -> bool: ...
    def measureChildWithMargins(self, child: android.view.View, widthUsed: int | java.jint | java.lang.Integer, heightUsed: int | java.jint | java.lang.Integer, /) -> None: ...
    def notifyItemSizeChanged(self) -> None: ...
    def onAttachedToWindow(self, view: androidx.recyclerview.widget.RecyclerView, /) -> None: ...
    def onDetachedFromWindow(self, view: androidx.recyclerview.widget.RecyclerView, recycler: androidx.recyclerview.widget.RecyclerView.Recycler, /) -> None: ...
    def onFocusSearchFailed(self, focused: android.view.View, focusDirection: int | java.jint | java.lang.Integer, recycler: androidx.recyclerview.widget.RecyclerView.Recycler, state: androidx.recyclerview.widget.RecyclerView.State, /) -> android.view.View: ...
    def onInitializeAccessibilityEvent(self, event: android.view.accessibility.AccessibilityEvent, /) -> None: ...
    def onItemsAdded(self, recyclerView: androidx.recyclerview.widget.RecyclerView, positionStart: int | java.jint | java.lang.Integer, itemCount: int | java.jint | java.lang.Integer, /) -> None: ...
    def onItemsChanged(self, recyclerView: androidx.recyclerview.widget.RecyclerView, /) -> None: ...
    def onItemsRemoved(self, recyclerView: androidx.recyclerview.widget.RecyclerView, positionStart: int | java.jint | java.lang.Integer, itemCount: int | java.jint | java.lang.Integer, /) -> None: ...
    def onLayoutChildren(self, recycler: androidx.recyclerview.widget.RecyclerView.Recycler, state: androidx.recyclerview.widget.RecyclerView.State, /) -> None: ...
    def onLayoutCompleted(self, state: androidx.recyclerview.widget.RecyclerView.State, /) -> None: ...
    def requestChildRectangleOnScreen(self, parent: androidx.recyclerview.widget.RecyclerView, child: android.view.View, rect: android.graphics.Rect, immediate: bool | java.jboolean | java.lang.Boolean, focusedChildVisible: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def scrollHorizontallyBy(self, dx: int | java.jint | java.lang.Integer, recycler: androidx.recyclerview.widget.RecyclerView.Recycler, state: androidx.recyclerview.widget.RecyclerView.State, /) -> int: ...
    def scrollToPosition(self, position: int | java.jint | java.lang.Integer, /) -> None: ...
    def scrollVerticallyBy(self, dy: int | java.jint | java.lang.Integer, recycler: androidx.recyclerview.widget.RecyclerView.Recycler, state: androidx.recyclerview.widget.RecyclerView.State, /) -> int: ...
    def setCarouselAlignment(self, alignment: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCarouselStrategy(self, carouselStrategy: CarouselStrategy, /) -> None: ...
    def setDebuggingEnabled(self, recyclerView: androidx.recyclerview.widget.RecyclerView, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setOrientation(self, orientation: int | java.jint | java.lang.Integer, /) -> None: ...
    def smoothScrollToPosition(self, recyclerView: androidx.recyclerview.widget.RecyclerView, state: androidx.recyclerview.widget.RecyclerView.State, position: int | java.jint | java.lang.Integer, /) -> None: ...

class CarouselOrientationHelper(java.lang.Object): ...

class CarouselSnapHelper(androidx.recyclerview.widget.SnapHelper):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, disableFling: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def attachToRecyclerView(self, recyclerView: androidx.recyclerview.widget.RecyclerView, /) -> None: ...
    def calculateDistanceToFinalSnap(self, layoutManager: androidx.recyclerview.widget.RecyclerView.LayoutManager, view: android.view.View, /) -> java.chaquopy.JavaArrayJInt: ...
    def createScroller(self, layoutManager: androidx.recyclerview.widget.RecyclerView.LayoutManager, /) -> androidx.recyclerview.widget.RecyclerView.SmoothScroller: ...
    def findSnapView(self, layoutManager: androidx.recyclerview.widget.RecyclerView.LayoutManager, /) -> android.view.View: ...
    def findTargetSnapPosition(self, layoutManager: androidx.recyclerview.widget.RecyclerView.LayoutManager, velocityX: int | java.jint | java.lang.Integer, velocityY: int | java.jint | java.lang.Integer, /) -> int: ...

class CarouselStrategy(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def getChildMaskPercentage(maskedSize: float | java.jfloat | java.lang.Float, unmaskedSize: float | java.jfloat | java.lang.Float, childMargins: float | java.jfloat | java.lang.Float, /) -> float: ...
    def getSmallItemSizeMax(self) -> float: ...
    def getSmallItemSizeMin(self) -> float: ...
    def onFirstChildMeasuredWithMargins(self, arg1: Carousel, arg2: android.view.View, /) -> KeylineState: ...
    def setSmallItemSizeMax(self, maxSmallItemSize: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setSmallItemSizeMin(self, minSmallItemSize: float | java.jfloat | java.lang.Float, /) -> None: ...
    def shouldRefreshKeylineState(self, carousel: Carousel, oldItemCount: int | java.jint | java.lang.Integer, /) -> bool: ...

class CarouselStrategyHelper(java.lang.Object): ...

class FullScreenCarouselStrategy(CarouselStrategy):
    def __init__(self) -> None: ...
    def onFirstChildMeasuredWithMargins(self, carousel: Carousel, child: android.view.View, /) -> KeylineState: ...

class HeroCarouselStrategy(CarouselStrategy):
    def __init__(self) -> None: ...
    def onFirstChildMeasuredWithMargins(self, carousel: Carousel, child: android.view.View, /) -> KeylineState: ...
    def shouldRefreshKeylineState(self, carousel: Carousel, oldItemCount: int | java.jint | java.lang.Integer, /) -> bool: ...

class KeylineState(java.lang.Object):

    class Builder(java.lang.Object):
        def __init__(self, itemSize: float | java.jfloat | java.lang.Float, carouselSize: int | java.jint | java.lang.Integer, /) -> None: ...
        def addAnchorKeyline(self, offsetLoc: float | java.jfloat | java.lang.Float, mask: float | java.jfloat | java.lang.Float, maskedItemSize: float | java.jfloat | java.lang.Float, /) -> KeylineState.Builder: ...
        @typing.overload
        def addKeyline(self, offsetLoc: float | java.jfloat | java.lang.Float, mask: float | java.jfloat | java.lang.Float, maskedItemSize: float | java.jfloat | java.lang.Float, /) -> KeylineState.Builder: ...
        @typing.overload
        def addKeyline(self, offsetLoc: float | java.jfloat | java.lang.Float, mask: float | java.jfloat | java.lang.Float, maskedItemSize: float | java.jfloat | java.lang.Float, isFocal: bool | java.jboolean | java.lang.Boolean, /) -> KeylineState.Builder: ...
        @typing.overload
        def addKeyline(self, offsetLoc: float | java.jfloat | java.lang.Float, mask: float | java.jfloat | java.lang.Float, maskedItemSize: float | java.jfloat | java.lang.Float, isFocal: bool | java.jboolean | java.lang.Boolean, isAnchor: bool | java.jboolean | java.lang.Boolean, /) -> KeylineState.Builder: ...
        @typing.overload
        def addKeyline(self, offsetLoc: float | java.jfloat | java.lang.Float, mask: float | java.jfloat | java.lang.Float, maskedItemSize: float | java.jfloat | java.lang.Float, isFocal: bool | java.jboolean | java.lang.Boolean, isAnchor: bool | java.jboolean | java.lang.Boolean, cutoff: float | java.jfloat | java.lang.Float, /) -> KeylineState.Builder: ...
        @typing.overload
        def addKeyline(self, offsetLoc: float | java.jfloat | java.lang.Float, mask: float | java.jfloat | java.lang.Float, maskedItemSize: float | java.jfloat | java.lang.Float, isFocal: bool | java.jboolean | java.lang.Boolean, isAnchor: bool | java.jboolean | java.lang.Boolean, cutoff: float | java.jfloat | java.lang.Float, leftOrTopPaddingShift: float | java.jfloat | java.lang.Float, rightOrBottomPaddingShift: float | java.jfloat | java.lang.Float, /) -> KeylineState.Builder: ...
        @typing.overload
        def addKeylineRange(self, offsetLoc: float | java.jfloat | java.lang.Float, mask: float | java.jfloat | java.lang.Float, maskedItemSize: float | java.jfloat | java.lang.Float, count: int | java.jint | java.lang.Integer, /) -> KeylineState.Builder: ...
        @typing.overload
        def addKeylineRange(self, offsetLoc: float | java.jfloat | java.lang.Float, mask: float | java.jfloat | java.lang.Float, maskedItemSize: float | java.jfloat | java.lang.Float, count: int | java.jint | java.lang.Integer, isFocal: bool | java.jboolean | java.lang.Boolean, /) -> KeylineState.Builder: ...
        def build(self) -> KeylineState: ...

class KeylineStateList(java.lang.Object):
    def getShiftedState(self, scrollOffset: float | java.jfloat | java.lang.Float, minScrollOffset: float | java.jfloat | java.lang.Float, maxScrollOffset: float | java.jfloat | java.lang.Float, /) -> KeylineState: ...

class Maskable(java.lang.Object):
    def getMaskRectF(self) -> android.graphics.RectF: ...
    def getMaskXPercentage(self) -> float: ...
    def setMaskRectF(self, arg1: android.graphics.RectF, /) -> None: ...
    def setMaskXPercentage(self, arg1: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setOnMaskChangedListener(self, arg1: OnMaskChangedListener, /) -> None: ...

class MaskableFrameLayout(android.widget.FrameLayout, Maskable, com.google.android.material.shape.Shapeable):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def dispatchDraw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getFocusedRect(self, r: android.graphics.Rect, /) -> None: ...
    def getMaskRectF(self) -> android.graphics.RectF: ...
    def getMaskXPercentage(self) -> float: ...
    def getShapeAppearanceModel(self) -> com.google.android.material.shape.ShapeAppearanceModel: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onHoverEvent(self, event: android.view.MotionEvent, /) -> bool: ...
    def onInitializeAccessibilityNodeInfo(self, info: android.view.accessibility.AccessibilityNodeInfo, /) -> None: ...
    def onInterceptTouchEvent(self, event: android.view.MotionEvent, /) -> bool: ...
    def onSizeChanged(self, w: int | java.jint | java.lang.Integer, h: int | java.jint | java.lang.Integer, oldw: int | java.jint | java.lang.Integer, oldh: int | java.jint | java.lang.Integer, /) -> None: ...
    def onTouchEvent(self, event: android.view.MotionEvent, /) -> bool: ...
    def setForceCompatClipping(self, forceCompatClipping: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setMaskRectF(self, maskRect: android.graphics.RectF, /) -> None: ...
    def setMaskXPercentage(self, percentage: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setOnHoverListener(self, l: android.view.View.OnHoverListener, /) -> None: ...
    def setOnMaskChangedListener(self, onMaskChangedListener: OnMaskChangedListener, /) -> None: ...
    def setShapeAppearanceModel(self, shapeAppearanceModel: com.google.android.material.shape.ShapeAppearanceModel, /) -> None: ...

class MultiBrowseCarouselStrategy(CarouselStrategy):
    def __init__(self) -> None: ...
    def onFirstChildMeasuredWithMargins(self, carousel: Carousel, child: android.view.View, /) -> KeylineState: ...
    def shouldRefreshKeylineState(self, carousel: Carousel, oldItemCount: int | java.jint | java.lang.Integer, /) -> bool: ...

class OnMaskChangedListener(java.lang.Object):
    def onMaskChanged(self, arg1: android.graphics.RectF, /) -> None: ...

class UncontainedCarouselStrategy(CarouselStrategy):
    def __init__(self) -> None: ...
    def onFirstChildMeasuredWithMargins(self, carousel: Carousel, child: android.view.View, /) -> KeylineState: ...
