import typing

import android.content
import android.graphics
import android.os
import java
import java.io
import java.lang
import java.util
import org.osmdroid.tileprovider
import org.osmdroid.tileprovider.modules
import org.osmdroid.tileprovider.tilesource
import org.osmdroid.util
import org.osmdroid.views

class CacheManager(java.lang.Object):
    mTileProvider: org.osmdroid.tileprovider.MapTileProviderBase = ...
    mTileWriter: org.osmdroid.tileprovider.modules.IFilesystemCache = ...
    mMinZoomLevel: int = ...
    mMaxZoomLevel: int = ...
    mPendingTasks: java.util.Set[CacheManager.CacheManagerTask] = ...
    @typing.overload
    def __init__(self, mapView: org.osmdroid.views.MapView, /) -> None: ...
    @typing.overload
    def __init__(self, mapView: org.osmdroid.views.MapView, writer: org.osmdroid.tileprovider.modules.IFilesystemCache, /) -> None: ...
    @typing.overload
    def __init__(self, pTileProvider: org.osmdroid.tileprovider.MapTileProviderBase, pWriter: org.osmdroid.tileprovider.modules.IFilesystemCache, pMinZoomLevel: int | java.jint | java.lang.Integer, pMaxZoomLevel: int | java.jint | java.lang.Integer, /) -> None: ...
    def cacheCapacity(self) -> int: ...
    def cancelAllJobs(self) -> None: ...
    def checkTile(self, pTile: org.osmdroid.tileprovider.MapTile, /) -> bool: ...
    @typing.overload
    def cleanAreaAsync(self, ctx: android.content.Context, geoPoints: java.util.ArrayList[org.osmdroid.util.GeoPoint], zoomMin: int | java.jint | java.lang.Integer, zoomMax: int | java.jint | java.lang.Integer, /) -> CacheManager.CacheManagerTask: ...
    @typing.overload
    def cleanAreaAsync(self, ctx: android.content.Context, tiles: java.util.List[org.osmdroid.tileprovider.MapTile], zoomMin: int | java.jint | java.lang.Integer, zoomMax: int | java.jint | java.lang.Integer, /) -> CacheManager.CacheManagerTask: ...
    @typing.overload
    def cleanAreaAsync(self, ctx: android.content.Context, bb: org.osmdroid.util.BoundingBox, zoomMin: int | java.jint | java.lang.Integer, zoomMax: int | java.jint | java.lang.Integer, /) -> CacheManager.CacheManagerTask: ...
    def currentCacheUsage(self) -> int: ...
    def deleteTile(self, pTile: org.osmdroid.tileprovider.MapTile, /) -> bool: ...
    def directorySize(self, pDirectory: java.io.File, /) -> int: ...
    @typing.overload
    def downloadAreaAsync(self, ctx: android.content.Context, geoPoints: java.util.ArrayList[org.osmdroid.util.GeoPoint], zoomMin: int | java.jint | java.lang.Integer, zoomMax: int | java.jint | java.lang.Integer, /) -> CacheManager.CacheManagerTask: ...
    @typing.overload
    def downloadAreaAsync(self, ctx: android.content.Context, pTiles: java.util.List[org.osmdroid.tileprovider.MapTile], zoomMin: int | java.jint | java.lang.Integer, zoomMax: int | java.jint | java.lang.Integer, /) -> CacheManager.CacheManagerTask: ...
    @typing.overload
    def downloadAreaAsync(self, ctx: android.content.Context, bb: org.osmdroid.util.BoundingBox, zoomMin: int | java.jint | java.lang.Integer, zoomMax: int | java.jint | java.lang.Integer, /) -> CacheManager.CacheManagerTask: ...
    @typing.overload
    def downloadAreaAsync(self, ctx: android.content.Context, geoPoints: java.util.ArrayList[org.osmdroid.util.GeoPoint], zoomMin: int | java.jint | java.lang.Integer, zoomMax: int | java.jint | java.lang.Integer, callback: CacheManager.CacheManagerCallback, /) -> CacheManager.CacheManagerTask: ...
    @typing.overload
    def downloadAreaAsync(self, ctx: android.content.Context, bb: org.osmdroid.util.BoundingBox, zoomMin: int | java.jint | java.lang.Integer, zoomMax: int | java.jint | java.lang.Integer, callback: CacheManager.CacheManagerCallback, /) -> CacheManager.CacheManagerTask: ...
    @typing.overload
    def downloadAreaAsyncNoUI(self, ctx: android.content.Context, geoPoints: java.util.ArrayList[org.osmdroid.util.GeoPoint], zoomMin: int | java.jint | java.lang.Integer, zoomMax: int | java.jint | java.lang.Integer, callback: CacheManager.CacheManagerCallback, /) -> CacheManager.CacheManagerTask: ...
    @typing.overload
    def downloadAreaAsyncNoUI(self, ctx: android.content.Context, bb: org.osmdroid.util.BoundingBox, zoomMin: int | java.jint | java.lang.Integer, zoomMax: int | java.jint | java.lang.Integer, callback: CacheManager.CacheManagerCallback, /) -> CacheManager.CacheManagerTask: ...
    def execute(self, pTask: CacheManager.CacheManagerTask, /) -> CacheManager.CacheManagerTask: ...
    def extendedBoundsFromGeoPoints(self, geoPoints: java.util.ArrayList[org.osmdroid.util.GeoPoint], minZoomLevel: int | java.jint | java.lang.Integer, /) -> org.osmdroid.util.BoundingBox: ...
    def getCleaningAction(self) -> CacheManager.CacheManagerAction: ...
    def getCleaningDialog(self, pCtx: android.content.Context, pTask: CacheManager.CacheManagerTask, /) -> CacheManager.CacheManagerDialog: ...
    @staticmethod
    def getCoordinatesFromMapTile(x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, zoom: int | java.jint | java.lang.Integer, /) -> org.osmdroid.util.GeoPoint: ...
    def getDownloadingAction(self) -> CacheManager.CacheManagerAction: ...
    def getDownloadingDialog(self, pCtx: android.content.Context, pTask: CacheManager.CacheManagerTask, /) -> CacheManager.CacheManagerDialog: ...
    @staticmethod
    def getFileName(tileSource: org.osmdroid.tileprovider.tilesource.ITileSource, tile: org.osmdroid.tileprovider.MapTile, /) -> java.io.File: ...
    @staticmethod
    def getMapTileFromCoordinates(aLat: float | java.jdouble | java.lang.Double, aLon: float | java.jdouble | java.lang.Double, zoom: int | java.jint | java.lang.Integer, /) -> android.graphics.Point: ...
    def getPendingJobs(self) -> int: ...
    @typing.overload
    @staticmethod
    def getTilesCoverage(pGeoPoints: java.util.ArrayList[org.osmdroid.util.GeoPoint], pZoomLevel: int | java.jint | java.lang.Integer, /) -> java.util.Collection[org.osmdroid.tileprovider.MapTile]: ...
    @typing.overload
    @staticmethod
    def getTilesCoverage(pBB: org.osmdroid.util.BoundingBox, pZoomLevel: int | java.jint | java.lang.Integer, /) -> java.util.Collection[org.osmdroid.tileprovider.MapTile]: ...
    @typing.overload
    @staticmethod
    def getTilesCoverage(pGeoPoints: java.util.ArrayList[org.osmdroid.util.GeoPoint], pZoomMin: int | java.jint | java.lang.Integer, pZoomMax: int | java.jint | java.lang.Integer, /) -> java.util.List[org.osmdroid.tileprovider.MapTile]: ...
    @typing.overload
    @staticmethod
    def getTilesCoverage(pBB: org.osmdroid.util.BoundingBox, pZoomMin: int | java.jint | java.lang.Integer, pZoomMax: int | java.jint | java.lang.Integer, /) -> java.util.List[org.osmdroid.tileprovider.MapTile]: ...
    def loadTile(self, tileSource: org.osmdroid.tileprovider.tilesource.OnlineTileSourceBase, tile: org.osmdroid.tileprovider.MapTile, /) -> bool: ...
    def possibleTilesCovered(self, pGeoPoints: java.util.ArrayList[org.osmdroid.util.GeoPoint], pZoomMin: int | java.jint | java.lang.Integer, pZoomMax: int | java.jint | java.lang.Integer, /) -> int: ...
    def possibleTilesInArea(self, pBB: org.osmdroid.util.BoundingBox, pZoomMin: int | java.jint | java.lang.Integer, pZoomMax: int | java.jint | java.lang.Integer, /) -> int: ...

    class CacheManagerAction(java.lang.Object):
        def getProgressModulo(self) -> int: ...
        def preCheck(self) -> bool: ...
        def tileAction(self, arg1: org.osmdroid.tileprovider.MapTile, /) -> bool: ...

    class CacheManagerTask(android.os.AsyncTask[java.lang.Object, java.lang.Integer, java.lang.Integer]):
        @typing.overload
        def __init__(self, pManager: CacheManager, pAction: CacheManager.CacheManagerAction, pGeoPoints: java.util.ArrayList[org.osmdroid.util.GeoPoint], pZoomMin: int | java.jint | java.lang.Integer, pZoomMax: int | java.jint | java.lang.Integer, /) -> None: ...
        @typing.overload
        def __init__(self, pManager: CacheManager, pAction: CacheManager.CacheManagerAction, pTiles: java.util.List[org.osmdroid.tileprovider.MapTile], pZoomMin: int | java.jint | java.lang.Integer, pZoomMax: int | java.jint | java.lang.Integer, /) -> None: ...
        @typing.overload
        def __init__(self, pManager: CacheManager, pAction: CacheManager.CacheManagerAction, pBB: org.osmdroid.util.BoundingBox, pZoomMin: int | java.jint | java.lang.Integer, pZoomMax: int | java.jint | java.lang.Integer, /) -> None: ...
        def addCallback(self, pCallback: CacheManager.CacheManagerCallback, /) -> None: ...
        def doInBackground(self, *params: java.lang.Object) -> int: ...
        def onCancelled(self) -> None: ...
        def onPostExecute(self, specialCount: int | java.jint | java.lang.Integer, /) -> None: ...
        def onPreExecute(self) -> None: ...
        def onProgressUpdate(self, *count: java.jint) -> None: ...

    class CacheManagerDialog(CacheManager.CacheManagerCallback):
        def __init__(self, pCtx: android.content.Context, pTask: CacheManager.CacheManagerTask, /) -> None: ...
        def downloadStarted(self) -> None: ...
        def getUITitle(self) -> str: ...
        def onTaskComplete(self) -> None: ...
        def onTaskFailed(self, errors: int | java.jint | java.lang.Integer, /) -> None: ...
        def setPossibleTilesInArea(self, total: int | java.jint | java.lang.Integer, /) -> None: ...
        def updateProgress(self, progress: int | java.jint | java.lang.Integer, currentZoomLevel: int | java.jint | java.lang.Integer, zoomMin: int | java.jint | java.lang.Integer, zoomMax: int | java.jint | java.lang.Integer, /) -> None: ...
        def zoomMessage(self, zoomLevel: int | java.jint | java.lang.Integer, zoomMin: int | java.jint | java.lang.Integer, zoomMax: int | java.jint | java.lang.Integer, /) -> str: ...

    class CacheManagerCallback(java.lang.Object):
        def downloadStarted(self) -> None: ...
        def onTaskComplete(self) -> None: ...
        def onTaskFailed(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
        def setPossibleTilesInArea(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
        def updateProgress(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, arg4: int | java.jint | java.lang.Integer, /) -> None: ...
