import typing

import android.content
import android.content.res
import android.database.sqlite
import android.graphics.drawable
import java
import java.chaquopy
import java.io
import java.lang
import java.util
import java.util.concurrent
import java.util.zip
import org
import org.osmdroid.tileprovider
import org.osmdroid.tileprovider.tilesource

class ArchiveFileFactory(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def getArchiveFile(pFile: java.io.File, /) -> IArchiveFile: ...
    @staticmethod
    def isFileExtensionRegistered(extension: str | java.lang.String, /) -> bool: ...
    @staticmethod
    def registerArchiveFileProvider(provider: typing.Type[IArchiveFile], fileExtension: str | java.lang.String, /) -> None: ...

class ConfigurablePriorityThreadFactory(java.util.concurrent.ThreadFactory):
    def __init__(self, pPriority: int | java.jint | java.lang.Integer, pName: str | java.lang.String, /) -> None: ...
    def newThread(self, pRunnable: java.lang.Runnable, /) -> java.lang.Thread: ...

class DatabaseFileArchive(IArchiveFile):
    TABLE: typing.ClassVar[str] = ...
    COLUMN_PROVIDER: typing.ClassVar[str] = ...
    COLUMN_TILE: typing.ClassVar[str] = ...
    COLUMN_KEY: typing.ClassVar[str] = ...
    def __init__(self) -> None: ...
    def close(self) -> None: ...
    @staticmethod
    def getDatabaseFileArchive(pFile: java.io.File, /) -> DatabaseFileArchive: ...
    def getImage(self, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, pTile: org.osmdroid.tileprovider.MapTile, /) -> java.chaquopy.JavaArrayJByte: ...
    def getInputStream(self, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, pTile: org.osmdroid.tileprovider.MapTile, /) -> java.io.InputStream: ...
    def getTileSources(self) -> java.util.Set[java.lang.String]: ...
    def init(self, pFile: java.io.File, /) -> None: ...
    def toString(self) -> str: ...

class GEMFFileArchive(IArchiveFile):
    def __init__(self) -> None: ...
    def close(self) -> None: ...
    @staticmethod
    def getGEMFFileArchive(pFile: java.io.File, /) -> GEMFFileArchive: ...
    def getInputStream(self, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, pTile: org.osmdroid.tileprovider.MapTile, /) -> java.io.InputStream: ...
    def getTileSources(self) -> java.util.Set[java.lang.String]: ...
    def init(self, pFile: java.io.File, /) -> None: ...
    def toString(self) -> str: ...

class IArchiveFile(java.lang.Object):
    def close(self) -> None: ...
    def getInputStream(self, arg1: org.osmdroid.tileprovider.tilesource.ITileSource, arg2: org.osmdroid.tileprovider.MapTile, /) -> java.io.InputStream: ...
    def getTileSources(self) -> java.util.Set[java.lang.String]: ...
    def init(self, arg1: java.io.File, /) -> None: ...

class IFilesystemCache(java.lang.Object):
    def exists(self, arg1: org.osmdroid.tileprovider.tilesource.ITileSource, arg2: org.osmdroid.tileprovider.MapTile, /) -> bool: ...
    def onDetach(self) -> None: ...
    def remove(self, arg1: org.osmdroid.tileprovider.tilesource.ITileSource, arg2: org.osmdroid.tileprovider.MapTile, /) -> bool: ...
    def saveFile(self, arg1: org.osmdroid.tileprovider.tilesource.ITileSource, arg2: org.osmdroid.tileprovider.MapTile, arg3: java.io.InputStream, /) -> bool: ...

class INetworkAvailablityCheck(java.lang.Object):
    def getCellularDataNetworkAvailable(self) -> bool: ...
    def getNetworkAvailable(self) -> bool: ...
    def getRouteToPathExists(self, arg1: int | java.jint | java.lang.Integer, /) -> bool: ...
    def getWiFiNetworkAvailable(self) -> bool: ...

class MBTilesFileArchive(IArchiveFile):
    TABLE_TILES: typing.ClassVar[str] = ...
    COL_TILES_ZOOM_LEVEL: typing.ClassVar[str] = ...
    COL_TILES_TILE_COLUMN: typing.ClassVar[str] = ...
    COL_TILES_TILE_ROW: typing.ClassVar[str] = ...
    COL_TILES_TILE_DATA: typing.ClassVar[str] = ...
    def __init__(self) -> None: ...
    def close(self) -> None: ...
    @staticmethod
    def getDatabaseFileArchive(pFile: java.io.File, /) -> MBTilesFileArchive: ...
    def getInputStream(self, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, pTile: org.osmdroid.tileprovider.MapTile, /) -> java.io.InputStream: ...
    def getTileSources(self) -> java.util.Set[java.lang.String]: ...
    def init(self, pFile: java.io.File, /) -> None: ...
    def toString(self) -> str: ...

class MapTileAssetsProvider(MapTileFileStorageProviderBase):
    @typing.overload
    def __init__(self, pRegisterReceiver: org.osmdroid.tileprovider.IRegisterReceiver, pAssets: android.content.res.AssetManager, /) -> None: ...
    @typing.overload
    def __init__(self, pRegisterReceiver: org.osmdroid.tileprovider.IRegisterReceiver, pAssets: android.content.res.AssetManager, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, /) -> None: ...
    @typing.overload
    def __init__(self, pRegisterReceiver: org.osmdroid.tileprovider.IRegisterReceiver, pAssets: android.content.res.AssetManager, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, pThreadPoolSize: int | java.jint | java.lang.Integer, pPendingQueueSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def getMaximumZoomLevel(self) -> int: ...
    def getMinimumZoomLevel(self) -> int: ...
    def getName(self) -> str: ...
    def getThreadGroupName(self) -> str: ...
    def getTileLoader(self) -> java.lang.Runnable: ...
    def getUsesDataConnection(self) -> bool: ...
    def setTileSource(self, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, /) -> None: ...

    class TileLoader(org.osmdroid.tileprovider.modules.MapTileModuleProviderBase.TileLoader):
        def __init__(self, this_0: MapTileAssetsProvider, pAssets: android.content.res.AssetManager, /) -> None: ...
        def loadTile(self, pState: org.osmdroid.tileprovider.MapTileRequestState, /) -> android.graphics.drawable.Drawable: ...

class MapTileDownloader(MapTileModuleProviderBase):
    @typing.overload
    def __init__(self, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, /) -> None: ...
    @typing.overload
    def __init__(self, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, pFilesystemCache: IFilesystemCache, /) -> None: ...
    @typing.overload
    def __init__(self, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, pFilesystemCache: IFilesystemCache, pNetworkAvailablityCheck: INetworkAvailablityCheck, /) -> None: ...
    @typing.overload
    def __init__(self, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, pFilesystemCache: IFilesystemCache, pNetworkAvailablityCheck: INetworkAvailablityCheck, pThreadPoolSize: int | java.jint | java.lang.Integer, pPendingQueueSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def detach(self) -> None: ...
    def getMaximumZoomLevel(self) -> int: ...
    def getMinimumZoomLevel(self) -> int: ...
    def getName(self) -> str: ...
    def getThreadGroupName(self) -> str: ...
    def getTileLoader(self) -> java.lang.Runnable: ...
    def getTileSource(self) -> org.osmdroid.tileprovider.tilesource.ITileSource: ...
    def getUsesDataConnection(self) -> bool: ...
    def setTileSource(self, tileSource: org.osmdroid.tileprovider.tilesource.ITileSource, /) -> None: ...

    class TileLoader(org.osmdroid.tileprovider.modules.MapTileModuleProviderBase.TileLoader):
        def __init__(self, this_0: MapTileDownloader, /) -> None: ...
        def loadTile(self, aState: org.osmdroid.tileprovider.MapTileRequestState, /) -> android.graphics.drawable.Drawable: ...
        def tileLoaded(self, pState: org.osmdroid.tileprovider.MapTileRequestState, pDrawable: android.graphics.drawable.Drawable, /) -> None: ...

class MapTileFileArchiveProvider(MapTileFileStorageProviderBase):
    @typing.overload
    def __init__(self, pRegisterReceiver: org.osmdroid.tileprovider.IRegisterReceiver, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, /) -> None: ...
    @typing.overload
    def __init__(self, pRegisterReceiver: org.osmdroid.tileprovider.IRegisterReceiver, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, pArchives: java.chaquopy.JavaArray[IArchiveFile], /) -> None: ...
    def detach(self) -> None: ...
    def getMaximumZoomLevel(self) -> int: ...
    def getMinimumZoomLevel(self) -> int: ...
    def getName(self) -> str: ...
    def getThreadGroupName(self) -> str: ...
    def getTileLoader(self) -> java.lang.Runnable: ...
    def getUsesDataConnection(self) -> bool: ...
    def onMediaMounted(self) -> None: ...
    def onMediaUnmounted(self) -> None: ...
    def setTileSource(self, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, /) -> None: ...

    class TileLoader(org.osmdroid.tileprovider.modules.MapTileModuleProviderBase.TileLoader):
        def __init__(self, this_0: MapTileFileArchiveProvider, /) -> None: ...
        def loadTile(self, pState: org.osmdroid.tileprovider.MapTileRequestState, /) -> android.graphics.drawable.Drawable: ...

class MapTileFileStorageProviderBase(MapTileModuleProviderBase):
    def __init__(self, pRegisterReceiver: org.osmdroid.tileprovider.IRegisterReceiver, pThreadPoolSize: int | java.jint | java.lang.Integer, pPendingQueueSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def detach(self) -> None: ...
    @staticmethod
    def isSdCardAvailable() -> bool: ...
    def onMediaMounted(self) -> None: ...
    def onMediaUnmounted(self) -> None: ...

class MapTileFilesystemProvider(MapTileFileStorageProviderBase):
    @typing.overload
    def __init__(self, pRegisterReceiver: org.osmdroid.tileprovider.IRegisterReceiver, /) -> None: ...
    @typing.overload
    def __init__(self, pRegisterReceiver: org.osmdroid.tileprovider.IRegisterReceiver, aTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, /) -> None: ...
    @typing.overload
    def __init__(self, pRegisterReceiver: org.osmdroid.tileprovider.IRegisterReceiver, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, pMaximumCachedFileAge: int | java.jlong | java.lang.Long, /) -> None: ...
    @typing.overload
    def __init__(self, pRegisterReceiver: org.osmdroid.tileprovider.IRegisterReceiver, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, pMaximumCachedFileAge: int | java.jlong | java.lang.Long, pThreadPoolSize: int | java.jint | java.lang.Integer, pPendingQueueSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def getMaximumZoomLevel(self) -> int: ...
    def getMinimumZoomLevel(self) -> int: ...
    def getName(self) -> str: ...
    def getThreadGroupName(self) -> str: ...
    def getTileLoader(self) -> java.lang.Runnable: ...
    def getUsesDataConnection(self) -> bool: ...
    def setTileSource(self, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, /) -> None: ...

    class TileLoader(org.osmdroid.tileprovider.modules.MapTileModuleProviderBase.TileLoader):
        def __init__(self, this_0: MapTileFilesystemProvider, /) -> None: ...
        def loadTile(self, pState: org.osmdroid.tileprovider.MapTileRequestState, /) -> android.graphics.drawable.Drawable: ...

class MapTileModuleProviderBase(java.lang.Object):
    mQueueLockObject: java.lang.Object = ...
    mWorking: java.util.HashMap[org.osmdroid.tileprovider.MapTile, org.osmdroid.tileprovider.MapTileRequestState] = ...
    mPending: java.util.LinkedHashMap[org.osmdroid.tileprovider.MapTile, org.osmdroid.tileprovider.MapTileRequestState] = ...
    def __init__(self, pThreadPoolSize: int | java.jint | java.lang.Integer, pPendingQueueSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def detach(self) -> None: ...
    def getMaximumZoomLevel(self) -> int: ...
    def getMinimumZoomLevel(self) -> int: ...
    def getName(self) -> str: ...
    def getThreadGroupName(self) -> str: ...
    def getTileLoader(self) -> java.lang.Runnable: ...
    def getUsesDataConnection(self) -> bool: ...
    def loadMapTileAsync(self, pState: org.osmdroid.tileprovider.MapTileRequestState, /) -> None: ...
    def setTileSource(self, arg1: org.osmdroid.tileprovider.tilesource.ITileSource, /) -> None: ...

    class CantContinueException(java.lang.Exception):
        @typing.overload
        def __init__(self, this_0: MapTileModuleProviderBase, pDetailMessage: str | java.lang.String, /) -> None: ...
        @typing.overload
        def __init__(self, this_0: MapTileModuleProviderBase, pThrowable: java.lang.Throwable, /) -> None: ...

    class TileLoader(java.lang.Runnable):
        def __init__(self, this_0: MapTileModuleProviderBase, /) -> None: ...
        def loadTile(self, arg1: org.osmdroid.tileprovider.MapTileRequestState, /) -> android.graphics.drawable.Drawable: ...
        def nextTile(self) -> org.osmdroid.tileprovider.MapTileRequestState: ...
        def onTileLoaderInit(self) -> None: ...
        def onTileLoaderShutdown(self) -> None: ...
        def run(self) -> None: ...
        def tileLoaded(self, pState: org.osmdroid.tileprovider.MapTileRequestState, pDrawable: android.graphics.drawable.Drawable, /) -> None: ...
        def tileLoadedExpired(self, pState: org.osmdroid.tileprovider.MapTileRequestState, pDrawable: android.graphics.drawable.Drawable, /) -> None: ...
        def tileLoadedFailed(self, pState: org.osmdroid.tileprovider.MapTileRequestState, /) -> None: ...

class MapTileSqlCacheProvider(MapTileFileStorageProviderBase):
    @typing.overload
    def __init__(self, pRegisterReceiver: org.osmdroid.tileprovider.IRegisterReceiver, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, /) -> None: ...
    @typing.overload
    def __init__(self, pRegisterReceiver: org.osmdroid.tileprovider.IRegisterReceiver, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, pMaximumCachedFileAge: int | java.jlong | java.lang.Long, /) -> None: ...
    def detach(self) -> None: ...
    def getMaximumZoomLevel(self) -> int: ...
    def getMinimumZoomLevel(self) -> int: ...
    def getName(self) -> str: ...
    def getThreadGroupName(self) -> str: ...
    def getTileLoader(self) -> java.lang.Runnable: ...
    def getUsesDataConnection(self) -> bool: ...
    def hasTile(self, pTile: org.osmdroid.tileprovider.MapTile, /) -> bool: ...
    def onMediaMounted(self) -> None: ...
    def onMediaUnmounted(self) -> None: ...
    def setTileSource(self, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, /) -> None: ...

    class TileLoader(org.osmdroid.tileprovider.modules.MapTileModuleProviderBase.TileLoader):
        def __init__(self, this_0: MapTileSqlCacheProvider, /) -> None: ...
        def loadTile(self, pState: org.osmdroid.tileprovider.MapTileRequestState, /) -> android.graphics.drawable.Drawable: ...

class NetworkAvailabliltyCheck(INetworkAvailablityCheck):
    def __init__(self, aContext: android.content.Context, /) -> None: ...
    def getCellularDataNetworkAvailable(self) -> bool: ...
    def getNetworkAvailable(self) -> bool: ...
    def getRouteToPathExists(self, hostAddress: int | java.jint | java.lang.Integer, /) -> bool: ...
    def getWiFiNetworkAvailable(self) -> bool: ...

class OfflineTileProvider(org.osmdroid.tileprovider.MapTileProviderArray, org.osmdroid.tileprovider.IMapTileProviderCallback):
    def __init__(self, pRegisterReceiver: org.osmdroid.tileprovider.IRegisterReceiver, source: java.chaquopy.JavaArray[java.io.File], /) -> None: ...
    def detach(self) -> None: ...
    def getArchives(self) -> java.chaquopy.JavaArray[IArchiveFile]: ...

class SqlTileWriter(IFilesystemCache):
    DATABASE_FILENAME: typing.ClassVar[str] = ...
    COLUMN_EXPIRES: typing.ClassVar[str] = ...
    CLEANUP_ON_START: typing.ClassVar[bool] = ...
    db_file: java.io.File = ...
    db: android.database.sqlite.SQLiteDatabase = ...
    def __init__(self) -> None: ...
    @typing.overload
    def exists(self, pTileSource: str | java.lang.String, pTile: org.osmdroid.tileprovider.MapTile, /) -> bool: ...
    @typing.overload
    def exists(self, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, pTile: org.osmdroid.tileprovider.MapTile, /) -> bool: ...
    def getRowCount(self, tileSourceName: str | java.lang.String, /) -> int: ...
    def importFromFileCache(self, removeFromFileSystem: bool | java.jboolean | java.lang.Boolean, /) -> java.chaquopy.JavaArrayJInt: ...
    def onDetach(self) -> None: ...
    @typing.overload
    def purgeCache(self) -> bool: ...
    @typing.overload
    def purgeCache(self, mTileSourceName: str | java.lang.String, /) -> bool: ...
    def remove(self, pTileSourceInfo: org.osmdroid.tileprovider.tilesource.ITileSource, pTile: org.osmdroid.tileprovider.MapTile, /) -> bool: ...
    def runCleanupOperation(self) -> None: ...
    def saveFile(self, pTileSourceInfo: org.osmdroid.tileprovider.tilesource.ITileSource, pTile: org.osmdroid.tileprovider.MapTile, pStream: java.io.InputStream, /) -> bool: ...

class SqliteArchiveTileWriter(IFilesystemCache):
    def __init__(self, outputFile: str | java.lang.String, /) -> None: ...
    def exists(self, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, pTile: org.osmdroid.tileprovider.MapTile, /) -> bool: ...
    def onDetach(self) -> None: ...
    def remove(self, tileSource: org.osmdroid.tileprovider.tilesource.ITileSource, tile: org.osmdroid.tileprovider.MapTile, /) -> bool: ...
    def saveFile(self, pTileSourceInfo: org.osmdroid.tileprovider.tilesource.ITileSource, pTile: org.osmdroid.tileprovider.MapTile, pStream: java.io.InputStream, /) -> bool: ...

class TileWriter(IFilesystemCache):
    def __init__(self) -> None: ...
    def exists(self, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, pTile: org.osmdroid.tileprovider.MapTile, /) -> bool: ...
    @staticmethod
    def getUsedCacheSpace() -> int: ...
    def onDetach(self) -> None: ...
    def remove(self, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, pTile: org.osmdroid.tileprovider.MapTile, /) -> bool: ...
    def saveFile(self, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, pTile: org.osmdroid.tileprovider.MapTile, pStream: java.io.InputStream, /) -> bool: ...

class ZipFileArchive(IArchiveFile):
    mZipFile: java.util.zip.ZipFile = ...
    def __init__(self) -> None: ...
    def close(self) -> None: ...
    def getInputStream(self, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, pTile: org.osmdroid.tileprovider.MapTile, /) -> java.io.InputStream: ...
    def getTileSources(self) -> java.util.Set[java.lang.String]: ...
    @staticmethod
    def getZipFileArchive(pFile: java.io.File, /) -> ZipFileArchive: ...
    def init(self, pFile: java.io.File, /) -> None: ...
    def toString(self) -> str: ...
