import java.lang.annotation
import kotlin.jvm.internal

class strictfp(java.lang.annotation.Annotation, kotlin.jvm.internal.KObject): ...

class synchronized(java.lang.annotation.Annotation, kotlin.jvm.internal.KObject): ...

class transient(java.lang.annotation.Annotation, kotlin.jvm.internal.KObject): ...

class volatile(java.lang.annotation.Annotation, kotlin.jvm.internal.KObject): ...
