import typing

import java
import java.chaquopy
import java.lang
import java.lang.annotation
import java.util.concurrent
import kotlin
import kotlin.jvm.functions

class AbstractDoubleTimeSource(TimeSource):
    def __init__(self, unit: DurationUnit, /) -> None: ...
    def getUnit(self) -> DurationUnit: ...
    def markNow(self) -> TimeMark: ...
    def read(self) -> float: ...

class AbstractLongTimeSource(TimeSource):
    def __init__(self, unit: DurationUnit, /) -> None: ...
    def getUnit(self) -> DurationUnit: ...
    def markNow(self) -> TimeMark: ...
    def read(self) -> int: ...

class AdjustedTimeMark(TimeMark):
    def getMark(self) -> TimeMark: ...

class Duration(java.lang.Comparable[Duration]):
    Companion: typing.ClassVar[Duration.Companion] = ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

    class Companion(java.lang.Object):
        def convert(self, value: float | java.jdouble | java.lang.Double, sourceUnit: DurationUnit, targetUnit: DurationUnit, /) -> float: ...

class DurationJvmKt(java.lang.Object):
    @staticmethod
    def formatToExactDecimals(value: float | java.jdouble | java.lang.Double, decimals: int | java.jint | java.lang.Integer, /) -> str: ...
    @staticmethod
    def formatUpToDecimals(value: float | java.jdouble | java.lang.Double, decimals: int | java.jint | java.lang.Integer, /) -> str: ...
    @staticmethod
    def getDurationAssertionsEnabled() -> bool: ...

class DurationKt(java.lang.Object):
    NANOS_IN_MILLIS: typing.ClassVar[int] = ...
    MAX_NANOS: typing.ClassVar[int] = ...
    MAX_MILLIS: typing.ClassVar[int] = ...
    @typing.overload
    @staticmethod
    def getDays(this_days: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def getDays(this_days: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getDays(this_days: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def getHours(this_hours: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def getHours(this_hours: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getHours(this_hours: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMicroseconds(this_microseconds: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMicroseconds(this_microseconds: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMicroseconds(this_microseconds: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMilliseconds(this_milliseconds: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMilliseconds(this_milliseconds: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMilliseconds(this_milliseconds: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMinutes(this_minutes: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMinutes(this_minutes: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMinutes(this_minutes: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def getNanoseconds(this_nanoseconds: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def getNanoseconds(this_nanoseconds: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getNanoseconds(this_nanoseconds: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def getSeconds(this_seconds: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def getSeconds(this_seconds: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getSeconds(this_seconds: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def toDuration(this_toDuration: float | java.jdouble | java.lang.Double, unit: DurationUnit, /) -> int: ...
    @typing.overload
    @staticmethod
    def toDuration(this_toDuration: int | java.jint | java.lang.Integer, unit: DurationUnit, /) -> int: ...
    @typing.overload
    @staticmethod
    def toDuration(this_toDuration: int | java.jlong | java.lang.Long, unit: DurationUnit, /) -> int: ...

class DurationUnit(java.lang.Enum[DurationUnit]):
    NANOSECONDS: typing.ClassVar[DurationUnit] = ...
    MICROSECONDS: typing.ClassVar[DurationUnit] = ...
    MILLISECONDS: typing.ClassVar[DurationUnit] = ...
    SECONDS: typing.ClassVar[DurationUnit] = ...
    MINUTES: typing.ClassVar[DurationUnit] = ...
    HOURS: typing.ClassVar[DurationUnit] = ...
    DAYS: typing.ClassVar[DurationUnit] = ...
    @staticmethod
    def valueOf(value: str | java.lang.String, /) -> DurationUnit: ...
    @staticmethod
    def values() -> java.chaquopy.JavaArray[DurationUnit]: ...

class DurationUnitKt(DurationUnitKt__DurationUnitKt): ...

class DurationUnitKt__DurationUnitJvmKt(java.lang.Object):
    def __init__(self) -> None: ...
    @typing.overload
    @staticmethod
    def convertDurationUnit(value: float | java.jdouble | java.lang.Double, sourceUnit: DurationUnit, targetUnit: DurationUnit, /) -> float: ...
    @typing.overload
    @staticmethod
    def convertDurationUnit(value: int | java.jlong | java.lang.Long, sourceUnit: DurationUnit, targetUnit: DurationUnit, /) -> int: ...
    @staticmethod
    def convertDurationUnitOverflow(value: int | java.jlong | java.lang.Long, sourceUnit: DurationUnit, targetUnit: DurationUnit, /) -> int: ...
    @staticmethod
    def toDurationUnit(this_toDurationUnit: java.util.concurrent.TimeUnit, /) -> DurationUnit: ...
    @staticmethod
    def toTimeUnit(this_toTimeUnit: DurationUnit, /) -> java.util.concurrent.TimeUnit: ...

class DurationUnitKt__DurationUnitKt(DurationUnitKt__DurationUnitJvmKt):
    def __init__(self) -> None: ...
    @staticmethod
    def durationUnitByIsoChar(isoChar: str | java.jchar | java.lang.Character, isTimeComponent: bool | java.jboolean | java.lang.Boolean, /) -> DurationUnit: ...
    @staticmethod
    def durationUnitByShortName(shortName: str | java.lang.String, /) -> DurationUnit: ...
    @staticmethod
    def shortName(this_shortName: DurationUnit, /) -> str: ...

class ExperimentalTime(java.lang.annotation.Annotation): ...

class MeasureTimeKt(java.lang.Object):
    @typing.overload
    @staticmethod
    def measureTime(block: kotlin.jvm.functions.Function0[kotlin.Unit], /) -> int: ...
    @typing.overload
    @staticmethod
    def measureTime(this_measureTime: TimeSource, block: kotlin.jvm.functions.Function0[kotlin.Unit], /) -> int: ...
    _measureTimedValue_0__T = typing.TypeVar('_measureTimedValue_0__T')  # <T>
    _measureTimedValue_1__T = typing.TypeVar('_measureTimedValue_1__T')  # <T>
    @typing.overload
    @staticmethod
    def measureTimedValue(block: kotlin.jvm.functions.Function0[_measureTimedValue_0__T], /) -> TimedValue[_measureTimedValue_0__T]: ...
    @typing.overload
    @staticmethod
    def measureTimedValue(this_measureTimedValue: TimeSource, block: kotlin.jvm.functions.Function0[_measureTimedValue_1__T], /) -> TimedValue[_measureTimedValue_1__T]: ...

class MonotonicTimeSource(AbstractLongTimeSource, TimeSource):
    INSTANCE: typing.ClassVar[MonotonicTimeSource] = ...
    def read(self) -> int: ...
    def toString(self) -> str: ...

class TestTimeSource(AbstractLongTimeSource):
    def __init__(self) -> None: ...
    def read(self) -> int: ...

class TimeMark(java.lang.Object):
    def __init__(self) -> None: ...
    def hasNotPassedNow(self) -> bool: ...
    def hasPassedNow(self) -> bool: ...

class TimeSource(java.lang.Object):
    Companion: typing.ClassVar[TimeSource.Companion] = ...
    def markNow(self) -> TimeMark: ...

    class Monotonic(TimeSource):
        INSTANCE: typing.ClassVar[TimeSource.Monotonic] = ...
        def markNow(self) -> TimeMark: ...
        def toString(self) -> str: ...

    class Companion(java.lang.Object): ...

class TimeSourceKt(java.lang.Object): ...

_TimedValue__T = typing.TypeVar('_TimedValue__T')  # <T>
class TimedValue(java.lang.Object, typing.Generic[_TimedValue__T]):
    def component1(self) -> _TimedValue__T: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getValue(self) -> _TimedValue__T: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
