import typing

import java
import java.lang
import kotlin

_ComparableRange__T = typing.TypeVar('_ComparableRange__T')  # <T>
class ComparableRange(kotlin.ranges.ClosedRange[_ComparableRange__T], typing.Generic[_ComparableRange__T]):
    def __init__(self, start: _ComparableRange__T, endInclusive: _ComparableRange__T, /) -> None: ...
    def contains(self, value: _ComparableRange__T, /) -> bool: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getEndInclusive(self) -> _ComparableRange__T: ...
    def getStart(self) -> _ComparableRange__T: ...
    def hashCode(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def toString(self) -> str: ...

class RangesKt(java.lang.Object):
    @typing.overload
    @staticmethod
    def byteRangeContains(receiver: ClosedRange[java.lang.Byte], value: float | java.jdouble | java.lang.Double, /) -> bool: ...
    @typing.overload
    @staticmethod
    def byteRangeContains(receiver: ClosedRange[java.lang.Byte], value: float | java.jfloat | java.lang.Float, /) -> bool: ...
    @typing.overload
    @staticmethod
    def byteRangeContains(receiver: ClosedRange[java.lang.Byte], value: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    @staticmethod
    def byteRangeContains(receiver: ClosedRange[java.lang.Byte], value: int | java.jlong | java.lang.Long, /) -> bool: ...
    @typing.overload
    @staticmethod
    def byteRangeContains(receiver: ClosedRange[java.lang.Byte], value: int | java.jshort | java.lang.Short, /) -> bool: ...
    @staticmethod
    def checkStepIsPositive(isPositive: bool | java.jboolean | java.lang.Boolean, step: java.lang.Number, /) -> None: ...
    _coerceAtLeast_5__T = typing.TypeVar('_coerceAtLeast_5__T')  # <T>
    @typing.overload
    @staticmethod
    def coerceAtLeast(receiver: int | java.jbyte | java.lang.Byte, minimumValue: int | java.jbyte | java.lang.Byte, /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceAtLeast(receiver: float | java.jdouble | java.lang.Double, minimumValue: float | java.jdouble | java.lang.Double, /) -> float: ...
    @typing.overload
    @staticmethod
    def coerceAtLeast(receiver: float | java.jfloat | java.lang.Float, minimumValue: float | java.jfloat | java.lang.Float, /) -> float: ...
    @typing.overload
    @staticmethod
    def coerceAtLeast(receiver: int | java.jint | java.lang.Integer, minimumValue: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceAtLeast(receiver: int | java.jlong | java.lang.Long, minimumValue: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceAtLeast(receiver: _coerceAtLeast_5__T, minimumValue: _coerceAtLeast_5__T, /) -> _coerceAtLeast_5__T: ...
    @typing.overload
    @staticmethod
    def coerceAtLeast(receiver: int | java.jshort | java.lang.Short, minimumValue: int | java.jshort | java.lang.Short, /) -> int: ...
    _coerceAtMost_5__T = typing.TypeVar('_coerceAtMost_5__T')  # <T>
    @typing.overload
    @staticmethod
    def coerceAtMost(receiver: int | java.jbyte | java.lang.Byte, maximumValue: int | java.jbyte | java.lang.Byte, /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceAtMost(receiver: float | java.jdouble | java.lang.Double, maximumValue: float | java.jdouble | java.lang.Double, /) -> float: ...
    @typing.overload
    @staticmethod
    def coerceAtMost(receiver: float | java.jfloat | java.lang.Float, maximumValue: float | java.jfloat | java.lang.Float, /) -> float: ...
    @typing.overload
    @staticmethod
    def coerceAtMost(receiver: int | java.jint | java.lang.Integer, maximumValue: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceAtMost(receiver: int | java.jlong | java.lang.Long, maximumValue: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceAtMost(receiver: _coerceAtMost_5__T, maximumValue: _coerceAtMost_5__T, /) -> _coerceAtMost_5__T: ...
    @typing.overload
    @staticmethod
    def coerceAtMost(receiver: int | java.jshort | java.lang.Short, maximumValue: int | java.jshort | java.lang.Short, /) -> int: ...
    _coerceIn_2__T = typing.TypeVar('_coerceIn_2__T')  # <T>
    _coerceIn_8__T = typing.TypeVar('_coerceIn_8__T')  # <T>
    @typing.overload
    @staticmethod
    def coerceIn(receiver: int | java.jint | java.lang.Integer, range: ClosedRange[java.lang.Integer], /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceIn(receiver: int | java.jlong | java.lang.Long, range: ClosedRange[java.lang.Long], /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceIn(receiver: _coerceIn_2__T, range: ClosedRange[_coerceIn_2__T], /) -> _coerceIn_2__T: ...
    @typing.overload
    @staticmethod
    def coerceIn(receiver: int | java.jbyte | java.lang.Byte, minimumValue: int | java.jbyte | java.lang.Byte, maximumValue: int | java.jbyte | java.lang.Byte, /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceIn(receiver: float | java.jdouble | java.lang.Double, minimumValue: float | java.jdouble | java.lang.Double, maximumValue: float | java.jdouble | java.lang.Double, /) -> float: ...
    @typing.overload
    @staticmethod
    def coerceIn(receiver: float | java.jfloat | java.lang.Float, minimumValue: float | java.jfloat | java.lang.Float, maximumValue: float | java.jfloat | java.lang.Float, /) -> float: ...
    @typing.overload
    @staticmethod
    def coerceIn(receiver: int | java.jint | java.lang.Integer, minimumValue: int | java.jint | java.lang.Integer, maximumValue: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceIn(receiver: int | java.jlong | java.lang.Long, minimumValue: int | java.jlong | java.lang.Long, maximumValue: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def coerceIn(receiver: _coerceIn_8__T, minimumValue: _coerceIn_8__T, maximumValue: _coerceIn_8__T, /) -> _coerceIn_8__T: ...
    @typing.overload
    @staticmethod
    def coerceIn(receiver: int | java.jshort | java.lang.Short, minimumValue: int | java.jshort | java.lang.Short, maximumValue: int | java.jshort | java.lang.Short, /) -> int: ...
    @typing.overload
    @staticmethod
    def doubleRangeContains(receiver: ClosedRange[java.lang.Double], value: int | java.jbyte | java.lang.Byte, /) -> bool: ...
    @typing.overload
    @staticmethod
    def doubleRangeContains(receiver: ClosedRange[java.lang.Double], value: float | java.jfloat | java.lang.Float, /) -> bool: ...
    @typing.overload
    @staticmethod
    def doubleRangeContains(receiver: ClosedRange[java.lang.Double], value: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    @staticmethod
    def doubleRangeContains(receiver: ClosedRange[java.lang.Double], value: int | java.jlong | java.lang.Long, /) -> bool: ...
    @typing.overload
    @staticmethod
    def doubleRangeContains(receiver: ClosedRange[java.lang.Double], value: int | java.jshort | java.lang.Short, /) -> bool: ...
    @typing.overload
    @staticmethod
    def downTo(receiver: int | java.jbyte | java.lang.Byte, to: int | java.jbyte | java.lang.Byte, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def downTo(receiver: int | java.jbyte | java.lang.Byte, to: int | java.jint | java.lang.Integer, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def downTo(receiver: int | java.jbyte | java.lang.Byte, to: int | java.jlong | java.lang.Long, /) -> LongProgression: ...
    @typing.overload
    @staticmethod
    def downTo(receiver: int | java.jbyte | java.lang.Byte, to: int | java.jshort | java.lang.Short, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def downTo(receiver: str | java.jchar | java.lang.Character, to: str | java.jchar | java.lang.Character, /) -> CharProgression: ...
    @typing.overload
    @staticmethod
    def downTo(receiver: int | java.jint | java.lang.Integer, to: int | java.jbyte | java.lang.Byte, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def downTo(receiver: int | java.jint | java.lang.Integer, to: int | java.jint | java.lang.Integer, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def downTo(receiver: int | java.jint | java.lang.Integer, to: int | java.jlong | java.lang.Long, /) -> LongProgression: ...
    @typing.overload
    @staticmethod
    def downTo(receiver: int | java.jint | java.lang.Integer, to: int | java.jshort | java.lang.Short, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def downTo(receiver: int | java.jlong | java.lang.Long, to: int | java.jbyte | java.lang.Byte, /) -> LongProgression: ...
    @typing.overload
    @staticmethod
    def downTo(receiver: int | java.jlong | java.lang.Long, to: int | java.jint | java.lang.Integer, /) -> LongProgression: ...
    @typing.overload
    @staticmethod
    def downTo(receiver: int | java.jlong | java.lang.Long, to: int | java.jlong | java.lang.Long, /) -> LongProgression: ...
    @typing.overload
    @staticmethod
    def downTo(receiver: int | java.jlong | java.lang.Long, to: int | java.jshort | java.lang.Short, /) -> LongProgression: ...
    @typing.overload
    @staticmethod
    def downTo(receiver: int | java.jshort | java.lang.Short, to: int | java.jbyte | java.lang.Byte, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def downTo(receiver: int | java.jshort | java.lang.Short, to: int | java.jint | java.lang.Integer, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def downTo(receiver: int | java.jshort | java.lang.Short, to: int | java.jlong | java.lang.Long, /) -> LongProgression: ...
    @typing.overload
    @staticmethod
    def downTo(receiver: int | java.jshort | java.lang.Short, to: int | java.jshort | java.lang.Short, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def floatRangeContains(receiver: ClosedRange[java.lang.Float], value: int | java.jbyte | java.lang.Byte, /) -> bool: ...
    @typing.overload
    @staticmethod
    def floatRangeContains(receiver: ClosedRange[java.lang.Float], value: float | java.jdouble | java.lang.Double, /) -> bool: ...
    @typing.overload
    @staticmethod
    def floatRangeContains(receiver: ClosedRange[java.lang.Float], value: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    @staticmethod
    def floatRangeContains(receiver: ClosedRange[java.lang.Float], value: int | java.jlong | java.lang.Long, /) -> bool: ...
    @typing.overload
    @staticmethod
    def floatRangeContains(receiver: ClosedRange[java.lang.Float], value: int | java.jshort | java.lang.Short, /) -> bool: ...
    @typing.overload
    @staticmethod
    def intRangeContains(receiver: ClosedRange[java.lang.Integer], value: int | java.jbyte | java.lang.Byte, /) -> bool: ...
    @typing.overload
    @staticmethod
    def intRangeContains(receiver: ClosedRange[java.lang.Integer], value: float | java.jdouble | java.lang.Double, /) -> bool: ...
    @typing.overload
    @staticmethod
    def intRangeContains(receiver: ClosedRange[java.lang.Integer], value: float | java.jfloat | java.lang.Float, /) -> bool: ...
    @typing.overload
    @staticmethod
    def intRangeContains(receiver: ClosedRange[java.lang.Integer], value: int | java.jlong | java.lang.Long, /) -> bool: ...
    @typing.overload
    @staticmethod
    def intRangeContains(receiver: ClosedRange[java.lang.Integer], value: int | java.jshort | java.lang.Short, /) -> bool: ...
    @typing.overload
    @staticmethod
    def longRangeContains(receiver: ClosedRange[java.lang.Long], value: int | java.jbyte | java.lang.Byte, /) -> bool: ...
    @typing.overload
    @staticmethod
    def longRangeContains(receiver: ClosedRange[java.lang.Long], value: float | java.jdouble | java.lang.Double, /) -> bool: ...
    @typing.overload
    @staticmethod
    def longRangeContains(receiver: ClosedRange[java.lang.Long], value: float | java.jfloat | java.lang.Float, /) -> bool: ...
    @typing.overload
    @staticmethod
    def longRangeContains(receiver: ClosedRange[java.lang.Long], value: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    @staticmethod
    def longRangeContains(receiver: ClosedRange[java.lang.Long], value: int | java.jshort | java.lang.Short, /) -> bool: ...
    _rangeTo__T = typing.TypeVar('_rangeTo__T')  # <T>
    @staticmethod
    def rangeTo(receiver: _rangeTo__T, that: _rangeTo__T, /) -> ClosedRange[_rangeTo__T]: ...
    @typing.overload
    @staticmethod
    def reversed(receiver: CharProgression, /) -> CharProgression: ...
    @typing.overload
    @staticmethod
    def reversed(receiver: IntProgression, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def reversed(receiver: LongProgression, /) -> LongProgression: ...
    @typing.overload
    @staticmethod
    def shortRangeContains(receiver: ClosedRange[java.lang.Short], value: int | java.jbyte | java.lang.Byte, /) -> bool: ...
    @typing.overload
    @staticmethod
    def shortRangeContains(receiver: ClosedRange[java.lang.Short], value: float | java.jdouble | java.lang.Double, /) -> bool: ...
    @typing.overload
    @staticmethod
    def shortRangeContains(receiver: ClosedRange[java.lang.Short], value: float | java.jfloat | java.lang.Float, /) -> bool: ...
    @typing.overload
    @staticmethod
    def shortRangeContains(receiver: ClosedRange[java.lang.Short], value: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    @staticmethod
    def shortRangeContains(receiver: ClosedRange[java.lang.Short], value: int | java.jlong | java.lang.Long, /) -> bool: ...
    @typing.overload
    @staticmethod
    def step(receiver: CharProgression, step: int | java.jint | java.lang.Integer, /) -> CharProgression: ...
    @typing.overload
    @staticmethod
    def step(receiver: IntProgression, step: int | java.jint | java.lang.Integer, /) -> IntProgression: ...
    @typing.overload
    @staticmethod
    def step(receiver: LongProgression, step: int | java.jlong | java.lang.Long, /) -> LongProgression: ...
    @typing.overload
    @staticmethod
    def until(receiver: int | java.jbyte | java.lang.Byte, to: int | java.jbyte | java.lang.Byte, /) -> IntRange: ...
    @typing.overload
    @staticmethod
    def until(receiver: int | java.jbyte | java.lang.Byte, to: int | java.jint | java.lang.Integer, /) -> IntRange: ...
    @typing.overload
    @staticmethod
    def until(receiver: int | java.jbyte | java.lang.Byte, to: int | java.jlong | java.lang.Long, /) -> LongRange: ...
    @typing.overload
    @staticmethod
    def until(receiver: int | java.jbyte | java.lang.Byte, to: int | java.jshort | java.lang.Short, /) -> IntRange: ...
    @typing.overload
    @staticmethod
    def until(receiver: str | java.jchar | java.lang.Character, to: str | java.jchar | java.lang.Character, /) -> CharRange: ...
    @typing.overload
    @staticmethod
    def until(receiver: int | java.jint | java.lang.Integer, to: int | java.jbyte | java.lang.Byte, /) -> IntRange: ...
    @typing.overload
    @staticmethod
    def until(receiver: int | java.jint | java.lang.Integer, to: int | java.jint | java.lang.Integer, /) -> IntRange: ...
    @typing.overload
    @staticmethod
    def until(receiver: int | java.jint | java.lang.Integer, to: int | java.jlong | java.lang.Long, /) -> LongRange: ...
    @typing.overload
    @staticmethod
    def until(receiver: int | java.jint | java.lang.Integer, to: int | java.jshort | java.lang.Short, /) -> IntRange: ...
    @typing.overload
    @staticmethod
    def until(receiver: int | java.jlong | java.lang.Long, to: int | java.jbyte | java.lang.Byte, /) -> LongRange: ...
    @typing.overload
    @staticmethod
    def until(receiver: int | java.jlong | java.lang.Long, to: int | java.jint | java.lang.Integer, /) -> LongRange: ...
    @typing.overload
    @staticmethod
    def until(receiver: int | java.jlong | java.lang.Long, to: int | java.jlong | java.lang.Long, /) -> LongRange: ...
    @typing.overload
    @staticmethod
    def until(receiver: int | java.jlong | java.lang.Long, to: int | java.jshort | java.lang.Short, /) -> LongRange: ...
    @typing.overload
    @staticmethod
    def until(receiver: int | java.jshort | java.lang.Short, to: int | java.jbyte | java.lang.Byte, /) -> IntRange: ...
    @typing.overload
    @staticmethod
    def until(receiver: int | java.jshort | java.lang.Short, to: int | java.jint | java.lang.Integer, /) -> IntRange: ...
    @typing.overload
    @staticmethod
    def until(receiver: int | java.jshort | java.lang.Short, to: int | java.jlong | java.lang.Long, /) -> LongRange: ...
    @typing.overload
    @staticmethod
    def until(receiver: int | java.jshort | java.lang.Short, to: int | java.jshort | java.lang.Short, /) -> IntRange: ...
