import typing

import android.app
import android.content
import android.content.res
import android.database
import android.graphics.drawable
import android.os
import android.util
import android.view
import android.widget
import androidx.appcompat.graphics.drawable
import androidx.appcompat.view
import androidx.appcompat.view.menu
import androidx.appcompat.widget
import androidx.core.app
import androidx.drawerlayout.widget
import androidx.fragment.app
import java
import java.chaquopy
import java.lang
import java.lang.annotation

class ActionBar(java.lang.Object):
    NAVIGATION_MODE_STANDARD: typing.ClassVar[int] = ...
    NAVIGATION_MODE_LIST: typing.ClassVar[int] = ...
    NAVIGATION_MODE_TABS: typing.ClassVar[int] = ...
    DISPLAY_USE_LOGO: typing.ClassVar[int] = ...
    DISPLAY_SHOW_HOME: typing.ClassVar[int] = ...
    DISPLAY_HOME_AS_UP: typing.ClassVar[int] = ...
    DISPLAY_SHOW_TITLE: typing.ClassVar[int] = ...
    DISPLAY_SHOW_CUSTOM: typing.ClassVar[int] = ...
    def __init__(self) -> None: ...
    def addOnMenuVisibilityListener(self, arg1: ActionBar.OnMenuVisibilityListener, /) -> None: ...
    @typing.overload
    def addTab(self, arg1: ActionBar.Tab, /) -> None: ...
    @typing.overload
    def addTab(self, arg1: ActionBar.Tab, arg2: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def addTab(self, arg1: ActionBar.Tab, arg2: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def addTab(self, arg1: ActionBar.Tab, arg2: int | java.jint | java.lang.Integer, arg3: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def closeOptionsMenu(self) -> bool: ...
    def collapseActionView(self) -> bool: ...
    def dispatchMenuVisibilityChanged(self, visible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def getCustomView(self) -> android.view.View: ...
    def getDisplayOptions(self) -> int: ...
    def getElevation(self) -> float: ...
    def getHeight(self) -> int: ...
    def getHideOffset(self) -> int: ...
    def getNavigationItemCount(self) -> int: ...
    def getNavigationMode(self) -> int: ...
    def getSelectedNavigationIndex(self) -> int: ...
    def getSelectedTab(self) -> ActionBar.Tab: ...
    def getSubtitle(self) -> java.lang.CharSequence: ...
    def getTabAt(self, arg1: int | java.jint | java.lang.Integer, /) -> ActionBar.Tab: ...
    def getTabCount(self) -> int: ...
    def getThemedContext(self) -> android.content.Context: ...
    def getTitle(self) -> java.lang.CharSequence: ...
    def hide(self) -> None: ...
    def invalidateOptionsMenu(self) -> bool: ...
    def isHideOnContentScrollEnabled(self) -> bool: ...
    def isShowing(self) -> bool: ...
    def isTitleTruncated(self) -> bool: ...
    def newTab(self) -> ActionBar.Tab: ...
    def onConfigurationChanged(self, config: android.content.res.Configuration, /) -> None: ...
    def onKeyShortcut(self, keyCode: int | java.jint | java.lang.Integer, ev: android.view.KeyEvent, /) -> bool: ...
    def onMenuKeyEvent(self, event: android.view.KeyEvent, /) -> bool: ...
    def openOptionsMenu(self) -> bool: ...
    def removeAllTabs(self) -> None: ...
    def removeOnMenuVisibilityListener(self, arg1: ActionBar.OnMenuVisibilityListener, /) -> None: ...
    def removeTab(self, arg1: ActionBar.Tab, /) -> None: ...
    def removeTabAt(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
    def selectTab(self, arg1: ActionBar.Tab, /) -> None: ...
    def setBackgroundDrawable(self, arg1: android.graphics.drawable.Drawable, /) -> None: ...
    @typing.overload
    def setCustomView(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCustomView(self, arg1: android.view.View, /) -> None: ...
    @typing.overload
    def setCustomView(self, arg1: android.view.View, arg2: ActionBar.LayoutParams, /) -> None: ...
    def setDefaultDisplayHomeAsUpEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDisplayHomeAsUpEnabled(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def setDisplayOptions(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setDisplayOptions(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDisplayShowCustomEnabled(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDisplayShowHomeEnabled(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDisplayShowTitleEnabled(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDisplayUseLogoEnabled(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setElevation(self, elevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setHideOffset(self, offset: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHideOnContentScrollEnabled(self, hideOnContentScroll: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def setHomeActionContentDescription(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setHomeActionContentDescription(self, description: java.lang.CharSequence, /) -> None: ...
    @typing.overload
    def setHomeAsUpIndicator(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setHomeAsUpIndicator(self, indicator: android.graphics.drawable.Drawable, /) -> None: ...
    def setHomeButtonEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def setIcon(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setIcon(self, arg1: android.graphics.drawable.Drawable, /) -> None: ...
    def setListNavigationCallbacks(self, arg1: android.widget.SpinnerAdapter, arg2: ActionBar.OnNavigationListener, /) -> None: ...
    @typing.overload
    def setLogo(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setLogo(self, arg1: android.graphics.drawable.Drawable, /) -> None: ...
    def setNavigationMode(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
    def setSelectedNavigationItem(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
    def setShowHideAnimationEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setSplitBackgroundDrawable(self, d: android.graphics.drawable.Drawable, /) -> None: ...
    def setStackedBackgroundDrawable(self, d: android.graphics.drawable.Drawable, /) -> None: ...
    @typing.overload
    def setSubtitle(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setSubtitle(self, arg1: java.lang.CharSequence, /) -> None: ...
    @typing.overload
    def setTitle(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setTitle(self, arg1: java.lang.CharSequence, /) -> None: ...
    def setWindowTitle(self, title: java.lang.CharSequence, /) -> None: ...
    def show(self) -> None: ...
    def startActionMode(self, callback: androidx.appcompat.view.ActionMode.Callback, /) -> androidx.appcompat.view.ActionMode: ...

    class LayoutParams(android.view.ViewGroup.MarginLayoutParams):
        gravity: int = ...
        @typing.overload
        def __init__(self, gravity: int | java.jint | java.lang.Integer, /) -> None: ...
        @typing.overload
        def __init__(self, source: android.view.ViewGroup.LayoutParams, /) -> None: ...
        @typing.overload
        def __init__(self, source: ActionBar.LayoutParams, /) -> None: ...
        @typing.overload
        def __init__(self, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, /) -> None: ...
        @typing.overload
        def __init__(self, c: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
        @typing.overload
        def __init__(self, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, gravity: int | java.jint | java.lang.Integer, /) -> None: ...

    class TabListener(java.lang.Object):
        def onTabReselected(self, arg1: ActionBar.Tab, arg2: androidx.fragment.app.FragmentTransaction, /) -> None: ...
        def onTabSelected(self, arg1: ActionBar.Tab, arg2: androidx.fragment.app.FragmentTransaction, /) -> None: ...
        def onTabUnselected(self, arg1: ActionBar.Tab, arg2: androidx.fragment.app.FragmentTransaction, /) -> None: ...

    class Tab(java.lang.Object):
        INVALID_POSITION: typing.ClassVar[int] = ...
        def __init__(self) -> None: ...
        def getContentDescription(self) -> java.lang.CharSequence: ...
        def getCustomView(self) -> android.view.View: ...
        def getIcon(self) -> android.graphics.drawable.Drawable: ...
        def getPosition(self) -> int: ...
        def getTag(self) -> java.lang.Object: ...
        def getText(self) -> java.lang.CharSequence: ...
        def select(self) -> None: ...
        @typing.overload
        def setContentDescription(self, arg1: int | java.jint | java.lang.Integer, /) -> ActionBar.Tab: ...
        @typing.overload
        def setContentDescription(self, arg1: java.lang.CharSequence, /) -> ActionBar.Tab: ...
        @typing.overload
        def setCustomView(self, arg1: int | java.jint | java.lang.Integer, /) -> ActionBar.Tab: ...
        @typing.overload
        def setCustomView(self, arg1: android.view.View, /) -> ActionBar.Tab: ...
        @typing.overload
        def setIcon(self, arg1: int | java.jint | java.lang.Integer, /) -> ActionBar.Tab: ...
        @typing.overload
        def setIcon(self, arg1: android.graphics.drawable.Drawable, /) -> ActionBar.Tab: ...
        def setTabListener(self, arg1: ActionBar.TabListener, /) -> ActionBar.Tab: ...
        def setTag(self, arg1: java.lang.Object | int | bool | float | str, /) -> ActionBar.Tab: ...
        @typing.overload
        def setText(self, arg1: int | java.jint | java.lang.Integer, /) -> ActionBar.Tab: ...
        @typing.overload
        def setText(self, arg1: java.lang.CharSequence, /) -> ActionBar.Tab: ...

    class OnMenuVisibilityListener(java.lang.Object):
        def onMenuVisibilityChanged(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

    class OnNavigationListener(java.lang.Object):
        def onNavigationItemSelected(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jlong | java.lang.Long, /) -> bool: ...

    class DisplayOptions(java.lang.annotation.Annotation): ...

    class NavigationMode(java.lang.annotation.Annotation): ...

class ActionBarDrawerToggle(androidx.drawerlayout.widget.DrawerLayout.DrawerListener):
    @typing.overload
    def __init__(self, activity: android.app.Activity, drawerLayout: androidx.drawerlayout.widget.DrawerLayout, openDrawerContentDescRes: int | java.jint | java.lang.Integer, closeDrawerContentDescRes: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, activity: android.app.Activity, drawerLayout: androidx.drawerlayout.widget.DrawerLayout, toolbar: androidx.appcompat.widget.Toolbar, openDrawerContentDescRes: int | java.jint | java.lang.Integer, closeDrawerContentDescRes: int | java.jint | java.lang.Integer, /) -> None: ...
    def getDrawerArrowDrawable(self) -> androidx.appcompat.graphics.drawable.DrawerArrowDrawable: ...
    def getToolbarNavigationClickListener(self) -> android.view.View.OnClickListener: ...
    def isDrawerIndicatorEnabled(self) -> bool: ...
    def isDrawerSlideAnimationEnabled(self) -> bool: ...
    def onConfigurationChanged(self, newConfig: android.content.res.Configuration, /) -> None: ...
    def onDrawerClosed(self, drawerView: android.view.View, /) -> None: ...
    def onDrawerOpened(self, drawerView: android.view.View, /) -> None: ...
    def onDrawerSlide(self, drawerView: android.view.View, slideOffset: float | java.jfloat | java.lang.Float, /) -> None: ...
    def onDrawerStateChanged(self, newState: int | java.jint | java.lang.Integer, /) -> None: ...
    def onOptionsItemSelected(self, item: android.view.MenuItem, /) -> bool: ...
    def setDrawerArrowDrawable(self, drawable: androidx.appcompat.graphics.drawable.DrawerArrowDrawable, /) -> None: ...
    def setDrawerIndicatorEnabled(self, enable: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDrawerSlideAnimationEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def setHomeAsUpIndicator(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setHomeAsUpIndicator(self, indicator: android.graphics.drawable.Drawable, /) -> None: ...
    def setToolbarNavigationClickListener(self, onToolbarNavigationClickListener: android.view.View.OnClickListener, /) -> None: ...
    def syncState(self) -> None: ...

    class Delegate(java.lang.Object):
        def getActionBarThemedContext(self) -> android.content.Context: ...
        def getThemeUpIndicator(self) -> android.graphics.drawable.Drawable: ...
        def isNavigationVisible(self) -> bool: ...
        def setActionBarDescription(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
        def setActionBarUpIndicator(self, arg1: android.graphics.drawable.Drawable, arg2: int | java.jint | java.lang.Integer, /) -> None: ...

    class DelegateProvider(java.lang.Object):
        def getDrawerToggleDelegate(self) -> ActionBarDrawerToggle.Delegate: ...

class ActionBarDrawerToggleHoneycomb(java.lang.Object):
    @staticmethod
    def getThemeUpIndicator(activity: android.app.Activity, /) -> android.graphics.drawable.Drawable: ...
    @staticmethod
    def setActionBarDescription(info: ActionBarDrawerToggleHoneycomb.SetIndicatorInfo, activity: android.app.Activity, contentDescRes: int | java.jint | java.lang.Integer, /) -> ActionBarDrawerToggleHoneycomb.SetIndicatorInfo: ...
    @staticmethod
    def setActionBarUpIndicator(activity: android.app.Activity, drawable: android.graphics.drawable.Drawable, contentDescRes: int | java.jint | java.lang.Integer, /) -> ActionBarDrawerToggleHoneycomb.SetIndicatorInfo: ...

class AlertController(java.lang.Object):
    def __init__(self, context: android.content.Context, di: AppCompatDialog, window: android.view.Window, /) -> None: ...
    def getButton(self, whichButton: int | java.jint | java.lang.Integer, /) -> android.widget.Button: ...
    def getIconAttributeResId(self, attrId: int | java.jint | java.lang.Integer, /) -> int: ...
    def getListView(self) -> android.widget.ListView: ...
    def installContent(self) -> None: ...
    def onKeyDown(self, keyCode: int | java.jint | java.lang.Integer, event: android.view.KeyEvent, /) -> bool: ...
    def onKeyUp(self, keyCode: int | java.jint | java.lang.Integer, event: android.view.KeyEvent, /) -> bool: ...
    def setButton(self, whichButton: int | java.jint | java.lang.Integer, text: java.lang.CharSequence, listener: android.content.DialogInterface.OnClickListener, msg: android.os.Message, icon: android.graphics.drawable.Drawable, /) -> None: ...
    def setButtonPanelLayoutHint(self, layoutHint: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCustomTitle(self, customTitleView: android.view.View, /) -> None: ...
    @typing.overload
    def setIcon(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setIcon(self, icon: android.graphics.drawable.Drawable, /) -> None: ...
    def setMessage(self, message: java.lang.CharSequence, /) -> None: ...
    def setTitle(self, title: java.lang.CharSequence, /) -> None: ...
    @typing.overload
    def setView(self, layoutResId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setView(self, view: android.view.View, /) -> None: ...
    @typing.overload
    def setView(self, view: android.view.View, viewSpacingLeft: int | java.jint | java.lang.Integer, viewSpacingTop: int | java.jint | java.lang.Integer, viewSpacingRight: int | java.jint | java.lang.Integer, viewSpacingBottom: int | java.jint | java.lang.Integer, /) -> None: ...

    class AlertParams(java.lang.Object):
        mContext: android.content.Context = ...
        mInflater: android.view.LayoutInflater = ...
        mIconId: int = ...
        mIcon: android.graphics.drawable.Drawable = ...
        mIconAttrId: int = ...
        mTitle: java.lang.CharSequence = ...
        mCustomTitleView: android.view.View = ...
        mMessage: java.lang.CharSequence = ...
        mPositiveButtonText: java.lang.CharSequence = ...
        mPositiveButtonIcon: android.graphics.drawable.Drawable = ...
        mPositiveButtonListener: android.content.DialogInterface.OnClickListener = ...
        mNegativeButtonText: java.lang.CharSequence = ...
        mNegativeButtonIcon: android.graphics.drawable.Drawable = ...
        mNegativeButtonListener: android.content.DialogInterface.OnClickListener = ...
        mNeutralButtonText: java.lang.CharSequence = ...
        mNeutralButtonIcon: android.graphics.drawable.Drawable = ...
        mNeutralButtonListener: android.content.DialogInterface.OnClickListener = ...
        mCancelable: bool = ...
        mOnCancelListener: android.content.DialogInterface.OnCancelListener = ...
        mOnDismissListener: android.content.DialogInterface.OnDismissListener = ...
        mOnKeyListener: android.content.DialogInterface.OnKeyListener = ...
        mItems: java.chaquopy.JavaArray[java.lang.CharSequence] = ...
        mAdapter: android.widget.ListAdapter = ...
        mOnClickListener: android.content.DialogInterface.OnClickListener = ...
        mViewLayoutResId: int = ...
        mView: android.view.View = ...
        mViewSpacingLeft: int = ...
        mViewSpacingTop: int = ...
        mViewSpacingRight: int = ...
        mViewSpacingBottom: int = ...
        mViewSpacingSpecified: bool = ...
        mCheckedItems: java.chaquopy.JavaArrayJBoolean = ...
        mIsMultiChoice: bool = ...
        mIsSingleChoice: bool = ...
        mCheckedItem: int = ...
        mOnCheckboxClickListener: android.content.DialogInterface.OnMultiChoiceClickListener = ...
        mCursor: android.database.Cursor = ...
        mLabelColumn: str = ...
        mIsCheckedColumn: str = ...
        mForceInverseBackground: bool = ...
        mOnItemSelectedListener: android.widget.AdapterView.OnItemSelectedListener = ...
        mOnPrepareListViewListener: AlertController.AlertParams.OnPrepareListViewListener = ...
        mRecycleOnMeasure: bool = ...
        def __init__(self, context: android.content.Context, /) -> None: ...
        def apply(self, dialog: AlertController, /) -> None: ...

        class OnPrepareListViewListener(java.lang.Object):
            def onPrepareListView(self, arg1: android.widget.ListView, /) -> None: ...

    class RecycleListView(android.widget.ListView):
        @typing.overload
        def __init__(self, context: android.content.Context, /) -> None: ...
        @typing.overload
        def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
        def setHasDecor(self, hasTitle: bool | java.jboolean | java.lang.Boolean, hasButtons: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class AlertDialog(AppCompatDialog, android.content.DialogInterface):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, themeResId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, cancelable: bool | java.jboolean | java.lang.Boolean, cancelListener: android.content.DialogInterface.OnCancelListener, /) -> None: ...
    def getButton(self, whichButton: int | java.jint | java.lang.Integer, /) -> android.widget.Button: ...
    def getListView(self) -> android.widget.ListView: ...
    def onCreate(self, savedInstanceState: android.os.Bundle, /) -> None: ...
    def onKeyDown(self, keyCode: int | java.jint | java.lang.Integer, event: android.view.KeyEvent, /) -> bool: ...
    def onKeyUp(self, keyCode: int | java.jint | java.lang.Integer, event: android.view.KeyEvent, /) -> bool: ...
    @typing.overload
    def setButton(self, whichButton: int | java.jint | java.lang.Integer, text: java.lang.CharSequence, listener: android.content.DialogInterface.OnClickListener, /) -> None: ...
    @typing.overload
    def setButton(self, whichButton: int | java.jint | java.lang.Integer, text: java.lang.CharSequence, msg: android.os.Message, /) -> None: ...
    @typing.overload
    def setButton(self, whichButton: int | java.jint | java.lang.Integer, text: java.lang.CharSequence, icon: android.graphics.drawable.Drawable, listener: android.content.DialogInterface.OnClickListener, /) -> None: ...
    def setCustomTitle(self, customTitleView: android.view.View, /) -> None: ...
    @typing.overload
    def setIcon(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setIcon(self, icon: android.graphics.drawable.Drawable, /) -> None: ...
    def setIconAttribute(self, attrId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMessage(self, message: java.lang.CharSequence, /) -> None: ...
    def setTitle(self, title: java.lang.CharSequence, /) -> None: ...
    @typing.overload
    def setView(self, view: android.view.View, /) -> None: ...
    @typing.overload
    def setView(self, view: android.view.View, viewSpacingLeft: int | java.jint | java.lang.Integer, viewSpacingTop: int | java.jint | java.lang.Integer, viewSpacingRight: int | java.jint | java.lang.Integer, viewSpacingBottom: int | java.jint | java.lang.Integer, /) -> None: ...

    class Builder(java.lang.Object):
        @typing.overload
        def __init__(self, context: android.content.Context, /) -> None: ...
        @typing.overload
        def __init__(self, context: android.content.Context, themeResId: int | java.jint | java.lang.Integer, /) -> None: ...
        def create(self) -> AlertDialog: ...
        def getContext(self) -> android.content.Context: ...
        def setAdapter(self, adapter: android.widget.ListAdapter, listener: android.content.DialogInterface.OnClickListener, /) -> AlertDialog.Builder: ...
        def setCancelable(self, cancelable: bool | java.jboolean | java.lang.Boolean, /) -> AlertDialog.Builder: ...
        def setCursor(self, cursor: android.database.Cursor, listener: android.content.DialogInterface.OnClickListener, labelColumn: str | java.lang.String, /) -> AlertDialog.Builder: ...
        def setCustomTitle(self, customTitleView: android.view.View, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setIcon(self, iconId: int | java.jint | java.lang.Integer, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setIcon(self, icon: android.graphics.drawable.Drawable, /) -> AlertDialog.Builder: ...
        def setIconAttribute(self, attrId: int | java.jint | java.lang.Integer, /) -> AlertDialog.Builder: ...
        def setInverseBackgroundForced(self, useInverseBackground: bool | java.jboolean | java.lang.Boolean, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setItems(self, itemsId: int | java.jint | java.lang.Integer, listener: android.content.DialogInterface.OnClickListener, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setItems(self, items: java.chaquopy.JavaArray[java.lang.CharSequence], listener: android.content.DialogInterface.OnClickListener, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setMessage(self, messageId: int | java.jint | java.lang.Integer, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setMessage(self, message: java.lang.CharSequence, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setMultiChoiceItems(self, itemsId: int | java.jint | java.lang.Integer, checkedItems: java.chaquopy.JavaArrayJBoolean, listener: android.content.DialogInterface.OnMultiChoiceClickListener, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setMultiChoiceItems(self, items: java.chaquopy.JavaArray[java.lang.CharSequence], checkedItems: java.chaquopy.JavaArrayJBoolean, listener: android.content.DialogInterface.OnMultiChoiceClickListener, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setMultiChoiceItems(self, cursor: android.database.Cursor, isCheckedColumn: str | java.lang.String, labelColumn: str | java.lang.String, listener: android.content.DialogInterface.OnMultiChoiceClickListener, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setNegativeButton(self, textId: int | java.jint | java.lang.Integer, listener: android.content.DialogInterface.OnClickListener, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setNegativeButton(self, text: java.lang.CharSequence, listener: android.content.DialogInterface.OnClickListener, /) -> AlertDialog.Builder: ...
        def setNegativeButtonIcon(self, icon: android.graphics.drawable.Drawable, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setNeutralButton(self, textId: int | java.jint | java.lang.Integer, listener: android.content.DialogInterface.OnClickListener, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setNeutralButton(self, text: java.lang.CharSequence, listener: android.content.DialogInterface.OnClickListener, /) -> AlertDialog.Builder: ...
        def setNeutralButtonIcon(self, icon: android.graphics.drawable.Drawable, /) -> AlertDialog.Builder: ...
        def setOnCancelListener(self, onCancelListener: android.content.DialogInterface.OnCancelListener, /) -> AlertDialog.Builder: ...
        def setOnDismissListener(self, onDismissListener: android.content.DialogInterface.OnDismissListener, /) -> AlertDialog.Builder: ...
        def setOnItemSelectedListener(self, listener: android.widget.AdapterView.OnItemSelectedListener, /) -> AlertDialog.Builder: ...
        def setOnKeyListener(self, onKeyListener: android.content.DialogInterface.OnKeyListener, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setPositiveButton(self, textId: int | java.jint | java.lang.Integer, listener: android.content.DialogInterface.OnClickListener, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setPositiveButton(self, text: java.lang.CharSequence, listener: android.content.DialogInterface.OnClickListener, /) -> AlertDialog.Builder: ...
        def setPositiveButtonIcon(self, icon: android.graphics.drawable.Drawable, /) -> AlertDialog.Builder: ...
        def setRecycleOnMeasureEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setSingleChoiceItems(self, itemsId: int | java.jint | java.lang.Integer, checkedItem: int | java.jint | java.lang.Integer, listener: android.content.DialogInterface.OnClickListener, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setSingleChoiceItems(self, adapter: android.widget.ListAdapter, checkedItem: int | java.jint | java.lang.Integer, listener: android.content.DialogInterface.OnClickListener, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setSingleChoiceItems(self, items: java.chaquopy.JavaArray[java.lang.CharSequence], checkedItem: int | java.jint | java.lang.Integer, listener: android.content.DialogInterface.OnClickListener, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setSingleChoiceItems(self, cursor: android.database.Cursor, checkedItem: int | java.jint | java.lang.Integer, labelColumn: str | java.lang.String, listener: android.content.DialogInterface.OnClickListener, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setTitle(self, titleId: int | java.jint | java.lang.Integer, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setTitle(self, title: java.lang.CharSequence, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setView(self, layoutResId: int | java.jint | java.lang.Integer, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setView(self, view: android.view.View, /) -> AlertDialog.Builder: ...
        @typing.overload
        def setView(self, view: android.view.View, viewSpacingLeft: int | java.jint | java.lang.Integer, viewSpacingTop: int | java.jint | java.lang.Integer, viewSpacingRight: int | java.jint | java.lang.Integer, viewSpacingBottom: int | java.jint | java.lang.Integer, /) -> AlertDialog.Builder: ...
        def show(self) -> AlertDialog: ...

class AppCompatActivity(androidx.fragment.app.FragmentActivity, AppCompatCallback, androidx.core.app.TaskStackBuilder.SupportParentable, ActionBarDrawerToggle.DelegateProvider):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, contentLayoutId: int | java.jint | java.lang.Integer, /) -> None: ...
    def addContentView(self, view: android.view.View, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    def attachBaseContext(self, newBase: android.content.Context, /) -> None: ...
    def closeOptionsMenu(self) -> None: ...
    def dispatchKeyEvent(self, event: android.view.KeyEvent, /) -> bool: ...
    def findViewById(self, id: int | java.jint | java.lang.Integer, /) -> android.view.View: ...
    def getDelegate(self) -> AppCompatDelegate: ...
    def getDrawerToggleDelegate(self) -> ActionBarDrawerToggle.Delegate: ...
    def getMenuInflater(self) -> android.view.MenuInflater: ...
    def getResources(self) -> android.content.res.Resources: ...
    def getSupportActionBar(self) -> ActionBar: ...
    def getSupportParentActivityIntent(self) -> android.content.Intent: ...
    def invalidateOptionsMenu(self) -> None: ...
    def onConfigurationChanged(self, newConfig: android.content.res.Configuration, /) -> None: ...
    def onContentChanged(self) -> None: ...
    def onCreate(self, savedInstanceState: android.os.Bundle, /) -> None: ...
    def onCreateSupportNavigateUpTaskStack(self, builder: androidx.core.app.TaskStackBuilder, /) -> None: ...
    def onDestroy(self) -> None: ...
    def onKeyDown(self, keyCode: int | java.jint | java.lang.Integer, event: android.view.KeyEvent, /) -> bool: ...
    def onMenuItemSelected(self, featureId: int | java.jint | java.lang.Integer, item: android.view.MenuItem, /) -> bool: ...
    def onMenuOpened(self, featureId: int | java.jint | java.lang.Integer, menu: android.view.Menu, /) -> bool: ...
    def onNightModeChanged(self, mode: int | java.jint | java.lang.Integer, /) -> None: ...
    def onPanelClosed(self, featureId: int | java.jint | java.lang.Integer, menu: android.view.Menu, /) -> None: ...
    def onPostCreate(self, savedInstanceState: android.os.Bundle, /) -> None: ...
    def onPostResume(self) -> None: ...
    def onPrepareSupportNavigateUpTaskStack(self, builder: androidx.core.app.TaskStackBuilder, /) -> None: ...
    def onSaveInstanceState(self, outState: android.os.Bundle, /) -> None: ...
    def onStart(self) -> None: ...
    def onStop(self) -> None: ...
    def onSupportActionModeFinished(self, mode: androidx.appcompat.view.ActionMode, /) -> None: ...
    def onSupportActionModeStarted(self, mode: androidx.appcompat.view.ActionMode, /) -> None: ...
    def onSupportContentChanged(self) -> None: ...
    def onSupportNavigateUp(self) -> bool: ...
    def onTitleChanged(self, title: java.lang.CharSequence, color: int | java.jint | java.lang.Integer, /) -> None: ...
    def onWindowStartingSupportActionMode(self, callback: androidx.appcompat.view.ActionMode.Callback, /) -> androidx.appcompat.view.ActionMode: ...
    def openOptionsMenu(self) -> None: ...
    @typing.overload
    def setContentView(self, layoutResID: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setContentView(self, view: android.view.View, /) -> None: ...
    @typing.overload
    def setContentView(self, view: android.view.View, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    def setSupportActionBar(self, toolbar: androidx.appcompat.widget.Toolbar, /) -> None: ...
    def setSupportProgress(self, progress: int | java.jint | java.lang.Integer, /) -> None: ...
    def setSupportProgressBarIndeterminate(self, indeterminate: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setSupportProgressBarIndeterminateVisibility(self, visible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setSupportProgressBarVisibility(self, visible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setTheme(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    def startSupportActionMode(self, callback: androidx.appcompat.view.ActionMode.Callback, /) -> androidx.appcompat.view.ActionMode: ...
    def supportInvalidateOptionsMenu(self) -> None: ...
    def supportNavigateUpTo(self, upIntent: android.content.Intent, /) -> None: ...
    def supportRequestWindowFeature(self, featureId: int | java.jint | java.lang.Integer, /) -> bool: ...
    def supportShouldUpRecreateTask(self, targetIntent: android.content.Intent, /) -> bool: ...

class AppCompatCallback(java.lang.Object):
    def onSupportActionModeFinished(self, arg1: androidx.appcompat.view.ActionMode, /) -> None: ...
    def onSupportActionModeStarted(self, arg1: androidx.appcompat.view.ActionMode, /) -> None: ...
    def onWindowStartingSupportActionMode(self, arg1: androidx.appcompat.view.ActionMode.Callback, /) -> androidx.appcompat.view.ActionMode: ...

class AppCompatDelegate(java.lang.Object):
    MODE_NIGHT_FOLLOW_SYSTEM: typing.ClassVar[int] = ...
    MODE_NIGHT_AUTO_TIME: typing.ClassVar[int] = ...
    MODE_NIGHT_AUTO: typing.ClassVar[int] = ...
    MODE_NIGHT_NO: typing.ClassVar[int] = ...
    MODE_NIGHT_YES: typing.ClassVar[int] = ...
    MODE_NIGHT_AUTO_BATTERY: typing.ClassVar[int] = ...
    MODE_NIGHT_UNSPECIFIED: typing.ClassVar[int] = ...
    FEATURE_SUPPORT_ACTION_BAR: typing.ClassVar[int] = ...
    FEATURE_SUPPORT_ACTION_BAR_OVERLAY: typing.ClassVar[int] = ...
    FEATURE_ACTION_MODE_OVERLAY: typing.ClassVar[int] = ...
    def addContentView(self, arg1: android.view.View, arg2: android.view.ViewGroup.LayoutParams, /) -> None: ...
    def applyDayNight(self) -> bool: ...
    def attachBaseContext(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    @staticmethod
    def create(activity: android.app.Activity, callback: AppCompatCallback, /) -> AppCompatDelegate: ...
    @typing.overload
    @staticmethod
    def create(dialog: android.app.Dialog, callback: AppCompatCallback, /) -> AppCompatDelegate: ...
    @typing.overload
    @staticmethod
    def create(context: android.content.Context, activity: android.app.Activity, callback: AppCompatCallback, /) -> AppCompatDelegate: ...
    @typing.overload
    @staticmethod
    def create(context: android.content.Context, window: android.view.Window, callback: AppCompatCallback, /) -> AppCompatDelegate: ...
    def createView(self, arg1: android.view.View, arg2: str | java.lang.String, arg3: android.content.Context, arg4: android.util.AttributeSet, /) -> android.view.View: ...
    def findViewById(self, arg1: int | java.jint | java.lang.Integer, /) -> android.view.View: ...
    @staticmethod
    def getDefaultNightMode() -> int: ...
    def getDrawerToggleDelegate(self) -> ActionBarDrawerToggle.Delegate: ...
    def getLocalNightMode(self) -> int: ...
    def getMenuInflater(self) -> android.view.MenuInflater: ...
    def getSupportActionBar(self) -> ActionBar: ...
    def hasWindowFeature(self, arg1: int | java.jint | java.lang.Integer, /) -> bool: ...
    def installViewFactory(self) -> None: ...
    def invalidateOptionsMenu(self) -> None: ...
    @staticmethod
    def isCompatVectorFromResourcesEnabled() -> bool: ...
    def isHandleNativeActionModesEnabled(self) -> bool: ...
    def onConfigurationChanged(self, arg1: android.content.res.Configuration, /) -> None: ...
    def onCreate(self, arg1: android.os.Bundle, /) -> None: ...
    def onDestroy(self) -> None: ...
    def onPostCreate(self, arg1: android.os.Bundle, /) -> None: ...
    def onPostResume(self) -> None: ...
    def onSaveInstanceState(self, arg1: android.os.Bundle, /) -> None: ...
    def onStart(self) -> None: ...
    def onStop(self) -> None: ...
    def requestWindowFeature(self, arg1: int | java.jint | java.lang.Integer, /) -> bool: ...
    @staticmethod
    def setCompatVectorFromResourcesEnabled(enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def setContentView(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setContentView(self, arg1: android.view.View, /) -> None: ...
    @typing.overload
    def setContentView(self, arg1: android.view.View, arg2: android.view.ViewGroup.LayoutParams, /) -> None: ...
    @staticmethod
    def setDefaultNightMode(mode: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHandleNativeActionModesEnabled(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setLocalNightMode(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
    def setSupportActionBar(self, arg1: androidx.appcompat.widget.Toolbar, /) -> None: ...
    def setTheme(self, themeResId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTitle(self, arg1: java.lang.CharSequence, /) -> None: ...
    def startSupportActionMode(self, arg1: androidx.appcompat.view.ActionMode.Callback, /) -> androidx.appcompat.view.ActionMode: ...

    class NightMode(java.lang.annotation.Annotation): ...

class AppCompatDelegateImpl(AppCompatDelegate, androidx.appcompat.view.menu.MenuBuilder.Callback, android.view.LayoutInflater.Factory2):
    def addContentView(self, v: android.view.View, lp: android.view.ViewGroup.LayoutParams, /) -> None: ...
    def applyDayNight(self) -> bool: ...
    def attachBaseContext(self, context: android.content.Context, /) -> None: ...
    def createView(self, parent: android.view.View, name: str | java.lang.String, context: android.content.Context, attrs: android.util.AttributeSet, /) -> android.view.View: ...
    def findViewById(self, id: int | java.jint | java.lang.Integer, /) -> android.view.View: ...
    def getDrawerToggleDelegate(self) -> ActionBarDrawerToggle.Delegate: ...
    def getLocalNightMode(self) -> int: ...
    def getMenuInflater(self) -> android.view.MenuInflater: ...
    def getPanelState(self, featureId: int | java.jint | java.lang.Integer, required: bool | java.jboolean | java.lang.Boolean, /) -> AppCompatDelegateImpl.PanelFeatureState: ...
    def getSupportActionBar(self) -> ActionBar: ...
    def hasWindowFeature(self, featureId: int | java.jint | java.lang.Integer, /) -> bool: ...
    def installViewFactory(self) -> None: ...
    def invalidateOptionsMenu(self) -> None: ...
    def isHandleNativeActionModesEnabled(self) -> bool: ...
    def onConfigurationChanged(self, newConfig: android.content.res.Configuration, /) -> None: ...
    def onCreate(self, savedInstanceState: android.os.Bundle, /) -> None: ...
    @typing.overload
    def onCreateView(self, name: str | java.lang.String, context: android.content.Context, attrs: android.util.AttributeSet, /) -> android.view.View: ...
    @typing.overload
    def onCreateView(self, parent: android.view.View, name: str | java.lang.String, context: android.content.Context, attrs: android.util.AttributeSet, /) -> android.view.View: ...
    def onDestroy(self) -> None: ...
    def onMenuItemSelected(self, menu: androidx.appcompat.view.menu.MenuBuilder, item: android.view.MenuItem, /) -> bool: ...
    def onMenuModeChange(self, menu: androidx.appcompat.view.menu.MenuBuilder, /) -> None: ...
    def onPostCreate(self, savedInstanceState: android.os.Bundle, /) -> None: ...
    def onPostResume(self) -> None: ...
    def onSaveInstanceState(self, outState: android.os.Bundle, /) -> None: ...
    def onStart(self) -> None: ...
    def onStop(self) -> None: ...
    def requestWindowFeature(self, featureId: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def setContentView(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setContentView(self, v: android.view.View, /) -> None: ...
    @typing.overload
    def setContentView(self, v: android.view.View, lp: android.view.ViewGroup.LayoutParams, /) -> None: ...
    def setHandleNativeActionModesEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setLocalNightMode(self, mode: int | java.jint | java.lang.Integer, /) -> None: ...
    def setSupportActionBar(self, toolbar: androidx.appcompat.widget.Toolbar, /) -> None: ...
    def setTheme(self, themeResId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTitle(self, title: java.lang.CharSequence, /) -> None: ...
    def startSupportActionMode(self, callback: androidx.appcompat.view.ActionMode.Callback, /) -> androidx.appcompat.view.ActionMode: ...

    class PanelFeatureState(java.lang.Object):
        qwertyMode: bool = ...
        def clearMenuPresenters(self) -> None: ...
        def hasPanelItems(self) -> bool: ...

class AppCompatDialog(android.app.Dialog, AppCompatCallback):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, theme: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, cancelable: bool | java.jboolean | java.lang.Boolean, cancelListener: android.content.DialogInterface.OnCancelListener, /) -> None: ...
    def addContentView(self, view: android.view.View, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    def dispatchKeyEvent(self, event: android.view.KeyEvent, /) -> bool: ...
    def findViewById(self, id: int | java.jint | java.lang.Integer, /) -> android.view.View: ...
    def getDelegate(self) -> AppCompatDelegate: ...
    def getSupportActionBar(self) -> ActionBar: ...
    def invalidateOptionsMenu(self) -> None: ...
    def onCreate(self, savedInstanceState: android.os.Bundle, /) -> None: ...
    def onStop(self) -> None: ...
    def onSupportActionModeFinished(self, mode: androidx.appcompat.view.ActionMode, /) -> None: ...
    def onSupportActionModeStarted(self, mode: androidx.appcompat.view.ActionMode, /) -> None: ...
    def onWindowStartingSupportActionMode(self, callback: androidx.appcompat.view.ActionMode.Callback, /) -> androidx.appcompat.view.ActionMode: ...
    @typing.overload
    def setContentView(self, layoutResID: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setContentView(self, view: android.view.View, /) -> None: ...
    @typing.overload
    def setContentView(self, view: android.view.View, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    @typing.overload
    def setTitle(self, titleId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setTitle(self, title: java.lang.CharSequence, /) -> None: ...
    def supportRequestWindowFeature(self, featureId: int | java.jint | java.lang.Integer, /) -> bool: ...

class AppCompatDialogFragment(androidx.fragment.app.DialogFragment):
    def __init__(self) -> None: ...
    def onCreateDialog(self, savedInstanceState: android.os.Bundle, /) -> android.app.Dialog: ...
    def setupDialog(self, dialog: android.app.Dialog, style: int | java.jint | java.lang.Integer, /) -> None: ...

class AppCompatViewInflater(java.lang.Object):
    def __init__(self) -> None: ...
    def createAutoCompleteTextView(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> androidx.appcompat.widget.AppCompatAutoCompleteTextView: ...
    def createButton(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> androidx.appcompat.widget.AppCompatButton: ...
    def createCheckBox(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> androidx.appcompat.widget.AppCompatCheckBox: ...
    def createCheckedTextView(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> androidx.appcompat.widget.AppCompatCheckedTextView: ...
    def createEditText(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> androidx.appcompat.widget.AppCompatEditText: ...
    def createImageButton(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> androidx.appcompat.widget.AppCompatImageButton: ...
    def createImageView(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> androidx.appcompat.widget.AppCompatImageView: ...
    def createMultiAutoCompleteTextView(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> androidx.appcompat.widget.AppCompatMultiAutoCompleteTextView: ...
    def createRadioButton(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> androidx.appcompat.widget.AppCompatRadioButton: ...
    def createRatingBar(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> androidx.appcompat.widget.AppCompatRatingBar: ...
    def createSeekBar(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> androidx.appcompat.widget.AppCompatSeekBar: ...
    def createSpinner(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> androidx.appcompat.widget.AppCompatSpinner: ...
    def createTextView(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> androidx.appcompat.widget.AppCompatTextView: ...
    def createToggleButton(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> androidx.appcompat.widget.AppCompatToggleButton: ...
    def createView(self, context: android.content.Context, name: str | java.lang.String, attrs: android.util.AttributeSet, /) -> android.view.View: ...

class NavItemSelectedListener(android.widget.AdapterView.OnItemSelectedListener):
    def __init__(self, listener: ActionBar.OnNavigationListener, /) -> None: ...
    def onItemSelected(self, parent: android.widget.AdapterView[java.lang.Object], view: android.view.View, position: int | java.jint | java.lang.Integer, id: int | java.jlong | java.lang.Long, /) -> None: ...
    def onNothingSelected(self, parent: android.widget.AdapterView[java.lang.Object], /) -> None: ...

class ResourcesFlusher(java.lang.Object): ...

class ToolbarActionBar(ActionBar):
    def addOnMenuVisibilityListener(self, listener: ActionBar.OnMenuVisibilityListener, /) -> None: ...
    @typing.overload
    def addTab(self, tab: ActionBar.Tab, /) -> None: ...
    @typing.overload
    def addTab(self, tab: ActionBar.Tab, position: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def addTab(self, tab: ActionBar.Tab, setSelected: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def addTab(self, tab: ActionBar.Tab, position: int | java.jint | java.lang.Integer, setSelected: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def closeOptionsMenu(self) -> bool: ...
    def collapseActionView(self) -> bool: ...
    def dispatchMenuVisibilityChanged(self, isVisible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def getCustomView(self) -> android.view.View: ...
    def getDisplayOptions(self) -> int: ...
    def getElevation(self) -> float: ...
    def getHeight(self) -> int: ...
    def getNavigationItemCount(self) -> int: ...
    def getNavigationMode(self) -> int: ...
    def getSelectedNavigationIndex(self) -> int: ...
    def getSelectedTab(self) -> ActionBar.Tab: ...
    def getSubtitle(self) -> java.lang.CharSequence: ...
    def getTabAt(self, index: int | java.jint | java.lang.Integer, /) -> ActionBar.Tab: ...
    def getTabCount(self) -> int: ...
    def getThemedContext(self) -> android.content.Context: ...
    def getTitle(self) -> java.lang.CharSequence: ...
    def getWrappedWindowCallback(self) -> android.view.Window.Callback: ...
    def hide(self) -> None: ...
    def invalidateOptionsMenu(self) -> bool: ...
    def isShowing(self) -> bool: ...
    def isTitleTruncated(self) -> bool: ...
    def newTab(self) -> ActionBar.Tab: ...
    def onConfigurationChanged(self, config: android.content.res.Configuration, /) -> None: ...
    def onKeyShortcut(self, keyCode: int | java.jint | java.lang.Integer, ev: android.view.KeyEvent, /) -> bool: ...
    def onMenuKeyEvent(self, event: android.view.KeyEvent, /) -> bool: ...
    def openOptionsMenu(self) -> bool: ...
    def removeAllTabs(self) -> None: ...
    def removeOnMenuVisibilityListener(self, listener: ActionBar.OnMenuVisibilityListener, /) -> None: ...
    def removeTab(self, tab: ActionBar.Tab, /) -> None: ...
    def removeTabAt(self, position: int | java.jint | java.lang.Integer, /) -> None: ...
    def requestFocus(self) -> bool: ...
    def selectTab(self, tab: ActionBar.Tab, /) -> None: ...
    def setBackgroundDrawable(self, d: android.graphics.drawable.Drawable, /) -> None: ...
    @typing.overload
    def setCustomView(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCustomView(self, view: android.view.View, /) -> None: ...
    @typing.overload
    def setCustomView(self, view: android.view.View, layoutParams: ActionBar.LayoutParams, /) -> None: ...
    def setDefaultDisplayHomeAsUpEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDisplayHomeAsUpEnabled(self, showHomeAsUp: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def setDisplayOptions(self, options: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setDisplayOptions(self, options: int | java.jint | java.lang.Integer, mask: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDisplayShowCustomEnabled(self, showCustom: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDisplayShowHomeEnabled(self, showHome: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDisplayShowTitleEnabled(self, showTitle: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDisplayUseLogoEnabled(self, useLogo: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setElevation(self, elevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def setHomeActionContentDescription(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setHomeActionContentDescription(self, description: java.lang.CharSequence, /) -> None: ...
    @typing.overload
    def setHomeAsUpIndicator(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setHomeAsUpIndicator(self, indicator: android.graphics.drawable.Drawable, /) -> None: ...
    def setHomeButtonEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def setIcon(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setIcon(self, icon: android.graphics.drawable.Drawable, /) -> None: ...
    def setListNavigationCallbacks(self, adapter: android.widget.SpinnerAdapter, callback: ActionBar.OnNavigationListener, /) -> None: ...
    @typing.overload
    def setLogo(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setLogo(self, logo: android.graphics.drawable.Drawable, /) -> None: ...
    def setNavigationMode(self, mode: int | java.jint | java.lang.Integer, /) -> None: ...
    def setSelectedNavigationItem(self, position: int | java.jint | java.lang.Integer, /) -> None: ...
    def setShowHideAnimationEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setSplitBackgroundDrawable(self, d: android.graphics.drawable.Drawable, /) -> None: ...
    def setStackedBackgroundDrawable(self, d: android.graphics.drawable.Drawable, /) -> None: ...
    @typing.overload
    def setSubtitle(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setSubtitle(self, subtitle: java.lang.CharSequence, /) -> None: ...
    @typing.overload
    def setTitle(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setTitle(self, title: java.lang.CharSequence, /) -> None: ...
    def setWindowTitle(self, title: java.lang.CharSequence, /) -> None: ...
    def show(self) -> None: ...

class TwilightCalculator(java.lang.Object):
    DAY: typing.ClassVar[int] = ...
    NIGHT: typing.ClassVar[int] = ...
    sunset: int = ...
    sunrise: int = ...
    state: int = ...
    def calculateTwilight(self, time: int | java.jlong | java.lang.Long, latitude: float | java.jdouble | java.lang.Double, longitude: float | java.jdouble | java.lang.Double, /) -> None: ...

class TwilightManager(java.lang.Object): ...

class WindowDecorActionBar(ActionBar, androidx.appcompat.widget.ActionBarOverlayLayout.ActionBarVisibilityCallback):
    @typing.overload
    def __init__(self, dialog: android.app.Dialog, /) -> None: ...
    @typing.overload
    def __init__(self, layout: android.view.View, /) -> None: ...
    @typing.overload
    def __init__(self, activity: android.app.Activity, overlayMode: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def addOnMenuVisibilityListener(self, listener: ActionBar.OnMenuVisibilityListener, /) -> None: ...
    @typing.overload
    def addTab(self, tab: ActionBar.Tab, /) -> None: ...
    @typing.overload
    def addTab(self, tab: ActionBar.Tab, position: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def addTab(self, tab: ActionBar.Tab, setSelected: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def addTab(self, tab: ActionBar.Tab, position: int | java.jint | java.lang.Integer, setSelected: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def animateToMode(self, toActionMode: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def collapseActionView(self) -> bool: ...
    def dispatchMenuVisibilityChanged(self, isVisible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def doHide(self, fromSystem: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def doShow(self, fromSystem: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def enableContentAnimations(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def getCustomView(self) -> android.view.View: ...
    def getDisplayOptions(self) -> int: ...
    def getElevation(self) -> float: ...
    def getHeight(self) -> int: ...
    def getHideOffset(self) -> int: ...
    def getNavigationItemCount(self) -> int: ...
    def getNavigationMode(self) -> int: ...
    def getSelectedNavigationIndex(self) -> int: ...
    def getSelectedTab(self) -> ActionBar.Tab: ...
    def getSubtitle(self) -> java.lang.CharSequence: ...
    def getTabAt(self, index: int | java.jint | java.lang.Integer, /) -> ActionBar.Tab: ...
    def getTabCount(self) -> int: ...
    def getThemedContext(self) -> android.content.Context: ...
    def getTitle(self) -> java.lang.CharSequence: ...
    def hasIcon(self) -> bool: ...
    def hasLogo(self) -> bool: ...
    def hide(self) -> None: ...
    def hideForSystem(self) -> None: ...
    def isHideOnContentScrollEnabled(self) -> bool: ...
    def isShowing(self) -> bool: ...
    def isTitleTruncated(self) -> bool: ...
    def newTab(self) -> ActionBar.Tab: ...
    def onConfigurationChanged(self, newConfig: android.content.res.Configuration, /) -> None: ...
    def onContentScrollStarted(self) -> None: ...
    def onContentScrollStopped(self) -> None: ...
    def onKeyShortcut(self, keyCode: int | java.jint | java.lang.Integer, event: android.view.KeyEvent, /) -> bool: ...
    def onWindowVisibilityChanged(self, visibility: int | java.jint | java.lang.Integer, /) -> None: ...
    def removeAllTabs(self) -> None: ...
    def removeOnMenuVisibilityListener(self, listener: ActionBar.OnMenuVisibilityListener, /) -> None: ...
    def removeTab(self, tab: ActionBar.Tab, /) -> None: ...
    def removeTabAt(self, position: int | java.jint | java.lang.Integer, /) -> None: ...
    def requestFocus(self) -> bool: ...
    def selectTab(self, tab: ActionBar.Tab, /) -> None: ...
    def setBackgroundDrawable(self, d: android.graphics.drawable.Drawable, /) -> None: ...
    @typing.overload
    def setCustomView(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCustomView(self, view: android.view.View, /) -> None: ...
    @typing.overload
    def setCustomView(self, view: android.view.View, layoutParams: ActionBar.LayoutParams, /) -> None: ...
    def setDefaultDisplayHomeAsUpEnabled(self, enable: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDisplayHomeAsUpEnabled(self, showHomeAsUp: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def setDisplayOptions(self, options: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setDisplayOptions(self, options: int | java.jint | java.lang.Integer, mask: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDisplayShowCustomEnabled(self, showCustom: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDisplayShowHomeEnabled(self, showHome: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDisplayShowTitleEnabled(self, showTitle: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setDisplayUseLogoEnabled(self, useLogo: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setElevation(self, elevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setHideOffset(self, offset: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHideOnContentScrollEnabled(self, hideOnContentScroll: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def setHomeActionContentDescription(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setHomeActionContentDescription(self, description: java.lang.CharSequence, /) -> None: ...
    @typing.overload
    def setHomeAsUpIndicator(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setHomeAsUpIndicator(self, indicator: android.graphics.drawable.Drawable, /) -> None: ...
    def setHomeButtonEnabled(self, enable: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def setIcon(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setIcon(self, icon: android.graphics.drawable.Drawable, /) -> None: ...
    def setListNavigationCallbacks(self, adapter: android.widget.SpinnerAdapter, callback: ActionBar.OnNavigationListener, /) -> None: ...
    @typing.overload
    def setLogo(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setLogo(self, logo: android.graphics.drawable.Drawable, /) -> None: ...
    def setNavigationMode(self, mode: int | java.jint | java.lang.Integer, /) -> None: ...
    def setSelectedNavigationItem(self, position: int | java.jint | java.lang.Integer, /) -> None: ...
    def setShowHideAnimationEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setSplitBackgroundDrawable(self, d: android.graphics.drawable.Drawable, /) -> None: ...
    def setStackedBackgroundDrawable(self, d: android.graphics.drawable.Drawable, /) -> None: ...
    @typing.overload
    def setSubtitle(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setSubtitle(self, subtitle: java.lang.CharSequence, /) -> None: ...
    @typing.overload
    def setTitle(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setTitle(self, title: java.lang.CharSequence, /) -> None: ...
    def setWindowTitle(self, title: java.lang.CharSequence, /) -> None: ...
    def show(self) -> None: ...
    def showForSystem(self) -> None: ...
    def startActionMode(self, callback: androidx.appcompat.view.ActionMode.Callback, /) -> androidx.appcompat.view.ActionMode: ...

    class TabImpl(ActionBar.Tab):
        def __init__(self, this_0: WindowDecorActionBar, /) -> None: ...
        def getCallback(self) -> ActionBar.TabListener: ...
        def getContentDescription(self) -> java.lang.CharSequence: ...
        def getCustomView(self) -> android.view.View: ...
        def getIcon(self) -> android.graphics.drawable.Drawable: ...
        def getPosition(self) -> int: ...
        def getTag(self) -> java.lang.Object: ...
        def getText(self) -> java.lang.CharSequence: ...
        def select(self) -> None: ...
        @typing.overload
        def setContentDescription(self, resId: int | java.jint | java.lang.Integer, /) -> ActionBar.Tab: ...
        @typing.overload
        def setContentDescription(self, contentDesc: java.lang.CharSequence, /) -> ActionBar.Tab: ...
        @typing.overload
        def setCustomView(self, layoutResId: int | java.jint | java.lang.Integer, /) -> ActionBar.Tab: ...
        @typing.overload
        def setCustomView(self, view: android.view.View, /) -> ActionBar.Tab: ...
        @typing.overload
        def setIcon(self, resId: int | java.jint | java.lang.Integer, /) -> ActionBar.Tab: ...
        @typing.overload
        def setIcon(self, icon: android.graphics.drawable.Drawable, /) -> ActionBar.Tab: ...
        def setPosition(self, position: int | java.jint | java.lang.Integer, /) -> None: ...
        def setTabListener(self, callback: ActionBar.TabListener, /) -> ActionBar.Tab: ...
        def setTag(self, tag: java.lang.Object | int | bool | float | str, /) -> ActionBar.Tab: ...
        @typing.overload
        def setText(self, resId: int | java.jint | java.lang.Integer, /) -> ActionBar.Tab: ...
        @typing.overload
        def setText(self, text: java.lang.CharSequence, /) -> ActionBar.Tab: ...

    class ActionModeImpl(androidx.appcompat.view.ActionMode, androidx.appcompat.view.menu.MenuBuilder.Callback):
        def __init__(self, this_0: WindowDecorActionBar, context: android.content.Context, callback: androidx.appcompat.view.ActionMode.Callback, /) -> None: ...
        def dispatchOnCreate(self) -> bool: ...
        def finish(self) -> None: ...
        def getCustomView(self) -> android.view.View: ...
        def getMenu(self) -> android.view.Menu: ...
        def getMenuInflater(self) -> android.view.MenuInflater: ...
        def getSubtitle(self) -> java.lang.CharSequence: ...
        def getTitle(self) -> java.lang.CharSequence: ...
        def invalidate(self) -> None: ...
        def isTitleOptional(self) -> bool: ...
        def onCloseMenu(self, menu: androidx.appcompat.view.menu.MenuBuilder, allMenusAreClosing: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
        def onCloseSubMenu(self, menu: androidx.appcompat.view.menu.SubMenuBuilder, /) -> None: ...
        def onMenuItemSelected(self, menu: androidx.appcompat.view.menu.MenuBuilder, item: android.view.MenuItem, /) -> bool: ...
        def onMenuModeChange(self, menu: androidx.appcompat.view.menu.MenuBuilder, /) -> None: ...
        def onSubMenuSelected(self, subMenu: androidx.appcompat.view.menu.SubMenuBuilder, /) -> bool: ...
        def setCustomView(self, view: android.view.View, /) -> None: ...
        @typing.overload
        def setSubtitle(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
        @typing.overload
        def setSubtitle(self, subtitle: java.lang.CharSequence, /) -> None: ...
        @typing.overload
        def setTitle(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
        @typing.overload
        def setTitle(self, title: java.lang.CharSequence, /) -> None: ...
        def setTitleOptionalHint(self, titleOptional: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
