import typing

import android.content
import android.graphics
import android.util
import android.view
import android.view.accessibility
import android.widget
import androidx.recyclerview.widget
import com.google.android.material.shape
import java
import java.lang

class Carousel(java.lang.Object):
    def getContainerWidth(self) -> int: ...

class CarouselLayoutManager(androidx.recyclerview.widget.RecyclerView.LayoutManager, Carousel):
    def __init__(self) -> None: ...
    def canScrollHorizontally(self) -> bool: ...
    def computeHorizontalScrollExtent(self, state: androidx.recyclerview.widget.RecyclerView.State, /) -> int: ...
    def computeHorizontalScrollOffset(self, state: androidx.recyclerview.widget.RecyclerView.State, /) -> int: ...
    def computeHorizontalScrollRange(self, state: androidx.recyclerview.widget.RecyclerView.State, /) -> int: ...
    def generateDefaultLayoutParams(self) -> androidx.recyclerview.widget.RecyclerView.LayoutParams: ...
    def getContainerWidth(self) -> int: ...
    def getDecoratedBoundsWithMargins(self, view: android.view.View, outBounds: android.graphics.Rect, /) -> None: ...
    def measureChildWithMargins(self, child: android.view.View, widthUsed: int | java.jint | java.lang.Integer, heightUsed: int | java.jint | java.lang.Integer, /) -> None: ...
    def onInitializeAccessibilityEvent(self, event: android.view.accessibility.AccessibilityEvent, /) -> None: ...
    def onLayoutChildren(self, recycler: androidx.recyclerview.widget.RecyclerView.Recycler, state: androidx.recyclerview.widget.RecyclerView.State, /) -> None: ...
    def onLayoutCompleted(self, state: androidx.recyclerview.widget.RecyclerView.State, /) -> None: ...
    def requestChildRectangleOnScreen(self, parent: androidx.recyclerview.widget.RecyclerView, child: android.view.View, rect: android.graphics.Rect, immediate: bool | java.jboolean | java.lang.Boolean, focusedChildVisible: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def scrollHorizontallyBy(self, dx: int | java.jint | java.lang.Integer, recycler: androidx.recyclerview.widget.RecyclerView.Recycler, state: androidx.recyclerview.widget.RecyclerView.State, /) -> int: ...
    def scrollToPosition(self, position: int | java.jint | java.lang.Integer, /) -> None: ...
    def setCarouselStrategy(self, carouselStrategy: CarouselStrategy, /) -> None: ...
    def setDebuggingEnabled(self, recyclerView: androidx.recyclerview.widget.RecyclerView, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def smoothScrollToPosition(self, recyclerView: androidx.recyclerview.widget.RecyclerView, state: androidx.recyclerview.widget.RecyclerView.State, position: int | java.jint | java.lang.Integer, /) -> None: ...

class CarouselStrategy(java.lang.Object):
    def __init__(self) -> None: ...

class KeylineState(java.lang.Object): ...

class KeylineStateList(java.lang.Object):
    def getShiftedState(self, scrollOffset: float | java.jfloat | java.lang.Float, minScrollOffset: float | java.jfloat | java.lang.Float, maxScrollOffset: float | java.jfloat | java.lang.Float, /) -> KeylineState: ...

class Maskable(java.lang.Object):
    def getMaskRectF(self) -> android.graphics.RectF: ...
    def getMaskXPercentage(self) -> float: ...
    def setMaskXPercentage(self, arg1: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setOnMaskChangedListener(self, arg1: OnMaskChangedListener, /) -> None: ...

class MaskableFrameLayout(android.widget.FrameLayout, Maskable, com.google.android.material.shape.Shapeable):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def dispatchDraw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getMaskRectF(self) -> android.graphics.RectF: ...
    def getMaskXPercentage(self) -> float: ...
    def getShapeAppearanceModel(self) -> com.google.android.material.shape.ShapeAppearanceModel: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onSizeChanged(self, w: int | java.jint | java.lang.Integer, h: int | java.jint | java.lang.Integer, oldw: int | java.jint | java.lang.Integer, oldh: int | java.jint | java.lang.Integer, /) -> None: ...
    def onTouchEvent(self, event: android.view.MotionEvent, /) -> bool: ...
    def setForceCompatClipping(self, forceCompatClipping: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setMaskXPercentage(self, percentage: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setOnMaskChangedListener(self, onMaskChangedListener: OnMaskChangedListener, /) -> None: ...
    def setShapeAppearanceModel(self, shapeAppearanceModel: com.google.android.material.shape.ShapeAppearanceModel, /) -> None: ...

class MultiBrowseCarouselStrategy(CarouselStrategy):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, forceCompactArrangement: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class OnMaskChangedListener(java.lang.Object):
    def onMaskChanged(self, arg1: android.graphics.RectF, /) -> None: ...
