import typing

import android.app
import android.content
import android.content.res
import android.os
import android.view
import android.window
import androidx.activity.contextaware
import androidx.activity.result
import androidx.activity.result.contract
import androidx.core.app
import androidx.core.content
import androidx.core.util
import androidx.core.view
import androidx.lifecycle
import androidx.lifecycle.viewmodel
import androidx.savedstate
import java
import java.chaquopy
import java.lang

class Cancellable(java.lang.Object):
    def cancel(self) -> None: ...

class ComponentActivity(androidx.core.app.ComponentActivity, androidx.activity.contextaware.ContextAware, androidx.lifecycle.LifecycleOwner, androidx.lifecycle.ViewModelStoreOwner, androidx.lifecycle.HasDefaultViewModelProviderFactory, androidx.savedstate.SavedStateRegistryOwner, OnBackPressedDispatcherOwner, androidx.activity.result.ActivityResultRegistryOwner, androidx.activity.result.ActivityResultCaller, androidx.core.content.OnConfigurationChangedProvider, androidx.core.content.OnTrimMemoryProvider, androidx.core.app.OnNewIntentProvider, androidx.core.app.OnMultiWindowModeChangedProvider, androidx.core.app.OnPictureInPictureModeChangedProvider, androidx.core.view.MenuHost):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, contentLayoutId: int | java.jint | java.lang.Integer, /) -> None: ...
    def addContentView(self, view: android.view.View, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    @typing.overload
    def addMenuProvider(self, provider: androidx.core.view.MenuProvider, /) -> None: ...
    @typing.overload
    def addMenuProvider(self, provider: androidx.core.view.MenuProvider, owner: androidx.lifecycle.LifecycleOwner, /) -> None: ...
    @typing.overload
    def addMenuProvider(self, provider: androidx.core.view.MenuProvider, owner: androidx.lifecycle.LifecycleOwner, state: androidx.lifecycle.Lifecycle.State, /) -> None: ...
    def addOnConfigurationChangedListener(self, listener: androidx.core.util.Consumer[android.content.res.Configuration], /) -> None: ...
    def addOnContextAvailableListener(self, listener: androidx.activity.contextaware.OnContextAvailableListener, /) -> None: ...
    def addOnMultiWindowModeChangedListener(self, listener: androidx.core.util.Consumer[androidx.core.app.MultiWindowModeChangedInfo], /) -> None: ...
    def addOnNewIntentListener(self, listener: androidx.core.util.Consumer[android.content.Intent], /) -> None: ...
    def addOnPictureInPictureModeChangedListener(self, listener: androidx.core.util.Consumer[androidx.core.app.PictureInPictureModeChangedInfo], /) -> None: ...
    def addOnTrimMemoryListener(self, listener: androidx.core.util.Consumer[java.lang.Integer], /) -> None: ...
    def getActivityResultRegistry(self) -> androidx.activity.result.ActivityResultRegistry: ...
    def getDefaultViewModelCreationExtras(self) -> androidx.lifecycle.viewmodel.CreationExtras: ...
    def getDefaultViewModelProviderFactory(self) -> androidx.lifecycle.ViewModelProvider.Factory: ...
    def getLastCustomNonConfigurationInstance(self) -> java.lang.Object: ...
    def getLifecycle(self) -> androidx.lifecycle.Lifecycle: ...
    def getOnBackPressedDispatcher(self) -> OnBackPressedDispatcher: ...
    def getSavedStateRegistry(self) -> androidx.savedstate.SavedStateRegistry: ...
    def getViewModelStore(self) -> androidx.lifecycle.ViewModelStore: ...
    def invalidateMenu(self) -> None: ...
    def onActivityResult(self, requestCode: int | java.jint | java.lang.Integer, resultCode: int | java.jint | java.lang.Integer, data: android.content.Intent, /) -> None: ...
    def onBackPressed(self) -> None: ...
    def onConfigurationChanged(self, newConfig: android.content.res.Configuration, /) -> None: ...
    def onCreate(self, savedInstanceState: android.os.Bundle, /) -> None: ...
    def onCreatePanelMenu(self, featureId: int | java.jint | java.lang.Integer, menu: android.view.Menu, /) -> bool: ...
    def onMenuItemSelected(self, featureId: int | java.jint | java.lang.Integer, item: android.view.MenuItem, /) -> bool: ...
    @typing.overload
    def onMultiWindowModeChanged(self, isInMultiWindowMode: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def onMultiWindowModeChanged(self, isInMultiWindowMode: bool | java.jboolean | java.lang.Boolean, newConfig: android.content.res.Configuration, /) -> None: ...
    def onNewIntent(self, intent: android.content.Intent, /) -> None: ...
    def onPanelClosed(self, featureId: int | java.jint | java.lang.Integer, menu: android.view.Menu, /) -> None: ...
    @typing.overload
    def onPictureInPictureModeChanged(self, isInPictureInPictureMode: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def onPictureInPictureModeChanged(self, isInPictureInPictureMode: bool | java.jboolean | java.lang.Boolean, newConfig: android.content.res.Configuration, /) -> None: ...
    def onPreparePanel(self, featureId: int | java.jint | java.lang.Integer, view: android.view.View, menu: android.view.Menu, /) -> bool: ...
    def onRequestPermissionsResult(self, requestCode: int | java.jint | java.lang.Integer, permissions: java.chaquopy.JavaArray[java.lang.String], grantResults: java.chaquopy.JavaArrayJInt, /) -> None: ...
    def onRetainCustomNonConfigurationInstance(self) -> java.lang.Object: ...
    def onRetainNonConfigurationInstance(self) -> java.lang.Object: ...
    def onSaveInstanceState(self, outState: android.os.Bundle, /) -> None: ...
    def onTrimMemory(self, level: int | java.jint | java.lang.Integer, /) -> None: ...
    def peekAvailableContext(self) -> android.content.Context: ...
    _registerForActivityResult_0__I = typing.TypeVar('_registerForActivityResult_0__I')  # <I>
    _registerForActivityResult_0__O = typing.TypeVar('_registerForActivityResult_0__O')  # <O>
    _registerForActivityResult_1__I = typing.TypeVar('_registerForActivityResult_1__I')  # <I>
    _registerForActivityResult_1__O = typing.TypeVar('_registerForActivityResult_1__O')  # <O>
    @typing.overload
    def registerForActivityResult(self, contract: androidx.activity.result.contract.ActivityResultContract[_registerForActivityResult_0__I, _registerForActivityResult_0__O], callback: androidx.activity.result.ActivityResultCallback[_registerForActivityResult_0__O], /) -> androidx.activity.result.ActivityResultLauncher[_registerForActivityResult_0__I]: ...
    @typing.overload
    def registerForActivityResult(self, contract: androidx.activity.result.contract.ActivityResultContract[_registerForActivityResult_1__I, _registerForActivityResult_1__O], registry: androidx.activity.result.ActivityResultRegistry, callback: androidx.activity.result.ActivityResultCallback[_registerForActivityResult_1__O], /) -> androidx.activity.result.ActivityResultLauncher[_registerForActivityResult_1__I]: ...
    def removeMenuProvider(self, provider: androidx.core.view.MenuProvider, /) -> None: ...
    def removeOnConfigurationChangedListener(self, listener: androidx.core.util.Consumer[android.content.res.Configuration], /) -> None: ...
    def removeOnContextAvailableListener(self, listener: androidx.activity.contextaware.OnContextAvailableListener, /) -> None: ...
    def removeOnMultiWindowModeChangedListener(self, listener: androidx.core.util.Consumer[androidx.core.app.MultiWindowModeChangedInfo], /) -> None: ...
    def removeOnNewIntentListener(self, listener: androidx.core.util.Consumer[android.content.Intent], /) -> None: ...
    def removeOnPictureInPictureModeChangedListener(self, listener: androidx.core.util.Consumer[androidx.core.app.PictureInPictureModeChangedInfo], /) -> None: ...
    def removeOnTrimMemoryListener(self, listener: androidx.core.util.Consumer[java.lang.Integer], /) -> None: ...
    def reportFullyDrawn(self) -> None: ...
    @typing.overload
    def setContentView(self, layoutResID: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setContentView(self, view: android.view.View, /) -> None: ...
    @typing.overload
    def setContentView(self, view: android.view.View, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    @typing.overload
    def startActivityForResult(self, intent: android.content.Intent, requestCode: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def startActivityForResult(self, intent: android.content.Intent, requestCode: int | java.jint | java.lang.Integer, options: android.os.Bundle, /) -> None: ...
    @typing.overload
    def startIntentSenderForResult(self, intent: android.content.IntentSender, requestCode: int | java.jint | java.lang.Integer, fillInIntent: android.content.Intent, flagsMask: int | java.jint | java.lang.Integer, flagsValues: int | java.jint | java.lang.Integer, extraFlags: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def startIntentSenderForResult(self, intent: android.content.IntentSender, requestCode: int | java.jint | java.lang.Integer, fillInIntent: android.content.Intent, flagsMask: int | java.jint | java.lang.Integer, flagsValues: int | java.jint | java.lang.Integer, extraFlags: int | java.jint | java.lang.Integer, options: android.os.Bundle, /) -> None: ...

class ComponentDialog(android.app.Dialog, androidx.lifecycle.LifecycleOwner, OnBackPressedDispatcherOwner):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, themeResId: int | java.jint | java.lang.Integer, /) -> None: ...
    def addContentView(self, view: android.view.View, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    def getLifecycle(self) -> androidx.lifecycle.Lifecycle: ...
    def getOnBackPressedDispatcher(self) -> OnBackPressedDispatcher: ...
    def onBackPressed(self) -> None: ...
    def onCreate(self, savedInstanceState: android.os.Bundle, /) -> None: ...
    def onStart(self) -> None: ...
    def onStop(self) -> None: ...
    @typing.overload
    def setContentView(self, layoutResID: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setContentView(self, view: android.view.View, /) -> None: ...
    @typing.overload
    def setContentView(self, view: android.view.View, params: android.view.ViewGroup.LayoutParams, /) -> None: ...

class ImmLeaksCleaner(androidx.lifecycle.LifecycleEventObserver):
    def onStateChanged(self, source: androidx.lifecycle.LifecycleOwner, event: androidx.lifecycle.Lifecycle.Event, /) -> None: ...

class OnBackPressedCallback(java.lang.Object):
    def __init__(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def handleOnBackPressed(self) -> None: ...
    def isEnabled(self) -> bool: ...
    def remove(self) -> None: ...
    def setEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class OnBackPressedDispatcher(java.lang.Object):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, fallbackOnBackPressed: java.lang.Runnable, /) -> None: ...
    @typing.overload
    def addCallback(self, onBackPressedCallback: OnBackPressedCallback, /) -> None: ...
    @typing.overload
    def addCallback(self, owner: androidx.lifecycle.LifecycleOwner, onBackPressedCallback: OnBackPressedCallback, /) -> None: ...
    def hasEnabledCallbacks(self) -> bool: ...
    def onBackPressed(self) -> None: ...
    def setOnBackInvokedDispatcher(self, invoker: android.window.OnBackInvokedDispatcher, /) -> None: ...

class OnBackPressedDispatcherOwner(androidx.lifecycle.LifecycleOwner):
    def getOnBackPressedDispatcher(self) -> OnBackPressedDispatcher: ...

class ViewTreeOnBackPressedDispatcherOwner(java.lang.Object):
    @staticmethod
    def get(this_findViewTreeOnBackPressedDispatcherOwner: android.view.View, /) -> OnBackPressedDispatcherOwner: ...
    @staticmethod
    def set(this_setViewTreeOnBackPressedDispatcherOwner: android.view.View, onBackPressedDispatcherOwner: OnBackPressedDispatcherOwner, /) -> None: ...
