import android.animation
import android.content
import android.graphics.drawable
import android.os
import android.text
import android.util
import android.view
import android.view.accessibility
import android.widget
import androidx.activity
import androidx.appcompat.widget
import androidx.coordinatorlayout.widget
import com.google.android.material.appbar
import com.google.android.material.motion
import java
import java.chaquopy
import java.lang
import typing



class SearchBar(androidx.appcompat.widget.Toolbar):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def addCollapseAnimationListener(self, listener: android.animation.AnimatorListenerAdapter, /) -> None: ...
    def addExpandAnimationListener(self, listener: android.animation.AnimatorListenerAdapter, /) -> None: ...
    def addOnLoadAnimationCallback(self, onLoadAnimationCallback: SearchBar.OnLoadAnimationCallback, /) -> None: ...
    def addView(self, child: android.view.View, index: int | java.jint | java.lang.Integer, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    def clearText(self) -> None: ...
    @typing.overload
    def collapse(self, expandedView: android.view.View, /) -> bool: ...
    @typing.overload
    def collapse(self, expandedView: android.view.View, appBarLayout: com.google.android.material.appbar.AppBarLayout, /) -> bool: ...
    @typing.overload
    def collapse(self, expandedView: android.view.View, appBarLayout: com.google.android.material.appbar.AppBarLayout, skipAnimation: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    @typing.overload
    def expand(self, expandedView: android.view.View, /) -> bool: ...
    @typing.overload
    def expand(self, expandedView: android.view.View, appBarLayout: com.google.android.material.appbar.AppBarLayout, /) -> bool: ...
    @typing.overload
    def expand(self, expandedView: android.view.View, appBarLayout: com.google.android.material.appbar.AppBarLayout, skipAnimation: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def getCenterView(self) -> android.view.View: ...
    def getCornerSize(self) -> float: ...
    def getDefaultMarginVerticalResource(self) -> int: ...
    def getDefaultNavigationIconResource(self) -> int: ...
    def getHint(self) -> java.lang.CharSequence: ...
    def getMaxWidth(self) -> int: ...
    def getStrokeColor(self) -> int: ...
    def getStrokeWidth(self) -> float: ...
    def getText(self) -> java.lang.CharSequence: ...
    def getTextCentered(self) -> bool: ...
    def getTextView(self) -> android.widget.TextView: ...
    def inflateMenu(self, resId: int | java.jint | java.lang.Integer, /) -> None: ...
    def isCollapsing(self) -> bool: ...
    def isDefaultScrollFlagsEnabled(self) -> bool: ...
    def isExpanding(self) -> bool: ...
    def isLiftOnScroll(self) -> bool: ...
    def isOnLoadAnimationFadeInEnabled(self) -> bool: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onInitializeAccessibilityNodeInfo(self, info: android.view.accessibility.AccessibilityNodeInfo, /) -> None: ...
    def onLayout(self, changed: bool | java.jboolean | java.lang.Boolean, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def onRestoreInstanceState(self, state: android.os.Parcelable, /) -> None: ...
    def onSaveInstanceState(self) -> android.os.Parcelable: ...
    def removeCollapseAnimationListener(self, listener: android.animation.AnimatorListenerAdapter, /) -> bool: ...
    def removeExpandAnimationListener(self, listener: android.animation.AnimatorListenerAdapter, /) -> bool: ...
    def removeOnLoadAnimationCallback(self, onLoadAnimationCallback: SearchBar.OnLoadAnimationCallback, /) -> bool: ...
    def setCenterView(self, view: android.view.View, /) -> None: ...
    def setDefaultScrollFlagsEnabled(self, defaultScrollFlagsEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setElevation(self, elevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def setHint(self, hintResId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setHint(self, hint: java.lang.CharSequence, /) -> None: ...
    def setLiftOnScroll(self, liftOnScroll: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setMaxWidth(self, maxWidth: int | java.jint | java.lang.Integer, /) -> None: ...
    def setNavigationIcon(self, navigationIcon: android.graphics.drawable.Drawable, /) -> None: ...
    def setNavigationOnClickListener(self, listener: android.view.View.OnClickListener, /) -> None: ...
    def setOnLoadAnimationFadeInEnabled(self, onLoadAnimationFadeInEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setStrokeColor(self, strokeColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setStrokeWidth(self, strokeWidth: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setSubtitle(self, subtitle: java.lang.CharSequence, /) -> None: ...
    @typing.overload
    def setText(self, textResId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setText(self, text: java.lang.CharSequence, /) -> None: ...
    def setTextCentered(self, textCentered: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setTitle(self, title: java.lang.CharSequence, /) -> None: ...
    def startOnLoadAnimation(self) -> None: ...
    def stopOnLoadAnimation(self) -> None: ...

    class OnLoadAnimationCallback(java.lang.Object):
        def __init__(self) -> None: ...
        def onAnimationEnd(self) -> None: ...
        def onAnimationStart(self) -> None: ...

    class ScrollingViewBehavior(com.google.android.material.appbar.AppBarLayout.ScrollingViewBehavior):
        @typing.overload
        def __init__(self) -> None: ...
        @typing.overload
        def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
        def onDependentViewChanged(self, parent: androidx.coordinatorlayout.widget.CoordinatorLayout, child: android.view.View, dependency: android.view.View, /) -> bool: ...
        def shouldHeaderOverlapScrollingChild(self) -> bool: ...

class SearchBarAnimationHelper(java.lang.Object): ...

class SearchView(android.widget.FrameLayout, androidx.coordinatorlayout.widget.CoordinatorLayout.AttachedBehavior, com.google.android.material.motion.MaterialBackHandler):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def addHeaderView(self, headerView: android.view.View, /) -> None: ...
    def addTransitionListener(self, transitionListener: SearchView.TransitionListener, /) -> None: ...
    def addView(self, child: android.view.View, index: int | java.jint | java.lang.Integer, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    def cancelBackProgress(self) -> None: ...
    def clearFocusAndHideKeyboard(self) -> None: ...
    def clearText(self) -> None: ...
    def getBehavior(self) -> androidx.coordinatorlayout.widget.CoordinatorLayout.Behavior[SearchView]: ...
    def getCurrentTransitionState(self) -> SearchView.TransitionState: ...
    def getDefaultNavigationIconResource(self) -> int: ...
    def getEditText(self) -> android.widget.EditText: ...
    def getHint(self) -> java.lang.CharSequence: ...
    def getSearchPrefix(self) -> android.widget.TextView: ...
    def getSearchPrefixText(self) -> java.lang.CharSequence: ...
    def getSoftInputMode(self) -> int: ...
    def getText(self) -> android.text.Editable: ...
    def getToolbar(self) -> androidx.appcompat.widget.Toolbar: ...
    def handleBackInvoked(self) -> None: ...
    def hide(self) -> None: ...
    def inflateMenu(self, menuResId: int | java.jint | java.lang.Integer, /) -> None: ...
    def isAnimatedNavigationIcon(self) -> bool: ...
    def isAutoShowKeyboard(self) -> bool: ...
    def isMenuItemsAnimated(self) -> bool: ...
    def isSetupWithSearchBar(self) -> bool: ...
    def isShowing(self) -> bool: ...
    def isUseWindowInsetsController(self) -> bool: ...
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onFinishInflate(self) -> None: ...
    def onRestoreInstanceState(self, state: android.os.Parcelable, /) -> None: ...
    def onSaveInstanceState(self) -> android.os.Parcelable: ...
    def removeAllHeaderViews(self) -> None: ...
    def removeHeaderView(self, headerView: android.view.View, /) -> None: ...
    def removeTransitionListener(self, transitionListener: SearchView.TransitionListener, /) -> None: ...
    def requestFocusAndShowKeyboard(self) -> None: ...
    def setAnimatedNavigationIcon(self, animatedNavigationIcon: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setAutoShowKeyboard(self, autoShowKeyboard: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setElevation(self, elevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def setHint(self, hintResId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setHint(self, hint: java.lang.CharSequence, /) -> None: ...
    def setMenuItemsAnimated(self, menuItemsAnimated: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setModalForAccessibility(self, isSearchViewModal: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setOnMenuItemClickListener(self, onMenuItemClickListener: androidx.appcompat.widget.Toolbar.OnMenuItemClickListener, /) -> None: ...
    def setSearchPrefixText(self, searchPrefixText: java.lang.CharSequence, /) -> None: ...
    def setStatusBarSpacerEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def setText(self, textResId: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setText(self, text: java.lang.CharSequence, /) -> None: ...
    def setToolbarTouchscreenBlocksFocus(self, touchscreenBlocksFocus: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setUseWindowInsetsController(self, useWindowInsetsController: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setVisible(self, visible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setupWithSearchBar(self, searchBar: SearchBar, /) -> None: ...
    def show(self) -> None: ...
    def startBackProgress(self, backEvent: androidx.activity.BackEventCompat, /) -> None: ...
    def updateBackProgress(self, backEvent: androidx.activity.BackEventCompat, /) -> None: ...
    def updateSoftInputMode(self) -> None: ...

    class TransitionState(java.lang.Enum[SearchView.TransitionState]):
        HIDING: typing.ClassVar[SearchView.TransitionState] = ...
        HIDDEN: typing.ClassVar[SearchView.TransitionState] = ...
        SHOWING: typing.ClassVar[SearchView.TransitionState] = ...
        SHOWN: typing.ClassVar[SearchView.TransitionState] = ...
        @staticmethod
        def valueOf(name: str | java.lang.String, /) -> SearchView.TransitionState: ...
        @staticmethod
        def values() -> java.chaquopy.JavaArray[SearchView.TransitionState]: ...

    class Behavior(androidx.coordinatorlayout.widget.CoordinatorLayout.Behavior[SearchView]):
        @typing.overload
        def __init__(self) -> None: ...
        @typing.overload
        def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
        def onDependentViewChanged(self, parent: androidx.coordinatorlayout.widget.CoordinatorLayout, child: SearchView, dependency: android.view.View, /) -> bool: ...

    class TransitionListener(java.lang.Object):
        def onStateChanged(self, arg1: SearchView, arg2: SearchView.TransitionState, arg3: SearchView.TransitionState, /) -> None: ...

class SearchViewAnimationHelper(java.lang.Object):
    def cancelBackProgress(self) -> None: ...
    def finishBackProgress(self) -> None: ...
    def onHandleBackInvoked(self) -> androidx.activity.BackEventCompat: ...
    def updateBackProgress(self, backEvent: androidx.activity.BackEventCompat, /) -> None: ...
