import typing

import android.content
import java.lang
import org.osmdroid.views
import org.osmdroid.views.overlay

class LatLonGridlineOverlay(java.lang.Object):
    lineColor: typing.ClassVar[int] = ...
    fontColor: typing.ClassVar[int] = ...
    backgroundColor: typing.ClassVar[int] = ...
    def __init__(self) -> None: ...
    @staticmethod
    def getLatLonGrid(ctx: android.content.Context, mapView: org.osmdroid.views.MapView, /) -> org.osmdroid.views.overlay.FolderOverlay: ...
