import typing

import java
import java.lang
import java.util
import java.util.concurrent
import java.util.concurrent.atomic
import java.util.concurrent.locks
import kotlin
import kotlin.coroutines
import kotlin.coroutines.jvm.internal
import kotlin.jvm.functions
import kotlinx
import kotlinx.coroutines

_ArrayQueue__T = typing.TypeVar('_ArrayQueue__T')  # <T>
class ArrayQueue(java.lang.Object, typing.Generic[_ArrayQueue__T]):
    def __init__(self) -> None: ...
    def addLast(self, element: _ArrayQueue__T, /) -> None: ...
    def clear(self) -> None: ...
    def isEmpty(self) -> bool: ...
    def removeFirstOrNull(self) -> _ArrayQueue__T: ...

class AtomicDesc(java.lang.Object):
    atomicOp: AtomicOp[java.lang.Object] = ...
    def __init__(self) -> None: ...
    def complete(self, arg1: AtomicOp[java.lang.Object], arg2: java.lang.Object | int | bool | float | str, /) -> None: ...
    def getAtomicOp(self) -> AtomicOp[java.lang.Object]: ...
    def prepare(self, arg1: AtomicOp[java.lang.Object], /) -> java.lang.Object: ...
    def setAtomicOp(self, <set-?>: AtomicOp[java.lang.Object], /) -> None: ...

class AtomicKt(java.lang.Object):
    NO_DECISION: typing.ClassVar[java.lang.Object] = ...
    RETRY_ATOMIC: typing.ClassVar[java.lang.Object] = ...

_AtomicOp__T = typing.TypeVar('_AtomicOp__T')  # <T>
class AtomicOp(OpDescriptor, typing.Generic[_AtomicOp__T]):
    def __init__(self) -> None: ...
    def complete(self, arg1: _AtomicOp__T, arg2: java.lang.Object | int | bool | float | str, /) -> None: ...
    def decide(self, decision: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def getAtomicOp(self) -> AtomicOp[java.lang.Object]: ...
    def getConsensus(self) -> java.lang.Object: ...
    def getOpSequence(self) -> int: ...
    def isDecided(self) -> bool: ...
    def perform(self, affected: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def prepare(self, arg1: _AtomicOp__T, /) -> java.lang.Object: ...

class ConcurrentKt(java.lang.Object):
    @staticmethod
    def identitySet(expectedSize: int | java.jint | java.lang.Integer, /) -> java.util.Set[java.lang.Object]: ...
    @staticmethod
    def removeFutureOnCancel(executor: java.util.concurrent.Executor, /) -> bool: ...
    @staticmethod
    def subscriberList() -> java.util.List[java.lang.Object]: ...
    _withLock__T = typing.TypeVar('_withLock__T')  # <T>
    @staticmethod
    def withLock(this_withLock: java.util.concurrent.locks.ReentrantLock, action: kotlin.jvm.functions.Function0[_withLock__T], /) -> _withLock__T: ...

class ConcurrentLinkedListKt(java.lang.Object):
    _close__N = typing.TypeVar('_close__N', bound=ConcurrentLinkedListNode[N])  # <N>
    @staticmethod
    def close(this_close: _close__N, /) -> _close__N: ...

_ConcurrentLinkedListNode__N = typing.TypeVar('_ConcurrentLinkedListNode__N', bound=ConcurrentLinkedListNode[N])  # <N>
class ConcurrentLinkedListNode(java.lang.Object, typing.Generic[_ConcurrentLinkedListNode__N]):
    def __init__(self, prev: _ConcurrentLinkedListNode__N, /) -> None: ...
    def cleanPrev(self) -> None: ...
    def getNext(self) -> _ConcurrentLinkedListNode__N: ...
    def getPrev(self) -> _ConcurrentLinkedListNode__N: ...
    def getRemoved(self) -> bool: ...
    def isTail(self) -> bool: ...
    def markAsClosed(self) -> bool: ...
    def nextOrIfClosed(self, onClosedAction: kotlin.jvm.functions.Function0, /) -> _ConcurrentLinkedListNode__N: ...
    def remove(self) -> None: ...
    def trySetNext(self, value: _ConcurrentLinkedListNode__N, /) -> bool: ...

class Concurrent_commonKt(java.lang.Object): ...

class ContextScope(kotlinx.coroutines.CoroutineScope):
    def __init__(self, context: kotlin.coroutines.CoroutineContext, /) -> None: ...
    def getCoroutineContext(self) -> kotlin.coroutines.CoroutineContext: ...
    def toString(self) -> str: ...

_DispatchedContinuation__T = typing.TypeVar('_DispatchedContinuation__T')  # <T>
class DispatchedContinuation(kotlinx.coroutines.DispatchedTask[_DispatchedContinuation__T], kotlin.coroutines.jvm.internal.CoroutineStackFrame, kotlin.coroutines.Continuation[_DispatchedContinuation__T], typing.Generic[_DispatchedContinuation__T]):
    dispatcher: kotlinx.coroutines.CoroutineDispatcher = ...
    continuation: kotlin.coroutines.Continuation[_DispatchedContinuation__T] = ...
    _state: java.lang.Object = ...
    countOrElement: java.lang.Object = ...
    def __init__(self, dispatcher: kotlinx.coroutines.CoroutineDispatcher, continuation: kotlin.coroutines.Continuation[_DispatchedContinuation__T], /) -> None: ...
    def awaitReusability(self) -> None: ...
    def cancelCompletedResult$kotlinx_coroutines_core(self, takenState: java.lang.Object | int | bool | float | str, cause: java.lang.Throwable, /) -> None: ...
    def claimReusableCancellableContinuation(self) -> kotlinx.coroutines.CancellableContinuationImpl[_DispatchedContinuation__T]: ...
    def dispatchYield$kotlinx_coroutines_core(self, context: kotlin.coroutines.CoroutineContext, value: _DispatchedContinuation__T, /) -> None: ...
    def getCallerFrame(self) -> kotlin.coroutines.jvm.internal.CoroutineStackFrame: ...
    def getContext(self) -> kotlin.coroutines.CoroutineContext: ...
    def getDelegate$kotlinx_coroutines_core(self) -> kotlin.coroutines.Continuation[_DispatchedContinuation__T]: ...
    def getReusableCancellableContinuation(self) -> kotlinx.coroutines.CancellableContinuationImpl[java.lang.Object]: ...
    def getStackTraceElement(self) -> java.lang.StackTraceElement: ...
    def isReusable(self, requester: kotlinx.coroutines.CancellableContinuationImpl[java.lang.Object], /) -> bool: ...
    def postponeCancellation(self, cause: java.lang.Throwable, /) -> bool: ...
    def release(self) -> None: ...
    def resumeCancellableWith(self, result: java.lang.Object | int | bool | float | str, onCancellation: kotlin.jvm.functions.Function1[java.lang.Throwable, kotlin.Unit], /) -> None: ...
    def resumeCancelled(self, state: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def resumeUndispatchedWith(self, result: java.lang.Object | int | bool | float | str, /) -> None: ...
    def resumeWith(self, result: java.lang.Object | int | bool | float | str, /) -> None: ...
    def takeState$kotlinx_coroutines_core(self) -> java.lang.Object: ...
    def toString(self) -> str: ...
    def tryReleaseClaimedContinuation(self, continuation: kotlinx.coroutines.CancellableContinuation[java.lang.Object], /) -> java.lang.Throwable: ...

class DispatchedContinuationKt(java.lang.Object):
    REUSABLE_CLAIMED: typing.ClassVar[Symbol] = ...
    @staticmethod
    def resumeCancellableWith(this_resumeCancellableWith: kotlin.coroutines.Continuation[java.lang.Object], result: java.lang.Object | int | bool | float | str, onCancellation: kotlin.jvm.functions.Function1[java.lang.Throwable, kotlin.Unit], /) -> None: ...
    @staticmethod
    def yieldUndispatched(this_yieldUndispatched: DispatchedContinuation[kotlin.Unit], /) -> bool: ...

class ExceptionsConstuctorKt(java.lang.Object):
    _tryCopyException__E = typing.TypeVar('_tryCopyException__E', bound=java.lang.Throwable)  # <E>
    @staticmethod
    def tryCopyException(exception: _tryCopyException__E, /) -> _tryCopyException__E: ...

class FastServiceLoader(java.lang.Object):
    INSTANCE: typing.ClassVar[FastServiceLoader] = ...
    def loadMainDispatcherFactory$kotlinx_coroutines_core(self) -> java.util.List[MainDispatcherFactory]: ...
    _loadProviders$kotlinx_coroutines_core__S = typing.TypeVar('_loadProviders$kotlinx_coroutines_core__S')  # <S>
    def loadProviders$kotlinx_coroutines_core(self, service: typing.Type[_loadProviders.kotlinx_coroutines_core__S], loader: java.lang.ClassLoader, /) -> java.util.List[_loadProviders.kotlinx_coroutines_core__S]: ...

class FastServiceLoaderKt(java.lang.Object):
    @staticmethod
    def getANDROID_DETECTED() -> bool: ...

_InlineList__E = typing.TypeVar('_InlineList__E')  # <E>
class InlineList(java.lang.Object, typing.Generic[_InlineList__E]):
    @staticmethod
    def constructor-impl(holder: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl(arg0: java.lang.Object | int | bool | float | str, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl0(p1: java.lang.Object | int | bool | float | str, p2: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def forEachReversed-impl(arg0: java.lang.Object | int | bool | float | str, action: kotlin.jvm.functions.Function1[E, kotlin.Unit], /) -> None: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def hashCode-impl(arg0: java.lang.Object | int | bool | float | str, /) -> int: ...
    @staticmethod
    def plus-FjFbRPM(arg0: java.lang.Object | int | bool | float | str, element: E, /) -> java.lang.Object: ...
    def toString(self) -> str: ...
    @staticmethod
    def toString-impl(arg0: java.lang.Object | int | bool | float | str, /) -> str: ...

class LocalAtomicsKt(java.lang.Object): ...

class LocalAtomics_commonKt(java.lang.Object):
    @staticmethod
    def getValue(this_value: java.util.concurrent.atomic.AtomicInteger, /) -> int: ...
    @staticmethod
    def setValue(this_value: java.util.concurrent.atomic.AtomicInteger, value: int | java.jint | java.lang.Integer, /) -> None: ...

class LockFreeLinkedListHead(LockFreeLinkedListNode):
    def __init__(self) -> None: ...
    def isEmpty(self) -> bool: ...
    def isRemoved(self) -> bool: ...
    def nextIfRemoved(self) -> LockFreeLinkedListNode: ...
    def remove(self) -> bool: ...
    def validate$kotlinx_coroutines_core(self) -> None: ...

class LockFreeLinkedListKt(java.lang.Object):
    UNDECIDED: typing.ClassVar[int] = ...
    SUCCESS: typing.ClassVar[int] = ...
    FAILURE: typing.ClassVar[int] = ...
    @staticmethod
    def getCONDITION_FALSE() -> java.lang.Object: ...
    @staticmethod
    def getLIST_EMPTY() -> java.lang.Object: ...
    @staticmethod
    def unwrap(this_unwrap: java.lang.Object | int | bool | float | str, /) -> LockFreeLinkedListNode: ...


_LockFreeLinkedListNode__AddLastDesc__T = typing.TypeVar('_LockFreeLinkedListNode__AddLastDesc__T', bound=LockFreeLinkedListNode)  # <T>

_LockFreeLinkedListNode__RemoveFirstDesc__T = typing.TypeVar('_LockFreeLinkedListNode__RemoveFirstDesc__T')  # <T>
class LockFreeLinkedListNode(java.lang.Object):
    def __init__(self) -> None: ...
    def addLast(self, node: LockFreeLinkedListNode, /) -> None: ...
    def addLastIf(self, node: LockFreeLinkedListNode, condition: kotlin.jvm.functions.Function0[java.lang.Boolean], /) -> bool: ...
    def addLastIfPrev(self, node: LockFreeLinkedListNode, predicate: kotlin.jvm.functions.Function1[LockFreeLinkedListNode, java.lang.Boolean], /) -> bool: ...
    def addLastIfPrevAndIf(self, node: LockFreeLinkedListNode, predicate: kotlin.jvm.functions.Function1[LockFreeLinkedListNode, java.lang.Boolean], condition: kotlin.jvm.functions.Function0[java.lang.Boolean], /) -> bool: ...
    def addNext(self, node: LockFreeLinkedListNode, next: LockFreeLinkedListNode, /) -> bool: ...
    def addOneIfEmpty(self, node: LockFreeLinkedListNode, /) -> bool: ...
    _describeAddLast__T = typing.TypeVar('_describeAddLast__T', bound=LockFreeLinkedListNode)  # <T>
    def describeAddLast(self, node: _describeAddLast__T, /) -> LockFreeLinkedListNode.AddLastDesc[_describeAddLast__T]: ...
    def describeRemoveFirst(self) -> LockFreeLinkedListNode.RemoveFirstDesc[LockFreeLinkedListNode]: ...
    def getNext(self) -> java.lang.Object: ...
    def getNextNode(self) -> LockFreeLinkedListNode: ...
    def getPrevNode(self) -> LockFreeLinkedListNode: ...
    def helpRemove(self) -> None: ...
    def helpRemovePrev(self) -> None: ...
    def isRemoved(self) -> bool: ...
    def makeCondAddOp(self, node: LockFreeLinkedListNode, condition: kotlin.jvm.functions.Function0[java.lang.Boolean], /) -> LockFreeLinkedListNode.CondAddOp: ...
    def nextIfRemoved(self) -> LockFreeLinkedListNode: ...
    def remove(self) -> bool: ...
    def removeFirstOrNull(self) -> LockFreeLinkedListNode: ...
    def removeOrNext(self) -> LockFreeLinkedListNode: ...
    def toString(self) -> str: ...
    def tryCondAddNext(self, node: LockFreeLinkedListNode, next: LockFreeLinkedListNode, condAdd: LockFreeLinkedListNode.CondAddOp, /) -> int: ...
    def validateNode$kotlinx_coroutines_core(self, prev: LockFreeLinkedListNode, next: LockFreeLinkedListNode, /) -> None: ...

    class CondAddOp(AtomicOp[LockFreeLinkedListNode]):
        newNode: LockFreeLinkedListNode = ...
        oldNext: LockFreeLinkedListNode = ...
        def __init__(self, newNode: LockFreeLinkedListNode, /) -> None: ...
        def complete(self, affected: LockFreeLinkedListNode, failure: java.lang.Object | int | bool | float | str, /) -> None: ...
    class AddLastDesc(kotlinx.coroutines.internal.LockFreeLinkedListNode.AbstractAtomicDesc, typing.Generic[_LockFreeLinkedListNode__AddLastDesc__T]):
        queue: LockFreeLinkedListNode = ...
        node: _LockFreeLinkedListNode__AddLastDesc__T = ...
        def __init__(self, queue: LockFreeLinkedListNode, node: _LockFreeLinkedListNode__AddLastDesc__T, /) -> None: ...
        def finishOnSuccess(self, affected: LockFreeLinkedListNode, next: LockFreeLinkedListNode, /) -> None: ...
        def finishPrepare(self, prepareOp: LockFreeLinkedListNode.PrepareOp, /) -> None: ...
        def getAffectedNode(self) -> LockFreeLinkedListNode: ...
        def getOriginalNext(self) -> LockFreeLinkedListNode: ...
        def retry(self, affected: LockFreeLinkedListNode, next: java.lang.Object | int | bool | float | str, /) -> bool: ...
        def takeAffectedNode(self, op: OpDescriptor, /) -> LockFreeLinkedListNode: ...
        def updatedNext(self, affected: LockFreeLinkedListNode, next: LockFreeLinkedListNode, /) -> java.lang.Object: ...
    class RemoveFirstDesc(kotlinx.coroutines.internal.LockFreeLinkedListNode.AbstractAtomicDesc, typing.Generic[_LockFreeLinkedListNode__RemoveFirstDesc__T]):
        queue: LockFreeLinkedListNode = ...
        def __init__(self, queue: LockFreeLinkedListNode, /) -> None: ...
        def failure(self, affected: LockFreeLinkedListNode, /) -> java.lang.Object: ...
        def finishOnSuccess(self, affected: LockFreeLinkedListNode, next: LockFreeLinkedListNode, /) -> None: ...
        def finishPrepare(self, prepareOp: LockFreeLinkedListNode.PrepareOp, /) -> None: ...
        def getAffectedNode(self) -> LockFreeLinkedListNode: ...
        def getOriginalNext(self) -> LockFreeLinkedListNode: ...
        def getResult(self) -> _LockFreeLinkedListNode__RemoveFirstDesc__T: ...
        def retry(self, affected: LockFreeLinkedListNode, next: java.lang.Object | int | bool | float | str, /) -> bool: ...
        def takeAffectedNode(self, op: OpDescriptor, /) -> LockFreeLinkedListNode: ...
        def updatedNext(self, affected: LockFreeLinkedListNode, next: LockFreeLinkedListNode, /) -> java.lang.Object: ...

    class PrepareOp(OpDescriptor):
        affected: LockFreeLinkedListNode = ...
        next: LockFreeLinkedListNode = ...
        desc: LockFreeLinkedListNode.AbstractAtomicDesc = ...
        def __init__(self, affected: LockFreeLinkedListNode, next: LockFreeLinkedListNode, desc: LockFreeLinkedListNode.AbstractAtomicDesc, /) -> None: ...
        def finishPrepare(self) -> None: ...
        def getAtomicOp(self) -> AtomicOp[java.lang.Object]: ...
        def perform(self, affected: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
        def toString(self) -> str: ...

    class AbstractAtomicDesc(AtomicDesc):
        def __init__(self) -> None: ...
        def complete(self, op: AtomicOp[java.lang.Object], failure: java.lang.Object | int | bool | float | str, /) -> None: ...
        def failure(self, affected: LockFreeLinkedListNode, /) -> java.lang.Object: ...
        def finishOnSuccess(self, arg1: LockFreeLinkedListNode, arg2: LockFreeLinkedListNode, /) -> None: ...
        def finishPrepare(self, arg1: LockFreeLinkedListNode.PrepareOp, /) -> None: ...
        def getAffectedNode(self) -> LockFreeLinkedListNode: ...
        def getOriginalNext(self) -> LockFreeLinkedListNode: ...
        def onPrepare(self, prepareOp: LockFreeLinkedListNode.PrepareOp, /) -> java.lang.Object: ...
        def onRemoved(self, affected: LockFreeLinkedListNode, /) -> None: ...
        def prepare(self, op: AtomicOp[java.lang.Object], /) -> java.lang.Object: ...
        def retry(self, affected: LockFreeLinkedListNode, next: java.lang.Object | int | bool | float | str, /) -> bool: ...
        def takeAffectedNode(self, op: OpDescriptor, /) -> LockFreeLinkedListNode: ...
        def updatedNext(self, arg1: LockFreeLinkedListNode, arg2: LockFreeLinkedListNode, /) -> java.lang.Object: ...

class LockFreeLinkedList_commonKt(java.lang.Object):
    REMOVE_PREPARED: typing.ClassVar[java.lang.Object] = ...

_LockFreeTaskQueue__E = typing.TypeVar('_LockFreeTaskQueue__E')  # <E>
class LockFreeTaskQueue(java.lang.Object, typing.Generic[_LockFreeTaskQueue__E]):
    def __init__(self, singleConsumer: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def addLast(self, element: _LockFreeTaskQueue__E, /) -> bool: ...
    def close(self) -> None: ...
    def getSize(self) -> int: ...
    def isClosed(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    _map__R = typing.TypeVar('_map__R')  # <R>
    def map(self, transform: kotlin.jvm.functions.Function1[_LockFreeTaskQueue__E, _map__R], /) -> java.util.List[_map__R]: ...
    def removeFirstOrNull(self) -> _LockFreeTaskQueue__E: ...

_LockFreeTaskQueueCore__E = typing.TypeVar('_LockFreeTaskQueueCore__E')  # <E>
class LockFreeTaskQueueCore(java.lang.Object, typing.Generic[_LockFreeTaskQueueCore__E]):
    Companion: typing.ClassVar[LockFreeTaskQueueCore.Companion] = ...
    INITIAL_CAPACITY: typing.ClassVar[int] = ...
    CAPACITY_BITS: typing.ClassVar[int] = ...
    MAX_CAPACITY_MASK: typing.ClassVar[int] = ...
    HEAD_SHIFT: typing.ClassVar[int] = ...
    HEAD_MASK: typing.ClassVar[int] = ...
    TAIL_SHIFT: typing.ClassVar[int] = ...
    TAIL_MASK: typing.ClassVar[int] = ...
    FROZEN_SHIFT: typing.ClassVar[int] = ...
    FROZEN_MASK: typing.ClassVar[int] = ...
    CLOSED_SHIFT: typing.ClassVar[int] = ...
    CLOSED_MASK: typing.ClassVar[int] = ...
    MIN_ADD_SPIN_CAPACITY: typing.ClassVar[int] = ...
    REMOVE_FROZEN: typing.ClassVar[Symbol] = ...
    ADD_SUCCESS: typing.ClassVar[int] = ...
    ADD_FROZEN: typing.ClassVar[int] = ...
    ADD_CLOSED: typing.ClassVar[int] = ...
    def __init__(self, capacity: int | java.jint | java.lang.Integer, singleConsumer: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def addLast(self, element: _LockFreeTaskQueueCore__E, /) -> int: ...
    def close(self) -> bool: ...
    def getSize(self) -> int: ...
    def isClosed(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    _map__R = typing.TypeVar('_map__R')  # <R>
    def map(self, transform: kotlin.jvm.functions.Function1[_LockFreeTaskQueueCore__E, _map__R], /) -> java.util.List[_map__R]: ...
    def next(self) -> LockFreeTaskQueueCore[_LockFreeTaskQueueCore__E]: ...
    def removeFirstOrNull(self) -> java.lang.Object: ...

    class Placeholder(java.lang.Object):
        index: int = ...
        def __init__(self, index: int | java.jint | java.lang.Integer, /) -> None: ...

    class Companion(java.lang.Object):
        def addFailReason(self, this_addFailReason: int | java.jlong | java.lang.Long, /) -> int: ...
        def updateHead(self, this_updateHead: int | java.jlong | java.lang.Long, newHead: int | java.jint | java.lang.Integer, /) -> int: ...
        def updateTail(self, this_updateTail: int | java.jlong | java.lang.Long, newTail: int | java.jint | java.lang.Integer, /) -> int: ...
        _withState__T = typing.TypeVar('_withState__T')  # <T>
        def withState(self, this_withState: int | java.jlong | java.lang.Long, block: kotlin.jvm.functions.Function2[int, int, _withState__T], /) -> _withState__T: ...
        def wo(self, this_wo: int | java.jlong | java.lang.Long, other: int | java.jlong | java.lang.Long, /) -> int: ...

class LockFreeTaskQueueKt(java.lang.Object): ...

class MainDispatcherFactory(java.lang.Object):
    def createDispatcher(self, arg1: java.util.List[MainDispatcherFactory], /) -> kotlinx.coroutines.MainCoroutineDispatcher: ...
    def getLoadPriority(self) -> int: ...
    def hintOnError(self) -> str: ...

    class DefaultImpls(java.lang.Object):
        @staticmethod
        def hintOnError(this: MainDispatcherFactory, /) -> str: ...

class MainDispatcherLoader(java.lang.Object):
    INSTANCE: typing.ClassVar[MainDispatcherLoader] = ...
    dispatcher: typing.ClassVar[kotlinx.coroutines.MainCoroutineDispatcher] = ...

class MainDispatchersKt(java.lang.Object):
    @staticmethod
    def isMissing(this_isMissing: kotlinx.coroutines.MainCoroutineDispatcher, /) -> bool: ...
    @staticmethod
    def throwMissingMainDispatcherException() -> None: ...
    @staticmethod
    def tryCreateDispatcher(this_tryCreateDispatcher: MainDispatcherFactory, factories: java.util.List[MainDispatcherFactory], /) -> kotlinx.coroutines.MainCoroutineDispatcher: ...

class MissingMainCoroutineDispatcher(kotlinx.coroutines.MainCoroutineDispatcher, kotlinx.coroutines.Delay):
    def __init__(self, cause: java.lang.Throwable, errorHint: str | java.lang.String, /) -> None: ...
    def delay(self, time: int | java.jlong | java.lang.Long, completion: kotlin.coroutines.Continuation[java.lang.Object], /) -> java.lang.Object: ...
    def dispatch(self, context: kotlin.coroutines.CoroutineContext, block: java.lang.Runnable, /) -> None: ...
    def getImmediate(self) -> kotlinx.coroutines.MainCoroutineDispatcher: ...
    def invokeOnTimeout(self, timeMillis: int | java.jlong | java.lang.Long, block: java.lang.Runnable, context: kotlin.coroutines.CoroutineContext, /) -> kotlinx.coroutines.DisposableHandle: ...
    def isDispatchNeeded(self, context: kotlin.coroutines.CoroutineContext, /) -> bool: ...
    def scheduleResumeAfterDelay(self, timeMillis: int | java.jlong | java.lang.Long, continuation: kotlinx.coroutines.CancellableContinuation[kotlin.Unit], /) -> None: ...
    def toString(self) -> str: ...

class MissingMainCoroutineDispatcherFactory(MainDispatcherFactory):
    INSTANCE: typing.ClassVar[MissingMainCoroutineDispatcherFactory] = ...
    def createDispatcher(self, allFactories: java.util.List[MainDispatcherFactory], /) -> kotlinx.coroutines.MainCoroutineDispatcher: ...
    def getLoadPriority(self) -> int: ...
    def hintOnError(self) -> str: ...

class OnUndeliveredElementKt(java.lang.Object):
    _bindCancellationFun__E = typing.TypeVar('_bindCancellationFun__E')  # <E>
    @staticmethod
    def bindCancellationFun(this_bindCancellationFun: kotlin.jvm.functions.Function1[_bindCancellationFun__E, kotlin.Unit], element: _bindCancellationFun__E, context: kotlin.coroutines.CoroutineContext, /) -> kotlin.jvm.functions.Function1[java.lang.Throwable, kotlin.Unit]: ...
    _callUndeliveredElement__E = typing.TypeVar('_callUndeliveredElement__E')  # <E>
    @staticmethod
    def callUndeliveredElement(this_callUndeliveredElement: kotlin.jvm.functions.Function1[_callUndeliveredElement__E, kotlin.Unit], element: _callUndeliveredElement__E, context: kotlin.coroutines.CoroutineContext, /) -> None: ...
    _callUndeliveredElementCatchingException__E = typing.TypeVar('_callUndeliveredElementCatchingException__E')  # <E>
    @staticmethod
    def callUndeliveredElementCatchingException(this_callUndeliveredElementCatchingException: kotlin.jvm.functions.Function1[_callUndeliveredElementCatchingException__E, kotlin.Unit], element: _callUndeliveredElementCatchingException__E, undeliveredElementException: UndeliveredElementException, /) -> UndeliveredElementException: ...

class OpDescriptor(java.lang.Object):
    def __init__(self) -> None: ...
    def getAtomicOp(self) -> AtomicOp[java.lang.Object]: ...
    def isEarlierThan(self, that: OpDescriptor, /) -> bool: ...
    def perform(self, arg1: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def toString(self) -> str: ...

class ProbesSupportKt(java.lang.Object):
    _probeCoroutineCreated__T = typing.TypeVar('_probeCoroutineCreated__T')  # <T>
    @staticmethod
    def probeCoroutineCreated(completion: kotlin.coroutines.Continuation[_probeCoroutineCreated__T], /) -> kotlin.coroutines.Continuation[_probeCoroutineCreated__T]: ...

class Removed(java.lang.Object):
    ref: LockFreeLinkedListNode = ...
    def __init__(self, ref: LockFreeLinkedListNode, /) -> None: ...
    def toString(self) -> str: ...

_ScopeCoroutine__T = typing.TypeVar('_ScopeCoroutine__T')  # <T>
class ScopeCoroutine(kotlinx.coroutines.AbstractCoroutine[_ScopeCoroutine__T], kotlin.coroutines.jvm.internal.CoroutineStackFrame, typing.Generic[_ScopeCoroutine__T]):
    uCont: kotlin.coroutines.Continuation[_ScopeCoroutine__T] = ...
    def __init__(self, context: kotlin.coroutines.CoroutineContext, uCont: kotlin.coroutines.Continuation[_ScopeCoroutine__T], /) -> None: ...
    def afterCompletion(self, state: java.lang.Object | int | bool | float | str, /) -> None: ...
    def afterResume(self, state: java.lang.Object | int | bool | float | str, /) -> None: ...
    def getCallerFrame(self) -> kotlin.coroutines.jvm.internal.CoroutineStackFrame: ...
    def getParent$kotlinx_coroutines_core(self) -> kotlinx.coroutines.Job: ...
    def getStackTraceElement(self) -> java.lang.StackTraceElement: ...
    def isScopedCoroutine(self) -> bool: ...

_Segment__S = typing.TypeVar('_Segment__S', bound=Segment[S])  # <S>
class Segment(ConcurrentLinkedListNode[_Segment__S], typing.Generic[_Segment__S]):
    def __init__(self, id: int | java.jlong | java.lang.Long, prev: _Segment__S, pointers: int | java.jint | java.lang.Integer, /) -> None: ...
    def decPointers$kotlinx_coroutines_core(self) -> bool: ...
    def getId(self) -> int: ...
    def getMaxSlots(self) -> int: ...
    def getRemoved(self) -> bool: ...
    def onSlotCleaned(self) -> None: ...
    def tryIncPointers$kotlinx_coroutines_core(self) -> bool: ...

_SegmentOrClosed__S = typing.TypeVar('_SegmentOrClosed__S', bound=Segment[S])  # <S>
class SegmentOrClosed(java.lang.Object, typing.Generic[_SegmentOrClosed__S]):
    @staticmethod
    def constructor-impl(value: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl(arg0: java.lang.Object | int | bool | float | str, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl0(p1: java.lang.Object | int | bool | float | str, p2: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def getSegment-impl(arg0: java.lang.Object | int | bool | float | str, /) -> S: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def hashCode-impl(arg0: java.lang.Object | int | bool | float | str, /) -> int: ...
    @staticmethod
    def isClosed-impl(arg0: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def toString(self) -> str: ...
    @staticmethod
    def toString-impl(arg0: java.lang.Object | int | bool | float | str, /) -> str: ...

class StackTraceRecoveryKt(java.lang.Object):
    @staticmethod
    def artificialFrame(message: str | java.lang.String, /) -> java.lang.StackTraceElement: ...
    @staticmethod
    def initCause(this_initCause: java.lang.Throwable, cause: java.lang.Throwable, /) -> None: ...
    @staticmethod
    def isArtificial(this_isArtificial: java.lang.StackTraceElement, /) -> bool: ...
    @staticmethod
    def recoverAndThrow(exception: java.lang.Throwable, completion: kotlin.coroutines.Continuation[java.lang.Object], /) -> java.lang.Object: ...
    _recoverStackTrace_0__E = typing.TypeVar('_recoverStackTrace_0__E', bound=java.lang.Throwable)  # <E>
    _recoverStackTrace_1__E = typing.TypeVar('_recoverStackTrace_1__E', bound=java.lang.Throwable)  # <E>
    @typing.overload
    @staticmethod
    def recoverStackTrace(exception: _recoverStackTrace_0__E, /) -> _recoverStackTrace_0__E: ...
    @typing.overload
    @staticmethod
    def recoverStackTrace(exception: _recoverStackTrace_1__E, continuation: kotlin.coroutines.Continuation[java.lang.Object], /) -> _recoverStackTrace_1__E: ...
    _unwrap__E = typing.TypeVar('_unwrap__E', bound=java.lang.Throwable)  # <E>
    @staticmethod
    def unwrap(exception: _unwrap__E, /) -> _unwrap__E: ...
    _unwrapImpl__E = typing.TypeVar('_unwrapImpl__E', bound=java.lang.Throwable)  # <E>
    @staticmethod
    def unwrapImpl(exception: _unwrapImpl__E, /) -> _unwrapImpl__E: ...

class Symbol(java.lang.Object):
    def __init__(self, symbol: str | java.lang.String, /) -> None: ...
    def getSymbol(self) -> str: ...
    def toString(self) -> str: ...
    def unbox(self, value: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...

class SynchronizedKt(java.lang.Object):
    _synchronized__T = typing.TypeVar('_synchronized__T')  # <T>
    @staticmethod
    def synchronized(lock: java.lang.Object | int | bool | float | str, block: kotlin.jvm.functions.Function0[_synchronized__T], /) -> _synchronized__T: ...

class SystemPropsKt(java.lang.Object):
    @staticmethod
    def getAVAILABLE_PROCESSORS() -> int: ...
    @typing.overload
    @staticmethod
    def systemProp(propertyName: str | java.lang.String, /) -> str: ...
    @typing.overload
    @staticmethod
    def systemProp(propertyName: str | java.lang.String, defaultValue: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    @typing.overload
    @staticmethod
    def systemProp(propertyName: str | java.lang.String, defaultValue: int | java.jint | java.lang.Integer, minValue: int | java.jint | java.lang.Integer, maxValue: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def systemProp(propertyName: str | java.lang.String, defaultValue: int | java.jlong | java.lang.Long, minValue: int | java.jlong | java.lang.Long, maxValue: int | java.jlong | java.lang.Long, /) -> int: ...

class ThreadContextKt(java.lang.Object):
    NO_THREAD_ELEMENTS: typing.ClassVar[Symbol] = ...
    @staticmethod
    def restoreThreadContext(context: kotlin.coroutines.CoroutineContext, oldState: java.lang.Object | int | bool | float | str, /) -> None: ...
    @staticmethod
    def threadContextElements(context: kotlin.coroutines.CoroutineContext, /) -> java.lang.Object: ...
    @staticmethod
    def updateThreadContext(context: kotlin.coroutines.CoroutineContext, countOrElement: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...

_ThreadLocalElement__T = typing.TypeVar('_ThreadLocalElement__T')  # <T>
class ThreadLocalElement(kotlinx.coroutines.ThreadContextElement[_ThreadLocalElement__T], typing.Generic[_ThreadLocalElement__T]):
    def __init__(self, value: _ThreadLocalElement__T, threadLocal: java.lang.ThreadLocal[_ThreadLocalElement__T], /) -> None: ...
    _fold__R = typing.TypeVar('_fold__R')  # <R>
    def fold(self, initial: _fold__R, operation: kotlin.jvm.functions.Function2[_fold__R, kotlin.coroutines.CoroutineContext.Element, _fold__R], /) -> _fold__R: ...
    _get__E = typing.TypeVar('_get__E')  # <E>
    def get(self, key: kotlin.coroutines.CoroutineContext.Key[_get__E], /) -> _get__E: ...
    def getKey(self) -> kotlin.coroutines.CoroutineContext.Key[java.lang.Object]: ...
    def minusKey(self, key: kotlin.coroutines.CoroutineContext.Key[java.lang.Object], /) -> kotlin.coroutines.CoroutineContext: ...
    def plus(self, context: kotlin.coroutines.CoroutineContext, /) -> kotlin.coroutines.CoroutineContext: ...
    def restoreThreadContext(self, context: kotlin.coroutines.CoroutineContext, oldState: _ThreadLocalElement__T, /) -> None: ...
    def toString(self) -> str: ...
    def updateThreadContext(self, context: kotlin.coroutines.CoroutineContext, /) -> _ThreadLocalElement__T: ...

class ThreadLocalKey(kotlin.coroutines.CoroutineContext.Key[ThreadLocalElement[java.lang.Object]]):
    def __init__(self, threadLocal: java.lang.ThreadLocal[java.lang.Object], /) -> None: ...
    def copy(self, threadLocal: java.lang.ThreadLocal[java.lang.Object], /) -> ThreadLocalKey: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class ThreadLocalKt(java.lang.Object): ...

_ThreadSafeHeap__T = typing.TypeVar('_ThreadSafeHeap__T')  # <T>
class ThreadSafeHeap(java.lang.Object, typing.Generic[_ThreadSafeHeap__T]):
    def __init__(self) -> None: ...
    def addImpl(self, node: _ThreadSafeHeap__T, /) -> None: ...
    def addLast(self, node: _ThreadSafeHeap__T, /) -> None: ...
    def addLastIf(self, node: _ThreadSafeHeap__T, cond: kotlin.jvm.functions.Function1[_ThreadSafeHeap__T, java.lang.Boolean], /) -> bool: ...
    def clear(self) -> None: ...
    def firstImpl(self) -> _ThreadSafeHeap__T: ...
    def getSize(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def peek(self) -> _ThreadSafeHeap__T: ...
    def remove(self, node: _ThreadSafeHeap__T, /) -> bool: ...
    def removeAtImpl(self, index: int | java.jint | java.lang.Integer, /) -> _ThreadSafeHeap__T: ...
    def removeFirstIf(self, predicate: kotlin.jvm.functions.Function1[_ThreadSafeHeap__T, java.lang.Boolean], /) -> _ThreadSafeHeap__T: ...
    def removeFirstOrNull(self) -> _ThreadSafeHeap__T: ...

class ThreadSafeHeapNode(java.lang.Object):
    def getHeap(self) -> ThreadSafeHeap[java.lang.Object]: ...
    def getIndex(self) -> int: ...
    def setHeap(self, arg1: ThreadSafeHeap[java.lang.Object], /) -> None: ...
    def setIndex(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...

class ThreadState(java.lang.Object):
    context: kotlin.coroutines.CoroutineContext = ...
    def __init__(self, context: kotlin.coroutines.CoroutineContext, n: int | java.jint | java.lang.Integer, /) -> None: ...
    def append(self, element: kotlinx.coroutines.ThreadContextElement[java.lang.Object], value: java.lang.Object | int | bool | float | str, /) -> None: ...
    def restore(self, context: kotlin.coroutines.CoroutineContext, /) -> None: ...

class UndeliveredElementException(java.lang.RuntimeException):
    def __init__(self, message: str | java.lang.String, cause: java.lang.Throwable, /) -> None: ...
