import android.animation
import android.content
import android.content.res
import android.graphics.drawable
import android.os
import android.util
import android.view
import androidx.appcompat.widget
import androidx.coordinatorlayout.widget
import com.google.android.material.behavior
import com.google.android.material.shape
import java
import java.lang
import java.lang.annotation
import java.util
import typing



class BottomAppBar(androidx.appcompat.widget.Toolbar, androidx.coordinatorlayout.widget.CoordinatorLayout.AttachedBehavior):
    FAB_ALIGNMENT_MODE_CENTER: typing.ClassVar[int] = ...
    FAB_ALIGNMENT_MODE_END: typing.ClassVar[int] = ...
    FAB_ANCHOR_MODE_EMBED: typing.ClassVar[int] = ...
    FAB_ANCHOR_MODE_CRADLE: typing.ClassVar[int] = ...
    FAB_ANIMATION_MODE_SCALE: typing.ClassVar[int] = ...
    FAB_ANIMATION_MODE_SLIDE: typing.ClassVar[int] = ...
    MENU_ALIGNMENT_MODE_AUTO: typing.ClassVar[int] = ...
    MENU_ALIGNMENT_MODE_START: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def addOnScrollStateChangedListener(self, listener: com.google.android.material.behavior.HideBottomViewOnScrollBehavior.OnScrollStateChangedListener, /) -> None: ...
    def clearOnScrollStateChangedListeners(self) -> None: ...
    def createFabDefaultXAnimation(self, targetMode: int | java.jint | java.lang.Integer, animators: java.util.List[android.animation.Animator], /) -> None: ...
    def getActionMenuViewTranslationX(self, actionMenuView: androidx.appcompat.widget.ActionMenuView, fabAlignmentMode: int | java.jint | java.lang.Integer, fabAttached: bool | java.jboolean | java.lang.Boolean, /) -> int: ...
    def getBackgroundTint(self) -> android.content.res.ColorStateList: ...
    def getBehavior(self) -> BottomAppBar.Behavior: ...
    def getCradleVerticalOffset(self) -> float: ...
    def getFabAlignmentMode(self) -> int: ...
    def getFabAlignmentModeEndMargin(self) -> int: ...
    def getFabAnchorMode(self) -> int: ...
    def getFabAnimationMode(self) -> int: ...
    def getFabCradleMargin(self) -> float: ...
    def getFabCradleRoundedCornerRadius(self) -> float: ...
    def getHideOnScroll(self) -> bool: ...
    def getMenuAlignmentMode(self) -> int: ...
    def isScrolledDown(self) -> bool: ...
    def isScrolledUp(self) -> bool: ...
    def onAttachedToWindow(self) -> None: ...
    def onLayout(self, changed: bool | java.jboolean | java.lang.Boolean, l: int | java.jint | java.lang.Integer, t: int | java.jint | java.lang.Integer, r: int | java.jint | java.lang.Integer, b: int | java.jint | java.lang.Integer, /) -> None: ...
    def onRestoreInstanceState(self, state: android.os.Parcelable, /) -> None: ...
    def onSaveInstanceState(self) -> android.os.Parcelable: ...
    @typing.overload
    def performHide(self) -> None: ...
    @typing.overload
    def performHide(self, animate: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def performShow(self) -> None: ...
    @typing.overload
    def performShow(self, animate: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def removeOnScrollStateChangedListener(self, listener: com.google.android.material.behavior.HideBottomViewOnScrollBehavior.OnScrollStateChangedListener, /) -> None: ...
    def replaceMenu(self, newMenu: int | java.jint | java.lang.Integer, /) -> None: ...
    def setBackgroundTint(self, backgroundTint: android.content.res.ColorStateList, /) -> None: ...
    def setCradleVerticalOffset(self, verticalOffset: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setElevation(self, elevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setFabAlignmentMode(self, fabAlignmentMode: int | java.jint | java.lang.Integer, /) -> None: ...
    def setFabAlignmentModeAndReplaceMenu(self, fabAlignmentMode: int | java.jint | java.lang.Integer, newMenu: int | java.jint | java.lang.Integer, /) -> None: ...
    def setFabAlignmentModeEndMargin(self, margin: int | java.jint | java.lang.Integer, /) -> None: ...
    def setFabAnchorMode(self, fabAnchorMode: int | java.jint | java.lang.Integer, /) -> None: ...
    def setFabAnimationMode(self, fabAnimationMode: int | java.jint | java.lang.Integer, /) -> None: ...
    def setFabCradleMargin(self, cradleMargin: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setFabCradleRoundedCornerRadius(self, roundedCornerRadius: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setHideOnScroll(self, hide: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setMenuAlignmentMode(self, menuAlignmentMode: int | java.jint | java.lang.Integer, /) -> None: ...
    def setNavigationIcon(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...
    def setNavigationIconTint(self, navigationIconTint: int | java.jint | java.lang.Integer, /) -> None: ...
    def setSubtitle(self, subtitle: java.lang.CharSequence, /) -> None: ...
    def setTitle(self, title: java.lang.CharSequence, /) -> None: ...

    class Behavior(com.google.android.material.behavior.HideBottomViewOnScrollBehavior[BottomAppBar]):
        @typing.overload
        def __init__(self) -> None: ...
        @typing.overload
        def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
        def onLayoutChild(self, parent: androidx.coordinatorlayout.widget.CoordinatorLayout, child: BottomAppBar, layoutDirection: int | java.jint | java.lang.Integer, /) -> bool: ...
        def onStartNestedScroll(self, coordinatorLayout: androidx.coordinatorlayout.widget.CoordinatorLayout, child: BottomAppBar, directTargetChild: android.view.View, target: android.view.View, axes: int | java.jint | java.lang.Integer, type: int | java.jint | java.lang.Integer, /) -> bool: ...

    class MenuAlignmentMode(java.lang.annotation.Annotation): ...

    class FabAnimationMode(java.lang.annotation.Annotation): ...

    class FabAnchorMode(java.lang.annotation.Annotation): ...

    class FabAlignmentMode(java.lang.annotation.Annotation): ...

class BottomAppBarTopEdgeTreatment(com.google.android.material.shape.EdgeTreatment, java.lang.Cloneable):
    def __init__(self, fabMargin: float | java.jfloat | java.lang.Float, roundedCornerRadius: float | java.jfloat | java.lang.Float, cradleVerticalOffset: float | java.jfloat | java.lang.Float, /) -> None: ...
    def getEdgePath(self, length: float | java.jfloat | java.lang.Float, center: float | java.jfloat | java.lang.Float, interpolation: float | java.jfloat | java.lang.Float, shapePath: com.google.android.material.shape.ShapePath, /) -> None: ...
    def getFabCornerRadius(self) -> float: ...
    def getFabDiameter(self) -> float: ...
    def getHorizontalOffset(self) -> float: ...
    def setFabCornerSize(self, size: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setFabDiameter(self, fabDiameter: float | java.jfloat | java.lang.Float, /) -> None: ...
