import typing

import android.animation
import android.content
import android.graphics
import android.graphics.drawable
import android.util
import android.view
import android.widget
import androidx.fragment.app
import java
import java.chaquopy
import java.lang
import java.lang.annotation
import java.util

class AnimatorUtils(java.lang.Object): ...

class ArcMotion(PathMotion):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    def getMaximumAngle(self) -> float: ...
    def getMinimumHorizontalAngle(self) -> float: ...
    def getMinimumVerticalAngle(self) -> float: ...
    def getPath(self, startX: float | java.jfloat | java.lang.Float, startY: float | java.jfloat | java.lang.Float, endX: float | java.jfloat | java.lang.Float, endY: float | java.jfloat | java.lang.Float, /) -> android.graphics.Path: ...
    def setMaximumAngle(self, angleInDegrees: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setMinimumHorizontalAngle(self, angleInDegrees: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setMinimumVerticalAngle(self, angleInDegrees: float | java.jfloat | java.lang.Float, /) -> None: ...

class AutoTransition(TransitionSet):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...

class CanvasUtils(java.lang.Object): ...

class ChangeBounds(Transition):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    def captureEndValues(self, transitionValues: TransitionValues, /) -> None: ...
    def captureStartValues(self, transitionValues: TransitionValues, /) -> None: ...
    def createAnimator(self, sceneRoot: android.view.ViewGroup, startValues: TransitionValues, endValues: TransitionValues, /) -> android.animation.Animator: ...
    def getResizeClip(self) -> bool: ...
    def getTransitionProperties(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    def setResizeClip(self, resizeClip: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class ChangeClipBounds(Transition):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    def captureEndValues(self, transitionValues: TransitionValues, /) -> None: ...
    def captureStartValues(self, transitionValues: TransitionValues, /) -> None: ...
    def createAnimator(self, sceneRoot: android.view.ViewGroup, startValues: TransitionValues, endValues: TransitionValues, /) -> android.animation.Animator: ...
    def getTransitionProperties(self) -> java.chaquopy.JavaArray[java.lang.String]: ...

class ChangeImageTransform(Transition):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    def captureEndValues(self, transitionValues: TransitionValues, /) -> None: ...
    def captureStartValues(self, transitionValues: TransitionValues, /) -> None: ...
    def createAnimator(self, sceneRoot: android.view.ViewGroup, startValues: TransitionValues, endValues: TransitionValues, /) -> android.animation.Animator: ...
    def getTransitionProperties(self) -> java.chaquopy.JavaArray[java.lang.String]: ...

class ChangeScroll(Transition):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    def captureEndValues(self, transitionValues: TransitionValues, /) -> None: ...
    def captureStartValues(self, transitionValues: TransitionValues, /) -> None: ...
    def createAnimator(self, sceneRoot: android.view.ViewGroup, startValues: TransitionValues, endValues: TransitionValues, /) -> android.animation.Animator: ...
    def getTransitionProperties(self) -> java.chaquopy.JavaArray[java.lang.String]: ...

class ChangeTransform(Transition):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    def captureEndValues(self, transitionValues: TransitionValues, /) -> None: ...
    def captureStartValues(self, transitionValues: TransitionValues, /) -> None: ...
    def createAnimator(self, sceneRoot: android.view.ViewGroup, startValues: TransitionValues, endValues: TransitionValues, /) -> android.animation.Animator: ...
    def getReparent(self) -> bool: ...
    def getReparentWithOverlay(self) -> bool: ...
    def getTransitionProperties(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    def setReparent(self, reparent: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setReparentWithOverlay(self, reparentWithOverlay: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class CircularPropagation(VisibilityPropagation):
    def __init__(self) -> None: ...
    def getStartDelay(self, sceneRoot: android.view.ViewGroup, transition: Transition, startValues: TransitionValues, endValues: TransitionValues, /) -> int: ...
    def setPropagationSpeed(self, propagationSpeed: float | java.jfloat | java.lang.Float, /) -> None: ...

class Explode(Visibility):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    def captureEndValues(self, transitionValues: TransitionValues, /) -> None: ...
    def captureStartValues(self, transitionValues: TransitionValues, /) -> None: ...
    def onAppear(self, sceneRoot: android.view.ViewGroup, view: android.view.View, startValues: TransitionValues, endValues: TransitionValues, /) -> android.animation.Animator: ...
    def onDisappear(self, sceneRoot: android.view.ViewGroup, view: android.view.View, startValues: TransitionValues, endValues: TransitionValues, /) -> android.animation.Animator: ...

class Fade(Visibility):
    IN: typing.ClassVar[int] = ...
    OUT: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, fadingMode: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    def captureStartValues(self, transitionValues: TransitionValues, /) -> None: ...
    def onAppear(self, sceneRoot: android.view.ViewGroup, view: android.view.View, startValues: TransitionValues, endValues: TransitionValues, /) -> android.animation.Animator: ...
    def onDisappear(self, sceneRoot: android.view.ViewGroup, view: android.view.View, startValues: TransitionValues, endValues: TransitionValues, /) -> android.animation.Animator: ...

class FloatArrayEvaluator(android.animation.TypeEvaluator[java.chaquopy.JavaArrayJFloat]):
    def evaluate(self, fraction: float | java.jfloat | java.lang.Float, startValue: java.chaquopy.JavaArrayJFloat, endValue: java.chaquopy.JavaArrayJFloat, /) -> java.chaquopy.JavaArrayJFloat: ...

class FragmentTransitionSupport(androidx.fragment.app.FragmentTransitionImpl):
    def __init__(self) -> None: ...
    def addTarget(self, transitionObj: java.lang.Object | int | bool | float | str, view: android.view.View, /) -> None: ...
    def addTargets(self, transitionObj: java.lang.Object | int | bool | float | str, views: java.util.ArrayList[android.view.View], /) -> None: ...
    def beginDelayedTransition(self, sceneRoot: android.view.ViewGroup, transition: java.lang.Object | int | bool | float | str, /) -> None: ...
    def canHandle(self, transition: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def cloneTransition(self, transition: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def mergeTransitionsInSequence(self, exitTransitionObj: java.lang.Object | int | bool | float | str, enterTransitionObj: java.lang.Object | int | bool | float | str, sharedElementTransitionObj: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def mergeTransitionsTogether(self, transition1: java.lang.Object | int | bool | float | str, transition2: java.lang.Object | int | bool | float | str, transition3: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def removeTarget(self, transitionObj: java.lang.Object | int | bool | float | str, view: android.view.View, /) -> None: ...
    def replaceTargets(self, transitionObj: java.lang.Object | int | bool | float | str, oldTargets: java.util.ArrayList[android.view.View], newTargets: java.util.ArrayList[android.view.View], /) -> None: ...
    def scheduleHideFragmentView(self, exitTransitionObj: java.lang.Object | int | bool | float | str, fragmentView: android.view.View, exitingViews: java.util.ArrayList[android.view.View], /) -> None: ...
    def scheduleRemoveTargets(self, overallTransitionObj: java.lang.Object | int | bool | float | str, enterTransition: java.lang.Object | int | bool | float | str, enteringViews: java.util.ArrayList[android.view.View], exitTransition: java.lang.Object | int | bool | float | str, exitingViews: java.util.ArrayList[android.view.View], sharedElementTransition: java.lang.Object | int | bool | float | str, sharedElementsIn: java.util.ArrayList[android.view.View], /) -> None: ...
    @typing.overload
    def setEpicenter(self, transitionObj: java.lang.Object | int | bool | float | str, epicenter: android.graphics.Rect, /) -> None: ...
    @typing.overload
    def setEpicenter(self, transitionObj: java.lang.Object | int | bool | float | str, view: android.view.View, /) -> None: ...
    def setSharedElementTargets(self, transitionObj: java.lang.Object | int | bool | float | str, nonExistentView: android.view.View, sharedViews: java.util.ArrayList[android.view.View], /) -> None: ...
    def swapSharedElementTargets(self, sharedElementTransitionObj: java.lang.Object | int | bool | float | str, sharedElementsOut: java.util.ArrayList[android.view.View], sharedElementsIn: java.util.ArrayList[android.view.View], /) -> None: ...
    def wrapTransitionInSet(self, transition: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...

class GhostView(java.lang.Object):
    def reserveEndViewTransition(self, arg1: android.view.ViewGroup, arg2: android.view.View, /) -> None: ...
    def setVisibility(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...

class GhostViewHolder(android.widget.FrameLayout):
    def onViewAdded(self, child: android.view.View, /) -> None: ...
    def onViewRemoved(self, child: android.view.View, /) -> None: ...

class GhostViewPlatform(GhostView):
    def reserveEndViewTransition(self, viewGroup: android.view.ViewGroup, view: android.view.View, /) -> None: ...
    def setVisibility(self, visibility: int | java.jint | java.lang.Integer, /) -> None: ...

class GhostViewPort(android.view.ViewGroup, GhostView):
    def onAttachedToWindow(self) -> None: ...
    def onDetachedFromWindow(self) -> None: ...
    def onDraw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def onLayout(self, changed: bool | java.jboolean | java.lang.Boolean, l: int | java.jint | java.lang.Integer, t: int | java.jint | java.lang.Integer, r: int | java.jint | java.lang.Integer, b: int | java.jint | java.lang.Integer, /) -> None: ...
    def reserveEndViewTransition(self, viewGroup: android.view.ViewGroup, view: android.view.View, /) -> None: ...
    def setVisibility(self, visibility: int | java.jint | java.lang.Integer, /) -> None: ...

class GhostViewUtils(java.lang.Object): ...

class ImageViewUtils(java.lang.Object): ...

class MatrixUtils(java.lang.Object): ...

class ObjectAnimatorUtils(java.lang.Object): ...

class PathMotion(java.lang.Object):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    def getPath(self, arg1: float | java.jfloat | java.lang.Float, arg2: float | java.jfloat | java.lang.Float, arg3: float | java.jfloat | java.lang.Float, arg4: float | java.jfloat | java.lang.Float, /) -> android.graphics.Path: ...

_PathProperty__T = typing.TypeVar('_PathProperty__T')  # <T>
class PathProperty(android.util.Property[_PathProperty__T, java.lang.Float], typing.Generic[_PathProperty__T]):
    def get(self, object: _PathProperty__T, /) -> float: ...
    def set(self, target: _PathProperty__T, fraction: float | java.jfloat | java.lang.Float, /) -> None: ...

class PatternPathMotion(PathMotion):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, patternPath: android.graphics.Path, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    def getPath(self, startX: float | java.jfloat | java.lang.Float, startY: float | java.jfloat | java.lang.Float, endX: float | java.jfloat | java.lang.Float, endY: float | java.jfloat | java.lang.Float, /) -> android.graphics.Path: ...
    def getPatternPath(self) -> android.graphics.Path: ...
    def setPatternPath(self, patternPath: android.graphics.Path, /) -> None: ...

class PropertyValuesHolderUtils(java.lang.Object): ...

class RectEvaluator(android.animation.TypeEvaluator[android.graphics.Rect]):
    def evaluate(self, fraction: float | java.jfloat | java.lang.Float, startValue: android.graphics.Rect, endValue: android.graphics.Rect, /) -> android.graphics.Rect: ...

class Scene(java.lang.Object):
    @typing.overload
    def __init__(self, sceneRoot: android.view.ViewGroup, /) -> None: ...
    @typing.overload
    def __init__(self, sceneRoot: android.view.ViewGroup, layout: android.view.View, /) -> None: ...
    def enter(self) -> None: ...
    def exit(self) -> None: ...
    @staticmethod
    def getCurrentScene(sceneRoot: android.view.ViewGroup, /) -> Scene: ...
    @staticmethod
    def getSceneForLayout(sceneRoot: android.view.ViewGroup, layoutId: int | java.jint | java.lang.Integer, context: android.content.Context, /) -> Scene: ...
    def getSceneRoot(self) -> android.view.ViewGroup: ...
    def setEnterAction(self, action: java.lang.Runnable, /) -> None: ...
    def setExitAction(self, action: java.lang.Runnable, /) -> None: ...

class SidePropagation(VisibilityPropagation):
    def __init__(self) -> None: ...
    def getStartDelay(self, sceneRoot: android.view.ViewGroup, transition: Transition, startValues: TransitionValues, endValues: TransitionValues, /) -> int: ...
    def setPropagationSpeed(self, propagationSpeed: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setSide(self, side: int | java.jint | java.lang.Integer, /) -> None: ...

class Slide(Visibility):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, slideEdge: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    def captureEndValues(self, transitionValues: TransitionValues, /) -> None: ...
    def captureStartValues(self, transitionValues: TransitionValues, /) -> None: ...
    def getSlideEdge(self) -> int: ...
    def onAppear(self, sceneRoot: android.view.ViewGroup, view: android.view.View, startValues: TransitionValues, endValues: TransitionValues, /) -> android.animation.Animator: ...
    def onDisappear(self, sceneRoot: android.view.ViewGroup, view: android.view.View, startValues: TransitionValues, endValues: TransitionValues, /) -> android.animation.Animator: ...
    def setSlideEdge(self, slideEdge: int | java.jint | java.lang.Integer, /) -> None: ...

    class GravityFlag(java.lang.annotation.Annotation): ...

class Styleable(java.lang.Object): ...

class Transition(java.lang.Cloneable):
    MATCH_INSTANCE: typing.ClassVar[int] = ...
    MATCH_NAME: typing.ClassVar[int] = ...
    MATCH_ID: typing.ClassVar[int] = ...
    MATCH_ITEM_ID: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    def addListener(self, listener: Transition.TransitionListener, /) -> Transition: ...
    @typing.overload
    def addTarget(self, targetId: int | java.jint | java.lang.Integer, /) -> Transition: ...
    @typing.overload
    def addTarget(self, target: android.view.View, /) -> Transition: ...
    @typing.overload
    def addTarget(self, targetType: typing.Type[java.lang.Object], /) -> Transition: ...
    @typing.overload
    def addTarget(self, targetName: str | java.lang.String, /) -> Transition: ...
    def animate(self, animator: android.animation.Animator, /) -> None: ...
    def cancel(self) -> None: ...
    def captureEndValues(self, arg1: TransitionValues, /) -> None: ...
    def captureStartValues(self, arg1: TransitionValues, /) -> None: ...
    def clone(self) -> Transition: ...
    def createAnimator(self, sceneRoot: android.view.ViewGroup, startValues: TransitionValues, endValues: TransitionValues, /) -> android.animation.Animator: ...
    def createAnimators(self, sceneRoot: android.view.ViewGroup, startValues: TransitionValuesMaps, endValues: TransitionValuesMaps, startValuesList: java.util.ArrayList[TransitionValues], endValuesList: java.util.ArrayList[TransitionValues], /) -> None: ...
    def end(self) -> None: ...
    @typing.overload
    def excludeChildren(self, targetId: int | java.jint | java.lang.Integer, exclude: bool | java.jboolean | java.lang.Boolean, /) -> Transition: ...
    @typing.overload
    def excludeChildren(self, target: android.view.View, exclude: bool | java.jboolean | java.lang.Boolean, /) -> Transition: ...
    @typing.overload
    def excludeChildren(self, type: typing.Type[java.lang.Object], exclude: bool | java.jboolean | java.lang.Boolean, /) -> Transition: ...
    @typing.overload
    def excludeTarget(self, targetId: int | java.jint | java.lang.Integer, exclude: bool | java.jboolean | java.lang.Boolean, /) -> Transition: ...
    @typing.overload
    def excludeTarget(self, target: android.view.View, exclude: bool | java.jboolean | java.lang.Boolean, /) -> Transition: ...
    @typing.overload
    def excludeTarget(self, type: typing.Type[java.lang.Object], exclude: bool | java.jboolean | java.lang.Boolean, /) -> Transition: ...
    @typing.overload
    def excludeTarget(self, targetName: str | java.lang.String, exclude: bool | java.jboolean | java.lang.Boolean, /) -> Transition: ...
    def getDuration(self) -> int: ...
    def getEpicenter(self) -> android.graphics.Rect: ...
    def getEpicenterCallback(self) -> Transition.EpicenterCallback: ...
    def getInterpolator(self) -> android.animation.TimeInterpolator: ...
    def getName(self) -> str: ...
    def getPathMotion(self) -> PathMotion: ...
    def getPropagation(self) -> TransitionPropagation: ...
    def getStartDelay(self) -> int: ...
    def getTargetIds(self) -> java.util.List[java.lang.Integer]: ...
    def getTargetNames(self) -> java.util.List[java.lang.String]: ...
    def getTargetTypes(self) -> java.util.List[typing.Type[java.lang.Object]]: ...
    def getTargets(self) -> java.util.List[android.view.View]: ...
    def getTransitionProperties(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    def getTransitionValues(self, view: android.view.View, start: bool | java.jboolean | java.lang.Boolean, /) -> TransitionValues: ...
    def isTransitionRequired(self, startValues: TransitionValues, endValues: TransitionValues, /) -> bool: ...
    def pause(self, sceneRoot: android.view.View, /) -> None: ...
    def removeListener(self, listener: Transition.TransitionListener, /) -> Transition: ...
    @typing.overload
    def removeTarget(self, targetId: int | java.jint | java.lang.Integer, /) -> Transition: ...
    @typing.overload
    def removeTarget(self, target: android.view.View, /) -> Transition: ...
    @typing.overload
    def removeTarget(self, target: typing.Type[java.lang.Object], /) -> Transition: ...
    @typing.overload
    def removeTarget(self, targetName: str | java.lang.String, /) -> Transition: ...
    def resume(self, sceneRoot: android.view.View, /) -> None: ...
    def runAnimators(self) -> None: ...
    def setDuration(self, duration: int | java.jlong | java.lang.Long, /) -> Transition: ...
    def setEpicenterCallback(self, epicenterCallback: Transition.EpicenterCallback, /) -> None: ...
    def setInterpolator(self, interpolator: android.animation.TimeInterpolator, /) -> Transition: ...
    def setMatchOrder(self, *matches: java.jint) -> None: ...
    def setPathMotion(self, pathMotion: PathMotion, /) -> None: ...
    def setPropagation(self, transitionPropagation: TransitionPropagation, /) -> None: ...
    def setStartDelay(self, startDelay: int | java.jlong | java.lang.Long, /) -> Transition: ...
    def start(self) -> None: ...
    def toString(self) -> str: ...

    class EpicenterCallback(java.lang.Object):
        def __init__(self) -> None: ...
        def onGetEpicenter(self, arg1: Transition, /) -> android.graphics.Rect: ...

    class TransitionListener(java.lang.Object):
        def onTransitionCancel(self, arg1: Transition, /) -> None: ...
        def onTransitionEnd(self, arg1: Transition, /) -> None: ...
        def onTransitionPause(self, arg1: Transition, /) -> None: ...
        def onTransitionResume(self, arg1: Transition, /) -> None: ...
        def onTransitionStart(self, arg1: Transition, /) -> None: ...

    class MatchOrder(java.lang.annotation.Annotation): ...

class TransitionInflater(java.lang.Object):
    @staticmethod
    def from_(context: android.content.Context, /) -> TransitionInflater: ...
    def inflateTransition(self, resource: int | java.jint | java.lang.Integer, /) -> Transition: ...
    def inflateTransitionManager(self, resource: int | java.jint | java.lang.Integer, sceneRoot: android.view.ViewGroup, /) -> TransitionManager: ...

class TransitionListenerAdapter(Transition.TransitionListener):
    def __init__(self) -> None: ...
    def onTransitionCancel(self, transition: Transition, /) -> None: ...
    def onTransitionEnd(self, transition: Transition, /) -> None: ...
    def onTransitionPause(self, transition: Transition, /) -> None: ...
    def onTransitionResume(self, transition: Transition, /) -> None: ...
    def onTransitionStart(self, transition: Transition, /) -> None: ...

class TransitionManager(java.lang.Object):
    def __init__(self) -> None: ...
    @typing.overload
    @staticmethod
    def beginDelayedTransition(sceneRoot: android.view.ViewGroup, /) -> None: ...
    @typing.overload
    @staticmethod
    def beginDelayedTransition(sceneRoot: android.view.ViewGroup, transition: Transition, /) -> None: ...
    @staticmethod
    def endTransitions(sceneRoot: android.view.ViewGroup, /) -> None: ...
    @typing.overload
    @staticmethod
    def go(scene: Scene, /) -> None: ...
    @typing.overload
    @staticmethod
    def go(scene: Scene, transition: Transition, /) -> None: ...
    @typing.overload
    def setTransition(self, scene: Scene, transition: Transition, /) -> None: ...
    @typing.overload
    def setTransition(self, fromScene: Scene, toScene: Scene, transition: Transition, /) -> None: ...
    def transitionTo(self, scene: Scene, /) -> None: ...

class TransitionPropagation(java.lang.Object):
    def __init__(self) -> None: ...
    def captureValues(self, arg1: TransitionValues, /) -> None: ...
    def getPropagationProperties(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    def getStartDelay(self, arg1: android.view.ViewGroup, arg2: Transition, arg3: TransitionValues, arg4: TransitionValues, /) -> int: ...

class TransitionSet(Transition):
    ORDERING_TOGETHER: typing.ClassVar[int] = ...
    ORDERING_SEQUENTIAL: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    def addListener(self, listener: Transition.TransitionListener, /) -> TransitionSet: ...
    @typing.overload
    def addTarget(self, targetId: int | java.jint | java.lang.Integer, /) -> TransitionSet: ...
    @typing.overload
    def addTarget(self, target: android.view.View, /) -> TransitionSet: ...
    @typing.overload
    def addTarget(self, targetType: typing.Type[java.lang.Object], /) -> TransitionSet: ...
    @typing.overload
    def addTarget(self, targetName: str | java.lang.String, /) -> TransitionSet: ...
    def addTransition(self, transition: Transition, /) -> TransitionSet: ...
    def cancel(self) -> None: ...
    def captureEndValues(self, transitionValues: TransitionValues, /) -> None: ...
    def captureStartValues(self, transitionValues: TransitionValues, /) -> None: ...
    def clone(self) -> Transition: ...
    def createAnimators(self, sceneRoot: android.view.ViewGroup, startValues: TransitionValuesMaps, endValues: TransitionValuesMaps, startValuesList: java.util.ArrayList[TransitionValues], endValuesList: java.util.ArrayList[TransitionValues], /) -> None: ...
    @typing.overload
    def excludeTarget(self, targetId: int | java.jint | java.lang.Integer, exclude: bool | java.jboolean | java.lang.Boolean, /) -> Transition: ...
    @typing.overload
    def excludeTarget(self, target: android.view.View, exclude: bool | java.jboolean | java.lang.Boolean, /) -> Transition: ...
    @typing.overload
    def excludeTarget(self, type: typing.Type[java.lang.Object], exclude: bool | java.jboolean | java.lang.Boolean, /) -> Transition: ...
    @typing.overload
    def excludeTarget(self, targetName: str | java.lang.String, exclude: bool | java.jboolean | java.lang.Boolean, /) -> Transition: ...
    def getOrdering(self) -> int: ...
    def getTransitionAt(self, index: int | java.jint | java.lang.Integer, /) -> Transition: ...
    def getTransitionCount(self) -> int: ...
    def pause(self, sceneRoot: android.view.View, /) -> None: ...
    def removeListener(self, listener: Transition.TransitionListener, /) -> TransitionSet: ...
    @typing.overload
    def removeTarget(self, targetId: int | java.jint | java.lang.Integer, /) -> TransitionSet: ...
    @typing.overload
    def removeTarget(self, target: android.view.View, /) -> TransitionSet: ...
    @typing.overload
    def removeTarget(self, target: typing.Type[java.lang.Object], /) -> TransitionSet: ...
    @typing.overload
    def removeTarget(self, target: str | java.lang.String, /) -> TransitionSet: ...
    def removeTransition(self, transition: Transition, /) -> TransitionSet: ...
    def resume(self, sceneRoot: android.view.View, /) -> None: ...
    def runAnimators(self) -> None: ...
    def setDuration(self, duration: int | java.jlong | java.lang.Long, /) -> TransitionSet: ...
    def setEpicenterCallback(self, epicenterCallback: Transition.EpicenterCallback, /) -> None: ...
    def setInterpolator(self, interpolator: android.animation.TimeInterpolator, /) -> TransitionSet: ...
    def setOrdering(self, ordering: int | java.jint | java.lang.Integer, /) -> TransitionSet: ...
    def setPathMotion(self, pathMotion: PathMotion, /) -> None: ...
    def setPropagation(self, propagation: TransitionPropagation, /) -> None: ...
    def setStartDelay(self, startDelay: int | java.jlong | java.lang.Long, /) -> TransitionSet: ...

class TransitionUtils(java.lang.Object): ...

class TransitionValues(java.lang.Object):
    values: java.util.Map[java.lang.String, java.lang.Object] = ...
    view: android.view.View = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, view: android.view.View, /) -> None: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class TransitionValuesMaps(java.lang.Object): ...

class TranslationAnimationCreator(java.lang.Object): ...

class ViewGroupOverlayApi14(ViewOverlayApi14, ViewGroupOverlayImpl):
    def add(self, view: android.view.View, /) -> None: ...
    def remove(self, view: android.view.View, /) -> None: ...

class ViewGroupOverlayApi18(ViewGroupOverlayImpl):
    @typing.overload
    def add(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...
    @typing.overload
    def add(self, view: android.view.View, /) -> None: ...
    @typing.overload
    def remove(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...
    @typing.overload
    def remove(self, view: android.view.View, /) -> None: ...

class ViewGroupOverlayImpl(ViewOverlayImpl):
    def add(self, arg1: android.view.View, /) -> None: ...
    def remove(self, arg1: android.view.View, /) -> None: ...

class ViewGroupUtils(java.lang.Object): ...

class ViewGroupUtilsApi14(java.lang.Object): ...

class ViewOverlayApi14(ViewOverlayImpl):
    mOverlayViewGroup: ViewOverlayApi14.OverlayViewGroup = ...
    def add(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...
    def remove(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...

class ViewOverlayApi18(ViewOverlayImpl):
    def add(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...
    def remove(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...

class ViewOverlayImpl(java.lang.Object):
    def add(self, arg1: android.graphics.drawable.Drawable, /) -> None: ...
    def remove(self, arg1: android.graphics.drawable.Drawable, /) -> None: ...

class ViewUtils(java.lang.Object): ...

class ViewUtilsApi19(ViewUtilsBase):
    def clearNonTransitionAlpha(self, view: android.view.View, /) -> None: ...
    def getTransitionAlpha(self, view: android.view.View, /) -> float: ...
    def saveNonTransitionAlpha(self, view: android.view.View, /) -> None: ...
    def setTransitionAlpha(self, view: android.view.View, alpha: float | java.jfloat | java.lang.Float, /) -> None: ...

class ViewUtilsApi21(ViewUtilsApi19):
    def setAnimationMatrix(self, view: android.view.View, matrix: android.graphics.Matrix, /) -> None: ...
    def transformMatrixToGlobal(self, view: android.view.View, matrix: android.graphics.Matrix, /) -> None: ...
    def transformMatrixToLocal(self, view: android.view.View, matrix: android.graphics.Matrix, /) -> None: ...

class ViewUtilsApi22(ViewUtilsApi21):
    def setLeftTopRightBottom(self, v: android.view.View, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...

class ViewUtilsApi23(ViewUtilsApi22):
    def setTransitionVisibility(self, view: android.view.View, visibility: int | java.jint | java.lang.Integer, /) -> None: ...

class ViewUtilsApi29(ViewUtilsApi23):
    def getTransitionAlpha(self, view: android.view.View, /) -> float: ...
    def setAnimationMatrix(self, view: android.view.View, matrix: android.graphics.Matrix, /) -> None: ...
    def setLeftTopRightBottom(self, v: android.view.View, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTransitionAlpha(self, view: android.view.View, alpha: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTransitionVisibility(self, view: android.view.View, visibility: int | java.jint | java.lang.Integer, /) -> None: ...
    def transformMatrixToGlobal(self, view: android.view.View, matrix: android.graphics.Matrix, /) -> None: ...
    def transformMatrixToLocal(self, view: android.view.View, matrix: android.graphics.Matrix, /) -> None: ...

class ViewUtilsBase(java.lang.Object):
    def clearNonTransitionAlpha(self, view: android.view.View, /) -> None: ...
    def getTransitionAlpha(self, view: android.view.View, /) -> float: ...
    def saveNonTransitionAlpha(self, view: android.view.View, /) -> None: ...
    def setAnimationMatrix(self, view: android.view.View, matrix: android.graphics.Matrix, /) -> None: ...
    def setLeftTopRightBottom(self, v: android.view.View, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTransitionAlpha(self, view: android.view.View, alpha: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTransitionVisibility(self, view: android.view.View, visibility: int | java.jint | java.lang.Integer, /) -> None: ...
    def transformMatrixToGlobal(self, view: android.view.View, matrix: android.graphics.Matrix, /) -> None: ...
    def transformMatrixToLocal(self, view: android.view.View, matrix: android.graphics.Matrix, /) -> None: ...

class Visibility(Transition):
    MODE_IN: typing.ClassVar[int] = ...
    MODE_OUT: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    def captureEndValues(self, transitionValues: TransitionValues, /) -> None: ...
    def captureStartValues(self, transitionValues: TransitionValues, /) -> None: ...
    def createAnimator(self, sceneRoot: android.view.ViewGroup, startValues: TransitionValues, endValues: TransitionValues, /) -> android.animation.Animator: ...
    def getMode(self) -> int: ...
    def getTransitionProperties(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    def isTransitionRequired(self, startValues: TransitionValues, newValues: TransitionValues, /) -> bool: ...
    def isVisible(self, values: TransitionValues, /) -> bool: ...
    @typing.overload
    def onAppear(self, sceneRoot: android.view.ViewGroup, view: android.view.View, startValues: TransitionValues, endValues: TransitionValues, /) -> android.animation.Animator: ...
    @typing.overload
    def onAppear(self, sceneRoot: android.view.ViewGroup, startValues: TransitionValues, startVisibility: int | java.jint | java.lang.Integer, endValues: TransitionValues, endVisibility: int | java.jint | java.lang.Integer, /) -> android.animation.Animator: ...
    @typing.overload
    def onDisappear(self, sceneRoot: android.view.ViewGroup, view: android.view.View, startValues: TransitionValues, endValues: TransitionValues, /) -> android.animation.Animator: ...
    @typing.overload
    def onDisappear(self, sceneRoot: android.view.ViewGroup, startValues: TransitionValues, startVisibility: int | java.jint | java.lang.Integer, endValues: TransitionValues, endVisibility: int | java.jint | java.lang.Integer, /) -> android.animation.Animator: ...
    def setMode(self, mode: int | java.jint | java.lang.Integer, /) -> None: ...

    class Mode(java.lang.annotation.Annotation): ...

class VisibilityPropagation(TransitionPropagation):
    def __init__(self) -> None: ...
    def captureValues(self, values: TransitionValues, /) -> None: ...
    def getPropagationProperties(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    def getViewVisibility(self, values: TransitionValues, /) -> int: ...
    def getViewX(self, values: TransitionValues, /) -> int: ...
    def getViewY(self, values: TransitionValues, /) -> int: ...

class WindowIdApi14(WindowIdImpl):
    def equals(self, o: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def hashCode(self) -> int: ...

class WindowIdApi18(WindowIdImpl):
    def equals(self, o: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def hashCode(self) -> int: ...

class WindowIdImpl(java.lang.Object): ...
