import typing

import java
import java.lang

class MathKt(java.lang.Object):
    PI: typing.ClassVar[float] = ...
    E: typing.ClassVar[float] = ...
    @staticmethod
    def acosh(x: float | java.jdouble | java.lang.Double, /) -> float: ...
    @staticmethod
    def asinh(x: float | java.jdouble | java.lang.Double, /) -> float: ...
    @staticmethod
    def atanh(x: float | java.jdouble | java.lang.Double, /) -> float: ...
    @typing.overload
    @staticmethod
    def getSign(receiver: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getSign(receiver: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def log(x: float | java.jdouble | java.lang.Double, base: float | java.jdouble | java.lang.Double, /) -> float: ...
    @typing.overload
    @staticmethod
    def log(x: float | java.jfloat | java.lang.Float, base: float | java.jfloat | java.lang.Float, /) -> float: ...
    @typing.overload
    @staticmethod
    def log2(x: float | java.jdouble | java.lang.Double, /) -> float: ...
    @typing.overload
    @staticmethod
    def log2(x: float | java.jfloat | java.lang.Float, /) -> float: ...
    @typing.overload
    @staticmethod
    def roundToInt(receiver: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def roundToInt(receiver: float | java.jfloat | java.lang.Float, /) -> int: ...
    @typing.overload
    @staticmethod
    def roundToLong(receiver: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def roundToLong(receiver: float | java.jfloat | java.lang.Float, /) -> int: ...
    @typing.overload
    @staticmethod
    def truncate(x: float | java.jdouble | java.lang.Double, /) -> float: ...
    @typing.overload
    @staticmethod
    def truncate(x: float | java.jfloat | java.lang.Float, /) -> float: ...
