import typing

import android.net
import android.os
import android.webkit
import androidx.webkit
import java
import java.chaquopy
import java.lang
import java.lang.reflect
import org.chromium.support_lib_boundary

class FrameworkServiceWorkerClient(android.webkit.ServiceWorkerClient):
    def __init__(self, impl: androidx.webkit.ServiceWorkerClientCompat, /) -> None: ...
    def shouldInterceptRequest(self, request: android.webkit.WebResourceRequest, /) -> android.webkit.WebResourceResponse: ...

class IncompatibleApkWebViewProviderFactory(WebViewProviderFactory):
    def __init__(self) -> None: ...
    def createWebView(self, webview: android.webkit.WebView, /) -> org.chromium.support_lib_boundary.WebViewProviderBoundaryInterface: ...
    def getServiceWorkerController(self) -> org.chromium.support_lib_boundary.ServiceWorkerControllerBoundaryInterface: ...
    def getStatics(self) -> org.chromium.support_lib_boundary.StaticsBoundaryInterface: ...
    def getWebViewFeatures(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    def getWebkitToCompatConverter(self) -> org.chromium.support_lib_boundary.WebkitToCompatConverterBoundaryInterface: ...

class SafeBrowsingResponseImpl(androidx.webkit.SafeBrowsingResponseCompat):
    @typing.overload
    def __init__(self, response: android.webkit.SafeBrowsingResponse, /) -> None: ...
    @typing.overload
    def __init__(self, invocationHandler: java.lang.reflect.InvocationHandler, /) -> None: ...
    def backToSafety(self, report: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def proceed(self, report: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def showInterstitial(self, allowReporting: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class ServiceWorkerClientAdapter(org.chromium.support_lib_boundary.ServiceWorkerClientBoundaryInterface):
    def __init__(self, client: androidx.webkit.ServiceWorkerClientCompat, /) -> None: ...
    def getSupportedFeatures(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    def shouldInterceptRequest(self, request: android.webkit.WebResourceRequest, /) -> android.webkit.WebResourceResponse: ...

class ServiceWorkerControllerImpl(androidx.webkit.ServiceWorkerControllerCompat):
    def __init__(self) -> None: ...
    def getServiceWorkerWebSettings(self) -> androidx.webkit.ServiceWorkerWebSettingsCompat: ...
    def setServiceWorkerClient(self, client: androidx.webkit.ServiceWorkerClientCompat, /) -> None: ...

class ServiceWorkerWebSettingsImpl(androidx.webkit.ServiceWorkerWebSettingsCompat):
    @typing.overload
    def __init__(self, settings: android.webkit.ServiceWorkerWebSettings, /) -> None: ...
    @typing.overload
    def __init__(self, invocationHandler: java.lang.reflect.InvocationHandler, /) -> None: ...
    def getAllowContentAccess(self) -> bool: ...
    def getAllowFileAccess(self) -> bool: ...
    def getBlockNetworkLoads(self) -> bool: ...
    def getCacheMode(self) -> int: ...
    def setAllowContentAccess(self, allow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setAllowFileAccess(self, allow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setBlockNetworkLoads(self, flag: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setCacheMode(self, mode: int | java.jint | java.lang.Integer, /) -> None: ...

class VisualStateCallbackAdapter(org.chromium.support_lib_boundary.VisualStateCallbackBoundaryInterface):
    def __init__(self, visualStateCallback: androidx.webkit.WebViewCompat.VisualStateCallback, /) -> None: ...
    def onComplete(self, requestId: int | java.jlong | java.lang.Long, /) -> None: ...

class WebMessageAdapter(org.chromium.support_lib_boundary.WebMessageBoundaryInterface):
    def getData(self) -> str: ...
    def getPorts(self) -> java.chaquopy.JavaArray[java.lang.reflect.InvocationHandler]: ...
    def getSupportedFeatures(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    @staticmethod
    def webMessageCompatFromBoundaryInterface(boundaryInterface: org.chromium.support_lib_boundary.WebMessageBoundaryInterface, /) -> androidx.webkit.WebMessageCompat: ...

class WebMessageCallbackAdapter(org.chromium.support_lib_boundary.WebMessageCallbackBoundaryInterface):
    def getSupportedFeatures(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    def onMessage(self, port: java.lang.reflect.InvocationHandler, message: java.lang.reflect.InvocationHandler, /) -> None: ...

class WebMessagePortImpl(androidx.webkit.WebMessagePortCompat):
    @typing.overload
    def __init__(self, frameworksImpl: android.webkit.WebMessagePort, /) -> None: ...
    @typing.overload
    def __init__(self, invocationHandler: java.lang.reflect.InvocationHandler, /) -> None: ...
    def close(self) -> None: ...
    @staticmethod
    def compatToFrameworkMessage(message: androidx.webkit.WebMessageCompat, /) -> android.webkit.WebMessage: ...
    @staticmethod
    def compatToPorts(compatPorts: java.chaquopy.JavaArray[androidx.webkit.WebMessagePortCompat], /) -> java.chaquopy.JavaArray[android.webkit.WebMessagePort]: ...
    @staticmethod
    def frameworkMessageToCompat(message: android.webkit.WebMessage, /) -> androidx.webkit.WebMessageCompat: ...
    def getFrameworkPort(self) -> android.webkit.WebMessagePort: ...
    def getInvocationHandler(self) -> java.lang.reflect.InvocationHandler: ...
    @staticmethod
    def portsToCompat(ports: java.chaquopy.JavaArray[android.webkit.WebMessagePort], /) -> java.chaquopy.JavaArray[androidx.webkit.WebMessagePortCompat]: ...
    def postMessage(self, message: androidx.webkit.WebMessageCompat, /) -> None: ...
    @typing.overload
    def setWebMessageCallback(self, callback: androidx.webkit.WebMessagePortCompat.WebMessageCallbackCompat, /) -> None: ...
    @typing.overload
    def setWebMessageCallback(self, handler: android.os.Handler, callback: androidx.webkit.WebMessagePortCompat.WebMessageCallbackCompat, /) -> None: ...

class WebResourceErrorImpl(androidx.webkit.WebResourceErrorCompat):
    @typing.overload
    def __init__(self, error: android.webkit.WebResourceError, /) -> None: ...
    @typing.overload
    def __init__(self, invocationHandler: java.lang.reflect.InvocationHandler, /) -> None: ...
    def getDescription(self) -> java.lang.CharSequence: ...
    def getErrorCode(self) -> int: ...

class WebResourceRequestAdapter(java.lang.Object):
    def __init__(self, boundaryInterface: org.chromium.support_lib_boundary.WebResourceRequestBoundaryInterface, /) -> None: ...
    def isRedirect(self) -> bool: ...

class WebSettingsAdapter(java.lang.Object):
    def __init__(self, boundaryInterface: org.chromium.support_lib_boundary.WebSettingsBoundaryInterface, /) -> None: ...
    def getDisabledActionModeMenuItems(self) -> int: ...
    def getOffscreenPreRaster(self) -> bool: ...
    def getSafeBrowsingEnabled(self) -> bool: ...
    def setDisabledActionModeMenuItems(self, menuItems: int | java.jint | java.lang.Integer, /) -> None: ...
    def setOffscreenPreRaster(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setSafeBrowsingEnabled(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class WebViewFeatureInternal(java.lang.Enum[WebViewFeatureInternal]):
    VISUAL_STATE_CALLBACK_FEATURE: typing.ClassVar[WebViewFeatureInternal] = ...
    OFF_SCREEN_PRERASTER: typing.ClassVar[WebViewFeatureInternal] = ...
    SAFE_BROWSING_ENABLE: typing.ClassVar[WebViewFeatureInternal] = ...
    DISABLED_ACTION_MODE_MENU_ITEMS: typing.ClassVar[WebViewFeatureInternal] = ...
    START_SAFE_BROWSING: typing.ClassVar[WebViewFeatureInternal] = ...
    SAFE_BROWSING_WHITELIST: typing.ClassVar[WebViewFeatureInternal] = ...
    SAFE_BROWSING_PRIVACY_POLICY_URL: typing.ClassVar[WebViewFeatureInternal] = ...
    SERVICE_WORKER_BASIC_USAGE: typing.ClassVar[WebViewFeatureInternal] = ...
    SERVICE_WORKER_CACHE_MODE: typing.ClassVar[WebViewFeatureInternal] = ...
    SERVICE_WORKER_CONTENT_ACCESS: typing.ClassVar[WebViewFeatureInternal] = ...
    SERVICE_WORKER_FILE_ACCESS: typing.ClassVar[WebViewFeatureInternal] = ...
    SERVICE_WORKER_BLOCK_NETWORK_LOADS: typing.ClassVar[WebViewFeatureInternal] = ...
    SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST: typing.ClassVar[WebViewFeatureInternal] = ...
    RECEIVE_WEB_RESOURCE_ERROR: typing.ClassVar[WebViewFeatureInternal] = ...
    RECEIVE_HTTP_ERROR: typing.ClassVar[WebViewFeatureInternal] = ...
    SHOULD_OVERRIDE_WITH_REDIRECTS: typing.ClassVar[WebViewFeatureInternal] = ...
    SAFE_BROWSING_HIT: typing.ClassVar[WebViewFeatureInternal] = ...
    WEB_RESOURCE_REQUEST_IS_REDIRECT: typing.ClassVar[WebViewFeatureInternal] = ...
    WEB_RESOURCE_ERROR_GET_DESCRIPTION: typing.ClassVar[WebViewFeatureInternal] = ...
    WEB_RESOURCE_ERROR_GET_CODE: typing.ClassVar[WebViewFeatureInternal] = ...
    SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY: typing.ClassVar[WebViewFeatureInternal] = ...
    SAFE_BROWSING_RESPONSE_PROCEED: typing.ClassVar[WebViewFeatureInternal] = ...
    SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL: typing.ClassVar[WebViewFeatureInternal] = ...
    WEB_MESSAGE_PORT_POST_MESSAGE: typing.ClassVar[WebViewFeatureInternal] = ...
    WEB_MESSAGE_PORT_CLOSE: typing.ClassVar[WebViewFeatureInternal] = ...
    WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK: typing.ClassVar[WebViewFeatureInternal] = ...
    CREATE_WEB_MESSAGE_CHANNEL: typing.ClassVar[WebViewFeatureInternal] = ...
    POST_WEB_MESSAGE: typing.ClassVar[WebViewFeatureInternal] = ...
    WEB_MESSAGE_CALLBACK_ON_MESSAGE: typing.ClassVar[WebViewFeatureInternal] = ...
    @staticmethod
    def getFeature(feature: str | java.lang.String, /) -> WebViewFeatureInternal: ...
    @staticmethod
    def getUnsupportedOperationException() -> java.lang.UnsupportedOperationException: ...
    @staticmethod
    def getWebViewApkFeaturesForTesting() -> java.chaquopy.JavaArray[java.lang.String]: ...
    def isSupportedByFramework(self) -> bool: ...
    def isSupportedByWebView(self) -> bool: ...
    @staticmethod
    def valueOf(name: str | java.lang.String, /) -> WebViewFeatureInternal: ...
    @staticmethod
    def values() -> java.chaquopy.JavaArray[WebViewFeatureInternal]: ...

class WebViewGlueCommunicator(java.lang.Object):
    @staticmethod
    def getCompatConverter() -> WebkitToCompatConverter: ...
    @staticmethod
    def getFactory() -> WebViewProviderFactory: ...
    @staticmethod
    def getWebViewClassLoader() -> java.lang.ClassLoader: ...

class WebViewProviderAdapter(java.lang.Object):
    def __init__(self, impl: org.chromium.support_lib_boundary.WebViewProviderBoundaryInterface, /) -> None: ...
    def createWebMessageChannel(self) -> java.chaquopy.JavaArray[androidx.webkit.WebMessagePortCompat]: ...
    def insertVisualStateCallback(self, requestId: int | java.jlong | java.lang.Long, callback: androidx.webkit.WebViewCompat.VisualStateCallback, /) -> None: ...
    def postWebMessage(self, message: androidx.webkit.WebMessageCompat, targetOrigin: android.net.Uri, /) -> None: ...

class WebViewProviderFactory(java.lang.Object):
    def createWebView(self, arg1: android.webkit.WebView, /) -> org.chromium.support_lib_boundary.WebViewProviderBoundaryInterface: ...
    def getServiceWorkerController(self) -> org.chromium.support_lib_boundary.ServiceWorkerControllerBoundaryInterface: ...
    def getStatics(self) -> org.chromium.support_lib_boundary.StaticsBoundaryInterface: ...
    def getWebViewFeatures(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    def getWebkitToCompatConverter(self) -> org.chromium.support_lib_boundary.WebkitToCompatConverterBoundaryInterface: ...

class WebViewProviderFactoryAdapter(WebViewProviderFactory):
    def __init__(self, impl: org.chromium.support_lib_boundary.WebViewProviderFactoryBoundaryInterface, /) -> None: ...
    def createWebView(self, webview: android.webkit.WebView, /) -> org.chromium.support_lib_boundary.WebViewProviderBoundaryInterface: ...
    def getServiceWorkerController(self) -> org.chromium.support_lib_boundary.ServiceWorkerControllerBoundaryInterface: ...
    def getStatics(self) -> org.chromium.support_lib_boundary.StaticsBoundaryInterface: ...
    def getWebViewFeatures(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    def getWebkitToCompatConverter(self) -> org.chromium.support_lib_boundary.WebkitToCompatConverterBoundaryInterface: ...

class WebkitToCompatConverter(java.lang.Object):
    def __init__(self, impl: org.chromium.support_lib_boundary.WebkitToCompatConverterBoundaryInterface, /) -> None: ...
    @typing.overload
    def convertServiceWorkerSettings(self, settings: android.webkit.ServiceWorkerWebSettings, /) -> java.lang.reflect.InvocationHandler: ...
    @typing.overload
    def convertServiceWorkerSettings(self, serviceWorkerSettings: java.lang.reflect.InvocationHandler, /) -> android.webkit.ServiceWorkerWebSettings: ...
    def convertSettings(self, webSettings: android.webkit.WebSettings, /) -> WebSettingsAdapter: ...
    def convertWebResourceRequest(self, request: android.webkit.WebResourceRequest, /) -> WebResourceRequestAdapter: ...
