import typing

import java.io
import java.lang
import java.lang.annotation
import kotlin
import kotlin.coroutines.jvm.internal
import kotlin.jvm.functions

class AbstractCoroutineContextElement(CoroutineContext.Element):
    def __init__(self, key: CoroutineContext.Key[java.lang.Object], /) -> None: ...
    _fold__R = typing.TypeVar('_fold__R')  # <R>
    def fold(self, initial: _fold__R, operation: kotlin.jvm.functions.Function2[_fold__R, CoroutineContext.Element, _fold__R], /) -> _fold__R: ...
    _get__E = typing.TypeVar('_get__E')  # <E>
    def get(self, key: CoroutineContext.Key[_get__E], /) -> _get__E: ...
    def getKey(self) -> CoroutineContext.Key[java.lang.Object]: ...
    def minusKey(self, key: CoroutineContext.Key[java.lang.Object], /) -> CoroutineContext: ...
    def plus(self, context: CoroutineContext, /) -> CoroutineContext: ...

class CombinedContext(CoroutineContext, java.io.Serializable):
    def __init__(self, left: CoroutineContext, element: CoroutineContext.Element, /) -> None: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    _fold__R = typing.TypeVar('_fold__R')  # <R>
    def fold(self, initial: _fold__R, operation: kotlin.jvm.functions.Function2[_fold__R, CoroutineContext.Element, _fold__R], /) -> _fold__R: ...
    _get__E = typing.TypeVar('_get__E')  # <E>
    def get(self, key: CoroutineContext.Key[_get__E], /) -> _get__E: ...
    def hashCode(self) -> int: ...
    def minusKey(self, key: CoroutineContext.Key[java.lang.Object], /) -> CoroutineContext: ...
    def plus(self, context: CoroutineContext, /) -> CoroutineContext: ...
    def toString(self) -> str: ...

_Continuation__T = typing.TypeVar('_Continuation__T')  # <T>
class Continuation(java.lang.Object, typing.Generic[_Continuation__T]):
    def getContext(self) -> CoroutineContext: ...
    def resumeWith(self, arg1: java.lang.Object | int | bool | float | str, /) -> None: ...

class ContinuationInterceptor(CoroutineContext.Element):
    Key: typing.ClassVar[ContinuationInterceptor.Key] = ...
    _get__E = typing.TypeVar('_get__E')  # <E>
    def get(self, arg1: CoroutineContext.Key[_get__E], /) -> _get__E: ...
    _interceptContinuation__T = typing.TypeVar('_interceptContinuation__T')  # <T>
    def interceptContinuation(self, arg1: Continuation[_interceptContinuation__T], /) -> Continuation[_interceptContinuation__T]: ...
    def minusKey(self, arg1: CoroutineContext.Key[java.lang.Object], /) -> CoroutineContext: ...
    def releaseInterceptedContinuation(self, arg1: Continuation[java.lang.Object], /) -> None: ...

    class DefaultImpls(java.lang.Object):
        _fold__R = typing.TypeVar('_fold__R')  # <R>
        @staticmethod
        def fold(this: ContinuationInterceptor, initial: _fold__R, operation: kotlin.jvm.functions.Function2[_fold__R, CoroutineContext.Element, _fold__R], /) -> _fold__R: ...
        _get__E = typing.TypeVar('_get__E')  # <E>
        @staticmethod
        def get(this: ContinuationInterceptor, key: CoroutineContext.Key[_get__E], /) -> _get__E: ...
        @staticmethod
        def minusKey(this: ContinuationInterceptor, key: CoroutineContext.Key[java.lang.Object], /) -> CoroutineContext: ...
        @staticmethod
        def plus(this: ContinuationInterceptor, context: CoroutineContext, /) -> CoroutineContext: ...
        @staticmethod
        def releaseInterceptedContinuation(this: ContinuationInterceptor, continuation: Continuation[java.lang.Object], /) -> None: ...

    class Key(CoroutineContext.Key[ContinuationInterceptor]): ...

class ContinuationKt(java.lang.Object):
    _createCoroutine_0__T = typing.TypeVar('_createCoroutine_0__T')  # <T>
    _createCoroutine_1__R = typing.TypeVar('_createCoroutine_1__R')  # <R>
    _createCoroutine_1__T = typing.TypeVar('_createCoroutine_1__T')  # <T>
    @typing.overload
    @staticmethod
    def createCoroutine(this_createCoroutine: kotlin.jvm.functions.Function1[Continuation[_createCoroutine_0__T], java.lang.Object], completion: Continuation[_createCoroutine_0__T], /) -> Continuation[kotlin.Unit]: ...
    @typing.overload
    @staticmethod
    def createCoroutine(this_createCoroutine: kotlin.jvm.functions.Function2[_createCoroutine_1__R, Continuation[_createCoroutine_1__T], java.lang.Object], receiver: _createCoroutine_1__R, completion: Continuation[_createCoroutine_1__T], /) -> Continuation[kotlin.Unit]: ...
    _startCoroutine_0__T = typing.TypeVar('_startCoroutine_0__T')  # <T>
    _startCoroutine_1__R = typing.TypeVar('_startCoroutine_1__R')  # <R>
    _startCoroutine_1__T = typing.TypeVar('_startCoroutine_1__T')  # <T>
    @typing.overload
    @staticmethod
    def startCoroutine(this_startCoroutine: kotlin.jvm.functions.Function1[Continuation[_startCoroutine_0__T], java.lang.Object], completion: Continuation[_startCoroutine_0__T], /) -> None: ...
    @typing.overload
    @staticmethod
    def startCoroutine(this_startCoroutine: kotlin.jvm.functions.Function2[_startCoroutine_1__R, Continuation[_startCoroutine_1__T], java.lang.Object], receiver: _startCoroutine_1__R, completion: Continuation[_startCoroutine_1__T], /) -> None: ...


_CoroutineContext__Key__E = typing.TypeVar('_CoroutineContext__Key__E')  # <E>
class CoroutineContext(java.lang.Object):
    _fold__R = typing.TypeVar('_fold__R')  # <R>
    def fold(self, arg1: _fold__R, arg2: kotlin.jvm.functions.Function2[_fold__R, CoroutineContext.Element, _fold__R], /) -> _fold__R: ...
    _get__E = typing.TypeVar('_get__E')  # <E>
    def get(self, arg1: CoroutineContext.Key[_get__E], /) -> _get__E: ...
    def minusKey(self, arg1: CoroutineContext.Key[java.lang.Object], /) -> CoroutineContext: ...
    def plus(self, arg1: CoroutineContext, /) -> CoroutineContext: ...
    class Key(java.lang.Object, typing.Generic[_CoroutineContext__Key__E]): ...

    class Element(CoroutineContext):
        _fold__R = typing.TypeVar('_fold__R')  # <R>
        def fold(self, arg1: _fold__R, arg2: kotlin.jvm.functions.Function2[_fold__R, CoroutineContext.Element, _fold__R], /) -> _fold__R: ...
        _get__E = typing.TypeVar('_get__E')  # <E>
        def get(self, arg1: CoroutineContext.Key[_get__E], /) -> _get__E: ...
        def getKey(self) -> CoroutineContext.Key[java.lang.Object]: ...
        def minusKey(self, arg1: CoroutineContext.Key[java.lang.Object], /) -> CoroutineContext: ...

        class DefaultImpls(java.lang.Object):
            _fold__R = typing.TypeVar('_fold__R')  # <R>
            @staticmethod
            def fold(this: CoroutineContext.Element, initial: _fold__R, operation: kotlin.jvm.functions.Function2[_fold__R, CoroutineContext.Element, _fold__R], /) -> _fold__R: ...
            _get__E = typing.TypeVar('_get__E')  # <E>
            @staticmethod
            def get(this: CoroutineContext.Element, key: CoroutineContext.Key[_get__E], /) -> _get__E: ...
            @staticmethod
            def minusKey(this: CoroutineContext.Element, key: CoroutineContext.Key[java.lang.Object], /) -> CoroutineContext: ...
            @staticmethod
            def plus(this: CoroutineContext.Element, context: CoroutineContext, /) -> CoroutineContext: ...

    class DefaultImpls(java.lang.Object):
        @staticmethod
        def plus(this: CoroutineContext, context: CoroutineContext, /) -> CoroutineContext: ...

class EmptyCoroutineContext(CoroutineContext, java.io.Serializable):
    INSTANCE: typing.ClassVar[EmptyCoroutineContext] = ...
    _fold__R = typing.TypeVar('_fold__R')  # <R>
    def fold(self, initial: _fold__R, operation: kotlin.jvm.functions.Function2[_fold__R, CoroutineContext.Element, _fold__R], /) -> _fold__R: ...
    _get__E = typing.TypeVar('_get__E')  # <E>
    def get(self, key: CoroutineContext.Key[_get__E], /) -> _get__E: ...
    def hashCode(self) -> int: ...
    def minusKey(self, key: CoroutineContext.Key[java.lang.Object], /) -> CoroutineContext: ...
    def plus(self, context: CoroutineContext, /) -> CoroutineContext: ...
    def toString(self) -> str: ...

class RestrictsSuspension(java.lang.annotation.Annotation): ...

_SafeContinuation__T = typing.TypeVar('_SafeContinuation__T')  # <T>
class SafeContinuation(Continuation[_SafeContinuation__T], kotlin.coroutines.jvm.internal.CoroutineStackFrame, typing.Generic[_SafeContinuation__T]):
    Companion: typing.ClassVar[SafeContinuation.Companion] = ...
    @typing.overload
    def __init__(self, delegate: Continuation[_SafeContinuation__T], /) -> None: ...
    @typing.overload
    def __init__(self, delegate: Continuation[_SafeContinuation__T], initialResult: java.lang.Object | int | bool | float | str, /) -> None: ...
    def getCallerFrame(self) -> kotlin.coroutines.jvm.internal.CoroutineStackFrame: ...
    def getContext(self) -> CoroutineContext: ...
    def getOrThrow(self) -> java.lang.Object: ...
    def getStackTraceElement(self) -> java.lang.StackTraceElement: ...
    def resumeWith(self, result: java.lang.Object | int | bool | float | str, /) -> None: ...
    def toString(self) -> str: ...
