import typing

import java
import java.chaquopy
import java.lang
import java.util
import kotlin
import kotlin.collections
import kotlin.random
import kotlin.ranges

class UArraysKt(UArraysKt___UArraysKt): ...

class UArraysKt___UArraysJvmKt(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def asList--ajY-9A(this_asList_u2d_u2dajY_u2d9A: java.chaquopy.JavaArrayJInt, /) -> java.util.List[kotlin.UInt]: ...
    @staticmethod
    def asList-GBYM_sE(this_asList_u2dGBYM_sE: java.chaquopy.JavaArrayJByte, /) -> java.util.List[kotlin.UByte]: ...
    @staticmethod
    def asList-QwZRm1k(this_asList_u2dQwZRm1k: java.chaquopy.JavaArrayJLong, /) -> java.util.List[kotlin.ULong]: ...
    @staticmethod
    def asList-rL5Bavg(this_asList_u2drL5Bavg: java.chaquopy.JavaArrayJShort, /) -> java.util.List[kotlin.UShort]: ...
    @staticmethod
    def binarySearch-2fe2U9s(this_binarySearch_u2d2fe2U9s: java.chaquopy.JavaArrayJInt, element: int | java.jint | java.lang.Integer, fromIndex: int | java.jint | java.lang.Integer, toIndex: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def binarySearch-EtDCXyQ(this_binarySearch_u2dEtDCXyQ: java.chaquopy.JavaArrayJShort, element: int | java.jshort | java.lang.Short, fromIndex: int | java.jint | java.lang.Integer, toIndex: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def binarySearch-K6DWlUc(this_binarySearch_u2dK6DWlUc: java.chaquopy.JavaArrayJLong, element: int | java.jlong | java.lang.Long, fromIndex: int | java.jint | java.lang.Integer, toIndex: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def binarySearch-WpHrYlw(this_binarySearch_u2dWpHrYlw: java.chaquopy.JavaArrayJByte, element: int | java.jbyte | java.lang.Byte, fromIndex: int | java.jint | java.lang.Integer, toIndex: int | java.jint | java.lang.Integer, /) -> int: ...

class UArraysKt___UArraysKt(UArraysKt___UArraysJvmKt):
    def __init__(self) -> None: ...
    @staticmethod
    def contentEquals-FGO6Aew(this_contentEquals_u2dFGO6Aew: java.chaquopy.JavaArrayJShort, other: java.chaquopy.JavaArrayJShort, /) -> bool: ...
    @staticmethod
    def contentEquals-KJPZfPQ(this_contentEquals_u2dKJPZfPQ: java.chaquopy.JavaArrayJInt, other: java.chaquopy.JavaArrayJInt, /) -> bool: ...
    @staticmethod
    def contentEquals-kV0jMPg(this_contentEquals_u2dkV0jMPg: java.chaquopy.JavaArrayJByte, other: java.chaquopy.JavaArrayJByte, /) -> bool: ...
    @staticmethod
    def contentEquals-lec5QzE(this_contentEquals_u2dlec5QzE: java.chaquopy.JavaArrayJLong, other: java.chaquopy.JavaArrayJLong, /) -> bool: ...
    @staticmethod
    def contentHashCode-2csIQuQ(this_contentHashCode_u2d2csIQuQ: java.chaquopy.JavaArrayJByte, /) -> int: ...
    @staticmethod
    def contentHashCode-XUkPCBk(this_contentHashCode_u2dXUkPCBk: java.chaquopy.JavaArrayJInt, /) -> int: ...
    @staticmethod
    def contentHashCode-d-6D3K8(this_contentHashCode_u2dd_u2d6D3K8: java.chaquopy.JavaArrayJShort, /) -> int: ...
    @staticmethod
    def contentHashCode-uLth9ew(this_contentHashCode_u2duLth9ew: java.chaquopy.JavaArrayJLong, /) -> int: ...
    @staticmethod
    def contentToString-2csIQuQ(this_contentToString_u2d2csIQuQ: java.chaquopy.JavaArrayJByte, /) -> str: ...
    @staticmethod
    def contentToString-XUkPCBk(this_contentToString_u2dXUkPCBk: java.chaquopy.JavaArrayJInt, /) -> str: ...
    @staticmethod
    def contentToString-d-6D3K8(this_contentToString_u2dd_u2d6D3K8: java.chaquopy.JavaArrayJShort, /) -> str: ...
    @staticmethod
    def contentToString-uLth9ew(this_contentToString_u2duLth9ew: java.chaquopy.JavaArrayJLong, /) -> str: ...
    @staticmethod
    def drop-PpDY95g(this_drop_u2dPpDY95g: java.chaquopy.JavaArrayJByte, n: int | java.jint | java.lang.Integer, /) -> java.util.List[kotlin.UByte]: ...
    @staticmethod
    def drop-nggk6HY(this_drop_u2dnggk6HY: java.chaquopy.JavaArrayJShort, n: int | java.jint | java.lang.Integer, /) -> java.util.List[kotlin.UShort]: ...
    @staticmethod
    def drop-qFRl0hI(this_drop_u2dqFRl0hI: java.chaquopy.JavaArrayJInt, n: int | java.jint | java.lang.Integer, /) -> java.util.List[kotlin.UInt]: ...
    @staticmethod
    def drop-r7IrZao(this_drop_u2dr7IrZao: java.chaquopy.JavaArrayJLong, n: int | java.jint | java.lang.Integer, /) -> java.util.List[kotlin.ULong]: ...
    @staticmethod
    def dropLast-PpDY95g(this_dropLast_u2dPpDY95g: java.chaquopy.JavaArrayJByte, n: int | java.jint | java.lang.Integer, /) -> java.util.List[kotlin.UByte]: ...
    @staticmethod
    def dropLast-nggk6HY(this_dropLast_u2dnggk6HY: java.chaquopy.JavaArrayJShort, n: int | java.jint | java.lang.Integer, /) -> java.util.List[kotlin.UShort]: ...
    @staticmethod
    def dropLast-qFRl0hI(this_dropLast_u2dqFRl0hI: java.chaquopy.JavaArrayJInt, n: int | java.jint | java.lang.Integer, /) -> java.util.List[kotlin.UInt]: ...
    @staticmethod
    def dropLast-r7IrZao(this_dropLast_u2dr7IrZao: java.chaquopy.JavaArrayJLong, n: int | java.jint | java.lang.Integer, /) -> java.util.List[kotlin.ULong]: ...
    @staticmethod
    def fill-2fe2U9s(this_fill_u2d2fe2U9s: java.chaquopy.JavaArrayJInt, element: int | java.jint | java.lang.Integer, fromIndex: int | java.jint | java.lang.Integer, toIndex: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def fill-EtDCXyQ(this_fill_u2dEtDCXyQ: java.chaquopy.JavaArrayJShort, element: int | java.jshort | java.lang.Short, fromIndex: int | java.jint | java.lang.Integer, toIndex: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def fill-K6DWlUc(this_fill_u2dK6DWlUc: java.chaquopy.JavaArrayJLong, element: int | java.jlong | java.lang.Long, fromIndex: int | java.jint | java.lang.Integer, toIndex: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def fill-WpHrYlw(this_fill_u2dWpHrYlw: java.chaquopy.JavaArrayJByte, element: int | java.jbyte | java.lang.Byte, fromIndex: int | java.jint | java.lang.Integer, toIndex: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def firstOrNull--ajY-9A(this_firstOrNull_u2d_u2dajY_u2d9A: java.chaquopy.JavaArrayJInt, /) -> kotlin.UInt: ...
    @staticmethod
    def firstOrNull-GBYM_sE(this_firstOrNull_u2dGBYM_sE: java.chaquopy.JavaArrayJByte, /) -> kotlin.UByte: ...
    @staticmethod
    def firstOrNull-QwZRm1k(this_firstOrNull_u2dQwZRm1k: java.chaquopy.JavaArrayJLong, /) -> kotlin.ULong: ...
    @staticmethod
    def firstOrNull-rL5Bavg(this_firstOrNull_u2drL5Bavg: java.chaquopy.JavaArrayJShort, /) -> kotlin.UShort: ...
    @staticmethod
    def getIndices--ajY-9A(this_indices: java.chaquopy.JavaArrayJInt, /) -> kotlin.ranges.IntRange: ...
    @staticmethod
    def getIndices-GBYM_sE(this_indices: java.chaquopy.JavaArrayJByte, /) -> kotlin.ranges.IntRange: ...
    @staticmethod
    def getIndices-QwZRm1k(this_indices: java.chaquopy.JavaArrayJLong, /) -> kotlin.ranges.IntRange: ...
    @staticmethod
    def getIndices-rL5Bavg(this_indices: java.chaquopy.JavaArrayJShort, /) -> kotlin.ranges.IntRange: ...
    @staticmethod
    def getLastIndex--ajY-9A(this_lastIndex: java.chaquopy.JavaArrayJInt, /) -> int: ...
    @staticmethod
    def getLastIndex-GBYM_sE(this_lastIndex: java.chaquopy.JavaArrayJByte, /) -> int: ...
    @staticmethod
    def getLastIndex-QwZRm1k(this_lastIndex: java.chaquopy.JavaArrayJLong, /) -> int: ...
    @staticmethod
    def getLastIndex-rL5Bavg(this_lastIndex: java.chaquopy.JavaArrayJShort, /) -> int: ...
    @staticmethod
    def getOrNull-PpDY95g(this_getOrNull_u2dPpDY95g: java.chaquopy.JavaArrayJByte, index: int | java.jint | java.lang.Integer, /) -> kotlin.UByte: ...
    @staticmethod
    def getOrNull-nggk6HY(this_getOrNull_u2dnggk6HY: java.chaquopy.JavaArrayJShort, index: int | java.jint | java.lang.Integer, /) -> kotlin.UShort: ...
    @staticmethod
    def getOrNull-qFRl0hI(this_getOrNull_u2dqFRl0hI: java.chaquopy.JavaArrayJInt, index: int | java.jint | java.lang.Integer, /) -> kotlin.UInt: ...
    @staticmethod
    def getOrNull-r7IrZao(this_getOrNull_u2dr7IrZao: java.chaquopy.JavaArrayJLong, index: int | java.jint | java.lang.Integer, /) -> kotlin.ULong: ...
    @staticmethod
    def lastOrNull--ajY-9A(this_lastOrNull_u2d_u2dajY_u2d9A: java.chaquopy.JavaArrayJInt, /) -> kotlin.UInt: ...
    @staticmethod
    def lastOrNull-GBYM_sE(this_lastOrNull_u2dGBYM_sE: java.chaquopy.JavaArrayJByte, /) -> kotlin.UByte: ...
    @staticmethod
    def lastOrNull-QwZRm1k(this_lastOrNull_u2dQwZRm1k: java.chaquopy.JavaArrayJLong, /) -> kotlin.ULong: ...
    @staticmethod
    def lastOrNull-rL5Bavg(this_lastOrNull_u2drL5Bavg: java.chaquopy.JavaArrayJShort, /) -> kotlin.UShort: ...
    @staticmethod
    def maxOrNull--ajY-9A(this_maxOrNull_u2d_u2dajY_u2d9A: java.chaquopy.JavaArrayJInt, /) -> kotlin.UInt: ...
    @staticmethod
    def maxOrNull-GBYM_sE(this_maxOrNull_u2dGBYM_sE: java.chaquopy.JavaArrayJByte, /) -> kotlin.UByte: ...
    @staticmethod
    def maxOrNull-QwZRm1k(this_maxOrNull_u2dQwZRm1k: java.chaquopy.JavaArrayJLong, /) -> kotlin.ULong: ...
    @staticmethod
    def maxOrNull-rL5Bavg(this_maxOrNull_u2drL5Bavg: java.chaquopy.JavaArrayJShort, /) -> kotlin.UShort: ...
    @staticmethod
    def maxWithOrNull-XMRcp5o(this_maxWithOrNull_u2dXMRcp5o: java.chaquopy.JavaArrayJByte, comparator: java.util.Comparator[kotlin.UByte], /) -> kotlin.UByte: ...
    @staticmethod
    def maxWithOrNull-YmdZ_VM(this_maxWithOrNull_u2dYmdZ_VM: java.chaquopy.JavaArrayJInt, comparator: java.util.Comparator[kotlin.UInt], /) -> kotlin.UInt: ...
    @staticmethod
    def maxWithOrNull-eOHTfZs(this_maxWithOrNull_u2deOHTfZs: java.chaquopy.JavaArrayJShort, comparator: java.util.Comparator[kotlin.UShort], /) -> kotlin.UShort: ...
    @staticmethod
    def maxWithOrNull-zrEWJaI(this_maxWithOrNull_u2dzrEWJaI: java.chaquopy.JavaArrayJLong, comparator: java.util.Comparator[kotlin.ULong], /) -> kotlin.ULong: ...
    @staticmethod
    def minOrNull--ajY-9A(this_minOrNull_u2d_u2dajY_u2d9A: java.chaquopy.JavaArrayJInt, /) -> kotlin.UInt: ...
    @staticmethod
    def minOrNull-GBYM_sE(this_minOrNull_u2dGBYM_sE: java.chaquopy.JavaArrayJByte, /) -> kotlin.UByte: ...
    @staticmethod
    def minOrNull-QwZRm1k(this_minOrNull_u2dQwZRm1k: java.chaquopy.JavaArrayJLong, /) -> kotlin.ULong: ...
    @staticmethod
    def minOrNull-rL5Bavg(this_minOrNull_u2drL5Bavg: java.chaquopy.JavaArrayJShort, /) -> kotlin.UShort: ...
    @staticmethod
    def minWithOrNull-XMRcp5o(this_minWithOrNull_u2dXMRcp5o: java.chaquopy.JavaArrayJByte, comparator: java.util.Comparator[kotlin.UByte], /) -> kotlin.UByte: ...
    @staticmethod
    def minWithOrNull-YmdZ_VM(this_minWithOrNull_u2dYmdZ_VM: java.chaquopy.JavaArrayJInt, comparator: java.util.Comparator[kotlin.UInt], /) -> kotlin.UInt: ...
    @staticmethod
    def minWithOrNull-eOHTfZs(this_minWithOrNull_u2deOHTfZs: java.chaquopy.JavaArrayJShort, comparator: java.util.Comparator[kotlin.UShort], /) -> kotlin.UShort: ...
    @staticmethod
    def minWithOrNull-zrEWJaI(this_minWithOrNull_u2dzrEWJaI: java.chaquopy.JavaArrayJLong, comparator: java.util.Comparator[kotlin.ULong], /) -> kotlin.ULong: ...
    @staticmethod
    def plus-CFIt9YE(this_plus_u2dCFIt9YE: java.chaquopy.JavaArrayJInt, elements: java.util.Collection[kotlin.UInt], /) -> java.chaquopy.JavaArrayJInt: ...
    @staticmethod
    def plus-kzHmqpY(this_plus_u2dkzHmqpY: java.chaquopy.JavaArrayJLong, elements: java.util.Collection[kotlin.ULong], /) -> java.chaquopy.JavaArrayJLong: ...
    @staticmethod
    def plus-ojwP5H8(this_plus_u2dojwP5H8: java.chaquopy.JavaArrayJShort, elements: java.util.Collection[kotlin.UShort], /) -> java.chaquopy.JavaArrayJShort: ...
    @staticmethod
    def plus-xo_DsdI(this_plus_u2dxo_DsdI: java.chaquopy.JavaArrayJByte, elements: java.util.Collection[kotlin.UByte], /) -> java.chaquopy.JavaArrayJByte: ...
    @staticmethod
    def random-2D5oskM(this_random_u2d2D5oskM: java.chaquopy.JavaArrayJInt, random: kotlin.random.Random, /) -> int: ...
    @staticmethod
    def random-JzugnMA(this_random_u2dJzugnMA: java.chaquopy.JavaArrayJLong, random: kotlin.random.Random, /) -> int: ...
    @staticmethod
    def random-oSF2wD8(this_random_u2doSF2wD8: java.chaquopy.JavaArrayJByte, random: kotlin.random.Random, /) -> int: ...
    @staticmethod
    def random-s5X_as8(this_random_u2ds5X_as8: java.chaquopy.JavaArrayJShort, random: kotlin.random.Random, /) -> int: ...
    @staticmethod
    def randomOrNull-2D5oskM(this_randomOrNull_u2d2D5oskM: java.chaquopy.JavaArrayJInt, random: kotlin.random.Random, /) -> kotlin.UInt: ...
    @staticmethod
    def randomOrNull-JzugnMA(this_randomOrNull_u2dJzugnMA: java.chaquopy.JavaArrayJLong, random: kotlin.random.Random, /) -> kotlin.ULong: ...
    @staticmethod
    def randomOrNull-oSF2wD8(this_randomOrNull_u2doSF2wD8: java.chaquopy.JavaArrayJByte, random: kotlin.random.Random, /) -> kotlin.UByte: ...
    @staticmethod
    def randomOrNull-s5X_as8(this_randomOrNull_u2ds5X_as8: java.chaquopy.JavaArrayJShort, random: kotlin.random.Random, /) -> kotlin.UShort: ...
    @staticmethod
    def reversed--ajY-9A(this_reversed_u2d_u2dajY_u2d9A: java.chaquopy.JavaArrayJInt, /) -> java.util.List[kotlin.UInt]: ...
    @staticmethod
    def reversed-GBYM_sE(this_reversed_u2dGBYM_sE: java.chaquopy.JavaArrayJByte, /) -> java.util.List[kotlin.UByte]: ...
    @staticmethod
    def reversed-QwZRm1k(this_reversed_u2dQwZRm1k: java.chaquopy.JavaArrayJLong, /) -> java.util.List[kotlin.ULong]: ...
    @staticmethod
    def reversed-rL5Bavg(this_reversed_u2drL5Bavg: java.chaquopy.JavaArrayJShort, /) -> java.util.List[kotlin.UShort]: ...
    @staticmethod
    def shuffle--ajY-9A(this_shuffle_u2d_u2dajY_u2d9A: java.chaquopy.JavaArrayJInt, /) -> None: ...
    @staticmethod
    def shuffle-2D5oskM(this_shuffle_u2d2D5oskM: java.chaquopy.JavaArrayJInt, random: kotlin.random.Random, /) -> None: ...
    @staticmethod
    def shuffle-GBYM_sE(this_shuffle_u2dGBYM_sE: java.chaquopy.JavaArrayJByte, /) -> None: ...
    @staticmethod
    def shuffle-JzugnMA(this_shuffle_u2dJzugnMA: java.chaquopy.JavaArrayJLong, random: kotlin.random.Random, /) -> None: ...
    @staticmethod
    def shuffle-QwZRm1k(this_shuffle_u2dQwZRm1k: java.chaquopy.JavaArrayJLong, /) -> None: ...
    @staticmethod
    def shuffle-oSF2wD8(this_shuffle_u2doSF2wD8: java.chaquopy.JavaArrayJByte, random: kotlin.random.Random, /) -> None: ...
    @staticmethod
    def shuffle-rL5Bavg(this_shuffle_u2drL5Bavg: java.chaquopy.JavaArrayJShort, /) -> None: ...
    @staticmethod
    def shuffle-s5X_as8(this_shuffle_u2ds5X_as8: java.chaquopy.JavaArrayJShort, random: kotlin.random.Random, /) -> None: ...
    @staticmethod
    def singleOrNull--ajY-9A(this_singleOrNull_u2d_u2dajY_u2d9A: java.chaquopy.JavaArrayJInt, /) -> kotlin.UInt: ...
    @staticmethod
    def singleOrNull-GBYM_sE(this_singleOrNull_u2dGBYM_sE: java.chaquopy.JavaArrayJByte, /) -> kotlin.UByte: ...
    @staticmethod
    def singleOrNull-QwZRm1k(this_singleOrNull_u2dQwZRm1k: java.chaquopy.JavaArrayJLong, /) -> kotlin.ULong: ...
    @staticmethod
    def singleOrNull-rL5Bavg(this_singleOrNull_u2drL5Bavg: java.chaquopy.JavaArrayJShort, /) -> kotlin.UShort: ...
    @staticmethod
    def slice-F7u83W8(this_slice_u2dF7u83W8: java.chaquopy.JavaArrayJLong, indices: java.lang.Iterable[java.lang.Integer], /) -> java.util.List[kotlin.ULong]: ...
    @staticmethod
    def slice-HwE9HBo(this_slice_u2dHwE9HBo: java.chaquopy.JavaArrayJInt, indices: java.lang.Iterable[java.lang.Integer], /) -> java.util.List[kotlin.UInt]: ...
    @staticmethod
    def slice-JGPC0-M(this_slice_u2dJGPC0_u2dM: java.chaquopy.JavaArrayJShort, indices: java.lang.Iterable[java.lang.Integer], /) -> java.util.List[kotlin.UShort]: ...
    @staticmethod
    def slice-JQknh5Q(this_slice_u2dJQknh5Q: java.chaquopy.JavaArrayJByte, indices: java.lang.Iterable[java.lang.Integer], /) -> java.util.List[kotlin.UByte]: ...
    @staticmethod
    def slice-Q6IL4kU(this_slice_u2dQ6IL4kU: java.chaquopy.JavaArrayJShort, indices: kotlin.ranges.IntRange, /) -> java.util.List[kotlin.UShort]: ...
    @staticmethod
    def slice-ZRhS8yI(this_slice_u2dZRhS8yI: java.chaquopy.JavaArrayJLong, indices: kotlin.ranges.IntRange, /) -> java.util.List[kotlin.ULong]: ...
    @staticmethod
    def slice-c0bezYM(this_slice_u2dc0bezYM: java.chaquopy.JavaArrayJByte, indices: kotlin.ranges.IntRange, /) -> java.util.List[kotlin.UByte]: ...
    @staticmethod
    def slice-tAntMlw(this_slice_u2dtAntMlw: java.chaquopy.JavaArrayJInt, indices: kotlin.ranges.IntRange, /) -> java.util.List[kotlin.UInt]: ...
    @staticmethod
    def sliceArray-CFIt9YE(this_sliceArray_u2dCFIt9YE: java.chaquopy.JavaArrayJInt, indices: java.util.Collection[java.lang.Integer], /) -> java.chaquopy.JavaArrayJInt: ...
    @staticmethod
    def sliceArray-Q6IL4kU(this_sliceArray_u2dQ6IL4kU: java.chaquopy.JavaArrayJShort, indices: kotlin.ranges.IntRange, /) -> java.chaquopy.JavaArrayJShort: ...
    @staticmethod
    def sliceArray-ZRhS8yI(this_sliceArray_u2dZRhS8yI: java.chaquopy.JavaArrayJLong, indices: kotlin.ranges.IntRange, /) -> java.chaquopy.JavaArrayJLong: ...
    @staticmethod
    def sliceArray-c0bezYM(this_sliceArray_u2dc0bezYM: java.chaquopy.JavaArrayJByte, indices: kotlin.ranges.IntRange, /) -> java.chaquopy.JavaArrayJByte: ...
    @staticmethod
    def sliceArray-kzHmqpY(this_sliceArray_u2dkzHmqpY: java.chaquopy.JavaArrayJLong, indices: java.util.Collection[java.lang.Integer], /) -> java.chaquopy.JavaArrayJLong: ...
    @staticmethod
    def sliceArray-ojwP5H8(this_sliceArray_u2dojwP5H8: java.chaquopy.JavaArrayJShort, indices: java.util.Collection[java.lang.Integer], /) -> java.chaquopy.JavaArrayJShort: ...
    @staticmethod
    def sliceArray-tAntMlw(this_sliceArray_u2dtAntMlw: java.chaquopy.JavaArrayJInt, indices: kotlin.ranges.IntRange, /) -> java.chaquopy.JavaArrayJInt: ...
    @staticmethod
    def sliceArray-xo_DsdI(this_sliceArray_u2dxo_DsdI: java.chaquopy.JavaArrayJByte, indices: java.util.Collection[java.lang.Integer], /) -> java.chaquopy.JavaArrayJByte: ...
    @staticmethod
    def sort--ajY-9A(this_sort_u2d_u2dajY_u2d9A: java.chaquopy.JavaArrayJInt, /) -> None: ...
    @staticmethod
    def sort--nroSd4(this_sort_u2d_u2dnroSd4: java.chaquopy.JavaArrayJLong, fromIndex: int | java.jint | java.lang.Integer, toIndex: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def sort-4UcCI2c(this_sort_u2d4UcCI2c: java.chaquopy.JavaArrayJByte, fromIndex: int | java.jint | java.lang.Integer, toIndex: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def sort-Aa5vz7o(this_sort_u2dAa5vz7o: java.chaquopy.JavaArrayJShort, fromIndex: int | java.jint | java.lang.Integer, toIndex: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def sort-GBYM_sE(this_sort_u2dGBYM_sE: java.chaquopy.JavaArrayJByte, /) -> None: ...
    @staticmethod
    def sort-QwZRm1k(this_sort_u2dQwZRm1k: java.chaquopy.JavaArrayJLong, /) -> None: ...
    @staticmethod
    def sort-oBK06Vg(this_sort_u2doBK06Vg: java.chaquopy.JavaArrayJInt, fromIndex: int | java.jint | java.lang.Integer, toIndex: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def sort-rL5Bavg(this_sort_u2drL5Bavg: java.chaquopy.JavaArrayJShort, /) -> None: ...
    @staticmethod
    def sortDescending--ajY-9A(this_sortDescending_u2d_u2dajY_u2d9A: java.chaquopy.JavaArrayJInt, /) -> None: ...
    @staticmethod
    def sortDescending--nroSd4(this_sortDescending_u2d_u2dnroSd4: java.chaquopy.JavaArrayJLong, fromIndex: int | java.jint | java.lang.Integer, toIndex: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def sortDescending-4UcCI2c(this_sortDescending_u2d4UcCI2c: java.chaquopy.JavaArrayJByte, fromIndex: int | java.jint | java.lang.Integer, toIndex: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def sortDescending-Aa5vz7o(this_sortDescending_u2dAa5vz7o: java.chaquopy.JavaArrayJShort, fromIndex: int | java.jint | java.lang.Integer, toIndex: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def sortDescending-GBYM_sE(this_sortDescending_u2dGBYM_sE: java.chaquopy.JavaArrayJByte, /) -> None: ...
    @staticmethod
    def sortDescending-QwZRm1k(this_sortDescending_u2dQwZRm1k: java.chaquopy.JavaArrayJLong, /) -> None: ...
    @staticmethod
    def sortDescending-oBK06Vg(this_sortDescending_u2doBK06Vg: java.chaquopy.JavaArrayJInt, fromIndex: int | java.jint | java.lang.Integer, toIndex: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def sortDescending-rL5Bavg(this_sortDescending_u2drL5Bavg: java.chaquopy.JavaArrayJShort, /) -> None: ...
    @staticmethod
    def sorted--ajY-9A(this_sorted_u2d_u2dajY_u2d9A: java.chaquopy.JavaArrayJInt, /) -> java.util.List[kotlin.UInt]: ...
    @staticmethod
    def sorted-GBYM_sE(this_sorted_u2dGBYM_sE: java.chaquopy.JavaArrayJByte, /) -> java.util.List[kotlin.UByte]: ...
    @staticmethod
    def sorted-QwZRm1k(this_sorted_u2dQwZRm1k: java.chaquopy.JavaArrayJLong, /) -> java.util.List[kotlin.ULong]: ...
    @staticmethod
    def sorted-rL5Bavg(this_sorted_u2drL5Bavg: java.chaquopy.JavaArrayJShort, /) -> java.util.List[kotlin.UShort]: ...
    @staticmethod
    def sortedArray--ajY-9A(this_sortedArray_u2d_u2dajY_u2d9A: java.chaquopy.JavaArrayJInt, /) -> java.chaquopy.JavaArrayJInt: ...
    @staticmethod
    def sortedArray-GBYM_sE(this_sortedArray_u2dGBYM_sE: java.chaquopy.JavaArrayJByte, /) -> java.chaquopy.JavaArrayJByte: ...
    @staticmethod
    def sortedArray-QwZRm1k(this_sortedArray_u2dQwZRm1k: java.chaquopy.JavaArrayJLong, /) -> java.chaquopy.JavaArrayJLong: ...
    @staticmethod
    def sortedArray-rL5Bavg(this_sortedArray_u2drL5Bavg: java.chaquopy.JavaArrayJShort, /) -> java.chaquopy.JavaArrayJShort: ...
    @staticmethod
    def sortedArrayDescending--ajY-9A(this_sortedArrayDescending_u2d_u2dajY_u2d9A: java.chaquopy.JavaArrayJInt, /) -> java.chaquopy.JavaArrayJInt: ...
    @staticmethod
    def sortedArrayDescending-GBYM_sE(this_sortedArrayDescending_u2dGBYM_sE: java.chaquopy.JavaArrayJByte, /) -> java.chaquopy.JavaArrayJByte: ...
    @staticmethod
    def sortedArrayDescending-QwZRm1k(this_sortedArrayDescending_u2dQwZRm1k: java.chaquopy.JavaArrayJLong, /) -> java.chaquopy.JavaArrayJLong: ...
    @staticmethod
    def sortedArrayDescending-rL5Bavg(this_sortedArrayDescending_u2drL5Bavg: java.chaquopy.JavaArrayJShort, /) -> java.chaquopy.JavaArrayJShort: ...
    @staticmethod
    def sortedDescending--ajY-9A(this_sortedDescending_u2d_u2dajY_u2d9A: java.chaquopy.JavaArrayJInt, /) -> java.util.List[kotlin.UInt]: ...
    @staticmethod
    def sortedDescending-GBYM_sE(this_sortedDescending_u2dGBYM_sE: java.chaquopy.JavaArrayJByte, /) -> java.util.List[kotlin.UByte]: ...
    @staticmethod
    def sortedDescending-QwZRm1k(this_sortedDescending_u2dQwZRm1k: java.chaquopy.JavaArrayJLong, /) -> java.util.List[kotlin.ULong]: ...
    @staticmethod
    def sortedDescending-rL5Bavg(this_sortedDescending_u2drL5Bavg: java.chaquopy.JavaArrayJShort, /) -> java.util.List[kotlin.UShort]: ...
    @staticmethod
    def sumOfUByte(this_sum: java.chaquopy.JavaArray[kotlin.UByte], /) -> int: ...
    @staticmethod
    def sumOfUInt(this_sum: java.chaquopy.JavaArray[kotlin.UInt], /) -> int: ...
    @staticmethod
    def sumOfULong(this_sum: java.chaquopy.JavaArray[kotlin.ULong], /) -> int: ...
    @staticmethod
    def sumOfUShort(this_sum: java.chaquopy.JavaArray[kotlin.UShort], /) -> int: ...
    @staticmethod
    def take-PpDY95g(this_take_u2dPpDY95g: java.chaquopy.JavaArrayJByte, n: int | java.jint | java.lang.Integer, /) -> java.util.List[kotlin.UByte]: ...
    @staticmethod
    def take-nggk6HY(this_take_u2dnggk6HY: java.chaquopy.JavaArrayJShort, n: int | java.jint | java.lang.Integer, /) -> java.util.List[kotlin.UShort]: ...
    @staticmethod
    def take-qFRl0hI(this_take_u2dqFRl0hI: java.chaquopy.JavaArrayJInt, n: int | java.jint | java.lang.Integer, /) -> java.util.List[kotlin.UInt]: ...
    @staticmethod
    def take-r7IrZao(this_take_u2dr7IrZao: java.chaquopy.JavaArrayJLong, n: int | java.jint | java.lang.Integer, /) -> java.util.List[kotlin.ULong]: ...
    @staticmethod
    def takeLast-PpDY95g(this_takeLast_u2dPpDY95g: java.chaquopy.JavaArrayJByte, n: int | java.jint | java.lang.Integer, /) -> java.util.List[kotlin.UByte]: ...
    @staticmethod
    def takeLast-nggk6HY(this_takeLast_u2dnggk6HY: java.chaquopy.JavaArrayJShort, n: int | java.jint | java.lang.Integer, /) -> java.util.List[kotlin.UShort]: ...
    @staticmethod
    def takeLast-qFRl0hI(this_takeLast_u2dqFRl0hI: java.chaquopy.JavaArrayJInt, n: int | java.jint | java.lang.Integer, /) -> java.util.List[kotlin.UInt]: ...
    @staticmethod
    def takeLast-r7IrZao(this_takeLast_u2dr7IrZao: java.chaquopy.JavaArrayJLong, n: int | java.jint | java.lang.Integer, /) -> java.util.List[kotlin.ULong]: ...
    @staticmethod
    def toTypedArray--ajY-9A(this_toTypedArray_u2d_u2dajY_u2d9A: java.chaquopy.JavaArrayJInt, /) -> java.chaquopy.JavaArray[kotlin.UInt]: ...
    @staticmethod
    def toTypedArray-GBYM_sE(this_toTypedArray_u2dGBYM_sE: java.chaquopy.JavaArrayJByte, /) -> java.chaquopy.JavaArray[kotlin.UByte]: ...
    @staticmethod
    def toTypedArray-QwZRm1k(this_toTypedArray_u2dQwZRm1k: java.chaquopy.JavaArrayJLong, /) -> java.chaquopy.JavaArray[kotlin.ULong]: ...
    @staticmethod
    def toTypedArray-rL5Bavg(this_toTypedArray_u2drL5Bavg: java.chaquopy.JavaArrayJShort, /) -> java.chaquopy.JavaArray[kotlin.UShort]: ...
    @staticmethod
    def toUByteArray(this_toUByteArray: java.chaquopy.JavaArray[kotlin.UByte], /) -> java.chaquopy.JavaArrayJByte: ...
    @staticmethod
    def toUIntArray(this_toUIntArray: java.chaquopy.JavaArray[kotlin.UInt], /) -> java.chaquopy.JavaArrayJInt: ...
    @staticmethod
    def toULongArray(this_toULongArray: java.chaquopy.JavaArray[kotlin.ULong], /) -> java.chaquopy.JavaArrayJLong: ...
    @staticmethod
    def toUShortArray(this_toUShortArray: java.chaquopy.JavaArray[kotlin.UShort], /) -> java.chaquopy.JavaArrayJShort: ...
    @staticmethod
    def withIndex--ajY-9A(this_withIndex_u2d_u2dajY_u2d9A: java.chaquopy.JavaArrayJInt, /) -> java.lang.Iterable[kotlin.collections.IndexedValue[kotlin.UInt]]: ...
    @staticmethod
    def withIndex-GBYM_sE(this_withIndex_u2dGBYM_sE: java.chaquopy.JavaArrayJByte, /) -> java.lang.Iterable[kotlin.collections.IndexedValue[kotlin.UByte]]: ...
    @staticmethod
    def withIndex-QwZRm1k(this_withIndex_u2dQwZRm1k: java.chaquopy.JavaArrayJLong, /) -> java.lang.Iterable[kotlin.collections.IndexedValue[kotlin.ULong]]: ...
    @staticmethod
    def withIndex-rL5Bavg(this_withIndex_u2drL5Bavg: java.chaquopy.JavaArrayJShort, /) -> java.lang.Iterable[kotlin.collections.IndexedValue[kotlin.UShort]]: ...
    _zip-C-E_24M__R = typing.TypeVar('_zip-C-E_24M__R')  # <R>
    @staticmethod
    def zip-C-E_24M(this_zip_u2dC_u2dE_24M: java.chaquopy.JavaArrayJInt, other: java.chaquopy.JavaArray[_zip-C-E_24M__R], /) -> java.util.List[kotlin.Pair[kotlin.UInt, _zip-C-E_24M__R]]: ...
    _zip-F7u83W8__R = typing.TypeVar('_zip-F7u83W8__R')  # <R>
    @staticmethod
    def zip-F7u83W8(this_zip_u2dF7u83W8: java.chaquopy.JavaArrayJLong, other: java.lang.Iterable[_zip-F7u83W8__R], /) -> java.util.List[kotlin.Pair[kotlin.ULong, _zip-F7u83W8__R]]: ...
    _zip-HwE9HBo__R = typing.TypeVar('_zip-HwE9HBo__R')  # <R>
    @staticmethod
    def zip-HwE9HBo(this_zip_u2dHwE9HBo: java.chaquopy.JavaArrayJInt, other: java.lang.Iterable[_zip-HwE9HBo__R], /) -> java.util.List[kotlin.Pair[kotlin.UInt, _zip-HwE9HBo__R]]: ...
    _zip-JGPC0-M__R = typing.TypeVar('_zip-JGPC0-M__R')  # <R>
    @staticmethod
    def zip-JGPC0-M(this_zip_u2dJGPC0_u2dM: java.chaquopy.JavaArrayJShort, other: java.lang.Iterable[_zip-JGPC0-M__R], /) -> java.util.List[kotlin.Pair[kotlin.UShort, _zip-JGPC0-M__R]]: ...
    _zip-JQknh5Q__R = typing.TypeVar('_zip-JQknh5Q__R')  # <R>
    @staticmethod
    def zip-JQknh5Q(this_zip_u2dJQknh5Q: java.chaquopy.JavaArrayJByte, other: java.lang.Iterable[_zip-JQknh5Q__R], /) -> java.util.List[kotlin.Pair[kotlin.UByte, _zip-JQknh5Q__R]]: ...
    @staticmethod
    def zip-ctEhBpI(this_zip_u2dctEhBpI: java.chaquopy.JavaArrayJInt, other: java.chaquopy.JavaArrayJInt, /) -> java.util.List[kotlin.Pair[kotlin.UInt, kotlin.UInt]]: ...
    _zip-f7H3mmw__R = typing.TypeVar('_zip-f7H3mmw__R')  # <R>
    @staticmethod
    def zip-f7H3mmw(this_zip_u2df7H3mmw: java.chaquopy.JavaArrayJLong, other: java.chaquopy.JavaArray[_zip-f7H3mmw__R], /) -> java.util.List[kotlin.Pair[kotlin.ULong, _zip-f7H3mmw__R]]: ...
    @staticmethod
    def zip-kdPth3s(this_zip_u2dkdPth3s: java.chaquopy.JavaArrayJByte, other: java.chaquopy.JavaArrayJByte, /) -> java.util.List[kotlin.Pair[kotlin.UByte, kotlin.UByte]]: ...
    @staticmethod
    def zip-mazbYpA(this_zip_u2dmazbYpA: java.chaquopy.JavaArrayJShort, other: java.chaquopy.JavaArrayJShort, /) -> java.util.List[kotlin.Pair[kotlin.UShort, kotlin.UShort]]: ...
    _zip-nl983wc__R = typing.TypeVar('_zip-nl983wc__R')  # <R>
    @staticmethod
    def zip-nl983wc(this_zip_u2dnl983wc: java.chaquopy.JavaArrayJByte, other: java.chaquopy.JavaArray[_zip-nl983wc__R], /) -> java.util.List[kotlin.Pair[kotlin.UByte, _zip-nl983wc__R]]: ...
    _zip-uaTIQ5s__R = typing.TypeVar('_zip-uaTIQ5s__R')  # <R>
    @staticmethod
    def zip-uaTIQ5s(this_zip_u2duaTIQ5s: java.chaquopy.JavaArrayJShort, other: java.chaquopy.JavaArray[_zip-uaTIQ5s__R], /) -> java.util.List[kotlin.Pair[kotlin.UShort, _zip-uaTIQ5s__R]]: ...
    @staticmethod
    def zip-us8wMrg(this_zip_u2dus8wMrg: java.chaquopy.JavaArrayJLong, other: java.chaquopy.JavaArrayJLong, /) -> java.util.List[kotlin.Pair[kotlin.ULong, kotlin.ULong]]: ...
