import typing

import android.content
import android.content.res
import android.graphics
import android.graphics.drawable
import android.os
import android.util
import android.view
import android.widget
import java
import java.chaquopy
import java.lang
import java.util
import org
import org.osmdroid.api
import org.osmdroid.events
import org.osmdroid.tileprovider
import org.osmdroid.tileprovider.tilesource
import org.osmdroid.util
import org.osmdroid.util.constants
import org.osmdroid.views
import org.osmdroid.views.overlay.infowindow
import org.osmdroid.views.util.constants

_ClickableIconOverlay__DataType = typing.TypeVar('_ClickableIconOverlay__DataType')  # <DataType>
class ClickableIconOverlay(IconOverlay, typing.Generic[_ClickableIconOverlay__DataType]):
    mId: int = ...
    def __init__(self, data: _ClickableIconOverlay__DataType, /) -> None: ...
    @staticmethod
    def find(list: java.util.List[ClickableIconOverlay], id: int | java.jint | java.lang.Integer, /) -> ClickableIconOverlay: ...
    def getData(self) -> _ClickableIconOverlay__DataType: ...
    def getID(self) -> int: ...
    def hitTest(self, event: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onLongPress(self, event: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onMarkerClicked(self, arg1: org.osmdroid.views.MapView, arg2: int | java.jint | java.lang.Integer, arg3: org.osmdroid.api.IGeoPoint, arg4: _ClickableIconOverlay__DataType, /) -> bool: ...
    def onMarkerLongPress(self, mapView: org.osmdroid.views.MapView, markerId: int | java.jint | java.lang.Integer, geoPosition: org.osmdroid.api.IGeoPoint, data: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def onSingleTapConfirmed(self, event: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def set(self, id: int | java.jint | java.lang.Integer, position: org.osmdroid.api.IGeoPoint, icon: android.graphics.drawable.Drawable, data: _ClickableIconOverlay__DataType, /) -> ClickableIconOverlay: ...

class CopyrightOverlay(Overlay):
    alignBottom: bool = ...
    alignRight: bool = ...
    def __init__(self, context: android.content.Context, /) -> None: ...
    def draw(self, canvas: android.graphics.Canvas, map: org.osmdroid.views.MapView, shadow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setAlignBottom(self, alignBottom: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setAlignRight(self, alignRight: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setOffset(self, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTextColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTextSize(self, fontSize: int | java.jint | java.lang.Integer, /) -> None: ...

class DefaultOverlayManager(java.util.AbstractList[Overlay], OverlayManager):
    def __init__(self, tilesOverlay: TilesOverlay, /) -> None: ...
    def add(self, pIndex: int | java.jint | java.lang.Integer, pElement: Overlay, /) -> None: ...
    def get(self, pIndex: int | java.jint | java.lang.Integer, /) -> Overlay: ...
    def getTilesOverlay(self) -> TilesOverlay: ...
    def onCreateOptionsMenu(self, pMenu: android.view.Menu, menuIdOffset: int | java.jint | java.lang.Integer, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onDetach(self, pMapView: org.osmdroid.views.MapView, /) -> None: ...
    def onDoubleTap(self, e: android.view.MotionEvent, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onDoubleTapEvent(self, e: android.view.MotionEvent, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onDown(self, pEvent: android.view.MotionEvent, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onDraw(self, c: android.graphics.Canvas, pMapView: org.osmdroid.views.MapView, /) -> None: ...
    def onFling(self, pEvent1: android.view.MotionEvent, pEvent2: android.view.MotionEvent, pVelocityX: float | java.jfloat | java.lang.Float, pVelocityY: float | java.jfloat | java.lang.Float, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onKeyDown(self, keyCode: int | java.jint | java.lang.Integer, event: android.view.KeyEvent, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onKeyUp(self, keyCode: int | java.jint | java.lang.Integer, event: android.view.KeyEvent, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onLongPress(self, pEvent: android.view.MotionEvent, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onOptionsItemSelected(self, item: android.view.MenuItem, menuIdOffset: int | java.jint | java.lang.Integer, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onPrepareOptionsMenu(self, pMenu: android.view.Menu, menuIdOffset: int | java.jint | java.lang.Integer, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onScroll(self, pEvent1: android.view.MotionEvent, pEvent2: android.view.MotionEvent, pDistanceX: float | java.jfloat | java.lang.Float, pDistanceY: float | java.jfloat | java.lang.Float, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onShowPress(self, pEvent: android.view.MotionEvent, pMapView: org.osmdroid.views.MapView, /) -> None: ...
    def onSingleTapConfirmed(self, e: android.view.MotionEvent, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onSingleTapUp(self, pEvent: android.view.MotionEvent, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onSnapToItem(self, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, snapPoint: android.graphics.Point, pMapView: org.osmdroid.api.IMapView, /) -> bool: ...
    def onTouchEvent(self, event: android.view.MotionEvent, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onTrackballEvent(self, event: android.view.MotionEvent, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def overlays(self) -> java.util.List[Overlay]: ...
    def overlaysReversed(self) -> java.lang.Iterable[Overlay]: ...
    def remove(self, pIndex: int | java.jint | java.lang.Integer, /) -> Overlay: ...
    def set(self, pIndex: int | java.jint | java.lang.Integer, pElement: Overlay, /) -> Overlay: ...
    def setOptionsMenusEnabled(self, pEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setTilesOverlay(self, tilesOverlay: TilesOverlay, /) -> None: ...
    def size(self) -> int: ...

class FolderOverlay(Overlay):
    mOverlayManager: OverlayManager = ...
    mName: str = ...
    mDescription: str = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, ctx: android.content.Context, /) -> None: ...
    def add(self, item: Overlay, /) -> bool: ...
    def closeAllInfoWindows(self) -> None: ...
    def draw(self, canvas: android.graphics.Canvas, osm: org.osmdroid.views.MapView, shadow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def getDescription(self) -> str: ...
    def getItems(self) -> java.util.List[Overlay]: ...
    def getName(self) -> str: ...
    def onDetach(self, mapView: org.osmdroid.views.MapView, /) -> None: ...
    def onLongPress(self, e: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onSingleTapConfirmed(self, e: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onSingleTapUp(self, e: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onTouchEvent(self, e: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def remove(self, item: Overlay, /) -> bool: ...
    def setDescription(self, description: str | java.lang.String, /) -> None: ...
    def setName(self, name: str | java.lang.String, /) -> None: ...

class IOverlayMenuProvider(java.lang.Object):
    def isOptionsMenuEnabled(self) -> bool: ...
    def onCreateOptionsMenu(self, arg1: android.view.Menu, arg2: int | java.jint | java.lang.Integer, arg3: org.osmdroid.views.MapView, /) -> bool: ...
    def onOptionsItemSelected(self, arg1: android.view.MenuItem, arg2: int | java.jint | java.lang.Integer, arg3: org.osmdroid.views.MapView, /) -> bool: ...
    def onPrepareOptionsMenu(self, arg1: android.view.Menu, arg2: int | java.jint | java.lang.Integer, arg3: org.osmdroid.views.MapView, /) -> bool: ...
    def setOptionsMenuEnabled(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class IconOverlay(Overlay):
    ANCHOR_CENTER: typing.ClassVar[float] = ...
    ANCHOR_LEFT: typing.ClassVar[float] = ...
    ANCHOR_TOP: typing.ClassVar[float] = ...
    ANCHOR_RIGHT: typing.ClassVar[float] = ...
    ANCHOR_BOTTOM: typing.ClassVar[float] = ...
    mIcon: android.graphics.drawable.Drawable = ...
    mPosition: org.osmdroid.api.IGeoPoint = ...
    mBearing: float = ...
    mAnchorU: float = ...
    mAnchorV: float = ...
    mAlpha: float = ...
    mFlat: bool = ...
    mPositionPixels: android.graphics.Point = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, position: org.osmdroid.api.IGeoPoint, icon: android.graphics.drawable.Drawable, /) -> None: ...
    def draw(self, canvas: android.graphics.Canvas, mapView: org.osmdroid.views.MapView, shadow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def getPosition(self) -> org.osmdroid.api.IGeoPoint: ...
    @typing.overload
    def moveTo(self, event: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> IconOverlay: ...
    @typing.overload
    def moveTo(self, position: org.osmdroid.api.IGeoPoint, mapView: org.osmdroid.views.MapView, /) -> IconOverlay: ...
    def set(self, position: org.osmdroid.api.IGeoPoint, icon: android.graphics.drawable.Drawable, /) -> IconOverlay: ...

_ItemizedIconOverlay__Item = typing.TypeVar('_ItemizedIconOverlay__Item', bound=OverlayItem)  # <Item>

_ItemizedIconOverlay__OnItemGestureListener__T = typing.TypeVar('_ItemizedIconOverlay__OnItemGestureListener__T')  # <T>
class ItemizedIconOverlay(ItemizedOverlay[_ItemizedIconOverlay__Item], typing.Generic[_ItemizedIconOverlay__Item]):
    mItemList: java.util.List[_ItemizedIconOverlay__Item] = ...
    mOnItemGestureListener: ItemizedIconOverlay.OnItemGestureListener[_ItemizedIconOverlay__Item] = ...
    @typing.overload
    def __init__(self, pContext: android.content.Context, pList: java.util.List[_ItemizedIconOverlay__Item], pOnItemGestureListener: ItemizedIconOverlay.OnItemGestureListener[_ItemizedIconOverlay__Item], /) -> None: ...
    @typing.overload
    def __init__(self, pList: java.util.List[_ItemizedIconOverlay__Item], pOnItemGestureListener: ItemizedIconOverlay.OnItemGestureListener[_ItemizedIconOverlay__Item], pContext: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, pList: java.util.List[_ItemizedIconOverlay__Item], pDefaultMarker: android.graphics.drawable.Drawable, pOnItemGestureListener: ItemizedIconOverlay.OnItemGestureListener[_ItemizedIconOverlay__Item], pContext: android.content.Context, /) -> None: ...
    @typing.overload
    def addItem(self, item: _ItemizedIconOverlay__Item, /) -> bool: ...
    @typing.overload
    def addItem(self, location: int | java.jint | java.lang.Integer, item: _ItemizedIconOverlay__Item, /) -> None: ...
    def addItems(self, items: java.util.List[_ItemizedIconOverlay__Item], /) -> bool: ...
    def createItem(self, index: int | java.jint | java.lang.Integer, /) -> _ItemizedIconOverlay__Item: ...
    def getDrawnItemsLimit(self) -> int: ...
    def onDetach(self, mapView: org.osmdroid.views.MapView, /) -> None: ...
    def onLongPress(self, event: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onLongPressHelper(self, index: int | java.jint | java.lang.Integer, item: _ItemizedIconOverlay__Item, /) -> bool: ...
    def onSingleTapConfirmed(self, event: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onSingleTapUpHelper(self, index: int | java.jint | java.lang.Integer, item: _ItemizedIconOverlay__Item, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onSnapToItem(self, pX: int | java.jint | java.lang.Integer, pY: int | java.jint | java.lang.Integer, pSnapPoint: android.graphics.Point, pMapView: org.osmdroid.api.IMapView, /) -> bool: ...
    @typing.overload
    def removeAllItems(self) -> None: ...
    @typing.overload
    def removeAllItems(self, withPopulate: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def removeItem(self, position: int | java.jint | java.lang.Integer, /) -> _ItemizedIconOverlay__Item: ...
    @typing.overload
    def removeItem(self, item: _ItemizedIconOverlay__Item, /) -> bool: ...
    def setDrawnItemsLimit(self, aLimit: int | java.jint | java.lang.Integer, /) -> None: ...
    def size(self) -> int: ...

    class ActiveItem(java.lang.Object):
        def run(self, arg1: int | java.jint | java.lang.Integer, /) -> bool: ...
    class OnItemGestureListener(java.lang.Object, typing.Generic[_ItemizedIconOverlay__OnItemGestureListener__T]):
        def onItemLongPress(self, arg1: int | java.jint | java.lang.Integer, arg2: _ItemizedIconOverlay__OnItemGestureListener__T, /) -> bool: ...
        def onItemSingleTapUp(self, arg1: int | java.jint | java.lang.Integer, arg2: _ItemizedIconOverlay__OnItemGestureListener__T, /) -> bool: ...

_ItemizedOverlay__Item = typing.TypeVar('_ItemizedOverlay__Item', bound=OverlayItem)  # <Item>
class ItemizedOverlay(Overlay, org.osmdroid.views.overlay.Overlay.Snappable, typing.Generic[_ItemizedOverlay__Item]):
    mDefaultMarker: android.graphics.drawable.Drawable = ...
    mDrawFocusedItem: bool = ...
    scaleX: float = ...
    scaleY: float = ...
    @typing.overload
    def __init__(self, pDefaultMarker: android.graphics.drawable.Drawable, /) -> None: ...
    @typing.overload
    def __init__(self, ctx: android.content.Context, pDefaultMarker: android.graphics.drawable.Drawable, /) -> None: ...
    def boundToHotspot(self, marker: android.graphics.drawable.Drawable, hotspot: OverlayItem.HotspotPlace, /) -> android.graphics.drawable.Drawable: ...
    def createItem(self, arg1: int | java.jint | java.lang.Integer, /) -> _ItemizedOverlay__Item: ...
    def draw(self, canvas: android.graphics.Canvas, mapView: org.osmdroid.views.MapView, shadow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def getDefaultMarker(self, state: int | java.jint | java.lang.Integer, /) -> android.graphics.drawable.Drawable: ...
    def getFocus(self) -> _ItemizedOverlay__Item: ...
    def getItem(self, position: int | java.jint | java.lang.Integer, /) -> _ItemizedOverlay__Item: ...
    def hitTest(self, item: _ItemizedOverlay__Item, marker: android.graphics.drawable.Drawable, hitX: int | java.jint | java.lang.Integer, hitY: int | java.jint | java.lang.Integer, /) -> bool: ...
    def onDetach(self, mapView: org.osmdroid.views.MapView, /) -> None: ...
    def onDrawItem(self, canvas: android.graphics.Canvas, item: _ItemizedOverlay__Item, curScreenCoords: android.graphics.Point, aMapOrientation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def onSingleTapConfirmed(self, e: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onTap(self, index: int | java.jint | java.lang.Integer, /) -> bool: ...
    def populate(self) -> None: ...
    def setDrawFocusedItem(self, drawFocusedItem: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setFocus(self, item: _ItemizedOverlay__Item, /) -> None: ...
    def setOnFocusChangeListener(self, l: ItemizedOverlay.OnFocusChangeListener, /) -> None: ...
    def size(self) -> int: ...

    class OnFocusChangeListener(java.lang.Object):
        def onFocusChanged(self, arg1: ItemizedOverlay[java.lang.Object], arg2: OverlayItem, /) -> None: ...

class ItemizedOverlayControlView(android.widget.LinearLayout):
    mPreviousButton: android.widget.ImageButton = ...
    mNextButton: android.widget.ImageButton = ...
    mCenterToButton: android.widget.ImageButton = ...
    mNavToButton: android.widget.ImageButton = ...
    mLis: ItemizedOverlayControlView.ItemizedOverlayControlViewListener = ...
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    def setItemizedOverlayControlViewListener(self, lis: ItemizedOverlayControlView.ItemizedOverlayControlViewListener, /) -> None: ...
    def setNavToVisible(self, pVisibility: int | java.jint | java.lang.Integer, /) -> None: ...
    def setNextEnabled(self, pEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setPreviousEnabled(self, pEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

    class ItemizedOverlayControlViewListener(java.lang.Object):
        def onCenter(self) -> None: ...
        def onNavTo(self) -> None: ...
        def onNext(self) -> None: ...
        def onPrevious(self) -> None: ...

_ItemizedOverlayWithFocus__Item = typing.TypeVar('_ItemizedOverlayWithFocus__Item', bound=OverlayItem)  # <Item>
class ItemizedOverlayWithFocus(ItemizedIconOverlay[_ItemizedOverlayWithFocus__Item], typing.Generic[_ItemizedOverlayWithFocus__Item]):
    mMarkerFocusedBackgroundColor: int = ...
    mMarkerBackgroundPaint: android.graphics.Paint = ...
    mDescriptionPaint: android.graphics.Paint = ...
    mTitlePaint: android.graphics.Paint = ...
    mMarkerFocusedBase: android.graphics.drawable.Drawable = ...
    mFocusedItemIndex: int = ...
    mFocusItemsOnTap: bool = ...
    @typing.overload
    def __init__(self, pContext: android.content.Context, aList: java.util.List[_ItemizedOverlayWithFocus__Item], aOnItemTapListener: ItemizedIconOverlay.OnItemGestureListener[_ItemizedOverlayWithFocus__Item], /) -> None: ...
    @typing.overload
    def __init__(self, aList: java.util.List[_ItemizedOverlayWithFocus__Item], aOnItemTapListener: ItemizedIconOverlay.OnItemGestureListener[_ItemizedOverlayWithFocus__Item], pContext: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, aList: java.util.List[_ItemizedOverlayWithFocus__Item], pMarker: android.graphics.drawable.Drawable, pMarkerFocused: android.graphics.drawable.Drawable, pFocusedBackgroundColor: int | java.jint | java.lang.Integer, aOnItemTapListener: ItemizedIconOverlay.OnItemGestureListener[_ItemizedOverlayWithFocus__Item], pContext: android.content.Context, /) -> None: ...
    def draw(self, c: android.graphics.Canvas, osmv: org.osmdroid.views.MapView, shadow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def getFocusedItem(self) -> _ItemizedOverlayWithFocus__Item: ...
    def onDetach(self, mapView: org.osmdroid.views.MapView, /) -> None: ...
    def onSingleTapUpHelper(self, index: int | java.jint | java.lang.Integer, item: _ItemizedOverlayWithFocus__Item, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def setDescriptionBoxCornerWidth(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDescriptionBoxPadding(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDescriptionLineHeight(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDescriptionMaxWidth(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDescriptionTitleExtraLineHeight(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setFocusItemsOnTap(self, doit: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def setFocusedItem(self, pIndex: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setFocusedItem(self, pItem: _ItemizedOverlayWithFocus__Item, /) -> None: ...
    def setFontSize(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMarkerBackgroundColor(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMarkerDescriptionForegroundColor(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMarkerTitleForegroundColor(self, value: int | java.jint | java.lang.Integer, /) -> None: ...
    def unSetFocusedItem(self) -> None: ...

class MapEventsOverlay(Overlay):
    @typing.overload
    def __init__(self, receiver: org.osmdroid.events.MapEventsReceiver, /) -> None: ...
    @typing.overload
    def __init__(self, ctx: android.content.Context, receiver: org.osmdroid.events.MapEventsReceiver, /) -> None: ...
    def draw(self, c: android.graphics.Canvas, osmv: org.osmdroid.views.MapView, shadow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def onLongPress(self, e: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onSingleTapConfirmed(self, e: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...

class Marker(OverlayWithIW):
    ENABLE_TEXT_LABELS_WHEN_NO_IMAGE: typing.ClassVar[bool] = ...
    mTextLabelBackgroundColor: int = ...
    mTextLabelForegroundColor: int = ...
    mTextLabelFontSize: int = ...
    mIcon: android.graphics.drawable.Drawable = ...
    mPosition: org.osmdroid.util.GeoPoint = ...
    mBearing: float = ...
    mAnchorU: float = ...
    mAnchorV: float = ...
    mIWAnchorU: float = ...
    mIWAnchorV: float = ...
    mAlpha: float = ...
    mDraggable: bool = ...
    mIsDragged: bool = ...
    mFlat: bool = ...
    mOnMarkerClickListener: Marker.OnMarkerClickListener = ...
    mOnMarkerDragListener: Marker.OnMarkerDragListener = ...
    mImage: android.graphics.drawable.Drawable = ...
    mPanToView: bool = ...
    mPositionPixels: android.graphics.Point = ...
    mDefaultInfoWindow: typing.ClassVar[org.osmdroid.views.overlay.infowindow.MarkerInfoWindow] = ...
    mDefaultIcon: typing.ClassVar[android.graphics.drawable.Drawable] = ...
    resource: android.content.res.Resources = ...
    ANCHOR_CENTER: typing.ClassVar[float] = ...
    ANCHOR_LEFT: typing.ClassVar[float] = ...
    ANCHOR_TOP: typing.ClassVar[float] = ...
    ANCHOR_RIGHT: typing.ClassVar[float] = ...
    ANCHOR_BOTTOM: typing.ClassVar[float] = ...
    @typing.overload
    def __init__(self, mapView: org.osmdroid.views.MapView, /) -> None: ...
    @typing.overload
    def __init__(self, mapView: org.osmdroid.views.MapView, resourceProxy: android.content.Context, /) -> None: ...
    @staticmethod
    def cleanDefaults() -> None: ...
    def draw(self, canvas: android.graphics.Canvas, mapView: org.osmdroid.views.MapView, shadow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def getAlpha(self) -> float: ...
    def getImage(self) -> android.graphics.drawable.Drawable: ...
    def getPosition(self) -> org.osmdroid.util.GeoPoint: ...
    def getRotation(self) -> float: ...
    def getTextLabelBackgroundColor(self) -> int: ...
    def getTextLabelFontSize(self) -> int: ...
    def getTextLabelForegroundColor(self) -> int: ...
    def hitTest(self, event: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def isDraggable(self) -> bool: ...
    def isFlat(self) -> bool: ...
    def isInfoWindowShown(self) -> bool: ...
    def moveToEventPosition(self, event: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> None: ...
    def onDetach(self, mapView: org.osmdroid.views.MapView, /) -> None: ...
    def onLongPress(self, event: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onMarkerClickDefault(self, marker: Marker, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onSingleTapConfirmed(self, event: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onTouchEvent(self, event: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def remove(self, mapView: org.osmdroid.views.MapView, /) -> None: ...
    def setAlpha(self, alpha: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setAnchor(self, anchorU: float | java.jfloat | java.lang.Float, anchorV: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setDraggable(self, draggable: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setFlat(self, flat: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setIcon(self, icon: android.graphics.drawable.Drawable, /) -> None: ...
    def setImage(self, image: android.graphics.drawable.Drawable, /) -> None: ...
    def setInfoWindow(self, infoWindow: org.osmdroid.views.overlay.infowindow.MarkerInfoWindow, /) -> None: ...
    def setInfoWindowAnchor(self, anchorU: float | java.jfloat | java.lang.Float, anchorV: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setOnMarkerClickListener(self, listener: Marker.OnMarkerClickListener, /) -> None: ...
    def setOnMarkerDragListener(self, listener: Marker.OnMarkerDragListener, /) -> None: ...
    def setPanToView(self, panToView: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setPosition(self, position: org.osmdroid.util.GeoPoint, /) -> None: ...
    def setRotation(self, rotation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setTextLabelBackgroundColor(self, mTextLabelBackgroundColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTextLabelFontSize(self, mTextLabelFontSize: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTextLabelForegroundColor(self, mTextLabelForegroundColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def showInfoWindow(self) -> None: ...

    class OnMarkerDragListener(java.lang.Object):
        def onMarkerDrag(self, arg1: Marker, /) -> None: ...
        def onMarkerDragEnd(self, arg1: Marker, /) -> None: ...
        def onMarkerDragStart(self, arg1: Marker, /) -> None: ...

    class OnMarkerClickListener(java.lang.Object):
        def onMarkerClick(self, arg1: Marker, arg2: org.osmdroid.views.MapView, /) -> bool: ...

class MinimapOverlay(TilesOverlay):
    @typing.overload
    def __init__(self, pContext: android.content.Context, pTileRequestCompleteHandler: android.os.Handler, /) -> None: ...
    @typing.overload
    def __init__(self, pContext: android.content.Context, pTileRequestCompleteHandler: android.os.Handler, pTileProvider: org.osmdroid.tileprovider.MapTileProviderBase, /) -> None: ...
    @typing.overload
    def __init__(self, pContext: android.content.Context, pTileRequestCompleteHandler: android.os.Handler, pTileProvider: org.osmdroid.tileprovider.MapTileProviderBase, pZoomDifference: int | java.jint | java.lang.Integer, /) -> None: ...
    def draw(self, c: android.graphics.Canvas, osmv: org.osmdroid.views.MapView, shadow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def getHeight(self) -> int: ...
    def getPadding(self) -> int: ...
    def getWidth(self) -> int: ...
    def getZoomDifference(self) -> int: ...
    def isOptionsMenuEnabled(self) -> bool: ...
    def onDoubleTap(self, pEvent: android.view.MotionEvent, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onLongPress(self, pEvent: android.view.MotionEvent, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onSingleTapUp(self, pEvent: android.view.MotionEvent, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onTileReadyToDraw(self, c: android.graphics.Canvas, currentMapTile: android.graphics.drawable.Drawable, tileRect: android.graphics.Rect, /) -> None: ...
    def setHeight(self, height: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPadding(self, padding: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTileSource(self, pTileSource: org.osmdroid.tileprovider.tilesource.ITileSource, /) -> None: ...
    def setWidth(self, width: int | java.jint | java.lang.Integer, /) -> None: ...
    def setZoomDifference(self, zoomDifference: int | java.jint | java.lang.Integer, /) -> None: ...

class NonAcceleratedOverlay(Overlay):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, ctx: android.content.Context, /) -> None: ...
    def draw(self, c: android.graphics.Canvas, osmv: org.osmdroid.views.MapView, shadow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def isUsingBackingBitmap(self) -> bool: ...
    def onDetach(self, mapView: org.osmdroid.views.MapView, /) -> None: ...
    @typing.overload
    def onDraw(self, arg1: android.graphics.Canvas, arg2: org.osmdroid.views.MapView, arg3: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def onDraw(self, c: android.graphics.Canvas, acceleratedCanvas: android.graphics.Canvas, osmv: org.osmdroid.views.MapView, shadow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class Overlay(org.osmdroid.views.util.constants.OverlayConstants):
    SHADOW_X_SKEW: typing.ClassVar[float] = ...
    SHADOW_Y_SCALE: typing.ClassVar[float] = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, ctx: android.content.Context, /) -> None: ...
    def draw(self, arg1: android.graphics.Canvas, arg2: org.osmdroid.views.MapView, arg3: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def drawAt(canvas: android.graphics.Canvas, drawable: android.graphics.drawable.Drawable, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, shadow: bool | java.jboolean | java.lang.Boolean, aMapOrientation: float | java.jfloat | java.lang.Float, /) -> None: ...
    @staticmethod
    def getSafeMenuId() -> int: ...
    @staticmethod
    def getSafeMenuIdSequence(count: int | java.jint | java.lang.Integer, /) -> int: ...
    def isEnabled(self) -> bool: ...
    def onDetach(self, mapView: org.osmdroid.views.MapView, /) -> None: ...
    def onDoubleTap(self, e: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onDoubleTapEvent(self, e: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onDown(self, e: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onFling(self, pEvent1: android.view.MotionEvent, pEvent2: android.view.MotionEvent, pVelocityX: float | java.jfloat | java.lang.Float, pVelocityY: float | java.jfloat | java.lang.Float, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onKeyDown(self, keyCode: int | java.jint | java.lang.Integer, event: android.view.KeyEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onKeyUp(self, keyCode: int | java.jint | java.lang.Integer, event: android.view.KeyEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onLongPress(self, e: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onScroll(self, pEvent1: android.view.MotionEvent, pEvent2: android.view.MotionEvent, pDistanceX: float | java.jfloat | java.lang.Float, pDistanceY: float | java.jfloat | java.lang.Float, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onShowPress(self, pEvent: android.view.MotionEvent, pMapView: org.osmdroid.views.MapView, /) -> None: ...
    def onSingleTapConfirmed(self, e: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onSingleTapUp(self, e: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onTouchEvent(self, event: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onTrackballEvent(self, event: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def setEnabled(self, pEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

    class Snappable(java.lang.Object):
        def onSnapToItem(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, arg3: android.graphics.Point, arg4: org.osmdroid.api.IMapView, /) -> bool: ...

class OverlayItem(java.lang.Object):
    ITEM_STATE_FOCUSED_MASK: typing.ClassVar[int] = ...
    ITEM_STATE_PRESSED_MASK: typing.ClassVar[int] = ...
    ITEM_STATE_SELECTED_MASK: typing.ClassVar[int] = ...
    DEFAULT_MARKER_SIZE: typing.ClassVar[android.graphics.Point] = ...
    mUid: str = ...
    mTitle: str = ...
    mSnippet: str = ...
    mGeoPoint: org.osmdroid.api.IGeoPoint = ...
    mMarker: android.graphics.drawable.Drawable = ...
    mHotspotPlace: OverlayItem.HotspotPlace = ...
    @typing.overload
    def __init__(self, aTitle: str | java.lang.String, aSnippet: str | java.lang.String, aGeoPoint: org.osmdroid.api.IGeoPoint, /) -> None: ...
    @typing.overload
    def __init__(self, aUid: str | java.lang.String, aTitle: str | java.lang.String, aDescription: str | java.lang.String, aGeoPoint: org.osmdroid.api.IGeoPoint, /) -> None: ...
    def getDrawable(self) -> android.graphics.drawable.Drawable: ...
    def getHeight(self) -> int: ...
    def getMarker(self, stateBitset: int | java.jint | java.lang.Integer, /) -> android.graphics.drawable.Drawable: ...
    def getMarkerHotspot(self) -> OverlayItem.HotspotPlace: ...
    def getPoint(self) -> org.osmdroid.api.IGeoPoint: ...
    def getSnippet(self) -> str: ...
    def getTitle(self) -> str: ...
    def getUid(self) -> str: ...
    def getWidth(self) -> int: ...
    def setMarker(self, marker: android.graphics.drawable.Drawable, /) -> None: ...
    def setMarkerHotspot(self, place: OverlayItem.HotspotPlace, /) -> None: ...
    @staticmethod
    def setState(drawable: android.graphics.drawable.Drawable, stateBitset: int | java.jint | java.lang.Integer, /) -> None: ...

    class HotspotPlace(java.lang.Enum[OverlayItem.HotspotPlace]):
        NONE: typing.ClassVar[OverlayItem.HotspotPlace] = ...
        CENTER: typing.ClassVar[OverlayItem.HotspotPlace] = ...
        BOTTOM_CENTER: typing.ClassVar[OverlayItem.HotspotPlace] = ...
        TOP_CENTER: typing.ClassVar[OverlayItem.HotspotPlace] = ...
        RIGHT_CENTER: typing.ClassVar[OverlayItem.HotspotPlace] = ...
        LEFT_CENTER: typing.ClassVar[OverlayItem.HotspotPlace] = ...
        UPPER_RIGHT_CORNER: typing.ClassVar[OverlayItem.HotspotPlace] = ...
        LOWER_RIGHT_CORNER: typing.ClassVar[OverlayItem.HotspotPlace] = ...
        UPPER_LEFT_CORNER: typing.ClassVar[OverlayItem.HotspotPlace] = ...
        LOWER_LEFT_CORNER: typing.ClassVar[OverlayItem.HotspotPlace] = ...
        @staticmethod
        def valueOf(name: str | java.lang.String, /) -> OverlayItem.HotspotPlace: ...
        @staticmethod
        def values() -> java.chaquopy.JavaArray[OverlayItem.HotspotPlace]: ...

class OverlayManager(java.util.List[Overlay]):
    def add(self, arg1: int | java.jint | java.lang.Integer, arg2: Overlay, /) -> None: ...
    def get(self, arg1: int | java.jint | java.lang.Integer, /) -> Overlay: ...
    def getTilesOverlay(self) -> TilesOverlay: ...
    def onCreateOptionsMenu(self, arg1: android.view.Menu, arg2: int | java.jint | java.lang.Integer, arg3: org.osmdroid.views.MapView, /) -> bool: ...
    def onDetach(self, arg1: org.osmdroid.views.MapView, /) -> None: ...
    def onDoubleTap(self, arg1: android.view.MotionEvent, arg2: org.osmdroid.views.MapView, /) -> bool: ...
    def onDoubleTapEvent(self, arg1: android.view.MotionEvent, arg2: org.osmdroid.views.MapView, /) -> bool: ...
    def onDown(self, arg1: android.view.MotionEvent, arg2: org.osmdroid.views.MapView, /) -> bool: ...
    def onDraw(self, arg1: android.graphics.Canvas, arg2: org.osmdroid.views.MapView, /) -> None: ...
    def onFling(self, arg1: android.view.MotionEvent, arg2: android.view.MotionEvent, arg3: float | java.jfloat | java.lang.Float, arg4: float | java.jfloat | java.lang.Float, arg5: org.osmdroid.views.MapView, /) -> bool: ...
    def onKeyDown(self, arg1: int | java.jint | java.lang.Integer, arg2: android.view.KeyEvent, arg3: org.osmdroid.views.MapView, /) -> bool: ...
    def onKeyUp(self, arg1: int | java.jint | java.lang.Integer, arg2: android.view.KeyEvent, arg3: org.osmdroid.views.MapView, /) -> bool: ...
    def onLongPress(self, arg1: android.view.MotionEvent, arg2: org.osmdroid.views.MapView, /) -> bool: ...
    def onOptionsItemSelected(self, arg1: android.view.MenuItem, arg2: int | java.jint | java.lang.Integer, arg3: org.osmdroid.views.MapView, /) -> bool: ...
    def onPrepareOptionsMenu(self, arg1: android.view.Menu, arg2: int | java.jint | java.lang.Integer, arg3: org.osmdroid.views.MapView, /) -> bool: ...
    def onScroll(self, arg1: android.view.MotionEvent, arg2: android.view.MotionEvent, arg3: float | java.jfloat | java.lang.Float, arg4: float | java.jfloat | java.lang.Float, arg5: org.osmdroid.views.MapView, /) -> bool: ...
    def onShowPress(self, arg1: android.view.MotionEvent, arg2: org.osmdroid.views.MapView, /) -> None: ...
    def onSingleTapConfirmed(self, arg1: android.view.MotionEvent, arg2: org.osmdroid.views.MapView, /) -> bool: ...
    def onSingleTapUp(self, arg1: android.view.MotionEvent, arg2: org.osmdroid.views.MapView, /) -> bool: ...
    def onSnapToItem(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, arg3: android.graphics.Point, arg4: org.osmdroid.api.IMapView, /) -> bool: ...
    def onTouchEvent(self, arg1: android.view.MotionEvent, arg2: org.osmdroid.views.MapView, /) -> bool: ...
    def onTrackballEvent(self, arg1: android.view.MotionEvent, arg2: org.osmdroid.views.MapView, /) -> bool: ...
    def overlays(self) -> java.util.List[Overlay]: ...
    def overlaysReversed(self) -> java.lang.Iterable[Overlay]: ...
    def remove(self, arg1: int | java.jint | java.lang.Integer, /) -> Overlay: ...
    def set(self, arg1: int | java.jint | java.lang.Integer, arg2: Overlay, /) -> Overlay: ...
    def setOptionsMenusEnabled(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setTilesOverlay(self, arg1: TilesOverlay, /) -> None: ...
    def size(self) -> int: ...

class OverlayWithIW(Overlay):
    mTitle: str = ...
    mSnippet: str = ...
    mSubDescription: str = ...
    mInfoWindow: org.osmdroid.views.overlay.infowindow.InfoWindow = ...
    mRelatedObject: java.lang.Object = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, ctx: android.content.Context, /) -> None: ...
    def closeInfoWindow(self) -> None: ...
    def getInfoWindow(self) -> org.osmdroid.views.overlay.infowindow.InfoWindow: ...
    def getRelatedObject(self) -> java.lang.Object: ...
    def getSnippet(self) -> str: ...
    def getSubDescription(self) -> str: ...
    def getTitle(self) -> str: ...
    def isInfoWindowOpen(self) -> bool: ...
    def onDestroy(self) -> None: ...
    def setInfoWindow(self, infoWindow: org.osmdroid.views.overlay.infowindow.InfoWindow, /) -> None: ...
    def setRelatedObject(self, relatedObject: java.lang.Object | int | bool | float | str, /) -> None: ...
    def setSnippet(self, snippet: str | java.lang.String, /) -> None: ...
    def setSubDescription(self, subDescription: str | java.lang.String, /) -> None: ...
    def setTitle(self, title: str | java.lang.String, /) -> None: ...

class PathOverlay(Overlay):
    mPaint: android.graphics.Paint = ...
    @typing.overload
    def __init__(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, color: int | java.jint | java.lang.Integer, width: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def __init__(self, color: int | java.jint | java.lang.Integer, ctx: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, color: int | java.jint | java.lang.Integer, width: float | java.jfloat | java.lang.Float, ctx: android.content.Context, /) -> None: ...
    @typing.overload
    def addGreatCircle(self, startPoint: org.osmdroid.util.GeoPoint, endPoint: org.osmdroid.util.GeoPoint, /) -> None: ...
    @typing.overload
    def addGreatCircle(self, startPoint: org.osmdroid.util.GeoPoint, endPoint: org.osmdroid.util.GeoPoint, numberOfPoints: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def addPoint(self, aPoint: org.osmdroid.api.IGeoPoint, /) -> None: ...
    @typing.overload
    def addPoint(self, aLatitude: float | java.jdouble | java.lang.Double, aLongitude: float | java.jdouble | java.lang.Double, /) -> None: ...
    @typing.overload
    def addPoints(self, aPoints: java.util.List[org.osmdroid.api.IGeoPoint], /) -> None: ...
    @typing.overload
    def addPoints(self, *aPoints: org.osmdroid.api.IGeoPoint) -> None: ...
    def clearPath(self) -> None: ...
    def draw(self, canvas: android.graphics.Canvas, mapView: org.osmdroid.views.MapView, shadow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def getNumberOfPoints(self) -> int: ...
    def getPaint(self) -> android.graphics.Paint: ...
    def setAlpha(self, a: int | java.jint | java.lang.Integer, /) -> None: ...
    def setColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPaint(self, pPaint: android.graphics.Paint, /) -> None: ...

class Polygon(OverlayWithIW):
    mFillPaint: android.graphics.Paint = ...
    mOutlinePaint: android.graphics.Paint = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, ctx: android.content.Context, /) -> None: ...
    def contains(self, event: android.view.MotionEvent, /) -> bool: ...
    def draw(self, canvas: android.graphics.Canvas, mapView: org.osmdroid.views.MapView, shadow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def getFillColor(self) -> int: ...
    def getHoles(self) -> java.util.List[java.util.ArrayList[org.osmdroid.util.GeoPoint]]: ...
    def getOutlinePaint(self) -> android.graphics.Paint: ...
    def getPoints(self) -> java.util.List[org.osmdroid.util.GeoPoint]: ...
    def getStrokeColor(self) -> int: ...
    def getStrokeWidth(self) -> float: ...
    def isVisible(self) -> bool: ...
    def onDetach(self, mapView: org.osmdroid.views.MapView, /) -> None: ...
    def onSingleTapConfirmed(self, event: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    @staticmethod
    def pointsAsCircle(center: org.osmdroid.util.GeoPoint, radiusInMeters: float | java.jdouble | java.lang.Double, /) -> java.util.ArrayList[org.osmdroid.util.GeoPoint]: ...
    @typing.overload
    @staticmethod
    def pointsAsRect(rectangle: org.osmdroid.util.BoundingBox, /) -> java.util.ArrayList[org.osmdroid.api.IGeoPoint]: ...
    @typing.overload
    @staticmethod
    def pointsAsRect(rectangle: org.osmdroid.util.BoundingBoxE6, /) -> java.util.ArrayList[org.osmdroid.api.IGeoPoint]: ...
    @typing.overload
    @staticmethod
    def pointsAsRect(center: org.osmdroid.util.GeoPoint, lengthInMeters: float | java.jdouble | java.lang.Double, widthInMeters: float | java.jdouble | java.lang.Double, /) -> java.util.ArrayList[org.osmdroid.api.IGeoPoint]: ...
    def setFillColor(self, fillColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setHoles(self, holes: java.util.List[java.util.List[org.osmdroid.util.GeoPoint]], /) -> None: ...
    def setPoints(self, points: java.util.List[org.osmdroid.util.GeoPoint], /) -> None: ...
    def setStrokeColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    def setStrokeWidth(self, width: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setVisible(self, visible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class Polyline(OverlayWithIW):
    mGeodesic: bool = ...
    mPaint: android.graphics.Paint = ...
    mRepeatPath: bool = ...
    mOnClickListener: Polyline.OnClickListener = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, ctx: android.content.Context, /) -> None: ...
    def addGreatCircle(self, startPoint: org.osmdroid.util.GeoPoint, endPoint: org.osmdroid.util.GeoPoint, numberOfPoints: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def addPoint(self, aPoint: org.osmdroid.util.GeoPoint, /) -> None: ...
    @typing.overload
    def addPoint(self, aLatitudeE6: int | java.jint | java.lang.Integer, aLongitudeE6: int | java.jint | java.lang.Integer, /) -> None: ...
    def clearPath(self) -> None: ...
    def draw(self, canvas: android.graphics.Canvas, mapView: org.osmdroid.views.MapView, shadow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def drawOld(self, canvas: android.graphics.Canvas, mapView: org.osmdroid.views.MapView, shadow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def getColor(self) -> int: ...
    def getNumberOfPoints(self) -> int: ...
    def getPaint(self) -> android.graphics.Paint: ...
    def getPoints(self) -> java.util.List[org.osmdroid.util.GeoPoint]: ...
    def getWidth(self) -> float: ...
    def isCloseTo(self, point: org.osmdroid.util.GeoPoint, tolerance: float | java.jdouble | java.lang.Double, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def isGeodesic(self) -> bool: ...
    def isVisible(self) -> bool: ...
    def onClickDefault(self, polyline: Polyline, mapView: org.osmdroid.views.MapView, eventPos: org.osmdroid.util.GeoPoint, /) -> bool: ...
    def onDetach(self, mapView: org.osmdroid.views.MapView, /) -> None: ...
    def onSingleTapConfirmed(self, event: android.view.MotionEvent, mapView: org.osmdroid.views.MapView, /) -> bool: ...
    def precomputePoints(self, pj: org.osmdroid.views.Projection, /) -> None: ...
    def setColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    def setGeodesic(self, geodesic: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setOnClickListener(self, listener: Polyline.OnClickListener, /) -> None: ...
    def setPoints(self, points: java.util.List[org.osmdroid.util.GeoPoint], /) -> None: ...
    def setVisible(self, visible: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setWidth(self, width: float | java.jfloat | java.lang.Float, /) -> None: ...
    def showInfoWindow(self, position: org.osmdroid.util.GeoPoint, /) -> None: ...

    class OnClickListener(java.lang.Object):
        def onClick(self, arg1: Polyline, arg2: org.osmdroid.views.MapView, arg3: org.osmdroid.util.GeoPoint, /) -> bool: ...

class ScaleBarOverlay(Overlay, org.osmdroid.util.constants.GeoConstants):
    alignBottom: bool = ...
    alignRight: bool = ...
    barPath: android.graphics.Path = ...
    latitudeBarRect: android.graphics.Rect = ...
    longitudeBarRect: android.graphics.Rect = ...
    xdpi: float = ...
    ydpi: float = ...
    screenWidth: int = ...
    screenHeight: int = ...
    def __init__(self, mapView: org.osmdroid.views.MapView, /) -> None: ...
    def disableScaleBar(self) -> None: ...
    def draw(self, c: android.graphics.Canvas, mapView: org.osmdroid.views.MapView, shadow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def drawLatitudeScale(self, latitude: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def drawLongitudeScale(self, longitude: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def enableScaleBar(self) -> None: ...
    def getBarPaint(self) -> android.graphics.Paint: ...
    def getTextPaint(self) -> android.graphics.Paint: ...
    def getUnitsOfMeasure(self) -> ScaleBarOverlay.UnitsOfMeasure: ...
    def onDetach(self, mapView: org.osmdroid.views.MapView, /) -> None: ...
    def rebuildBarPath(self, projection: org.osmdroid.views.Projection, /) -> None: ...
    def scaleBarLengthText(self, meters: int | java.jint | java.lang.Integer, /) -> str: ...
    def setAlignBottom(self, alignBottom: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setAlignRight(self, alignRight: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setBackgroundPaint(self, pBgPaint: android.graphics.Paint, /) -> None: ...
    def setBarPaint(self, pBarPaint: android.graphics.Paint, /) -> None: ...
    def setCentred(self, centred: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setEnableAdjustLength(self, adjustLength: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setLineWidth(self, width: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setMaxLength(self, pMaxLengthInCm: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setMinZoom(self, zoom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setScaleBarOffset(self, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTextPaint(self, pTextPaint: android.graphics.Paint, /) -> None: ...
    def setTextSize(self, size: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setUnitsOfMeasure(self, unitsOfMeasure: ScaleBarOverlay.UnitsOfMeasure, /) -> None: ...

    class UnitsOfMeasure(java.lang.Enum[ScaleBarOverlay.UnitsOfMeasure]):
        metric: typing.ClassVar[ScaleBarOverlay.UnitsOfMeasure] = ...
        imperial: typing.ClassVar[ScaleBarOverlay.UnitsOfMeasure] = ...
        nautical: typing.ClassVar[ScaleBarOverlay.UnitsOfMeasure] = ...
        @staticmethod
        def valueOf(name: str | java.lang.String, /) -> ScaleBarOverlay.UnitsOfMeasure: ...
        @staticmethod
        def values() -> java.chaquopy.JavaArray[ScaleBarOverlay.UnitsOfMeasure]: ...

class TilesOverlay(Overlay, IOverlayMenuProvider):
    MENU_MAP_MODE: typing.ClassVar[int] = ...
    MENU_TILE_SOURCE_STARTING_ID: typing.ClassVar[int] = ...
    MENU_OFFLINE: typing.ClassVar[int] = ...
    mTileProvider: org.osmdroid.tileprovider.MapTileProviderBase = ...
    userSelectedLoadingDrawable: android.graphics.drawable.Drawable = ...
    mDebugPaint: android.graphics.Paint = ...
    INVERT_COLORS: typing.ClassVar[android.graphics.ColorFilter] = ...
    def __init__(self, aTileProvider: org.osmdroid.tileprovider.MapTileProviderBase, aContext: android.content.Context, /) -> None: ...
    def draw(self, c: android.graphics.Canvas, osmv: org.osmdroid.views.MapView, shadow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def drawTiles(self, c: android.graphics.Canvas, projection: org.osmdroid.views.Projection, zoomLevel: int | java.jint | java.lang.Integer, tileSizePx: int | java.jint | java.lang.Integer, viewPort: android.graphics.Rect, /) -> None: ...
    def getLoadingBackgroundColor(self) -> int: ...
    def getLoadingLineColor(self) -> int: ...
    def getMaximumZoomLevel(self) -> int: ...
    def getMinimumZoomLevel(self) -> int: ...
    def getOvershootTileCache(self) -> int: ...
    def isOptionsMenuEnabled(self) -> bool: ...
    def onCreateOptionsMenu(self, pMenu: android.view.Menu, pMenuIdOffset: int | java.jint | java.lang.Integer, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onDetach(self, pMapView: org.osmdroid.views.MapView, /) -> None: ...
    def onOptionsItemSelected(self, pItem: android.view.MenuItem, pMenuIdOffset: int | java.jint | java.lang.Integer, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onPrepareOptionsMenu(self, pMenu: android.view.Menu, pMenuIdOffset: int | java.jint | java.lang.Integer, pMapView: org.osmdroid.views.MapView, /) -> bool: ...
    def onTileReadyToDraw(self, c: android.graphics.Canvas, currentMapTile: android.graphics.drawable.Drawable, tileRect: android.graphics.Rect, /) -> None: ...
    def setColorFilter(self, filter: android.graphics.ColorFilter, /) -> None: ...
    def setLoadingBackgroundColor(self, pLoadingBackgroundColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setLoadingDrawable(self, drawable: android.graphics.drawable.Drawable, /) -> None: ...
    def setLoadingLineColor(self, pLoadingLineColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setOptionsMenuEnabled(self, pOptionsMenuEnabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setOvershootTileCache(self, overshootTileCache: int | java.jint | java.lang.Integer, /) -> None: ...
    def setUseDataConnection(self, aMode: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def useDataConnection(self) -> bool: ...
