import typing

import java.chaquopy
import java.lang
import java.lang.reflect

class BoundaryInterfaceReflectionUtil(java.lang.Object):
    def __init__(self) -> None: ...
    _castToSuppLibClass__T = typing.TypeVar('_castToSuppLibClass__T')  # <T>
    @staticmethod
    def castToSuppLibClass(clazz: typing.Type[_castToSuppLibClass__T], invocationHandler: java.lang.reflect.InvocationHandler, /) -> _castToSuppLibClass__T: ...
    @staticmethod
    def containsFeature(features: java.chaquopy.JavaArray[java.lang.String], soughtFeature: str | java.lang.String, /) -> bool: ...
    @staticmethod
    def createInvocationHandlerFor(delegate: java.lang.Object | int | bool | float | str, /) -> java.lang.reflect.InvocationHandler: ...
    @staticmethod
    def dupeMethod(method: java.lang.reflect.Method, delegateLoader: java.lang.ClassLoader, /) -> java.lang.reflect.Method: ...
    @staticmethod
    def getDelegateFromInvocationHandler(invocationHandler: java.lang.reflect.InvocationHandler, /) -> java.lang.Object: ...

class Features(java.lang.Object):
    VISUAL_STATE_CALLBACK: typing.ClassVar[str] = ...
    RECEIVE_WEB_RESOURCE_ERROR: typing.ClassVar[str] = ...
    RECEIVE_HTTP_ERROR: typing.ClassVar[str] = ...
    SAFE_BROWSING_HIT: typing.ClassVar[str] = ...
    SHOULD_OVERRIDE_WITH_REDIRECTS: typing.ClassVar[str] = ...
    OFF_SCREEN_PRERASTER: typing.ClassVar[str] = ...
    SAFE_BROWSING_ENABLE: typing.ClassVar[str] = ...
    DISABLED_ACTION_MODE_MENU_ITEMS: typing.ClassVar[str] = ...
    START_SAFE_BROWSING: typing.ClassVar[str] = ...
    SAFE_BROWSING_WHITELIST: typing.ClassVar[str] = ...
    SAFE_BROWSING_PRIVACY_POLICY_URL: typing.ClassVar[str] = ...
    SERVICE_WORKER_BASIC_USAGE: typing.ClassVar[str] = ...
    SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST: typing.ClassVar[str] = ...
    SERVICE_WORKER_CACHE_MODE: typing.ClassVar[str] = ...
    SERVICE_WORKER_CONTENT_ACCESS: typing.ClassVar[str] = ...
    SERVICE_WORKER_FILE_ACCESS: typing.ClassVar[str] = ...
    SERVICE_WORKER_BLOCK_NETWORK_LOADS: typing.ClassVar[str] = ...
    WEB_RESOURCE_REQUEST_IS_REDIRECT: typing.ClassVar[str] = ...
    WEB_RESOURCE_ERROR_GET_DESCRIPTION: typing.ClassVar[str] = ...
    WEB_RESOURCE_ERROR_GET_CODE: typing.ClassVar[str] = ...
    SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY: typing.ClassVar[str] = ...
    SAFE_BROWSING_RESPONSE_PROCEED: typing.ClassVar[str] = ...
    SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL: typing.ClassVar[str] = ...
    WEB_MESSAGE_PORT_POST_MESSAGE: typing.ClassVar[str] = ...
    WEB_MESSAGE_PORT_CLOSE: typing.ClassVar[str] = ...
    WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK: typing.ClassVar[str] = ...
    CREATE_WEB_MESSAGE_CHANNEL: typing.ClassVar[str] = ...
    POST_WEB_MESSAGE: typing.ClassVar[str] = ...
    WEB_MESSAGE_CALLBACK_ON_MESSAGE: typing.ClassVar[str] = ...
