import java.lang
import org.apache.http.client

class HttpClientFactory(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def createHttpClient() -> org.apache.http.client.HttpClient: ...
    @staticmethod
    def setFactoryInstance(aHttpClientFactory: IHttpClientFactory, /) -> None: ...

class IHttpClientFactory(java.lang.Object):
    def createHttpClient(self) -> org.apache.http.client.HttpClient: ...
