import typing

import java
import java.chaquopy
import java.io
import java.lang
import java.net
import java.nio.charset
import java.util
import jet

class IoPackage-Files-fb9d69f1(java.lang.Object):
    @staticmethod
    def appendBytes(receiver: java.io.File, data: java.chaquopy.JavaArrayJByte, /) -> None: ...
    @typing.overload
    @staticmethod
    def appendText(receiver: java.io.File, text: str | java.lang.String, encoding: str | java.lang.String, /) -> None: ...
    @typing.overload
    @staticmethod
    def appendText(receiver: java.io.File, text: str | java.lang.String, encoding: java.nio.charset.Charset, /) -> None: ...
    @staticmethod
    def appendText$default(arg1: java.io.File, arg2: str | java.lang.String, arg3: str | java.lang.String, arg4: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def copyTo(receiver: java.io.File, file: java.io.File, bufferSize: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def copyTo$default(arg1: java.io.File, arg2: java.io.File, arg3: int | java.jint | java.lang.Integer, arg4: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def forEachBlock(receiver: java.io.File, closure: jet.Function2[java.chaquopy.JavaArrayJByte, int, jet.Unit], /) -> None: ...
    @staticmethod
    def forEachLine(receiver: java.io.File, charset: str | java.lang.String, closure: jet.Function1[str, jet.Unit], /) -> None: ...
    @staticmethod
    def forEachLine$default(arg1: java.io.File, arg2: str | java.lang.String, arg3: jet.Function1, arg4: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def getCanonicalPath(receiver: java.io.File, /) -> str: ...
    @staticmethod
    def getDirectory(receiver: java.io.File, /) -> java.io.File: ...
    @staticmethod
    def getExtension(receiver: java.io.File, /) -> str: ...
    @staticmethod
    def getName(receiver: java.io.File, /) -> str: ...
    @staticmethod
    def getPath(receiver: java.io.File, /) -> str: ...
    @staticmethod
    def isDescendant(receiver: java.io.File, file: java.io.File, /) -> bool: ...
    @staticmethod
    def listFiles(receiver: java.io.File, filter: jet.Function1[java.io.File, bool], /) -> java.chaquopy.JavaArray[java.io.File]: ...
    @staticmethod
    def readBytes(receiver: java.io.File, /) -> java.chaquopy.JavaArrayJByte: ...
    @staticmethod
    def readLines(receiver: java.io.File, charset: str | java.lang.String, /) -> java.util.List[java.lang.String]: ...
    @staticmethod
    def readLines$default(arg1: java.io.File, arg2: str | java.lang.String, arg3: int | java.jint | java.lang.Integer, /) -> java.util.List: ...
    @typing.overload
    @staticmethod
    def readText(receiver: java.io.File, encoding: str | java.lang.String, /) -> str: ...
    @typing.overload
    @staticmethod
    def readText(receiver: java.io.File, encoding: java.nio.charset.Charset, /) -> str: ...
    @staticmethod
    def readText$default(arg1: java.io.File, arg2: str | java.lang.String, arg3: int | java.jint | java.lang.Integer, /) -> str: ...
    @staticmethod
    def reader(receiver: java.io.File, /) -> java.io.FileReader: ...
    @staticmethod
    def recurse(receiver: java.io.File, block: jet.Function1[java.io.File, jet.Unit], /) -> None: ...
    @staticmethod
    def relativePath(receiver: java.io.File, descendant: java.io.File, /) -> str: ...
    @staticmethod
    def writeBytes(receiver: java.io.File, data: java.chaquopy.JavaArrayJByte, /) -> None: ...
    @typing.overload
    @staticmethod
    def writeText(receiver: java.io.File, text: str | java.lang.String, encoding: str | java.lang.String, /) -> None: ...
    @typing.overload
    @staticmethod
    def writeText(receiver: java.io.File, text: str | java.lang.String, encoding: java.nio.charset.Charset, /) -> None: ...
    @staticmethod
    def writeText$default(arg1: java.io.File, arg2: str | java.lang.String, arg3: str | java.lang.String, arg4: int | java.jint | java.lang.Integer, /) -> None: ...

class IoPackage-JIO-4bdd52f8(java.lang.Object):
    @typing.overload
    @staticmethod
    def buffered(receiver: java.io.InputStream, bufferSize: int | java.jint | java.lang.Integer, /) -> java.io.InputStream: ...
    @typing.overload
    @staticmethod
    def buffered(receiver: java.io.OutputStream, bufferSize: int | java.jint | java.lang.Integer, /) -> java.io.BufferedOutputStream: ...
    @typing.overload
    @staticmethod
    def buffered(receiver: java.io.Reader, bufferSize: int | java.jint | java.lang.Integer, /) -> java.io.BufferedReader: ...
    @typing.overload
    @staticmethod
    def buffered(receiver: java.io.Writer, bufferSize: int | java.jint | java.lang.Integer, /) -> java.io.BufferedWriter: ...
    @typing.overload
    @staticmethod
    def buffered$default(arg1: java.io.InputStream, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, /) -> java.io.InputStream: ...
    @typing.overload
    @staticmethod
    def buffered$default(arg1: java.io.OutputStream, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, /) -> java.io.BufferedOutputStream: ...
    @typing.overload
    @staticmethod
    def buffered$default(arg1: java.io.Reader, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, /) -> java.io.BufferedReader: ...
    @typing.overload
    @staticmethod
    def buffered$default(arg1: java.io.Writer, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, /) -> java.io.BufferedWriter: ...
    @typing.overload
    @staticmethod
    def copyTo(receiver: java.io.InputStream, out: java.io.OutputStream, bufferSize: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def copyTo(receiver: java.io.Reader, out: java.io.Writer, bufferSize: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def copyTo$default(arg1: java.io.InputStream, arg2: java.io.OutputStream, arg3: int | java.jint | java.lang.Integer, arg4: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def copyTo$default(arg1: java.io.Reader, arg2: java.io.Writer, arg3: int | java.jint | java.lang.Integer, arg4: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def forEachLine(receiver: java.io.Reader, block: jet.Function1[str, jet.Unit], /) -> None: ...
    @staticmethod
    def getDefaultBufferSize() -> int: ...
    @staticmethod
    def getDefaultCharset() -> java.nio.charset.Charset: ...
    @staticmethod
    def getStdin() -> java.io.BufferedReader: ...
    @staticmethod
    def iterator(receiver: java.io.InputStream, /) -> jet.ByteIterator: ...
    @staticmethod
    def lineIterator(receiver: java.io.BufferedReader, /) -> java.util.Iterator[java.lang.String]: ...
    @typing.overload
    @staticmethod
    def print_(message: int | java.jbyte | java.lang.Byte, /) -> None: ...
    @typing.overload
    @staticmethod
    def print_(message: str | java.jchar | java.lang.Character, /) -> None: ...
    @typing.overload
    @staticmethod
    def print_(message: float | java.jdouble | java.lang.Double, /) -> None: ...
    @typing.overload
    @staticmethod
    def print_(message: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    @staticmethod
    def print_(message: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    @staticmethod
    def print_(message: int | java.jlong | java.lang.Long, /) -> None: ...
    @typing.overload
    @staticmethod
    def print_(message: java.lang.Object | int | bool | float | str, /) -> None: ...
    @typing.overload
    @staticmethod
    def print_(message: int | java.jshort | java.lang.Short, /) -> None: ...
    @typing.overload
    @staticmethod
    def print_(message: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    @staticmethod
    def print_(message: java.chaquopy.JavaArrayJChar, /) -> None: ...
    @typing.overload
    @staticmethod
    def println() -> None: ...
    @typing.overload
    @staticmethod
    def println(message: int | java.jbyte | java.lang.Byte, /) -> None: ...
    @typing.overload
    @staticmethod
    def println(message: str | java.jchar | java.lang.Character, /) -> None: ...
    @typing.overload
    @staticmethod
    def println(message: float | java.jdouble | java.lang.Double, /) -> None: ...
    @typing.overload
    @staticmethod
    def println(message: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    @staticmethod
    def println(message: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    @staticmethod
    def println(message: int | java.jlong | java.lang.Long, /) -> None: ...
    @typing.overload
    @staticmethod
    def println(message: java.lang.Object | int | bool | float | str, /) -> None: ...
    @typing.overload
    @staticmethod
    def println(message: int | java.jshort | java.lang.Short, /) -> None: ...
    @typing.overload
    @staticmethod
    def println(message: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    @staticmethod
    def println(message: java.chaquopy.JavaArrayJChar, /) -> None: ...
    @typing.overload
    @staticmethod
    def readBytes(receiver: java.net.URL, /) -> java.chaquopy.JavaArrayJByte: ...
    @typing.overload
    @staticmethod
    def readBytes(receiver: java.io.InputStream, estimatedSize: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJByte: ...
    @staticmethod
    def readBytes$default(arg1: java.io.InputStream, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJByte: ...
    @staticmethod
    def readLine() -> str: ...
    @typing.overload
    @staticmethod
    def readText(receiver: java.io.Reader, /) -> str: ...
    @typing.overload
    @staticmethod
    def readText(receiver: java.net.URL, encoding: str | java.lang.String, /) -> str: ...
    @typing.overload
    @staticmethod
    def readText(receiver: java.net.URL, encoding: java.nio.charset.Charset, /) -> str: ...
    @staticmethod
    def readText$default(arg1: java.net.URL, arg2: str | java.lang.String, arg3: int | java.jint | java.lang.Integer, /) -> str: ...
    @typing.overload
    @staticmethod
    def reader(receiver: java.io.InputStream, encoding: str | java.lang.String, /) -> java.io.InputStreamReader: ...
    @typing.overload
    @staticmethod
    def reader(receiver: java.io.InputStream, encoding: java.nio.charset.Charset, /) -> java.io.InputStreamReader: ...
    @typing.overload
    @staticmethod
    def reader(receiver: java.io.InputStream, encoding: java.nio.charset.CharsetDecoder, /) -> java.io.InputStreamReader: ...
    @staticmethod
    def reader$default(arg1: java.io.InputStream, arg2: java.nio.charset.Charset, arg3: int | java.jint | java.lang.Integer, /) -> java.io.InputStreamReader: ...
    _use__T = typing.TypeVar('_use__T')  # <T>
    _use__R = typing.TypeVar('_use__R')  # <R>
    @staticmethod
    def use(receiver: _use__T, block: jet.Function1[_use__T, _use__R], /) -> _use__R: ...
    _useLines__T = typing.TypeVar('_useLines__T')  # <T>
    @staticmethod
    def useLines(receiver: java.io.Reader, block: jet.Function1[java.util.Iterator[str], _useLines__T], /) -> _useLines__T: ...
    @typing.overload
    @staticmethod
    def writer(receiver: java.io.OutputStream, encoding: str | java.lang.String, /) -> java.io.OutputStreamWriter: ...
    @typing.overload
    @staticmethod
    def writer(receiver: java.io.OutputStream, encoding: java.nio.charset.Charset, /) -> java.io.OutputStreamWriter: ...
    @typing.overload
    @staticmethod
    def writer(receiver: java.io.OutputStream, encoding: java.nio.charset.CharsetEncoder, /) -> java.io.OutputStreamWriter: ...
    @staticmethod
    def writer$default(arg1: java.io.OutputStream, arg2: java.nio.charset.Charset, arg3: int | java.jint | java.lang.Integer, /) -> java.io.OutputStreamWriter: ...

class IoPackage(java.lang.Object):
    @staticmethod
    def appendBytes(receiver: java.io.File, data: java.chaquopy.JavaArrayJByte, /) -> None: ...
    @typing.overload
    @staticmethod
    def appendText(receiver: java.io.File, text: str | java.lang.String, encoding: str | java.lang.String, /) -> None: ...
    @typing.overload
    @staticmethod
    def appendText(receiver: java.io.File, text: str | java.lang.String, encoding: java.nio.charset.Charset, /) -> None: ...
    @staticmethod
    def appendText$default(arg1: java.io.File, arg2: str | java.lang.String, arg3: str | java.lang.String, arg4: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    @staticmethod
    def buffered(receiver: java.io.InputStream, bufferSize: int | java.jint | java.lang.Integer, /) -> java.io.InputStream: ...
    @typing.overload
    @staticmethod
    def buffered(receiver: java.io.OutputStream, bufferSize: int | java.jint | java.lang.Integer, /) -> java.io.BufferedOutputStream: ...
    @typing.overload
    @staticmethod
    def buffered(receiver: java.io.Reader, bufferSize: int | java.jint | java.lang.Integer, /) -> java.io.BufferedReader: ...
    @typing.overload
    @staticmethod
    def buffered(receiver: java.io.Writer, bufferSize: int | java.jint | java.lang.Integer, /) -> java.io.BufferedWriter: ...
    @typing.overload
    @staticmethod
    def buffered$default(arg1: java.io.InputStream, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, /) -> java.io.InputStream: ...
    @typing.overload
    @staticmethod
    def buffered$default(arg1: java.io.OutputStream, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, /) -> java.io.BufferedOutputStream: ...
    @typing.overload
    @staticmethod
    def buffered$default(arg1: java.io.Reader, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, /) -> java.io.BufferedReader: ...
    @typing.overload
    @staticmethod
    def buffered$default(arg1: java.io.Writer, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, /) -> java.io.BufferedWriter: ...
    @typing.overload
    @staticmethod
    def copyTo(receiver: java.io.File, file: java.io.File, bufferSize: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def copyTo(receiver: java.io.InputStream, out: java.io.OutputStream, bufferSize: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def copyTo(receiver: java.io.Reader, out: java.io.Writer, bufferSize: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def copyTo$default(arg1: java.io.File, arg2: java.io.File, arg3: int | java.jint | java.lang.Integer, arg4: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def copyTo$default(arg1: java.io.InputStream, arg2: java.io.OutputStream, arg3: int | java.jint | java.lang.Integer, arg4: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def copyTo$default(arg1: java.io.Reader, arg2: java.io.Writer, arg3: int | java.jint | java.lang.Integer, arg4: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def forEachBlock(receiver: java.io.File, closure: jet.Function2[java.chaquopy.JavaArrayJByte, int, jet.Unit], /) -> None: ...
    @typing.overload
    @staticmethod
    def forEachLine(receiver: java.io.Reader, block: jet.Function1[str, jet.Unit], /) -> None: ...
    @typing.overload
    @staticmethod
    def forEachLine(receiver: java.io.File, charset: str | java.lang.String, closure: jet.Function1[str, jet.Unit], /) -> None: ...
    @staticmethod
    def forEachLine$default(arg1: java.io.File, arg2: str | java.lang.String, arg3: jet.Function1, arg4: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def getCanonicalPath(receiver: java.io.File, /) -> str: ...
    @staticmethod
    def getDefaultBufferSize() -> int: ...
    @staticmethod
    def getDefaultCharset() -> java.nio.charset.Charset: ...
    @staticmethod
    def getDirectory(receiver: java.io.File, /) -> java.io.File: ...
    @staticmethod
    def getExtension(receiver: java.io.File, /) -> str: ...
    @staticmethod
    def getName(receiver: java.io.File, /) -> str: ...
    @staticmethod
    def getPath(receiver: java.io.File, /) -> str: ...
    @staticmethod
    def getStdin() -> java.io.BufferedReader: ...
    @staticmethod
    def isDescendant(receiver: java.io.File, file: java.io.File, /) -> bool: ...
    @staticmethod
    def iterator(receiver: java.io.InputStream, /) -> jet.ByteIterator: ...
    @staticmethod
    def lineIterator(receiver: java.io.BufferedReader, /) -> java.util.Iterator[java.lang.String]: ...
    @staticmethod
    def listFiles(receiver: java.io.File, filter: jet.Function1[java.io.File, bool], /) -> java.chaquopy.JavaArray[java.io.File]: ...
    @typing.overload
    @staticmethod
    def print_(message: int | java.jbyte | java.lang.Byte, /) -> None: ...
    @typing.overload
    @staticmethod
    def print_(message: str | java.jchar | java.lang.Character, /) -> None: ...
    @typing.overload
    @staticmethod
    def print_(message: float | java.jdouble | java.lang.Double, /) -> None: ...
    @typing.overload
    @staticmethod
    def print_(message: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    @staticmethod
    def print_(message: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    @staticmethod
    def print_(message: int | java.jlong | java.lang.Long, /) -> None: ...
    @typing.overload
    @staticmethod
    def print_(message: java.lang.Object | int | bool | float | str, /) -> None: ...
    @typing.overload
    @staticmethod
    def print_(message: int | java.jshort | java.lang.Short, /) -> None: ...
    @typing.overload
    @staticmethod
    def print_(message: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    @staticmethod
    def print_(message: java.chaquopy.JavaArrayJChar, /) -> None: ...
    @typing.overload
    @staticmethod
    def println() -> None: ...
    @typing.overload
    @staticmethod
    def println(message: int | java.jbyte | java.lang.Byte, /) -> None: ...
    @typing.overload
    @staticmethod
    def println(message: str | java.jchar | java.lang.Character, /) -> None: ...
    @typing.overload
    @staticmethod
    def println(message: float | java.jdouble | java.lang.Double, /) -> None: ...
    @typing.overload
    @staticmethod
    def println(message: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    @staticmethod
    def println(message: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    @staticmethod
    def println(message: int | java.jlong | java.lang.Long, /) -> None: ...
    @typing.overload
    @staticmethod
    def println(message: java.lang.Object | int | bool | float | str, /) -> None: ...
    @typing.overload
    @staticmethod
    def println(message: int | java.jshort | java.lang.Short, /) -> None: ...
    @typing.overload
    @staticmethod
    def println(message: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    @staticmethod
    def println(message: java.chaquopy.JavaArrayJChar, /) -> None: ...
    @typing.overload
    @staticmethod
    def readBytes(receiver: java.io.File, /) -> java.chaquopy.JavaArrayJByte: ...
    @typing.overload
    @staticmethod
    def readBytes(receiver: java.net.URL, /) -> java.chaquopy.JavaArrayJByte: ...
    @typing.overload
    @staticmethod
    def readBytes(receiver: java.io.InputStream, estimatedSize: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJByte: ...
    @staticmethod
    def readBytes$default(arg1: java.io.InputStream, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJByte: ...
    @staticmethod
    def readLine() -> str: ...
    @staticmethod
    def readLines(receiver: java.io.File, charset: str | java.lang.String, /) -> java.util.List[java.lang.String]: ...
    @staticmethod
    def readLines$default(arg1: java.io.File, arg2: str | java.lang.String, arg3: int | java.jint | java.lang.Integer, /) -> java.util.List: ...
    @typing.overload
    @staticmethod
    def readText(receiver: java.io.Reader, /) -> str: ...
    @typing.overload
    @staticmethod
    def readText(receiver: java.io.File, encoding: str | java.lang.String, /) -> str: ...
    @typing.overload
    @staticmethod
    def readText(receiver: java.io.File, encoding: java.nio.charset.Charset, /) -> str: ...
    @typing.overload
    @staticmethod
    def readText(receiver: java.net.URL, encoding: str | java.lang.String, /) -> str: ...
    @typing.overload
    @staticmethod
    def readText(receiver: java.net.URL, encoding: java.nio.charset.Charset, /) -> str: ...
    @typing.overload
    @staticmethod
    def readText$default(arg1: java.io.File, arg2: str | java.lang.String, arg3: int | java.jint | java.lang.Integer, /) -> str: ...
    @typing.overload
    @staticmethod
    def readText$default(arg1: java.net.URL, arg2: str | java.lang.String, arg3: int | java.jint | java.lang.Integer, /) -> str: ...
    @typing.overload
    @staticmethod
    def reader(receiver: java.io.File, /) -> java.io.FileReader: ...
    @typing.overload
    @staticmethod
    def reader(receiver: java.io.InputStream, encoding: str | java.lang.String, /) -> java.io.InputStreamReader: ...
    @typing.overload
    @staticmethod
    def reader(receiver: java.io.InputStream, encoding: java.nio.charset.Charset, /) -> java.io.InputStreamReader: ...
    @typing.overload
    @staticmethod
    def reader(receiver: java.io.InputStream, encoding: java.nio.charset.CharsetDecoder, /) -> java.io.InputStreamReader: ...
    @staticmethod
    def reader$default(arg1: java.io.InputStream, arg2: java.nio.charset.Charset, arg3: int | java.jint | java.lang.Integer, /) -> java.io.InputStreamReader: ...
    @staticmethod
    def recurse(receiver: java.io.File, block: jet.Function1[java.io.File, jet.Unit], /) -> None: ...
    @staticmethod
    def relativePath(receiver: java.io.File, descendant: java.io.File, /) -> str: ...
    _use__T = typing.TypeVar('_use__T')  # <T>
    _use__R = typing.TypeVar('_use__R')  # <R>
    @staticmethod
    def use(receiver: _use__T, block: jet.Function1[_use__T, _use__R], /) -> _use__R: ...
    _useLines__T = typing.TypeVar('_useLines__T')  # <T>
    @staticmethod
    def useLines(receiver: java.io.Reader, block: jet.Function1[java.util.Iterator[str], _useLines__T], /) -> _useLines__T: ...
    @staticmethod
    def writeBytes(receiver: java.io.File, data: java.chaquopy.JavaArrayJByte, /) -> None: ...
    @typing.overload
    @staticmethod
    def writeText(receiver: java.io.File, text: str | java.lang.String, encoding: str | java.lang.String, /) -> None: ...
    @typing.overload
    @staticmethod
    def writeText(receiver: java.io.File, text: str | java.lang.String, encoding: java.nio.charset.Charset, /) -> None: ...
    @staticmethod
    def writeText$default(arg1: java.io.File, arg2: str | java.lang.String, arg3: str | java.lang.String, arg4: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    @staticmethod
    def writer(receiver: java.io.OutputStream, encoding: str | java.lang.String, /) -> java.io.OutputStreamWriter: ...
    @typing.overload
    @staticmethod
    def writer(receiver: java.io.OutputStream, encoding: java.nio.charset.Charset, /) -> java.io.OutputStreamWriter: ...
    @typing.overload
    @staticmethod
    def writer(receiver: java.io.OutputStream, encoding: java.nio.charset.CharsetEncoder, /) -> java.io.OutputStreamWriter: ...
    @staticmethod
    def writer$default(arg1: java.io.OutputStream, arg2: java.nio.charset.Charset, arg3: int | java.jint | java.lang.Integer, /) -> java.io.OutputStreamWriter: ...

class LineIterator(jet.JetObject, java.util.Iterator[java.lang.String]):
    def __init__(self, reader: java.io.BufferedReader, /) -> None: ...
    def getReader(self) -> java.io.BufferedReader: ...
    def hasNext(self) -> bool: ...
    def next(self) -> str: ...
    def remove(self) -> None: ...
