import typing

import java
import java.chaquopy
import java.io
import java.lang
import java.lang.annotation
import java.util
import kotlin.collections
import kotlin.jvm.functions
import kotlin.jvm.internal.markers

class ArrayIntrinsicsKt(java.lang.Object): ...

class BuilderInference(java.lang.annotation.Annotation): ...

class Deprecated(java.lang.annotation.Annotation):
    def level(self) -> DeprecationLevel: ...
    def message(self) -> str: ...
    def replaceWith(self) -> ReplaceWith: ...

class DeprecationLevel(java.lang.Enum[DeprecationLevel]):
    WARNING: typing.ClassVar[DeprecationLevel] = ...
    ERROR: typing.ClassVar[DeprecationLevel] = ...
    HIDDEN: typing.ClassVar[DeprecationLevel] = ...
    @staticmethod
    def valueOf(arg1: str | java.lang.String, /) -> DeprecationLevel: ...
    @staticmethod
    def values() -> java.chaquopy.JavaArray[DeprecationLevel]: ...

class DslMarker(java.lang.annotation.Annotation): ...

class ExceptionsKt(ExceptionsKt__ExceptionsKt): ...

class ExceptionsKt__ExceptionsKt(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def addSuppressed(receiver: java.lang.Throwable, exception: java.lang.Throwable, /) -> None: ...
    @staticmethod
    def getStackTrace(receiver: java.lang.Throwable, /) -> java.chaquopy.JavaArray[java.lang.StackTraceElement]: ...

class Experimental(java.lang.annotation.Annotation):
    def level(self) -> Experimental.Level: ...

    class Level(java.lang.Enum[Experimental.Level]):
        WARNING: typing.ClassVar[Experimental.Level] = ...
        ERROR: typing.ClassVar[Experimental.Level] = ...
        @staticmethod
        def valueOf(arg1: str | java.lang.String, /) -> Experimental.Level: ...
        @staticmethod
        def values() -> java.chaquopy.JavaArray[Experimental.Level]: ...

class ExperimentalMultiplatform(java.lang.annotation.Annotation): ...

class ExperimentalUnsignedTypes(java.lang.annotation.Annotation): ...

class ExtensionFunctionType(java.lang.annotation.Annotation): ...

_Function__R = typing.TypeVar('_Function__R')  # <R>
class Function(java.lang.Object, typing.Generic[_Function__R]): ...

class HashCodeKt(java.lang.Object): ...

_InitializedLazyImpl__T = typing.TypeVar('_InitializedLazyImpl__T')  # <T>
class InitializedLazyImpl(Lazy[_InitializedLazyImpl__T], java.io.Serializable, typing.Generic[_InitializedLazyImpl__T]):
    def __init__(self, value: _InitializedLazyImpl__T, /) -> None: ...
    def getValue(self) -> _InitializedLazyImpl__T: ...
    def isInitialized(self) -> bool: ...
    def toString(self) -> str: ...

class KotlinNullPointerException(java.lang.NullPointerException):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, message: str | java.lang.String, /) -> None: ...

class KotlinVersion(java.lang.Comparable[KotlinVersion]):
    MAX_COMPONENT_VALUE: typing.ClassVar[int] = ...
    CURRENT: typing.ClassVar[KotlinVersion] = ...
    Companion: typing.ClassVar[KotlinVersion.Companion] = ...
    @typing.overload
    def __init__(self, major: int | java.jint | java.lang.Integer, minor: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, major: int | java.jint | java.lang.Integer, minor: int | java.jint | java.lang.Integer, patch: int | java.jint | java.lang.Integer, /) -> None: ...
    def compareTo(self, other: KotlinVersion, /) -> int: ...
    def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getMajor(self) -> int: ...
    def getMinor(self) -> int: ...
    def getPatch(self) -> int: ...
    def hashCode(self) -> int: ...
    @typing.overload
    def isAtLeast(self, major: int | java.jint | java.lang.Integer, minor: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def isAtLeast(self, major: int | java.jint | java.lang.Integer, minor: int | java.jint | java.lang.Integer, patch: int | java.jint | java.lang.Integer, /) -> bool: ...
    def toString(self) -> str: ...

    class Companion(java.lang.Object): ...

class LateinitKt(java.lang.Object): ...

_Lazy__T = typing.TypeVar('_Lazy__T')  # <T>
class Lazy(java.lang.Object, typing.Generic[_Lazy__T]):
    def getValue(self) -> _Lazy__T: ...
    def isInitialized(self) -> bool: ...

class LazyKt(LazyKt__LazyKt): ...

class LazyKt__LazyJVMKt(java.lang.Object):
    def __init__(self) -> None: ...
    _lazy_0__T = typing.TypeVar('_lazy_0__T')  # <T>
    _lazy_1__T = typing.TypeVar('_lazy_1__T')  # <T>
    _lazy_2__T = typing.TypeVar('_lazy_2__T')  # <T>
    @typing.overload
    @staticmethod
    def lazy(initializer: kotlin.jvm.functions.Function0[_lazy_0__T], /) -> Lazy[_lazy_0__T]: ...
    @typing.overload
    @staticmethod
    def lazy(lock: java.lang.Object | int | bool | float | str, initializer: kotlin.jvm.functions.Function0[_lazy_1__T], /) -> Lazy[_lazy_1__T]: ...
    @typing.overload
    @staticmethod
    def lazy(mode: LazyThreadSafetyMode, initializer: kotlin.jvm.functions.Function0[_lazy_2__T], /) -> Lazy[_lazy_2__T]: ...

class LazyKt__LazyKt(LazyKt__LazyJVMKt):
    def __init__(self) -> None: ...
    _lazyOf__T = typing.TypeVar('_lazyOf__T')  # <T>
    @staticmethod
    def lazyOf(value: _lazyOf__T, /) -> Lazy[_lazyOf__T]: ...

class LazyThreadSafetyMode(java.lang.Enum[LazyThreadSafetyMode]):
    SYNCHRONIZED: typing.ClassVar[LazyThreadSafetyMode] = ...
    PUBLICATION: typing.ClassVar[LazyThreadSafetyMode] = ...
    NONE: typing.ClassVar[LazyThreadSafetyMode] = ...
    @staticmethod
    def valueOf(arg1: str | java.lang.String, /) -> LazyThreadSafetyMode: ...
    @staticmethod
    def values() -> java.chaquopy.JavaArray[LazyThreadSafetyMode]: ...

class MathKt(MathKt__NumbersKt): ...

class MathKt__BigDecimalsKt(java.lang.Object):
    def __init__(self) -> None: ...

class MathKt__BigIntegersKt(MathKt__BigDecimalsKt):
    def __init__(self) -> None: ...

class MathKt__NumbersKt(MathKt__BigIntegersKt):
    def __init__(self) -> None: ...

class Metadata(java.lang.annotation.Annotation):
    def bv(self) -> java.chaquopy.JavaArrayJInt: ...
    def d1(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    def d2(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    def k(self) -> int: ...
    def mv(self) -> java.chaquopy.JavaArrayJInt: ...
    def pn(self) -> str: ...
    def xi(self) -> int: ...
    def xs(self) -> str: ...

class NoWhenBranchMatchedException(java.lang.RuntimeException):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, message: str | java.lang.String, /) -> None: ...
    @typing.overload
    def __init__(self, cause: java.lang.Throwable, /) -> None: ...
    @typing.overload
    def __init__(self, message: str | java.lang.String, cause: java.lang.Throwable, /) -> None: ...

class NotImplementedError(java.lang.Error):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, message: str | java.lang.String, /) -> None: ...

class OptionalExpectation(java.lang.annotation.Annotation): ...

_Pair__A = typing.TypeVar('_Pair__A')  # <A>
_Pair__B = typing.TypeVar('_Pair__B')  # <B>
class Pair(java.io.Serializable, typing.Generic[_Pair__A, _Pair__B]):
    def __init__(self, first: _Pair__A, second: _Pair__B, /) -> None: ...
    def component1(self) -> _Pair__A: ...
    def component2(self) -> _Pair__B: ...
    def copy(self, first: _Pair__A, second: _Pair__B, /) -> Pair[_Pair__A, _Pair__B]: ...
    def equals(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getFirst(self) -> _Pair__A: ...
    def getSecond(self) -> _Pair__B: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class ParameterName(java.lang.annotation.Annotation):
    def name(self) -> str: ...

class PreconditionsKt(PreconditionsKt__PreconditionsKt): ...

class PreconditionsKt__AssertionsJVMKt(java.lang.Object):
    def __init__(self) -> None: ...

class PreconditionsKt__PreconditionsKt(PreconditionsKt__AssertionsJVMKt):
    def __init__(self) -> None: ...

class PublishedApi(java.lang.annotation.Annotation): ...

class ReplaceWith(java.lang.annotation.Annotation):
    def expression(self) -> str: ...
    def imports(self) -> java.chaquopy.JavaArray[java.lang.String]: ...

_Result__T = typing.TypeVar('_Result__T')  # <T>
class Result(java.io.Serializable, typing.Generic[_Result__T]):
    Companion: typing.ClassVar[Result.Companion] = ...
    @staticmethod
    def constructor-impl(value: java.lang.Object | int | bool | float | str, /) -> java.lang.Object: ...
    def equals(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl(arg1: java.lang.Object | int | bool | float | str, arg2: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl0(p1: java.lang.Object | int | bool | float | str, p2: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def exceptionOrNull-impl(this: java.lang.Object | int | bool | float | str, /) -> java.lang.Throwable: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def hashCode-impl(arg1: java.lang.Object | int | bool | float | str, /) -> int: ...
    @staticmethod
    def isFailure-impl(this: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def isSuccess-impl(this: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def toString(self) -> str: ...
    @staticmethod
    def toString-impl(this: java.lang.Object | int | bool | float | str, /) -> str: ...

    class Failure(java.io.Serializable):
        exception: java.lang.Throwable = ...
        def __init__(self, exception: java.lang.Throwable, /) -> None: ...
        def equals(self, other: java.lang.Object | int | bool | float | str, /) -> bool: ...
        def hashCode(self) -> int: ...
        def toString(self) -> str: ...

    class Companion(java.lang.Object): ...

class ResultKt(java.lang.Object):
    @staticmethod
    def createFailure(exception: java.lang.Throwable, /) -> java.lang.Object: ...
    @staticmethod
    def throwOnFailure(receiver: java.lang.Object | int | bool | float | str, /) -> None: ...

_SafePublicationLazyImpl__T = typing.TypeVar('_SafePublicationLazyImpl__T')  # <T>
class SafePublicationLazyImpl(Lazy[_SafePublicationLazyImpl__T], java.io.Serializable, typing.Generic[_SafePublicationLazyImpl__T]):
    Companion: typing.ClassVar[SafePublicationLazyImpl.Companion] = ...
    def __init__(self, initializer: kotlin.jvm.functions.Function0[_SafePublicationLazyImpl__T], /) -> None: ...
    def getValue(self) -> _SafePublicationLazyImpl__T: ...
    def isInitialized(self) -> bool: ...
    def toString(self) -> str: ...

    class Companion(java.lang.Object): ...

class SinceKotlin(java.lang.annotation.Annotation):
    def version(self) -> str: ...

class StandardKt(StandardKt__SynchronizedKt): ...

class StandardKt__StandardKt(java.lang.Object):
    def __init__(self) -> None: ...

class StandardKt__SynchronizedKt(StandardKt__StandardKt):
    def __init__(self) -> None: ...

class SuccessOrFailureKt(java.lang.Object): ...

class Suppress(java.lang.annotation.Annotation):
    def names(self) -> java.chaquopy.JavaArray[java.lang.String]: ...

class SuspendKt(java.lang.Object): ...

_SynchronizedLazyImpl__T = typing.TypeVar('_SynchronizedLazyImpl__T')  # <T>
class SynchronizedLazyImpl(Lazy[_SynchronizedLazyImpl__T], java.io.Serializable, typing.Generic[_SynchronizedLazyImpl__T]):
    def __init__(self, initializer: kotlin.jvm.functions.Function0[_SynchronizedLazyImpl__T], lock: java.lang.Object | int | bool | float | str, /) -> None: ...
    def getValue(self) -> _SynchronizedLazyImpl__T: ...
    def isInitialized(self) -> bool: ...
    def toString(self) -> str: ...

_Triple__A = typing.TypeVar('_Triple__A')  # <A>
_Triple__B = typing.TypeVar('_Triple__B')  # <B>
_Triple__C = typing.TypeVar('_Triple__C')  # <C>
class Triple(java.io.Serializable, typing.Generic[_Triple__A, _Triple__B, _Triple__C]):
    def __init__(self, first: _Triple__A, second: _Triple__B, third: _Triple__C, /) -> None: ...
    def component1(self) -> _Triple__A: ...
    def component2(self) -> _Triple__B: ...
    def component3(self) -> _Triple__C: ...
    def copy(self, first: _Triple__A, second: _Triple__B, third: _Triple__C, /) -> Triple[_Triple__A, _Triple__B, _Triple__C]: ...
    def equals(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getFirst(self) -> _Triple__A: ...
    def getSecond(self) -> _Triple__B: ...
    def getThird(self) -> _Triple__C: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class TuplesKt(java.lang.Object):
    _to__A = typing.TypeVar('_to__A')  # <A>
    _to__B = typing.TypeVar('_to__B')  # <B>
    @staticmethod
    def to(receiver: _to__A, that: _to__B, /) -> Pair[_to__A, _to__B]: ...
    _toList_0__T = typing.TypeVar('_toList_0__T')  # <T>
    _toList_1__T = typing.TypeVar('_toList_1__T')  # <T>
    @typing.overload
    @staticmethod
    def toList(receiver: Pair[_toList_0__T, _toList_0__T], /) -> java.util.List[_toList_0__T]: ...
    @typing.overload
    @staticmethod
    def toList(receiver: Triple[_toList_1__T, _toList_1__T, _toList_1__T], /) -> java.util.List[_toList_1__T]: ...

class TypeAliasesKt(java.lang.Object): ...

class TypeCastException(java.lang.ClassCastException):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, message: str | java.lang.String, /) -> None: ...

class UByte(java.lang.Comparable[UByte]):
    MIN_VALUE: typing.ClassVar[int] = ...
    MAX_VALUE: typing.ClassVar[int] = ...
    SIZE_BYTES: typing.ClassVar[int] = ...
    SIZE_BITS: typing.ClassVar[int] = ...
    Companion: typing.ClassVar[UByte.Companion] = ...
    @staticmethod
    def constructor-impl(data: int | java.jbyte | java.lang.Byte, /) -> int: ...
    def equals(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl(arg1: int | java.jbyte | java.lang.Byte, arg2: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl0(p1: int | java.jbyte | java.lang.Byte, p2: int | java.jbyte | java.lang.Byte, /) -> bool: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def hashCode-impl(arg1: int | java.jbyte | java.lang.Byte, /) -> int: ...
    def toString(self) -> str: ...
    @staticmethod
    def toString-impl(this: int | java.jbyte | java.lang.Byte, /) -> str: ...

    class Companion(java.lang.Object): ...

class UByteArray(java.util.Collection[UByte], kotlin.jvm.internal.markers.KMappedMarker):
    def add-7apg3OU(self, arg1: int | java.jbyte | java.lang.Byte, /) -> bool: ...
    def addAll(self, arg1: java.util.Collection[UByte], /) -> bool: ...
    def clear(self) -> None: ...
    @typing.overload
    @staticmethod
    def constructor-impl(size: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJByte: ...
    @typing.overload
    @staticmethod
    def constructor-impl(storage: java.chaquopy.JavaArrayJByte, /) -> java.chaquopy.JavaArrayJByte: ...
    @typing.overload
    def contains-7apg3OU(self, arg1: int | java.jbyte | java.lang.Byte, /) -> bool: ...
    @typing.overload
    @staticmethod
    def contains-7apg3OU(this: java.chaquopy.JavaArrayJByte, element: int | java.jbyte | java.lang.Byte, /) -> bool: ...
    def containsAll(self, arg1: java.util.Collection[java.lang.Object], /) -> bool: ...
    @staticmethod
    def containsAll-impl(this: java.chaquopy.JavaArrayJByte, elements: java.util.Collection[UByte], /) -> bool: ...
    def equals(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl(arg1: java.chaquopy.JavaArrayJByte, arg2: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl0(p1: java.chaquopy.JavaArrayJByte, p2: java.chaquopy.JavaArrayJByte, /) -> bool: ...
    @staticmethod
    def get-impl(this: java.chaquopy.JavaArrayJByte, index: int | java.jint | java.lang.Integer, /) -> int: ...
    def getSize(self) -> int: ...
    @staticmethod
    def getSize-impl(this: java.chaquopy.JavaArrayJByte, /) -> int: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def hashCode-impl(arg1: java.chaquopy.JavaArrayJByte, /) -> int: ...
    def isEmpty(self) -> bool: ...
    @staticmethod
    def isEmpty-impl(this: java.chaquopy.JavaArrayJByte, /) -> bool: ...
    def iterator(self) -> kotlin.collections.UByteIterator: ...
    @staticmethod
    def iterator-impl(this: java.chaquopy.JavaArrayJByte, /) -> kotlin.collections.UByteIterator: ...
    def remove(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def removeAll(self, arg1: java.util.Collection[java.lang.Object], /) -> bool: ...
    def retainAll(self, arg1: java.util.Collection[java.lang.Object], /) -> bool: ...
    @staticmethod
    def set-VurrAj0(this: java.chaquopy.JavaArrayJByte, index: int | java.jint | java.lang.Integer, value: int | java.jbyte | java.lang.Byte, /) -> None: ...
    _toArray_1__T = typing.TypeVar('_toArray_1__T')  # <T>
    @typing.overload
    def toArray(self) -> java.chaquopy.JavaArray[java.lang.Object]: ...
    @typing.overload
    def toArray(self, arg1: java.chaquopy.JavaArray[_toArray_1__T], /) -> java.chaquopy.JavaArray[_toArray_1__T]: ...
    def toString(self) -> str: ...
    @staticmethod
    def toString-impl(arg1: java.chaquopy.JavaArrayJByte, /) -> str: ...

class UByteArrayKt(java.lang.Object): ...

class UByteKt(java.lang.Object): ...

class UInt(java.lang.Comparable[UInt]):
    MIN_VALUE: typing.ClassVar[int] = ...
    MAX_VALUE: typing.ClassVar[int] = ...
    SIZE_BYTES: typing.ClassVar[int] = ...
    SIZE_BITS: typing.ClassVar[int] = ...
    Companion: typing.ClassVar[UInt.Companion] = ...
    @staticmethod
    def constructor-impl(data: int | java.jint | java.lang.Integer, /) -> int: ...
    def equals(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl(arg1: int | java.jint | java.lang.Integer, arg2: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl0(p1: int | java.jint | java.lang.Integer, p2: int | java.jint | java.lang.Integer, /) -> bool: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def hashCode-impl(arg1: int | java.jint | java.lang.Integer, /) -> int: ...
    def toString(self) -> str: ...
    @staticmethod
    def toString-impl(this: int | java.jint | java.lang.Integer, /) -> str: ...

    class Companion(java.lang.Object): ...

class UIntArray(java.util.Collection[UInt], kotlin.jvm.internal.markers.KMappedMarker):
    def add-WZ4Q5Ns(self, arg1: int | java.jint | java.lang.Integer, /) -> bool: ...
    def addAll(self, arg1: java.util.Collection[UInt], /) -> bool: ...
    def clear(self) -> None: ...
    @typing.overload
    @staticmethod
    def constructor-impl(size: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJInt: ...
    @typing.overload
    @staticmethod
    def constructor-impl(storage: java.chaquopy.JavaArrayJInt, /) -> java.chaquopy.JavaArrayJInt: ...
    @typing.overload
    def contains-WZ4Q5Ns(self, arg1: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    @staticmethod
    def contains-WZ4Q5Ns(this: java.chaquopy.JavaArrayJInt, element: int | java.jint | java.lang.Integer, /) -> bool: ...
    def containsAll(self, arg1: java.util.Collection[java.lang.Object], /) -> bool: ...
    @staticmethod
    def containsAll-impl(this: java.chaquopy.JavaArrayJInt, elements: java.util.Collection[UInt], /) -> bool: ...
    def equals(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl(arg1: java.chaquopy.JavaArrayJInt, arg2: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl0(p1: java.chaquopy.JavaArrayJInt, p2: java.chaquopy.JavaArrayJInt, /) -> bool: ...
    @staticmethod
    def get-impl(this: java.chaquopy.JavaArrayJInt, index: int | java.jint | java.lang.Integer, /) -> int: ...
    def getSize(self) -> int: ...
    @staticmethod
    def getSize-impl(this: java.chaquopy.JavaArrayJInt, /) -> int: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def hashCode-impl(arg1: java.chaquopy.JavaArrayJInt, /) -> int: ...
    def isEmpty(self) -> bool: ...
    @staticmethod
    def isEmpty-impl(this: java.chaquopy.JavaArrayJInt, /) -> bool: ...
    def iterator(self) -> kotlin.collections.UIntIterator: ...
    @staticmethod
    def iterator-impl(this: java.chaquopy.JavaArrayJInt, /) -> kotlin.collections.UIntIterator: ...
    def remove(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def removeAll(self, arg1: java.util.Collection[java.lang.Object], /) -> bool: ...
    def retainAll(self, arg1: java.util.Collection[java.lang.Object], /) -> bool: ...
    @staticmethod
    def set-VXSXFK8(this: java.chaquopy.JavaArrayJInt, index: int | java.jint | java.lang.Integer, value: int | java.jint | java.lang.Integer, /) -> None: ...
    _toArray_1__T = typing.TypeVar('_toArray_1__T')  # <T>
    @typing.overload
    def toArray(self) -> java.chaquopy.JavaArray[java.lang.Object]: ...
    @typing.overload
    def toArray(self, arg1: java.chaquopy.JavaArray[_toArray_1__T], /) -> java.chaquopy.JavaArray[_toArray_1__T]: ...
    def toString(self) -> str: ...
    @staticmethod
    def toString-impl(arg1: java.chaquopy.JavaArrayJInt, /) -> str: ...

class UIntArrayKt(java.lang.Object): ...

class UIntKt(java.lang.Object): ...

class ULong(java.lang.Comparable[ULong]):
    MIN_VALUE: typing.ClassVar[int] = ...
    MAX_VALUE: typing.ClassVar[int] = ...
    SIZE_BYTES: typing.ClassVar[int] = ...
    SIZE_BITS: typing.ClassVar[int] = ...
    Companion: typing.ClassVar[ULong.Companion] = ...
    @staticmethod
    def constructor-impl(data: int | java.jlong | java.lang.Long, /) -> int: ...
    def equals(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl(arg1: int | java.jlong | java.lang.Long, arg2: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl0(p1: int | java.jlong | java.lang.Long, p2: int | java.jlong | java.lang.Long, /) -> bool: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def hashCode-impl(arg1: int | java.jlong | java.lang.Long, /) -> int: ...
    def toString(self) -> str: ...
    @staticmethod
    def toString-impl(this: int | java.jlong | java.lang.Long, /) -> str: ...

    class Companion(java.lang.Object): ...

class ULongArray(java.util.Collection[ULong], kotlin.jvm.internal.markers.KMappedMarker):
    def add-VKZWuLQ(self, arg1: int | java.jlong | java.lang.Long, /) -> bool: ...
    def addAll(self, arg1: java.util.Collection[ULong], /) -> bool: ...
    def clear(self) -> None: ...
    @typing.overload
    @staticmethod
    def constructor-impl(size: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJLong: ...
    @typing.overload
    @staticmethod
    def constructor-impl(storage: java.chaquopy.JavaArrayJLong, /) -> java.chaquopy.JavaArrayJLong: ...
    @typing.overload
    def contains-VKZWuLQ(self, arg1: int | java.jlong | java.lang.Long, /) -> bool: ...
    @typing.overload
    @staticmethod
    def contains-VKZWuLQ(this: java.chaquopy.JavaArrayJLong, element: int | java.jlong | java.lang.Long, /) -> bool: ...
    def containsAll(self, arg1: java.util.Collection[java.lang.Object], /) -> bool: ...
    @staticmethod
    def containsAll-impl(this: java.chaquopy.JavaArrayJLong, elements: java.util.Collection[ULong], /) -> bool: ...
    def equals(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl(arg1: java.chaquopy.JavaArrayJLong, arg2: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl0(p1: java.chaquopy.JavaArrayJLong, p2: java.chaquopy.JavaArrayJLong, /) -> bool: ...
    @staticmethod
    def get-impl(this: java.chaquopy.JavaArrayJLong, index: int | java.jint | java.lang.Integer, /) -> int: ...
    def getSize(self) -> int: ...
    @staticmethod
    def getSize-impl(this: java.chaquopy.JavaArrayJLong, /) -> int: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def hashCode-impl(arg1: java.chaquopy.JavaArrayJLong, /) -> int: ...
    def isEmpty(self) -> bool: ...
    @staticmethod
    def isEmpty-impl(this: java.chaquopy.JavaArrayJLong, /) -> bool: ...
    def iterator(self) -> kotlin.collections.ULongIterator: ...
    @staticmethod
    def iterator-impl(this: java.chaquopy.JavaArrayJLong, /) -> kotlin.collections.ULongIterator: ...
    def remove(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def removeAll(self, arg1: java.util.Collection[java.lang.Object], /) -> bool: ...
    def retainAll(self, arg1: java.util.Collection[java.lang.Object], /) -> bool: ...
    @staticmethod
    def set-k8EXiF4(this: java.chaquopy.JavaArrayJLong, index: int | java.jint | java.lang.Integer, value: int | java.jlong | java.lang.Long, /) -> None: ...
    _toArray_1__T = typing.TypeVar('_toArray_1__T')  # <T>
    @typing.overload
    def toArray(self) -> java.chaquopy.JavaArray[java.lang.Object]: ...
    @typing.overload
    def toArray(self, arg1: java.chaquopy.JavaArray[_toArray_1__T], /) -> java.chaquopy.JavaArray[_toArray_1__T]: ...
    def toString(self) -> str: ...
    @staticmethod
    def toString-impl(arg1: java.chaquopy.JavaArrayJLong, /) -> str: ...

class ULongArrayKt(java.lang.Object): ...

class ULongKt(java.lang.Object): ...

class UNINITIALIZED_VALUE(java.lang.Object):
    INSTANCE: typing.ClassVar[UNINITIALIZED_VALUE] = ...

class UShort(java.lang.Comparable[UShort]):
    MIN_VALUE: typing.ClassVar[int] = ...
    MAX_VALUE: typing.ClassVar[int] = ...
    SIZE_BYTES: typing.ClassVar[int] = ...
    SIZE_BITS: typing.ClassVar[int] = ...
    Companion: typing.ClassVar[UShort.Companion] = ...
    @staticmethod
    def constructor-impl(data: int | java.jshort | java.lang.Short, /) -> int: ...
    def equals(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl(arg1: int | java.jshort | java.lang.Short, arg2: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl0(p1: int | java.jshort | java.lang.Short, p2: int | java.jshort | java.lang.Short, /) -> bool: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def hashCode-impl(arg1: int | java.jshort | java.lang.Short, /) -> int: ...
    def toString(self) -> str: ...
    @staticmethod
    def toString-impl(this: int | java.jshort | java.lang.Short, /) -> str: ...

    class Companion(java.lang.Object): ...

class UShortArray(java.util.Collection[UShort], kotlin.jvm.internal.markers.KMappedMarker):
    def add-xj2QHRw(self, arg1: int | java.jshort | java.lang.Short, /) -> bool: ...
    def addAll(self, arg1: java.util.Collection[UShort], /) -> bool: ...
    def clear(self) -> None: ...
    @typing.overload
    @staticmethod
    def constructor-impl(size: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJShort: ...
    @typing.overload
    @staticmethod
    def constructor-impl(storage: java.chaquopy.JavaArrayJShort, /) -> java.chaquopy.JavaArrayJShort: ...
    @typing.overload
    def contains-xj2QHRw(self, arg1: int | java.jshort | java.lang.Short, /) -> bool: ...
    @typing.overload
    @staticmethod
    def contains-xj2QHRw(this: java.chaquopy.JavaArrayJShort, element: int | java.jshort | java.lang.Short, /) -> bool: ...
    def containsAll(self, arg1: java.util.Collection[java.lang.Object], /) -> bool: ...
    @staticmethod
    def containsAll-impl(this: java.chaquopy.JavaArrayJShort, elements: java.util.Collection[UShort], /) -> bool: ...
    def equals(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl(arg1: java.chaquopy.JavaArrayJShort, arg2: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl0(p1: java.chaquopy.JavaArrayJShort, p2: java.chaquopy.JavaArrayJShort, /) -> bool: ...
    @staticmethod
    def get-impl(this: java.chaquopy.JavaArrayJShort, index: int | java.jint | java.lang.Integer, /) -> int: ...
    def getSize(self) -> int: ...
    @staticmethod
    def getSize-impl(this: java.chaquopy.JavaArrayJShort, /) -> int: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def hashCode-impl(arg1: java.chaquopy.JavaArrayJShort, /) -> int: ...
    def isEmpty(self) -> bool: ...
    @staticmethod
    def isEmpty-impl(this: java.chaquopy.JavaArrayJShort, /) -> bool: ...
    def iterator(self) -> kotlin.collections.UShortIterator: ...
    @staticmethod
    def iterator-impl(this: java.chaquopy.JavaArrayJShort, /) -> kotlin.collections.UShortIterator: ...
    def remove(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def removeAll(self, arg1: java.util.Collection[java.lang.Object], /) -> bool: ...
    def retainAll(self, arg1: java.util.Collection[java.lang.Object], /) -> bool: ...
    @staticmethod
    def set-01HTLdE(this: java.chaquopy.JavaArrayJShort, index: int | java.jint | java.lang.Integer, value: int | java.jshort | java.lang.Short, /) -> None: ...
    _toArray_1__T = typing.TypeVar('_toArray_1__T')  # <T>
    @typing.overload
    def toArray(self) -> java.chaquopy.JavaArray[java.lang.Object]: ...
    @typing.overload
    def toArray(self, arg1: java.chaquopy.JavaArray[_toArray_1__T], /) -> java.chaquopy.JavaArray[_toArray_1__T]: ...
    def toString(self) -> str: ...
    @staticmethod
    def toString-impl(arg1: java.chaquopy.JavaArrayJShort, /) -> str: ...

class UShortArrayKt(java.lang.Object): ...

class UShortKt(java.lang.Object): ...

class UninitializedPropertyAccessException(java.lang.RuntimeException):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, message: str | java.lang.String, /) -> None: ...
    @typing.overload
    def __init__(self, cause: java.lang.Throwable, /) -> None: ...
    @typing.overload
    def __init__(self, message: str | java.lang.String, cause: java.lang.Throwable, /) -> None: ...

class Unit(java.lang.Object):
    INSTANCE: typing.ClassVar[Unit] = ...
    def toString(self) -> str: ...

_UnsafeLazyImpl__T = typing.TypeVar('_UnsafeLazyImpl__T')  # <T>
class UnsafeLazyImpl(Lazy[_UnsafeLazyImpl__T], java.io.Serializable, typing.Generic[_UnsafeLazyImpl__T]):
    def __init__(self, initializer: kotlin.jvm.functions.Function0[_UnsafeLazyImpl__T], /) -> None: ...
    def getValue(self) -> _UnsafeLazyImpl__T: ...
    def isInitialized(self) -> bool: ...
    def toString(self) -> str: ...

class UnsafeVariance(java.lang.annotation.Annotation): ...

class UnsignedKt(java.lang.Object):
    @staticmethod
    def uintCompare(v1: int | java.jint | java.lang.Integer, v2: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def uintDivide-J1ME1BU(v1: int | java.jint | java.lang.Integer, v2: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def uintRemainder-J1ME1BU(v1: int | java.jint | java.lang.Integer, v2: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def ulongCompare(v1: int | java.jlong | java.lang.Long, v2: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def ulongDivide-eb3DHEI(v1: int | java.jlong | java.lang.Long, v2: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def ulongRemainder-eb3DHEI(v1: int | java.jlong | java.lang.Long, v2: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def ulongToString(v: int | java.jlong | java.lang.Long, /) -> str: ...
    @typing.overload
    @staticmethod
    def ulongToString(v: int | java.jlong | java.lang.Long, base: int | java.jint | java.lang.Integer, /) -> str: ...

class UseExperimental(java.lang.annotation.Annotation):
    def markerClass(self) -> java.chaquopy.JavaArray[typing.Type[java.lang.annotation.Annotation]]: ...

class WasExperimental(java.lang.annotation.Annotation):
    def markerClass(self) -> java.chaquopy.JavaArray[typing.Type[java.lang.annotation.Annotation]]: ...

class _Assertions(java.lang.Object):
    ENABLED: typing.ClassVar[bool] = ...
    INSTANCE: typing.ClassVar[_Assertions] = ...
