import typing

import android.database
import java
import java.chaquopy
import java.lang

class CursorKt(java.lang.Object):
    @staticmethod
    def getBlob(receiver: android.database.Cursor, columnName: str | java.lang.String, /) -> java.chaquopy.JavaArrayJByte: ...
    @typing.overload
    @staticmethod
    def getBlobOrNull(receiver: android.database.Cursor, index: int | java.jint | java.lang.Integer, /) -> java.chaquopy.JavaArrayJByte: ...
    @typing.overload
    @staticmethod
    def getBlobOrNull(receiver: android.database.Cursor, columnName: str | java.lang.String, /) -> java.chaquopy.JavaArrayJByte: ...
    @staticmethod
    def getDouble(receiver: android.database.Cursor, columnName: str | java.lang.String, /) -> float: ...
    @typing.overload
    @staticmethod
    def getDoubleOrNull(receiver: android.database.Cursor, index: int | java.jint | java.lang.Integer, /) -> float: ...
    @typing.overload
    @staticmethod
    def getDoubleOrNull(receiver: android.database.Cursor, columnName: str | java.lang.String, /) -> float: ...
    @staticmethod
    def getFloat(receiver: android.database.Cursor, columnName: str | java.lang.String, /) -> float: ...
    @typing.overload
    @staticmethod
    def getFloatOrNull(receiver: android.database.Cursor, index: int | java.jint | java.lang.Integer, /) -> float: ...
    @typing.overload
    @staticmethod
    def getFloatOrNull(receiver: android.database.Cursor, columnName: str | java.lang.String, /) -> float: ...
    @staticmethod
    def getInt(receiver: android.database.Cursor, columnName: str | java.lang.String, /) -> int: ...
    @typing.overload
    @staticmethod
    def getIntOrNull(receiver: android.database.Cursor, index: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getIntOrNull(receiver: android.database.Cursor, columnName: str | java.lang.String, /) -> int: ...
    @staticmethod
    def getLong(receiver: android.database.Cursor, columnName: str | java.lang.String, /) -> int: ...
    @typing.overload
    @staticmethod
    def getLongOrNull(receiver: android.database.Cursor, index: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getLongOrNull(receiver: android.database.Cursor, columnName: str | java.lang.String, /) -> int: ...
    @staticmethod
    def getShort(receiver: android.database.Cursor, columnName: str | java.lang.String, /) -> int: ...
    @typing.overload
    @staticmethod
    def getShortOrNull(receiver: android.database.Cursor, index: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getShortOrNull(receiver: android.database.Cursor, columnName: str | java.lang.String, /) -> int: ...
    @staticmethod
    def getString(receiver: android.database.Cursor, columnName: str | java.lang.String, /) -> str: ...
    @typing.overload
    @staticmethod
    def getStringOrNull(receiver: android.database.Cursor, index: int | java.jint | java.lang.Integer, /) -> str: ...
    @typing.overload
    @staticmethod
    def getStringOrNull(receiver: android.database.Cursor, columnName: str | java.lang.String, /) -> str: ...
