import typing

import android.graphics
import java
import java.chaquopy
import java.lang

class ISafeCanvas(java.lang.Object):
    @typing.overload
    def clipPath(self, arg1: SafeTranslatedPath, /) -> bool: ...
    @typing.overload
    def clipPath(self, arg1: SafeTranslatedPath, arg2: android.graphics.Region.Op, /) -> bool: ...
    @typing.overload
    def clipRect(self, arg1: android.graphics.Rect, /) -> bool: ...
    @typing.overload
    def clipRect(self, arg1: android.graphics.Rect, arg2: android.graphics.Region.Op, /) -> bool: ...
    @typing.overload
    def clipRect(self, arg1: float | java.jdouble | java.lang.Double, arg2: float | java.jdouble | java.lang.Double, arg3: float | java.jdouble | java.lang.Double, arg4: float | java.jdouble | java.lang.Double, /) -> bool: ...
    @typing.overload
    def clipRect(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, arg4: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def clipRect(self, arg1: float | java.jdouble | java.lang.Double, arg2: float | java.jdouble | java.lang.Double, arg3: float | java.jdouble | java.lang.Double, arg4: float | java.jdouble | java.lang.Double, arg5: android.graphics.Region.Op, /) -> bool: ...
    @typing.overload
    def clipRegion(self, arg1: android.graphics.Region, /) -> bool: ...
    @typing.overload
    def clipRegion(self, arg1: android.graphics.Region, arg2: android.graphics.Region.Op, /) -> bool: ...
    def concat(self, arg1: android.graphics.Matrix, /) -> None: ...
    def drawARGB(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, arg4: int | java.jint | java.lang.Integer, /) -> None: ...
    def drawArc(self, arg1: android.graphics.Rect, arg2: float | java.jfloat | java.lang.Float, arg3: float | java.jfloat | java.lang.Float, arg4: bool | java.jboolean | java.lang.Boolean, arg5: SafePaint, /) -> None: ...
    @typing.overload
    def drawBitmap(self, arg1: android.graphics.Bitmap, arg2: android.graphics.Matrix, arg3: SafePaint, /) -> None: ...
    @typing.overload
    def drawBitmap(self, arg1: android.graphics.Bitmap, arg2: float | java.jdouble | java.lang.Double, arg3: float | java.jdouble | java.lang.Double, arg4: SafePaint, /) -> None: ...
    @typing.overload
    def drawBitmap(self, arg1: android.graphics.Bitmap, arg2: android.graphics.Rect, arg3: android.graphics.Rect, arg4: SafePaint, /) -> None: ...
    @typing.overload
    def drawBitmap(self, arg1: java.chaquopy.JavaArrayJInt, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, arg4: float | java.jdouble | java.lang.Double, arg5: float | java.jdouble | java.lang.Double, arg6: int | java.jint | java.lang.Integer, arg7: int | java.jint | java.lang.Integer, arg8: bool | java.jboolean | java.lang.Boolean, arg9: SafePaint, /) -> None: ...
    @typing.overload
    def drawBitmap(self, arg1: java.chaquopy.JavaArrayJInt, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, arg4: int | java.jint | java.lang.Integer, arg5: int | java.jint | java.lang.Integer, arg6: int | java.jint | java.lang.Integer, arg7: int | java.jint | java.lang.Integer, arg8: bool | java.jboolean | java.lang.Boolean, arg9: SafePaint, /) -> None: ...
    def drawBitmapMesh(self, arg1: android.graphics.Bitmap, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, arg4: java.chaquopy.JavaArrayJDouble, arg5: int | java.jint | java.lang.Integer, arg6: java.chaquopy.JavaArrayJInt, arg7: int | java.jint | java.lang.Integer, arg8: SafePaint, /) -> None: ...
    def drawCircle(self, arg1: float | java.jdouble | java.lang.Double, arg2: float | java.jdouble | java.lang.Double, arg3: float | java.jfloat | java.lang.Float, arg4: SafePaint, /) -> None: ...
    @typing.overload
    def drawColor(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def drawColor(self, arg1: int | java.jint | java.lang.Integer, arg2: android.graphics.PorterDuff.Mode, /) -> None: ...
    def drawLine(self, arg1: float | java.jdouble | java.lang.Double, arg2: float | java.jdouble | java.lang.Double, arg3: float | java.jdouble | java.lang.Double, arg4: float | java.jdouble | java.lang.Double, arg5: SafePaint, /) -> None: ...
    @typing.overload
    def drawLines(self, arg1: java.chaquopy.JavaArrayJDouble, arg2: SafePaint, /) -> None: ...
    @typing.overload
    def drawLines(self, arg1: java.chaquopy.JavaArrayJDouble, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, arg4: SafePaint, /) -> None: ...
    def drawOval(self, arg1: android.graphics.Rect, arg2: SafePaint, /) -> None: ...
    def drawPaint(self, arg1: SafePaint, /) -> None: ...
    def drawPath(self, arg1: SafeTranslatedPath, arg2: SafePaint, /) -> None: ...
    @typing.overload
    def drawPicture(self, arg1: android.graphics.Picture, /) -> None: ...
    @typing.overload
    def drawPicture(self, arg1: android.graphics.Picture, arg2: android.graphics.Rect, /) -> None: ...
    def drawPoint(self, arg1: float | java.jdouble | java.lang.Double, arg2: float | java.jdouble | java.lang.Double, arg3: SafePaint, /) -> None: ...
    @typing.overload
    def drawPoints(self, arg1: java.chaquopy.JavaArrayJDouble, arg2: SafePaint, /) -> None: ...
    @typing.overload
    def drawPoints(self, arg1: java.chaquopy.JavaArrayJDouble, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, arg4: SafePaint, /) -> None: ...
    @typing.overload
    def drawPosText(self, arg1: str | java.lang.String, arg2: java.chaquopy.JavaArrayJDouble, arg3: SafePaint, /) -> None: ...
    @typing.overload
    def drawPosText(self, arg1: java.chaquopy.JavaArrayJChar, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, arg4: java.chaquopy.JavaArrayJDouble, arg5: SafePaint, /) -> None: ...
    def drawRGB(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def drawRect(self, arg1: android.graphics.Rect, arg2: SafePaint, /) -> None: ...
    @typing.overload
    def drawRect(self, arg1: float | java.jdouble | java.lang.Double, arg2: float | java.jdouble | java.lang.Double, arg3: float | java.jdouble | java.lang.Double, arg4: float | java.jdouble | java.lang.Double, arg5: SafePaint, /) -> None: ...
    def drawRoundRect(self, arg1: android.graphics.Rect, arg2: float | java.jfloat | java.lang.Float, arg3: float | java.jfloat | java.lang.Float, arg4: SafePaint, /) -> None: ...
    @typing.overload
    def drawText(self, arg1: str | java.lang.String, arg2: float | java.jdouble | java.lang.Double, arg3: float | java.jdouble | java.lang.Double, arg4: SafePaint, /) -> None: ...
    @typing.overload
    def drawText(self, arg1: java.lang.CharSequence, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, arg4: float | java.jdouble | java.lang.Double, arg5: float | java.jdouble | java.lang.Double, arg6: SafePaint, /) -> None: ...
    @typing.overload
    def drawText(self, arg1: str | java.lang.String, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, arg4: float | java.jdouble | java.lang.Double, arg5: float | java.jdouble | java.lang.Double, arg6: SafePaint, /) -> None: ...
    @typing.overload
    def drawText(self, arg1: java.chaquopy.JavaArrayJChar, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, arg4: float | java.jdouble | java.lang.Double, arg5: float | java.jdouble | java.lang.Double, arg6: SafePaint, /) -> None: ...
    @typing.overload
    def drawTextOnPath(self, arg1: str | java.lang.String, arg2: SafeTranslatedPath, arg3: float | java.jfloat | java.lang.Float, arg4: float | java.jfloat | java.lang.Float, arg5: SafePaint, /) -> None: ...
    @typing.overload
    def drawTextOnPath(self, arg1: java.chaquopy.JavaArrayJChar, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, arg4: SafeTranslatedPath, arg5: float | java.jfloat | java.lang.Float, arg6: float | java.jfloat | java.lang.Float, arg7: SafePaint, /) -> None: ...
    def drawVertices(self, arg1: android.graphics.Canvas.VertexMode, arg2: int | java.jint | java.lang.Integer, arg3: java.chaquopy.JavaArrayJDouble, arg4: int | java.jint | java.lang.Integer, arg5: java.chaquopy.JavaArrayJFloat, arg6: int | java.jint | java.lang.Integer, arg7: java.chaquopy.JavaArrayJInt, arg8: int | java.jint | java.lang.Integer, arg9: java.chaquopy.JavaArrayJShort, arg10: int | java.jint | java.lang.Integer, arg11: int | java.jint | java.lang.Integer, arg12: SafePaint, /) -> None: ...
    @typing.overload
    def getClipBounds(self) -> android.graphics.Rect: ...
    @typing.overload
    def getClipBounds(self, arg1: android.graphics.Rect, /) -> bool: ...
    def getDensity(self) -> int: ...
    def getDrawFilter(self) -> android.graphics.DrawFilter: ...
    def getHeight(self) -> int: ...
    @typing.overload
    def getMatrix(self) -> android.graphics.Matrix: ...
    @typing.overload
    def getMatrix(self, arg1: android.graphics.Matrix, /) -> None: ...
    def getSafeCanvas(self) -> android.graphics.Canvas: ...
    def getSaveCount(self) -> int: ...
    def getUnsafeCanvas(self, arg1: ISafeCanvas.UnsafeCanvasHandler, /) -> None: ...
    def getWidth(self) -> int: ...
    def getWrappedCanvas(self) -> android.graphics.Canvas: ...
    def getXOffset(self) -> int: ...
    def getYOffset(self) -> int: ...
    def isOpaque(self) -> bool: ...
    @typing.overload
    def quickReject(self, arg1: android.graphics.Rect, arg2: android.graphics.Canvas.EdgeType, /) -> bool: ...
    @typing.overload
    def quickReject(self, arg1: SafeTranslatedPath, arg2: android.graphics.Canvas.EdgeType, /) -> bool: ...
    @typing.overload
    def quickReject(self, arg1: float | java.jdouble | java.lang.Double, arg2: float | java.jdouble | java.lang.Double, arg3: float | java.jdouble | java.lang.Double, arg4: float | java.jdouble | java.lang.Double, arg5: android.graphics.Canvas.EdgeType, /) -> bool: ...
    def restore(self) -> None: ...
    def restoreToCount(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def rotate(self, arg1: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def rotate(self, arg1: float | java.jfloat | java.lang.Float, arg2: float | java.jdouble | java.lang.Double, arg3: float | java.jdouble | java.lang.Double, /) -> None: ...
    @typing.overload
    def save(self) -> int: ...
    @typing.overload
    def save(self, arg1: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    def saveLayer(self, arg1: android.graphics.Rect, arg2: SafePaint, arg3: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    def saveLayer(self, arg1: float | java.jdouble | java.lang.Double, arg2: float | java.jdouble | java.lang.Double, arg3: float | java.jdouble | java.lang.Double, arg4: float | java.jdouble | java.lang.Double, arg5: SafePaint, arg6: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    def saveLayerAlpha(self, arg1: android.graphics.Rect, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    def saveLayerAlpha(self, arg1: float | java.jdouble | java.lang.Double, arg2: float | java.jdouble | java.lang.Double, arg3: float | java.jdouble | java.lang.Double, arg4: float | java.jdouble | java.lang.Double, arg5: int | java.jint | java.lang.Integer, arg6: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    def scale(self, arg1: float | java.jfloat | java.lang.Float, arg2: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def scale(self, arg1: float | java.jfloat | java.lang.Float, arg2: float | java.jfloat | java.lang.Float, arg3: float | java.jdouble | java.lang.Double, arg4: float | java.jdouble | java.lang.Double, /) -> None: ...
    def setBitmap(self, arg1: android.graphics.Bitmap, /) -> None: ...
    def setDensity(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDrawFilter(self, arg1: android.graphics.DrawFilter, /) -> None: ...
    def setMatrix(self, arg1: android.graphics.Matrix, /) -> None: ...
    def skew(self, arg1: float | java.jfloat | java.lang.Float, arg2: float | java.jfloat | java.lang.Float, /) -> None: ...
    def translate(self, arg1: float | java.jfloat | java.lang.Float, arg2: float | java.jfloat | java.lang.Float, /) -> None: ...

    class UnsafeCanvasHandler(java.lang.Object):
        def onUnsafeCanvas(self, arg1: android.graphics.Canvas, /) -> None: ...

class SafeBitmapShader(android.graphics.BitmapShader):
    def __init__(self, bitmap: android.graphics.Bitmap, tileX: android.graphics.Shader.TileMode, tileY: android.graphics.Shader.TileMode, /) -> None: ...
    def onDrawCycleStart(self, canvas: ISafeCanvas, /) -> None: ...

class SafeDashPathEffect(android.graphics.PathDashPathEffect):
    def __init__(self, intervals: java.chaquopy.JavaArrayJFloat, phase: float | java.jfloat | java.lang.Float, strokeWidth: float | java.jfloat | java.lang.Float, /) -> None: ...
    @staticmethod
    def createSafeDashedPath(intervals: java.chaquopy.JavaArrayJFloat, phase: float | java.jfloat | java.lang.Float, strokeWidth: float | java.jfloat | java.lang.Float, reuse: android.graphics.Path, /) -> android.graphics.Path: ...

class SafePaint(android.graphics.Paint):
    def __init__(self) -> None: ...
    def setPathEffect(self, effect: android.graphics.PathEffect, /) -> android.graphics.PathEffect: ...

class SafeTranslatedCanvas(android.graphics.Canvas, ISafeCanvas):
    xOffset: int = ...
    yOffset: int = ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, canvas: android.graphics.Canvas, /) -> None: ...
    @typing.overload
    def clipPath(self, path: SafeTranslatedPath, /) -> bool: ...
    @typing.overload
    def clipPath(self, path: SafeTranslatedPath, op: android.graphics.Region.Op, /) -> bool: ...
    @typing.overload
    def clipRect(self, rect: android.graphics.Rect, /) -> bool: ...
    @typing.overload
    def clipRect(self, rect: android.graphics.Rect, op: android.graphics.Region.Op, /) -> bool: ...
    @typing.overload
    def clipRect(self, left: float | java.jdouble | java.lang.Double, top: float | java.jdouble | java.lang.Double, right: float | java.jdouble | java.lang.Double, bottom: float | java.jdouble | java.lang.Double, /) -> bool: ...
    @typing.overload
    def clipRect(self, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> bool: ...
    @typing.overload
    def clipRect(self, left: float | java.jdouble | java.lang.Double, top: float | java.jdouble | java.lang.Double, right: float | java.jdouble | java.lang.Double, bottom: float | java.jdouble | java.lang.Double, op: android.graphics.Region.Op, /) -> bool: ...
    @typing.overload
    def clipRegion(self, region: android.graphics.Region, /) -> bool: ...
    @typing.overload
    def clipRegion(self, region: android.graphics.Region, op: android.graphics.Region.Op, /) -> bool: ...
    def clone(self) -> java.lang.Object: ...
    def concat(self, matrix: android.graphics.Matrix, /) -> None: ...
    def drawARGB(self, a: int | java.jint | java.lang.Integer, r: int | java.jint | java.lang.Integer, g: int | java.jint | java.lang.Integer, b: int | java.jint | java.lang.Integer, /) -> None: ...
    def drawArc(self, oval: android.graphics.Rect, startAngle: float | java.jfloat | java.lang.Float, sweepAngle: float | java.jfloat | java.lang.Float, useCenter: bool | java.jboolean | java.lang.Boolean, paint: SafePaint, /) -> None: ...
    @typing.overload
    def drawBitmap(self, bitmap: android.graphics.Bitmap, matrix: android.graphics.Matrix, paint: SafePaint, /) -> None: ...
    @typing.overload
    def drawBitmap(self, bitmap: android.graphics.Bitmap, left: float | java.jdouble | java.lang.Double, top: float | java.jdouble | java.lang.Double, paint: SafePaint, /) -> None: ...
    @typing.overload
    def drawBitmap(self, bitmap: android.graphics.Bitmap, src: android.graphics.Rect, dst: android.graphics.Rect, paint: android.graphics.Paint, /) -> None: ...
    @typing.overload
    def drawBitmap(self, bitmap: android.graphics.Bitmap, src: android.graphics.Rect, dst: android.graphics.Rect, paint: SafePaint, /) -> None: ...
    @typing.overload
    def drawBitmap(self, colors: java.chaquopy.JavaArrayJInt, offset: int | java.jint | java.lang.Integer, stride: int | java.jint | java.lang.Integer, x: float | java.jdouble | java.lang.Double, y: float | java.jdouble | java.lang.Double, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, hasAlpha: bool | java.jboolean | java.lang.Boolean, paint: SafePaint, /) -> None: ...
    @typing.overload
    def drawBitmap(self, colors: java.chaquopy.JavaArrayJInt, offset: int | java.jint | java.lang.Integer, stride: int | java.jint | java.lang.Integer, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, hasAlpha: bool | java.jboolean | java.lang.Boolean, paint: SafePaint, /) -> None: ...
    def drawBitmapMesh(self, bitmap: android.graphics.Bitmap, meshWidth: int | java.jint | java.lang.Integer, meshHeight: int | java.jint | java.lang.Integer, verts: java.chaquopy.JavaArrayJDouble, vertOffset: int | java.jint | java.lang.Integer, colors: java.chaquopy.JavaArrayJInt, colorOffset: int | java.jint | java.lang.Integer, paint: SafePaint, /) -> None: ...
    def drawCircle(self, cx: float | java.jdouble | java.lang.Double, cy: float | java.jdouble | java.lang.Double, radius: float | java.jfloat | java.lang.Float, paint: SafePaint, /) -> None: ...
    @typing.overload
    def drawColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def drawColor(self, color: int | java.jint | java.lang.Integer, mode: android.graphics.PorterDuff.Mode, /) -> None: ...
    def drawLine(self, startX: float | java.jdouble | java.lang.Double, startY: float | java.jdouble | java.lang.Double, stopX: float | java.jdouble | java.lang.Double, stopY: float | java.jdouble | java.lang.Double, paint: SafePaint, /) -> None: ...
    @typing.overload
    def drawLines(self, pts: java.chaquopy.JavaArrayJDouble, paint: SafePaint, /) -> None: ...
    @typing.overload
    def drawLines(self, pts: java.chaquopy.JavaArrayJDouble, offset: int | java.jint | java.lang.Integer, count: int | java.jint | java.lang.Integer, paint: SafePaint, /) -> None: ...
    def drawOval(self, oval: android.graphics.Rect, paint: SafePaint, /) -> None: ...
    def drawPaint(self, paint: SafePaint, /) -> None: ...
    def drawPath(self, path: SafeTranslatedPath, paint: SafePaint, /) -> None: ...
    @typing.overload
    def drawPicture(self, picture: android.graphics.Picture, /) -> None: ...
    @typing.overload
    def drawPicture(self, picture: android.graphics.Picture, dst: android.graphics.Rect, /) -> None: ...
    def drawPoint(self, x: float | java.jdouble | java.lang.Double, y: float | java.jdouble | java.lang.Double, paint: SafePaint, /) -> None: ...
    @typing.overload
    def drawPoints(self, pts: java.chaquopy.JavaArrayJDouble, paint: SafePaint, /) -> None: ...
    @typing.overload
    def drawPoints(self, pts: java.chaquopy.JavaArrayJDouble, offset: int | java.jint | java.lang.Integer, count: int | java.jint | java.lang.Integer, paint: SafePaint, /) -> None: ...
    @typing.overload
    def drawPosText(self, text: str | java.lang.String, pos: java.chaquopy.JavaArrayJDouble, paint: SafePaint, /) -> None: ...
    @typing.overload
    def drawPosText(self, text: java.chaquopy.JavaArrayJChar, index: int | java.jint | java.lang.Integer, count: int | java.jint | java.lang.Integer, pos: java.chaquopy.JavaArrayJDouble, paint: SafePaint, /) -> None: ...
    def drawRGB(self, r: int | java.jint | java.lang.Integer, g: int | java.jint | java.lang.Integer, b: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def drawRect(self, r: android.graphics.Rect, paint: SafePaint, /) -> None: ...
    @typing.overload
    def drawRect(self, left: float | java.jdouble | java.lang.Double, top: float | java.jdouble | java.lang.Double, right: float | java.jdouble | java.lang.Double, bottom: float | java.jdouble | java.lang.Double, paint: SafePaint, /) -> None: ...
    def drawRoundRect(self, rect: android.graphics.Rect, rx: float | java.jfloat | java.lang.Float, ry: float | java.jfloat | java.lang.Float, paint: SafePaint, /) -> None: ...
    @typing.overload
    def drawText(self, text: str | java.lang.String, x: float | java.jdouble | java.lang.Double, y: float | java.jdouble | java.lang.Double, paint: SafePaint, /) -> None: ...
    @typing.overload
    def drawText(self, text: java.lang.CharSequence, start: int | java.jint | java.lang.Integer, end: int | java.jint | java.lang.Integer, x: float | java.jdouble | java.lang.Double, y: float | java.jdouble | java.lang.Double, paint: SafePaint, /) -> None: ...
    @typing.overload
    def drawText(self, text: str | java.lang.String, start: int | java.jint | java.lang.Integer, end: int | java.jint | java.lang.Integer, x: float | java.jdouble | java.lang.Double, y: float | java.jdouble | java.lang.Double, paint: SafePaint, /) -> None: ...
    @typing.overload
    def drawText(self, text: java.chaquopy.JavaArrayJChar, index: int | java.jint | java.lang.Integer, count: int | java.jint | java.lang.Integer, x: float | java.jdouble | java.lang.Double, y: float | java.jdouble | java.lang.Double, paint: SafePaint, /) -> None: ...
    @typing.overload
    def drawTextOnPath(self, text: str | java.lang.String, path: SafeTranslatedPath, hOffset: float | java.jfloat | java.lang.Float, vOffset: float | java.jfloat | java.lang.Float, paint: SafePaint, /) -> None: ...
    @typing.overload
    def drawTextOnPath(self, text: java.chaquopy.JavaArrayJChar, index: int | java.jint | java.lang.Integer, count: int | java.jint | java.lang.Integer, path: SafeTranslatedPath, hOffset: float | java.jfloat | java.lang.Float, vOffset: float | java.jfloat | java.lang.Float, paint: SafePaint, /) -> None: ...
    def drawVertices(self, mode: android.graphics.Canvas.VertexMode, vertexCount: int | java.jint | java.lang.Integer, verts: java.chaquopy.JavaArrayJDouble, vertOffset: int | java.jint | java.lang.Integer, texs: java.chaquopy.JavaArrayJFloat, texOffset: int | java.jint | java.lang.Integer, colors: java.chaquopy.JavaArrayJInt, colorOffset: int | java.jint | java.lang.Integer, indices: java.chaquopy.JavaArrayJShort, indexOffset: int | java.jint | java.lang.Integer, indexCount: int | java.jint | java.lang.Integer, paint: SafePaint, /) -> None: ...
    def equals(self, o: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getClipBounds(self, bounds: android.graphics.Rect, /) -> bool: ...
    def getDensity(self) -> int: ...
    def getDrawFilter(self) -> android.graphics.DrawFilter: ...
    def getHeight(self) -> int: ...
    def getMatrix(self, ctm: android.graphics.Matrix, /) -> None: ...
    def getOriginalMatrix(self) -> android.graphics.Matrix: ...
    def getSafeCanvas(self) -> android.graphics.Canvas: ...
    def getSaveCount(self) -> int: ...
    def getUnsafeCanvas(self, handler: ISafeCanvas.UnsafeCanvasHandler, /) -> None: ...
    def getWidth(self) -> int: ...
    def getWrappedCanvas(self) -> android.graphics.Canvas: ...
    def getXOffset(self) -> int: ...
    def getYOffset(self) -> int: ...
    def hashCode(self) -> int: ...
    def isOpaque(self) -> bool: ...
    @typing.overload
    def quickReject(self, rect: android.graphics.Rect, type: android.graphics.Canvas.EdgeType, /) -> bool: ...
    @typing.overload
    def quickReject(self, path: SafeTranslatedPath, type: android.graphics.Canvas.EdgeType, /) -> bool: ...
    @typing.overload
    def quickReject(self, left: float | java.jdouble | java.lang.Double, top: float | java.jdouble | java.lang.Double, right: float | java.jdouble | java.lang.Double, bottom: float | java.jdouble | java.lang.Double, type: android.graphics.Canvas.EdgeType, /) -> bool: ...
    def restore(self) -> None: ...
    def restoreToCount(self, saveCount: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def rotate(self, degrees: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def rotate(self, degrees: float | java.jfloat | java.lang.Float, px: float | java.jdouble | java.lang.Double, py: float | java.jdouble | java.lang.Double, /) -> None: ...
    @typing.overload
    def save(self) -> int: ...
    @typing.overload
    def save(self, saveFlags: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    def saveLayer(self, bounds: android.graphics.Rect, paint: SafePaint, saveFlags: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    def saveLayer(self, left: float | java.jdouble | java.lang.Double, top: float | java.jdouble | java.lang.Double, right: float | java.jdouble | java.lang.Double, bottom: float | java.jdouble | java.lang.Double, paint: SafePaint, saveFlags: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    def saveLayerAlpha(self, bounds: android.graphics.Rect, alpha: int | java.jint | java.lang.Integer, saveFlags: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    def saveLayerAlpha(self, left: float | java.jdouble | java.lang.Double, top: float | java.jdouble | java.lang.Double, right: float | java.jdouble | java.lang.Double, bottom: float | java.jdouble | java.lang.Double, alpha: int | java.jint | java.lang.Integer, saveFlags: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    def scale(self, sx: float | java.jfloat | java.lang.Float, sy: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def scale(self, sx: float | java.jfloat | java.lang.Float, sy: float | java.jfloat | java.lang.Float, px: float | java.jdouble | java.lang.Double, py: float | java.jdouble | java.lang.Double, /) -> None: ...
    def setBitmap(self, bitmap: android.graphics.Bitmap, /) -> None: ...
    def setCanvas(self, canvas: android.graphics.Canvas, /) -> None: ...
    def setDensity(self, density: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDrawFilter(self, filter: android.graphics.DrawFilter, /) -> None: ...
    def setMatrix(self, matrix: android.graphics.Matrix, /) -> None: ...
    def skew(self, sx: float | java.jfloat | java.lang.Float, sy: float | java.jfloat | java.lang.Float, /) -> None: ...
    def toOffsetFloatAry(self, rect: java.chaquopy.JavaArrayJDouble, reuse: java.chaquopy.JavaArrayJFloat, /) -> java.chaquopy.JavaArrayJFloat: ...
    def toOffsetRectF(self, rect: android.graphics.Rect, reuse: android.graphics.RectF, /) -> android.graphics.RectF: ...
    def toString(self) -> str: ...
    def translate(self, dx: float | java.jfloat | java.lang.Float, dy: float | java.jfloat | java.lang.Float, /) -> None: ...

class SafeTranslatedPath(android.graphics.Path):
    xOffset: int = ...
    yOffset: int = ...
    def __init__(self) -> None: ...
    @typing.overload
    def addArc(self, oval: android.graphics.Rect, startAngle: float | java.jfloat | java.lang.Float, sweepAngle: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def addArc(self, oval: android.graphics.RectF, startAngle: float | java.jfloat | java.lang.Float, sweepAngle: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def addCircle(self, x: float | java.jdouble | java.lang.Double, y: float | java.jdouble | java.lang.Double, radius: float | java.jfloat | java.lang.Float, dir: android.graphics.Path.Direction, /) -> None: ...
    @typing.overload
    def addCircle(self, x: float | java.jfloat | java.lang.Float, y: float | java.jfloat | java.lang.Float, radius: float | java.jfloat | java.lang.Float, dir: android.graphics.Path.Direction, /) -> None: ...
    @typing.overload
    def addOval(self, oval: android.graphics.Rect, dir: android.graphics.Path.Direction, /) -> None: ...
    @typing.overload
    def addOval(self, oval: android.graphics.RectF, dir: android.graphics.Path.Direction, /) -> None: ...
    @typing.overload
    def addPath(self, src: android.graphics.Path, /) -> None: ...
    @typing.overload
    def addPath(self, src: android.graphics.Path, matrix: android.graphics.Matrix, /) -> None: ...
    @typing.overload
    def addPath(self, src: android.graphics.Path, dx: float | java.jfloat | java.lang.Float, dy: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def addRect(self, rect: android.graphics.Rect, dir: android.graphics.Path.Direction, /) -> None: ...
    @typing.overload
    def addRect(self, rect: android.graphics.RectF, dir: android.graphics.Path.Direction, /) -> None: ...
    @typing.overload
    def addRect(self, left: float | java.jdouble | java.lang.Double, top: float | java.jdouble | java.lang.Double, right: float | java.jdouble | java.lang.Double, bottom: float | java.jdouble | java.lang.Double, dir: android.graphics.Path.Direction, /) -> None: ...
    @typing.overload
    def addRect(self, left: float | java.jfloat | java.lang.Float, top: float | java.jfloat | java.lang.Float, right: float | java.jfloat | java.lang.Float, bottom: float | java.jfloat | java.lang.Float, dir: android.graphics.Path.Direction, /) -> None: ...
    @typing.overload
    def addRoundRect(self, rect: android.graphics.Rect, radii: java.chaquopy.JavaArrayJFloat, dir: android.graphics.Path.Direction, /) -> None: ...
    @typing.overload
    def addRoundRect(self, rect: android.graphics.RectF, radii: java.chaquopy.JavaArrayJFloat, dir: android.graphics.Path.Direction, /) -> None: ...
    @typing.overload
    def addRoundRect(self, rect: android.graphics.Rect, rx: float | java.jfloat | java.lang.Float, ry: float | java.jfloat | java.lang.Float, dir: android.graphics.Path.Direction, /) -> None: ...
    @typing.overload
    def addRoundRect(self, rect: android.graphics.RectF, rx: float | java.jfloat | java.lang.Float, ry: float | java.jfloat | java.lang.Float, dir: android.graphics.Path.Direction, /) -> None: ...
    @typing.overload
    def arcTo(self, oval: android.graphics.Rect, startAngle: float | java.jfloat | java.lang.Float, sweepAngle: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def arcTo(self, oval: android.graphics.RectF, startAngle: float | java.jfloat | java.lang.Float, sweepAngle: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def arcTo(self, oval: android.graphics.Rect, startAngle: float | java.jfloat | java.lang.Float, sweepAngle: float | java.jfloat | java.lang.Float, forceMoveTo: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def arcTo(self, oval: android.graphics.RectF, startAngle: float | java.jfloat | java.lang.Float, sweepAngle: float | java.jfloat | java.lang.Float, forceMoveTo: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def close(self) -> None: ...
    @typing.overload
    def computeBounds(self, bounds: android.graphics.Rect, exact: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def computeBounds(self, bounds: android.graphics.RectF, exact: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def cubicTo(self, x1: float | java.jdouble | java.lang.Double, y1: float | java.jdouble | java.lang.Double, x2: float | java.jdouble | java.lang.Double, y2: float | java.jdouble | java.lang.Double, x3: float | java.jdouble | java.lang.Double, y3: float | java.jdouble | java.lang.Double, /) -> None: ...
    @typing.overload
    def cubicTo(self, x1: float | java.jfloat | java.lang.Float, y1: float | java.jfloat | java.lang.Float, x2: float | java.jfloat | java.lang.Float, y2: float | java.jfloat | java.lang.Float, x3: float | java.jfloat | java.lang.Float, y3: float | java.jfloat | java.lang.Float, /) -> None: ...
    def finalize(self) -> None: ...
    def getFillType(self) -> android.graphics.Path.FillType: ...
    def incReserve(self, extraPtCount: int | java.jint | java.lang.Integer, /) -> None: ...
    def isEmpty(self) -> bool: ...
    def isInverseFillType(self) -> bool: ...
    @typing.overload
    def isRect(self, rect: android.graphics.Rect, /) -> bool: ...
    @typing.overload
    def isRect(self, rect: android.graphics.RectF, /) -> bool: ...
    @typing.overload
    def lineTo(self, x: float | java.jdouble | java.lang.Double, y: float | java.jdouble | java.lang.Double, /) -> None: ...
    @typing.overload
    def lineTo(self, x: float | java.jfloat | java.lang.Float, y: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def moveTo(self, x: float | java.jdouble | java.lang.Double, y: float | java.jdouble | java.lang.Double, /) -> None: ...
    @typing.overload
    def moveTo(self, x: float | java.jfloat | java.lang.Float, y: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def offset(self, dx: float | java.jfloat | java.lang.Float, dy: float | java.jfloat | java.lang.Float, /) -> None: ...
    @typing.overload
    def offset(self, dx: float | java.jfloat | java.lang.Float, dy: float | java.jfloat | java.lang.Float, dst: android.graphics.Path, /) -> None: ...
    def onDrawCycleStart(self, canvas: ISafeCanvas, /) -> None: ...
    @typing.overload
    def quadTo(self, x1: float | java.jdouble | java.lang.Double, y1: float | java.jdouble | java.lang.Double, x2: float | java.jdouble | java.lang.Double, y2: float | java.jdouble | java.lang.Double, /) -> None: ...
    @typing.overload
    def quadTo(self, x1: float | java.jfloat | java.lang.Float, y1: float | java.jfloat | java.lang.Float, x2: float | java.jfloat | java.lang.Float, y2: float | java.jfloat | java.lang.Float, /) -> None: ...
    def rCubicTo(self, x1: float | java.jfloat | java.lang.Float, y1: float | java.jfloat | java.lang.Float, x2: float | java.jfloat | java.lang.Float, y2: float | java.jfloat | java.lang.Float, x3: float | java.jfloat | java.lang.Float, y3: float | java.jfloat | java.lang.Float, /) -> None: ...
    def rLineTo(self, dx: float | java.jfloat | java.lang.Float, dy: float | java.jfloat | java.lang.Float, /) -> None: ...
    def rMoveTo(self, dx: float | java.jfloat | java.lang.Float, dy: float | java.jfloat | java.lang.Float, /) -> None: ...
    def rQuadTo(self, dx1: float | java.jfloat | java.lang.Float, dy1: float | java.jfloat | java.lang.Float, dx2: float | java.jfloat | java.lang.Float, dy2: float | java.jfloat | java.lang.Float, /) -> None: ...
    def reset(self) -> None: ...
    def rewind(self) -> None: ...
    def set(self, src: android.graphics.Path, /) -> None: ...
    def setFillType(self, ft: android.graphics.Path.FillType, /) -> None: ...
    @typing.overload
    def setLastPoint(self, dx: float | java.jdouble | java.lang.Double, dy: float | java.jdouble | java.lang.Double, /) -> None: ...
    @typing.overload
    def setLastPoint(self, dx: float | java.jfloat | java.lang.Float, dy: float | java.jfloat | java.lang.Float, /) -> None: ...
    def toOffsetRectF(self, rect: android.graphics.Rect, reuse: android.graphics.RectF, /) -> android.graphics.RectF: ...
    def toggleInverseFillType(self) -> None: ...
    @typing.overload
    def transform(self, matrix: android.graphics.Matrix, /) -> None: ...
    @typing.overload
    def transform(self, matrix: android.graphics.Matrix, dst: android.graphics.Path, /) -> None: ...
