import typing

import java
import java.lang
import java.lang.annotation
import java.util.concurrent
import kotlin
import kotlin.jvm.functions

class AbstractDoubleTimeSource(TimeSource):
    def __init__(self, unit: java.util.concurrent.TimeUnit, /) -> None: ...
    def getUnit(self) -> java.util.concurrent.TimeUnit: ...
    def markNow(self) -> TimeMark: ...
    def read(self) -> float: ...

class AbstractLongTimeSource(TimeSource):
    def __init__(self, unit: java.util.concurrent.TimeUnit, /) -> None: ...
    def getUnit(self) -> java.util.concurrent.TimeUnit: ...
    def markNow(self) -> TimeMark: ...
    def read(self) -> int: ...

class AdjustedTimeMark(TimeMark):
    def elapsedNow-UwyO8pc(self) -> int: ...
    def getAdjustment-UwyO8pc(self) -> int: ...
    def getMark(self) -> TimeMark: ...
    def plus-LRDsOJo(self, duration: int | java.jlong | java.lang.Long, /) -> TimeMark: ...

class Duration(java.lang.Comparable[Duration]):
    Companion: typing.ClassVar[Duration.Companion] = ...
    @typing.overload
    def compareTo-LRDsOJo(self, arg1: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def compareTo-LRDsOJo(this: int | java.jlong | java.lang.Long, other: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def constructor-impl(rawValue: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def div-LRDsOJo(this: int | java.jlong | java.lang.Long, other: int | java.jlong | java.lang.Long, /) -> float: ...
    @typing.overload
    @staticmethod
    def div-UwyO8pc(this: int | java.jlong | java.lang.Long, scale: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def div-UwyO8pc(this: int | java.jlong | java.lang.Long, scale: int | java.jint | java.lang.Integer, /) -> int: ...
    def equals(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl(arg1: int | java.jlong | java.lang.Long, arg2: java.lang.Object | int | bool | float | str, /) -> bool: ...
    @staticmethod
    def equals-impl0(p1: int | java.jlong | java.lang.Long, p2: int | java.jlong | java.lang.Long, /) -> bool: ...
    @staticmethod
    def getAbsoluteValue-UwyO8pc(this: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def getHoursComponent-impl(this: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def getInDays-impl(this: int | java.jlong | java.lang.Long, /) -> float: ...
    @staticmethod
    def getInHours-impl(this: int | java.jlong | java.lang.Long, /) -> float: ...
    @staticmethod
    def getInMicroseconds-impl(this: int | java.jlong | java.lang.Long, /) -> float: ...
    @staticmethod
    def getInMilliseconds-impl(this: int | java.jlong | java.lang.Long, /) -> float: ...
    @staticmethod
    def getInMinutes-impl(this: int | java.jlong | java.lang.Long, /) -> float: ...
    @staticmethod
    def getInNanoseconds-impl(this: int | java.jlong | java.lang.Long, /) -> float: ...
    @staticmethod
    def getInSeconds-impl(this: int | java.jlong | java.lang.Long, /) -> float: ...
    @staticmethod
    def getInWholeDays-impl(this: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def getInWholeHours-impl(this: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def getInWholeMicroseconds-impl(this: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def getInWholeMilliseconds-impl(this: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def getInWholeMinutes-impl(this: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def getInWholeNanoseconds-impl(this: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def getInWholeSeconds-impl(this: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def getMinutesComponent-impl(this: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def getNanosecondsComponent-impl(this: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def getSecondsComponent-impl(this: int | java.jlong | java.lang.Long, /) -> int: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def hashCode-impl(arg1: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def isFinite-impl(this: int | java.jlong | java.lang.Long, /) -> bool: ...
    @staticmethod
    def isInfinite-impl(this: int | java.jlong | java.lang.Long, /) -> bool: ...
    @staticmethod
    def isNegative-impl(this: int | java.jlong | java.lang.Long, /) -> bool: ...
    @staticmethod
    def isPositive-impl(this: int | java.jlong | java.lang.Long, /) -> bool: ...
    @staticmethod
    def minus-LRDsOJo(this: int | java.jlong | java.lang.Long, other: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def plus-LRDsOJo(this: int | java.jlong | java.lang.Long, other: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def times-UwyO8pc(this: int | java.jlong | java.lang.Long, scale: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def times-UwyO8pc(this: int | java.jlong | java.lang.Long, scale: int | java.jint | java.lang.Integer, /) -> int: ...
    _toComponents-impl_0__T = typing.TypeVar('_toComponents-impl_0__T')  # <T>
    _toComponents-impl_1__T = typing.TypeVar('_toComponents-impl_1__T')  # <T>
    _toComponents-impl_2__T = typing.TypeVar('_toComponents-impl_2__T')  # <T>
    _toComponents-impl_3__T = typing.TypeVar('_toComponents-impl_3__T')  # <T>
    @typing.overload
    @staticmethod
    def toComponents-impl(this: int | java.jlong | java.lang.Long, action: kotlin.jvm.functions.Function2[int, int, _toComponents-impl_0__T], /) -> _toComponents-impl_0__T: ...
    @typing.overload
    @staticmethod
    def toComponents-impl(this: int | java.jlong | java.lang.Long, action: kotlin.jvm.functions.Function3[int, int, int, _toComponents-impl_1__T], /) -> _toComponents-impl_1__T: ...
    @typing.overload
    @staticmethod
    def toComponents-impl(this: int | java.jlong | java.lang.Long, action: kotlin.jvm.functions.Function4[int, int, int, int, _toComponents-impl_2__T], /) -> _toComponents-impl_2__T: ...
    @typing.overload
    @staticmethod
    def toComponents-impl(this: int | java.jlong | java.lang.Long, action: kotlin.jvm.functions.Function5[int, int, int, int, int, _toComponents-impl_3__T], /) -> _toComponents-impl_3__T: ...
    @staticmethod
    def toDouble-impl(this: int | java.jlong | java.lang.Long, unit: java.util.concurrent.TimeUnit, /) -> float: ...
    @staticmethod
    def toInt-impl(this: int | java.jlong | java.lang.Long, unit: java.util.concurrent.TimeUnit, /) -> int: ...
    @staticmethod
    def toIsoString-impl(this: int | java.jlong | java.lang.Long, /) -> str: ...
    @staticmethod
    def toLong-impl(this: int | java.jlong | java.lang.Long, unit: java.util.concurrent.TimeUnit, /) -> int: ...
    @staticmethod
    def toLongMilliseconds-impl(this: int | java.jlong | java.lang.Long, /) -> int: ...
    @staticmethod
    def toLongNanoseconds-impl(this: int | java.jlong | java.lang.Long, /) -> int: ...
    def toString(self) -> str: ...
    @typing.overload
    @staticmethod
    def toString-impl(this: int | java.jlong | java.lang.Long, /) -> str: ...
    @typing.overload
    @staticmethod
    def toString-impl(this: int | java.jlong | java.lang.Long, unit: java.util.concurrent.TimeUnit, decimals: int | java.jint | java.lang.Integer, /) -> str: ...
    @staticmethod
    def unaryMinus-UwyO8pc(this: int | java.jlong | java.lang.Long, /) -> int: ...

    class Companion(java.lang.Object):
        def convert(self, value: float | java.jdouble | java.lang.Double, sourceUnit: java.util.concurrent.TimeUnit, targetUnit: java.util.concurrent.TimeUnit, /) -> float: ...
        @typing.overload
        def days-UwyO8pc(self, value: float | java.jdouble | java.lang.Double, /) -> int: ...
        @typing.overload
        def days-UwyO8pc(self, value: int | java.jint | java.lang.Integer, /) -> int: ...
        @typing.overload
        def days-UwyO8pc(self, value: int | java.jlong | java.lang.Long, /) -> int: ...
        def getINFINITE-UwyO8pc(self) -> int: ...
        def getNEG_INFINITE-UwyO8pc$kotlin_stdlib(self) -> int: ...
        def getZERO-UwyO8pc(self) -> int: ...
        @typing.overload
        def hours-UwyO8pc(self, value: float | java.jdouble | java.lang.Double, /) -> int: ...
        @typing.overload
        def hours-UwyO8pc(self, value: int | java.jint | java.lang.Integer, /) -> int: ...
        @typing.overload
        def hours-UwyO8pc(self, value: int | java.jlong | java.lang.Long, /) -> int: ...
        @typing.overload
        def microseconds-UwyO8pc(self, value: float | java.jdouble | java.lang.Double, /) -> int: ...
        @typing.overload
        def microseconds-UwyO8pc(self, value: int | java.jint | java.lang.Integer, /) -> int: ...
        @typing.overload
        def microseconds-UwyO8pc(self, value: int | java.jlong | java.lang.Long, /) -> int: ...
        @typing.overload
        def milliseconds-UwyO8pc(self, value: float | java.jdouble | java.lang.Double, /) -> int: ...
        @typing.overload
        def milliseconds-UwyO8pc(self, value: int | java.jint | java.lang.Integer, /) -> int: ...
        @typing.overload
        def milliseconds-UwyO8pc(self, value: int | java.jlong | java.lang.Long, /) -> int: ...
        @typing.overload
        def minutes-UwyO8pc(self, value: float | java.jdouble | java.lang.Double, /) -> int: ...
        @typing.overload
        def minutes-UwyO8pc(self, value: int | java.jint | java.lang.Integer, /) -> int: ...
        @typing.overload
        def minutes-UwyO8pc(self, value: int | java.jlong | java.lang.Long, /) -> int: ...
        @typing.overload
        def nanoseconds-UwyO8pc(self, value: float | java.jdouble | java.lang.Double, /) -> int: ...
        @typing.overload
        def nanoseconds-UwyO8pc(self, value: int | java.jint | java.lang.Integer, /) -> int: ...
        @typing.overload
        def nanoseconds-UwyO8pc(self, value: int | java.jlong | java.lang.Long, /) -> int: ...
        @typing.overload
        def seconds-UwyO8pc(self, value: float | java.jdouble | java.lang.Double, /) -> int: ...
        @typing.overload
        def seconds-UwyO8pc(self, value: int | java.jint | java.lang.Integer, /) -> int: ...
        @typing.overload
        def seconds-UwyO8pc(self, value: int | java.jlong | java.lang.Long, /) -> int: ...

class DurationKt(java.lang.Object):
    NANOS_IN_MILLIS: typing.ClassVar[int] = ...
    MAX_NANOS: typing.ClassVar[int] = ...
    MAX_MILLIS: typing.ClassVar[int] = ...
    @typing.overload
    @staticmethod
    def getDays(this_days: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def getDays(this_days: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getDays(this_days: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def getHours(this_hours: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def getHours(this_hours: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getHours(this_hours: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMicroseconds(this_microseconds: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMicroseconds(this_microseconds: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMicroseconds(this_microseconds: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMilliseconds(this_milliseconds: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMilliseconds(this_milliseconds: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMilliseconds(this_milliseconds: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMinutes(this_minutes: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMinutes(this_minutes: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getMinutes(this_minutes: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def getNanoseconds(this_nanoseconds: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def getNanoseconds(this_nanoseconds: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getNanoseconds(this_nanoseconds: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def getSeconds(this_seconds: float | java.jdouble | java.lang.Double, /) -> int: ...
    @typing.overload
    @staticmethod
    def getSeconds(this_seconds: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getSeconds(this_seconds: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def toDuration(this_toDuration: float | java.jdouble | java.lang.Double, unit: java.util.concurrent.TimeUnit, /) -> int: ...
    @typing.overload
    @staticmethod
    def toDuration(this_toDuration: int | java.jint | java.lang.Integer, unit: java.util.concurrent.TimeUnit, /) -> int: ...
    @typing.overload
    @staticmethod
    def toDuration(this_toDuration: int | java.jlong | java.lang.Long, unit: java.util.concurrent.TimeUnit, /) -> int: ...

class DurationUnitKt(DurationUnitKt__DurationUnitKt): ...

class DurationUnitKt__DurationUnitJvmKt(java.lang.Object):
    def __init__(self) -> None: ...
    @typing.overload
    @staticmethod
    def convertDurationUnit(value: float | java.jdouble | java.lang.Double, sourceUnit: java.util.concurrent.TimeUnit, targetUnit: java.util.concurrent.TimeUnit, /) -> float: ...
    @typing.overload
    @staticmethod
    def convertDurationUnit(value: int | java.jlong | java.lang.Long, sourceUnit: java.util.concurrent.TimeUnit, targetUnit: java.util.concurrent.TimeUnit, /) -> int: ...
    @staticmethod
    def convertDurationUnitOverflow(value: int | java.jlong | java.lang.Long, sourceUnit: java.util.concurrent.TimeUnit, targetUnit: java.util.concurrent.TimeUnit, /) -> int: ...

class DurationUnitKt__DurationUnitKt(DurationUnitKt__DurationUnitJvmKt):
    def __init__(self) -> None: ...
    @staticmethod
    def shortName(this_shortName: java.util.concurrent.TimeUnit, /) -> str: ...

class ExperimentalTime(java.lang.annotation.Annotation): ...

class FormatToDecimalsKt(java.lang.Object):
    @staticmethod
    def formatScientific(value: float | java.jdouble | java.lang.Double, /) -> str: ...
    @staticmethod
    def formatToExactDecimals(value: float | java.jdouble | java.lang.Double, decimals: int | java.jint | java.lang.Integer, /) -> str: ...
    @staticmethod
    def formatUpToDecimals(value: float | java.jdouble | java.lang.Double, decimals: int | java.jint | java.lang.Integer, /) -> str: ...

class MeasureTimeKt(java.lang.Object):
    @typing.overload
    @staticmethod
    def measureTime(block: kotlin.jvm.functions.Function0[kotlin.Unit], /) -> int: ...
    @typing.overload
    @staticmethod
    def measureTime(this_measureTime: TimeSource, block: kotlin.jvm.functions.Function0[kotlin.Unit], /) -> int: ...
    _measureTimedValue_0__T = typing.TypeVar('_measureTimedValue_0__T')  # <T>
    _measureTimedValue_1__T = typing.TypeVar('_measureTimedValue_1__T')  # <T>
    @typing.overload
    @staticmethod
    def measureTimedValue(block: kotlin.jvm.functions.Function0[_measureTimedValue_0__T], /) -> TimedValue[_measureTimedValue_0__T]: ...
    @typing.overload
    @staticmethod
    def measureTimedValue(this_measureTimedValue: TimeSource, block: kotlin.jvm.functions.Function0[_measureTimedValue_1__T], /) -> TimedValue[_measureTimedValue_1__T]: ...

class MonotonicTimeSource(AbstractLongTimeSource, TimeSource):
    INSTANCE: typing.ClassVar[MonotonicTimeSource] = ...
    def read(self) -> int: ...
    def toString(self) -> str: ...

class TestTimeSource(AbstractLongTimeSource):
    def __init__(self) -> None: ...
    def plusAssign-LRDsOJo(self, duration: int | java.jlong | java.lang.Long, /) -> None: ...
    def read(self) -> int: ...

class TimeMark(java.lang.Object):
    def __init__(self) -> None: ...
    def elapsedNow-UwyO8pc(self) -> int: ...
    def hasNotPassedNow(self) -> bool: ...
    def hasPassedNow(self) -> bool: ...
    def minus-LRDsOJo(self, duration: int | java.jlong | java.lang.Long, /) -> TimeMark: ...
    def plus-LRDsOJo(self, duration: int | java.jlong | java.lang.Long, /) -> TimeMark: ...

class TimeSource(java.lang.Object):
    Companion: typing.ClassVar[TimeSource.Companion] = ...
    def markNow(self) -> TimeMark: ...

    class Monotonic(TimeSource):
        INSTANCE: typing.ClassVar[TimeSource.Monotonic] = ...
        def markNow(self) -> TimeMark: ...
        def toString(self) -> str: ...

    class Companion(java.lang.Object): ...

class TimeSourceKt(java.lang.Object): ...

_TimedValue__T = typing.TypeVar('_TimedValue__T')  # <T>
class TimedValue(java.lang.Object, typing.Generic[_TimedValue__T]):
    def component1(self) -> _TimedValue__T: ...
    def component2-UwyO8pc(self) -> int: ...
    def copy-RFiDyg4(self, value: _TimedValue__T, duration: int | java.jlong | java.lang.Long, /) -> TimedValue[_TimedValue__T]: ...
    def equals(self, arg1: java.lang.Object | int | bool | float | str, /) -> bool: ...
    def getDuration-UwyO8pc(self) -> int: ...
    def getValue(self) -> _TimedValue__T: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
