import typing

import android.graphics
import android.graphics.drawable
import java
import java.chaquopy
import java.lang
import java.util
import kotlin
import kotlin.jvm.functions

class BitmapKt(java.lang.Object):
    @staticmethod
    def applyCanvas(this_applyCanvas: android.graphics.Bitmap, block: kotlin.jvm.functions.Function1[android.graphics.Canvas, kotlin.Unit], /) -> android.graphics.Bitmap: ...
    @typing.overload
    @staticmethod
    def contains(this_contains: android.graphics.Bitmap, p: android.graphics.Point, /) -> bool: ...
    @typing.overload
    @staticmethod
    def contains(this_contains: android.graphics.Bitmap, p: android.graphics.PointF, /) -> bool: ...
    @typing.overload
    @staticmethod
    def createBitmap(width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, config: android.graphics.Bitmap.Config, /) -> android.graphics.Bitmap: ...
    @typing.overload
    @staticmethod
    def createBitmap(width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, config: android.graphics.Bitmap.Config, hasAlpha: bool | java.jboolean | java.lang.Boolean, colorSpace: android.graphics.ColorSpace, /) -> android.graphics.Bitmap: ...
    @staticmethod
    def get(this_get: android.graphics.Bitmap, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, /) -> int: ...
    @staticmethod
    def scale(this_scale: android.graphics.Bitmap, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, filter: bool | java.jboolean | java.lang.Boolean, /) -> android.graphics.Bitmap: ...
    @staticmethod
    def set(this_set: android.graphics.Bitmap, x: int | java.jint | java.lang.Integer, y: int | java.jint | java.lang.Integer, color: int | java.jint | java.lang.Integer, /) -> None: ...

class CanvasKt(java.lang.Object):
    @typing.overload
    @staticmethod
    def withClip(this_withClip: android.graphics.Canvas, clipPath: android.graphics.Path, block: kotlin.jvm.functions.Function1[android.graphics.Canvas, kotlin.Unit], /) -> None: ...
    @typing.overload
    @staticmethod
    def withClip(this_withClip: android.graphics.Canvas, clipRect: android.graphics.Rect, block: kotlin.jvm.functions.Function1[android.graphics.Canvas, kotlin.Unit], /) -> None: ...
    @typing.overload
    @staticmethod
    def withClip(this_withClip: android.graphics.Canvas, clipRect: android.graphics.RectF, block: kotlin.jvm.functions.Function1[android.graphics.Canvas, kotlin.Unit], /) -> None: ...
    @typing.overload
    @staticmethod
    def withClip(this_withClip: android.graphics.Canvas, left: float | java.jfloat | java.lang.Float, top: float | java.jfloat | java.lang.Float, right: float | java.jfloat | java.lang.Float, bottom: float | java.jfloat | java.lang.Float, block: kotlin.jvm.functions.Function1[android.graphics.Canvas, kotlin.Unit], /) -> None: ...
    @typing.overload
    @staticmethod
    def withClip(this_withClip: android.graphics.Canvas, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, block: kotlin.jvm.functions.Function1[android.graphics.Canvas, kotlin.Unit], /) -> None: ...
    @staticmethod
    def withMatrix(this_withMatrix: android.graphics.Canvas, matrix: android.graphics.Matrix, block: kotlin.jvm.functions.Function1[android.graphics.Canvas, kotlin.Unit], /) -> None: ...
    @staticmethod
    def withRotation(this_withRotation: android.graphics.Canvas, degrees: float | java.jfloat | java.lang.Float, pivotX: float | java.jfloat | java.lang.Float, pivotY: float | java.jfloat | java.lang.Float, block: kotlin.jvm.functions.Function1[android.graphics.Canvas, kotlin.Unit], /) -> None: ...
    @staticmethod
    def withSave(this_withSave: android.graphics.Canvas, block: kotlin.jvm.functions.Function1[android.graphics.Canvas, kotlin.Unit], /) -> None: ...
    @staticmethod
    def withScale(this_withScale: android.graphics.Canvas, x: float | java.jfloat | java.lang.Float, y: float | java.jfloat | java.lang.Float, pivotX: float | java.jfloat | java.lang.Float, pivotY: float | java.jfloat | java.lang.Float, block: kotlin.jvm.functions.Function1[android.graphics.Canvas, kotlin.Unit], /) -> None: ...
    @staticmethod
    def withSkew(this_withSkew: android.graphics.Canvas, x: float | java.jfloat | java.lang.Float, y: float | java.jfloat | java.lang.Float, block: kotlin.jvm.functions.Function1[android.graphics.Canvas, kotlin.Unit], /) -> None: ...
    @staticmethod
    def withTranslation(this_withTranslation: android.graphics.Canvas, x: float | java.jfloat | java.lang.Float, y: float | java.jfloat | java.lang.Float, block: kotlin.jvm.functions.Function1[android.graphics.Canvas, kotlin.Unit], /) -> None: ...

class ColorKt(java.lang.Object):
    @typing.overload
    @staticmethod
    def component1(this_component1: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def component1(this_component1: int | java.jlong | java.lang.Long, /) -> float: ...
    @typing.overload
    @staticmethod
    def component1(this_component1: android.graphics.Color, /) -> float: ...
    @typing.overload
    @staticmethod
    def component2(this_component2: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def component2(this_component2: int | java.jlong | java.lang.Long, /) -> float: ...
    @typing.overload
    @staticmethod
    def component2(this_component2: android.graphics.Color, /) -> float: ...
    @typing.overload
    @staticmethod
    def component3(this_component3: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def component3(this_component3: int | java.jlong | java.lang.Long, /) -> float: ...
    @typing.overload
    @staticmethod
    def component3(this_component3: android.graphics.Color, /) -> float: ...
    @typing.overload
    @staticmethod
    def component4(this_component4: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def component4(this_component4: int | java.jlong | java.lang.Long, /) -> float: ...
    @typing.overload
    @staticmethod
    def component4(this_component4: android.graphics.Color, /) -> float: ...
    @typing.overload
    @staticmethod
    def convertTo(this_convertTo: int | java.jint | java.lang.Integer, colorSpace: android.graphics.ColorSpace.Named, /) -> int: ...
    @typing.overload
    @staticmethod
    def convertTo(this_convertTo: int | java.jint | java.lang.Integer, colorSpace: android.graphics.ColorSpace, /) -> int: ...
    @typing.overload
    @staticmethod
    def convertTo(this_convertTo: int | java.jlong | java.lang.Long, colorSpace: android.graphics.ColorSpace.Named, /) -> int: ...
    @typing.overload
    @staticmethod
    def convertTo(this_convertTo: int | java.jlong | java.lang.Long, colorSpace: android.graphics.ColorSpace, /) -> int: ...
    @typing.overload
    @staticmethod
    def convertTo(this_convertTo: android.graphics.Color, colorSpace: android.graphics.ColorSpace.Named, /) -> android.graphics.Color: ...
    @typing.overload
    @staticmethod
    def convertTo(this_convertTo: android.graphics.Color, colorSpace: android.graphics.ColorSpace, /) -> android.graphics.Color: ...
    @typing.overload
    @staticmethod
    def getAlpha(this_alpha: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getAlpha(this_alpha: int | java.jlong | java.lang.Long, /) -> float: ...
    @typing.overload
    @staticmethod
    def getBlue(this_blue: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getBlue(this_blue: int | java.jlong | java.lang.Long, /) -> float: ...
    @staticmethod
    def getColorSpace(this_colorSpace: int | java.jlong | java.lang.Long, /) -> android.graphics.ColorSpace: ...
    @typing.overload
    @staticmethod
    def getGreen(this_green: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getGreen(this_green: int | java.jlong | java.lang.Long, /) -> float: ...
    @typing.overload
    @staticmethod
    def getLuminance(this_luminance: int | java.jint | java.lang.Integer, /) -> float: ...
    @typing.overload
    @staticmethod
    def getLuminance(this_luminance: int | java.jlong | java.lang.Long, /) -> float: ...
    @typing.overload
    @staticmethod
    def getRed(this_red: int | java.jint | java.lang.Integer, /) -> int: ...
    @typing.overload
    @staticmethod
    def getRed(this_red: int | java.jlong | java.lang.Long, /) -> float: ...
    @staticmethod
    def isSrgb(this_isSrgb: int | java.jlong | java.lang.Long, /) -> bool: ...
    @staticmethod
    def isWideGamut(this_isWideGamut: int | java.jlong | java.lang.Long, /) -> bool: ...
    @staticmethod
    def plus(this_plus: android.graphics.Color, c: android.graphics.Color, /) -> android.graphics.Color: ...
    @typing.overload
    @staticmethod
    def toColor(this_toColor: int | java.jint | java.lang.Integer, /) -> android.graphics.Color: ...
    @typing.overload
    @staticmethod
    def toColor(this_toColor: int | java.jlong | java.lang.Long, /) -> android.graphics.Color: ...
    @typing.overload
    @staticmethod
    def toColorInt(this_toColorInt: int | java.jlong | java.lang.Long, /) -> int: ...
    @typing.overload
    @staticmethod
    def toColorInt(this_toColorInt: str | java.lang.String, /) -> int: ...
    @staticmethod
    def toColorLong(this_toColorLong: int | java.jint | java.lang.Integer, /) -> int: ...

class ImageDecoderKt(java.lang.Object):
    @staticmethod
    def decodeBitmap(this_decodeBitmap: android.graphics.ImageDecoder.Source, action: kotlin.jvm.functions.Function3[android.graphics.ImageDecoder, android.graphics.ImageDecoder.ImageInfo, android.graphics.ImageDecoder.Source, kotlin.Unit], /) -> android.graphics.Bitmap: ...
    @staticmethod
    def decodeDrawable(this_decodeDrawable: android.graphics.ImageDecoder.Source, action: kotlin.jvm.functions.Function3[android.graphics.ImageDecoder, android.graphics.ImageDecoder.ImageInfo, android.graphics.ImageDecoder.Source, kotlin.Unit], /) -> android.graphics.drawable.Drawable: ...

class MatrixKt(java.lang.Object):
    @staticmethod
    def rotationMatrix(degrees: float | java.jfloat | java.lang.Float, px: float | java.jfloat | java.lang.Float, py: float | java.jfloat | java.lang.Float, /) -> android.graphics.Matrix: ...
    @staticmethod
    def scaleMatrix(sx: float | java.jfloat | java.lang.Float, sy: float | java.jfloat | java.lang.Float, /) -> android.graphics.Matrix: ...
    @staticmethod
    def times(this_times: android.graphics.Matrix, m: android.graphics.Matrix, /) -> android.graphics.Matrix: ...
    @staticmethod
    def translationMatrix(tx: float | java.jfloat | java.lang.Float, ty: float | java.jfloat | java.lang.Float, /) -> android.graphics.Matrix: ...
    @staticmethod
    def values(this_values: android.graphics.Matrix, /) -> java.chaquopy.JavaArrayJFloat: ...

class PaintKt(java.lang.Object):
    @staticmethod
    def setBlendMode(this_setBlendMode: android.graphics.Paint, blendModeCompat: BlendModeCompat, /) -> bool: ...

class PathKt(java.lang.Object):
    @staticmethod
    def and_(this_and: android.graphics.Path, p: android.graphics.Path, /) -> android.graphics.Path: ...
    @staticmethod
    def flatten(this_flatten: android.graphics.Path, error: float | java.jfloat | java.lang.Float, /) -> java.lang.Iterable[PathSegment]: ...
    @staticmethod
    def minus(this_minus: android.graphics.Path, p: android.graphics.Path, /) -> android.graphics.Path: ...
    @staticmethod
    def or_(this_or: android.graphics.Path, p: android.graphics.Path, /) -> android.graphics.Path: ...
    @staticmethod
    def plus(this_plus: android.graphics.Path, p: android.graphics.Path, /) -> android.graphics.Path: ...
    @staticmethod
    def xor(this_xor: android.graphics.Path, p: android.graphics.Path, /) -> android.graphics.Path: ...

class PictureKt(java.lang.Object):
    @staticmethod
    def record(this_record: android.graphics.Picture, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, block: kotlin.jvm.functions.Function1[android.graphics.Canvas, kotlin.Unit], /) -> android.graphics.Picture: ...

class PointKt(java.lang.Object):
    @typing.overload
    @staticmethod
    def component1(this_component1: android.graphics.Point, /) -> int: ...
    @typing.overload
    @staticmethod
    def component1(this_component1: android.graphics.PointF, /) -> float: ...
    @typing.overload
    @staticmethod
    def component2(this_component2: android.graphics.Point, /) -> int: ...
    @typing.overload
    @staticmethod
    def component2(this_component2: android.graphics.PointF, /) -> float: ...
    @typing.overload
    @staticmethod
    def minus(this_minus: android.graphics.Point, xy: int | java.jint | java.lang.Integer, /) -> android.graphics.Point: ...
    @typing.overload
    @staticmethod
    def minus(this_minus: android.graphics.Point, p: android.graphics.Point, /) -> android.graphics.Point: ...
    @typing.overload
    @staticmethod
    def minus(this_minus: android.graphics.PointF, xy: float | java.jfloat | java.lang.Float, /) -> android.graphics.PointF: ...
    @typing.overload
    @staticmethod
    def minus(this_minus: android.graphics.PointF, p: android.graphics.PointF, /) -> android.graphics.PointF: ...
    @typing.overload
    @staticmethod
    def plus(this_plus: android.graphics.Point, xy: int | java.jint | java.lang.Integer, /) -> android.graphics.Point: ...
    @typing.overload
    @staticmethod
    def plus(this_plus: android.graphics.Point, p: android.graphics.Point, /) -> android.graphics.Point: ...
    @typing.overload
    @staticmethod
    def plus(this_plus: android.graphics.PointF, xy: float | java.jfloat | java.lang.Float, /) -> android.graphics.PointF: ...
    @typing.overload
    @staticmethod
    def plus(this_plus: android.graphics.PointF, p: android.graphics.PointF, /) -> android.graphics.PointF: ...
    @staticmethod
    def toPoint(this_toPoint: android.graphics.PointF, /) -> android.graphics.Point: ...
    @staticmethod
    def toPointF(this_toPointF: android.graphics.Point, /) -> android.graphics.PointF: ...
    @typing.overload
    @staticmethod
    def unaryMinus(this_unaryMinus: android.graphics.Point, /) -> android.graphics.Point: ...
    @typing.overload
    @staticmethod
    def unaryMinus(this_unaryMinus: android.graphics.PointF, /) -> android.graphics.PointF: ...

class PorterDuffKt(java.lang.Object):
    @staticmethod
    def toColorFilter(this_toColorFilter: android.graphics.PorterDuff.Mode, color: int | java.jint | java.lang.Integer, /) -> android.graphics.PorterDuffColorFilter: ...
    @staticmethod
    def toXfermode(this_toXfermode: android.graphics.PorterDuff.Mode, /) -> android.graphics.PorterDuffXfermode: ...

class RectKt(java.lang.Object):
    @typing.overload
    @staticmethod
    def and_(this_and: android.graphics.Rect, r: android.graphics.Rect, /) -> android.graphics.Rect: ...
    @typing.overload
    @staticmethod
    def and_(this_and: android.graphics.RectF, r: android.graphics.RectF, /) -> android.graphics.RectF: ...
    @typing.overload
    @staticmethod
    def component1(this_component1: android.graphics.Rect, /) -> int: ...
    @typing.overload
    @staticmethod
    def component1(this_component1: android.graphics.RectF, /) -> float: ...
    @typing.overload
    @staticmethod
    def component2(this_component2: android.graphics.Rect, /) -> int: ...
    @typing.overload
    @staticmethod
    def component2(this_component2: android.graphics.RectF, /) -> float: ...
    @typing.overload
    @staticmethod
    def component3(this_component3: android.graphics.Rect, /) -> int: ...
    @typing.overload
    @staticmethod
    def component3(this_component3: android.graphics.RectF, /) -> float: ...
    @typing.overload
    @staticmethod
    def component4(this_component4: android.graphics.Rect, /) -> int: ...
    @typing.overload
    @staticmethod
    def component4(this_component4: android.graphics.RectF, /) -> float: ...
    @typing.overload
    @staticmethod
    def contains(this_contains: android.graphics.Rect, p: android.graphics.Point, /) -> bool: ...
    @typing.overload
    @staticmethod
    def contains(this_contains: android.graphics.RectF, p: android.graphics.PointF, /) -> bool: ...
    @typing.overload
    @staticmethod
    def minus(this_minus: android.graphics.Rect, xy: int | java.jint | java.lang.Integer, /) -> android.graphics.Rect: ...
    @typing.overload
    @staticmethod
    def minus(this_minus: android.graphics.Rect, xy: android.graphics.Point, /) -> android.graphics.Rect: ...
    @typing.overload
    @staticmethod
    def minus(this_minus: android.graphics.Rect, r: android.graphics.Rect, /) -> android.graphics.Region: ...
    @typing.overload
    @staticmethod
    def minus(this_minus: android.graphics.RectF, xy: float | java.jfloat | java.lang.Float, /) -> android.graphics.RectF: ...
    @typing.overload
    @staticmethod
    def minus(this_minus: android.graphics.RectF, xy: android.graphics.PointF, /) -> android.graphics.RectF: ...
    @typing.overload
    @staticmethod
    def minus(this_minus: android.graphics.RectF, r: android.graphics.RectF, /) -> android.graphics.Region: ...
    @typing.overload
    @staticmethod
    def or_(this_or: android.graphics.Rect, r: android.graphics.Rect, /) -> android.graphics.Rect: ...
    @typing.overload
    @staticmethod
    def or_(this_or: android.graphics.RectF, r: android.graphics.RectF, /) -> android.graphics.RectF: ...
    @typing.overload
    @staticmethod
    def plus(this_plus: android.graphics.Rect, xy: int | java.jint | java.lang.Integer, /) -> android.graphics.Rect: ...
    @typing.overload
    @staticmethod
    def plus(this_plus: android.graphics.Rect, xy: android.graphics.Point, /) -> android.graphics.Rect: ...
    @typing.overload
    @staticmethod
    def plus(this_plus: android.graphics.Rect, r: android.graphics.Rect, /) -> android.graphics.Rect: ...
    @typing.overload
    @staticmethod
    def plus(this_plus: android.graphics.RectF, xy: float | java.jfloat | java.lang.Float, /) -> android.graphics.RectF: ...
    @typing.overload
    @staticmethod
    def plus(this_plus: android.graphics.RectF, xy: android.graphics.PointF, /) -> android.graphics.RectF: ...
    @typing.overload
    @staticmethod
    def plus(this_plus: android.graphics.RectF, r: android.graphics.RectF, /) -> android.graphics.RectF: ...
    @typing.overload
    @staticmethod
    def times(this_times: android.graphics.Rect, factor: int | java.jint | java.lang.Integer, /) -> android.graphics.Rect: ...
    @typing.overload
    @staticmethod
    def times(this_times: android.graphics.RectF, factor: float | java.jfloat | java.lang.Float, /) -> android.graphics.RectF: ...
    @typing.overload
    @staticmethod
    def times(this_times: android.graphics.RectF, factor: int | java.jint | java.lang.Integer, /) -> android.graphics.RectF: ...
    @staticmethod
    def toRect(this_toRect: android.graphics.RectF, /) -> android.graphics.Rect: ...
    @staticmethod
    def toRectF(this_toRectF: android.graphics.Rect, /) -> android.graphics.RectF: ...
    @typing.overload
    @staticmethod
    def toRegion(this_toRegion: android.graphics.Rect, /) -> android.graphics.Region: ...
    @typing.overload
    @staticmethod
    def toRegion(this_toRegion: android.graphics.RectF, /) -> android.graphics.Region: ...
    @staticmethod
    def transform(this_transform: android.graphics.RectF, m: android.graphics.Matrix, /) -> android.graphics.RectF: ...
    @typing.overload
    @staticmethod
    def xor(this_xor: android.graphics.Rect, r: android.graphics.Rect, /) -> android.graphics.Region: ...
    @typing.overload
    @staticmethod
    def xor(this_xor: android.graphics.RectF, r: android.graphics.RectF, /) -> android.graphics.Region: ...

class RegionKt(java.lang.Object):
    @typing.overload
    @staticmethod
    def and_(this_and: android.graphics.Region, r: android.graphics.Rect, /) -> android.graphics.Region: ...
    @typing.overload
    @staticmethod
    def and_(this_and: android.graphics.Region, r: android.graphics.Region, /) -> android.graphics.Region: ...
    @staticmethod
    def contains(this_contains: android.graphics.Region, p: android.graphics.Point, /) -> bool: ...
    @staticmethod
    def forEach(this_forEach: android.graphics.Region, action: kotlin.jvm.functions.Function1[android.graphics.Rect, kotlin.Unit], /) -> None: ...
    @staticmethod
    def iterator(this_iterator: android.graphics.Region, /) -> java.util.Iterator[android.graphics.Rect]: ...
    @typing.overload
    @staticmethod
    def minus(this_minus: android.graphics.Region, r: android.graphics.Rect, /) -> android.graphics.Region: ...
    @typing.overload
    @staticmethod
    def minus(this_minus: android.graphics.Region, r: android.graphics.Region, /) -> android.graphics.Region: ...
    @staticmethod
    def not_(this_not: android.graphics.Region, /) -> android.graphics.Region: ...
    @typing.overload
    @staticmethod
    def or_(this_or: android.graphics.Region, r: android.graphics.Rect, /) -> android.graphics.Region: ...
    @typing.overload
    @staticmethod
    def or_(this_or: android.graphics.Region, r: android.graphics.Region, /) -> android.graphics.Region: ...
    @typing.overload
    @staticmethod
    def plus(this_plus: android.graphics.Region, r: android.graphics.Rect, /) -> android.graphics.Region: ...
    @typing.overload
    @staticmethod
    def plus(this_plus: android.graphics.Region, r: android.graphics.Region, /) -> android.graphics.Region: ...
    @staticmethod
    def unaryMinus(this_unaryMinus: android.graphics.Region, /) -> android.graphics.Region: ...
    @typing.overload
    @staticmethod
    def xor(this_xor: android.graphics.Region, r: android.graphics.Rect, /) -> android.graphics.Region: ...
    @typing.overload
    @staticmethod
    def xor(this_xor: android.graphics.Region, r: android.graphics.Region, /) -> android.graphics.Region: ...

class ShaderKt(java.lang.Object):
    @staticmethod
    def transform(this_transform: android.graphics.Shader, block: kotlin.jvm.functions.Function1[android.graphics.Matrix, kotlin.Unit], /) -> None: ...
