import android.content
import android.graphics
import android.util
import android.view
import androidx.recyclerview.widget
import java
import java.lang
import typing



class MaterialDivider(android.view.View):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def getDividerColor(self) -> int: ...
    def getDividerInsetEnd(self) -> int: ...
    def getDividerInsetStart(self) -> int: ...
    def getDividerThickness(self) -> int: ...
    def onDraw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDividerColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDividerColorResource(self, colorId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDividerInsetEnd(self, insetEnd: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDividerInsetEndResource(self, insetEndId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDividerInsetStart(self, insetStart: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDividerInsetStartResource(self, insetStartId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDividerThickness(self, thickness: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDividerThicknessResource(self, thicknessId: int | java.jint | java.lang.Integer, /) -> None: ...

class MaterialDividerItemDecoration(androidx.recyclerview.widget.RecyclerView.ItemDecoration):
    HORIZONTAL: typing.ClassVar[int] = ...
    VERTICAL: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, context: android.content.Context, orientation: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, orientation: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, orientation: int | java.jint | java.lang.Integer, /) -> None: ...
    def getDividerColor(self) -> int: ...
    def getDividerInsetEnd(self) -> int: ...
    def getDividerInsetStart(self) -> int: ...
    def getDividerThickness(self) -> int: ...
    def getItemOffsets(self, outRect: android.graphics.Rect, view: android.view.View, parent: androidx.recyclerview.widget.RecyclerView, state: androidx.recyclerview.widget.RecyclerView.State, /) -> None: ...
    def getOrientation(self) -> int: ...
    def isLastItemDecorated(self) -> bool: ...
    def onDraw(self, canvas: android.graphics.Canvas, parent: androidx.recyclerview.widget.RecyclerView, state: androidx.recyclerview.widget.RecyclerView.State, /) -> None: ...
    def setDividerColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDividerColorResource(self, context: android.content.Context, colorId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDividerInsetEnd(self, insetEnd: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDividerInsetEndResource(self, context: android.content.Context, insetEndId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDividerInsetStart(self, insetStart: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDividerInsetStartResource(self, context: android.content.Context, insetStartId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDividerThickness(self, thickness: int | java.jint | java.lang.Integer, /) -> None: ...
    def setDividerThicknessResource(self, context: android.content.Context, thicknessId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setLastItemDecorated(self, lastItemDecorated: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setOrientation(self, orientation: int | java.jint | java.lang.Integer, /) -> None: ...
    def shouldDrawDivider(self, position: int | java.jint | java.lang.Integer, adapter: androidx.recyclerview.widget.RecyclerView.Adapter[java.lang.Object], /) -> bool: ...
