import typing

import java
import java.chaquopy
import java.io
import java.lang
import java.lang.ref
import java.util
import kotlin.collections
import kotlin.coroutines
import kotlin.coroutines.jvm.internal
import kotlinx.coroutines

class AgentInstallationType(java.lang.Object):
    INSTANCE: typing.ClassVar[AgentInstallationType] = ...

_ConcurrentWeakMap__K = typing.TypeVar('_ConcurrentWeakMap__K')  # <K>
_ConcurrentWeakMap__V = typing.TypeVar('_ConcurrentWeakMap__V')  # <V>
class ConcurrentWeakMap(kotlin.collections.AbstractMutableMap[_ConcurrentWeakMap__K, _ConcurrentWeakMap__V], typing.Generic[_ConcurrentWeakMap__K, _ConcurrentWeakMap__V]):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, weakRefQueue: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def clear(self) -> None: ...
    def get(self, key: java.lang.Object | int | bool | float | str, /) -> _ConcurrentWeakMap__V: ...
    def getEntries(self) -> java.util.Set[java.util.Map.Entry[_ConcurrentWeakMap__K, _ConcurrentWeakMap__V]]: ...
    def getKeys(self) -> java.util.Set[_ConcurrentWeakMap__K]: ...
    def getSize(self) -> int: ...
    def put(self, key: _ConcurrentWeakMap__K, value: _ConcurrentWeakMap__V, /) -> _ConcurrentWeakMap__V: ...
    def remove(self, key: java.lang.Object | int | bool | float | str, /) -> _ConcurrentWeakMap__V: ...
    def runWeakRefQueueCleaningLoopUntilInterrupted(self) -> None: ...

class ConcurrentWeakMapKt(java.lang.Object): ...

class DebugCoroutineInfo(java.lang.Object):
    def __init__(self, source: DebugCoroutineInfoImpl, context: kotlin.coroutines.CoroutineContext, /) -> None: ...
    def getContext(self) -> kotlin.coroutines.CoroutineContext: ...
    def getCreationStackBottom(self) -> kotlin.coroutines.jvm.internal.CoroutineStackFrame: ...
    def getCreationStackTrace(self) -> java.util.List[java.lang.StackTraceElement]: ...
    def getLastObservedFrame(self) -> kotlin.coroutines.jvm.internal.CoroutineStackFrame: ...
    def getLastObservedThread(self) -> java.lang.Thread: ...
    def getSequenceNumber(self) -> int: ...
    def getState(self) -> str: ...
    def lastObservedStackTrace(self) -> java.util.List[java.lang.StackTraceElement]: ...

class DebugCoroutineInfoImpl(java.lang.Object):
    sequenceNumber: int = ...
    lastObservedThread: java.lang.Thread = ...
    def __init__(self, context: kotlin.coroutines.CoroutineContext, creationStackBottom: StackTraceFrame, sequenceNumber: int | java.jlong | java.lang.Long, /) -> None: ...
    def getContext(self) -> kotlin.coroutines.CoroutineContext: ...
    def getCreationStackBottom(self) -> StackTraceFrame: ...
    def getCreationStackTrace(self) -> java.util.List[java.lang.StackTraceElement]: ...
    def getState(self) -> str: ...
    def lastObservedStackTrace(self) -> java.util.List[java.lang.StackTraceElement]: ...
    def toString(self) -> str: ...

class DebugCoroutineInfoImplKt(java.lang.Object):
    CREATED: typing.ClassVar[str] = ...
    RUNNING: typing.ClassVar[str] = ...
    SUSPENDED: typing.ClassVar[str] = ...

class DebugProbesImpl(java.lang.Object):
    INSTANCE: typing.ClassVar[DebugProbesImpl] = ...
    def dumpCoroutines(self, out: java.io.PrintStream, /) -> None: ...
    def dumpCoroutinesInfo(self) -> java.util.List[DebugCoroutineInfo]: ...
    def dumpCoroutinesInfoAsJsonAndReferences(self) -> java.chaquopy.JavaArray[java.lang.Object]: ...
    def dumpDebuggerInfo(self) -> java.util.List[DebuggerInfo]: ...
    def enhanceStackTraceWithThreadDump(self, info: DebugCoroutineInfo, coroutineTrace: java.util.List[java.lang.StackTraceElement], /) -> java.util.List[java.lang.StackTraceElement]: ...
    def enhanceStackTraceWithThreadDumpAsJson(self, info: DebugCoroutineInfo, /) -> str: ...
    def getEnableCreationStackTraces(self) -> bool: ...
    def getSanitizeStackTraces(self) -> bool: ...
    def hierarchyToString(self, job: kotlinx.coroutines.Job, /) -> str: ...
    def install(self) -> None: ...
    def setEnableCreationStackTraces(self, set___: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setSanitizeStackTraces(self, set___: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def uninstall(self) -> None: ...

class DebugProbesKt(java.lang.Object):
    _probeCoroutineCreated__T = typing.TypeVar('_probeCoroutineCreated__T')  # <T>
    @staticmethod
    def probeCoroutineCreated(completion: kotlin.coroutines.Continuation[_probeCoroutineCreated__T], /) -> kotlin.coroutines.Continuation[_probeCoroutineCreated__T]: ...
    @staticmethod
    def probeCoroutineResumed(frame: kotlin.coroutines.Continuation[java.lang.Object], /) -> None: ...
    @staticmethod
    def probeCoroutineSuspended(frame: kotlin.coroutines.Continuation[java.lang.Object], /) -> None: ...

class DebuggerInfo(java.io.Serializable):
    def __init__(self, source: DebugCoroutineInfoImpl, context: kotlin.coroutines.CoroutineContext, /) -> None: ...
    def getCoroutineId(self) -> int: ...
    def getDispatcher(self) -> str: ...
    def getLastObservedStackTrace(self) -> java.util.List[java.lang.StackTraceElement]: ...
    def getLastObservedThreadName(self) -> str: ...
    def getLastObservedThreadState(self) -> str: ...
    def getName(self) -> str: ...
    def getSequenceNumber(self) -> int: ...
    def getState(self) -> str: ...

_HashedWeakRef__T = typing.TypeVar('_HashedWeakRef__T')  # <T>
class HashedWeakRef(java.lang.ref.WeakReference[_HashedWeakRef__T], typing.Generic[_HashedWeakRef__T]):
    hash: int = ...
    def __init__(self, ref: _HashedWeakRef__T, queue: java.lang.ref.ReferenceQueue[_HashedWeakRef__T], /) -> None: ...

class Marked(java.lang.Object):
    ref: java.lang.Object = ...
    def __init__(self, ref: java.lang.Object | int | bool | float | str, /) -> None: ...

class StackTraceFrame(kotlin.coroutines.jvm.internal.CoroutineStackFrame):
    def __init__(self, callerFrame: kotlin.coroutines.jvm.internal.CoroutineStackFrame, stackTraceElement: java.lang.StackTraceElement, /) -> None: ...
    def getCallerFrame(self) -> kotlin.coroutines.jvm.internal.CoroutineStackFrame: ...
    def getStackTraceElement(self) -> java.lang.StackTraceElement: ...
