import typing

import android.content
import android.content.res
import android.graphics
import android.graphics.drawable
import android.util
import android.view
import android.widget
import java
import java.chaquopy
import java.lang

class CardView(android.widget.FrameLayout):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyleAttr: int | java.jint | java.lang.Integer, /) -> None: ...
    def getCardBackgroundColor(self) -> android.content.res.ColorStateList: ...
    def getCardElevation(self) -> float: ...
    def getContentPaddingBottom(self) -> int: ...
    def getContentPaddingLeft(self) -> int: ...
    def getContentPaddingRight(self) -> int: ...
    def getContentPaddingTop(self) -> int: ...
    def getMaxCardElevation(self) -> float: ...
    def getPreventCornerOverlap(self) -> bool: ...
    def getRadius(self) -> float: ...
    def getUseCompatPadding(self) -> bool: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCardBackgroundColor(self, color: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setCardBackgroundColor(self, color: android.content.res.ColorStateList, /) -> None: ...
    def setCardElevation(self, elevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setContentPadding(self, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMaxCardElevation(self, maxElevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setMinimumHeight(self, minHeight: int | java.jint | java.lang.Integer, /) -> None: ...
    def setMinimumWidth(self, minWidth: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPadding(self, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPaddingRelative(self, start: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, end: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPreventCornerOverlap(self, preventCornerOverlap: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setRadius(self, radius: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setUseCompatPadding(self, useCompatPadding: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class CardViewApi17Impl(CardViewBaseImpl):
    def initStatic(self) -> None: ...

class CardViewApi21Impl(CardViewImpl):
    def getBackgroundColor(self, cardView: CardViewDelegate, /) -> android.content.res.ColorStateList: ...
    def getElevation(self, cardView: CardViewDelegate, /) -> float: ...
    def getMaxElevation(self, cardView: CardViewDelegate, /) -> float: ...
    def getMinHeight(self, cardView: CardViewDelegate, /) -> float: ...
    def getMinWidth(self, cardView: CardViewDelegate, /) -> float: ...
    def getRadius(self, cardView: CardViewDelegate, /) -> float: ...
    def initStatic(self) -> None: ...
    def initialize(self, cardView: CardViewDelegate, context: android.content.Context, backgroundColor: android.content.res.ColorStateList, radius: float | java.jfloat | java.lang.Float, elevation: float | java.jfloat | java.lang.Float, maxElevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def onCompatPaddingChanged(self, cardView: CardViewDelegate, /) -> None: ...
    def onPreventCornerOverlapChanged(self, cardView: CardViewDelegate, /) -> None: ...
    def setBackgroundColor(self, cardView: CardViewDelegate, color: android.content.res.ColorStateList, /) -> None: ...
    def setElevation(self, cardView: CardViewDelegate, elevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setMaxElevation(self, cardView: CardViewDelegate, maxElevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setRadius(self, cardView: CardViewDelegate, radius: float | java.jfloat | java.lang.Float, /) -> None: ...
    def updatePadding(self, cardView: CardViewDelegate, /) -> None: ...

class CardViewBaseImpl(CardViewImpl):
    def getBackgroundColor(self, cardView: CardViewDelegate, /) -> android.content.res.ColorStateList: ...
    def getElevation(self, cardView: CardViewDelegate, /) -> float: ...
    def getMaxElevation(self, cardView: CardViewDelegate, /) -> float: ...
    def getMinHeight(self, cardView: CardViewDelegate, /) -> float: ...
    def getMinWidth(self, cardView: CardViewDelegate, /) -> float: ...
    def getRadius(self, cardView: CardViewDelegate, /) -> float: ...
    def initStatic(self) -> None: ...
    def initialize(self, cardView: CardViewDelegate, context: android.content.Context, backgroundColor: android.content.res.ColorStateList, radius: float | java.jfloat | java.lang.Float, elevation: float | java.jfloat | java.lang.Float, maxElevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def onCompatPaddingChanged(self, cardView: CardViewDelegate, /) -> None: ...
    def onPreventCornerOverlapChanged(self, cardView: CardViewDelegate, /) -> None: ...
    def setBackgroundColor(self, cardView: CardViewDelegate, color: android.content.res.ColorStateList, /) -> None: ...
    def setElevation(self, cardView: CardViewDelegate, elevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setMaxElevation(self, cardView: CardViewDelegate, maxElevation: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setRadius(self, cardView: CardViewDelegate, radius: float | java.jfloat | java.lang.Float, /) -> None: ...
    def updatePadding(self, cardView: CardViewDelegate, /) -> None: ...

class CardViewDelegate(java.lang.Object):
    def getCardBackground(self) -> android.graphics.drawable.Drawable: ...
    def getCardView(self) -> android.view.View: ...
    def getPreventCornerOverlap(self) -> bool: ...
    def getUseCompatPadding(self) -> bool: ...
    def setCardBackground(self, arg1: android.graphics.drawable.Drawable, /) -> None: ...
    def setMinWidthHeightInternal(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, /) -> None: ...
    def setShadowPadding(self, arg1: int | java.jint | java.lang.Integer, arg2: int | java.jint | java.lang.Integer, arg3: int | java.jint | java.lang.Integer, arg4: int | java.jint | java.lang.Integer, /) -> None: ...

class CardViewImpl(java.lang.Object):
    def getBackgroundColor(self, arg1: CardViewDelegate, /) -> android.content.res.ColorStateList: ...
    def getElevation(self, arg1: CardViewDelegate, /) -> float: ...
    def getMaxElevation(self, arg1: CardViewDelegate, /) -> float: ...
    def getMinHeight(self, arg1: CardViewDelegate, /) -> float: ...
    def getMinWidth(self, arg1: CardViewDelegate, /) -> float: ...
    def getRadius(self, arg1: CardViewDelegate, /) -> float: ...
    def initStatic(self) -> None: ...
    def initialize(self, arg1: CardViewDelegate, arg2: android.content.Context, arg3: android.content.res.ColorStateList, arg4: float | java.jfloat | java.lang.Float, arg5: float | java.jfloat | java.lang.Float, arg6: float | java.jfloat | java.lang.Float, /) -> None: ...
    def onCompatPaddingChanged(self, arg1: CardViewDelegate, /) -> None: ...
    def onPreventCornerOverlapChanged(self, arg1: CardViewDelegate, /) -> None: ...
    def setBackgroundColor(self, arg1: CardViewDelegate, arg2: android.content.res.ColorStateList, /) -> None: ...
    def setElevation(self, arg1: CardViewDelegate, arg2: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setMaxElevation(self, arg1: CardViewDelegate, arg2: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setRadius(self, arg1: CardViewDelegate, arg2: float | java.jfloat | java.lang.Float, /) -> None: ...
    def updatePadding(self, arg1: CardViewDelegate, /) -> None: ...

class RoundRectDrawable(android.graphics.drawable.Drawable):
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getColor(self) -> android.content.res.ColorStateList: ...
    def getOpacity(self) -> int: ...
    def getOutline(self, outline: android.graphics.Outline, /) -> None: ...
    def getRadius(self) -> float: ...
    def isStateful(self) -> bool: ...
    def onBoundsChange(self, bounds: android.graphics.Rect, /) -> None: ...
    def onStateChange(self, stateSet: java.chaquopy.JavaArrayJInt, /) -> bool: ...
    def setAlpha(self, alpha: int | java.jint | java.lang.Integer, /) -> None: ...
    def setColor(self, color: android.content.res.ColorStateList, /) -> None: ...
    def setColorFilter(self, cf: android.graphics.ColorFilter, /) -> None: ...
    def setTintList(self, tint: android.content.res.ColorStateList, /) -> None: ...
    def setTintMode(self, tintMode: android.graphics.PorterDuff.Mode, /) -> None: ...

class RoundRectDrawableWithShadow(android.graphics.drawable.Drawable):
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getOpacity(self) -> int: ...
    def getPadding(self, padding: android.graphics.Rect, /) -> bool: ...
    def isStateful(self) -> bool: ...
    def onBoundsChange(self, bounds: android.graphics.Rect, /) -> None: ...
    def onStateChange(self, stateSet: java.chaquopy.JavaArrayJInt, /) -> bool: ...
    def setAlpha(self, alpha: int | java.jint | java.lang.Integer, /) -> None: ...
    def setColorFilter(self, cf: android.graphics.ColorFilter, /) -> None: ...
