import typing

import android.app
import android.content
import android.content.res
import android.graphics
import android.os
import android.view
import android.view.inputmethod
import android.window
import androidx.activity.contextaware
import androidx.activity.result
import androidx.activity.result.contract
import androidx.core.app
import androidx.core.content
import androidx.core.util
import androidx.core.view
import androidx.lifecycle
import androidx.lifecycle.viewmodel
import androidx.savedstate
import java
import java.chaquopy
import java.lang
import java.lang.annotation
import java.lang.reflect
import java.util.concurrent
import kotlin
import kotlin.coroutines
import kotlin.jvm.functions

class ActivityViewModelLazyKt(java.lang.Object): ...

class Api26Impl(java.lang.Object):
    INSTANCE: typing.ClassVar[Api26Impl] = ...
    def setPipParamsSourceRectHint(self, activity: android.app.Activity, hint: android.graphics.Rect, /) -> None: ...

class Api34Impl(java.lang.Object):
    INSTANCE: typing.ClassVar[Api34Impl] = ...
    def createOnBackEvent(self, touchX: float | java.jfloat | java.lang.Float, touchY: float | java.jfloat | java.lang.Float, progress: float | java.jfloat | java.lang.Float, swipeEdge: int | java.jint | java.lang.Integer, /) -> android.window.BackEvent: ...
    def progress(self, backEvent: android.window.BackEvent, /) -> float: ...
    def swipeEdge(self, backEvent: android.window.BackEvent, /) -> int: ...
    def touchX(self, backEvent: android.window.BackEvent, /) -> float: ...
    def touchY(self, backEvent: android.window.BackEvent, /) -> float: ...

class BackEventCompat(java.lang.Object):
    Companion: typing.ClassVar[BackEventCompat.Companion] = ...
    EDGE_LEFT: typing.ClassVar[int] = ...
    EDGE_RIGHT: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, backEvent: android.window.BackEvent, /) -> None: ...
    @typing.overload
    def __init__(self, touchX: float | java.jfloat | java.lang.Float, touchY: float | java.jfloat | java.lang.Float, progress: float | java.jfloat | java.lang.Float, swipeEdge: int | java.jint | java.lang.Integer, /) -> None: ...
    def getProgress(self) -> float: ...
    def getSwipeEdge(self) -> int: ...
    def getTouchX(self) -> float: ...
    def getTouchY(self) -> float: ...
    def toBackEvent(self) -> android.window.BackEvent: ...
    def toString(self) -> str: ...

    class Companion(java.lang.Object): ...

    class SwipeEdge(java.lang.annotation.Annotation): ...

class Cancellable(java.lang.Object):
    def cancel(self) -> None: ...

class ComponentActivity(androidx.core.app.ComponentActivity, androidx.activity.contextaware.ContextAware, androidx.lifecycle.LifecycleOwner, androidx.lifecycle.ViewModelStoreOwner, androidx.lifecycle.HasDefaultViewModelProviderFactory, androidx.savedstate.SavedStateRegistryOwner, OnBackPressedDispatcherOwner, androidx.activity.result.ActivityResultRegistryOwner, androidx.activity.result.ActivityResultCaller, androidx.core.content.OnConfigurationChangedProvider, androidx.core.content.OnTrimMemoryProvider, androidx.core.app.OnNewIntentProvider, androidx.core.app.OnMultiWindowModeChangedProvider, androidx.core.app.OnPictureInPictureModeChangedProvider, androidx.core.app.OnUserLeaveHintProvider, androidx.core.view.MenuHost, FullyDrawnReporterOwner):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, contentLayoutId: int | java.jint | java.lang.Integer, /) -> None: ...
    def addContentView(self, view: android.view.View, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    @typing.overload
    def addMenuProvider(self, provider: androidx.core.view.MenuProvider, /) -> None: ...
    @typing.overload
    def addMenuProvider(self, provider: androidx.core.view.MenuProvider, owner: androidx.lifecycle.LifecycleOwner, /) -> None: ...
    @typing.overload
    def addMenuProvider(self, provider: androidx.core.view.MenuProvider, owner: androidx.lifecycle.LifecycleOwner, state: androidx.lifecycle.Lifecycle.State, /) -> None: ...
    def addOnConfigurationChangedListener(self, listener: androidx.core.util.Consumer[android.content.res.Configuration], /) -> None: ...
    def addOnContextAvailableListener(self, listener: androidx.activity.contextaware.OnContextAvailableListener, /) -> None: ...
    def addOnMultiWindowModeChangedListener(self, listener: androidx.core.util.Consumer[androidx.core.app.MultiWindowModeChangedInfo], /) -> None: ...
    def addOnNewIntentListener(self, listener: androidx.core.util.Consumer[android.content.Intent], /) -> None: ...
    def addOnPictureInPictureModeChangedListener(self, listener: androidx.core.util.Consumer[androidx.core.app.PictureInPictureModeChangedInfo], /) -> None: ...
    def addOnTrimMemoryListener(self, listener: androidx.core.util.Consumer[java.lang.Integer], /) -> None: ...
    def addOnUserLeaveHintListener(self, listener: java.lang.Runnable, /) -> None: ...
    def getActivityResultRegistry(self) -> androidx.activity.result.ActivityResultRegistry: ...
    def getDefaultViewModelCreationExtras(self) -> androidx.lifecycle.viewmodel.CreationExtras: ...
    def getDefaultViewModelProviderFactory(self) -> androidx.lifecycle.ViewModelProvider.Factory: ...
    def getFullyDrawnReporter(self) -> FullyDrawnReporter: ...
    def getLastCustomNonConfigurationInstance(self) -> java.lang.Object: ...
    def getLifecycle(self) -> androidx.lifecycle.Lifecycle: ...
    def getOnBackPressedDispatcher(self) -> OnBackPressedDispatcher: ...
    def getSavedStateRegistry(self) -> androidx.savedstate.SavedStateRegistry: ...
    def getViewModelStore(self) -> androidx.lifecycle.ViewModelStore: ...
    def initializeViewTreeOwners(self) -> None: ...
    def invalidateMenu(self) -> None: ...
    def onActivityResult(self, requestCode: int | java.jint | java.lang.Integer, resultCode: int | java.jint | java.lang.Integer, data: android.content.Intent, /) -> None: ...
    def onBackPressed(self) -> None: ...
    def onConfigurationChanged(self, newConfig: android.content.res.Configuration, /) -> None: ...
    def onCreate(self, savedInstanceState: android.os.Bundle, /) -> None: ...
    def onCreatePanelMenu(self, featureId: int | java.jint | java.lang.Integer, menu: android.view.Menu, /) -> bool: ...
    def onMenuItemSelected(self, featureId: int | java.jint | java.lang.Integer, item: android.view.MenuItem, /) -> bool: ...
    @typing.overload
    def onMultiWindowModeChanged(self, isInMultiWindowMode: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def onMultiWindowModeChanged(self, isInMultiWindowMode: bool | java.jboolean | java.lang.Boolean, newConfig: android.content.res.Configuration, /) -> None: ...
    def onNewIntent(self, intent: android.content.Intent, /) -> None: ...
    def onPanelClosed(self, featureId: int | java.jint | java.lang.Integer, menu: android.view.Menu, /) -> None: ...
    @typing.overload
    def onPictureInPictureModeChanged(self, isInPictureInPictureMode: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @typing.overload
    def onPictureInPictureModeChanged(self, isInPictureInPictureMode: bool | java.jboolean | java.lang.Boolean, newConfig: android.content.res.Configuration, /) -> None: ...
    def onPreparePanel(self, featureId: int | java.jint | java.lang.Integer, view: android.view.View, menu: android.view.Menu, /) -> bool: ...
    def onRequestPermissionsResult(self, requestCode: int | java.jint | java.lang.Integer, permissions: java.chaquopy.JavaArray[java.lang.String], grantResults: java.chaquopy.JavaArrayJInt, /) -> None: ...
    def onRetainCustomNonConfigurationInstance(self) -> java.lang.Object: ...
    def onRetainNonConfigurationInstance(self) -> java.lang.Object: ...
    def onSaveInstanceState(self, outState: android.os.Bundle, /) -> None: ...
    def onTrimMemory(self, level: int | java.jint | java.lang.Integer, /) -> None: ...
    def onUserLeaveHint(self) -> None: ...
    def peekAvailableContext(self) -> android.content.Context: ...
    _registerForActivityResult_0__I = typing.TypeVar('_registerForActivityResult_0__I')  # <I>
    _registerForActivityResult_0__O = typing.TypeVar('_registerForActivityResult_0__O')  # <O>
    _registerForActivityResult_1__I = typing.TypeVar('_registerForActivityResult_1__I')  # <I>
    _registerForActivityResult_1__O = typing.TypeVar('_registerForActivityResult_1__O')  # <O>
    @typing.overload
    def registerForActivityResult(self, contract: androidx.activity.result.contract.ActivityResultContract[_registerForActivityResult_0__I, _registerForActivityResult_0__O], callback: androidx.activity.result.ActivityResultCallback[_registerForActivityResult_0__O], /) -> androidx.activity.result.ActivityResultLauncher[_registerForActivityResult_0__I]: ...
    @typing.overload
    def registerForActivityResult(self, contract: androidx.activity.result.contract.ActivityResultContract[_registerForActivityResult_1__I, _registerForActivityResult_1__O], registry: androidx.activity.result.ActivityResultRegistry, callback: androidx.activity.result.ActivityResultCallback[_registerForActivityResult_1__O], /) -> androidx.activity.result.ActivityResultLauncher[_registerForActivityResult_1__I]: ...
    def removeMenuProvider(self, provider: androidx.core.view.MenuProvider, /) -> None: ...
    def removeOnConfigurationChangedListener(self, listener: androidx.core.util.Consumer[android.content.res.Configuration], /) -> None: ...
    def removeOnContextAvailableListener(self, listener: androidx.activity.contextaware.OnContextAvailableListener, /) -> None: ...
    def removeOnMultiWindowModeChangedListener(self, listener: androidx.core.util.Consumer[androidx.core.app.MultiWindowModeChangedInfo], /) -> None: ...
    def removeOnNewIntentListener(self, listener: androidx.core.util.Consumer[android.content.Intent], /) -> None: ...
    def removeOnPictureInPictureModeChangedListener(self, listener: androidx.core.util.Consumer[androidx.core.app.PictureInPictureModeChangedInfo], /) -> None: ...
    def removeOnTrimMemoryListener(self, listener: androidx.core.util.Consumer[java.lang.Integer], /) -> None: ...
    def removeOnUserLeaveHintListener(self, listener: java.lang.Runnable, /) -> None: ...
    def reportFullyDrawn(self) -> None: ...
    @typing.overload
    def setContentView(self, layoutResID: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setContentView(self, view: android.view.View, /) -> None: ...
    @typing.overload
    def setContentView(self, view: android.view.View, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    @typing.overload
    def startActivityForResult(self, intent: android.content.Intent, requestCode: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def startActivityForResult(self, intent: android.content.Intent, requestCode: int | java.jint | java.lang.Integer, options: android.os.Bundle, /) -> None: ...
    @typing.overload
    def startIntentSenderForResult(self, intent: android.content.IntentSender, requestCode: int | java.jint | java.lang.Integer, fillInIntent: android.content.Intent, flagsMask: int | java.jint | java.lang.Integer, flagsValues: int | java.jint | java.lang.Integer, extraFlags: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def startIntentSenderForResult(self, intent: android.content.IntentSender, requestCode: int | java.jint | java.lang.Integer, fillInIntent: android.content.Intent, flagsMask: int | java.jint | java.lang.Integer, flagsValues: int | java.jint | java.lang.Integer, extraFlags: int | java.jint | java.lang.Integer, options: android.os.Bundle, /) -> None: ...

    class NonConfigurationInstances(java.lang.Object):
        def __init__(self) -> None: ...
        def getCustom(self) -> java.lang.Object: ...
        def getViewModelStore(self) -> androidx.lifecycle.ViewModelStore: ...
        def setCustom(self, set___: java.lang.Object | int | bool | float | str, /) -> None: ...
        def setViewModelStore(self, set___: androidx.lifecycle.ViewModelStore, /) -> None: ...

class ComponentDialog(android.app.Dialog, androidx.lifecycle.LifecycleOwner, OnBackPressedDispatcherOwner, androidx.savedstate.SavedStateRegistryOwner):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, themeResId: int | java.jint | java.lang.Integer, /) -> None: ...
    def addContentView(self, view: android.view.View, params: android.view.ViewGroup.LayoutParams, /) -> None: ...
    def getLifecycle(self) -> androidx.lifecycle.Lifecycle: ...
    def getOnBackPressedDispatcher(self) -> OnBackPressedDispatcher: ...
    def getSavedStateRegistry(self) -> androidx.savedstate.SavedStateRegistry: ...
    def initializeViewTreeOwners(self) -> None: ...
    def onBackPressed(self) -> None: ...
    def onCreate(self, savedInstanceState: android.os.Bundle, /) -> None: ...
    def onSaveInstanceState(self) -> android.os.Bundle: ...
    def onStart(self) -> None: ...
    def onStop(self) -> None: ...
    @typing.overload
    def setContentView(self, layoutResID: int | java.jint | java.lang.Integer, /) -> None: ...
    @typing.overload
    def setContentView(self, view: android.view.View, /) -> None: ...
    @typing.overload
    def setContentView(self, view: android.view.View, params: android.view.ViewGroup.LayoutParams, /) -> None: ...

class EdgeToEdge(java.lang.Object):
    @typing.overload
    @staticmethod
    def enable(this_enableEdgeToEdge: ComponentActivity, /) -> None: ...
    @typing.overload
    @staticmethod
    def enable(this_enableEdgeToEdge: ComponentActivity, statusBarStyle: SystemBarStyle, /) -> None: ...
    @typing.overload
    @staticmethod
    def enable(this_enableEdgeToEdge: ComponentActivity, statusBarStyle: SystemBarStyle, navigationBarStyle: SystemBarStyle, /) -> None: ...
    @staticmethod
    def getDefaultDarkScrim() -> int: ...
    @staticmethod
    def getDefaultLightScrim() -> int: ...

class EdgeToEdgeApi21(EdgeToEdgeBase):
    def __init__(self) -> None: ...
    def setUp(self, statusBarStyle: SystemBarStyle, navigationBarStyle: SystemBarStyle, window: android.view.Window, view: android.view.View, statusBarIsDark: bool | java.jboolean | java.lang.Boolean, navigationBarIsDark: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class EdgeToEdgeApi23(EdgeToEdgeBase):
    def __init__(self) -> None: ...
    def setUp(self, statusBarStyle: SystemBarStyle, navigationBarStyle: SystemBarStyle, window: android.view.Window, view: android.view.View, statusBarIsDark: bool | java.jboolean | java.lang.Boolean, navigationBarIsDark: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class EdgeToEdgeApi26(EdgeToEdgeBase):
    def __init__(self) -> None: ...
    def setUp(self, statusBarStyle: SystemBarStyle, navigationBarStyle: SystemBarStyle, window: android.view.Window, view: android.view.View, statusBarIsDark: bool | java.jboolean | java.lang.Boolean, navigationBarIsDark: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class EdgeToEdgeApi28(EdgeToEdgeApi26):
    def __init__(self) -> None: ...
    def adjustLayoutInDisplayCutoutMode(self, window: android.view.Window, /) -> None: ...

class EdgeToEdgeApi29(EdgeToEdgeApi28):
    def __init__(self) -> None: ...
    def setUp(self, statusBarStyle: SystemBarStyle, navigationBarStyle: SystemBarStyle, window: android.view.Window, view: android.view.View, statusBarIsDark: bool | java.jboolean | java.lang.Boolean, navigationBarIsDark: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class EdgeToEdgeApi30(EdgeToEdgeApi29):
    def __init__(self) -> None: ...
    def adjustLayoutInDisplayCutoutMode(self, window: android.view.Window, /) -> None: ...

class EdgeToEdgeBase(EdgeToEdgeImpl):
    def __init__(self) -> None: ...
    def adjustLayoutInDisplayCutoutMode(self, window: android.view.Window, /) -> None: ...
    def setUp(self, statusBarStyle: SystemBarStyle, navigationBarStyle: SystemBarStyle, window: android.view.Window, view: android.view.View, statusBarIsDark: bool | java.jboolean | java.lang.Boolean, navigationBarIsDark: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class EdgeToEdgeImpl(java.lang.Object):
    def adjustLayoutInDisplayCutoutMode(self, arg1: android.view.Window, /) -> None: ...
    def setUp(self, arg1: SystemBarStyle, arg2: SystemBarStyle, arg3: android.view.Window, arg4: android.view.View, arg5: bool | java.jboolean | java.lang.Boolean, arg6: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class FullyDrawnReporter(java.lang.Object):
    def __init__(self, executor: java.util.concurrent.Executor, reportFullyDrawn: kotlin.jvm.functions.Function0[kotlin.Unit], /) -> None: ...
    def addOnReportDrawnListener(self, callback: kotlin.jvm.functions.Function0[kotlin.Unit], /) -> None: ...
    def addReporter(self) -> None: ...
    def fullyDrawnReported(self) -> None: ...
    def isFullyDrawnReported(self) -> bool: ...
    def removeOnReportDrawnListener(self, callback: kotlin.jvm.functions.Function0[kotlin.Unit], /) -> None: ...
    def removeReporter(self) -> None: ...

class FullyDrawnReporterKt(java.lang.Object):
    @staticmethod
    def reportWhenComplete(this_reportWhenComplete: FullyDrawnReporter, reporter: kotlin.jvm.functions.Function1[kotlin.coroutines.Continuation[kotlin.Unit], java.lang.Object], arg3: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...

class FullyDrawnReporterOwner(java.lang.Object):
    def getFullyDrawnReporter(self) -> FullyDrawnReporter: ...

class ImmLeaksCleaner(androidx.lifecycle.LifecycleEventObserver):
    Companion: typing.ClassVar[ImmLeaksCleaner.Companion] = ...
    def __init__(self, activity: android.app.Activity, /) -> None: ...
    def onStateChanged(self, source: androidx.lifecycle.LifecycleOwner, event: androidx.lifecycle.Lifecycle.Event, /) -> None: ...

    class Cleaner(java.lang.Object):
        def clearNextServedView(self, arg1: android.view.inputmethod.InputMethodManager, /) -> bool: ...
        def getLock(self, arg1: android.view.inputmethod.InputMethodManager, /) -> java.lang.Object: ...
        def getServedView(self, arg1: android.view.inputmethod.InputMethodManager, /) -> android.view.View: ...

    class Companion(java.lang.Object):
        def getCleaner(self) -> ImmLeaksCleaner.Cleaner: ...

    class FailedInitialization(ImmLeaksCleaner.Cleaner):
        INSTANCE: typing.ClassVar[ImmLeaksCleaner.FailedInitialization] = ...
        def clearNextServedView(self, this_clearNextServedView: android.view.inputmethod.InputMethodManager, /) -> bool: ...
        def getLock(self, this_lock: android.view.inputmethod.InputMethodManager, /) -> java.lang.Object: ...
        def getServedView(self, this_servedView: android.view.inputmethod.InputMethodManager, /) -> android.view.View: ...

    class ValidCleaner(ImmLeaksCleaner.Cleaner):
        def __init__(self, hField: java.lang.reflect.Field, servedViewField: java.lang.reflect.Field, nextServedViewField: java.lang.reflect.Field, /) -> None: ...
        def clearNextServedView(self, this_clearNextServedView: android.view.inputmethod.InputMethodManager, /) -> bool: ...
        def getLock(self, this_lock: android.view.inputmethod.InputMethodManager, /) -> java.lang.Object: ...
        def getServedView(self, this_servedView: android.view.inputmethod.InputMethodManager, /) -> android.view.View: ...

class OnBackPressedCallback(java.lang.Object):
    def __init__(self, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def addCancellable(self, cancellable: Cancellable, /) -> None: ...
    def handleOnBackCancelled(self) -> None: ...
    def handleOnBackPressed(self) -> None: ...
    def handleOnBackProgressed(self, backEvent: BackEventCompat, /) -> None: ...
    def handleOnBackStarted(self, backEvent: BackEventCompat, /) -> None: ...
    def isEnabled(self) -> bool: ...
    def remove(self) -> None: ...
    def removeCancellable(self, cancellable: Cancellable, /) -> None: ...
    def setEnabled(self, value: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class OnBackPressedDispatcher(java.lang.Object):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, fallbackOnBackPressed: java.lang.Runnable, /) -> None: ...
    @typing.overload
    def __init__(self, fallbackOnBackPressed: java.lang.Runnable, onHasEnabledCallbacksChanged: androidx.core.util.Consumer[java.lang.Boolean], /) -> None: ...
    @typing.overload
    def addCallback(self, onBackPressedCallback: OnBackPressedCallback, /) -> None: ...
    @typing.overload
    def addCallback(self, owner: androidx.lifecycle.LifecycleOwner, onBackPressedCallback: OnBackPressedCallback, /) -> None: ...
    def dispatchOnBackCancelled(self) -> None: ...
    def dispatchOnBackProgressed(self, backEvent: BackEventCompat, /) -> None: ...
    def dispatchOnBackStarted(self, backEvent: BackEventCompat, /) -> None: ...
    def hasEnabledCallbacks(self) -> bool: ...
    def onBackPressed(self) -> None: ...
    def setOnBackInvokedDispatcher(self, invoker: android.window.OnBackInvokedDispatcher, /) -> None: ...

    class Api33Impl(java.lang.Object):
        INSTANCE: typing.ClassVar[OnBackPressedDispatcher.Api33Impl] = ...
        def createOnBackInvokedCallback(self, onBackInvoked: kotlin.jvm.functions.Function0[kotlin.Unit], /) -> android.window.OnBackInvokedCallback: ...
        def registerOnBackInvokedCallback(self, dispatcher: java.lang.Object | int | bool | float | str, priority: int | java.jint | java.lang.Integer, callback: java.lang.Object | int | bool | float | str, /) -> None: ...
        def unregisterOnBackInvokedCallback(self, dispatcher: java.lang.Object | int | bool | float | str, callback: java.lang.Object | int | bool | float | str, /) -> None: ...

    class Api34Impl(java.lang.Object):
        INSTANCE: typing.ClassVar[OnBackPressedDispatcher.Api34Impl] = ...
        def createOnBackAnimationCallback(self, onBackStarted: kotlin.jvm.functions.Function1[BackEventCompat, kotlin.Unit], onBackProgressed: kotlin.jvm.functions.Function1[BackEventCompat, kotlin.Unit], onBackInvoked: kotlin.jvm.functions.Function0[kotlin.Unit], onBackCancelled: kotlin.jvm.functions.Function0[kotlin.Unit], /) -> android.window.OnBackInvokedCallback: ...

class OnBackPressedDispatcherKt(java.lang.Object):
    @staticmethod
    def addCallback(this_addCallback: OnBackPressedDispatcher, owner: androidx.lifecycle.LifecycleOwner, enabled: bool | java.jboolean | java.lang.Boolean, onBackPressed: kotlin.jvm.functions.Function1[OnBackPressedCallback, kotlin.Unit], /) -> OnBackPressedCallback: ...

class OnBackPressedDispatcherOwner(androidx.lifecycle.LifecycleOwner):
    def getOnBackPressedDispatcher(self) -> OnBackPressedDispatcher: ...

class PipHintTrackerKt(java.lang.Object):
    @staticmethod
    def trackPipAnimationHintView(this_trackPipAnimationHintView: android.app.Activity, view: android.view.View, completion: kotlin.coroutines.Continuation[kotlin.Unit], /) -> java.lang.Object: ...

class SystemBarStyle(java.lang.Object):
    Companion: typing.ClassVar[SystemBarStyle.Companion] = ...
    @typing.overload
    @staticmethod
    def auto(lightScrim: int | java.jint | java.lang.Integer, darkScrim: int | java.jint | java.lang.Integer, /) -> SystemBarStyle: ...
    @typing.overload
    @staticmethod
    def auto(lightScrim: int | java.jint | java.lang.Integer, darkScrim: int | java.jint | java.lang.Integer, detectDarkMode: kotlin.jvm.functions.Function1[android.content.res.Resources, java.lang.Boolean], /) -> SystemBarStyle: ...
    @staticmethod
    def dark(scrim: int | java.jint | java.lang.Integer, /) -> SystemBarStyle: ...
    @staticmethod
    def light(scrim: int | java.jint | java.lang.Integer, darkScrim: int | java.jint | java.lang.Integer, /) -> SystemBarStyle: ...

    class Companion(java.lang.Object):
        @typing.overload
        def auto(self, lightScrim: int | java.jint | java.lang.Integer, darkScrim: int | java.jint | java.lang.Integer, /) -> SystemBarStyle: ...
        @typing.overload
        def auto(self, lightScrim: int | java.jint | java.lang.Integer, darkScrim: int | java.jint | java.lang.Integer, detectDarkMode: kotlin.jvm.functions.Function1[android.content.res.Resources, java.lang.Boolean], /) -> SystemBarStyle: ...
        def dark(self, scrim: int | java.jint | java.lang.Integer, /) -> SystemBarStyle: ...
        def light(self, scrim: int | java.jint | java.lang.Integer, darkScrim: int | java.jint | java.lang.Integer, /) -> SystemBarStyle: ...

class ViewTreeFullyDrawnReporterOwner(java.lang.Object):
    @staticmethod
    def get(this_findViewTreeFullyDrawnReporterOwner: android.view.View, /) -> FullyDrawnReporterOwner: ...
    @staticmethod
    def set(this_setViewTreeFullyDrawnReporterOwner: android.view.View, fullyDrawnReporterOwner: FullyDrawnReporterOwner, /) -> None: ...

class ViewTreeOnBackPressedDispatcherOwner(java.lang.Object):
    @staticmethod
    def get(this_findViewTreeOnBackPressedDispatcherOwner: android.view.View, /) -> OnBackPressedDispatcherOwner: ...
    @staticmethod
    def set(this_setViewTreeOnBackPressedDispatcherOwner: android.view.View, onBackPressedDispatcherOwner: OnBackPressedDispatcherOwner, /) -> None: ...
