import typing

import android.content
import android.database
import android.net
import java
import java.chaquopy
import java.io
import java.lang
import java.util.concurrent

_AsyncTaskLoader__D = typing.TypeVar('_AsyncTaskLoader__D')  # <D>
class AsyncTaskLoader(Loader[_AsyncTaskLoader__D], typing.Generic[_AsyncTaskLoader__D]):
    def __init__(self, context: android.content.Context, /) -> None: ...
    def cancelLoadInBackground(self) -> None: ...
    def dump(self, prefix: str | java.lang.String, fd: java.io.FileDescriptor, writer: java.io.PrintWriter, args: java.chaquopy.JavaArray[java.lang.String], /) -> None: ...
    def getExecutor(self) -> java.util.concurrent.Executor: ...
    def isLoadInBackgroundCanceled(self) -> bool: ...
    def loadInBackground(self) -> _AsyncTaskLoader__D: ...
    def onCancelLoad(self) -> bool: ...
    def onCanceled(self, data: _AsyncTaskLoader__D, /) -> None: ...
    def onForceLoad(self) -> None: ...
    def onLoadInBackground(self) -> _AsyncTaskLoader__D: ...
    def setUpdateThrottle(self, delayMS: int | java.jlong | java.lang.Long, /) -> None: ...

class CursorLoader(AsyncTaskLoader[android.database.Cursor]):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, uri: android.net.Uri, projection: java.chaquopy.JavaArray[java.lang.String], selection: str | java.lang.String, selectionArgs: java.chaquopy.JavaArray[java.lang.String], sortOrder: str | java.lang.String, /) -> None: ...
    def cancelLoadInBackground(self) -> None: ...
    def deliverResult(self, cursor: android.database.Cursor, /) -> None: ...
    def dump(self, prefix: str | java.lang.String, fd: java.io.FileDescriptor, writer: java.io.PrintWriter, args: java.chaquopy.JavaArray[java.lang.String], /) -> None: ...
    def getProjection(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    def getSelection(self) -> str: ...
    def getSelectionArgs(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    def getSortOrder(self) -> str: ...
    def getUri(self) -> android.net.Uri: ...
    def loadInBackground(self) -> android.database.Cursor: ...
    def onCanceled(self, cursor: android.database.Cursor, /) -> None: ...
    def onReset(self) -> None: ...
    def onStartLoading(self) -> None: ...
    def onStopLoading(self) -> None: ...
    def setProjection(self, projection: java.chaquopy.JavaArray[java.lang.String], /) -> None: ...
    def setSelection(self, selection: str | java.lang.String, /) -> None: ...
    def setSelectionArgs(self, selectionArgs: java.chaquopy.JavaArray[java.lang.String], /) -> None: ...
    def setSortOrder(self, sortOrder: str | java.lang.String, /) -> None: ...
    def setUri(self, uri: android.net.Uri, /) -> None: ...

_Loader__D = typing.TypeVar('_Loader__D')  # <D>

_Loader__OnLoadCanceledListener__D = typing.TypeVar('_Loader__OnLoadCanceledListener__D')  # <D>

_Loader__OnLoadCompleteListener__D = typing.TypeVar('_Loader__OnLoadCompleteListener__D')  # <D>
class Loader(java.lang.Object, typing.Generic[_Loader__D]):
    def __init__(self, context: android.content.Context, /) -> None: ...
    def abandon(self) -> None: ...
    def cancelLoad(self) -> bool: ...
    def commitContentChanged(self) -> None: ...
    def dataToString(self, data: _Loader__D, /) -> str: ...
    def deliverCancellation(self) -> None: ...
    def deliverResult(self, data: _Loader__D, /) -> None: ...
    def dump(self, prefix: str | java.lang.String, fd: java.io.FileDescriptor, writer: java.io.PrintWriter, args: java.chaquopy.JavaArray[java.lang.String], /) -> None: ...
    def forceLoad(self) -> None: ...
    def getContext(self) -> android.content.Context: ...
    def getId(self) -> int: ...
    def isAbandoned(self) -> bool: ...
    def isReset(self) -> bool: ...
    def isStarted(self) -> bool: ...
    def onAbandon(self) -> None: ...
    def onCancelLoad(self) -> bool: ...
    def onContentChanged(self) -> None: ...
    def onForceLoad(self) -> None: ...
    def onReset(self) -> None: ...
    def onStartLoading(self) -> None: ...
    def onStopLoading(self) -> None: ...
    def registerListener(self, id: int | java.jint | java.lang.Integer, listener: Loader.OnLoadCompleteListener[_Loader__D], /) -> None: ...
    def registerOnLoadCanceledListener(self, listener: Loader.OnLoadCanceledListener[_Loader__D], /) -> None: ...
    def reset(self) -> None: ...
    def rollbackContentChanged(self) -> None: ...
    def startLoading(self) -> None: ...
    def stopLoading(self) -> None: ...
    def takeContentChanged(self) -> bool: ...
    def toString(self) -> str: ...
    def unregisterListener(self, listener: Loader.OnLoadCompleteListener[_Loader__D], /) -> None: ...
    def unregisterOnLoadCanceledListener(self, listener: Loader.OnLoadCanceledListener[_Loader__D], /) -> None: ...
    class OnLoadCanceledListener(java.lang.Object, typing.Generic[_Loader__OnLoadCanceledListener__D]):
        def onLoadCanceled(self, arg1: Loader[_Loader__OnLoadCanceledListener__D], /) -> None: ...
    class OnLoadCompleteListener(java.lang.Object, typing.Generic[_Loader__OnLoadCompleteListener__D]):
        def onLoadComplete(self, arg1: Loader[_Loader__OnLoadCompleteListener__D], arg2: _Loader__OnLoadCompleteListener__D, /) -> None: ...

    class ForceLoadContentObserver(android.database.ContentObserver):
        def __init__(self, this_0: Loader, /) -> None: ...
        def deliverSelfNotifications(self) -> bool: ...
        def onChange(self, selfChange: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

_ModernAsyncTask__Result = typing.TypeVar('_ModernAsyncTask__Result')  # <Result>
class ModernAsyncTask(java.lang.Object, typing.Generic[_ModernAsyncTask__Result]):
    def cancel(self, mayInterruptIfRunning: bool | java.jboolean | java.lang.Boolean, /) -> bool: ...
    def doInBackground(self) -> _ModernAsyncTask__Result: ...
    def executeOnExecutor(self, exec_: java.util.concurrent.Executor, /) -> None: ...
    def isCancelled(self) -> bool: ...
    def onCancelled(self, result: _ModernAsyncTask__Result, /) -> None: ...
    def onPostExecute(self, result: _ModernAsyncTask__Result, /) -> None: ...

    class Status(java.lang.Enum[ModernAsyncTask.Status]):
        PENDING: typing.ClassVar[ModernAsyncTask.Status] = ...
        RUNNING: typing.ClassVar[ModernAsyncTask.Status] = ...
        FINISHED: typing.ClassVar[ModernAsyncTask.Status] = ...
        @staticmethod
        def valueOf(name: str | java.lang.String, /) -> ModernAsyncTask.Status: ...
        @staticmethod
        def values() -> java.chaquopy.JavaArray[ModernAsyncTask.Status]: ...
