import typing

import android.content
import android.content.res
import android.graphics
import android.graphics.drawable
import androidx.core.graphics.drawable
import com.google.android.material.shape
import java
import java.chaquopy
import java.lang

class RippleDrawableCompat(android.graphics.drawable.Drawable, com.google.android.material.shape.Shapeable, androidx.core.graphics.drawable.TintAwareDrawable):
    def __init__(self, shapeAppearanceModel: com.google.android.material.shape.ShapeAppearanceModel, /) -> None: ...
    def draw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def getConstantState(self) -> android.graphics.drawable.Drawable.ConstantState: ...
    def getOpacity(self) -> int: ...
    def getShapeAppearanceModel(self) -> com.google.android.material.shape.ShapeAppearanceModel: ...
    def isStateful(self) -> bool: ...
    def mutate(self) -> RippleDrawableCompat: ...
    def onBoundsChange(self, bounds: android.graphics.Rect, /) -> None: ...
    def onStateChange(self, stateSet: java.chaquopy.JavaArrayJInt, /) -> bool: ...
    def setAlpha(self, alpha: int | java.jint | java.lang.Integer, /) -> None: ...
    def setColorFilter(self, colorFilter: android.graphics.ColorFilter, /) -> None: ...
    def setShapeAppearanceModel(self, shapeAppearanceModel: com.google.android.material.shape.ShapeAppearanceModel, /) -> None: ...
    def setTint(self, tintColor: int | java.jint | java.lang.Integer, /) -> None: ...
    def setTintList(self, tintList: android.content.res.ColorStateList, /) -> None: ...
    def setTintMode(self, tintMode: android.graphics.PorterDuff.Mode, /) -> None: ...

class RippleUtils(java.lang.Object):
    USE_FRAMEWORK_RIPPLE: typing.ClassVar[bool] = ...
    @staticmethod
    def convertToRippleDrawableColor(rippleColor: android.content.res.ColorStateList, /) -> android.content.res.ColorStateList: ...
    @staticmethod
    def createOvalRippleLollipop(context: android.content.Context, padding: int | java.jint | java.lang.Integer, /) -> android.graphics.drawable.Drawable: ...
    @staticmethod
    def sanitizeRippleDrawableColor(rippleColor: android.content.res.ColorStateList, /) -> android.content.res.ColorStateList: ...
    @staticmethod
    def shouldDrawRippleCompat(stateSet: java.chaquopy.JavaArrayJInt, /) -> bool: ...
