import android.content
import android.content.res
import android.graphics
import android.util
import androidx.appcompat.widget
import com.google.android.material.shape
import java
import java.lang
import typing



class ShapeableImageView(androidx.appcompat.widget.AppCompatImageView, com.google.android.material.shape.Shapeable):
    @typing.overload
    def __init__(self, context: android.content.Context, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, /) -> None: ...
    @typing.overload
    def __init__(self, context: android.content.Context, attrs: android.util.AttributeSet, defStyle: int | java.jint | java.lang.Integer, /) -> None: ...
    def getContentPaddingBottom(self) -> int: ...
    def getContentPaddingEnd(self) -> int: ...
    def getContentPaddingLeft(self) -> int: ...
    def getContentPaddingRight(self) -> int: ...
    def getContentPaddingStart(self) -> int: ...
    def getContentPaddingTop(self) -> int: ...
    def getPaddingBottom(self) -> int: ...
    def getPaddingEnd(self) -> int: ...
    def getPaddingLeft(self) -> int: ...
    def getPaddingRight(self) -> int: ...
    def getPaddingStart(self) -> int: ...
    def getPaddingTop(self) -> int: ...
    def getShapeAppearanceModel(self) -> com.google.android.material.shape.ShapeAppearanceModel: ...
    def getStrokeColor(self) -> android.content.res.ColorStateList: ...
    def getStrokeWidth(self) -> float: ...
    def onDraw(self, canvas: android.graphics.Canvas, /) -> None: ...
    def onMeasure(self, widthMeasureSpec: int | java.jint | java.lang.Integer, heightMeasureSpec: int | java.jint | java.lang.Integer, /) -> None: ...
    def onSizeChanged(self, width: int | java.jint | java.lang.Integer, height: int | java.jint | java.lang.Integer, oldWidth: int | java.jint | java.lang.Integer, oldHeight: int | java.jint | java.lang.Integer, /) -> None: ...
    def setContentPadding(self, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setContentPaddingRelative(self, start: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, end: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPadding(self, left: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, right: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setPaddingRelative(self, start: int | java.jint | java.lang.Integer, top: int | java.jint | java.lang.Integer, end: int | java.jint | java.lang.Integer, bottom: int | java.jint | java.lang.Integer, /) -> None: ...
    def setShapeAppearanceModel(self, shapeAppearanceModel: com.google.android.material.shape.ShapeAppearanceModel, /) -> None: ...
    def setStrokeColor(self, strokeColor: android.content.res.ColorStateList, /) -> None: ...
    def setStrokeColorResource(self, strokeColorResourceId: int | java.jint | java.lang.Integer, /) -> None: ...
    def setStrokeWidth(self, strokeWidth: float | java.jfloat | java.lang.Float, /) -> None: ...
    def setStrokeWidthResource(self, strokeWidthResourceId: int | java.jint | java.lang.Integer, /) -> None: ...
