import typing

import java.chaquopy
import java.lang
import java.lang.annotation

class Async(java.lang.Object):

    class Execute(java.lang.annotation.Annotation): ...

    class Schedule(java.lang.annotation.Annotation): ...

class Contract(java.lang.annotation.Annotation):
    def mutates(self) -> str: ...
    def pure(self) -> bool: ...
    def value(self) -> str: ...

class Nls(java.lang.annotation.Annotation):
    def capitalization(self) -> Nls.Capitalization: ...

    class Capitalization(java.lang.Enum[Nls.Capitalization]):
        NotSpecified: typing.ClassVar[Nls.Capitalization] = ...
        Title: typing.ClassVar[Nls.Capitalization] = ...
        Sentence: typing.ClassVar[Nls.Capitalization] = ...
        @staticmethod
        def valueOf(name: str | java.lang.String, /) -> Nls.Capitalization: ...
        @staticmethod
        def values() -> java.chaquopy.JavaArray[Nls.Capitalization]: ...

class NonNls(java.lang.annotation.Annotation): ...

class NotNull(java.lang.annotation.Annotation):
    def exception(self) -> typing.Type[java.lang.Exception]: ...
    def value(self) -> str: ...

class Nullable(java.lang.annotation.Annotation):
    def value(self) -> str: ...

class PropertyKey(java.lang.annotation.Annotation):
    def resourceBundle(self) -> str: ...

class TestOnly(java.lang.annotation.Annotation): ...
