import typing

import android.app
import android.content
import android.content.pm
import android.database
import android.net
import android.os
import android.webkit
import androidx
import java
import java.chaquopy
import java.io
import java.lang
import java.lang.annotation
import java.lang.reflect
import java.util
import java.util.concurrent
import org.chromium.support_lib_boundary

class CookieManagerCompat(java.lang.Object):
    @staticmethod
    def getCookieInfo(cookieManager: android.webkit.CookieManager, url: str | java.lang.String, /) -> java.util.List[java.lang.String]: ...

class DropDataContentProvider(android.content.ContentProvider):
    def __init__(self) -> None: ...
    def call(self, method: str | java.lang.String, arg: str | java.lang.String, extras: android.os.Bundle, /) -> android.os.Bundle: ...
    def delete(self, uri: android.net.Uri, selection: str | java.lang.String, selectionArgs: java.chaquopy.JavaArray[java.lang.String], /) -> int: ...
    def getType(self, uri: android.net.Uri, /) -> str: ...
    def insert(self, uri: android.net.Uri, contentValues: android.content.ContentValues, /) -> android.net.Uri: ...
    def onCreate(self) -> bool: ...
    def openFile(self, uri: android.net.Uri, mode: str | java.lang.String, /) -> android.os.ParcelFileDescriptor: ...
    def query(self, uri: android.net.Uri, projection: java.chaquopy.JavaArray[java.lang.String], selection: str | java.lang.String, selectionArgs: java.chaquopy.JavaArray[java.lang.String], sortOrder: str | java.lang.String, /) -> android.database.Cursor: ...
    def update(self, uri: android.net.Uri, contentValues: android.content.ContentValues, s: str | java.lang.String, strings: java.chaquopy.JavaArray[java.lang.String], /) -> int: ...

class JavaScriptReplyProxy(java.lang.Object):
    def __init__(self) -> None: ...
    def postMessage(self, arg1: str | java.lang.String, /) -> None: ...

class ProcessGlobalConfig(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def apply(config: ProcessGlobalConfig, /) -> None: ...
    def setDataDirectorySuffix(self, context: android.content.Context, suffix: str | java.lang.String, /) -> ProcessGlobalConfig: ...

class ProxyConfig(java.lang.Object):
    MATCH_HTTP: typing.ClassVar[str] = ...
    MATCH_HTTPS: typing.ClassVar[str] = ...
    MATCH_ALL_SCHEMES: typing.ClassVar[str] = ...
    def __init__(self, proxyRules: java.util.List[ProxyConfig.ProxyRule], bypassRules: java.util.List[java.lang.String], reverseBypass: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def getBypassRules(self) -> java.util.List[java.lang.String]: ...
    def getProxyRules(self) -> java.util.List[ProxyConfig.ProxyRule]: ...
    def isReverseBypassEnabled(self) -> bool: ...

    class Builder(java.lang.Object):
        @typing.overload
        def __init__(self) -> None: ...
        @typing.overload
        def __init__(self, proxyConfig: ProxyConfig, /) -> None: ...
        def addBypassRule(self, bypassRule: str | java.lang.String, /) -> ProxyConfig.Builder: ...
        @typing.overload
        def addDirect(self) -> ProxyConfig.Builder: ...
        @typing.overload
        def addDirect(self, schemeFilter: str | java.lang.String, /) -> ProxyConfig.Builder: ...
        @typing.overload
        def addProxyRule(self, proxyUrl: str | java.lang.String, /) -> ProxyConfig.Builder: ...
        @typing.overload
        def addProxyRule(self, proxyUrl: str | java.lang.String, schemeFilter: str | java.lang.String, /) -> ProxyConfig.Builder: ...
        def build(self) -> ProxyConfig: ...
        def bypassSimpleHostnames(self) -> ProxyConfig.Builder: ...
        def removeImplicitRules(self) -> ProxyConfig.Builder: ...
        def setReverseBypassEnabled(self, reverseBypass: bool | java.jboolean | java.lang.Boolean, /) -> ProxyConfig.Builder: ...

    class ProxyRule(java.lang.Object):
        @typing.overload
        def __init__(self, url: str | java.lang.String, /) -> None: ...
        @typing.overload
        def __init__(self, schemeFilter: str | java.lang.String, url: str | java.lang.String, /) -> None: ...
        def getSchemeFilter(self) -> str: ...
        def getUrl(self) -> str: ...

    class ProxyScheme(java.lang.annotation.Annotation): ...

class ProxyController(java.lang.Object):
    def __init__(self) -> None: ...
    def clearProxyOverride(self, arg1: java.util.concurrent.Executor, arg2: java.lang.Runnable, /) -> None: ...
    @staticmethod
    def getInstance() -> ProxyController: ...
    def setProxyOverride(self, arg1: ProxyConfig, arg2: java.util.concurrent.Executor, arg3: java.lang.Runnable, /) -> None: ...

class SafeBrowsingResponseCompat(java.lang.Object):
    def __init__(self) -> None: ...
    def backToSafety(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def proceed(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def showInterstitial(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...

class ScriptHandler(java.lang.Object):
    def __init__(self) -> None: ...
    def remove(self) -> None: ...

class ServiceWorkerClientCompat(java.lang.Object):
    def __init__(self) -> None: ...
    def shouldInterceptRequest(self, arg1: android.webkit.WebResourceRequest, /) -> android.webkit.WebResourceResponse: ...

class ServiceWorkerControllerCompat(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def getInstance() -> ServiceWorkerControllerCompat: ...
    def getServiceWorkerWebSettings(self) -> ServiceWorkerWebSettingsCompat: ...
    def setServiceWorkerClient(self, arg1: ServiceWorkerClientCompat, /) -> None: ...

class ServiceWorkerWebSettingsCompat(java.lang.Object):
    def __init__(self) -> None: ...
    def getAllowContentAccess(self) -> bool: ...
    def getAllowFileAccess(self) -> bool: ...
    def getBlockNetworkLoads(self) -> bool: ...
    def getCacheMode(self) -> int: ...
    def getRequestedWithHeaderOriginAllowList(self) -> java.util.Set[java.lang.String]: ...
    def setAllowContentAccess(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setAllowFileAccess(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setBlockNetworkLoads(self, arg1: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    def setCacheMode(self, arg1: int | java.jint | java.lang.Integer, /) -> None: ...
    def setRequestedWithHeaderOriginAllowList(self, arg1: java.util.Set[java.lang.String], /) -> None: ...

    class CacheMode(java.lang.annotation.Annotation): ...

class TracingConfig(java.lang.Object):
    CATEGORIES_NONE: typing.ClassVar[int] = ...
    CATEGORIES_ALL: typing.ClassVar[int] = ...
    CATEGORIES_ANDROID_WEBVIEW: typing.ClassVar[int] = ...
    CATEGORIES_WEB_DEVELOPER: typing.ClassVar[int] = ...
    CATEGORIES_INPUT_LATENCY: typing.ClassVar[int] = ...
    CATEGORIES_RENDERING: typing.ClassVar[int] = ...
    CATEGORIES_JAVASCRIPT_AND_RENDERING: typing.ClassVar[int] = ...
    CATEGORIES_FRAME_VIEWER: typing.ClassVar[int] = ...
    RECORD_UNTIL_FULL: typing.ClassVar[int] = ...
    RECORD_CONTINUOUSLY: typing.ClassVar[int] = ...
    def __init__(self, predefinedCategories: int | java.jint | java.lang.Integer, customIncludedCategories: java.util.List[java.lang.String], tracingMode: int | java.jint | java.lang.Integer, /) -> None: ...
    def getCustomIncludedCategories(self) -> java.util.List[java.lang.String]: ...
    def getPredefinedCategories(self) -> int: ...
    def getTracingMode(self) -> int: ...

    class Builder(java.lang.Object):
        def __init__(self) -> None: ...
        @typing.overload
        def addCategories(self, categories: java.util.Collection[java.lang.String], /) -> TracingConfig.Builder: ...
        @typing.overload
        def addCategories(self, *predefinedCategories: java.jint) -> TracingConfig.Builder: ...
        @typing.overload
        def addCategories(self, *categories: java.lang.String) -> TracingConfig.Builder: ...
        def build(self) -> TracingConfig: ...
        def setTracingMode(self, tracingMode: int | java.jint | java.lang.Integer, /) -> TracingConfig.Builder: ...

    class TracingMode(java.lang.annotation.Annotation): ...

    class PredefinedCategories(java.lang.annotation.Annotation): ...

class TracingController(java.lang.Object):
    def __init__(self) -> None: ...
    @staticmethod
    def getInstance() -> TracingController: ...
    def isTracing(self) -> bool: ...
    def start(self, arg1: TracingConfig, /) -> None: ...
    def stop(self, arg1: java.io.OutputStream, arg2: java.util.concurrent.Executor, /) -> bool: ...

class WebMessageCompat(java.lang.Object):
    TYPE_STRING: typing.ClassVar[int] = ...
    TYPE_ARRAY_BUFFER: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self, data: str | java.lang.String, /) -> None: ...
    @typing.overload
    def __init__(self, arrayBuffer: java.chaquopy.JavaArrayJByte, /) -> None: ...
    @typing.overload
    def __init__(self, data: str | java.lang.String, ports: java.chaquopy.JavaArray[WebMessagePortCompat], /) -> None: ...
    @typing.overload
    def __init__(self, arrayBuffer: java.chaquopy.JavaArrayJByte, ports: java.chaquopy.JavaArray[WebMessagePortCompat], /) -> None: ...
    def getArrayBuffer(self) -> java.chaquopy.JavaArrayJByte: ...
    def getData(self) -> str: ...
    def getPorts(self) -> java.chaquopy.JavaArray[WebMessagePortCompat]: ...
    def getType(self) -> int: ...

    class Type(java.lang.annotation.Annotation): ...

class WebMessagePortCompat(java.lang.Object):
    def __init__(self) -> None: ...
    def close(self) -> None: ...
    def getFrameworkPort(self) -> android.webkit.WebMessagePort: ...
    def getInvocationHandler(self) -> java.lang.reflect.InvocationHandler: ...
    def postMessage(self, arg1: WebMessageCompat, /) -> None: ...
    @typing.overload
    def setWebMessageCallback(self, arg1: WebMessagePortCompat.WebMessageCallbackCompat, /) -> None: ...
    @typing.overload
    def setWebMessageCallback(self, arg1: android.os.Handler, arg2: WebMessagePortCompat.WebMessageCallbackCompat, /) -> None: ...

    class WebMessageCallbackCompat(java.lang.Object):
        def __init__(self) -> None: ...
        def onMessage(self, port: WebMessagePortCompat, message: WebMessageCompat, /) -> None: ...

class WebResourceErrorCompat(java.lang.Object):
    def __init__(self) -> None: ...
    def getDescription(self) -> java.lang.CharSequence: ...
    def getErrorCode(self) -> int: ...

    class NetErrorCode(java.lang.annotation.Annotation): ...

class WebResourceRequestCompat(java.lang.Object):
    @staticmethod
    def isRedirect(request: android.webkit.WebResourceRequest, /) -> bool: ...

class WebSettingsCompat(java.lang.Object):
    FORCE_DARK_OFF: typing.ClassVar[int] = ...
    FORCE_DARK_AUTO: typing.ClassVar[int] = ...
    FORCE_DARK_ON: typing.ClassVar[int] = ...
    DARK_STRATEGY_USER_AGENT_DARKENING_ONLY: typing.ClassVar[int] = ...
    DARK_STRATEGY_WEB_THEME_DARKENING_ONLY: typing.ClassVar[int] = ...
    DARK_STRATEGY_PREFER_WEB_THEME_OVER_USER_AGENT_DARKENING: typing.ClassVar[int] = ...
    @staticmethod
    def getDisabledActionModeMenuItems(settings: android.webkit.WebSettings, /) -> int: ...
    @staticmethod
    def getEnterpriseAuthenticationAppLinkPolicyEnabled(settings: android.webkit.WebSettings, /) -> bool: ...
    @staticmethod
    def getForceDark(settings: android.webkit.WebSettings, /) -> int: ...
    @staticmethod
    def getForceDarkStrategy(settings: android.webkit.WebSettings, /) -> int: ...
    @staticmethod
    def getOffscreenPreRaster(settings: android.webkit.WebSettings, /) -> bool: ...
    @staticmethod
    def getRequestedWithHeaderOriginAllowList(settings: android.webkit.WebSettings, /) -> java.util.Set[java.lang.String]: ...
    @staticmethod
    def getSafeBrowsingEnabled(settings: android.webkit.WebSettings, /) -> bool: ...
    @staticmethod
    def isAlgorithmicDarkeningAllowed(settings: android.webkit.WebSettings, /) -> bool: ...
    @staticmethod
    def setAlgorithmicDarkeningAllowed(settings: android.webkit.WebSettings, allow: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def setDisabledActionModeMenuItems(settings: android.webkit.WebSettings, menuItems: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setEnterpriseAuthenticationAppLinkPolicyEnabled(settings: android.webkit.WebSettings, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def setForceDark(settings: android.webkit.WebSettings, forceDarkMode: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setForceDarkStrategy(settings: android.webkit.WebSettings, forceDarkBehavior: int | java.jint | java.lang.Integer, /) -> None: ...
    @staticmethod
    def setOffscreenPreRaster(settings: android.webkit.WebSettings, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def setRequestedWithHeaderOriginAllowList(settings: android.webkit.WebSettings, allowList: java.util.Set[java.lang.String], /) -> None: ...
    @staticmethod
    def setSafeBrowsingEnabled(settings: android.webkit.WebSettings, enabled: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def setWillSuppressErrorPage(settings: android.webkit.WebSettings, suppressed: bool | java.jboolean | java.lang.Boolean, /) -> None: ...
    @staticmethod
    def willSuppressErrorPage(settings: android.webkit.WebSettings, /) -> bool: ...

    class ForceDarkStrategy(java.lang.annotation.Annotation): ...

    class ForceDark(java.lang.annotation.Annotation): ...

    class MenuItemFlags(java.lang.annotation.Annotation): ...

class WebViewAssetLoader(java.lang.Object):
    DEFAULT_DOMAIN: typing.ClassVar[str] = ...
    def shouldInterceptRequest(self, url: android.net.Uri, /) -> android.webkit.WebResourceResponse: ...

    class PathHandler(java.lang.Object):
        def handle(self, arg1: str | java.lang.String, /) -> android.webkit.WebResourceResponse: ...

    class Builder(java.lang.Object):
        def __init__(self) -> None: ...
        def addPathHandler(self, path: str | java.lang.String, handler: WebViewAssetLoader.PathHandler, /) -> WebViewAssetLoader.Builder: ...
        def build(self) -> WebViewAssetLoader: ...
        def setDomain(self, domain: str | java.lang.String, /) -> WebViewAssetLoader.Builder: ...
        def setHttpAllowed(self, httpAllowed: bool | java.jboolean | java.lang.Boolean, /) -> WebViewAssetLoader.Builder: ...

    class InternalStoragePathHandler(androidx.webkit.WebViewAssetLoader.PathHandler):
        def __init__(self, context: android.content.Context, directory: java.io.File, /) -> None: ...
        def handle(self, path: str | java.lang.String, /) -> android.webkit.WebResourceResponse: ...

    class ResourcesPathHandler(androidx.webkit.WebViewAssetLoader.PathHandler):
        def __init__(self, context: android.content.Context, /) -> None: ...
        def handle(self, path: str | java.lang.String, /) -> android.webkit.WebResourceResponse: ...

    class AssetsPathHandler(androidx.webkit.WebViewAssetLoader.PathHandler):
        def __init__(self, context: android.content.Context, /) -> None: ...
        def handle(self, path: str | java.lang.String, /) -> android.webkit.WebResourceResponse: ...

class WebViewClientCompat(android.webkit.WebViewClient, org.chromium.support_lib_boundary.WebViewClientBoundaryInterface):
    def __init__(self) -> None: ...
    def getSupportedFeatures(self) -> java.chaquopy.JavaArray[java.lang.String]: ...
    def onPageCommitVisible(self, view: android.webkit.WebView, url: str | java.lang.String, /) -> None: ...
    @typing.overload
    def onReceivedError(self, view: android.webkit.WebView, request: android.webkit.WebResourceRequest, error: android.webkit.WebResourceError, /) -> None: ...
    @typing.overload
    def onReceivedError(self, view: android.webkit.WebView, request: android.webkit.WebResourceRequest, error: WebResourceErrorCompat, /) -> None: ...
    @typing.overload
    def onReceivedError(self, view: android.webkit.WebView, request: android.webkit.WebResourceRequest, handler: java.lang.reflect.InvocationHandler, /) -> None: ...
    def onReceivedHttpError(self, view: android.webkit.WebView, request: android.webkit.WebResourceRequest, errorResponse: android.webkit.WebResourceResponse, /) -> None: ...
    @typing.overload
    def onSafeBrowsingHit(self, view: android.webkit.WebView, request: android.webkit.WebResourceRequest, threatType: int | java.jint | java.lang.Integer, response: android.webkit.SafeBrowsingResponse, /) -> None: ...
    @typing.overload
    def onSafeBrowsingHit(self, view: android.webkit.WebView, request: android.webkit.WebResourceRequest, threatType: int | java.jint | java.lang.Integer, callback: SafeBrowsingResponseCompat, /) -> None: ...
    @typing.overload
    def onSafeBrowsingHit(self, view: android.webkit.WebView, request: android.webkit.WebResourceRequest, threatType: int | java.jint | java.lang.Integer, handler: java.lang.reflect.InvocationHandler, /) -> None: ...
    def onWebAuthnIntent(self, view: android.webkit.WebView, intent: android.app.PendingIntent, callback: java.lang.reflect.InvocationHandler, /) -> bool: ...
    def shouldOverrideUrlLoading(self, view: android.webkit.WebView, request: android.webkit.WebResourceRequest, /) -> bool: ...

    class SafeBrowsingThreat(java.lang.annotation.Annotation): ...

class WebViewCompat(java.lang.Object):
    @staticmethod
    def addDocumentStartJavaScript(webview: android.webkit.WebView, script: str | java.lang.String, allowedOriginRules: java.util.Set[java.lang.String], /) -> ScriptHandler: ...
    @staticmethod
    def addWebMessageListener(webView: android.webkit.WebView, jsObjectName: str | java.lang.String, allowedOriginRules: java.util.Set[java.lang.String], listener: WebViewCompat.WebMessageListener, /) -> None: ...
    @staticmethod
    def createWebMessageChannel(webview: android.webkit.WebView, /) -> java.chaquopy.JavaArray[WebMessagePortCompat]: ...
    @staticmethod
    def getCurrentLoadedWebViewPackage() -> android.content.pm.PackageInfo: ...
    @staticmethod
    def getCurrentWebViewPackage(context: android.content.Context, /) -> android.content.pm.PackageInfo: ...
    @staticmethod
    def getSafeBrowsingPrivacyPolicyUrl() -> android.net.Uri: ...
    @staticmethod
    def getVariationsHeader() -> str: ...
    @staticmethod
    def getWebChromeClient(webview: android.webkit.WebView, /) -> android.webkit.WebChromeClient: ...
    @staticmethod
    def getWebViewClient(webview: android.webkit.WebView, /) -> android.webkit.WebViewClient: ...
    @staticmethod
    def getWebViewRenderProcess(webview: android.webkit.WebView, /) -> WebViewRenderProcess: ...
    @staticmethod
    def getWebViewRenderProcessClient(webview: android.webkit.WebView, /) -> WebViewRenderProcessClient: ...
    @staticmethod
    def isMultiProcessEnabled() -> bool: ...
    @staticmethod
    def postVisualStateCallback(webview: android.webkit.WebView, requestId: int | java.jlong | java.lang.Long, callback: WebViewCompat.VisualStateCallback, /) -> None: ...
    @staticmethod
    def postWebMessage(webview: android.webkit.WebView, message: WebMessageCompat, targetOrigin: android.net.Uri, /) -> None: ...
    @staticmethod
    def removeWebMessageListener(webview: android.webkit.WebView, jsObjectName: str | java.lang.String, /) -> None: ...
    @staticmethod
    def setSafeBrowsingAllowlist(hosts: java.util.Set[java.lang.String], callback: android.webkit.ValueCallback[java.lang.Boolean], /) -> None: ...
    @staticmethod
    def setSafeBrowsingWhitelist(hosts: java.util.List[java.lang.String], callback: android.webkit.ValueCallback[java.lang.Boolean], /) -> None: ...
    @typing.overload
    @staticmethod
    def setWebViewRenderProcessClient(webview: android.webkit.WebView, webViewRenderProcessClient: WebViewRenderProcessClient, /) -> None: ...
    @typing.overload
    @staticmethod
    def setWebViewRenderProcessClient(webview: android.webkit.WebView, executor: java.util.concurrent.Executor, webViewRenderProcessClient: WebViewRenderProcessClient, /) -> None: ...
    @staticmethod
    def startSafeBrowsing(context: android.content.Context, callback: android.webkit.ValueCallback[java.lang.Boolean], /) -> None: ...

    class VisualStateCallback(java.lang.Object):
        def onComplete(self, arg1: int | java.jlong | java.lang.Long, /) -> None: ...

    class WebMessageListener(java.lang.Object):
        def onPostMessage(self, arg1: android.webkit.WebView, arg2: WebMessageCompat, arg3: android.net.Uri, arg4: bool | java.jboolean | java.lang.Boolean, arg5: JavaScriptReplyProxy, /) -> None: ...

class WebViewFeature(java.lang.Object):
    VISUAL_STATE_CALLBACK: typing.ClassVar[str] = ...
    OFF_SCREEN_PRERASTER: typing.ClassVar[str] = ...
    SAFE_BROWSING_ENABLE: typing.ClassVar[str] = ...
    DISABLED_ACTION_MODE_MENU_ITEMS: typing.ClassVar[str] = ...
    START_SAFE_BROWSING: typing.ClassVar[str] = ...
    SAFE_BROWSING_ALLOWLIST: typing.ClassVar[str] = ...
    SAFE_BROWSING_WHITELIST: typing.ClassVar[str] = ...
    SAFE_BROWSING_PRIVACY_POLICY_URL: typing.ClassVar[str] = ...
    SERVICE_WORKER_BASIC_USAGE: typing.ClassVar[str] = ...
    SERVICE_WORKER_CACHE_MODE: typing.ClassVar[str] = ...
    SERVICE_WORKER_CONTENT_ACCESS: typing.ClassVar[str] = ...
    SERVICE_WORKER_FILE_ACCESS: typing.ClassVar[str] = ...
    SERVICE_WORKER_BLOCK_NETWORK_LOADS: typing.ClassVar[str] = ...
    SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST: typing.ClassVar[str] = ...
    RECEIVE_WEB_RESOURCE_ERROR: typing.ClassVar[str] = ...
    RECEIVE_HTTP_ERROR: typing.ClassVar[str] = ...
    SHOULD_OVERRIDE_WITH_REDIRECTS: typing.ClassVar[str] = ...
    SAFE_BROWSING_HIT: typing.ClassVar[str] = ...
    TRACING_CONTROLLER_BASIC_USAGE: typing.ClassVar[str] = ...
    WEB_RESOURCE_REQUEST_IS_REDIRECT: typing.ClassVar[str] = ...
    WEB_RESOURCE_ERROR_GET_DESCRIPTION: typing.ClassVar[str] = ...
    WEB_RESOURCE_ERROR_GET_CODE: typing.ClassVar[str] = ...
    SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY: typing.ClassVar[str] = ...
    SAFE_BROWSING_RESPONSE_PROCEED: typing.ClassVar[str] = ...
    SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL: typing.ClassVar[str] = ...
    WEB_MESSAGE_PORT_POST_MESSAGE: typing.ClassVar[str] = ...
    WEB_MESSAGE_PORT_CLOSE: typing.ClassVar[str] = ...
    WEB_MESSAGE_GET_MESSAGE_PAYLOAD: typing.ClassVar[str] = ...
    WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK: typing.ClassVar[str] = ...
    CREATE_WEB_MESSAGE_CHANNEL: typing.ClassVar[str] = ...
    POST_WEB_MESSAGE: typing.ClassVar[str] = ...
    WEB_MESSAGE_CALLBACK_ON_MESSAGE: typing.ClassVar[str] = ...
    GET_WEB_VIEW_CLIENT: typing.ClassVar[str] = ...
    GET_WEB_CHROME_CLIENT: typing.ClassVar[str] = ...
    GET_WEB_VIEW_RENDERER: typing.ClassVar[str] = ...
    WEB_VIEW_RENDERER_TERMINATE: typing.ClassVar[str] = ...
    WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE: typing.ClassVar[str] = ...
    PROXY_OVERRIDE: typing.ClassVar[str] = ...
    SUPPRESS_ERROR_PAGE: typing.ClassVar[str] = ...
    MULTI_PROCESS: typing.ClassVar[str] = ...
    FORCE_DARK: typing.ClassVar[str] = ...
    FORCE_DARK_STRATEGY: typing.ClassVar[str] = ...
    ALGORITHMIC_DARKENING: typing.ClassVar[str] = ...
    WEB_MESSAGE_LISTENER: typing.ClassVar[str] = ...
    DOCUMENT_START_SCRIPT: typing.ClassVar[str] = ...
    PROXY_OVERRIDE_REVERSE_BYPASS: typing.ClassVar[str] = ...
    GET_VARIATIONS_HEADER: typing.ClassVar[str] = ...
    ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY: typing.ClassVar[str] = ...
    GET_COOKIE_INFO: typing.ClassVar[str] = ...
    STARTUP_FEATURE_SET_DATA_DIRECTORY_SUFFIX: typing.ClassVar[str] = ...
    REQUESTED_WITH_HEADER_ALLOW_LIST: typing.ClassVar[str] = ...
    @staticmethod
    def isFeatureSupported(feature: str | java.lang.String, /) -> bool: ...
    @staticmethod
    def isStartupFeatureSupported(context: android.content.Context, startupFeature: str | java.lang.String, /) -> bool: ...

    class WebViewStartupFeature(java.lang.annotation.Annotation): ...

    class WebViewSupportFeature(java.lang.annotation.Annotation): ...

class WebViewRenderProcess(java.lang.Object):
    def __init__(self) -> None: ...
    def terminate(self) -> bool: ...

class WebViewRenderProcessClient(java.lang.Object):
    def __init__(self) -> None: ...
    def onRenderProcessResponsive(self, arg1: android.webkit.WebView, arg2: WebViewRenderProcess, /) -> None: ...
    def onRenderProcessUnresponsive(self, arg1: android.webkit.WebView, arg2: WebViewRenderProcess, /) -> None: ...
