name: Publish to PyPI

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish_pypi:
    name: Publish chunk ${{ matrix.chunk }} to PyPI
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chunk: ${{ fromJson(needs.build.outputs.matrix) }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-${{ matrix.chunk }}
          path: dist/

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
          attestations: false
          verbose: true
